  // Auto-generated by tools/build_field_spell_gfx.py. Do not edit.
  CUSTOM_FIELD_SPELL_SEAL_OF_ORICHALCOS = 1,
  CUSTOM_FIELD_SPELL_SANCTUARY_IN_THE_SKY = 2,
  CUSTOM_FIELD_SPELL_A_LEGENDARY_OCEAN = 3,
