#ifndef GUARD_CUSTOM_MUSIC_GENERATED_H
#define GUARD_CUSTOM_MUSIC_GENERATED_H

#define CUSTOM_MUSIC_SONG_COUNT 1
#define CUSTOM_MUSIC_SONG_ID_MIN 679
#define CUSTOM_MUSIC_SONG_ID_MAX 679

#define MUSIC_CUSTOM_HYPERDRIVE 679

void PlayCustomMusic(u8 songIndex);
void PlayCustomMusicById(u16 songId);

#endif // GUARD_CUSTOM_MUSIC_GENERATED_H
