#ifndef GUARD_CUSTOM_VOICES_GENERATED_H
#define GUARD_CUSTOM_VOICES_GENERATED_H

#define CUSTOM_VOICE_SONG_COUNT 33
#define CUSTOM_VOICE_MATCH_COUNT 111
#define CUSTOM_VOICE_OPPONENT_ANY 0xFFFF
#define CUSTOM_VOICE_MPLAY_PLAYER 3
#define CUSTOM_VOICE_SONG_ID_MIN 601
#define CUSTOM_VOICE_MAX_PCM_SAMPLES 55586
#define CUSTOM_VOICE_PCM_BUFFER_BYTES 55604
#define CUSTOM_VOICE_PART_SIZE 18
#define CUSTOM_VOICE_SONG_ID_MAX 633

#define SFX_VOICE_DUKE_1 601
#define SFX_VOICE_DUKE_2 602
#define SFX_VOICE_DUKE_3 603
#define SFX_VOICE_TRISTAN_1 604
#define SFX_VOICE_TRISTAN_2 605
#define SFX_VOICE_TRISTAN_3 606
#define SFX_VOICE_MAI_1 607
#define SFX_VOICE_MAI_2 608
#define SFX_VOICE_MAI_3 609
#define SFX_VOICE_TEA_1 610
#define SFX_VOICE_TEA_2 611
#define SFX_VOICE_TEA_3 612
#define SFX_VOICE_WEEVIL_1 613
#define SFX_VOICE_WEEVIL_2 614
#define SFX_VOICE_WEEVIL_3 615
#define SFX_VOICE_REX_1 616
#define SFX_VOICE_REX_2 617
#define SFX_VOICE_REX_3 618
#define SFX_VOICE_MAKO_1 619
#define SFX_VOICE_MAKO_2 620
#define SFX_VOICE_MAKO_3 621
#define SFX_VOICE_DARK_MARIK_1 622
#define SFX_VOICE_DARK_MARIK_2 623
#define SFX_VOICE_DARK_MARIK_3 624
#define SFX_VOICE_DARK_BAKURA_1 625
#define SFX_VOICE_DARK_BAKURA_2 626
#define SFX_VOICE_DARK_BAKURA_3 627
#define SFX_VOICE_BANDIT_KEITH_1 628
#define SFX_VOICE_BANDIT_KEITH_2 629
#define SFX_VOICE_BANDIT_KEITH_3 630
#define SFX_VOICE_ISHIZU_1 631
#define SFX_VOICE_ISHIZU_2 632
#define SFX_VOICE_ISHIZU_3 633

enum CustomVoiceTriggerType {
  CUSTOM_VOICE_TRIGGER_TURN_START = 0,
  CUSTOM_VOICE_TRIGGER_ATTACK_CARD = 1,
  CUSTOM_VOICE_TRIGGER_OPPONENT_LP_BELOW = 2,
};

struct CustomVoiceClipMeta {
  u16 songId;
  u16 duelistId;
  u16 opponentId;
  u16 cardId;
  u16 lpThreshold;
  u8 triggerType;
  u8 priority;
  u8 replaceVanilla;
  u8 songIndex;
  const u8 *turnText;
};

void PlayCustomVoiceClip(u8 songIndex);

#endif // GUARD_CUSTOM_VOICES_GENERATED_H
