#ifndef GUARD_CONSTANTS_EFFECT_USAGE_H
#define GUARD_CONSTANTS_EFFECT_USAGE_H

enum CardEffectUsage {
  EFFECT_USAGE_NONE,
  EFFECT_USAGE_ONCE,
  EFFECT_USAGE_ONCE_PER_TURN,
  EFFECT_USAGE_MULTIPLE_PER_TURN,
  EFFECT_USAGE_CONTINUOUS,
};

#endif // GUARD_CONSTANTS_EFFECT_USAGE_H
