/* Generated by tools/generate_cg_assets.py. Do not edit. */
#ifndef GUARD_EVENT_CG_GENERATED_H
#define GUARD_EVENT_CG_GENERATED_H

enum EventCg {
  CG_NONE = 0,
  CG_TEST_1,
  CG_TEST_PLACEHOLDER,
  EVENT_CG_COUNT
};

#endif
