#ifndef GUARD_OPENING_SCREENS_H
#define GUARD_OPENING_SCREENS_H

#define OPENING_SCREEN_COUNT 3

#define OPENING_SCREEN_TILE_BYTES 0x9600
#define OPENING_SCREEN_PALETTE_BYTES 512
#define OPENING_SCREEN_MAP_WIDTH 30
#define OPENING_SCREEN_MAP_HEIGHT 20
#define OPENING_SCREEN_BG2CNT 0x1F82
#define OPENING_SCREEN_HOLD_FRAMES 120
#define OPENING_SCREEN_FADE_STEP_FRAMES 3

#endif
