#ifndef EVENT_MACROS_H
#define EVENT_MACROS_H

/* These files are parsed by tools/vanilla_events.py, not compiled directly. */

#define EVENT_SCRIPT_REPLACEMENT(vanilla_addr, name, on_false, on_true)
#define EVENT_SCRIPT(name, on_false, on_true)
#define END_EVENT_SCRIPT()

#define RAW(...)
#define DIALOGUE(text)
#define LANGUAGE_TEXT(language, text)
#define END_LANGUAGE_TEXT()
#define TEXT(text)
#define PLAYER_NAME()
#define NEWLINE()
#define PAGE_BREAK()
#define CHOICE()
#define PORTRAIT(portrait_id, expression, position)
#define HIDE_PORTRAIT()
#define SET_FLAG(flag)
#define CHECK_FLAG(flag)
#define CLEAR_FLAG(flag)
#define RESTORE_LIFE_POINTS()
#define DUEL(opponent)
#define PLAY_MUSIC(music)
#define SET_MAP_MUSIC(music)
#define STOP_MUSIC(music)
#define FADE_MUSIC(music)
#define START_MENU()
#define SAVE()
#define MOVE_OBJECT(object_id, direction, distance, wander)
#define STOP_FOOTSTEPS()
#define SET_OBJECT_POSITION(object_id, x, y, frame)
#define SHOW_OBJECT(object_id, x, y, frame, mode, unused)
#define WALK_OBJECT_X(object_id, target)
#define WALK_OBJECT_Y(object_id, target)
#define SLIDE_OBJECT(object_id, direction, distance)
#define OBJECT_EFFECT(object_mask, mode)
#define SPECIAL(command)
#define CUTSCENE(cutscene_id)
#define DELAY(frames)
#define ADD_CARD(card)
#define REMOVE_CARD(card)
#define CONDITION_CHECK(condition)
#define FADE_SCREEN(speed)
#define SWAP_OBJECT_SPRITE(object_id, sprite_id)
#define WARP(map_id, state, connection, unused)
#define REACTION(reaction, object_mask)
#define COMMAND_7C_ARG(command, argument)
#define FALLTHROUGH()
#define END()

#endif
