#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_39_state_03: map 39 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08ED4ABC, map_39_state_03_08ED4ABC, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MAKO)
  LOAD_SPRITE(2, SPRITE_STRINGS)
  PLAY_MUSIC(MUSIC_407)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(16)
  TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_POSITION_AUTO, "S-say something!")
  TALK(PORTRAIT_STRINGS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_POSITION_AUTO,
      "W-what a strange individual! I've never felt so",
      "uncomfortable..."
  )
  SET_FLAG(EVENT_FLAG_SAW_STRINGS_MAKING_MAKO_UNCOMFORTABLE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AD4, map_39_state_03_08ED4AD4, 0x08ED4AE0, EVENT_NOP)
  TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hey, you've come just at the right time.",
      "Can you do something about this person?",
      "I lack the skill to deal with such weirdness."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AE0, map_39_state_03_08ED4AE0, 0x08ED4AEC, 0x08ED4AF8)
  TEXT("{CARD_1}Leave it to me!\nHe creeps me out, too.{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AEC, map_39_state_03_08ED4AEC, 0x08ED4B04, EVENT_NOP)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'm counting on you!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B04, map_39_state_03_08ED4B04, 0x08ED4B10, 0x08F0404C)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 12, 0)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_Y(0, 56)
  WALK_OBJECT_X(0, 56)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(13, 64)
  WALK_OBJECT_X(13, 64)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 64)
  WALK_OBJECT_X(14, 48)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DUEL(DUELIST_STRINGS_070)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B10, map_39_state_03_08ED4B10, 0x08ED4B1C, EVENT_NOP)
  SET_MAP_MUSIC(248)
  PLAY_MUSIC(MUSIC_248)
  TALK(PORTRAIT_STRINGS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...Lost...")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 88)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 128)
  MOVE_OBJECT(1, DIRECTION_LEFT, 4, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_POSITION_AUTO,
      "Yes! Thank you!",
      "But what brings you here?"
  )
  PLAY_MUSIC(MUSIC_332)
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B1C, map_39_state_03_08ED4B1C, 0x08ED4B28, 0x08ED4B34)
  PLAY_MUSIC(MUSIC_702)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I see. What a horrible situation!",
      "This is why I've been sensing trouble among the",
      "waves.",
      "My instincts tell me something more sinister is",
      "in the works."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0)
  DELAY(16)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Anyways, I'm going to the Town of Domino.")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 72)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_Y(1, 68)
  WALK_OBJECT_X(1, 128)
  SET_FLAG(EVENT_FLAG_DEFEATED_STRINGS)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B28, map_39_state_03_08ED4B28, EVENT_NOP, EVENT_NOP)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Let's go find another ally!")
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B34, map_39_state_03_08ED4B34, EVENT_NOP, EVENT_NOP)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Okay! Let's also get back to the Town of Domino!")
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AF8, map_39_state_03_08ED4AF8, 0x08ED4B04, EVENT_NOP)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Please reconsider! You're the only one I trust.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AC8, map_39_state_03_08ED4AC8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_STRINGS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...")
  FALLTHROUGH()
END_EVENT_SCRIPT()
