#include "event_macros.h"
#include "overworld.h"

/* map_23_state_08: map 23 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E952C4, map_23_state_08_08E952C4, 0x08E952D0, 0x08E952DC)
  PLAY_MUSIC(0)
  PORTRAIT(1, 6, 8)
  LANGUAGE_TEXT(0, "That image I just saw...\n\n")
  LANGUAGE_TEXT(1, "Cette image, l\xe0\nmaintenant...\n\n")
  LANGUAGE_TEXT(2, "Dieses Bild gerade...\n\n")
  LANGUAGE_TEXT(3, "Quell'immagine appena...\n\n")
  LANGUAGE_TEXT(4, "Esa imagen...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8192)
  DELAY(8)
  PORTRAIT(1, 6, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, you saw it too,\ndidn't you?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu l'as vue,\ntoi aussi ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du hast es doch\nauch gesehen, oder?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, l'hai\nvista anche tu, vero?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, la has visto,\nt\xfa tambi\xe9n, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952D0, map_23_state_08_08E952D0, 0x08E952E8, 0x08F04040)
  PORTRAIT(1, 3, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being will\ndestroy the world...\n\nWhat Ishizu said really was\ntrue...\n\n")
  LANGUAGE_TEXT(1, "Le monde est en train\nd'\xeatre d\xe9truit par\n\nReshef, l'Etre des\nt\xe9n\xe8bres...\n\nLa proph\xe9tie d'Ishizu\n\xe9tait donc vraie...\n\n")
  LANGUAGE_TEXT(2, "Die Welt wird von Reschef\ndem Dunklen zerst\xf6rt...\n\nIshizus Worte waren wahr...\n\n")
  LANGUAGE_TEXT(3, "Il mondo distrutto da\nReshef il Tenebroso...\n\nAveva proprio ragione\nIshizu...\n\n")
  LANGUAGE_TEXT(4, "El mundo destruido por\nReshef, el Ser Oscuro...\n\nLo que Ishizu dijo\nera verdad...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952E8, map_23_state_08_08E952E8, 0x08F04250, 0x08F04040)
  LANGUAGE_TEXT(0, "And... My other self...\n\nBut... Why...\n\n")
  LANGUAGE_TEXT(1, "Et...\nL'autre moi...\n\nMais...\nPourquoi...\n\n")
  LANGUAGE_TEXT(2, "Und...\nMein anderes Ich...\n\nAber...\nWarum...\n\n")
  LANGUAGE_TEXT(3, "E...\nL'altro me stesso...\n\nMa...\nPerch\xe9...\n\n")
  LANGUAGE_TEXT(4, "Y...\nMi otro yo...\n\nPero...\n\xbfPor qu\xe9?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "We have to hurry!\n\nIf we don't, there's going\nto be a world of trouble!\n\nLet's go back and see Ishizu\nright away!\n\n")
  LANGUAGE_TEXT(1, "De toute fa\xe7on, il\nfaut se d\xe9p\xeacher.\n\nSinon, je crois qu'on\nva avoir des ennuis.\n\nRetournons vite\nvoir Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Egal, wir m\xfcssen uns\nbeeilen, sonst gibt es\n\nwohl \xc4rger. Los, gehen wir\nsofort zur\xfcck zu Ishizu.\n\n")
  LANGUAGE_TEXT(3, "Be', comunque,\ndobbiamo sbrigarci.\n\nAltrimenti saranno\nguai, credo.\n\nTorniamo subito\nda Ishizu.\n\n")
  LANGUAGE_TEXT(4, "De cualquier modo,\ntenemos que correr.\n\nSi no, va a haber\nproblemas, creo.\n\nVolvamos a ver a\nIshizu ahora mismo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F04250, map_23_state_08_08F04250, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952DC, map_23_state_08_08E952DC, 0x08E952E8, 0x08F04040)
  PORTRAIT(1, 3, 8)
  LANGUAGE_TEXT(0, "I know that it's hard to\nbelieve.\n\nReshef the Dark Being\ndestroying the world...\n\nI don't want to believe it\neither.\n\n")
  LANGUAGE_TEXT(1, "Je sais, c'est\ndifficile \xe0 croire.\n\nMais Reshef, l'Etre des\nt\xe9n\xe8bres est en train\n\nde d\xe9truire le monde...\n\nJe pr\xe9f\xe8re aussi ne pas y\ncroire.\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf, es ist schwer\nzu verstehen.\n\nDie Welt wird von Reschef\ndem Dunklen zerst\xf6rt...\n\nIch will es auch nicht\nglauben.\n\n")
  LANGUAGE_TEXT(3, "So che \xe8 difficile\nda credere.\n\nIl mondo distrutto da\nReshef il Tenebroso...\n\nNeanch'io voglio crederci.\n\n")
  LANGUAGE_TEXT(4, "S\xe9 que es dif\xedcil\nde creer.\n\nEl mundo destruido por\nReshef, el Ser Oscuro...\n\nTampoco quiero\ncreerlo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952F4, map_23_state_08_08E952F4, 0x08F04040, 0x08F04040)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "We have secretly guarded\nover the Millennium Items.\n\nMillennium Items are\nbelieved to attract each\n\nother.\n\nThe Millennium Necklace will\nlead you to the next one.\n\nAlong with the Millennium\nItems...\n\nYou will face the Millennium\nGuardians.\n\nYou must overcome the\nchallenges we present.\n\n")
  LANGUAGE_TEXT(1, "Nous avons gard\xe9\nen secret les\n\nObjets du mill\xe9nium.\n\nOn dit que les Objets du\nmill\xe9nium s'attirent\n\nles uns les autres.\nLe Collier du mill\xe9nium\n\nva te conduire\naux autres objets.\n\nEt avec les\nObjets du mill\xe9nium...\n\nTu vas affronter les\nGardiens du Mill\xe9nium.\n\nTu... tu dois relever les\nd\xe9fis que nous te lan\xe7ons.\n\n")
  LANGUAGE_TEXT(2, "Wir haben die Millenniums-\ngegenst\xe4nde insgeheim\n\ngeh\xfctet.\n\nMillenniumsgegenst\xe4nde\nziehen sich angeblich\n\ngegenseitig an. Die\nMillenniumskette f\xfchrt\n\ndich zum n\xe4chsten\nGegenstand.\n\nUnd zusammen mit den\nMillenniumsgegenst\xe4nden...\n\nWirst du den Millenniums-\nw\xe4chtern gegen\xfcberstehen.\n\nDu... Du solltest unsere He-\nrausforderungen bew\xe4ltigen.\n\n")
  LANGUAGE_TEXT(3, "Abbiamo fatto la guardia in\nsegreto agli Oggetti\n\nMillenari.\n\nSi dice che gli Oggetti\nMillenari si attraggano a\n\nvicenda. La Collana\nMillenaria ti condurr\xe0\n\nal prossimo oggetto.\n\nE insieme agli Oggetti\nMillenari... Affronterai i\n\nGuardiani Millenari.\nTu... dovresti superare\n\nle sfide che noi lanciamo.\n\n")
  LANGUAGE_TEXT(4, "Hemos hecho guardia secreta\na los Objetos del Milenio.\n\nSe dice que los Objetos del\nMilenio se atraen entre s\xed.\n\nEl Collar del Milenio\nte llevar\xe1 al siguiente.\n\nY, junto con los\nObjetos del Milenio...\n\nTe enfrentar\xe1s a los\nGuardianes del Milenio.\n\nT\xfa... deber\xedas superar\nlos retos que ponemos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95300, map_23_state_08_08E95300, 0x08F04040, 0x08F04040)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "You are only allowed to duel\nme once.\n\nDid you not have to leave\nimmediately?\n\n")
  LANGUAGE_TEXT(1, "Je te donne une chance de\nm'affronter en duel,\n\npas plus. Tu ne devais pas\npartir imm\xe9diatement ?\n\n")
  LANGUAGE_TEXT(2, "Du hast nur eine Chance,\num dich mit mir zu\n\nduellieren. Das ist alles.\n\nMusst du nicht sofort\ngehen?\n\n")
  LANGUAGE_TEXT(3, "Hai una sola possibilit\xe0\ndi duellare con me,\n\nuna e basta. Non dovevi\npartire subito?\n\n")
  LANGUAGE_TEXT(4, "Tienes una oportunidad\nde retarme; nada m\xe1s.\n\n\xbfNo ten\xedas que marchar\nde inmediato?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9530C, map_23_state_08_08E9530C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
