#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_01: map 12 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E6EF64, map_12_state_01_08E6EF64, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "This is Kaiba Corporation.\n"
    "This is not a place for\n\n"
    "civilians.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF70, map_12_state_01_08E6EF70, 0x08E6EF7C, 0x08E6EF94)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_ROLAND)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF7C, map_12_state_01_08E6EF7C, 0x08E6EF88, 0x08F0404C)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Duel? No, that is not\n"
    "permitted on these\n\n"
    "premises.\n\n"
    "...Is what I'm ordered to\n"
    "say.\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "But I always wanted to play\n"
    "to see what it's like.\n\n"
    "Let's duel!\n\n"
)
  DUEL(DUELIST_ROLAND_012)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF88, map_12_state_01_08E6EF88, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_KAIBACORP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Hmm... I think Mr. Kaiba is\n"
    "better at this than I am.\n\n"
)
  SET_FLAG(EVENT_FLAG_DEFEATED_ROLAND)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF94, map_12_state_01_08E6EF94, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "No, no. Not again!\n\n"
    "If Mr. Kaiba catches me,\n"
    "I'll be fired on the spot!\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
