#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_07: map 51 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08EE3F44, map_51_state_07_08EE3F44, 0x08EE3F68, 0x08EE3FBC)
  LOAD_SPRITE(1, SPRITE_MAI)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_MAI_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F68, map_51_state_07_08EE3F68, 0x08EE3F74, 0x08EE3FA4)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(1, 60, 48, 0, 1, 0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MAI3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F74, map_51_state_07_08EE3F74, 0x08EE3F80, 0x08EE3F8C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_MAI_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F80, map_51_state_07_08EE3F80, 0x08EE3F98, 0x08EE401C)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "This is as far as you'll get!")
  DUEL(DUELIST_MAI_118)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F98, map_51_state_07_08EE3F98, 0x08EE4004, EVENT_NOP)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I have the support of my friends...",
      "I'm not a spineless duelist like you!"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_MAI_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F8C, map_51_state_07_08EE3F8C, 0x08EE3F98, 0x08EE401C)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You're back again?",
      "Don't make me repeat myself!",
      "I won't allow you to get past me!"
  )
  DUEL(DUELIST_MAI_118)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FA4, map_51_state_07_08EE3FA4, 0x08EE3FB0, 0x08EE401C)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I don't care who I'm dueling!",
      "I always win!"
  )
  DUEL(DUELIST_MAI_118)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FB0, map_51_state_07_08EE3FB0, 0x08EE3FBC, EVENT_NOP)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Something that can both be seen and not seen...",
      "It's the courage to accept the pain of defeat.",
      "I always pretended to be strong even though I feared",
      "the despair after a defeat...",
      "{PLAYER}... You cut through the darkness.",
      "You are the light in the hearts of duelists."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_393)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  DELAY(8)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(SPRITE_CHEVALIER, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_MAI_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FBC, map_51_state_07_08EE3FBC, EVENT_NOP, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_GOT_PAST_DARK_MAI_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F50, map_51_state_07_08EE3F50, 0x08EE3F44, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3F5C, map_51_state_07_08EE3F5C, 0x08EE3F44, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE4010, map_51_state_07_08EE4010, EVENT_NOP, EVENT_NOP)
  CLEAR_FLAG(234)
  WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 6, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
