#include "event_macros.h"
#include "overworld.h"

/* map_55_state_02: map 55 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EF0570, map_55_state_02_08EF0570, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_MEDIUM_RUBBLE)
  LOAD_SPRITE(2, SPRITE_SMALL_RUBBLE)
  LOAD_SPRITE(3, SPRITE_BIG_RUBBLE)
  LOAD_SPRITE(4, SPRITE_MEDIUM_RUBBLE)
  LOAD_SPRITE(5, SPRITE_SMALL_RUBBLE)
  LOAD_SPRITE(6, SPRITE_BIG_RUBBLE)
  LOAD_SPRITE(7, SPRITE_MEDIUM_RUBBLE)
  LOAD_SPRITE(8, SPRITE_SMALL_RUBBLE)
  LOAD_SPRITE(9, SPRITE_BIG_RUBBLE)
  LOAD_SPRITE(10, SPRITE_MEDIUM_RUBBLE)
  LOAD_SPRITE(11, SPRITE_SMALL_RUBBLE)
  DELAY(128)
  FADE_SCREEN(8)
  WARP(54, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
