#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_35_state_01: map 35 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EC62A8, map_35_state_01_08EC62A8, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_REX)
  LOAD_SPRITE(2, SPRITE_GIRL_ARCHEOLOGIST)
  LOAD_SPRITE(3, SPRITE_THOUGHTFUL_ARCHEOLOGIST)
  PLAY_MUSIC(MUSIC_263)
  SCREEN_SHAKE(16)
  DELAY(16)
  PLAY_MUSIC(MUSIC_245)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "What... It's an earthquake!")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Is Reshef's resurrection causing the tremors?")
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
      "Whatever it is, stay on your toes.",
      "We better keep moving, guys."
  )
  SET_FLAG(EVENT_FLAG_SAW_CAVE_EARTHQUAKE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62CC, map_35_state_01_08EC62CC, 0x08EC62D8, 0x08EC632C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62D8, map_35_state_01_08EC62D8, 0x08EC62F0, 0x08EC6320)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_REX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62F0, map_35_state_01_08EC62F0, 0x08EC62FC, 0x08EC6308)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What are you three chumpasaurs doing here?",
      "You came all the way out here to see me?"
  )
  PLAY_MUSIC(MUSIC_332)
  FADE_SCREEN(4)
  TALK(PORTRAIT_REX, EXPRESSION_REX_SURPRISED, PORTRAIT_POSITION_AUTO, "Millennium Item?")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_1)
  DELAY(16)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You came all the way here looking for one of those",
      "things?",
      "Well... I could tell you what I know...",
      "But only if you can beat my Dino Deck!"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62FC, map_35_state_01_08EC62FC, 0x08EC6314, 0x08F0404C)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "That's the spirit! Let's duel!")
  DUEL(DUELIST_REX_046)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6314, map_35_state_01_08EC6314, 0x08EC6320, EVENT_NOP)
  PLAY_MUSIC(MUSIC_245)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Graaaah! You win!",
      "I wanted to learn how to strengthen my deck.",
      "That's why I came here because there's supposed to",
      "be some secret in these parts, but I guess I was",
      "wrong.",
      "I won't lose next time, though."
  )
  SET_FLAG(EVENT_FLAG_DEFEATED_REX)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 9, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 9, 0)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6320, map_35_state_01_08EC6320, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I don't know if it's what you're looking for...",
      "But I hear there's something odd in the back of the",
      "cave.",
      "Good luck on finding that thing."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6308, map_35_state_01_08EC6308, 0x08EC62FC, 0x08EC6308)
  TALK(PORTRAIT_REX, EXPRESSION_REX_ANGRY, PORTRAIT_POSITION_AUTO,
      "Yeah, I know you have more urgent things to do.",
      "But I don't care what you think.",
      "I've got my own reasons for dueling and dealing dino",
      "demolition.",
      "Come on, you wanna duel or not!"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC632C, map_35_state_01_08EC632C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Heh, looks like you found what you wanted.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62E4, map_35_state_01_08EC62E4, 0x08EC62F0, 0x08EC6338)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_REX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6338, map_35_state_01_08EC6338, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I'm starting over and rebuilding my deck from",
      "scratch. Another time."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62B4, map_35_state_01_08EC62B4, EVENT_NOP, EVENT_NOP)
  TEXT("That quake was off the Richter scale!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC62C0, map_35_state_01_08EC62C0, EVENT_NOP, EVENT_NOP)
  TEXT(
      "We don't often get quakes around these parts.",
      "I hope nothing bad is going to happen."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
