#include "event_macros.h"
#include "overworld.h"

/* map_30_state_01: map 30 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EAD9EC, map_30_state_01_08EAD9EC, 0x08EADA04, 0x08EADA34)
  CHECK_FLAG(18)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA04, map_30_state_01_08EADA04, 0x08EADA10, 0x08F0404C)
  PLAY_MUSIC(402)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "Those drawn by the\nMillennium Item...\n\nProve your worth here among\nthe eternal slumber.\n\n")
  LANGUAGE_TEXT(1, "Ceux qui sont attir\xe9s,\njusqu'ici parmi les morts,\n\npar cet Objet du mill\xe9nium\ndoivent se montrer dignes.\n\n")
  LANGUAGE_TEXT(2, "Wer vom Millenniumsgegen-\nstand angezogen wird...\n\nBeweise hier bei den schla-\nfenden Toten seine Kraft.\n\n")
  LANGUAGE_TEXT(3, "Coloro che sono attratti\ndall'Oggetto Millenario...\n\nDevono provare di esserne\ndegni qui, tra i morti.\n\n")
  LANGUAGE_TEXT(4, "Aquellos atra\xeddos por\nel Objeto del Milenio...\n\nDemostrad vuestra val\xeda\naqu\xed, entre los muertos\n\ndurmientes.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 58)
  WALK_OBJECT_X(0, 60)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_X(13, 66)
  WALK_OBJECT_Y(13, 68)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_X(14, 54)
  WALK_OBJECT_Y(14, 68)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  DUEL(37)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA10, map_30_state_01_08EADA10, 0x08EADA1C, 0x08F04040)
  PLAY_MUSIC(402)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "Impressive. Take this item.\n\n")
  LANGUAGE_TEXT(1, "Impressionnant.\nPrends cet objet.\n\n")
  LANGUAGE_TEXT(2, "Beeindruckend.\nNimm dies hier.\n\n")
  LANGUAGE_TEXT(3, "Davvero notevole.\nPrendi questo oggetto.\n\n")
  LANGUAGE_TEXT(4, "Impresionante.\nToma este objeto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA1C, map_30_state_01_08EADA1C, 0x08EADA28, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 60, 36, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(278)
  SLIDE_OBJECT(3, 0, 18)
  DELAY(8)
  PLAY_MUSIC(279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(280)
  SHOW_OBJECT(2, 60, 44, 0, 1, 0)
  DELAY(16)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, 7, 8)
  LANGUAGE_TEXT(0, "W-what? It's happening\nagain! This time, it's\n\nBakura!\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? Encore \xe7a ?\nCette fois, c'est Bakura !\n\n")
  LANGUAGE_TEXT(2, "W-was? Schon wieder?\nDieses Mal ist es Bakura!\n\n")
  LANGUAGE_TEXT(3, "C-cosa? Di nuovo?\nQuesta volta \xe8 Bakura!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9? \xbfEsto de nuevo?\n\xa1Es Bakura esta vez!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DARK_BAKURA, 0, 8)
  LANGUAGE_TEXT(0, "Which fool woke me up?\n\nHmm? Kukuku... I can feel\nit...\n\nI feel a storm brewing over\nthe Egyptian God Cards!\n\nI see a world where darkness\nrules...\n\nA world perfect for me!\n\nKukuku...\n\n")
  LANGUAGE_TEXT(1, "Quel est l'imb\xe9cile\nqui m'a r\xe9veill\xe9 ?\n\nMmm ? Kukuku...\nJe le sens...\n\nUn orage se pr\xe9pare\nau-dessus des cartes !\n\nUn monde o\xf9 r\xe8gnent\nles t\xe9n\xe8bres...\n\nOn pourrait presque\naimer \xe7a, ouais.\n\nKukuku...\n\n")
  LANGUAGE_TEXT(2, "Welcher Narr hat mich\ngeweckt?\n\nHmm? Kukuku...\nIch sp\xfcre es...\n\n\xdcber den G\xf6tterkarten zieht\nein Sturm auf!\n\nEine Welt, in der die\nDunkelheit herrscht...\n\nEinem k\xf6nnte das gefallen,\nja.\n\nKukuku...\n\n")
  LANGUAGE_TEXT(3, "Chi \xe8 l'idiota che\nmi ha svegliato?\n\nHmm? Eheheh...\nLo sento...\n\nSi prepara una tempesta\na causa delle carte divine!\n\nUn mondo dove regna\nl'oscurit\xe0...\n\nA qualcuno potrebbe anche\nnon dispiacere affatto.\n\nEheheheh...\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 loco me ha\ndespertado?\n\n\xbfHmm? Kukuku...\nLo puedo sentir...\n\nSe est\xe1 montando una buena\npor las cartas de los\n\ndioses.\n\nUn mundo en el que\nimpere la oscuridad...\n\nA alguien le podr\xeda\ngustar eso, s\xed...\n\nKukuku...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(4, 2)
  DELAY(64)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA28, map_30_state_01_08EADA28, 0x08F04250, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, 5, 8)
  LANGUAGE_TEXT(0, "Yikes! Millennium Items give\nme the willies.\n\n")
  LANGUAGE_TEXT(1, "Hi !\nCes Objets du mill\xe9nium,\n\n\xe7a me donne\nla chair de poule !\n\n")
  LANGUAGE_TEXT(2, "Aaaah!\nMillenniumsgegenst\xe4nde\n\nmachen mir echt Angst.\n\n")
  LANGUAGE_TEXT(3, "Brrrr! Gli Oggetti Millenari\nmi fanno venire i brividi.\n\n")
  LANGUAGE_TEXT(4, "\xa1Uf! Los Objetos del Milenio\nme dan el yuyu, t\xedo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "With the Millennium Ring, we\nnow have three items.\n\n{PLAYER}, let's get back to\nIshizu.\n\n")
  LANGUAGE_TEXT(1, "Avec cet Anneau du\nmill\xe9nium, \xe7a fait\n\nmaintenant trois objets.\n\n{PLAYER}, retournons\nvoir Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Mit dem Millenniumsring sind\nes jetzt drei Gegenst\xe4nde.\n\n{PLAYER}, kehren wir zu\nIshizu zur\xfcck.\n\n")
  LANGUAGE_TEXT(3, "Con l'Anello Millenario,\nora fanno tre oggetti.\n\n{PLAYER}, torniamo\nda Ishizu.\n\n")
  LANGUAGE_TEXT(4, "Con el Anillo del Milenio\nya son tres objetos.\n\n{PLAYER}, volvamos\na ver a Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(18)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA34, map_30_state_01_08EADA34, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "Millennium Items are\nbelieved to attract each\n\nother.\n\nThe Millennium Ring will\nlead you to the next one.\n\n")
  LANGUAGE_TEXT(1, "Il para\xeet que les Objets du\nmill\xe9nium s'attirent les\n\nuns les autres. L'Anneau du\nmill\xe9nium va te mener \xe0\n\nl'objet suivant.\n\n")
  LANGUAGE_TEXT(2, "Millenniumsgegenst\xe4nde\nziehen sich angeblich an.\n\nDer Millenniumsring f\xfchrt\ndich zum n\xe4chsten\n\nGegenstand.\n\n")
  LANGUAGE_TEXT(3, "Si dice che gli Oggetti\nMillenari si attraggano a\n\nvicenda. L'Anello Millena-\nrio ti condurr\xe0 al prossimo\n\noggetto.\n\n")
  LANGUAGE_TEXT(4, "Se dice que los Objetos del\nMilenio se atraen entre s\xed.\n\nEl Anillo del Milenio te\nllevar\xe1 al siguiente.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAD9F8, map_30_state_01_08EAD9F8, 0x08EADA04, 0x08EADA40)
  CHECK_FLAG(18)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA40, map_30_state_01_08EADA40, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "You are only allowed to duel\nme once.\n\nDid you not have to leave\nimmediately?\n\n")
  LANGUAGE_TEXT(1, "Je te donne une chance de\nm'affronter en duel, pas\n\nplus. Tu ne devais pas\npartir tout de suite ?\n\n")
  LANGUAGE_TEXT(2, "Du hast nur eine Chance,\num dich mit mir zu\n\nduellieren. Das ist alles.\n\nMusst du nicht sofort\ngehen?\n\n")
  LANGUAGE_TEXT(3, "Hai una sola possibilit\xe0\ndi duellare con me, una\n\ne basta. Non dovevi\npartire immediatamente?\n\n")
  LANGUAGE_TEXT(4, "Tienes una oportunidad\nde retarme; nada m\xe1s.\n\n\xbfNo ten\xedas que marchar\nde inmediato?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
