#include "event_macros.h"

/* map_28_state_01: map 28 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EA69C8, map_28_state_01_08EA69C8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(16)
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(32)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 0, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  LANGUAGE_TEXT(0, "Now this is rare.\n\n")
  LANGUAGE_TEXT(1, "Voici qui est assez rare.\n\n")
  LANGUAGE_TEXT(2, "Ist das nicht merkw\xfcrdig?\n\n")
  LANGUAGE_TEXT(3, "Lo trovo proprio strano.\n\n")
  LANGUAGE_TEXT(4, "\xbfNo es esto un\ntanto extra\xf1o?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "It certainly is.\n\n")
  LANGUAGE_TEXT(1, "Oui, en effet,\nmon petit chou.\n\n")
  LANGUAGE_TEXT(2, "Doch, sehr.\n\n")
  LANGUAGE_TEXT(3, "S\xec, lo \xe8 davvero.\n\n")
  LANGUAGE_TEXT(4, "S\xed, ciertamente.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(32)
  LANGUAGE_TEXT(0, "This is a community cemetery\nfrom long ago.\n\n")
  LANGUAGE_TEXT(1, "Cet endroit est un ancien\ncimeti\xe8re communautaire.\n\n")
  LANGUAGE_TEXT(2, "Das hier ist ein alter\nst\xe4dtischer Friedhof.\n\n")
  LANGUAGE_TEXT(3, "Tanto tempo fa questo\nera un cimitero.\n\n")
  LANGUAGE_TEXT(4, "Este lugar es un\ncementerio comunitario\n\ndesde hace mucho.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(32)
  LANGUAGE_TEXT(0, "I know. It's called the\nCatacombs.\n\n")
  LANGUAGE_TEXT(1, "Oui, je le savais. Ca\ns'appelle les Catacombes.\n\n")
  LANGUAGE_TEXT(2, "Ja, ich wei\xdf. Man nennt\nihn {BYTE_8168}Die Katakomben{BYTE_8168}.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, lo sapevo. Lo\nchiamano le Catacombe.\n\n")
  LANGUAGE_TEXT(4, "S\xed, lo sab\xeda. Son\nlas Catacumbas.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(16)
  LANGUAGE_TEXT(0, "That's right! You've done\nyour homework.\n\n")
  LANGUAGE_TEXT(1, "Bravo, tu as bien\nappris ta le\xe7on.\n\n")
  LANGUAGE_TEXT(2, "Stimmt. Du hast deine Haus-\naufgaben gut gemacht.\n\n")
  LANGUAGE_TEXT(3, "Esatto. Vedo che hai\nstudiato e sei preparata.\n\n")
  LANGUAGE_TEXT(4, "Eso es, has hecho\nlas tareas...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(270)
  REACTION(1, 4)
  DELAY(16)
  LANGUAGE_TEXT(0, "I haven't done any homework\nin decades, dear.\n\n")
  LANGUAGE_TEXT(1, "Il y a bien longtemps\n\nque je n'ai plus de\nle\xe7ons \xe0 apprendre.\n\n")
  LANGUAGE_TEXT(2, "Ich mache seit Jahrzehnten\nkeine Hausaufgaben mehr.\n\n")
  LANGUAGE_TEXT(3, "\xc8 da una vita che non\nstudio pi\xf9, caro.\n\n")
  LANGUAGE_TEXT(4, "No he hecho las tareas\nen d\xe9cadas, cari\xf1o.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(272)
  REACTION(3, 6)
  SET_FLAG(184)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69D4, map_28_state_01_08EA69D4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This is a community cemetery\nfrom long ago.\n\n")
  LANGUAGE_TEXT(1, "Cet endroit est un ancien\ncimeti\xe8re communautaire.\n\n")
  LANGUAGE_TEXT(2, "Das hier ist ein alter\nst\xe4dtischer Friedhof.\n\n")
  LANGUAGE_TEXT(3, "Tanto tempo fa questo\nera un cimitero.\n\n")
  LANGUAGE_TEXT(4, "Este lugar es un\ncementerio comunitario\n\ndesde hace mucho.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69E0, map_28_state_01_08EA69E0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Duo? What do you mean? Do\nyou want me to be your\n\npartner?\n\nDo you want to perform a duo\nand sing with me?\n\n")
  LANGUAGE_TEXT(1, "Un duo ? Comment \xe7a ?\nJe serais ton partenaire ?\n\nEst-ce qu'on devra\nchanter ensemble ?\n\n")
  LANGUAGE_TEXT(2, "Duo? Was soll das hei\xdfen?\nBin ich dein Partner?\n\nSollen wir etwa gemeinsam\nsingen?\n\n")
  LANGUAGE_TEXT(3, "Un duo? Che sarebbe?\nFar\xf2 coppia con te?\n\nCanteremo insieme?\n\n")
  LANGUAGE_TEXT(4, "\xbfD\xfao? \xbfQu\xe9 dices?\n\xbfVoy a ser tu pareja?\n\n\xbfVamos a cantar juntos?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69EC, map_28_state_01_08EA69EC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "It's called the Catacombs.\n\nFor some reason, this place\nmakes me feel calm.\n\n")
  LANGUAGE_TEXT(1, "Cet endroit s'appelle\nles Catacombes.\n\nJe ne sais pas pourquoi,\nmais cet endroit me calme.\n\n")
  LANGUAGE_TEXT(2, "Man nennt ihn {BYTE_8168}Die\nKatakomben{BYTE_8168}.\n\nUnd aus irgendeinem Grund\nerf\xfcllt mich dieser Ort\n\nmit Ruhe und Frieden.\n\n")
  LANGUAGE_TEXT(3, "Qui lo chiamano le\nCatacombe. Non so\n\nperch\xe9, ma questo posto\nmi fa sentire calma.\n\n")
  LANGUAGE_TEXT(4, "Se llama las Catacumbas.\n\nNo s\xe9 por qu\xe9, pero\neste lugar me hace\n\nestar en calma.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69F8, map_28_state_01_08EA69F8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Jewel?\n\nYou'll buy one for me?\n\n")
  LANGUAGE_TEXT(1, "Des bijoux ?\n\nTu vas en acheter\nun pour moi ?\n\n")
  LANGUAGE_TEXT(2, "Schmuckst\xfcck?\n\nDu willst mir eins kaufen?\n\n")
  LANGUAGE_TEXT(3, "Un gioiello?\n\nNe comprerai uno per me?\n\n")
  LANGUAGE_TEXT(4, "\xbfJoya?\n\n\xbfMe comprar\xe1s una?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
