#include "event_macros.h"
#include "overworld.h"

/* map_28_state_03: map 28 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EA69BC, map_28_state_03_08EA69BC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "I want the fortuneteller to\ntell me if me and my\n\nsnookums are made for each\nother!\n\n")
  LANGUAGE_TEXT(1, "Je vais l'affronter\npour voir \xe0 quel point\n\nnous sommes\ncompatibles !\n\n")
  LANGUAGE_TEXT(2, "Ich will erfahren, wie\ngut wir zusammenpassen!\n\n")
  LANGUAGE_TEXT(3, "Gli dir\xf2 di vedere se\nsiamo compatibili!\n\n")
  LANGUAGE_TEXT(4, "\xa1Quiero encontrarle\npara ver cu\xe1n\n\ncompatibles somos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "I'll get him to look into my\npast life.\n\n")
  LANGUAGE_TEXT(1, "Oh, non, je vais lui\nposer des questions\n\nsur ma vie pr\xe9c\xe9dente.\n\n")
  LANGUAGE_TEXT(2, "Oh nein, ich will mehr \xfcber\nmeine Vergangenheit wissen.\n\n")
  LANGUAGE_TEXT(3, "Oh, no, io gli far\xf2 control-\nlare la mia vita passata.\n\n")
  LANGUAGE_TEXT(4, "Oh, no, \xe9l ver\xe1\nmi vida anterior.\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "Isn't it exciting,\nsugarmuffin?\n\n")
  LANGUAGE_TEXT(1, "Tu ne trouves\npas \xe7a excitant ?\n\n")
  LANGUAGE_TEXT(2, "Ist es nicht aufregend?\n\n")
  LANGUAGE_TEXT(3, "Non lo trovi eccitante?\n\n")
  LANGUAGE_TEXT(4, "\xbfNo es emocionante?\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "It certainly is, kissylips!\n\n")
  LANGUAGE_TEXT(1, "Oh si, tr\xe8s excitant !\n\n")
  LANGUAGE_TEXT(2, "Oh ja!\n\n")
  LANGUAGE_TEXT(3, "Oh, s\xec, eccome!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ciertamente s\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 104)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 12)
  DELAY(8)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 2)
  DELAY(16)
  LANGUAGE_TEXT(0, "L-look... There he is...\n\nI... I know.\n\nOkay! Let's have him tell\nour fortunes!\n\nUrgh!\n\n")
  LANGUAGE_TEXT(1, "R-regarde...\nLe voil\xe0...\n\nJe... Je sais.\n\nOK ! On va lui demander\nnotre avenir !\n\nMmm !\n\n")
  LANGUAGE_TEXT(2, "Sch-schau...\nDa ist er...\n\nI-ich wei\xdf.\n\nOkay! Lassen wir uns von ihm\nunser Schicksal deuten!\n\nArgh!\n\n")
  LANGUAGE_TEXT(3, "G-guarda...\nEccolo l\xec...\n\nS\xec... Lo so.\n\nBene! Ci faremo\npredire il futuro!\n\nUrgh!\n\n")
  LANGUAGE_TEXT(4, "M-mira...\nAqu\xed est\xe1...\n\nLo... Lo s\xe9..\n\n\xa1Vale! \xa1Que nos diga\nnuestras suertes!\n\n\xa1Urgh!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Wh-what's the matter,\nlovebucket?\n\nMy back... Ow, ow, ow...\n\n")
  LANGUAGE_TEXT(1, "Q.. Qu'est-ce qu'il se\npasse, mon chou ?\n\nMon dos...\nA\xefe, a\xefe, a\xefe...\n\n")
  LANGUAGE_TEXT(2, "W-was ist los, mein Lieber?\n\nMein R\xfccken...\nOje oje...\n\n")
  LANGUAGE_TEXT(3, "Che... che\nsuccede, caro?\n\nLa mia schiena...\nOhi, ohi, ohi...\n\n")
  LANGUAGE_TEXT(4, "\xbfCu-cu\xe1l es el\nproblema, cari\xf1o?\n\nMi espalda...\nOu, ou, ou...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 56)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Are you okay?\n\nThe elderly should take it\neasy.\n\n")
  LANGUAGE_TEXT(1, "Est-ce que \xe7a va ?\n\nLes personnes \xe2g\xe9es\nne devraient pas\n\nessayer d'en faire trop.\n\n")
  LANGUAGE_TEXT(2, "Ist alles in Ordnung?\n\n\xc4ltere Menschen sollten\nes nicht \xfcbertreiben.\n\n")
  LANGUAGE_TEXT(3, "Tutto bene?\n\nGli anziani non\ndovrebbero strafare.\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s bien?\n\nLos mayores no deben\nhacer esfuerzos.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 12)
  DELAY(8)
  LANGUAGE_TEXT(0, "I had him do a reading about\nmy health...\n\nOh... What a waste...\n\n")
  LANGUAGE_TEXT(1, "Je lui ai pos\xe9 des questions\nsur mon \xe9tat de sant\xe9...\n\nOh... Quel g\xe2chis...\n\n")
  LANGUAGE_TEXT(2, "Ich habe mir von ihm\nsagen lassen,\n\nwie es um meine\nGesundheit steht...\n\nOh... Was f\xfcr eine Zeit-\nverschwendung...\n\n")
  LANGUAGE_TEXT(3, "Mi sono fatto dare notizie\nsulla mia salute...\n\nOh... Che spreco...\n\n")
  LANGUAGE_TEXT(4, "Le he pedido que\nme {BYTE_8168}lea{BYTE_8168} la salud...\n\nOh... Qu\xe9 derroche...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 2)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Speaking of who... What\nhappened to him?\n\n")
  LANGUAGE_TEXT(1, "Au fait... Qu'est-ce\nqu'il est devenu ?\n\n")
  LANGUAGE_TEXT(2, "\xdcbrigens... Was ist\nmit ihm geschehen?\n\n")
  LANGUAGE_TEXT(3, "Comunque...\nCosa gli \xe8 successo?\n\n")
  LANGUAGE_TEXT(4, "Por cierto...\n\xbfQu\xe9 le ha pasado?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 16, 0)
  DELAY(8)
  WALK_OBJECT_Y(3, 54)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(8)
  LANGUAGE_TEXT(0, "Wh-where are you going?\n\n")
  LANGUAGE_TEXT(1, "O\xf9... o\xf9 est-ce\nque tu vas ?\n\n")
  LANGUAGE_TEXT(2, "W-wohin gehst du?\n\n")
  LANGUAGE_TEXT(3, "D-dove te ne vai?\n\n")
  LANGUAGE_TEXT(4, "\xbfD-d\xf3nde vas?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "To see my friend.\n\n")
  LANGUAGE_TEXT(1, "Voir mon ami.\n\n")
  LANGUAGE_TEXT(2, "Zu meinem Freund.\n\n")
  LANGUAGE_TEXT(3, "A trovare il mio amico.\n\n")
  LANGUAGE_TEXT(4, "A ver a mi amigo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 0)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  COMMAND_7C_ARG(2, 16)
  FADE_SCREEN(16)
  WARP(31, 8, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
