#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_15_state_01: map 15 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E7A458, map_15_state_01_08E7A458, 0x08E7A464, 0x08E7A470)
  LOAD_SPRITE(1, SPRITE_NERVOUS_DUELIST)
  LOAD_SPRITE(2, SPRITE_ARROGANT_DUELIST)
  LOAD_SPRITE(3, SPRITE_INSECURE_DUELIST)
  LOAD_SPRITE(4, SPRITE_KAIBACORP_ADMIRER)
  LOAD_SPRITE(5, SPRITE_DOMINO_STATION_GUARD_2)
  PLAY_MUSIC(MUSIC_231)
  TALK(PORTRAIT_JOEY,
      "The Duel Express is reserved for duelists only...",
      "I'm raring to go!"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Our objective is...\nI won't lose!{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A464, map_15_state_01_08E7A464, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_JOEY,
      "Yeah, I know.",
      "But if we raise our duelist level while we look for the",
      "Millennium Items...",
      "That's like killing two birds with one stone."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A470, map_15_state_01_08E7A470, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_JOEY,
      "Me neither!",
      "It'll be a while until we reach the Egypt Exhibition.",
      "Let's raise our duelist levels while we can!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A47C, map_15_state_01_08E7A47C, 0x08E7A494, 0x08E7A4B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A494, map_15_state_01_08E7A494, EVENT_NOP, EVENT_NOP)
  TEXT
  (
      "W-"
  )
  DELAY(8)
  TEXT
  (
      "w-"
  )
  DELAY(8)
  TEXT
  (
      "w-"
  )
  DELAY(8)
  TEXT(
      "what?",
      "I-"
  )
  DELAY(8)
  TEXT
  (
      "I-"
  )
  DELAY(8)
  TEXT
  (
      "I-"
  )
  DELAY(8)
  TEXT("I'm n-")
  DELAY(8)
  TEXT
  (
      "not "
  )
  DELAY(8)
  TEXT("n-n-nervous!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4B8, map_15_state_01_08E7A4B8, EVENT_NOP, EVENT_NOP)
  TEXT(
      "That one duel calmed me down!",
      "Thank you!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A488, map_15_state_01_08E7A488, 0x08E7A4A0, 0x08E7A4B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4A0, map_15_state_01_08E7A4A0, 0x08E7A4AC, 0x08F0404C)
  TEXT
  (
      "W-"
  )
  DELAY(8)
  TEXT
  (
      "w-"
  )
  DELAY(8)
  TEXT
  (
      "w-"
  )
  DELAY(8)
  TEXT(
      "well, okay.",
      "I-"
  )
  DELAY(8)
  TEXT
  (
      "i-"
  )
  DELAY(8)
  TEXT("it's t-t-time to d-d-d-duel!")
  DUEL(DUELIST_JOEY_017)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4AC, map_15_state_01_08E7A4AC, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_231)
  TEXT
  (
      "Wow, "
  )
  DELAY(8)
  TEXT(
      "losing helped me relax. There's no more pressure to",
      "win."
  )
  SET_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4C4, map_15_state_01_08E7A4C4, EVENT_NOP, EVENT_NOP)
  TEXT("What a motley crew of pathetic duelists.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4D0, map_15_state_01_08E7A4D0, 0x08E7A4DC, 0x08E7A4F4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_ARROGANT_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4DC, map_15_state_01_08E7A4DC, 0x08E7A4E8, 0x08F0404C)
  TEXT(
      "Why? The tourney hasn't started yet, and we still",
      "haven't boarded the Duel Express!",
      "But I like your spunk! I accept your challenge!"
  )
  DUEL(DUELIST_JOEY_018)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4E8, map_15_state_01_08E7A4E8, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_231)
  TEXT(
      "I'm saving my real strategies for the",
      "tournament.."
  )
  SET_FLAG(EVENT_FLAG_DEFEATED_ARROGANT_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4F4, map_15_state_01_08E7A4F4, EVENT_NOP, EVENT_NOP)
  TEXT("I'll take you on again inside the train.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A50C, map_15_state_01_08E7A50C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Everyone looks so tough.",
      "I'm not sure if I can last until the end."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A500, map_15_state_01_08E7A500, 0x08E7A518, 0x08E7A530)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_INSECURE_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A518, map_15_state_01_08E7A518, 0x08E7A524, 0x08F0404C)
  TEXT("But you don't look so tough...")
  DELAY(8)
  TEXT("I think I can beat you.")
  DUEL(DUELIST_JOEY_019)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A524, map_15_state_01_08E7A524, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_231)
  TEXT("How could I lose to someone like you?")
  SET_FLAG(EVENT_FLAG_DEFEATED_INSECURE_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A530, map_15_state_01_08E7A530, EVENT_NOP, EVENT_NOP)
  TEXT("I'm fixing my deck.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A53C, map_15_state_01_08E7A53C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "KaibaCorp sure knows how to throw an event.",
      "They're letting us ride a chartered express train for",
      "free."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A548, map_15_state_01_08E7A548, 0x08E7A554, 0x08E7A56C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_KAIBA_CORP_ADMIRER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A554, map_15_state_01_08E7A554, 0x08E7A560, 0x08F0404C)
  TEXT("Huh, sure.")
  DUEL(DUELIST_JOEY_020)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A560, map_15_state_01_08E7A560, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_231)
  TEXT("Oh, yup, I lost. But that was fun.")
  SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA_CORP_ADMIRER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A56C, map_15_state_01_08E7A56C, EVENT_NOP, EVENT_NOP)
  TEXT("The train's leaving soon. Next time.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A578, map_15_state_01_08E7A578, EVENT_NOP, EVENT_NOP)
  TEXT(
      "The Duel Express is bound for the Egypt Exhibition.",
      "The station is very crowded due to the duel tournament.",
      "Please board the train in an orderly manner."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A584, map_15_state_01_08E7A584, 0x08E7A590, 0x08E7A5A8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A590, map_15_state_01_08E7A590, 0x08E7A59C, 0x08F0404C)
  TEXT(
      "Uhh, I'm on duty...",
      "B-but, I did want to give this game a try.",
      "Let's duel!"
  )
  DUEL(DUELIST_JOEY_021)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A59C, map_15_state_01_08E7A59C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_231)
  TEXT("I quite enjoyed that.")
  SET_FLAG(EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5A8, map_15_state_01_08E7A5A8, EVENT_NOP, EVENT_NOP)
  TEXT("The next stop is the Egypt Exhibition.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
