#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_03: map 12 state 3 */

LOAD_SPRITE(1, SPRITE_ROLAND)
LOAD_SPRITE(2, SPRITE_MOKUBA)
LOAD_SPRITE(3, SPRITE_TRISTAN)
LOAD_SPRITE(4, SPRITE_DUKE)
PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
WALK_OBJECT_X(0, 16)
WALK_OBJECT_Y(13, 54)
WALK_OBJECT_X(13, 6)
WALK_OBJECT_Y(14, 42)
WALK_OBJECT_X(14, 6)
DELAY(16)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I told you! No!\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_LEFT,
    "Oh, come on, please?\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yeah, we're Kaiba's best\n"
    "friends.\n\n"
)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I've never heard of you two\n"
    "before.\n\n"
)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_TRISTAN | SPRITE_DUKE)
WALK_OBJECT_X(SPRITE_MOKUBA, 102)
WALK_OBJECT_Y(SPRITE_MOKUBA, 56)
MOVE_OBJECT(SPRITE_MOKUBA, DIRECTION_LEFT, 0, 0)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "What's going on?\n\n"
)
MOVE_OBJECT(SPRITE_ROLAND, DIRECTION_RIGHT, 0, 0)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Master Mokuba...\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, PORTRAIT_LEFT,
    "M-Mokuba! We're friends,\n"
    "right?\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Tristan, that's not what\n"
    "we're here for.\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Whoops, that's right.\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "...Will somebody tell me\n"
    "what's going on?\n\n"
)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "These two are demanding\n"
    "that...\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Let us use your Duel\n"
    "Machine!\n\n"
)
WALK_OBJECT_X(SPRITE_TRISTAN, 94)
WALK_OBJECT_X(SPRITE_DUKE, 94)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "The Duel Machine?\n\n"
    "Why do you want it?\n\n"
)
SLIDE_OBJECT(SPRITE_TRISTAN, 0, 4)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_LEFT,
    "So Serenity will go out with\n"
    "me...\n\n"
)
PLAY_MUSIC(MUSIC_395)
SLIDE_OBJECT(SPRITE_DUKE, 2, 4)
SLIDE_OBJECT(SPRITE_TRISTAN, 2, 4)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "N-no! That's not it!\n\n"
    "We want to improve our duel\n"
    "levels.\n\n"
)
SLIDE_OBJECT(SPRITE_TRISTAN, 0, 4)
SLIDE_OBJECT(SPRITE_DUKE, 0, 4)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_LEFT,
    "Yeah! And THEN get a date\n"
    "with Serenity...\n\n"
)
PLAY_MUSIC(MUSIC_395)
SLIDE_OBJECT(SPRITE_DUKE, 2, 4)
SLIDE_OBJECT(SPRITE_TRISTAN, 2, 4)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MOKUBA)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Uh... Well, Seto's not here\n"
    "right now, so I guess it's\n\n"
    "okay...\n\n"
)
PLAY_MUSIC(MUSIC_273)
REACTION(REACTION_LOVE_HEART, SPRITE_TRISTAN | SPRITE_DUKE)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_LEFT,
    "Thanks Mokuba!\n\n"
)
WALK_OBJECT_X(SPRITE_TRISTAN, 102)
WALK_OBJECT_Y(SPRITE_TRISTAN, 44)
WALK_OBJECT_X(SPRITE_TRISTAN, 128)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yeah, thank you Mokuba.\n\n"
)
WALK_OBJECT_X(SPRITE_DUKE, 102)
WALK_OBJECT_Y(SPRITE_DUKE, 44)
WALK_OBJECT_X(SPRITE_DUKE, 128)
WALK_OBJECT_Y(SPRITE_MOKUBA, 44)
WALK_OBJECT_X(SPRITE_MOKUBA, 128)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO,
    "What the heck are those two\n"
    "up to?\n\n"
)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_ENTER_THE_DUEL_MACHINE_ROOM)

EVENT_SCRIPT_REPLACEMENT(0x08E6F000, map_12_state_03_08E6F000, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "This is the first time\n"
    "Master Mokuba invited his\n\n"
    "friends to visit him at\n"
    "work...\n\n"
    "But are those two really his\n"
    "friends?\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
