#include "event_macros.h"
#include "overworld.h"

/* map_31_state_09: map 31 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08EB43A8, map_31_state_09_08EB43A8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(410)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24577)
  DELAY(8)
  PLAY_MUSIC(280)
  SHOW_OBJECT(1, 72, 44, 0, 1, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I am Paradox.\n\nI am the sage of all\nduelists.\n\nI have heard many things\nabout you.\n\n")
  LANGUAGE_TEXT(1, "Je suis Paradox.\n\nLe plus sage de\ntous les duellistes.\n\nJ'ai entendu\nparler de vous.\n\n")
  LANGUAGE_TEXT(2, "Ich bin Paradox.\n\nIch bin der Weise aller\nDuellanten.\n\nIch habe schon\nvon euch geh\xf6rt.\n\n")
  LANGUAGE_TEXT(3, "Sono Paradox, il\nsaggio di tutti i\n\nduellanti. Ho sentito\nparlare di voi.\n\n")
  LANGUAGE_TEXT(4, "Yo soy Paradox.\n\nSoy el sabio de\ntodos los duelistas.\n\nHe o\xeddo hablar de vosotros.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 2)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "However, there's something\ndifferent about you.\n\nYou're not who I\nexpected...\n\n")
  LANGUAGE_TEXT(1, "Mais les apparences\nsont trompeuses.\n\n")
  LANGUAGE_TEXT(2, "Aber die Dinge sind wohl\nnicht so, wie man sagt.\n\n")
  LANGUAGE_TEXT(3, "Ma le cose sembrano\ndiverse da come pensavo.\n\n")
  LANGUAGE_TEXT(4, "Pero las cosas no parecen\nser como he o\xeddo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Enough with the weird\nintroductions!\n\nLet's cut to the chase.\nWhere's Pegasus?\n\n")
  LANGUAGE_TEXT(1, "H\xe9, le vieux, t'inqui\xe8te\npas pour \xe7a !\n\nArr\xeatons-nous ici.\nO\xf9 est Pegasus ?\n\n")
  LANGUAGE_TEXT(2, "He, mach dir keine Sorgen,\nalter Mann!\n\nSprechen wir \xfcber die Jagd\nhier. Wo ist Pegasus?\n\n")
  LANGUAGE_TEXT(3, "Ehi, lascia stare,\nnonnetto!\n\nVeniamo al dunque.\nDov'\xe8 Pegasus?\n\n")
  LANGUAGE_TEXT(4, "\xa1Bah! \xa1no te preocupes\npor eso, anciano!\n\nDejemos aqu\xed la persecuci\xf3n.\n\xbfD\xf3nde est\xe1 Pegasus?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(REACTION_SWEATDROP, 8193)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Why do you want to know?\n\n")
  LANGUAGE_TEXT(1, "Mais quel est l'int\xe9r\xeat\nde partir ?\n\n")
  LANGUAGE_TEXT(2, "Und was, wenn\nihr es wisst?\n\n")
  LANGUAGE_TEXT(3, "E a cosa vi serve\nandarlo a cercare?\n\n")
  LANGUAGE_TEXT(4, "\xbfY de qu\xe9 servir\xe1?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "We have to stop the Dark\nBeing at all costs!\n\n")
  LANGUAGE_TEXT(1, "Nous devons arr\xeater l'Etre\ndes t\xe9n\xe8bres, co\xfbte que\n\nco\xfbte.\n\n")
  LANGUAGE_TEXT(2, "Wir m\xfcssen den Dunklen\nunter allen Umst\xe4nden\n\naufhalten.\n\n")
  LANGUAGE_TEXT(3, "Dobbiamo fermare ad\nogni costo il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Tenemos que detener al Ser\nOscuro, no importa c\xf3mo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being...\n\nIf the three Egyptian God\nCards regained their\n\npower...\n\nIt may be possible to thwart\nReshef's grand design...\n\n")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des\nt\xe9n\xe8bres...\n\nPeut-\xeatre que si les\n{BYTE_8252} cartes de dieux\n\nretrouvent leur\npuissance...\n\nOn pourra contrecarrer\nles plans de Reshef...\n\n")
  LANGUAGE_TEXT(2, "Reschef der Dunkle...\n\nWenn die drei G\xf6tterkarten\nihre Macht zur\xfcckerhielten,\n\nk\xf6nnte man Reschefs Pl\xe4ne\nvielleicht vereiteln...\n\n")
  LANGUAGE_TEXT(3, "Reshef il Tenebroso...\nForse se le tre carte\n\ndivine riacquistassero\npotere, si potrebbe\n\nostacolare il grande\npiano di Reshef...\n\n")
  LANGUAGE_TEXT(4, "Reshef, el Ser Oscuro...\n\nQuiz\xe1 si las tres\ncartas de los dioses\n\nrecuperaran poder...\n\nPuede ser posible\ndetener el dise\xf1o\n\ngrandioso de Reshef...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah, so tell us where he's\nat...\n\n")
  LANGUAGE_TEXT(1, "Alors, dis-nous vite\no\xf9 il est...\n\n")
  LANGUAGE_TEXT(2, "Na, dann sag uns schnell,\nwo...\n\n")
  LANGUAGE_TEXT(3, "Be', allora vedi di\ndirci in fretta dove...\n\n")
  LANGUAGE_TEXT(4, "Bien, entonces date prisa\nen decirnos d\xf3nde...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Patience, young one.\nPatience.\n\n{PLAYER}, The Winged Dragon\nof Ra that you hold...\n\n")
  LANGUAGE_TEXT(1, "Ne sois pas\nsi impatient.\n\n{PLAYER}, le Dragon\nail\xe9 que tu poss\xe8des...\n\n")
  LANGUAGE_TEXT(2, "Immer mit Geduld.\n\n{PLAYER}, der gefl\xfcgelte\nDrache von Ra, den du\n\nin den H\xe4nden h\xe4ltst...\n\n")
  LANGUAGE_TEXT(3, "Tieni a freno la\ntua impazienza.\n\n{PLAYER}, il Drago\nAlato di Ra che hai...\n\n")
  LANGUAGE_TEXT(4, "Cont\xe9n la impaciencia.\n\n{PLAYER}, el Drag\xf3n con\nalas de Ra que tienes...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That card will not help you\nat Pegasus's castle.\n\nThe Winged Dragon of Ra has\nnot yet awoken.\n\n")
  LANGUAGE_TEXT(1, "Cette carte\nne t'aidera pas\n\nune fois arriv\xe9 au\nch\xe2teau de Pegasus.\n\nLe Dragon ail\xe9 de Ra\nne s'est pas r\xe9veill\xe9.\n\n")
  LANGUAGE_TEXT(2, "Diese Karte wird dir in\nPegasus' Burg nichts\n\nnutzen. Der gefl\xfcgelte\nDrache von Ra ist noch\n\nnicht erwacht.\n\n")
  LANGUAGE_TEXT(3, "Quella carta non ti aiuter\xe0\nal castello di Pegasus.\n\nIl Drago Alato di Ra non si\n\xe8 ancora risvegliato.\n\n")
  LANGUAGE_TEXT(4, "Esa carta no te ayudar\xe1\nen el castillo de Pegasus.\n\nEl Drag\xf3n con alas de Ra\na\xfan no se ha despertado.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That's right!\n\nIt's in Sphere Mode, right?\n\n")
  LANGUAGE_TEXT(1, "C'est \xe7a !\n\nIl est en mode Sph\xe8re ou\nun truc dans ce genre ?\n\n")
  LANGUAGE_TEXT(2, "Genau!\n\nEr befindet sich im Sph\xe4ren-\nModus oder so, stimmt's?\n\n")
  LANGUAGE_TEXT(3, "Proprio cos\xec!\n\n\xc8 in modalit\xe0 Sfera o\nqualcosa del genere, vero?\n\n")
  LANGUAGE_TEXT(4, "\xa1Cierto!\n\nEst\xe1 en el modo esfera\no as\xed, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You must restore Ra's power.\n\nThere must be someone who\nknows how to wake it...\n\n")
  LANGUAGE_TEXT(1, "Vous devez retrouver\nla puissance de Ra.\n\nQuelqu'un doit savoir\ncomment la r\xe9veiller...\n\n")
  LANGUAGE_TEXT(2, "Ihr m\xfcsst erst Ras Macht\nzur\xfcckgewinnen.\n\nIrgendjemand wei\xdf bestimmt,\nwie man sie weckt...\n\n")
  LANGUAGE_TEXT(3, "Dovete riconquistare\nil potere di Ra.\n\nCi dev'essere qualcuno che\nsa come risvegliarlo...\n\n")
  LANGUAGE_TEXT(4, "Deb\xe9is recobrar el\npoder de Ra.\n\nDebe de haber alguien que\nsepa c\xf3mo despertarlo...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_TALKED_TO_PARADOX_ABOUT_RA)
  FALLTHROUGH()
END_EVENT_SCRIPT()
