#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_30_state_01: map 30 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EAD9EC, map_30_state_01_08EAD9EC, 0x08EADA04, 0x08EADA34)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  LOAD_SPRITE(2, SPRITE_BAKURA)
  LOAD_SPRITE(3, SPRITE_MILLENNIUM_RING)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA04, map_30_state_01_08EADA04, 0x08EADA10, 0x08F0404C)
  PLAY_MUSIC(MUSIC_402)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Those drawn by the\n"
    "Millennium Item...\n\n"
    "Prove your worth here among\n"
    "the eternal slumber.\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 58)
  WALK_OBJECT_X(0, 60)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(13, 66)
  WALK_OBJECT_Y(13, 68)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_X(14, 54)
  WALK_OBJECT_Y(14, 68)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_037)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA10, map_30_state_01_08EADA10, 0x08EADA1C, 0x08F04040)
  PLAY_MUSIC(MUSIC_402)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Impressive. Take this item.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA1C, map_30_state_01_08EADA1C, 0x08EADA28, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(3, 60, 36, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_278)
  SLIDE_OBJECT(3, 0, 18)
  DELAY(8)
  PLAY_MUSIC(MUSIC_279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(2, 60, 44, 0, 1, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO,
    "W-what? It's happening\n"
    "again! This time, it's\n\n"
    "Bakura!\n\n"
)
  TALK(PORTRAIT_DARK_BAKURA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Which fool woke me up?\n\n"
    "Hmm? Kukuku... I can feel\n"
    "it...\n\n"
    "I feel a storm brewing over\n"
    "the Egyptian God Cards!\n\n"
    "I see a world where darkness\n"
    "rules...\n\n"
    "A world perfect for me!\n\n"
    "Kukuku...\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  DELAY(64)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA28, map_30_state_01_08EADA28, 0x08F04250, 0x08F04040)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Yikes! Millennium Items give\n"
    "me the willies.\n\n"
)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "With the Millennium Ring, we\n"
    "now have three items.\n\n"
    "{PLAYER}, let's get back to\n"
    "Ishizu.\n\n"
)
  SET_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA34, map_30_state_01_08EADA34, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Millennium Items are\n"
    "believed to attract each\n\n"
    "other.\n\n"
    "The Millennium Ring will\n"
    "lead you to the next one.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAD9F8, map_30_state_01_08EAD9F8, 0x08EADA04, 0x08EADA40)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EADA40, map_30_state_01_08EADA40, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You are only allowed to duel\n"
    "me once.\n\n"
    "Did you not have to leave\n"
    "immediately?\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
