#include "event_macros.h"
#include "overworld.h"

/* map_01_state_05: map 1 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E4282C, map_01_state_05_08E4282C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls have left,\nbut...\n\nWhy do I still feel uneasy?\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls sont\npartis, mais...\n\nPourquoi est-ce que j'ai cet\n\xe9trange pressentiment ?\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls sind fort,\naber...\n\nWarum f\xfchle ich mich nur\nso unbehaglich?\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls se ne sono\nandati, ma... Come mai\n\nprovo questa strana\nsensazione di terrore?\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls se\nhan marchado, pero...\n\n\xbfPor qu\xe9 tengo este\nsentimiento de\n\nque algo malo pasa?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42838, map_01_state_05_08E42838, 0x08E42844, 0x08E4285C)
  CHECK_FLAG(113)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42844, map_01_state_05_08E42844, 0x08E42850, 0x08F0404C)
  LANGUAGE_TEXT(0, "Sure thing!\n\n")
  LANGUAGE_TEXT(1, "C'est s\xfbr !\n\n")
  LANGUAGE_TEXT(2, "Aber sicher!\n\n")
  LANGUAGE_TEXT(3, "Ma certo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Claro!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(85)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42850, map_01_state_05_08E42850, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Yeah, dueling sure is fun.\n\n")
  LANGUAGE_TEXT(1, "Ouais, se battre en\nduel, c'est marrant.\n\n")
  LANGUAGE_TEXT(2, "Klar, duellieren macht\nSpa\xdf.\n\n")
  LANGUAGE_TEXT(3, "Duellare \xe8 davvero\ndivertente.\n\n")
  LANGUAGE_TEXT(4, "S\xed, luchar es divertido\nde verdad.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(113)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4285C, map_01_state_05_08E4285C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm tinkering with my deck\nso I can win next time.\n\nLet's duel some other time.\n\n")
  LANGUAGE_TEXT(1, "Je bidouille mon Deck pour\ngagner la prochaine fois.\n\nBattons-nous en duel\nune autre fois.\n\n")
  LANGUAGE_TEXT(2, "Ich feile an meinem Deck,\ndamit ich beim n\xe4chsten\n\nMal gewinne. Duellieren wir\nuns ein anderes Mal.\n\n")
  LANGUAGE_TEXT(3, "Sto sistemando il mio deck\nper vincere la prossima\n\nvolta. Duelliamo in\nun'altra occasione.\n\n")
  LANGUAGE_TEXT(4, "Estoy enredando con\nmi deck para poder\n\nganar la pr\xf3xima vez.\nLuchemos en otra ocasi\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42868, map_01_state_05_08E42868, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "There are evil duelists,\nlike the Neo Ghouls...\n\nBut it's still fun to duel.\n\n")
  LANGUAGE_TEXT(1, "Il y a des m\xe9chants\ncomme les Neo Ghouls.\n\nMais m\xeame avec eux,\nles duels sont marrants.\n\n")
  LANGUAGE_TEXT(2, "Es gibt \xfcble Typen wie\ndie Neo Ghouls.\n\nAber trotzdem macht\nDuellieren Spa\xdf.\n\n")
  LANGUAGE_TEXT(3, "Ci sono dei mascalzoni\ncome i Neo Ghouls.\n\nMa i duelli sono\ndivertenti anche cos\xec.\n\n")
  LANGUAGE_TEXT(4, "Hay tipos malos\ncomo los Neo Ghouls.\n\nPero, a\xfan as\xed, los duelos\nson divertidos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42874, map_01_state_05_08E42874, 0x08E42880, 0x08E42898)
  CHECK_FLAG(114)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42880, map_01_state_05_08E42880, 0x08E4288C, 0x08F0404C)
  LANGUAGE_TEXT(0, "Okay! I'm not going to lose!\n\n")
  LANGUAGE_TEXT(1, "OK !\nJe ne vais pas perdre !\n\n")
  LANGUAGE_TEXT(2, "Okay!\nIch werde nicht verlieren!\n\n")
  LANGUAGE_TEXT(3, "Okay!\nIo non perder\xf2 di certo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale!\n\xa1No voy a perder!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(86)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4288C, map_01_state_05_08E4288C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Sigh... I lost after all.\n\n")
  LANGUAGE_TEXT(1, "Mince.\nJ'ai tout perdu.\n\n")
  LANGUAGE_TEXT(2, "Mist. Ich habe doch\nnoch verloren.\n\n")
  LANGUAGE_TEXT(3, "Maledizione.\nAlla fine ho perso.\n\n")
  LANGUAGE_TEXT(4, "Maldita sea.\nHe perdido.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(114)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42898, map_01_state_05_08E42898, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm not good enough to\ncompete against you.\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas assez fort\npour jouer contre toi.\n\n")
  LANGUAGE_TEXT(2, "Ich bin nicht gut genug\nals Gegner f\xfcr dich.\n\n")
  LANGUAGE_TEXT(3, "Non sono abbastanza\nforte da giocare con te.\n\n")
  LANGUAGE_TEXT(4, "No soy lo bastante bueno\ncomo para enfrentarme a ti.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428A4, map_01_state_05_08E428A4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hyohyohyohyo!\n\nThe Neo Ghouls are gone, all\nthanks to me!\n\nYou maggots better be\ngrateful.\n\nJust to let you know, my\nswarm of bugs are more\n\nrugged than ever!\n\n")
  LANGUAGE_TEXT(1, "Hyo hyo hyo !\n\nGr\xe2ce \xe0 moi, les Neo Ghouls\nsont partis !\n\nTu devrais \xeatre\nreconnaissant.\n\nJe vais renforcer mon\nDeck en contemplant\n\nces insectes.\n\n")
  LANGUAGE_TEXT(2, "Hyohyohyohyo!\n\nDank mir sind die Neo\nGhouls abgezogen!\n\nDu solltest mir\ndankbar sein.\n\nIch werde mein Deck st\xe4rken,\nw\xe4hrend ich mir ein paar\n\nh\xfcbsche K\xe4fer anschaue.\n\n")
  LANGUAGE_TEXT(3, "Iohiohiohioh!\n\nGrazie a me, i Neo\nGhouls se ne sono andati!\n\nDovresti essermi grato.\n\nMentre guardo gli insetti,\nrafforzer\xf2 il mio deck.\n\n")
  LANGUAGE_TEXT(4, "\xa1Hyohyohyohyo!\n\n\xa1Gracias a m\xed, los Neo\nGhouls se han marchado!\n\n\xa1Deber\xedas estar agradecido!\n\nVoy a reforzar mi deck\nmientras miro insectos.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 0)
  SET_OBJECT_POSITION(3, 128, 96, 0)
  SET_FLAG(115)
  SET_MAP_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()
