#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_02: map 6 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CC00, map_06_state_02_08E5CC00, 0x08E5CC0C, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_TRISTAN)
  LOAD_SPRITE(2, SPRITE_DUKE)
  LOAD_SPRITE(3, SPRITE_LUCKY)
  LOAD_SPRITE(4, SPRITE_YUGI)
  LOAD_SPRITE(5, SPRITE_SERENITY)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  WALK_OBJECT_Y(0, 40)
  WALK_OBJECT_X(0, 88)
  WALK_OBJECT_Y(13, 56)
  WALK_OBJECT_X(13, 88)
  WALK_OBJECT_Y(14, 48)
  WALK_OBJECT_X(14, 88)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC0C, map_06_state_02_08E5CC0C, 0x08E5CC18, EVENT_NOP)
  PLAY_MUSIC(MUSIC_371)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Go, Gradius!")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_DEFEATED, PORTRAIT_POSITION_AUTO,
      "Gwaaah!",
      "I lost again!"
  )
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hahaha, you can duel me a thousand times and I'll",
      "still win them all.",
      "Since it's clear that I'm the better duelist, I get",
      "to go out with Serenity, like we agreed."
  )
  HIDE_PORTRAIT()
  DELAY(4)
  WALK_OBJECT_X(14, 64)
  DELAY(8)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_14)
  DELAY(8)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
      "Hey hey! What's the big idea!",
      "What's this so-called agreement? No one told me!"
  )
  HIDE_PORTRAIT()
  DELAY(4)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1 | OBJECT_2)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Yeah, Duke! For once, Joey's right. I'm canceling our",
      "deal!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "That's not fair! You're the one who thought it up!")
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO, "Tristaaaaaaaaaaan!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC18, map_06_state_02_08E5CC18, 0x08E5CC24, EVENT_NOP)
  WALK_OBJECT_X(5, 76)
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_ANGRY, PORTRAIT_POSITION_AUTO,
      "Joey! You promised you wouldn't fight, especially",
      "with your friends."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "B-but Serenity...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_273)
  REACTION(REACTION_LOVE_HEART, OBJECT_1 | OBJECT_2)
  TEXT("You're so sweet, Serenity!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC24, map_06_state_02_08E5CC24, 0x08E5CC30, EVENT_NOP)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_14)
  DELAY(32)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Serenity, I wasn't fighting.")
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, PORTRAIT_POSITION_AUTO,
      "You weren't? It looked like you were... I guess I was",
      "wrong.",
      "I'm sorry, Joey."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "Nah, you don't need to apologize...")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, PORTRAIT_POSITION_AUTO,
      "Yeah! Serenity, you didn't do anything wrong! You",
      "never do anything wrong."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC30, map_06_state_02_08E5CC30, 0x08E5CC3C, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Serenity, which duelist do you like? Strong and tough,",
      "like me?"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hmm."
  )
  DELAY(43)
  TEXT
  (
      "."
  )
  DELAY(43)
  TEXT
  (
      ". "
  )
  DELAY(43)
  TEXT("Maybe...")
  HIDE_PORTRAIT()
  DELAY(43)
  WALK_OBJECT_X(1, 48)
  WALK_OBJECT_X(14, 68)
  DELAY(32)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "But I think a duelist like Mai is the best!")
  PLAY_MUSIC(MUSIC_273)
  REACTION(REACTION_LOVE_HEART, OBJECT_5)
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_1 | OBJECT_2 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "{BYTE_8169}...That's not the answer we're looking for...{BYTE_816A}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC3C, map_06_state_02_08E5CC3C, 0x08E5CC48, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_POSITION_AUTO,
      "If that's the case, I'll duel Mai Valentine!",
      "I'll beat her and prove that I'm a powerful duelist,",
      "especially stronger than Duke!",
      "And then she'll fall madly in love with me!"
  )
  WALK_OBJECT_X(1, 144)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Hey, wait! You can't ditch me!")
  WALK_OBJECT_X(2, 144)
  MOVE_OBJECT(5, DIRECTION_RIGHT, 4, 1)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_5)
  DELAY(32)
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, PORTRAIT_POSITION_AUTO, "Tristan and Duke... What's gotten into them?")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_14)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC48, map_06_state_02_08E5CC48, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "I'm never gonna leave them alone with you, Serenity...")
  SET_FLAG(EVENT_FLAG_TRISTAN_AND_DUKE_WENT_TO_SEE_MAI)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC54, map_06_state_02_08E5CC54, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{PLAYER}, please keep an eye on Joey.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC60, map_06_state_02_08E5CC60, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I'm no match for you, {PLAYER}.",
      "If you want to duel, I think my big brother would be a",
      "finer opponent.",
      "He's always practicing to become the best duelist in",
      "the world."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
