#include "event_macros.h"
#include "overworld.h"

/* map_24_state_05: map 24 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E9821C, map_24_state_05_08E9821C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "It's so awesome that the Neo\nGhouls are gone.\n\n")
  LANGUAGE_TEXT(1, "C'est trop bien, les Neo\nGhouls sont partis.\n\n")
  LANGUAGE_TEXT(2, "Es ist ein phantastisches\nGef\xfchl, nun da die\n\nNeo Ghouls fort sind.\n\n")
  LANGUAGE_TEXT(3, "Splendido, i Neo Ghouls\nse ne sono andati.\n\n")
  LANGUAGE_TEXT(4, "Es incre\xedble, los\nNeo Ghouls se han ido.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(1, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98228, map_24_state_05_08E98228, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Get lost! Stop making fun of\nme!\n\nHow am I supposed to duel\nwithout any cards?\n\nThe Neo Ghouls stole every\none of my cards!\n\n")
  LANGUAGE_TEXT(1, "Arr\xeate ! Te moque\npas de moi !\n\nComment veux-tu que\nje me batte en duel\n\nsi je n'ai pas de cartes ?\n\nLes Neo Ghouls me\nles ont toutes prises.\n\n")
  LANGUAGE_TEXT(2, "Verschwinde! Mach dich\nnicht \xfcber mich lustig!\n\nWie soll ich mich denn\nohne Karten duellieren?\n\nDie Neo Ghouls haben mir\nalle Karten gestohlen!\n\n")
  LANGUAGE_TEXT(3, "Vedi di smammare!\nNon prenderti gioco di me!\n\nCome faccio a duellare senza\ncarte? I Neo Ghouls mi\n\nportato via le carte,\ndalla prima all'ultima!\n\n")
  LANGUAGE_TEXT(4, "\xa1Pi\xe9rdete!\n\xa1No te r\xedas de m\xed!\n\n\xbfC\xf3mo voy a\nluchar sin cartas?\n\n\xa1Los Neo Ghouls se\nllevaron todas mis cartas!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(1, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98234, map_24_state_05_08E98234, 0x08F04040, 0x08F04040)
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  LANGUAGE_TEXT(0, "Takeshi, like, I don't care\nif you can't duel. I love\n\nyou!\n\n")
  LANGUAGE_TEXT(1, "Takeshi, je m'en fiche\nsi tu ne peux pas\n\nte battre en duel.\nJe t'aime !\n\n")
  LANGUAGE_TEXT(2, "Takeshi, es ist mir egal,\nwenn du dich nicht\n\nduellieren kannst.\nIch liebe dich!\n\n")
  LANGUAGE_TEXT(3, "Takeshi, non m'importa\nse non puoi duellare.\n\nIo ti amo!\n\n")
  LANGUAGE_TEXT(4, "Takeshi, no me im-\nporta si no puedes\n\nluchar. \xa1Te quiero!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98240, map_24_state_05_08E98240, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "What are you, like some kind\nof dueling fanatic?\n\nYou're, like, totally\nbugging me! Go away.\n\n")
  LANGUAGE_TEXT(1, "T'es qui, toi ? Un de\nces obs\xe9d\xe9s des duels ?\n\nVraiment, tu crains !\nAllez, vas-t-en !\n\n")
  LANGUAGE_TEXT(2, "Was, bist du eine Art\nDuellfreak?\n\nDu spinnst ja total!\nHau ab.\n\n")
  LANGUAGE_TEXT(3, "Che sei un appassionato\ndi duelli, per caso?\n\nSei davvero fuori di testa!\nVattene.\n\n")
  LANGUAGE_TEXT(4, "\xbfT\xfa qu\xe9 eres?\n\xbfUn bicho raro del duelo?\n\n\xa1Eres raro de verdad!\nVete por ah\xed.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
