#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_13_state_01: map 13 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E716A0, map_13_state_01_08E716A0, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MOKUBA)
  LOAD_SPRITE(2, SPRITE_TRISTAN)
  LOAD_SPRITE(3, SPRITE_DUKE)
  LOAD_SPRITE(4, SPRITE_INVISIBLE)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Mokuba, crank it up to the max duelist level!")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "No way! The computer will totally pummel you! Start",
      "at level {BYTE_8251}.",
      "If you can't win at that level, then you're plain",
      "lame."
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Oh, fine. I guess that'll have to do.")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Set me up at the same level!")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Okay, start the Duel Machine!")
  PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  FADE_SCREEN(2)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_DEFEATED, PORTRAIT_POSITION_AUTO, "Gwaaaaaaah!")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I... I barely won.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  TEXT(
      "ASSESSING DUELIST LEVEL...",
      "ASSESSING DUELIST LEVEL...",
      "ASSESSMENT COMPLETE.",
      "BOTH IDIOTS. BOTH IDIOTS."
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "Are you serious?")
  TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "But I won!")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Simply winning doesn't impress the Duel Machine.",
      "It also checks for spell and trap combos.",
      "Judging by your skills, I'd say the computer made the",
      "right call."
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Oh yeah? One more time!")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Go right ahead. But I think you're wasting your time.")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 32)
  WALK_OBJECT_Y(1, 52)
  WALK_OBJECT_X(1, 16)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DUELING_THE_DUEL_MACHINE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716AC, map_13_state_01_08E716AC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "I'm training! Don't distract me!")
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716B8, map_13_state_01_08E716B8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "Can't you see I'm dueling?")
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716C4, map_13_state_01_08E716C4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "I can't lose to Tristan.")
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716D0, map_13_state_01_08E716D0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "Please don't bug me while I'm training.")
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E71760, map_13_state_01_08E71760, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  TEXT(
      "OPERATING AT DUELIST LEVEL {BYTE_8251}.",
      "SYSTEM IN OPERATION."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7176C, map_13_state_01_08E7176C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  TEXT(
      "OPERATING AT DUELIST LEVEL FOR IDIOTS.",
      "SYSTEM IN OPERATION.",
      "WAIT FOR YOUR TURN BEFORE STARTING."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
