#include "event_macros.h"
#include "overworld.h"

/* map_31_state_08: map 31 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08EB43CC, map_31_state_08_08EB43CC, 0x08EB43D8, 0x08F04040)
  PLAY_MUSIC(706)
  PLAY_MUSIC(380)
  SHOW_OBJECT(2, 64, 96, 0, 0, 0)
  MOVE_OBJECT(2, 2, 32, 0)
  MOVE_OBJECT(2, 1, 6, 0)
  MOVE_OBJECT(2, 2, 8, 0)
  MOVE_OBJECT(2, 1, 8, 0)
  MOVE_OBJECT(2, 2, 4, 0)
  MOVE_OBJECT(2, 1, 4, 0)
  MOVE_OBJECT(2, 2, 12, 0)
  MOVE_OBJECT(2, 1, 6, 0)
  MOVE_OBJECT(2, 3, 8, 0)
  MOVE_OBJECT(2, 0, 6, 0)
  MOVE_OBJECT(2, 1, 10, 0)
  MOVE_OBJECT(2, 0, 10, 0)
  MOVE_OBJECT(2, 3, 4, 0)
  MOVE_OBJECT(2, 0, 4, 0)
  MOVE_OBJECT(2, 1, 6, 0)
  MOVE_OBJECT(2, 2, 8, 0)
  MOVE_OBJECT(2, 1, 4, 0)
  WALK_OBJECT_Y(2, 42)
  WALK_OBJECT_X(2, 24)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB43D8, map_31_state_08_08EB43D8, 0x08F04040, 0x08F04040)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  WALK_OBJECT_Y(1, 42)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(32)
  PLAY_MUSIC(367)
  SLIDE_OBJECT(1, 1, 20)
  MOVE_OBJECT(2, 2, 8, 0)
  MOVE_OBJECT(2, 1, 12, 0)
  MOVE_OBJECT(2, 2, 6, 0)
  MOVE_OBJECT(2, 1, 4, 0)
  MOVE_OBJECT(2, 2, 6, 0)
  MOVE_OBJECT(2, 1, 6, 0)
  MOVE_OBJECT(2, 2, 8, 0)
  WALK_OBJECT_X(2, 0)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(275)
  REACTION(5, 2)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PORTRAIT(PORTRAIT_WEEVIL, 0, 1)
  LANGUAGE_TEXT(0, "Arrrgh! That bug got away!\n\n")
  LANGUAGE_TEXT(1, "Arrrgh ! Ce mis\xe9rable\ninsecte s'est \xe9chapp\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Arrrgh! Der K\xe4fer ist\nmir entwischt!\n\n")
  LANGUAGE_TEXT(3, "Arrrgh! Quel dannato\ninsetto mi \xe8 sfuggito!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arrrgh! \xa1Ese bicho\nse ha escapado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_WEEVIL, 0, 1)
  LANGUAGE_TEXT(0, "But... The insects have come\nback...\n\n...Does that mean he's back\ntoo?\n\n")
  LANGUAGE_TEXT(1, "Mais... Les insectes\nsont de retour...\n\n... Est-ce qu'il serait\nlui aussi de retour ?\n\n")
  LANGUAGE_TEXT(2, "Aber...\nDie K\xe4fer sind zur\xfcck...\n\n... Ob er auch zur\xfcck ist?\n\n")
  LANGUAGE_TEXT(3, "Ma... Gli insetti\nsono tornati...\n\n... Sar\xe0 tornato pure lui?\n\n")
  LANGUAGE_TEXT(4, "Pero..\n\nLos insectos han\nregresado...\n\n... \xbf\xc9l tambi\xe9n?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(8)
  MOVE_OBJECT(1, 0, 6, 0)
  DELAY(4)
  MOVE_OBJECT(1, 3, 4, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(8)
  MOVE_OBJECT(1, 1, 4, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_WEEVIL, 0, 1)
  LANGUAGE_TEXT(0, "He probably doesn't think of\nme as a friend, so I\n\nshouldn't go visit him....\n\nBut I did give him my\ncard...\n\nSo maybe it wouldn't be\nweird for me to visit him.\n\nYup, that's what I'll do.\n\nI'll just say I want to see\nhow my card is doing!\n\n")
  LANGUAGE_TEXT(1, "Je... Je lui ai\ndonn\xe9 ma carte.\n\nCe ne serait donc\npas bizarre pour moi\n\nd'aller le voir.\n\nOui.\nJe vais faire \xe7a.\n\nJe vais voir comment\nma carte est utilis\xe9e !\n\n")
  LANGUAGE_TEXT(2, "Ich...\nIch gab ihm meine Karte.\n\nDamit ich ihn besuchen kann,\nohne Verdacht zu erregen.\n\nJa.\nDas geht.\n\nIch werde schauen, was\nmeine Karte macht!\n\n")
  LANGUAGE_TEXT(3, "Io...\nGli ho dato la mia carta.\n\nQuindi non c'\xe8 niente di\nstrano se vado a vederlo.\n\nS\xec.\nFar\xf2 cos\xec.\n\nAndr\xf2 a vedere cosa\ncombina la mia carta!\n\n")
  LANGUAGE_TEXT(4, "Le...\nLe di mi carta.\n\nPor lo que no ser\xeda\nraro que fuera a verle.\n\nS\xed.\nEso funcionar\xe1.\n\n\xa1Voy a ver c\xf3mo\nle va a mi carta!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 96)
  COMMAND_7C_ARG(2, 16)
  FADE_SCREEN(16)
  WARP(34, 5, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
