#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_29_state_08: map 29 state 8 */

LOAD_SPRITE(1, SPRITE_BONZ)
LOAD_SPRITE(2, SPRITE_JEAN_CLAUDE_MAGNUM)
LOAD_SPRITE(3, SPRITE_FORTUNE_TABLE)
PLAY_MUSIC(MUSIC_JEAN_CLAUDE_MAGNUM)
DELAY(32)
MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
DELAY(16)
MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
DELAY(16)
MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Oh! Fantastic!\n\n"
    "This is where we'll film my\n"
    "new movie!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(2, 60)
MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Hey! You!\n\n"
)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Are you talking to me?\n\n"
)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "I'm Hollywood superstar Jean\n"
    "Claude Magnum, but I'm sure\n\n"
    "you already knew that.\n\n"
    "I'm shooting my next film\n"
    "here.\n\n"
)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "...\n\n"
)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "What are you doing here?\n\n"
)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "I'm a tour guide, plus I\n"
    "read fortunes.\n\n"
)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Fortunetelling!\n\n"
    "How absolutely spectacular!\n\n"
    "I want you to read the\n"
    "future regarding my\n\n"
    "marriage proposal to Mai\n"
    "Valentine.\n\n"
)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "No problem.\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_RIGHT, 8, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_LEFT, 16, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_RIGHT, 8, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Spirits of the Catacombs,\n"
    "answer me...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_RIGHT, 16, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Infuse me with the knowledge\n"
    "of the past so that I can\n\n"
    "glimpse the future...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(1, DIRECTION_LEFT, 10, 0)
MOVE_OBJECT(1, DIRECTION_DOWN, 10, 0)
MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_DOWN, 10, 0)
MOVE_OBJECT(1, DIRECTION_RIGHT, 10, 0)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_RIGHT, 10, 0)
MOVE_OBJECT(1, DIRECTION_UP, 10, 0)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_UP, 10, 0)
MOVE_OBJECT(1, DIRECTION_LEFT, 10, 0)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(32)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
DELAY(64)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_2)
DELAY(32)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
DELAY(8)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "You can marry her if you win\n"
    "three duels in a row.\n\n"
)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Really? You better not be\n"
    "joking!\n\n"
    "If it's true, it was worth\n"
    "making this trip to the\n\n"
    "Italian Catacombs!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Let the countdown to my\n"
    "wedding begin!\n\n"
    "There's my first victim!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(8)
WALK_OBJECT_X(2, 30)
DELAY(16)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "I'm counting down to my\n"
    "marriage with Mai!\n\n"
    "Don't worry. Even when you\n"
    "lose, I'll let you be my\n\n"
    "best man.\n\n"
)
DUEL(DUELIST_JEAN_CLAUDE_MAGNUM_131)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, PORTRAIT_POSITION_AUTO)
TEXT
(
    "N-noooooo!\n\n"
    "My marriage to Mai...\n\n"
)
PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Oh, oh yeah!! I just need to\n"
    "win three times in a row!\n\n"
    "It never said I had to duel\n"
    "anybody strong!\n\n"
    "That's why I'm outta here!\n\n"
    "Farewell!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(2, 0)
SHOW_OBJECT(2, 128, 96, 0, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "...I forgot to mention that\n"
    "if lose even one duel, your\n\n"
    "fortune changes. Oh well.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
SET_FLAG(EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM2)
