#include "event_macros.h"
#include "overworld.h"

/* map_39_state_03: map 39 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08ED4ABC, map_39_state_03_08ED4ABC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(407)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, 7, 8)
  LANGUAGE_TEXT(0, "S-say something!\n\n")
  LANGUAGE_TEXT(1, "D-dis quelque chose !\n\n")
  LANGUAGE_TEXT(2, "S-sag etwas!\n\n")
  LANGUAGE_TEXT(3, "Di'... Di' qualcosa!\n\n")
  LANGUAGE_TEXT(4, "\xa1D...di algo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_STRINGS, 0, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 0, 8, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, 7, 8)
  LANGUAGE_TEXT(0, "W-what a strange individual!\nI've never felt so\n\nuncomfortable...\n\n")
  LANGUAGE_TEXT(1, "T-tu me fais peur !\nC'est trop effrayant...\n\n")
  LANGUAGE_TEXT(2, "D-du machst mir Angst!\nDas ist zu unheimlich...\n\n")
  LANGUAGE_TEXT(3, "Mi dai i brividi!\n\xc8 troppo spaventoso...\n\n")
  LANGUAGE_TEXT(4, "\xa1M...me est\xe1s asustando!\nEsto es demasiado raro...\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(93)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AD4, map_39_state_03_08ED4AD4, 0x08ED4AE0, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, 1, 8)
  LANGUAGE_TEXT(0, "Hey, you've come just at the\nright time.\n\nCan you do something about\nthis person?\n\nI lack the skill to deal\nwith such weirdness.\n\n")
  LANGUAGE_TEXT(1, "Oh, h\xe9, tu parles\nd'arriver au bon moment.\n\nEst-ce que tu peux t'occuper\nde ce mec \xe0 ma place ?\n\nJ'ai du mal avec lui,\ntu as compris ?\n\n")
  LANGUAGE_TEXT(2, "Oh, he, du kommst mir\nwie gerufen.\n\nErledigst du f\xfcr mich\ndiesen Typ?\n\nIch habe Probleme mit\nihm, verstehst du?\n\n")
  LANGUAGE_TEXT(3, "Ehi, proprio un\ntempismo perfetto.\n\nPuoi vedertela tu con questo\nragazzo, al posto mio?\n\nHo qualche difficolt\xe0 con i\ntipi come lui, capito?\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, eh, habla de llegar\nen su momento!\n\n\xbfPuedo mandarte a tratar\ncon ese t\xedo por m\xed?\n\nLo he pasado mal con su\ntipo, \xbfentendido?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AE0, map_39_state_03_08ED4AE0, 0x08ED4AEC, 0x08ED4AF8)
  LANGUAGE_TEXT(0, "{CARD_1}Leave it to me!\nHe creeps me out, too.{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Je m'en occupe !\nMoi aussi, j'ai peur.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}\xdcberlass ihn mir!\nMir macht er auch Angst.{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Lascia fare a me!\nSono spaventato anch'io.{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1D\xe9jamelo a m\xed!\nNo, \xa1estoy asustado!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AEC, map_39_state_03_08ED4AEC, 0x08ED4B04, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, 0, 8)
  LANGUAGE_TEXT(0, "I'm counting on you!\n\n")
  LANGUAGE_TEXT(1, "Ouais, il est \xe0 toi !\n\n")
  LANGUAGE_TEXT(2, "Okay, er geh\xf6rt ganz dir!\n\n")
  LANGUAGE_TEXT(3, "Bene, \xe8 tutto tuo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uf! \xa1Guay, es todo tuyo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B04, map_39_state_03_08ED4B04, 0x08ED4B10, 0x08F0404C)
  MOVE_OBJECT(2, 0, 0, 0)
  MOVE_OBJECT(1, 3, 12, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  WALK_OBJECT_Y(0, 56)
  WALK_OBJECT_X(0, 56)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_Y(13, 64)
  WALK_OBJECT_X(13, 64)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 64)
  WALK_OBJECT_X(14, 48)
  MOVE_OBJECT(14, 2, 0, 0)
  DUEL(70)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B10, map_39_state_03_08ED4B10, 0x08ED4B1C, 0x08F04040)
  SET_MAP_MUSIC(248)
  PLAY_MUSIC(248)
  PORTRAIT(PORTRAIT_STRINGS, 0, 8)
  LANGUAGE_TEXT(0, "...Lost...\n\n")
  LANGUAGE_TEXT(1, "... Perdu...\n\n")
  LANGUAGE_TEXT(2, "... Verloren...\n\n")
  LANGUAGE_TEXT(3, "... Ho perso...\n\n")
  LANGUAGE_TEXT(4, "... Perdido...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 88)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 128)
  MOVE_OBJECT(1, 1, 4, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, 1, 8)
  LANGUAGE_TEXT(0, "Yes! Thank you!\n\nBut what brings you here?\n\n")
  LANGUAGE_TEXT(1, "Ah, oui !\nSauv\xe9e enfin !\n\nMais qu'est-ce qui\nvous am\xe8ne jusqu'ici ?\n\n")
  LANGUAGE_TEXT(2, "Ja, endlich!\nEndlich gerettet!\n\nAber sagt, was f\xfchrt\neuch hierher?\n\n")
  LANGUAGE_TEXT(3, "Uauh, s\xec!\nSono salvo, finalmente!\n\nMa ditemi, cosa\nvi porta qui?\n\n")
  LANGUAGE_TEXT(4, "\xa1Uf, s\xed!\n\xa1Al fin, salvado!\n\nPero decid, \xbfqu\xe9 os\ntrae por aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B1C, map_39_state_03_08ED4B1C, 0x08ED4B28, 0x08ED4B34)
  PLAY_MUSIC(702)
  PORTRAIT(PORTRAIT_MAKO, 0, 8)
  LANGUAGE_TEXT(0, "I see. What a horrible\nsituation!\n\nThis is why I've been\nsensing trouble among the\n\nwaves.\n\nMy instincts tell me\nsomething more sinister is\n\nin the works.\n\n")
  LANGUAGE_TEXT(1, "Je vois, je vois.\nVoil\xe0 ce qui se passe.\n\nEst-ce qu'il y aurait un\nlien avec la mer en furie ?\n\nJe crois que \xe7a cache\nquelque chose d'autre.\n\n")
  LANGUAGE_TEXT(2, "Verstehe. So ist das\nalso. K\xf6nnte es etwas\n\nmit dem aufgew\xfchlten\nMeer zu tun haben?\n\nIch glaube nicht, dass\ndas alles ist.\n\n")
  LANGUAGE_TEXT(3, "Ho capito. Cos\xec sta\nsuccedendo questo.\n\nAvr\xe0 a che fare con il mare\nagitato? C'\xe8 sempre\n\nqualcosa di pi\xf9 al di\nl\xe0 di ci\xf2 che si vede.\n\n")
  LANGUAGE_TEXT(4, "Ya veo, ya veo.\nEso es lo que est\xe1 pasando.\n\n\xbfPodr\xeda tener que ver con\nlos mares turbulentos?\n\nNo creo que eso\nsea todo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, 0, 8)
  LANGUAGE_TEXT(0, "Anyways, I'm going to the\nTown of Domino.\n\n")
  LANGUAGE_TEXT(1, "Bon, OK, je pars\npour Domino.\n\n")
  LANGUAGE_TEXT(2, "Ich mache mich jetzt jeden-\nfalls auf nach Domino.\n\n")
  LANGUAGE_TEXT(3, "Comunque, d'accordo,\nverr\xf2 a Domino.\n\n")
  LANGUAGE_TEXT(4, "De todos modos, bien,\nir\xe9 a Domino.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 72)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  WALK_OBJECT_Y(1, 68)
  WALK_OBJECT_X(1, 128)
  SET_FLAG(86)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B28, map_39_state_03_08ED4B28, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Let's go find another ally!\n\n")
  LANGUAGE_TEXT(1, "Essayons de trouver\nun autre alli\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Suchen wir noch einen\nVerb\xfcndeten!\n\n")
  LANGUAGE_TEXT(3, "Andiamo a trovare\nun altro alleato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Busquemos otro aliado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B34, map_39_state_03_08ED4B34, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Okay! Let's also get back to\nthe Town of Domino!\n\n")
  LANGUAGE_TEXT(1, "OK ! Retournons aussi\n\xe0 Domino !\n\n")
  LANGUAGE_TEXT(2, "Okay! Lasst uns auch\nnach Domino heimkehren!\n\n")
  LANGUAGE_TEXT(3, "Okay! Torniamo anche\nnoi a Domino!\n\n")
  LANGUAGE_TEXT(4, "\xa1De acuerdo, volvamos\na Domino tambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AF8, map_39_state_03_08ED4AF8, 0x08ED4B04, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, 0, 8)
  LANGUAGE_TEXT(0, "Please reconsider! You're\nthe only one I trust.\n\n")
  LANGUAGE_TEXT(1, "Allez, sois gentil !\nRends-moi service !\n\n")
  LANGUAGE_TEXT(2, "Sei doch nicht so!\nTu mir den Gefallen!\n\n")
  LANGUAGE_TEXT(3, "No, non puoi esserlo!\nFammi questo favore!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ahora no seas as\xed!\n\xa1Hazme un favor!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AC8, map_39_state_03_08ED4AC8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_STRINGS, 0, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
