#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_13: map 12 state 13 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F174, map_12_state_13_08E6F174, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  LOAD_SPRITE(2, SPRITE_MOKUBA)
  LOAD_SPRITE(3, SPRITE_BIG_FIVE)
  LOAD_SPRITE(4, SPRITE_BIG_FIVE)
  LOAD_SPRITE(5, SPRITE_BIG_FIVE)
  LOAD_SPRITE(6, SPRITE_BIG_FIVE)
  LOAD_SPRITE(7, SPRITE_BIG_FIVE)
  LOAD_SPRITE(8, SPRITE_SERENITY)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Roland, you played a good Kaibaman.")
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Thank you, Master Mokuba.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Everyone, good work! I'm counting on you again for",
      "the next show!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_3 | OBJECT_4 | OBJECT_5 | OBJECT_6 | OBJECT_7)
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TEXT("Men, he did give us a job...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TEXT("But we were once The Big Five...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TEXT(
      "Is this a job fit for the former KaibaCorp Board of",
      "Directors?"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_3 | OBJECT_4 | OBJECT_5 | OBJECT_6 | OBJECT_7)
  DELAY(16)
  TEXT(
      "No! It's not!",
      "I don't want a job entertaining runts!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(4)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(6, 0)
  MOVE_OBJECT(6, DIRECTION_LEFT, 16, 0)
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(7, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TEXT(
      "Wh-where are you going, Big {BYTE_8253}?",
      "Wait for me!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, DIRECTION_LEFT, 16, 0)
  DELAY(16)
  TEXT("Don't leave me alone!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, DIRECTION_LEFT, 16, 0)
  DELAY(32)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(7, DIRECTION_UP, 0, 0)
  DELAY(32)
  TEXT(
      "W-we should go, too.",
      "Y-yes we should.",
      "Wait for us!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(5, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 16, 0)
  WALK_OBJECT_X(7, 0)
  MOVE_OBJECT(7, DIRECTION_LEFT, 16, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO,
      "The Big Five are a buncha weirdoes. Man, I'd hate to",
      "be them."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, DIRECTION_UP, 2, 0)
  DELAY(16)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Joey, Yugi, {PLAYER}, wasn't that fun?")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Let's all watch the show again sometime!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(8, 0)
  SHOW_OBJECT(8, 128, 96, 0, 0, 0)
  SET_FLAG(EVENT_FLAG_WATCHED_THE_KAIBAMAN_SHOW)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1B0, map_12_state_13_08E6F1B0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I was the one wearing the Kaibaman costume.",
      "But that's top secret!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1BC, map_12_state_13_08E6F1BC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "There's no way you can beat Kaibaman.",
      "You shouldn't even try."
  )
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F198, map_12_state_13_08E6F198, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "The Kaibaman show is really popular.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1A4, map_12_state_13_08E6F1A4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I bet you think you're a better duelist because you",
      "saw the show.",
      "But you're really not, so you should forget about",
      "dueling.",
      "You'll only get humiliated."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
