#include "event_macros.h"
#include "overworld.h"

/* map_32_state_09: map 32 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08EB9144, map_32_state_09_08EB9144, 0x08EB9150, 0x08EB9168)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("You'll proceed no further\nwithout defeating me!\n\n")
  DUEL(82)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9150, map_32_state_09_08EB9150, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_242)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Most impressive.\nYou deserve a card.\n\nTake this Curse of Dragon.\n\n")
  ADD_CARD(39)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Your path is clear.\nAdvance.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN5)
  FALLTHROUGH()
END_EVENT_SCRIPT()
