#include "event_macros.h"

/* map_33_state_01: map 33 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EBEACC, map_33_state_01_08EBEACC, 0x08EBEAE4, 0x08EBEB20)
  CHECK_FLAG(19)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEAE4, map_33_state_01_08EBEAE4, 0x08EBEAF0, 0x08F0404C)
  PLAY_MUSIC(402)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "Those drawn by the\nMillennium Item...\n\nProve your worth at this\nfortress of the ancients!\n\n")
  LANGUAGE_TEXT(1, "Ceux qui sont attir\xe9s par\nl'Objet du mill\xe9nium...\n\nMontrez-vous dignes d'eux\ndans cette forteresse\n\nde nos anc\xeatres !\n\n")
  LANGUAGE_TEXT(2, "Wer vom Millenniums-\ngegenstand angezogen\n\nwird... Beweise an dieser\nantiken Festung,\n\ndass er w\xfcrdig ist!\n\n")
  LANGUAGE_TEXT(3, "Coloro che sono attratti\ndall'Oggetto Millenario...\n\nProvino di esserne degni\npresso questa antica\n\nfortezza!\n\n")
  LANGUAGE_TEXT(4, "Aquellos atra\xeddos por\nel Objeto del Milenio...\n\n\xa1Que demuestren su val\xeda\nen esta fortaleza de los\n\nantepasados!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 64)
  WALK_OBJECT_X(0, 60)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 74)
  WALK_OBJECT_X(13, 66)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 74)
  WALK_OBJECT_X(14, 54)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  DUEL(42)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEAF0, map_33_state_01_08EBEAF0, 0x08EBEAFC, 0x08EBEB08)
  PLAY_MUSIC(402)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "Impressive. Take this item.\n\n")
  LANGUAGE_TEXT(1, "Impressionnant.\nPrends cet objet.\n\n")
  LANGUAGE_TEXT(2, "Beeindruckend.\nNimm das hier.\n\n")
  LANGUAGE_TEXT(3, "Davvero notevole.\nPrendi questo oggetto.\n\n")
  LANGUAGE_TEXT(4, "Impresionante.\nToma este objeto.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 60, 40, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(278)
  SLIDE_OBJECT(3, 0, 18)
  DELAY(8)
  PLAY_MUSIC(279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(280)
  SHOW_OBJECT(2, 60, 54, 0, 1, 0)
  DELAY(16)
  PORTRAIT(5, 1, 0)
  LANGUAGE_TEXT(0, "Oh! This is unbelievable!\n\nWho is it? Who's tapping\ninto my memory?\n\n")
  LANGUAGE_TEXT(1, "Oh !\nIncroyable !\n\nQui c'est ? Qui s'introduit\ndans ma m\xe9moire ?\n\n")
  LANGUAGE_TEXT(2, "Oh! Es ist unglaublich!\nWer ist da?\n\nWer interessiert sich f\xfcr\nmeine Erinnerungen?\n\n")
  LANGUAGE_TEXT(3, "Oh, \xe8 incredibile!\nChi \xe8?\n\nChi \xe8 che si intromette\nnella mia memoria?\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh!\n\xa1Es incre\xedble!\n\n\xbfQui\xe9n es? \xbfQui\xe9n enreda\ncon mi memoria?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 2, 0)
  LANGUAGE_TEXT(0, "W-what? It's Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? C'est\nSol Chevalsky !\n\n")
  LANGUAGE_TEXT(2, "W-was?\nEs ist Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(3, "C-cosa?\n\xc8 Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9?\n\xa1Es Sol Chevalsky!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(1, 6, 0)
  LANGUAGE_TEXT(0, "There's something wrong!\n\nPegasus is the one with the\nMillennium Eye...\n\n{PLAYER}, could this be...\n\n")
  LANGUAGE_TEXT(1, "Quelque chose ne\ntourne pas rond !\n\nL'\u0152il du mill\xe9nium\nappartenait \xe0 Pegasus...\n\n{PLAYER}, est-ce\nque \xe7a pourrait \xeatre...\n\n")
  LANGUAGE_TEXT(2, "Da stimmt etwas nicht!\n\nPegasus besa\xdf das\nMillenniumsauge...\n\n{PLAYER}, k\xf6nnte dies...\n\n")
  LANGUAGE_TEXT(3, "C'\xe8 qualcosa che non va!\n\nPegasus era il detentore\ndell'Occhio Millenario...\n\n{PLAYER}, non\nsar\xe0 mica...\n\n")
  LANGUAGE_TEXT(4, "\xa1Hay algo raro!\n\nPegasus era el tenedor\ndel Ojo del Milenio...\n\n{PLAYER}, podr\xeda\nesto ser...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}It's Pegasus!\nIt's Sol Chevalsky!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}C'est Pegasus !\nC'est Sol Chevalsky !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Es ist Pegasus!\nEs ist Sol Chevalsky!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}\xc8 Pegasus!\n\xc8 Sol Chevalsky!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1Es Pegasus!\n\xa1Es Sol Chevalsky!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEAFC, map_33_state_01_08EBEAFC, 0x08EBEB14, 0x08F04040)
  PORTRAIT(5, 0, 0)
  LANGUAGE_TEXT(0, "Pegasus... That name brings\nback memories.\n\nBut my name is now Sol\nChevalsky.\n\nI have been, shall we say,\nreborn.\n\n")
  LANGUAGE_TEXT(1, "Pegasus... Ce nom\nme rend nostalgique.\n\nMaintenant, je m'appelle\nSol Chevalsky.\n\nJe suis n\xe9 \xe0 nouveau.\n\n")
  LANGUAGE_TEXT(2, "Pegasus... Ein Name, der\nmich melancholisch macht.\n\nAber jetzt hei\xdfe ich Sol\nChevalsky.\n\nIch bin wiedergeboren.\n\n")
  LANGUAGE_TEXT(3, "Pegasus... Quel nome\nmi ricolma di nostalgia.\n\nMa ora il mio nome \xe8\nSol Chevalsky.\n\nSono rinato.\n\n")
  LANGUAGE_TEXT(4, "Pegasus... Ese nombre\nme llena de nostalgia.\n\nPero mi nombre es\nSol Chevalsky ahora.\n\nHe renacido.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB14, map_33_state_01_08EBEB14, 0x08F04250, 0x08F04040)
  LANGUAGE_TEXT(0, "I see that you are making\nexcellent progress through\n\nmy game.\n\nI suggest you keep\nplaying... as if you had a\n\nchoice!\n\nI know you still have\nquestions of my\n\nintentions...\n\nMaybe they will be answered\nwhen you reach me.\n\nHahahaha...\n\n")
  LANGUAGE_TEXT(1, "Je vois que tu fais des\nprogr\xe8s dans mon jeu.\n\nTu n'as pas d'autre choix :\ntu dois continuer \xe0 jouer.\n\nTa curiosit\xe9\nsera satisfaite...\n\nQuand tu m'auras retrouv\xe9.\nFufufu...\n\n")
  LANGUAGE_TEXT(2, "Wie ich sehe, machst du\ndich gut in meinem Spiel.\n\nDu musst weiterspielen -\ndu hast keine Wahl.\n\nDeine Neugier wird befrie-\ndigt werden...\n\nWenn du mich erreichst.\nFufufu...\n\n")
  LANGUAGE_TEXT(3, "Vedo che stai facendo\ngrandi progressi nel\n\nmio gioco.\n\nNon hai altra scelta:\ncontinua a giocare.\n\nLa tua curiosit\xe0 sar\xe0\nsoddisfatta...\n\nQuando mi avrai\nraggiunto. Ihihih...\n\n")
  LANGUAGE_TEXT(4, "Veo que progresas\nmucho en mi juego.\n\nNo tienes otra alterna-\ntiva que seguir jugando.\n\nTu curiosidad ser\xe1\nsatisfecha...\n\nCuando me alcances.\nFufufu...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(281)
  OBJECT_EFFECT(4, 2)
  DELAY(64)
  PORTRAIT(1, 6, 0)
  LANGUAGE_TEXT(0, "Sol Chevalsky is Pegasus...\n\nLet's get back to Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Sol Chevalsky \xe9tait\nPegasus...\n\nRetournons voir Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Sol Chevalsky war Pegasus...\n\nKehren wir zu Ishizu zur\xfcck.\n\n")
  LANGUAGE_TEXT(3, "Sol Chevalsky era Pegasus...\n\nTorniamo da Ishizu.\n\n")
  LANGUAGE_TEXT(4, "Sol Chevalsky era Pegasus...\n\nVolvamos con Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(19)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB08, map_33_state_01_08EBEB08, 0x08EBEB14, 0x08F04040)
  PORTRAIT(5, 0, 0)
  LANGUAGE_TEXT(0, "Ah, you are very insightful,\nmy boy.\n\nYou are exactly right. I am\nSol Chevalsky.\n\nThe name Pegasus is in the\npast. It no longer has\n\nanything to do with me.\n\n")
  LANGUAGE_TEXT(1, "Ah, tu as une \xe2me\npure, mon petit.\n\nTu as raison : je\nsuis Sol Chevalsky.\n\nJe me suis d\xe9barrass\xe9\ndu nom de Pegasus...\n\n")
  LANGUAGE_TEXT(2, "Ah, du bist reinen Herzens,\nmein Junge.\n\nDu hast nat\xfcrlich Recht,\nich bin Sol Chevalsky.\n\nIch habe den Namen Pegasus\nabgelegt...\n\n")
  LANGUAGE_TEXT(3, "Eh, ragazzo mio, tu\nhai un animo puro.\n\nHai proprio ragione,\nsono Sol Chevalsky.\n\nMi sono liberato del\nnome Pegasus...\n\n")
  LANGUAGE_TEXT(4, "Ah, tienes una mente\npura, hijo m\xedo.\n\nTienes raz\xf3n, soy\nSol Chevalsky.\n\nHe prescindido del\nnombre Pegasus...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB20, map_33_state_01_08EBEB20, 0x08F04040, 0x08F04040)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "Millennium Items are\nbelieved to attract each\n\nother.\n\nThe Millennium Eye will lead\nyou to the next one.\n\n")
  LANGUAGE_TEXT(1, "Il para\xeet que les Objets du\nmill\xe9nium s'attirent les\n\nuns les autres. L'\u0152il du\nmill\xe9nium va te conduire\n\nau prochain objet.\n\n")
  LANGUAGE_TEXT(2, "Millenniumsgegenst\xe4nde\nziehen sich angeblich an.\n\nDas Millenniumsauge\nwird dich zum n\xe4chsten\n\nGegenstand f\xfchren.\n\n")
  LANGUAGE_TEXT(3, "Si dice che gli Oggetti\nMillenari si attraggano a\n\nvicenda. L'Occhio\nMillenario ti condurr\xe0\n\nal prossimo oggetto.\n\n")
  LANGUAGE_TEXT(4, "Se dice que los Objetos del\nMilenio se atraen entre s\xed.\n\nEl Ojo del Milenio te\nllevar\xe1 al siguiente\n\nobjeto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEAD8, map_33_state_01_08EBEAD8, 0x08EBEAE4, 0x08EBEB2C)
  CHECK_FLAG(19)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB2C, map_33_state_01_08EBEB2C, 0x08F04040, 0x08F04040)
  PORTRAIT(46, 0, 8)
  LANGUAGE_TEXT(0, "You are only allowed to duel\nme once.\n\nDid you not have to leave\nimmediately?\n\n")
  LANGUAGE_TEXT(1, "Je te donne\nune seule chance\n\nde m'affronter en duel,\npas plus.\n\nTu ne devais pas partir\ntout de suite ?\n\n")
  LANGUAGE_TEXT(2, "Du hast nur eine Chance,\num dich mit mir zu\n\nduellieren. Das ist alles.\n\nMusst du nicht sofort\ngehen?\n\n")
  LANGUAGE_TEXT(3, "Hai una sola possibilit\xe0\ndi duellare con me,\n\nuna e basta. Non dovevi\npartire subito?\n\n")
  LANGUAGE_TEXT(4, "Tienes una oportunidad\nde retarme; nada m\xe1s.\n\n\xbfNo ten\xedas que marchar\nde inmediato?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
