#include "event_macros.h"
#include "overworld.h"

/* map_02_state_04: map 2 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08E47944, map_02_state_04_08E47944, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls weren't that\nscary, were they?\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls n'\xe9taient\npas si m\xe9chants, si ?\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls waren doch\nnicht so Angst erregend,\n\noder?\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls non erano poi\ncos\xec terrificanti, vero?\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls no\neran tan temibles, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47950, map_02_state_04_08E47950, 0x08E4795C, 0x08E47974)
  CHECK_FLAG(116)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4795C, map_02_state_04_08E4795C, 0x08E47968, 0x08F0404C)
  LANGUAGE_TEXT(0, "You're challenging me to a\nduel?\n\nOkay, sure.\nI'll take you on.\n\n")
  LANGUAGE_TEXT(1, "Tu me d\xe9fie en duel ?\n\nOK, pas de probl\xe8me.\nBattons-nous.\n\n")
  LANGUAGE_TEXT(2, "Du forderst mich zu\neinem Duell heraus?\n\nOkay, warum nicht.\nIch nehme an.\n\n")
  LANGUAGE_TEXT(3, "Mi stai sfidando a duello?\nVa bene, certo. Ci sto.\n\n")
  LANGUAGE_TEXT(4, "\xbfMe retas a un duelo?\n\nVale, claro.\nEn guardia.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(87)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47968, map_02_state_04_08E47968, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Uh... I guess I'm just not\nconcentrating today.\n\n")
  LANGUAGE_TEXT(1, "Mmm...\nAujourd'hui,\n\nje ne suis pas\nassez concentr\xe9.\n\n")
  LANGUAGE_TEXT(2, "\xc4h... Ich glaube, ich bin\nheute etwas zerstreut.\n\n")
  LANGUAGE_TEXT(3, "Uh... Mi sa che oggi sono\npoco concentrato.\n\n")
  LANGUAGE_TEXT(4, "Uh... Creo que\nhoy no es mi d\xeda.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(116)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47974, map_02_state_04_08E47974, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm not feeling good today.\nNo thanks.\n\n")
  LANGUAGE_TEXT(1, "Je ne me sens pas\ntr\xe8s bien aujourd'hui.\n\nNon merci.\n\n")
  LANGUAGE_TEXT(2, "Ich f\xfchle mich heute nicht\nganz wohl. Lieber nicht.\n\n")
  LANGUAGE_TEXT(3, "No, grazie. Oggi non\nmi sento in gran forma.\n\n")
  LANGUAGE_TEXT(4, "No me encuentro muy all\xe1\nhoy. No, gracias.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47980, map_02_state_04_08E47980, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Zompire is the awesomest!\n\n")
  LANGUAGE_TEXT(1, "Zompire est cool.\n\n")
  LANGUAGE_TEXT(2, "Zompire ist cool.\n\n")
  LANGUAGE_TEXT(3, "Zompire \xe8 forte.\n\n")
  LANGUAGE_TEXT(4, "Zompire es chachi.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4798C, map_02_state_04_08E4798C, 0x08E47998, 0x08E479B0)
  CHECK_FLAG(117)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47998, map_02_state_04_08E47998, 0x08E479A4, 0x08F0404C)
  LANGUAGE_TEXT(0, "A real hero doesn't run from\na fight.\n\nThat's why I'm going to stay\nand duel because that's\n\nwhat Zompire would do!\n\n")
  LANGUAGE_TEXT(1, "Pour \xeatre\nun vrai h\xe9ros,\n\nil ne faut jamais\nrefuser de se battre.\n\nJe vais faire de mon\nmieux, comme Zompire !\n\n")
  LANGUAGE_TEXT(2, "Ein wahrer Held scheut\nkeinen Kampf.\n\nIch werde mein Bestes geben,\nwie es Zompire tun w\xfcrde!\n\n")
  LANGUAGE_TEXT(3, "Per diventare veri eroi, non\nbisogna evitare lo scontro.\n\nFar\xf2 del mio meglio, come\nfarebbe anche Zompire!\n\n")
  LANGUAGE_TEXT(4, "Uno no debe evadir la\nlucha para ser un h\xe9roe\n\nde verdad.\n\n\xa1Lo har\xe9 lo mejor que pueda,\ncomo lo har\xeda Zompire!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(88)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E479A4, map_02_state_04_08E479A4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "I guess I'll never be a true\nhero...\n\nNo! I have to push those\nnegative thoughts out of my\n\nhead!\n\n")
  LANGUAGE_TEXT(1, "Eh bien, je ne serais\njamais un vrai h\xe9ros...\n\nNon... Je ne vais\npas abandonner !\n\n")
  LANGUAGE_TEXT(2, "Ich werde wohl nie ein\nechter Held...\n\nNein...\nIch werde nicht aufgeben!\n\n")
  LANGUAGE_TEXT(3, "Immagino che non\ndiventer\xf2 mai un vero\n\neroe... Per\xf2, no...\nNon moller\xf2!\n\n")
  LANGUAGE_TEXT(4, "Creo que nunca ser\xe9 un\nh\xe9roe de verdad...\n\nNo...\n\xa1No abandonar\xe9!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(117)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E479B0, map_02_state_04_08E479B0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Only hard work will turn me\nfrom a zero into a hero.\n\nThat's why I have to keep\ntrying.\n\nPlease duel with me again in\nthe future.\n\n")
  LANGUAGE_TEXT(1, "Sans effort, on ne peut\npas devenir un h\xe9ros.\n\nJe vais continuer\n\xe0 essayer.\n\nA l'avenir, bats-toi\n\xe0 nouveau contre moi.\n\n")
  LANGUAGE_TEXT(2, "Ohne Schwei\xdf wird niemand\nein Held.\n\nIch werde es weiter\nversuchen.\n\nBitte duelliere dich irgend-\nwann noch einmal mit mir.\n\n")
  LANGUAGE_TEXT(3, "Non si diventa eroi\nsenza alcuno sforzo.\n\nContinuer\xf2 a provarci.\n\nIn futuro, duella di\nnuovo con me.\n\n")
  LANGUAGE_TEXT(4, "Nadie puede ser un h\xe9roe\nsin esforzarse.\n\nVoy a seguir intent\xe1ndolo.\n\nPor favor, lucha conmigo\nm\xe1s adelante.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E479BC, map_02_state_04_08E479BC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, 0, 8)
  LANGUAGE_TEXT(0, "The Town of Domino is now\nsafe.\n\nBut you still have something\nto do, don't you?\n\nI'm going back to the cruise\nship.\n\nDon't give up, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Domino est sauv\xe9e\nmaintenant.\n\nMais il te reste encore\nune chose \xe0 faire, non ?\n\nJe retourne au paquebot\nde croisi\xe8re.\n\nN'abandonne pas,\n{PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Domino ist jetzt sicher.\n\nAber du hast doch noch\neine Aufgabe, oder?\n\nIch gehe zur\xfcck aufs\nKreuzfahrtschiff.\n\nGib nicht auf, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Ora Domino \xe8 al sicuro.\n\nMa hai ancora qualcosa\nda fare, non \xe8 cos\xec?\n\nIo me ne torno alla\nnave da crociera.\n\nNon mollare, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "Domino est\xe1 segura ahora.\n\nPero todav\xeda tienes\nalgo que hacer, \xbfno?\n\nVuelvo al crucero.\n\n\xa1No abandones, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(3, 39)
  WALK_OBJECT_X(3, 0)
  SET_OBJECT_POSITION(3, 128, 96, 0)
  SET_FLAG(118)
  SET_MAP_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()
