#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_22_state_05: map 22 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CB40, map_22_state_05_08E8CB40, 0x08E8CB4C, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_SETO)
  LOAD_SPRITE(2, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(3, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(4, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(5, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(6, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(7, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(8, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(9, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(10, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(11, SPRITE_EGYPT_EXHIBITION_VISITOR)
  CHECK_FLAG(EVENT_FLAG_SAW_KAIBA_DEFEAT_A_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB4C, map_22_state_05_08E8CB4C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO, "I summon Blue-Eyes White Dragon!")
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO, "White Lightning!")
  PLAY_MUSIC(MUSIC_338)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_ATTACK_DOWN)
  DELAY(16)
  PLAY_MUSIC(MUSIC_284)
  SLIDE_OBJECT(2, 0, 16)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  DELAY(16)
  WALK_OBJECT_X(3, 64)
  MOVE_OBJECT(3, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "What's with these Neo Ghoul scrubs!",
      "There's no end to them!"
  )
  SET_FLAG(EVENT_FLAG_SAW_KAIBA_DEFEAT_A_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB58, map_22_state_05_08E8CB58, 0x08E8CB70, 0x08E8CB88)
  CHECK_FLAG(EVENT_FLAG_KAIBA_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB70, map_22_state_05_08E8CB70, 0x08E8CB7C, EVENT_NOP)
  WALK_OBJECT_X(0, 56)
  WALK_OBJECT_Y(0, 20)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(14, 46)
  WALK_OBJECT_Y(14, 15)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(13, 46)
  WALK_OBJECT_Y(13, 26)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Am I here to rescue Ishizu?",
      "Heh, that's your business, not mine.",
      "I'm only here because I need to resurrect Obelisk the",
      "Tormentor.",
      "I don't know what kind of trick you pulled...",
      "But no one had no right to turn my card into stone!",
      "It's clear Ishizu's somehow involved...",
      "And I want to find out how!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB7C, map_22_state_05_08E8CB7C, EVENT_NOP, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_UP, 4, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(8)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "You Neo Ghouls haven't had enough yet?",
      "Fine! I'll crush you until you beg me for mercy!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "What are you losers still doing here?",
      "Go and find your precious Ishizu!"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 4, 0)
  SET_FLAG(EVENT_FLAG_KAIBA_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB88, map_22_state_05_08E8CB88, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "What are you losers still doing here?",
      "Go and find your precious Ishizu!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB64, map_22_state_05_08E8CB64, 0x08E8CB70, 0x08E8CB88)
  CHECK_FLAG(EVENT_FLAG_KAIBA_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB94, map_22_state_05_08E8CB94, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "If I take down Kaiba, I'll be promoted! Hihihi...")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBA0, map_22_state_05_08E8CBA0, EVENT_NOP, EVENT_NOP)
  TEXT(
      "I was enjoying the Egypt Exhibition...",
      "Until all chaos broke out."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBAC, map_22_state_05_08E8CBAC, EVENT_NOP, EVENT_NOP)
  TEXT(
      "I'm not a duelist.",
      "That's why they left me alone."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
