#include "event_macros.h"
#include "overworld.h"

/* map_26_state_01: map 26 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3B90, map_26_state_01_08EA3B90, 0x08EA3B9C, 0x08F04040)
  PLAY_MUSIC(32)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Mai, my darling!\n\nPlease marry me! Be mine,\nMai Valentine!\n\n")
  LANGUAGE_TEXT(1, "Mai, ma ch\xe9rie !\n\nEpouse-moi, s'il te pla\xeet !\n\nDeviens ma femme,\nMai Valentine !\n\n")
  LANGUAGE_TEXT(2, "Meine geliebte Mai!\n\nHeirate mich, bitte! Werde\ndie meine, Mai Valentine!\n\n")
  LANGUAGE_TEXT(3, "Mia cara Mai!\n\nSposami, ti prego! Mai\nValentine, non vuoi\n\nessere mia?\n\n")
  LANGUAGE_TEXT(4, "\xa1Mi querida Mai!\n\n\xa1C\xe1sate conmigo!\n\xa1S\xe9 m\xeda, Mai Valentine!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Stop following me!\n\nI already told you, I'll\nonly marry if you beat me\n\nin a duel.\n\n")
  LANGUAGE_TEXT(1, "Arr\xeate de me harceler.\nJe te l'ai d\xe9j\xe0 dit :\n\n\xe0 condition que tu\nme battes en duel.\n\n")
  LANGUAGE_TEXT(2, "Lass mich in Ruhe.\n\nIch sagte es doch schon:\nNur wenn du mich in einem\n\nDuell besiegst.\n\n")
  LANGUAGE_TEXT(3, "Smettila di perseguitarmi.\n\nTi ho detto che lo far\xf2 solo\nse mi batterai in duello.\n\n")
  LANGUAGE_TEXT(4, "Deja de dar la lata.\n\nTe lo dije, s\xf3lo si me\nvenc\xedas en duelo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Okay!\n\nThen today's the day you'll\nbe marching with me to the\n\nchapel!\n\n")
  LANGUAGE_TEXT(1, "OK !\nAujourd'hui, tu vas\n\ndevenir ma femme,\nMai Valentine !\n\n")
  LANGUAGE_TEXT(2, "Okay! Heute ist der Tag,\n\nan dem du die meine wirst,\nMai Valentine!\n\n")
  LANGUAGE_TEXT(3, "Ci sto!\n\nOggi sarai mia, Mai\nValentine!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale!\n\n\xa1Hoy ser\xe1s m\xeda,\nMai Valentine!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3B9C, map_26_state_01_08EA3B9C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Harpie Lady Sisters!\n\n")
  LANGUAGE_TEXT(1, "Les Harpies !\n\n")
  LANGUAGE_TEXT(2, "Fl\xfcgel-Ladys!\n\n")
  LANGUAGE_TEXT(3, "Arpie Splendenti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Damas de Harpie!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 12)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(1, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(2, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(3, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(4, "\xa1Harpies' Triangle Ecstasy!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(341)
  COMMAND_7C_ARG(8, 13)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(2, 1, 16)
  DELAY(32)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Urrrrggggh..\n\nM-my, my, my Mai, you are\nexcellent, as always!\n\nBut today, I'm better than\nusual!\n\nI've constructed a new\nperfect absolute ultimate\n\ndeck filled with special\nunique powerful rare cards!\n\nLet's duel again, my\nValentine!\n\n")
  LANGUAGE_TEXT(1, "Urrrrggggh..\n\nM-ma, ma, ma Mai Valentine,\ntu es si douce !\n\nMais aujourd'hui, je\nme sens diff\xe9rent !\n\nJ'ai le Deck le plus\npuissant avec des cartes\n\nrares ! Donne-moi une autre\nchance, Mai Valentine !\n\n")
  LANGUAGE_TEXT(2, "Arrrrggggh..\n\nOh je oh je oh je, Mai\nValentine, du bist so gut!\n\nAber heute bin ich nicht\nich selbst - oh nein!\n\nIch besitze das ultimative\nDeck mit besonderen,\n\nseltenen Karten!\n\nGib mir bitte noch eine\nChance, Mai Valentine!\n\n")
  LANGUAGE_TEXT(3, "Urgggghh...\n\nMia, mia cara Mai Valentine,\nsei cos\xec buona!\n\nMa oggi, non sono\nin vena, proprio no!\n\nHo il super deck con\ncarte rare speciali!\n\nTi prego, dammi un'altra\npossibilit\xe0, Mai Valentine!\n\n")
  LANGUAGE_TEXT(4, "Urrrrggggh.\n\nM-mi, mi, mi Mai Valentine,\n\xa1eres tan buena!\n\nPero hoy yo no soy el\nde costumbre, \xa1o no!\n\nTengo la deck definitiva con\ncartas raras especiales.\n\n\xa1Por favor, dame otra\noportunidad, mi\n\nMai Valentine!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 16, 0)
  DELAY(16)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(15)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, 0)
  LANGUAGE_TEXT(0, "...I can't deal with this.\n\n")
  LANGUAGE_TEXT(1, "... Je ne peux plus faire\nface \xe0 cette situation.\n\n")
  LANGUAGE_TEXT(2, "... Das ist zu viel f\xfcr\nmich.\n\n")
  LANGUAGE_TEXT(3, "... Non ne posso pi\xf9.\n\n")
  LANGUAGE_TEXT(4, "... No puedo con esto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_SAW_JEAN_CLAUDE_MAGNUM_PROPOSE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BA8, map_26_state_01_08EA3BA8, 0x08EA3BD8, 0x08EA3BC0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BD8, map_26_state_01_08EA3BD8, 0x08EA3BE4, 0x08F04040)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(0, 31)
  WALK_OBJECT_X(0, 96)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Am I glad to see you! You\ncame just at the right\n\ntime.\n\nCan you duel that creep in\nmy place?\n\n")
  LANGUAGE_TEXT(1, "Tu arrives au bon moment.\n\nEt si tu te battais\n\xe0 ma place en duel\n\ncontre ce tar\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Du kommst gerade richtig.\n\nWarum duellierst du dich\nnicht f\xfcr mich mit diesem\n\nSchleimbeutel?\n\n")
  LANGUAGE_TEXT(3, "Sei arrivato al momento\ngiusto.\n\nChe ne dici di duellare con\nquell'idiota per me?\n\n")
  LANGUAGE_TEXT(4, "Llegaste en el\nmomento adecuado.\n\n\xbfPor qu\xe9 no luchas con\nese gusano por m\xed?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BE4, map_26_state_01_08EA3BE4, 0x08EA3BFC, 0x08EA3BF0)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BFC, map_26_state_01_08EA3BFC, 0x08EA3C08, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You're a real lifesaver!\n\n")
  LANGUAGE_TEXT(1, "Tu me sauves la vie !\n\n")
  LANGUAGE_TEXT(2, "Du bist ein wirklicher\nLebensretter.\n\n")
  LANGUAGE_TEXT(3, "Mi hai salvato la vita!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eres un salvavidas\nde verdad!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 8)
  LANGUAGE_TEXT(0, "Jean Claude Magnum! {PLAYER}\nwill take you on!\n\n")
  LANGUAGE_TEXT(1, "Magnum ! {PLAYER}\nva t'affronter en duel !\n\n")
  LANGUAGE_TEXT(2, "Magnum! {PLAYER}\nfordert dich zum Duell!\n\n")
  LANGUAGE_TEXT(3, "Magnum! {PLAYER}\nsi batter\xe0 con te!\n\n")
  LANGUAGE_TEXT(4, "\xa1Magnum!\n\xa1{PLAYER} te reta!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "It doesn't matter who you\nforce me to duel, Mai!\n\nWhen I win, you have to\nmarry me, as you promised!\n\n")
  LANGUAGE_TEXT(1, "Peu importe contre qui\nje me bats en duel, Mai !\n\nSi je gagne, je t'\xe9pouserai\ntout de suite !\n\n")
  LANGUAGE_TEXT(2, "Gegen wen ich auch\nspielen soll, Mai!\n\nWenn ich gewinne, geht\nes sofort zum Altar!\n\n")
  LANGUAGE_TEXT(3, "Non m'importa con chi\nmi farai duellare, Mai!\n\nSe vincer\xf2, ci sposeremo\nimmediatamente!\n\n")
  LANGUAGE_TEXT(4, "\xa1No importa con qui\xe9n\nme hagas luchar, Mai!\n\nSi gano, \xa1nos casaremos\nde inmediato!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 2)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "...You better not lose.\n\n")
  LANGUAGE_TEXT(1, "... Je t'en supplie,\nne perds pas.\n\n")
  LANGUAGE_TEXT(2, "... Bitte... verlier nicht.\n\n")
  LANGUAGE_TEXT(3, "... Non perdere, ti prego.\n\n")
  LANGUAGE_TEXT(4, "... Por favor, no pierdas.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 31)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  DUEL(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C08, map_26_state_01_08EA3C08, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  SET_FLAG(EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, 8)
  PLAY_MUSIC(15)
  LANGUAGE_TEXT(0, "How could this happen? I'm a\nbig time star! I never lose\n\nis any of my movies...\n\n")
  LANGUAGE_TEXT(1, "Je suis une star\nhollywoodienne !\n\nJe ne perds jamais...\n\n")
  LANGUAGE_TEXT(2, "Ich bin ein Hollywood-Star!\nIch verliere nie...\n\n")
  LANGUAGE_TEXT(3, "Sono una star di Hollywood!\nNon perdo mai...\n\n")
  LANGUAGE_TEXT(4, "\xa1Soy una estrella de\nHollywood! Nunca pierdo...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Thanks, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Merci, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Danke, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Grazie, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Gracias, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BF0, map_26_state_01_08EA3BF0, 0x08EA3BE4, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "How can you turn a request\ndown from a lady?\n\nWhat kind of gentleman are\nyou!\n\nQuit your whining and duel\nthat Hollywood halfwit!\n\n")
  LANGUAGE_TEXT(1, "Quoi, dire non \xe0 une fille\naussi belle que moi ?\n\nCa ne va pas ou quoi ?\n\nArr\xeate de te plaindre\net bats-toi en duel !\n\n")
  LANGUAGE_TEXT(2, "Du schl\xe4gst einem so h\xfcb-\nschen M\xe4dchen einen\n\nWunsch ab? Was ist los\nmit dir?\n\nH\xf6r auf, so wehleidig zu\nsein und befreie mich von\n\ndiesem ekligen Verfolger!\n\n")
  LANGUAGE_TEXT(3, "Non deluderai mica una\nragazza cos\xec bella?\n\nChe ti succede?\n\nSmettila di frignare e\nduella con quel seccatore!\n\n")
  LANGUAGE_TEXT(4, "\xbfPuedes rechazar a\nuna chica tan bella?\n\n\xbfQu\xe9 te pasa?\n\n\xa1Deja de quejarte y lucha\ncon ese acosador!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BC0, map_26_state_01_08EA3BC0, 0x08EA3C2C, 0x08EA3C38)
  CHECK_FLAG(EVENT_FLAG_RICH_SPOUSES_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C2C, map_26_state_01_08EA3C2C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You're searching for a\nMillennium Item?\n\nI don't know how I can help\nyou... Hmm...\n\nActually, there's mysterious\ncargo in the ship's hold.\n\nMaybe you'll find something\nthere.\n\nI'll leave the hold\nunlocked. Consider that as\n\na thank you for saving me.\n\n")
  LANGUAGE_TEXT(1, "Tu es \xe0 la recherche\nd'un Objet du mill\xe9nium ?\n\nJe ne m'y connais\npas trop.\n\nMais il y a une\ncargaison \xe9trange\n\n\xe0 bord du paquebot.\n\nPour te remercier, je vais\nlaisser les cales ouvertes.\n\n")
  LANGUAGE_TEXT(2, "Du suchst einen\nMillenniumsgegenstand?\n\nDar\xfcber wei\xdf ich nicht\nviel.\n\nAber im Frachtraum sind\nmysteri\xf6se Dinge.\n\nAls Dankesch\xf6n lasse ich den\nFrachtraum unverschlossen.\n\n")
  LANGUAGE_TEXT(3, "Cerchi un Oggetto\nMillenario?\n\nNon ne so granch\xe9.\nMa la stiva della nave\n\ncontiene un carico\nmisterioso. Lascer\xf2\n\nla stiva aperta, per\nsdebitarmi con te.\n\n")
  LANGUAGE_TEXT(4, "\xbfBuscas un\nObjeto del Milenio?\n\nNo s\xe9 mucho de eso.\n\nPero hay una carga\nmisteriosa en la\n\nbodega del barco.\n\nLa dejar\xe9 abierta\uff1b as\xed\nte doy las gracias.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_RICH_SPOUSES_MOVED_OUT_OF_THE_WAY)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 8, 0)
  WALK_OBJECT_Y(3, 76)
  MOVE_OBJECT(3, 1, 32, 1)
  MOVE_OBJECT(4, 1, 8, 0)
  WALK_OBJECT_Y(4, 76)
  MOVE_OBJECT(4, 1, 16, 1)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C38, map_26_state_01_08EA3C38, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You were looking for a\nMillennium Item, right?\n\nI hope you can find it in\nthe ship's hold.\n\n")
  LANGUAGE_TEXT(1, "Tu cherchais un\nObjet du mill\xe9nium ?\n\nJe crois que tu\npourras le trouver\n\ndans les cales\ndu paquebot.\n\n")
  LANGUAGE_TEXT(2, "Du suchst den\nMillenniumsgegenstand?\n\nIch hoffe, du findest ihn im\nFrachtraum.\n\n")
  LANGUAGE_TEXT(3, "Cercavi l'Oggetto\nMillenario?\n\nSpero che lo troverai\nnella stiva della nave.\n\n")
  LANGUAGE_TEXT(4, "\xbfBuscas el Objeto del\nMilenio?\n\nEspero que lo encuentres en\nla bodega del barco.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BB4, map_26_state_01_08EA3BB4, 0x08EA3BD8, 0x08EA3BCC)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3BCC, map_26_state_01_08EA3BCC, 0x08EA3C2C, 0x08EA3C44)
  CHECK_FLAG(EVENT_FLAG_RICH_SPOUSES_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C44, map_26_state_01_08EA3C44, 0x08EA3C50, 0x08EA3C68)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MAI)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C50, map_26_state_01_08EA3C50, 0x08EA3C5C, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My job is to duel guests on\nthis cruise.\n\nAnd believe me, I take my\njob seriously!\n\n")
  LANGUAGE_TEXT(1, "Mon boulot, c'est\nd'affronter en duel\n\nles invit\xe9s de la croisi\xe8re.\nMais je ne m'abaisse pas\n\nau niveau de mes\nadversaires.\n\n")
  LANGUAGE_TEXT(2, "Es ist mein Job, mich mit\nKreuzfahrtg\xe4sten zu\n\nduellieren.\n\nAber ich spiele nie auf dem\ntiefen Level meiner Gegner.\n\n")
  LANGUAGE_TEXT(3, "Il mio compito \xe8 duellare\ncon gli ospiti della\n\ncrociera. Ma non scendo\nmai al livello dei miei\n\navversari.\n\n")
  LANGUAGE_TEXT(4, "Mi trabajo es luchar con\nhu\xe9spedes del barco.\n\nPero nunca me pongo\nal nivel de mis oponentes.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(33)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C5C, map_26_state_01_08EA3C5C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  SET_FLAG(EVENT_FLAG_DEFEATED_MAI)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I lost.\n\n")
  LANGUAGE_TEXT(1, "OK, j'ai perdu.\n\n")
  LANGUAGE_TEXT(2, "Okay, ich habe verloren.\n\n")
  LANGUAGE_TEXT(3, "Okay, ho perso.\n\n")
  LANGUAGE_TEXT(4, "Vale, he perdido.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C68, map_26_state_01_08EA3C68, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I have to duel with the\nother guests.\n\nPlease challenge someone\nelse, alright?\n\n")
  LANGUAGE_TEXT(1, "Je dois aussi\nme battre en duel\n\ncontre d'autres invit\xe9s.\n\nTu veux bien d\xe9fier\nquelqu'un d'autre ?\n\n")
  LANGUAGE_TEXT(2, "Ich muss mich auch mit\nanderen G\xe4sten duellieren.\n\nBitte fordere einen anderen\nheraus, okay?\n\n")
  LANGUAGE_TEXT(3, "Devo duellare anche\ncon gli altri ospiti.\n\nSfida qualcun altro, okay?\n\n")
  LANGUAGE_TEXT(4, "Tengo que luchar con\notros hu\xe9spedes.\n\nPor favor, reta a\nalg\xfan otro, \xbfvale?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C14, map_26_state_01_08EA3C14, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I already hear wedding\nbells!!\n\n")
  LANGUAGE_TEXT(1, "Mai Valentine\nsera la mienne !\n\n")
  LANGUAGE_TEXT(2, "Mai Valentine wird mein\nwerden!\n\n")
  LANGUAGE_TEXT(3, "Mai Valentine sar\xe0 mia!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mai Valentine ser\xe1 m\xeda!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C20, map_26_state_01_08EA3C20, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't think so! This is\nnot the time!\n\nCan't you see that I'm\ntrying to propose?\n\n")
  LANGUAGE_TEXT(1, "Oh, non, non ! Il n'y\na pas de temps \xe0 perdre !\n\nTu ne comprends\ndonc pas ?\n\nC'est une demande\nen mariage !\n\n")
  LANGUAGE_TEXT(2, "Oh nein, nein!\nIch darf nicht verlieren!\n\nSiehst du denn nicht, dass\nich ihr einen Antrag\n\nmachen m\xf6chte?\n\n")
  LANGUAGE_TEXT(3, "Oh no, no! Non c'\xe8\ntempo da perdere!\n\nNon vedi? Sto cercando\ndi chiederle la mano!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, no, no!\n\xa1No hay tiempo que perder!\n\n\xbfNo te das cuenta?\n\n\xa1Intento proponerte\nmatrimonio!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C98, map_26_state_01_08EA3C98, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This ship's lady duelist is\nbeautiful, no?\n\n")
  LANGUAGE_TEXT(1, "La femme duelliste\nde ce paquebot\n\nest tr\xe8s belle,\nn'est-ce pas ?\n\n")
  LANGUAGE_TEXT(2, "Die Schiffsduellantin ist\neine echte Sch\xf6nheit,\n\nnicht wahr?\n\n")
  LANGUAGE_TEXT(3, "La duellante della nave\n\xe8 bella, no?\n\n")
  LANGUAGE_TEXT(4, "La duelista del barco\nes bella, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CA4, map_26_state_01_08EA3CA4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Sorry, chap.\n\nI prefer to watch.\n\n")
  LANGUAGE_TEXT(1, "D\xe9sol\xe9, mon ami.\n\nJe pr\xe9f\xe8re \xeatre un\nspectateur, c'est tout.\n\n")
  LANGUAGE_TEXT(2, "Tut mir Leid, mein Junge.\n\nIch schaue lieber zu.\n\n")
  LANGUAGE_TEXT(3, "Scusa, ragazzo mio.\n\nPreferisco guardare.\nTutto qui.\n\n")
  LANGUAGE_TEXT(4, "Lo siento, chico.\n\nPrefiero mirar, eso\nes todo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CB0, map_26_state_01_08EA3CB0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "My husband has a thing for\nfemale duelists.\n\n")
  LANGUAGE_TEXT(1, "Mon mari aime\nbien regarder\n\nles femmes se\nbattre en duel.\n\n")
  LANGUAGE_TEXT(2, "Mein Mann hat ein Faible\nf\xfcr Duellantinnen.\n\n")
  LANGUAGE_TEXT(3, "Mio marito ha un debole\nper le duellanti.\n\n")
  LANGUAGE_TEXT(4, "Mi marido tiene debi-\nlidad por las duelistas.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CBC, map_26_state_01_08EA3CBC, 0x08EA3CC8, 0x08EA3CE0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RICH_WIFE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CC8, map_26_state_01_08EA3CC8, 0x08EA3CD4, 0x08F0404C)
  LANGUAGE_TEXT(0, "A duel against me? How\nenchanting!\n\nI hope you show me the\nropes, young lad.\n\n")
  LANGUAGE_TEXT(1, "Un duel avec moi ? Je dois\ndire que \xe7a me tente.\n\nEt si tu m'expliquais les\nr\xe8gles, mon petit ?\n\n")
  LANGUAGE_TEXT(2, "Ein Duell mit mir? Das\nh\xf6rt sich interessant an.\n\nErkl\xe4rst du mir die\nRegeln, Kleiner?\n\n")
  LANGUAGE_TEXT(3, "Un duello con me?\nSembra interessante.\n\nChe ne dici di mostrarmi\ncome si fa, ragazzino?\n\n")
  LANGUAGE_TEXT(4, "\xbfUn duelo conmigo?\nSuena interesante.\n\n\xbfPor qu\xe9 no me ense\xf1as c\xf3mo\nse hace, peque\xf1o?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(34)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CD4, map_26_state_01_08EA3CD4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  SET_FLAG(EVENT_FLAG_DEFEATED_RICH_WIFE)
  LANGUAGE_TEXT(0, "Losing is never enjoyable.\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas marrant\nde perdre, pas vrai ?\n\n")
  LANGUAGE_TEXT(2, "Verlieren tut weh,\nnicht wahr?\n\n")
  LANGUAGE_TEXT(3, "\xc8 duro perdere, vero?\n\n")
  LANGUAGE_TEXT(4, "Perder pica, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CE0, map_26_state_01_08EA3CE0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Sorry, dear. Some other\ntime.\n\n")
  LANGUAGE_TEXT(1, "D\xe9sol\xe9, tr\xe8s cher.\nUne autre fois peut-\xeatre.\n\n")
  LANGUAGE_TEXT(2, "Tut mir Leid, mein Lieber.\nEin andermal.\n\n")
  LANGUAGE_TEXT(3, "Mi spiace, caro.\nUn'altra volta.\n\n")
  LANGUAGE_TEXT(4, "Lo siento, querido.\nOtra vez ser\xe1.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
