#include "event_macros.h"
#include "overworld.h"

/* map_60_state_05: map 60 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08F03A8C, map_60_state_05_08F03A8C, 0x08F03AA4, 0x08F03A98)
  PLAY_MUSIC(27)
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, you've finally\nsucceeded.\n\nYou have obtained the secret\nbehind the Phoenix Mode.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu as enfin\nr\xe9ussi, n'est-ce pas ?\n\nTu as obtenu le code\nsecret du Mode Ph\xe9nix.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du hast es endlich\ngeschafft, nicht wahr?\n\nDu hast das Geheimnis des\nPh\xf6nix-Modus entdeckt.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, alla fine ce\nl'hai fatta, non \xe8 cos\xec?\n\nHai ottenuto il segreto\ndella Modalit\xe0 Fenice.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, finalmente lo has\nhecho, \xbfno es as\xed?\n\nHas obtenido el secreto\ndel Modo F\xe9nix.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(51, 0, 8)
  LANGUAGE_TEXT(0, "Master Marik...\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Marik...\n\n")
  LANGUAGE_TEXT(2, "Meister Marik...\n\n")
  LANGUAGE_TEXT(3, "Maestro Marik...\n\n")
  LANGUAGE_TEXT(4, "Amo Marik...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "Yes, I know, Odion.\n\nI am going to awaken\n{PLAYER}'s The Winged\n\nDragon of Ra so that he can\nuse the Phoenix Mode.\n\n")
  LANGUAGE_TEXT(1, "Oui, je sais, Odion.\n\nJe dois r\xe9veiller le Dragon\nAil\xe9 de Ra de {PLAYER}.\n\nDe fa\xe7on \xe0 passer\nau Mode Ph\xe9nix.\n\n")
  LANGUAGE_TEXT(2, "Ja, ich wei\xdf, Odion.\n\nIch soll {PLAYER}s gefl\xfcgel-\nten Drachen von Ra wecken.\n\nSodass er in den Ph\xf6nix-\nModus wechselt.\n\n")
  LANGUAGE_TEXT(3, "S\xec, lo so, Odion.\n\nDevo risvegliare il Drago\nAlato di Ra di {PLAYER}.\n\nPer fare in modo che\ndiventi la Modalit\xe0 Fenice.\n\n")
  LANGUAGE_TEXT(4, "S\xed, lo s\xe9, Odion.\n\nTengo que despertar\nal Drag\xf3n Alado\n\nde Ra de {PLAYER}.\n\nPara que se vuelva\nel Modo F\xe9nix.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 64)
  DELAY(16)
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "I'll need to see The Winged\nDragon of Ra.\n\n")
  LANGUAGE_TEXT(1, "J'aurais besoin de voir\nle Dragon Ail\xe9 de Ra.\n\n")
  LANGUAGE_TEXT(2, "Ich muss zum gefl\xfcgelten\nDrachen von Ra gehen.\n\n")
  LANGUAGE_TEXT(3, "Dovr\xf2 vedere il\nDrago Alato di Ra.\n\n")
  LANGUAGE_TEXT(4, "Tendr\xe9 que ver al\nDrag\xf3n Alado de Ra.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(285)
  DELAY(16)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "Awaken! Phoenix Mode!\n\n")
  LANGUAGE_TEXT(1, "R\xe9veille-toi !\nMode Ph\xe9nix !\n\n")
  LANGUAGE_TEXT(2, "Erwache!\nPh\xf6nix-Modus!\n\n")
  LANGUAGE_TEXT(3, "Risvegliati,\nModalit\xe0 Fenice!\n\n")
  LANGUAGE_TEXT(4, "\xa1Despierta!\n\xa1Modo F\xe9nix!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(377)
  COMMAND_7C_ARG(8, 48)
  PLAY_MUSIC(385)
  COMMAND_7C_ARG(8, 46)
  COMMAND_7C_ARG(8, 22)
  PLAY_MUSIC(386)
  COMMAND_7C_ARG(8, 50)
  COMMAND_7C_ARG(8, 51)
  SET_FLAG(226)
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "Phoenix! Be calm!\n\nYour enemy is the one who\nweakened the Egyptian God\n\nCards.\n\nWith {PLAYER}, you must\nsmite that enemy!\n\n")
  LANGUAGE_TEXT(1, "Ph\xe9nix !\nCalme-toi !\n\nTon ennemi est celui qui a\nrendu les cartes de dieux\n\nplus faibles.\nAvec l'aide de {PLAYER},\n\nd\xe9barrasse-nous de cet\nennemi !\n\n")
  LANGUAGE_TEXT(2, "Ph\xf6nix!\nSei ruhig!\n\nDein Feind ist der, der die\nG\xf6tterkarten schw\xe4chte.\n\nDu musst den Feind mit\n{PLAYER} niederstrecken!\n\n")
  LANGUAGE_TEXT(3, "Fenice!\nCalmati!\n\nIl tuo nemico \xe8 colui che ha\nrisvegliato le carte\n\ndivine.\n\nCon {PLAYER}, devi\nsconfiggere quel nemico!\n\n")
  LANGUAGE_TEXT(4, "\xa1F\xe9nix!\n\xa1C\xe1lmate!\n\nTu enemigo es el que\ndebilit\xf3 a las cartas\n\nde los dioses.\n\n\xa1Con {PLAYER}, has de\ngolpear a ese enemigo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(51, 0, 8)
  LANGUAGE_TEXT(0, "What terrifying power...\n\n")
  LANGUAGE_TEXT(1, "Quelle puissance\neffrayante...\n\n")
  LANGUAGE_TEXT(2, "Welch furchtbare Macht...\n\n")
  LANGUAGE_TEXT(3, "Che potere terrificante...\n\n")
  LANGUAGE_TEXT(4, "Qu\xe9 temible poder...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 64)
  DELAY(16)
  PLAY_MUSIC(285)
  REMOVE_CARD(240)
  ADD_CARD(412)
  DELAY(16)
  WALK_OBJECT_Y(1, 44)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "Received The Winged Dragon\nof Ra {BYTE_8169}Phoenix Mode{BYTE_816A}!\n\n")
  LANGUAGE_TEXT(1, "Re\xe7u le Dragon Ail\xe9 de\nRa {BYTE_8169}Mode Ph\xe9nix{BYTE_816A} !\n\n")
  LANGUAGE_TEXT(2, "Den gefl\xfcgelten Drachen von\nRa erhalten {BYTE_8169}Ph\xf6nix-Modus{BYTE_816A}!\n\n")
  LANGUAGE_TEXT(3, "Ricevuto il Drago Alato di\nRa {BYTE_8169}Modalit\xe0 Fenice{BYTE_816A}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Recibido el Drag\xf3n Alado\nde Ra {BYTE_8169}Modo F\xe9nix{BYTE_816A}!\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  LANGUAGE_TEXT(1, "Le menu de r\xe9glage\ndu deck va s'afficher.")
  LANGUAGE_TEXT(2, "Das Men\xfc zur Deckeinstellung\nwird ge\xf6ffnet.")
  LANGUAGE_TEXT(3, "Verr\xe0 aperto il menu di\nsistemazione del deck.")
  LANGUAGE_TEXT(4, "Se abrir\xe1 el men\xfa de\najuste del deck.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03AA4, map_60_state_05_08F03AA4, 0x08F04040, 0x08F04040)
  PORTRAIT(48, 0, 8)
  LANGUAGE_TEXT(0, "The Winged Dragon of Ra has\nfully awakened.\n\nWhat you do with its power\nis up to you, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Le Dragon Ail\xe9 de Ra\ns'est enti\xe8rement r\xe9veill\xe9.\n\nL'utilisation de sa\npuissance ne d\xe9pend que de\n\ntoi, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Der gefl\xfcgelte Drache von Ra\nwurde voll erweckt.\n\nEs liegt an dir, {PLAYER},\nwas du damit tust.\n\n")
  LANGUAGE_TEXT(3, "Il Drago Alato di Ra si \xe8\nrisvegliato completamente.\n\nOra sta a te, {PLAYER},\ndecidere cosa farne\n\ndel suo potere.\n\n")
  LANGUAGE_TEXT(4, "El Drag\xf3n Alado de Ra ha\ndespertado por completo.\n\nLo que t\xfa hagas\ncon su poder, es\n\ncosa tuya, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(203)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A98, map_60_state_05_08F03A98, 0x08F03AA4, 0x08F03A98)
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  LANGUAGE_TEXT(1, "Le menu de r\xe9glage\ndu deck va s'afficher.")
  LANGUAGE_TEXT(2, "Das Men\xfc zur Deckeinstellung\nwird ge\xf6ffnet.")
  LANGUAGE_TEXT(3, "Verr\xe0 aperto il menu di\nsistemazione del deck.")
  LANGUAGE_TEXT(4, "Se abrir\xe1 el men\xfa de\najuste del deck.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()
