#include "event_macros.h"

/* map_37_state_05: map 37 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08ECD844, map_37_state_05_08ECD844, 0x08ECD850, 0x08ECD85C)
  CHECK_FLAG(131)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD850, map_37_state_05_08ECD850, 0x08F04040, 0x08F04040)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "Do you sense it?\nThe tortured waves,\n\nthe crashing sea...\n\nSomething's wrong.\nSomething's different.\n\n")
  LANGUAGE_TEXT(1, "Tu le sens aussi ?\nL'atmosph\xe8re maritime...\n\nQuelque chose a chang\xe9.\n\nQuelque chose ne tourne\npas rond.\n\n")
  LANGUAGE_TEXT(2, "Sp\xfcrst du es auch? Die\nAtmosph\xe4re des Meeres...\n\nEtwas stimmt da nicht.\nEtwas ist anders.\n\n")
  LANGUAGE_TEXT(3, "La senti anche tu?\nL'atmosfera del mare...\n\nQualcosa non va.\nC'\xe8 qualcosa di diverso.\n\n")
  LANGUAGE_TEXT(4, "\xbfLo notas tambi\xe9n?\nLa atm\xf3sfera del mar...\n\nAlgo malo pasa.\nAlgo ha cambiado.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD85C, map_37_state_05_08ECD85C, 0x08F04040, 0x08F04040)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "I've passed you my spirit.\n\nJust as the world's oceans\nare connected, our souls\n\nare united.\n\n")
  LANGUAGE_TEXT(1, "Mon esprit, je\nte l'ai donn\xe9.\n\nToi et moi, nous sommes\nli\xe9s par le duel.\n\nComme la mer rejoint les\nextr\xe9mit\xe9s du monde.\n\n")
  LANGUAGE_TEXT(2, "Mein Geist ist jetzt\nbei dir.\n\nWir beide sind durch\nunser Duell vereint.\n\nWie das Meer rund um\ndie Welt eins ist.\n\n")
  LANGUAGE_TEXT(3, "Il mio spirito, l'ho passato\na te. Tu ed io siamo uniti\n\nper mezzo del duello.\nProprio come il mare\n\nsi ricongiunge attorno\nal mondo.\n\n")
  LANGUAGE_TEXT(4, "Mi esp\xedritu, te lo\nhe pasado a ti.\n\nT\xfa y yo, estamos unidos por\nmedio de nuestra lucha.\n\nJusto como el mar est\xe1\nunido por todo el mundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD868, map_37_state_05_08ECD868, 0x08ECD874, 0x08ECD88C)
  CHECK_FLAG(131)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD874, map_37_state_05_08ECD874, 0x08ECD880, 0x08F0404C)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, you feel it, too?\n\nThe sea... It's afraid.\n\nThe ocean is terrified!\n\n{PLAYER}, you are intending\nto fight something that can\n\nparalyze the waters to its\nbriny deep!\n\nDo not deny it. I can tell.\n\nIn that case, take my spirit\nto battle with you!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu le\nressens, aussi ?\n\nLa mer...\nElle a peur.\n\nCette mer \xe9norme.\nElle est terrifi\xe9e.\n\n{PLAYER}, c'est\nce que tu affrontes ?\n\nJe le ressens.\n\nTu peux aussi\nprendre mon esprit\n\ndans cette bataille !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, sp\xfcrst du\nes auch?\n\nDas Meer...\nEs hat Angst.\n\nDieses riesige Meer...\nf\xfcrchtet sich.\n\n{PLAYER}, musst du\ndagegen k\xe4mpfen?\n\nIch sp\xfcre es.\n\nDu nimmst meinen Geist\nmit in den Kampf!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, lo\nsenti anche tu?\n\nIl mare...\nHa paura.\n\nQuesto immenso mare...\n\xc8 terrorizzato.\n\n{PLAYER}, \xe8 questo ci\xf2\nche dovrai affrontare?\n\nTe lo dico io.\n\nPorta in battaglia\nanche il mio spirito!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER},\n\xbftambi\xe9n lo notas?\n\nEl mar...\nEst\xe1 asustado.\n\nEste gran mar...\nEst\xe1 aterrorizado.\n\n{PLAYER}, \xbfes eso\ncon lo que te enfrentas?\n\nLo puedo decir.\n\n\xa1Lleva mi esp\xedritu\ntambi\xe9n a esa batalla!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(103)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD880, map_37_state_05_08ECD880, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(249)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "I've passed you my spirit.\n\nJust as the world's oceans\nare connected, our souls\n\nare united.\n\nWait, take my spirit card.\n\nIt's The Legendary\nFisherman.\n\nThe sea will drown you if\nyou show fear.\n\nIt's the same with dueling.\n\nKeep fighting without fear!\n\n")
  LANGUAGE_TEXT(1, "Mon esprit, je\nte l'ai donn\xe9.\n\nToi et moi, nous sommes\nli\xe9s par le duel.\n\nComme la mer rejoint les\nextr\xe9mit\xe9s du monde.\n\nAttends, prends aussi\nma carte spirituelle.\n\nC'est le P\xeacheur\nl\xe9gendaire.\n\nLa mer montrera\nsa col\xe8re d\xe8s que\n\ntu lui montreras\nque tu as peur.\n\nC'est pareil en duel.\n\nAlors, avance\nsans peur !\n\n")
  LANGUAGE_TEXT(2, "Mein Geist ist jetzt\nbei dir.\n\nWir beide sind durch\nunser Duell vereint.\n\nWie das Meer rund um\ndie Welt eins ist.\n\nWarte, nimm auch meine\nGeisterkarte.\n\nEs ist der legend\xe4re\nFischer.\n\nSobald du Furcht zeigst,\nf\xe4hrt das Meer seine\n\nKrallen aus. Es ist wie\nDuellieren.\n\nSchreite furchtlos voran!\n\n")
  LANGUAGE_TEXT(3, "Il mio spirito, l'ho passato\na te. Tu ed io siamo uniti\n\nper mezzo del duello.\nProprio come il mare\n\nsi ricongiunge attorno\nal mondo.\n\nAspetta, prendi anche\nla mia carta-spirito.\n\n\xc8 il Pescatore Leggendario.\nIl mare sguainer\xe0 le\n\nsue zanne nel momento\nin cui mostrerai paura.\n\n\xc8 come duellare. Vai avanti\nsenza timore!\n\n")
  LANGUAGE_TEXT(4, "Mi esp\xedritu, te lo\nhe pasado a ti.\n\nT\xfa y yo, estamos unidos por\nmedio de nuestra lucha.\n\nJusto como el mar est\xe1\nunido por todo el mundo.\n\nEspera, ll\xe9vate tambi\xe9n mi\ncarta de esp\xedritu.\n\nEs el Pescador legendario.\n\nEl mar mostrar\xe1 sus\ncolmillos en cuanto\n\nperciba tu miedo.\nEs lo mismo que al luchar.\n\n\xa1Sigue adelante sin miedo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 8)
  LANGUAGE_TEXT(0, "Received The Legendary\nFisherman.")
  LANGUAGE_TEXT(1, "Re\xe7u le P\xeacheur l\xe9gendaire.")
  LANGUAGE_TEXT(2, "Legend\xe4ren Fischer\nerhalten.")
  LANGUAGE_TEXT(3, "Ricevuto un Pescatore\nLeggendario.")
  LANGUAGE_TEXT(4, "Recibido un\nPescador legendario.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(249)
  PAGE_BREAK()
  ADD_CARD(257)
  SET_FLAG(131)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD88C, map_37_state_05_08ECD88C, 0x08ECD898, 0x08F0404C)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "No matter how tough the\nenemy, there's nothing to\n\nfear!\n\nAttack your foe with all\nyour might!\n\nI'm going to give my all in\nthis duel!\n\n")
  LANGUAGE_TEXT(1, "Il n'y a pas \xe0 avoir peur,\nm\xeame si ton ennemi\n\nest tr\xe8s fort.\n\nAffronte ton ennemi avec\ntoute ta puissance.\n\nDans ce duel, je vais donner\ntout ce que j'ai !\n\n")
  LANGUAGE_TEXT(2, "F\xfcrchte dich nicht, wie\nstark dein Gegner auch\n\nsein mag. Greif mit voller\nKraft an.\n\nIch gebe dir alles in\ndiesem Duell!\n\n")
  LANGUAGE_TEXT(3, "Non bisogna avere paura\nanche se il nemico \xe8 forte.\n\nVai incontro al nemico\ncon tutta la tua forza.\n\nCi metter\xf2 tutto me\nstesso in questo duello!\n\n")
  LANGUAGE_TEXT(4, "No hay por qu\xe9 temer ni al\nenemigo m\xe1s fuerte.\n\nVe hacia tu enemigo\ncon todo tu poder.\n\n\xa1Voy a darte todo mi\nser en este duelo!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(150)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD898, map_37_state_05_08ECD898, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(249)
  PORTRAIT(12, 0, 8)
  LANGUAGE_TEXT(0, "Did you learn anything from\nthis duel?\n\nAll oceans may look the same\nto you, but I can tell the\n\ndifference.\n\nYou just need to develop a\ndiscerning eye.\n\n")
  LANGUAGE_TEXT(1, "As-tu gagn\xe9 quelque\nchose dans tout cela ?\n\nLa mer a l'air d'\xeatre la\nm\xeame, mais elle est\n\nl\xe9g\xe8rement diff\xe9rente.\n\nIl faut juste \xeatre\nplus observateur.\n\n")
  LANGUAGE_TEXT(2, "Hat es dir etwas gebracht?\n\nDas Meer mag unver\xe4ndert\naussehen, aber eine Nuance\n\nist anders. Du musst nur ein\nGesp\xfcr daf\xfcr entwickeln.\n\n")
  LANGUAGE_TEXT(3, "Ci hai guadagnato\nqualcosa da questo?\n\nIl mare pu\xf2 sembrare\nsempre lo stesso, ma\n\n\xe8 leggermente diverso.\nDevi solo imparare\n\na distinguere.\n\n")
  LANGUAGE_TEXT(4, "\xbfHas obtenido algo\nde esto?\n\nPuede que el mar\nparezca igual, pero\n\nes sutilmente\ndiferente.\n\nS\xf3lo tienes que\ndesarrollar un ojo\n\nque sepa discernir.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
