#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_54_state_01: map 54 state 1 */

LOAD_SPRITE(1, SPRITE_SETO)
LOAD_SPRITE(2, SPRITE_ISHIZU)
LOAD_SPRITE(3, SPRITE_MOKUBA)
LOAD_SPRITE(4, SPRITE_CHEVALIER)
LOAD_SPRITE(5, SPRITE_VIDEO_CARD)
PLAY_MUSIC(MUSIC_INSIDE_PEGASUS_CASTLE)
DELAY(16)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "Go, Blue-Eyes White Dragon!\n\n"
)
PLAY_MUSIC(MUSIC_333)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
DELAY(16)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "White Lightning Attack!\n\n"
)
PLAY_MUSIC(MUSIC_338)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_ATTACK_BOTTOM_MIDDLE)
DELAY(16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(SPRITE_CHEVALIER, 2, 16)
PLAY_MUSIC(MUSIC_282)
OBJECT_EFFECT(SPRITE_CHEVALIER, OBJECT_EFFECT_TELEPORT)
DELAY(16)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_DOWN, 0, 0)
DELAY(32)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Humph. So you finally showed\n"
    "up. But you're too late.\n\n"
    "That Pegasus... I will crush\n"
    "him myself!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_Y(SPRITE_ISHIZU, 72)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Kaiba... You cannot win\n"
    "alone... One Egyptian God\n\n"
    "Card isn't enough.\n\n"
    "You have no chance.\n\n"
    "Not against Pegasus and\n"
    "Reshef the Dark Being.\n\n"
)
TALK(PORTRAIT_SETO, 1, PORTRAIT_POSITION_AUTO,
    "My deck is perfect!\n\n"
    "Whoever the opponent may be,\n"
    "defeat isn't in the cards!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
SHOW_OBJECT(SPRITE_MOKUBA, 60, 18, 0, 0, 0)
WALK_OBJECT_Y(SPRITE_MOKUBA, 32)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_SETO | SPRITE_ISHIZU)
DELAY(8)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Then duel me, big brother,\n"
    "with your perfect deck.\n\n"
)
TALK(PORTRAIT_SETO, 6, PORTRAIT_POSITION_AUTO,
    "Wh-what? Mokuba? Wh-what are\n"
    "you saying?\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Reshef is going to rule this\n"
    "world anyway.\n\n"
    "It's better to quit fighting\n"
    "and accept fate.\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Mokuba's spirit is under\n"
    "control...\n\n"
)
TALK(PORTRAIT_SETO, 5, PORTRAIT_POSITION_AUTO,
    "Pegasus! How dare you!\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Big brother, will you join\n"
    "me?\n\n"
    "Or would you like to duel?\n\n"
)
TALK(PORTRAIT_SETO, 3, PORTRAIT_POSITION_AUTO,
    "Mokuba...\n\n"
    "I... I can't duel against\n"
    "Mokuba...\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_LEFT, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_ISHIZU)
DELAY(16)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, you must duel in\n"
    "Kaiba's place.\n\n"
    "That is the only way to\n"
    "break the mind control over\n\n"
    "Mokuba.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, SPRITE_MOKUBA)
DELAY(16)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Huh? {PLAYER} wants to duel\n"
    "me?\n\n"
    "Sure. You have to ante your\n"
    "Egyptian God Card.\n\n"
    "I don't care who I have to\n"
    "duel as long as I can get\n\n"
    "an Egyptian God Card.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Grr... Mokuba...\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Big brother, there's no need\n"
    "to be sad.\n\n"
    "After {PLAYER}, you're next!\n\n"
    "Ahahahahahaha!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_SETO)
DELAY(16)
WALK_OBJECT_Y(0, 52)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MOKUBA)
DELAY(16)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Don't give me that look!\n\n"
    "I'll show you how it feels\n"
    "to lose!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_SETO, 37)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_RIGHT, 0, 0)
DELAY(16)
WALK_OBJECT_Y(0, 63)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(16)
WALK_OBJECT_Y(SPRITE_MOKUBA, 42)
DELAY(16)
DUEL(DUELIST_MOKUBA_119)
PLAY_MUSIC(MUSIC_369)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Arrggh! M-my head! Seto, it\n"
    "hurts!\n\n"
    "Help me, Seto!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_SETO)
DELAY(8)
TALK(PORTRAIT_SETO, 6, PORTRAIT_POSITION_AUTO,
    "Mokuba!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_Y(SPRITE_SETO, 54)
WALK_OBJECT_X(SPRITE_SETO, 60)
WALK_OBJECT_Y(SPRITE_SETO, 50)
DELAY(8)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Mokuba, have you regained\n"
    "your senses?\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO,
    "Seto... I... I...\n\n"
)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Don't say another word. It's\n"
    "over, Mokuba.\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO,
    "Big brother...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_SETO, 34)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_DOWN, 0, 0)
DELAY(16)
WALK_OBJECT_Y(SPRITE_MOKUBA, 37)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_RIGHT, 0, 0)
WALK_OBJECT_X(SPRITE_MOKUBA, 68)
MOVE_OBJECT(SPRITE_MOKUBA, DIRECTION_DOWN, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_DOWN, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_405)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I hate to say this, but I\n"
    "owe you one.\n\n"
    "You have to duel Pegasus\n"
    "next...\n\n"
    "You need my Egyptian God\n"
    "Card, don't you?\n\n"
    "Fine... I could just hand it\n"
    "to you....\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU)
DELAY(8)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Kaiba...\n\n"
)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "But you and I are duelists.\n\n"
    "Therefore, the only way you\n"
    "can get my card is in a\n\n"
    "duel!\n\n"
    "That's all that needs to be\n"
    "said.\n\n"
    "Now, come on, {PLAYER}.\n\n"
    "My strongest monster will\n"
    "annhilate you!\n\n"
    "Obelisk the Tormentor will\n"
    "decide the outcome!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_SETO, 42)
DELAY(32)
DUEL(DUELIST_SETO_120)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Urrrgh...\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Your powers were evenly\n"
    "matched...\n\n"
    "But {PLAYER}'s pure spirit\n"
    "won the duel.\n\n"
    "He also received the help of\n"
    "his fellow duelists...\n\n"
    "Perhaps his pure spirit can\n"
    "counter the Dark Being.\n\n"
)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "There's nothing for me to\n"
    "say.\n\n"
    "You earned this card.\n\n"
    "I don't care if you duel\n"
    "Pegasus or Reshef...\n\n"
    "Just don't lose using my\n"
    "best card!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_285)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 60, 46, 0, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_286)
SLIDE_OBJECT(SPRITE_VIDEO_CARD, 0, 16)
DELAY(32)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 128, 96, 0, 0, 0)
DELAY(32)
TEXT
(
    "Received Obelisk the\n"
    "Tormentor!"
)
PLAY_MUSIC(MUSIC_701)
DELAY(240)
DELAY(80)
PAGE_BREAK()
ADD_CARD(234)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Come, {PLAYER}, we must go.\n\n"
    "The time has come to seal\n"
    "Reshef the Dark Being.\n\n"
)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)
SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA)

EVENT_SCRIPT_REPLACEMENT(0x08EE9C3C, map_54_state_01_08EE9C3C, 0x08EE9C30, 0x08EE9C3C)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "But... If you refuse...\n\n"
    "Reshef the Dark Being will\n"
    "rule the world.\n\n"
    "Please, {PLAYER}!\n\n"
    "You must duel in Kaiba's\n"
    "place!\n\n"
)
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "{CARD_1}Yes\n"
    "No{CARD_2}\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C60, map_54_state_01_08EE9C60, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Hurry up and beat Pegasus.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C78, map_54_state_01_08EE9C78, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Come, {PLAYER}, we must go.\n\n"
    "The time has come to seal\n"
    "Reshef the Dark Being.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C6C, map_54_state_01_08EE9C6C, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO,
    "...\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
