#include "event_macros.h"
#include "overworld.h"

/* map_23_state_01: map 23 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E95294, map_23_state_01_08E95294, 0x08E952A0, 0x08E952AC)
  PLAY_MUSIC(402)
  DELAY(8)
  PORTRAIT(PORTRAIT_PANICK, EXPRESSION_PANIK_DEFEATED, 8)
  LANGUAGE_TEXT(0, "Giyaaaaah!\n\n")
  LANGUAGE_TEXT(1, "Giyaaaaah !\n\n")
  LANGUAGE_TEXT(2, "Gijaaaaah!\n\n")
  LANGUAGE_TEXT(3, "Iiiahhhhh!\n\n")
  LANGUAGE_TEXT(4, "\xa1Giyaaaaah!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(205)
  OBJECT_EFFECT(4, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  WALK_OBJECT_X(0, 68)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_X(0, 52)
  WALK_OBJECT_Y(0, 44)
  WALK_OBJECT_Y(13, 74)
  WALK_OBJECT_X(13, 68)
  WALK_OBJECT_Y(13, 54)
  WALK_OBJECT_X(13, 58)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 74)
  WALK_OBJECT_X(14, 68)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 46)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(1, 28)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You've come for the\nMillennium Necklace?\n\n")
  LANGUAGE_TEXT(1, "Tu es l\xe0 pour le\nCollier du mill\xe9nium ?\n\n")
  LANGUAGE_TEXT(2, "Du willst die\nMillenniumskette?\n\n")
  LANGUAGE_TEXT(3, "Sei qui per la\nCollana Millenaria?\n\n")
  LANGUAGE_TEXT(4, "\xbfHas venido por el\nCollar del Milenio?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952A0, map_23_state_01_08E952A0, 0x08E952B8, 0x08F0404C)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Fine... The Millennium\nNecklace is yours.\n\nIt is my duty to protect a\nMillennium Item...\n\nFor I am a Millennium\nGuardian!\n\nYou must prove yourself to\nme in a duel.\n\nTo see if you are worthy of\na Millennium Item!\n\nYou will only get the\nMillennium Necklace if you\n\ncan pass my challenge!\n\n")
  LANGUAGE_TEXT(1, "Tr\xe8s bien... Le Collier du\nmill\xe9nium est \xe0 toi.\n\nJ'ai pour devoir de prot\xe9ger\nun Objet du mill\xe9nium.\n\nJe suis un Gardien du\nMill\xe9nium. Tu dois prouver\n\ntes capacit\xe9s en\nm'affrontant en duel.\n\nPour voir si tu es digne\nd'un Objet du mill\xe9nium !\n\nMais seulement si tu\npeux relever mon d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Gut... Die Millenniums-\nkette geh\xf6rt dir.\n\nEs ist meine Pflicht, Mi-\nllenniumsgegenst\xe4nde zu\n\nsch\xfctzen. Ich bin ein\nMillenniumsw\xe4chter.\n\nBeweis in einem Duell,\ndass du w\xfcrdig bist.\n\nEines Millenniumsgegen-\nstands w\xfcrdig!\n\nAber nur, wenn du meine\nHerausforderung annimmst\n\nund gewinnst!\n\n")
  LANGUAGE_TEXT(3, "Bene... La Collana\nMillenaria \xe8 tua.\n\nHo il compito di proteggere\nun Oggetto Millenario.\n\nSono un Guardiano\nMillenario.\n\nDevi darmi prova di\nesserne degno in un\n\nduello. Per vedere se ti me-\nriti un Oggetto Millenario!\n\nMa solo se batterai\nla mia sfida!\n\n")
  LANGUAGE_TEXT(4, "Vale... El Collar del\nMilenio es tuyo.\n\nEs mi deber proteger un\nObjeto del Milenio.\n\nSoy un Guardi\xe1n del\nMilenio.\n\nDebes demostrarme que eres\ndigno en un duelo.\n\n\xa1Para ver si eres digno\nde un Objeto del Milenio!\n\n\xa1Pero s\xf3lo si puedes\nsuperar mi reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(154)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952B8, map_23_state_01_08E952B8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(0)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You are still clumsy and\nunrefined...\n\nBut deep within you, I since\na faint glimmer of hope.\n\nYou have proven yourself.\nTake this. It is yours.\n\n")
  LANGUAGE_TEXT(1, "Tu es encore maladroit\net inexp\xe9riment\xe9...\n\nMais je vois en toi\nune lueur d'espoir.\n\nTu as fait tes preuves.\n\nTiens, prends-le.\nC'est \xe0 toi.\n\n")
  LANGUAGE_TEXT(2, "Du bist noch tolpatschig\nund ungeschickt...\n\nAber ich erkenne auch\neinen schwachen\n\nHoffnungsschimmer.\n\nDu hast dich bew\xe4hrt. Hier,\nnimm, das ist f\xfcr dich.\n\n")
  LANGUAGE_TEXT(3, "Sei ancora impacciato\ne imperfetto...\n\nMa vedo in te anche un\nlieve bagliore di speranza.\n\nHai superato la prova.\nTieni, appartiene a te.\n\n")
  LANGUAGE_TEXT(4, "Eres torpe y poco\nrefinado...\n\nPero en ti veo un\nrayo de esperanza.\n\nHas probado tu val\xeda.\nToma esto, es tuyo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 52, 30, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(278)
  SLIDE_OBJECT(3, 0, 12)
  DELAY(8)
  PLAY_MUSIC(279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(373)
  SPECIAL(0)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Wh-what is this?\n\n")
  LANGUAGE_TEXT(1, "Qu-qu'est-ce que c'est ?\n\n")
  LANGUAGE_TEXT(2, "W-was ist das?\n\n")
  LANGUAGE_TEXT(3, "Che-che cos'\xe8?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 es esto?\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN1)
  FADE_SCREEN(4)
  CUTSCENE(0)
  WARP(23, 8, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952AC, map_23_state_01_08E952AC, 0x08E952B8, 0x08F0404C)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Spare me your lies.\n\nA liar isn't worthy of the\nMillennium Necklace.\n\nIt is my duty to protect a\nMillennium Item...\n\nFor I am a Millennium\nGuardian!\n\nYou must prove yourself to\nme in a duel.\n\nTo see if you are worthy of\na Millennium Item!\n\nPass my challenge to obtain\nits mystical revelations!\n\n")
  LANGUAGE_TEXT(1, "Epargne-moi\ntes mensonges.\n\nUn menteur ne m\xe9rite pas\nle Collier du mill\xe9nium.\n\nJ'ai pour devoir de prot\xe9ger\nun Objet du mill\xe9nium.\n\nJe suis un Gardien du\nMill\xe9nium. Tu dois prouver\n\ntes capacit\xe9s en\nm'affrontant en duel.\n\nPour voir si tu es digne\nd'un Objet du mill\xe9nium !\n\nRel\xe8ve mon d\xe9fi et b\xe9n\xe9ficie\nde ses r\xe9v\xe9lations !\n\n")
  LANGUAGE_TEXT(2, "Spar dir die L\xfcgen.\n\nEin L\xfcgner ist der Mill-\nenniumskette nicht w\xfcrdig.\n\nEs ist meine Pflicht, Mi-\nllenniumsgegenst\xe4nde zu\n\nsch\xfctzen. Ich bin ein\nMillenniumsw\xe4chter.\n\nBeweis in einem Duell,\ndass du w\xfcrdig bist.\n\nEines Millenniumsgegen-\nstands w\xfcrdig!\n\nBesiege mich - du wirst\nErstaunliches erfahren!\n\n")
  LANGUAGE_TEXT(3, "Risparmiami le tue\nbugie.\n\nUn bugiardo non \xe8 degno\ndella Collana Millenaria.\n\nHo il compito di proteggere\nun Oggetto Millenario.\n\nSono un Guardiano\nMillenario.\n\nDevi darmi prova di\nesserne degno in un\n\nduello. Per vedere se ti me-\nriti un Oggetto Millenario!\n\nVinci la mia sfida e otter-\nrai le sue rivelazioni!\n\n")
  LANGUAGE_TEXT(4, "Ah\xf3rrate las mentiras.\n\nUn mentiroso no se merece el\nCollar del Milenio.\n\nEs mi deber proteger un\nObjeto del Milenio.\n\nSoy un Guardi\xe1n del\nMilenio.\n\nDebes demostrarme que eres\ndigno en un duelo.\n\n\xa1Para ver si eres digno\nde un Objeto del Milenio!\n\nSupera mi reto y obt\xe9n\nsus revelaciones.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(154)
  FALLTHROUGH()
END_EVENT_SCRIPT()
