#include "event_macros.h"
#include "overworld.h"

/* map_42_state_01: map 42 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED9D70, map_42_state_01_08ED9D70, 0x08ED9D7C, 0x08F04040)
  PLAY_MUSIC(254)
  DELAY(16)
  WALK_OBJECT_X(1, 98)
  DELAY(8)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Nihihi... I commend you on\ncoming this far.\n\n")
  LANGUAGE_TEXT(1, "Nihihi... Je suis\nimpressionn\xe9\n\nde vous voir\narriver jusqu'ici.\n\n")
  LANGUAGE_TEXT(2, "Nihihi... Nicht schlecht -\nihr habt es weit gebracht.\n\n")
  LANGUAGE_TEXT(3, "Nihihi... Complimenti,\nper essere giunti fin qui.\n\n")
  LANGUAGE_TEXT(4, "Nihihi... Debo feli-\ncitaros por haber\n\nllegado hasta aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 98)
  DELAY(16)
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Gehehehehe...\n\nBut you're not going any\nfarther. We won't let you!\n\n")
  LANGUAGE_TEXT(1, "Gehehehehe...\n\nVous n'irez pas\nplus loin.\n\nNous ne vous\nlaisserons pas faire !\n\n")
  LANGUAGE_TEXT(2, "Gehehehehe...\n\nAber das war's. Weiter\nlassen wir euch nicht!\n\n")
  LANGUAGE_TEXT(3, "Ieheheheheh...\n\nNon andrete oltre. Non\nve lo permetteremo!\n\n")
  LANGUAGE_TEXT(4, "Jejejejeje...\n\nNo ir\xe9is m\xe1s lejos.\n\xa1No os dejaremos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(2, 68)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Hah! In your dreams! We'll\ntake you on!\n\n")
  LANGUAGE_TEXT(1, "Ha ! C'est \xe7a, r\xeavez\ntoujours !\n\nOn va vous affronter !\n\n")
  LANGUAGE_TEXT(2, "Hah! Ihr tr\xe4umt wohl!\nWir machen euch fertig!\n\n")
  LANGUAGE_TEXT(3, "Hah! Neanche per sogno!\nVi affronteremo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hah! \xa1So\xf1\xe1is!\n\xa1Os haremos frente!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, pick who you want\nto duel!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, choisis celui\ncontre qui tu vas\n\nte battre en duel !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, w\xe4hl einen\nGegner!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, scegline\nuno con cui duellare!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}, escoge al que\nquieras para luchar!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9D7C, map_42_state_01_08ED9D7C, 0x08ED9D88, 0x08ED9D94)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}PaniK\nMimic of Doom{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}PaniK\nMimic of Doom{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}PaniK\nMimic of Doom{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}PaniK\nMimic of Doom{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}PaniK\nMimic of Doom{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9D88, map_42_state_01_08ED9D88, 0x08ED9DA0, 0x08F0404C)
  WALK_OBJECT_Y(2, 74)
  WALK_OBJECT_X(2, 88)
  WALK_OBJECT_Y(0, 64)
  WALK_OBJECT_X(0, 88)
  WALK_OBJECT_Y(13, 70)
  WALK_OBJECT_X(13, 78)
  DELAY(16)
  DUEL(160)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DA0, map_42_state_01_08ED9DA0, 0x08ED9DB8, 0x08ED9E18)
  CHECK_FLAG(EVENT_FLAG_TAG_DUELED_WITH_JOEY_AGAINST_THE_DOMINO_STATIONS_GUARDS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DB8, map_42_state_01_08ED9DB8, 0x08ED9DC4, 0x08F04040)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I... I lost again?!\n\n")
  LANGUAGE_TEXT(1, "Je... J'ai encore\nperdu ?!\n\n")
  LANGUAGE_TEXT(2, "Ich... Ich habe schon wieder\nverloren?!\n\n")
  LANGUAGE_TEXT(3, "Io... Ho perso di nuovo?!\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfHe... he vuelto a perder?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "H-how dare you... But how\nwill you deal with this?\n\n")
  LANGUAGE_TEXT(1, "C-comment oses-tu...\n\nComment vas-tu\nfaire face ?\n\n")
  LANGUAGE_TEXT(2, "W-wie kannst du es\nwagen...\n\nAber was machst du jetzt?\n\n")
  LANGUAGE_TEXT(3, "Come osi... Non la\npasserai liscia!\n\n")
  LANGUAGE_TEXT(4, "\xbfCo-c\xf3mo osas?...\nPero, \xbfc\xf3mo vas\n\na hacer con esto?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Gehehehehe! We'll duel until\nI win!\n\n")
  LANGUAGE_TEXT(1, "Hi hi hi !\nBattons-nous\n\nen duel jusqu'\xe0\nce que je gagne !\n\n")
  LANGUAGE_TEXT(2, "Gehehehehe!\n\nWir duellieren uns, bis\nich gewinne!\n\n")
  LANGUAGE_TEXT(3, "Ieheheheheh! Duelliamo\nfinch\xe9 non vinco io!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jejejejeje!\n\n\xa1Lucharemos hasta\nque gane!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 92)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8193)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Forget it, you lowlifes!\n\nYou're not going to waste\n{PLAYER} and Yugi's time!\n\n")
  LANGUAGE_TEXT(1, "Laissez tomber,\nduellistes de bas \xe9tage !\n\nVous n'allez pas faire\nperdre leur temps\n\n\xe0 {PLAYER} et \xe0 Yugi !\n\n")
  LANGUAGE_TEXT(2, "Vergesst es, ihr mickrigen\nDuellanten!\n\nIhr werdet nicht die Zeit\nvon {PLAYER} und Yugi\n\nvergeuden!\n\n")
  LANGUAGE_TEXT(3, "Neanche a pensarci,\nduellanti da quattro soldi!\n\nNon sprecherete il tempo\ndi {PLAYER} e di Yugi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Olvidadlo, duelistas\nde poca monta!\n\n\xa1No vais a desper-\ndiciar el tiempo de\n\n{PLAYER} y Yugi!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DC4, map_42_state_01_08ED9DC4, 0x08ED9DD0, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Let me handle this!\n{PLAYER}, you keep going!\n\n")
  LANGUAGE_TEXT(1, "Laisse-moi m'en occuper !\n{PLAYER}, continue\n\n\xe0 progresser !\n\n")
  LANGUAGE_TEXT(2, "\xdcberlass das nur mir!\n{PLAYER}, geh du weiter!\n\n")
  LANGUAGE_TEXT(3, "A questo ci penso io!\nTu vai avanti, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo me ocupo de esto!\n\xa1{PLAYER}, t\xfa sigue!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DD0, map_42_state_01_08ED9DD0, 0x08ED9DDC, 0x08ED9DE8)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}By yourself?\nI'm counting on you!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}C'est impossible !\nJe compte sur toi !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Das ist unm\xf6glich!\nIch verlass mich auf dich!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}\xc8 impossibile!\nConto su di te!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1Eso es imposible!\n\xa1Cuento contigo!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DDC, map_42_state_01_08ED9DDC, 0x08ED9DF4, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Heh, I know I'm in over my\nhead!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, je sais que\nc'est trop pour moi !\n\n")
  LANGUAGE_TEXT(2, "Heh, ich wei\xdf, dass es\nknifflig wird!\n\n")
  LANGUAGE_TEXT(3, "Eh, lo so che mi sento\ntroppo coinvolto!\n\n")
  LANGUAGE_TEXT(4, "Heh, \xa1s\xe9 que estoy\nmetido a tope!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DF4, map_42_state_01_08ED9DF4, 0x08ED9E00, 0x08F04040)
  LANGUAGE_TEXT(0, "I don't have any Egyptian\nGod Cards...\n\nThat's why you have to keep\ngoing, {PLAYER}!\n\nMake sure you take down\nPegasus!\n\n")
  LANGUAGE_TEXT(1, "Je n'ai pas de\ncartes de dieux.\n\nC'est pour cela que tu dois continuer, {PLAYER} !\n\nVa r\xe9gler le compte\nde Pegasus !\n\n")
  LANGUAGE_TEXT(2, "Ich habe keine\nG\xf6tterkarten...\n\nDarum musst du weitergehen,\n{PLAYER}!\n\nSorge daf\xfcr, dass du\nPegasus erledigst!\n\n")
  LANGUAGE_TEXT(3, "Non ho carte divine...\nPer questo devi andare\n\navanti, {PLAYER}!\n\nMi raccomando,\nsistema Pegasus!\n\n")
  LANGUAGE_TEXT(4, "No tengo cartas\nde los dioses...\n\n\xa1Por eso tienes que\nseguir, {PLAYER}!\n\n\xa1Aseg\xfarate de que\nderrotas a Pegasus!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 92)
  WALK_OBJECT_Y(2, 69)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Nihihihi...\n\nA scrub is challenging me?\nHow amusing!\n\n")
  LANGUAGE_TEXT(1, "Nihihihi...\n\nUn mec comme toi me d\xe9fie ?\nComme c'est amusant !\n\n")
  LANGUAGE_TEXT(2, "Nihihihi...\n\nEiner wie du will es mit\nmir aufnehmen? Wie am\xfcsant!\n\n")
  LANGUAGE_TEXT(3, "Nihihi... E tu pretenderesti\ndi sfidare me?\n\nMa fammi ridere!\n\n")
  LANGUAGE_TEXT(4, "Nihihihi...\n\n\xbfTipos como t\xfa\nme ret\xe1is?\n\n\xa1Qu\xe9 divertido!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Gehehehehe...\n\nYou think you can beat the\ntwo of us by yourself?\n\nDon't make me laugh!\nGehehehehe!\n\n")
  LANGUAGE_TEXT(1, "Hi hi hi hi...\n\nTu crois pouvoir\nnous battre sans\n\nl'aide de personne ?\n\nComme c'est dr\xf4le !\nAh ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Gehehehehe...\n\nDu glaubst, du allein k\xf6nn-\ntest uns beide besiegen?\n\nSehr witzig!\nGehehehehe!\n\n")
  LANGUAGE_TEXT(3, "Geheheheheh...\n\nPensi di riuscire a\nbattere noi due da solo?\n\nChe ridere!\nGeheheheheh!\n\n")
  LANGUAGE_TEXT(4, "Jejejeje...\n\n\xbfCrees que nos puedes\nvencer t\xfa solo?\n\n\xa1Hilarante!\n\xa1Jejejeje!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "You two are all talk! Why\ndon't ya shut your mouths\n\nand duel!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, fermez-la et\nbattez-vous en duel !\n\n")
  LANGUAGE_TEXT(2, "Hey, seid still! Haltet den\nMund und k\xe4mpft!\n\n")
  LANGUAGE_TEXT(3, "Chiudete la bocca!\nState zitti e duellate!\n\n")
  LANGUAGE_TEXT(4, "Hey, \xa1callaos!\n\xa1Callad y luchad!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E00, map_42_state_01_08ED9E00, 0x08ED9E0C, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 8)
  SLIDE_OBJECT(3, 3, 8)
  SLIDE_OBJECT(2, 3, 8)
  DELAY(16)
  SLIDE_OBJECT(2, 1, 2)
  SLIDE_OBJECT(1, 1, 2)
  SLIDE_OBJECT(3, 1, 2)
  DELAY(24)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 6)
  SLIDE_OBJECT(3, 3, 6)
  SLIDE_OBJECT(2, 3, 6)
  DELAY(16)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 4)
  SLIDE_OBJECT(3, 3, 4)
  SLIDE_OBJECT(2, 3, 4)
  DELAY(22)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Th-this guy... He's pretty\ngood.\n\nBut I can't lose! I refuse\nto lose!\n\n{PLAYER}, what are you\nwaiting for? Go on!\n\n")
  LANGUAGE_TEXT(1, "Ce.. Ce type...\nIl est plut\xf4t fort.\n\nMais je ne peux\npas perdre !\n\n{PLAYER}, qu'est-ce\nque tu attends ! Vas-y !\n\n")
  LANGUAGE_TEXT(2, "D-dieser Typ... ist\nziemlich gut.\n\nAber ich kann nicht verlier-\nen. Ich darf einfach nicht!\n\n{PLAYER}, worauf wartest\ndu? Geh schon!\n\n")
  LANGUAGE_TEXT(3, "Per\xf2! Il ragazzo...\n\xc8 piuttosto bravo.\n\nMa non posso perdere!\nNon posso permettermi\n\ndi perdere! {PLAYER},\ncosa aspetti? Vai!\n\n")
  LANGUAGE_TEXT(4, "E-este t\xedo...\nEs muy bueno.\n\n\xa1Pero no puedo perder!\n\xa1No se me permite perder!\n\n{PLAYER}, \xbfa qu\xe9\nesperas? \xa1Vamos!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E0C, map_42_state_01_08ED9E0C, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  SLIDE_OBJECT(2, 1, 4)
  SLIDE_OBJECT(1, 1, 4)
  SLIDE_OBJECT(3, 1, 4)
  DELAY(18)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 8)
  SLIDE_OBJECT(3, 3, 8)
  SLIDE_OBJECT(2, 3, 8)
  DELAY(20)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 6)
  SLIDE_OBJECT(3, 3, 6)
  SLIDE_OBJECT(2, 3, 6)
  DELAY(16)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(1, 3, 6)
  SLIDE_OBJECT(3, 3, 6)
  SLIDE_OBJECT(2, 3, 6)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(254)
  PLAY_MUSIC(272)
  REACTION(3, 8192)
  DELAY(32)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "...Let's go, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "... Allons-y, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "... Gehen wir, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "... Andiamo, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "... Vamos, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_PANIK_AND_MIMIC_OF_DOOM2)
  SET_FLAG(EVENT_FLAG_JOEY_LEFT_THE_PARTY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DE8, map_42_state_01_08ED9DE8, 0x08ED9DF4, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yeah, leave it to me,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Ouais, laisse-moi faire,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ja, \xfcberlass es nur mir,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Certo, lascia fare a\nme, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "S\xed, d\xe9jamelo a m\xed,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E18, map_42_state_01_08ED9E18, 0x08ED9E30, 0x08ED9E3C)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Let's do this, Red-Eyes!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, yeux rouges !\n\n")
  LANGUAGE_TEXT(2, "Na los, Rotauge!\n\n")
  LANGUAGE_TEXT(3, "Andiamo, Occhi Rossi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, Ojos rojos!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 7)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(1, "Inferno Fire Blast !\n\n")
  LANGUAGE_TEXT(2, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(3, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(4, "\xa1Inferno Fire Blast!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(389)
  COMMAND_7C_ARG(8, 39)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(3, 3, 8)
  DELAY(64)
  MOVE_OBJECT(3, 1, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Tsk... This garbage can't\nstop me...\n\n")
  LANGUAGE_TEXT(1, "Pff... Je ne peux pas\nlaisser des minables\n\ncomme eux nous retenir...\n\n")
  LANGUAGE_TEXT(2, "Tss... Ich darf nicht\nzulassen, dass uns Abschaum\n\nwie dieser aufh\xe4lt...\n\n")
  LANGUAGE_TEXT(3, "Acc...Non posso permettere\na dei fetenti come questi\n\ndi bloccarci...\n\n")
  LANGUAGE_TEXT(4, "Tch... No puedo\npermitir que nos\n\ndetenga basura\ncomo \xe9sta...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  SET_FLAG(EVENT_FLAG_FLASHBACK)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_RIGHT_DOMINO_STATION_GUARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E30, map_42_state_01_08ED9E30, 0x08F04040, 0x08F04040)
  WARP(14, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E3C, map_42_state_01_08ED9E3C, 0x08F04040, 0x08F04040)
  WARP(14, 8, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9D94, map_42_state_01_08ED9D94, 0x08ED9DAC, 0x08F0404C)
  WALK_OBJECT_Y(2, 64)
  WALK_OBJECT_X(2, 88)
  WALK_OBJECT_Y(0, 74)
  WALK_OBJECT_X(0, 88)
  WALK_OBJECT_Y(13, 77)
  WALK_OBJECT_X(13, 78)
  DELAY(16)
  DUEL(161)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DAC, map_42_state_01_08ED9DAC, 0x08ED9DB8, 0x08ED9E24)
  SET_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_MIMIC_OF_DOOM2)
  CHECK_FLAG(EVENT_FLAG_TAG_DUELED_WITH_JOEY_AGAINST_THE_DOMINO_STATIONS_GUARDS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E24, map_42_state_01_08ED9E24, 0x08ED9E30, 0x08ED9E3C)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Let's do this, Red-Eyes!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, yeux rouges !\n\n")
  LANGUAGE_TEXT(2, "Na los, Rotauge!\n\n")
  LANGUAGE_TEXT(3, "Andiamo, Occhi Rossi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, Ojos rojos!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 7)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 0)
  LANGUAGE_TEXT(0, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(1, "Inferno Fire Blast !\n\n")
  LANGUAGE_TEXT(2, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(3, "Inferno Fire Blast!\n\n")
  LANGUAGE_TEXT(4, "\xa1Inferno Fire Blast!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(389)
  COMMAND_7C_ARG(8, 39)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(1, 3, 8)
  DELAY(64)
  MOVE_OBJECT(1, 1, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Tsk... This garbage can't\nstop me...\n\n")
  LANGUAGE_TEXT(1, "Pff... Je ne peux pas\nlaisser des minables\n\ncomme eux nous retenir...\n\n")
  LANGUAGE_TEXT(2, "Tss... Ich darf nicht\nzulassen, dass uns Abschaum\n\nwie dieser aufh\xe4lt...\n\n")
  LANGUAGE_TEXT(3, "Acc...Non posso permettere\na dei fetenti come questi\n\ndi bloccarci...\n\n")
  LANGUAGE_TEXT(4, "Tch... No puedo\npermitir que nos\n\ndetenga basura\ncomo \xe9sta...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  SET_FLAG(EVENT_FLAG_FLASHBACK)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_RIGHT_DOMINO_STATION_GUARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E60, map_42_state_01_08ED9E60, 0x08F04040, 0x08F04040)
  SET_FLAG(EVENT_FLAG_UNLOCKED_DUNGEON)
  FALLTHROUGH()
END_EVENT_SCRIPT()
