#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_07_state_07: map 7 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E5F984, map_07_state_07_08E5F984, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_TEA)
  LOAD_SPRITE(2, SPRITE_GRANDPA_MUTO)
  LOAD_SPRITE(3, SPRITE_YUGI)
  LOAD_SPRITE(4, SPRITE_JOEY)
  LOAD_SPRITE(5, SPRITE_MONKEY_ROBOT)
  LOAD_SPRITE(6, SPRITE_INVISIBLE)
  LOAD_SPRITE(7, SPRITE_INVISIBLE)
  PLAY_MUSIC(MUSIC_323)
  TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_POSITION_AUTO, "Ukki!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F990, map_07_state_07_08E5F990, 0x08E5F99C, 0x08E5F9A8)
  PLAY_MUSIC(MUSIC_326)
  TALK(PORTRAIT_ROBOT_MOkNEY, 2, PORTRAIT_POSITION_AUTO, "Ukki! Ukikki!")
  DUEL(DUELIST_ROBOT_MO_152)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F99C, map_07_state_07_08E5F99C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  PLAY_MUSIC(MUSIC_325)
  TALK(PORTRAIT_ROBOT_MOkNEY, 5, PORTRAIT_POSITION_AUTO, "Ukiiii.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
