#include "event_macros.h"
#include "overworld.h"

/* map_00_state_17: map 0 state 17 */

EVENT_SCRIPT_REPLACEMENT(0x08E34E20, map_00_state_17_08E34E20, 0x08E34E2C, 0x08E34E44)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_ESPA_ROBA2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E2C, map_00_state_17_08E34E2C, 0x08E34E38, 0x08F0404C)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "Pipipi...\n\n")
  LANGUAGE_TEXT(1, "Pipipi...\n\n")
  LANGUAGE_TEXT(2, "Pipipi...\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\n\n")
  LANGUAGE_TEXT(4, "Pipipi...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Who are you fighting?\n\nActually, don't tell me.\nDuelists don't communicate\n\nwith words. We communicate\nwith cards!\n\nDon't underestimate my\nPsychic Power deck!\n\n")
  LANGUAGE_TEXT(1, "Pourquoi tu te bats ?\n\nNon... Les explications\nsont inutiles\n\nentre duellistes.\nNe sous-estime pas\n\nla puissance de mon\nDeck psychique.\n\n")
  LANGUAGE_TEXT(2, "Wogegen k\xe4mpfst du?\n\nNein... Duellanten ver-\nstehen sich ohne Worte.\n\nUntersch\xe4tz nicht mein\nPsychodeck.\n\n")
  LANGUAGE_TEXT(3, "Per cosa combatti?\n\nNo...Tra i duellanti,\nnon servono le parole.\n\nNon sottovalutare il\nmio deck dai poteri\n\nparanormali.\n\n")
  LANGUAGE_TEXT(4, "\xbfContra qu\xe9 luchas?\n\nNo... No hay necesidad de\nhablar entre duelistas.\n\nNo subestimes mi deck de\npoderes s\xedquicos.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(84)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E38, map_00_state_17_08E34E38, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "Pipipi... You win.\n\n")
  LANGUAGE_TEXT(1, "Pipipi...\nOK, tu as gagn\xe9.\n\n")
  LANGUAGE_TEXT(2, "Pipipi...\nOkay, du hast gewonnen.\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\nE va bene, hai vinto.\n\n")
  LANGUAGE_TEXT(4, "Pipipi...\nVale, t\xfa ganas.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't know who you're\nfighting, but take my Jinzo\n\nwith you.\n\nThis card represents my\nspirit.\n\nYour fight is far from over,\nbut... Pipipi...\n\nYes. I sense you'll be fine.\n\nA duelist becomes more\npowerful when he has\n\nfriends supporting him.\n\nSo think of Jinzo as me.\n\nAs long as you have my help,\nyou're not fighting alone!\n\n")
  LANGUAGE_TEXT(1, "Je ne sais pas exactement\npour quelle raison\n\ntu te bats...\n\nMais veux-tu bien prendre\nmon Jinzo avec toi ?\n\nIl repr\xe9sente mon esprit.\n\nTon combat n'est\npas termin\xe9.\n\nMais...\nPipipi...\n\nOui.\nTu vas t'en sortir.\n\nUn duelliste est fort\ns'il est accompagn\xe9.\n\nJinzo est mon alter ego.\n\nRappelle-toi, tu ne\nvas pas te battre seul.\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf ja nicht genau,\nwogegen du k\xe4mpfst...\n\nAber nimm doch mein\nJinzo mit.\n\nEs repr\xe4sentiert meinen\nGeist.\n\nDein Kampf ist noch nicht\nzu Ende.\n\nAber...\nPipipi...\n\nJa. Du wirst es schon\nschaffen.\n\nEin Duellant ist stark, wenn\ner nicht allein ist.\n\nJinzo ist mein zweites Ich.\n\nDenk daran: Du wirst nicht\nallein k\xe4mpfen.\n\n")
  LANGUAGE_TEXT(3, "Non so esattamente per\ncosa stai combattendo...\n\nMa vuoi prendere il\nmio Jinzo con te?\n\nRappresenta il mio spirito.\n\nLa tua battaglia non\n\xe8 ancora finita.\n\nMa...\nEheheheh...\n\nS\xec.\nAndr\xe0 tutto bene.\n\nUn duellante \xe8 forte\nse non \xe8 da solo.\n\nJinzo \xe8 il mio alter ego.\n\nRicordati che non sarai\nda solo a combattere.\n\n")
  LANGUAGE_TEXT(4, "No s\xe9 exactamente\ncontra qu\xe9 luchas...\n\nPero, \xbfte llevar\xedas\na mi Jinzo contigo?\n\nRepresenta mi esp\xedritu.\n\nTu batalla no se\nha terminado a\xfan.\n\nPero...\nPipipi...\n\nS\xed.\nEstar\xe1s bien.\n\nUn duelista es fuerte\nsi no est\xe1 s\xf3lo.\n\nJinzo es mi otro yo.\n\nRecuerda, no vas a\nluchar s\xf3lo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Received Jinzo.")
  LANGUAGE_TEXT(1, "Re\xe7u un Jinzo.")
  LANGUAGE_TEXT(2, "Ein Jinzo erhalten.")
  LANGUAGE_TEXT(3, "Ricevuto un Jinzo.")
  LANGUAGE_TEXT(4, "Recibido un Jinzo.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(4)
  PAGE_BREAK()
  ADD_CARD(752)
  SET_FLAG(EVENT_FLAG_DEFEATED_ESPA_ROBA2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E44, map_00_state_17_08E34E44, 0x08E34E50, 0x08F0404C)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "If you think dueling me will\nhelp you improve...\n\nThen I'll be happy to duel\nyou!\n\n")
  LANGUAGE_TEXT(1, "Si tu crois que me battre\nen duel, \xe7a va t'aider...\n\nAlors d'accord, je veux\nbien me battre en duel !\n\n")
  LANGUAGE_TEXT(2, "Wenn du glaubst, ein Duell\nmit mir k\xf6nnte dir\n\nhelfen...\nDann nehme ich gerne an!\n\n")
  LANGUAGE_TEXT(3, "Se pensi che duellare con\nme ti sar\xe0 di aiuto...\n\nBenissimo, sar\xf2 felice\ndi duellare con te!\n\n")
  LANGUAGE_TEXT(4, "Si crees que luchar\nconmigo te ayudar\xe1...\n\nEntonces, claro, \xa1lo\nhar\xe9 encantado!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(146)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E50, map_00_state_17_08E34E50, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "A duelist's greatest\nstrength is his potential.\n\nThe hope we instill in our\ncards makes our decks\n\npowerful.\n\nPipipi...\n\nI don't have to read the\ncosmic forces to know that\n\nyou're a more skilled\nduelist than before!\n\n")
  LANGUAGE_TEXT(1, "La puissance des\nduellistes est r\xe9elle.\n\nLes r\xeaves que nous faisons\ndans nos cartes...\n\nVoil\xe0 ce qui rend nos\nDecks plus puissants...\n\nPipipi...\n\nCe n'est pas une pr\xe9diction.\nTu es devenu plus fort !\n\n")
  LANGUAGE_TEXT(2, "Die Macht von Duellanten wie\nuns hat gro\xdfes Potenzial.\n\nDie Tr\xe4ume, die wir in\nunsere Karten legen...\n\nErst sie machen unsere Decks\nstark. Pipipi...\n\nDamit will ich nicht das\nErgebnis vorhersagen.\n\nDu bist einfach stark\ngeworden!\n\n")
  LANGUAGE_TEXT(3, "La potenza dei duellanti\ncome noi \xe8 potenziale.\n\nI sogni che facciamo\nsulle nostre carte...\n\nSono ci\xf2 che rende\nforti i nostri deck.\n\nEheheh...\n\nNon \xe8 una predizione. Sei\ndiventato forte davvero!\n\n")
  LANGUAGE_TEXT(4, "El poder de los duelistas\ncomo nosotros es potencial.\n\nLos sue\xf1os que invertimos\nen nuestras cartas...\n\nSon lo que hacen nuestros\ndecks fuertes.\n\nPipipi...\n\nNo es una predicci\xf3n.\n\xa1Te has hecho fuerte!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
