#include "event_macros.h"
#include "overworld.h"

/* map_31_state_03: map 31 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EB42AC, map_31_state_03_08EB42AC, 0x08EB42B8, 0x08EB42C4)
  SET_FLAG(EVENT_FLAG_JOEY_FOUND_PARA_AND_DOX_SUSPICIOUS)
  WALK_OBJECT_X(14, 104)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 0)
  LANGUAGE_TEXT(0, "There's somethin' fishy\nabout those guys. Really\n\nfishy.\n\n{PLAYER}, you think so too,\nright?\n\n")
  LANGUAGE_TEXT(1, "Ces types ont l'air\nlouche, pas vrai ?\n\n{PLAYER}, qu'est-ce\nque tu en penses ?\n\nTu es d'accord ?\n\n")
  LANGUAGE_TEXT(2, "Mit den Typen stimmte etwas\nnicht. Eindeutig.\n\n{PLAYER}, das glaubst du\ndoch auch, oder?\n\n")
  LANGUAGE_TEXT(3, "Quei tizi erano sospetti.\nEntrambi, naturalmente.\n\n{PLAYER}, non la pensi\ncos\xec anche tu?\n\n")
  LANGUAGE_TEXT(4, "Esos tipos eran\nescurridizos. Es obvio.\n\n{PLAYER}, t\xfa lo\ncrees tambi\xe9n, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yup\nNope{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Ouais\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Jepp\nN\xf6\xf6{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Esatto\nPer niente{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42B8, map_31_state_03_08EB42B8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Let's check 'em out again.\n\n")
  LANGUAGE_TEXT(1, "On ferait bien de\nv\xe9rifier \xe0 nouveau.\n\n")
  LANGUAGE_TEXT(2, "Wir sollten sie einmal genau\nunter die Lupe nehmen.\n\n")
  LANGUAGE_TEXT(3, "Dovremmo controllarli\ndi nuovo.\n\n")
  LANGUAGE_TEXT(4, "Deber\xedamos ver-\nlos de nuevo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42C4, map_31_state_03_08EB42C4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 0)
  LANGUAGE_TEXT(0, "I'm tellin' ya, there's\nsomethin' weird about those\n\nguys!\n\nEvery bone in my body tells\nme dat, and my instinct is\n\nnever wrong!\n\nLet's check 'em out again.\n\n")
  LANGUAGE_TEXT(1, "Ils ont vraiment un\ncomportement bizarre !\n\nJe suis s\xfbr que quelque\nchose ne va pas.\n\nAllons v\xe9rifier.\n\n")
  LANGUAGE_TEXT(2, "Irgendetwas stimmt mit\ndenen nicht!\n\nMein Instinkt sagt mir, dass\nda etwas faul ist.\n\nSchauen wir sie uns noch\neinmal genau an.\n\n")
  LANGUAGE_TEXT(3, "Nascondono certamente\nqualcosa!\n\nL'istinto mi dice che c'\xe8\nqualcosa che non va.\n\nControlliamoli di nuovo.\n\n")
  LANGUAGE_TEXT(4, "Hay algo escurridizo en\nellos, \xa1sin duda!\n\nMi instinto me dice\nque algo pasa.\n\nVolvamos a\ncomprobarlos.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
