#include "event_macros.h"

/* map_23_state_10: map 23 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08E95498, map_23_state_10_08E95498, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(401)
  DELAY(64)
  PLAY_MUSIC(347)
  COMMAND_7C_ARG(8, 42)
  PORTRAIT(20, 6, 8)
  LANGUAGE_TEXT(0, "Wh-what's this?!\n\n")
  LANGUAGE_TEXT(1, "Q-qu'est-ce que\nc'est que \xe7a ?!\n\n")
  LANGUAGE_TEXT(2, "W-was zum Teufel?!\n\n")
  LANGUAGE_TEXT(3, "Ma che diavolo?!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ...qu\xe9 demonios?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(2, 2, 8)
  LANGUAGE_TEXT(0, "It's Ra's judgment...\nActually, it's more than\n\nthat.\n\nFeel the wrath for angering\nthe Egyptian Gods!\n\n")
  LANGUAGE_TEXT(1, "Le jugement de Ra...\nNon, pas seulement.\n\nMesure la col\xe8re divine !\n\n")
  LANGUAGE_TEXT(2, "Ras Urteil...\nNein, nicht nur das.\n\nSp\xfcre den Zorn der G\xf6tter!\n\n")
  LANGUAGE_TEXT(3, "Il giudizio di Ra...\nNo, non solo quello.\n\nConoscerai la\ncollera divina!\n\n")
  LANGUAGE_TEXT(4, "El juicio de Ra...\nNo, no s\xf3lo eso.\n\n\xa1Prueba la ira divina!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(359)
  COMMAND_7C_ARG(8, 43)
  COMMAND_7C_ARG(8, 45)
  PLAY_MUSIC(348)
  COMMAND_7C_ARG(8, 47)
  PLAY_MUSIC(302)
  PORTRAIT(20, 4, 8)
  LANGUAGE_TEXT(0, "Gwaaah!\n\n")
  LANGUAGE_TEXT(1, "Gouaah !\n\n")
  LANGUAGE_TEXT(2, "Gwaaah!\n\n")
  LANGUAGE_TEXT(3, "Aaaahhhhhh!\n\n")
  LANGUAGE_TEXT(4, "\xa1Guaaah!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(303)
  SHOW_OBJECT(5, 58, 38, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(205)
  OBJECT_EFFECT(2, 0)
  DELAY(64)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  WARP(60, 4, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
