#include "event_macros.h"
#include "overworld.h"

/* map_00_state_05: map 0 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E34B14, map_00_state_05_08E34B14, 0x08E34B2C, 0x08E34B38)
  LOAD_SPRITE(1, SPRITE_ISHIZU)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_RING_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B2C, map_00_state_05_08E34B2C, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(MUSIC_ISHIZU_ISHTAR)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Bandit Keith is also\nsearching for the\n\nMillennium Items...\n\nI am afraid that he\ncomplicates matters\n\ngreatly.\n\nOur need for urgency has\nincreased.\n\nReshef the Dark Being is\ninsidious.\n\nHe exploits the weaknesses\nin the souls of duelists.\n\nI hope that Bandit Keith\ndoes not succumb to his\n\npower...\n\nFortunately, Bandit Keith\ndid not find the Millennium\n\nRing.\n\nThat is a ray of hope among\nall this darkness.\n\nFour Millennium Items\nremain...\n\nAnd the next one is in.")
  DELAY(43)
  TEXT(".")
  DELAY(43)
  TEXT(".")
  DELAY(43)
  TEXT("\nChina. At the Great Wall.\n\nThe Dark Being's power is\nintensifying with every\n\npassing moment.\n\nPlease find the next\nMillennium Item quickly.\n\n")
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_RING_TO_ISHIZU)
  SET_FLAG(EVENT_FLAG_UNLOCKED_CHINA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B38, map_00_state_05_08E34B38, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Sol Chevalsky resurrected\nthe Dark Being...\n\nWe need the Egyptian God\nCards to stop it.\n\nWe must restore the Egyptian\nGod Cards from stone.\n\nBut in order to do so, we\nrequire the Millennium\n\nItems.\n\nThe fourth item is at the\nGreat Wall of China.\n\nPlease recover it as soon as\nyou can.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B20, map_00_state_05_08E34B20, 0x08E34B2C, 0x08E34B44)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_RING_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B44, map_00_state_05_08E34B44, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Please. Hurry to the Great\nWall of China.\n\nReshef the Dark Being will\nsoon engulf the world.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
