#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_07_state_05: map 7 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E5F8B8, map_07_state_05_08E5F8B8, 0x08E5F8C4, 0x08E5F8D0)
  LOAD_SPRITE(1, SPRITE_TEA)
  LOAD_SPRITE(2, SPRITE_GRANDPA_MUTO)
  LOAD_SPRITE(3, SPRITE_YUGI)
  LOAD_SPRITE(4, SPRITE_JOEY)
  LOAD_SPRITE(5, SPRITE_INVISIBLE)
  LOAD_SPRITE(6, SPRITE_INVISIBLE)
  CHECK_FLAG(EVENT_FLAG_TOLD_TEA_YOU_WILL_GO_FACE_PEGASUS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F8C4, map_07_state_05_08E5F8C4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You're going to face Pegasus?",
      "I see... Please be careful, {PLAYER}."
  )
  SET_FLAG(EVENT_FLAG_TOLD_TEA_YOU_WILL_GO_FACE_PEGASUS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F8D0, map_07_state_05_08E5F8D0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, I know you can win!",
      "Beat Pegasus and rescue Mokuba!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F8DC, map_07_state_05_08E5F8DC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What's the point of dueling me?",
      "Pegasus is the one you really want, {PLAYER}."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
