#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_31_state_08: map 31 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08EB43CC, map_31_state_08_08EB43CC, 0x08EB43D8, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_WEEVIL)
  LOAD_SPRITE(2, SPRITE_BUTTERFLY)
  PLAY_MUSIC(MUSIC_706)
  PLAY_MUSIC(MUSIC_380)
  SHOW_OBJECT(2, 64, 96, 0, 0, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 32, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 6, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 8, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 8, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 4, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 4, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 12, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 6, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 8, 0)
  MOVE_OBJECT(2, DIRECTION_DOWN, 6, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 10, 0)
  MOVE_OBJECT(2, DIRECTION_DOWN, 10, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 4, 0)
  MOVE_OBJECT(2, DIRECTION_DOWN, 4, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 6, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 8, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 4, 0)
  WALK_OBJECT_Y(2, 42)
  WALK_OBJECT_X(2, 24)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB43D8, map_31_state_08_08EB43D8, 0x08F04040, 0x08F04040)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(8)
  WALK_OBJECT_Y(1, 42)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_367)
  SLIDE_OBJECT(1, 1, 20)
  MOVE_OBJECT(2, DIRECTION_UP, 8, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 12, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 6, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 4, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 6, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 6, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 8, 0)
  WALK_OBJECT_X(2, 0)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_1)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "Arrrgh! That bug got away!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "But... The insects have come\n"
      "back...\n\n"
      "...Does that mean he's back\n"
      "too?\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 8, 0)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 6, 0)
  DELAY(4)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 4, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_LEFT, 4, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "He probably doesn't think of\n"
      "me as a friend, so I\n\n"
      "shouldn't go visit him....\n\n"
      "But I did give him my\n"
      "card...\n\n"
      "So maybe it wouldn't be\n"
      "weird for me to visit him.\n\n"
      "Yup, that's what I'll do.\n\n"
      "I'll just say I want to see\n"
      "how my card is doing!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 96)
  FADE_MUSIC(16)
  FADE_SCREEN(16)
  WARP(LOCATION_CANADA_RUINS_OUTSIDE, 5, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
