#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_01: map 23 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E95294, map_23_state_01_08E95294, 0x08E952A0, 0x08E952AC)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  LOAD_SPRITE(2, SPRITE_PANIK)
  LOAD_SPRITE(3, SPRITE_MILLENNIUM_NECKLACE)
  PLAY_MUSIC(MUSIC_402)
  DELAY(8)
  TALK(PORTRAIT_PANICK, EXPRESSION_PANIK_DEFEATED, PORTRAIT_POSITION_AUTO, "Giyaaaaah!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_205)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_DISAPPEAR)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
  WALK_OBJECT_X(0, 68)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_X(0, 52)
  WALK_OBJECT_Y(0, 44)
  WALK_OBJECT_Y(13, 74)
  WALK_OBJECT_X(13, 68)
  WALK_OBJECT_Y(13, 54)
  WALK_OBJECT_X(13, 58)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 74)
  WALK_OBJECT_X(14, 68)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 46)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(1, 28)
  DELAY(16)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You've come for the Millennium Necklace?")
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952A0, map_23_state_01_08E952A0, 0x08E952B8, 0x08F0404C)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Fine... The Millennium Necklace is yours.",
      "It is my duty to protect a Millennium Item...",
      "For I am a Millennium Guardian!",
      "You must prove yourself to me in a duel.",
      "To see if you are worthy of a Millennium Item!",
      "You will only get the Millennium Necklace if you",
      "can pass my challenge!"
  )
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_154)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952B8, map_23_state_01_08E952B8, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(SOUND_NONE)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You are still clumsy and unrefined...",
      "But deep within you, I since a faint glimmer of hope.",
      "You have proven yourself. Take this. It is yours."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(3, 52, 30, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_278)
  SLIDE_OBJECT(3, 0, 12)
  DELAY(8)
  PLAY_MUSIC(MUSIC_279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_373)
  SPECIAL(0)
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO, "Wh-what is this?")
  SET_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN1)
  FADE_SCREEN(4)
  CUTSCENE(0)
  WARP(LOCATION_EGYPT_EXHIBITION_MILLENNIUM_GUARDIAN, 8, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E952AC, map_23_state_01_08E952AC, 0x08E952B8, 0x08F0404C)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Spare me your lies.",
      "A liar isn't worthy of the Millennium Necklace.",
      "It is my duty to protect a Millennium Item...",
      "For I am a Millennium Guardian!",
      "You must prove yourself to me in a duel.",
      "To see if you are worthy of a Millennium Item!",
      "Pass my challenge to obtain its mystical revelations!"
  )
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_154)
  FALLTHROUGH()
END_EVENT_SCRIPT()
