#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_60_state_05: map 60 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08F03A8C, map_60_state_05_08F03A8C, 0x08F03AA4, 0x08F03A98)
  LOAD_SPRITE(1, SPRITE_MARIK)
  LOAD_SPRITE(2, SPRITE_ODION)
  PLAY_MUSIC(MUSIC_MARIK_ISHTAR)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, you've finally succeeded.",
      "You have obtained the secret behind the Phoenix Mode."
  )
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Master Marik...")
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Yes, I know, Odion.",
      "I am going to awaken {PLAYER}'s The Winged",
      "Dragon of Ra so that he can use the Phoenix Mode."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 64)
  DELAY(16)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'll need to see The Winged Dragon of Ra.")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_285)
  DELAY(16)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Awaken! Phoenix Mode!")
  PLAY_MUSIC(MUSIC_377)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPARKLE_RETURNS)
  PLAY_MUSIC(MUSIC_385)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_LIGHTNING_KILLS_KEITH)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_22)
  PLAY_MUSIC(MUSIC_386)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_PHOENIX_RA_TURNS_TO_FIREBALL)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_51)
  SET_FLAG(EVENT_FLAG_LIGHT_THE_CANDLE_IN_MARIKS_ROOM)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Phoenix! Be calm!",
      "Your enemy is the one who weakened the Egyptian God",
      "Cards.",
      "With {PLAYER}, you must smite that enemy!"
  )
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "What terrifying power...")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 64)
  DELAY(16)
  PLAY_MUSIC(MUSIC_285)
  REMOVE_CARD(240)
  ADD_CARD(412)
  DELAY(16)
  WALK_OBJECT_Y(1, 44)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_NONE, "Received The Winged Dragon of Ra {BYTE_8169}Phoenix Mode{BYTE_816A}!")
  TEXT("The deck adjustment menu will be opened.")
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03AA4, map_60_state_05_08F03AA4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "The Winged Dragon of Ra has fully awakened.",
      "What you do with its power is up to you, {PLAYER}."
  )
  SET_FLAG(EVENT_FLAG_OBTAINED_PHOENIX_MODE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A98, map_60_state_05_08F03A98, 0x08F03AA4, 0x08F03A98)
  TEXT("The deck adjustment menu will be opened.")
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()
