#include "event_macros.h"
#include "overworld.h"

/* map_40_state_01: map 40 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED55F0, map_40_state_01_08ED55F0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(252)
  DELAY(8)
  WALK_OBJECT_X(1, 56)
  DELAY(8)
  WALK_OBJECT_X(0, 76)
  WALK_OBJECT_X(13, 86)
  WALK_OBJECT_X(14, 86)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "So... This is Pegasus's\nisland.\n\nSeto Kaiba has probably\nalready gone ahead.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(48)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I do not know what Pegasus\nis planning.\n\nBut we cannot ignore Reshef\nthe Dark Being.\n\nHarsh battles await.\n\nBut don't succumb in the\nface of adversity.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_ENTERED_PEGASUS_ISLAND)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED5608, map_40_state_01_08ED5608, 0x08F04244, 0x08F04040)
  SET_FLAG(EVENT_FLAG_LEAVING_THE_CABLE_CAR_LEADS_TO_THE_TOP_OF_PEGASUS_ISLAND)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED55FC, map_40_state_01_08ED55FC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Duelist Kingdom\nTournament was once held\n\nhere.\n\nHowever, the island has been\ntransformed since then.\n\nThere must be many duelists\nunder Reshef's control.\n\nThey're ready to ambush us.\n\nBe careful as you make your\nway to Pegasus's castle.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
