#include "event_macros.h"

/* map_05_state_06: map 5 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E51088, map_05_state_06_08E51088, 0x08F04040, 0x08F04040)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  LANGUAGE_TEXT(0, "Oh no! I lost again.\n\n")
  LANGUAGE_TEXT(1, "Oh, mince !\nJ'ai encore perdu.\n\n")
  LANGUAGE_TEXT(2, "Oh, Mist!\nSchon wieder verloren.\n\n")
  LANGUAGE_TEXT(3, "No, dannazione!\nHo perso di nuovo.\n\n")
  LANGUAGE_TEXT(4, "Oh, \xa1vaya!\nHe vuelto a perder.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  LANGUAGE_TEXT(0, "Hahah, I did it! Try harder\nnext time!\n\n")
  LANGUAGE_TEXT(1, "Ha ah, j'ai r\xe9ussi !\n\nEssaie de faire mieux\nla prochaine fois !\n\n")
  LANGUAGE_TEXT(2, "Hahah, geschafft! Streng\ndich beim n\xe4chsten Mal\n\nmehr an!\n\n")
  LANGUAGE_TEXT(3, "Hahah, ce l'ho fatta! La\nprossima volta,\n\nimpegnati di pi\xf9!\n\n")
  LANGUAGE_TEXT(4, "Jajaja, \xa1lo hice!\n\xa1Esfu\xe9rzate m\xe1s\n\nla pr\xf3xima vez!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  LANGUAGE_TEXT(0, "Yeah, I'm not going to lose\nagain!\n\n")
  LANGUAGE_TEXT(1, "Ouais, la prochaine fois,\nje ne vais pas perdre !\n\n")
  LANGUAGE_TEXT(2, "Ja, beim n\xe4chsten Mal\nwerde ich nicht verlieren!\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0. La prossima volta\nnon perder\xf2!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed, no perder\xe9\nla pr\xf3xima vez!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(6, 15, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
