#include "event_macros.h"
#include "overworld.h"

/* map_04_state_03: map 4 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E4D114, map_04_state_03_08E4D114, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "A few duelists are nice.\n\nHe looks pretty scary, but\nhe's actually a good guy.\n\n")
  LANGUAGE_TEXT(1, "Il y a des chics types\nparmi les duellistes.\n\nIl fait peur, mais\nc'est un type bien.\n\n")
  LANGUAGE_TEXT(2, "Es gibt auch nette\nDuellanten.\n\nEr sieht Angst einfl\xf6\xdfend\naus, ist aber nicht b\xf6se.\n\n")
  LANGUAGE_TEXT(3, "Tra i duellanti, ci sono\ndei bravi ragazzi.\n\nLui incute paura, ma\n\xe8 un bravo ragazzo.\n\n")
  LANGUAGE_TEXT(4, "Hay buenos tipos entre\nlos duelistas.\n\nTiene un aspecto temible,\npero es un buen tipo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D120, map_04_state_03_08E4D120, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls took one look\nat his face and ran.\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls ont jet\xe9\nun coup d'\u0153il\n\n\xe0 son visage et puis\nils sont partis.\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls warfen\neinen Blick auf ihn und\n\nzogen ab.\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls lo hanno\nguardato in faccia e\n\nse ne sono andati.\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls vieron su\ncara y salieron corriendo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D12C, map_04_state_03_08E4D12C, 0x08E4D150, 0x08E4D138)
  CHECK_FLAG(EVENT_FLAG_SEARCHING_FOR_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D150, map_04_state_03_08E4D150, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hihihi, I unleashed my Neo\nGhost deck...\n\nAnd the Neo Ghouls fled in\nterror.\n\n")
  LANGUAGE_TEXT(1, "Hihihi, j'ai d\xe9terr\xe9 mon\nDeck N\xe9o Fant\xf4me...\n\nCa a terrifi\xe9\nles Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Hihihi, ich habe mein\nNeo-Geisterdeck zum\n\nVorschein gebracht...\n\nUnd schon rannten die Neo\nGhouls geschockt davon.\n\n")
  LANGUAGE_TEXT(3, "Eheheh, ho tirato fuori\nil mio nuovo deck di\n\nfantasmi... e i Neo Ghouls\nse la sono data a gambe.\n\n")
  LANGUAGE_TEXT(4, "Ji,ji,ji, desenterr\xe9 mi\ndeck neofantasma...\n\nLos Neo Ghouls se\nlargaron aterrorizados.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D138, map_04_state_03_08E4D138, 0x08E4D144, 0x08E4D150)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D144, map_04_state_03_08E4D144, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "There are Neo Ghouls hiding\nin the Town of Domino?\n\nI didn't know that.\n\n")
  LANGUAGE_TEXT(1, "Des Neo Ghouls se\ncachent \xe0 Domino ?\n\nJe n'en ai jamais\nentendu parler.\n\n")
  LANGUAGE_TEXT(2, "Es verbergen sich Neo\nGhouls in Domino?\n\nDavon wei\xdf ich nichts.\n\n")
  LANGUAGE_TEXT(3, "Dei Neo Ghouls si\nnascondono a Domino?\n\nNon ne so niente.\n\n")
  LANGUAGE_TEXT(4, "\xbfHay Neo Ghouls\nescondidos en Domino?\n\nNo s\xe9 nada de eso.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D15C, map_04_state_03_08E4D15C, 0x08E4D168, 0x08F0404C)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My Neo Ghost deck will haunt\nyou...\n\n")
  LANGUAGE_TEXT(1, "Mon Deck N\xe9o Fant\xf4me\nva te hanter...\n\n")
  LANGUAGE_TEXT(2, "Mein Neo-Geisterdeck wird\ndich verfolgen...\n\n")
  LANGUAGE_TEXT(3, "Il mio nuovo deck di\nfantasmi ti perseguiter\xe0.\n\n")
  LANGUAGE_TEXT(4, "Mi deck neofantasma\nte perseguir\xe1...\n\n")
  END_LANGUAGE_TEXT()
  DUEL(60)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D168, map_04_state_03_08E4D168, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(9)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER} is ghoulishly more\nclever than the Neo\n\nGhouls...\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} est bien plus\nfort que les Neo Ghouls...\n\n")
  LANGUAGE_TEXT(2, "{PLAYER} ist eine Stufe\nbesser als die Neo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER} \xe8 superiore\nai Neo Ghouls...\n\n")
  LANGUAGE_TEXT(4, "{PLAYER} es superior a\nlos Neo Ghouls...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
