#include "event_macros.h"
#include "overworld.h"

/* map_29_state_07: map 29 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC90C, map_29_state_07_08EAC90C, 0x08EAC918, 0x08EAC924)
  LOAD_SPRITE(1, SPRITE_BONZ)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_BONZ3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC918, map_29_state_07_08EAC918, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Ahhh... It's good to be back\nin the dark.\n\nI don't know why everyone\nwant to be in the light.\n\nIt's so relaxing...\n\nBut something doesn't feel\nright...\n\nIt feels the same as the\ntime I was taking orders\n\nfrom Bandit Keith...\n\nThe best way to forget my\ntroubles is to have a duel!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC924, map_29_state_07_08EAC924, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Your journey is far from\nover.\n\nBut my card will definitely\nhelp you.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC930, map_29_state_07_08EAC930, 0x08EAC93C, 0x08EAC954)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_BONZ3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC93C, map_29_state_07_08EAC93C, 0x08EAC948, 0x08F0404C)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I've dueled you before,\n{PLAYER}...\n\nBut I've never seen you so\ndetermined.\n\nYou must be preparing for an\nenormous duel.\n\nOkay! {PLAYER}, I'll duel\nyou anytime you want.\n\n")
  DUEL(100)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC948, map_29_state_07_08EAC948, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I lost because you wanted to\nwin more than I did.\n\nIt's easy to tell you're\npreparing for a great\n\nbattle, {PLAYER}.\n\nYou have an enormous weight\non your shoulders. I wish I\n\ncould help you...\n\nI know! Take this card.\n\nIt represents me.\n\nIt's Pumpking the King of\nGhosts.\n\nI know it will come in\nhandy...\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Received Pumpking the King\nof Ghosts.")
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(16)
  PAGE_BREAK()
  ADD_CARD(99)
  SET_FLAG(EVENT_FLAG_DEFEATED_BONZ3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC954, map_29_state_07_08EAC954, 0x08EAC960, 0x08F0404C)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I'm a better duelist now\nthan when I was in Bandit\n\nKeith's gang.\n\nIf dueling me will hone your\nskills...\n\nI'll duel you anytime you\nwant.\n\n")
  DUEL(148)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC960, map_29_state_07_08EAC960, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("D-did I help you a little?\n\nI'm rooting for you. Win!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
