#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_14_state_07: map 14 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E77588, map_14_state_07_08E77588, 0x08E775A0, 0x08E775AC)
  LOAD_SPRITE(1, SPRITE_YUGI)
  LOAD_SPRITE(2, SPRITE_JOEY)
  LOAD_SPRITE(3, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(4, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(5, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(6, SPRITE_FENG_LONG)
  LOAD_SPRITE(7, SPRITE_NIBBLES)
  PLAY_MUSIC(MUSIC_230)
  HIDE_PORTRAIT()
  DELAY(64)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "What took ya so long, {PLAYER}!",
      "If you're having trouble against these guys...",
      "Well, I'd hate to think what'd happen against some",
      "real competition.",
      "Hurry and catch up to my level!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  DELAY(64)
  FADE_MUSIC(4)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_MIMIC_OF_DOOM2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E775A0, map_14_state_07_08E775A0, EVENT_NOP, EVENT_NOP)
  WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E775AC, map_14_state_07_08E775AC, EVENT_NOP, EVENT_NOP)
  WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE, 4, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
