#include "event_macros.h"
#include "overworld.h"

/* map_12_state_02: map 12 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E6EFA0, map_12_state_02_08E6EFA0, 0x08E6EFAC, 0x08E6EFB8)
  PORTRAIT(10, 0, 8)
  LANGUAGE_TEXT(0, "My big brother isn't here.\n\nHe's investigating the\nMillennium Items.\n\n")
  LANGUAGE_TEXT(1, "Mon grand fr\xe8re\nn'est pas l\xe0.\n\nIl est \xe0 la recherche\ndes Objets du mill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder ist\nnicht hier.\n\nEr studiert die\nMillenniumsgegenst\xe4nde.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello non \xe8 qui.\n\nSta cercando gli\nOggetti Millenari.\n\n")
  LANGUAGE_TEXT(4, "Mi gran hermano\nno est\xe1 aqu\xed.\n\nEst\xe1 investigando los\nObjetos del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(19)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFAC, map_12_state_02_08E6EFAC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "He said there's another\ngroup also looking for\n\nthem.\n\n")
  LANGUAGE_TEXT(1, "D'apr\xe8s lui, un autre\ngroupe est aussi en\n\ntrain de les chercher.\n\n")
  LANGUAGE_TEXT(2, "Er sagte, noch eine andere\nGruppe suche sie.\n\n")
  LANGUAGE_TEXT(3, "Ha detto che pure un altro\ngruppo gli d\xe0 la caccia.\n\n")
  LANGUAGE_TEXT(4, "Dijo que hay otro\ngrupo buscando.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFB8, map_12_state_02_08E6EFB8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The other group searching\nfor the Items call\n\nthemselves the Neo Ghouls.\n\nYou better watch out for\nthem. They sound like\n\ntrouble.\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls sont\naussi \xe0 leur recherche.\n\nFais attention \xe0 eux.\n\n")
  LANGUAGE_TEXT(2, "Auch die Neo Ghouls sind\nhinter ihnen her.\n\nHalte Ausschau nach ihnen\nund nimm dich in Acht.\n\n")
  LANGUAGE_TEXT(3, "Anche i Neo Ghouls\nli stanno cercando.\n\nStai in guardia.\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls\ntambi\xe9n los buscan.\n\nVigila por si los ves..\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFC4, map_12_state_02_08E6EFC4, 0x08E6EFD0, 0x08E6EFE8)
  CHECK_FLAG(46)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFD0, map_12_state_02_08E6EFD0, 0x08E6EFDC, 0x08F0404C)
  PORTRAIT(10, 0, 8)
  LANGUAGE_TEXT(0, "Seto isn't here. But don't\nunderestimate my skills, or\n\nyou're gonna pay big time!\n\n")
  LANGUAGE_TEXT(1, "Mon grand fr\xe8re\nn'est pas l\xe0.\n\nMais c'est pas une\nraison pour m'insulter !\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder ist nicht\nhier. Aber st\xf6r mich nicht!\n\n")
  LANGUAGE_TEXT(3, "Mio fratello non \xe8 qui. Ma\nnon mi mancare di rispetto!\n\n")
  LANGUAGE_TEXT(4, "Mi gran hermano\nno est\xe1 aqu\xed.\n\n\xa1Pero no pases de m\xed!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(13)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFDC, map_12_state_02_08E6EFDC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  PORTRAIT(10, 2, 8)
  LANGUAGE_TEXT(0, "Argh! I can't believe I\nlost!\n\nBut believe me, my big\nbrother won't lose to no\n\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Wouaah !\nTu me mets en col\xe8re !\n\nMon grand fr\xe8re\nne va pas perdre\n\ncontre toi, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Waaah!\nDu machst mich w\xfctend!\n\nMein gro\xdfer Bruder verliert\ngegen keinen {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Insomma! Mi hai\nfatto arrabbiare!\n\nMio fratello non\nperder\xe0 con nessun\n\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Waaah!\n\xa1Me enfadas!\n\n\xa1Mi gran hermano no\nperder\xe1 con ning\xfan\n\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(46)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFE8, map_12_state_02_08E6EFE8, 0x08F04040, 0x08F04040)
  PORTRAIT(10, 0, 8)
  LANGUAGE_TEXT(0, "I'm a busy guy. I don't have\nmuch free time.\n\n")
  LANGUAGE_TEXT(1, "Je n'ai pas tellement\nle temps, tu sais.\n\n")
  LANGUAGE_TEXT(2, "Ich habe nicht so viel Zeit,\nwei\xdft du?\n\n")
  LANGUAGE_TEXT(3, "Non ho tanto tempo, sai.\n\n")
  LANGUAGE_TEXT(4, "No tengo mucho\ntiempo, \xbfsabes?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
