#include "event_macros.h"
#include "overworld.h"

/* map_39_state_01: map 39 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED4A80, map_39_state_01_08ED4A80, 0x08ED4A8C, 0x08ED4A98)
  PLAY_MUSIC(401)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24577)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "L-look!\n\n")
  LANGUAGE_TEXT(1, "R-regardez !\n\n")
  LANGUAGE_TEXT(2, "Sch-schaut!\n\n")
  LANGUAGE_TEXT(3, "G-guardate!\n\n")
  LANGUAGE_TEXT(4, "\xa1M-mirad!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 4, 0)
  DELAY(32)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 144, 112, 0, 0, 0)
  DELAY(32)
  WALK_OBJECT_Y(1, 69)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "It's been a long time,\npartner.\n\n")
  LANGUAGE_TEXT(1, "Ca faisait tr\xe8s\nlongtemps, coll\xe8gue.\n\n")
  LANGUAGE_TEXT(2, "Es ist lange her, Partner.\n\n")
  LANGUAGE_TEXT(3, "Ne \xe8 passato di tempo,\nsocio.\n\n")
  LANGUAGE_TEXT(4, "Ha pasado mucho\ntiempo, socio.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 68)
  WALK_OBJECT_X(13, 76)
  WALK_OBJECT_Y(13, 63)
  MOVE_OBJECT(13, 1, 0, 0)
  WALK_OBJECT_X(14, 76)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I've already snatched the\nMillennium Item here.\n\nIncluding the ones you have,\nthat makes six.\n\nIshizu told me to bring back\nall the Millennium Items.\n\nFork over the Millennium\nItems you have.\n\nWhat are you waiting for?\nGive it!\n\n")
  LANGUAGE_TEXT(1, "Ici, j'ai d\xe9j\xe0 ramass\xe9\nl'Objet du mill\xe9nium.\n\nAvec les tiens, cela\nfait six en tout.\n\nIshizu m'a dit de ramener\ntous les Objets du\n\nmill\xe9nium.\nDonne-moi ceux que tu as.\n\nLes choses vont tourner\nau vinaigre si on ne se\n\nd\xe9p\xeache pas.\n\n")
  LANGUAGE_TEXT(2, "Ich habe den Millenniums-\ngegenstand hier bereits\n\ngefunden.\n\nZusammen mit deinen sind\nes damit sechs.\n\nIshizu sagte, ich solle alle\nMillenniumsgegenst\xe4nde\n\nzur\xfcckbringen. Gib mir\ndeine.\n\nWenn wir uns nicht beeilen,\nwird es b\xf6se enden.\n\n")
  LANGUAGE_TEXT(3, "Qui ho gi\xe0 raccolto\nl'Oggetto Millenario.\n\nCon quelli che gi\xe0\nhai, fanno sei.\n\nIshizu mi ha detto di\nriportare indietro tutti\n\ngli Oggetti Millenari.\nDammi gli Oggetti\n\nMillenari che hai. Se non\nci sbrighiamo, le cose\n\nsi metteranno male.\n\n")
  LANGUAGE_TEXT(4, "Ya he cogido el Objeto\ndel Milenio de aqu\xed.\n\nEso hace seis con los\nque ya tienes.\n\nIshizu me dijo que trajera\ntodos los Objetos del\n\nMilenio.\n\nEntrega los Objetos del\nMilenio que tienes.\n\nLas cosas se van a poner\nfeas si no nos damos prisa.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4A8C, map_39_state_01_08ED4A8C, 0x08ED4AA4, 0x08F04040)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That's right. You did the\nright thing.\n\n")
  LANGUAGE_TEXT(1, "Bravo. Tu fais bien\nde m'\xe9couter.\n\n")
  LANGUAGE_TEXT(2, "Gut. Zusammenarbeit\nist am besten.\n\n")
  LANGUAGE_TEXT(3, "Bene. Ubbidire\n\xe8 la cosa migliore.\n\n")
  LANGUAGE_TEXT(4, "Eso es. El cumplimiento\nes lo mejor.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 1)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AA4, map_39_state_01_08ED4AA4, 0x08ED4AB0, 0x08F0404C)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, 8)
  LANGUAGE_TEXT(0, "Come on, what are you\nwaiting for, you idiot!\n\nHand over the Millennium\nItems!\n\n")
  LANGUAGE_TEXT(1, "Allez, d\xe9p\xeache-toi !\n\nDonne-moi les\nObjets du mill\xe9nium !\n\n")
  LANGUAGE_TEXT(2, "Los, mach schon! Gib mir\nsofort die Millenniums-\n\ngegenst\xe4nde!\n\n")
  LANGUAGE_TEXT(3, "Forza! Dammi subito\ngli Oggetti Millenari!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, ahora! \xa1Entrega\nlos Objetos del Milenio!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wait a second! There's\nsomething wrong about him,\n\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Attends une seconde !\n\nQuelque chose ne\nva pas, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Halt! Da stimmt etwas\nnicht, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Aspetta un attimo!\n{PLAYER}, c'\xe8\n\nqualcosa che non va!\n\n")
  LANGUAGE_TEXT(4, "\xa1Espera un segundo!\n\xa1Algo no anda bien,\n\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wh-what do you mean?\n\nI'm the same ol' dude you\nall know and love!\n\nHow could things go wrong? I\nlook exactly like him!\n\n")
  LANGUAGE_TEXT(1, "Qu-qu'est-ce qui\nse passe ?\n\nJ'ai l'air suspect ?\n\nJe ressemble en tout\npoint \xe0 l'autre Yugi...\n\n")
  LANGUAGE_TEXT(2, "W-was ist los?\n\nSehe ich etwa verd\xe4chtig\naus?\n\nIch sehe doch in jeder\nHinsicht so aus wie der\n\nandere Yugi...\n\n")
  LANGUAGE_TEXT(3, "Be'? Che succede?\nNon vi fidate di me?\n\nAssomiglio in tutto e per\ntutto all'altro Yugi...\n\n")
  LANGUAGE_TEXT(4, "\xbfC-cu\xe1l es el problema?\n\n\xbfHay algo sospechoso\nsobre m\xed?\n\nEn todo, soy como\nel otro Yugi...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My disguise is perfect.\n\n")
  LANGUAGE_TEXT(1, "Mon d\xe9guisement\ndevrait \xeatre parfait.\n\n")
  LANGUAGE_TEXT(2, "Meine Verkleidung m\xfcsste\nperfekt sein.\n\n")
  LANGUAGE_TEXT(3, "Il mio travestimento\ndovrebbe essere perfetto.\n\n")
  LANGUAGE_TEXT(4, "Mi disfraz deber\xeda\nser perfecto.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24577)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Disguise?\n\n")
  LANGUAGE_TEXT(1, "D\xe9guisement ?\n\n")
  LANGUAGE_TEXT(2, "Verkleidung?\n\n")
  LANGUAGE_TEXT(3, "Travestimento?\n\n")
  LANGUAGE_TEXT(4, "\xbfDisfraz?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Uh... No, not a disguise! I\nmeant... Um, I...\n\n")
  LANGUAGE_TEXT(1, "Euh... Mmm, je...\n\n")
  LANGUAGE_TEXT(2, "\xc4h... \xc4hm, ich...\n\n")
  LANGUAGE_TEXT(3, "Ecco... Ehm... Io...\n\n")
  LANGUAGE_TEXT(4, "Uh... Um, yo...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 1, 4, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(0, 1, 4, 0)
  MOVE_OBJECT(13, 1, 4, 0)
  MOVE_OBJECT(14, 1, 4, 0)
  DELAY(16)
  MOVE_OBJECT(1, 1, 4, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(0, 1, 4, 0)
  MOVE_OBJECT(13, 1, 4, 0)
  MOVE_OBJECT(14, 1, 4, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Argh! My cover is blown! But\nit doesn't matter!\n\n")
  LANGUAGE_TEXT(1, "Mince ! Je me suis vendu !\nMais \xe7a ne fait rien !\n\n")
  LANGUAGE_TEXT(2, "Ts! Meine Tarnung ist dahin!\nAber das ist unwichtig!\n\n")
  LANGUAGE_TEXT(3, "Accidenti! La mia copertura\n\xe8 saltata! Ma non importa!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vaya! \xa1Me han pillado!\n\xa1Pero no importa!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(330)
  SWAP_OBJECT_SPRITE(1, 27)
  DELAY(32)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Gehehehehe!\n\nI am the Mimic of Doom!\n\nWe'll duel for the\nMillennium Items!\n\n")
  LANGUAGE_TEXT(1, "Gui hi hi hi !\n\nJe suis le Mimic of Doom !\n\nOn va se battre en duel pour\nles Objets du mill\xe9nium !\n\n")
  LANGUAGE_TEXT(2, "Gehehehehe!\n\nIch bin der Mimic of Doom!\n\nWir duellieren uns um\ndie Millenniumsgegenst\xe4nde!\n\n")
  LANGUAGE_TEXT(3, "Eheheheheh!\n\nSono il Mimic of Doom!\n\nDuelleremo per gli\nOggetti Millenari!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jehehehehe!\n\n\xa1Soy el Mimic of Doom!\n\n\xa1Lucharemos por los\nObjetos del Milenio!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(50)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4AB0, map_39_state_01_08ED4AB0, 0x08F04250, 0x08F04040)
  PORTRAIT(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_MIMIC_OF_DOOM_DEFEATED, 8)
  LANGUAGE_TEXT(0, "Nooooooo! I can't lose!\n\n")
  LANGUAGE_TEXT(1, "Nooooooon !\nJe ne peux pas perdre !\n\n")
  LANGUAGE_TEXT(2, "Neiiiin!\nIch kann nicht verlieren!\n\n")
  LANGUAGE_TEXT(3, "Nooooooo!\nNon posso perdere!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nooooooo!\n\xa1No puedo perder!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 42, 70, 0, 0, 0)
  SLIDE_OBJECT(3, 1, 2)
  WALK_OBJECT_X(1, 124)
  SHOW_OBJECT(1, 144, 112, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(0, 48)
  WALK_OBJECT_X(13, 58)
  WALK_OBJECT_X(14, 58)
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 144, 112, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(406)
  PLAY_MUSIC(280)
  SHOW_OBJECT(2, 36, 69, 0, 1, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Six Millennium Items... You\nare to be praised.\n\nI hope you will not give up\nuntil you defeat Reshef...\n\nAnd save Pegasus from the\ndarkness...\n\n")
  LANGUAGE_TEXT(1, "Bravo !\nSix Objets du mill\xe9nium...\n\nMais il ne faut pas se\nlaisser aller tant que\n\nReshef n'est pas battu\n\net que Pegasus n'a pas \xe9t\xe9\nsauv\xe9 des t\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "Sechs Millenniumsgegen-\nst\xe4nde...\n\nDaf\xfcr habt ihr Lob verdient.\n\nIch hoffe, ihr werdet nicht\nruhen, bis Reschef besiegt\n\nund Pegasus vor der Fins-\nternis gerettet ist...\n\n")
  LANGUAGE_TEXT(3, "Sei Oggetti Millenari...\nI miei complimenti.\n\nSpero che continuerete\nfinch\xe9 Reshef non sar\xe0\n\nsconfitto... E Pegasus\nsalvato dall'oscurit\xe0...\n\n")
  LANGUAGE_TEXT(4, "Seis Objetos del Milenio...\nHay que alabarte.\n\nEspero que no cej\xe9is hasta\nque Reshef sea vencido...\n\nY Pegasus salvado de\nla oscuridad...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "For Pegasus is also a\nvictim.\n\nHe has been swallowed by\nReshef's powers of\n\ndarkness.\n\nYou must save the world and\nPegasus from the shadows...\n\n")
  LANGUAGE_TEXT(1, "Pegasus est\naussi une victime.\n\nIl a \xe9t\xe9 englouti par\nles t\xe9n\xe8bres de Reshef.\n\nSauvez le monde et\nPegasus des t\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "Auch Pegasus ist ein Opfer.\n\nEr wurde von Reschefs\nFinsternis mitgerissen.\n\nRettet die Welt und\nbewahrt Pegasus\n\nvor der Dunkelheit...\n\n")
  LANGUAGE_TEXT(3, "Anche Pegasus \xe8\nuna vittima.\n\n\xc8 stato catturato dal-\nl'oscurit\xe0 di Reshef.\n\nSalvate il mondo e\nPegasus dall'oscurit\xe0...\n\n")
  LANGUAGE_TEXT(4, "Pegasus, es tambi\xe9n\nuna v\xedctima..\n\nHa sido engullido por la\noscuridad de Reshef.\n\nSalvad al mundo y a Pegasus\nde la oscuridad...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(4, 2)
  SHOW_OBJECT(2, 144, 112, 0, 0, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Millennium Scale...\n\nWe now have six Millennium\nItems.\n\nQuick, let's get back to\nIshizu!\n\n")
  LANGUAGE_TEXT(1, "La Balance du mill\xe9nium...\n\nMaintenant, nous avons\nsix Objets du mill\xe9nium.\n\nVite, retournons voir\nIshizu !\n\n")
  LANGUAGE_TEXT(2, "Die Millenniumsschale...\n\nWir haben jetzt sechs\nMillenniumsgegenst\xe4nde.\n\nSchnell zur\xfcck zu\nIshizu!\n\n")
  LANGUAGE_TEXT(3, "La Bilancia Millenaria...\n\nOra abbiamo sei\nOggetti Millenari.\n\nSbrighiamoci,\ntorniamo da Ishizu!\n\n")
  LANGUAGE_TEXT(4, "Las Pesas del Milenio...\n\nAhora tenemos seis\nObjetos del Milenio.\n\n\xa1R\xe1pido, regresemos\ndonde Ishizu!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_MIMIC_OF_DOOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4A98, map_39_state_01_08ED4A98, 0x08ED4AA4, 0x08F04040)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What? I said hand it over!\nNow do it!\n\n")
  LANGUAGE_TEXT(1, "Je crois avoir dit que les\nchoses tourneraient au\n\nvinaigre si on ne se\nd\xe9p\xeache pas.\n\n")
  LANGUAGE_TEXT(2, "Sagte ich nicht, es wird\nb\xf6se enden, wenn wir uns\n\nnicht beeilen?\n\n")
  LANGUAGE_TEXT(3, "Guarda che se non ci\nsbrighiamo, le cose\n\nsi metteranno male.\nMi hai sentito?\n\n")
  LANGUAGE_TEXT(4, "\xbfNo dije que las cosas\nse pondr\xedan feas si no\n\nnos d\xe1bamos prisa?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 1)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()
