#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_15: map 6 state 15 */

LOAD_SPRITE(1, SPRITE_TRISTAN)
LOAD_SPRITE(2, SPRITE_DUKE)
LOAD_SPRITE(3, SPRITE_SERENITY)
LOAD_SPRITE(4, SPRITE_LUCKY)
LOAD_SPRITE(5, SPRITE_TEA)
LOAD_SPRITE(6, SPRITE_GRANDPA_MUTO)
LOAD_SPRITE(7, SPRITE_KID_1)
LOAD_SPRITE(8, SPRITE_KID_2)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "The happy expressions on the\n"
    "children's faces...\n\n"
    "Those are the faces of the\n"
    "Town of Domino at peace.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
WALK_OBJECT_X(SPRITE_KID_1, 96)
WALK_OBJECT_X(SPRITE_KID_2, 96)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_1, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Hi! Can I see your cards?\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_2, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Do you have any new cards?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_GRANDPA_MUTO, DIRECTION_RIGHT, 0, 0)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "As a matter of fact, some\n"
    "rare cards have come in.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_1, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Yeah! I'll buy some!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_2, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Hey, no fair! They're mine!\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "There's no need to fight.\n"
    "I have two of each, so you\n\n"
    "both can get one.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_1, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Okay!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_KID_2, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Sure!\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Fine, let's head inside.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_KID_1, 75)
WALK_OBJECT_Y(SPRITE_KID_1, 39)
SHOW_OBJECT(SPRITE_KID_1, 128, 96, 0, 0, 0)
WALK_OBJECT_X(SPRITE_KID_2, 84)
WALK_OBJECT_Y(SPRITE_KID_2, 44)
WALK_OBJECT_X(SPRITE_KID_2, 75)
WALK_OBJECT_Y(SPRITE_KID_2, 39)
SHOW_OBJECT(SPRITE_KID_2, 128, 96, 0, 0, 0)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_GRANDPA_MUTO, DIRECTION_LEFT, 0, 0)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "The boys will be back soon.\n"
    "There's no doubt.\n\n"
    "Isn't that right, Tea?\n\n"
)
TALK(PORTRAIT_TEA, EXPRESSION_TEA_SAD, PORTRAIT_LEFT,
    "...Yes. You're right.\n\n"
)
TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I'll wait a little while\n"
    "longer...\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yes, yes. That would be\n"
    "best.\n\n"
)
WALK_OBJECT_Y(SPRITE_GRANDPA_MUTO, 39)
SHOW_OBJECT(SPRITE_GRANDPA_MUTO, 128, 96, 0, 0, 0)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Though in all honesty, I'm\n"
    "getting kinda worried.\n\n"
)
TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, PORTRAIT_LEFT,
    "L-look at that...\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "That's KaibaCorp's\n"
    "helicopter.\n\n"
)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_TRISTAN | SPRITE_DUKE | SPRITE_SERENITY | SPRITE_LUCKY | SPRITE_TEA)
FADE_SCREEN(8)
WARP(LOCATION_CLOCK_TOWER_SQUARE_NORTHWEST, 19, 0, 0)
