#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_57_state_04: map 57 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EFB450, map_57_state_04_08EFB450, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_KAIBAMAN)
  LOAD_SPRITE(2, SPRITE_DEEPSEA_WARRIOR)
  LOAD_SPRITE(3, SPRITE_NIGHTMARE_PENGUIN)
  LOAD_SPRITE(4, SPRITE_JUDGE_MAN)
  LOAD_SPRITE(5, SPRITE_ROBOTIC_KNIGHT)
  LOAD_SPRITE(6, SPRITE_JINZO)
  LOAD_SPRITE(7, SPRITE_KID_1)
  LOAD_SPRITE(8, SPRITE_KID_2)
  LOAD_SPRITE(9, SPRITE_KID_3)
  LOAD_SPRITE(10, SPRITE_KID_3_2)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_7, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  TEXT
  (
      "Go for it, Kaibaman!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_8, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  TEXT
  (
      "Don't give up, Kaibaman!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_344)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "Justice just rules! I am\n"
      "victorious in victory!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_DRAGON_MASTER_KNIGHT_FULL_ART)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "Dragon Sabre Blast!\n\n"
  )
  PLAY_MUSIC(MUSIC_342)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_DRAGON_MASTER_KNIGHT_ATTACK)
  DELAY(16)
  FADE_MUSIC(16)
  FADE_SCREEN(16)
  WARP(LOCATION_DOMINO_PIER_CASINO_MAIN_ROOM, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
