#include "event_macros.h"
#include "overworld.h"

/* map_00_state_07: map 0 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E34BBC, map_00_state_07_08E34BBC, 0x08E34BD4, 0x08E34BE0)
  CHECK_FLAG(70)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BD4, map_00_state_07_08E34BD4, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "It is always important to\nrelax and take a step away\n\nfrom your main mission.\n\nFor the road of destiny is\nnot a straight path.\n\nThere are many side roads\nand streets that you can\n\nwander along.\n\nThe more roads you take, the\nmore you will see of the\n\nworld, and the more you will\nlearn.\n\nHowever, Reshef is gaining\npower far faster than\n\nexpected.\n\nWe must return to the main\npath. Hurry and resurrect\n\nthe Egyptian God Cards.\n\nThe last Egyptian God Card\nremaining is The Winged\n\nDragon of Ra.\n\nIn order to restore the\nfinal Egyptian God Card\n\nfrom stone...\n\nPlease hurry and obtain the\nnext Millennium Item.\n\nThe next Millennium Item\nis.")
  LANGUAGE_TEXT(1, "Il faut parfois savoir\nse d\xe9tendre.\n\nTon destin ne suit pas\ntoujours une ligne droite.\n\nParfois, il faut prendre\ndes chemins d\xe9tourn\xe9s.\n\nEt ce n'est pas forc\xe9ment\nune mauvaise chose.\n\nMais Reshef devient\nde plus en plus puissant.\n\nNous devons vite restaurer\nles cartes de dieux.\n\nLa derni\xe8re carte sacr\xe9e\nest le Dragon Ail\xe9 de Ra.\n\nPour restaurer la derni\xe8re\ncarte de dieux... il faut\n\nvite obtenir le prochain\nObjet du mill\xe9nium.\n\nIl se trouve l\xe0 o\xf9 des\nformes pr\xe9historiques")
  LANGUAGE_TEXT(2, "Manchmal muss man\neinfach abschalten.\n\nDas Schicksal geht nicht\nimmer auf geraden Wegen.\n\nMitunter ist selbst ein\nkleiner Umweg vonn\xf6ten.\n\nDas muss nicht unbedingt\nschlecht sein.\n\nAber Reschef gewinnt\nschneller als erwartet an\n\nMacht.\n\nWir m\xfcssen uns sputen und\ndie G\xf6tterkarten\n\nwiederherstellen.\n\nDie eine heilige Karte,\ndie noch verbleibt, ist der\n\ngefl\xfcgelte Drache von Ra.\n\nUm die letzte G\xf6tterkarte\naus dem Stein zu\n\nbefreien, such schnell den")
  LANGUAGE_TEXT(3, "A volte \xe8 necessario\nrilassarsi. Il proprio\n\ndestino non sempre\nsegue una strada\n\ndiritta. A volte bisogna\nanche vagare. Non \xe8 detto\n\nche ci\xf2 sia negativo. Ma\nReshef sta acquistando\n\npotere molto pi\xf9 in fretta\ndel previsto. Dobbiamo\n\nsbrigarci a risuscitare le\ncarte divine.\n\nLa sola carta sacra mancante\n\xe8 il Drago Alato di Ra.\n\nPer ripristinare la carta\ndivina finale dalla\n\npietra...\n\nRecupera in fretta il\nprossimo Oggetto\n\nMillenario, che si trova.")
  LANGUAGE_TEXT(4, "Es necesario relajarse\na veces.\n\nTu destino no siempre\nsigue una l\xednea recta.\n\nA veces, es necesario\nzigzaguear.\n\nHacerlo no tiene que\nser algo malo.\n\nPero Reshef est\xe1 recu-\nperando poder m\xe1s\n\nr\xe1pido de lo esperado.\nHemos de correr y\n\nresucitar las cartas\nde los dioses.\n\nLa carta sagrada que\nqueda es el Drag\xf3n\n\nAlado de Ra.\n\nPara recuperar de su estado\np\xe9treo a la \xfaltima carta...\n\nObt\xe9n el siguiente Objeto\ndel Milenio r\xe1pidamente.\n\nEl siguiente Objeto del\nMilenio es.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, "")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, "")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\n\nIn a place where prehistoric\nlife forms are preserved in\n\nrock...\n\nA fossil excavation site in\nCanada.\n\n")
  LANGUAGE_TEXT(1, "\n\nsont pr\xe9serv\xe9es\ndans la roche.\n\nUn site d'excavation de\nfossiles au Canada.\n\n")
  LANGUAGE_TEXT(2, "\nn\xe4chsten Millenniums-\n\ngegenstand. Du findest\nihn dort, wo pr\xe4his-\n\ntorisches Leben in Stein\nverewigt ist.\n\nAn einer Fundst\xe4tte f\xfcr\nFossilien in Kanada.\n\n")
  LANGUAGE_TEXT(3, "\ndove forme di vita\n\npreistorica sono conservate\nnella pietra.\n\nUn sito di scavi fossili\nin Canada.\n\n")
  LANGUAGE_TEXT(4, "\n\nDonde las formas pre-\nhist\xf3ricas est\xe1n con-\n\nservadas en piedra.\n\nUn yacimiento de f\xf3siles\nen Canad\xe1.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(70)
  SET_FLAG(252)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BE0, map_00_state_07_08E34BE0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "The Dark Being was\nresurrected by Sol\n\nChevalsky...\n\nNo, not Sol Chevalsky, but\nPegasus.\n\nTo imprison Reshef, we need\none more Egyptian God Card.\n\nWe need the power of The\nWinged Dragon of Ra.\n\nWe must resurrect the card\nfrom stone.\n\nPlease find the Millennium\nItems to restore it.\n\nThe fifth Millennium Item is\nin Canada among fossils.\n\nYou will find it at a fossil\nexcavation site.\n\n")
  LANGUAGE_TEXT(1, "L'Etre des t\xe9n\xe8bres,\nressuscit\xe9 par Sol\n\nChevalsky... Non, c'est\nPegasus, n'est-ce pas ?\n\nPour emprisonner Reshef,\nil nous faut encore\n\nune carte de dieu.\nNous avons besoin\n\nde la puissance\ndu Dragon Ail\xe9 de Ra.\n\nIl faut restaurer\ncette carte p\xe9trifi\xe9e.\n\nTrouve l'Objet du mill\xe9nium\npour la restaurer.\n\nLe {BYTE_8254}\xe8me Objet du mill\xe9nium\nse trouve au Canada,\n\ndans un site d'excavation\ndes fossiles.\n\n")
  LANGUAGE_TEXT(2, "Der Dunkle wurde von\nSol Chevalsky wieder zum\n\nLeben erweckt... Nein, er\nist ja Pegasus, oder?\n\nUm Reschef zu fangen,\nben\xf6tigen wir noch eine\n\nG\xf6tterkarte.\n\nWir brauchen die Macht des\ngefl\xfcgelten Drachen von Ra.\n\nWir m\xfcssen die Karte aus dem\nStein befreien.\n\nBitte such den Millenniums-\ngegenstand, der die Karte\n\nfreisetzen kann.\n\nDer f\xfcnfte Millenniums-\ngegenstand liegt\n\nzwischen kanadischen\nFossilien.\n\nDu findest ihn an\neiner Ausgrabungsst\xe4tte.\n\n")
  LANGUAGE_TEXT(3, "Il Tenebroso risuscitato\nda Sol Chevalsky...\n\nNo, \xe8 Pegasus, vero?\n\nPer imprigionare Reshef,\nci serve un'altra carta\n\ndivina. Ci serve la potenza\ndel Drago Alato di Ra.\n\nDobbiamo risuscitare la\ncarta dalla pietra.\n\nTrova l'Oggetto Millenario\nper ripristinarla.\n\nIl quinto Oggetto Millenario\n\xe8 in Canada, tra i\n\nfossili. Lo troverai in\nun sito di scavi fossili.\n\n")
  LANGUAGE_TEXT(4, "El Ser Oscuro resucitado\npor Sol Chevalsky...\n\nNo, es Pegasus, \xbfno?\n\nPara encerrar a Reshef,\nnecesitamos una carta\n\ndel dios m\xe1s.\n\nNecesitamos el poder del\nDrag\xf3n Alado de Ra.\n\nDebemos restaurar la carta\nde su estado p\xe9treo.\n\nPor favor, encuentra el\nObjeto del Milenio para\n\nrestaurarla.\n\nEl quinto Objeto del Milenio\nest\xe1 en Canad\xe1,\n\nentre f\xf3siles.\n\nLo encontrar\xe1s en un\nyacimiento de f\xf3siles.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BC8, map_00_state_07_08E34BC8, 0x08E34BD4, 0x08E34BEC)
  CHECK_FLAG(70)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BEC, map_00_state_07_08E34BEC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Please. Hurry to the fossil\nexcavation site.\n\nReshef the Dark Being will\nsoon engulf the world.\n\n")
  LANGUAGE_TEXT(1, "D\xe9p\xeache-toi d'aller au site\nd'excavation des fossiles.\n\nReshef, l'Etre des t\xe9n\xe8bres\nva bient\xf4t plonger le monde\n\ndans les t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Bitte begib dich schnell\nzur geolog.\n\nAusgrabungsst\xe4tte.\n\nReschef der Dunkle wird\nbald die Welt vernichten.\n\n")
  LANGUAGE_TEXT(3, "Ti prego, recati in fretta\nal sito di scavi fossili.\n\nIl mondo cadr\xe0 presto\nnelle grinfie di\n\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Por favor, corre al\nyacimiento de f\xf3siles.\n\nReshef, el Ser Oscuro pronto\nacabar\xe1 con el mundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
