#include "event_macros.h"
#include "overworld.h"

/* map_06_state_12: map 6 state 12 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CDA4, map_06_state_12_08E5CDA4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(33)
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(0, 12)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(3, 44)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, 1)
  LANGUAGE_TEXT(0, "Tristan!\n\n")
  LANGUAGE_TEXT(1, "Tristan !\n\n")
  LANGUAGE_TEXT(2, "Tristan!\n\n")
  LANGUAGE_TEXT(3, "Tristan!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tristan!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 52)
  DELAY(16)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 1)
  LANGUAGE_TEXT(0, "Ukiiii!\n\n")
  LANGUAGE_TEXT(1, "Ukiiii !\n\n")
  LANGUAGE_TEXT(2, "Ukiiii!\n\n")
  LANGUAGE_TEXT(3, "Ukiiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiiii!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I'm so glad you found him!\n\n")
  LANGUAGE_TEXT(1, "Je suis si contente, vous\nl'avez enfin retrouv\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Ich bin so froh, dass ihr\nihn gefunden habt!\n\n")
  LANGUAGE_TEXT(3, "Sono felicissima che lo\nabbiate trovato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Estoy tan contenta de\nque lo hay\xe1is encontrado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(14, 40)
  WALK_OBJECT_X(14, 60)
  DELAY(16)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Hey, Tristan! That's enough!\nGet away from Serenity.\n\n")
  LANGUAGE_TEXT(1, "H\xe9, Tristan !\nCa suffit !\n\nLaisse Serenity\ntranquille.\n\n")
  LANGUAGE_TEXT(2, "He, Tristan! Das reicht!\nWeg von Serenity.\n\n")
  LANGUAGE_TEXT(3, "Ehi, Tristan! Ora basta!\nLascia stare Serenity!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hey, Tristan! \xa1Ya vale!\nAl\xe9jate de Serenity.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Why, you...\n\n")
  LANGUAGE_TEXT(1, "Pourquoi, tu...\n\n")
  LANGUAGE_TEXT(2, "Warum, du...\n\n")
  LANGUAGE_TEXT(3, "Insomma, tu...\n\n")
  LANGUAGE_TEXT(4, "Por qu\xe9, t\xfa...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 36)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(14, 52)
  DELAY(8)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_ANGRY, 1)
  LANGUAGE_TEXT(0, "Stop Joey!\n\nHasn't Tristan suffer enough\nalready?\n\n")
  LANGUAGE_TEXT(1, "Arr\xeate, grand fr\xe8re !\n\nTristan souffre d\xe9j\xe0\nassez comme \xe7a.\n\n")
  LANGUAGE_TEXT(2, "H\xf6r auf, gro\xdfer Bruder!\n\nTristan leidet furchtbar\nin seiner jetzigen Lage.\n\n")
  LANGUAGE_TEXT(3, "Smettila, fratello!\n\nTristan soffre gi\xe0\nabbastanza cos\xec.\n\n")
  LANGUAGE_TEXT(4, "\xa1Detente, gran hermano!\n\nTristan est\xe1 sufriendo\nmucho as\xed.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Yeah, but...\n\n")
  LANGUAGE_TEXT(1, "Ouais, mais...\n\n")
  LANGUAGE_TEXT(2, "Ja, aber...\n\n")
  LANGUAGE_TEXT(3, "S\xec, ma...\n\n")
  LANGUAGE_TEXT(4, "S\xed, pero...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(326)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 1)
  LANGUAGE_TEXT(0, "Ukiii ukiii!\n\n")
  LANGUAGE_TEXT(1, "Ukiii ukiii !\n\n")
  LANGUAGE_TEXT(2, "Ukiii ukiii!\n\n")
  LANGUAGE_TEXT(3, "Ukiii ukiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiii ukiii!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "You're starting to tick me\noff, Tristan...\n\n")
  LANGUAGE_TEXT(1, "C'est aga\xe7ant...\n\n")
  LANGUAGE_TEXT(2, "Das hier ist\nunversch\xe4mt...\n\n")
  LANGUAGE_TEXT(3, "\xc8 insopportabile...\n\n")
  LANGUAGE_TEXT(4, "As\xed se est\xe1\nempeorando...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 48)
  WALK_OBJECT_X(0, 60)
  WALK_OBJECT_Y(13, 40)
  WALK_OBJECT_X(13, 60)
  DELAY(64)
  SET_OBJECT_POSITION(5, 74, 40, 0)
  WALK_OBJECT_Y(5, 44)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Oh? That monkey robot...\n\n")
  LANGUAGE_TEXT(1, "Oh ?\nCe singe robot...\n\n")
  LANGUAGE_TEXT(2, "Oh?\nDer Affenroboter...\n\n")
  LANGUAGE_TEXT(3, "Ma quella scimmia robot...\n\n")
  LANGUAGE_TEXT(4, "\xbfOh?\nEse robot mono...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, 1)
  LANGUAGE_TEXT(0, "Grandpa, this monkey robot\nis actually Tristan.\n\n")
  LANGUAGE_TEXT(1, "Grand-p\xe8re, ce singe robot,\nen r\xe9alit\xe9, c'est Tristan.\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfvater, dieser Affen-\nroboter ist Tristan.\n\n")
  LANGUAGE_TEXT(3, "Nonno, questa scimmia\nrobot in realt\xe0 \xe8 Tristan.\n\n")
  LANGUAGE_TEXT(4, "Abuelo, este robot\nmono es Tristan.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 32)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yugi, what on earth are you\nsaying?\n\n")
  LANGUAGE_TEXT(1, "Yugi, mais qu'est-ce\nque tu veux dire par l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Yugi, was zum Teufel\nsagst du da?\n\n")
  LANGUAGE_TEXT(3, "Yugi, ma che dici?\n\n")
  LANGUAGE_TEXT(4, "Yugi, \xbfqu\xe9 diablos\ndices?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, 1)
  LANGUAGE_TEXT(0, "I know it's hard to believe.\n\nBut it's true.\n\n")
  LANGUAGE_TEXT(1, "Je sais, c'est\ndifficile \xe0 croire.\n\nMais c'est vrai.\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf, es ist kaum\nzu glauben.\n\nAber es ist wahr.\n\n")
  LANGUAGE_TEXT(3, "Lo so che \xe8 difficile da\ncredere, ma \xe8 la verit\xe0.\n\n")
  LANGUAGE_TEXT(4, "S\xe9 que es dif\xedcil de\ncreer.\n\nPero as\xed es.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I'll prove it to ya.\n\n")
  LANGUAGE_TEXT(1, "Papy, je vais\nte le prouver.\n\n")
  LANGUAGE_TEXT(2, "Opa, ich beweise es dir.\n\n")
  LANGUAGE_TEXT(3, "Nonno, te ne dar\xf2 la prova.\n\n")
  LANGUAGE_TEXT(4, "Abuelo, te lo\ndemostrar\xe9.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Tristan, if you can under-\nstand me, howl three times.\n\n")
  LANGUAGE_TEXT(1, "Tristan ! Si tu me com-\nprends, crie {BYTE_8252} fois.\n\n")
  LANGUAGE_TEXT(2, "He, Tristan, wenn du mich\nverstehst, ruf dreimal.\n\n")
  LANGUAGE_TEXT(3, "Ehi, Tristan, se mi\ncapisci, grida tre volte.\n\n")
  LANGUAGE_TEXT(4, "Hey, Tristan, si me\nentiendes, grita\n\ntres veces.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 1)
  LANGUAGE_TEXT(0, "Uki! Uki!\nUkiki!\n\n")
  LANGUAGE_TEXT(1, "Uki ! Uki !\nUkiki !\n\n")
  LANGUAGE_TEXT(2, "Uki! Uki!\nUkiki!\n\n")
  LANGUAGE_TEXT(3, "Uki! Uki! Ukiki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki! \xa1Uki!\n\xa1Ukiki!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "And that's all she wrote.\n\n")
  LANGUAGE_TEXT(1, "Tu vois, grand-p\xe8re ?\nAlors, tu as compris ?\n\n")
  LANGUAGE_TEXT(2, "Siehst du, Opa?\nVerstehst du jetzt?\n\n")
  LANGUAGE_TEXT(3, "Visto, nonno? Ora\nci credi?\n\n")
  LANGUAGE_TEXT(4, "\xbfVes, abuelo?\n\xbfLo entiendes ahora?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hohohohoho!\n\n")
  LANGUAGE_TEXT(1, "Ho ho ho ho !\n\n")
  LANGUAGE_TEXT(2, "Hohohohoho!\n\n")
  LANGUAGE_TEXT(3, "Ohohohoho!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajajaja!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24589)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 1)
  LANGUAGE_TEXT(0, "Wh-what's the matter,\nGrandpa?\n\n")
  LANGUAGE_TEXT(1, "Q-qu'est-ce qui se\npasse, Grand-p\xe8re ?\n\n")
  LANGUAGE_TEXT(2, "Was ist denn daran so\nlustig, Gro\xdfvater?\n\n")
  LANGUAGE_TEXT(3, "Che c'\xe8 che non va,\nnonno?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 ocurre,\nabuelo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You kids are too much.\n\nThat monkey robot was one of\nthe products I was selling\n\nin my store.\n\nBut since no one bought it,\nI was playing with it.\n\n")
  LANGUAGE_TEXT(1, "Je voulais justement\nte le demander.\n\nCe singe robot est\nune marchandise.\n\nMais puisque personne\nne l'avait achet\xe9,\n\nje jouais avec lui.\n\n")
  LANGUAGE_TEXT(2, "Das m\xf6chte ich euch\nfragen.\n\nDieser Affenroboter ist\nWare.\n\nAber da ihn niemand kaufte,\nhabe ich damit gespielt.\n\n")
  LANGUAGE_TEXT(3, "Lo voglio chiedere a voi.\nQuella scimmia robot \xe8\n\nuna merce. Ma dato che\nnessuno l'ha comprata,\n\nio ci stavo giocando.\n\n")
  LANGUAGE_TEXT(4, "Eso es lo que yo\nquiero saber.\n\nEse mono robot\nes mercanc\xeda\n\nPero como nadie lo compr\xf3,\nestaba jugando con \xe9l.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "B-but... It understood\neverything I said.\n\n")
  LANGUAGE_TEXT(1, "M-mais... Il comprenait\nce que je lui disais.\n\n")
  LANGUAGE_TEXT(2, "A-aber... Er hat mich doch\nverstanden.\n\n")
  LANGUAGE_TEXT(3, "Ma come... Capiva\nci\xf2 che le dicevo.\n\n")
  LANGUAGE_TEXT(4, "P-pero... Entendi\xf3 lo\nque le dec\xeda.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That's because I programmed\nit so it would.\n\nI was wondering where it\nwent, but I'm glad to have\n\nit back.\n\nCome on, monkey robot. Let's\ngo back to the shop!\n\n")
  LANGUAGE_TEXT(1, "C'est parce que je l'ai\nprogramm\xe9 comme \xe7a.\n\nJe me demandais\no\xf9 il \xe9tait all\xe9.\n\nEh bien, je suis content de\nvoir qu'il est de retour\n\nici.\n\nAllez, singe robot,\nretourne au magasin !\n\n")
  LANGUAGE_TEXT(2, "Weil ich ihn so pro-\ngrammiert habe.\n\nIch habe mich schon ge-\nwundert, wo er steckt.\n\nAber es ist sch\xf6n,\nihn wiederzuhaben.\n\nKomm, Affenroboter,\nzur\xfcck in den Laden!\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 l'ho programmata\nio per farlo.\n\nMi chiedevo dove\nfosse finita.\n\nBe', sono contento che\nsia rientrata a casa.\n\nForza, scimmia robot,\ntorniamo in negozio!\n\n")
  LANGUAGE_TEXT(4, "Eso es porque lo\nprogram\xe9 as\xed.\n\nMe preguntaba\nd\xf3nde estaba.\n\nBueno, est\xe1 bien\nque haya vuelto.\n\nVamos, mono robot,\nde vuelta a la tienda.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 40)
  SET_OBJECT_POSITION(5, 128, 128, 0)
  DELAY(32)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  MOVE_OBJECT(3, 1, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(64)
  PLAY_MUSIC(272)
  REACTION(3, 24589)
  PLAY_MUSIC(274)
  REACTION(4, 2)
  DELAY(32)
  WALK_OBJECT_X(4, 80)
  DELAY(16)
  PLAY_MUSIC(31)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hi, guys! What are you all\ndoing here?\n\n")
  LANGUAGE_TEXT(1, "Salut, les mecs !\n\nQu'est-ce que vous\nfaites tous ici ?\n\n")
  LANGUAGE_TEXT(2, "Hallo ihr! Was macht\nihr alle hier?\n\n")
  LANGUAGE_TEXT(3, "Salve, ragazzi! Che ci\nfate tutti qui?\n\n")
  LANGUAGE_TEXT(4, "\xa1Hola, chicos! \xbfQu\xe9\nhac\xe9is todos aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24589)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(3, 3, 0, 0)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, 0)
  LANGUAGE_TEXT(0, "Huh, what? Why are you all\nlooking at me weird?\n\n")
  LANGUAGE_TEXT(1, "Hein, quoi ?\n\nPourquoi est-ce que vous me\nregardez si bizarrement ?\n\n")
  LANGUAGE_TEXT(2, "Was ist los? Warum schaut\nihr mich alle so an?\n\n")
  LANGUAGE_TEXT(3, "Ehi, e allora? Perch\xe9 mi\nguardate in quel modo?\n\n")
  LANGUAGE_TEXT(4, "Eh, \xbfqu\xe9? \xbfPor qu\xe9\nme mir\xe1is as\xed?\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(14, 72)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "You... Where in the world\nwere you?\n\n")
  LANGUAGE_TEXT(1, "Toi... O\xf9 diable\n\xe9tais-tu pass\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Du... Wo zum Teufel\nhast du gesteckt?\n\n")
  LANGUAGE_TEXT(3, "Tu... Si pu\xf2 sapere\ndove cavolo eri finito?\n\n")
  LANGUAGE_TEXT(4, "T\xfa...\n\xbfD\xf3nde diablos estabas?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, 8)
  LANGUAGE_TEXT(0, "I... I had the munchies, so\nI went out for some food.\n\n")
  LANGUAGE_TEXT(1, "Je... cherchais juste\nquelque chose \xe0 manger.\n\n")
  LANGUAGE_TEXT(2, "Ich... Ich hatte Hunger und\nwar deshalb einkaufen.\n\n")
  LANGUAGE_TEXT(3, "Ero solo... uscito\na mangiare qualcosa.\n\n")
  LANGUAGE_TEXT(4, "Yo... Sal\xed a comer algo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "You idiot! After we went ape\nover you!\n\n")
  LANGUAGE_TEXT(1, "On s'est fait du\nsouci \xe0 cause de toi !\n\n")
  LANGUAGE_TEXT(2, "Du... Wir haben uns vor\nSorge verr\xfcckt gemacht!\n\n")
  LANGUAGE_TEXT(3, "Razza di... Hai idea di come\nci hai fatto preoccupare?\n\n")
  LANGUAGE_TEXT(4, "T\xfa...\n\n\xa1Nos volvimos micos\nbusc\xe1ndote!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, 8)
  LANGUAGE_TEXT(0, "Wh-what are you talking\nabout?\n\n")
  LANGUAGE_TEXT(1, "Mais... De quoi\nparlez-vous ?\n\n")
  LANGUAGE_TEXT(2, "W-wovon sprecht ihr?\n\n\n")
  LANGUAGE_TEXT(3, "Ma... ma di cosa\nstate parlando?\n\n")
  LANGUAGE_TEXT(4, "\xbfDe q-qu\xe9 habl\xe1is?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Then this monkey robot is\nreally just a robot?\n\n")
  LANGUAGE_TEXT(1, "Alors ce singe robot\nn'est en fait qu'un robot ?\n\n")
  LANGUAGE_TEXT(2, "Dann ist dieser Affenroboter\nalso wirklich nur...\n\nein Roboter?\n\n")
  LANGUAGE_TEXT(3, "Allora questa scimmia robot\n\xe8 davvero solo un robot?\n\n")
  LANGUAGE_TEXT(4, "Entonces, \xbfese mono\nrobot es s\xf3lo un robot?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 1)
  LANGUAGE_TEXT(0, "Ukikikikikiii!\n\n")
  LANGUAGE_TEXT(1, "Ukikikikikiii !\n\n")
  LANGUAGE_TEXT(2, "Ukikikikikiii!\n\n")
  LANGUAGE_TEXT(3, "Ukikikikikiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukikikikikiii!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 74)
  WALK_OBJECT_Y(1, 40)
  SET_OBJECT_POSITION(1, 128, 128, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That's what you get for\nmonkeying around.\n\n")
  LANGUAGE_TEXT(1, "Voil\xe0 ce qui arrive \xe0 force\nde faire des singeries.\n\n")
  LANGUAGE_TEXT(2, "Das hast du nun vom\nHerumalbern.\n\n")
  LANGUAGE_TEXT(3, "Cos\xec imparate a\nperdere tempo.\n\n")
  LANGUAGE_TEXT(4, "Eso te llevas por\nhacer el macaco.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 24597)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Uh... Yeah... Nice one,\nSerenity...\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha...\nQuelle blague...\n\n")
  LANGUAGE_TEXT(2, "Uh... Hahaha... Das ist\ndoch wohl ein Witz...\n\n")
  LANGUAGE_TEXT(3, "Uh... Hahaha...\nChe ridere...\n\n")
  LANGUAGE_TEXT(4, "Uh... Jajaja...\nMenuda broma...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CE10, map_06_state_12_08E5CE10, 0x08F04040, 0x08F04040)
  SET_FLAG(185)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDC8, map_06_state_12_08E5CDC8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm glad you guys care so\nmuch...\n\n")
  LANGUAGE_TEXT(1, "Eh bien, merci de vous\n\xeatre inqui\xe9t\xe9 de moi...\n\n")
  LANGUAGE_TEXT(2, "Na, wenigstens hasst du dir\nSorgen um mich gemacht...\n\n")
  LANGUAGE_TEXT(3, "Be', dovrei essere felice\nche vi preoccupiate per\n\nme...\n\n")
  LANGUAGE_TEXT(4, "Vaya, deber\xeda alegrarme de\nque os preocup\xe9is de m\xed...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, 8)
  LANGUAGE_TEXT(0, "But come on! You've got to\nbe kidding!\n\nI don't look anything like\nthat monkey robot!\n\n")
  LANGUAGE_TEXT(1, "Mais enfin, vous devez\nplaisanter.\n\nEst-ce que je ressemble\n\xe0 ce singe robot ?\n\n")
  LANGUAGE_TEXT(2, "Aber gib's schon zu,\ndu machst Witze.\n\nInwiefern habe ich \xc4hnlich-\nkeit mit dem Roboter?\n\n")
  LANGUAGE_TEXT(3, "Ma andiamo,\nstarete scherzando.\n\nCome posso somigliare\na quella scimmia robot?\n\n")
  LANGUAGE_TEXT(4, "Pero, vamos, est\xe1is\nde broma.\n\n\xbfEn qu\xe9 me parezco\na ese robot mono?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDBC, map_06_state_12_08E5CDBC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I totally thought that the\nmonkey robot was Tristan.\n\nYou have to admit, there is\na strong resemblance.\n\n")
  LANGUAGE_TEXT(1, "J'\xe9tais convaincu que le\nsinge robot \xe9tait Tristan.\n\nCa lui va bien, ce r\xf4le\nde singe robot...\n\n")
  LANGUAGE_TEXT(2, "Ich war \xfcberzeugt davon,\ndass Tristan der\n\nAffenroboter war. Er sieht\nso nach Roboter aus.\n\n")
  LANGUAGE_TEXT(3, "Ero convinto che la scimmia\nrobot fosse Tristan.\n\nSomiglia un po' a quella\nscimmia robot.\n\n")
  LANGUAGE_TEXT(4, "Estaba convencido de que\nese robot mono era Tristan.\n\n\xc9l se parece al mono robot.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDB0, map_06_state_12_08E5CDB0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I wasn't trying to be\nfunny...\n\n")
  LANGUAGE_TEXT(1, "Je n'essayais pas\nd'\xeatre dr\xf4le.\n\n")
  LANGUAGE_TEXT(2, "Ich wollte damit keinen\nWitz machen...\n\n")
  LANGUAGE_TEXT(3, "Prima dicevo sul serio...\n\n")
  LANGUAGE_TEXT(4, "No pretend\xeda\nbromear antes...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
