#include "event_macros.h"
#include "overworld.h"

/* map_24_state_01: map 24 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E98144, map_24_state_01_08E98144, 0x08E98150, 0x08F04040)
  PLAY_MUSIC(239)
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Takeshi, is it really okay\nto be onboard this luxury\n\nliner?\n\nIt looks, like, really\nexpensive.\n\n")
  LANGUAGE_TEXT(1, "Takeshi, tu crois\nqu'on a le droit\n\nd'\xeatre sur ce bateau ?\nTout est si luxueux.\n\n")
  LANGUAGE_TEXT(2, "Takeshi, darf ich wirklich\nauf dieses exklusive\n\nSchiff?\n\nEs wirkt so teuer.\n\n")
  LANGUAGE_TEXT(3, "Takeshi, possiamo stare\ndavvero su questa\n\nnave fantastica?\nSembra proprio costosa.\n\n")
  LANGUAGE_TEXT(4, "Takeshi, \xbfde verdad no\npasa nada por estar\n\nen este barco tan\nestupendo?\n\nParece muy caro.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Don't you worry about a\nthing, babe.\n\nAll I have to do is win some\nduels. Piece of cake!\n\nReally? Takeshi, you're so\nsmart!\n\nAww, shucks. C'mon, I'm not\nthat smart.")
  LANGUAGE_TEXT(1, "Ne t'inqui\xe8te pas, b\xe9b\xe9.\n\nIl suffit de gagner\ndes duels.\n\nC'est aussi simple que \xe7a !\n\nVraiment ?\n\nTakeshi, qu'est-ce\nque tu es intelligent !\n\nOh, non, je suis pas si.")
  LANGUAGE_TEXT(2, "Mach dir keine Sorgen,\nBaby.\n\nDu musst nur ein paar Duelle\ngewinnen. Ein Kinderspiel.\n\nWirklich?\nTakeshi, du bist so clever!\n\nNein, nein, ich bin nicht.")
  LANGUAGE_TEXT(3, "Non preoccuparti di\nnulla, piccola.\n\nDevi solo vincere qualche\nduello. Facile, no?\n\nDavvero? Come sei\nintelligente, Takeshi!\n\nNo, no, non lo sono.")
  LANGUAGE_TEXT(4, "No te preocupes por\nnada, nena.\n\nS\xf3lo tienes que ganar\nunos duelos.\n\n\xa1Nada m\xe1s f\xe1cil!\n\n\xbfDe verdad?\nTakeshi, \xa1eres tan listo!\n\nNo, no, no soy.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ". ")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "Okay, I admit\n\nit! I am smart! My cranium's\nbursting with brains!\n\n")
  LANGUAGE_TEXT(1, "\nEnfin, si ! Intelligent !\n\n")
  LANGUAGE_TEXT(2, "\nNa klar! Ich bin clever!\n\n")
  LANGUAGE_TEXT(3, "Ma\ncerto che s\xec! Intelligente!\n\n")
  LANGUAGE_TEXT(4, "\n\xa1Claro que s\xed! \xa1Listo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98150, map_24_state_01_08E98150, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24577)
  DELAY(32)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  SET_FLAG(EVENT_FLAG_SAW_TAKESHI_BRAG)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E981BC, map_24_state_01_08E981BC, 0x08E98174, 0x08E981A4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_TAKESHI)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98174, map_24_state_01_08E98174, 0x08E98180, 0x08E9818C)
  LANGUAGE_TEXT(0, "Huh? You want to duel\nagainst me?\n\n")
  LANGUAGE_TEXT(1, "Hein ? Tu veux te battre\nen duel avec moi ?\n\n")
  LANGUAGE_TEXT(2, "H\xe4? Du willst dich mit\nmir duellieren?\n\n")
  LANGUAGE_TEXT(3, "Come? Vorresti\nduellare con me?\n\n")
  LANGUAGE_TEXT(4, "\xbfEh? \xbfQuieres luchar\nconmigo?\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98180, map_24_state_01_08E98180, 0x08E98198, 0x08F0404C)
  LANGUAGE_TEXT(0, "F-fine! Watch me, Etsuko!\n\n")
  LANGUAGE_TEXT(1, "Bon, d'accord !\nOuvre l'\u0153il, Etsuko !\n\n")
  LANGUAGE_TEXT(2, "G-gut!\nAchte auf mich, Etsuko!\n\n")
  LANGUAGE_TEXT(3, "Be', bene! Stammi\na guardare, Etsuko!\n\n")
  LANGUAGE_TEXT(4, "\xa1V-vale!\n\xa1M\xedrame, Etsuko!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  DUEL(31)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98198, map_24_state_01_08E98198, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(239)
  LANGUAGE_TEXT(0, "Takeshi, are you okay?\n\nHe dueled you, like, totally\nseriously! That is, like,\n\nso not cool!\n\nTakeshi, let's ditch these\njerks!\n\nUh... Yeah.\n\n")
  LANGUAGE_TEXT(1, "Takeshi, \xe7a va ?\n\nIl se l'est vraiment jou\xe9\ns\xe9rieux ! Pas cool du tout.\n\nTakeshi, oublions\nces tar\xe9s !\n\nMmh... Ouais.\n\n")
  LANGUAGE_TEXT(2, "Takeshi, ist alles in\nOrdnung?\n\nEr hat im Ernst mit dir\ngespielt! Total uncool!\n\nTakeshi, ignorieren wir\neinfach diesen P\xf6bel!\n\n\xc4h... Ja.\n\n")
  LANGUAGE_TEXT(3, "Takeshi, va tutto bene?\n\nPer quello giocare \xe8 una\ncosa seria! Che idiota!\n\nTakeshi, ignoriamo\nquesti imbecilli!\n\nUh... Hai ragione.\n\n")
  LANGUAGE_TEXT(4, "Takeshi, \xbfest\xe1s bien?\n\nLuch\xf3 totalmente en\nserio. \xa1Qu\xe9 poco nivel!\n\nTakeshi, \xa1pasemos de\nestos memos!\n\nUh... S\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  SET_FLAG(EVENT_FLAG_DEFEATED_TAKESHI)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9818C, map_24_state_01_08E9818C, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "He chickened out because\nhe's scared of you,\n\nTakeshi!\n\nYou're soooo awesome,\nTakeshi!\n\n")
  LANGUAGE_TEXT(1, "Tu lui as fait peur,\nTakeshi !\n\nTu es vraiment\nle plus fort !\n\n")
  LANGUAGE_TEXT(2, "Er hat Angst - wegen dir,\nTakeshi!\n\nDu bist so imposant,\nTakeshi!\n\n")
  LANGUAGE_TEXT(3, "Si \xe8 tirato indietro\na causa tua, Takeshi!\n\nSei fortissimo, Takeshi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Se asust\xf3 de ti,\nTakeshi!\n\n\xa1Eres tan grande,\nTakeshi!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E981A4, map_24_state_01_08E981A4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Hey, we told you to take a\nhike, creep.\n\n")
  LANGUAGE_TEXT(1, "H\xe9, on t'avait pourtant\ndit de partir, minable.\n\n")
  LANGUAGE_TEXT(2, "He, du solltest doch\nabhauen, Schleimer.\n\n")
  LANGUAGE_TEXT(3, "Ehi, ti abbiamo detto\ndi smammare, idiota.\n\n")
  LANGUAGE_TEXT(4, "Hey, te dijimos que\nte largaras, gusano.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(1, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E981C8, map_24_state_01_08E981C8, 0x08E98174, 0x08E981B0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_TAKESHI)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E981B0, map_24_state_01_08E981B0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "What's your problem! I'm not\nplaying you again.\n\n")
  LANGUAGE_TEXT(1, "Ne fais pas le malin, je\nne bats plus contre toi.\n\n")
  LANGUAGE_TEXT(2, "Werd nicht frech, gegen dich\nspiele ich nicht mehr.\n\n")
  LANGUAGE_TEXT(3, "Non fare l'impertinente.\nCon te non gioco pi\xf9.\n\n")
  LANGUAGE_TEXT(4, "No seas chulo, no luchar\xe9\ncontigo de nuevo.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(1, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9815C, map_24_state_01_08E9815C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Don't bug us! Go away,\ncreep!\n\n")
  LANGUAGE_TEXT(1, "Laisse-nous tranquille !\nAllez, va-t-en !\n\n")
  LANGUAGE_TEXT(2, "St\xf6r uns nicht!\nHau ab, du Klette!\n\n")
  LANGUAGE_TEXT(3, "Lasciaci in pace!\nVattene, idiota!\n\n")
  LANGUAGE_TEXT(4, "\xa1No molestes!\n\xa1Vete por ah\xed, gusano!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E98168, map_24_state_01_08E98168, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "What's your problem?\n\nYou are, like, so uncool!\n\n")
  LANGUAGE_TEXT(1, "Pourquoi est-ce que\ntu t'\xe9nerves ?\n\nC'est pas du tout cool !\n\n")
  LANGUAGE_TEXT(2, "Wor\xfcber regst du dich\nso auf?\n\nDas ist \xfcberhaupt nicht\ncool!\n\n")
  LANGUAGE_TEXT(3, "Cos'\xe8 tutta questa\nagitazione?\n\n\xc8 proprio da scemi!\n\n")
  LANGUAGE_TEXT(4, "\xbfPor qu\xe9 andas tan\nazorado?\n\n\xa1Qu\xe9 poco nivel!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
