#include "event_macros.h"

/* map_35_state_04: map 35 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EC6344, map_35_state_04_08EC6344, 0x08EC6350, 0x08F04040)
  PLAY_MUSIC(11)
  PORTRAIT(11, 2, 0)
  LANGUAGE_TEXT(0, "Two on one's not fair, you\ndorkasaurus!\n\n")
  LANGUAGE_TEXT(1, "Deux contre un,\nce n'est pas juste !\n\nFaites preuve de fair-play !\n\n")
  LANGUAGE_TEXT(2, "Zwei gegen einen ist nicht\nfair. Zeigt etwas Stolz!\n\n")
  LANGUAGE_TEXT(3, "Non vale, due contro uno!\nDov'\xe8 finito l'orgoglio?\n\n")
  LANGUAGE_TEXT(4, "\xa1Dos contra uno no es justo!\n\xa1Mostrad alg\xfan orgullo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(49, 0, 0)
  LANGUAGE_TEXT(0, "Fair? We don't know the\nmeaning of the word fair!\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas la\npeine de pleurnicher,\n\nce n'est pas \xe7a\nqui va t'aider !\n\n")
  LANGUAGE_TEXT(2, "Weinen hilft dir bei den\nNeo Ghouls auch nicht!\n\n")
  LANGUAGE_TEXT(3, "Con i Neo Ghouls,\n\xe8 inutile strepitare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Llorar por eso no te\nayudar\xe1 con los Neo Ghouls!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 2)
  DELAY(16)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_X(13, 64)
  WALK_OBJECT_X(14, 64)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(11, 6, 8)
  LANGUAGE_TEXT(0, "You scavengers...\n\n")
  LANGUAGE_TEXT(1, "Esp\xe8ce de...\n\n")
  LANGUAGE_TEXT(2, "Du verdammter...\n\n")
  LANGUAGE_TEXT(3, "Maledetti...\n\n")
  LANGUAGE_TEXT(4, "Asquerosos...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(49, 0, 0)
  LANGUAGE_TEXT(0, "Tsk! Our boy has friends!\n\nWe'll wipe the floor with\nall of you!\n\n")
  LANGUAGE_TEXT(1, "Tch ! Le petit avait\ndes amis !\n\nOn va tous les \xe9craser !\n\n")
  LANGUAGE_TEXT(2, "Tss! Unser Kleiner hatte\nFreunde!\n\nAn euch treten wir uns\ngleich die F\xfc\xdfe ab!\n\n")
  LANGUAGE_TEXT(3, "Ah! Il nostro ragazzo\naveva gli amici!\n\nFaremo piazza pulita\ndi tutti voi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Chss! \xa1El chico ten\xeda\namigos!\n\n\xa1Fregaremos el suelo\ncon todos vosotros!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(11, 0, 8)
  LANGUAGE_TEXT(0, "With {PLAYER} at my side,\nyou guys are as scary as\n\nbaby birds!\n\nI won't lose to any Neo\nGhouls!\n\n{PLAYER}, which one do you\nwant to take?\n\n")
  LANGUAGE_TEXT(1, "Avec {PLAYER} de mon\nc\xf4t\xe9, vous ne faites pas le\n\npoids. On ne va pas perdre\ncontre les Neo Ghouls !\n\n{PLAYER},\nlequel tu prends ?\n\n")
  LANGUAGE_TEXT(2, "Mit {PLAYER} an meiner Seite\nk\xf6nnt ihr nichts\n\nausrichten!\n\nIch verliere nicht gegen Neo\nGhouls!\n\n{PLAYER}, mit wem willst\ndu es aufnehmen?\n\n")
  LANGUAGE_TEXT(3, "Con {PLAYER} dalla mia\nparte, siete una nullit\xe0!\n\nNon perder\xf2 con nessun\nNeo Ghoul!\n\n{PLAYER}, quale\nvuoi prendere?\n\n")
  LANGUAGE_TEXT(4, "\xa1Con {PLAYER} a mi lado,\nt\xedos, no sois nada!\n\n\xa1No voy a perder con\nning\xfan Neo Ghoul!\n\n{PLAYER},\n\xbfcu\xe1l quieres?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6350, map_35_state_04_08EC6350, 0x08EC635C, 0x08EC6374)
  LANGUAGE_TEXT(0, "{CARD_1}The guy on the right.\nThe guy on the left.{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Le mec \xe0 droite.\nLe mec \xe0 gauche.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Mit dem rechten.\nMit dem linken.{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Quello a destra.\nQuello a sinistra.{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}El tipo de la derecha.\nEl tipo de la izquierda.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC635C, map_35_state_04_08EC635C, 0x08EC6368, 0x08F0404C)
  WALK_OBJECT_X(0, 96)
  WALK_OBJECT_Y(0, 52)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_X(1, 84)
  WALK_OBJECT_Y(1, 52)
  DUEL(66)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6368, map_35_state_04_08EC6368, 0x08EC638C, 0x08F04040)
  PLAY_MUSIC(245)
  PORTRAIT(49, 0, 0)
  LANGUAGE_TEXT(0, "You'll pay for this!\n\n")
  LANGUAGE_TEXT(1, "Tu vas le regretter !\n\n")
  LANGUAGE_TEXT(2, "Das wirst du noch b\xfc\xdfen!\n\n")
  LANGUAGE_TEXT(3, "La pagherai per questo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo pagar\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 32)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  WALK_OBJECT_Y(3, 48)
  WALK_OBJECT_X(3, 248)
  WALK_OBJECT_X(2, 32)
  WALK_OBJECT_Y(2, 48)
  WALK_OBJECT_X(2, 248)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC638C, map_35_state_04_08EC638C, 0x08EC6398, 0x08F04040)
  PORTRAIT(11, 0, 8)
  LANGUAGE_TEXT(0, "Thanks, I owe you one.\n\nIf you need any help, don't\nhesitate to ask.\n\n")
  LANGUAGE_TEXT(1, "Merci, je te suis\nreconnaissant.\n\nSi tu as besoin d'aide,\nn'h\xe9site pas \xe0 me le\n\ndemander.\n\n")
  LANGUAGE_TEXT(2, "Danke, ich bin dir\netwas schuldig.\n\nWenn du Hilfe brauchst,\nmusst du nur fragen.\n\n")
  LANGUAGE_TEXT(3, "Grazie, ti sono debitore.\n\nSe ti serve aiuto, non\nesitare a chiedermelo.\n\n")
  LANGUAGE_TEXT(4, "Gracias, te debo una.\n\nSi necesitas ayuda, no\ndudes en pedirla.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6398, map_35_state_04_08EC6398, 0x08EC63A4, 0x08EC63B0)
  PLAY_MUSIC(702)
  PORTRAIT(11, 6, 8)
  LANGUAGE_TEXT(0, "What? They're all over the\nTown of Domino?\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Ils sont partout\n\xe0 Domino ?\n\n")
  LANGUAGE_TEXT(2, "Was? Sie sind \xfcberall in\nDomino?\n\n")
  LANGUAGE_TEXT(3, "Cosa? Hanno invaso Domino?\nQuei Neo Ghouls non la\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? \xbfEst\xe1n por\ntodas partes en Domino?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(11, 2, 8)
  LANGUAGE_TEXT(0, "Those Neo Ghouls won't get\naway with this!\n\nAll right! Leave it to me!\n\nI'll trample those clowns!\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls ne vont\npas s'en tirer comme \xe7a !\n\nOK, laisse-moi, je m'en\noccupe !\n\nJe vais faire d\xe9guerpir\nces clowns !\n\n")
  LANGUAGE_TEXT(2, "So leicht kommen diese\nNeo Ghouls nicht davon!\n\nOkay! \xdcberlass es mir!\n\nIch werde ihnen schon\nBeine machen!\n\n")
  LANGUAGE_TEXT(3, "faranno franca! Benissimo!\nCi penso io! Far\xf2\n\nscappare quei pagliacci\na gambe levate!\n\n")
  LANGUAGE_TEXT(4, "\xa1Esos Neo Ghouls no van a\nsalirse con la suya!\n\n\xa1Muy bien!\n\xa1D\xe9jamelos!\n\n\xa1Mandar\xe9 a esos payasos\na fre\xedr monas!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(1, 64)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  WALK_OBJECT_X(1, 248)
  SET_FLAG(84)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC63A4, map_35_state_04_08EC63A4, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Let's go find another ally!\n\n")
  LANGUAGE_TEXT(1, "Essayons de trouver\nun autre allier !\n\n")
  LANGUAGE_TEXT(2, "Suchen wir uns einen\nanderen Verb\xfcndeten!\n\n")
  LANGUAGE_TEXT(3, "Andiamo a trovare\nun altro alleato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien, vamos a\nbuscar otro aliado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC63B0, map_35_state_04_08EC63B0, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Okay! Let's also get back to\nthe Town of Domino!\n\n")
  LANGUAGE_TEXT(1, "OK ! Retournons\naussi \xe0 Domino !\n\n")
  LANGUAGE_TEXT(2, "Okay! Kehren wir auch\nnach Domino zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Okay! Torniamo anche\nnoi a Domino!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien, volvamos a\nDomino tambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6374, map_35_state_04_08EC6374, 0x08EC6380, 0x08F0404C)
  WALK_OBJECT_X(0, 84)
  WALK_OBJECT_Y(0, 52)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_X(1, 96)
  WALK_OBJECT_Y(1, 52)
  DUEL(67)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC6380, map_35_state_04_08EC6380, 0x08EC638C, 0x08F04040)
  PLAY_MUSIC(245)
  PORTRAIT(49, 0, 0)
  LANGUAGE_TEXT(0, "You'll pay for this!\n\n")
  LANGUAGE_TEXT(1, "Tu vas le regretter !\n\n")
  LANGUAGE_TEXT(2, "Das wirst du noch b\xfc\xdfen!\n\n")
  LANGUAGE_TEXT(3, "La pagherai per questo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo pagar\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 32)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  WALK_OBJECT_Y(3, 48)
  WALK_OBJECT_X(3, 248)
  WALK_OBJECT_X(2, 32)
  WALK_OBJECT_Y(2, 48)
  WALK_OBJECT_X(2, 248)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC63BC, map_35_state_04_08EC63BC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Good to see you safe and\nsound, eh?\n\n")
  LANGUAGE_TEXT(1, "Content de vous voir\nsains et saufs !\n\n")
  LANGUAGE_TEXT(2, "Sch\xf6n, euch gesund\nwiederzusehen.\n\n")
  LANGUAGE_TEXT(3, "Mi fa piacere vedere\nche siete sani e salvi.\n\n")
  LANGUAGE_TEXT(4, "Es bueno veros\nsanos y salvos, \xbfeh?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC63C8, map_35_state_04_08EC63C8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I believe you have more\nimportant things to do..\n\nI think you should get\nmoving, eh?\n\n")
  LANGUAGE_TEXT(1, "Vous devez faire\nquelque chose.\n\nVous feriez mieux\nd'y aller, non ?\n\n")
  LANGUAGE_TEXT(2, "Ihr habt eine Aufgabe.\n\nSolltet ihr euch nicht bes-\nser auf den Weg machen?\n\n")
  LANGUAGE_TEXT(3, "Avete qualcosa da fare.\nPenso che fareste meglio\n\na darvi una mossa.\n\n")
  LANGUAGE_TEXT(4, "Ten\xe9is algo que hacer.\nMejor os mov\xe9is, \xbfeh?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC63D4, map_35_state_04_08EC63D4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I tell you, excavating\nfossils is slow and\n\nlaborious.\n\nEven though it's hard work,\nI never take shortcuts.\n\nI never take fossils that\nsomeone else found.\n\nI bet that's the same with\ndueling. You don't steal\n\nsomeone else's cards.\n\nI'm no duelist, and I never\nsaid I was one.\n\nBut I know what the Neo\nGhouls are doing is wrong.\n\n")
  LANGUAGE_TEXT(1, "Creuser pour trouver\ndes fossiles,\n\nc'est un travail long\net laborieux !\n\nEt pourtant, on\nne vole jamais, non ?\n\nOn ne prend jamais ce\nque les autres ont trouv\xe9.\n\nJe parie que c'est\npareil en duel.\n\nJe n'ai jamais dit que\nj'\xe9tais un duelliste.\n\nMais je sais que\nce que font les Neo\n\nGhouls n'est pas bien.\n\n")
  LANGUAGE_TEXT(2, "Fossilien auszugraben ist\neine m\xfchsame T\xe4tigkeit.\n\nAber deswegen w\xfcrde man\ndoch nie stehlen, oder?\n\nWir w\xfcrden nie den Fund\neines Kollegen nehmen.\n\nBei Duellen ist es sicher\n\xe4hnlich.\n\nIch bin kein Duellant.\n\nDoch ich wei\xdf, dass die\nNeo Ghouls Unrecht tun.\n\n")
  LANGUAGE_TEXT(3, "Scavare fossili \xe8 un lavoro\nlento e laborioso,\n\ncredetemi. Ma anche se \xe8\nduro, non si ruba mai\n\nniente. Non si prendono mai\ni fossili trovati da altri.\n\nScommetto che con i\nduelli \xe8 la stessa cosa.\n\nNon sono un duellante e non\nho mai detto di esserlo.\n\nMa so che quello che fanno\ni Neo Ghouls \xe8 sbagliato.\n\n")
  LANGUAGE_TEXT(4, "Excavar f\xf3siles es lento\ny laborioso, os lo digo.\n\nPero aunque sea duro,\nnunca robas, \xbfeh?\n\nNunca coges f\xf3siles\nhallados por otro.\n\nApuesto que pasa lo\nmismo retando.\n\nNo soy duelista,\nnunca dije serlo.\n\nPero s\xe9 que lo que hacen los\nNeo Ghouls est\xe1 mal.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
