#include "event_macros.h"
#include "overworld.h"

/* map_13_state_01: map 13 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E716A0, map_13_state_01_08E716A0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(31)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Mokuba, crank it up to the\nmax duelist level!\n\n")
  LANGUAGE_TEXT(1, "Mokuba, passe au niveau\nde duel maximum !\n\n")
  LANGUAGE_TEXT(2, "Mokuba, stell dich\naufs h\xf6chste\n\nDuellanten-Level ein!\n\n")
  LANGUAGE_TEXT(3, "Mokuba, puntiamo al massimo\nlivello duellante!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mokuba, ponlo al\nnivel duelista m\xe1ximo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No way! The computer will\ntotally pummel you! Start\n\nat level {BYTE_8251}.\n\nIf you can't win at that\nlevel, then you're plain\n\nlame.\n\n")
  LANGUAGE_TEXT(1, "Tu plaisantes\nou quoi ?\n\nTu commences\nau niveau {BYTE_8251}.\n\nSi tu perds \xe0 ce niveau,\ntu es un gros nul.\n\n")
  LANGUAGE_TEXT(2, "Das ist doch wohl ein Witz -\nDu beginnst mit Level {BYTE_8251}.\n\nWenn du da nicht gewinnen\nkannst, hast du Pech!\n\n")
  LANGUAGE_TEXT(3, "Stai scherzando? Inizi\nal livello {BYTE_8251}.\n\nSe non vinci a quel livello,\nsei un buono a nulla.\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s de broma?\nEmpiezas en el nivel {BYTE_8251}.\n\nSi no puedes ganar ah\xed,\neres un cutre.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh, fine. I guess that'll\nhave to do.\n\n")
  LANGUAGE_TEXT(1, "Oh, OK.\nCa devrait aller.\n\n")
  LANGUAGE_TEXT(2, "Oh, okay.\nSchon gut.\n\n")
  LANGUAGE_TEXT(3, "Oh, okay. Sta bene.\n\n")
  LANGUAGE_TEXT(4, "Oh, vale.\nAs\xed ser\xe1.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Set me up at the same level!\n\n")
  LANGUAGE_TEXT(1, "Tu peux me mettre\nau m\xeame niveau ?\n\n")
  LANGUAGE_TEXT(2, "Kann ich auf dem gleichen\nLevel spielen?\n\n")
  LANGUAGE_TEXT(3, "Puoi mettermi allo\nstesso livello?\n\n")
  LANGUAGE_TEXT(4, "\xbfPuedes ponerme al\nmismo nivel?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Okay, start the Duel\nMachine!\n\n")
  LANGUAGE_TEXT(1, "OK, la Duel Machine\nest en marche !\n\n")
  LANGUAGE_TEXT(2, "Okay, die Duel Machine kann\nstarten!\n\n")
  LANGUAGE_TEXT(3, "Okay, Duel Machine\nvia!\n\n")
  LANGUAGE_TEXT(4, "Vale, \xa1vamos, Duel Machine!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(211)
  FADE_SCREEN(2)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_DEFEATED, 8)
  LANGUAGE_TEXT(0, "Gwaaaaaaah!\n\n")
  LANGUAGE_TEXT(1, "Gouaaaaaaah !\n\n")
  LANGUAGE_TEXT(2, "Uaaaaaah!\n\n")
  LANGUAGE_TEXT(3, "Guaaaaaaah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Guaaaaaaah!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I... I barely won.\n\n")
  LANGUAGE_TEXT(1, "J'ai...\nJ'ai r\xe9ussi \xe0 gagner.\n\n")
  LANGUAGE_TEXT(2, "Ich... Ich habe gewonnen.\n\n")
  LANGUAGE_TEXT(3, "Io...sono riuscito a\nvincere.\n\n")
  LANGUAGE_TEXT(4, "He... He ganado.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  PLAY_MUSIC(211)
  LANGUAGE_TEXT(0, "ASSESSING DUELIST LEVEL...\n\nASSESSING DUELIST LEVEL...\n\nASSESSMENT COMPLETE.\n\nBOTH IDIOTS. BOTH IDIOTS.\n\n")
  LANGUAGE_TEXT(1, "EVALUATION NIVEAU\nDU DUEL...\n\nEVALUATION NIVEAU\nDU DUEL...\n\nEVALUATION TERMINEE.\n\nTOUS LES DEUX NULS.\nTOUS LES DEUX NULS.\n\n")
  LANGUAGE_TEXT(2, "DUELLANTEN-LEVEL WIRD\nBEWERTET...\n\nDUELLANTEN-LEVEL WIRD\nBEWERTET...\n\nBEWERTUNG ABGESCHLOSSEN.\n\nBEIDE SCHWACH.\nBEIDE SCHWACH.\n\n")
  LANGUAGE_TEXT(3, "VALUTAZIONE DEL LIVELLO\nDUELLANTE IN CORSO...\n\nVALUTAZIONE DEL LIVELLO\nDUELLANTE IN CORSO...\n\nVALUTAZIONE COMPLETATA.\n\nENTRAMBI DILETTANTI.\nENTRAMBI DILETTANTI.\n\n")
  LANGUAGE_TEXT(4, "EVALUANDO NIVEL\nDEL DUELISTA...\n\nEVALUANDO NIVEL\nDEL DUELISTA...\n\nEVALUACI\xd3N COMPLETA.\n\nAMBOS CUTRES\nAMBOS CUTRES.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "Are you serious?\n\n")
  LANGUAGE_TEXT(1, "Tu es s\xe9rieux ?\n\n")
  LANGUAGE_TEXT(2, "Soll das dein Ernst sein?\n\n")
  LANGUAGE_TEXT(3, "Parli sul serio?\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s de broma?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "But I won!\n\n")
  LANGUAGE_TEXT(1, "Mais j'ai gagn\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Aber ich habe gewonnen!\n\n")
  LANGUAGE_TEXT(3, "Ma io ho vinto!\n\n")
  LANGUAGE_TEXT(4, "Pero, \xa1he ganado!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Simply winning doesn't\nimpress the Duel Machine.\n\nIt also checks for spell and\ntrap combos.\n\nJudging by your skills, I'd\nsay the computer made the\n\nright call.\n\n")
  LANGUAGE_TEXT(1, "Le simple fait de gagner\nn'impressionne pas la\n\nDuel Machine. Elle v\xe9rifie\naussi les combos magiques\n\nainsi que les pi\xe8ges.\n\nVu tes aptitudes, la\nmachine a s\xfbrement raison.\n\n")
  LANGUAGE_TEXT(2, "Gewinnen allein beeindruckt\ndie Duel Machine nicht.\n\nSie pr\xfcft auch, ob du\nZauber- und Fallencombos\n\nverwendet hast.\nAngesichts deiner F\xe4higkei-\n\nten war das Urteil aber\nwohl korrekt.\n\n")
  LANGUAGE_TEXT(3, "La Duel Machine non\nvaluta solo le vittorie.\n\nControlla pure le combina-\nzioni di magia e trappole.\n\nCon le vostre abilit\xe0, direi\nche ha valutato bene.\n\n")
  LANGUAGE_TEXT(4, "S\xf3lo por ganar no\nse impresiona a la\n\nDuel Machine.\n\nTambi\xe9n, verifica\ncombinados de\n\nmagia y trampas.\n\nCon vuestras aptitudes,\ndir\xeda que est\xe1 acertada.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh yeah? One more time!\n\n")
  LANGUAGE_TEXT(1, "Et zut !\nEncore une fois !\n\n")
  LANGUAGE_TEXT(2, "Verdammt!\nNoch einmal!\n\n")
  LANGUAGE_TEXT(3, "Maledizione!\nUna volta ancora!\n\n")
  LANGUAGE_TEXT(4, "\xa1Maldita sea!\n\xa1Una vez m\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Go right ahead. But I think\nyou're wasting your time.\n\n")
  LANGUAGE_TEXT(1, "OK. Mais je crois que vous\nme faites perdre mon temps.\n\n")
  LANGUAGE_TEXT(2, "Na los. Aber ich glaube, ihr\nvergeudet nur eure Zeit.\n\n")
  LANGUAGE_TEXT(3, "Andate avanti. Ma penso\nche sia tempo sprecato.\n\n")
  LANGUAGE_TEXT(4, "Int\xe9ntalo. Pero creo\nque pierden el tiempo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 32)
  WALK_OBJECT_Y(1, 52)
  WALK_OBJECT_X(1, 16)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DUELING_THE_DUEL_MACHINE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716AC, map_13_state_01_08E716AC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "I'm training! Don't distract\nme!\n\n")
  LANGUAGE_TEXT(1, "Je suis en train\nde m'entra\xeener !\n\nNe me parle pas !\n\n")
  LANGUAGE_TEXT(2, "Ich \xfcbe noch!\nSprich nicht mit mir!\n\n")
  LANGUAGE_TEXT(3, "Mi sto allenando!\nNon parlare con me!\n\n")
  LANGUAGE_TEXT(4, "\xa1Estoy entrenando!\n\xa1No me hables ahora!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716B8, map_13_state_01_08E716B8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "Can't you see I'm dueling?\n\n")
  LANGUAGE_TEXT(1, "Tu ne vois pas que\nje me bats en duel ?\n\n")
  LANGUAGE_TEXT(2, "Siehst du nicht, dass ich\nmich duelliere?\n\n")
  LANGUAGE_TEXT(3, "Non vedi che sto duellando?\n\n")
  LANGUAGE_TEXT(4, "\xbfNo ves que estoy\nbati\xe9ndome?\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716C4, map_13_state_01_08E716C4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "I can't lose to Tristan.\n\n")
  LANGUAGE_TEXT(1, "Je ne veux pas \xeatre\nderri\xe8re Tristan.\n\n")
  LANGUAGE_TEXT(2, "Ich darf nicht hinter\nTristan zur\xfcckfallen.\n\n")
  LANGUAGE_TEXT(3, "Non posso farmi\nsuperare da Tristan.\n\n")
  LANGUAGE_TEXT(4, "No puedo quedarme\natr\xe1s, Tristan.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(3, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716D0, map_13_state_01_08E716D0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, 8)
  LANGUAGE_TEXT(0, "Please don't bug me while\nI'm training.\n\n")
  LANGUAGE_TEXT(1, "Laisse-moi tranquille\npendant que je m'entra\xeene.\n\n")
  LANGUAGE_TEXT(2, "Bitte st\xf6r mich nicht.\nIch \xfcbe.\n\n")
  LANGUAGE_TEXT(3, "Ti prego, non mi rompere\nmentre mi sto allenando.\n\n")
  LANGUAGE_TEXT(4, "Por favor, no me des\nla lata mientras entreno.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(3, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E71760, map_13_state_01_08E71760, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(211)
  LANGUAGE_TEXT(0, "OPERATING AT DUELIST LEVEL\n{BYTE_8251}.\n\nSYSTEM IN OPERATION.\n\n")
  LANGUAGE_TEXT(1, "REGLAGE DUELLISTES\nDE NIVEAU {BYTE_8251}.\n\nSYSTEME\nOPERATIONNEL.\n\n")
  LANGUAGE_TEXT(2, "DUELLANTEN-LEVEL {BYTE_8251}\nAKTIVIERT.\n\nSYSTEM IN BETRIEB.\n\n")
  LANGUAGE_TEXT(3, "FUNZIONAMENTO AL\nLIVELLO DUELLANTE {BYTE_8251}.\n\nSISTEMA OPERATIVO.\n\n")
  LANGUAGE_TEXT(4, "OPERANDO A NIVEL\nDUELISTA {BYTE_8251}.\n\nSISTEMA FUNCIONANDO.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7176C, map_13_state_01_08E7176C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(211)
  LANGUAGE_TEXT(0, "OPERATING AT DUELIST LEVEL\nFOR IDIOTS.\n\nSYSTEM IN OPERATION.\n\nWAIT FOR YOUR TURN BEFORE\nSTARTING.\n\n")
  LANGUAGE_TEXT(1, "REGLAGE NIVEAU\nDUELLISTES NULS.\n\nSYSTEME\nOPERATIONNEL.\n\nATTENDRE SON TOUR\nAVANT DE COMMENCER.\n\n")
  LANGUAGE_TEXT(2, "DUELLANTEN-LEVEL F\xdcR\nSCHWACHK\xd6PFE AKTIVIERT.\n\nSYSTEM IN BETRIEB.\n\nWARTE, BIS DU AN DER REIHE\nBIST, BEVOR DU BEGINNST.\n\n")
  LANGUAGE_TEXT(3, "FUNZIONAMENTO AL\nLIVELLO DUELLANTE\n\nPER DILETTANTI.\nSISTEMA OPERATIVO.\n\nATTENDI IL TUO TURNO\nPRIMA DI INIZIARE.\n\n")
  LANGUAGE_TEXT(4, "OPERANDO A NIVEL\nDUELISTA PARA CUTRES.\n\nSISTEMA FUNCIONANDO.\n\nESPERA TU TURNO ANTES\nDE COMENZAR.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
