#include "event_macros.h"
#include "overworld.h"

/* map_33_state_05: map 33 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EBEBE0, map_33_state_05_08EBEBE0, 0x08EBEBEC, 0x08EBEBF8)
  PLAY_MUSIC(410)
  DELAY(16)
  PLAY_MUSIC(280)
  SHOW_OBJECT(1, 60, 68, 0, 1, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "What took you so long?\n\nHowever, you've passed the\nchallenges so far.\n\nAlong the way, you have\nbeen given cards.\n\nDo you understand what they\nrepresent?\n\n")
  LANGUAGE_TEXT(1, "Eh bien, l'attente \xe9tait\nplut\xf4t longue.\n\nMais pour l'instant,\ntout se passe bien.\n\nBon, on vous a donn\xe9 des\ncartes en chemin.\n\nEst-ce que vous comprenez\nce qu'elles repr\xe9sentent ?\n\n")
  LANGUAGE_TEXT(2, "Ihr habt mich aber lange\nwarten lassen.\n\nAber so weit, so gut.\nJetzt habt ihr Karten, die\n\neuch auf eurem Weg\nhelfen werden.\n\nVersteht ihr die Bedeutung\ndieser Karten?\n\n")
  LANGUAGE_TEXT(3, "Perbacco, l'attesa \xe8\nstata piuttosto lunga.\n\nMa fin qui, va tutto bene.\n\nAllora, lungo il cammino\navete ricevuto delle carte.\n\nCapite ci\xf2 che\nrappresentano?\n\n")
  LANGUAGE_TEXT(4, "Vaya, vaya: ha sido una\nespera larguita.\n\nPero ha valido la pena.\n\nBueno, os han dado\ncartas en el camino.\n\n\xbfComprend\xe9is qu\xe9\nrepresentan?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBEC, map_33_state_05_08EBEBEC, 0x08EBEC04, 0x08F04040)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "Ah! Good, good!\nGood for you!\n\n")
  LANGUAGE_TEXT(1, "Ah, c'est bien !\nTant mieux pour vous !\n\n")
  LANGUAGE_TEXT(2, "Ah, gut, gut!\nSch\xf6n f\xfcr euch!\n\n")
  LANGUAGE_TEXT(3, "Ah, bene, bene!\nBuon per voi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ah, bien, bien!\n\xa1Bien por vosotros!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC04, map_33_state_05_08EBEC04, 0x08EBEC10, 0x08EBEC1C)
  LANGUAGE_TEXT(0, "Fine.\nThen answer my questions.\n\nWhich card should come\nfirst?\n\n")
  LANGUAGE_TEXT(1, "Bien. Laissez-moi vous\nposer une question.\n\nQuelle carte vient\nen premier ?\n\n")
  LANGUAGE_TEXT(2, "Okay. Eine Frage.\n\nWelche Karte kommt\nzuerst?\n\n")
  LANGUAGE_TEXT(3, "Bene. Lasciatemi\nchiedervi questo.\n\nQuale carta dovrebbe\nessere la prima?\n\n")
  LANGUAGE_TEXT(4, "Estupendo.\nOs preguntar\xe9 esto:\n\n\xbfQu\xe9 carta debe ir\nprimero?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Celtic Guardian\nKuriboh{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Gardien celte\nKuriboh{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Keltischer W\xe4chter\nKuriboh{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Guardiano Celtico\nKuriboh{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Guardi\xe1n celta\nKuriboh{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC10, map_33_state_05_08EBEC10, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "That isn't right, is it?\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas la\nbonne r\xe9ponse, si ?\n\n")
  LANGUAGE_TEXT(2, "Das stimmt doch wohl\nnicht, oder?\n\n")
  LANGUAGE_TEXT(3, "Non \xe8 giusto, vero?\n\n")
  LANGUAGE_TEXT(4, "No es correcto,\n\xbfno?\n\n")
  END_LANGUAGE_TEXT()
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  WARP(31, 7, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC1C, map_33_state_05_08EBEC1C, 0x08EBEC28, 0x08EBEC40)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "Ah, good!\nYou seem to understand.\n\nThen which card should come\nfifth?\n\n")
  LANGUAGE_TEXT(1, "Ah, bien ! Vous avez l'air\nd'avoir compris.\n\nAlors quelle carte vient\nen cinqui\xe8me ?\n\n")
  LANGUAGE_TEXT(2, "Ah, gut! Ihr scheint es\nja doch zu verstehen.\n\nWelche Karte sollte dann\ndie f\xfcnfte sein?\n\n")
  LANGUAGE_TEXT(3, "Ah, bene!\nSembrate aver capito.\n\nDunque, quale carta\ndovrebbe essere la quinta?\n\n")
  LANGUAGE_TEXT(4, "\xa1Ah, bien!\nParece que entend\xe9is.\n\nEntonces, \xbfqu\xe9 carta\ndebe ir la quinta?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Curse of Dragon\nGiant Soldier of Stone{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Mal\xe9diction du dragon\nSoldat g\xe9ant de pierre{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Drachenfluch\nRiesen-Steinsoldat{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Anatema del Drago\nSoldato di Pietra{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Maldici\xf3n de Drag\xf3n\nSoldado gigante de piedra{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC28, map_33_state_05_08EBEC28, 0x08EBEC4C, 0x08EBEC34)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "Well done! You seem to\nreally understand.\n\n")
  LANGUAGE_TEXT(1, "Bravo ! Vous avez l'air\nd'avoir tout compris.\n\n")
  LANGUAGE_TEXT(2, "Gut! Ihr scheint euch ja\nwirklich auszukennen.\n\n")
  LANGUAGE_TEXT(3, "Ottimo! A quanto\npare avete capito bene.\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien hecho! Realmente\nparec\xe9is comprender.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Oh, I get it. The cards we\nreceived were in sequence.\n\nThey were in the order of\ntheir levels.\n\n")
  LANGUAGE_TEXT(1, "Oh, j'ai compris. Les\ncartes ont un ordre.\n\nElles sont class\xe9es\nselon leur niveau.\n\n")
  LANGUAGE_TEXT(2, "Jetzt verstehe ich. Wir\nhaben diese Karten in\n\nihrer richtigen Reihenfolge\nerhalten.\n\nIn der Reihenfolge ihrer\nLevels.\n\n")
  LANGUAGE_TEXT(3, "Ho capito. Le carte\nche abbiamo ricevuto\n\nerano in sequenza, in\nbase ai loro livelli.\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh!, Lo tengo. Las\ncartas que nos\n\ndieron iban seguidas.\n\nIban por orden de\nsus niveles.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Kuriboh's level one, so it\ncame first.\n\nCurse of Dragon came last\nbecause it's level five.\n\nThat's what we had to\nfigure out, right,\n\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(1, "Kuriboh est de niveau {BYTE_8250}\nalors elle vient en\n\npremier.\n\nLa Mal\xe9diction du\ndragon est en dernier\n\ncar c'est une carte\nde niveau cinq.\n\nC'est bien \xe7a, n'est-ce\npas, {PLAYER} ?\n\n")
  LANGUAGE_TEXT(2, "Kuriboh ist Level eins, ihn\nbekamen wir zuerst.\n\nDrachenfluch bekamen wir\nzuletzt, er ist Level f\xfcnf.\n\nDas steckte dahinter,\nstimmt's, {PLAYER}?\n\n")
  LANGUAGE_TEXT(3, "Kuriboh \xe8 di livello uno,\nquindi era la prima.\n\nAnatema del Drago era\nl'ultima perch\xe9 \xe8 di\n\nlivello cinque. Chiaro no,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(4, "Kuriboh es el nivel uno,\npor lo que vino primero.\n\nMaldici\xf3n de Drag\xf3n vino\nla \xfaltima porque es\n\nel nivel cinco.\n\nDe eso se trataba,\n\xbfno, {PLAYER}?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "You still haven't passed\nall my tests.\n\nYou claim to be a duelist.\nTherefore, we shall duel.\n\n")
  LANGUAGE_TEXT(1, "Mais je ne suis pas encore\ntotalement satisfait.\n\nApr\xe8s tout, tu es\nun duelliste.\n\nAlors, battons-nous\nen duel.\n\n")
  LANGUAGE_TEXT(2, "Ich bin noch nicht\nzufrieden.\n\nDu bist doch ein Duellant.\nDuellieren wir uns.\n\n")
  LANGUAGE_TEXT(3, "Non mi hai ancora\nsoddisfatto.\n\nIn fin dei conti, sei\nun duellante.\n\nAllora duelleremo.\n\n")
  LANGUAGE_TEXT(4, "A\xfan no me has\nsatisfecho.\n\nDespu\xe9s de todo,\neres duelista.\n\nAs\xed que lucharemos.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(83)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC4C, map_33_state_05_08EBEC4C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(410)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "Hmm... I haven't dueled for\nso long my instincts are\n\nrusty.\n\n")
  LANGUAGE_TEXT(1, "Hmm... Mon intuition\nme fait d\xe9faut,\n\nje ne l'utilise s\xfbrement\npas assez.\n\n")
  LANGUAGE_TEXT(2, "Hmm... Meine Instinkte sind\nwohl etwas eingerostet.\n\n")
  LANGUAGE_TEXT(3, "Hmm... I miei istinti\ndevono essersi\n\narrugginiti per\nl'inattivit\xe0.\n\n")
  LANGUAGE_TEXT(4, "Hmm... Mis instintos\ndeben de estar\n\noxidados por falta\nde uso.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Making excuses?\nSome sage.\n\n")
  LANGUAGE_TEXT(1, "Tu te trouves des excuses ?\nEh bien, pour un sage...\n\n")
  LANGUAGE_TEXT(2, "Du machst Ausfl\xfcchte?\nEin sch\xf6ner Weiser.\n\n")
  LANGUAGE_TEXT(3, "Cerchi delle scuse?\nMa che saggio.\n\n")
  LANGUAGE_TEXT(4, "Excusas, \xbfeh?\nAlg\xfan sabio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "...Oh well.\n\nI will grant your wish.\n\nPegasus is on his island.\n\nThe island is cloaked by a\nmagical barrier.\n\nI shall extinguish that\nbarrier for you.\n\nHah!\n\n")
  LANGUAGE_TEXT(1, "... Ca ira.\n\nBien. Votre v\u0153u sera\nexauc\xe9.\n\nPegasus est sur son \xeele.\n\nCette \xeele est\nentour\xe9e d'une barri\xe8re.\n\nJe casserai cette\nbarri\xe8re pour vous.\n\nHah !\n\n")
  LANGUAGE_TEXT(2, "... Das reicht.\n\nNa gut. Euer Wunsch sei\neuch gew\xe4hrt.\n\nPegasus ist auf seiner\nInsel.\n\nDie Insel ist durch eine\nBarriere verh\xfcllt.\n\nIch werde sie f\xfcr euch\ndurchbrechen.\n\nHah!\n\n")
  LANGUAGE_TEXT(3, "... Basta cos\xec.\n\nBene, il vostro desiderio\nsar\xe0 esaudito.\n\nPegasus \xe8 sulla\nsua isola.\n\nL'isola \xe8 protetta\nda una barriera.\n\nInfranger\xf2 per voi\nquella barriera.\n\nHah!\n\n")
  LANGUAGE_TEXT(4, "... Eso servir\xe1.\n\nBien. Vuestros deseos\nse cumplir\xe1n.\n\nPegasus est\xe1 en su isla.\n\nLa isla est\xe1 rodeada\npor una barrera.\n\nRomper\xe9 esa barrera\npara vosotros.\n\n\xa1Aj\xe1!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(331)
  SPECIAL(0)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "That is all I can do\nto help you.\n\nI'm afraid the rest is\nentirely up to you.\n\nThe hope of the world rests\nwith you...\n\n")
  LANGUAGE_TEXT(1, "C'est tout ce que je\npeux faire pour vous.\n\nLe reste, c'est \xe0 vous\nde le r\xe9aliser.\n\nLe monde\ncompte sur vous...\n\n")
  LANGUAGE_TEXT(2, "Mehr kann ich nicht f\xfcr\neuch tun.\n\nAlles andere liegt dann\nbei euch.\n\nDie Hoffnung der Welt\nruht auf euch...\n\n")
  LANGUAGE_TEXT(3, "Non posso fare altro\nper voi.\n\nMi spiace, ma voi dovrete\nfare tutto il resto.\n\nLe speranze del mondo\nsono riposte su di voi...\n\n")
  LANGUAGE_TEXT(4, "Es todo lo que puedo\nhacer por vosotros.\n\nEl resto, me temo, os\ntoca a vosotros.\n\nLa esperanza del mundo est\xe1\nen vuestras manos...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(2, 2)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  DELAY(32)
  PORTRAIT(PORTRAIT_JOEY, 5, 8)
  LANGUAGE_TEXT(0, "Wh-what?\nHe disappeared?\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ?\nIl a disparu ?\n\n")
  LANGUAGE_TEXT(2, "W-was? Er ist\neinfach verschwunden?\n\n")
  LANGUAGE_TEXT(3, "Ehi, ma cosa...?\n\xc8 scomparso?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ...qu\xe9?\n\xbfHa desaparecido?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "What a strange old man.\n\n")
  LANGUAGE_TEXT(1, "Quel vieillard incroyable !\n\n")
  LANGUAGE_TEXT(2, "Ein toller alter Herr.\n\n")
  LANGUAGE_TEXT(3, "Che vecchio fantastico.\n\n")
  LANGUAGE_TEXT(4, "\xa1Qu\xe9 fant\xe1stico anciano!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 5, 8)
  LANGUAGE_TEXT(0, "Strange? Freaktacular, I'd\nsay. Let's get outta here.\n\n")
  LANGUAGE_TEXT(1, "Incroyable ? Je dirais\nplut\xf4t effrayant...\n\nPartons d'ici.\n\n")
  LANGUAGE_TEXT(2, "Toll? Ausgeflippt, w\xfcrde\nich eher sagen.\n\nMachen wir, dass wir hier\nrauskommen.\n\n")
  LANGUAGE_TEXT(3, "Fantastico? Io lo\ndefinirei stravagante.\n\nAndiamocene da qui.\n\n")
  LANGUAGE_TEXT(4, "\xbfFant\xe1stico? Raro, dir\xeda\nyo. Salgamos de aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Yes, let's go to Pegasus's\nisland, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Oui, allons sur l'\xeele de\nPegasus, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Ja, auf zu Pegasus'\nInsel, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "S\xec, andiamo sull'isola di\nPegasus, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed, vamos a la isla de\nPegasus, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(158)
  SET_FLAG(250)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC34, map_33_state_05_08EBEC34, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC40, map_33_state_05_08EBEC40, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "What's that?\nYou don't know?\n\nThat's the wrong card.\n\n")
  LANGUAGE_TEXT(1, "Comment \xe7a ?\nVous ne savez pas ?\n\nCe n'est pas celle-l\xe0.\n\n")
  LANGUAGE_TEXT(2, "Was? Ihr wisst es gar\nnicht?\n\nDie ist es jedenfalls nicht.\n\n")
  LANGUAGE_TEXT(3, "Ma come? Non lo\nsapete davvero?\n\nNon \xe8 quella.\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 es eso?\n\xbfDe verdad no lo sab\xe9is?\n\nEsa no es.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  OBJECT_EFFECT(24577, 2)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FADE_SCREEN(4)
  WARP(31, 7, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBF8, map_33_state_05_08EBEBF8, 0x08EBEC04, 0x08F04040)
  PORTRAIT(PORTRAIT_PARADOX, 0, 8)
  LANGUAGE_TEXT(0, "Don't disappoint me.\n\nAt least pretend that you\nknow!\n\n")
  LANGUAGE_TEXT(1, "Non, non.\nVous me d\xe9cevez.\n\nFaites au moins\nsemblant de savoir.\n\n")
  LANGUAGE_TEXT(2, "Nein, nein.\nEntt\xe4uscht mich nicht.\n\nTut doch wenigstens so,\nals w\xfcsstet ihr es!\n\n")
  LANGUAGE_TEXT(3, "Ma no, no.\nNon mi deludete.\n\nAlmeno fate finta\ndi capire!\n\n")
  LANGUAGE_TEXT(4, "No, no.\nNo me decepcion\xe9is.\n\n\xa1Al menos, pretended\nque sab\xe9is!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
