#include "event_macros.h"
#include "overworld.h"

/* map_48_state_03: map 48 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EDE8CC, map_48_state_03_08EDE8CC, 0x08EDE8F0, 0x08F04040)
  PLAY_MUSIC(17)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm also going to give\neverything I've got.\n\nI have to get the spirit of\nthe Puzzle back...\n\n")
  LANGUAGE_TEXT(1, "Je vais aussi me\ndonner au maximum.\n\nJe dois r\xe9cup\xe9rer\nmon autre moi.\n\n")
  LANGUAGE_TEXT(2, "Auch ich werde mein Bestes\ngeben.\n\nIch muss mein anderes Ich\nzur\xfcckbekommen...\n\n")
  LANGUAGE_TEXT(3, "Anch'io ce la\nmetter\xf2 tutta.\n\nDevo fare tornare\nl'altro me stesso...\n\n")
  LANGUAGE_TEXT(4, "Yo tambi\xe9n pondr\xe9 toda la\ncarne en el asador.\n\nTengo que recuperar\na mi otro yo...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE8F0, map_48_state_03_08EDE8F0, 0x08EDE8FC, 0x08F04040)
  WALK_OBJECT_X(2, 48)
  SWAP_OBJECT_SPRITE(2, 23)
  WALK_OBJECT_Y(2, 42)
  MOVE_OBJECT(2, 0, 0, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  WALK_OBJECT_X(3, 72)
  SWAP_OBJECT_SPRITE(3, 24)
  WALK_OBJECT_Y(3, 42)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(404)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Fufufu... Excellent, well\ndone! You didn't turn tail\n\nand run.\n\n")
  LANGUAGE_TEXT(1, "Fufufu... Bien, bien,\nvous avez su faire face.\n\n")
  LANGUAGE_TEXT(2, "Fufufu... Sehr sch\xf6n, ihr\nhabt euch also nicht\n\nvor Angst davongemacht.\n\n")
  LANGUAGE_TEXT(3, "Eheheh...Bene bene, non ve\nla siete data a gambe.\n\n")
  LANGUAGE_TEXT(4, "Fufufu... Bien, bien,\nno salisteis corriendo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hooray! We wouldn't have it\nany other way.\n\nThe pieces of the Millennium\nPuzzle are on the top floor\n\nof the castle.\n\n")
  LANGUAGE_TEXT(1, "Nous n'aurions pas\nfait autrement.\n\nLes morceaux du Puzzle\ndu mill\xe9nium sont ici.\n\nA l'\xe9tage sup\xe9rieur\ndu ch\xe2teau.\n\n")
  LANGUAGE_TEXT(2, "Das gef\xe4llt uns.\n\nDie Teile des Millenniums-\npuzzles sind hier.\n\nIm obersten Stockwerk\nder Burg.\n\n")
  LANGUAGE_TEXT(3, "Non c'era altro modo\nper procurarselo.\n\nI pezzi del Puzzle\nMillenario sono qui.\n\nAll'ultimo piano\ndel castello.\n\n")
  LANGUAGE_TEXT(4, "No aceptar\xedamos\nninguna otra cosa.\n\nLas piezas del Puzzle del\nMilenio est\xe1n aqu\xed.\n\nEn el piso m\xe1s\nalto del castillo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 1)
  LANGUAGE_TEXT(0, "Of course, we don't\nintend...\n\n")
  LANGUAGE_TEXT(1, "Bien s\xfbr, nous n'avons\npas l'intention...\n\n")
  LANGUAGE_TEXT(2, "Nat\xfcrlich werden wir\neuch...\n\n")
  LANGUAGE_TEXT(3, "Naturalmente, non\nabbiamo intenzione di...\n\n")
  LANGUAGE_TEXT(4, "Por supuesto, no\npretendemos...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 0)
  LANGUAGE_TEXT(0, "...To let you go there\nbecause this is your end!\n\n")
  LANGUAGE_TEXT(1, "... De vous laisser\naller jusque l\xe0.\n\n")
  LANGUAGE_TEXT(2, "... Aber nicht dorthin\nlassen.\n\n")
  LANGUAGE_TEXT(3, "... Lasciarvi andare lass\xf9.\n\n")
  LANGUAGE_TEXT(4, "... Permitiros ir.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, which one will you\nduel?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, lequel veux-tu\naffronter en duel ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, mit wem willst\ndu dich duellieren?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, con quale\nvuoi duellare?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfcon\nqui\xe9n luchar\xe1s?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE8FC, map_48_state_03_08EDE8FC, 0x08EDE908, 0x08EDE914)
  LANGUAGE_TEXT(0, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Para\nDox{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE908, map_48_state_03_08EDE908, 0x08EDE920, 0x08F0404C)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "So, {PLAYER} shall be mine?\n\n")
  LANGUAGE_TEXT(1, "Alors {PLAYER},\ntu vas m'appartenir ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER} wird also\nmir geh\xf6ren?\n\n")
  LANGUAGE_TEXT(3, "Allora, {PLAYER}\nsar\xe0 mio?\n\n")
  LANGUAGE_TEXT(4, "As\xed que, \xbf{PLAYER}\nser\xe1 m\xedo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Younger brother, I entrust\nyou with Yugi.\n\n")
  LANGUAGE_TEXT(1, "Fr\xe9rot, je te confie Yugi.\n\n")
  LANGUAGE_TEXT(2, "Bruder, ich vertraue dir\nYugi an.\n\n")
  LANGUAGE_TEXT(3, "Fratello, ti affido Yugi.\n\n")
  LANGUAGE_TEXT(4, "Hermano, te\nconf\xedo a Yugi.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Elder brother, leave him to\nme.\n\n")
  LANGUAGE_TEXT(1, "Je m'occupe de lui, fr\xe9rot.\n\n")
  LANGUAGE_TEXT(2, "Bruder, \xfcberlass ihn nur\nmir.\n\n")
  LANGUAGE_TEXT(3, "Fratello, lascialo a me.\n\n")
  LANGUAGE_TEXT(4, "Hermano, d\xe9jamelo\na m\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 66)
  MOVE_OBJECT(3, 0, 0, 0)
  WALK_OBJECT_X(2, 54)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's do it, {PLAYER}!\n\nIt's time to duel!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, {PLAYER} !\n\nBattons-nous en duel !\n\n")
  LANGUAGE_TEXT(2, "Packen wir's, {PLAYER}!\n\nDuell!\n\n")
  LANGUAGE_TEXT(3, "Diamoci dentro, {PLAYER}!\n\nForza, duella!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, {PLAYER}!\n\n\xa1Lucha!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 66)
  WALK_OBJECT_Y(1, 48)
  WALK_OBJECT_X(0, 54)
  WALK_OBJECT_Y(0, 48)
  DELAY(16)
  DUEL(162)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE920, map_48_state_03_08EDE920, 0x08EDE938, 0x08F04040)
  PLAY_MUSIC(404)
  HIDE_PORTRAIT()
  DELAY(16)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(32)
  SLIDE_OBJECT(1, 0, 2)
  DELAY(16)
  SLIDE_OBJECT(3, 0, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "He's a lot stronger... Much\nmore powerful than\n\nbefore...\n\nBut I can't lose!\n\nI've got to save my other\nself!\n\nSpirit of the Puzzle! Lend\nme your strength!\n\n")
  LANGUAGE_TEXT(1, "Il est bien plus fort...\nBien plus qu'avant...\n\nMais je ne peux\npas perdre !\n\nJe dois sauver\nl'autre moi !\n\nL'autre moi ! Pr\xeate-\nmoi ta puissance !\n\n")
  LANGUAGE_TEXT(2, "Er ist viel st\xe4rker...\nViel st\xe4rker als zuvor...\n\nAber ich darf nicht\nverlieren!\n\nIch muss mein anderes\nIch befreien!\n\nAnderes Ich! Schenk mir\ndeine Kraft!\n\n")
  LANGUAGE_TEXT(3, "\xc8 molto pi\xf9 forte...\nMolto pi\xf9 di prima...\n\nMa non posso perdere!\n\nDevo salvare l'altro\nme stesso!\n\nAltro me stesso!\nPrestami il tuo potere!\n\n")
  LANGUAGE_TEXT(4, "Es mucho m\xe1s fuerte...\nMucho m\xe1s que antes...\n\n\xa1Pero no puedo perder!\n\n\xa1Tengo que salvar\na mi otro yo!\n\n\xa1Mi otro yo!\n\xa1Dame tu poder!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's go, Dark Magician!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, Magicien\ndes t\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Los, Dark Magician!\n\n")
  LANGUAGE_TEXT(3, "Forza, Mago Oscuro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, Mago oscuro!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 8)
  DELAY(16)
  SLIDE_OBJECT(3, 2, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, 1)
  LANGUAGE_TEXT(0, "Wh-what?! No! Not now!\n\nHow could he draw the Dark\nMagician now?\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ?! Non !\nPas maintenant !\n\nComment a-t-il pu tirer\nun Magicien des t\xe9n\xe8bres ?\n\n")
  LANGUAGE_TEXT(2, "W-was?!\nNein, nicht jetzt!\n\nWie konnte er jetzt nur\neinen Dark Magician ziehen?\n\n")
  LANGUAGE_TEXT(3, "Che... che cosa?!\nNo! Non adesso!\n\nCome ha fatto a tirare un\nMago Oscuro, adesso?\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfQ-qu\xe9?!\n\xa1No! \xa1Ahora no!\n\n\xbfC\xf3mo ha podido sacar\nun Mago oscuro ahora?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Dark Magic Attack!\n\n")
  LANGUAGE_TEXT(1, "La magie noire !\n\n")
  LANGUAGE_TEXT(2, "Dunkler Zauber!\n\n")
  LANGUAGE_TEXT(3, "Magia Oscura!\n\n")
  LANGUAGE_TEXT(4, "\xa1Magia oscura!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(376)
  COMMAND_7C_ARG(8, 38)
  DELAY(16)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, 1)
  LANGUAGE_TEXT(0, "Gwaaaaaaah!\n\n")
  LANGUAGE_TEXT(1, "Gouaaaaah !\n\n")
  LANGUAGE_TEXT(2, "Gwaaaaaaah!\n\n")
  LANGUAGE_TEXT(3, "Guaaaaaah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Gwaaaaaaah!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(284)
  SLIDE_OBJECT(3, 2, 4)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE938, map_48_state_03_08EDE938, 0x08EDE944, 0x08F04040)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You... You're not getting\naway with this!\n\n")
  LANGUAGE_TEXT(1, "Vous... Vous n'allez pas\nvous en sortir comme \xe7a !\n\n")
  LANGUAGE_TEXT(2, "Du... Damit kommst du\nnicht davon!\n\n")
  LANGUAGE_TEXT(3, "Voi... Non la passerete\nliscia per questo!\n\n")
  LANGUAGE_TEXT(4, "Vosotros... \xa1no\nvais a ganar!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "We must stop them, no matter\nwhat it takes!\n\n")
  LANGUAGE_TEXT(1, "Nous devons \xe0 tout\nprix les arr\xeater !\n\n")
  LANGUAGE_TEXT(2, "Wir m\xfcssen sie um jeden\nPreis aufhalten!\n\n")
  LANGUAGE_TEXT(3, "Dobbiamo fermarli qui,\nin un modo o nell'altro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hemos de detenerlos\naqu\xed! \xa1Como sea!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Our reputation is at stake!\n\n")
  LANGUAGE_TEXT(1, "Notre r\xe9putation\nen d\xe9pend !\n\n")
  LANGUAGE_TEXT(2, "Unser Ruf steht auf dem\nSpiel!\n\n")
  LANGUAGE_TEXT(3, "\xc8 in gioco la nostra\nstessa reputazione!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nuestra reputaci\xf3n\nest\xe1 en juego!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Come on! We duel again!\n\n")
  LANGUAGE_TEXT(1, "Allez ! Battons-nous\nencore en duel !\n\n")
  LANGUAGE_TEXT(2, "Los! Duellieren wir uns\nnoch einmal!\n\n")
  LANGUAGE_TEXT(3, "Forza!\nDuelliamo di nuovo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos!\n\xa1Luchamos de nuevo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE944, map_48_state_03_08EDE944, 0x08EDE950, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 2, 4, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 1)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE950, map_48_state_03_08EDE950, 0x08EDE95C, 0x08EDE98C)
  CHECK_FLAG(197)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE95C, map_48_state_03_08EDE95C, 0x08EDE968, 0x08EDE974)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I... I just want to save\nhim...\n\nI want to save my other\nself...\n\n")
  LANGUAGE_TEXT(1, "Je... Je veux\njuste le sauver...\n\nJe veux sauver\nl'autre moi...\n\n")
  LANGUAGE_TEXT(2, "Ich... Ich will es nur\nretten...\n\nMein anderes Ich...\n\n")
  LANGUAGE_TEXT(3, "Io...\nVoglio solo salvarlo...\n\nVoglio salvare l'altro\nme stesso...\n\n")
  LANGUAGE_TEXT(4, "Yo...\nS\xf3lo quiero salvarle...\n\nQuiero salvar a mi\notro yo...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(332)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  SET_FLAG(243)
  CHECK_FLAG(198)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE968, map_48_state_03_08EDE968, 0x08F04040, 0x08F04040)
  WARP(14, 9, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE974, map_48_state_03_08EDE974, 0x08F04040, 0x08F04040)
  WARP(14, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE98C, map_48_state_03_08EDE98C, 0x08EDE998, 0x08F04040)
  PLAY_MUSIC(400)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE998, map_48_state_03_08EDE998, 0x08EDE9A4, 0x08EDE9B0)
  LANGUAGE_TEXT(0, "I can't be defeated here...\n\nI have to keep going or I'll\nnever rescue him!\n\n")
  LANGUAGE_TEXT(1, "Je ne peux pas\nrester bloqu\xe9 ici.\n\nJe dois avancer pour\nsauver l'autre moi.\n\n")
  LANGUAGE_TEXT(2, "Was nutzt es, wenn ich\nhier festsitze...\n\nIch muss weiter, um mein\nanderes Ich zu retten.\n\n")
  LANGUAGE_TEXT(3, "Non mi conviene\nbloccarmi qui...\n\nDevo andare avanti per\nsalvare l'altro me stesso.\n\n")
  LANGUAGE_TEXT(4, "No es bueno para\nm\xed atascarme aqu\xed...\n\nTengo que seguir para\nsalvar a mi otro yo.\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(200)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE9A4, map_48_state_03_08EDE9A4, 0x08EDE9BC, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE9BC, map_48_state_03_08EDE9BC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}! Let me handle\nthem!\n\nYou keep going!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} ! Laisse-\nmoi m'en occuper !\n\nTu ferais mieux de\nte mettre en route !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}!\n\xdcberlass das mir!\n\nDu musst weitergehen!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}!\nLasciali a me!\n\nTu devi andare avanti!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}!\n\xa1Yo me ocupo de ellos!\n\n\xa1Tienes que seguir!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 0)
  LANGUAGE_TEXT(0, "Wahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Ouahahahahaha !\n\n")
  LANGUAGE_TEXT(2, "Wahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Uahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Wahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 1)
  LANGUAGE_TEXT(0, "You mean to take on...\n\n")
  LANGUAGE_TEXT(1, "Tu veux nous\naffronter...\n\n")
  LANGUAGE_TEXT(2, "Du willst es also mit...\n\n")
  LANGUAGE_TEXT(3, "Vorresti sfidare...\n\n")
  LANGUAGE_TEXT(4, "\xbfDices pelear con...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 0)
  LANGUAGE_TEXT(0, "...The both of us? All\nalone?\n\n")
  LANGUAGE_TEXT(1, "... Tous les deux en\nduel ? Et tout seul ?\n\n")
  LANGUAGE_TEXT(2, "... Uns beiden im Duell\naufnehmen? Allein?\n\n")
  LANGUAGE_TEXT(3, "... Noi due a duello?\nTu, da solo?\n\n")
  LANGUAGE_TEXT(4, "... \xbfNosotros dos en\nduelos? \xbfSolo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm not alone!\n\nThe spirit of the Puzzle is\nalways with me!\n\nYou stole the pieces of the\nMillennium Puzzle...\n\nAnd the spirit!\n\nI'm never going to forgive\nyou!\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas seul !\n\nMon autre moi\nm'accompagne !\n\nVous avez vol\xe9 les pi\xe8ces\ndu Puzzle du mill\xe9nium...\n\nVous avez subtilis\xe9 l'esprit\nde mon autre moi !\n\nJe ne vous pardonnerai\njamais !\n\n")
  LANGUAGE_TEXT(2, "Ich bin nicht allein!\n\nMein anderes Ich steht\nmir stets zur Seite!\n\nIhr habt die Teile des Mill-\nenniumspuzzles gestohlen...\n\nDen Geist meines anderen\nIchs!\n\nDas werde ich euch nie\nverzeihen!\n\n")
  LANGUAGE_TEXT(3, "Non sono affatto solo!\n\nL'altro me stesso \xe8\nsempre con me!\n\nAvete preso i pezzi del\nPuzzle Millenario...\n\nAvete preso lo spirito\ndell'altro me stesso!\n\nNon ve lo perdoner\xf2 mai!\n\n")
  LANGUAGE_TEXT(4, "\xa1No estoy solo!\n\n\xa1Mi otro yo est\xe1\nsiempre conmigo!\n\nOs llevasteis las piezas\ndel Puzzle del Milenio...\n\n\xa1Os llevasteis el esp\xedritu\nde mi otro yo!\n\n\xa1Nunca os perdonar\xe9!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 12)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Th-then we shall duel!\n\n")
  LANGUAGE_TEXT(1, "Alors, battons-nous !\n\n")
  LANGUAGE_TEXT(2, "D-dann duellieren wir uns!\n\n")
  LANGUAGE_TEXT(3, "E-e allora duelliamo!\n\n")
  LANGUAGE_TEXT(4, "\xa1E-entonces lucharemos!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "And settle matters for sure!\n\n")
  LANGUAGE_TEXT(1, "Et r\xe9glons cela une\nbonne fois pour toutes !\n\n")
  LANGUAGE_TEXT(2, "Entscheiden wir den\nKampf ein f\xfcr alle Mal!\n\n")
  LANGUAGE_TEXT(3, "Sistemiamo la faccenda\nuna volta per tutte!\n\n")
  LANGUAGE_TEXT(4, "\xa1Y zanjaremos lo que se\ntercie para siempre!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 56)
  MOVE_OBJECT(2, 0, 0, 0)
  WALK_OBJECT_X(3, 64)
  MOVE_OBJECT(3, 0, 0, 0)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 42)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}! I'm counting on\nyou!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} ! Maintenant,\nc'est \xe0 toi de jouer !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}!\nJetzt liegt es bei dir!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}!\nOra dipende tutto da te!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}!\n\xa1Todo depende de ti!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(32)
  WALK_OBJECT_X(0, 49)
  WALK_OBJECT_Y(0, 18)
  DELAY(32)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Grrr... This kid... He's\ngood...\n\n")
  LANGUAGE_TEXT(1, "Grrr... Ce gamin...\nIl est tr\xe8s fort...\n\n")
  LANGUAGE_TEXT(2, "Grrr... Dieser Junge...\nEr ist gut...\n\n")
  LANGUAGE_TEXT(3, "Grrr... Questo ragazzino...\n\xc8 in gamba...\n\n")
  LANGUAGE_TEXT(4, "Grrr... Este ni\xf1o...\nEs bueno...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Is he really dueling by\nhimself?\n\n")
  LANGUAGE_TEXT(1, "Il se bat vraiment seul ?\n\n")
  LANGUAGE_TEXT(2, "K\xe4mpft er wirklich\nallein?\n\n")
  LANGUAGE_TEXT(3, "Sta veramente\nduellando da solo?\n\n")
  LANGUAGE_TEXT(4, "\xbfRealmente lucha solo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Leave them to me! Keep\ngoing!\n\n")
  LANGUAGE_TEXT(1, "Laisse-moi m'occuper d'eux !\nTu dois avancer !\n\n")
  LANGUAGE_TEXT(2, "\xdcberlass sie nur mir!\nDu musst weitergehen!\n\n")
  LANGUAGE_TEXT(3, "A loro ci penso io!\nTu devi andare avanti!\n\n")
  LANGUAGE_TEXT(4, "\xa1D\xe9jamelos a m\xed!\n\xa1Has de seguir!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(48)
  WALK_OBJECT_Y(0, 0)
  SHOW_OBJECT(0, 128, 96, 0, 0, 0)
  SET_FLAG(143)
  SET_FLAG(242)
  WARP(49, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE9B0, map_48_state_03_08EDE9B0, 0x08EDE9BC, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE914, map_48_state_03_08EDE914, 0x08EDE92C, 0x08F0404C)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{PLAYER}... An opponent most\nworthy.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}... Un\ntr\xe8s noble adversaire.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}... Ein\nw\xfcrdiger Gegner.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}... Un\navversario pi\xf9 che degno.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}... Un oponente\nde lo m\xe1s digno.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Elder brother, I leave you\nto take down Yugi.\n\n")
  LANGUAGE_TEXT(1, "Fr\xe9rot, charge-toi de nous\nd\xe9barrasser de Yugi.\n\n")
  LANGUAGE_TEXT(2, "Bruder, ich \xfcberlass Yugi\ndir.\n\n")
  LANGUAGE_TEXT(3, "Fratello, tu sistema Yugi.\n\n")
  LANGUAGE_TEXT(4, "Hermano, te dejo\nderrotar a Yugi.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "It shall be done!\n\n")
  LANGUAGE_TEXT(1, "Avec plaisir !\n\n")
  LANGUAGE_TEXT(2, "So sei es!\n\n")
  LANGUAGE_TEXT(3, "Sar\xe0 fatto!\n\n")
  LANGUAGE_TEXT(4, "\xa1As\xed se har\xe1!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 54)
  MOVE_OBJECT(2, 0, 0, 0)
  WALK_OBJECT_X(3, 66)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's do it, {PLAYER}!\n\nIt's time to duel!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, {PLAYER} !\n\nBattons-nous en duel !\n\n")
  LANGUAGE_TEXT(2, "Packen wir's, {PLAYER}!\n\nDuell!\n\n")
  LANGUAGE_TEXT(3, "Diamoci dentro, {PLAYER}!\n\nForza, duella!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, {PLAYER}!\n\n\xa1Lucha!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 54)
  WALK_OBJECT_Y(1, 48)
  WALK_OBJECT_X(0, 66)
  WALK_OBJECT_Y(0, 48)
  DELAY(16)
  DUEL(163)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDE92C, map_48_state_03_08EDE92C, 0x08EDE938, 0x08F04040)
  PLAY_MUSIC(404)
  HIDE_PORTRAIT()
  DELAY(16)
  SLIDE_OBJECT(3, 2, 4)
  DELAY(32)
  SLIDE_OBJECT(1, 0, 2)
  DELAY(16)
  SLIDE_OBJECT(2, 0, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "He's a lot stronger... Much\nmore powerful than\n\nbefore...\n\nBut I can't lose!\n\nI've got to save my other\nself!\n\nSpirit of the Puzzle! Lend\nme your strength!\n\n")
  LANGUAGE_TEXT(1, "Il est bien plus fort...\nBien plus qu'avant...\n\nMais je ne peux\npas perdre !\n\nJe dois sauver\nl'autre moi !\n\nL'autre moi ! Pr\xeate-\nmoi ta puissance !\n\n")
  LANGUAGE_TEXT(2, "Er ist viel st\xe4rker...\nViel st\xe4rker als zuvor...\n\nAber ich darf nicht\nverlieren!\n\nIch muss mein anderes\nIch befreien!\n\nAnderes Ich! Schenk mir\ndeine Kraft!\n\n")
  LANGUAGE_TEXT(3, "\xc8 molto pi\xf9 forte...\nMolto pi\xf9 di prima...\n\nMa non posso perdere!\n\nDevo salvare l'altro\nme stesso!\n\nAltro me stesso!\nPrestami il tuo potere!\n\n")
  LANGUAGE_TEXT(4, "Es mucho m\xe1s fuerte...\nMucho m\xe1s que antes...\n\n\xa1Pero no puedo perder!\n\n\xa1Tengo que salvar\na mi otro yo!\n\n\xa1Mi otro yo!\n\xa1Dame tu poder!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's go, Dark Magician!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, Magicien\ndes t\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Los, Dark Magician!\n\n")
  LANGUAGE_TEXT(3, "Forza, Mago Oscuro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, Mago oscuro!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 8)
  DELAY(16)
  SLIDE_OBJECT(2, 2, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, 0)
  LANGUAGE_TEXT(0, "Wh-what?! No! Not now!\n\nHow could he draw the Dark\nMagician now?\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ?! Non !\nPas maintenant !\n\nComment a-t-il pu tirer\nun Magicien des t\xe9n\xe8bres ?\n\n")
  LANGUAGE_TEXT(2, "W-was?!\nNein, nicht jetzt!\n\nWie konnte er jetzt nur\neinen Dark Magician ziehen?\n\n")
  LANGUAGE_TEXT(3, "Che... che cosa?!\nNo! Non adesso!\n\nCome ha fatto a tirare un\nMago Oscuro, adesso?\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfQ-qu\xe9?!\n\xa1No! \xa1Ahora no!\n\n\xbfC\xf3mo ha podido sacar\nun Mago oscuro ahora?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Dark Magic Attack!\n\n")
  LANGUAGE_TEXT(1, "La magie noire !\n\n")
  LANGUAGE_TEXT(2, "Dunkler Zauber!\n\n")
  LANGUAGE_TEXT(3, "Magia Oscura!\n\n")
  LANGUAGE_TEXT(4, "\xa1Magia oscura!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(376)
  COMMAND_7C_ARG(8, 38)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, 0)
  LANGUAGE_TEXT(0, "Gwaaaaaaah!\n\n")
  LANGUAGE_TEXT(1, "Gouaaaaah !\n\n")
  LANGUAGE_TEXT(2, "Gwaaaaaaah!\n\n")
  LANGUAGE_TEXT(3, "Guaaaaaah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Gwaaaaaaah!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(284)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(16)
  SET_FLAG(200)
  FALLTHROUGH()
END_EVENT_SCRIPT()
