#include "event_macros.h"
#include "overworld.h"

/* map_05_state_02: map 5 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E50F20, map_05_state_02_08E50F20, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, no, no... My\nHyozanryu...\n\nThe Neo Ghouls ripped it\noff.\n\nThey couldn't care less\nabout having a fair duel.\n\n")
  LANGUAGE_TEXT(1, "Zut, zut et rezut...\nMon Hyozanryu...\n\nLes Neo Ghouls\nl'ont d\xe9truit.\n\nIls s'en foutent\nd'\xeatre \xe9quitables.\n\n")
  LANGUAGE_TEXT(2, "Mist, Mist...\nMein Hyozanryu...\n\nDie Neo Ghouls haben\nihn mir abgekn\xf6pft.\n\nFair Play kennen sie wohl\nnicht.\n\n")
  LANGUAGE_TEXT(3, "No, no, dannazione...\nLa mia Hyozanryu...\n\nMe l'hanno rubata\ni Neo Ghouls.\n\nNon ci provano nemmeno\na giocare lealmente.\n\n")
  LANGUAGE_TEXT(4, "Huy, huy, huy...\nMi Hyozanryu...\n\nLos Neo Ghouls lo\nrajaron.\n\nLes tiene sin cuidado\nser justos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F2C, map_05_state_02_08E50F2C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "How do you expect me to duel\nwithout my rare cards?\n\n")
  LANGUAGE_TEXT(1, "Comment est-ce que je\npeux me battre en duel\n\nsans mes cartes rares ?\n\n")
  LANGUAGE_TEXT(2, "Wie soll ich ohne meine\nseltenen Karten k\xe4mpfen?\n\n")
  LANGUAGE_TEXT(3, "Come pretendi che duelli\nsenza le mie carte rare?\n\n")
  LANGUAGE_TEXT(4, "\xbfC\xf3mo esperas que luche\nsin mis cartas raras?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F38, map_05_state_02_08E50F38, 0x08E50F44, 0x08E50F74)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Domino duelists are\nspineless wimps!\n\nNo one's shown the least bit\nof resistance!\n\n")
  LANGUAGE_TEXT(1, "Les duellistes de Domino,\nce sont des l\xe2ches\n\ninvert\xe9br\xe9s !\n\nIls n'ont m\xeame\npas r\xe9sist\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Domino-Duellanten sind\nfeige!\n\nKeiner zeigt den geringsten\nWiderstandswillen!\n\n")
  LANGUAGE_TEXT(3, "I duellanti di Domino\nsono inetti smidollati!\n\nNessuno ha mostrato la\nbench\xe9 minima resistenza!\n\n")
  LANGUAGE_TEXT(4, "\xa1Los duelistas de Domino\nson d\xe9biles peleles!\n\n\xa1Ni uno opuso la\nmenor resistencia!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(61)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F44, map_05_state_02_08E50F44, 0x08E50F50, 0x08E50F5C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F50, map_05_state_02_08E50F50, 0x08E50F68, 0x08F04040)
  PLAY_MUSIC(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F68, map_05_state_02_08E50F68, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You showed resistance...too\nmuch resistance!\n\n")
  LANGUAGE_TEXT(1, "Tu as trop r\xe9sist\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Du hast dich zu sehr\nwidersetzt!\n\n")
  LANGUAGE_TEXT(3, "Tu hai resistito fin troppo!\n\n")
  LANGUAGE_TEXT(4, "\xa1T\xfa resististe un mont\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 60)
  WALK_OBJECT_Y(3, 0)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F5C, map_05_state_02_08E50F5C, 0x08E50F68, 0x08F04040)
  PLAY_MUSIC(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F74, map_05_state_02_08E50F74, 0x08E50F80, 0x08F0404C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F80, map_05_state_02_08E50F80, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(79)
  CLEAR_FLAG(78)
  CLEAR_FLAG(182)
  CLEAR_FLAG(102)
  FALLTHROUGH()
END_EVENT_SCRIPT()
