#include "event_macros.h"
#include "overworld.h"

/* map_02_state_03: map 2 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E478E4, map_02_state_03_08E478E4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Those Neo Ghouls!\n\nThey'd better watch out or\nI'll pummel them next time!\n\n")
  LANGUAGE_TEXT(1, "Ces Neo Ghouls !\n\nIls ont int\xe9r\xeat \xe0 ce\nque je ne les voie plus !\n\n")
  LANGUAGE_TEXT(2, "Diese Neo Ghouls!\n\nSie k\xf6nnen nur hoffen, mir\nnie wieder zu begegnen!\n\n")
  LANGUAGE_TEXT(3, "Quei Neo Ghouls!\nSe dovessi incontrarli\n\ndi nuovo, faranno\nmeglio a stare attenti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Los Neo Ghouls esos!\n\n\xa1M\xe1s les vale vigilar por\nsi los veo otra vez!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E478F0, map_02_state_03_08E478F0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Zompire is the most\nawesomest ever! He's my\n\nhero!\n\nOne day, I'm going to be\nstrong, just like Zompire.\n\n")
  LANGUAGE_TEXT(1, "J'admire Zompire,\nle h\xe9ros t\xe9n\xe9breux.\n\nC'est mon h\xe9ros !\n\nUn jour, je serai\naussi fort que Zompire.\n\n")
  LANGUAGE_TEXT(2, "Ich bewundere den dunklen\nHelden Zompire. Cool!\n\nEines Tages werde ich so\nstark wie Zompire.\n\n")
  LANGUAGE_TEXT(3, "Ammiro l'oscuro eroe\nZompire. \xc8 il mio eroe!\n\nUn giorno sar\xf2 forte\ncome Zompire.\n\n")
  LANGUAGE_TEXT(4, "Admiro al h\xe9roe oscuro\nZompire. \xa1Es mi h\xe9roe!\n\nUn d\xeda ser\xe9 tan fuerte\ncomo Zompire.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E478FC, map_02_state_03_08E478FC, 0x08E47920, 0x08E47908)
  CHECK_FLAG(159)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47920, map_02_state_03_08E47920, 0x08F04040, 0x08F04040)
  PORTRAIT(6, 0, 8)
  LANGUAGE_TEXT(0, "Leave it to me!\n\nThe Neo Ghouls are no match\nfor me!\n\n")
  LANGUAGE_TEXT(1, "Je vais m'occuper de \xe7a !\n\nLes Neo Ghouls ne vont\npas s'en tirer comme \xe7a.\n\n")
  LANGUAGE_TEXT(2, "Ich k\xfcmmere mich um alles!\n\nDie Neo Ghouls kommen\nnicht so leicht davon.\n\n")
  LANGUAGE_TEXT(3, "Ci penser\xf2 io a loro!\n\nI Neo Ghouls non la\npasseranno liscia!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo me ocupar\xe9!\n\nLos Neo Ghouls no se\nsaldr\xe1n con la suya.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47908, map_02_state_03_08E47908, 0x08E47914, 0x08E47920)
  CHECK_FLAG(160)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47914, map_02_state_03_08E47914, 0x08F04040, 0x08F04040)
  PORTRAIT(6, 0, 8)
  LANGUAGE_TEXT(0, "There are Neo Ghouls still\nhiding in the Town of\n\nDomino?\n\nThat may explain some\nthings. There's something\n\nmysterious going on at\nKaibaCorp.\n\n")
  LANGUAGE_TEXT(1, "Alors, il y a des Neo Ghouls\nqui se cachent encore \xe0\n\nDomino ?\n\nCette Kaiba Corporation\ncache des trucs bizarres.\n\n")
  LANGUAGE_TEXT(2, "Es verbergen sich also\nnoch einige Neo Ghouls\n\nin Domino?\n\nMit der Kaiba Corporation\nstimmt etwas nicht.\n\n")
  LANGUAGE_TEXT(3, "Cos\xec, dei Neo Ghouls si\nnascondono ancora a\n\nDomino? Ho qualche sospetto\nsulla Kaiba Corporation.\n\n")
  LANGUAGE_TEXT(4, "\xbfAs\xed que a\xfan hay Neo Ghouls\nescondidos en Domino?\n\nHay gato encerrado\nen Kaiba Corporation.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4792C, map_02_state_03_08E4792C, 0x08E47938, 0x08F0404C)
  PORTRAIT(6, 0, 8)
  LANGUAGE_TEXT(0, "You want to duel me for\npractice before facing the\n\nNeo Ghouls?\n\nI hope I don't beat you so\nhard that you don't feel\n\nlike dueling ever again.\n\n")
  LANGUAGE_TEXT(1, "Tu veux un duel pour te\npr\xe9parer aux Neo Ghouls ?\n\nCe n'est pas ma faute si tu\nn'as pas confiance en toi.\n\n")
  LANGUAGE_TEXT(2, "Um dich f\xfcr den Kampf mit\nden Neo Ghouls aufzuw\xe4rmen\n\nm\xf6chtest du dich duellieren?\nDein fehlendes Selbstver-\n\ntrauen ist nicht meine\nSchuld.\n\n")
  LANGUAGE_TEXT(3, "Vuoi duellare per\nriscaldarti prima\n\ndi affrontare i Neo\nGhouls? Non \xe8\n\ncolpa mia se non\nti senti sicuro.\n\n")
  LANGUAGE_TEXT(4, "\xbfQuieres luchar como\ncalentamiento para\n\nlos Neo Ghouls?\n\nNo es culpa m\xeda si\npierdes la confianza.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(58)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E47938, map_02_state_03_08E47938, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(9)
  PORTRAIT(6, 0, 8)
  LANGUAGE_TEXT(0, "Good! Now show those same\ntechniques against the Neo\n\nGhouls.\n\n")
  LANGUAGE_TEXT(1, "C'est comme \xe7a qu'on\npeut se d\xe9barrasser\n\ndes Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "So kannst du die Neo\nGhouls fertig machen.\n\n")
  LANGUAGE_TEXT(3, "\xc8 cos\xec che potrai\nfare fuori i Neo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "As\xed es como puedes\naplastar a los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
