#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_03_state_02: map 3 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E4A91C, map_03_state_02_08E4A91C, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_KAIBA_FAN)
  LOAD_SPRITE(2, SPRITE_RED_HAIR)
  LOAD_SPRITE(3, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(4, SPRITE_NEO_GHOUL)
  PLAY_MUSIC(MUSIC_NEO_GHOULS_INVADE)
  TEXT("Help me!")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  WALK_OBJECT_X(1, 40)
  WALK_OBJECT_X(3, 28)
  DELAY(16)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Silence! Hand over your rare cards right now!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_LEFT, 8, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TEXT(
      "I never said I was putting up my rare cards as ante in",
      "this duel!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_LEFT, 8, 0)
  DELAY(16)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Well, you thought wrong! Give me your rare cards!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  TEXT("N-Neo Ghouls... You horrible stinking thugs...")
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Ha ha ha! Flattery will get you nowhere! All the",
      "world's rare cards belong to the Neo Ghouls!"
  )
  SET_FLAG(EVENT_FLAG_NEO_GHOULS_ATTACKED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A928, map_03_state_02_08E4A928, 0x08E4A934, 0x08E4A94C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_KAIBA_FAN_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A934, map_03_state_02_08E4A934, EVENT_NOP, EVENT_NOP)
  TEXT("H-help me, please!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A94C, map_03_state_02_08E4A94C, EVENT_NOP, EVENT_NOP)
  TEXT("The Neo Ghouls are awful people. Just awful.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A940, map_03_state_02_08E4A940, EVENT_NOP, EVENT_NOP)
  TEXT("Please, no! No more duels!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A958, map_03_state_02_08E4A958, 0x08E4A964, 0x08E4A97C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RED_HAIR_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A964, map_03_state_02_08E4A964, EVENT_NOP, EVENT_NOP)
  TEXT("M-my rare cards are gone...")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A97C, map_03_state_02_08E4A97C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "The Neo Ghouls have completely overrun the Town",
      "of Domino!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A970, map_03_state_02_08E4A970, EVENT_NOP, EVENT_NOP)
  TEXT("Duel... Please, I'm too scared....")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A988, map_03_state_02_08E4A988, 0x08E4A9A0, 0x08E4AA18)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'll take your rare cards, too!")
  DUEL(DUELIST_NEO_GHOUL_052)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9A0, map_03_state_02_08E4A9A0, 0x08E4A9AC, 0x08E4A9B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9AC, map_03_state_02_08E4A9AC, 0x08E4A9C4, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS_INVADE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9C4, map_03_state_02_08E4A9C4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Y-you punk! Don't think you'll win again!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_LEFT, 40, 0)
  SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA_FAN_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9B8, map_03_state_02_08E4A9B8, 0x08E4A9C4, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA18, map_03_state_02_08E4AA18, 0x08E4AA24, 0x08F0404C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA24, map_03_state_02_08E4AA24, 0x08F0404C, EVENT_NOP)
  CLEAR_FLAG(79)
  CLEAR_FLAG(78)
  CLEAR_FLAG(182)
  CLEAR_FLAG(102)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A994, map_03_state_02_08E4A994, 0x08E4A9A0, 0x08E4AA18)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "This is your first, and last, mistake!")
  DUEL(DUELIST_NEO_GHOUL_052)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9D0, map_03_state_02_08E4A9D0, 0x08E4A9E8, 0x08E4AA18)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You have some rare cards that I want.")
  DUEL(DUELIST_NEO_GHOUL_053)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9E8, map_03_state_02_08E4A9E8, 0x08E4A9F4, 0x08E4AA00)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9F4, map_03_state_02_08E4A9F4, 0x08E4AA0C, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS_INVADE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA0C, map_03_state_02_08E4AA0C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I may have lost, but there are many other Neo Ghouls",
      "waiting for you!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 32)
  WALK_OBJECT_X(4, 72)
  MOVE_OBJECT(4, DIRECTION_UP, 48, 0)
  SET_FLAG(EVENT_FLAG_DEFEATED_RED_HAIR_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA00, map_03_state_02_08E4AA00, 0x08E4AA0C, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9DC, map_03_state_02_08E4A9DC, 0x08E4A9E8, 0x08E4AA18)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You fool! You dare challenge me?")
  DUEL(DUELIST_NEO_GHOUL_053)
  FALLTHROUGH()
END_EVENT_SCRIPT()
