#include "event_macros.h"
#include "overworld.h"

/* map_14_state_01: map 14 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E774EC, map_14_state_01_08E774EC, 0x08E774F8, 0x08F04040)
  CHECK_FLAG(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E774F8, map_14_state_01_08E774F8, 0x08E77504, 0x08E7757C)
  PLAY_MUSIC(230)
  DELAY(16)
  WALK_OBJECT_Y(3, 32)
  DELAY(16)
  LANGUAGE_TEXT(0, "You're duelists?\n\n")
  LANGUAGE_TEXT(1, "Vous \xeates des duellistes ?\n\n")
  LANGUAGE_TEXT(2, "Ihr seid Duellanten?\n\n")
  LANGUAGE_TEXT(3, "Siete duellanti?\n\n")
  LANGUAGE_TEXT(4, "\xbfSois duelistas?\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77504, map_14_state_01_08E77504, 0x08E77510, 0x08F04040)
  WALK_OBJECT_Y(0, 44)
  WALK_OBJECT_Y(13, 54)
  WALK_OBJECT_Y(14, 54)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77510, map_14_state_01_08E77510, 0x08E7751C, 0x08F04040)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Ah, you are? Then please!\nStep on board!\n\nJust kidding! It's never\nthat easy.\n\n")
  LANGUAGE_TEXT(1, "Vous \xeates des duellistes ?\nBon, alors montez \xe0 bord !\n\nCa devrait toujours\nse passer comme \xe7a,\n\nmais \xe7a n'est pas\naussi facile que cela.\n\n")
  LANGUAGE_TEXT(2, "Seid ihr Duellanten?\nDann steigt ein!\n\nSo sollte es sein, aber so\neinfach ist es nie.\n\n")
  LANGUAGE_TEXT(3, "Siete duellanti? Allora\nsalite a bordo, prego!\n\nCos\xec dovrebbe essere, ma\nnon \xe8 mai cos\xec facile.\n\n")
  LANGUAGE_TEXT(4, "\xbfSois duelistas?\nEntonces, \xa1subid!\n\nAs\xed deber\xeda ser, pero\nnunca es tan f\xe1cil.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 32)
  DELAY(8)
  LANGUAGE_TEXT(0, "If you wish to board the\nDuel Express...\n\n")
  LANGUAGE_TEXT(1, "Si vous voulez monter \xe0\nbord du Duel Express...\n\n")
  LANGUAGE_TEXT(2, "Wenn ihr mit dem Duel\nExpress fahren wollt...\n\n")
  LANGUAGE_TEXT(3, "Se volete salire a bordo\ndel Duel Express...\n\n")
  LANGUAGE_TEXT(4, "Si quer\xe9is subir al\nDuel Express...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "You'll have to get by us\nfirst.\n\n")
  LANGUAGE_TEXT(1, "Vous allez devoir d'abord\nnous affronter.\n\n")
  LANGUAGE_TEXT(2, "... m\xfcsst ihr erst an uns\nvorbeikommen.\n\n")
  LANGUAGE_TEXT(3, "Prima dovrete superarci.\n\n")
  LANGUAGE_TEXT(4, "Primero, nos tendr\xe9is\nque ganar.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Winning this tag duel is\nyour boarding pass!\n\n")
  LANGUAGE_TEXT(1, "Si vous sortez victorieux\nde ce duel \xe0 deux, vous\n\npourrez monter \xe0 bord !\n\n")
  LANGUAGE_TEXT(2, "Wenn ihr dieses Doppelduell\ngewinnt, d\xfcrft ihr\n\nmitfahren!\n\n")
  LANGUAGE_TEXT(3, "Per salire, dovrete vincere\nquesto duello doppio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ganar este duelo a dos\nes la tarjeta de embarque!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7751C, map_14_state_01_08E7751C, 0x08E77528, 0x08E77540)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "I wasn't expectin' things to\nbe a cakewalk...\n\nBut who woulda imagined a\ntag duel to test our\n\nskills?\n\n")
  LANGUAGE_TEXT(1, "Je ne m'attendais pas\n\xe0 ce que tout se passe\n\nfacilement...\n\nMais un duel \xe0 deux comme\n\xe7a, sans pr\xe9venir ?\n\n")
  LANGUAGE_TEXT(2, "Ich habe ja nicht erwartet,\ndass es einfach sein\n\nw\xfcrde...\n\nAber gleich ein Doppelduell\num uns zu testen?\n\n")
  LANGUAGE_TEXT(3, "Sapevo che non sarebbe\nstato tutto rose e fiori...\n\nMa un duello per metterci\nalla prova, su due piedi?\n\n")
  LANGUAGE_TEXT(4, "No esperaba que esto\nfuera un paseo...\n\n\xbfPero un duelo a dos para\nprobarnos, as\xed, sin m\xe1s...?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Well, I don't think we have\na choice.\n\nThere's no way every duelist\nin the world can fit into\n\nthe train.\n\n")
  LANGUAGE_TEXT(1, "Ils n'ont pas le choix.\nIls ne peuvent pas\n\nlaisser monter \xe0 bord\nn'importe quel duelliste.\n\n")
  LANGUAGE_TEXT(2, "Sie haben keine andere Wahl.\n\nSie d\xfcrfen nicht jeden Duel-\nlanten in den Zug lassen.\n\n")
  LANGUAGE_TEXT(3, "Non hanno scelta. Non\npossono mica fare\n\nsalire a bordo del treno\ntutti i duellanti.\n\n")
  LANGUAGE_TEXT(4, "No tienen opci\xf3n.\n\nNo pueden dejar subir al\ntren a cualquier duelista.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "I guess dat's true... But in\na tag duel, you'll need a\n\npartner!\n\n")
  LANGUAGE_TEXT(1, "Ouais... Mais\npour un duel \xe0 deux,\n\ntu auras besoin\nd'un partenaire.\n\n")
  LANGUAGE_TEXT(2, "Ja... Aber f\xfcr ein Doppel-\nduell brauchst du\n\neinen Partner.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0... Ma servir\xe0 un socio\nper un duello doppio.\n\n")
  LANGUAGE_TEXT(4, "S\xed... Pero se necesita un\ncolega para un duelo a dos.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, who do you want to\nteam up with? Me or Yugi?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, avec qui\ntu veux faire \xe9quipe ?\n\nMoi ou Yugi ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, mit wem willst du\nspielen? Mit mir oder Yugi?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, con chi vuoi\nstare? Con me o con Yugi?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfcon qui\xe9n\nte asocias? \xbfYugi o yo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "{CARD_1}Yugi Muto\nJoey Wheeler{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Yugi Muto\nJoey Wheeler{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Yugi Muto\nJoey Wheeler{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Yugi Muto\nJoey Wheeler{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Yugi Muto\nJoey Wheeler{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77528, map_14_state_01_08E77528, 0x08E77534, 0x08F0404C)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Okay! You can count on me,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "OK ! Tu peux compter\nsur moi, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Okay! Du kannst dich auf\nmich verlassen, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Okay! Puoi contare su\ndi me, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale! \xa1Cuenta conmigo,\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 2, 4, 0)
  WALK_OBJECT_X(13, 43)
  WALK_OBJECT_Y(13, 44)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  DUEL(159)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77534, map_14_state_01_08E77534, 0x08E77558, 0x08F04040)
  PLAY_MUSIC(230)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Gotta hand it to you, Yugi.\nThat duel lasted barely a\n\nsecond!\n\nOn the other hand...\n\n")
  LANGUAGE_TEXT(1, "A toi de jouer, Yugi.\nC'\xe9tait instantan\xe9.\n\nD'un autre c\xf4t\xe9...\n\n")
  LANGUAGE_TEXT(2, "Das muss ich dir lassen,\nYugi. Das ging schnell.\n\nAndererseits...\n\n")
  LANGUAGE_TEXT(3, "I miei complimenti, Yugi.\n\xc8 stato fulmineo.\n\nD'altra parte...\n\n")
  LANGUAGE_TEXT(4, "Te lo reconozco, Yugi.\nHa sido instant\xe1neo\n\nPor otra parte...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 7, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, you had me\nworried!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, arr\xeate de\nme faire peur comme \xe7a.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, mach mir nicht\nsolche Angst.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, smettila\ndi spaventarmi cos\xec!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, deja de\nasustarme as\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "I... I couldn't afford to\nwaste any time.\n\nI have to find the spirit\nright away!\n\nBut {PLAYER}'s duel was\npretty impressive.\n\nLet's keep this up, guys!\n\n")
  LANGUAGE_TEXT(1, "Je... Je ne peux pas perdre\nde temps comme \xe7a.\n\nJe dois avant tout\ntrouver mon autre moi.\n\nMais le duel de {PLAYER}\n\xe9tait impressionnant.\n\nContinuez comme \xe7a,\nles amis !\n\n")
  LANGUAGE_TEXT(2, "Ich... ich darf keine Zeit\nvertr\xf6deln. Jedenfalls\n\nnicht, bis ich mein\nanderes Ich gefunden habe.\n\nAber das Duell von {PLAYER}\nwar ganz sch\xf6n\n\nbeeindruckend.\nWeiter so, Leute!\n\n")
  LANGUAGE_TEXT(3, "Io... Non posso mica\nsprecare il mio tempo.\n\nPrima devo trovare\nl'altro me stesso.\n\nMa il duello di {PLAYER}\n\xe8 stato notevole.\n\nForza e coraggio, amici!\n\n")
  LANGUAGE_TEXT(4, "No... No puedo perder\ntiempo.\n\nNo hasta que encuentre\nmi otro yo.\n\nPero el duelo de {PLAYER}\nha sido impresionante.\n\n\xa1A seguir as\xed, t\xedos!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(198)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77558, map_14_state_01_08E77558, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Bravo!\n\n")
  LANGUAGE_TEXT(1, "Bravo !\n\n")
  LANGUAGE_TEXT(2, "Bravo!\n\n")
  LANGUAGE_TEXT(3, "Complimenti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bravo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Please feel free to board\nthe train.\n\n")
  LANGUAGE_TEXT(1, "Bienvenue \xe0 bord.\n\n")
  LANGUAGE_TEXT(2, "Ihr d\xfcrft einsteigen.\n\n")
  LANGUAGE_TEXT(3, "Salite pure sul treno.\n\n")
  LANGUAGE_TEXT(4, "Suban al tren, si\nquieren.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 68)
  MOVE_OBJECT(3, 1, 0, 0)
  WALK_OBJECT_Y(2, 26)
  MOVE_OBJECT(2, 0, 0, 0)
  SET_FLAG(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77540, map_14_state_01_08E77540, 0x08E7754C, 0x08F0404C)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Okay! That was a wise\ndecision, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "OK ! Je suis ton\nhomme, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Okay! Ich bin dabei,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Okay! Sono quello che\nfa per te, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale!\n\xa1Soy tu hombre, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(14, 43)
  WALK_OBJECT_Y(14, 44)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  DUEL(159)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7754C, map_14_state_01_08E7754C, 0x08E77558, 0x08F04040)
  PLAY_MUSIC(230)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "What took ya so long,\n{PLAYER}!\n\nIf you're having trouble\nagainst these guys...\n\nWell, I'd hate to think\nwhat'd happen against some\n\nreal competition.\n\nHurry and catch up to my\nlevel!\n\n")
  LANGUAGE_TEXT(1, "Tu es trop lent,\n{PLAYER} !\n\nSi tu as des ennuis\navec ce type de mecs...\n\nJe me fais du souci\npour ton avenir.\n\nD\xe9p\xeache-toi et essaie\nd'atteindre mon niveau !\n\n")
  LANGUAGE_TEXT(2, "Du bist zu langsam,\n{PLAYER}!\n\nWenn du mit diesen Typen\nschon Probleme hast...\n\n... m\xf6chte ich nicht wissen,\nwas als N\xe4chstes passiert.\n\nBeeil dich, damit du so gut\nwirst wie ich!\n\n")
  LANGUAGE_TEXT(3, "Sei troppo lento,\n{PLAYER}!\n\nSe hai problemi con\ntipi come questi...\n\nNon ci voglio neanche\npensare a cosa accadrebbe\n\ndopo. Sbrigati a raggiungere\nil mio livello!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eres demasiado lento,\n{PLAYER}!\n\nSi tienes problemas\ncon tipos as\xed...\n\nVaya, odio pensar\nqu\xe9 podr\xeda pasar.\n\n\xa1Corre y ponte a\nmi nivel!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  SET_FLAG(197)
  SET_FLAG(198)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7757C, map_14_state_01_08E7757C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "There's a chartered express\ntrain reserved exclusively\n\nfor duelists.\n\nIf you're not a duelist, I'm\nsorry, but you are not\n\nallowed to enter.\n\n")
  LANGUAGE_TEXT(1, "Aujourd'hui, un train\nexpress a \xe9t\xe9 affr\xe9t\xe9\n\npour les duellistes\nuniquement.\n\nSi vous n'\xeates pas\nduellistes, je suis d\xe9sol\xe9\n\nmais vous ne pouvez\npas monter \xe0 bord.\n\n")
  LANGUAGE_TEXT(2, "Der Charterzug bef\xf6rdert\nheute nur Duellanten.\n\nWenn ihr keine Duellanten\nseid, d\xfcrft ihr leider\n\nnicht mitfahren.\n\n")
  LANGUAGE_TEXT(3, "Oggi c'\xe8 un espresso specia-\nle solo per i duellanti. Se\n\nnon siete duellanti, non\npotete salire, purtroppo.\n\n")
  LANGUAGE_TEXT(4, "Hoy hay un express ch\xe1rter\ns\xf3lo para duelistas.\n\nSi no sois duelistas,\nlo siento, pero no\n\npod\xe9is subir.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(3, 26)
  MOVE_OBJECT(3, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E774E0, map_14_state_01_08E774E0, 0x08E77360, 0x08F04040)
  CHECK_FLAG(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77360, map_14_state_01_08E77360, 0x08F04040, 0x08F04040)
  WALK_OBJECT_X(13, 56)
  WALK_OBJECT_Y(13, 0)
  WALK_OBJECT_X(14, 56)
  WALK_OBJECT_Y(14, 0)
  DELAY(64)
  WALK_OBJECT_Y(6, 48)
  DELAY(16)
  PLAY_MUSIC(0)
  PLAY_MUSIC(414)
  PORTRAIT(PORTRAIT_PANICK, 0, 8)
  LANGUAGE_TEXT(0, "Hee hee hee... I've found\nthem...\n\n")
  LANGUAGE_TEXT(1, "Hi hi hi...\nJe les ai trouv\xe9s...\n\n")
  LANGUAGE_TEXT(2, "Hihihi...\nIch habe sie gefunden...\n\n")
  LANGUAGE_TEXT(3, "Ihihih...\nLi ho trovati...\n\n")
  LANGUAGE_TEXT(4, "Jijiji...\nLos encontr\xe9...\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(6, 0)
  SET_FLAG(11)
  WARP(15, 1, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E773E4, map_14_state_01_08E773E4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "KaibaCorp is amazing.\n\nThey chartered an entire\nexpress train just for a\n\nduel tournament...\n\n")
  LANGUAGE_TEXT(1, "La Kaiba Corporation\nest vraiment \xe9tonnante.\n\nAffr\xe9ter un train express\nsp\xe9cialement pour\n\nun tournoi de duels...\n\n")
  LANGUAGE_TEXT(2, "Die Kaiba Corporation\nist wirklich erstaunlich.\n\nEin Charterzug f\xfcr ein\nDuellturnier...\n\n")
  LANGUAGE_TEXT(3, "La Kaiba Corporation \xe8\ndavvero sorprendente.\n\nNoleggiare un treno espresso\nper un torneo di duelli...\n\n")
  LANGUAGE_TEXT(4, "Kaiba Corporation es\nmuy sorprendente.\n\nFletan un tren express\npara un torneo de duelos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77564, map_14_state_01_08E77564, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "All aboard! Duel Express\nwill soon depart!\n\nThe next and only stop is\nthe Egypt Exhibition!\n\n")
  LANGUAGE_TEXT(1, "En voiture ! Le Duel\nExpress va bient\xf4t partir !\n\nProchain et dernier arr\xeat :\nl'Exposition \xe9gyptienne !\n\n")
  LANGUAGE_TEXT(2, "Alle einsteigen! Der Duel\nExpress f\xe4hrt gleich ab!\n\nDie n\xe4chste und einzige\nHaltestelle ist die\n\n\xe4gyptische Ausstellung.\n\n")
  LANGUAGE_TEXT(3, "Tutti a bordo! Il Duel\nExpress sta per partire!\n\nProssima e unica fermata:\nla Mostra Egizia!\n\n")
  LANGUAGE_TEXT(4, "\xa1Todos a bordo! \xa1El Duel\nExpress saldr\xe1 pronto!\n\n\xa1La pr\xf3xima y \xfanica parada\nes la Exposici\xf3n Egipcia!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77570, map_14_state_01_08E77570, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Duel Express is only\nrunning for duelists today.\n\nNon-duelists are not allowed\nto ride.\n\n")
  LANGUAGE_TEXT(1, "Aujourd'hui,\nle Duel Express\n\nn'accepte\nque les duellistes.\n\nLes non duellistes n'ont\npas le droit de monter.\n\n")
  LANGUAGE_TEXT(2, "Der Duel Express bef\xf6rdert\nheute nur Duellanten.\n\nAndere Passagiere d\xfcrfen\nheute nicht mitfahren.\n\n")
  LANGUAGE_TEXT(3, "Oggi sul Duel Express\npossono salire solo i\n\nduellanti. Tutti gli altri\nnon possono prenderlo.\n\n")
  LANGUAGE_TEXT(4, "El Duel Express hoy\ns\xf3lo lleva duelistas.\n\nLos que no lo son, hoy\nno pueden subir.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7736C, map_14_state_01_08E7736C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "If you win this tournament,\nyou get a lot of ante\n\ncards!\n\nWith these high stakes, it's\nmore exciting than any\n\nstreet fight, hiyah!\n\n")
  LANGUAGE_TEXT(1, "Si tu remportes ce tournoi,\ntu remporteras le butin\n\nde guerre !\n\nC'est encore mieux\nqu'un duel de rue, hiyah !\n\n")
  LANGUAGE_TEXT(2, "Wer das Turnier gewinnt,\nbekommt die Kriegsbeute!\n\nDas macht mich hei\xdfer als\nein Stra\xdfenkampf!\n\n")
  LANGUAGE_TEXT(3, "Se vinci questo torneo, ti\ndanno un bottino di guerra!\n\nPer me \xe8 meglio di una\nbattaglia di strada!\n\n")
  LANGUAGE_TEXT(4, "\xa1Si ganas este torneo\nte llevas un bot\xedn!\n\nMe pone m\xe1s que una lucha\ncallejera, \xa1hiyah!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77378, map_14_state_01_08E77378, 0x08E77384, 0x08E7739C)
  CHECK_FLAG(183)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77384, map_14_state_01_08E77384, 0x08E77390, 0x08F0404C)
  LANGUAGE_TEXT(0, "Heheh! I'll take you on!\nFeel the heat! Hiyah!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 h\xe9 h\xe9 ! Je veux\nbien t'affronter !\n\nTu vas souffrir !\nHiyah !\n\n")
  LANGUAGE_TEXT(2, "Hihihi! Ich nehme es mit dir\nauf! Sp\xfcrst du die Hitze?!\n\n")
  LANGUAGE_TEXT(3, "Eheheh! Ci sto!\nChe sballo! S\xec\xec\xec!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jejeje! \xa1Te reto!\n\xa1Siente el calor! \xa1Hiyah!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E77390, map_14_state_01_08E77390, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(230)
  LANGUAGE_TEXT(0, "Quit rubbing it in!\n\nI'm never playing you again!\nHiyah!\n\n")
  LANGUAGE_TEXT(1, "Ouais, remue le couteau\ndans la plaie !\n\nJe ne battrais plus\njamais contre toi !\n\n")
  LANGUAGE_TEXT(2, "Ja, mach du mich jetzt auch\nnoch fertig!\n\nGegen dich spiele ich nie\nwieder!\n\n")
  LANGUAGE_TEXT(3, "Vedi di non ricordarmelo!\n\nCon te non ci gioco\nmai pi\xf9! Mai!\n\n")
  LANGUAGE_TEXT(4, "S\xed, t\xfa vete por ah\xed y\ndi lo que quieras.\n\n\xa1No vuelvo a luchar\ncontra ti! \xa1Hiyah!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(183)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7739C, map_14_state_01_08E7739C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I said I'm never playing you\nagain! Hiyah!\n\n")
  LANGUAGE_TEXT(1, "Je t'ai d\xe9j\xe0 dit que\nje ne me battrais plus\n\nen duel contre toi !\n\n")
  LANGUAGE_TEXT(2, "Ich sagte doch, dass ich nie\nwieder gegen dich spiele!\n\n")
  LANGUAGE_TEXT(3, "Avevo detto che non avrei\npi\xf9 giocato con te!\n\n")
  LANGUAGE_TEXT(4, "\xa1Dije que no vuelvo a\nluchar contra ti! \xa1Hiyah!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E773A8, map_14_state_01_08E773A8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Dueling is stupid.\n\nHaven't you heard?\n\nThere are a bunch of bad\nguys who rip off rare cards\n\nin duels.\n\nYou would think dueling is\nstupid too if you ran into\n\nthem!\n\n")
  LANGUAGE_TEXT(1, "Se battre en duel,\nc'est stupide.\n\nTu ne le savais pas ?\nIl y a des m\xe9chants qui\n\nvolent des cartes rares\nen duel.\n\nToi aussi, tu les\nd\xe9testerais si tu devais\n\nles affronter en duel !\n\n")
  LANGUAGE_TEXT(2, "Duellieren ist dumm.\n\nWusstest du denn nicht, dass\nes \xfcble Typen gibt,\n\ndie in Duellen seltene\nKarten stehlen. Wenn du\n\nihnen begegnen w\xfcrdest, w\xe4re\ndir das Duellieren auch\n\nvergangen!\n\n")
  LANGUAGE_TEXT(3, "\xc8 stupido duellare.\n\nNon lo sai?\n\nCi sono dei tipacci che\nrubano le carte rare nei\n\nduelli. Se li incontrassi,\npure tu odieresti duellare!\n\n")
  LANGUAGE_TEXT(4, "Batirse en duelo\nes est\xfapido.\n\n\xbfNo lo sabes?\n\nHay tipos malos que rajan\ncartas raras en duelos.\n\nT\xfa tambi\xe9n lo odiar\xedas si te\ntoparas con ellos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E773B4, map_14_state_01_08E773B4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No way! Forget it!\n\nI don't even want to look at\nany cards!\n\n")
  LANGUAGE_TEXT(1, "Pas question, oublie \xe7a !\n\nJe ne veux m\xeame\nplus voir de cartes !\n\n")
  LANGUAGE_TEXT(2, "Unm\xf6glich, vergiss es!\n\nIch will Karten nicht\neinmal sehen!\n\n")
  LANGUAGE_TEXT(3, "Neanche per sogno,\nscordatelo!\n\nLe carte non le voglio\nneanche vedere!\n\n")
  LANGUAGE_TEXT(4, "Ni hablar, \xa1olv\xeddalo!\n\nNi siquiera quiero\nver cartas.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
