#include "event_macros.h"
#include "overworld.h"

/* map_57_state_04: map 57 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EFB450, map_57_state_04_08EFB450, 0x08F04040, 0x08F04040)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(128, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Go for it, Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "Vas-y, Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Nur zu, Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "Forza, Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(256, 1)
  DELAY(8)
  LANGUAGE_TEXT(0, "Don't give up, Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "N'abandonne pas,\nKaibaman !\n\n")
  LANGUAGE_TEXT(2, "Nicht aufgeben, Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "Non mollare, Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1No abandones,\nKaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(344)
  PORTRAIT(47, 0, 0)
  LANGUAGE_TEXT(0, "Justice just rules! I am\nvictorious in victory!\n\n")
  LANGUAGE_TEXT(1, "La justice va l'emporter !\nEt je sortirai victorieux !\n\n")
  LANGUAGE_TEXT(2, "Die Gerechtigkeit wird\nsiegen! Der Sieg ist mein!\n\n")
  LANGUAGE_TEXT(3, "La giustizia prevarr\xe0!\nLa vittoria sar\xe0 mia!\n\n")
  LANGUAGE_TEXT(4, "\xa1La justicia vencer\xe1!\n\xa1La victoria ser\xe1 m\xeda!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 16)
  DELAY(16)
  PORTRAIT(47, 0, 0)
  LANGUAGE_TEXT(0, "Dragon Sabre Blast!\n\n")
  LANGUAGE_TEXT(1, "Galaxy Crush !\n\n")
  LANGUAGE_TEXT(2, "Galaxy Crush!\n\n")
  LANGUAGE_TEXT(3, "Galaxy Crush!\n\n")
  LANGUAGE_TEXT(4, "\xa1Galaxy Crush!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(342)
  COMMAND_7C_ARG(8, 17)
  DELAY(16)
  COMMAND_7C_ARG(2, 16)
  FADE_SCREEN(16)
  WARP(26, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
