#include "event_macros.h"
#include "overworld.h"

/* map_26_state_09: map 26 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3D88, map_26_state_09_08EA3D88, 0x08EA3D94, 0x08EA3DA0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MAI3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D94, map_26_state_09_08EA3D94, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}... You came here\nfor a reason, didn't you?\n\nWhatever it is, I'm here to\nhelp.\n\nChallenge me whenever you\nfeel ready.\n\nAs duelists, we understand\neach other the best when we\n\nduel.\n\nIt sounds weird, but it's\ntrue.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DA0, map_26_state_09_08EA3DA0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The people in the Town of\nDomino are happy now that\n\nthe Neo Ghouls are gone.\n\nBut don't you sense\nsomething strange?\n\nI don't know what it is, but\nit doesn't feel good.\n\nIt feels like the last turn\nof a duel that I'm about to\n\nlose.\n\nIt's just awful!\n\n{PLAYER}, this enemy that\nyou're facing...\n\nWho is it?\n\nWho can create so much\ntension in the air?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DAC, map_26_state_09_08EA3DAC, 0x08EA3DB8, 0x08EA3DD0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MAI3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DB8, map_26_state_09_08EA3DB8, 0x08EA3DC4, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Duelists get to know each\nother through dueling.\n\nOnce duelists battle, a bond\ndevelops that didn't exist\n\nbefore.\n\n{PLAYER}, I accept your\nduel!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(97)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DC4, map_26_state_09_08EA3DC4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}...\n\nI can tell you're planning\nto face something huge and\n\nterrible...\n\nBut you'll be fine.\n\nThere's a bond between us!\n\nEven when we're far apart,\nour hearts beat as one.\n\nThis is Harpie Lady. It\nrepresents my spirit as a\n\nduelist.\n\nI'm not required to give it\nto you, but I want you to\n\nhave it.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Received Harpie Lady.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(15)
  PAGE_BREAK()
  ADD_CARD(62)
  SET_FLAG(EVENT_FLAG_DEFEATED_MAI3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DD0, map_26_state_09_08EA3DD0, 0x08EA3DDC, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, I don't know what\nyou're facing.\n\nBut I know it won't be easy.\n\nRemember that every duelist\nhas unlimited potential.\n\nIf you think it'll help,\nI'll duel you anytime!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(147)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DDC, map_26_state_09_08EA3DDC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Did this duel help you?\n\nDon't lose, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
