#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_03_state_01: map 3 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E4A8A4, map_03_state_01_08E4A8A4, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_KAIBA_FAN)
  LOAD_SPRITE(2, SPRITE_RED_HAIR)
  TEXT(
      "I'm a huge fan of Mr. Seto Kaiba.",
      "I wonder if Kaiba Corporation would hire me?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8B0, map_03_state_01_08E4A8B0, 0x08E4A8BC, 0x08E4A8D4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_KAIBA_FAN)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8BC, map_03_state_01_08E4A8BC, 0x08E4A8C8, 0x08F0404C)
  TEXT("I'll duel in a way that would make Mr. Kaiba proud!")
  DUEL(DUELIST_ID_005)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8C8, map_03_state_01_08E4A8C8, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_CLOCK_TOWER_SQUARE)
  TEXT("KaibaCorp won't hire me if I can't win...")
  SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA_FAN)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8D4, map_03_state_01_08E4A8D4, EVENT_NOP, EVENT_NOP)
  TEXT("I wish I could meet Mr. Kaiba...")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8E0, map_03_state_01_08E4A8E0, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Dueling is only fun if you don't cheat.",
      "You should always choose ante cards before dueling.",
      "That way, there won't be any arguments later."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8EC, map_03_state_01_08E4A8EC, 0x08E4A8F8, 0x08E4A910)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RED_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A8F8, map_03_state_01_08E4A8F8, 0x08E4A904, 0x08F0404C)
  TEXT("We'll duel fair and square!")
  DUEL(DUELIST_ID_006)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A904, map_03_state_01_08E4A904, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_CLOCK_TOWER_SQUARE)
  TEXT("I'm so disappointed...")
  SET_FLAG(EVENT_FLAG_DEFEATED_RED_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A910, map_03_state_01_08E4A910, EVENT_NOP, EVENT_NOP)
  TEXT("Hold on, I'm fixing my deck right now.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
