#include "event_macros.h"

/* map_00_state_18: map 0 state 18 */

EVENT_SCRIPT_REPLACEMENT(0x08E34A54, map_00_state_18_08E34A54, 0x08E34A60, 0x08F04040)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(16, 0, 8)
  LANGUAGE_TEXT(0, "But we cannot worry about\nthat now. Time is of the\n\nessence.\n\nThe second Millennium Item\nmust be found...\n\nSo that we can restore the\nEgyptian God Cards.\n\nThat is the only way we can\ndefeat Sol Chevalsky...\n\nAnd imprison Reshef the Dark\nBeing again.\n\n{PLAYER}, please find the\nnext Millennium Item.\n\n")
  LANGUAGE_TEXT(1, "Mais nous ne devons\npas perdre de temps.\n\nIl faut trouver le {BYTE_8251}\xe8me\nObjet du mill\xe9nium...\n\nde fa\xe7on \xe0 restaurer\nles cartes de dieux.\n\nAinsi, nous pourrons\nbattre Sol Chevalsky...\n\nEt enfermer \xe0 nouveau\nReshef, l'Etre des\n\nt\xe9n\xe8bres.\n\n{PLAYER}, s'il te pla\xeet,\nva chercher le prochain\n\nObjet du mill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "Jetzt kommt es aufs\nTiming an.\n\nWir m\xfcssen den zweiten\nMillenniumsgegenstand\n\nfinden...\n\nund die G\xf6tterkarten\nwiederherstellen.\n\nNur so k\xf6nnen wir Sol\nChevalsky besiegen...\n\nund Reschef den Dunklen\nwieder einsperren.\n\n{PLAYER}, such bitte\nden n\xe4chsten Millen-\n\nniumsgegenstand.\n\n")
  LANGUAGE_TEXT(3, "Ma ora, \xe8 il tempo la\ncosa pi\xf9 importante.\n\nBisogna trovare il secondo\nOggetto Millenario...\n\nCos\xec potremo ripristinare\nle carte divine.\n\nSolo cos\xec sconfiggeremo\nSol Chevalsky...\n\nE imprigioneremo di nuovo\nReshef il Tenebroso.\n\nTi prego, {PLAYER}, trova il\nprossimo Oggetto\n\nMillenario.\n\n")
  LANGUAGE_TEXT(4, "Pero ahora, no hay\ntiempo que perder.\n\nHay que encontrar el segundo\nObjeto del Milenio...\n\nPara restaurar las\ncartas de los dioses.\n\nAs\xed podremos derrotar\na Sol Chevalsky...\n\nY volver a encerrar a\nReshef, el Ser Oscuro.\n\n{PLAYER}, encuentra el\npr\xf3ximo Objeto del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A60, map_00_state_18_08E34A60, 0x08E34A78, 0x08E34A6C)
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A78, map_00_state_18_08E34A78, 0x08F04040, 0x08F04040)
  PORTRAIT(16, 1, 8)
  LANGUAGE_TEXT(0, "Thank you.\n\nThe next Millennium Item.")
  LANGUAGE_TEXT(1, "Merci.\nLe prochain Objet du\n\nmill\xe9nium.")
  LANGUAGE_TEXT(2, "Danke.\nDer n\xe4chste\n\nMillenniumsgegenstand.")
  LANGUAGE_TEXT(3, "Grazie.\n\nIl prossimo Oggetto\nMillenario.")
  LANGUAGE_TEXT(4, "Gracias.\n\nEl pr\xf3ximo\nObjeto del Milenio.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ". ")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\nGo to Domino Pier.\n\nThe Millennium Item should\nbe aboard the cruise ship.\n\n")
  LANGUAGE_TEXT(1, "\nVa \xe0 la jet\xe9e de Domino.\n\nL'Objet du mill\xe9nium devrait\n\xeatre \xe0 bord du paquebot.\n\n")
  LANGUAGE_TEXT(2, "\nGeh zum Kai von Domino.\n\nDer Millenniumsgegenstand\nm\xfcsste auf dem\n\nKreuzfahrtschiff sein.\n\n")
  LANGUAGE_TEXT(3, "Vai al molo\n\ndi Domino. L'Oggetto\nMillenario dovrebbe\n\ntrovarsi a bordo della\nnave da crociera.\n\n")
  LANGUAGE_TEXT(4, "\n\nVe al muelle de Domino.\n\nEl Objeto del Milenio\ndeber\xeda estar en el\n\ncrucero.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(255)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A6C, map_00_state_18_08E34A6C, 0x08E34A60, 0x08F04040)
  PORTRAIT(16, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, I have no one to\nturn to but to you.\n\nI know I am asking for the\nimpossible, but I beg for\n\nyour help.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, je n'ai\npersonne d'autre\n\nvers qui me tourner.\nJe sais que je demande\n\nl'impossible, mais je te\nsupplie de m'aider.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du bist der einzi-\nge, der mir helfen kann.\n\nIch wei\xdf, es ist schwer,\naber ich flehe dich an -\n\nhilf mir!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, posso\nchiederlo solo a te. So\n\ndi chiedere l'impossibile,\nma ti supplico di aiutarmi.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, s\xf3lo te\ntengo a ti.\n\nS\xe9 que pido algo imposible,\npero ruego tu ayuda.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
