#include "event_macros.h"
#include "overworld.h"

/* map_57_state_03: map 57 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EFB444, map_57_state_03_08EFB444, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "All right, crew! Everyone\nready?\n\n")
  LANGUAGE_TEXT(1, "Bon, tout le monde est\npr\xeat dans cette \xe9quipe ?\n\n")
  LANGUAGE_TEXT(2, "Okay, Leute!\nAlle bereit?\n\n")
  LANGUAGE_TEXT(3, "Allora, ragazzi!\nSiete tutti pronti?\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, todos!\n\xbfTodo el mundo listo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  LANGUAGE_TEXT(0, "Yes, I understand. But...\n\n")
  LANGUAGE_TEXT(1, "Oui, oui.\nMais...\n\n")
  LANGUAGE_TEXT(2, "Ja, ja.\nAber...\n\n")
  LANGUAGE_TEXT(3, "S\xec, io sono pronto.\nMa...\n\n")
  LANGUAGE_TEXT(4, "S\xed, s\xed, lo estoy.\nPero...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  LANGUAGE_TEXT(0, "We're missing two of our\nmembers...\n\n")
  LANGUAGE_TEXT(1, "Il nous manque\nencore deux membres...\n\n")
  LANGUAGE_TEXT(2, "Zwei unserer Leute\nfehlen...\n\n")
  LANGUAGE_TEXT(3, "Mancano due dei nostri...\n\n")
  LANGUAGE_TEXT(4, "No encontramos a dos\nde nuestros miembros...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  LANGUAGE_TEXT(0, "What's the point of doing a\nchildren's show?\n\n")
  LANGUAGE_TEXT(1, "Faire un spectacle\npour enfants,\n\nest-ce que cela a\nencore un sens ?\n\n")
  LANGUAGE_TEXT(2, "Was hat es mit dem\nKinderprogramm auf sich?\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 dovremmo fare uno\nspettacolo per bambini?\n\n")
  LANGUAGE_TEXT(4, "\xbfTiene alguna raz\xf3n hacer\nun show para ni\xf1os?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "You fools!\n\n")
  LANGUAGE_TEXT(1, "Imb\xe9ciles !\n\n")
  LANGUAGE_TEXT(2, "Ihr Schwachk\xf6pfe!\n\n")
  LANGUAGE_TEXT(3, "Razza di imbecilli!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tontos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 124)
  DELAY(8)
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "The children are afraid!\n\nThe Neo Ghouls stole their\nrare cards.\n\nKaibaman represents hope to\nthe kids.\n\nWhen Masters Mokuba and Seto\nreturn, how would they feel\n\nif children aren't enjoying\ndueling?\n\nWe can't let Masters Mokuba\nand Seto see that.\n\nThat's why we have to give\nhope to the kids.\n\n")
  LANGUAGE_TEXT(1, "Les enfants ont peur !\n\nLes Neo Ghouls leur ont vol\xe9\nleurs cartes rares.\n\nKaibaman est le h\xe9ros\nqui repr\xe9sentait pour\n\neux l'espoir.\n\nMa\xeetre Mokuba et Seto\nvont revenir, c'est s\xfbr.\n\nMais si les enfants\nn'aiment plus les duels ?\n\nNous devons donc continuer\n\xe0 donner de l'espoir\n\naux enfants.\n\n")
  LANGUAGE_TEXT(2, "Die Kinder haben Angst!\n\nDie Neo Ghouls hatten ihre\nseltenen Karten gestohlen.\n\nKaibaman ist der Held, er\ngibt den Kindern Hoffnung.\n\nMeister Mokuba und Seto\nwerden sicher zur\xfcckkehren.\n\nAber was, wenn die Kinder\ndann keine Duelle m\xf6gen?\n\nWir k\xf6nnen nicht zulassen,\ndass Meister Mokuba und\n\nSeto das erleben.\n\nBis dahin m\xfcssen wir den\nKindern Hoffnung geben.\n\n")
  LANGUAGE_TEXT(3, "I bambini hanno paura!\nI Neo Ghouls gli hanno\n\nrubato le carte rare.\nKaibaman \xe8 l'eroe che\n\nper i bambini incarna\nla speranza. I maestri\n\nMokuba e Seto torneranno\ndi sicuro. Ma cosa\n\nsuccede se i bambini non si\ndivertono pi\xf9 a duellare?\n\nNon possiamo permettere che\nal loro ritorno i maestri\n\nMokuba e Seto trovino\nquesta situazione. Fino\n\nad allora, dobbiamo dare\nsperanza ai bambini.\n\n")
  LANGUAGE_TEXT(4, "\xa1Los ni\xf1os est\xe1n asustados!\n\nLos Neo Ghouls les han\nrobado sus cartas raras.\n\nKaibaman es el h\xe9roe que\nrepresenta la esperanza\n\npara los ni\xf1os.\n\nSeguro que amo Mokuba\ny Seto volver\xe1n.\n\nPero, \xbfy qu\xe9 pasa si los\nni\xf1os no disfrutan de\n\nlos duelos?\n\nNo podemos dejar que\nel amo Mokuba y Seto\n\nregresen para verlo.\n\nHasta entonces, tenemos que\ndar esperanza a los ni\xf1os.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(3, 3, 0, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  MOVE_OBJECT(6, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "As a bonus, I'll speak to\nMaster Kaiba about giving\n\nyou better jobs.\n\n")
  LANGUAGE_TEXT(1, "Je vais parler\n\xe0 ma\xeetre Seto\n\n\xe0 propos d'un\nemploi pour toi.\n\n")
  LANGUAGE_TEXT(2, "Ich spreche mit Meister Seto\n\xfcber deine Stelle.\n\n")
  LANGUAGE_TEXT(3, "Parler\xf2 al maestro Seto\ndella tua assunzione.\n\n")
  LANGUAGE_TEXT(4, "Hablar\xe9 con amo\nSeto de tu empleo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(1, 108)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 124)
  DELAY(16)
  MOVE_OBJECT(5, 0, 0, 0)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(32, 1)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(5, 105)
  PORTRAIT(PORTRAIT_MILLENIMUM_GUARDIAN_UNUSED, 0, 0)
  LANGUAGE_TEXT(0, "I... I'll do it!\n\n")
  LANGUAGE_TEXT(1, "Je...\nJe vais le faire !\n\n")
  LANGUAGE_TEXT(2, "Ich...\nIch werde das tun!\n\n")
  LANGUAGE_TEXT(3, "Io...\nIo ci sto!\n\n")
  LANGUAGE_TEXT(4, "Yo...\n\xa1Lo har\xe9!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(6, 0, 0, 0)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(64, 1)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(6, 107)
  PORTRAIT(PORTRAIT_JINZO, 0, 0)
  LANGUAGE_TEXT(0, "Yes!\n\n")
  LANGUAGE_TEXT(1, "Oui !\n\n")
  LANGUAGE_TEXT(2, "Ja!\n\n")
  LANGUAGE_TEXT(3, "S\xec!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  MOVE_OBJECT(3, 0, 0, 0)
  MOVE_OBJECT(4, 0, 0, 0)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(2, 104)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(3, 103)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  PLAY_MUSIC(361)
  SWAP_OBJECT_SPRITE(4, 106)
  FADE_SCREEN(8)
  WARP(57, 4, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
