#include "event_macros.h"
#include "overworld.h"

/* map_37_state_01: map 37 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ECD7D8, map_37_state_01_08ECD7D8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(708)
  PLAY_MUSIC(383)
  DELAY(16)
  MOVE_OBJECT(1, 0, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I can hear the sea raging...\n\nIt's shouting as if nature\nis out of balance.\n\n")
  LANGUAGE_TEXT(1, "J'entends la mer en furie...\nElle nous avertit\n\nque quelque chose\nse passe.\n\n")
  LANGUAGE_TEXT(2, "Ich h\xf6re das Meer\nrauschen...\n\nEs k\xfcndet etwas an.\n\n")
  LANGUAGE_TEXT(3, "Sento il mare\nagitarsi...\n\nGrida che sta\nsuccedendo qualcosa.\n\n")
  LANGUAGE_TEXT(4, "Puedo o\xedr al mar\nembravecido...\n\nGrita que algo pasa.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_SAW_MAKO_TALK_TO_HIMSELF)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7E4, map_37_state_01_08ECD7E4, 0x08ECD7FC, 0x08ECD820)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7FC, map_37_state_01_08ECD7FC, 0x08ECD808, 0x08ECD814)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Can you not hear it? Can you\nnot hear the pain of the\n\nocean?\n\nI was raised on the high\nseas, so I can understand\n\nwhen all is not right.\n\nThe waters are crying, but\nabout what...\n\n")
  LANGUAGE_TEXT(1, "Tu l'entends aussi ?\nLa mer pleure ?\n\nJe suis un hommede la mer.\nJe comprends ses humeurs.\n\nEt elle crie car quelque\nchose se passe.\n\n")
  LANGUAGE_TEXT(2, "H\xf6rst du es auch?\nDie Rufe des Meeres?\n\nIch bin ein alter Seeb\xe4r.\nIch verstehe die\n\nStimmungen der See.\n\nUnd sie k\xfcndet bestimmt\netwas an.\n\n")
  LANGUAGE_TEXT(3, "Riesci a sentirle anche\ntu, le grida del mare?\n\nSono un uomo di mare.\nRiconosco il suo umore.\n\nE sta gridando che sta\nsuccedendo qualcosa.\n\n")
  LANGUAGE_TEXT(4, "\xbfLo oyes t\xfa tambi\xe9n?\n\xbfLos gritos del mar?\n\nSoy un hombre del mar.\nEntiendo su car\xe1cter.\n\nY grita que algo pasa.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Actually...\nYou're imagining things{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}En fait...\nTu t'imagines des choses{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja...\nDu bildest dir das ein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Veramente...\n\xc8 solo la tua immaginazione{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Realmente...\nEst\xe1s imaginando cosas.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD808, map_37_state_01_08ECD808, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What's going on?\n\n")
  LANGUAGE_TEXT(1, "C'est quoi,\ncette histoire ?\n\n")
  LANGUAGE_TEXT(2, "Worum geht es eigentlich?\n\n")
  LANGUAGE_TEXT(3, "Allora, che succede?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 es todo esto?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(8)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being?\nThat's hard to believe.\n\nBut the tides have been far\nfrom normal.\n\nIf anything has to do with\nthis mystery...\n\nGo deeper into the island.\nYou may find something.\n\n")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des\nt\xe9n\xe8bres ?\n\nC'est pas \xe9vident \xe0 croire.\n\nMais il se passe parfois\ndes choses bizarres.\n\nEnfonce-toi\nplus loin dans l'\xeele.\n\nTu vas trouver\nquelque chose.\n\n")
  LANGUAGE_TEXT(2, "Reschef der Dunkle?\nKaum zu glauben.\n\nAber in der letzten Zeit\ngeht Merkw\xfcrdiges vor.\n\nWenn es mal nichts\nhiermit zu tun hat...\n\nGeh weiter ins Innere der\nInsel. Dort findest du\n\netwas.\n\n")
  LANGUAGE_TEXT(3, "Reshef il Tenebroso?\n\xc8 difficile crederci.\n\nMa sono successe\nstrane cose.\n\nSe hanno qualcosa a\nche fare con questo...\n\nAddentrati nell'isola\ne troverai qualcosa.\n\n")
  LANGUAGE_TEXT(4, "\xbfReshef, el Ser Oscuro?\nEs dif\xedcil de creer.\n\nPero han pasado\ncosas raras.\n\nSi tiene algo que\nver con esto...\n\nVe m\xe1s dentro de la isla.\nEncontrar\xe1s algo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD814, map_37_state_01_08ECD814, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh, I'm imagining things, am\nI?\n\nYou cannot deceive me.\n\nI can tell you're hiding\nsomething...important.\n\n")
  LANGUAGE_TEXT(1, "Alors, comme \xe7a, je\nm'imagine des choses ?\n\nCes yeux, ce ne sont pas\ndes trous dans une\n\nplanche, tu sais.\n\nJe suis s\xfbr que tu\ncaches quelque chose.\n\n")
  LANGUAGE_TEXT(2, "Ich bilde es mir also\nnur ein, ja?\n\nDiese Augen sind keine Ast-\nl\xf6cher in einer Planke,\n\nwei\xdft du? Ich merke doch,\ndass du etwas verbirgst.\n\n")
  LANGUAGE_TEXT(3, "Cos\xec io mi inventerei\ncose inesistenti?\n\nQuesti occhi ci vedono\nbenissimo, capito?\n\nIo dico che mi stai\nnascondendo qualcosa.\n\n")
  LANGUAGE_TEXT(4, "Imagino cosas, \xbfyo?\n\nEstos ojos no son agujeros\nvac\xedos, \xbfsabes?\n\nS\xe9 que ocultas\nalgo malo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You do not have to reveal\nyour secrets if you are not\n\nso inclined.\n\nBut I will let you know that\nthe tides have been far\n\nfrom normal.\n\nIf anything has to do with\nthis mystery...\n\nGo deeper into the island.\nYou may find something.\n\n")
  LANGUAGE_TEXT(1, "Tu n'as pas \xe0 me le\ndire si tu ne veux pas.\n\nMais des choses\nbizarres se passent.\n\nSi cela a \xe0 voir avec\ncela...\n\nEnfonce-toi dans l'\xeele.\n\nTu vas trouver\nquelque chose.\n\n")
  LANGUAGE_TEXT(2, "Du musst es mir nicht\nsagen.\n\nAber in der letzten Zeit\ngeht Merkw\xfcrdiges vor.\n\nWenn es mal nichts\nhiermit zu tun hat...\n\nGeh weiter ins Innere der\nInsel. Dort findest du\n\netwas.\n\n")
  LANGUAGE_TEXT(3, "Non devi dirmelo\nper forza.\n\nMa sono successe\nstrane cose.\n\nSe hanno qualcosa a\nche fare con questo...\n\nAddentrati nell'isola\ne troverai qualcosa.\n\n")
  LANGUAGE_TEXT(4, "No me lo tienes que\ndecir si no quieres.\n\nPero han pasado\ncosas raras.\n\nSi tiene algo que\nver con esto...\n\nVe m\xe1s dentro de la isla.\nEncontrar\xe1s algo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD820, map_37_state_01_08ECD820, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "There's something wrong with\nthe sea.\n\nI hope it's not a sign of\nsome impending catastrophe.\n\n")
  LANGUAGE_TEXT(1, "Il y a quelque chose\nqui ne tourne pas rond\n\navec la mer.\nJ'esp\xe8re que \xe7a n'est\n\npas le pr\xe9sage\nd'une catastrophe.\n\n")
  LANGUAGE_TEXT(2, "Mit dem Meer geht etwas\nvor.\n\nIch hoffe, das ist kein\nschlechtes Omen.\n\n")
  LANGUAGE_TEXT(3, "Il mare ha qualcosa\nche non va. Spero\n\nche non sia presagio\ndi qualcosa di terribile.\n\n")
  LANGUAGE_TEXT(4, "Algo malo pasa con\nel mar.\n\nEspero que no sea un signo\nde algo horrible.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7F0, map_37_state_01_08ECD7F0, 0x08ECD7FC, 0x08ECD82C)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD82C, map_37_state_01_08ECD82C, 0x08ECD838, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, 8)
  LANGUAGE_TEXT(0, "Fine! Mako Tsunami does not\nflee from any challenge!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 ! Mako Tsunami\nrel\xe8ve tous les d\xe9fis !\n\n")
  LANGUAGE_TEXT(2, "Aye! Mako Tsunami\ndr\xfcckt sich vor keiner\n\nHerausforderung!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Mako Tsunami non si\ntira indietro alle sfide!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ay! \xa1Mako Tsunami no\nrechaza ning\xfan reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(48)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD838, map_37_state_01_08ECD838, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(246)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, 8)
  LANGUAGE_TEXT(0, "Excellent duel!\n\nBut next time, you won't win\nso easily!\n\n")
  LANGUAGE_TEXT(1, "Toi aussi, tu es fort !\n\nCa ne va pas se\nterminer comme \xe7a\n\npour toi la prochaine\nfois !\n\n")
  LANGUAGE_TEXT(2, "Aye, du bist auch nicht\nschlecht!\n\nAber beim n\xe4chsten Mal\nsieht das Ende anders aus!\n\n")
  LANGUAGE_TEXT(3, "Ehi, sei bravo pure tu!\n\nMa la prossima volta\nnon finir\xe0 cos\xec!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ay, tambi\xe9n eres bueno!\n\n\xa1No acabar\xe1 as\xed\nla pr\xf3xima vez!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
