#include "event_macros.h"
#include "overworld.h"

/* map_37_state_01: map 37 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ECD7D8, map_37_state_01_08ECD7D8, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_MAKO)
  PLAY_MUSIC(708)
  PLAY_MUSIC(383)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I can hear the sea raging...\n\nIt's shouting as if nature\nis out of balance.\n\n")
  SET_FLAG(EVENT_FLAG_SAW_MAKO_TALK_TO_HIMSELF)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7E4, map_37_state_01_08ECD7E4, 0x08ECD7FC, 0x08ECD820)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7FC, map_37_state_01_08ECD7FC, 0x08ECD808, 0x08ECD814)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Can you not hear it? Can you\nnot hear the pain of the\n\nocean?\n\nI was raised on the high\nseas, so I can understand\n\nwhen all is not right.\n\nThe waters are crying, but\nabout what...\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("{CARD_1}Actually...\nYou're imagining things{CARD_2}\n\n")
  SET_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD808, map_37_state_01_08ECD808, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("What's going on?\n\n")
  PLAY_MUSIC(332)
  FADE_SCREEN(8)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Reshef the Dark Being?\nThat's hard to believe.\n\nBut the tides have been far\nfrom normal.\n\nIf anything has to do with\nthis mystery...\n\nGo deeper into the island.\nYou may find something.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD814, map_37_state_01_08ECD814, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Oh, I'm imagining things, am\nI?\n\nYou cannot deceive me.\n\nI can tell you're hiding\nsomething...important.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("You do not have to reveal\nyour secrets if you are not\n\nso inclined.\n\nBut I will let you know that\nthe tides have been far\n\nfrom normal.\n\nIf anything has to do with\nthis mystery...\n\nGo deeper into the island.\nYou may find something.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD820, map_37_state_01_08ECD820, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("There's something wrong with\nthe sea.\n\nI hope it's not a sign of\nsome impending catastrophe.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD7F0, map_37_state_01_08ECD7F0, 0x08ECD7FC, 0x08ECD82C)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_MAKO)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD82C, map_37_state_01_08ECD82C, 0x08ECD838, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_POSITION_AUTO)
  TEXT("Fine! Mako Tsunami does not\nflee from any challenge!\n\n")
  DUEL(48)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ECD838, map_37_state_01_08ECD838, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(246)
  PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_POSITION_AUTO)
  TEXT("Excellent duel!\n\nBut next time, you won't win\nso easily!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
