#include "event_macros.h"
#include "overworld.h"

/* map_29_state_07: map 29 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC90C, map_29_state_07_08EAC90C, 0x08EAC918, 0x08EAC924)
  CHECK_FLAG(135)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC918, map_29_state_07_08EAC918, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ahhh... It's good to be back\nin the dark.\n\nI don't know why everyone\nwant to be in the light.\n\nIt's so relaxing...\n\nBut something doesn't feel\nright...\n\nIt feels the same as the\ntime I was taking orders\n\nfrom Bandit Keith...\n\nThe best way to forget my\ntroubles is to have a duel!\n\n")
  LANGUAGE_TEXT(1, "Ahhh... Quel plaisir d'\xeatre\nde retour ici,\n\ndans l'obscurit\xe9.\nC'est si relaxant...\n\nMais pourquoi les\ngens veulent toujours\n\n\xeatre sous des\nlumi\xe8res aveuglantes ?\n\nMais j'ai un dr\xf4le\nde sentiment...\n\nComme quand j'\xe9tais\nsous les ordres de Ken...\n\nRien de tel qu'un duel\npour me mettre\n\nde bonne humeur.\n\n")
  LANGUAGE_TEXT(2, "Ahhh... Es ist ein gutes\nGef\xfchl, wieder hier in der\n\nDunkelheit zu sein.\nSo entspannend...\n\nWarum wollen sie alle\ndieses helle Licht?\n\nAber ich habe ein ungutes\nGef\xfchl...\n\nWie zu der Zeit, als mir\nKeith befahl...\n\nEin Duell ist die beste\nMedizin, um Unbehagen\n\nzu zerstreuen.\n\n")
  LANGUAGE_TEXT(3, "Ahhh... Che bello\ntornare qui, al buio.\n\n\xc8 cos\xec rilassante...\n\nPerch\xe9 tutti amano stare\nsotto la luce forte?\n\nMa ho una strana\nsensazione...\n\nCome quando prendevo\nordini da Keith...\n\nUn duello \xe8 il modo\nmigliore per allontanare\n\nla malinconia.\n\n")
  LANGUAGE_TEXT(4, "Ahhh... Es bueno estar\nde vuelta en la oscuridad.\n\nEs tan relajante...\n\n\xbfPor qu\xe9 todo el mundo\nquiere estar bajo el sol?\n\nPero tengo un\nmal presentimiento...\n\nComo cuando recib\xeda\n\xf3rdenes de Keith...\n\nUn duelo es lo mejor para\nelevar los \xe1nimos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC924, map_29_state_07_08EAC924, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Your journey is far from\nover.\n\nBut my card will definitely\nhelp you.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} n'a pas encore\nfini de se battre.\n\nMais ma carte spirituelle\nva s\xfbrement t'aider.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}s Kampf ist noch\nlange nicht vorbei.\n\nAber meine Geisterkarte wird\ndir bestimmt helfen.\n\n")
  LANGUAGE_TEXT(3, "La fine della battaglia di\n{PLAYER} \xe8 ancora lontana.\n\nMa la mia carta-spirito\nti sar\xe0 certo di aiuto.\n\n")
  LANGUAGE_TEXT(4, "La lucha de {PLAYER} no ha\nhecho m\xe1s que empezar.\n\nPero mi carta de esp\xedritu\nte ayudar\xe1 seguro\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC930, map_29_state_07_08EAC930, 0x08EAC93C, 0x08EAC954)
  CHECK_FLAG(135)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC93C, map_29_state_07_08EAC93C, 0x08EAC948, 0x08F0404C)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I've dueled you before,\n{PLAYER}...\n\nBut I've never seen you so\ndetermined.\n\nYou must be preparing for an\nenormous duel.\n\nOkay! {PLAYER}, I'll duel\nyou anytime you want.\n\n")
  LANGUAGE_TEXT(1, "Je t'ai d\xe9j\xe0 affront\xe9\nen duel, {PLAYER}.\n\nMais je ne t'ai jamais\nvu aussi d\xe9termin\xe9...\n\nTu ne pr\xe9pares\ns\xfbrement pas\n\nun duel ordinaire.\nOK, {PLAYER} !\n\nJe me battrais en duel\nd\xe8s que tu le voudras.\n\n")
  LANGUAGE_TEXT(2, "Ich habe mich schon fr\xfcher\nmit dir duelliert,\n\n{PLAYER}... Aber nie sahst\ndu so entschlossen aus.\n\nBereitest du dich auf kein\ngew\xf6hnliches Duell vor?\n\nOkay! {PLAYER}, ich nehme\nes jederzeit mit dir auf.\n\n")
  LANGUAGE_TEXT(3, "Ho gi\xe0 duellato con te,\n{PLAYER}...\n\nMa non ti ho mai visto\ncon uno sguardo cos\xec\n\ndeterminato. Mi pare di\ncapire che ti stai\n\npreparando per un duello\nfuori dal comune. Okay,\n\n{PLAYER}, dueller\xf2 con te\nogni volta che vorrai.\n\n")
  LANGUAGE_TEXT(4, "He luchado antes,\ncontigo, {PLAYER}...\n\nPero nunca te he\nvisto tan decidido.\n\nSupongo que el duelo\npara el que te preparas\n\nno es normal.\n\n\xa1Vale! {PLAYER},\nluchar\xe9 contigo\n\nsiempre que quieras.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(100)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC948, map_29_state_07_08EAC948, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I lost because you wanted to\nwin more than I did.\n\nIt's easy to tell you're\npreparing for a great\n\nbattle, {PLAYER}.\n\nYou have an enormous weight\non your shoulders. I wish I\n\ncould help you...\n\nI know! Take this card.\n\nIt represents me.\n\nIt's Pumpking the King of\nGhosts.\n\nI know it will come in\nhandy...\n\n")
  LANGUAGE_TEXT(1, "Je veux bien perdre.\n\nTon fardeau, {PLAYER},\na fait la diff\xe9rence.\n\nJe le vois bien.\n\nTu portes un fardeau \xe9norme,\nen notre nom \xe0 tous.\n\nJe me suis battu en duel\ncontre toi, mon ami.\n\nJ'esp\xe8re que tu vas gagner.\n\nJe sais !\nPrends cette carte.\n\nC'est ma carte\nspirituelle.\n\nC'est le Roi des fant\xf4mes.\n\nElle va s\xfbrement t'aider.\n\n")
  LANGUAGE_TEXT(2, "Ich akzeptiere die\nNiederlage.\n\nDeine Last, {PLAYER}, hat\ndich zum Sieg gef\xfchrt.\n\nSelbst ich sp\xfcre das.\n\nDu tr\xe4gst eine Riesenlast\nf\xfcr uns alle.\n\nIch habe mich mit dir\nduelliert, mein Freund.\n\nIch hoffe, du wirst Erfolg\nhaben.\n\nDu wirst es!\nNimm diese Karte!\n\nNimm meine Geisterkarte. Es\nist Pumpking, Geisterk\xf6nig.\n\nEr wird dir sicher helfen.\n\n")
  LANGUAGE_TEXT(3, "Accetto la sconfitta.\n\nIl tuo fardello, {PLAYER},\nha fatto la differenza.\n\nLo capisco anch'io.\n\nStai portando un enorme\nfardello per tutti noi.\n\nHo duellato insieme a\nte, amico mio.\n\nSpero che tu riesca\nnella tua impresa.\n\nLo so!\nPrendi questa carta.\n\nPrendi la mia carta-\nspirito.\n\n\xc8 il Re dei Fantasmi.\nTi aiuter\xe0 di certo.\n\n")
  LANGUAGE_TEXT(4, "Acepto la derrota.\n\nTu carga, {PLAYER},\nha sido la diferencia.\n\nHasta yo puedo decirlo.\n\nLlevas una enorme carga\npor todos nosotros.\n\nHe luchado junto a ti,\namigo.\n\nEspero que triunfes.\n\n\xa1Lo s\xe9!\nToma esta carta.\n\nToma mi carta de esp\xedritu.\n\nEs Pumpking el rey\nde fantasmas.\n\nSeguro que te ayudar\xe1.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Received Pumpking the King\nof Ghosts.")
  LANGUAGE_TEXT(1, "Re\xe7u le Roi des fant\xf4mes.")
  LANGUAGE_TEXT(2, "Pumpking, Geisterk\xf6nig,\nerhalten.")
  LANGUAGE_TEXT(3, "Ricevuto un Re dei Fantasmi.")
  LANGUAGE_TEXT(4, "Recibido un Pumpking\nel rey de fantasmas.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(16)
  PAGE_BREAK()
  ADD_CARD(99)
  SET_FLAG(135)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC954, map_29_state_07_08EAC954, 0x08EAC960, 0x08F0404C)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm a better duelist now\nthan when I was in Bandit\n\nKeith's gang.\n\nIf dueling me will hone your\nskills...\n\nI'll duel you anytime you\nwant.\n\n")
  LANGUAGE_TEXT(1, "Je ne suis plus\naux ordres de Ken.\n\nSi tu crois qu'un duel\navec moi te permettra\n\nd'aiguiser tes sens...\n\nalors je veux bien\nme battre contre toi.\n\n")
  LANGUAGE_TEXT(2, "Ich bin nicht mehr so wie\nfr\xfcher, als mir Keith\n\nBefehle erteilte.\n\nWenn ein Duell mit mir\ndeine Sinne sch\xe4rft...\n\nK\xe4mpfe ich jederzeit gerne\nmit dir.\n\n")
  LANGUAGE_TEXT(3, "Non sono pi\xf9 come quando\nprendevo ordini da Keith.\n\nSe duellare con me\nacuir\xe0 i tuoi sensi...\n\nAllora dueller\xf2 con te in\nqualsiasi momento.\n\n")
  LANGUAGE_TEXT(4, "No soy como cuando recib\xeda\n\xf3rdenes de Keith.\n\nSi luchar conmigo\nelevar\xe1 tus sentidos...\n\nEntonces, luchar\xe9\ncontigo cuando sea.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(148)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC960, map_29_state_07_08EAC960, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "D-did I help you a little?\n\nI'm rooting for you. Win!\n\n")
  LANGUAGE_TEXT(1, "E-est-ce que je t'ai\naid\xe9, m\xeame un peu ?\n\nJe te soutiens.\nFais de ton mieux.\n\n")
  LANGUAGE_TEXT(2, "H-habe ich dir wenigstens\nein wenig geholfen?\n\nIch dr\xfcck dir die Daumen.\nGib dein Bestes.\n\n")
  LANGUAGE_TEXT(3, "Almeno... ti ho\naiutato un po'?\n\nFaccio il tifo per te.\nMetticela tutta.\n\n")
  LANGUAGE_TEXT(4, "\xbfT-te he ayudado\naunque sea un poco?\n\nEstoy contigo.\nEsm\xe9rate.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
