#include "event_macros.h"
#include "overworld.h"

/* map_55_state_03: map 55 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EF057C, map_55_state_03_08EF057C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Fufufu... You've finally\narrived.\n\nDuelists of pure hearts and\nspirits, I was hoping you\n\nwould come.\n\nWhy? Because your defeats\nwill make the best\n\nofferings for the reborn\nReshef!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Now! Go, my disciples!\n\nGo forth and defeat them!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(4, 1)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Gawry nida!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(8, 1)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Gawry nida!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 96)
  WALK_OBJECT_Y(4, 96)
  WALK_OBJECT_Y(3, 96)
  WALK_OBJECT_Y(2, 96)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being\ncreated my disciples.\n\nThese duelists have neither\nemotion nor mercy.\n\nCrush them, my minions!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, 8)
  LANGUAGE_TEXT(0, "Ahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(43, 3, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
