#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_14_state_09: map 14 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08E775B8, map_14_state_09_08E775B8, 0x08E775D0, 0x08E775DC)
  LOAD_SPRITE(1, SPRITE_YUGI)
  LOAD_SPRITE(2, SPRITE_JOEY)
  LOAD_SPRITE(3, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(4, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(5, SPRITE_DOMINO_STATION_GUARD)
  LOAD_SPRITE(6, SPRITE_FENG_LONG)
  LOAD_SPRITE(7, SPRITE_NIBBLES)
  PLAY_MUSIC(MUSIC_230)
  HIDE_PORTRAIT()
  DELAY(64)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Gotta hand it to you, Yugi. That duel lasted barely a",
      "second!",
      "On the other hand..."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_RIGHT, "{PLAYER}, you had me worried!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "I... I couldn't afford to waste any time.",
      "I have to find the spirit right away!",
      "But {PLAYER}'s duel was pretty impressive.",
      "Let's keep this up, guys!"
  )
  HIDE_PORTRAIT()
  DELAY(64)
  FADE_MUSIC(4)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_DOX2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E775D0, map_14_state_09_08E775D0, EVENT_NOP, EVENT_NOP)
  WARP(LOCATION_PEGASUS_ISLAND_DUNGEON_STAIRCASE, 5, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E775DC, map_14_state_09_08E775DC, EVENT_NOP, EVENT_NOP)
  WARP(LOCATION_PEGASUS_ISLAND_DUNGEON_STAIRCASE, 6, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
