#include "event_macros.h"
#include "overworld.h"

/* map_00_state_18: map 0 state 18 */

EVENT_SCRIPT_REPLACEMENT(0x08E34A54, map_00_state_18_08E34A54, 0x08E34A60, 0x08F04040)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But we cannot worry about\nthat now. Time is of the\n\nessence.\n\nThe second Millennium Item\nmust be found...\n\nSo that we can restore the\nEgyptian God Cards.\n\nThat is the only way we can\ndefeat Sol Chevalsky...\n\nAnd imprison Reshef the Dark\nBeing again.\n\n{PLAYER}, please find the\nnext Millennium Item.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A60, map_00_state_18_08E34A60, 0x08E34A78, 0x08E34A6C)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A78, map_00_state_18_08E34A78, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "Thank you.\n\nThe next Millennium Item.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\nGo to Domino Pier.\n\nThe Millennium Item should\nbe aboard the cruise ship.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_UNLOCKED_DOMINO_PIER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A6C, map_00_state_18_08E34A6C, 0x08E34A60, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, I have no one to\nturn to but to you.\n\nI know I am asking for the\nimpossible, but I beg for\n\nyour help.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
