#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_41_state_02: map 41 state 2 */

LOAD_SPRITE(1, SPRITE_CHEVALIER)
LOAD_SPRITE(2, SPRITE_CHEVALIER)
LOAD_SPRITE(3, SPRITE_CHEVALIER)
PLAY_MUSIC(MUSIC_253)
DELAY(64)
PLAY_MUSIC(MUSIC_255)
SET_FLAG(EVENT_FLAG_SHAKE_SCREEN_AND_MOVE_BACKGROUND)
DELAY(64)
PLAY_MUSIC(MUSIC_258)
PLAY_MUSIC(MUSIC_412)
SCREEN_SHAKE(1)
DELAY(8)
PLAY_MUSIC(MUSIC_259)
SHOW_OBJECT(1, 40, 54, 0, 2, 0)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_260)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "Gawry nida! Gawry nida!\n\n"
    "We win all duels! Gawry!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(1, 50)
WALK_OBJECT_X(1, 48)
DELAY(16)
DUEL(DUELIST_JOEY_105)
PLAY_MUSIC(MUSIC_253)
PLAY_MUSIC(MUSIC_257)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "G-gawry nida... G-ga..\n"
    "n-niii.... urrri...\n\n"
)
PLAY_MUSIC(MUSIC_282)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
DELAY(32)
PLAY_MUSIC(MUSIC_258)
SCREEN_SHAKE(1)
DELAY(8)
PLAY_MUSIC(MUSIC_259)
SHOW_OBJECT(2, 76, 42, 0, 2, 0)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_260)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Gawry nida! Gawry nida!\n\n"
    "We win all duels! Gawry!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(2, 50)
WALK_OBJECT_X(2, 68)
DELAY(16)
DUEL(DUELIST_JOEY_105)
PLAY_MUSIC(MUSIC_253)
PLAY_MUSIC(MUSIC_257)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "G-gawry nida... G-ga..\n"
    "n-niii.... urrri...\n\n"
)
PLAY_MUSIC(MUSIC_282)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
DELAY(32)
PLAY_MUSIC(MUSIC_258)
SCREEN_SHAKE(1)
DELAY(8)
PLAY_MUSIC(MUSIC_259)
SHOW_OBJECT(3, 46, 36, 0, 2, 0)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_260)
OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_JUMPING)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "Gawry nida! Gawry nida!\n\n"
    "We win all duels! Gawry!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(3, 58)
WALK_OBJECT_Y(3, 42)
DELAY(16)
DUEL(DUELIST_JOEY_105)
PLAY_MUSIC(MUSIC_253)
PLAY_MUSIC(MUSIC_257)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "G-gawry nida... G-ga..\n"
    "n-niii.... urrri...\n\n"
)
PLAY_MUSIC(MUSIC_282)
OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_TELEPORT)
DELAY(64)
PLAY_MUSIC(MUSIC_256)
CLEAR_FLAG(246)
DELAY(64)
WALK_OBJECT_Y(0, 60)
SHOW_OBJECT(0, 128, 96, 0, 0, 0)
CHECK_FLAG(EVENT_FLAG_LEAVING_THE_CABLE_CAR_LEADS_TO_THE_TOP_OF_PEGASUS_ISLAND)
CHECK_FLAG(EVENT_FLAG_DEFEATED_KAIBA)
WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_BOTTOM_OUTSIDE, 2, 0, 0)

EVENT_SCRIPT_REPLACEMENT(0x08ED7CC0, map_41_state_02_08ED7CC0, 0x08F04040, 0x08F04040)
WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_BOTTOM_OUTSIDE, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7CCC, map_41_state_02_08ED7CCC, 0x08ED7CD8, 0x08ED7CE4)
CHECK_FLAG(EVENT_FLAG_DEFEATED_PANIK_AND_MIMIC_OF_DOOM2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7CD8, map_41_state_02_08ED7CD8, 0x08F04040, 0x08F04040)
CLEAR_FLAG(180)
  WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7CE4, map_41_state_02_08ED7CE4, 0x08F04040, 0x08F04040)
CLEAR_FLAG(180)
  WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
