#include "event_macros.h"
#include "overworld.h"

/* map_38_state_07: map 38 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08ED1778, map_38_state_07_08ED1778, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(33)
  DELAY(32)
  MOVE_OBJECT(2, 0, 8, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(3, 3, 8, 0)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(32)
  MOVE_OBJECT(5, 2, 8, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(4, 1, 8, 0)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(32)
  PORTRAIT(12, 0, 0)
  LANGUAGE_TEXT(0, "Keep working! There's no\ntime to rest!\n\n")
  LANGUAGE_TEXT(1, "Continue ! Pas le\ntemps de se reposer !\n\n")
  LANGUAGE_TEXT(2, "Weiter so! Nur keine\nM\xfcdigkeit vorsch\xfctzen!\n\n")
  LANGUAGE_TEXT(3, "Continua a lavorare!\nNiente pause!\n\n")
  LANGUAGE_TEXT(4, "\xa1Sigue d\xe1ndole!\n\xa1No hay descansos!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(323)
  PORTRAIT(38, 0, 0)
  LANGUAGE_TEXT(0, "U-ukiii...\n\n")
  LANGUAGE_TEXT(1, "U-ukiii...\n\n")
  LANGUAGE_TEXT(2, "U-ukiii...\n\n")
  LANGUAGE_TEXT(3, "U-ukiii...\n\n")
  LANGUAGE_TEXT(4, "U-ukiii...\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(37, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
