#include "event_macros.h"
#include "overworld.h"

/* map_60_state_01: map 60 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08F039CC, map_60_state_01_08F039CC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(27)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "Father, Mother...\n\nAnd all those people I\nharmed...\n\nI hope that the sun shines\nupon your spirits.\n\n")
  LANGUAGE_TEXT(1, "P\xe8re, M\xe8re...\n\nTous ces gens \xe0 qui\nj'ai fait du mal...\n\nJe prie pour que le soleil\nillumine vos esprits.\n\n")
  LANGUAGE_TEXT(2, "Vater, Mutter...\n\nAll die Menschen, denen\nich geschadet hatte...\n\nIch bete, dass die Sonne\neure Seelen erleuchtet.\n\n")
  LANGUAGE_TEXT(3, "Padre, Madre...\nE tutti coloro ai quali\n\nho fatto del male...\nPrego affinch\xe9 il sole\n\nrisplenda sui vostri\nspiriti.\n\n")
  LANGUAGE_TEXT(4, "Padre, madre...\n\nY a todos los que he hecho\nda\xf1o...\n\nRezo para que el sol brille\nen vuestros esp\xedritus.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "Hello. It has been a long\ntime.\n\n")
  LANGUAGE_TEXT(1, "Bonjour.\nCa faisait longtemps.\n\n")
  LANGUAGE_TEXT(2, "Hallo.\nEs ist lange her.\n\n")
  LANGUAGE_TEXT(3, "Salve.\n\xc8 da un po' che non\n\nci si vede.\n\n")
  LANGUAGE_TEXT(4, "Hola.\nHa pasado\n\nmucho tiempo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Master Marik, forgive us for\ndisturbing your rituals.\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Marik,\npardonnez-nous\n\nde d\xe9ranger vos pri\xe8res.\n\n")
  LANGUAGE_TEXT(2, "Meister Marik, vergebt die\nSt\xf6rung eurer Gebete.\n\n")
  LANGUAGE_TEXT(3, "Maestro Marik, ci\nperdoni per avere\n\ndisturbato le sue\npreghiere.\n\n")
  LANGUAGE_TEXT(4, "Amo Marik, perd\xf3nenos por\nperturbar sus plegarias.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "It does not matter. They are\nalways welcome.\n\nEven my departed Father\nwould have welcomed them.\n\n")
  LANGUAGE_TEXT(1, "Ca ne fait rien. Vous\n\xeates les bienvenus.\n\nMais mon P\xe8re d\xe9funt\nles aurait accueillis.\n\n")
  LANGUAGE_TEXT(2, "Das macht nichts.\nSie sind willkommen.\n\nSogar mein verblichener\nVater h\xe4tte sie begr\xfc\xdft.\n\n")
  LANGUAGE_TEXT(3, "Non ha importanza.\nSono i benvenuti qui.\n\nAnche il mio defunto Padre\nli avrebbe accolti.\n\n")
  LANGUAGE_TEXT(4, "No importa.\nSon bienvenidos aqu\xed.\n\nIncluso mi padre,\nya ido, les habr\xeda\n\ndado la bienvenida.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Marik, we need your help.\n\nWe have to awaken {PLAYER}'s\nThe Winged Dragon of Ra.\n\n")
  LANGUAGE_TEXT(1, "Marik, nous avons\nbesoin de ton aide.\n\nNous devons r\xe9veiller\n\nle Dragon Ail\xe9 de Ra\nde {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Marik, wir brauchen deine\nHilfe.\n\nUm {PLAYER}s Gefl\xfcgelten\nDrachen von Ra zu erwecken.\n\n")
  LANGUAGE_TEXT(3, "Marik, abbiamo bisogno\ndel suo aiuto. Dobbiamo\n\nrisvegliare il Drago Alato\ndi Ra di {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Marik, necesitamos\ntu ayuda.\n\nTenemos que despertar al\nDrag\xf3n Alado de Ra de\n\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "...Tell me more.\n\n")
  LANGUAGE_TEXT(1, "... Et encore...\n\n")
  LANGUAGE_TEXT(2, "... sagt mir mehr.\n\n")
  LANGUAGE_TEXT(3, "... Vai avanti.\n\n")
  LANGUAGE_TEXT(4, "... Decidme m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "So... That explains why my\nsister left in a hurry.\n\nIt makes sense now...\n\n")
  LANGUAGE_TEXT(1, "Ceci explique\ndonc pourquoi...\n\nma s\u0153ur est partie\ntoute paniqu\xe9e.\n\nJe comprends tout\nmaintenant.\n\n")
  LANGUAGE_TEXT(2, "Aha... Deshalb floh meine\nSchwester in Panik.\n\nEs ergibt jetzt einen\nSinn...\n\n")
  LANGUAGE_TEXT(3, "Cos\xec... \xc8 per questo\nche mia sorella se\n\nn'\xe8 andata in preda\nal panico.\n\nOra tutto ha un senso...\n\n")
  LANGUAGE_TEXT(4, "Entonces... Eso explica\nporqu\xe9 mi hermana se\n\nfue tan asustada.\nAhora tiene sentido.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "I understand what you seek.\n\n")
  LANGUAGE_TEXT(1, "Je comprends\nce que vous cherchez.\n\n")
  LANGUAGE_TEXT(2, "Ich begreife, was ihr sucht.\n\n")
  LANGUAGE_TEXT(3, "Capisco cosa state\ncercando.\n\n")
  LANGUAGE_TEXT(4, "Entiendo lo que\nbusc\xe1is.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Great! Then how about\ngetting on it right away?\n\n")
  LANGUAGE_TEXT(1, "G\xe9nial ! Alors, si on s'y\nmettait tout de suite ?\n\n")
  LANGUAGE_TEXT(2, "Klasse! Dann k\xf6nnen wir es\nsofort in Angriff nehmen.\n\n")
  LANGUAGE_TEXT(3, "Ottimo! Allora che ne dice\ndi darci subito da fare?\n\n")
  LANGUAGE_TEXT(4, "\xa1Estupendo! Entonces,\n\xbfqu\xe9 tal si se ponen con\n\nello ahora mismo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "I will not awaken Ra so\neasily.\n\n")
  LANGUAGE_TEXT(1, "Cependant, je ne vais pas\nr\xe9veiller Ra si facilement.\n\n")
  LANGUAGE_TEXT(2, "Ich werde Ra allerdings\nnicht so einfach wecken.\n\n")
  LANGUAGE_TEXT(3, "Tuttavia, non mi sar\xe0\nfacile risvegliare Ra.\n\n")
  LANGUAGE_TEXT(4, "Sin embargo, no despertar\xe9\na Ra tan f\xe1cilmente.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 2, 8)
  LANGUAGE_TEXT(0, "What?!\n\n")
  LANGUAGE_TEXT(1, "Quoi ?!\n\n")
  LANGUAGE_TEXT(2, "Was?!\n\n")
  LANGUAGE_TEXT(3, "Come sarebbe?!\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfQu\xe9?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "I believe you know why.\n\nRa is the most powerful of\nthe Egyptian God Cards.\n\nYou felt its mystical\nstrength firsthand.\n\n")
  LANGUAGE_TEXT(1, "Tu connais d\xe9j\xe0 la r\xe9ponse.\n\nRa est la plus puissante\ndes cartes de dieux.\n\nTu devrais le savoir, tu en\nas d\xe9j\xe0 fait l'exp\xe9rience.\n\n")
  LANGUAGE_TEXT(2, "Ich denke, ihr kennt\ndie Antwort bereits.\n\nRa ist die m\xe4chtigste der\nG\xf6tterkarten.\n\nDas solltet ihr wissen. Ihr\nhabt es doch selbst erlebt.\n\n")
  LANGUAGE_TEXT(3, "Credo che tu gi\xe0 conosca\nla risposta.\n\nRa \xe8 la pi\xf9 potente\ndelle carte divine.\n\nDovresti saperlo. Lo hai\nsperimentato tu stesso.\n\n")
  LANGUAGE_TEXT(4, "Creo que sabes\nla respuesta.\n\nRa es la m\xe1s poderosa de las\ncartas de los dioses.\n\nLo deber\xedas saber. Lo has\nvivido en propia carne.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(332)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  SET_FLAG(243)
  WARP(23, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A38, map_60_state_01_08F03A38, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "There must be a secret in\nthe hieroglyphics.\n\nA secret method for\nawakening the Phoenix Mode.\n\n")
  LANGUAGE_TEXT(1, "Ce texte hi\xe9ratique doit\nbien cacher un secret.\n\nUn secret pour activer\nle Mode Ph\xe9nix.\n\n")
  LANGUAGE_TEXT(2, "Es muss sich ein Geheimnis\nhinter der Priesterschrift\n\nverbergen. Die L\xf6sung, wie\nman den Ph\xf6nix-Modus\n\nerweckt.\n\n")
  LANGUAGE_TEXT(3, "Il testo ieratico cela\nsicuramente un segreto.\n\nUn segreto per risvegliare\nla Modalit\xe0 Fenice.\n\n")
  LANGUAGE_TEXT(4, "Debe de haber un secreto\ntras el texto hier\xe1tico.\n\nUn secreto para despertar\nal Modo F\xe9nix.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A44, map_60_state_01_08F03A44, 0x08F03A50, 0x08F03A5C)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "Fine.\n\nI have been freed of my\nobligations as a\n\ngravekeeper.\n\nWhen I duel, I duel for\nmyself and will use all my\n\narcane strategies!\n\n")
  LANGUAGE_TEXT(1, "Bien.\n\nJ'ai \xe9t\xe9 lib\xe9r\xe9 de mon\ndestin de fossoyeur.\n\nEn duel, je vais donner le\nmaximum de moi-m\xeame !\n\n")
  LANGUAGE_TEXT(2, "Gut.\n\nIch bin von meinem Schicksal\nals Grabh\xfcter befreit.\n\nWenn ich mich duelliere,\ngebe ich vollen Einsatz!\n\n")
  LANGUAGE_TEXT(3, "Bene.\n\nSono stato liberato dal\nmio destino di custode\n\ndi tombe. Quando dueller\xf2,\nniente mi fermer\xe0!\n\n")
  LANGUAGE_TEXT(4, "Vale.\n\nHe sido liberado\nde mi destino como\n\nguardi\xe1n de tumbas.\n\n\xa1Cuando luche, no\nahorrar\xe9 esfuerzos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(158)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A50, map_60_state_01_08F03A50, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(27)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "You won...\n\nYou may be ready to face the\nDark Being...\n\n")
  LANGUAGE_TEXT(1, "Tu as gagn\xe9...\n\nCette victoire est\ndigne d'un duelliste\n\naffrontant l'Etre des\nt\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "Du hast gewonnen...\n\nDieser Sieg nutzt einem\nDuellanten, der dem\n\nDunklen gegen\xfcbersteht.\n\n")
  LANGUAGE_TEXT(3, "Hai vinto...\n\nQuesta vittoria va a\nvantaggio di un duellante\n\nche dovr\xe0 affrontare il\nTenebroso...\n\n")
  LANGUAGE_TEXT(4, "Has ganado...\n\nEsta victoria corresponde a\nun duelista que se enfrente\n\nal Ser Oscuro...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A5C, map_60_state_01_08F03A5C, 0x08F0404C, 0x08F04040)
  SET_FLAG(205)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A08, map_60_state_01_08F03A08, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Since you arrived, Master\nMarik has been chanting\n\ndevoutly.\n\nHe is chanting to atone for\nhis past sins.\n\n")
  LANGUAGE_TEXT(1, "Depuis votre arriv\xe9e,\n\nMa\xeetre Marik prie\navec d\xe9votion.\n\nIl fait cela pour\nexpier ses fautes.\n\n")
  LANGUAGE_TEXT(2, "Seit ihr kamt, betet\nMeister Marik innig.\n\nEr betet, um f\xfcr fr\xfchere\nS\xfcnden zu b\xfc\xdfen.\n\n")
  LANGUAGE_TEXT(3, "Da quando siete venuti,\nil maestro Marik ha\n\npregato con devozione.\nLe sue sono preghiere di\n\nespiazione per i peccati\ncommessi in passato.\n\n")
  LANGUAGE_TEXT(4, "Desde que vinisteis,\nel amo Marik ha\n\nestado rezando\ndevotamente.\n\nReza para expiar\nsus pecados pasados.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A14, map_60_state_01_08F03A14, 0x08F03A20, 0x08F03A2C)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "You dare enter my haven of\ntraps?\n\nFine! We shall duel!\n\n")
  LANGUAGE_TEXT(1, "Tu oses entrer dans mon\nantre cribl\xe9e de pi\xe8ges ?\n\nTr\xe8s bien !\nBattons-nous en duel !\n\n")
  LANGUAGE_TEXT(2, "Du wagst es, mein Fallen-\narsenal zu betreten?\n\nGut!\nWir werden k\xe4mpfen!\n\n")
  LANGUAGE_TEXT(3, "Tu osi entrare nel mio\ncovo di trappole?\n\nBene!\nAllora duelliamo!\n\n")
  LANGUAGE_TEXT(4, "\xbfOsas entrar en mi\npara\xedso de trampas?\n\n\xa1Vale!\n\xa1Lucharemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A20, map_60_state_01_08F03A20, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(27)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Gah! Your fighting spirit is\nmost impressive!\n\n")
  LANGUAGE_TEXT(1, "Grr ! Ta volont\xe9\nde combattre est tr\xe8s\n\nimpressionnante !\n\n")
  LANGUAGE_TEXT(2, "Gah! Dein Kampfgeist ist\n\xe4u\xdferst beeindruckend!\n\n")
  LANGUAGE_TEXT(3, "Ah! Il tuo spirito\ncombattente \xe8\n\ndavvero notevole!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vaya! Tu \xe1nimo luchador\nes impresionante.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A2C, map_60_state_01_08F03A2C, 0x08F0404C, 0x08F04040)
  SET_FLAG(205)
  FALLTHROUGH()
END_EVENT_SCRIPT()
