#include "event_macros.h"
#include "overworld.h"

/* map_12_state_12: map 12 state 12 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F138, map_12_state_12_08E6F138, 0x08E6F144, 0x08E6F150)
  PLAY_MUSIC(31)
  MOVE_OBJECT(0, 3, 8, 0)
  MOVE_OBJECT(13, 3, 8, 0)
  MOVE_OBJECT(14, 3, 8, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  DELAY(8)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "You're Seto Kaiba, aren't\nyou?\n\n")
  LANGUAGE_TEXT(1, "Tu es Kaiba Seto,\nn'est-ce pas ?\n\n")
  LANGUAGE_TEXT(2, "Du bist doch Kaiba Seto,\noder?\n\n")
  LANGUAGE_TEXT(3, "Tu sei Kaiba Seto, vero?\n\n")
  LANGUAGE_TEXT(4, "T\xfa eres Kaiba Seto, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 24577)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8192)
  DELAY(8)
  PORTRAIT(10, 2, 8)
  LANGUAGE_TEXT(0, "Who are you? You're not very\npolite.\n\n")
  LANGUAGE_TEXT(1, "Et toi, qui es-tu ?\n\nTu n'as pas \xe9t\xe9 polie\nenvers mon grand fr\xe8re.\n\n")
  LANGUAGE_TEXT(2, "Und wo steckst du? Du bist\nunh\xf6flich zu meinem Bruder.\n\n")
  LANGUAGE_TEXT(3, "E tu chi sei? Non rivolgerti\ncos\xec a mio fratello.\n\n")
  LANGUAGE_TEXT(4, "\xbfY t\xfa qui\xe9n eres?\n\nEst\xe1s siendo grosero con\ngran hermano.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(39, 0, 8)
  LANGUAGE_TEXT(0, "I'm Rebecca.\n\nAnd this is my friend Teddy.\n\n")
  LANGUAGE_TEXT(1, "Je m'appelle Rebecca.\n\nEt voici mon amie Terry.\n\n")
  LANGUAGE_TEXT(2, "Ich bin Rebecca.\n\nUnd das ist mein\nFreund Terry.\n\n")
  LANGUAGE_TEXT(3, "Io sono Rebecca.\n\nE questa \xe8 la mia\namica Terry.\n\n")
  LANGUAGE_TEXT(4, "Soy Rebecca.\n\nY \xe9ste es mi amigo Terry.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PORTRAIT(40, 0, 8)
  DELAY(96)
  PORTRAIT(10, 0, 8)
  LANGUAGE_TEXT(0, "A stuffed animal is your\nfriend?\n\n")
  LANGUAGE_TEXT(1, "Quoi, cette poup\xe9e,\nc'est ton amie ?\n\n")
  LANGUAGE_TEXT(2, "Du nennst eine Puppe deine\nFreundin?\n\n")
  LANGUAGE_TEXT(3, "Hai una bambola\nimbottita per amica?\n\n")
  LANGUAGE_TEXT(4, "\xbfUn peluche es\ntu amigo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "Be quiet! Teddy's not a\nstuffed animal!\n\nTeddy is the best bear in\nthe galaxy! Growl!\n\nAnd we know a secret, don't\nwe, Teddy?\n\n")
  LANGUAGE_TEXT(1, "Arr\xeate ! Terry n'est\npas une poup\xe9e !\n\nLaisse-la tranquille !\n\nNous savons quelque\nchose sur toi, hein Terry ?\n\n")
  LANGUAGE_TEXT(2, "Sei still! Terry ist doch\nkeine Puppe!\n\nTerry ist Terry!\n\nWir wissen etwas, nicht\nwahr, Terry?\n\n")
  LANGUAGE_TEXT(3, "Zitto! Terry non \xe8 una\nbambola imbottita!\n\nTerry \xe8 Terry!\n\nNe sappiamo qualcosa\nnoi, vero, Terry?\n\n")
  LANGUAGE_TEXT(4, "\xa1Calla! \xa1Terry no es\nun peluche!\n\n\xa1Terry es Terry!\n\nSabemos algo, \xbfno\nes verdad, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "You're the one who tore up\nSolomon Muto's card.\n\nYou tore up his Blue-Eyes\nWhite Dragon.\n\n")
  LANGUAGE_TEXT(1, "C'est toi qui a d\xe9chir\xe9 la\ncarte de Solomon Muto.\n\nTu as d\xe9chir\xe9 son dragon\nblanc aux yeux bleus.\n\n")
  LANGUAGE_TEXT(2, "Du hast Solomon Mutos\nKarte zerrissen.\n\nSeinen blau\xe4ugigen\nwei\xdfen Drachen.\n\n")
  LANGUAGE_TEXT(3, "Tu sei quello che ha\ndistrutto la carta di\n\nSolomon Muto, la sua\nDrago Bianco Occhi Blu.\n\n")
  LANGUAGE_TEXT(4, "T\xfa rompiste la tarjeta\nde Solomon Muto.\n\nT\xfa rompiste su Drag\xf3n\nblanco de ojos azules.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 4)
  DELAY(8)
  PORTRAIT(3, 0, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(10, 3, 8)
  LANGUAGE_TEXT(0, "H-how did you know...\n\n")
  LANGUAGE_TEXT(1, "M-mais...\n\n")
  LANGUAGE_TEXT(2, "A-aber...\n\n")
  LANGUAGE_TEXT(3, "M-ma...\n\n")
  LANGUAGE_TEXT(4, "P-pero...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(32)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "My grandfather gave Mr. Muto\nthat card.\n\nThat Blue-Eyes White Dragon\nwas a symbol of their\n\nfriendship, but you tore it\nup!\n\nYou're not going to get away\nwith that! Right, Teddy?\n\n")
  LANGUAGE_TEXT(1, "Mon grand-p\xe8re avait donn\xe9\ncette carte \xe0 M. Muto.\n\nCe dragon blanc\naux yeux bleus,\n\nc'\xe9tait le symbole\nde leur amiti\xe9.\n\nMais tu l'as d\xe9chir\xe9.\n\nJe ne te le pardonnerai\npas, hein, Terry ?\n\n")
  LANGUAGE_TEXT(2, "Mein Gro\xdfvater gab\nHerrn Muto diese Karte.\n\nDer blau\xe4ugige w. Drache\nwar ein Zeichen ihrer\n\nFreundschaft. Und du\nhast die Karte zerrissen.\n\nDas kann ich dir nicht\nverzeihen, Terry.\n\n")
  LANGUAGE_TEXT(3, "Mio nonno ha dato quella\ncarta al Sig. Muto. Quel\n\nDrago Bianco Occhi Blu\nera un segno di amicizia.\n\nMa tu l'hai distrutto.\n\nNon ti perdono, dico\nbene, Terry?\n\n")
  LANGUAGE_TEXT(4, "Esa tarjeta se la dio al\nSr. Muto mi abuelo.\n\nEse Drag\xf3n blanco de\nojos azules era un\n\ns\xedmbolo de amistad.\n\nPero t\xfa lo rompiste.\n\nNo te perdono,\n\xbfno es as\xed, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(3, 0, 8)
  LANGUAGE_TEXT(0, "So what do you want me to\ndo?\n\n")
  LANGUAGE_TEXT(1, "Mais alors qu'est-ce\nque je peux y faire ?\n\n")
  LANGUAGE_TEXT(2, "Was soll ich also jetzt\ntun?\n\n")
  LANGUAGE_TEXT(3, "Allora cosa vuoi che\nfaccia per rimediare?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 quieres que haga\nal respecto?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(10, 2, 8)
  LANGUAGE_TEXT(0, "Seto, just ignore her...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re, ce n'est pas\nla peine de t'occuper\n\nd'elle...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder, du musst dich\nnicht mit ihr abgeben...\n\n")
  LANGUAGE_TEXT(3, "Fratello, non stare a\nperdere tempo con lei...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano, no tienes\nque tratar con ella...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "I challenge you to a duel!\n\n")
  LANGUAGE_TEXT(1, "Tu peux m'affronter en\nduel. On verra alors\n\n")
  LANGUAGE_TEXT(2, "Du kannst dich mit\nmir duellieren.\n\n")
  LANGUAGE_TEXT(3, "Puoi duellare con me.\n\n")
  LANGUAGE_TEXT(4, "Puedes luchar conmigo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "I'll wipe that smirk off\nyour face.\n\nBecause you're facing the\nUnited States champion!\n\nRight, Teddy?\n\n")
  LANGUAGE_TEXT(1, "si tu es toujours\naussi arrogant !\n\nCar je suis la\nchampionne U.S.\n\nPas vrai, Terry ?\n\n")
  LANGUAGE_TEXT(2, "Ich werde deiner Arroganz\neinen D\xe4mpfer versetzen.\n\nIch bin amerikanische\nMeisterin.\n\nStimmt's, Terry?\n\n")
  LANGUAGE_TEXT(3, "Dar\xf2 una bella lezione\nalla tua arroganza.\n\nVisto che sono la\ncampionessa U.S.A.\n\nGiusto, Terry?\n\n")
  LANGUAGE_TEXT(4, "Te bajar\xe9 los humos.\n\nPorque soy la\ncampeona de EE.UU.\n\n\xbfNo es as\xed, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(3, 0, 8)
  LANGUAGE_TEXT(0, "U.S. champ? That's it?\n\nAt your duelist level, I can\ndefeat you blindfolded.\n\n")
  LANGUAGE_TEXT(1, "Championne U.S. ?\nC'est tout ?\n\nEt tu me d\xe9fie alors que tu\nn'es qu'\xe0 ce niveau-l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Amerikanische Meisterin?\nIst das alles?\n\nUnd mit dem Level willst\ndu mich herausfordern?\n\n")
  LANGUAGE_TEXT(3, "La campionessa U.S.A.?\nTutto qui?\n\nE tu sfidi me a quel\nlivello?\n\n")
  LANGUAGE_TEXT(4, "\xbfCampeona de EE.UU.?\n\xbfEso es todo?\n\n\xbfMe retas a ese\nnivel de nada?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(5, 16)
  DELAY(8)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "At my level?! Are you making\nfun of me?!\n\n")
  LANGUAGE_TEXT(1, "Qu'\xe0 ce niveau-l\xe0 ?\nOh, toi...\n\n")
  LANGUAGE_TEXT(2, "Mit dem Level?\nAber du...\n\n")
  LANGUAGE_TEXT(3, "A che livello ti riferisci?\nEhi, bada...\n\n")
  LANGUAGE_TEXT(4, "\xbfNivel de nada?\nPor qu\xe9, t\xfa...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(3, 0, 8)
  LANGUAGE_TEXT(0, "No, I'm just telling the\ntruth.\n\nYour skills are nothing but\na joke.\n\nBut if you still insist on\nchallenging me...\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce que tu crois ?\n\nDepuis la chute de Pegasus,\nle niveau des duellistes\n\nam\xe9ricains fait rire tout le\nmonde.\n\nMais si tu insistes...\n\n")
  LANGUAGE_TEXT(2, "Was erwartest du nach\nPegasus' Niederlage?\n\nDas amerikanische Duellan-\nten-Level ist ein Witz.\n\nAber wenn du auf einem\nDuell bestehst...\n\n")
  LANGUAGE_TEXT(3, "Cosa pretendi, dopo la\nsconfitta di Pegasus?\n\nIl livello duellante degli\namericani fa ridere.\n\nMa se proprio insisti a\nvolermi sfidare...\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 esperas tras la\nca\xedda de Pegasus?\n\nEl nivel duelista americano\nes una broma.\n\nPero si insistes\nen retarme...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8)
  DELAY(8)
  PORTRAIT(3, 1, 8)
  LANGUAGE_TEXT(0, "I have a better idea. Duel\nagainst {PLAYER}.\n\nIf you can beat him, I'll\nduel you.\n\n")
  LANGUAGE_TEXT(1, "On va s'y prendre\ncomme \xe7a :\n\naffronte {PLAYER}\nen duel.\n\nSi tu sors vainqueur,\nje t'affronterai en duel.\n\n")
  LANGUAGE_TEXT(2, "Wir machen es so: Duelliere\ndich mit {PLAYER}.\n\nWenn du ihn besiegst, duel-\nliere ich mich mit dir.\n\n")
  LANGUAGE_TEXT(3, "Faremo cos\xec. Tu\nduelli con {PLAYER}.\n\nSe riesci a batterlo, io\ndueller\xf2 con te.\n\n")
  LANGUAGE_TEXT(4, "Lo haremos as\xed:\nLucha con {PLAYER}.\n\nSi le ganas, me\nbatir\xe9 contigo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24593)
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(13, 24)
  WALK_OBJECT_Y(13, 48)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(48)
  WALK_OBJECT_Y(13, 44)
  WALK_OBJECT_X(13, 30)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_X(0, 40)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 20)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Rebecca, I know you're\nupset, but there's no point\n\nattacking Kaiba.\n\n")
  LANGUAGE_TEXT(1, "Rebecca, je\ncomprends ta col\xe8re.\n\nMais ce n'est pas\nune raison\n\npour engueuler Seto.\n\n")
  LANGUAGE_TEXT(2, "Rebecca, ich verstehe\ndeinen Zorn.\n\nAber es nutzt nichts, wenn\ndu jetzt Seto z\xfcrnst.\n\n")
  LANGUAGE_TEXT(3, "Rebecca, capisco\nperch\xe9 sei arrabbiata.\n\nMa ora non ha senso\nprendersela con Seto.\n\n")
  LANGUAGE_TEXT(4, "Rebecca, comprendo por\nqu\xe9 est\xe1s enfadada.\n\nPero no hay raz\xf3n\nen reprochar nada\n\na Seto ahora.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "Yugi...\n\nI'm not challenging Kaiba\nbecause I'm angry.\n\nI want to duel him to test\nmy skills.\n\nRight, Teddy?\n\n")
  LANGUAGE_TEXT(1, "Yugi Muto...\n\nJe ne d\xe9fie pas Seto\npar simple haine.\n\nJe veux juste savoir\nquel est son vrai niveau.\n\nPas vrai, Terry ?\n\n")
  LANGUAGE_TEXT(2, "Yugi Muto...\n\nIch fordere Seto nicht\naus Hass heraus.\n\nIch m\xf6chte nur wissen, wie\ngut er wirklich ist.\n\nStimmt's, Terry?\n\n")
  LANGUAGE_TEXT(3, "Yugi Muto...\n\nIo non sto sfidando\nSeto perch\xe9 lo odio.\n\nVoglio solo vedere\nquanto \xe8 bravo in realt\xe0.\n\nGiusto, Terry?\n\n")
  LANGUAGE_TEXT(4, "Yugi Muto...\n\nNo reto a Seto porque\nle odie.\n\nS\xf3lo quiero ver cu\xe1n\nbueno es en realidad.\n\n\xbfNo es as\xed, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Rebecca...\n\n")
  LANGUAGE_TEXT(1, "Rebecca...\n\n")
  LANGUAGE_TEXT(2, "Rebecca...\n\n")
  LANGUAGE_TEXT(3, "Rebecca...\n\n")
  LANGUAGE_TEXT(4, "Rebecca...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 2, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 40)
  WALK_OBJECT_Y(4, 40)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 48, 40, 0, 0, 0)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(8)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(39, 0, 8)
  LANGUAGE_TEXT(0, "Hmm... Are you really that\nstrong of a duelist?\n\nYou sure don't look it.\nTeddy doesn't think so,\n\neither.\n\n")
  LANGUAGE_TEXT(1, "Hmm... Es-tu vraiment\nun bon duelliste ?\n\nOn ne le dirait pas.\nPas vrai, Terry ?\n\n")
  LANGUAGE_TEXT(2, "Hmm... Bist du wirklich\nso stark?\n\nDu wirkst gar nicht so.\nStimmt's, Terry?\n\n")
  LANGUAGE_TEXT(3, "Hmm... Sei davvero\nforte come duellante?\n\nA guardarti, non si\ndirebbe. Giusto, Terry?\n\n")
  LANGUAGE_TEXT(4, "Hmm... \xbfEres tan\nfuerte en los duelos?\n\nNo lo pareces.\n\xbfNo es as\xed, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  PORTRAIT(39, 0, 8)
  LANGUAGE_TEXT(0, "But I'm still dueling you!\n\n")
  LANGUAGE_TEXT(1, "Mais il faut que tu\nm'affrontes en duel !\n\n")
  LANGUAGE_TEXT(2, "Aber du musst dich\nmit mir duellieren!\n\n")
  LANGUAGE_TEXT(3, "Ma devi duellare con me!\n\n")
  LANGUAGE_TEXT(4, "\xa1Pero tienes que\nluchar conmigo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F144, map_12_state_12_08E6F144, 0x08E6F15C, 0x08F0404C)
  DUEL(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F15C, map_12_state_12_08E6F15C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "I... I lost?\n\nDid I really lose? Teddy?\n\n")
  LANGUAGE_TEXT(1, "Je... j'ai perdu ?\n\nEst-ce que j'ai vraiment\nperdu ? Terry ?\n\n")
  LANGUAGE_TEXT(2, "Was, ich habe verloren?\n\nWirklich verloren? Ist\ndas m\xf6glich? Terry?\n\n")
  LANGUAGE_TEXT(3, "Io... ho perso?\n\nMa ho perso davvero?\nTerry?\n\n")
  LANGUAGE_TEXT(4, "P... \xbfPerd\xed?\n\n\xbfDe verdad he perdido?\n\xbfTerry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(3, 1, 8)
  LANGUAGE_TEXT(0, "Humph. That duel was a joke.\n\n")
  LANGUAGE_TEXT(1, "Mmm. Arr\xeate ton cin\xe9ma.\n\n")
  LANGUAGE_TEXT(2, "Hm. So viel also zu deiner\nShow.\n\n")
  LANGUAGE_TEXT(3, "Uff. Basta con questa\ncommedia.\n\n")
  LANGUAGE_TEXT(4, "Vaya. Tanta comedia\npara esto.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(3, 2, 8)
  LANGUAGE_TEXT(0, "If you want your revenge,\ncome back when you actually\n\npose a challenge.\n\nYou know where to find me!\n\n")
  LANGUAGE_TEXT(1, "Si tu veux une revanche,\nreviens quand tu seras\n\nen meilleure forme.\nMoi, Kaiba Seto,\n\nje serais toujours\npr\xeat \xe0 t'affronter.\n\n")
  LANGUAGE_TEXT(2, "Wenn du eine Revanche\nm\xf6chtest, \xfcb erst mal.\n\nIch, Kaiba Seto, werde mich\ndir stets gerne stellen.\n\n")
  LANGUAGE_TEXT(3, "Se vuoi la vendetta, torna\nquando sarai migliore.\n\nIo, Kaiba Seto, non fuggir\xf2\ne non mi nasconder\xf2 da te.\n\n")
  LANGUAGE_TEXT(4, "Si te quieres vengar, vuelve\ncuando seas mejor.\n\nYo, Kaiba Seto, no\nme esconder\xe9 de ti.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, 1, 16, 0)
  PORTRAIT(10, 0, 8)
  LANGUAGE_TEXT(0, "Just to let you know, my\nbrother would have finished\n\nyou off in half the number\nof turns!\n\n")
  LANGUAGE_TEXT(1, "Tu n'es pas pr\xeat\nd'atteindre le niveau\n\nde grand fr\xe8re.\n\n")
  LANGUAGE_TEXT(2, "Du reichst meinem gro\xdfen\nBruder nicht das Wasser.\n\n")
  LANGUAGE_TEXT(3, "Non ti avvicini neanche\nminimamente al livello\n\ndi mio fratello.\n\n")
  LANGUAGE_TEXT(4, "Est\xe1s muy lejos del\nnivel de gran hermano.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 0)
  MOVE_OBJECT(2, 1, 16, 0)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 16)
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Rebecca...\n\nI know Kaiba is arrogant and\nsays terrible things, but\n\nhe is a different person.\n\nThe Kaiba you saw today\nisn't like the Kaiba of\n\nold.\n\n")
  LANGUAGE_TEXT(1, "Rebecca...\n\nSeto est toujours aussi\nhorrible et arrogant.\n\nMais il a chang\xe9.\nLe Seto d'aujourd'hui\n\nn'est pas celui que je\nconnaissais autrefois.\n\n")
  LANGUAGE_TEXT(2, "Rebecca...\n\nSeto war noch immer arrogant\nund sagt schlimme Sachen.\n\nAber er hat sich gebessert.\n\nDer Seto, den du heute\nerlebt hast,\n\nist nicht mehr der Seto\nvon fr\xfcher.\n\n")
  LANGUAGE_TEXT(3, "Rebecca...\n\nSeto si comporta ancora\nda arrogante e dice cose\n\nterribili. Ma rispetto a\nprima, \xe8 cambiato. Il Seto\n\nche hai visto oggi \xe8 diverso\ndal Seto di un tempo.\n\n")
  LANGUAGE_TEXT(4, "Rebecca...\n\nSeto a\xfan act\xfaa con\narrogancia y dice\n\ncosas terribles.\n\nPero no es como\nera antes.\n\nEl Seto que has visto\nhoy no es el de antes.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(64)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "I don't care...\n\nKaiba's right. Without\nPegasus and Bandit Keith,\n\nAmerica doesn't have the top\nduelists anymore.\n\nThat's why I came here. To\nprove that we're still\n\npretty good!\n\n")
  LANGUAGE_TEXT(1, "Ca ne fait rien.\n\nCe que Seto a dit\nest vrai.\n\nLes Etats-Unis ont perdu\nPegasus et Bandit Ken.\n\nEt donc le niveau de\nduelliste du pays a chut\xe9.\n\nCa m'\xe9nerve... C'est\npour cela que je suis l\xe0.\n\n")
  LANGUAGE_TEXT(2, "Das spielt keine Rolle.\n\nSeto sprach die Wahrheit.\n\nAmerika hat Pegasus und\nBandit Keith verloren.\n\nDadurch ist das Duellanten-\nLevel in den USA gesunken.\n\nDas gefiel mir nicht...\nDarum kam ich hierher.\n\n")
  LANGUAGE_TEXT(3, "Non ha nessuna importanza.\nQuello che ha detto Seto \xe8\n\nvero. L'America ha perso\nPegasus e Bandit Keith.\n\nCos\xec il livello duellante\ndel Paese \xe8 calato\n\ne io non lo sopporto. Per\nquesto sono venuta qui.\n\n")
  LANGUAGE_TEXT(4, "Eso no importa nada.\n\nSeto dice la verdad.\n\nAm\xe9rica ha perdido a\nPegasus y a Bandit Keith.\n\nY, as\xed, ha bajado el\nnivel duelista del pa\xeds.\n\nLo odiaba...\nPor eso vine aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(39, 0, 8)
  LANGUAGE_TEXT(0, "But losing to {PLAYER}...\nThat was an eye-opener.\n\nI should have been training\nthan complaining.\n\nI'm turning over a new leaf.\nI'm going to raise my\n\nduelist level so that I can\nput the United States back\n\non the map!\n\nJust you wait. I'll beat\nKaiba, Yugi, and you.\n\nRight, Teddy?\n\n")
  LANGUAGE_TEXT(1, "Mais perdre contre {PLAYER},\n\xe7a m'a ouvert les yeux...\n\nJ'ai oubli\xe9 de travailler\net j'ai accus\xe9 les autres.\n\nJe vais travailler pour\nessayer de relever mon\n\nniveau de duelliste.\n\nTu verras, je vais battre\nKaiba Seto, Yugi,\n\net m\xeame toi.\nPas vrai, Terry ?\n\n")
  LANGUAGE_TEXT(2, "Aber gegen {PLAYER}\nzu verlieren...\n\nDas hat mir die Augen\nge\xf6ffnet.\n\nIch habe mich nicht bem\xfcht\nund stets nur anderen die\n\nSchuld gegeben. Jetzt werde\nich versuchen, mein Duel-\n\nlanten-Level zu steigern.\n\nWart's nur ab.\nIch werde Kaiba Seto,\n\nYugi und dich besiegen.\nStimmt's, Terry?\n\n")
  LANGUAGE_TEXT(3, "Ma perdere con {PLAYER}...\nmi ha aperto gli occhi.\n\nAvevo dimenticato il\nlavoro e incolpavo gli\n\naltri. Lavorer\xf2 per\naumentare il mio livello\n\nduellante. Aspetta e\nvedrai che batter\xf2 Kaiba\n\nSeto, Yugi e te.\nDico bene, Terry?\n\n")
  LANGUAGE_TEXT(4, "Pero perder con {PLAYER}...\nMe hizo darme cuenta.\n\nDej\xe9 de trabajar y s\xf3lo\nculpaba a los dem\xe1s.\n\nVoy a trabajar para\nelevar mi nivel duelista.\n\nS\xf3lo espera. Os vencer\xe9 a\nti, Kaiba Seto y Yugi.\n\n\xbfNo es as\xed, Terry?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(40, 0, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(1, 1, 8)
  LANGUAGE_TEXT(0, "Yup! And I'll also train so\nthat I won't lose!\n\n")
  LANGUAGE_TEXT(1, "Ouais ! Et je continuerai\n\xe0 m'entra\xeener pour \xeatre s\xfbr\n\nde ne pas perdre !\n\n")
  LANGUAGE_TEXT(2, "Genau! Und ich werde mich\nanstrengen, damit ich nicht\n\nverliere!\n\n")
  LANGUAGE_TEXT(3, "Giusto! E io continuer\xf2 a\nlavorare per non perdere!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed! Y continuar\xe9\ntrabajando para no perder.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(39, 0, 8)
  LANGUAGE_TEXT(0, "I'm going home to practice!\n\nSay bye to Solomon Muto for\nme!\n\n")
  LANGUAGE_TEXT(1, "OK, je dois y aller.\n\nMerci de dire bonjour \xe0\nSolomon Muto de ma part.\n\n")
  LANGUAGE_TEXT(2, "Okay, ich muss jetzt gehen.\n\nGr\xfc\xdft bitte Solomon Muto\nvon mir.\n\n")
  LANGUAGE_TEXT(3, "Bene. Ora devo andare.\n\nTi prego, saluta Solomon\nMuto da parte mia.\n\n")
  LANGUAGE_TEXT(4, "Vale, me tengo que ir.\n\nSaluda a Solomon Muto\nde mi parte, por favor.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 2, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, 1, 16, 0)
  DELAY(16)
  SET_FLAG(176)
  PLAY_MUSIC(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F150, map_12_state_12_08E6F150, 0x08E6F15C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  DELAY(8)
  PORTRAIT(39, 5, 8)
  LANGUAGE_TEXT(0, "Even if you don't want to\nduel, I do!\n\nCome on! Or are you chicken!\n\n")
  LANGUAGE_TEXT(1, "M\xeame si tu ne veux\npas, moi je le veux !\n\nAllez !\nCommen\xe7ons !\n\n")
  LANGUAGE_TEXT(2, "Selbst wenn du es nicht\nwillst - ich schon!\n\nAlso komm!\nFangen wir an!\n\n")
  LANGUAGE_TEXT(3, "Anche se tu non vuoi,\nlo voglio io!\n\nForza, iniziamo!\n\n")
  LANGUAGE_TEXT(4, "Aunque no quieras,\n\xa1yo s\xed!\n\n\xa1Vamos!\n\xa1Empecemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1C8, map_12_state_12_08E6F1C8, 0x08F04040, 0x08F04040)
  PORTRAIT(30, 0, 8)
  LANGUAGE_TEXT(0, "That girl is no match for\nMaster Seto, but in ten\n\nyears, she will be ready to\ntake on the world.\n\n")
  LANGUAGE_TEXT(1, "Cette fille ne sera pas\npr\xeate avant {BYTE_8250}{BYTE_824F} ans...\n\nPour l'instant, elle\nne fait pas le poids\n\nface \xe0 un adversaire\ncomme ma\xeetre Seto.\n\n")
  LANGUAGE_TEXT(2, "Vielleicht ist das M\xe4dchen\nin zehn Jahren ganz gut...\n\nJetzt ist sie Meister Seto\njedenfalls nicht gewachsen.\n\n")
  LANGUAGE_TEXT(3, "Quella ragazza sar\xe0\npronta tra {BYTE_8250}{BYTE_824F} anni...\n\nAdesso non sarebbe\nin grado di affrontare\n\nil maestro Seto.\n\n")
  LANGUAGE_TEXT(4, "A esa ni\xf1a le quedan\nunos {BYTE_8250}{BYTE_824F} a\xf1os para\n\nestar lista.\n\nNo es rival para el\namo Seto ahora.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
