#include "event_macros.h"
#include "overworld.h"

/* map_12_state_12: map 12 state 12 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F138, map_12_state_12_08E6F138, 0x08E6F144, 0x08E6F150)
  PLAY_MUSIC(31)
  MOVE_OBJECT(0, 3, 8, 0)
  MOVE_OBJECT(13, 3, 8, 0)
  MOVE_OBJECT(14, 3, 8, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "You're Seto Kaiba, aren't\nyou?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 24577)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 8192)
  DELAY(8)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, 8)
  LANGUAGE_TEXT(0, "Who are you? You're not very\npolite.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm Rebecca.\n\nAnd this is my friend Teddy.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "A stuffed animal is your\nfriend?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "Be quiet! Teddy's not a\nstuffed animal!\n\nTeddy is the best bear in\nthe galaxy! Growl!\n\nAnd we know a secret, don't\nwe, Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "You're the one who tore up\nSolomon Muto's card.\n\nYou tore up his Blue-Eyes\nWhite Dragon.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, 8)
  LANGUAGE_TEXT(0, "H-how did you know...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "My grandfather gave Mr. Muto\nthat card.\n\nThat Blue-Eyes White Dragon\nwas a symbol of their\n\nfriendship, but you tore it\nup!\n\nYou're not going to get away\nwith that! Right, Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "So what do you want me to\ndo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, 8)
  LANGUAGE_TEXT(0, "Seto, just ignore her...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "I challenge you to a duel!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "I'll wipe that smirk off\nyour face.\n\nBecause you're facing the\nUnited States champion!\n\nRight, Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "U.S. champ? That's it?\n\nAt your duelist level, I can\ndefeat you blindfolded.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(REACTION_ANGRY, 16)
  DELAY(8)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "At my level?! Are you making\nfun of me?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No, I'm just telling the\ntruth.\n\nYour skills are nothing but\na joke.\n\nBut if you still insist on\nchallenging me...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "I have a better idea. Duel\nagainst {PLAYER}.\n\nIf you can beat him, I'll\nduel you.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24593)
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(13, 24)
  WALK_OBJECT_Y(13, 48)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(48)
  WALK_OBJECT_Y(13, 44)
  WALK_OBJECT_X(13, 30)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_X(0, 40)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 20)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Rebecca, I know you're\nupset, but there's no point\n\nattacking Kaiba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "Yugi...\n\nI'm not challenging Kaiba\nbecause I'm angry.\n\nI want to duel him to test\nmy skills.\n\nRight, Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Rebecca...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 2, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 40)
  WALK_OBJECT_Y(4, 40)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 48, 40, 0, 0, 0)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(8)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hmm... Are you really that\nstrong of a duelist?\n\nYou sure don't look it.\nTeddy doesn't think so,\n\neither.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(REACTION_SWEATDROP, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But I'm still dueling you!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F144, map_12_state_12_08E6F144, 0x08E6F15C, 0x08F0404C)
  DUEL(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F15C, map_12_state_12_08E6F15C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "I... I lost?\n\nDid I really lose? Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "Humph. That duel was a joke.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "If you want your revenge,\ncome back when you actually\n\npose a challenge.\n\nYou know where to find me!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, 1, 16, 0)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Just to let you know, my\nbrother would have finished\n\nyou off in half the number\nof turns!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 0)
  MOVE_OBJECT(2, 1, 16, 0)
  PLAY_MUSIC(275)
  REACTION(REACTION_ANGRY, 16384)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 16)
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Rebecca...\n\nI know Kaiba is arrogant and\nsays terrible things, but\n\nhe is a different person.\n\nThe Kaiba you saw today\nisn't like the Kaiba of\n\nold.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(64)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "I don't care...\n\nKaiba's right. Without\nPegasus and Bandit Keith,\n\nAmerica doesn't have the top\nduelists anymore.\n\nThat's why I came here. To\nprove that we're still\n\npretty good!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But losing to {PLAYER}...\nThat was an eye-opener.\n\nI should have been training\nthan complaining.\n\nI'm turning over a new leaf.\nI'm going to raise my\n\nduelist level so that I can\nput the United States back\n\non the map!\n\nJust you wait. I'll beat\nKaiba, Yugi, and you.\n\nRight, Teddy?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, 8)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "Yup! And I'll also train so\nthat I won't lose!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm going home to practice!\n\nSay bye to Solomon Muto for\nme!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 2, 0)
  DELAY(8)
  PLAY_MUSIC(372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, 1, 16, 0)
  DELAY(16)
  SET_FLAG(EVENT_FLAG_DEFEATED_REBECCA)
  PLAY_MUSIC(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F150, map_12_state_12_08E6F150, 0x08E6F15C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_REBECCA, 5, 8)
  LANGUAGE_TEXT(0, "Even if you don't want to\nduel, I do!\n\nCome on! Or are you chicken!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1C8, map_12_state_12_08E6F1C8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That girl is no match for\nMaster Seto, but in ten\n\nyears, she will be ready to\ntake on the world.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
