#include "event_macros.h"
#include "overworld.h"

/* map_00_state_09: map 0 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08E34C34, map_00_state_09_08E34C34, 0x08E34C4C, 0x08E34CB8)
  CHECK_FLAG(EVENT_FLAG_ISHIZU_IS_WAITING_FOR_KAIBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C4C, map_00_state_09_08E34C4C, 0x08E34C7C, 0x08E34C64)
  CHECK_FLAG(EVENT_FLAG_SAW_LUCKY_IN_CLOCK_TOWER_SQUARE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C7C, map_00_state_09_08E34C7C, 0x08E34C94, 0x08E34C88)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have obtained the\nMillennium Scale.\n\nWe now have six Millennium\nItems... Thank you.\n\nWe should now be able to use\nall three Egyptian God\n\nCards!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(0)
  PLAY_MUSIC(704)
  PLAY_MUSIC(291)
  REMOVE_CARD(238)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Slifer the Sky Dragon card\nturned into stone!\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C94, map_00_state_09_08E34C94, 0x08E34CA0, 0x08E34CAC)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wh-what's happening?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, 8)
  LANGUAGE_TEXT(0, "What's wrong?\n\nN-no! The Winged Dragon of\nRa did not resurrect...\n\nAnd even worse, Slifer the\nSky Dragon has turned back\n\ninto stone...\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(EVENT_FLAG_UNLOCKED_MONKEY_ROBOT_SIDEQUEST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CA0, map_00_state_09_08E34CA0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef's power must be\ngrowing exponentially!\n\nThe same fate most likely\nbefell Kaiba's card.\n\nObelisk the Tormentor has\nalso turned back into\n\nstone.\n\nPlease bring Kaiba here\nquickly.\n\nWe must fully revive the\nEgyptian God Cards...\n\nBut in order to do so, we\nneed the power of all seven\n\nMillennium Items.\n\nFurthermore, all three\nEgyptian God Cards must be\n\nreunited in one location.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The final Millennium Item...\n\nWe have yet to find the\nMillennium Puzzle.\n\nBut I have an idea as to its\nwhereabouts.\n\nPlease leave the Millennium\nPuzzle to me.\n\nWhile I look for it, please\nbring Kaiba here.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_ISHIZU_IS_WAITING_FOR_KAIBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CAC, map_00_state_09_08E34CAC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Is this the force of Reshef\nthe Dark Being?\n\nBut without the Egyptian God\nCards, we are helpless.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "There must be something we\ncan do.\n\nI must think of all\npossibilities, no matter\n\nhow small.\n\nIn the meantime, please\ntrain diligently.\n\nYou must raise your duelist\nlevel, or you will have no\n\nchance to win.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "If you insist, Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I guess we have no other\nchoice.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(2, 56)
  WALK_OBJECT_X(2, 48)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24579)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(33)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This dog... Isn't this\nLucky, Tristan's dog?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What would Lucky be doing\nhere?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 55)
  WALK_OBJECT_Y(2, 71)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24577)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Do ya think somethin'\nhappened at Tristan's\n\nhouse?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't worry about me.\n\nYou should check on your\nfriend immediately.\n\nIn the meantime, I will\nthink of a plan to stop\n\nReshef.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Okay, Ishizu. Good luck!\n\n{PLAYER}, Joey, let's go!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 112)
  SET_FLAG(EVENT_FLAG_SAW_LUCKY_IN_CLOCK_TOWER_SQUARE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C88, map_00_state_09_08E34C88, 0x08E34C94, 0x08E34C88)
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C64, map_00_state_09_08E34C64, 0x08E34CD0, 0x08E34CE8)
  CHECK_FLAG(EVENT_FLAG_COMPLETED_ROBOT_MONKEY_SIDEQUEST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CD0, map_00_state_09_08E34CD0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "In order to restore the\nEgyptian God Cards from\n\nstone...\n\nI'm sorry, but I have yet to\nfind the solution.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CE8, map_00_state_09_08E34CE8, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have returned at the\nright time.\n\nTo restore the Egyptian God\nCards from stone...\n\nWe need the Millennium\nItems.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But we tried that already.\nIt didn't work.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That was because the Items\nwere too weak.\n\nWe need all the Millennium\nItems in one place.\n\nIf we have them all, the\nEgyptian God Cards will be\n\nrestored.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "All the Millennium Items...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yes, all that remains is the\nMillennium Puzzle.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 8192)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Have no fear.\n\nI have an idea of its\nwhereabouts.\n\nI will retrieve the\nMillennium Puzzle.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ishizu, you don't have to\ngo.\n\nLet us handle it.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I have a different task for\nyou.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "A different one?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ra and Slifer were not the\nonly Egyptian God Cards\n\nthat turned into stone...\n\nKaiba's Obelisk the\nTormentor must have turned\n\ninto stone as well.\n\nPlease find Kaiba.\n\nWe need to bring the seven\nMillennium Items...\n\nAnd the three Egyptian God\nCards together.\n\nOnly then can we fully\nrestore the Egyptian God\n\nCards.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_ISHIZU_IS_WAITING_FOR_KAIBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CB8, map_00_state_09_08E34CB8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I will find the Millennium\nPuzzle..\n\nIn the meantime, please\nbring Kaiba here.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C40, map_00_state_09_08E34C40, 0x08E34C58, 0x08E34CC4)
  CHECK_FLAG(EVENT_FLAG_ISHIZU_IS_WAITING_FOR_KAIBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C58, map_00_state_09_08E34C58, 0x08E34C7C, 0x08E34C70)
  CHECK_FLAG(EVENT_FLAG_SAW_LUCKY_IN_CLOCK_TOWER_SQUARE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C70, map_00_state_09_08E34C70, 0x08E34CDC, 0x08E34CE8)
  CHECK_FLAG(EVENT_FLAG_COMPLETED_ROBOT_MONKEY_SIDEQUEST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CDC, map_00_state_09_08E34CDC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I thought you were going to\nlook for your friend\n\nTristan.\n\nI'm having difficulty\nfinding out how to restore\n\nthe Egyptian God Cards.\n\nIt will take me more time.\nSince there is little that\n\nyou can do to help...\n\nYou should concentrate on\nfinding your friend.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CC4, map_00_state_09_08E34CC4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Egyptian God Cards have\nbeen turned back into\n\nstone.\n\nTo fully resurrect them, the\nseven Millennium Items...\n\nAnd the three Egyptian God\nCards must be brought\n\ntogether.\n\nPlease bring Kaiba here\nright away.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
