#include "event_macros.h"
#include "overworld.h"

/* map_06_state_10: map 6 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD80, map_06_state_10_08E5CD80, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, 5, 8)
  LANGUAGE_TEXT(0, "...And that's what happened.\n\n")
  LANGUAGE_TEXT(1, "... Et voil\xe0\nce qui est arriv\xe9.\n\n")
  LANGUAGE_TEXT(2, "... Folgendes ist passiert.\n\n")
  LANGUAGE_TEXT(3, "... E questo \xe8 quanto\n\xe8 successo.\n\n")
  LANGUAGE_TEXT(4, "... Y eso es lo que pas\xf3.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  PORTRAIT(PORTRAIT_SERENITY, 3, 8)
  LANGUAGE_TEXT(0, "Big brother... I saw this\nlook on Tristan's face...\n\nIt was as if he was saying\nthat he didn't want anyone\n\nto follow him.\n\nI wonder if he's going to be\nokay...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re... Tristan a\nfait une dr\xf4le de t\xeate...\n\nComme s'il ne voulait\npas qu'on le suive.\n\nEst-ce que \xe7a va aller ?\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder... Tristan hat\nso eine Grimasse gezogen...\n\nAls wollte er nicht, dass\nihm jemand folgt.\n\nIst wohl alles okay?\n\n")
  LANGUAGE_TEXT(3, "Fratello... Tristan\nha fatto una smorfia...\n\nCome se non volesse\nessere seguito.\n\nAndr\xe0 tutto bene?\n\n")
  LANGUAGE_TEXT(4, "Gran hermano...\nTristan puso una cara...\n\nComo si no quisiera\nque le siguieran.\n\n\xbfVa a estar bien?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 2, 8)
  LANGUAGE_TEXT(0, "Don't worry about a thing,\nSerenity.\n\nTristan's our friend.\nThere's no way we'll\n\nabandon him!\n\nWe'll look for him, but I\nwant you to stay here,\n\nSerenity. Just in case he\ncomes back.\n\n")
  LANGUAGE_TEXT(1, "Ne t'inqui\xe8te pas,\nSerenity.\n\nIl n'est pas question que\nnous abandonnions Tristan.\n\nNous allons essayer\nde le trouver.\n\nAlors reste-l\xe0,\nSerenity.\n\nIl se peut aussi que\nTristan revienne ici.\n\n")
  LANGUAGE_TEXT(2, "Mach dir keine Sorgen,\nSerenity.\n\nWir lassen Tristan nat\xfcrlich\nnicht im Stich.\n\nWir versuchen, ihn zu\nfinden.\n\nBleib ruhig hier, Serenity.\n\nVielleicht taucht Tristan ja\npl\xf6tzlich auch hier auf.\n\n")
  LANGUAGE_TEXT(3, "Non hai niente di cui\npreoccuparti, Serenity.\n\nNon abbandoneremo\nmai Tristan. Proveremo\n\na cercarlo, mentre tu\nresterai qui, Serenity.\n\nTristan potrebbe pure farsi\nvivo qui all'improvviso.\n\n")
  LANGUAGE_TEXT(4, "No te preocupes de\nnada, Serenity.\n\nDe ning\xfan modo\nabandonaremos a Tristan.\n\nIntentaremos encontrarle;\nespera aqu\xed, Serenity.\n\nAdem\xe1s, puede que\nTristan venga por aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(161)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD98, map_06_state_10_08E5CD98, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "I bet Tristan ran off on\npurpose!\n\nThat's the only way Serenity\nwould pay attention to him\n\ninstead of me!\n\n...N-no, he wouldn't do\nthat. He's not that type of\n\nguy.\n\n")
  LANGUAGE_TEXT(1, "Est-ce que Tristan\nl'a fait expr\xe8s ?\n\nPour que Serenity le\nremarque et qu'elle ait\n\npiti\xe9 de lui ? Non,\nil ne ferait pas \xe7a...\n\n")
  LANGUAGE_TEXT(2, "Hat Tristan das\nabsichtlich getan?\n\nUm Serenitys Aufmerksamkeit\nund Sympathien zu gewinnen?\n\nN-nein, das w\xfcrde er nie\ntun...\n\n")
  LANGUAGE_TEXT(3, "Tristan l'avr\xe0 fatto\ndi proposito? Per\n\nattirare l'attenzione e\nla simpatia di Serenity?\n\nNo, no, non l'avrebbe\nmai fatto...\n\n")
  LANGUAGE_TEXT(4, "\xbfLo hizo aposta Tristan?\n\n\xbfPara conseguir la atenci\xf3n\ny compasi\xf3n de Serenity?\n\nN-no, no har\xeda tal cosa...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD8C, map_06_state_10_08E5CD8C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, 3, 8)
  LANGUAGE_TEXT(0, "Where could Tristan have\ngone?\n\n")
  LANGUAGE_TEXT(1, "O\xf9 est-ce que Tristan\na bien pu passer ?\n\n")
  LANGUAGE_TEXT(2, "Wo k\xf6nnte Tristan sein?\n\n")
  LANGUAGE_TEXT(3, "Dove pu\xf2 essere\nandato Tristan?\n\n")
  LANGUAGE_TEXT(4, "\xbfD\xf3nde puede haber\nido Tristan?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
