#include "event_macros.h"
#include "overworld.h"

/* map_49_state_01: map 49 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EDEBF0, map_49_state_01_08EDEBF0, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  SET_FLAG(EVENT_FLAG_UNLOCKED_PEGASUS_CASTLE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDEBD8, map_49_state_01_08EDEBD8, 0x08EDEBE4, 0x08F0404C)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Gawry nida! Gawry nida!\n\nYou'll go no further! Gawry!\n\n")
  DUEL(112)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDEBE4, map_49_state_01_08EDEBE4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_DUNGEON)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("G-gawry n-nida...\nM-master... G-gaah...\n\n")
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
