#include "event_macros.h"
#include "overworld.h"

/* map_34_state_04: map 34 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EC265C, map_34_state_04_08EC265C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "A long time ago, we were on\na dig in Egypt where we\n\nunearthed a stone tablet.\n\nLegend says the Egyptian\nGods fused together to\n\ncontain a malevolent and\ndangerous force inside the\n\ntablet.\n\nIf the darkness is ever set\nfree, the world will end.\n\nIt might just be a fairy\ntale, but it's pretty scary\n\nstuff.\n\n")
  LANGUAGE_TEXT(1, "Il y a longtemps, on faisait\ndes fouilles en Egypte,\n\nnon ?\n\nQuelqu'un avait enlev\xe9\nune tablette en pierre.\n\nEt \xe7a avait lib\xe9r\xe9 un \xeatre\nvraiment mal\xe9fique.\n\nMais il \xe9tait retenu par\nles dieux \xe9gyptiens\n\nqui avaient fusionn\xe9.\n\nSi cet \xeatre des t\xe9n\xe8bres\nest lib\xe9r\xe9, ce sera la fin\n\ndu monde.\n\nC'est ce qu'on m'a dit.\nCa fait plut\xf4t peur.\n\n")
  LANGUAGE_TEXT(2, "Vor langer Zeit gruben wir\nin \xc4gypten...\n\nJemand fand eine Stein-\ntafel.\n\nEs hie\xdf, in ihr sei ein\ndunkles Wesen,\n\nein sehr gef\xe4hrliches,\nversiegelt.\n\nDie fusionierten \xe4gypt.\nG\xf6tter hielten es\n\nverschlossen.\n\nWenn das dunkle Wesen\nfreigesetzt wird, bedeutet\n\ndas den Weltuntergang.\n\nDas sagte man mir jeden-\nfalls. Sehr beunruhigend.\n\n")
  LANGUAGE_TEXT(3, "Tanto tempo fa, stavamo\nlavorando a uno scavo\n\nin Egitto. Qualcuno dissot-\nterr\xf2 una tavoletta di\n\npietra. Dissero che vi era\nintrappolato un essere\n\noscuro, uno davvero\nmalefico. Fu trattenuto\n\ndagli dei egizi, che si\nunirono. Se quell'essere\n\noscuro venisse liberato,\nper il mondo sarebbe la\n\nfine. Cos\xec mi hanno detto.\nRoba da brividi.\n\n")
  LANGUAGE_TEXT(4, "Hace mucho tiempo,\nestuvimos en una\n\nexcavaci\xf3n en Egipto, \xbfeh?\n\nAlguien desenterr\xf3\nuna tabla de piedra.\n\nDec\xeda que hab\xeda encerrado\na un ser oscuro, uno malo\n\nde verdad.\nFue mantenido ah\xed por\n\ndioses egipcios que se\nfusionaron entre s\xed.\n\nSi ese ser oscuro sale,\nser\xe1 el fin del mundo.\n\nEso es lo que me dijeron.\nEn verdad asusta.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2668, map_34_state_04_08EC2668, 0x08EC2674, 0x08EC268C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SERIOUS_ARCHEOLOGIST2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2674, map_34_state_04_08EC2674, 0x08EC2680, 0x08F0404C)
  LANGUAGE_TEXT(0, "A duel, eh?\n\nWell, all right. It'll be a\nnice change of pace.\n\n")
  LANGUAGE_TEXT(1, "Un duel, hein ?\nEh bien, d'accord.\n\nCa me changera\nles id\xe9es.\n\n")
  LANGUAGE_TEXT(2, "Ein Duell, was?\n\nNa gut. Das ist\nwenigstens Abwechslung.\n\n")
  LANGUAGE_TEXT(3, "Un duello, eh?\n\nBe', perch\xe9 no?\nCos\xec mi distraggo un po'.\n\n")
  LANGUAGE_TEXT(4, "Un duelo, \xbfeh?\n\nBueno, vale.\nSer\xe1 un cambio.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(101)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2680, map_34_state_04_08EC2680, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(244)
  LANGUAGE_TEXT(0, "Hey, that was fun!\n\nBut it's about time I got\nback to work.\n\n")
  LANGUAGE_TEXT(1, "Eh bien, c'\xe9tait marrant !\n\nMais maintenant, je dois\nretourner travailler.\n\n")
  LANGUAGE_TEXT(2, "Hey, das hat Spa\xdf\ngemacht!\n\nAber jetzt sollte ich wieder\nan die Arbeit zur\xfcckkehren.\n\n")
  LANGUAGE_TEXT(3, "Ehi, mi sono divertito!\n\nMa ora devo tornare\nal lavoro.\n\n")
  LANGUAGE_TEXT(4, "\xa1Bueno, hey, ha\nsido divertido!\n\nPero es hora de\nvolver al trabajo, eh.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_SERIOUS_ARCHEOLOGIST2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC268C, map_34_state_04_08EC268C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm working. Another time.\n\n")
  LANGUAGE_TEXT(1, "Je travaille, tu ne vois\npas ? Une autre fois.\n\n")
  LANGUAGE_TEXT(2, "Ich arbeite, siehst du das\nnicht? Ein andermal.\n\n")
  LANGUAGE_TEXT(3, "Sto lavorando, sai?\nFacciamo un'altra volta.\n\n")
  LANGUAGE_TEXT(4, "Estoy trabajando, \xbfeh?\nEn otra ocasi\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2698, map_34_state_04_08EC2698, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I hear Duel Monsters are\nbased on stone tablets.\n\nWeren't those tablets found\nin Egypt?\n\nWe only dig fossils here, so\nwe won't find any tablets.\n\n")
  LANGUAGE_TEXT(1, "Il para\xeet que les\nDuel Monsters\n\nviennent de ces\ntablettes en pierre.\n\nCes tablettes n'ont pas\n\xe9t\xe9 trouv\xe9es en Egypte ?\n\nIci, on ne fait que\nchercher des fossiles,\n\n\xe7a n'a donc rien \xe0 voir.\n\n")
  LANGUAGE_TEXT(2, "Ich h\xf6re, Duel Monster\nbasieren auf Steintafeln.\n\nWurden diese Tafeln nicht\nin \xc4gypten gefunden?\n\nHier graben wir nur nach\nFossilien, da spielt\n\nes also keine Rolle.\n\n")
  LANGUAGE_TEXT(3, "Ho sentito dire che Duel\nMonsters \xe8 un gioco\n\nbasato su tavolette di\npietra. Non sono state\n\ntrovate in Egitto? Qui\ncerchiamo solo fossili,\n\nquindi non ci interessa.\n\n")
  LANGUAGE_TEXT(4, "He o\xeddo que Duel\nMonsters est\xe1\n\nbasado en unas\ntablas de piedra.\n\n\xbfNo se encontraron\nesas tablas en Egipto?\n\nS\xf3lo excavamos\nf\xf3siles aqu\xed, por\n\nlo que no ha de ser\nuna preocupaci\xf3n, eh.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC26A4, map_34_state_04_08EC26A4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Nah, I'm focused on my work.\n\nI don't duel at all.\n\n")
  LANGUAGE_TEXT(1, "Non, je me concentre\nsur mon travail.\n\nPas question de\nse battre en duel.\n\n")
  LANGUAGE_TEXT(2, "N\xf6\xf6, ich konzentriere mich\nnur auf meine Arbeit.\n\nIch duelliere mich nicht.\n\n")
  LANGUAGE_TEXT(3, "No, sono concentrato\nsul mio lavoro e basta.\n\nIo non duello proprio.\n\n")
  LANGUAGE_TEXT(4, "Nah, estoy centrado en mi\ntrabajo y nada m\xe1s.\n\nNunca lucho, eh.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC26B0, map_34_state_04_08EC26B0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I wish I could unearth some\nrare fossils.\n\nActually, I'd like to find\nanything, as long as it's\n\nrare.\n\n")
  LANGUAGE_TEXT(1, "J'aimerais pouvoir trouver\ndes fossiles rares...\n\nEnfin, n'importe\nquoi de rare...\n\n")
  LANGUAGE_TEXT(2, "Ich w\xfcnschte, ich f\xe4nde ein\npaar seltene Fossilien.\n\nSofern sie selten sind, ist\nes egal, was...\n\n")
  LANGUAGE_TEXT(3, "Magari potessi trovare\ndei fossili rari! Be',\n\nqualunque rarit\xe0\nandrebbe bene, ma...\n\n")
  LANGUAGE_TEXT(4, "Me gustar\xeda desenterrar unos\nf\xf3siles raros, \xbfeh?\n\nBueno, si fuera raro,\ncasi todo servir\xeda, pero...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC26BC, map_34_state_04_08EC26BC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, I'll get in trouble if I\ngoof off too much.\n\nSorry, next time.\n\n")
  LANGUAGE_TEXT(1, "Non, je vais avoir des\nennuis si je m'arr\xeate\n\nde travailler.\n\nD\xe9sol\xe9, mon gars,\nla prochaine fois ?\n\n")
  LANGUAGE_TEXT(2, "Nein, ich bekomme \xc4rger,\nwenn ich meiner Arbeit zu\n\nlange fern bleibe. Tut mir\nLeid. Ein andermal, ja?\n\n")
  LANGUAGE_TEXT(3, "No, per me sarebbero\nguai se perdessi troppo\n\ntempo. Mi spiace, amico,\nmagari un'altra volta.\n\n")
  LANGUAGE_TEXT(4, "No, me meter\xe9 en\nproblemas si hago\n\nel tonto demasiado.\n\nLo siento, chico,\nla pr\xf3xima vez, \xbfeh?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
