#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_26_state_10: map 26 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3E60, map_26_state_10_08EA3E60, 0x08EA3E6C, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_MAI)
  LOAD_SPRITE(2, SPRITE_JEAN_CLAUDE_MAGNUM)
  PLAY_MUSIC(MUSIC_JEAN_CLAUDE_MAGNUM)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "Mai Valentine, be mine!\n"
      "Marry me!\n\n"
      "Please!\n\n"
  )
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT)
  TEXT
  (
      "Would you quit already?\n"
      "You're annoying me.\n\n"
  )
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "But if you marry me, I won't\n"
      "annoy you anymore.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "I'm a Hollywood star. I have\n"
      "my pride.\n\n"
      "I'm not leaving until you\n"
      "say yes.\n\n"
  )
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT)
  TEXT
  (
      "Listen to me, Romeo.\n\n"
      "I already have someone\n"
      "special.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "So you can give up now, Jean\n"
      "Claude.\n\n"
  )
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "Wh-who is he?\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT)
  TEXT
  (
      "That's none of your\n"
      "business.\n\n"
  )
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "You're lying, aren't you?\n"
      "You're just trying to make\n\n"
      "me leave.\n\n"
  )
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT)
  TEXT
  (
      "Er, um...\n\n"
  )
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "See! There really isn't\n"
      "anyone special!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 4, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT)
  TEXT
  (
      "Th-that's not true! There\n"
      "really is someone!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 4, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1 | OBJECT_2)
  DELAY(32)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_1)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "{BYTE_8169}...Why am I getting so\n"
      "worked up over this?{BYTE_816A}\n\n"
      "{BYTE_8169}And why do I keep thinking\n"
      "about him?{BYTE_816A}\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "...I wonder... How he's\n"
      "doing...\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(8)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "He? W-wait!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT)
  TEXT
  (
      "Would you be quiet!\n\n"
      "I'm going out. Cover for me\n"
      "as the dealer.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(8)
  MOVE_OBJECT(2, DIRECTION_DOWN, 4, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, PORTRAIT_LEFT)
  TEXT
  (
      "B-but! Wait! Mai, please!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 72)
  WALK_OBJECT_X(1, 64)
  WALK_OBJECT_Y(1, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3E6C, map_26_state_10_08EA3E6C, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 16)
  FADE_SCREEN(16)
  WARP(28, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
