#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_43_state_03: map 43 state 3 */

LOAD_SPRITE(1, SPRITE_CHEVALIER)
LOAD_SPRITE(2, SPRITE_CHEVALIER)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13)
DELAY(8)
WALK_OBJECT_X(1, 112)
DELAY(16)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Gawry nida!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(2, 8)
DELAY(16)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "Gawry nida!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_260)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "You'll go no further!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_260)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "Gawry!\n\n"
)
SET_FLAG(EVENT_FLAG_ENTERED_DUNGEON)
