#include "event_macros.h"
#include "overworld.h"

/* map_05_state_04: map 5 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08E51004, map_05_state_04_08E51004, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Let's see... Who might have\nrare cards...\n\nWho looks weak enough for me\nto beat...\n\nThere have to be suckers\naround somewhere.\n\n")
  LANGUAGE_TEXT(1, "Voyons voir... Qui pourrait\navoir des cartes rares...\n\nQui a l'air assez\nfacile \xe0 battre...\n\nIl doit bien y avoir un\nduelliste assez faible...\n\n")
  LANGUAGE_TEXT(2, "Mal sehen... Wer k\xf6nnte\nseltene Karten besitzen...\n\nWer sieht als Gegner schwach\ngenug aus...\n\nIrgendwo muss es doch solche\nDuellanten geben.\n\n")
  LANGUAGE_TEXT(3, "Vediamo... Chi potrebbe\navere le carte rare...\n\nChi sembra abbastanza\ndebole da battere... Da\n\nqualche parte ci saranno\nduellanti del genere.\n\n")
  LANGUAGE_TEXT(4, "Veamos... Qui\xe9n podr\xe1\ntener cartas raras...\n\nQui\xe9n parece lo bastante\nd\xe9bil como para vencerle...\n\nHa de haber duelistas\nas\xed en alg\xfan lado.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51010, map_05_state_04_08E51010, 0x08E5101C, 0x08E51034)
  CHECK_FLAG(121)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5101C, map_05_state_04_08E5101C, 0x08E51028, 0x08F0404C)
  LANGUAGE_TEXT(0, "If you lose, it's going to\ncost you a rare card.\n\nThose are my rules, and if\nyou don't like it, tough!\n\n")
  LANGUAGE_TEXT(1, "Si tu perds, \xe7a te\nco\xfbtera une carte rare.\n\nH\xe9, c'est ma r\xe8gle,\nalors tais-toi.\n\n")
  LANGUAGE_TEXT(2, "Wenn du verlierst, kostet\nes dich eine seltene Karte.\n\nHe, das ist meine Regel,\ndu h\xe4ltst den Mund.\n\n")
  LANGUAGE_TEXT(3, "Se perdi, mi darai\nuna carta rara.\n\nLe regole le decido io\ne tu chiudi il becco.\n\n")
  LANGUAGE_TEXT(4, "Si pierdes, te costar\xe1\nuna carta rara.\n\nHey, es mi norma y t\xfa mant\xe9n\nla boca cerrada.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(90)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51028, map_05_state_04_08E51028, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "You're not supposed to be\nstrong!\n\n")
  LANGUAGE_TEXT(1, "Tu n'es pas\ncens\xe9 \xeatre fort !\n\n")
  LANGUAGE_TEXT(2, "Es hei\xdft doch, du w\xe4rst\nnicht stark!\n\n")
  LANGUAGE_TEXT(3, "Ma tu non dovresti\nessere forte!\n\n")
  LANGUAGE_TEXT(4, "\xa1Se supone que\nno eres fuerte!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(121)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51034, map_05_state_04_08E51034, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Forget it. I'm not dueling\nyou again.\n\n")
  LANGUAGE_TEXT(1, "Oublie. Je ne me bats\nplus en duel contre toi.\n\n")
  LANGUAGE_TEXT(2, "Vergiss es. Mit dir\nduelliere ich mich nicht\n\nmehr.\n\n")
  LANGUAGE_TEXT(3, "Scordatelo. Io\nnon duello pi\xf9 con te.\n\n")
  LANGUAGE_TEXT(4, "Olv\xeddalo. No me batir\xe9\ncontigo de nuevo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51040, map_05_state_04_08E51040, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll never forget Mako\nTsunami.\n\nHe's one of the duelists who\nsaved the Town of Domino.\n\n")
  LANGUAGE_TEXT(1, "Je n'oublierai jamais\nMako Tsunami.\n\nC'est l'un des duellistes\nqui a sauv\xe9 Domino.\n\n")
  LANGUAGE_TEXT(2, "Ich werde Mako Tsunami\nnie vergessen.\n\nEr ist einer der Duellanten,\ndie Domino retteten.\n\n")
  LANGUAGE_TEXT(3, "Non scorder\xf2 mai\nMako Tsunami.\n\n\xc8 uno dei duellanti che\nhanno salvato Domino.\n\n")
  LANGUAGE_TEXT(4, "Nunca olvidar\xe9 a\nMako Tsunami.\n\nEs uno de los duelistas\nque salv\xf3 Domino.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5104C, map_05_state_04_08E5104C, 0x08E51058, 0x08E51070)
  CHECK_FLAG(122)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51058, map_05_state_04_08E51058, 0x08E51064, 0x08F0404C)
  LANGUAGE_TEXT(0, "Yes! I accept your\nchallenge!\n\n")
  LANGUAGE_TEXT(1, "Oui ! Je veux bien\nrelever ton d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Ja! Ich nehme deine Heraus-\nforderung an!\n\n")
  LANGUAGE_TEXT(3, "S\xec! Accetto la sfida!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed! \xa1Acepto tu\nreto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(91)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51064, map_05_state_04_08E51064, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "I'm not as good as Mako\nTsunami yet.\n\n")
  LANGUAGE_TEXT(1, "Mais je ne suis pas\nencore aussi bon que\n\nMako Tsunami.\n\n")
  LANGUAGE_TEXT(2, "So gut wie Mako Tsunami bin\nich zwar noch nicht ganz.\n\n")
  LANGUAGE_TEXT(3, "Non sono ancora al\nlivello di Mako Tsunami.\n\n")
  LANGUAGE_TEXT(4, "No voy a coger a\nMako Tsunami a\xfan.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(122)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E51070, map_05_state_04_08E51070, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "If you pick on me, you're no\ndifferent than the Neo\n\nGhouls.\n\n")
  LANGUAGE_TEXT(1, "Tu veux t'en prendre\n\xe0 moi.\n\nTu es vraiment diff\xe9rent\ndes Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Hast du es auf mich\nabgesehen?\n\nDarin unterscheidest du\ndich von den Neo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "Pensi di scegliere me? Sei\ndiverso dai Neo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s pensando en\ndarme la lata?\n\nEso te hace diferente\nde los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5107C, map_05_state_04_08E5107C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAKO, 0, 8)
  LANGUAGE_TEXT(0, "Sigh... I miss the sea! I'm\ngoing back home among the\n\nwaves!\n\n")
  LANGUAGE_TEXT(1, "Ahh... La mer me manque !\nJe veux y retourner !\n\n")
  LANGUAGE_TEXT(2, "Seufz... ich vermisse das\nMeer!\n\nIch kehre dorthin zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Ahim\xe8... Quanto mi manca\nil mare! Io ci torno!\n\n")
  LANGUAGE_TEXT(4, "Snif... \xa1Echo de menos el\nmar! \xa1Regresar\xe9 a \xe9l!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 61)
  WALK_OBJECT_Y(3, 0)
  SET_OBJECT_POSITION(3, 128, 96, 0)
  SET_FLAG(123)
  SET_MAP_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()
