#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_36_state_01: map 36 state 1 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EC9C0C, map_36_state_01_08EC9C0C, 0x08EC9C24, 0x08EC9C3C)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  LOAD_SPRITE(2, SPRITE_MARIK)
  LOAD_SPRITE(3, SPRITE_MILLENNIUM_ROD)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC9C24, map_36_state_01_08EC9C24, 0x08EC9C30, 0x08F0404C)
  PLAY_MUSIC(MUSIC_402)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Those drawn by the\n"
    "Millennium Item...\n\n"
    "Prove your worth among the\n"
    "sleeping ancient dragons..\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 62)
  WALK_OBJECT_Y(0, 56)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_X(14, 52)
  WALK_OBJECT_Y(14, 56)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(13, 52)
  WALK_OBJECT_Y(13, 62)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_047)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC9C30, map_36_state_01_08EC9C30, 0x08F04250, 0x08F04040)
  PLAY_MUSIC(MUSIC_402)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Impressive. Take this item.\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(3, 80, 56, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_278)
  SLIDE_OBJECT(3, 1, 14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_279)
  SHOW_OBJECT(3, 128, 96, 0, 1, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(2, 72, 56, 0, 1, 0)
  DELAY(16)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Who's calling me?\n\n"
    "I'm living a new life in\n"
    "Egypt.\n\n"
    "My job as a tombkeeper is\n"
    "over...\n\n"
    "We will meet again somewhere\n"
    "sometime...\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  DELAY(64)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Marik...\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_266)
  SCREEN_SHAKE(8)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "We have the Millennium\n"
    "Rod...\n\n"
)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Let's get outta here and\n"
    "back to Ishizu!\n\n"
)
  SET_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC9C3C, map_36_state_01_08EC9C3C, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Millennium Items are\n"
    "believed to attract each\n\n"
    "other.\n\n"
    "The Millennium Rod will lead\n"
    "you to the next one.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC9C18, map_36_state_01_08EC9C18, 0x08EC9C24, 0x08EC9C48)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC9C48, map_36_state_01_08EC9C48, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You are only allowed to duel\n"
    "me once.\n\n"
    "Did you not have to leave\n"
    "immediately?\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
