#include "event_macros.h"

/* map_29_state_05: map 29 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC8D0, map_29_state_05_08EAC8D0, 0x08EAC8DC, 0x08F0404C)
  PLAY_MUSIC(11)
  PORTRAIT(49, 0, 1)
  LANGUAGE_TEXT(0, "You're defying Master\nKeith's orders?\n\nAfter he was willing to let\nyou join him, just like old\n\ntimes!\n\n")
  LANGUAGE_TEXT(1, "Alors tu d\xe9fies les ordres\nde ma\xeetre Ken ?\n\nIl veut bien que tu\nle rejoigne,\n\ncomme dans le\nbon vieux temps !\n\n")
  LANGUAGE_TEXT(2, "Du widersetzt dich also dem\nBefehl von Meister Keith?\n\nEr ist bereit, dich wie\nfr\xfcher aufzunehmen!\n\n")
  LANGUAGE_TEXT(3, "Cos\xec, disobbedisci agli\nordini del maestro Keith?\n\nLui \xe8 disposto ad\naccoglierti tra i suoi\n\ncome ai vecchi tempi!\n\n")
  LANGUAGE_TEXT(4, "Conque \xbfdesaf\xedas las\n\xf3rdenes del amo Keith?\n\n\xa1Est\xe1 dispuesto a\ndejarte reunirte\n\ncon \xe9l, como en los\nviejos tiempos!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(15, 0, 1)
  LANGUAGE_TEXT(0, "He never treated me with\nrespect!\n\nI don't trust him!\n\n")
  LANGUAGE_TEXT(1, "Il ne traite pas\nles gens avec respect.\n\nOn ne peut pas\nlui faire confiance.\n\n")
  LANGUAGE_TEXT(2, "Er behandelt die Leute\nohne Respekt.\n\nIhm kann man nicht\ntrauen.\n\n")
  LANGUAGE_TEXT(3, "Tratta la gente senza\nalcun rispetto.\n\nNon ci si pu\xf2 fidare di lui.\n\n")
  LANGUAGE_TEXT(4, "Trata a la gente\nsin ning\xfan respeto.\n\nNo se puede\nconfiar en \xe9l.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(49, 0, 1)
  LANGUAGE_TEXT(0, "You fool! Pledge your\nallegiance to Bandit Keith!\n\nIf you do, he's willing to\nlet you use all the rare\n\ncards you want.\n\n")
  LANGUAGE_TEXT(1, "Esp\xe8ce d'imb\xe9cile.\nFais serment d'all\xe9geance\n\n\xe0 Ken. Il te laissera\nutiliser toutes les cartes\n\nrares que tu voudras.\n\n")
  LANGUAGE_TEXT(2, "Du Dickkopf. Schw\xf6r\nKeith die Treue.\n\nEr wird dir erlauben, alle\nseltenen Karten zu\n\nbenutzen, die du willst.\n\n")
  LANGUAGE_TEXT(3, "Idiota cocciuto! Prometti\ndi essere fedele a Keith.\n\nLui ti far\xe0 usare tutte le\ncarte rare che vorrai.\n\n")
  LANGUAGE_TEXT(4, "T\xfa, loco cabezota.\nJura tu lealtad a Keith.\n\nTe dejar\xe1 usar todas las\ncartas raras que quieras.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(15, 0, 1)
  LANGUAGE_TEXT(0, "I'm not afraid of him\nanymore!\n\n")
  LANGUAGE_TEXT(1, "Je ne suis plus\ncomme \xe7a !\n\n")
  LANGUAGE_TEXT(2, "Ich bin nicht mehr so!\n\n")
  LANGUAGE_TEXT(3, "Io sono cambiato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ya no soy as\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 56)
  WALK_OBJECT_X(13, 46)
  WALK_OBJECT_X(14, 46)
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 4)
  DELAY(8)
  PORTRAIT(49, 0, 1)
  LANGUAGE_TEXT(0, "Tsk, the cavalry arrives!\n\nI'll take care of them\nfirst!\n\n")
  LANGUAGE_TEXT(1, "Pff, petits imb\xe9ciles !\n\nJe vais d'abord\nm'occuper d'eux !\n\n")
  LANGUAGE_TEXT(2, "Tss, was mischt ihr\neuch ein?!\n\nDie erledige ich zuerst!\n\n")
  LANGUAGE_TEXT(3, "Ecco altri idioti che\nvogliono immischiarsi!\n\nPrima mi occuper\xf2 di loro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Chss, locos\nentrometidos!\n\n\xa1Primero me\nencargar\xe9 de ellos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 66)
  DELAY(16)
  DUEL(65)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8DC, map_29_state_05_08EAC8DC, 0x08EAC8E8, 0x08F04040)
  PLAY_MUSIC(241)
  PORTRAIT(49, 0, 1)
  LANGUAGE_TEXT(0, "Grah! You'll regret this!\n\n")
  LANGUAGE_TEXT(1, "Grah ! Tu vas voir,\ntu vas le regretter !\n\n")
  LANGUAGE_TEXT(2, "Grah! Ich werde daf\xfcr sor-\ngen, dass ihr es bereut!\n\n")
  LANGUAGE_TEXT(3, "Gaah! Vedrai che te\nla far\xf2 pagare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Grah! \xa1Har\xe9\nque lo sientas!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 57)
  WALK_OBJECT_X(2, 248)
  WALK_OBJECT_Y(1, 54)
  MOVE_OBJECT(1, 1, 8, 0)
  DELAY(16)
  PORTRAIT(15, 0, 1)
  LANGUAGE_TEXT(0, "Th-thanks for saving me!\n\nHonestly, I was a little\nscared.\n\nBut you guys... Why are you\nhere?\n\n")
  LANGUAGE_TEXT(1, "Oh...\nSauv\xe9 !\n\nSinc\xe8rement,\nj'ai eu un peu peur.\n\nMais vous, les gars...\nPourquoi vous \xeates l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Oh...\nGerettet!\n\nEhrlich gesagt hatte ich\netwas Angst.\n\nAber ihr... Was macht\nihr hier?\n\n")
  LANGUAGE_TEXT(3, "Oh...\nL'ho scampata!\n\nIn tutta onest\xe0, ho\navuto un po' di paura.\n\nE voi, ragazzi...\nCome mai siete qui?\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh...!\n\xa1Salvado!\n\nEn serio, estaba\nalgo asustado.\n\nPero t\xedos...\n\xbfPor qu\xe9 est\xe1is aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8E8, map_29_state_05_08EAC8E8, 0x08EAC8F4, 0x08EAC900)
  PLAY_MUSIC(0)
  PLAY_MUSIC(702)
  PORTRAIT(15, 0, 1)
  LANGUAGE_TEXT(0, "I didn't know that was going\non in town!\n\nThe Neo Ghouls don't scare\nme anymore.\n\nI'm a much better duelist!\nI'll help you, too.\n\nI'll go to the Town of\nDomino! The Neo Ghouls\n\ndon't stand a ghost of a\nchance!\n\n")
  LANGUAGE_TEXT(1, "Je ne savais pas\nce qui se passait.\n\nLes Neo Ghouls ne\nme font plus peur.\n\nJe ne suis plus\ncomme avant.\n\nJe vais vous aider.\nJe vais aller \xe0 Domino\n\npour nous d\xe9barrasser\ndes Neo Ghouls !\n\n")
  LANGUAGE_TEXT(2, "Ich wusste davon gar\nnichts.\n\nDie Neo Ghouls machen\nmir keine Angst mehr.\n\nIch bin anders als fr\xfcher.\nIch werde euch auch helfen.\n\nIch werde nach Domino\ngehen und die Neo Ghouls\n\naus der Stadt jagen!\n\n")
  LANGUAGE_TEXT(3, "Non sapevo che stesse\nsuccedendo una cosa\n\ndel genere. I Neo Ghouls non\nmi fanno pi\xf9 paura. Non\n\nsono pi\xf9 quello di prima.\nAnch'io vi dar\xf2 una mano.\n\nAndr\xf2 a Domino e caccer\xf2\ni Neo Ghouls!\n\n")
  LANGUAGE_TEXT(4, "No sab\xeda que estaba\nocurriendo algo as\xed.\n\nLos Neo Ghouls ya\nno me asustan.\n\nNo soy como antes.\nYo tambi\xe9n os ayudar\xe9.\n\n\xa1Ir\xe9 a Domino y echar\xe9\na los Neo Ghouls!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 51)
  WALK_OBJECT_X(1, 248)
  DELAY(16)
  SET_FLAG(83)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8F4, map_29_state_05_08EAC8F4, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(0, 1, 0, 0)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Let's go find another ally!\n\n")
  LANGUAGE_TEXT(1, "Allons chercher\nun nouvel allier !\n\n")
  LANGUAGE_TEXT(2, "Suchen wir uns einen\nanderen Verb\xfcndeten!\n\n")
  LANGUAGE_TEXT(3, "Andiamo a trovare un\naltro alleato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Busquemos otro aliado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC900, map_29_state_05_08EAC900, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(0, 1, 0, 0)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Okay! Let's also get back to\nthe Town of Domino!\n\n")
  LANGUAGE_TEXT(1, "OK ! Retournons\naussi \xe0 Domino !\n\n")
  LANGUAGE_TEXT(2, "Okay! Kehren wir auch\nnach Domino zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Okay! Torniamo anche\nnoi a Domino!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien, volvamos a\nDomino tambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()
