#include "event_macros.h"
#include "overworld.h"

/* map_19_state_01: map 19 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E83A84, map_19_state_01_08E83A84, 0x08E83A9C, 0x08E83B44)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_BONZ)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83A9C, map_19_state_01_08E83A9C, 0x08E83AA8, 0x08E83AB4)
  WALK_OBJECT_Y(0, 60)
  WALK_OBJECT_X(0, 96)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 70)
  WALK_OBJECT_X(13, 102)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 70)
  WALK_OBJECT_X(14, 90)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Welcome to the Catacombs.\n\nThis is a communal\ngraveyard from long,\n\nlong ago.\n\nI'm Bonz, your tour guide.\n\nIf you'd like, I'll show you\nsights you've never seen\n\nbefore.\n\n")
  LANGUAGE_TEXT(1, "Bienvenue aux Catacombes.\n\nCe lieu est un tr\xe8s vieux\ncimeti\xe8re communautaire.\n\nJe m'appelle Bonz,\nje suis votre guide.\n\nSi vous le d\xe9sirez,\nje peux vous proposer\n\nune visite guid\xe9e.\n\n")
  LANGUAGE_TEXT(2, "Willkommen in den\nKatakomben.\n\nDies ist ein uralter\nGemeindefriedhof.\n\nIch bin Bonz, euer\nFremdenf\xfchrer.\n\nIch f\xfchre euch gerne\nherum.\n\n")
  LANGUAGE_TEXT(3, "Benvenuti nelle Catacombe.\nQuesto \xe8 un cimitero\n\ndi tanti secoli fa. Io sono\nBonz, la vostra guida.\n\nSe siete qui in visita, vi\nfar\xf2 fare un giro.\n\n")
  LANGUAGE_TEXT(4, "Bienvenidos a las\nCatacumbas.\n\nEste es un cementerio\ncomunal muy antiguo.\n\nSoy Bonz, vuestro\ngu\xeda.\n\nSi sois turistas, os\nguiar\xe9.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AA8, map_19_state_01_08E83AA8, 0x08E83AC0, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, 0)
  LANGUAGE_TEXT(0, "Man, why do we hafta\nsightsee in this spooky\n\nplace... Not that I'm\nscared!\n\n")
  LANGUAGE_TEXT(1, "Oublie, cet endroit\nest trop sinistre\n\npour une visite guid\xe9e.\n\n")
  LANGUAGE_TEXT(2, "Diesen unheimlichen Ort\nm\xf6chte ich nicht\n\nbesichtigen.\n\n")
  LANGUAGE_TEXT(3, "Niente visite turistiche\nin questo posto da brividi.\n\n")
  LANGUAGE_TEXT(4, "Olv\xeddate de turismo\nen este l\xfagubre lugar.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "What are you talking about?\nThis place is the best!\n\nIf you're not tourists, what\nbrings you here?\n\n")
  LANGUAGE_TEXT(1, "C'est un endroit\ntr\xe8s original.\n\nSi vous n'\xeates pas\ndes touristes,\n\nqu'est-ce qui vous\nam\xe8ne jusqu'ici ?\n\n")
  LANGUAGE_TEXT(2, "Es ist ein sch\xf6ner Ort.\nInteressant.\n\nAber wenn ihr keine Touris-\nten seid, was f\xfchrt euch\n\ndann hierher?\n\n")
  LANGUAGE_TEXT(3, "\xc8 un bel posto. Ci\nsi diverte sempre.\n\nSe non siete turisti,\nperch\xe9 siete qui?\n\n")
  LANGUAGE_TEXT(4, "Este es un buen sitio.\nSiempre es divertido.\n\nSi no sois turistas,\n\xbfqu\xe9 os trae por aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AC0, map_19_state_01_08E83AC0, 0x08E83ACC, 0x08E83AD8)
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You're searching for a\nMillennium Item?\n\n")
  LANGUAGE_TEXT(1, "Vous recherchez un\nObjet du mill\xe9nium ?\n\n")
  LANGUAGE_TEXT(2, "Sucht ihr einen\nMillenniumsgegenstand?\n\n")
  LANGUAGE_TEXT(3, "Cercate un Oggetto\nMillenario?\n\n")
  LANGUAGE_TEXT(4, "\xbfBusc\xe1is un Objeto del\nMilenio?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm not sure if that thing\nis a Millennium Item...\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas s\xfbr que ce\nsoit un Objet du\n\nmill\xe9nium...\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf nicht, ob es ein\nMillenniumsgegenstand\n\nist...\n\n")
  LANGUAGE_TEXT(3, "Non sono sicuro se\nquella cosa \xe8 un\n\nOggetto Millenario...\n\n")
  LANGUAGE_TEXT(4, "No estoy seguro de\nque esa cosa sea\n\nun Objeto del Milenio...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, Bonz seems to know\nsomething!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, Bonz a l'air\nd'\xeatre au courant de\n\nquelque chose !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, Bonz scheint\netwas zu wissen!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, sembra\nche Bonz sappia qualcosa!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xa1Bonz\nparece saber algo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Where is it?\nLet's duel!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}O\xf9 \xe7a ?\nBattons-nous en duel !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Wo ist es?\nDuellieren wir uns!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Dov'\xe8?\nDuelliamo!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xbfD\xf3nde est\xe1?\n\xa1Luchemos!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83ACC, map_19_state_01_08E83ACC, 0x08E83AE4, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "...I may not look like one,\nbut I'm a duelist, too.\n\n")
  LANGUAGE_TEXT(1, "... Ca ne se voit\npeut-\xeatre pas\n\nmais je suis aussi\nun duelliste.\n\n")
  LANGUAGE_TEXT(2, "... Ich sehe vielleicht\nnicht so aus, aber auch ich\n\nbin ein Duellant.\n\n")
  LANGUAGE_TEXT(3, "... Anche se non sembra,\nsono un duellante pure io.\n\n")
  LANGUAGE_TEXT(4, "... Puede que no lo\naparente, pero\n\ntambi\xe9n soy duelista.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "If you want to get my\ninfo...\n\nDuel against my ghouls!\n\n")
  LANGUAGE_TEXT(1, "Si vous voulez que je vous\ndonne des informations...\n\nIl faudra d'abord\nm'affronter en duel !\n\n")
  LANGUAGE_TEXT(2, "Wenn ihr etwas von mir\nerfahren m\xf6chtet...\n\nm\xfcsst ihr mich erst\nbesiegen!\n\n")
  LANGUAGE_TEXT(3, "Se volete ottenere\ninformazioni da me...\n\nPrima duelliamo!\n\n")
  LANGUAGE_TEXT(4, "Si quer\xe9is obtener\ninformaci\xf3n de m\xed...\n\n\xa1Luchemos primero!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AE4, map_19_state_01_08E83AE4, 0x08E83AF0, 0x08F0404C)
  LANGUAGE_TEXT(0, "I'll tell you what I know if\nyou can beat me.\n\nBut what are your chances\nagainst my powerful Neo\n\nGhost Deck!\n\n")
  LANGUAGE_TEXT(1, "Je vous le dirai si vous\narrivez \xe0 me battre.\n\nJe vais vous montrer\n\xe0 quel point mon Deck\n\nN\xe9o Fant\xf4me est\npuissant !\n\n")
  LANGUAGE_TEXT(2, "Ich sage es euch, wenn ihr\nmich schlagen k\xf6nnt.\n\nIch zeige euch, wie stark\nmein Neo-Geisterdeck ist!\n\n")
  LANGUAGE_TEXT(3, "Ve lo dir\xf2 se riuscirete\na battermi.\n\nVi far\xf2 vedere quant'\xe8\nforte il mio nuovo deck\n\ndi fantasmi!\n\n")
  LANGUAGE_TEXT(4, "Os lo dir\xe9 si pod\xe9is\nvencerme.\n\n\xa1Os mostrar\xe9 cu\xe1n fuerte es\nmi deck neofantasma!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(36)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AF0, map_19_state_01_08E83AF0, 0x08E83AFC, 0x08E83B08)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "No! I lost!\n\n")
  LANGUAGE_TEXT(1, "Ohhh... Battu !\n\n")
  LANGUAGE_TEXT(2, "Ohhh... Besiegt!\n\n")
  LANGUAGE_TEXT(3, "Ohh... Sconfitto!\n\n")
  LANGUAGE_TEXT(4, "Ohhh... \xa1Vencido!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  PLAY_MUSIC(271)
  REACTION(0, 24579)
  DELAY(8)
  WALK_OBJECT_X(4, 56)
  WALK_OBJECT_X(6, 44)
  WALK_OBJECT_X(7, 40)
  DELAY(8)
  PLAY_MUSIC(407)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Kukuku...\n\nYou said your deck's\nimproved, but it's the same\n\nlame deck as always, Bonz.\n\n")
  LANGUAGE_TEXT(1, "Kukuku...\n\nToujours le m\xeame\nDeck aussi faible, Bonz.\n\n")
  LANGUAGE_TEXT(2, "Kukuku...\n\nDas gleiche mickrige\nDeck wie eh und je, Bonz.\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\n\n\xc8 sempre lo stesso\ndeck sfornito, Bonz.\n\n")
  LANGUAGE_TEXT(4, "Kukuku...\n\nEs la misma deck mal nutrida\nde siempre, Bonz.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "B-Bandit Keith!\n\n")
  LANGUAGE_TEXT(1, "B-Bandit Ken !\n\n")
  LANGUAGE_TEXT(2, "B-Bandit Keith!\n\n")
  LANGUAGE_TEXT(3, "B-Bandit Keith!\n\n")
  LANGUAGE_TEXT(4, "\xa1B-Bandit Keith!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I've never seen so many\nlosers in one place!\n\nI've watched tougher duels\nin kindergarten!\n\n")
  LANGUAGE_TEXT(1, "Alors, je vois que les plus\nfaibles se rassemblent\n\npour jouer ensemble.\nQuel duel ennuyeux !\n\n")
  LANGUAGE_TEXT(2, "Die Schwachen tun sich\nalso zusammen und\n\nspielen h\xfcbsch und artig.\n\nSo ein laues Spiel habe ich\nseit Jahren nicht erlebt.\n\n")
  LANGUAGE_TEXT(3, "Ma che bello, vedere i\ndeboli riunirsi e giocare.\n\nDa anni non vedevo un duello\ncos\xec poco entusiasmante.\n\n")
  LANGUAGE_TEXT(4, "As\xed que los d\xe9biles\nse juntan y luchan,\n\n\xa1qu\xe9 bonito!\n\nNo he visto un duelo\ntan flojo en a\xf1os.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}I'll take you on!\nWho's behind you?{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Je te d\xe9fie !\nQui t'accompagne ?{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ich nehme an!\nWer geh\xf6rt zu deinem Team?{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Ti sfider\xf2!\nCon chi sei venuto?{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1Te reto!\n\xbfCon qui\xe9n est\xe1s?{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AFC, map_19_state_01_08E83AFC, 0x08E83B14, 0x08F04040)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Kukuku... We could duel,\nbut...\n\nI'm not in the mood. I'm\njust here to show you that\n\nI'm alive and kickin'!\n\n")
  LANGUAGE_TEXT(1, "Kukuku... On pourrait\nfaire \xe7a, mais...\n\nJe suis seulement\nvenu ici pour faire\n\n\xe0 nouveau ta\nconnaissance.\n\n")
  LANGUAGE_TEXT(2, "Kukuku... Das k\xf6nnten\nwir tun, aber...\n\nHeute wollte ich mich nur\nwieder eingew\xf6hnen.\n\n")
  LANGUAGE_TEXT(3, "Pfui...\nSi potrebbe fare, ma...\n\nOggi sono venuto solo\nper riprendere i contatti.\n\n")
  LANGUAGE_TEXT(4, "Kukuku...\nPodr\xedamos hacerlo, pero...\n\nHoy s\xf3lo he venido\na reunirme de nuevo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B14, map_19_state_01_08E83B14, 0x08E83B20, 0x08E83B2C)
  LANGUAGE_TEXT(0, "After Marik's pathetic\ndefeat, I took control of\n\nthe Ghouls and their Rare\nHunters.\n\n")
  LANGUAGE_TEXT(1, "Apr\xe8s la chute de Marik,\nj'ai repris la direction\n\ndes Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Nach Mariks Sturz habe ich\ndie Ghouls \xfcbernommen.\n\n")
  LANGUAGE_TEXT(3, "Ho preso la guida dei\nGhouls dopo la caduta di\n\n")
  LANGUAGE_TEXT(4, "Me he hecho con los Ghouls\ntras la ca\xedda de Marik.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_STRINGS, EXPRESSION_NEUTRAL, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, 0)
  DELAY(64)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The Ghouls are now reborn as\nthe Neo Ghouls!\n\nAnd I, Bandit Keith, am the\nleader of the Neo Ghouls!\n\n")
  LANGUAGE_TEXT(1, "Les Ghouls sont alors\ndevenues les Neo Ghouls.\n\nEt je suis Bandit Ken\ndes Neo Ghouls !\n\n")
  LANGUAGE_TEXT(2, "Die Ghouls sind als Neo\nGhouls wiedergeboren.\n\nIch bin Bandit Keith von den\nNeo Ghouls!\n\n")
  LANGUAGE_TEXT(3, "Marik. I Ghouls ora sono\ndiventati i Neo Ghouls.\n\nRicordami come Bandit\nKeith dei Neo Ghouls!\n\n")
  LANGUAGE_TEXT(4, "Los Ghouls han renacido\ncomo los Neo Ghouls.\n\n\xa1Recu\xe9rdame como Bandit\nKeith de los Neo Ghouls!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(5, 48)
  DELAY(16)
  MOVE_OBJECT(4, 1, 0, 0)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Master Keith...\n\nWe have obtained the\ninformation you seek...\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Ken...\n\nNous avons obtenu\ndes renseignements\n\nsur ce que vous\nrecherchiez...\n\n")
  LANGUAGE_TEXT(2, "Meister Keith...\n\nWir haben Informationen\nzu dem, was Sie suchen...\n\n")
  LANGUAGE_TEXT(3, "Maestro Keith...\nAbbiamo ottenuto\n\ninformazioni su ci\xf2\nche cercate...\n\n")
  LANGUAGE_TEXT(4, "Amo Keith...\n\nHemos obtenido informaci\xf3n\nsobre lo que busca...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "So that's the key item for\ngetting the Egyptian God\n\nCards...\n\nKukuku... With this info,\nI've earned the right to\n\njoin the game...\n\n")
  LANGUAGE_TEXT(1, "L'objet cl\xe9 pour obtenir\nles cartes de dieux...\n\nKukuku... J'ai m\xe9rit\xe9\nde participer au jeu...\n\n")
  LANGUAGE_TEXT(2, "Der Gegenstand, den wir\nf\xfcr die G\xf6tterkarten\n\nben\xf6tigen...\n\nKukuku... Ich habe mir die\nTeilnahme verdient...\n\n")
  LANGUAGE_TEXT(3, "La chiave per ottenere\nle carte divine...\n\nEbbene... Mi sono\nguadagnato il diritto\n\ndi unirmi al gioco...\n\n")
  LANGUAGE_TEXT(4, "El objeto clave para obtener\nlas cartas de los dioses...\n\nKukuku... Me he\nganado el derecho\n\nde unirme al juego...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}You want the God Cards?\nJoin the game?{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Cart. de dieux? Pourquoi?\nParticiper au jeu?{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}G\xf6tterkarten? Warum?\nAm Spiel teilnehmen?{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Carte divine? Perch\xe9?\nUnirti al gioco?{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xbfCartas divinas? \xbfY eso?\n\xbfUnirse al juego?{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B20, map_19_state_01_08E83B20, 0x08E83B38, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You know why!\n\nI need 'em to thrash that\narrogant punk!\n\nI'll do anything, and I mean\nanything, to beat him!\n\n")
  LANGUAGE_TEXT(1, "Vous savez bien pourquoi !\n\nJe vais r\xe9duire ce petit\narrogant en bouillie !\n\nJe ferais tout pour avoir\ncette chance !\n\n")
  LANGUAGE_TEXT(2, "Ihr wisst schon warum!\n\nIch werde diesen arroganten\nWitzbold erledigen!\n\nF\xfcr diese Gelegenheit w\xfcrde\nich alles geben!\n\n")
  LANGUAGE_TEXT(3, "Sapete bene perch\xe9!\n\nBatter\xf2 quella\nmassa di arroganti!\n\nFar\xf2 di tutto per\naverne l'occasione!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vosotros sab\xe9is\npor qu\xe9!\n\n\xa1Voy a destrozar a esa\nescoria arrogante!\n\n\xa1Har\xe9 lo que sea para\nconseguir esa oportunidad!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B38, map_19_state_01_08E83B38, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll let you in on a little\nsecret.\n\nYou won't find what you're\nlooking for here.\n\nSee you losers around.\n\nKukuku...\n\n")
  LANGUAGE_TEXT(1, "Avant de partir, je vais\nvous confier un secret.\n\nCe n'est pas ici que vous\ntrouveezs ce que vous\n\ncherchez.\nOK, \xe0 bient\xf4t.\n\nKukuku...\n\n")
  LANGUAGE_TEXT(2, "Bevor wir gehen, verrate ich\neuch ein kleines Geheimnis.\n\nIhr werdet das Gesuchte hier\nnicht finden.\n\nNa, bis sp\xe4ter.\n\nKukuku...\n\n")
  LANGUAGE_TEXT(3, "Prima che ce ne andiamo,\nvi dir\xf2 un piccolo segreto.\n\nQui non troverete quello\nche cercate.\n\nBe', ci si vede.\n\nEheheheh...\n\n")
  LANGUAGE_TEXT(4, "Os dir\xe9 un secreto\nantes de que os vay\xe1is.\n\nNo encontrar\xe9is lo que\nbusc\xe1is aqu\xed.\n\nBueno, nos vemos.\n\nKukuku...\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(4, 248)
  WALK_OBJECT_X(6, 248)
  WALK_OBJECT_X(7, 248)
  WALK_OBJECT_X(5, 248)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_DEFEATED_BONZ)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B2C, map_19_state_01_08E83B2C, 0x08E83B38, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Heh, it's not fair that you\nrunts get all the fun.\n\nWe want to take part, too.\nOh, and another thing...\n\nI'll do anything to thrash\nthat arrogant punk!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, ce n'est pas juste que\nvous soyez le seul \xe0 vous\n\namuser. Laissez-nous aussi\nparticiper. En plus, j'ai\n\naussi m\xe9rit\xe9 de donner\nune bonne le\xe7on \xe0 ce\n\npetit arrogant !\n\n")
  LANGUAGE_TEXT(2, "He, ich will auch meinen\nSpa\xdf haben.\n\nWir wollen auch teilnehmen.\nUnd noch etwas...\n\nIch habe das Recht, diesen\narroganten Abschaum\n\nzu schlagen!\n\n")
  LANGUAGE_TEXT(3, "Non \xe8 mica giusto che vi\ndivertiate solo voi.\n\nFate partecipare anche noi.\nE poi c'\xe8 dell'altro...\n\nHo il diritto di battere\nquella massa di arroganti!\n\n")
  LANGUAGE_TEXT(4, "Eh, no es justo que s\xf3lo os\ndivirt\xe1is vosotros.\n\nParticipemos tambi\xe9n.\nY otra cosa...\n\n\xa1Tengo derecho a\ndar una paliza a esa\n\nescoria arrogante!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B08, map_19_state_01_08E83B08, 0x08E83B14, 0x08F04040)
  PORTRAIT(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Oops, I forgot to introduce\nyou to my crew.\n\n")
  LANGUAGE_TEXT(1, "Oh, j'ai oubli\xe9 de te\npr\xe9senter \xe0 mon gang.\n\n")
  LANGUAGE_TEXT(2, "Uuups, ich habe dir noch\ngar nicht mein Team\n\nvorgestellt.\n\n")
  LANGUAGE_TEXT(3, "Oh, dimenticavo di\npresentarti i miei amici.\n\n")
  LANGUAGE_TEXT(4, "Vaya, olvid\xe9 presentarte\na mi panda.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AD8, map_19_state_01_08E83AD8, 0x08E83AE4, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I see you have the heart of\na duelist.\n\nI accept your duel!\n\n")
  LANGUAGE_TEXT(1, "Vous savez parler\n\xe0 un duelliste.\n\nJ'accepte votre d\xe9fi\nen duel.\n\n")
  LANGUAGE_TEXT(2, "Ihr versteht die Psyche\nvon Duellanten.\n\nIch nehme die Herausfor-\nderung an.\n\n")
  LANGUAGE_TEXT(3, "Sapete bene cosa fa\nscattare un duellante.\n\nAccetto la vostra sfida\na duello.\n\n")
  LANGUAGE_TEXT(4, "Vosotros sab\xe9is lo que\nmueve a un duelista.\n\nAcepto vuestro reto de\nduelo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83AB4, map_19_state_01_08E83AB4, 0x08E83AC0, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Then what brings you here?\n\n")
  LANGUAGE_TEXT(1, "Alors, qu'est-ce qui\nvous am\xe8ne jusqu'ici ?\n\n")
  LANGUAGE_TEXT(2, "Was f\xfchrt euch dann\nhierher?\n\n")
  LANGUAGE_TEXT(3, "Allora perch\xe9 siete qui?\n\n")
  LANGUAGE_TEXT(4, "Entonces, \xbfqu\xe9 os\ntrae por aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83B44, map_19_state_01_08E83B44, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Bandit Keith said you won't\nfind anything here...\n\n")
  LANGUAGE_TEXT(1, "Ken a dit que ce n'est pas\nici que vous trouverez ce\n\n")
  LANGUAGE_TEXT(2, "Keith sagte, dass ihr das\nGesuchte hier nicht finden\n\n")
  LANGUAGE_TEXT(3, "Keith ha detto che non\ntroverete qui quello che\n\n")
  LANGUAGE_TEXT(4, "Keith dijo que no\nencontrar\xe9is lo que\n\nbusc\xe1is aqu\xed...\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "But there's a hidden chamber\nin the back.\n\n")
  LANGUAGE_TEXT(1, "que vous cherchez.\n\nMais il y a une pi\xe8ce\nsecr\xe8te \xe0 l'arri\xe8re.\n\n")
  LANGUAGE_TEXT(2, "werdet... Aber hinten gibt\nes eine Geheimkammer.\n\n")
  LANGUAGE_TEXT(3, "cercate... Ma sul retro\nc'\xe8 una camera segreta.\n\n")
  LANGUAGE_TEXT(4, "Pero hay una c\xe1mara\nsecreta detr\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I bet Bandit Keith's gang\ncouldn't get in.\n\nIt's over here.\n\n")
  LANGUAGE_TEXT(1, "Je parie que Ken et sa bande\nn'ont pas r\xe9ussi \xe0 entrer.\n\nC'est par l\xe0.\n\n")
  LANGUAGE_TEXT(2, "Keiths Team passte\nbestimmt nicht hinein.\n\nDie Kammer ist hier.\n\n")
  LANGUAGE_TEXT(3, "Scommetto che la\nbanda di Keith non\n\n\xe8 riuscita a entrarci.\n\xc8 da questa parte.\n\n")
  LANGUAGE_TEXT(4, "Apuesto algo a que la panda\nde Keith no podr\xeda entrar.\n\nEst\xe1 por aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 108)
  WALK_OBJECT_Y(1, 64)
  WALK_OBJECT_X(1, 128)
  SET_FLAG(EVENT_FLAG_BONZ_SAID_THERE_IS_A_HIDDEN_CHAMBER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E83A90, map_19_state_01_08E83A90, 0x08E83A9C, 0x08E83B44)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_BONZ)
  FALLTHROUGH()
END_EVENT_SCRIPT()
