#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_33_state_05: map 33 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EBEBE0, map_33_state_05_08EBEBE0, 0x08EBEBEC, 0x08EBEBF8)
  LOAD_SPRITE(1, SPRITE_PARADOX)
  PLAY_MUSIC(MUSIC_410)
  DELAY(16)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(1, 60, 68, 0, 1, 0)
  DELAY(64)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What took you so long?",
      "However, you've passed the challenges so far.",
      "Along the way, you have been given cards.",
      "Do you understand what they represent?"
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBEC, map_33_state_05_08EBEBEC, 0x08EBEC04, EVENT_NOP)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Ah! Good, good! Good for you!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC04, map_33_state_05_08EBEC04, 0x08EBEC10, 0x08EBEC1C)
  TEXT(
      "Fine. Then answer my questions.",
      "Which card should come first?"
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Celtic Guardian\nKuriboh{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC10, map_33_state_05_08EBEC10, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "That isn't right, is it?")
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  WARP(LOCATION_CHINA_GREAT_WALL_ENTRANCE, 7, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC1C, map_33_state_05_08EBEC1C, 0x08EBEC28, 0x08EBEC40)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Ah, good! You seem to understand.",
      "Then which card should come fifth?"
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Curse of Dragon\nGiant Soldier of Stone{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC28, map_33_state_05_08EBEC28, 0x08EBEC4C, 0x08EBEC34)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Well done! You seem to really understand.")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Oh, I get it. The cards we received were in sequence.",
      "They were in the order of their levels."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Kuriboh's level one, so it came first.",
      "Curse of Dragon came last because it's level five.",
      "That's what we had to figure out, right,",
      "{PLAYER}?"
  )
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You still haven't passed all my tests.",
      "You claim to be a duelist. Therefore, we shall duel."
  )
  DUEL(DUELIST_PARADOX_083)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC4C, map_33_state_05_08EBEC4C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_410)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hmm... I haven't dueled for so long my instincts are",
      "rusty."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Making excuses? Some sage.")
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "...Oh well.",
      "I will grant your wish.",
      "Pegasus is on his island.",
      "The island is cloaked by a magical barrier.",
      "I shall extinguish that barrier for you.",
      "Hah!"
  )
  PLAY_MUSIC(MUSIC_331)
  SPECIAL(0)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "That is all I can do to help you.",
      "I'm afraid the rest is entirely up to you.",
      "The hope of the world rests with you..."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  DELAY(32)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "Wh-what? He disappeared?")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "What a strange old man.")
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO, "Strange? Freaktacular, I'd say. Let's get outta here.")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Yes, let's go to Pegasus's island, {PLAYER}!")
  SET_FLAG(EVENT_FLAG_DEFEATED_PARADOX)
  SET_FLAG(EVENT_FLAG_UNLOCKED_PEGASUS_ISLAND)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC34, map_33_state_05_08EBEC34, 0x08F0404C, EVENT_NOP)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEC40, map_33_state_05_08EBEC40, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What's that? You don't know?",
      "That's the wrong card."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  OBJECT_EFFECT(OBJECT_0 | OBJECT_13 | OBJECT_14, OBJECT_EFFECT_TELEPORT)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FADE_SCREEN(4)
  WARP(LOCATION_CHINA_GREAT_WALL_ENTRANCE, 7, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBF8, map_33_state_05_08EBEBF8, 0x08EBEC04, EVENT_NOP)
  TALK(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Don't disappoint me.",
      "At least pretend that you know!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
