#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_16_state_06: map 16 state 6 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08E7DFB4, map_16_state_06_08E7DFB4, 0x08E7DFCC, 0x08E7DFE4)
  LOAD_SPRITE(1, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(2, SPRITE_DUEL_EXPRESS_CONDUCTOR)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFCC, map_16_state_06_08E7DFCC, 0x08E7DFD8, 0x08F0404C)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I won't let you reach Master\n"
    "Keith easily!\n\n"
)
  DUEL(DUELIST_NEO_GHOUL_072)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFD8, map_16_state_06_08E7DFD8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Master Keith, please forgive\n"
    "me!\n\n"
)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_SHAKE_SCREEN)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(8)
  WALK_OBJECT_X(2, 108)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  TEXT
  (
      "Th-the train! It's moving!\n\n"
      "The Neo Ghouls must have\n"
      "taken over the controls.\n\n"
      "But as the conductor...\n\n"
      "It's my job to perform my\n"
      "duties.\n\n"
      "Our next and only stop is\n"
      "the Egypt Exhibition.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFE4, map_16_state_06_08E7DFE4, 0x08F04040, 0x08F04040)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "...\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFC0, map_16_state_06_08E7DFC0, 0x08E7DFCC, 0x08E7DFE4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFF0, map_16_state_06_08E7DFF0, 0x08E7DFFC, 0x08E7E008)
  CHECK_FLAG(EVENT_FLAG_SHAKE_SCREEN)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFFC, map_16_state_06_08E7DFFC, 0x08F04040, 0x08F04040)
  TEXT
  (
      "Wh-what is happening?\n\n"
      "The Neo Ghouls have\n"
      "commandeered the train!\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7E008, map_16_state_06_08E7E008, 0x08F04040, 0x08F04040)
  TEXT
  (
      "The Neo Ghouls have\n"
      "commandeered this train.\n\n"
      "What will become of us?\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
