#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_05: map 51 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EE3E3C, map_51_state_05_08EE3E3C, 0x08EE3E60, 0x08EE3EB4)
  LOAD_SPRITE(1, SPRITE_MAKO)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_MAKO_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E60, map_51_state_05_08EE3E60, 0x08EE3E6C, 0x08EE3E9C)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(1, 60, 48, 0, 1, 0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MAKO3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E6C, map_51_state_05_08EE3E6C, 0x08EE3E78, 0x08EE3E84)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_MAKO_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E78, map_51_state_05_08EE3E78, 0x08EE3E90, 0x08EE401C)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You should learn about the depths of a duelist's soul.",
      "I'll show you the dark depths of my spirit...",
      "Darker than the deepest trenches of the sea!"
  )
  DUEL(DUELIST_MAKO_116)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E90, map_51_state_05_08EE3E90, 0x08EE3FEC, EVENT_NOP)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "So you think you've won?",
      "If you think that's enough to beat me...",
      "Then, you'll be stuck here forever!"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_MAKO_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E84, map_51_state_05_08EE3E84, 0x08EE3E90, 0x08EE401C)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You can come back as often as you like.",
      "It won't make a difference.",
      "You can never light the darkness in my heart!"
  )
  DUEL(DUELIST_MAKO_116)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E9C, map_51_state_05_08EE3E9C, 0x08EE3EA8, 0x08EE401C)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Witness the darkest depths of my dueling spirit!")
  DUEL(DUELIST_MAKO_116)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3EA8, map_51_state_05_08EE3EA8, 0x08EE3EB4, EVENT_NOP)
  TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I... I lost...",
      "A light pierced the dark depths of the sea..."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_393)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  DELAY(8)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(SPRITE_CHEVALIER, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_MAKO_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3EB4, map_51_state_05_08EE3EB4, EVENT_NOP, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_GOT_PAST_DARK_MAKO_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E48, map_51_state_05_08EE3E48, 0x08EE3E3C, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E54, map_51_state_05_08EE3E54, 0x08EE3E3C, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FF8, map_51_state_05_08EE3FF8, EVENT_NOP, EVENT_NOP)
  CLEAR_FLAG(232)
  WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 4, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
