#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_07: map 23 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E953A8, map_23_state_07_08E953A8, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_BANDIT_KEITH)
  LOAD_SPRITE(2, SPRITE_ISHIZU)
  LOAD_SPRITE(3, SPRITE_ATEM)
  SHOW_OBJECT(13, 68, 58, 0, 0, 0)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(3, 68, 50, 0, 1, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_401)
  TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_RIGHT, "It's been a long time, partner.")
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY,
      "My other self...",
      "I... I thought I'd never see you again."
  )
  TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_RIGHT,
      "Never forget that no matter what, we're always",
      "together."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, "Right!")
  TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_RIGHT, "Okay, partner! Let's get the Egyptian God Card back!")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_301)
  WALK_OBJECT_Y(3, 56)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  FADE_SCREEN(2)
  CLEAR_FLAG(239)
  WARP(LOCATION_EGYPT_EXHIBITION_MILLENNIUM_GUARDIAN, 9, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95474, map_23_state_07_08E95474, EVENT_NOP, EVENT_NOP)
  TEXT("...")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95468, map_23_state_07_08E95468, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'm sorry about this... Let's exit.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
