#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_47_state_02: map 47 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EDB084, map_47_state_02_08EDB084, 0x08EDB090, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_ISHIZU)
  LOAD_SPRITE(2, SPRITE_SETO)
  LOAD_SPRITE(3, SPRITE_ATEM)
  LOAD_SPRITE(4, SPRITE_JOEY)
  LOAD_SPRITE(5, SPRITE_MOKUBA)
  SET_OBJECT_POSITION(0, 8, 10, 0)
  WALK_OBJECT_X(0, 20)
  DELAY(32)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_1 | OBJECT_2 | OBJECT_3 | OBJECT_4 | OBJECT_5)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_322)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_KAIBA_CORP_HELICOPTER)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, "Hey! Everyone! Over here!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  HIDE_PORTRAIT()
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDB090, map_47_state_02_08EDB090, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(16)
  FADE_SCREEN(16)
  CLEAR_FLAG(247)
  WARP(LOCATION_KAIBACORP, 14, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
