#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_18_state_03: map 18 state 3 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08E80B2C, map_18_state_03_08E80B2C, 0x08E80B38, 0x08E80B44)
  LOAD_SPRITE(1, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(2, SPRITE_DUEL_EXPRESS_CONDUCTOR)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You must be pretty good to get this far!",
      "But I'm warning you, I'm much tougher than the other",
      "guys!"
  )
  DUEL(DUELIST_NEO_GHOUL_074)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80B38, map_18_state_03_08E80B38, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_236)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL3)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "H-how dare you...")
  PLAY_MUSIC(SOUND_NONE)
  PLAY_MUSIC(MUSIC_235)
  CLEAR_FLAG(247)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  DELAY(16)
  WALK_OBJECT_X(2, 112)
  TALK(PORTRAIT_NONE,
      "We have arrived!",
      "Last stop, the Egypt Exhibition!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 128)
  SET_MAP_MUSIC(232)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80B44, map_18_state_03_08E80B44, 0x08F0404C, EVENT_NOP)
  CLEAR_FLAG(99)
  CLEAR_FLAG(247)
  CLEAR_FLAG(100)
  FALLTHROUGH()
END_EVENT_SCRIPT()
