#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_17_state_01: map 17 state 1 */

LOAD_SPRITE(1, SPRITE_PANIK)
WALK_OBJECT_X(0, 92)
WALK_OBJECT_X(13, 102)
WALK_OBJECT_Y(13, 46)
MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
WALK_OBJECT_X(14, 102)
PLAY_MUSIC(MUSIC_414)
PORTRAIT(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Ha ha ha... You'll go no\n"
    "further.\n\n"
)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_2 | OBJECT_3)
WALK_OBJECT_X(1, 48)
PORTRAIT(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Ha ha ha... My name is\n"
    "PaniK.\n\n"
    "The Millennium Items will\n"
    "never be yours!\n\n"
)
SET_FLAG(EVENT_FLAG_DARKEN_SCREEN)
FADE_SCREEN(2)
WARP(LOCATION_DUEL_EXPRESS_CARRIAGE_MIDDLE, 7, 2, 0)
