#include "event_macros.h"
#include "overworld.h"

/* map_12_state_06: map 12 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F024, map_12_state_06_08E6F024, 0x08E6F018, 0x08E6F06C)
  CHECK_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F018, map_12_state_06_08E6F018, 0x08E6F03C, 0x08E6F054)
  CHECK_FLAG(78)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F03C, map_12_state_06_08E6F03C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This is Kaiba Corporation.\n\n")
  LANGUAGE_TEXT(1, "Nous sommes de la\nKaiba Corporation.\n\n")
  LANGUAGE_TEXT(2, "Hier ist die Kaiba\nCorporation.\n\n")
  LANGUAGE_TEXT(3, "Questa \xe8 la Kaiba\nCorporation.\n\n")
  LANGUAGE_TEXT(4, "Aqu\xed Kaiba Corporation.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F054, map_12_state_06_08E6F054, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Master Mokuba protects\nKaibaCorp, and I protect\n\nhim!\n\n")
  LANGUAGE_TEXT(1, "Je prot\xe8ge\nMa\xeetre Mokuba\n\nqui lui-m\xeame prot\xe8ge\nla Kaiba Corporation !\n\n")
  LANGUAGE_TEXT(2, "Ich sch\xfctze Meister Mokuba,\nder die Kaiba Corp.\n\nbewahrt!\n\n")
  LANGUAGE_TEXT(3, "Proteggo il maestro Mokuba,\nche protegge la Kaiba Corp!\n\n")
  LANGUAGE_TEXT(4, "\xa1Protejo al amo Mokuba\nque protege Kaiba Corp!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F06C, map_12_state_06_08E6F06C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I guess things have calmed\ndown for now.\n\nBut, please stay safe and\nkeep your guard up.\n\n")
  LANGUAGE_TEXT(1, "Je crois que les choses\nse sont calm\xe9es.\n\nMais restons cependant\nvigilants.\n\n")
  LANGUAGE_TEXT(2, "Die Lage hat sich wohl\nerst einmal beruhigt.\n\nDennoch sollten wir auf\nder Hut bleiben.\n\n")
  LANGUAGE_TEXT(3, "Per ora, le cose sembrano\nessersi sistemate. Ma\n\nnon bisogna abbassare\nla guardia.\n\n")
  LANGUAGE_TEXT(4, "Sospecho que las cosas se\nhan calmado por ahora.\n\nPero, no podemos\nbajar la guardia.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F030, map_12_state_06_08E6F030, 0x08E6F048, 0x08E6F060)
  CHECK_FLAG(78)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F048, map_12_state_06_08E6F048, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't have time to waste\non you kids.\n\n")
  LANGUAGE_TEXT(1, "Nous n'avons pas\nde temps \xe0 perdre\n\navec des gens\ncomme vous.\n\n")
  LANGUAGE_TEXT(2, "Ich kann meine Zeit nicht\nmit jemandem wie euch\n\nverschwenden.\n\n")
  LANGUAGE_TEXT(3, "Non ho tempo da perdere\ncon gente come voi.\n\n")
  LANGUAGE_TEXT(4, "No tengo el tiempo para\nperderlo con seres\n\ncomo vosotros.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F060, map_12_state_06_08E6F060, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "If you have time to duel\nagainst me, then duel the\n\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "Si vous avez du temps\npour m'affronter en duel,\n\naffrontez donc\nles Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Wenn ihr Zeit f\xfcr ein Duell\nhabt, fragt doch die\n\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "Se avete il tempo di\nduellare con me, fatelo\n\ncon i Neo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "Si ten\xe9is tiempo de retarme,\nhacedlo con los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F084, map_12_state_06_08E6F084, 0x08E6F078, 0x08E6F0B4)
  CHECK_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F078, map_12_state_06_08E6F078, 0x08E6F090, 0x08E6F0A8)
  CHECK_FLAG(79)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F090, map_12_state_06_08E6F090, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Seto's Obelisk card turned\ninto stone.\n\n")
  LANGUAGE_TEXT(1, "La carte Ob\xe9lisk de\ngrand fr\xe8re a \xe9t\xe9\n\ntransform\xe9e en pierre.\n\n")
  LANGUAGE_TEXT(2, "Die Obelisk-Karte meines\ngro\xdfen Bruders wurde\n\nversteinert.\n\n")
  LANGUAGE_TEXT(3, "La carta Obelisco di\nmio fratello si \xe8\n\ntramutata in pietra.\n\n")
  LANGUAGE_TEXT(4, "La carta Obelisk\nde gran hermano\n\nse ha vuelto de piedra.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0A8, map_12_state_06_08E6F0A8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My duty is to protect\nKaibaCorp.\n\nMy big brother left me in\ncharge, and I won't fail\n\nhim!\n\n")
  LANGUAGE_TEXT(1, "Je dois prot\xe9ger\nla Kaiba Corporation.\n\nMon grand fr\xe8re m'a\nconfi\xe9 cette t\xe2che.\n\n")
  LANGUAGE_TEXT(2, "Ich werde die Kaiba Corp.\nsch\xfctzen.\n\nMein gro\xdfer Bruder hat mir\ndas Kommando \xfcbertragen.\n\n")
  LANGUAGE_TEXT(3, "Protegger\xf2 la Kaiba\nCorporation.\n\nMio fratello mi ha\nincaricato di farlo.\n\n")
  LANGUAGE_TEXT(4, "Voy a proteger Kaiba\nCorporation.\n\nMi gran hermano\nme dej\xf3 al cargo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0B4, map_12_state_06_08E6F0B4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Seto left to meet the leader\nof the Neo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re est all\xe9 voir\nle boss des Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder besucht\nden Chef der Neo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello \xe8 andato a\nincontrare il capo dei\n\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "Gran hermano ha ido\na ver al jefe de los\n\nNeo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F09C, map_12_state_06_08E6F09C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm too busy to play with\nyou.\n\n")
  LANGUAGE_TEXT(1, "Je suis bien\ntrop occup\xe9\n\npour perdre du\ntemps avec toi.\n\n")
  LANGUAGE_TEXT(2, "Ich habe zu viel zu tun,\nals dass ich mich mit\n\ndir befassen k\xf6nnte.\n\n")
  LANGUAGE_TEXT(3, "Ho troppo da fare per\nperdere tempo con te.\n\n")
  LANGUAGE_TEXT(4, "Estoy demasiado\nocupado para hacer\n\nel tonto contigo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0C0, map_12_state_06_08E6F0C0, 0x08E6F0CC, 0x08E6F0D8)
  PLAY_MUSIC(405)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I figured you'd come.\n\nYou're here to see about\nObelisk the Tormentor.\n\nYou want to know if it's\nturned into stone, right?\n\n")
  LANGUAGE_TEXT(1, "Je pensais que\nvous viendriez.\n\nVous \xeates l\xe0 \xe0 propos\nd'Ob\xe9lisk, le Bourreau.\n\nVous voulez savoir si la\ncarte a \xe9t\xe9 transform\xe9e en\n\npierre, c'est bien \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Ich dachte mir schon,\ndass ihr kommen w\xfcrdet.\n\nIhr wollt nach Obelisk,\ndem Peiniger, schauen.\n\nIhr wollt wissen, ob er auch\nversteinert ist, stimmt's?\n\n")
  LANGUAGE_TEXT(3, "Immaginavo che sareste\nvenuti. Siete qui per avere\n\nnotizie di Obelisco del\nTiranno. Volete sapere se\n\nsi \xe8 tramutato in pietra,\ndico bene?\n\n")
  LANGUAGE_TEXT(4, "Supon\xeda que vendr\xedais.\n\nEst\xe1is aqu\xed para saber\nsobre Obelisk el\n\nAtormentador.\n\nQuer\xe9is saber si se ha\nvuelto de piedra, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0CC, map_12_state_06_08E6F0CC, 0x08E6F0E4, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "You think some stone magic\ntrick is going to make me\n\nbelieve in your crazy mumbo\njumbo?\n\nWhat do you take me for!\nI don't get fooled that\n\neasily!\n\nAnd now you want me to see\nIshizu?\n\n")
  LANGUAGE_TEXT(1, "Vous croyiez donc que\nces trucs surnaturels\n\nm'int\xe9ressaient ?\n\nPour qui me prenez-vous ?\nJe suis Kaiba Seto !\n\nJe dois donc\nvous accompagner\n\nsagement pour\naller voir Ishizu ?\n\n")
  LANGUAGE_TEXT(2, "Ich soll also bei euren\nokkulten Narreteien\n\nmitmachen?\n\nWas denkt ihr eigentlich von\nmir? Ich bin Kaiba Seto!\n\nIch soll euch pflichtbewusst\nzu Ishizu folgen?\n\n")
  LANGUAGE_TEXT(3, "Cos\xec vi aspettate che mi\nunisca alla vostra\n\nmisteriosa buffonata? Mi\nprendete in giro? Sono\n\nKaiba Seto, io!\n\nE io dovrei obbedire e\nvenire con voi da Ishizu?\n\n")
  LANGUAGE_TEXT(4, "As\xed que \xbfesper\xe1is que\nme una a vuestras\n\npayasadas ocultistas?\n\n\xbfCon qui\xe9n cre\xe9is que\nhabl\xe1is?\n\n\xa1Yo soy Kaiba Seto!\n\n\xbfVoy a obedecer e ir\xe9 con\nvosotros a ver a Ishizu?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Humph. I don't think so.\n\nI want nothing to do with\nyou losers.\n\nI'll find out who did this\nto Obelisk the Tormentor on\n\nmy own!\n\n")
  LANGUAGE_TEXT(1, "Pff !\nC'est ridicule.\n\nJe n'ai rien \xe0 voir avec\nces superstitions !\n\nMais je vais quand\nm\xeame r\xe9soudre\n\nl'\xe9nigme qui se\ncache derri\xe8re cela.\n\n")
  LANGUAGE_TEXT(2, "Hmph. L\xe4cherlich!\n\nIch habe mit euren \xfcber-\nnat\xfcrlichen Spinnereien\n\nnichts am Hut.\n\nAber ich werde dem billigen\nTrick, der hinter dieser\n\nAngelegenheit steckt, auf\ndie Schliche kommen.\n\n")
  LANGUAGE_TEXT(3, "Ma non farmi ridere! \xc8\nridicolo. Non voglio avere\n\na che fare con la vostra\nidiozia soprannaturale.\n\nMa sistemer\xf2 questa\nstupida faccenda.\n\n")
  LANGUAGE_TEXT(4, "Vaya. \xa1Qu\xe9 rid\xedculo!\nNo quiero tener nada\n\nque ver con vuestra\nidiotez sobrenatural.\n\nPero resolver\xe9 el truco\nbarato que hay\n\ntras de esto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0E4, map_12_state_06_08E6F0E4, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Mokuba, I have some errands\nto run.\n\nYou're in charge of\nKaibaCorp while I'm gone.\n\n")
  LANGUAGE_TEXT(1, "Mokuba, je dois partir.\nEn mon absence,\n\nje te charge de prot\xe9ger\nla Kaiba Corporation.\n\n")
  LANGUAGE_TEXT(2, "Mokuba, ich bin f\xfcr eine\nWeile weg.\n\nIch \xfcbertrage dir derweil\ndie Verantwortung f\xfcr die\n\nKaiba Corporation.\n\n")
  LANGUAGE_TEXT(3, "Mokuba, io devo uscire.\nIn mia assenza, sei tu\n\nresponsabile della\nKaiba Corp.\n\n")
  LANGUAGE_TEXT(4, "Mokuba, tengo que salir.\n\nQuedas al mando de Kaiba\nCorp en mi ausencia.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You can count on me, bro!\n\n")
  LANGUAGE_TEXT(1, "Pas de probl\xe8me,\ngrand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Keine Sorge, gro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Ci penso io, fratello!\n\n")
  LANGUAGE_TEXT(4, "\xa1D\xe9jamelo, gran hermano!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 40, 0)
  SET_FLAG(79)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0D8, map_12_state_06_08E6F0D8, 0x08E6F0E4, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No?\n\nThen there's nothing to talk\nabout.\n\nIshizu's probably behind\nthis stupid magic trick\n\nanyway.\n\nI'll meet her in person and\nmake her pay!\n\n")
  LANGUAGE_TEXT(1, "Tu crois que c'est faux ?\n\nAlors, je n'ai plus\nrien \xe0 te dire.\n\nJe parie qu'Ishizu est\nderri\xe8re tout cela.\n\nJe vais lui demander\nla v\xe9rit\xe9 en personne.\n\n")
  LANGUAGE_TEXT(2, "Ihr meint, das sei falsch?\n\nDann habe ich euch rein\ngar nichts zu sagen.\n\nIch vermute, Ishizu steckt\nhinter diesem Trick.\n\nIch werde schon noch die\nWahrheit von ihr erfahren.\n\n")
  LANGUAGE_TEXT(3, "E cos\xec sarebbe falso?\n\nAllora non ho proprio\nun bel niente da dirti.\n\nPresumo che dietro ci\nsia lo zampino di Ishizu.\n\nMi far\xf2 dire da lei in per-\nsona come stanno le cose.\n\n")
  LANGUAGE_TEXT(4, "\xbfDices que es falso?\n\nEntonces, no tengo nada en\nabsoluto que deciros.\n\nAsumo que es Ishizu quien\nest\xe1 tras este truco.\n\nLe sacar\xe9 la verdad\npersonalmente.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
