#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_57_state_03: map 57 state 3 */

#define LOCALID_ROLAND         1
#define LOCALID_BIG_FIVE_1     2
#define LOCALID_BIG_FIVE_2     3
#define LOCALID_BIG_FIVE_3     4
#define LOCALID_BIG_FIVE_4     5
#define LOCALID_BIG_FIVE_5     6

LOAD_SPRITE(LOCALID_ROLAND, SPRITE_ROLAND)
LOAD_SPRITE(LOCALID_BIG_FIVE_1, SPRITE_BIG_FIVE)
LOAD_SPRITE(LOCALID_BIG_FIVE_2, SPRITE_BIG_FIVE)
LOAD_SPRITE(LOCALID_BIG_FIVE_3, SPRITE_BIG_FIVE)
LOAD_SPRITE(LOCALID_BIG_FIVE_4, SPRITE_BIG_FIVE)
LOAD_SPRITE(LOCALID_BIG_FIVE_5, SPRITE_BIG_FIVE)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "All right, crew! Everyone\n"
    "ready?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_1), OBJECT_EFFECT_JUMPING)
TEXT
(
    "Yes, I understand. But...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_2), OBJECT_EFFECT_JUMPING)
TEXT
(
    "We're missing two of our\n"
    "members...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_3), OBJECT_EFFECT_JUMPING)
TEXT
(
    "What's the point of doing a\n"
    "children's show?\n\n"
)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You fools!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_LOCALID(LOCALID_BIG_FIVE_1) | OBJECT_LOCALID(LOCALID_BIG_FIVE_2) | OBJECT_LOCALID(LOCALID_BIG_FIVE_3) | OBJECT_LOCALID(LOCALID_BIG_FIVE_4) | OBJECT_LOCALID(LOCALID_BIG_FIVE_5))
DELAY(8)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "The children are afraid!\n\n"
    "The Neo Ghouls stole their\n"
    "rare cards.\n\n"
    "Kaibaman represents hope to\n"
    "the kids.\n\n"
    "When Masters Mokuba and Seto\n"
    "return, how would they feel\n\n"
    "if children aren't enjoying\n"
    "dueling?\n\n"
    "We can't let Masters Mokuba\n"
    "and Seto see that.\n\n"
    "That's why we have to give\n"
    "hope to the kids.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(LOCALID_BIG_FIVE_1, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_2, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_3, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_4, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_5, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "As a bonus, I'll speak to\n"
    "Master Kaiba about giving\n\n"
    "you better jobs.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_ROLAND, SPRITE_KAIBAMAN)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_LOCALID(LOCALID_BIG_FIVE_1) | OBJECT_LOCALID(LOCALID_BIG_FIVE_2) | OBJECT_LOCALID(LOCALID_BIG_FIVE_3) | OBJECT_LOCALID(LOCALID_BIG_FIVE_4) | OBJECT_LOCALID(LOCALID_BIG_FIVE_5))
DELAY(16)
MOVE_OBJECT(LOCALID_BIG_FIVE_4, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_4), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_BIG_FIVE_4, SPRITE_ROBOTIC_KNIGHT)
TALK(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I... I'll do it!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(LOCALID_BIG_FIVE_5, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_5), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_BIG_FIVE_5, SPRITE_JINZO)
TALK(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yes!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(LOCALID_BIG_FIVE_1, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_2, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(LOCALID_BIG_FIVE_3, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_1), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_BIG_FIVE_1, SPRITE_DEEPSEA_WARRIOR)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_2), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_BIG_FIVE_2, SPRITE_NIGHTMARE_PENGUIN)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_BIG_FIVE_3), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(LOCALID_BIG_FIVE_3, SPRITE_JUDGE_MAN)
FADE_SCREEN(8)
WARP(LOCATION_KAIBA_LAND, 4, 0, 0)
