#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_00_state_14: map 0 state 14 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08E34EC8, map_00_state_14_08E34EC8, 0x08E34ED4, 0x08E34EE0)
  LOAD_SPRITE(1, SPRITE_ISHIZU)
  LOAD_SPRITE(2, SPRITE_ESPA)
  LOAD_SPRITE(3, SPRITE_ROBA_BROTHER_1)
  LOAD_SPRITE(4, SPRITE_ROBA_BROTHER_2)
  LOAD_SPRITE(5, SPRITE_ROBA_BROTHER_3)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_PARADOX_ABOUT_RA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34ED4, map_00_state_14_08E34ED4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You must ask Paradox where Pegasus's castle is.",
      "Paradox is in China."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EE0, map_00_state_14_08E34EE0, 0x08E34EEC, 0x08E34EF8)
  CHECK_FLAG(EVENT_FLAG_ISHIZU_SAID_TO_GO_SEE_MARIK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EEC, map_00_state_14_08E34EEC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Did you meet Paradox?")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Well...")
  HIDE_PORTRAIT()
  PLAY_MUSIC(MUSIC_332)
  FADE_SCREEN(4)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I see...",
      "Only two men have deciphered the ancient hieroglyphics",
      "needed to awaken Ra..",
      "The first is Kaiba. But he is..."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "He went after Mokuba.")
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Then we just hafta meet the other guy.")
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "The other... Is my brother Marik.")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Ah... That makes sense.",
      "The Winged Dragon of Ra belonged to Marik."
  )
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Marik is living a new life in Egypt.",
      "Please see him there."
  )
  SET_FLAG(EVENT_FLAG_ISHIZU_SAID_TO_GO_SEE_MARIK)
  SET_FLAG(EVENT_FLAG_UNLOCKED_EGYPT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EF8, map_00_state_14_08E34EF8, 0x08E34F04, 0x08E34F10)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MARIK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F04, map_00_state_14_08E34F04, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Has The Winged Dragon of Ra awoken?",
      "Please meet my brother Marik in Egypt."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F10, map_00_state_14_08E34F10, 0x08E34F1C, 0x08E34F28)
  CHECK_FLAG(EVENT_FLAG_SAW_PARADOX_FLEE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F1C, map_00_state_14_08E34F1C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "It appears that Marik has awakened Ra.",
      "There is no time to waste.",
      "You must once again visit Paradox in China.",
      "He knows where Pegasus's castle is.",
      "Find the location of the castle and stop the Dark",
      "Being."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F28, map_00_state_14_08E34F28, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You must once again visit Paradox in China.",
      "He knows the location of Pegasus's castle."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34DFC, map_00_state_14_08E34DFC, 0x08E34E08, 0x08E34E14)
  CHECK_FLAG(EVENT_FLAG_ESPA_ROBA_THANKED_YOU_FOR_SAVING_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E08, map_00_state_14_08E34E08, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, PORTRAIT_POSITION_AUTO, "Pipipi... You managed to save Ishizu.")
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "But you still have a huge challenge ahead of you.",
      "I don't need psychic powers to predict this.",
      "I can tell just by the looking into your eyes.",
      "You'll be fine. Don't give up!"
  )
  SET_FLAG(EVENT_FLAG_ESPA_ROBA_THANKED_YOU_FOR_SAVING_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E14, map_00_state_14_08E34E14, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, PORTRAIT_POSITION_AUTO,
      "Pipipi...",
      "You're fighting to save the world."
  )
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You'll be fine as long as you don't give up!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EB0, map_00_state_14_08E34EB0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'm exhausted. I need to rest.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E5C, map_00_state_14_08E34E5C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "My big brother dueled great against the Neo Ghouls.",
      "He really showed them who's boss!",
      "He's the coolest guy I know!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E68, map_00_state_14_08E34E68, EVENT_NOP, EVENT_NOP)
  TEXT(
      "My big brother always says...",
      "A duelist becomes more powerful when he has",
      "friends supporting him."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E74, map_00_state_14_08E34E74, EVENT_NOP, EVENT_NOP)
  TEXT("I really like Espa! He's the best!")
  FALLTHROUGH()
END_EVENT_SCRIPT()
