#include "event_macros.h"
#include "overworld.h"

/* map_16_state_01: map 16 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E7DDF8, map_16_state_01_08E7DDF8, 0x08E7DE10, 0x08E7DE04)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE10, map_16_state_01_08E7DE10, 0x08E7DE88, 0x08F04040)
  LANGUAGE_TEXT(0, "Welcome aboard the Duel\nExpress!\n\nWe will be leaving very\nshortly.\n\n")
  LANGUAGE_TEXT(1, "Bienvenue \xe0 bord\ndu Duel Express !\n\nNous allons bient\xf4t\npartir.\n\n")
  LANGUAGE_TEXT(2, "Willkommen an Bord des\nDuel Express!\n\nWir fahren in K\xfcrze ab.\n\n")
  LANGUAGE_TEXT(3, "Benvenuti a bordo del\nDuel Express!\n\nPartiremo tra poco.\n\n")
  LANGUAGE_TEXT(4, "\xa1Bienvenidos a bordo\ndel Duel Express!\n\nSaldremos muy pronto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(14)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE88, map_16_state_01_08E7DE88, 0x08F04040, 0x08E7DE94)
  CHECK_FLAG(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE94, map_16_state_01_08E7DE94, 0x08F04040, 0x08E7DEA0)
  CHECK_FLAG(13)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEA0, map_16_state_01_08E7DEA0, 0x08F04040, 0x08E7DEAC)
  CHECK_FLAG(14)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEAC, map_16_state_01_08E7DEAC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(238)
  WALK_OBJECT_X(4, 108)
  DELAY(8)
  MOVE_OBJECT(4, 1, 0, 0)
  LANGUAGE_TEXT(0, "Forward all clear!\n\n")
  LANGUAGE_TEXT(1, "Pr\xeat \xe0 l'avant !\n\n")
  LANGUAGE_TEXT(2, "Freie Fahrt voraus!\n\n")
  LANGUAGE_TEXT(3, "Avanti c'\xe8 posto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Delante, despejado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  LANGUAGE_TEXT(0, "Rear all clear!\n\n")
  LANGUAGE_TEXT(1, "Pr\xeat \xe0 l'arri\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Hinten alles frei!\n\n")
  LANGUAGE_TEXT(3, "Dietro c'\xe8 posto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Detr\xe1s, despejado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 0, 0, 0)
  LANGUAGE_TEXT(0, "All clear for dueling!\n\n")
  LANGUAGE_TEXT(1, "Pr\xeat pour le duel !\n\n")
  LANGUAGE_TEXT(2, "Alles klar zum Duell!\n\n")
  LANGUAGE_TEXT(3, "C'\xe8 posto per duellare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Todo listo para el duelo!\n\n")
  END_LANGUAGE_TEXT()
  STOP_MUSIC(238)
  PLAY_MUSIC(370)
  LANGUAGE_TEXT(0, "Duel Express is good to go!\n\n")
  LANGUAGE_TEXT(1, "Le Duel Express\nest pr\xeat \xe0 partir !\n\n")
  LANGUAGE_TEXT(2, "Der Duel Express ist\nstartklar!\n\n")
  LANGUAGE_TEXT(3, "Il Duel Express \xe8 in\npartenza!\n\n")
  LANGUAGE_TEXT(4, "\xa1El Duel Express sale ya!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(234)
  SET_FLAG(247)
  HIDE_PORTRAIT()
  DELAY(4)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(4)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(4)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(4)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(4)
  MOVE_OBJECT(2, 0, 0, 1)
  DELAY(4)
  LANGUAGE_TEXT(0, "I'm going to give it my best\nshot!\n\n")
  LANGUAGE_TEXT(1, "Je veux donner\nle meilleur de moi !\n\n")
  LANGUAGE_TEXT(2, "Ich werde mein Bestes\ngeben!\n\n")
  LANGUAGE_TEXT(3, "Ce la metter\xe0 tutta!\n\n")
  LANGUAGE_TEXT(4, "\xa1Dar\xe9 lo mejor de m\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(4)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(4)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(4)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(4)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(4)
  MOVE_OBJECT(3, 0, 0, 1)
  DELAY(4)
  LANGUAGE_TEXT(0, "Our Duel Express is on the\ngo!\n\n")
  LANGUAGE_TEXT(1, "Notre Duel Express\ns'est mis en route !\n\n")
  LANGUAGE_TEXT(2, "Unser Duel Express rollt!\n\n")
  LANGUAGE_TEXT(3, "Il nostro Duel Express\nsta partendo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nuestro Duel Express\nse mueve!\n\n")
  END_LANGUAGE_TEXT()
  SET_MAP_MUSIC(234)
  SET_FLAG(0)
  CLEAR_FLAG(245)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE04, map_16_state_01_08E7DE04, 0x08E7DE28, 0x08E7DE1C)
  CHECK_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE28, map_16_state_01_08E7DE28, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The level of competition is\nhigher in the next car.\n\n")
  LANGUAGE_TEXT(1, "Le niveau de comp\xe9tition\nest plus \xe9lev\xe9 dans le\n\nwagon suivant.\n\n")
  LANGUAGE_TEXT(2, "Die Konkurrenz im n\xe4chsten\nWaggon ist st\xe4rker.\n\n")
  LANGUAGE_TEXT(3, "Il livello di gara \xe8 pi\xf9\nalto nella prossima\n\ncarrozza.\n\n")
  LANGUAGE_TEXT(4, "El nivel de lucha es mayor\nen el siguiente coche.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE1C, map_16_state_01_08E7DE1C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Best of luck.\n\n")
  LANGUAGE_TEXT(1, "Bonne chance.\n\n")
  LANGUAGE_TEXT(2, "Viel Gl\xfcck.\n\n")
  LANGUAGE_TEXT(3, "In bocca al lupo.\n\n")
  LANGUAGE_TEXT(4, "Mucha suerte.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE34, map_16_state_01_08E7DE34, 0x08E7DE10, 0x08E7DE40)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE40, map_16_state_01_08E7DE40, 0x08E7DE58, 0x08E7DE4C)
  CHECK_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE58, map_16_state_01_08E7DE58, 0x08E7DE64, 0x08E7DE70)
  LANGUAGE_TEXT(0, "You wish to duel against me?\nVery well.\n\nCan you beat me at your\nduelist level?\n\n")
  LANGUAGE_TEXT(1, "Tu veux te battre en duel\ncontre moi ? Tr\xe8s bien.\n\nTu crois me battre \xe0 ton\nniveau de duelliste ?\n\n")
  LANGUAGE_TEXT(2, "Du willst dich mit mir duel-\nlieren? Na gut.\n\nK\xf6nntest du mich auf deinem\nDuellanten-Level schlagen?\n\n")
  LANGUAGE_TEXT(3, "Vuoi duellare con me?\nBenissimo.\n\nPotrai battermi con il\ntuo livello duellante?\n\n")
  LANGUAGE_TEXT(4, "\xbfQuieres luchar conmigo?\nMuy bien.\n\n\xbfMe puedes vencer a\ntu nivel de duelista?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(25)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE64, map_16_state_01_08E7DE64, 0x08F04040, 0x08F04040)
  SET_FLAG(3)
  PLAY_MUSIC(236)
  LANGUAGE_TEXT(0, "I've been defeated.\n\nBut the next car won't be so\neasy.\n\n")
  LANGUAGE_TEXT(1, "Je suis battu.\n\nMais dans le prochain wagon,\n\xe7a ne sera pas aussi\n\nfacile.\n\n")
  LANGUAGE_TEXT(2, "Du hast mich besiegt.\n\nAber der n\xe4chste Waggon wird\nnicht so einfach f\xfcr dich.\n\n")
  LANGUAGE_TEXT(3, "Sono stato sconfitto.\n\nMa la prossima carrozza non\nsar\xe0 cos\xec facile per te.\n\n")
  LANGUAGE_TEXT(4, "He perdido.\n\nPero el pr\xf3ximo vag\xf3n no te\nser\xe1 tan f\xe1cil.\n\n")
  END_LANGUAGE_TEXT()
  SET_MAP_MUSIC(236)
  MOVE_OBJECT(1, 2, 8, 0)
  MOVE_OBJECT(1, 3, 24, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE70, map_16_state_01_08E7DE70, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DE4C, map_16_state_01_08E7DE4C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm not a worthwhile\nopponent for you.\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas un\nadversaire \xe0 ta taille.\n\n")
  LANGUAGE_TEXT(2, "Ich bin kein w\xfcrdiger\nGegner f\xfcr dich.\n\n")
  LANGUAGE_TEXT(3, "Non sono un degno\navversario per te.\n\n")
  LANGUAGE_TEXT(4, "No soy un digno\nrival para ti.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DCD8, map_16_state_01_08E7DCD8, 0x08E7DCF0, 0x08E7DCE4)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DCF0, map_16_state_01_08E7DCF0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm going to raise my\nduelist level here.\n\nThen, I'm going to the next\ncar.\n\n")
  LANGUAGE_TEXT(1, "Ici, je vais am\xe9liorer\nmon niveau de duelliste.\n\nEnsuite, je passe\nau wagon suivant.\n\n")
  LANGUAGE_TEXT(2, "Hier verbessere ich mein\nDuellanten-Level.\n\nUnd dann wechsle ich in\nden n\xe4chsten Waggon.\n\n")
  LANGUAGE_TEXT(3, "Qui aumenter\xf2 il\nmio livello duellante.\n\nPoi passer\xf2 alla\nprossima carrozza.\n\n")
  LANGUAGE_TEXT(4, "Voy a elevar mi\nnivel duelista aqu\xed.\n\nLuego, ir\xe9 al\nsiguiente coche.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DCE4, map_16_state_01_08E7DCE4, 0x08E7DCFC, 0x08E7DD08)
  CHECK_FLAG(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DCFC, map_16_state_01_08E7DCFC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm going to raise my\nduelist level here.\n\nThen, I'm going to the next\ncar.\n\n")
  LANGUAGE_TEXT(1, "Je vais am\xe9liorer ici\nmon niveau de duelliste.\n\nApr\xe8s, je pourrais\npasser au wagon suivant.\n\n")
  LANGUAGE_TEXT(2, "Hier werde ich mein Duel-\nlanten-Level verbessern.\n\nDann wechsle ich in den\nn\xe4chsten Waggon.\n\n")
  LANGUAGE_TEXT(3, "Qui aumenter\xf2 il mio\nlivello duellante.\n\nPoi passer\xf2 alla\nprossima carrozza.\n\n")
  LANGUAGE_TEXT(4, "Voy a elevar mi nivel de\nduelista aqu\xed.\n\nLuego, ir\xe9 al\nsiguiente coche.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD08, map_16_state_01_08E7DD08, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(236)
  LANGUAGE_TEXT(0, "A loss right off the bat...\nThis is hard to take.\n\n")
  LANGUAGE_TEXT(1, "Perdre si facilement...\nC'est pas facile \xe0\n\nadmettre.\n\n")
  LANGUAGE_TEXT(2, "Sofort verloren...\nEin harter Schlag.\n\n")
  LANGUAGE_TEXT(3, "Una sconfitta immediata...\n\xc8 dura da sopportare.\n\n")
  LANGUAGE_TEXT(4, "Perder de primeras...\nEso es duro de tragar.\n\n")
  END_LANGUAGE_TEXT()
  SET_MAP_MUSIC(236)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD14, map_16_state_01_08E7DD14, 0x08E7DD2C, 0x08E7DD20)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD2C, map_16_state_01_08E7DD2C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "We haven't even moved yet.\nHold your horses.\n\n")
  LANGUAGE_TEXT(1, "Nous n'avons m\xeame\npas encore boug\xe9.\n\nCalme tes ardeurs !\n\n")
  LANGUAGE_TEXT(2, "Wir sind noch nicht einmal\nlosgefahren.\n\nMach bitte mal halblang.\n\n")
  LANGUAGE_TEXT(3, "Ma se ancora non ci\nsiamo nemmeno mossi.\n\nDatti una calmata!\n\n")
  LANGUAGE_TEXT(4, "Todav\xeda no hemos\nni salido. Para el carro.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD20, map_16_state_01_08E7DD20, 0x08E7DD44, 0x08E7DD38)
  CHECK_FLAG(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD44, map_16_state_01_08E7DD44, 0x08E7DD5C, 0x08E7DD50)
  LANGUAGE_TEXT(0, "I'll get my first win off\nyou.\n\n")
  LANGUAGE_TEXT(1, "Laisse-moi d'abord\ngagner contre toi.\n\n")
  LANGUAGE_TEXT(2, "Aber erst hole ich mir von\ndir meinen ersten Sieg.\n\n")
  LANGUAGE_TEXT(3, "Con te otterr\xf2 il\nmio primo successo.\n\n")
  LANGUAGE_TEXT(4, "D\xe9jate ser mi\nprimera victoria.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(23)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD5C, map_16_state_01_08E7DD5C, 0x08E7DD08, 0x08F04040)
  SET_FLAG(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD50, map_16_state_01_08E7DD50, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD38, map_16_state_01_08E7DD38, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Go look for someone else to\nduel.\n\n")
  LANGUAGE_TEXT(1, "Cherche quelqu'un d'autre\n\xe0 affronter en duel.\n\n")
  LANGUAGE_TEXT(2, "Such dir einen anderen\nDuellpartner.\n\n")
  LANGUAGE_TEXT(3, "Cercati qualcun altro\ncon cui duellare.\n\n")
  LANGUAGE_TEXT(4, "Ve a buscar alguien\ncon quien luchar.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD68, map_16_state_01_08E7DD68, 0x08E7DD80, 0x08E7DD74)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD80, map_16_state_01_08E7DD80, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This train's stopping at the\nEgypt Exhibition, right?\n\n")
  LANGUAGE_TEXT(1, "Ce train s'arr\xeate bien \xe0\nl'Exposition \xe9gyptienne ?\n\n")
  LANGUAGE_TEXT(2, "Dieser Zug h\xe4lt doch an der\n\xe4gypt. Ausstellung, oder?\n\n")
  LANGUAGE_TEXT(3, "Questo treno si ferma alla\nMostra Egizia, giusto?\n\n")
  LANGUAGE_TEXT(4, "Este tren para en la\nExposici\xf3n Egipcia, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(13)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD74, map_16_state_01_08E7DD74, 0x08E7DD8C, 0x08E7DD98)
  CHECK_FLAG(2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD8C, map_16_state_01_08E7DD8C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Duel Express tourney is\nfinally on!\n\n")
  LANGUAGE_TEXT(1, "Le tournoi du Duel Express\na enfin commenc\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Das Turnier des Duel Express\nsteht endlich bevor!\n\n")
  LANGUAGE_TEXT(3, "Finalmente \xe8 iniziato il\ntorneo del Duel Express!\n\n")
  LANGUAGE_TEXT(4, "El torneo del Duel Express\npor fin ha llegado.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DD98, map_16_state_01_08E7DD98, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "You're not as weak as you\nlook.\n\n")
  LANGUAGE_TEXT(1, "Tu n'es pas aussi faible\nque tu en as l'air.\n\n")
  LANGUAGE_TEXT(2, "Du bist nicht so schwach\nwie du aussiehst.\n\n")
  LANGUAGE_TEXT(3, "Non sei poi cos\xec debole\ncome sembri... Troverai\n\n")
  LANGUAGE_TEXT(4, "No eres tan d\xe9bil\ncomo parece.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDA4, map_16_state_01_08E7DDA4, 0x08E7DDBC, 0x08E7DDB0)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDBC, map_16_state_01_08E7DDBC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Take me lightly and suffer\nthe consequences.\n\nWe'll duel once the train\npulls out.\n\n")
  LANGUAGE_TEXT(1, "Ne me traite pas\ncomme \xe7a \xe0 la l\xe9g\xe8re.\n\nOn se battra quand\nle train partira.\n\n")
  LANGUAGE_TEXT(2, "Untersch\xe4tz mich nicht.\n\nSobald der Zug losf\xe4hrt,\nduellieren wir uns.\n\n")
  LANGUAGE_TEXT(3, "Non prendermi sottogamba.\n\nDuelleremo quando il\ntreno lascer\xe0 la stazione.\n\n")
  LANGUAGE_TEXT(4, "No me tomes a la\nligera.\n\nLucharemos cuando\nel tren salga.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(13)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDB0, map_16_state_01_08E7DDB0, 0x08E7DDD4, 0x08E7DDC8)
  CHECK_FLAG(2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDD4, map_16_state_01_08E7DDD4, 0x08E7DDEC, 0x08E7DDE0)
  LANGUAGE_TEXT(0, "Think you can beat me?\n\n")
  LANGUAGE_TEXT(1, "Tu crois pouvoir\nme battre ?\n\n")
  LANGUAGE_TEXT(2, "Ob du mich wohl schlagen\nkannst?\n\n")
  LANGUAGE_TEXT(3, "Pensi di battermi?\n\n")
  LANGUAGE_TEXT(4, "\xbfCrees que me\npuedes vencer?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(24)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDEC, map_16_state_01_08E7DDEC, 0x08F04040, 0x08F04040)
  SET_FLAG(2)
  PLAY_MUSIC(236)
  LANGUAGE_TEXT(0, "Y-you're a lot tougher than\nyou look.\n\n")
  LANGUAGE_TEXT(1, "T-tu es bien plus fort\nque tu n'en as l'air.\n\n")
  LANGUAGE_TEXT(2, "D-du bist ja viel st\xe4rker\nals du aussiehst.\n\n")
  LANGUAGE_TEXT(3, "Certo che sei molto pi\xf9\nforte di quanto sembri.\n\n")
  LANGUAGE_TEXT(4, "E-eres m\xe1s fuerte\nde lo que parece.\n\n")
  END_LANGUAGE_TEXT()
  SET_MAP_MUSIC(236)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDE0, map_16_state_01_08E7DDE0, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DDC8, map_16_state_01_08E7DDC8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "You'll find your opponent in\nthe next car.\n\n")
  LANGUAGE_TEXT(1, "Tu trouveras un\nadversaire \xe0 ta taille\n\ndans le wagon suivant.\n\n")
  LANGUAGE_TEXT(2, "Im n\xe4chsten Waggon findest\ndu einen w\xfcrdigen Gegner.\n\n")
  LANGUAGE_TEXT(3, "qualcuno al pari tuo\nnella prossima carrozza.\n\n")
  LANGUAGE_TEXT(4, "Encontrar\xe1s tu rival\nen el siguiente coche.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEB8, map_16_state_01_08E7DEB8, 0x08E7DEC4, 0x08E7DED0)
  CHECK_FLAG(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEC4, map_16_state_01_08E7DEC4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This train is bound for the\nEgypt Exhibition.\n\nWe will be departing\nshortly.\n\nWhy not board now and spend\nsome time dueling?\n\n")
  LANGUAGE_TEXT(1, "Ce train a pour terminus\nl'Exposition \xe9gyptienne.\n\nNous allons bient\xf4t partir.\n\nPourquoi ne pas monter\nmaintenant et passer\n\nun peu de temps\n\xe0 vous battre en duel ?\n\n")
  LANGUAGE_TEXT(2, "Dieser Zug f\xe4hrt zur\n\xe4gypt. Ausstellung.\n\nEr f\xe4hrt bald ab.\nWarum steigt ihr nicht ein\n\nund liefert euch Duelle?\n\n")
  LANGUAGE_TEXT(3, "Questo treno \xe8 diretto\nalla Mostra Egizia.\n\nTra poco si parte.\nPerch\xe9 non salire\n\nadesso e passare del\ntempo a duellare?\n\n")
  LANGUAGE_TEXT(4, "Este tren va a la\nExposici\xf3n Egipcia.\n\nSaldremos pronto.\n\n\xbfPor qu\xe9 no subimos\ny luchamos un rato?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DED0, map_16_state_01_08E7DED0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Our next and only stop is\nthe Egypt Exhibition.\n\n")
  LANGUAGE_TEXT(1, "Prochain et dernier arr\xeat :\nl'Exposition \xe9gyptienne.\n\n")
  LANGUAGE_TEXT(2, "Der n\xe4chste, einzige Stopp\nist die \xe4gyp. Ausstellung.\n\n")
  LANGUAGE_TEXT(3, "La nostra prossima e\nunica fermata \xe8 la\n\nMostra Egizia.\n\n")
  LANGUAGE_TEXT(4, "La pr\xf3xima y \xfanica parada es\nla Exposici\xf3n Egipcia.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
