#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_46_state_01: map 46 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EDAD34, map_46_state_01_08EDAD34, 0x08EDAD40, 0x08F0404C)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Gawry nida! Gawry nida!\n\n"
      "We win all duels! Gawry!\n\n"
  )
  DUEL(DUELIST_CHEVALIER_110)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDAD40, map_46_state_01_08EDAD40, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_DUNGEON)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "G-gawry nida... G-ga..\n"
      "n-niii.... urrri...\n\n"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
