#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_52_state_01: map 52 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EE62A0, map_52_state_01_08EE62A0, 0x08EE62AC, 0x08EE62D0)
  LOAD_SPRITE(1, SPRITE_INVISIBLE)
  LOAD_SPRITE(2, SPRITE_SHADI)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_SHADIS_PORTRAIT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE62AC, map_52_state_01_08EE62AC, 0x08EE62B8, 0x08EE62C4)
  SET_FLAG(EVENT_FLAG_TALKED_TO_SHADIS_PORTRAIT)
  PLAY_MUSIC(MUSIC_406)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(0, 44)
  WALK_OBJECT_X(0, 72)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(2, 60, 44, 0, 1, 0)
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("You have traveled far...\nThere is but a little more\n\nto go.\n\nI implore that you save\nPegasus...\n\nOr Sol Chevalsky, as he now\ncalls himself.\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("My tale is long. Will you\nhear me out?\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("{CARD_1}Yes\nNo{CARD_2}\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE62B8, map_52_state_01_08EE62B8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("To learn the truth takes\ncourage...\n\nHear my tale of the tragedy\nof Pegasus.\n\nTime passed since Duelist\nKingdom...\n\nPegasus awoke from his long\ndream...\n\nHe wandered the globe, drawn\nby an unseen power.\n\nHe visited many ancient\nruins until his journey led\n\nhim to Egypt.\n\nBy chance, he found a stone\ntablet.\n\nSealed within it was Reshef\nthe Dark Being.\n\nAnd thus began Pegasus's\ntragedy.\n\nHe slowly deciphered the\nstone tablet...\n\nAnd realized the calamity it\ncould unleash.\n\nIt could bring eternal\ndarkness to the world...\n\nSo Pegasus was determined to\nprevent Reshef's escape.\n\nAs he further studied the\nstone tablet...\n\nHe was unaware that he was\nfalling under Reshef's\n\nspell...\n\nThe Egyptian God Cards are\nneeded to seal the stone\n\ntablet...\n\nBut they can also be used to\nresurrect Reshef.\n\nPegasus sought the Egyptian\nGod Cards to seal Reshef\n\nforever...\n\nBut, under Reshef's spell,\nhe did the exact opposite.\n\nHe used the Egyptian God\nCards in a resurrection\n\nritual...\n\nWhich freed Reshef and\nturned the Egyptian God\n\nCards to stone.\n\nThe Millennium Items were\nalso scattered across the\n\nglobe.\n\nPegasus is now fully under\nReshef's control.\n\n{PLAYER}, you must not hate\nPegasus.\n\nHatred makes your spirit as\ntainted as Reshef's.\n\nYou must enter the final\nbattle with a pure spirit.\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE62C4, map_52_state_01_08EE62C4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I understand you are in a\nhurry. So be it.\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE62D0, map_52_state_01_08EE62D0, 0x08F04040, 0x08F04040)
  TEXT("Shadi no longer appears...\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
