#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_37_state_07: map 37 state 7 */

#define LOCALID_MAKO             1
#define LOCALID_MONKEY_ROBOT_1   2
#define LOCALID_MONKEY_ROBOT_2   3
#define LOCALID_MONKEY_ROBOT_3   4
#define LOCALID_MONKEY_ROBOT_4   5
#define LOCALID_RAFT             6

LOAD_SPRITE(LOCALID_MAKO, SPRITE_MAKO)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_1, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_2, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_3, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_4, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_RAFT, SPRITE_RAFT)
PLAY_MUSIC(MUSIC_MONKEY_ROBOTS)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "We're setting sail!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_MONKEY_ROBOT_3), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_MONKEY_ROBOT_1) | OBJECT_LOCALID(LOCALID_MONKEY_ROBOT_2), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukikiiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT,
    "Wait for me!\n\n"
    "I'm returning back to the\n"
    "Town of Domino right now!\n\n"
)
FADE_SCREEN(8)
SHOW_OBJECT(SPRITE_MAKO, 128, 96, 0, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_1, 128, 96, 0, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_2, 128, 96, 0, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_3, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_RAFT, 128, 96, 0, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_4, 60, 0, 0, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_4, 0, 64)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 6, PORTRAIT_RIGHT,
    "Ukiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_MONKEY_ROBOT_4), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_LOCALID(LOCALID_MONKEY_ROBOT_4), OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_324)
TALK(PORTRAIT_ROBOT_MOkNEY, 5, PORTRAIT_RIGHT,
    "Ukikikikiiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_4, 0, 32)
FADE_MUSIC(16)
FADE_SCREEN(16)
WARP(LOCATION_CARD_SHOP_OUTSIDE, 14, 0, 0)
