#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_17_state_07: map 17 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E7F124, map_17_state_07_08E7F124, 0x08E7F13C, 0x08E7F130)
  LOAD_SPRITE(1, SPRITE_PANIK)
  LOAD_SPRITE(2, SPRITE_DUEL_EXPRESS_CONDUCTOR)
  PLAY_MUSIC(SOUND_NONE)
  PLAY_MUSIC(MUSIC_237)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Ha ha ha! Looks like we've\n"
    "entered a tunnel!\n\n"
    "And darkness gives me power!\n"
    "It's time to duel!\n\n"
)
  CLEAR_FLAG(240)
  DUEL(DUELIST_PANICK_153)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7F13C, map_17_state_07_08E7F13C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_236)
  TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Urgh...\n\n"
)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_235)
  PLAY_MUSIC(MUSIC_232)
  CLEAR_FLAG(247)
  DELAY(16)
  WALK_OBJECT_X(2, 112)
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "We're now arriving!\n\n"
    "This is our last stop, the\n"
    "Egypt Exhibition!\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 128)
  DELAY(16)
  TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I may have lost the duel...\n\n"
    "But you will never get the\n"
    "Millennium Items!\n\n"
)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  WALK_OBJECT_X(1, 144)
  SET_FLAG(EVENT_FLAG_DEFEATED_PANIK)
  CLEAR_FLAG(240)
  SET_FLAG(EVENT_FLAG_UNLOCKED_EGYPT_EXHIBITION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7F130, map_17_state_07_08E7F130, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  FALLTHROUGH()
END_EVENT_SCRIPT()
