#include "event_macros.h"
#include "overworld.h"

/* map_39_state_06: map 39 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08ED4B40, map_39_state_06_08ED4B40, 0x08ED4B4C, 0x08F0404C)
  PLAY_MUSIC(33)
  DELAY(16)
  WALK_OBJECT_X(1, 53)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(0, 69)
  WALK_OBJECT_X(13, 78)
  WALK_OBJECT_X(14, 78)
  DELAY(16)
  WALK_OBJECT_X(1, 16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 6, 8)
  LANGUAGE_TEXT(0, "Ukki?\n\n")
  LANGUAGE_TEXT(1, "Ukki ?\n\n")
  LANGUAGE_TEXT(2, "Ukki?\n\n")
  LANGUAGE_TEXT(3, "Ukki?\n\n")
  LANGUAGE_TEXT(4, "\xbfUkki?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Why are you running? Are you\nTristan?\n\n")
  LANGUAGE_TEXT(1, "Pourquoi est-ce que\ntu cours ?\n\nEst-ce que\nc'est toi Tristan ?\n\n")
  LANGUAGE_TEXT(2, "Warum rennst du?\nBist du Tristan?\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 corri? Sei tu\nTristan?\n\n")
  LANGUAGE_TEXT(4, "\xbfPor qu\xe9 corres?\n\xbfEres Tristan?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "Ukiiii...\n\n")
  LANGUAGE_TEXT(1, "Ukiiii...\n\n")
  LANGUAGE_TEXT(2, "Ukiiii...\n\n")
  LANGUAGE_TEXT(3, "Ukiiii...\n\n")
  LANGUAGE_TEXT(4, "Ukiiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "We'll know for sure after we\nduel!\n\n")
  LANGUAGE_TEXT(1, "On le saura quand\non l'affrontera en duel !\n\n")
  LANGUAGE_TEXT(2, "Wenn wir uns duellieren,\nwerden wir es herausfinden!\n\n")
  LANGUAGE_TEXT(3, "Lo sapremo quando\nduelleremo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo sabremos cuando\nnos enfrentemos!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(0, 24)
  WALK_OBJECT_X(13, 16)
  MOVE_OBJECT(13, 0, 0, 0)
  WALK_OBJECT_X(14, 16)
  MOVE_OBJECT(14, 2, 0, 0)
  DUEL(129)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED4B4C, map_39_state_06_08ED4B4C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(33)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "U-ukiiii...\n\n")
  LANGUAGE_TEXT(1, "U-ukiiii...\n\n")
  LANGUAGE_TEXT(2, "U-ukiiii...\n\n")
  LANGUAGE_TEXT(3, "U-ukiiii...\n\n")
  LANGUAGE_TEXT(4, "U-ukiiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "This monkey's lousy...\nThere's no doubt about it!\n\n")
  LANGUAGE_TEXT(1, "Ce satan\xe9 niveau\nd'aptitude...\n\nOn ne peut pas\ny \xe9chapper.\n\n")
  LANGUAGE_TEXT(2, "Diese lausige Taktik...\nDas kann nur einer sein.\n\n")
  LANGUAGE_TEXT(3, "Il livello di abilit\xe0 fa\npena. Non c'\xe8 dubbio.\n\n")
  LANGUAGE_TEXT(4, "Este pobre nivel...\nNo hay duda.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You're Tristan, aren't ya?\nHowl twice if it's true.\n\n")
  LANGUAGE_TEXT(1, "C'est toi Tristan ? Crie\ndeux fois si c'est toi.\n\n")
  LANGUAGE_TEXT(2, "Du bist Tristan, stimmt's?\nWenn ja, ruf zweimal.\n\n")
  LANGUAGE_TEXT(3, "Sei tu Tristan, non \xe8 cos\xec?\nGrida due volte se \xe8 vero.\n\n")
  LANGUAGE_TEXT(4, "T\xfa eres Tristan \xbfno?\nChilla dos veces si es as\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(326)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 8)
  LANGUAGE_TEXT(0, "Ukki! Ukikki!\n\n")
  LANGUAGE_TEXT(1, "Ukki !\nUkikki !\n\n")
  LANGUAGE_TEXT(2, "Ukki!\nUkikki!\n\n")
  LANGUAGE_TEXT(3, "Ukki! Ukikki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukki!\n\xa1Ukikki!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SAD, 8)
  LANGUAGE_TEXT(0, "Man, look at ya... How could\nKaiba do this to ya?\n\n")
  LANGUAGE_TEXT(1, "Mec, regarde-toi... Qu'est-\nce qu'ils ont fait de toi ?\n\n")
  LANGUAGE_TEXT(2, "Mann, was haben die nur\nmit dir gemacht?!\n\n")
  LANGUAGE_TEXT(3, "Guarda come sei conciato...\nChe ti hanno fatto?\n\n")
  LANGUAGE_TEXT(4, "T\xedo, m\xedrate...\n\xbfQu\xe9 te han hecho?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's take him back to the\nTown of Domino.\n\n")
  LANGUAGE_TEXT(1, "Quoi qu'il en soit,\nramenons-le \xe0 Domino.\n\n")
  LANGUAGE_TEXT(2, "Bringen wir ihn zur\xfcck\nnach Domino.\n\n")
  LANGUAGE_TEXT(3, "Riportiamolo a Domino.\n\n")
  LANGUAGE_TEXT(4, "Llev\xe9moslo de vuelta a\nDomino de todos modos.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_COMPLETED_ROBOT_MONKEY_SIDEQUEST)
  WARP(6, 12, 0, 0)
  FADE_SCREEN(8)
  FALLTHROUGH()
END_EVENT_SCRIPT()
