#include "event_macros.h"
#include "overworld.h"

/* map_56_state_01: map 56 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EF2F84, map_56_state_01_08EF2F84, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NOAH, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My name is Noah.\n\nShall I make you a\npermanent citizen of my\n\nvirtual world?\n\n")
  LANGUAGE_TEXT(1, "Je m'appelle Noah.\n\nTu veux devenir un citoyen\ndu monde virtuel ?\n\n")
  LANGUAGE_TEXT(2, "Mein Name ist Noah.\n\nSoll ich aus dir einen\nvirtuellen Denizen machen?\n\n")
  LANGUAGE_TEXT(3, "Mi chiamo Noah.\n\nDevo farti diventare citta-\ndino del mondo virtuale?\n\n")
  LANGUAGE_TEXT(4, "Mi nombre es Noah.\n\n\xbfDeber\xeda hacerte morador\ndel mundo virtual?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2F90, map_56_state_01_08EF2F90, 0x08EF2F9C, 0x08F0404C)
  PORTRAIT(PORTRAIT_NOAH, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Heh. You want me to duel\nyou?\n\nI admire your courage, but\nyour stupidity will be\n\nyour downfall!\n\nSavor the bitter taste of\ndefeat!\n\n")
  LANGUAGE_TEXT(1, "Quoi, moi ? Me battre\nen duel avec quelqu'un\n\ncomme toi ?\nD'accord.\n\nJe vais te donner un\navant-go\xfbt de la mort.\n\n")
  LANGUAGE_TEXT(2, "Hmm. Ich? Ein Duell mit\njemandem wie dir?\n\nNa gut.\n\nIch werde dir zeigen, was\neine Katastrophe ist.\n\n")
  LANGUAGE_TEXT(3, "Chi, io? Duellare con\ntipi come te?\n\nBene.\n\nTi far\xf2 assaggiare la\ncatastrofe.\n\n")
  LANGUAGE_TEXT(4, "\xa1Ha! \xbfA m\xed? \xbfBatirme en\nduelo con gente como t\xfa?\n\nVale.\n\nTe dar\xe9 una muestra de lo\nque es una cat\xe1strofe.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(134)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2F9C, map_56_state_01_08EF2F9C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_NOAH, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This can't be!\n\nMy skills are superior to\nyours in every way!\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas normal.\n\nJe suis en tout point\nsup\xe9rieur \xe0 toi...\n\n")
  LANGUAGE_TEXT(2, "Das ist unlogisch.\n\nIch bin dir in jeder\nHinsicht \xfcberlegen...\n\n")
  LANGUAGE_TEXT(3, "\xc8 illogico.\n\nSono superiore a te in ogni\nmodo possibile...\n\n")
  LANGUAGE_TEXT(4, "Esto no es l\xf3gico.\n\nSoy superior a ti lo mires\npor donde lo mires...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FA8, map_56_state_01_08EF2FA8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DARK_MARIK, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hahahahahahaha!\n\nI'll destroy you and plunge\nthe world into darkness!\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha ha !\n\nD\xe9truire ! Je vais\nfaire sombrer le monde\n\ndans les t\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Hahahahahahaha!\n\nZerst\xf6ren! Ich versenke\ndie Welt in Dunkelheit!\n\n")
  LANGUAGE_TEXT(3, "Hahahahahahaha!\n\nDistruzione! Far\xf2 piombare\nil mondo nelle tenebre!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajajajajajaja!\n\n\xa1Destrucci\xf3n! \xa1Sumir\xe9 al\nmundo en la oscuridad!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FB4, map_56_state_01_08EF2FB4, 0x08EF2FC0, 0x08F0404C)
  PORTRAIT(PORTRAIT_DARK_MARIK, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'll annihilate you quick.\n\nIn fact, I'll beat you in\none turn!\n\nFuhahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Je vais te pulv\xe9riser\nsur-le-champ.\n\nTu seras KO\nen un tour de main !\n\nFouah ha ha ha !\n\n")
  LANGUAGE_TEXT(2, "Ich l\xf6sche dich im\nNu aus.\n\nDu bist doch mit einem\nSchlag K.O.!\n\nFuhahahhaha!\n\n")
  LANGUAGE_TEXT(3, "Ti far\xf2 fuori\nimmediatamente.\n\nBaster\xe0 un solo turno\nper metterti k.o.!\n\nUahuahuahuahuah!\n\n")
  LANGUAGE_TEXT(4, "Te destruir\xe9\ninstant\xe1neamente.\n\n\xa1Ser\xe1 un solo asalto\npor KO!\n\n\xa1Jajajajajajaja!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(135)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FC0, map_56_state_01_08EF2FC0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_DARK_MARIK, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wh-what? How could I lose...\n\nJust wait. I will send you\nto the Shadow Realm in\n\ntime! Ha ha ha...\n\n")
  LANGUAGE_TEXT(1, "Qu-quoi ? Ce sont\nles types de ton genre\n\nqui m'ont pouss\xe9\njusqu'ici...\n\nPour toi aussi, ce sont\nles t\xe9n\xe8bres garanties...\n\n")
  LANGUAGE_TEXT(2, "W-was? Jemand wie du hat\nmich so weit getrieben...\n\nDamit ist auch dir ein Platz\nin der Finsternis sicher...\n\n")
  LANGUAGE_TEXT(3, "Che cosa? Quelli come te mi\nhanno spinto fin qui...\n\nTi sei pure assicurato un\nposto nelle tenebre...\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9? Los que son como t\xfa\nme forzaron a llegar\n\ntan lejos...\n\nEsto garantiza tu lugar\nen la oscuridad...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FCC, map_56_state_01_08EF2FCC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DARK_BAKURA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hahahahaha!\n\nI don't think it's wise for\nyou to get to know me!\n\n")
  LANGUAGE_TEXT(1, "Hi ha ha ha !\n\nPas de familiarit\xe9s\navec moi !\n\n")
  LANGUAGE_TEXT(2, "Hihahahaha!\n\nVersuch nicht, dich bei mir\neinzuschmeicheln!\n\n")
  LANGUAGE_TEXT(3, "Hiahahahahaha!\n\nNon fare troppo\nl'amicone con me!\n\n")
  LANGUAGE_TEXT(4, "\xa1jajajajajaja!\n\n\xa1No te hagas el bueno\nconmigo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FD8, map_56_state_01_08EF2FD8, 0x08EF2FE4, 0x08F0404C)
  PORTRAIT(PORTRAIT_DARK_BAKURA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My occult deck will banish\nyou into the shadows!\n\n")
  LANGUAGE_TEXT(1, "Avec mon Deck occulte, tu\nseras banni aux t\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Mein okkultes Deck verbannt\ndich in die Finsternis!\n\n")
  LANGUAGE_TEXT(3, "Il mio deck occulto ti\nspedir\xe0 nelle tenebre!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mi deck oculta te sumir\xe1\nen la oscuridad!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(136)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FE4, map_56_state_01_08EF2FE4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_DARK_BAKURA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Grr... I won't forget\nthis... I will get my\n\nrevenge!\n\n")
  LANGUAGE_TEXT(1, "Grrr... Souviens-toi de\n\xe7a... Je vais t'an\xe9antir...\n\n")
  LANGUAGE_TEXT(2, "Grr... Denk daran...\nIch erledige dich...\n\n")
  LANGUAGE_TEXT(3, "Grr... Ricordati questo...\n\nTi far\xf2 abbassare la\ncresta!\n\n")
  LANGUAGE_TEXT(4, "Grr... Recuerda esto...\nTe vencer\xe9...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FF0, map_56_state_01_08EF2FF0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, what can be seen\nand not seen at the same\n\ntime?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, c'est quelque\nchose de tangible\n\nmais de non visible.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, es ist sp\xfcrbar,\naber nicht sichtbar.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, \xe8 qualcosa di\ntangibile, ma non visibile.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, es algo\ntangible, pero no visible.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF2FFC, map_56_state_01_08EF2FFC, 0x08EF3008, 0x08F0404C)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I accept your challenge!\n\n")
  LANGUAGE_TEXT(1, "J'accepte ton d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Ich nehme deine\nHerausforderung an!\n\n")
  LANGUAGE_TEXT(3, "Accetto la sfida!\n\n")
  LANGUAGE_TEXT(4, "\xa1Acepto el reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(137)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3008, map_56_state_01_08EF3008, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You've become much stronger,\n{PLAYER}.\n\nBut you won't win so easily\nnext time.\n\n")
  LANGUAGE_TEXT(1, "Tu es maintenant bien\nplus fort, {PLAYER}.\n\nMais la prochaine fois,\nl'issue ne sera pas\n\nla m\xeame.\n\n")
  LANGUAGE_TEXT(2, "Du bist viel st\xe4rker\ngeworden, {PLAYER}.\n\nAber beim n\xe4chsten Mal sieht\ndas Ende anders aus.\n\n")
  LANGUAGE_TEXT(3, "Sei diventato molto pi\xf9\nforte, {PLAYER}.\n\nMa la prossima volta\nnon finir\xe0 cos\xec.\n\n")
  LANGUAGE_TEXT(4, "Ahora eres m\xe1s fuerte,\n{PLAYER}.\n\nPero no ser\xe1 as\xed\nla pr\xf3xima vez.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3014, map_56_state_01_08EF3014, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DARK_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}...\n\nYou're goin' down...\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}...\n\nJe vais te r\xe9duire en\nbouillie...\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}...\n\nIch mache dich fertig...\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}...\n\nTi batter\xf2...\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}...\n\nTe voy a reventar...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3020, map_56_state_01_08EF3020, 0x08EF302C, 0x08F0404C)
  PORTRAIT(PORTRAIT_DARK_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Even your family won't\nrecognize you after I\n\nfinish pummeling ya!\n\n")
  LANGUAGE_TEXT(1, "Je vais te r\xe9duire\nen petite bouillie.\n\n")
  LANGUAGE_TEXT(2, "Ich mache dich richtig\nfertig.\n\n")
  LANGUAGE_TEXT(3, "Non avrai scampo.\n\n")
  LANGUAGE_TEXT(4, "Te voy a reventar\npor completo.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(138)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF302C, map_56_state_01_08EF302C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_DARK_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My... Memories...\n\nI remember I'm a...\nTrue duelist...\n\nGwaaaaaaaaaaah!\n\n")
  LANGUAGE_TEXT(1, "Ma... m\xe9moire...\n\nMa m\xe9moire...\nde duelliste...\n\nGouaaaaah !\n\n")
  LANGUAGE_TEXT(2, "Mein... Ged\xe4chtnis...\n\nMein Duellanten-\nged\xe4chtnis...\n\nGwaaaaaaaaaaah!\n\n")
  LANGUAGE_TEXT(3, "La mia... memoria...\n\nMemoria...\ndel duellante...\n\nUaaaaaaaaaaah!\n\n")
  LANGUAGE_TEXT(4, "Mi... memoria...\n\nLa memoria...\ndel duelista...\n\n\xa1Guaaaaaaaaaaah!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3038, map_56_state_01_08EF3038, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You want to know who my\nstrongest rival is?\n\nHeh. One thing's for\ncertain. It's not you.\n\n")
  LANGUAGE_TEXT(1, "Le chemin de la gloire...\n\nQu'est-ce qui m'attend\nau bout de ce chemin...\n\nMmm. En tout cas, un truc\nest s\xfbr, ce n'est pas toi.\n\n")
  LANGUAGE_TEXT(2, "Mein Weg zum Ruhm... Was\nerwartet mich am Ende...\n\nHmph. Eins ist sicher.\nDu bestimmt nicht.\n\n")
  LANGUAGE_TEXT(3, "La mia strada verso la\ngloria... Cosa mi attende\n\nalla fine... Be', di certo\nnon si tratta di te.\n\n")
  LANGUAGE_TEXT(4, "Mi camino a la gloria...\nLo que me espera\n\nal final...\n\nVaya. Una cosa es segura.\nNo eres t\xfa.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3044, map_56_state_01_08EF3044, 0x08EF3050, 0x08F0404C)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "A duel can start anyplace\nand anytime two duelists\n\nmeet.\n\nI accept your duel!\n\n")
  LANGUAGE_TEXT(1, "Le duel a lieu l\xe0 o\xf9 les\nduellistes se rencontrent.\n\nTon d\xe9fi est accept\xe9.\n\n")
  LANGUAGE_TEXT(2, "Wo sich Duellanten treffen,\nduellieren sie sich auch.\n\nIch nehme deine\nHerausforderung an.\n\n")
  LANGUAGE_TEXT(3, "I duellanti si battono\nladdove si incontrano.\n\nAccetto la sfida.\n\n")
  LANGUAGE_TEXT(4, "Donde los duelistas se\nencuentran, es decir\n\ndonde se baten.\n\nAcepto el reto.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(139)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3050, map_56_state_01_08EF3050, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I... Lost?\n\nGrr... You better not lose\nto anyone else!\n\nNot after you'd beaten me!\n\n")
  LANGUAGE_TEXT(1, "J'ai... perdu ?\n\nGrr... J'esp\xe8re que\ntu ne perdras plus\n\ncontre qui que ce soit !\nPas apr\xe8s m'avoir battu !\n\n")
  LANGUAGE_TEXT(2, "Ich... verloren?\n\nGrr... Wenn du mich schon\ngeschlagen hast...\n\nDann gewinn wenigstens\nauch jedes weitere Duell!\n\n")
  LANGUAGE_TEXT(3, "Io... ho perso?\nGrr... Faresti bene a\n\nnon perdere con\nnessun altro!\n\nNon dopo avermi\nbattuto!\n\n")
  LANGUAGE_TEXT(4, "He... \xbfperdido?\n\nGrr... Mejor que no pierdas\n\xa1con nadie m\xe1s!\n\n\xa1No despu\xe9s de que\nme hayas vencido!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF305C, map_56_state_01_08EF305C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The finest drink,\nThe tastiest Gorgonzola\n\ncheese...\n\nThe funniest comic book in\nthe world...\n\nWhat more can any man want?\n\n")
  LANGUAGE_TEXT(1, "Le meilleur des vins,\ndu Gorgonzola...\n\nLa meilleure BD\nau monde...\n\nVoil\xe0, c'est \xe7a,\nla vraie vie...\n\n")
  LANGUAGE_TEXT(2, "Die erlesensten Weine,\nGorgonzola-K\xe4se...\n\nDie besten Comic-B\xfccher\nder Welt...\n\nDas sind f\xfcr mich\nhimmlische Zeiten.\n\n")
  LANGUAGE_TEXT(3, "Il migliore dei vini,\ndel gorgonzola...\n\nIl meglio dei libri di\nfumetti del mondo...\n\nPer me \xe8 il modo migliore\ndi passare il tempo...\n\n")
  LANGUAGE_TEXT(4, "El mejor de los vinos,\nQueso gorgonzola...\n\nEl mejor de los libros\nde c\xf3mics del mundo...\n\nA eso llamo yo el mejor\nde todos los tiempos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3068, map_56_state_01_08EF3068, 0x08EF3074, 0x08F0404C)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I've scanned your mind.\n\nI can read your strategies\nas if it were an open book!\n\nI hate to say this, but you\nhave no chance to win!\n\n")
  LANGUAGE_TEXT(1, "Lecture de pens\xe9e !\n\nJe peux lire tes pens\xe9es\ncomme dans un livre\n\nouvert !\n\nD\xe9sol\xe9 de te l'apprendre\nmais...\n\ntu n'as aucune chance\nde gagner !\n\n")
  LANGUAGE_TEXT(2, "Gehirnscan!\n\nIch kann deine Gef\xfchle wie\nein offenes Buch lesen!\n\nIch sage es nur ungern, aber\ndu hast keine Chance!\n\n")
  LANGUAGE_TEXT(3, "Scansione mentale!\n\nPosso leggerti le emozioni\ncome se fossi un libro\n\naperto! Mi rincresce dirlo,\nma non hai scampo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Esc\xe1ner mental!\n\n\xa1Puedo leer tus emociones\ncomo un libro abierto!\n\nOdio decirlo, pero \xa1no\ntienes nada que hacer!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(140)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3074, map_56_state_01_08EF3074, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Noooooo!\n\nI'm the creator of Duel\nMonsters!\n\nLosing is not in the cards!\nUnbelievable!\n\n")
  LANGUAGE_TEXT(1, "Noooooon !\n\nJe suis le cr\xe9ateur des\nDuel Monsters !\n\nLes cartes ne veulent pas\nque je perde ! Impossible !\n\n")
  LANGUAGE_TEXT(2, "Neiiiiin!\n\nIch habe die Duel\nMonster erschaffen!\n\nEine Niederlage steht f\xfcr\nmich nicht in den Karten!\n\nUnm\xf6glich!\n\n")
  LANGUAGE_TEXT(3, "Noooooo!\n\nHo creato io\nDuel Monsters!\n\nNelle carte non c'\xe8 scritta\nla mia sconfitta!\n\nIncredibile!\n\n")
  LANGUAGE_TEXT(4, "\xa1Noooooo!\n\n\xa1Soy el creador de los Duel\nMonsters!\n\n\xa1No est\xe1 en las cartas que\npierda! \xa1Incre\xedble!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3080, map_56_state_01_08EF3080, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I am Paradox.\n\nI am the sage for all\nduelists.\n\n")
  LANGUAGE_TEXT(1, "Je m'appelle Paradox.\n\nJe suis le sage\nde tous les duellistes.\n\n")
  LANGUAGE_TEXT(2, "Ich bin Paradox.\n\nIch bin der Weise\naller Duellanten.\n\n")
  LANGUAGE_TEXT(3, "Mi chiamo Paradox.\n\nSono il saggio di tutti\ni duellanti.\n\n")
  LANGUAGE_TEXT(4, "Soy Paradox.\n\nSoy el sabio de todos\nlos duelistas.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF308C, map_56_state_01_08EF308C, 0x08EF3098, 0x08F0404C)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You're challenging me?\nEither you're brave...\n\nOr you underestimate me...\n\n")
  LANGUAGE_TEXT(1, "Tu me lances un d\xe9fi ?\nTu es courageux...\n\nOu alors tu me\nsous-estimes...\n\n")
  LANGUAGE_TEXT(2, "Du forderst mich heraus?\nDu bist entweder mutig...\n\nOder du untersch\xe4tzt mich...\n\n")
  LANGUAGE_TEXT(3, "Tu mi stai sfidando?\nO hai del coraggio...\n\nOppure mi sottovaluti...\n\n")
  LANGUAGE_TEXT(4, "\xbfMe est\xe1s retando?\nO eres valiente...\n\nO me subestimas...\n\n")
  END_LANGUAGE_TEXT()
  DUEL(141)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF3098, map_56_state_01_08EF3098, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_PARADOX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Perhaps my time has\npassed...\n\n")
  LANGUAGE_TEXT(1, "Il est peut-\xeatre temps\npour ceux de mon \xe2ge\n\nde se retirer...\n\n")
  LANGUAGE_TEXT(2, "Vielleicht ist die Zeit f\xfcr\nTypen wie mich zu Ende...\n\n")
  LANGUAGE_TEXT(3, "Forse \xe8 finita l'epoca\ndi quelli come me...\n\n")
  LANGUAGE_TEXT(4, "Quiz\xe1s ha terminado la era\nde los que son como yo...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF30A4, map_56_state_01_08EF30A4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My name is Shadi...\n\nYou have a room in your\nsoul...\n\nWhich I will disassemble!\n\n")
  LANGUAGE_TEXT(1, "Je m'appelle Shadi...\n\nCe que ton c\u0153ur\ncache \xe0 l'int\xe9rieur...\n\nLaisse-moi\ny mettre de l'ordre.\n\n")
  LANGUAGE_TEXT(2, "Mein Name ist Shadi...\n\nDer Raum in deinem\nHerzen...\n\nIch gestalte ihn v\xf6llig\nneu f\xfcr dich.\n\n")
  LANGUAGE_TEXT(3, "Mi chiamo Shadi...\n\nLa stanza nel tuo cuore...\nCi penso io a riordinarla.\n\n")
  LANGUAGE_TEXT(4, "Soy Shadi...\n\nEl cuarto dentro de\ntu coraz\xf3n...\n\nLo reorganizar\xe9 para ti.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF30B0, map_56_state_01_08EF30B0, 0x08EF30BC, 0x08F0404C)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This duel has been foretold\nmillenniums ago...\n\nCan you overcome my test?\n\n")
  LANGUAGE_TEXT(1, "Ce duel s'\xe9tend sur\nplus de {BYTE_8252}.{BYTE_824F}{BYTE_824F}{BYTE_824F} ans...\n\nVas-tu pouvoir relever\nle d\xe9fi que je te pose ?\n\n")
  LANGUAGE_TEXT(2, "Dieses Duell umspannt\n\xfcber {BYTE_8252}.{BYTE_824F}{BYTE_824F}{BYTE_824F} Jahre...\n\nOb du mit meiner Heraus-\nforderung fertig wirst?\n\n")
  LANGUAGE_TEXT(3, "Questo duello ricopre\nben {BYTE_8252}{BYTE_824F}{BYTE_824F}{BYTE_824F} anni...\n\nPensi di vincere la sfida\nche rappresento?\n\n")
  LANGUAGE_TEXT(4, "Este duelo abarca m\xe1s de\n{BYTE_8252}.{BYTE_824F}{BYTE_824F}{BYTE_824F} a\xf1os...\n\n\xbfPodr\xedas superar el reto\nque represento?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(142)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF30BC, map_56_state_01_08EF30BC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(25)
  PORTRAIT(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have prevailed...\nI am thoroughly defeated.\n\n")
  LANGUAGE_TEXT(1, "Tu as gagn\xe9...\nJ'ai perdu cette bataille.\n\n")
  LANGUAGE_TEXT(2, "Der Sieg ist dein...\nIch habe verloren.\n\n")
  LANGUAGE_TEXT(3, "Hai prevalso...\nRiconosco la sconfitta.\n\n")
  LANGUAGE_TEXT(4, "Has ganado...\n\nMe has derrotado\npor completo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
