#include "event_macros.h"
#include "overworld.h"

/* map_06_state_13: map 6 state 13 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD08, map_06_state_13_08E5CD08, 0x08F04040, 0x08F04040)
  PORTRAIT(9, 0, 8)
  LANGUAGE_TEXT(0, "You did it, {PLAYER}.\n\nYou got rid of the Neo\nGhouls... Awesome!\n\nBut... Your battle isn't\nover yet, is it?\n\n{PLAYER}, I know you can\nwin!\n\nDon't worry about the Town\nof Domino. We'll take care\n\nof it.\n\nGo on ahead and duel like a\nchampion!\n\n")
  LANGUAGE_TEXT(1, "Tu as r\xe9ussi, {PLAYER}.\n\nTu nous as d\xe9barrass\xe9\ndes Neo Ghouls. G\xe9nial !\n\nMais... Ton combat\nn'est pas termin\xe9, si ?\n\n{PLAYER}, tu ne\npeux pas perdre !\n\nNe t'inqui\xe8te pas pour\nDomino, nous sommes l\xe0.\n\nContinue et bats-toi\navec conviction !\n\n")
  LANGUAGE_TEXT(2, "Du hast es geschafft,\n{PLAYER},\n\ndie Neo Ghouls loszu-\nwerden... Beeindruckend!\n\nAber... Dein Kampf ist\nnoch nicht vorbei, oder?\n\n{PLAYER}, keine Angst:\nDu kannst nicht verlieren!\n\nMach dir keine Sorgen um\nDomino, wir sind ja da.\n\nGeh nur und schlag dich\ntapfer!\n\n")
  LANGUAGE_TEXT(3, "Ce l'hai fatta, {PLAYER}.\n\nEliminare i Neo Ghouls...\n\xc8 stato fantastico!\n\nMa... La tua battaglia\nnon \xe8 ancora finita, eh?\n\nEhi, {PLAYER},\nnon puoi perdere!\n\nNon preoccuparti per\nDomino, ci saremo noi.\n\nTu vai avanti e combatti\nuna buona battaglia!\n\n")
  LANGUAGE_TEXT(4, "Lo hiciste, {PLAYER}.\n\nLibrarte de los Neo\nGhouls... \xa1Brutal!\n\nPero... Tu batalla no ha\nterminado a\xfan, \xbfno?\n\nPero, {PLAYER}, \xa1no\npuedes perder!\n\nNo te preocupes por Domino,\nestaremos aqu\xed.\n\n\xa1Ve y pelea como\nes debido!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD14, map_06_state_13_08E5CD14, 0x08E5CD20, 0x08F0404C)
  PORTRAIT(9, 0, 8)
  LANGUAGE_TEXT(0, "Sure! If you think you can\nlearn something from me,\n\nI'll duel you!\n\n")
  LANGUAGE_TEXT(1, "Bien s\xfbr ! Si tu crois\nque je suis assez fort,\n\nje suis ton homme !\n\n")
  LANGUAGE_TEXT(2, "Sicher! Wenn du mich f\xfcr\ngut genug h\xe4ltst -\n\nich stehe dir zur Verf\xfcgung!\n\n")
  LANGUAGE_TEXT(3, "Certo! Se pensi che\nsia abbastanza bravo,\n\nsono pronto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Claro! Si crees que soy\nlo bastante bueno,\n\n\xa1soy tu hombre!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(92)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD20, map_06_state_13_08E5CD20, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(6)
  PORTRAIT(9, 0, 8)
  LANGUAGE_TEXT(0, "I hope that was good\npractice.\n\n")
  LANGUAGE_TEXT(1, "J'ai au moins \xe9t\xe9 assez bon\npour un entra\xeenement, non ?\n\n")
  LANGUAGE_TEXT(2, "War ich wenigstens gut\nals Sparringpartner?\n\n")
  LANGUAGE_TEXT(3, "Sono stato bravo per\nfarti fare pratica, almeno?\n\n")
  LANGUAGE_TEXT(4, "Dime, \xbfpor lo menos\nhe sido bueno para\n\npracticar?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD2C, map_06_state_13_08E5CD2C, 0x08F04040, 0x08F04040)
  PORTRAIT(31, 0, 8)
  LANGUAGE_TEXT(0, "We'll look after things\nwhile you're gone,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "On s'occupera de tout en\nton absence, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Wir werden uns in deiner\nAbwesenheit um alles\n\nk\xfcmmern, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Ci occuperemo noi\ndi tutto in tua assenza,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Cuidaremos de todo en tu\nausencia, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD38, map_06_state_13_08E5CD38, 0x08E5CD44, 0x08F0404C)
  PORTRAIT(31, 0, 8)
  LANGUAGE_TEXT(0, "No problem! I'll duel if you\nwant me to.\n\n")
  LANGUAGE_TEXT(1, "Pas de probl\xe8me !\n\nJe me battrais en\nduel si tu le veux.\n\n")
  LANGUAGE_TEXT(2, "Kein Problem! Wenn du magst,\nduelliere ich mich mit dir.\n\n")
  LANGUAGE_TEXT(3, "Non c'\xe8 problema! Io duello\nse vuoi questo da me.\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale! Luchar\xe9 si\nas\xed lo quieres.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(93)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD44, map_06_state_13_08E5CD44, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(6)
  PORTRAIT(31, 0, 8)
  LANGUAGE_TEXT(0, "I guess I'm too weak to duel\nyou, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je crois que\nje suis trop faible\n\npour me battre\ncontre toi, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich bin wohl zu schwach\nf\xfcr ein Duell gegen dich,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Mi sa che sono troppo\ndebole per duellare con\n\nte, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Creo que estoy muy\nd\xe9bil para batirme\n\ncontigo, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD50, map_06_state_13_08E5CD50, 0x08F04040, 0x08F04040)
  PORTRAIT(32, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, good luck.\n\nI hope Joey doesn't get in\nthe way...\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, fais de\nton mieux.\n\nJ'esp\xe8re que mon fr\xe8re\nne fera pas de b\xeatises...\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, bitte gib\ndein Bestes. Ich hoffe,\n\ndass dir mein Bruder keine\nProbleme machen wird...\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, ti prego\ndi fare del tuo meglio.\n\nSpero che mio fratello\nnon faccia problemi...\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, hazlo lo\nmejor que puedas.\n\nEspero que mi hermano\nno cause problemas...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD5C, map_06_state_13_08E5CD5C, 0x08F04040, 0x08F04040)
  PORTRAIT(32, 0, 8)
  LANGUAGE_TEXT(0, "I wouldn't be much of a\nchallenge, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas assez forte\npour toi, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich w\xe4re f\xfcr dich nicht\ngut genug, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Non ti sarei di grande\naiuto, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "No ser\xeda bueno\npara ti, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
