#include "event_macros.h"
#include "overworld.h"

/* map_32_state_08: map 32 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08EB912C, map_32_state_08_08EB912C, 0x08EB9138, 0x08EB9168)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("You'll proceed no further\nwithout defeating me!\n\n")
  DUEL(81)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9138, map_32_state_08_08EB9138, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(242)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Most impressive.\nYou deserve a card.\n\nTake this Celtic Guardian.\n\n")
  ADD_CARD(41)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Your path is clear.\nAdvance.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(2, 2)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN4)
  FALLTHROUGH()
END_EVENT_SCRIPT()
