#include "event_macros.h"

/* map_10_state_03: map 10 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E63278, map_10_state_03_08E63278, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls are gone,\nbut...\n\nSomething doesn't feel\nright.\n\nI hope nothing terrible\nhappens.\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls sont\npartis, mais...\n\nJ'ai toujours cet\nhorrible pressentiment.\n\nJ'esp\xe8re qu'il ne va\nrien se passer d'horrible.\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls sind fort,\naber...\n\nIch habe noch immer dieses\nsehr ungute Gef\xfchl.\n\nIch hoffe, es wird nichts\nSchreckliches geschehen.\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls se ne sono\nandati, ma...Ho ancora\n\nuna tremenda sensazione\ndi sventura. Spero che\n\nnon accada niente di\nterribile.\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls se\nhan ido, pero...\n\nA\xfan tengo este horrible\nsentimiento de desgracia.\n\nEspero que no pase\nnada malo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E63284, map_10_state_03_08E63284, 0x08E63290, 0x08E632A8)
  CHECK_FLAG(127)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E63290, map_10_state_03_08E63290, 0x08E6329C, 0x08F0404C)
  LANGUAGE_TEXT(0, "I'll show you that I've\nimproved.\n\n")
  LANGUAGE_TEXT(1, "Je vais te montrer que je\nme suis am\xe9lior\xe9.\n\n")
  LANGUAGE_TEXT(2, "Ich zeige dir, dass ich etwas\nbesser geworden bin.\n\n")
  LANGUAGE_TEXT(3, "Ti dimostrer\xf2 che ho\nfatto progressi.\n\n")
  LANGUAGE_TEXT(4, "Te demostrar\xe9 que\nlo hago un poco mejor.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(94)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6329C, map_10_state_03_08E6329C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(7)
  LANGUAGE_TEXT(0, "Shucks. I guess I'm not good\nenough yet.\n\n")
  LANGUAGE_TEXT(1, "Zut. J'imagine que je ne\nsuis pas encore assez bon.\n\n")
  LANGUAGE_TEXT(2, "Mist. Ich bin wohl doch\nnoch nicht gut genug.\n\n")
  LANGUAGE_TEXT(3, "Maledizione. Mi sa\nche non sono ancora\n\nabbastanza bravo.\n\n")
  LANGUAGE_TEXT(4, "Vaya. Parece que no soy a\xfan\nlo bastante bueno.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(127)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E632A8, map_10_state_03_08E632A8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "After I make my deck\nstronger, okay?\n\n")
  LANGUAGE_TEXT(1, "Peut-\xeatre apr\xe8s avoir\nrenforc\xe9 mon Deck, OK ?\n\n")
  LANGUAGE_TEXT(2, "Wenn ich mein Deck noch\netwas gest\xe4rkt habe, okay?\n\n")
  LANGUAGE_TEXT(3, "Dopo che avr\xf2 rafforzato un\npo' pi\xf9 il mio deck, okay?\n\n")
  LANGUAGE_TEXT(4, "Despu\xe9s de que refuerce un\npoco m\xe1s mi deck, \xbfvale?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
