#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_43_state_03: map 43 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EDA644, map_43_state_03_08EDA644, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  LOAD_SPRITE(2, SPRITE_CHEVALIER)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13)
  DELAY(8)
  WALK_OBJECT_X(1, 112)
  DELAY(16)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Gawry nida!")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 8)
  DELAY(16)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Gawry nida!")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_260)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You'll go no further!")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_260)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Gawry!")
  SET_FLAG(EVENT_FLAG_ENTERED_DUNGEON)
  FALLTHROUGH()
END_EVENT_SCRIPT()
