#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_32_state_01: map 32 state 1 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EB8FC4, map_32_state_01_08EB8FC4, 0x08EB8FDC, 0x08EB8FDC)
  LOAD_SPRITE(1, SPRITE_DOX)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_DOX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB8FDC, map_32_state_01_08EB8FDC, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Aiyah! This is the Great Wall of China.",
      "It is one of China's treasures. There's nothing",
      "finer."
  )
  SET_FLAG(EVENT_FLAG_TALKED_TO_DOX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB8FD0, map_32_state_01_08EB8FD0, 0x08EB8FDC, 0x08EB8FE8)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_DOX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB8FE8, map_32_state_01_08EB8FE8, 0x08EB8FF4, 0x08EB8FF4)
  CHECK_FLAG(EVENT_FLAG_JOEY_FOUND_PARA_AND_DOX_SUSPICIOUS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB8FF4, map_32_state_01_08EB8FF4, EVENT_NOP, EVENT_NOP)
  TEXT("Aiyah! I do not know how to duel.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
