#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_54_state_01: map 54 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EE9C24, map_54_state_01_08EE9C24, 0x08EE9C30, 0x08EE9C3C)
  LOAD_SPRITE(1, SPRITE_SETO)
  LOAD_SPRITE(2, SPRITE_ISHIZU)
  LOAD_SPRITE(3, SPRITE_MOKUBA)
  LOAD_SPRITE(4, SPRITE_CHEVALIER)
  LOAD_SPRITE(5, SPRITE_VIDEO_CARD)
  PLAY_MUSIC(MUSIC_INSIDE_PEGASUS_CASTLE)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO, "Go, Blue-Eyes White Dragon!")
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO, "White Lightning Attack!")
  PLAY_MUSIC(MUSIC_338)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_ATTACK_BOTTOM_MIDDLE)
  DELAY(16)
  PLAY_MUSIC(MUSIC_284)
  SLIDE_OBJECT(4, 2, 16)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_TELEPORT)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Humph. So you finally showed up. But you're too late.",
      "That Pegasus... I will crush him myself!"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(2, 72)
  DELAY(16)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Kaiba... You cannot win alone... One Egyptian God",
      "Card isn't enough.",
      "You have no chance.",
      "Not against Pegasus and Reshef the Dark Being."
  )
  TALK(PORTRAIT_SETO, 1, PORTRAIT_POSITION_AUTO,
      "My deck is perfect!",
      "Whoever the opponent may be, defeat isn't in the cards!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(3, 60, 18, 0, 0, 0)
  WALK_OBJECT_Y(3, 32)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_1 | OBJECT_2)
  DELAY(8)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO, "Then duel me, big brother, with your perfect deck.")
  TALK(PORTRAIT_SETO, 6, PORTRAIT_POSITION_AUTO, "Wh-what? Mokuba? Wh-what are you saying?")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
      "Reshef is going to rule this world anyway.",
      "It's better to quit fighting and accept fate."
  )
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Mokuba's spirit is under control...")
  TALK(PORTRAIT_SETO, 5, PORTRAIT_POSITION_AUTO, "Pegasus! How dare you!")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
      "Big brother, will you join me?",
      "Or would you like to duel?"
  )
  TALK(PORTRAIT_SETO, 3, PORTRAIT_POSITION_AUTO,
      "Mokuba...",
      "I... I can't duel against Mokuba..."
  )
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_2)
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, you must duel in Kaiba's place.",
      "That is the only way to break the mind control over",
      "Mokuba."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_NONE, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C30, map_54_state_01_08EE9C30, 0x08EE9C48, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_3)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
      "Huh? {PLAYER} wants to duel me?",
      "Sure. You have to ante your Egyptian God Card.",
      "I don't care who I have to duel as long as I can get",
      "an Egyptian God Card."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Grr... Mokuba...")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
      "Big brother, there's no need to be sad.",
      "After {PLAYER}, you're next!",
      "Ahahahahahaha!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  WALK_OBJECT_Y(0, 52)
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_3)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_POSSESSED, PORTRAIT_POSITION_AUTO,
      "Don't give me that look!",
      "I'll show you how it feels to lose!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 37)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 63)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 42)
  DELAY(16)
  DUEL(DUELIST_MOKUBA_119)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C48, map_54_state_01_08EE9C48, 0x08EE9C54, 0x08F0404C)
  PLAY_MUSIC(MUSIC_369)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, PORTRAIT_POSITION_AUTO,
      "Arrggh! M-my head! Seto, it hurts!",
      "Help me, Seto!"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(8)
  TALK(PORTRAIT_SETO, 6, PORTRAIT_POSITION_AUTO, "Mokuba!")
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(1, 54)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 50)
  DELAY(8)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Mokuba, have you regained your senses?")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO, "Seto... I... I...")
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Don't say another word. It's over, Mokuba.")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO, "Big brother...")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 34)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 37)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(3, 68)
  MOVE_OBJECT(3, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_405)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I hate to say this, but I owe you one.",
      "You have to duel Pegasus next...",
      "You need my Egyptian God Card, don't you?",
      "Fine... I could just hand it to you...."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_2)
  DELAY(8)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Kaiba...")
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "But you and I are duelists.",
      "Therefore, the only way you can get my card is in a",
      "duel!",
      "That's all that needs to be said.",
      "Now, come on, {PLAYER}.",
      "My strongest monster will annhilate you!",
      "Obelisk the Tormentor will decide the outcome!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 42)
  DELAY(32)
  DUEL(DUELIST_SETO_120)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C54, map_54_state_01_08EE9C54, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Urrrgh...")
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Your powers were evenly matched...",
      "But {PLAYER}'s pure spirit won the duel.",
      "He also received the help of his fellow duelists...",
      "Perhaps his pure spirit can counter the Dark Being."
  )
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "There's nothing for me to say.",
      "You earned this card.",
      "I don't care if you duel Pegasus or Reshef...",
      "Just don't lose using my best card!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_285)
  SHOW_OBJECT(5, 60, 46, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_286)
  SLIDE_OBJECT(5, 0, 16)
  DELAY(32)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(32)
  TEXT("Received Obelisk the Tormentor!")
  PLAY_MUSIC(MUSIC_701)
  DELAY(240)
  DELAY(80)
  PAGE_BREAK()
  ADD_CARD(234)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Come, {PLAYER}, we must go.",
      "The time has come to seal Reshef the Dark Being."
  )
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C3C, map_54_state_01_08EE9C3C, 0x08EE9C30, 0x08EE9C3C)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "But... If you refuse...",
      "Reshef the Dark Being will rule the world.",
      "Please, {PLAYER}!",
      "You must duel in Kaiba's place!"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C60, map_54_state_01_08EE9C60, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Hurry up and beat Pegasus.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C78, map_54_state_01_08EE9C78, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Come, {PLAYER}, we must go.",
      "The time has come to seal Reshef the Dark Being."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C6C, map_54_state_01_08EE9C6C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO, "...")
  FALLTHROUGH()
END_EVENT_SCRIPT()
