#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_60_state_05: map 60 state 5 */

LOAD_SPRITE(1, SPRITE_MARIK)
LOAD_SPRITE(2, SPRITE_ODION)
PLAY_MUSIC(MUSIC_MARIK_ISHTAR)
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, you've finally\n"
    "succeeded.\n\n"
    "You have obtained the secret\n"
    "behind the Phoenix Mode.\n\n"
)
TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Master Marik...\n\n"
)
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Yes, I know, Odion.\n\n"
    "I am going to awaken\n"
    "{PLAYER}'s The Winged\n\n"
    "Dragon of Ra so that he can\n"
    "use the Phoenix Mode.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_MARIK, 64)
DELAY(16)
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I'll need to see The Winged\n"
    "Dragon of Ra.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_285)
DELAY(16)
WALK_OBJECT_Y(SPRITE_MARIK, 48)
DELAY(16)
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Awaken! Phoenix Mode!\n\n"
)
PLAY_MUSIC(MUSIC_377)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPARKLE_RETURNS)
PLAY_MUSIC(MUSIC_385)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_LIGHTNING_KILLS_KEITH)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_22)
PLAY_MUSIC(MUSIC_386)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_PHOENIX_RA_TURNS_TO_FIREBALL)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_51)
SET_FLAG(EVENT_FLAG_LIGHT_THE_CANDLE_IN_MARIKS_ROOM)
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Phoenix! Be calm!\n\n"
    "Your enemy is the one who\n"
    "weakened the Egyptian God\n\n"
    "Cards.\n\n"
    "With {PLAYER}, you must\n"
    "smite that enemy!\n\n"
)
TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "What terrifying power...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_MARIK, 64)
DELAY(16)
PLAY_MUSIC(MUSIC_285)
REMOVE_CARD(240)
ADD_CARD(412)
DELAY(16)
WALK_OBJECT_Y(SPRITE_MARIK, 44)
MOVE_OBJECT(SPRITE_MARIK, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Received The Winged Dragon\n"
    "of Ra {BYTE_8169}Phoenix Mode{BYTE_816A}!\n\n"
)
TEXT
(
    "The deck adjustment menu\n"
    "will be opened."
)
PAGE_BREAK()
START_MENU()
TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "The Winged Dragon of Ra has\n"
    "fully awakened.\n\n"
    "What you do with its power\n"
    "is up to you, {PLAYER}.\n\n"
)
SET_FLAG(EVENT_FLAG_OBTAINED_PHOENIX_MODE)

EVENT_SCRIPT_REPLACEMENT(0x08F03A98, map_60_state_05_08F03A98, 0x08F03AA4, 0x08F03A98)
TEXT
  (
      "The deck adjustment menu\n"
      "will be opened."
  )
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()
