#include "event_macros.h"
#include "overworld.h"

/* map_23_state_07: map 23 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E953A8, map_23_state_07_08E953A8, 0x08F04040, 0x08F04040)
  SHOW_OBJECT(13, 68, 58, 0, 0, 0)
  PLAY_MUSIC(280)
  SHOW_OBJECT(3, 68, 50, 0, 1, 0)
  DELAY(16)
  PLAY_MUSIC(401)
  PORTRAIT(PORTRAIT_ATEM, 1, 1)
  LANGUAGE_TEXT(0, "It's been a long time,\npartner.\n\n")
  LANGUAGE_TEXT(1, "Ca faisait une \xe9ternit\xe9,\npartenaire.\n\n")
  LANGUAGE_TEXT(2, "Es ist lange her, Partner.\n\n")
  LANGUAGE_TEXT(3, "Ne \xe8 passato di\ntempo, socio.\n\n")
  LANGUAGE_TEXT(4, "Ha pasado mucho\ntiempo, socio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 1, 0)
  LANGUAGE_TEXT(0, "My other self...\n\nI... I thought I'd never see\nyou again.\n\n")
  LANGUAGE_TEXT(1, "L'autre moi...\nJe... Je croyais\n\nque je ne te\nreverrais jamais.\n\n")
  LANGUAGE_TEXT(2, "Mein anderes Ich...\n\nIch... Ich dachte, ich sehe\ndich nie wieder.\n\n")
  LANGUAGE_TEXT(3, "L'altro me stesso...\n\nPensavo che... non\nti avrei pi\xf9 rivisto.\n\n")
  LANGUAGE_TEXT(4, "Mi otro yo...\n\nC...Cre\xed que no\nte ver\xeda m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ATEM, 1, 1)
  LANGUAGE_TEXT(0, "Never forget that no matter\nwhat, we're always\n\ntogether.\n\n")
  LANGUAGE_TEXT(1, "Rien ne peut\nnous s\xe9parer.\n\n")
  LANGUAGE_TEXT(2, "Wir gehen zusammen\ndurch Dick und D\xfcnn.\n\n")
  LANGUAGE_TEXT(3, "Siamo sempre insieme,\nnella buona e nella\n\ncattiva sorte.\n\n")
  LANGUAGE_TEXT(4, "Siempre juntos, a las duras\no a las maduras.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 1, 0)
  LANGUAGE_TEXT(0, "Right!\n\n")
  LANGUAGE_TEXT(1, "Exact.\n\n")
  LANGUAGE_TEXT(2, "Ja.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0.\n\n")
  LANGUAGE_TEXT(4, "S\xed.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ATEM, 1, 1)
  LANGUAGE_TEXT(0, "Okay, partner! Let's get the\nEgyptian God Card back!\n\n")
  LANGUAGE_TEXT(1, "OK, partenaire !\n\nR\xe9cup\xe9rons la\ncarte de dieu !\n\n")
  LANGUAGE_TEXT(2, "Okay, Partner! Holen wir\nuns die G\xf6tterkarte zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Okay, socio! Riprendiamoci\nla carta divina!\n\n")
  LANGUAGE_TEXT(4, "\xa1De acuerdo, socio! \xa1Vamos\na por la carta del dios!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(301)
  WALK_OBJECT_Y(3, 56)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  FADE_SCREEN(2)
  CLEAR_FLAG(239)
  WARP(23, 9, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95474, map_23_state_07_08E95474, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95468, map_23_state_07_08E95468, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "I'm sorry about this...\nLet's exit.\n\n")
  LANGUAGE_TEXT(1, "Je suis d\xe9sol\xe9e...\nLaisse-nous sortir ici.\n\n")
  LANGUAGE_TEXT(2, "Es tut mir Leid...\nGehen wir.\n\n")
  LANGUAGE_TEXT(3, "Mi dispiace...\nUsciamo qui.\n\n")
  LANGUAGE_TEXT(4, "Siento esto...\nSalgamos por aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
