#include "event_macros.h"
#include "overworld.h"

/* map_00_state_08: map 0 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E34BF8, map_00_state_08_08E34BF8, 0x08E34C10, 0x08E34C1C)
  CHECK_FLAG(71)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C10, map_00_state_08_08E34C10, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "I see you have obtained the\nMillennium Rod.\n\nOnly two Millennium Items\nremain...\n\n")
  LANGUAGE_TEXT(1, "Je vois que vous avez obtenu\nla Baguette du mill\xe9nium.\n\nIl reste encore deux\nObjets du mill\xe9nium...\n\n")
  LANGUAGE_TEXT(2, "Wie ich sehe, habt ihr den\nMillenniumsstab.\n\nBleiben nur noch zwei\nMillenniumsgegenst\xe4nde...\n\n")
  LANGUAGE_TEXT(3, "Vedo che avete ottenuto\nla Bacchetta Millenaria.\n\nOra rimangono altri due\nOggetti Millenari...\n\n")
  LANGUAGE_TEXT(4, "Veo que ten\xe9is la\nVara del Milenio.\n\nAhora quedan dos\nObjetos del Milenio...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24579)
  PLAY_MUSIC(264)
  COMMAND_7C_ARG(7, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being's\npower grows catastrophic!\n\nTime is running out!\n\nPlease search for the next\nMillennium Item.\n\nThe next Millennium Item\nis.")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des t\xe9n\xe8bres\nest de plus en plus\n\npuissant et cela va nous\nmener \xe0 la catastrophe.\n\nNous n'avons plus\nbeaucoup de temps.\n\nCherchez le prochain\nObjet du mill\xe9nium.")
  LANGUAGE_TEXT(2, "Die Macht von Reschef dem\nDunklen nimmt furchtbare\n\nAusma\xdfe an. Uns bleibt\nnicht mehr viel Zeit.\n\nSucht bitte den n\xe4chsten\nMillenniumsgegenstand.")
  LANGUAGE_TEXT(3, "Il potere di Reshef il\nTenebroso si fa sempre\n\npi\xf9 catastrofico. Il tempo\nsta per scadere.\n\nCercate il prossimo Oggetto\nMillenario, vi prego.\n\nIl prossimo Oggetto\nMillenario si trova.")
  LANGUAGE_TEXT(4, "El poder de Reshef, el Ser\nOscuro crece sin parar.\n\nEl tiempo se acaba.\n\nPor favor, buscad el\nsiguiente Objeto del\n\nMilenio.\n\nEl siguiente Objeto del\nMilenio est\xe1.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, "")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, "")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\n\nIn the Galapagos Islands.\nPlease hurry.\n\n")
  LANGUAGE_TEXT(1, "\n\nIl est dans les \xeeles\nGalapagos.\n\nS'il vous pla\xeet,\nd\xe9p\xeachez-vous !\n\n")
  LANGUAGE_TEXT(2, "\n\nIhr findet ihn auf den Gala-\npagosinseln. Beeilt euch.\n\n")
  LANGUAGE_TEXT(3, "\n\nNelle Isole Galapagos.\nSbrigatevi!\n\n")
  LANGUAGE_TEXT(4, "\n\nEn las Islas Gal\xe1pagos.\nDaos prisa.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(71)
  SET_FLAG(251)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C1C, map_00_state_08_08E34C1C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "The Dark Being was\nresurrected by Sol\n\nChevalsky...\n\nI'm sorry, I meant Pegasus.\n\nTo imprison Reshef, we need\none more Egyptian God Card.\n\nWe need the power of The\nWinged Dragon of Ra.\n\nWe must resurrect the card\nfrom stone.\n\nPlease find the Millennium\nItem to restore it.\n\nThe sixth Millennium Item is\nin the Galapagos Islands.\n\nPlease, you must hurry.\n\n")
  LANGUAGE_TEXT(1, "L'Etre des t\xe9n\xe8bres\nressuscit\xe9 par Sol\n\nChevalsky...\n\nJe suis d\xe9sol\xe9, Pegasus.\nPour emprisonner Reshef,\n\nil nous faut une carte\nde dieu suppl\xe9mentaire.\n\nNous avons besoin du\nDragon Ail\xe9 de Ra.\n\nIl faut ressusciter\nla carte p\xe9trifi\xe9e.\n\nVeuillez trouver\ncet Objet du mill\xe9nium\n\npour la restaurer.\n\nLe sixi\xe8me Objet du\nmill\xe9nium se trouve dans\n\nles \xeeles Galapagos.\n\nJe vous en supplie,\nd\xe9p\xeachez-vous !\n\n")
  LANGUAGE_TEXT(2, "Der Dunkle wurde von\nSol Chevalsky auferweckt...\n\nEntschuldigung, von\nPegasus.\n\nUm Reschef unsch\xe4dlich zu\nmachen, ist eine weitere\n\nG\xf6tterkarte n\xf6tig.\n\nWir brauchen die Macht des\ngefl\xfcgelten Drachen von Ra.\n\nWir m\xfcssen die Karte aus dem\nStein befreien.\n\nBitte findet den Millennium-\nsgegenstand, um die Karte\n\nwiederherzustellen. Ihr\nfindet den {BYTE_8255}.\n\nMillenniumsgegenstand\nauf den Galapagosinseln.\n\nBitte beeilt euch.\n\n")
  LANGUAGE_TEXT(3, "Il Tenebroso risuscitato\nda Sol Chevalsky...\n\nO meglio, Pegasus.\n\nPer imprigionare Reshef,\nci serve un'altra carta\n\ndivina. Ci serve la potenza\ndel Drago Alato di Ra.\n\nDobbiamo risuscitare la\ncarta dalla pietra.\n\nTrovate l'Oggetto Millenario\nper ripristinarla.\n\nIl sesto Oggetto Millenario\nsi trova nelle Isole\n\nGalapagos. Vi prego,\nfate in fretta.\n\n")
  LANGUAGE_TEXT(4, "El Ser Oscuro resucitado\npor Sol Chevalsky...\n\nLo siento, Pegasus.\n\nPara encerrar a Reshef\nnecesitamos una carta\n\ndel dios m\xe1s.\n\nNecesitamos el poder\ndel Drag\xf3n Alado de Ra.\n\nDebemos restaurar la carta\nde su estado p\xe9treo.\n\nEncontrad el Objeto del\nMilenio para restaurarla.\n\nEl sexto Objeto del Milenio\nest\xe1 en las Islas\n\nGal\xe1pagos.\nDeb\xe9is daros prisa.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C04, map_00_state_08_08E34C04, 0x08E34C10, 0x08E34C28)
  CHECK_FLAG(71)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C28, map_00_state_08_08E34C28, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Please. Hurry to the\nGalapagos Islands.\n\nReshef the Dark Being will\nsoon engulf the world in\n\nshadows.\n\n")
  LANGUAGE_TEXT(1, "S'il vous pla\xeet. D\xe9p\xeachez-\nvous de vous rendre\n\naux \xeeles Galapagos.\nReshef, l'Etre des t\xe9n\xe8bres\n\nva bient\xf4t\nengloutir le monde.\n\n")
  LANGUAGE_TEXT(2, "Bitte. Begebt euch schnell\nzu den Galapagosinseln.\n\nReschef der Dunkle wird\ndie Welt bald ins Verderben\n\nst\xfcrzen.\n\n")
  LANGUAGE_TEXT(3, "Vi prego. Recatevi in fretta\nnelle Isole Galapagos.\n\nIl mondo cadr\xe0 presto\nnelle grinfie di\n\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Por favor, corred a las\nIslas Gal\xe1pagos.\n\nReshef, el Ser Oscuro pronto\nacabar\xe1 con el mundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
