#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_01: map 51 state 1 */

CHECK_FLAG(EVENT_FLAG_ENTERED_PEGASUS_CASTLE)
PLAY_MUSIC(MUSIC_PEGASUS_CASTLE)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Welcome, {PLAYER} boy.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
DELAY(8)
SET_FLAG(EVENT_FLAG_ENTERED_PEGASUS_CASTLE)
FADE_SCREEN(8)
WARP(LOCATION_PEGASUS_CASTLE_RESHEF_TABLET_ROOM, 4, 0, 0)

EVENT_SCRIPT_REPLACEMENT(0x08EE4040, map_51_state_01_08EE4040, 0x08F04040, 0x08F04040)
SET_FLAG(EVENT_FLAG_GOT_PAST_FIRST_PEGASUS_CASTLE_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FC8, map_51_state_01_08EE3FC8, 0x08F04040, 0x08F04040)
CLEAR_FLAG(172)
  FALLTHROUGH()
END_EVENT_SCRIPT()
