#include "event_macros.h"
#include "overworld.h"

/* map_22_state_03: map 22 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CB34, map_22_state_03_08E8CB34, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(405)
  DELAY(16)
  WALK_OBJECT_Y(0, 26)
  WALK_OBJECT_X(0, 80)
  WALK_OBJECT_Y(13, 20)
  WALK_OBJECT_X(13, 90)
  WALK_OBJECT_Y(14, 32)
  WALK_OBJECT_X(14, 90)
  DELAY(16)
  MOVE_OBJECT(2, 3, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Humph. So the merry band of\nlosers finally have a clue\n\nabout what's really going\non.\n\n")
  LANGUAGE_TEXT(1, "Mm... Alors le peuple\ns'est rassembl\xe9\n\net a obtenu un indice.\n\n")
  LANGUAGE_TEXT(2, "Hmph. Der P\xf6bel machte\nalso gemeinsame Sache\n\nund bekam einen Hinweis.\n\n")
  LANGUAGE_TEXT(3, "Uff. E cos\xec la plebaglia\nsi \xe8 riunita e ha avuto\n\nun indizio.\n\n")
  LANGUAGE_TEXT(4, "Vaya. As\xed que la chusma se\nha unido y tiene una pista.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 3, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ishizu visited my big\nbrother.\n\nShe wanted him to get the\nEgyptian God Cards back.\n\n")
  LANGUAGE_TEXT(1, "Mon grand fr\xe8re a eu\nla visite de cette Ishizu.\n\nElle voulait qu'il r\xe9cup\xe8re\nles cartes de dieux.\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder erhielt\neinen Besuch - von Ishizu.\n\nEr soll die G\xf6tterkarten\nwiederbeschaffen.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello ha ricevuto\nla visita di quella Ishizu.\n\nVoleva che restituisse\nle carte divine.\n\n")
  LANGUAGE_TEXT(4, "Mi gran hermano ha\nrecibido una visita\n\nde \xe9sa tal Ishizu.\n\nQuer\xeda que \xe9l recuperara\nlas cartas de los dioses.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Mokuba, keep quiet.\n\nThe title as champion And\nthe strongest cards...\n\nOnly the most powerful\nduelist is worthy of these\n\ntwo things.\n\nAnd that duelist is me!\n\nI will recover the Egyptian\nGod Cards quick and easy.\n\n")
  LANGUAGE_TEXT(1, "Mokuba, reste calme.\n\nLes plus grands titres\net les meilleures cartes...\n\nSeuls les meilleurs\nduellistes en sont dignes.\n\nEt ce duelliste, c'est moi !\n\nJe vais r\xe9cup\xe9rer\nles cartes de dieux\n\nsans plus tarder.\n\n")
  LANGUAGE_TEXT(2, "Mokuba, sei still.\n\nDer beste Titel und die\nbesten Karten...\n\nsind nur des st\xe4rksten\nDuellanten w\xfcrdig.\n\nUnd das bin ich!\n\nIch werde die G\xf6tterkarten\nohne Einmischung von\n\nirgendjemandem\nzur\xfcckholen.\n\n")
  LANGUAGE_TEXT(3, "Mokuba, stai zitto.\n\nIl titolo pi\xf9 grande e\nle carte migliori...\n\nSolo il duellante pi\xf9\npotente se li merita.\n\nE quel duellante sono io!\n\nRecuperer\xf2 le carte divine\nsenza alcuna interferenza.\n\n")
  LANGUAGE_TEXT(4, "Mokuba, c\xe1llate.\n\nEl mejor t\xedtulo y las\nmejores cartas...\n\nSon s\xf3lo dignos del\nduelista m\xe1s fuerte.\n\n\xa1Y yo soy ese duelista!\n\nRecuperar\xe9 las cartas\nde los dioses sin ayuda.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I bet you guys are happy\nthat my big bro's gonna\n\nhelp you out, huh?\n\n")
  LANGUAGE_TEXT(1, "C'est g\xe9nial d'avoir mon\ngrand fr\xe8re de son c\xf4t\xe9,\n\npas vrai ?\n\n")
  LANGUAGE_TEXT(2, "Mit meinem gro\xdfen Bruder\nals Verb\xfcndeten geht es\n\numso besser, was?\n\n")
  LANGUAGE_TEXT(3, "\xc8 fantastico avere mio fra-\ntello dalla tua parte, eh?\n\n")
  LANGUAGE_TEXT(4, "Tener a mi gran hermano\ncontigo es bueno, \xbfeh?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Mokuba!\n\n")
  LANGUAGE_TEXT(1, "Mokuba !\n\n")
  LANGUAGE_TEXT(2, "Mokuba!\n\n")
  LANGUAGE_TEXT(3, "Mokuba!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mokuba!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 8)
  LANGUAGE_TEXT(0, "W-what is it, Seto?\n\n")
  LANGUAGE_TEXT(1, "Q-qu'est-ce qu'il y a,\ngrand fr\xe8re ?\n\n")
  LANGUAGE_TEXT(2, "W-was ist, gro\xdfer Bruder?\n\n")
  LANGUAGE_TEXT(3, "C-che c'\xe8, fratello?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 pasa,\ngran hermano?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I have no intention of\nteaming up with these\n\nclowns!\n\n")
  LANGUAGE_TEXT(1, "Je n'ai aucune intention de\ntravailler avec ces clowns.\n\n")
  LANGUAGE_TEXT(2, "Ich habe nicht die geringste\nAbsicht, mit diesen Clowns\n\nzusammenzuarbeiten.\n\n")
  LANGUAGE_TEXT(3, "Non ho alcuna intenzione\ndi lavorare con questi\n\npagliacci.\n\n")
  LANGUAGE_TEXT(4, "No tengo intenci\xf3n\nalguna de trabajar\n\ncon estos payasos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, 8)
  LANGUAGE_TEXT(0, "Big brother...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder...\n\n")
  LANGUAGE_TEXT(3, "Ma, fratello...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Listen up, you fools!\n\nA real duelist doesn't need\nhelp from a bunch of\n\ncheerleaders!\n\nAll you should count on is\nyour own strength!\n\nYou guys are so weak that\nnone of you can survive\n\nalone...\n\nAnd you expect me to team up\nwith you losers? Don't make\n\nme laugh!\n\nLet's go, Mokuba!\n\n")
  LANGUAGE_TEXT(1, "Vous tous,\nsoyez attentifs !\n\nSans alli\xe9s, un\nduelliste est bien seul !\n\nCe qui compte, c'est\nvotre propre pouvoir !\n\nUn duelliste qui compte sur\nle pouvoir des autres...\n\nC'est avec \xe7a que je\ndois m'allier ?\n\nC'est une plaisanterie\nou quoi ?\n\nJ'ai termin\xe9, Mokuba !\n\n")
  LANGUAGE_TEXT(2, "Ihr alle, passt auf!\n\nEin Duellant ist ein Einzel-\nk\xe4mpfer ohne Verb\xfcndete!\n\nEs z\xe4hlt nur die eigene\nKraft!\n\nWer sich auf die Kraft\nanderer verl\xe4sst...\n\nUnd ich soll da mitmachen?\nDas ist doch wohl ein Witz!\n\nDas war's, Mokuba!\n\n")
  LANGUAGE_TEXT(3, "Statemi bene a sentire,\ntutti quanti!\n\nUn duellante \xe8 una presenza\nsolitaria senza alleati!\n\nConta solo il vostro potere!\n\nUn duellante che si aggrappa\nal potere degli altri...\n\nIo dovrei lavorare con lui?\n\nRaccontami un'altra\nballa!\n\nBasta cos\xec,Mokuba!\n\n")
  LANGUAGE_TEXT(4, "Todos vosotros,\n\xa1prestad atenci\xf3n!\n\n\xa1Un duelista es una\npresencia solitaria\n\nsin aliados!\n\n\xa1Nada m\xe1s que vuestro\npoder importa!\n\nUn duelista que se aferra a\nlos poderes de los dem\xe1s...\n\n\xbfTengo que compartir eso?\n\xa1Dime otra broma!\n\n\xa1He terminado, Mokuba!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "Wahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Mouah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Wahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Uahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Wajajaja!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 1, 72, 0)
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(24)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(24)
  MOVE_OBJECT(3, 1, 68, 0)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(94)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB1C, map_22_state_03_08E8CB1C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This is the Egypt\nExhibition.\n\n")
  LANGUAGE_TEXT(1, "C'est l'Exposition\n\xe9gyptienne.\n\n")
  LANGUAGE_TEXT(2, "Das ist die \xe4gypt.\nAusstellung.\n\n")
  LANGUAGE_TEXT(3, "Questa \xe8 la\nMostra Egizia.\n\n")
  LANGUAGE_TEXT(4, "Esta es la\nExposici\xf3n Egipcia.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB28, map_22_state_03_08E8CB28, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No way, I'm not a duelist.\n\nI came here for the\nexhibition.\n\n")
  LANGUAGE_TEXT(1, "Attends une minute. Je\nne suis pas un duelliste.\n\nJe suis l\xe0 pour\nl'Exposition \xe9gyptienne.\n\n")
  LANGUAGE_TEXT(2, "Warte, ich bin kein\nDuellant.\n\nIch bin wegen der\nAusstellung hier.\n\n")
  LANGUAGE_TEXT(3, "Aspetta, io non sono\nun duellante.\n\nSono qui per la Mostra.\n\n")
  LANGUAGE_TEXT(4, "Espera, no soy\nduelista.\n\nHe venido por\nla Exposici\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
