#include "event_macros.h"
#include "overworld.h"

/* map_05_state_01: map 5 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E50EA8, map_05_state_01_08E50EA8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I won't be riding the Duel\nExpress...\n\nBut that doesn't mean my\nduelist level is low!\n\n")
  LANGUAGE_TEXT(1, "Je ne vais pas prendre\nle Duel Express...\n\nMais \xe7a ne veut pas dire\nque mon niveau de\n\nduelliste est bas !\n\n")
  LANGUAGE_TEXT(2, "Ich will nicht mit dem Duel\nExpress fahren...\n\nDas hei\xdft aber nicht, dass\nmein Duellanten-Level\n\nniedrig ist!\n\n")
  LANGUAGE_TEXT(3, "Non andr\xf2 sul Duel\nExpress... Ma ci\xf2 non\n\nsignifica che il mio li-\nvello duellante sia basso!\n\n")
  LANGUAGE_TEXT(4, "No ir\xe9 en el Duel\nExpress...\n\n\xa1Eso no quiere decir que mi\nnivel de duelista sea bajo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50EB4, map_05_state_01_08E50EB4, 0x08E50EC0, 0x08E50ED8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_STRINGER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50EC0, map_05_state_01_08E50EC0, 0x08E50ECC, 0x08F0404C)
  LANGUAGE_TEXT(0, "I still have my pride as a\nduelist.\n\nI don't feel like dueling,\nbut I'll still take you on\n\nfair and square.\n\n")
  LANGUAGE_TEXT(1, "J'ai encore mon\nhonneur de duelliste.\n\nRien qu'\xe0 l'id\xe9e,\n\xe7a me rend malade\n\nmais je vais t'affronter\n\xe9quitablement.\n\n")
  LANGUAGE_TEXT(2, "Ich habe noch immer meinen\nDuellantenstolz.\n\nIch will mich nicht\nwiederholen, aber ich bin\n\nein fairer Gegner.\n\n")
  LANGUAGE_TEXT(3, "Ho ancora il mio\norgoglio di duellante.\n\nMi fa sentire male dirlo,\nma giocher\xf2 onestamente.\n\n")
  LANGUAGE_TEXT(4, "A\xfan tengo mi\norgullo de duelista.\n\nMe enferma decirlo,\npero jugar\xe9 limpio.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50ECC, map_05_state_01_08E50ECC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Instead of fair and square,\nmaybe we should've played\n\nby my rules.\n\n")
  LANGUAGE_TEXT(1, "On aurait d\xfb jouer\nselon mes r\xe8gles.\n\n")
  LANGUAGE_TEXT(2, "Wir h\xe4tten nach meinen\nRegeln spielen sollen.\n\n")
  LANGUAGE_TEXT(3, "Avremmo dovuto giocare\ncon le mie regole.\n\n")
  LANGUAGE_TEXT(4, "Deber\xedamos haber\nluchado bajo mis normas.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_STRINGER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50ED8, map_05_state_01_08E50ED8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Let me tell this to you\nstraight. I'm not one of\n\nthose gracious losers. I\nhate losing!\n\nIt's no fun to lose to a\ntough duelist.\n\nSo you can forget about\ndueling me ever again.\n\nHumph!\n\n")
  LANGUAGE_TEXT(1, "Tu m'as battu, \xe7a\nm'\xe9nerve trop, mec.\n\nC'est pas marrant,\nse battre contre\n\nplus fort que soi.\n\nEn tout cas,\ntu peux oublier.\n\n")
  LANGUAGE_TEXT(2, "Du hast mich geschlagen, das\ngef\xe4llt mir gar nicht.\n\nGegen einen starken Gegner\nmacht es mir keinen Spa\xdf.\n\nVergiss es.\n\n")
  LANGUAGE_TEXT(3, "Mi hai battuto. Mi\nhai proprio seccato.\n\nNon mi diverto a duellare\ncon i tipi forti.\n\nPuoi scordartelo.\n\n")
  LANGUAGE_TEXT(4, "Me has vencido,\neso no me gusta.\n\nNo me mola luchar\ncon un tipo fuerte.\n\nOlv\xeddalo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50EE4, map_05_state_01_08E50EE4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Did you hear about the Duel\nExpress?\n\nAny duelist can get on\nboard.\n\nMaybe I should go, too.\n\n")
  LANGUAGE_TEXT(1, "Tu as entendu parler\ndu Duel Express ?\n\nTous les duellistes\npeuvent monter \xe0 bord.\n\nJe devrais peut-\xeatre\naussi y aller.\n\n")
  LANGUAGE_TEXT(2, "Hast du schon vom Duel\nExpress geh\xf6rt?\n\nJeder Duellant kann\nmitfahren.\n\nVielleicht sollte ich auch\neinsteigen.\n\n")
  LANGUAGE_TEXT(3, "Hai sentito parlare del\nDuel Express?\n\nQualsiasi duellante pu\xf2\nsalirvi a bordo.\n\nForse dovrei andarci\nanch'io.\n\n")
  LANGUAGE_TEXT(4, "\xbfHas o\xeddo sobre\nel Duel Express?\n\nCualquier duelista\npuede subirse en \xe9l.\n\nQuiz\xe1s, yo deber\xeda\nir tambi\xe9n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50EF0, map_05_state_01_08E50EF0, 0x08E50EFC, 0x08E50F14)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RED_MOHAWK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50EFC, map_05_state_01_08E50EFC, 0x08E50F08, 0x08F0404C)
  LANGUAGE_TEXT(0, "Sure thing!\n\nA duel's a duel, no matter\nwhere it's played!\n\n")
  LANGUAGE_TEXT(1, "Bien s\xfbr !\nUn duel, c'est un duel,\n\npeu importe\no\xf9 on se bat !\n\n")
  LANGUAGE_TEXT(2, "Na klar! Ein Duell\nist ein Duell,\n\nwelche Rolle spielt da\nschon der Ort!\n\n")
  LANGUAGE_TEXT(3, "Ma certo!\n\nUn duello \xe8 sempre un\nduello, dovunque si giochi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Claro!\n\nUn duelo es un duelo,\nall\xe1 donde se haga.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(9)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F08, map_05_state_01_08E50F08, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Tsk... Lost that one.\n\n")
  LANGUAGE_TEXT(1, "Pff...\nJ'ai perdu.\n\n")
  LANGUAGE_TEXT(2, "Tss...\nVerloren.\n\n")
  LANGUAGE_TEXT(3, "Acc...\nHo perso.\n\n")
  LANGUAGE_TEXT(4, "Tch...\nPerdiste.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_RED_MOHAWK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E50F14, map_05_state_01_08E50F14, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Huh? You again? Are you\npicking on me, you bully!\n\n")
  LANGUAGE_TEXT(1, "Hein ? Encore toi ?\nTu m'en veux ou quoi ?\n\n")
  LANGUAGE_TEXT(2, "Was? Du schon wieder? Hast\ndu's auf mich abgesehen?\n\n")
  LANGUAGE_TEXT(3, "Come? Di nuovo tu?\nCe l'hai con me?\n\n")
  LANGUAGE_TEXT(4, "\xbfEh? \xbfT\xfa, de nuevo?\n\xbfMe quieres fastidiar?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
