#include "event_macros.h"
#include "overworld.h"

/* map_00_state_19: map 0 state 19 */

EVENT_SCRIPT_REPLACEMENT(0x08E34EBC, map_00_state_19_08E34EBC, 0x08F04040, 0x08F04040)
  PORTRAIT(14, 9, 1)
  LANGUAGE_TEXT(0, "Pipipi...\n\n")
  LANGUAGE_TEXT(1, "Pipipi...\n\n")
  LANGUAGE_TEXT(2, "Pipipi...\n\n")
  LANGUAGE_TEXT(3, "Eeehhh...\n\n")
  LANGUAGE_TEXT(4, "Pipipi...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  LANGUAGE_TEXT(0, "Big brother...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder...\n\n")
  LANGUAGE_TEXT(3, "Fratello...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  LANGUAGE_TEXT(0, "Are you worried?\n\n")
  LANGUAGE_TEXT(1, "Est-ce que\ntu es inquiet ?\n\n")
  LANGUAGE_TEXT(2, "Hast du Angst?\n\n")
  LANGUAGE_TEXT(3, "Sei preoccupato?\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s preocupado?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "No... I'm not worried.\n\nI'm sure they'll get the job\ndone.\n\n")
  LANGUAGE_TEXT(1, "Non... Je ne suis\npas inquiet.\n\nJe suis s\xfbr qu'ils\nvont y arriver.\n\n")
  LANGUAGE_TEXT(2, "Nein... eigentlich nicht.\n\nIch bin mir sicher, dass\nsie ihre Aufgabe erf\xfcllen.\n\n")
  LANGUAGE_TEXT(3, "No...\nNon sono preoccupato.\n\nSono sicuro che riusciranno\nnell'impresa.\n\n")
  LANGUAGE_TEXT(4, "No...\nNo lo estoy.\n\nSeguro que har\xe1n\nel trabajo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  LANGUAGE_TEXT(0, "Yeah!\n\nThey're stronger than the\nBig Bad Five!\n\nThey won't lose to anyone!\n\n")
  LANGUAGE_TEXT(1, "Ouais !\n\nIls sont plus forts que\nles Cinq Grands M\xe9chants !\n\nIls ne perdront\ncontre personne !\n\n")
  LANGUAGE_TEXT(2, "Ja!\n\nSie sind st\xe4rker als\ndie Big Five!\n\nSie verlieren gegen\nniemanden!\n\n")
  LANGUAGE_TEXT(3, "Ma s\xec!\n\nSono pi\xf9 forti dei\nTemibili Cinque!\n\nNon perderanno con\nnessuno!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed!\n\n\xa1Son m\xe1s fuertes que los\nCinco Malvados!\n\n\xa1No perder\xe1n contra nadie!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "Hahahahaha!\n\nThat's right! There's no way\nthey'll lose!\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha ha !\n\nC'est \xe7a ! Ils ne\npeuvent plus perdre !\n\n")
  LANGUAGE_TEXT(2, "Hahahahaha!\n\nGenau! Sie k\xf6nnen\ngar nicht verlieren!\n\n")
  LANGUAGE_TEXT(3, "Hahahahaha!\n\nEsatto! Non possono\nproprio perdere!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajajaja!\n\n\xa1Eso es!\n\xa1No pueden perder!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  LANGUAGE_TEXT(0, "But they can't beat\nKaibaman!\n\n")
  LANGUAGE_TEXT(1, "Mais ils n'arriveront pas\n\xe0 battre Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Aber Kaibaman k\xf6nnen sie\nnicht besiegen!\n\n")
  LANGUAGE_TEXT(3, "Ma non possono\nbattere Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Pero no pueden\nvencer a Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  LANGUAGE_TEXT(0, "Well, duh. Kaibaman's\ninvincible!\n\nBut {PLAYER}'s number one!\n\n")
  LANGUAGE_TEXT(1, "Eh bien, mmm.\nKaibaman est invincible !\n\nMais {PLAYER},\nc'est le num\xe9ro {BYTE_8250} !\n\n")
  LANGUAGE_TEXT(2, "Na ja.\nKaibaman ist unschlagbar!\n\nAber {PLAYER} ist\nNummer eins!\n\n")
  LANGUAGE_TEXT(3, "Be', ecco...\nKaibaman \xe8 invincibile!\n\nMa {PLAYER} \xe8\nil numero uno!\n\n")
  LANGUAGE_TEXT(4, "Bueno, ah.\n\xa1Kaibaman es invencible!\n\n\xa1Pero {PLAYER}\nes el n\xfamero uno!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  LANGUAGE_TEXT(0, "So which one's stronger? A\nduelist who's invincible or\n\na duelist who's number one?\n\n")
  LANGUAGE_TEXT(1, "Alors, qui est\nle plus fort ?\n\nL'invincible ou\nle num\xe9ro un ?\n\n")
  LANGUAGE_TEXT(2, "Wer ist also st\xe4rker?\nDer Unbesiegbare oder\n\nNummer eins?\n\n")
  LANGUAGE_TEXT(3, "Allora chi \xe8 pi\xf9 forte?\nL'invincibile o il\n\nnumero uno?\n\n")
  LANGUAGE_TEXT(4, "Entonces, \xbfqui\xe9n es\nm\xe1s fuerte?\n\n\xbfEl invencible o el\nn\xfamero uno?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PLAY_MUSIC(390)
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "Wh-what's that sound?\n\n")
  LANGUAGE_TEXT(1, "Ce... c'est quoi\nce bruit ?\n\n")
  LANGUAGE_TEXT(2, "W-was ist das f\xfcr ein\nGer\xe4usch?\n\n")
  LANGUAGE_TEXT(3, "Co-cos'\xe8 questo rumore?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 es ese sonido?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Big brother! Over there!\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re !\nPar l\xe0 !\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder!\nDa vorne!\n\n")
  LANGUAGE_TEXT(3, "Fratello!\nLaggi\xf9!\n\n")
  LANGUAGE_TEXT(4, "\xa1Gran hermano!\n\xa1All\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(16)
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "That's KaibaCorp's\nhelicopter...\n\n")
  LANGUAGE_TEXT(1, "C'est l'h\xe9licopt\xe8re de\nla Kaiba Corporation...\n\n")
  LANGUAGE_TEXT(2, "Das ist der Hubschrauber\nder Kaiba Corporation...\n\n")
  LANGUAGE_TEXT(3, "\xc8 l'elicottero della\nKaiba Corporation...\n\n")
  LANGUAGE_TEXT(4, "\xc9se es el helic\xf3ptero\nde Kaiba Corporation...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  LANGUAGE_TEXT(0, "Let's go, big brother!\n\n")
  LANGUAGE_TEXT(1, "Allons-y, grand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Gehen wir, gro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Andiamo, fratello!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, gran hermano!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "Sure! Let's go!\n\n")
  LANGUAGE_TEXT(1, "OK !\nEn route !\n\n")
  LANGUAGE_TEXT(2, "Okay!\nGehen wir!\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0!\nAndiamo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Claro!\n\xa1Vamos!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(2, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
