#include "event_macros.h"
#include "overworld.h"

/* map_28_state_03: map 28 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EA69BC, map_28_state_03_08EA69BC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  TEXT("I want the fortuneteller to\ntell me if me and my\n\nsnookums are made for each\nother!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  TEXT("I'll get him to look into my\npast life.\n\n")
  TEXT("Isn't it exciting,\nsugarmuffin?\n\n")
  TEXT("It certainly is, kissylips!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 104)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 12)
  DELAY(8)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 2)
  DELAY(16)
  TEXT("L-look... There he is...\n\nI... I know.\n\nOkay! Let's have him tell\nour fortunes!\n\nUrgh!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  TEXT("Wh-what's the matter,\nlovebucket?\n\nMy back... Ow, ow, ow...\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 56)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Are you okay?\n\nThe elderly should take it\neasy.\n\n")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 12)
  DELAY(8)
  TEXT("I had him do a reading about\nmy health...\n\nOh... What a waste...\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 2)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Speaking of who... What\nhappened to him?\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 16, 0)
  DELAY(8)
  WALK_OBJECT_Y(3, 54)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(8)
  TEXT("Wh-where are you going?\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("To see my friend.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 0)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  COMMAND_7C_ARG(2, 16)
  FADE_SCREEN(16)
  WARP(31, 8, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
