#include "event_macros.h"
#include "overworld.h"

/* map_12_state_08: map 12 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F180, map_12_state_08_08E6F180, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(407)
  PORTRAIT(PORTRAIT_ARCANA_UNUSED, 0, 0)
  LANGUAGE_TEXT(0, "Kukuku... Fresh new prey to\nhunt...\n\n")
  LANGUAGE_TEXT(1, "Kukuku... Une nouvelle\nproie pour moi...\n\n")
  LANGUAGE_TEXT(2, "Kukuku... Frischfleisch\nf\xfcr mich...\n\n")
  LANGUAGE_TEXT(3, "Benone... Una nuova preda\nfresca da cacciare...\n\n")
  LANGUAGE_TEXT(4, "Kukuku... Nueva presa\nfresca que cazar\xe9...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 96)
  WALK_OBJECT_Y(1, 68)
  WALK_OBJECT_X(1, 128)
  PORTRAIT(PORTRAIT_YUGI, 0, 1)
  LANGUAGE_TEXT(0, "There he is! It's him,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Le voil\xe0 !\nC'est lui, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Da ist er!\nEr ist es, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Eccolo l\xec!\n\xc8 lui, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ah\xed est\xe1!\n\xa1Es \xe9l, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 1)
  LANGUAGE_TEXT(0, "He must be one of da\nremaining Neo Ghouls.\n\nHe's who Espa Roba was\ntalking about.\n\nI can't believe we couldn't\nfind him 'til now!\n\n")
  LANGUAGE_TEXT(1, "Ca doit \xeatre l'un de ces\nNeo Ghouls restants.\n\nCa doit \xeatre celui\ndont Roba parlait.\n\nIl est vraiment insistant !\n\n")
  LANGUAGE_TEXT(2, "Er ist bestimmt einer der\nletzten Neo Ghouls.\n\nEiner von denen, die Roba\nerw\xe4hnte.\n\nGanz sch\xf6n hartn\xe4ckig!\n\n")
  LANGUAGE_TEXT(3, "Dev'essere uno dei\nNeo Ghouls rimasti.\n\nSicuramente, \xe8 di lui\nche parlava Roba.\n\nNon si d\xe0 proprio per vinto!\n\n")
  LANGUAGE_TEXT(4, "Debe ser uno de los\nNeo Ghouls que queden.\n\nDebe de ser de lo que\nRoba estaba hablando.\n\n\xa1Habla de los\npersistentes!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 1)
  LANGUAGE_TEXT(0, "Let's go!\n\n")
  LANGUAGE_TEXT(1, "Allons-y !\n\n")
  LANGUAGE_TEXT(2, "Gehen wir!\n\n")
  LANGUAGE_TEXT(3, "Andiamo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(57, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
