#include "event_macros.h"
#include "overworld.h"

/* map_12_state_14: map 12 state 14 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F18C, map_12_state_14_08E6F18C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  DELAY(32)
  MOVE_OBJECT(1, 1, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "Master Mokuba... Master\nSeto...\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Mokuba...\nMa\xeetre Seto...\n\n")
  LANGUAGE_TEXT(2, "Meister Mokuba...\nMeister Seto...\n\n")
  LANGUAGE_TEXT(3, "Maestro Mokuba...\nMaestro Seto...\n\n")
  LANGUAGE_TEXT(4, "Amo Mokuba...\nAmo Seto...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_ROLAND, 0, 0)
  LANGUAGE_TEXT(0, "There's no point standing\naround.\n\nThere must be something that\nI can do...\n\nI know!\n\n")
  LANGUAGE_TEXT(1, "Pas la peine\nde rester plant\xe9 l\xe0.\n\nOn doit pouvoir faire\nquelque chose...\n\nJ'ai une id\xe9e !\n\n")
  LANGUAGE_TEXT(2, "Ich will nicht nur herum-\nstehen.\n\nIch muss doch irgendetwas\ntun k\xf6nnen...\n\nIch wei\xdf!\n\n")
  LANGUAGE_TEXT(3, "A che serve starsene cos\xec,\ncon le mani in mano?\n\nCi sar\xe0 pure qualcosa\nche posso fare...\n\nCi sono!\n\n")
  LANGUAGE_TEXT(4, "No hay raz\xf3n para estar por\naqu\xed de este modo.\n\nDebe de haber algo\nque pueda hacer...\n\n\xa1Ya s\xe9!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(1, 104)
  WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 128)
  FADE_SCREEN(8)
  WARP(57, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
