#include "event_macros.h"
#include "overworld.h"

/* map_26_state_06: map 26 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3CEC, map_26_state_06_08EA3CEC, 0x08EA3CF8, 0x08EA3D04)
  PLAY_MUSIC(407)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, 2, 0)
  LANGUAGE_TEXT(0, "Harpie Lady!\n\n")
  LANGUAGE_TEXT(1, "Harpie !\n\n")
  LANGUAGE_TEXT(2, "Fl\xfcgel-Lady!\n\n")
  LANGUAGE_TEXT(3, "Arpia Splendente!\n\n")
  LANGUAGE_TEXT(4, "\xa1Harpie Lady!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 12)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, 2, 0)
  LANGUAGE_TEXT(0, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(1, "Harpies' Triangle Ecstasy !\n\n")
  LANGUAGE_TEXT(2, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(3, "Harpies' Triangle Ecstasy!\n\n")
  LANGUAGE_TEXT(4, "\xa1Harpies' Triangle Ecstasy!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(341)
  COMMAND_7C_ARG(8, 13)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(3, 1, 8)
  PLAY_MUSIC(282)
  OBJECT_EFFECT(8, 2)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ARCANA, 0, 0)
  LANGUAGE_TEXT(0, "Hyahahahaha! Nice attack...\n\nBut how much longer can you\nkeep this up?\n\nGo!\n\n")
  LANGUAGE_TEXT(1, "Hya ha ha ! Tu es\nune vraie dure, petite.\n\nMais combien de\ntemps vas-tu tenir ?\n\nAllez !\n\n")
  LANGUAGE_TEXT(2, "Hyahahahaha!\nDu bist ja ganz sch\xf6n\n\nquirlig, Kleine.\n\nAber wie lange h\xe4ltst\ndu noch durch?\n\nFort mit dir!\n\n")
  LANGUAGE_TEXT(3, "Iahahahahah! Sei una\nche non molla, tu.\n\nMa quanto potrai\nresistere ancora?\n\nVai!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ja,ja, ja!\nEres peleona, chica.\n\nPero \xbfcu\xe1nto puedes\naguantar?\n\n\xa1Vamos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 24)
  MOVE_OBJECT(4, 3, 0, 0)
  SET_OBJECT_POSITION(3, 0, 52, 0)
  WALK_OBJECT_X(3, 24)
  WALK_OBJECT_Y(3, 32)
  WALK_OBJECT_X(3, 84)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, 2, 0)
  LANGUAGE_TEXT(0, "Grr... There's too many of\nthem...\n\n")
  LANGUAGE_TEXT(1, "Grr... Celles-ci, on\nne les arr\xeate pas...\n\n")
  LANGUAGE_TEXT(2, "Grr...\nH\xf6rt das denn nie auf?\n\n")
  LANGUAGE_TEXT(3, "Grr...\nNon finiscono mai...\n\n")
  LANGUAGE_TEXT(4, "Grr...\nNo hay fin para ellos...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 70)
  WALK_OBJECT_X(0, 21)
  WALK_OBJECT_Y(0, 30)
  WALK_OBJECT_X(0, 40)
  WALK_OBJECT_Y(13, 70)
  WALK_OBJECT_X(13, 21)
  WALK_OBJECT_Y(13, 36)
  WALK_OBJECT_X(13, 30)
  WALK_OBJECT_Y(14, 70)
  WALK_OBJECT_X(14, 21)
  WALK_OBJECT_Y(14, 36)
  WALK_OBJECT_X(14, 30)
  WALK_OBJECT_Y(14, 24)
  WALK_OBJECT_X(14, 30)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 4)
  DELAY(8)
  PLAY_MUSIC(407)
  MOVE_OBJECT(2, 1, 0, 0)
  MOVE_OBJECT(3, 1, 0, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ARCANA, 0, 0)
  LANGUAGE_TEXT(0, "Hyahahahaha! How good of you\nto visit!\n\nWhat's the fun without a\ncaptive audience!\n\nI'll give you two choices.\n\nDo nothing but watch this\nstunning show as I defeat\n\nthis woman...\n\nOr step in and be magically\ndefeated by me!\n\nHyahahahahaha!\n\nWhichever choice you make,\nI win!\n\nHyahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Hya ah ah ah ! C'est gentil\nde rendre visite seul !\n\nQuelle chance, une\nautre victoire en vue !\n\nMaintenant, je vais te\ndonner le choix.\n\nTais-toi et regarde cette\nfemme succomber devant\n\nnous. Ou laisse-moi te\nbattre sur-le-champ !\n\nBien s\xfbr, moi, je gagne\ndans un cas comme\n\ndans l'autre,\nHyah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Hyahaha! Sch\xf6n, dass\ndu selbst vorbeischaust!\n\nZum Gl\xfcck habe ich noch\neinen Trumpf in der Hand!\n\nIch stelle dich vor die\nWahl.\n\nSei still und schau zu, wie\ndiese Frau sich uns\n\nunterwirft...\n\nOder lass dich sofort von\nmir besiegen! Hahahaha!\n\nAber wie du dich auch\nentscheidest, ich gewinne\n\nsowieso! Hyahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Iahahahahah! Ma che\nbello farmi visita!\n\nUn altro motivo di orgoglio\nper me! Che fortuna!\n\nTi dar\xf2 due possibilit\xe0\ndi scelta.\n\nRimanere in silenzio e\nguardare questa donna\n\nsoccombere a noi...\nO subire la mia sconfitta\n\nqui su due piedi! Iahahah!\nNaturalmente, qualunque\n\nscelta tu faccia, sar\xf2 io\na vincere. Iahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ja, ja, ja! \xa1Qu\xe9 bien que\nnos visites solo!\n\nMe apunto otro\ntriunfo, \xa1qu\xe9 suerte!\n\nAhora, te dar\xe9 a elegir\nentre dos cosas.\n\nTe callas, y ves a esta\nmujer sucumbir ante nos...\n\n\xa1O te derroto ahora\nmismo! \xa1Ja, ja, ja!\n\nDesde luego, escojas lo que\nescojas gano yo siempre.\n\n\xa1Ja, ja, ja!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}I'm going to win!\nI'll let you surrender.{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Je vais gagner !\nJe veux partir d'ici.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ich werde gewinnen!\nGehen.{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Vincer\xf2 io!\nTi conviene rinunciare.{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1Voy a ganar!\nSalte de esto.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CF8, map_26_state_06_08EA3CF8, 0x08EA3D10, 0x08F0404C)
  PORTRAIT(PORTRAIT_ARCANA, 0, 0)
  LANGUAGE_TEXT(0, "Are you that anxious to be\nhumiliated?!\n\nI will have you begging on\nyour knees before it's\n\nover!\n\nI, Arkana, accept your\nchallenge!\n\n")
  LANGUAGE_TEXT(1, "Je vois que tu es\nimpatient d'\xeatre humili\xe9 !\n\nJe veux te voir ramper\ndevant moi, et vite !\n\nMoi, Arkana, j'ai d\xe9cid\xe9\nde relever ton d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Aha, du kannst deine Dem\xfcti-\ngung gar nicht abwarten!\n\nIch werde dich im Dreck\nzerquetschen!\n\nIch, Arkana, nehme deine\nHerausforderung an!\n\n")
  LANGUAGE_TEXT(3, "E cos\xec non vedi l'ora di\nassaporare l'umiliazione!\n\nTra poco striscerai\nai miei piedi!\n\nIo, Arkana, accetter\xf2\nla tua sfida!\n\n")
  LANGUAGE_TEXT(4, "\xa1Veo tu impaciencia\npor ser humillado!\n\n\xa1Estar\xe1s postrado ante\nm\xed ya mismo!\n\n\xa1Yo, Arkana, acepto\ntu reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(156)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D10, map_26_state_06_08EA3D10, 0x08EA3D1C, 0x08EA3D28)
  PLAY_MUSIC(407)
  PORTRAIT(PORTRAIT_ARCANA, 4, 0)
  LANGUAGE_TEXT(0, "Wh-what? I lost? The great\nArkana lost?\n\nHyahahahaha! This simply\ncannot be!\n\nThis must be a mistake!\nHyahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? J'ai perdu ?\nMoi, le grand Arkana ?\n\nHyah ah ah ah !\nC'est impossible !\n\nIl doit y avoir une erreur !\nHyah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "W-was? Ich habe verloren?\nDer gro\xdfe Arkana?\n\nHyahahahaha!\nUnm\xf6glich!\n\nDa muss ein Irrtum\nvorliegen! Hyahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Ma come? Ho perso?\nIo, il grande Arkana!\n\nIahahahahah!\nNon \xe8 possibile!\n\nCi dev'essere un errore!\nIahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ...qu\xe9? \xbfPerd\xed?\n\xbfEl gran Arkana?\n\n\xa1Ja, ja,ja!\n\xa1No puede ser!\n\n\xa1Debe de ser un error!\n\xa1Ja, ja, ja!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 102)
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 60)
  WALK_OBJECT_Y(2, 96)
  WALK_OBJECT_X(3, 102)
  WALK_OBJECT_Y(3, 68)
  WALK_OBJECT_X(3, 60)
  WALK_OBJECT_Y(3, 96)
  WALK_OBJECT_Y(4, 32)
  WALK_OBJECT_X(4, 102)
  WALK_OBJECT_Y(4, 68)
  WALK_OBJECT_X(4, 60)
  WALK_OBJECT_Y(4, 96)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  WALK_OBJECT_Y(1, 32)
  WALK_OBJECT_X(1, 72)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, 0, 0)
  LANGUAGE_TEXT(0, "You came here to save me?\n\n")
  LANGUAGE_TEXT(1, "Tu es venu ici rien que\npour m'aider ?\n\n")
  LANGUAGE_TEXT(2, "Du bist nur hier, um mich\nzu befreien?\n\n")
  LANGUAGE_TEXT(3, "Sei venuto fin qui\nper salvarmi?\n\n")
  LANGUAGE_TEXT(4, "\xbfViniste s\xf3lo para\nsacarme de apuros?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D1C, map_26_state_06_08EA3D1C, 0x08EA3D34, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, 0, 0)
  LANGUAGE_TEXT(0, "Thanks. I couldn't have done\nit without you.\n\n")
  LANGUAGE_TEXT(1, "Merci. Tu m'as\nsortie d'affaires.\n\n")
  LANGUAGE_TEXT(2, "Danke. Du hast mir\ngeholfen.\n\n")
  LANGUAGE_TEXT(3, "Grazie. Mi hai tirato\nfuori dai guai.\n\n")
  LANGUAGE_TEXT(4, "Gracias. Me has sacado\nde esa situaci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D34, map_26_state_06_08EA3D34, 0x08EA3D4C, 0x08EA3D40)
  LANGUAGE_TEXT(0, "So what exactly brings you\nout here?\n\nDid you want to see me about\nsomething?\n\n")
  LANGUAGE_TEXT(1, "Alors, qu'est-ce qui\nt'am\xe8ne ici ?\n\nTu voulais me voir\npour quoi ?\n\n")
  LANGUAGE_TEXT(2, "Was f\xfchrt dich also hierher?\n\nDu wolltest mich doch wegen\nirgendetwas sprechen, oder?\n\n")
  LANGUAGE_TEXT(3, "Allora per quale motivo\nsei venuto qui?\n\nVolevi vedermi per\nqualcosa, non \xe8 cos\xec?\n\n")
  LANGUAGE_TEXT(4, "Y, \xbfqu\xe9 te trae\nexactamente por aqu\xed?\n\nQuer\xedas verme acerca\nde algo, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PLAY_MUSIC(702)
  PORTRAIT(PORTRAIT_MAI, 2, 0)
  LANGUAGE_TEXT(0, "What! Those creeps...\n\nThe Neo Ghouls are\ndestroying the city?\n\nI won't let those cheaters\nget away with it!\n\nAll right, I'll help.\n\nWe'll show them what a\nreal duelist is all about!\n\n")
  LANGUAGE_TEXT(1, "C'est quoi, \xe7a ?\nAlors comme \xe7a,\n\nles Neo Ghouls s\xe8ment\nla terreur en ville ?\n\nJe ne vais pas les laisser\ns'en sortir si facilement.\n\nOK, je vais t'aider.\nOn va leur montrer\n\nce que valent\nles vrais duellistes !\n\n")
  LANGUAGE_TEXT(2, "Was? Diese elenden...\n\nDie Neo Ghouls verursachen\nein Chaos in der Stadt?\n\nDiese miesen Ganoven kommen\nmir nicht so leicht davon.\n\nOkay, ich helfe dir.\n\nWir zeigen ihnen den Stolz\nwahrer Duellanten!\n\n")
  LANGUAGE_TEXT(3, "Ah, \xe8 cos\xec?\nQuei maledetti...\n\nI Neo Ghouls seminano\nil panico in citt\xe0?\n\nNon permetter\xf2 a quei\ndisonesti duellanti di\n\nfarla franca. Bene, anche\nio dar\xf2 il mio aiuto. Gli\n\nfaremo vedere di che pasta\nsono fatti i veri\n\nduellanti!\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 es eso?\nConque esos asquerosos...\n\n\xbfLos Neo Ghouls est\xe1n\ncausando estragos\n\nen la ciudad?\n\nNo dejar\xe9 a esos\nsucios duelistas\n\nque esto quede as\xed.\nMuy bien, ayudar\xe9.\n\n\xa1Les mostraremos el\norgullo de los\n\nduelistas de verdad!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 102)
  WALK_OBJECT_Y(1, 68)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 96)
  SET_FLAG(82)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D4C, map_26_state_06_08EA3D4C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, 0, 1)
  LANGUAGE_TEXT(0, "Okay! Let's go find another\nally!\n\n")
  LANGUAGE_TEXT(1, "OK ! Allons chercher\nun autre alli\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Okay! Suchen wir uns\neinen anderen Verb\xfcndeten!\n\n")
  LANGUAGE_TEXT(3, "Okay! Andiamo a\ntrovare un altro alleato!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien, vamos a\nbuscar otro aliado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D40, map_26_state_06_08EA3D40, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, 0, 1)
  LANGUAGE_TEXT(0, "Okay! We should also get\nback to the Town of Domino!\n\n")
  LANGUAGE_TEXT(1, "OK ! On devrait aussi\nretourner \xe0 Domino !\n\n")
  LANGUAGE_TEXT(2, "Okay! Wir sollten auch nach\nDomino zur\xfcckkehren!\n\n")
  LANGUAGE_TEXT(3, "Okay! Anche noi dovremmo\ntornare a Domino!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bien, nosotros debemos\nvolver a Domino tambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D28, map_26_state_06_08EA3D28, 0x08EA3D34, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, 0, 0)
  LANGUAGE_TEXT(0, "Well, I didn't really need\nyour help, anyway.\n\nI could've beaten the Neo\nGhouls by myself!\n\n")
  LANGUAGE_TEXT(1, "En fait, je n'avais pas\nvraiment besoin d'aide.\n\nJ'aurais pu battre les\nNeo Ghouls moi-m\xeame.\n\n")
  LANGUAGE_TEXT(2, "Na, ich habe deine Hilfe\nohnehin nicht ben\xf6tigt.\n\nIch h\xe4tte die Neo Ghouls\nschon alleine besiegt!\n\n")
  LANGUAGE_TEXT(3, "Be', tanto non mi\nserviva il tuo aiuto.\n\nAvrei battuto i Neo\nGhouls da sola!\n\n")
  LANGUAGE_TEXT(4, "Bien, de todos modos,\nrealmente, no necesitaba\n\ntu ayuda.\n\n\xa1Pod\xeda haber batido a los\nNeo Ghouls yo solo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D04, map_26_state_06_08EA3D04, 0x08EA3D10, 0x08F0404C)
  PORTRAIT(PORTRAIT_ARCANA, 0, 0)
  LANGUAGE_TEXT(0, "You must be joking.\n\nYou're demanding that I beg\nyou for forgiveness?\n\nHyahahahaha! Whatever!\n\nYou're about to witness my\ndazzling duel skills!\n\nPrepare for Arkana's most\nexhilarating performance\n\nyet!\n\n")
  LANGUAGE_TEXT(1, "Comme c'est amusant.\n\nJe devrais implorer\nton pardon ?\n\nHyah ah ah ah !\nC'est parti !\n\nTu vas pouvoir constater\nmes aptitudes au duel !\n\nPr\xe9pare-toi \xe0 affronter\nArkana au meilleur de\n\nsa forme !\n\n")
  LANGUAGE_TEXT(2, "Wie am\xfcsant.\n\nIch soll dich um Vergebung\nbitten?\n\nHyahahahaha!\nAbgemacht!\n\nDu sollst Zeuge meines\natemberaubenden\n\nDuellgeschicks werden!\n\nSei bereit f\xfcr Arkanas\nbeste Duellleistung!\n\n")
  LANGUAGE_TEXT(3, "Divertente davvero.\n\nMi stai dicendo che io\ndovrei chiederti scusa?\n\nIahahahahah!\n\xc8 arrivata la tua ora!\n\nLa mia bravura in duello\nti fulminer\xe0! Preparati al\n\nduello spettacolare\nofferto da Arkana!\n\n")
  LANGUAGE_TEXT(4, "\xa1Pero qu\xe9 divertido!\n\n\xbfMe est\xe1s diciendo\nque te pida perd\xf3n?\n\n\xa1Ja, ja, ja!\n\xa1Vamos!\n\n\xa1Probar\xe1s mi deslumbrante\npericia en el duelo!\n\n\xa1Prep\xe1rate para la\nmayor representaci\xf3n\n\nde duelo de Arkana!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(156)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D58, map_26_state_06_08EA3D58, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls are\nfrightening individuals\n\nindeed.\n\nIf it weren't for Mai, my\nrare cards would be gone.\n\n")
  LANGUAGE_TEXT(1, "En effet, les Neo Ghouls\nsont effrayants.\n\nSans Mai, j'aurais perdu\nmes cartes rares.\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls sind wirk-\nlich Angst einfl\xf6\xdfend.\n\nWenn es Mai nicht g\xe4be,\nw\xe4ren die seltenen\n\nKarten weg.\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls incutono\nmolta paura. Se non\n\nfosse stato per Mai, avrei\nperso le mie carte rare.\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls son\ntemibles, desde luego.\n\nSi no fuera por Mai, mis\ncartas raras habr\xedan\n\ndesaparecido.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D64, map_26_state_06_08EA3D64, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Oh, no. No more duels for\nme, thank you kindly.\n\n")
  LANGUAGE_TEXT(1, "Oh, non. Plus de duels\npour moi, merci beaucoup.\n\n")
  LANGUAGE_TEXT(2, "Oh, nein danke. Keine\nweiteren Duelle f\xfcr mich.\n\n")
  LANGUAGE_TEXT(3, "Oh, no. Niente pi\xf9 duelli\nper me, ti ringrazio.\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, no! No m\xe1s duelos\npara m\xed, muchas gracias.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D70, map_26_state_06_08EA3D70, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "How could we be attacked by\nthe Neo Ghouls?\n\nDear me, this ship's\nsecurity is not up to\n\nsnuff.\n\n")
  LANGUAGE_TEXT(1, "Comment se fait-il\nque les Neo Ghouls\n\nont pu nous attaquer ?\n\nLa s\xe9curit\xe9 du paquebot\nn'est pas assez bonne.\n\n")
  LANGUAGE_TEXT(2, "Wie konnten uns die\nNeo Ghouls nur angreifen?\n\nDie Sicherheit dieses\nSchiffs ist zu d\xfcrftig.\n\n")
  LANGUAGE_TEXT(3, "Com'\xe8 possibile che i Neo\nGhouls ci abbiano\n\nattaccati? \xc8 ovvio che la\nsorveglianza sulla nave\n\nlascia a desiderare.\n\n")
  LANGUAGE_TEXT(4, "\xbfC\xf3mo pudimos ser\natacados por los\n\nNeo Ghouls?\n\nLa seguridad de este\nbarco es para llorar.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D7C, map_26_state_06_08EA3D7C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm sorry, the idea doesn't\nenthuse me.\n\n")
  LANGUAGE_TEXT(1, "Je suis d\xe9sol\xe9e, mais\ncela ne me dit rien.\n\n")
  LANGUAGE_TEXT(2, "Tut mir Leid, das ist\nnichts f\xfcr mich.\n\n")
  LANGUAGE_TEXT(3, "Mi spiace, ma l'idea\nnon mi entusiasma.\n\n")
  LANGUAGE_TEXT(4, "Lo siento, la idea no\nme entusiasma.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
