#include "event_macros.h"
#include "overworld.h"

/* map_10_state_01: map 10 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E63218, map_10_state_01_08E63218, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I want to get on the Duel\nExpress...\n\nBut I'm lost. I can't find\nDomino Station.\n\n")
  LANGUAGE_TEXT(1, "Je veux prendre le\nDuel Express...\n\nMais je suis perdu.\n\nJe ne trouve pas\nla gare de Domino.\n\n")
  LANGUAGE_TEXT(2, "Ich will mit dem Duel\nExpress fahren...\n\nAber ich habe mich verirrt.\nWo ist der Bahnhof von\n\nDomino?\n\n")
  LANGUAGE_TEXT(3, "Voglio salire sul Duel\nExpress... Ma mi\n\nsono perso. Non trovo la\nStazione di Domino.\n\n")
  LANGUAGE_TEXT(4, "Quiero ir en el\nDuel Express...\n\nPero me he perdido,\nno puedo encontrar\n\nla Estaci\xf3n Domino.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E63224, map_10_state_01_08E63224, 0x08E63230, 0x08E63248)
  CHECK_FLAG(37)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E63230, map_10_state_01_08E63230, 0x08E6323C, 0x08F0404C)
  LANGUAGE_TEXT(0, "I'll duel with the deck I\nmade exclusively for the\n\nDuel Express tournament.\n\n")
  LANGUAGE_TEXT(1, "Je vais me battre en duel\navec le Deck cr\xe9\xe9 pour\n\nle Duel Express.\n\n")
  LANGUAGE_TEXT(2, "Ich duelliere mich mit dem\nDeck, das ich f\xfcr den Duel\n\nExpress zusammengestellt\nhabe.\n\n")
  LANGUAGE_TEXT(3, "Dueller\xf2 con il deck che\nho preparato per il\n\nDuel Express.\n\n")
  LANGUAGE_TEXT(4, "Luchar\xe9 con el deck que hice\npara el Duel Express.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6323C, map_10_state_01_08E6323C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(7)
  LANGUAGE_TEXT(0, "Maybe it's a good think I'm\nnot on the Duel Express...\n\n")
  LANGUAGE_TEXT(1, "Je ne devrais peut-\xeatre pas\nprendre le Duel Express...\n\n")
  LANGUAGE_TEXT(2, "Vielleicht sollte ich nicht\nden Duel Express nehmen...\n\n")
  LANGUAGE_TEXT(3, "Forse non dovrei prendere\nil Duel Express...\n\n")
  LANGUAGE_TEXT(4, "Quiz\xe1s no tendr\xeda que\ncoger el Duel Express...\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(37)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E63248, map_10_state_01_08E63248, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Let me think about how to\nreconstruct my deck first.\n\n")
  LANGUAGE_TEXT(1, "Laisse-moi r\xe9fl\xe9chir\nun peu \xe0 mon Deck.\n\n")
  LANGUAGE_TEXT(2, "Mal sehen, wie mein Deck\naussehen sollte.\n\n")
  LANGUAGE_TEXT(3, "Fammi pensare a come\ndovrebbe essere\n\nfatto il mio deck.\n\n")
  LANGUAGE_TEXT(4, "D\xe9jame pensar c\xf3mo\ndeber\xeda hacer mi deck.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
