#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_08: map 6 state 8 */

LOAD_SPRITE(1, SPRITE_LUCKY)
LOAD_SPRITE(2, SPRITE_DUKE)
LOAD_SPRITE(3, SPRITE_SERENITY)
PLAY_MUSIC(MUSIC_MONKEY_ROBOTS)
DELAY(16)
PLAY_MUSIC(MUSIC_203)
TEXT
(
    "Arf arf arf arf arf!\n\n"
)
TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Lucky, what's wrong?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_SERENITY, DIRECTION_RIGHT, 0, 0)
WALK_OBJECT_X(0, 80)
WALK_OBJECT_X(13, 90)
WALK_OBJECT_X(14, 90)
DELAY(16)
TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Hey Joey!\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}! Yugi and Joey!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
DELAY(32)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
DELAY(32)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
DELAY(32)
MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Is Tristan around? I don't\n"
    "see him...\n\n"
)
TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SAD, PORTRAIT_POSITION_AUTO,
    "H-he...\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_SAD, PORTRAIT_POSITION_AUTO,
    "T-Tristan...\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Is something wrong?\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "What? Did somethin' happen\n"
    "to Tristan?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_DUKE | SPRITE_SERENITY)
WALK_OBJECT_X(14, 52)
WALK_OBJECT_Y(14, 40)
MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Serenity! Tell me! What\n"
    "happened to Tristan?\n\n"
)
TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SAD, PORTRAIT_POSITION_AUTO,
    "Joey...\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_SAD, PORTRAIT_POSITION_AUTO,
    "Joey... Tristan isn't\n"
    "here...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(0, 56)
WALK_OBJECT_X(13, 63)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Duh, I can see that. So\n"
    "where is he?\n\n"
)
HIDE_PORTRAIT()
PLAY_MUSIC(MUSIC_332)
FADE_SCREEN(4)
SET_FLAG(EVENT_FLAG_FLASHBACK)
WARP(LOCATION_CARD_SHOP_OUTSIDE, 9, 4, 0)
