#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_34_state_02: map 34 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EC2608, map_34_state_02_08EC2608, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_SERIOUS_ARCHEOLOGIST)
  LOAD_SPRITE(2, SPRITE_CHIEF_ARCHEOLOGIST)
  LOAD_SPRITE(3, SPRITE_FRIVOULOUS_ARCHEOLOGIST)
  LOAD_SPRITE(4, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(5, SPRITE_NEO_GHOUL)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  DELAY(16)
  WALK_OBJECT_X(4, 88)
  DELAY(16)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "There's a duelist here, I know it!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(5, 88)
  DELAY(16)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You better not cross the Neo Ghouls or we'll punish you",
      "hard!",
      "Be a good boy and tell us!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  WALK_OBJECT_X(1, 78)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  TEXT("H-he's in the cave...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  DELAY(4)
  MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
  DELAY(32)
  WALK_OBJECT_X(4, 106)
  WALK_OBJECT_Y(4, 32)
  SET_OBJECT_POSITION(4, 128, 96, 0)
  WALK_OBJECT_X(5, 106)
  WALK_OBJECT_Y(5, 32)
  SET_OBJECT_POSITION(5, 128, 96, 0)
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  SET_FLAG(EVENT_FLAG_SAW_NEO_GHOULS_ENTER_CANADA_CAVE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2614, map_34_state_02_08EC2614, EVENT_NOP, EVENT_NOP)
  TEXT("I can't believe the Neo Ghouls are here, eh?")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2620, map_34_state_02_08EC2620, EVENT_NOP, EVENT_NOP)
  TEXT("I'm in no mood for dueling, buddy.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC262C, map_34_state_02_08EC262C, EVENT_NOP, EVENT_NOP)
  TEXT("I hope the duelist in the cave's all right, eh?")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2638, map_34_state_02_08EC2638, EVENT_NOP, EVENT_NOP)
  TEXT("I'm no duelist, buddy. So I don't duel.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2644, map_34_state_02_08EC2644, EVENT_NOP, EVENT_NOP)
  TEXT("What do you suppose brought the Neo Ghouls out here?")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2650, map_34_state_02_08EC2650, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Sorry, pal, I dedicated my life to fossils.",
      "No more dueling for me."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
