#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_13: map 6 state 13 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD08, map_06_state_13_08E5CD08, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_TRISTAN)
  LOAD_SPRITE(2, SPRITE_DUKE)
  LOAD_SPRITE(3, SPRITE_SERENITY)
  LOAD_SPRITE(4, SPRITE_LUCKY)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You did it, {PLAYER}.",
      "You got rid of the Neo Ghouls... Awesome!",
      "But... Your battle isn't over yet, is it?",
      "{PLAYER}, I know you can win!",
      "Don't worry about the Town of Domino. We'll take care",
      "of it.",
      "Go on ahead and duel like a champion!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD14, map_06_state_13_08E5CD14, 0x08E5CD20, 0x08F0404C)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Sure! If you think you can learn something from me,",
      "I'll duel you!"
  )
  DUEL(DUELIST_TRISTAN_092)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD20, map_06_state_13_08E5CD20, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I hope that was good practice.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD2C, map_06_state_13_08E5CD2C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "We'll look after things while you're gone,",
      "{PLAYER}."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD38, map_06_state_13_08E5CD38, 0x08E5CD44, 0x08F0404C)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "No problem! I'll duel if you want me to.")
  DUEL(DUELIST_DUKE_093)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD44, map_06_state_13_08E5CD44, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I guess I'm too weak to duel you, {PLAYER}.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD50, map_06_state_13_08E5CD50, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, good luck.",
      "I hope Joey doesn't get in the way..."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD5C, map_06_state_13_08E5CD5C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I wouldn't be much of a challenge, {PLAYER}.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
