#include "event_macros.h"
#include "overworld.h"

/* map_12_state_02: map 12 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E6EFA0, map_12_state_02_08E6EFA0, 0x08E6EFAC, 0x08E6EFB8)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My big brother isn't here.\n\nHe's investigating the\nMillennium Items.\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFAC, map_12_state_02_08E6EFAC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "He said there's another\ngroup also looking for\n\nthem.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFB8, map_12_state_02_08E6EFB8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The other group searching\nfor the Items call\n\nthemselves the Neo Ghouls.\n\nYou better watch out for\nthem. They sound like\n\ntrouble.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFC4, map_12_state_02_08E6EFC4, 0x08E6EFD0, 0x08E6EFE8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MOKUBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFD0, map_12_state_02_08E6EFD0, 0x08E6EFDC, 0x08F0404C)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Seto isn't here. But don't\nunderestimate my skills, or\n\nyou're gonna pay big time!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(13)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFDC, map_12_state_02_08E6EFDC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, 8)
  LANGUAGE_TEXT(0, "Argh! I can't believe I\nlost!\n\nBut believe me, my big\nbrother won't lose to no\n\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_MOKUBA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EFE8, map_12_state_02_08E6EFE8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm a busy guy. I don't have\nmuch free time.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
