#include "event_macros.h"

/* map_11_state_03: map 11 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E64358, map_11_state_03_08E64358, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I managed to hide my rare\ncards from the Neo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "J'ai r\xe9ussi \xe0 conserver\nmes cartes rares\n\ndes mains des Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Ich konnte meine seltenen\nKarten vor den Neo Ghouls\n\nverbergen.\n\n")
  LANGUAGE_TEXT(3, "Ce l'ho fatta a non\ndare le mie carte\n\nrare ai Neo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "He conseguido evitar\nque los Neo Ghouls\n\nse queden con mis\ncartas raras.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64364, map_11_state_03_08E64364, 0x08E64370, 0x08E64388)
  CHECK_FLAG(128)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64370, map_11_state_03_08E64370, 0x08E6437C, 0x08F0404C)
  LANGUAGE_TEXT(0, "Do you know how hard it was\nto protect my rare cards?!\n\nI won't let you have one so\neasily!\n\n")
  LANGUAGE_TEXT(1, "J'ai r\xe9ussi \xe0 prot\xe9ger\nmes cartes rares.\n\nJe ne vais pas en\ndonner une maintenant.\n\n")
  LANGUAGE_TEXT(2, "Ich sch\xfctzte meine\nseltenen Karten.\n\nAuch jetzt werde ich keine\naufgeben.\n\n")
  LANGUAGE_TEXT(3, "Ho protetto le mie carte\nrare dai pericoli.\n\nE ora non intendo\ndarne via una.\n\n")
  LANGUAGE_TEXT(4, "He evitado que se da\xf1aran\nmis cartas raras.\n\nNo pienso perder\nni una.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(95)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6437C, map_11_state_03_08E6437C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(7)
  LANGUAGE_TEXT(0, "Tsk... After all I did to\nsave that rare card...\n\n")
  LANGUAGE_TEXT(1, "Pff... Apr\xe8s tout\nce que j'ai fait\n\npour prot\xe9ger\ncette carte rare...\n\n")
  LANGUAGE_TEXT(2, "Tss... Und dabei habe ich\ndiese seltene Karte\n\nso gesch\xfctzt...\n\n")
  LANGUAGE_TEXT(3, "No... Dopo tutto ci\xf2 che ho\nfatto per proteggere\n\nquella carta rara...\n\n")
  LANGUAGE_TEXT(4, "Tch... Despu\xe9s de\ntodo lo que hice\n\npara proteger esa\ncarta rara...\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(128)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64388, map_11_state_03_08E64388, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I don't want to lose any\nmore rare cards to you.\n\n")
  LANGUAGE_TEXT(1, "Je ne vais pas perdre\nd'autres cartes rares\n\nen me battant contre toi.\n\n")
  LANGUAGE_TEXT(2, "Ich will nicht noch mehr\nseltene Karten an dich\n\nverlieren.\n\n")
  LANGUAGE_TEXT(3, "Non perder\xf2 pi\xf9 carte\nrare con te.\n\n")
  LANGUAGE_TEXT(4, "No pienso que te hagas con\nuna carta rara m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
