#include "event_macros.h"
#include "overworld.h"

/* map_29_state_08: map 29 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC96C, map_29_state_08_08EAC96C, 0x08EAC978, 0x08F0404C)
  PLAY_MUSIC(32)
  DELAY(32)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh! Fantastic!\n\nThis is where we'll film my\nnew movie!\n\n")
  LANGUAGE_TEXT(1, "Oh ! Fantastique !\n\nC'est ici que le nouveau\nfilm sera film\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Oh! Fantastisch!\n\nHier wird der neue Film\ngedreht werden!\n\n")
  LANGUAGE_TEXT(3, "Oh! Fantastico!\n\n\xc8 qui che gireranno\nil nuovo film!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh! \xa1Fant\xe1stico!\n\n\xa1Aqu\xed se rodar\xe1 la\nnueva pel\xedcula!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 60)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hey! You!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 ! Toi !\n\n")
  LANGUAGE_TEXT(2, "He! Du da!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Dico a te!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hey! \xa1T\xfa!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Are you talking to me?\n\n")
  LANGUAGE_TEXT(1, "Vous m'avez appel\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Hast du mich gerufen?\n\n")
  LANGUAGE_TEXT(3, "Mi hai chiamato?\n\n")
  LANGUAGE_TEXT(4, "\xbfLlamaste?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm Hollywood superstar Jean\nClaude Magnum, but I'm sure\n\nyou already knew that.\n\nI'm shooting my next film\nhere.\n\n")
  LANGUAGE_TEXT(1, "Je suis\nJean-Claude Magnum,\n\nla m\xe9ga star\nhollywoodienne.\n\nNous allons filmer notre\nprochain film ici.\n\n")
  LANGUAGE_TEXT(2, "Ich bin Jean-Claude Magnum,\nder Hollywood-Superstar.\n\nWir drehen hier unseren\nn\xe4chsten Film.\n\n")
  LANGUAGE_TEXT(3, "Sono Jean-Claude Magnum,\nla superstar di Hollywood.\n\nGireremo qui il nostro\nprossimo film.\n\n")
  LANGUAGE_TEXT(4, "Soy Jean-Claude\nMagnum, la super-\n\nestrella de Hollywood.\n\nRodaremos nuestra\npr\xf3xima pel\xedcula aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What are you doing here?\n\n")
  LANGUAGE_TEXT(1, "Et qu'est-ce que\ntu fais par ici ?\n\n")
  LANGUAGE_TEXT(2, "Und was f\xfchrt dich hierher?\n\n")
  LANGUAGE_TEXT(3, "Tu cosa ci fai qui?\n\n")
  LANGUAGE_TEXT(4, "\xbfY t\xfa qu\xe9 haces aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm a tour guide, plus I\nread fortunes.\n\n")
  LANGUAGE_TEXT(1, "Je suis un guide et aussi un\ndiseur de bonne aventure.\n\n")
  LANGUAGE_TEXT(2, "Ich bin Reisef\xfchrer und\nWahrsager.\n\n")
  LANGUAGE_TEXT(3, "Sono una guida turistica\ne predico il futuro.\n\n")
  LANGUAGE_TEXT(4, "Soy gu\xeda tur\xedstico y\nadivino la suerte.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Fortunetelling!\n\nHow absolutely spectacular!\n\nI want you to read the\nfuture regarding my\n\nmarriage proposal to Mai\nValentine.\n\n")
  LANGUAGE_TEXT(1, "Diseur de bonne aventure !\n\nMais cela tombe \xe0 point !\n\nQu'en est-il de mes fian\xe7ai-\nlles \xe0 Mai Valentine.\n\n")
  LANGUAGE_TEXT(2, "Wahrsager!\n\nWelche F\xfcgung des\nSchicksals!\n\nBitte sag mir, was aus\nmeinem Antrag wird,\n\nden ich Mai Valentine\ngemacht habe.\n\n")
  LANGUAGE_TEXT(3, "Tu predici il futuro!\n\nMa che combinazione!\nPer favore, dimmi se Mai\n\nValentine accetter\xe0 la mia\nofferta di matrimonio.\n\n")
  LANGUAGE_TEXT(4, "\xa1Adivino!\n\n\xa1Qu\xe9 fortuito!\n\nDime sobre mi propuesta\na Mai Valentine.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No problem.\n\n")
  LANGUAGE_TEXT(1, "Ah oui, bien s\xfbr.\n\n")
  LANGUAGE_TEXT(2, "Kein Problem.\n\n")
  LANGUAGE_TEXT(3, "Ma certo.\n\n")
  LANGUAGE_TEXT(4, "Pues claro...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(8)
  MOVE_OBJECT(1, 1, 16, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(8)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(8)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Spirits of the Catacombs,\nanswer me...\n\n")
  LANGUAGE_TEXT(1, "L'esprit des Catacombes\nva me r\xe9pondre...\n\n")
  LANGUAGE_TEXT(2, "Die Geister der Katakomben\nantworten mir...\n\n")
  LANGUAGE_TEXT(3, "Gli spiriti delle Catacombe\nmi daranno risposta...\n\n")
  LANGUAGE_TEXT(4, "Los esp\xedritus de las\nCatacumbas me\n\nresponden...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 3, 16, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Infuse me with the knowledge\nof the past so that I can\n\nglimpse the future...\n\n")
  LANGUAGE_TEXT(1, "Conna\xeetre le pass\xe9\net pr\xe9voir le futur...\n\n")
  LANGUAGE_TEXT(2, "Kenntnis der Vergangenheit\nund ein Blick auf\n\ndie Zukunft...\n\n")
  LANGUAGE_TEXT(3, "Conoscenza del passato\ne uno sguardo al futuro...\n\n")
  LANGUAGE_TEXT(4, "Conocimiento del pasado\ny un vistazo del futuro...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 10, 0)
  MOVE_OBJECT(1, 0, 10, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 0, 10, 0)
  MOVE_OBJECT(1, 3, 10, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 3, 10, 0)
  MOVE_OBJECT(1, 2, 10, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(16)
  MOVE_OBJECT(1, 2, 10, 0)
  MOVE_OBJECT(1, 1, 10, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  DELAY(64)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 4)
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You can marry her if you win\nthree duels in a row.\n\n")
  LANGUAGE_TEXT(1, "Tu pourras te marier\nsi tu remportes\n\ntrois duels \xe0 la suite.\n\n")
  LANGUAGE_TEXT(2, "Gewinn drei Duelle in Folge,\ndann kannst du heiraten.\n\n")
  LANGUAGE_TEXT(3, "Potrai sposarti se vincerai\ntre duelli di fila.\n\n")
  LANGUAGE_TEXT(4, "Puedes casarte si ganas\ntres duelos seguidos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Really? You better not be\njoking!\n\nIf it's true, it was worth\nmaking this trip to the\n\nItalian Catacombs!\n\n")
  LANGUAGE_TEXT(1, "Vraiment ?\n\nCe voyage jusqu'\xe0\ncette terre \xe9loign\xe9e\n\naurait donc \xe9t\xe9 utile !\n\n")
  LANGUAGE_TEXT(2, "Wirklich?\nUngelogen?\n\nDiese Reise zu diesem entle-\ngenen Ort hat sich gelohnt!\n\n")
  LANGUAGE_TEXT(3, "Davvero? Non mi stai\nmentendo? Venire in\n\nquesto luogo lontano\n\xe8 stato la mia fortuna!\n\n")
  LANGUAGE_TEXT(4, "\xbfDe verdad?\n\xbfNo me mientes?\n\n\xa1Ha sido rentable\nvenir hasta aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let the countdown to my\nwedding begin!\n\nThere's my first victim!\n\n")
  LANGUAGE_TEXT(1, "Le compte \xe0 rebours\nde mon mariage\n\na commenc\xe9 ! Voici\nla premi\xe8re victime !\n\n")
  LANGUAGE_TEXT(2, "Der Countdown zu meiner\nHochzeit hat begonnen!\n\nDa ist auch schon mein\nerstes Opfer!\n\n")
  LANGUAGE_TEXT(3, "Inizia il conto alla\nrovescia al mio\n\nmatrimonio. Ma ecco\nla prima vittima!\n\n")
  LANGUAGE_TEXT(4, "\xa1La cuenta atr\xe1s a\nmi boda comienza!\n\n\xa1Ha aparecido la\nprimera v\xedctima!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(2, 30)
  DELAY(16)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm counting down to my\nmarriage with Mai!\n\nDon't worry. Even when you\nlose, I'll let you be my\n\nbest man.\n\n")
  LANGUAGE_TEXT(1, "Le compte \xe0 rebours\nde mon mariage \xe0 Mai\n\npeut commencer !\n\nTu vas \xeatre le premier\n\xe0 nous f\xe9liciter... !\n\n")
  LANGUAGE_TEXT(2, "Der Countdown f\xfcr meine\nHochzeit mit Mai beginnt!\n\nDu darfst mit der Glocke\ndie Trauung verk\xfcnden!\n\n")
  LANGUAGE_TEXT(3, "Dai il via al conto alla\nrovescia per le mie nozze\n\ncon Mai! Sarai tu il primo\na congratularti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Que comience la cuenta\natr\xe1s de mi boda con Mai!\n\n\xa1Hay que doblar la\nprimera campana\n\nde felicitaci\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(131)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC978, map_29_state_08_08EAC978, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, 8)
  LANGUAGE_TEXT(0, "N-noooooo!\n\nMy marriage to Mai...\n\n")
  LANGUAGE_TEXT(1, "N-noooooon !\n\nMon mariage \xe0 Mai...\n\n")
  LANGUAGE_TEXT(2, "N-neiiiiiiiin!\n\nMeine Hochzeit mit Mai...\n\n")
  LANGUAGE_TEXT(3, "Oh nooooo!\n\nLe mie nozze con Mai...\n\n")
  LANGUAGE_TEXT(4, "\xa1N-noooooo!\n\nMi boda con Mai...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh, oh yeah!! I just need to\nwin three times in a row!\n\nIt never said I had to duel\nanybody strong!\n\nThat's why I'm outta here!\n\nFarewell!\n\n")
  LANGUAGE_TEXT(1, "Oh ! Oh, oui !\nIl faut seulement\n\nque je gagne\n{BYTE_8252} fois de suite !\n\nPas la peine d'affronter\nplus fort que moi en duel !\n\nBon, je n'ai plus rien\n\xe0 faire ici !\n\nAdieu !\n\n")
  LANGUAGE_TEXT(2, "Oh! Oh, gut! Ich muss nur\ndreimal hintereinander\n\ngewinnen! Es kann auch ein\nsehr schwacher Gegner sein!\n\nDann kann ich wieder gehen!\n\nMach's gut!\n\n")
  LANGUAGE_TEXT(3, "Oh! Oh, s\xec! Devo solo\nvincere tre volte di fila!\n\nNon devo mica battermi\ncon qualcuno forte!\n\nQuindi non c'\xe8 bisogno\nche stia qui!\n\nAddio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh! \xa1Oh, s\xed!\n\n\xa1S\xf3lo tengo que ganar tres\nveces seguidas!\n\n\xa1No tengo que luchar con\nnadie medianamente fuerte!\n\nEntonces, \xa1no tengo\nque estar aqu\xed!\n\n\xa1Adi\xf3s!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 0)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "...I forgot to mention that\nif lose even one duel, your\n\nfortune changes. Oh well.\n\n")
  LANGUAGE_TEXT(1, "... Si tu perds,\nm\xeame une seule fois,\n\nta chance tournera...\n\n")
  LANGUAGE_TEXT(2, "Wenn du aber einmal\nverlierst, \xe4ndert sich\n\ndein Schicksal...\n\n")
  LANGUAGE_TEXT(3, "... Se perdi anche una sola\nvolta, le cose cambiano...\n\n")
  LANGUAGE_TEXT(4, "... Si pierdes una sola\nvez, tu suerte cambia...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24577)
  SET_FLAG(EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM2)
  FALLTHROUGH()
END_EVENT_SCRIPT()
