#include "event_macros.h"
#include "overworld.h"

/* map_31_state_01: map 31 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EB4264, map_31_state_01_08EB4264, 0x08EB427C, 0x08EB4288)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB427C, map_31_state_01_08EB427C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Hiyah! This is a special\ndish for all, found only at\n\nthe Great Wall!\n\nIt's my Great Wall noodle\nsoup! Eat and slurp!\n\n")
  LANGUAGE_TEXT(1, "Allez, allez !\nGo\xfbtez la sp\xe9cialit\xe9\n\nde la Grande Muraille !\nGo\xfbtez mes nouilles !\n\n")
  LANGUAGE_TEXT(2, "Aiyah! Das ist Spezialit\xe4t\nnul hiel an glo\xdfe Mauel!\n\nMeine Mauelnudel!\nMache ich spezial f\xfcl hiel!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Questa \xe8 una specialit\xe0\nche si trova solo qui,\n\nsulla Grande Muraglia!\nI miei tagliolini della\n\nGrande Muraglia! Fatti\napposta per questo posto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Aiyah! Esto es una\nespecialidad \xfanica\n\nde aqu\xed, la Gran Muralla.\n\nMis noodles de la Gran\nMuralla. \xa1Los hago\n\nespeciales para aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4288, map_31_state_01_08EB4288, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm very busy making\nnoodles, okay?\n\n")
  LANGUAGE_TEXT(1, "Je suis tr\xe8s occup\xe9\n\xe0 faire des nouilles, OK ?\n\n")
  LANGUAGE_TEXT(2, "Ich sehl viel zu tun mit\nNudeln, okay? Okay.\n\n")
  LANGUAGE_TEXT(3, "Sono molto indaffarato\na preparare i tagliolini,\n\ncapito? Okay.\n\n")
  LANGUAGE_TEXT(4, "Yo muy ocupado haciendo\nnoodles, \xbfvale? Vale.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4258, map_31_state_01_08EB4258, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(706)
  PLAY_MUSIC(380)
  WALK_OBJECT_Y(0, 56)
  SHOW_OBJECT(13, 78, 88, 0, 0, 0)
  WALK_OBJECT_Y(13, 66)
  SHOW_OBJECT(14, 66, 88, 0, 0, 0)
  WALK_OBJECT_Y(14, 66)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(1, 72)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  LANGUAGE_TEXT(0, "Hiyah! This is a special\ndish for all, found only at\n\nthe Great Wall!\n\nIt's my Great Wall noodle\nsoup! Eat and slurp!\n\n")
  LANGUAGE_TEXT(1, "Allez, allez !\nGo\xfbtez la sp\xe9cialit\xe9\n\nde la Grande Muraille !\nGo\xfbtez mes nouilles !\n\n")
  LANGUAGE_TEXT(2, "Aiyah! Das ist Spezialit\xe4t\nnul hiel an glo\xdfe Mauel!\n\nMeine Mauelnudel!\nMache ich spezial f\xfcl hiel!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Questa \xe8 una specialit\xe0\nche si trova solo qui,\n\nsulla Grande Muraglia!\nI miei tagliolini della\n\nGrande Muraglia! Fatti\napposta per questo posto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Aiyah! Esto es una\nespecialidad \xfanica\n\nde aqu\xed, la Gran Muralla.\n\nMis noodles de la Gran\nMuralla. \xa1Los hago\n\nespeciales para aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 68)
  WALK_OBJECT_Y(1, 38)
  MOVE_OBJECT(1, 0, 0, 0)
  SET_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4270, map_31_state_01_08EB4270, 0x08EB427C, 0x08EB4294)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4294, map_31_state_01_08EB4294, 0x08EB42A0, 0x08EB42D0)
  CHECK_FLAG(EVENT_FLAG_JOEY_FOUND_PARA_AND_DOX_SUSPICIOUS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42A0, map_31_state_01_08EB42A0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Hiyah! You want to duel?\n\nI'm too busy making noodles\nand gruel. I have no time\n\nto duel.\n\n")
  LANGUAGE_TEXT(1, "Aiyah ! Tu veux te battre\nen duel avec les cartes ?\n\nMoi, tr\xe8s occup\xe9 faire\nnouilles.\n\nPas le temps duel !\n\n")
  LANGUAGE_TEXT(2, "Aiyah! Willst du Duell mit\nKalten?\n\nIch sehl viel zu tun mit\nNudeln. Ich kein Duell.\n\n")
  LANGUAGE_TEXT(3, "Eh? Volere duellare\ncon le carte?\n\nSono indaffarato a\npreparare i tagliolini.\n\nIo non duellare.\n\n")
  LANGUAGE_TEXT(4, "\xa1Aiyah! \xbfQuieres luchar\ncon cartas?\n\nYo muy ocupado haciendo\nnoodles. No lucho.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42D0, map_31_state_01_08EB42D0, 0x08EB42DC, 0x08F0404C)
  PLAY_MUSIC(404)
  PLAY_MUSIC(330)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Grrr! How cleverly you\nsurmise to see through our\n\ndisguise!\n\n")
  LANGUAGE_TEXT(1, "Grrr ! Tu as remarqu\xe9\nnotre d\xe9guisement !\n\n")
  LANGUAGE_TEXT(2, "Grrr! Clever von dir, uns\nzu durchschauen!\n\n")
  LANGUAGE_TEXT(3, "Grr! E cos\xec, intelligentone,\nci hai scoperti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Grrr! \xa1Muy bueno eso\nde ver a trav\xe9s de\n\nnuestros disfraces!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 48)
  WALK_OBJECT_X(0, 68)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_X(13, 52)
  WALK_OBJECT_Y(13, 40)
  MOVE_OBJECT(13, 3, 0, 0)
  WALK_OBJECT_X(14, 84)
  WALK_OBJECT_Y(14, 40)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Very well! You leave us with\nno choice!\n\nI challenge you in Master\nSol Chevalsky's place!\n\nWe shall duel! Prepare to\nlose, you fool!\n\n")
  LANGUAGE_TEXT(1, "Tr\xe8s bien ! Nous n'avons\npas le choix !\n\nA la place de Ma\xeetre Sol\nChevalsky, je te d\xe9fie !\n\nBattons-nous en duel !\nEn garde !\n\n")
  LANGUAGE_TEXT(2, "Nun gut! Du l\xe4sst uns keine\nWahl! Im Namen von\n\nMeister Sol Chevalsky - ich\nfordere dich zum Duell!\n\nAuf in den Kampf!\nEn garde!\n\n")
  LANGUAGE_TEXT(3, "Benissimo! Non c'\xe8\naltra scelta!\n\nIo ti sfido al posto del\nMaestro Sol Chevalsky!\n\nDuelliamo allora!\nIn guardia!\n\n")
  LANGUAGE_TEXT(4, "\xa1Muy bien!\n\xa1No me dejas alternativa!\n\n\xa1Te reto en lugar del\namo Sol Chevalsky!\n\n\xa1Lucharemos!\n\xa1En guardia!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(39)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42DC, map_31_state_01_08EB42DC, 0x08EB42E8, 0x08F04040)
  PLAY_MUSIC(404)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "That was cruel! I concede\ndefeat in this duel!\n\nBut our true skill is in tag\nduels!\n\n")
  LANGUAGE_TEXT(1, "Tr\xe8s bien ! J'accepte la\nd\xe9faite dans ce duel !\n\nMais notre vraie force,\nce sont les duels \xe0 deux !\n\n")
  LANGUAGE_TEXT(2, "Na gut! Dieses Mal gebe\nich mich geschlagen!\n\nUnsere wahre St\xe4rke sind\njedoch die Doppelduelle!\n\n")
  LANGUAGE_TEXT(3, "Ebbene, ti concedo la\nsconfitta in questo duello!\n\nMa la nostra forza \xe8 nei\nduelli doppi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale! \xa1Admito que he\nperdido este duelo!\n\n\xa1Pero nuestro fuerte\nson los duelos a dos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 0)
  LANGUAGE_TEXT(0, "Younger brother, let us take\nthem down together!\n\n")
  LANGUAGE_TEXT(1, "Petit fr\xe8re, viens ici !\n\n")
  LANGUAGE_TEXT(2, "Kleiner Bruder, komm!\n\n")
  LANGUAGE_TEXT(3, "Fratello minore, vieni!\n\n")
  LANGUAGE_TEXT(4, "Hermano menor, \xa1ven!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(2, 92)
  PLAY_MUSIC(271)
  REACTION(0, 16384)
  SLIDE_OBJECT(14, 0, 6)
  MOVE_OBJECT(14, 2, 0, 0)
  WALK_OBJECT_X(2, 76)
  SWAP_OBJECT_SPRITE(2, 24)
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(8)
  MOVE_OBJECT(14, 3, 8, 0)
  MOVE_OBJECT(14, 2, 6, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Elder brother! I am here to\nhelp!\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re ! Je\nsuis l\xe0 pour t'aider !\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder!\nIch steh dir bei!\n\n")
  LANGUAGE_TEXT(3, "Fratello maggiore!\nSono qui per aiutare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hermano mayor!\n\xa1He venido a ayudar!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 0)
  LANGUAGE_TEXT(0, "In a tag duel, defeating the\nlikes of you...\n\n")
  LANGUAGE_TEXT(1, "Dans un duel \xe0 deux, battre\nun type comme toi...\n\n")
  LANGUAGE_TEXT(2, "In einem Doppelduell ist\nein Sieg gegen euch...\n\n")
  LANGUAGE_TEXT(3, "In un duello doppio,\nsconfiggere i tuoi pari...\n\n")
  LANGUAGE_TEXT(4, "En un duelo a dos, derrotar\na gente como vosotros...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "...Would be so simple I\nalready bid you adieu!\n\n")
  LANGUAGE_TEXT(1, "... \xe7a serait un peu\ncomme battre des b\xe9b\xe9s !\n\n")
  LANGUAGE_TEXT(2, "... ein Kinderspiel...\n\n")
  LANGUAGE_TEXT(3, "... Non sarebbe pi\xf9\ndifficile di battere\n\ndegli infanti!\n\n")
  LANGUAGE_TEXT(4, "... \xa1No ser\xeda m\xe1s duro\nque hacerlo con ni\xf1os!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42E8, map_31_state_01_08EB42E8, 0x08EB42F4, 0x08EB4300)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_Y(6, 64)
  DELAY(16)
  PLAY_MUSIC(405)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I can't believe you're\nstruggling against these\n\namateurs!\n\n")
  LANGUAGE_TEXT(1, "Pourquoi est-ce que tu\nlaisses ces nuls te\n\nralentir ?\n\n")
  LANGUAGE_TEXT(2, "Warum l\xe4sst du dich von die-\nsem Abschaum aufhalten?\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 consenti a questa\nfeccia di rallentarti?\n\n")
  LANGUAGE_TEXT(4, "\xbfPor qu\xe9 permites que estos\ncutres te enlentezcan?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24583)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Kaiba!\n\n")
  LANGUAGE_TEXT(1, "Kaiba Seto ?\n\n")
  LANGUAGE_TEXT(2, "Kaiba Seto?\n\n")
  LANGUAGE_TEXT(3, "Kaiba Seto?\n\n")
  LANGUAGE_TEXT(4, "\xbfKaiba Seto?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "My big brother's here to\ntake you down\n\nBecause you work for Sol\nChevalsky.\n\n")
  LANGUAGE_TEXT(1, "Mon fr\xe8re est venu\nvous donner une le\xe7on.\n\nVous \xeates les larbins\nde Sol Chevalsky.\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder ist hier,\num euch eine Lektion zu\n\nerteilen. Ihr seid die\nSchergen von Sol Chevalsky.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello \xe8 venuto\na darvi una batosta.\n\nSiete i servi di Sol\nChevalsky.\n\n")
  LANGUAGE_TEXT(4, "Mi gran hermano vino\na daros bien.\n\nSois los mequetrefes\nde Sol Chevalsky.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The only duelist worthy of\nthe Egyptian God Cards...\n\nIs me!\n\nI'll show no mercy, even\nagainst miserable duelists\n\nlike you!\n\n")
  LANGUAGE_TEXT(1, "Le seul duelliste digne\ndes cartes de dieux...\n\nC'est moi, Kaiba Seto !\n\nAvec moi, pas question\nde plaisanter !\n\n")
  LANGUAGE_TEXT(2, "Der einzige Duellant, der\ndie G\xf6tterkarten\n\nverdient...\n... bin ich, Kaiba Seto!\n\nIch dulde keine Einmischung,\nnicht einmal von Abschaum!\n\n")
  LANGUAGE_TEXT(3, "L'unico duellante degno\ndelle carte divine...\n\nSono io, Kaiba Seto!\n\nNon tollerer\xf2 interferenze,\nnemmeno dalla feccia!\n\n")
  LANGUAGE_TEXT(4, "El \xfanico duelista digno de\nlas cartas de los dioses...\n\nEse soy yo, \xa1Kaiba Seto!\n\n\xa1No tolerar\xe9 injerencias,\nni siquiera de cutres!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 0)
  LANGUAGE_TEXT(0, "{PLAYER}! Today's your lucky\nday!\n\nI'll help you! Choose which\nsissy to duel!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} ! Estime-\ntoi chanceux !\n\nJe vais t'aider ! Choisis un\nnul \xe0 battre en duel !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}! Sieh es als\nEhre an!\n\nIch helfe dir! W\xe4hl einen\naus diesem Abschaum\n\nals Duellgegner!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}! Considerati\nprivilegiato!\n\nTi aiuter\xf2! Scegliti un\nidiota con cui duellare!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}! \xa1Consid\xe9-\nrate un privilegiado!\n\n\xa1Te ayudar\xe9! \xa1Escoge a un\ncutre para el duelo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Para\nDox{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Para\nDox{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42F4, map_31_state_01_08EB42F4, 0x08EB430C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(5, 2, 8, 0)
  WALK_OBJECT_X(5, 76)
  WALK_OBJECT_Y(5, 48)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  MOVE_OBJECT(6, 3, 16, 0)
  WALK_OBJECT_Y(6, 48)
  MOVE_OBJECT(6, 1, 0, 0)
  DELAY(16)
  DUEL(40)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB430C, map_31_state_01_08EB430C, 0x08EB4318, 0x08F04040)
  PLAY_MUSIC(405)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Come forth, Blue-Eyes White\nDragon!\n\n")
  LANGUAGE_TEXT(1, "Approche, Dragon blanc\naux yeux bleus.\n\n")
  LANGUAGE_TEXT(2, "Komm her, blau\xe4ugiger\nwei\xdfer Drache!\n\n")
  LANGUAGE_TEXT(3, "Vieni qui, Drago\nBianco Occhi Blu!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ven aqu\xed, Drag\xf3n\nblanco de ojos azules!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 9)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "White Lightning!\n\n")
  LANGUAGE_TEXT(1, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(2, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(3, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(4, "\xa1Burst Stream of Ruin!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(338)
  COMMAND_7C_ARG(8, 55)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4318, map_31_state_01_08EB4318, 0x08EB4324, 0x08F04040)
  SLIDE_OBJECT(1, 2, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, 0)
  LANGUAGE_TEXT(0, "M-Master Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(1, "M-Ma\xeetre Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(2, "M-Meister Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(3, "M-Maestro Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(4, "A-amo Sol Chevalsky...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, 0)
  LANGUAGE_TEXT(0, "...W-we have failed you...\n\n")
  LANGUAGE_TEXT(1, "... N-nous avons manqu\xe9\n\xe0 nos engagements...\n\n")
  LANGUAGE_TEXT(2, "... W-wir haben Sie\nentt\xe4uscht...\n\n")
  LANGUAGE_TEXT(3, "... Ti-ti abbiamo deluso...\n\n")
  LANGUAGE_TEXT(4, "... T-te hemos fallado...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 0)
  LANGUAGE_TEXT(0, "Run to Sol Chevalsky and\ntell him.\n\nThat as long as Seto Kaiba\nlives...\n\nAll his plans are doomed to\nfail! Wahahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Retourne vite avertir\nSol Chevalsky\n\nque tant que Kaiba\nSeto sera en vie,\n\nses plans mal\xe9fiques\n\xe9choueront !\n\nMouah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Lauf zur\xfcck zu Sol\nChevalsky und teil ihm mit:\n\nSolange Kaiba Seto lebt...\n\nSind all seine Pl\xe4ne zum\nScheitern verurteilt!\n\nWahahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Corri da Sol\nChevalsky e digli\n\nche finch\xe9 Kaiba\nSeto vivr\xe0...\n\nle sue trame saranno\nsconvolte! Uahahahah!\n\n")
  LANGUAGE_TEXT(4, "Corre hasta Sol\nChevalsky y dile\n\nque en tanto Kaiba\nSeto viva...\n\nsus maquinaciones\nse ver\xe1n frustradas.\n\n\xa1Wajajaja!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4324, map_31_state_01_08EB4324, 0x08EB4330, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  WALK_OBJECT_Y(1, 96)
  MOVE_OBJECT(2, 3, 8, 0)
  WALK_OBJECT_Y(2, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4330, map_31_state_01_08EB4330, 0x08EB436C, 0x08F04040)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, you only won\nbecause you had my help.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu as gagn\xe9\ngr\xe2ce \xe0 mon aide.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du hast nur\nmit meiner Hilfe gewonnen.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, hai vinto\nsolo grazie al mio aiuto.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, s\xf3lo ganaste\ncon mi ayuda.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Listen, {PLAYER}.\n\nI walk my own road.\n\nI don't know if you'll win\nor fail on your journey...\n\nBut try not to disappoint\nme.\n\n")
  LANGUAGE_TEXT(1, "Ecoute, {PLAYER}.\n\nJe veux \xeatre seul sur\nle chemin de la victoire.\n\nJe ne sais pas si tu vas\nr\xe9ussir ou \xe9chouer.\n\nMais ne me d\xe9\xe7ois pas,\net bats-toi vaillamment.\n\n")
  LANGUAGE_TEXT(2, "H\xf6r zu, {PLAYER}.\n\nIch gehe meinen eigenen Weg\nzum Sieg.\n\nOb dich Erfolg oder\nNiederlage erwarten,\n\nsteht in den Sternen.\n\nAber entt\xe4usche mich nicht\nmit halbherzigen\n\nBem\xfchungen.\n\n")
  LANGUAGE_TEXT(3, "Stammi a sentire, {PLAYER}.\n\nSeguir\xf2 il mio percorso\nper la vittoria.\n\nNon so se ti aspetta la\nvittoria o la sconfitta.\n\nMa metticela tutta per\nnon deludermi.\n\n")
  LANGUAGE_TEXT(4, "Escucha, {PLAYER}.\n\nCaminar\xe9 mi propio\ncamino a la victoria.\n\nNo s\xe9 si es \xe9xito o\nfracaso lo que te espera.\n\nPero no me decepciones con\nun pobre esfuerzo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 1, 0)
  LANGUAGE_TEXT(0, "Now go and look for your\nmystical trinkets.\n\nWhile you play scavenger\nhunt, I'll save the world.\n\nWahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Maintenant pars et va\nchercher tes petits\n\nobjets surnaturels.\n\nLes faibles ont leur\nr\xf4le, eux aussi.\n\nOuah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Jetzt geh und such weiter\nnach deinem \xfcbernat\xfcrlichen\n\nTand. Schwache wie du\nhaben eigene Aufgaben.\n\nWahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Ora continua a cercare\ni tuoi ninnoli\n\nsoprannaturali. I deboli\ncome te hanno dei\n\nruoli a s\xe9 stanti.\nUahahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "Ahora ve y busca tus\nbaratijas sobrenaturales.\n\nLos d\xe9biles como t\xfa ten\xe9is\nvuestros roles propios.\n\n\xa1Wahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB436C, map_31_state_01_08EB436C, 0x08EB4378, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 96)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4378, map_31_state_01_08EB4378, 0x08EB4384, 0x08EB4390)
  WALK_OBJECT_Y(6, 56)
  WALK_OBJECT_X(6, 72)
  MOVE_OBJECT(6, 2, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You better hurry up and find\nthe Millennium Items.\n\nWe heard that the Neo Ghouls\nare hunting for them, too.\n\n")
  LANGUAGE_TEXT(1, "Tu ferais bien de te\nd\xe9p\xeacher \xe0 trouver\n\nles Objets du mill\xe9nium.\nOn a entendu dire\n\nque les Neo Ghouls les\ncherchaient eux aussi.\n\n")
  LANGUAGE_TEXT(2, "Beeil dich lieber - such\ndie Millenniumsgegenst\xe4nde.\n\nWir haben geh\xf6rt, dass auch\ndie Neo Ghouls hinter ihnen\n\nher sind.\n\n")
  LANGUAGE_TEXT(3, "Faresti meglio a sbrigarti\na cercare gli Oggetti\n\nMillenari. Abbiamo sentito\ndire che anche i Neo\n\nGhouls gli stanno dando\nla caccia.\n\n")
  LANGUAGE_TEXT(4, "Mejor que corras y halles\nlos Objetos del Milenio.\n\nHemos o\xeddo que los\nNeo Ghouls tambi\xe9n los\n\nandan buscando.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Is that true?\nSo it was true...{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Est-ce que c'est vrai ?\nAlors, c'est donc vrai...{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Wirklich?\nEs stimmte also...{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Davvero?\nAllora era vero... {CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xbfEs eso cierto?\nAs\xed que era cierto...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4384, map_31_state_01_08EB4384, 0x08EB439C, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You can thank KaibaCorp's\ninformation network.\n\nThat's why Seto's here, to\ngive you this info...\n\nOops, he told me not tell\nyou that.\n\nWell, see ya!\n\n")
  LANGUAGE_TEXT(1, "Tu peux remercier le\nr\xe9seau d'informations\n\nde la Kaiba Corporation.\n\nGrand fr\xe8re est en fait\nvenu te dire...\n\nOups, il m'a dit\nde ne rien dire.\n\nA plus !\n\n")
  LANGUAGE_TEXT(2, "Das wissen wir durch das\nInformationsnetz der\n\nKaiba Corp. Mein gro\xdfer\nBruder kam extra, um\n\neuch...\n\nUups, das sollte ich ja\nnicht verraten.\n\nBis sp\xe4ter.\n\n")
  LANGUAGE_TEXT(3, "Puoi ringraziare la rete\ninformativa della Kaiba\n\nCorp. Veramente, mio\nfratello era venuto per\n\ndirti... Accidenti, mi\naveva detto di non dirtelo.\n\nCi vediamo.\n\n")
  LANGUAGE_TEXT(4, "Puedes agradec\xe9rselo\na la red de informaci\xf3n\n\nde Kaiba Corp.\n\nGran hermano vino\nrealmente a decirte...\n\nVaya, me dijo que\nno te lo dijera.\n\nNos vemos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB439C, map_31_state_01_08EB439C, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  TEXT("{BYTE_8168}")
  WALK_OBJECT_Y(6, 96)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_DEFEATED_PARA_AND_DOX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4390, map_31_state_01_08EB4390, 0x08EB439C, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Oh, you knew already?\n\nTo think that we came all\nthe way out here...\n\nJust because Seto wanted you\nto have this info...\n\nOops, that's supposed to be\na secret! Don't let Seto\n\nknow that I told you!\n\nWell, see ya!\n\n")
  LANGUAGE_TEXT(1, "Oh, tu le savais d\xe9j\xe0 ?\n\nMon grand fr\xe8re m'a\ndit de te le dire...\n\nAlors nous sommes\nvenus jusqu'ici...\n\nOups, c'est un secret !\n\nA plus !\n\n")
  LANGUAGE_TEXT(2, "Oh, das wusstest du schon?\n\nMein gro\xdfer Bruder sagte,\nich solle dir mitteilen...\n\nDaher kamen wir extra\nhierher...\n\nUups, das ist ein Geheimnis!\n\nBis sp\xe4ter.\n\n")
  LANGUAGE_TEXT(3, "Oh, lo sapevi gi\xe0?\n\nMio fratello mi ha\ndetto di dirtelo...\n\nQuindi siamo venuti\nfin qui... Ups,\n\nquello \xe8 un segreto!\n\nCi vediamo.\n\n")
  LANGUAGE_TEXT(4, "Oh, \xbfya lo sab\xedas?\n\nMi gran hermano me dijo\nque te dijera...\n\nAs\xed que hicimos todo\nel camino hasta aqu\xed...\n\nVaya, \xa1eso es un\nsecreto!\n\nNos vemos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4300, map_31_state_01_08EB4300, 0x08EB433C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 76)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_Y(5, 48)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  MOVE_OBJECT(6, 1, 24, 0)
  WALK_OBJECT_Y(6, 48)
  MOVE_OBJECT(6, 3, 0, 0)
  DELAY(16)
  DUEL(41)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB433C, map_31_state_01_08EB433C, 0x08EB4348, 0x08F04040)
  PLAY_MUSIC(405)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Come forth, Blue-Eyes White\nDragon!\n\n")
  LANGUAGE_TEXT(1, "Approche, Dragon blanc\naux yeux bleus.\n\n")
  LANGUAGE_TEXT(2, "Komm her, blau\xe4ugiger\nwei\xdfer Drache!\n\n")
  LANGUAGE_TEXT(3, "Vieni qui, Drago\nBianco Occhi Blu!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ven aqu\xed, Drag\xf3n\nblanco de ojos azules!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 9)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "White Lightning!\n\n")
  LANGUAGE_TEXT(1, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(2, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(3, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(4, "\xa1Burst Stream of Ruin!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(338)
  COMMAND_7C_ARG(8, 18)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4348, map_31_state_01_08EB4348, 0x08EB4354, 0x08F04040)
  SLIDE_OBJECT(1, 2, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, 0)
  LANGUAGE_TEXT(0, "M-Master Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(1, "M-Ma\xeetre Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(2, "M-Meister Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(3, "M-Maestro Sol Chevalsky...\n\n")
  LANGUAGE_TEXT(4, "A-amo Sol Chevalsky...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(8)
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, 0)
  LANGUAGE_TEXT(0, "...W-we have failed you...\n\n")
  LANGUAGE_TEXT(1, "... N-nous avons manqu\xe9\n\xe0 nos engagements...\n\n")
  LANGUAGE_TEXT(2, "... W-wir haben Sie\nentt\xe4uscht...\n\n")
  LANGUAGE_TEXT(3, "... Ti-ti abbiamo deluso...\n\n")
  LANGUAGE_TEXT(4, "... T-te hemos fallado...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 0)
  LANGUAGE_TEXT(0, "Run to Sol Chevalsky and\ntell him.\n\nThat as long as Seto Kaiba\nlives...\n\nAll his plans are doomed to\nfail! Wahahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Retourne vite avertir\nSol Chevalsky\n\nque tant que Kaiba\nSeto sera en vie,\n\nses plans mal\xe9fiques\n\xe9choueront !\n\nMouah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Lauf zur\xfcck zu Sol\nChevalsky und teil ihm mit:\n\nSolange Kaiba Seto lebt...\n\nSind all seine Pl\xe4ne zum\nScheitern verurteilt!\n\nWahahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Corri da Sol\nChevalsky e digli\n\nche finch\xe9 Kaiba\nSeto vivr\xe0...\n\nle sue trame saranno\nsconvolte! Uahahahah!\n\n")
  LANGUAGE_TEXT(4, "Corre hasta Sol\nChevalsky y dile\n\nque en tanto Kaiba\nSeto viva...\n\nsus maquinaciones\nse ver\xe1n frustradas.\n\n\xa1Wajajaja!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4354, map_31_state_01_08EB4354, 0x08EB4360, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  WALK_OBJECT_Y(1, 96)
  MOVE_OBJECT(2, 3, 8, 0)
  WALK_OBJECT_Y(2, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4360, map_31_state_01_08EB4360, 0x08EB436C, 0x08F04040)
  MOVE_OBJECT(5, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, you only won\nbecause you had my help.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu as gagn\xe9\ngr\xe2ce \xe0 mon aide.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du hast nur\nmit meiner Hilfe gewonnen.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, hai vinto\nsolo grazie al mio aiuto.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, s\xf3lo ganaste\ncon mi ayuda.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Listen, {PLAYER}.\n\nI walk my own road.\n\nI don't know if you'll win\nor fail on your journey...\n\nBut try not to disappoint\nme.\n\n")
  LANGUAGE_TEXT(1, "Ecoute, {PLAYER}.\n\nJe veux \xeatre seul sur\nle chemin de la victoire.\n\nJe ne sais pas si tu vas\nr\xe9ussir ou \xe9chouer.\n\nMais ne me d\xe9\xe7ois pas,\net bats-toi vaillamment.\n\n")
  LANGUAGE_TEXT(2, "H\xf6r zu, {PLAYER}.\n\nIch gehe meinen eigenen Weg\nzum Sieg.\n\nOb dich Erfolg oder\nNiederlage erwarten,\n\nsteht in den Sternen.\n\nAber entt\xe4usche mich nicht\nmit halbherzigen\n\nBem\xfchungen.\n\n")
  LANGUAGE_TEXT(3, "Stammi a sentire, {PLAYER}.\n\nSeguir\xf2 il mio percorso\nper la vittoria.\n\nNon so se ti aspetta la\nvittoria o la sconfitta.\n\nMa metticela tutta per\nnon deludermi.\n\n")
  LANGUAGE_TEXT(4, "Escucha, {PLAYER}.\n\nCaminar\xe9 mi propio\ncamino a la victoria.\n\nNo s\xe9 si es \xe9xito o\nfracaso lo que te espera.\n\nPero no me decepciones con\nun pobre esfuerzo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 1, 0)
  LANGUAGE_TEXT(0, "Now go and look for your\nmystical trinkets.\n\nWhile you play scavenger\nhunt, I'll save the world.\n\nWahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Maintenant pars et va\nchercher tes petits\n\nobjets surnaturels.\n\nLes faibles ont leur\nr\xf4le, eux aussi.\n\nOuah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Jetzt geh und such weiter\nnach deinem \xfcbernat\xfcrlichen\n\nTand. Schwache wie du\nhaben eigene Aufgaben.\n\nWahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Ora continua a cercare\ni tuoi ninnoli\n\nsoprannaturali. I deboli\ncome te hanno dei\n\nruoli a s\xe9 stanti.\nUahahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "Ahora ve y busca tus\nbaratijas sobrenaturales.\n\nLos d\xe9biles como t\xfa ten\xe9is\nvuestros roles propios.\n\n\xa1Wahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
