#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_03_state_04: map 3 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08E4AA30, map_03_state_04_08E4AA30, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_KAIBA_FAN)
  LOAD_SPRITE(2, SPRITE_RED_HAIR)
  LOAD_SPRITE(3, SPRITE_REX)
  TEXT(
      "I was hoping that Kaiba would save us...",
      "But surprisingly, Rex Raptor came to our rescue."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA3C, map_03_state_04_08E4AA3C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "The Neo Ghouls are robbing everyone's rare cards.",
      "Somebody has to stop them!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA48, map_03_state_04_08E4AA48, 0x08E4AA6C, 0x08E4AA54)
  CHECK_FLAG(EVENT_FLAG_SEARCHING_FOR_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA6C, map_03_state_04_08E4AA6C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Leave it to me!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA54, map_03_state_04_08E4AA54, 0x08E4AA60, 0x08E4AA6C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA60, map_03_state_04_08E4AA60, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "The Neo Ghouls are hiding out in the Town of Domino?",
      "I thought they were heading towards KaibaCorp."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA78, map_03_state_04_08E4AA78, 0x08E4AA84, 0x08F0404C)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You wanna duel me? You really want to become",
      "extinct?",
      "All right! Let's duel!"
  )
  DUEL(DUELIST_REX_054)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA84, map_03_state_04_08E4AA84, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_DOMINO_CITY_LIBERATED)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Looks like your deck's coming together well.",
      "Keep it up and let's kick the Neo Ghouls outta town!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
