#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_37_state_06: map 37 state 6 */

LOAD_SPRITE(1, SPRITE_MAKO)
LOAD_SPRITE(2, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(3, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(4, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(5, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(6, SPRITE_FISH_1)
LOAD_SPRITE(7, SPRITE_FISH_2)
LOAD_SPRITE(8, SPRITE_FISH_3)
LOAD_SPRITE(9, SPRITE_FISH_4)
PLAY_MUSIC(MUSIC_MONKEY_ROBOTS)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
DELAY(8)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT)
TEXT
(
    "Hey! Wait! Wait up!\n\n"
)
PLAY_MUSIC(MUSIC_326)
PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT)
TEXT
(
    "Ukki! Ukikki!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
SHOW_OBJECT(6, 128, 96, 0, 0, 0)
SHOW_OBJECT(7, 128, 96, 0, 0, 0)
SHOW_OBJECT(8, 128, 96, 0, 0, 0)
SHOW_OBJECT(9, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(2, 1, 42)
SHOW_OBJECT(2, 128, 96, 0, 0, 0)
MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(3, 1, 42)
SHOW_OBJECT(3, 128, 96, 0, 0, 0)
MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(4, 2, 40)
SHOW_OBJECT(4, 128, 96, 0, 0, 0)
MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(5, 2, 56)
SHOW_OBJECT(5, 128, 96, 0, 0, 0)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
DELAY(32)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT)
TEXT
(
    "Tsk, these annoying little\n"
    "monkeys...\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(32)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT)
TEXT
(
    "Oh well. I'll just catch\n"
    "more fish.\n\n"
    "The sea is plentiful with\n"
    "her bounty.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_1)
DELAY(16)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
TEXT
(
    "...The sea isn't screaming\n"
    "anymore...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_273)
REACTION(REACTION_LOVE_HEART, OBJECT_1)
DELAY(16)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT)
TEXT
(
    "Those guys... They did it.\n\n"
    "But I can't let them become\n"
    "better duelists than me!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(1, 96)
PLAY_MUSIC(MUSIC_93)
FADE_SCREEN(4)
PLAY_MUSIC(MUSIC_94)
WALK_OBJECT_Y(1, 64)
DELAY(16)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT)
TEXT
(
    "Gahahahaha!\n\n"
    "What a haul! What a catch!\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(6, 50, 48, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(8, 62, 48, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(7, 50, 56, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(9, 62, 56, 0, 0, 0)
DELAY(32)
MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
SHOW_OBJECT(2, 8, 48, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
SHOW_OBJECT(3, 8, 56, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(4, 62, 8, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(5, 70, 8, 0, 0, 0)
DELAY(32)
MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(2, 3, 34)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(3, 3, 34)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(4, 0, 32)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(5, 0, 48)
MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
DELAY(32)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_275)
REACTION(REACTION_ANGRY, OBJECT_1)
DELAY(8)
SLIDE_OBJECT(1, 2, 8)
DELAY(8)
PORTRAIT(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT)
TEXT
(
    "You guys! You're asking for\n"
    "it now!\n\n"
)
PLAY_MUSIC(MUSIC_324)
PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 6, PORTRAIT_RIGHT)
TEXT
(
    "Ukiiiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(2, 1, 42)
SHOW_OBJECT(2, 128, 96, 0, 0, 0)
MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(3, 1, 42)
SHOW_OBJECT(3, 128, 96, 0, 0, 0)
MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(4, 2, 40)
SHOW_OBJECT(4, 128, 96, 0, 0, 0)
MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(5, 2, 56)
SHOW_OBJECT(5, 128, 96, 0, 0, 0)
FADE_SCREEN(8)
WARP(LOCATION_GALAPAGOS_FOREST, 6, 0, 0)
