#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_42_state_01: map 42 state 1 */

LOAD_SPRITE(1, SPRITE_PANIK)
LOAD_SPRITE(2, SPRITE_JOEY)
LOAD_SPRITE(3, SPRITE_MIMIC_OF_DOOM)
PLAY_MUSIC(MUSIC_254)
DELAY(16)
WALK_OBJECT_X(SPRITE_PANIK, 98)
DELAY(8)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_JOEY, DIRECTION_RIGHT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_403)
TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Nihihi... I commend you on\n"
    "coming this far.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_MIMIC_OF_DOOM, 98)
DELAY(16)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Gehehehehe...\n\n"
    "But you're not going any\n"
    "farther. We won't let you!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_X(SPRITE_JOEY, 68)
DELAY(8)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Hah! In your dreams! We'll\n"
    "take you on!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(SPRITE_JOEY, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "{PLAYER}, pick who you want\n"
    "to duel!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
WALK_OBJECT_Y(SPRITE_JOEY, 74)
WALK_OBJECT_X(SPRITE_JOEY, 88)
WALK_OBJECT_Y(0, 64)
WALK_OBJECT_X(0, 88)
WALK_OBJECT_Y(13, 70)
WALK_OBJECT_X(13, 78)
DELAY(16)
DUEL(DUELIST_JOEY_160)
CHECK_FLAG(EVENT_FLAG_TAG_DUELED_WITH_JOEY_AGAINST_THE_DOMINO_STATIONS_GUARDS)
PLAY_MUSIC(MUSIC_403)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I... I lost again?!\n\n"
)
TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "H-how dare you... But how\n"
    "will you deal with this?\n\n"
)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Gehehehehe! We'll duel until\n"
    "I win!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_JOEY, 92)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Forget it, you lowlifes!\n\n"
    "You're not going to waste\n"
    "{PLAYER} and Yugi's time!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_JOEY)
DELAY(8)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Let me handle this!\n"
    "{PLAYER}, you keep going!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Heh, I know I'm in over my\n"
    "head!\n\n"
)
TEXT
(
    "I don't have any Egyptian\n"
    "God Cards...\n\n"
    "That's why you have to keep\n"
    "going, {PLAYER}!\n\n"
    "Make sure you take down\n"
    "Pegasus!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_JOEY, 92)
WALK_OBJECT_Y(SPRITE_JOEY, 69)
MOVE_OBJECT(SPRITE_JOEY, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_PANICK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Nihihihi...\n\n"
    "A scrub is challenging me?\n"
    "How amusing!\n\n"
)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Gehehehehe...\n\n"
    "You think you can beat the\n"
    "two of us by yourself?\n\n"
    "Don't make me laugh!\n"
    "Gehehehehe!\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "You two are all talk! Why\n"
    "don't ya shut your mouths\n\n"
    "and duel!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 8)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 8)
SLIDE_OBJECT(SPRITE_JOEY, 3, 8)
DELAY(16)
SLIDE_OBJECT(SPRITE_JOEY, 1, 2)
SLIDE_OBJECT(SPRITE_PANIK, 1, 2)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 1, 2)
DELAY(24)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 6)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 6)
SLIDE_OBJECT(SPRITE_JOEY, 3, 6)
DELAY(16)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 4)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 4)
SLIDE_OBJECT(SPRITE_JOEY, 3, 4)
DELAY(22)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Th-this guy... He's pretty\n"
    "good.\n\n"
    "But I can't lose! I refuse\n"
    "to lose!\n\n"
    "{PLAYER}, what are you\n"
    "waiting for? Go on!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
SLIDE_OBJECT(SPRITE_JOEY, 1, 4)
SLIDE_OBJECT(SPRITE_PANIK, 1, 4)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 1, 4)
DELAY(18)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 8)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 8)
SLIDE_OBJECT(SPRITE_JOEY, 3, 8)
DELAY(20)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 6)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 6)
SLIDE_OBJECT(SPRITE_JOEY, 3, 6)
DELAY(16)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(SPRITE_PANIK, 3, 6)
SLIDE_OBJECT(SPRITE_MIMIC_OF_DOOM, 3, 6)
SLIDE_OBJECT(SPRITE_JOEY, 3, 6)
SHOW_OBJECT(SPRITE_PANIK, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_MIMIC_OF_DOOM, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_JOEY, 128, 96, 0, 0, 0)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)
PLAY_MUSIC(MUSIC_254)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_13)
DELAY(32)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "...Let's go, {PLAYER}.\n\n"
)
SET_FLAG(EVENT_FLAG_DEFEATED_PANIK_AND_MIMIC_OF_DOOM2)
SET_FLAG(EVENT_FLAG_JOEY_LEFT_THE_PARTY)

EVENT_SCRIPT_REPLACEMENT(0x08ED9DE8, map_42_state_01_08ED9DE8, 0x08ED9DF4, 0x08F04040)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yeah, leave it to me,\n"
    "{PLAYER}.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E18, map_42_state_01_08ED9E18, 0x08ED9E30, 0x08ED9E3C)
PLAY_MUSIC(MUSIC_403)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Let's do this, Red-Eyes!\n\n"
)
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RED_EYES_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Inferno Fire Blast!\n\n"
)
  PLAY_MUSIC(MUSIC_389)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RED_EYES_ATTACK)
  DELAY(16)
  PLAY_MUSIC(MUSIC_284)
  SLIDE_OBJECT(3, 3, 8)
  DELAY(64)
  MOVE_OBJECT(3, DIRECTION_LEFT, 8, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Tsk... This garbage can't\n"
    "stop me...\n\n"
)
  PLAY_MUSIC(MUSIC_332)
  FADE_MUSIC(4)
  FADE_SCREEN(4)
  SET_FLAG(EVENT_FLAG_FLASHBACK)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_RIGHT_DOMINO_STATION_GUARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E30, map_42_state_01_08ED9E30, 0x08F04040, 0x08F04040)
WARP(LOCATION_DOMINO_STATION_TURNSTILES, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E3C, map_42_state_01_08ED9E3C, 0x08F04040, 0x08F04040)
WARP(LOCATION_DOMINO_STATION_TURNSTILES, 8, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9D94, map_42_state_01_08ED9D94, 0x08ED9DAC, 0x08F0404C)
WALK_OBJECT_Y(2, 64)
  WALK_OBJECT_X(2, 88)
  WALK_OBJECT_Y(0, 74)
  WALK_OBJECT_X(0, 88)
  WALK_OBJECT_Y(13, 77)
  WALK_OBJECT_X(13, 78)
  DELAY(16)
  DUEL(DUELIST_JOEY_161)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9DAC, map_42_state_01_08ED9DAC, 0x08ED9DB8, 0x08ED9E24)
SET_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_MIMIC_OF_DOOM2)
  CHECK_FLAG(EVENT_FLAG_TAG_DUELED_WITH_JOEY_AGAINST_THE_DOMINO_STATIONS_GUARDS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E24, map_42_state_01_08ED9E24, 0x08ED9E30, 0x08ED9E3C)
PLAY_MUSIC(MUSIC_403)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Let's do this, Red-Eyes!\n\n"
)
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RED_EYES_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_LEFT,
    "Inferno Fire Blast!\n\n"
)
  PLAY_MUSIC(MUSIC_389)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RED_EYES_ATTACK)
  DELAY(16)
  PLAY_MUSIC(MUSIC_284)
  SLIDE_OBJECT(1, 3, 8)
  DELAY(64)
  MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Tsk... This garbage can't\n"
    "stop me...\n\n"
)
  PLAY_MUSIC(MUSIC_332)
  FADE_MUSIC(4)
  FADE_SCREEN(4)
  SET_FLAG(EVENT_FLAG_FLASHBACK)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_THE_RIGHT_DOMINO_STATION_GUARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED9E60, map_42_state_01_08ED9E60, 0x08F04040, 0x08F04040)
SET_FLAG(EVENT_FLAG_UNLOCKED_DUNGEON)
  FALLTHROUGH()
END_EVENT_SCRIPT()
