#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_46_state_01: map 46 state 1 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EDAD34, map_46_state_01_08EDAD34, 0x08EDAD40, 0x08F0404C)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Gawry nida! Gawry nida!",
      "We win all duels! Gawry!"
  )
  DUEL(DUELIST_CHEVALIER_110)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDAD40, map_46_state_01_08EDAD40, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_DUNGEON)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "G-gawry nida... G-ga.. n-niii.... urrri...")
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
