#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_16_state_03: map 16 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E7DEDC, map_16_state_03_08E7DEDC, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_DUEL_EXPRESS_CONDUCTOR)
  LOAD_SPRITE(2, SPRITE_YELLOW_SCARF)
  LOAD_SPRITE(3, SPRITE_DAMIEN_DRACO)
  LOAD_SPRITE(4, SPRITE_DUEL_EXPRESS_CONDUCTOR)
  TEXT("Thank you for riding with us.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF78, map_16_state_03_08E7DF78, 0x08E7DF84, 0x08E7DFA8)
  CHECK_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF84, map_16_state_03_08E7DF84, 0x08E7DF90, 0x08E7DF9C)
  CHECK_FLAG(EVENT_FLAG_LEAVING_THE_DUEL_EXPRESS_LEADS_TO_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF90, map_16_state_03_08E7DF90, EVENT_NOP, EVENT_NOP)
  TEXT("Thank you for riding with us.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF9C, map_16_state_03_08E7DF9C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "If you try to duel me, the train will depart.",
      "Please be aware of that."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFA8, map_16_state_03_08E7DFA8, EVENT_NOP, EVENT_NOP)
  TEXT(
      "If you try to duel me, the train will arrive.",
      "Please be aware of that."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEE8, map_16_state_03_08E7DEE8, 0x08E7DEF4, 0x08E7DF18)
  CHECK_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEF4, map_16_state_03_08E7DEF4, 0x08E7DF00, 0x08E7DF0C)
  CHECK_FLAG(EVENT_FLAG_LEAVING_THE_DUEL_EXPRESS_LEADS_TO_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF00, map_16_state_03_08E7DF00, EVENT_NOP, EVENT_NOP)
  TEXT("Thank you for riding with us.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF0C, map_16_state_03_08E7DF0C, EVENT_NOP, EVENT_NOP)
  TEXT("Our departure time has arrived.")
  WALK_OBJECT_X(4, 108)
  MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
  TEXT("All aboard!")
  PLAY_MUSIC(MUSIC_234)
  SET_FLAG(EVENT_FLAG_SHAKE_SCREEN)
  TEXT("The next and only stop is the Egypt Exhibition!")
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 24, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  SET_MAP_MUSIC(234)
  SET_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF18, map_16_state_03_08E7DF18, 0x08E7DF24, EVENT_NOP)
  TEXT("We will be arriving very shortly.")
  WALK_OBJECT_X(4, 88)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  PLAY_MUSIC(SOUND_NONE)
  PLAY_MUSIC(MUSIC_235)
  CLEAR_FLAG(247)
  TEXT(
      "Egypt Exhibition! Egypt Exhibition!",
      "Please make sure to take all your belongings with you."
  )
  SET_MAP_MUSIC(232)
  CLEAR_FLAG(245)
  CLEAR_FLAG(244)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF24, map_16_state_03_08E7DF24, 0x08E7DF48, 0x08E7DF30)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_PANIK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF48, map_16_state_03_08E7DF48, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(4)
  WARP(LOCATION_EGYPT_EXHIBITION_TRAIN_STATION, 0, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF30, map_16_state_03_08E7DF30, 0x08E7DF54, 0x08E7DF3C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF54, map_16_state_03_08E7DF54, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(4)
  WARP(LOCATION_EGYPT_EXHIBITION_TRAIN_STATION, 1, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF3C, map_16_state_03_08E7DF3C, 0x08E7DF60, 0x08E7DF6C)
  CHECK_FLAG(EVENT_FLAG_SAW_MOKUBA_GET_KIDNAPPED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF60, map_16_state_03_08E7DF60, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(4)
  WARP(LOCATION_EGYPT_EXHIBITION_TRAIN_STATION, 2, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF6C, map_16_state_03_08E7DF6C, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(4)
  WARP(LOCATION_EGYPT_EXHIBITION_TRAIN_STATION, 5, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
