#include "event_macros.h"
#include "overworld.h"

/* map_59_state_02: map 59 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EFDAA0, map_59_state_02_08EFDAA0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(26)
  SHOW_OBJECT(1, 61, 30, 0, 0, 0)
  WALK_OBJECT_Y(1, 48)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Master Marik will decipher\nthe hieroglyphics.\n\nBut he will need time.\n\nIt is best if you continue\nyour quest.\n\nI will wait for you here and\ninform you of his progress.\n\nPlease visit us\noccasionally.\n\nI am sure that will please\nMaster Marik.\n\nPlease give my regards to\nMistress Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Marik va d\xe9chiffrer\nle texte hi\xe9ratique.\n\nMais pour cela, il a\nbesoin de temps.\n\nVous feriez mieux de\ncontinuer votre qu\xeate.\n\nJe vous attendrai ici\n\net je vous informerai\nde l'\xe9volution.\n\nVenez nous rendre\nvisite de temps \xe0 autre.\n\nJe suis s\xfbr que Ma\xeetre\nMarik sera content.\n\nVeuillez saluer pour\nmoi madame Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Meister Marik wird die\nPriesterschrift deuten.\n\nDazu braucht er allerdings\neinige Zeit.\n\nAm besten fahrt ihr\nmit eurer Suche fort.\n\nIch warte hier auf euch und\ngebe euch den Stand.\n\nBitte besucht uns\ngelegentlich.\n\nMeister Marik w\xfcrde sich\ngewiss freuen.\n\nBitte gr\xfc\xdft Fr\xe4ulein\nIshizu von mir.\n\n")
  LANGUAGE_TEXT(3, "Il maestro Marik decifrer\xe0\nil testo ieratico.\n\nMa per farlo, ha bisogno\ndi tempo. Sarebbe\n\nmeglio se continuaste\nla vostra missione.\n\nIo vi aspetter\xf2 qui e vi\ninformer\xf2 dei progressi.\n\nOgni tanto venite a\nfarci visita.\n\nSono certo che il maestro\nMarik ne sar\xe0 felice.\n\nPorgete i miei saluti alla\nsignora Ishizu.\n\n")
  LANGUAGE_TEXT(4, "El amo Marik descifrar\xe1 el\ntexto hier\xe1tico.\n\nPero para hacerlo,\nnecesitar\xe1 algo de tiempo.\n\nSer\xeda mejor si continuarais\ncon vuestra misi\xf3n.\n\nOs esperar\xe9 aqu\xed y os\ninformar\xe9 del progreso.\n\nPor favor, visitadnos\nde vez en cuando.\n\nEstoy seguro de que\ncomplacer\xe1 al amo Marik.\n\nPor favor, saludad\na la ama Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_EXITED_MARIKS_HOME)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDAAC, map_59_state_02_08EFDAAC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Since you arrived, Master\nMarik has been chanting\n\ndevoutly.\n\nHe is chanting to atone for\nhis past sins.\n\n")
  LANGUAGE_TEXT(1, "Depuis votre arriv\xe9e,\n\nMa\xeetre Marik prie\navec d\xe9votion.\n\nIl fait cela pour\nexpier ses fautes.\n\n")
  LANGUAGE_TEXT(2, "Seit ihr kamt, betet\nMeister Marik innig.\n\nEr betet, um f\xfcr fr\xfchere\nS\xfcnden zu b\xfc\xdfen.\n\n")
  LANGUAGE_TEXT(3, "Da quando siete venuti,\nil maestro Marik ha\n\npregato con devozione.\nLe sue sono preghiere di\n\nespiazione per i peccati\ncommessi in passato.\n\n")
  LANGUAGE_TEXT(4, "Desde que vinisteis,\nel amo Marik ha\n\nestado rezando\ndevotamente.\n\nReza para expiar\nsus pecados pasados.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDAB8, map_59_state_02_08EFDAB8, 0x08EFDAC4, 0x08F0404C)
  PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You dare enter my haven of\ntraps?\n\nFine! We shall duel!\n\n")
  LANGUAGE_TEXT(1, "Tu oses entrer dans mon\nantre cribl\xe9e de pi\xe8ges ?\n\nTr\xe8s bien !\nBattons-nous en duel !\n\n")
  LANGUAGE_TEXT(2, "Du wagst es, mein Fallen-\narsenal zu betreten?\n\nGut!\nWir werden k\xe4mpfen!\n\n")
  LANGUAGE_TEXT(3, "Tu osi entrare nel mio\ncovo di trappole?\n\nBene!\nAllora duelliamo!\n\n")
  LANGUAGE_TEXT(4, "\xbfOsas entrar en mi\npara\xedso de trampas?\n\n\xa1Vale!\n\xa1Lucharemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDAC4, map_59_state_02_08EFDAC4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(26)
  PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Gah! Your fighting spirit is\nmost impressive!\n\n")
  LANGUAGE_TEXT(1, "Grr ! Ta volont\xe9\nde combattre est tr\xe8s\n\nimpressionnante !\n\n")
  LANGUAGE_TEXT(2, "Gah! Dein Kampfgeist ist\n\xe4u\xdferst beeindruckend!\n\n")
  LANGUAGE_TEXT(3, "Ah! Il tuo spirito\ncombattente \xe8\n\ndavvero notevole!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vaya! Tu \xe1nimo luchador\nes impresionante.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
