#include "event_macros.h"
#include "overworld.h"

/* map_16_state_06: map 16 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E7DFB4, map_16_state_06_08E7DFB4, 0x08E7DFCC, 0x08E7DFE4)
  CHECK_FLAG(99)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFCC, map_16_state_06_08E7DFCC, 0x08E7DFD8, 0x08F0404C)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I won't let you reach Master\nKeith easily!\n\n")
  LANGUAGE_TEXT(1, "Je ne vais pas te\nlaisser arriver\n\naussi facilement\n\xe0 ma\xeetre Ken !\n\n")
  LANGUAGE_TEXT(2, "Ich lass dich nicht so\nleicht zu Meister Keith!\n\n")
  LANGUAGE_TEXT(3, "Non ti far\xf2 arrivare\ntanto facilmente\n\nal maestro Keith!\n\n")
  LANGUAGE_TEXT(4, "\xa1No te dejar\xe9 llegar al\namo Keith f\xe1cilmente!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(72)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFD8, map_16_state_06_08E7DFD8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(11)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Master Keith, please forgive\nme!\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Ken,\npardonnez-moi !\n\n")
  LANGUAGE_TEXT(2, "Meister Keith, bitte vergib\nmir!\n\n")
  LANGUAGE_TEXT(3, "Maestro Keith, perdonami!\n\n")
  LANGUAGE_TEXT(4, "\xa1Amo Keith, por\nfavor, perd\xf3name!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(282)
  OBJECT_EFFECT(2, 2)
  SET_FLAG(247)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 4)
  DELAY(8)
  WALK_OBJECT_X(2, 108)
  MOVE_OBJECT(2, 1, 0, 0)
  LANGUAGE_TEXT(0, "Th-the train! It's moving!\n\nThe Neo Ghouls must have\ntaken over the controls.\n\nBut as the conductor...\n\nIt's my job to perform my\nduties.\n\nOur next and only stop is\nthe Egypt Exhibition.\n\n")
  LANGUAGE_TEXT(1, "L-le train ! Il s'est\nmis en route !\n\nLes Neo Ghouls ont\nd\xfb prendre le contr\xf4le.\n\nMais je suis encore\nle contr\xf4leur...\n\nJe dois remplir mes\nfonctions, comme\n\nd'habitude.\n\nProchain et dernier arr\xeat :\nl'Exposition \xe9gyptienne.\n\n")
  LANGUAGE_TEXT(2, "D-der Zug!\nEr f\xe4hrt!\n\nDie Neo Ghouls haben ihn\nin ihre Gewalt gebracht.\n\nAber ich bin noch der\nSchaffner...\n\nIch muss wie stets meine\nPflicht erf\xfcllen.\n\nUnser n\xe4chster und einziger\nHalt ist die\n\n\xe4gypt. Ausstellung.\n\n")
  LANGUAGE_TEXT(3, "Ehi... Il treno!\nSi sta muovendo!\n\nI Neo Ghouls devono\naverne preso il controllo!\n\nMa se anche fosse, sono\nsempre io il capotreno...\n\nDevo fare il mio dovere\ncome sempre.\n\nLa nostra prossima e unica\nfermata \xe8 la Mostra Egizia.\n\n")
  LANGUAGE_TEXT(4, "\xa1E...el tren!\n\xa1Est\xe1 andando!\n\nLos Neo Ghouls deben de\nhaber tomado los mandos.\n\nPero aun as\xed, sigo\nsiendo el revisor...\n\nDebo cumplir con mis\ndeberes como siempre.\n\nNuestra pr\xf3xima y\n\xfanica parada es la\n\nExposici\xf3n Egipcia.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 24577)
  DELAY(16)
  SET_FLAG(99)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFE4, map_16_state_06_08E7DFE4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFC0, map_16_state_06_08E7DFC0, 0x08E7DFCC, 0x08E7DFE4)
  CHECK_FLAG(99)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFF0, map_16_state_06_08E7DFF0, 0x08E7DFFC, 0x08E7E008)
  CHECK_FLAG(247)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFFC, map_16_state_06_08E7DFFC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Wh-what is happening?\n\nThe Neo Ghouls have\ncommandeered the train!\n\n")
  LANGUAGE_TEXT(1, "Q-qu'est-ce qui se passe ?\n\nLes Neo Ghouls ont\npris le contr\xf4le du train.\n\n")
  LANGUAGE_TEXT(2, "W-was geschieht?\n\nDie Neo Ghouls haben\nden Zug in ihrer Gewalt!\n\n")
  LANGUAGE_TEXT(3, "Ma che succede?\n\nI Neo Ghouls hanno preso\nil controllo del treno!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ...qu\xe9 est\xe1 pasando?\n\n\xa1Los Neo Ghouls se han\napropiado del tren!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7E008, map_16_state_06_08E7E008, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls have\ncommandeered this train.\n\nWhat will become of us?\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls ont pris\nle cont\xf4le du train.\n\nQu'est-ce qui va\nnous arriver ?\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls haben\nden Zug in ihrer Gewalt!\n\nWas wird jetzt aus uns?\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls hanno preso il\ncontrollo di questo treno!\n\nChe ne sar\xe0 di noi, ora?\n\n")
  LANGUAGE_TEXT(4, "\xa1Los Neo Ghouls se han\napropiado del tren!\n\n\xbfQu\xe9 ser\xe1 de nosotros\nahora?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
