#include "event_macros.h"
#include "overworld.h"

/* map_01_state_01: map 1 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E42670, map_01_state_01_08E42670, 0x08E4267C, 0x08F04040)
  PLAY_MUSIC(4)
  WALK_OBJECT_X(0, 24)
  WALK_OBJECT_X(14, 28)
  WALK_OBJECT_X(13, 28)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, what are you still\ndoing here?\n\nWeren't the three of you\ntaking the Duel Express?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SURPRISED, 1)
  LANGUAGE_TEXT(0, "Whaaat? The Millennium\nPuzzle is gone?\n\nBut how? How did that\nhappen?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  WALK_OBJECT_X(4, 40)
  WALK_OBJECT_Y(4, 32)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Forgive me, but I overheard\nyour conversation.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24585)
  DELAY(8)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "So it seems the Millennium\nPuzzle has also\n\ndisappeared...\n\nWhat I have feared the most\nis coming to fruition...\n\nPlease.\n\nI need your help.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 24585)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I see you're puzzled, but\nthat is only to be\n\nexpected.\n\nPlease bear with me and\nlisten to my words\n\ncarefully.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4267C, map_01_state_01_08E4267C, 0x08E42688, 0x08F04040)
  LANGUAGE_TEXT(0, "I have come to ask you\nduelists for your help.\n\nYou must save the world from\nReshef the Dark Being.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24585)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I understand this is sudden\nand confusing.\n\nHowever, the world is in\ngrave peril.\n\nOnly strong duelists, such\nas yourselves, can save us\n\nall from ruin before it's\ntoo late!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(4, 24)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "All the Millennium Items\nhave disappeared...\n\nThis is most likely due to\nReshef's resurrection.\n\nAn unknown entity must have\ncommenced a fusion ritual\n\non the Egyptian God Cards...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Which re-released Reshef the\nDark Being into the world.\n\nThe ritual stole the mighty\npower of the Egyptian God\n\nCards.\n\nAnd the cards, now drained\nof its mystical energies,\n\ntransformed into stone.\n\nYou must send the Dark Being\nto its eternal rest before\n\nthe world is destroyed.\n\nBut in order to accomplish\nthis feat, the Egyptian God\n\nCards are absolutely\nessential.\n\nHowever, since the Egyptian\nGod Cards have been turned\n\nto stone, they no longer\nhave power.\n\nOnly the Millennium Items\ncan restore them to their\n\nformer glory.\n\nThe Items have been\nscattered all over the\n\nworld.\n\nThey must be regained to\nresurrect the Egyptian God\n\nCards.\n\nAnd with help from the\nEgyptian Gods, we may have\n\na chance of sealing away the\nDark Being.\n\nI am counting on you to\naccomplish this task.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(4, 0, 4, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Please, my powerful\nduelists...\n\nIf left unchecked, the Dark\nBeing's strength will keep\n\ngrowing.\n\nThe world will be shrouded\nin perpetual darkness.\n\nPlease help save the world!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "What should we do, {PLAYER}?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 0, 0, 0)
  MOVE_OBJECT(0, 0, 0, 0)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42688, map_01_state_01_08E42688, 0x08E42694, 0x08E426D0)
  LANGUAGE_TEXT(0, "{CARD_1}Defeat the Dark Being\nThat's impossible...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42694, map_01_state_01_08E42694, 0x08E426A0, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 1)
  LANGUAGE_TEXT(0, "I knew you'd say that.\n\nBesides, I have to find my\nMillennium Puzzle.\n\nI'll go with you, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Since you said I'm a\npowerful duelist, how can I\n\nrefuse!\n\nI'm coming along, too,\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426A0, map_01_state_01_08E426A0, 0x08E426AC, 0x08E426B8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "I thank you from the bottom\nof my heart.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "First, the Millennium Items\nmust be recovered.\n\nAs a descendent of a clan of\ngravekeepers...\n\nI can sense the faint pulses\nof the Millennium Items.\n\nYou must first make your way\nto the Egypt Exhibition.\n\nIf my feelings are correct,\nthe first of the Millennium\n\nItems should be there.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(4, 16)
  DELAY(32)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I know what I ask is a great\nimposition.\n\nBut I have no one to turn to\nexcept for you...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{CARD_1}Leave it to us!\n...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426AC, map_01_state_01_08E426AC, 0x08E426C4, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "Your words have given me\nhope for the first time in\n\na long time.\n\nI leave the fate of the\nworld in your hands...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426C4, map_01_state_01_08E426C4, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  MOVE_OBJECT(4, 1, 32, 0)
  PLAY_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426B8, map_01_state_01_08E426B8, 0x08E426C4, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I know this seems like an\nimpossible task...\n\nBut I have faith in your\nspirit that you will save\n\nthe world...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426D0, map_01_state_01_08E426D0, 0x08E42688, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "What? And pretend that this\nDark Being doesn't exist?\n\nThis doesn't sound like you,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426E8, map_01_state_01_08E426E8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I want to ride the Duel\nExpress...\n\nBut at my level, I'll get\ncreamed in seconds.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426F4, map_01_state_01_08E426F4, 0x08E42700, 0x08E42718)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RED_HAT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42700, map_01_state_01_08E42700, 0x08E4270C, 0x08F0404C)
  LANGUAGE_TEXT(0, "A street duel? Sure! Let's\nduel!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4270C, map_01_state_01_08E4270C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Sigh... I knew I needed to\nbe better.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_RED_HAT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42718, map_01_state_01_08E42718, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll challenge you when I\nhave more experience.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42724, map_01_state_01_08E42724, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Today's the day the Duel\nExpress starts chugging!\n\nThe best duelists have\nentered this tournament,\n\nand when I say the best, I\nmean the best!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42730, map_01_state_01_08E42730, 0x08E4273C, 0x08E42754)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_STYLISH_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4273C, map_01_state_01_08E4273C, 0x08E42748, 0x08F0404C)
  LANGUAGE_TEXT(0, "You must be a bad duelist if\nyou're out here.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42748, map_01_state_01_08E42748, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "I said all the top duelists\nare aboard the Duel\n\nExpress.\n\n...But I may be wrong.\nYou're pretty tough!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_STYLISH_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42754, map_01_state_01_08E42754, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "You know I'm no match for\nyou.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426DC, map_01_state_01_08E426DC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "You're going, {PLAYER}?\n\nThe Egypt Exhibition is the\nlast stop on the Duel\n\nExpress.\n\nI don't think it's left yet,\nbut it will soon! If you\n\nhurry, you can still catch\nit at the station.\n\nI'll be waiting at Yugi's\ngrandpa's place.\n\nCome see us when you get\nback, okay?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 48, 0)
  SET_FLAG(EVENT_FLAG_TEA_LEFT_FOR_THE_SHOP)
  FALLTHROUGH()
END_EVENT_SCRIPT()
