#include "event_macros.h"
#include "overworld.h"

/* map_07_state_03: map 7 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E5F8E8, map_07_state_03_08E5F8E8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Grandpa! We're in trouble!\n\nTristan turned into a monkey\nrobot and ran away!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Monkey robot?\n\nLike the ones made by\nKaibaCorp?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "I knew it was that dirty rat\nKaiba's fault!\n\nOnly a psycho like him would\nmake a monkey out of my\n\nfriend!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The robot looked harmless to\nme...\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_GRANDPA_MUTO_SAID_KAIBA_CORP_PRODUCES_MONKEY_ROBOTS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F8F4, map_07_state_03_08E5F8F4, 0x08E5F900, 0x08F04040)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Why would Kaiba turn Tristan\ninto a robot...?\n\nWell, we have more important\nthings to worry about.\n\nIf Tristan is a monkey,\nwhere would he go?\n\n...Of course! He'd look for\nbananas.\n\nLook for him where you can\nfind bananas.\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(EVENT_FLAG_TEA_SAID_TO_LOOK_FOR_BANANAS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F900, map_07_state_03_08E5F900, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Bananas? That would be...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Galapagos Islands?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "We'll search where monkeys\nhang out!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_TEA_SAID_TO_LOOK_FOR_BANANAS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5F90C, map_07_state_03_08E5F90C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't you have to find\nTristan first?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
