#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_03: map 23 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E95318, map_23_state_03_08E95318, 0x08E95324, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_BANDIT_KEITH)
  LOAD_SPRITE(2, SPRITE_ISHIZU)
  LOAD_SPRITE(3, SPRITE_ATEM)
  LOAD_SPRITE(4, SPRITE_MILLENNIUM_NECKLACE)
  LOAD_SPRITE(5, SPRITE_MILLENNIUM_ROD)
  LOAD_SPRITE(6, SPRITE_MILLENNIUM_PUZZLE)
  LOAD_SPRITE(7, SPRITE_MILLENNIUM_KEY)
  LOAD_SPRITE(8, SPRITE_MILLENNIUM_EYE)
  LOAD_SPRITE(9, SPRITE_MILLENNIUM_RING)
  LOAD_SPRITE(10, SPRITE_MILLENNIUM_SCALE)
  PLAY_MUSIC(MUSIC_407)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  WALK_OBJECT_X(0, 76)
  WALK_OBJECT_Y(0, 64)
  WALK_OBJECT_Y(13, 74)
  WALK_OBJECT_X(13, 82)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 74)
  WALK_OBJECT_X(14, 70)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(1, 26)
  DELAY(16)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Kukuku... What took you so long? You've kept us",
      "waiting.",
      "But that gave me time to talk to this woman."
  )
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Then you should understand what I'm asking.",
      "We need your help to defeat the Dark Being..."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Idiot! All I care about is defeating Pegasus!")
  TEXT(
      "I don't give half a brain about the Dark Being or",
      "anyone else!",
      "Saving the world is not my problem!",
      "Hurry up and resurrect my Winged Dragon of Ra.",
      "Kukukukukuku!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 40)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "C'mon, I'm done talking!",
      "Hand over the Millennium Items."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95324, map_23_state_03_08E95324, 0x08E9533C, 0x08E95330)
  TEXT("{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9533C, map_23_state_03_08E9533C, 0x08E95348, EVENT_NOP)
  WALK_OBJECT_Y(0, 58)
  WALK_OBJECT_X(0, 62)
  WALK_OBJECT_Y(0, 48)
  DELAY(32)
  PLAY_MUSIC(MUSIC_316)
  DELAY(32)
  WALK_OBJECT_Y(0, 58)
  WALK_OBJECT_X(0, 76)
  WALK_OBJECT_Y(0, 64)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "All the Millennium Items are gathered here.",
      "You found six Millennium Items.",
      "The Millennium Necklace..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(4, 62, 28, 0, 0, 0)
  PAGE_BREAK()
  TEXT
  (
      "The Millennium Key..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(7, 52, 46, 0, 0, 0)
  PAGE_BREAK()
  TEXT
  (
      "The Millennium Ring..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(9, 72, 46, 0, 0, 0)
  PAGE_BREAK()
  TEXT
  (
      "The Millennium Eye..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(8, 52, 34, 0, 0, 0)
  PAGE_BREAK()
  TEXT
  (
      "The Millennium Rod..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(5, 72, 34, 0, 0, 0)
  PAGE_BREAK()
  TEXT
  (
      "The Millennium Scale..."
  )
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(10, 62, 52, 0, 0, 0)
  PAGE_BREAK()
  TEXT(
      "Kukuku...",
      "I can't thank you enough.",
      "You've collected the Millennium Items, just for",
      "me!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95348, map_23_state_03_08E95348, 0x08E95354, 0x08E95360)
  TEXT("{CARD_1}What do you mean?\nNo way!{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95354, map_23_state_03_08E95354, 0x08E9536C, EVENT_NOP)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Heh, don't underestimate the Neo Ghouls' spies.",
      "I knew you were gathering the Millennium Items from",
      "the very start.",
      "I let you find them.",
      "So that you would resurrect the Egyptian God Cards for",
      "me."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9536C, map_23_state_03_08E9536C, 0x08E95384, EVENT_NOP)
  TEXT(
      "While you were looking for them, I found the last",
      "Millennium Item.",
      "Yup, the Millennium Puzzle belongs to me."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(6, 62, 41, 0, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  MOVE_OBJECT(13, DIRECTION_UP, 4, 0)
  DELAY(8)
  SHOW_OBJECT(4, 128, 96, 0, 0, 0)
  SHOW_OBJECT(7, 128, 96, 0, 0, 0)
  SHOW_OBJECT(9, 128, 96, 0, 0, 0)
  SHOW_OBJECT(8, 128, 96, 0, 0, 0)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  SHOW_OBJECT(10, 128, 96, 0, 0, 0)
  SHOW_OBJECT(6, 128, 96, 0, 0, 0)
  PLAY_MUSIC(MUSIC_297)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_MILLENNIUM_ITEMS_COLLECTED)
  PLAY_MUSIC(MUSIC_298)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPHERE_RA_REVIVED)
  WALK_OBJECT_Y(0, 58)
  WALK_OBJECT_X(0, 62)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_Y(14, 58)
  WALK_OBJECT_X(14, 56)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(13, 58)
  WALK_OBJECT_X(13, 68)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95384, map_23_state_03_08E95384, 0x08E95390, 0x08F0404C)
  PLAY_MUSIC(MUSIC_407)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Kukukuku... I finally have it.",
      "The Egyptian God Card... The Winged Dragon of Ra is",
      "mine!",
      "And my first victim...will be you!"
  )
  DUEL(DUELIST_BANDIT_KEITH_077)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95390, map_23_state_03_08E95390, 0x08E9539C, EVENT_NOP)
  PLAY_MUSIC(MUSIC_299)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SLIFER_ATTACKS_SPHERE_RA)
  ADD_CARD(238)
  TEXT("You can use Slifer the Sky Dragon again!")
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_DEFEATED, PORTRAIT_POSITION_AUTO,
      "Wh-what? How could this happen!",
      "The Egyptian God Card refused to let me use its",
      "power?!",
      "That's it! I'm done playing fair!",
      "I'm the one with the hostage! Hand over your",
      "Egyptian God Card!"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1 | OBJECT_2)
  DELAY(8)
  PLAY_MUSIC(MUSIC_297)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_MILLENNIUM_ITEMS_COLLECTED)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(10)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(10)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(10)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(10)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(10)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_SURPRISED, PORTRAIT_POSITION_AUTO, "Wh-what? What's happening?")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_300)
  SHOW_OBJECT(6, 62, 42, 0, 0, 0)
  DELAY(32)
  SLIDE_OBJECT(6, 3, 6)
  SLIDE_OBJECT(6, 0, 8)
  DELAY(32)
  FADE_SCREEN(2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E9539C, map_23_state_03_08E9539C, EVENT_NOP, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_MAKE_BACKGROUND_BLACK)
  WARP(LOCATION_EGYPT_EXHIBITION_MILLENNIUM_GUARDIAN, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95360, map_23_state_03_08E95360, 0x08E9536C, EVENT_NOP)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You're so clueless.",
      "Go ahead and deny it. You can't change the facts!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95330, map_23_state_03_08E95330, 0x08E95324, EVENT_NOP)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "If you don't... Well, you don't want to know what",
      "I'll do to this woman."
  )
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...")
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Hurry up. Hand over the Millennium Items.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
