#include "event_macros.h"
#include "overworld.h"

/* map_02_state_07: map 2 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E479C8, map_02_state_07_08E479C8, 0x08F04040, 0x08F04040)
  DELAY(16)
  WALK_OBJECT_Y(1, 40)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(2, 48)
  WALK_OBJECT_Y(3, 48)
  WALK_OBJECT_Y(4, 56)
  WALK_OBJECT_Y(5, 56)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(12, 1, 1)
  LANGUAGE_TEXT(0, "Gahaha!\n\nAll duelists swim in the\nsame ocean!\n\nHurry home!\n\n")
  LANGUAGE_TEXT(1, "Gahaha !\n\nPour les duellistes, il n'y\na qu'une seule mer !\n\nD\xe9p\xeachez-vous de revenir !\n\n")
  LANGUAGE_TEXT(2, "Gahaha!\n\nF\xfcr Duellanten gibt es\nnur ein Meer!\n\nEilt zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Gahaha!\n\nPer i duellanti, ce n'\xe8\nsolo uno di mare!\n\nTornate indietro, di corsa!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajaja!\n\nPara los duelistas,\n\xa1s\xf3lo hay un mar!\n\n\xa1Volved deprisa!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(323)
  PORTRAIT(38, 0, 1)
  LANGUAGE_TEXT(0, "Ukkikki!\n\n")
  LANGUAGE_TEXT(1, "Ukkikki !\n\n")
  LANGUAGE_TEXT(2, "Ukkikki!\n\n")
  LANGUAGE_TEXT(3, "Ukkikki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukkikki!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(326)
  PORTRAIT(38, 0, 0)
  LANGUAGE_TEXT(0, "Ukikkiki, kikiiki!!\n\n")
  LANGUAGE_TEXT(1, "Ukikkiki, kikiiki !!\n\n")
  LANGUAGE_TEXT(2, "Ukikkiki, kikiiki!!\n\n")
  LANGUAGE_TEXT(3, "Ukikkiki, kikiiki!!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukikkiki, kikiiki!!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  PLAY_MUSIC(323)
  PORTRAIT(38, 0, 1)
  LANGUAGE_TEXT(0, "Ukikiiikiki!\n\n")
  LANGUAGE_TEXT(1, "Ukikiiikiki !\n\n")
  LANGUAGE_TEXT(2, "Ukikiiikiki!\n\n")
  LANGUAGE_TEXT(3, "Ukikiiikiki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukikiiikiki!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(36, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(24, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(36, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(24, 1)
  WALK_OBJECT_X(6, 24)
  DELAY(32)
  MOVE_OBJECT(6, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(6, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(6, 1, 0, 0)
  DELAY(16)
  MOVE_OBJECT(6, 3, 0, 0)
  DELAY(16)
  PORTRAIT(13, 0, 1)
  LANGUAGE_TEXT(0, "I'm here to check on my card\nI gave away.\n\nSo? Where are they?\n\n")
  LANGUAGE_TEXT(1, "Je suis venu v\xe9rifier\nma carte,\n\ncelle que\nj'ai donn\xe9e.\n\nAlors ?\nO\xf9 sont-elles ?\n\n")
  LANGUAGE_TEXT(2, "Ich will hier nach meiner\nKarte schauen, nach der,\n\ndie ich verschenkt habe.\n\nUnd?\nWo sind sie?\n\n")
  LANGUAGE_TEXT(3, "Sono qui per vedere come\nva la mia carta, quella\n\nche ho dato via. Allora?\nDove sono loro?\n\n")
  LANGUAGE_TEXT(4, "Vengo a ver mi carta,\nla que di.\n\n\xbfBueno?\n\xbfD\xf3nde est\xe1n?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(2, 1, 0, 0)
  MOVE_OBJECT(3, 1, 0, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(323)
  PORTRAIT(38, 0, 1)
  LANGUAGE_TEXT(0, "Uki?\n\n")
  LANGUAGE_TEXT(1, "Uki ?\n\n")
  LANGUAGE_TEXT(2, "Uki?\n\n")
  LANGUAGE_TEXT(3, "Uki?\n\n")
  LANGUAGE_TEXT(4, "\xbfUki?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(12, 0, 1)
  LANGUAGE_TEXT(0, "Are you worried about those\nguys?\n\n")
  LANGUAGE_TEXT(1, "Tu es inquiet \xe0 cause\nde ces types ?\n\n")
  LANGUAGE_TEXT(2, "Machst du dir Sorgen\nwegen dieser Typen?\n\n")
  LANGUAGE_TEXT(3, "Ti preoccupi per\nquei ragazzi?\n\n")
  LANGUAGE_TEXT(4, "\xbfTe preocupan\nesos chicos?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(13, 0, 1)
  LANGUAGE_TEXT(0, "I'm only worried about my\ncard!\n\n")
  LANGUAGE_TEXT(1, "Si je suis inquiet,\nc'est pour ma carte !\n\n")
  LANGUAGE_TEXT(2, "Ich mache mir nur Sorgen\num meine Karte!\n\n")
  LANGUAGE_TEXT(3, "Mi preoccupo solo\ndella mia carta!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xf3lo me preocupa\nmi carta!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(4, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
