#include "event_macros.h"
#include "overworld.h"

/* map_03_state_02: map 3 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E4A91C, map_03_state_02_08E4A91C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(10)
  LANGUAGE_TEXT(0, "Help me!\n\n")
  LANGUAGE_TEXT(1, "Aidez-moi !\n\n")
  LANGUAGE_TEXT(2, "Hilf mir!\n\n")
  LANGUAGE_TEXT(3, "Aiuto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ayudadme!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  WALK_OBJECT_X(1, 40)
  WALK_OBJECT_X(3, 28)
  DELAY(16)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "Silence! Hand over your rare\ncards right now!\n\n")
  LANGUAGE_TEXT(1, "Tais-toi. Donne-moi tes\ncartes rares, et vite !\n\n")
  LANGUAGE_TEXT(2, "Sei still. Gib mir sofort\ndeine seltenen Karten.\n\n")
  LANGUAGE_TEXT(3, "Zitto. Dammi subito\nle tue carte rare.\n\n")
  LANGUAGE_TEXT(4, "Calla. Entrega tus cartas\nraras ahora mismo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 8, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "I never said I was putting\nup my rare cards as ante in\n\nthis duel!\n\n")
  LANGUAGE_TEXT(1, "Je n'ai jamais dit que\nje me battrais en duel\n\navec des cartes rares\ncomme ante !\n\n")
  LANGUAGE_TEXT(2, "Ich habe nie behauptet,\ndass ich mit meinen\n\nseltenen Karten als Ante\nspielen w\xfcrde!\n\n")
  LANGUAGE_TEXT(3, "Non ho mai detto che\navrei duellato con le\n\nmie carte rare come\nposta in gioco!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nunca dije que luchar\xeda\ncon mis cartas raras\n\ncomo las ante!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 1, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "Well, you thought wrong!\nGive me your rare cards!\n\n")
  LANGUAGE_TEXT(1, "Arr\xeate de r\xe2ler ! Donne-\nmoi tes cartes rares !\n\n")
  LANGUAGE_TEXT(2, "Halt den Mund und gib mir\ndeine seltenen Karten!\n\n")
  LANGUAGE_TEXT(3, "Chiudi la bocca! Dammi\nle tue carte rare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Cierra el pico!\n\xa1Dame las cartas raras!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  LANGUAGE_TEXT(0, "N-Neo Ghouls... You horrible\nstinking thugs...\n\n")
  LANGUAGE_TEXT(1, "Les N-Neo Ghouls... Quelle\nbande de racailles...\n\n")
  LANGUAGE_TEXT(2, "N-Neo Ghouls...\nSchreckliche Schurken...\n\n")
  LANGUAGE_TEXT(3, "N-Neo Ghouls...\nMascalzoni schifosi...\n\n")
  LANGUAGE_TEXT(4, "N...Neo Ghouls...\nQu\xe9 horrorosos matones...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "Ha ha ha! Flattery will get\nyou nowhere! All the\n\nworld's rare cards belong to\nthe Neo Ghouls!\n\n")
  LANGUAGE_TEXT(1, "Toutes les cartes\nrares au monde\n\nappartiendront\naux Neo Ghouls !\n\n")
  LANGUAGE_TEXT(2, "Die seltenen Karten der Welt\ngeh\xf6ren den Neo Ghouls!\n\n")
  LANGUAGE_TEXT(3, "Le carte rare del mondo\nsaranno dei Neo Ghouls!\n\n")
  LANGUAGE_TEXT(4, "\xa1Las cartas raras del mundo\nser\xe1n de los Neo Ghouls!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(78)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A928, map_03_state_02_08E4A928, 0x08E4A934, 0x08E4A94C)
  CHECK_FLAG(80)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A934, map_03_state_02_08E4A934, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "H-help me, please!\n\n")
  LANGUAGE_TEXT(1, "S'il vous pla\xeet,\naidez-moi.\n\n")
  LANGUAGE_TEXT(2, "H-helft mir bitte.\n\n")
  LANGUAGE_TEXT(3, "Aiutatemi, vi prego.\n\n")
  LANGUAGE_TEXT(4, "\xa1\xa1Ayudadme, por favor!!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A94C, map_03_state_02_08E4A94C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls are awful\npeople. Just awful.\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls sont\ndes gens horribles.\n\nVraiment odieux.\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls sind schreck-\nlich. Einfach schrecklich.\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls sono tipi\norribili. S\xec, orribili.\n\n")
  LANGUAGE_TEXT(4, "Los Neo Ghouls son\nespantosos.\n\nSimplemente espantosos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A940, map_03_state_02_08E4A940, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Please, no!\nNo more duels!\n\n")
  LANGUAGE_TEXT(1, "S'il vous pla\xeet, non !\nPlus de duel !\n\n")
  LANGUAGE_TEXT(2, "Oh nein, bitte! Nicht noch\nmehr Duelle!\n\n")
  LANGUAGE_TEXT(3, "Vi prego, no!\nBasta con i duelli!\n\n")
  LANGUAGE_TEXT(4, "\xa1Por favor, no!\n\xa1No m\xe1s duelos!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A958, map_03_state_02_08E4A958, 0x08E4A964, 0x08E4A97C)
  CHECK_FLAG(81)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A964, map_03_state_02_08E4A964, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "M-my rare cards are gone...\n\n")
  LANGUAGE_TEXT(1, "M-mes cartes rares\nont disparu...\n\n")
  LANGUAGE_TEXT(2, "M-meine seltenen Karten...\n\n")
  LANGUAGE_TEXT(3, "Addio alle mie\ncarte rare...\n\n")
  LANGUAGE_TEXT(4, "M...mis cartas raras\nhan desaparecido...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A97C, map_03_state_02_08E4A97C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls have\ncompletely overrun the Town\n\nof Domino!\n\n")
  LANGUAGE_TEXT(1, "Les Neo Ghouls ont le\ncontr\xf4le total de Domino !\n\n")
  LANGUAGE_TEXT(2, "Die Neo Ghouls haben\nDomino v\xf6llig \xfcberrannt!\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls hanno\ninvaso tutta Domino!\n\n")
  LANGUAGE_TEXT(4, "\xa1Los Neo Ghouls han plagado Domino completamente!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A970, map_03_state_02_08E4A970, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Duel... Please, I'm too\nscared....\n\n")
  LANGUAGE_TEXT(1, "Un duel...\nJ'ai trop peur....\n\n")
  LANGUAGE_TEXT(2, "Duell... Bitte, ich habe\nzu viel Angst...\n\n")
  LANGUAGE_TEXT(3, "Duellare... Scusate,\nma ho troppa paura...\n\n")
  LANGUAGE_TEXT(4, "Duelo... Por favor, estoy\ndemasiado asustado....\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A988, map_03_state_02_08E4A988, 0x08E4A9A0, 0x08E4AA18)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "I'll take your rare cards,\ntoo!\n\n")
  LANGUAGE_TEXT(1, "Je vais aussi prendre\ntes cartes rares !\n\n")
  LANGUAGE_TEXT(2, "Gib mir auch deine\nseltenen Karten!\n\n")
  LANGUAGE_TEXT(3, "Anche le tue carte\nrare saranno mie!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo tambi\xe9n tendr\xe9\ntus cartas raras!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(52)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9A0, map_03_state_02_08E4A9A0, 0x08E4A9AC, 0x08E4A9B8)
  CHECK_FLAG(95)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9AC, map_03_state_02_08E4A9AC, 0x08E4A9C4, 0x08F04040)
  PLAY_MUSIC(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9C4, map_03_state_02_08E4A9C4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "Y-you punk! Don't think\nyou'll win again!\n\n")
  LANGUAGE_TEXT(1, "C-comment oses-tu ?!\n\nN'imagine pas que\ncela va se reproduire.\n\n")
  LANGUAGE_TEXT(2, "Wie kannst du es wagen!\nGlaub ja nicht, dass du\n\ndas wiederholen kannst!\n\n")
  LANGUAGE_TEXT(3, "Come osi! Non credere\nche succeder\xe0 di nuovo!\n\n")
  LANGUAGE_TEXT(4, "\xa1C...c\xf3mo osas! \xa1No creas\nque volver\xe1 a pasar!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 40, 0)
  SET_FLAG(80)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9B8, map_03_state_02_08E4A9B8, 0x08E4A9C4, 0x08F04040)
  PLAY_MUSIC(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA18, map_03_state_02_08E4AA18, 0x08E4AA24, 0x08F0404C)
  CHECK_FLAG(95)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA24, map_03_state_02_08E4AA24, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(79)
  CLEAR_FLAG(78)
  CLEAR_FLAG(182)
  CLEAR_FLAG(102)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A994, map_03_state_02_08E4A994, 0x08E4A9A0, 0x08E4AA18)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "This is your first, and\nlast, mistake!\n\n")
  LANGUAGE_TEXT(1, "Oui !\nUne victime consentante !\n\n")
  LANGUAGE_TEXT(2, "Ja!\nEin bereitwilliges Opfer!\n\n")
  LANGUAGE_TEXT(3, "S\xec!\nUna vittima volontaria!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed!\n\xa1Una v\xedctima deseosa!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(52)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9D0, map_03_state_02_08E4A9D0, 0x08E4A9E8, 0x08E4AA18)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "You have some rare cards\nthat I want.\n\n")
  LANGUAGE_TEXT(1, "Toi aussi, tu as l'air\nd'avoir des cartes rares.\n\n")
  LANGUAGE_TEXT(2, "Du scheinst ja auch\nseltene Karten zu haben.\n\n")
  LANGUAGE_TEXT(3, "A quanto pare, anche\ntu hai delle carte rare.\n\n")
  LANGUAGE_TEXT(4, "T\xfa pareces tener varias\ncartas raras tambi\xe9n.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(53)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9E8, map_03_state_02_08E4A9E8, 0x08E4A9F4, 0x08E4AA00)
  CHECK_FLAG(95)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9F4, map_03_state_02_08E4A9F4, 0x08E4AA0C, 0x08F04040)
  PLAY_MUSIC(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA0C, map_03_state_02_08E4AA0C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "I may have lost, but there\nare many other Neo Ghouls\n\nwaiting for you!\n\n")
  LANGUAGE_TEXT(1, "J'ai perdu, mais\nce n'est pas la fin\n\ndes Neo Ghouls !\n\n")
  LANGUAGE_TEXT(2, "Ich habe verloren, doch\ndas ist nicht das Ende\n\nder Neo Ghouls!\n\n")
  LANGUAGE_TEXT(3, "Ho perso, ma non finir\xe0\nqui per i Neo Ghouls!\n\n")
  LANGUAGE_TEXT(4, "\xa1Perd\xed, pero no es el fin\nde los Neo Ghouls!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 32)
  WALK_OBJECT_X(4, 72)
  MOVE_OBJECT(4, 2, 48, 0)
  SET_FLAG(81)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA00, map_03_state_02_08E4AA00, 0x08E4AA0C, 0x08F04040)
  PLAY_MUSIC(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4A9DC, map_03_state_02_08E4A9DC, 0x08E4A9E8, 0x08E4AA18)
  PORTRAIT(PORTRAIT_NEO_GHOUL, 0, 8)
  LANGUAGE_TEXT(0, "You fool! You dare challenge\nme?\n\n")
  LANGUAGE_TEXT(1, "Quel imb\xe9cile ! Tu\nme lances un d\xe9fi ?\n\n")
  LANGUAGE_TEXT(2, "Was f\xfcr ein Narr!\nDu forderst mich heraus?\n\n")
  LANGUAGE_TEXT(3, "Che mossa da idioti!\nTu mi stai sfidando?\n\n")
  LANGUAGE_TEXT(4, "\xa1Qu\xe9 loco!\n\xbfMe est\xe1s retando?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(53)
  FALLTHROUGH()
END_EVENT_SCRIPT()
