#include "event_macros.h"
#include "overworld.h"

/* map_03_state_05: map 3 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E4AA90, map_03_state_05_08E4AA90, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Kaiba Corporation is up\nahead.\n\nIs something going on there?\n\n")
  LANGUAGE_TEXT(1, "Kaiba Corporation,\nc'est par-l\xe0.\n\nIl y a quelque chose\nqui se passe l\xe0-bas ?\n\n")
  LANGUAGE_TEXT(2, "Die Kaiba Corporation\nbefindet sich hier hinter.\n\nStimmt dort etwas nicht?\n\n")
  LANGUAGE_TEXT(3, "La Kaiba Corporation\n\xe8 pi\xf9 su.\n\nSuccede qualcosa\nda quelle parti?\n\n")
  LANGUAGE_TEXT(4, "Kaiba Corporation\nest\xe1 por ah\xed.\n\n\xbfPasa algo ah\xed?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AA9C, map_03_state_05_08E4AA9C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm too worried about Mr.\nKaiba to duel.\n\n")
  LANGUAGE_TEXT(1, "Je suis trop inquiet \xe0\npropos de M. Kaiba Seto\n\npour me battre en duel.\n\n")
  LANGUAGE_TEXT(2, "Ich mache mir zu gro\xdfe\nSorgen um Kaiba Seto,\n\nals dass ich mich\nduellieren k\xf6nnte.\n\n")
  LANGUAGE_TEXT(3, "Sono troppo preoccupato\nper il signor Kaiba Seto\n\nper duellare.\n\n")
  LANGUAGE_TEXT(4, "Me preocupa que\nse bata en duelo\n\nel Sr. Kaiba Seto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AAA8, map_03_state_05_08E4AAA8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Town of Domino has\nbecome peaceful since the\n\nNeo Ghouls left.\n\n")
  LANGUAGE_TEXT(1, "Depuis que les Neo Ghouls\nsont partis, Domino est\n\ndevenue une ville bien\ntranquille.\n\n")
  LANGUAGE_TEXT(2, "Seit die Neo Ghouls fort\nsind, ist es in Domino\n\nrichtig friedlich.\n\n")
  LANGUAGE_TEXT(3, "A Domino \xe8 tornata la\npace dopo che i Neo\n\nGhouls se ne sono andati.\n\n")
  LANGUAGE_TEXT(4, "Domino est\xe1 en paz desde que\nse fueron los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AAB4, map_03_state_05_08E4AAB4, 0x08E4AAC0, 0x08E4AAD8)
  CHECK_FLAG(124)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AAC0, map_03_state_05_08E4AAC0, 0x08E4AACC, 0x08F0404C)
  LANGUAGE_TEXT(0, "I'm not going to lose.\n\n")
  LANGUAGE_TEXT(1, "Je ne vais pas perdre.\n\n")
  LANGUAGE_TEXT(2, "Ich werde nicht verlieren.\n\n")
  LANGUAGE_TEXT(3, "Io non perder\xf2 di certo.\n\n")
  LANGUAGE_TEXT(4, "No voy a perder.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(89)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AACC, map_03_state_05_08E4AACC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "It was fun, even though I\nlost.\n\n")
  LANGUAGE_TEXT(1, "J'ai perdu mais je me\nsuis bien amus\xe9.\n\n")
  LANGUAGE_TEXT(2, "Es hat Spa\xdf gemacht, auch\nwenn ich verloren habe.\n\n")
  LANGUAGE_TEXT(3, "Mi sono divertito, anche\nse ho perso.\n\n")
  LANGUAGE_TEXT(4, "Ha sido divertido,\nincluso perdiendo.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(124)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AAD8, map_03_state_05_08E4AAD8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Another time, all right?\n\n")
  LANGUAGE_TEXT(1, "Une autre fois, d'accord ?\n\n")
  LANGUAGE_TEXT(2, "Ein andermal, okay?\n\n")
  LANGUAGE_TEXT(3, "Un'altra volta, va bene?\n\n")
  LANGUAGE_TEXT(4, "En otra ocasi\xf3n,\n\xbfde acuerdo?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4AAE4, map_03_state_05_08E4AAE4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_REX, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Things are now as cool as\nthe Ice Age.\n\nI'm outta here.\n\nBack to boning up my deck\namong the fossils.\n\n")
  LANGUAGE_TEXT(1, "On dirait que les choses\nse sont calm\xe9es.\n\nBon, je m'en vais.\n\nJe vais am\xe9liorer mon Deck\nau milieu des fossiles !\n\n")
  LANGUAGE_TEXT(2, "Die Lage scheint sich\nberuhigt zu haben.\n\nIch fahre jetzt aber.\n\nIch muss mein Deck bei\nden Fossilien st\xe4rken.\n\n")
  LANGUAGE_TEXT(3, "A quanto pare, le cose\nsi sono sistemate.\n\nBe', io me ne vado.\n\nMe ne torno a rafforzare\nil mio deck tra i fossili.\n\n")
  LANGUAGE_TEXT(4, "Parece que las cosas se\nhan calmado.\n\nBueno, me voy.\n\nVuelvo a reforzar mi\ndeck entre f\xf3siles.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 0)
  SET_OBJECT_POSITION(3, 128, 96, 0)
  SET_FLAG(125)
  SET_MAP_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()
