#include "event_macros.h"
#include "overworld.h"

/* map_22_state_03: map 22 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CB34, map_22_state_03_08E8CB34, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(405)
  DELAY(16)
  WALK_OBJECT_Y(0, 26)
  WALK_OBJECT_X(0, 80)
  WALK_OBJECT_Y(13, 20)
  WALK_OBJECT_X(13, 90)
  WALK_OBJECT_Y(14, 32)
  WALK_OBJECT_X(14, 90)
  DELAY(16)
  MOVE_OBJECT(2, 3, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Humph. So the merry band of\nlosers finally have a clue\n\nabout what's really going\non.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 3, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Ishizu visited my big\nbrother.\n\nShe wanted him to get the\nEgyptian God Cards back.\n\n")
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Mokuba, keep quiet.\n\nThe title as champion And\nthe strongest cards...\n\nOnly the most powerful\nduelist is worthy of these\n\ntwo things.\n\nAnd that duelist is me!\n\nI will recover the Egyptian\nGod Cards quick and easy.\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I bet you guys are happy\nthat my big bro's gonna\n\nhelp you out, huh?\n\n")
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO)
  TEXT("Mokuba!\n\n")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, PORTRAIT_POSITION_AUTO)
  TEXT("W-what is it, Seto?\n\n")
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I have no intention of\nteaming up with these\n\nclowns!\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO)
  TEXT("Big brother...\n\n")
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO)
  TEXT("Listen up, you fools!\n\nA real duelist doesn't need\nhelp from a bunch of\n\ncheerleaders!\n\nAll you should count on is\nyour own strength!\n\nYou guys are so weak that\nnone of you can survive\n\nalone...\n\nAnd you expect me to team up\nwith you losers? Don't make\n\nme laugh!\n\nLet's go, Mokuba!\n\n")
  PORTRAIT(PORTRAIT_SETO, 1, PORTRAIT_POSITION_AUTO)
  TEXT("Wahahahahaha!\n\n")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 1, 72, 0)
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(24)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(24)
  MOVE_OBJECT(3, 1, 68, 0)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 1)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_SAW_KAIBA_AT_EGYPT_EXHIBITION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB1C, map_22_state_03_08E8CB1C, 0x08F04040, 0x08F04040)
  TEXT("This is the Egypt\nExhibition.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB28, map_22_state_03_08E8CB28, 0x08F04040, 0x08F04040)
  TEXT("No way, I'm not a duelist.\n\nI came here for the\nexhibition.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
