#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_12: map 6 state 12 */

LOAD_SPRITE(1, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(2, SPRITE_DUKE)
LOAD_SPRITE(3, SPRITE_SERENITY)
LOAD_SPRITE(4, SPRITE_TRISTAN)
LOAD_SPRITE(5, SPRITE_GRANDPA_MUTO)
LOAD_SPRITE(6, SPRITE_LUCKY)
PLAY_MUSIC(MUSIC_MONKEY_ROBOTS)
DELAY(32)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_DUKE | SPRITE_SERENITY)
MOVE_OBJECT(SPRITE_DUKE, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_SERENITY, DIRECTION_RIGHT, 0, 0)
DELAY(16)
WALK_OBJECT_X(SPRITE_SERENITY, 44)
TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, PORTRAIT_RIGHT,
    "Tristan!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_MONKEY_ROBOT, 52)
DELAY(16)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 5, PORTRAIT_RIGHT,
    "Ukiiii!\n\n"
)
TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "I'm so glad you found him!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(14, 40)
WALK_OBJECT_X(14, 60)
DELAY(16)
PLAY_MUSIC(MUSIC_275)
REACTION(REACTION_ANGRY, OBJECT_14)
DELAY(8)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Hey, Tristan! That's enough!\n"
    "Get away from Serenity.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MONKEY_ROBOT)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Why, you...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_MONKEY_ROBOT, 36)
MOVE_OBJECT(SPRITE_MONKEY_ROBOT, DIRECTION_RIGHT, 0, 0)
DELAY(8)
WALK_OBJECT_X(14, 52)
DELAY(8)
TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_ANGRY, PORTRAIT_RIGHT,
    "Stop Joey!\n\n"
    "Hasn't Tristan suffer enough\n"
    "already?\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO,
    "Yeah, but...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_MONKEY_ROBOT, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_MONKEY_ROBOT, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_326)
TALK(PORTRAIT_ROBOT_MOkNEY, 2, PORTRAIT_RIGHT,
    "Ukiii ukiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_275)
REACTION(REACTION_ANGRY, OBJECT_14)
DELAY(8)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "You're starting to tick me\n"
    "off, Tristan...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(0, 48)
WALK_OBJECT_X(0, 60)
WALK_OBJECT_Y(13, 40)
WALK_OBJECT_X(13, 60)
DELAY(64)
SET_OBJECT_POSITION(SPRITE_GRANDPA_MUTO, 74, 40, 0)
WALK_OBJECT_Y(SPRITE_GRANDPA_MUTO, 44)
MOVE_OBJECT(SPRITE_GRANDPA_MUTO, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Oh? That monkey robot...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_RIGHT,
    "Grandpa, this monkey robot\n"
    "is actually Tristan.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_274)
REACTION(REACTION_SWEATDROP, SPRITE_GRANDPA_MUTO)
DELAY(16)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Yugi, what on earth are you\n"
    "saying?\n\n"
)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_RIGHT,
    "I know it's hard to believe.\n\n"
    "But it's true.\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "I'll prove it to ya.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "Tristan, if you can under-\n"
    "stand me, howl three times.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_MONKEY_ROBOT, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_MONKEY_ROBOT, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_327)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Uki! Uki!\n"
    "Ukiki!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "And that's all she wrote.\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Hohohohoho!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_DUKE | SPRITE_SERENITY | OBJECT_13 | OBJECT_14)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_RIGHT,
    "Wh-what's the matter,\n"
    "Grandpa?\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You kids are too much.\n\n"
    "That monkey robot was one of\n"
    "the products I was selling\n\n"
    "in my store.\n\n"
    "But since no one bought it,\n"
    "I was playing with it.\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "B-but... It understood\n"
    "everything I said.\n\n"
)
TALK(PORTRAIT_SOLOMON, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "That's because I programmed\n"
    "it so it would.\n\n"
    "I was wondering where it\n"
    "went, but I'm glad to have\n\n"
    "it back.\n\n"
    "Come on, monkey robot. Let's\n"
    "go back to the shop!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_GRANDPA_MUTO, 40)
SET_OBJECT_POSITION(SPRITE_GRANDPA_MUTO, 128, 128, 0)
DELAY(32)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(SPRITE_SERENITY, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(SPRITE_DUKE, DIRECTION_UP, 0, 0)
DELAY(64)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0 | SPRITE_DUKE | SPRITE_SERENITY | OBJECT_13 | OBJECT_14)
PLAY_MUSIC(MUSIC_274)
REACTION(REACTION_SWEATDROP, SPRITE_MONKEY_ROBOT)
DELAY(32)
WALK_OBJECT_X(SPRITE_TRISTAN, 80)
DELAY(16)
PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Hi, guys! What are you all\n"
    "doing here?\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_DUKE | SPRITE_SERENITY | OBJECT_13 | OBJECT_14)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_DUKE, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_SERENITY, DIRECTION_RIGHT, 0, 0)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, PORTRAIT_LEFT,
    "Huh, what? Why are you all\n"
    "looking at me weird?\n\n"
)
WALK_OBJECT_X(14, 72)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "You... Where in the world\n"
    "were you?\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, PORTRAIT_POSITION_AUTO,
    "I... I had the munchies, so\n"
    "I went out for some food.\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "You idiot! After we went ape\n"
    "over you!\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, PORTRAIT_POSITION_AUTO,
    "Wh-what are you talking\n"
    "about?\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Then this monkey robot is\n"
    "really just a robot?\n\n"
)
HIDE_PORTRAIT()
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_MONKEY_ROBOT, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukikikikikiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_MONKEY_ROBOT, 74)
WALK_OBJECT_Y(SPRITE_MONKEY_ROBOT, 40)
SET_OBJECT_POSITION(SPRITE_MONKEY_ROBOT, 128, 128, 0)
DELAY(64)
TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "That's what you get for\n"
    "monkeying around.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_274)
REACTION(REACTION_SWEATDROP, OBJECT_0 | SPRITE_DUKE | SPRITE_TRISTAN | OBJECT_13 | OBJECT_14)
DELAY(16)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO,
    "Uh... Yeah... Nice one,\n"
    "Serenity...\n\n"
)

EVENT_SCRIPT_REPLACEMENT(0x08E5CE10, map_06_state_12_08E5CE10, 0x08F04040, 0x08F04040)
SET_FLAG(EVENT_FLAG_JOEY_COMPLAINED_ABOUT_TRISTAN)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDC8, map_06_state_12_08E5CDC8, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I'm glad you guys care so\n"
    "much...\n\n"
)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, PORTRAIT_POSITION_AUTO,
    "But come on! You've got to\n"
    "be kidding!\n\n"
    "I don't look anything like\n"
    "that monkey robot!\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDBC, map_06_state_12_08E5CDBC, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I totally thought that the\n"
    "monkey robot was Tristan.\n\n"
    "You have to admit, there is\n"
    "a strong resemblance.\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDB0, map_06_state_12_08E5CDB0, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I wasn't trying to be\n"
    "funny...\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
