#include "event_macros.h"
#include "overworld.h"

/* map_55_state_03: map 55 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EF057C, map_55_state_03_08EF057C, 0x08F04040, 0x08F04040)
  PORTRAIT(5, 0, 8)
  LANGUAGE_TEXT(0, "Fufufu... You've finally\narrived.\n\nDuelists of pure hearts and\nspirits, I was hoping you\n\nwould come.\n\nWhy? Because your defeats\nwill make the best\n\nofferings for the reborn\nReshef!\n\n")
  LANGUAGE_TEXT(1, "Fufufu...\nVous \xeates enfin arriv\xe9.\n\nOh, vous les duellistes, si\npurs de c\u0153ur et d'esprit.\n\nJ'attendais tellement\nvotre venue.\n\nVotre d\xe9faite sera le\nmeilleur cadeau que\n\nvous pourrez offrir\n\xe0 Reshef ressuscit\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Fufufu...\nEndlich seid ihr da.\n\nOh, Duellanten, reinen\nHerzens und reiner Seele.\n\nIch hatte euch sehnlich\nerwartet. Eure Niederlage\n\nwird das beste - das beste\nOpfer f\xfcr den wiederge-\n\nborenen Reschef!\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\nSiete arrivati, alla fine.\n\nVoi duellanti siete cos\xec\npuri di cuore e spirito.\n\nSperavo tanto che veniste.\nLa vostra sconfitta sar\xe0 la\n\nmigliore! La migliore offer-\nta per il rinato Reshef!\n\n")
  LANGUAGE_TEXT(4, "Fufufu...\nFinalmente hab\xe9is llegado.\n\nOh, vosotros duelistas,\ntan puros de coraz\xf3n\n\ny esp\xedritu.\nEsperaba que vinierais.\n\n\xa1Vuestra derrota es lo\nmejor!\n\n\xa1La mejor ofrenda para\nel renacido Reshef!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(5, 0, 8)
  LANGUAGE_TEXT(0, "Now! Go, my disciples!\n\nGo forth and defeat them!\n\n")
  LANGUAGE_TEXT(1, "Maintenant !\nAllez, mes disciples !\n\nAvancez et battez-les !\n\n")
  LANGUAGE_TEXT(2, "Nun los, meine Getreuen!\n\nGeht und vernichtet sie!\n\n")
  LANGUAGE_TEXT(3, "Ora!\nAvanti, miei discepoli!\n\nAndate a sconfiggerli!\n\n")
  LANGUAGE_TEXT(4, "\xa1Now!\n\xa1Vamos, mis disc\xedpulos!\n\n\xa1Id y derrotadlos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(4, 1)
  PORTRAIT(50, 0, 1)
  LANGUAGE_TEXT(0, "Gawry nida!\n\n")
  LANGUAGE_TEXT(1, "Grrr ah !\n\n")
  LANGUAGE_TEXT(2, "Grrrr!\n\n")
  LANGUAGE_TEXT(3, "Sar\xe0 fatto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vas a ver!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(8, 1)
  PORTRAIT(50, 0, 0)
  LANGUAGE_TEXT(0, "Gawry nida!\n\n")
  LANGUAGE_TEXT(1, "Grrr ah !\n\n")
  LANGUAGE_TEXT(2, "Grrrrrr!\n\n")
  LANGUAGE_TEXT(3, "Sar\xe0 fatto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vas a ver!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 96)
  WALK_OBJECT_Y(4, 96)
  WALK_OBJECT_Y(3, 96)
  WALK_OBJECT_Y(2, 96)
  PORTRAIT(5, 0, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being\ncreated my disciples.\n\nThese duelists have neither\nemotion nor mercy.\n\nCrush them, my minions!\n\n")
  LANGUAGE_TEXT(1, "Mes disciples sont la\ncr\xe9ation de Reshef,\n\nl'Etre des t\xe9n\xe8bres.\n\nCe sont des duellistes\nsans \xe9motion ni piti\xe9.\n\nAllez, donnez-leur un\navant-go\xfbt de la d\xe9faite.\n\n")
  LANGUAGE_TEXT(2, "Meine Getreuen wurden\nvon Reschef dem Dunklen\n\nerschaffen. Es sind Duel-\nlanten ohne Emotionen\n\noder Mitleid.\n\nLos, zeigt ihnen eine ver-\nnichtende Niederlage.\n\n")
  LANGUAGE_TEXT(3, "I miei discepoli sono stati\ncreati da Reshef il\n\nTenebroso.\n\nSono duellanti senza\nemozioni o piet\xe0. Forza,\n\nfategli assaporare una\nsconfitta schiacciante.\n\n")
  LANGUAGE_TEXT(4, "Mis disc\xedpulos son\nla creaci\xf3n de\n\nReshef, el Ser Oscuro.\n\nSon duelistas sin\nemoci\xf3n ni pena.\n\nVamos, hacedles\nprobar la derrota.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(5, 1, 8)
  LANGUAGE_TEXT(0, "Ahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Ahahahahaha !\n\n")
  LANGUAGE_TEXT(2, "Ahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Ahahahahaha!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  WARP(43, 3, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
