#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_26_state_10: map 26 state 10 */

LOAD_SPRITE(1, SPRITE_MAI)
LOAD_SPRITE(2, SPRITE_JEAN_CLAUDE_MAGNUM)
PLAY_MUSIC(MUSIC_JEAN_CLAUDE_MAGNUM)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_JEAN_CLAUDE_MAGNUM, OBJECT_EFFECT_JUMPING)
DELAY(8)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Mai Valentine, be mine!\n"
    "Marry me!\n\n"
    "Please!\n\n"
)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT,
    "Would you quit already?\n"
    "You're annoying me.\n\n"
)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "But if you marry me, I won't\n"
    "annoy you anymore.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MAI)
DELAY(16)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "I'm a Hollywood star. I have\n"
    "my pride.\n\n"
    "I'm not leaving until you\n"
    "say yes.\n\n"
)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT,
    "Listen to me, Romeo.\n\n"
    "I already have someone\n"
    "special.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_JEAN_CLAUDE_MAGNUM)
DELAY(32)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "So you can give up now, Jean\n"
    "Claude.\n\n"
)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Wh-who is he?\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_LEFT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_MAI)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT,
    "That's none of your\n"
    "business.\n\n"
)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You're lying, aren't you?\n"
    "You're just trying to make\n\n"
    "me leave.\n\n"
)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT,
    "Er, um...\n\n"
)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "See! There really isn't\n"
    "anyone special!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_JEAN_CLAUDE_MAGNUM, DIRECTION_RIGHT, 4, 0)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT,
    "Th-that's not true! There\n"
    "really is someone!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_LEFT, 4, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MAI | SPRITE_JEAN_CLAUDE_MAGNUM)
DELAY(32)
PLAY_MUSIC(MUSIC_274)
REACTION(REACTION_SWEATDROP, SPRITE_MAI)
DELAY(16)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "{BYTE_8169}...Why am I getting so\n"
    "worked up over this?{BYTE_816A}\n\n"
    "{BYTE_8169}And why do I keep thinking\n"
    "about him?{BYTE_816A}\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "...I wonder... How he's\n"
    "doing...\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_JEAN_CLAUDE_MAGNUM)
DELAY(8)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "He? W-wait!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT,
    "Would you be quiet!\n\n"
    "I'm going out. Cover for me\n"
    "as the dealer.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAI, DIRECTION_DOWN, 8, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_JEAN_CLAUDE_MAGNUM, DIRECTION_DOWN, 4, 0)
DELAY(8)
TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, PORTRAIT_LEFT,
    "B-but! Wait! Mai, please!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_MAI, 72)
WALK_OBJECT_X(SPRITE_MAI, 64)
WALK_OBJECT_Y(SPRITE_MAI, 96)
FADE_MUSIC(16)
FADE_SCREEN(16)
WARP(LOCATION_ITALY_CATACOMBS_LEFT, 3, 0, 0)
