#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_39_state_01: map 39 state 1 */

LOAD_SPRITE(1, SPRITE_ATEM)
LOAD_SPRITE(2, SPRITE_SHADI)
LOAD_SPRITE(3, SPRITE_MILLENNIUM_SCALE)
PLAY_MUSIC(MUSIC_401)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO,
    "L-look!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_UP, 4, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_316)
SHOW_OBJECT(SPRITE_MILLENNIUM_SCALE, 144, 112, 0, 0, 0)
DELAY(32)
WALK_OBJECT_Y(SPRITE_ATEM, 69)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "It's been a long time,\n"
    "partner.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(0, 68)
WALK_OBJECT_X(13, 76)
WALK_OBJECT_Y(13, 63)
MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
WALK_OBJECT_X(14, 76)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I've already snatched the\n"
    "Millennium Item here.\n\n"
    "Including the ones you have,\n"
    "that makes six.\n\n"
    "Ishizu told me to bring back\n"
    "all the Millennium Items.\n\n"
    "Fork over the Millennium\n"
    "Items you have.\n\n"
    "What are you waiting for?\n"
    "Give it!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "That's right. You did the\n"
    "right thing.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "Come on, what are you\n"
    "waiting for, you idiot!\n\n"
    "Hand over the Millennium\n"
    "Items!\n\n"
)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Wait a second! There's\n"
    "something wrong about him,\n\n"
    "{PLAYER}!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Wh-what do you mean?\n\n"
    "I'm the same ol' dude you\n"
    "all know and love!\n\n"
    "How could things go wrong? I\n"
    "look exactly like him!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_UP, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_DOWN, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_UP, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "My disguise is perfect.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Disguise?\n\n"
)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Uh... No, not a disguise! I\n"
    "meant... Um, I...\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(0, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(13, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(14, DIRECTION_LEFT, 4, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(0, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(13, DIRECTION_LEFT, 4, 0)
MOVE_OBJECT(14, DIRECTION_LEFT, 4, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Argh! My cover is blown! But\n"
    "it doesn't matter!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_330)
LOAD_SPRITE(1, SPRITE_MIMIC_OF_DOOM)
DELAY(32)
PLAY_MUSIC(MUSIC_403)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Gehehehehe!\n\n"
    "I am the Mimic of Doom!\n\n"
    "We'll duel for the\n"
    "Millennium Items!\n\n"
)
DUEL(DUELIST_MIMIC_OF_DOOM_050)
TALK(PORTRAIT_MIMIC_OF_DOOM, EXPRESSION_MIMIC_OF_DOOM_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Nooooooo! I can't lose!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_316)
SHOW_OBJECT(SPRITE_MILLENNIUM_SCALE, 42, 70, 0, 0, 0)
SLIDE_OBJECT(SPRITE_MILLENNIUM_SCALE, 1, 2)
WALK_OBJECT_X(SPRITE_MIMIC_OF_DOOM, 124)
SHOW_OBJECT(SPRITE_MIMIC_OF_DOOM, 144, 112, 0, 0, 0)
DELAY(16)
WALK_OBJECT_X(0, 48)
WALK_OBJECT_X(13, 58)
WALK_OBJECT_X(14, 58)
DELAY(16)
PLAY_MUSIC(MUSIC_316)
SHOW_OBJECT(SPRITE_MILLENNIUM_SCALE, 144, 112, 0, 0, 0)
DELAY(48)
PLAY_MUSIC(MUSIC_406)
PLAY_MUSIC(MUSIC_280)
SHOW_OBJECT(SPRITE_SHADI, 36, 69, 0, 1, 0)
DELAY(16)
TALK(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Six Millennium Items... You\n"
    "are to be praised.\n\n"
    "I hope you will not give up\n"
    "until you defeat Reshef...\n\n"
    "And save Pegasus from the\n"
    "darkness...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(16)
TALK(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "For Pegasus is also a\n"
    "victim.\n\n"
    "He has been swallowed by\n"
    "Reshef's powers of\n\n"
    "darkness.\n\n"
    "You must save the world and\n"
    "Pegasus from the shadows...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_281)
OBJECT_EFFECT(SPRITE_SHADI, OBJECT_EFFECT_TELEPORT)
SHOW_OBJECT(SPRITE_SHADI, 144, 112, 0, 0, 0)
DELAY(64)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "The Millennium Scale...\n\n"
    "We now have six Millennium\n"
    "Items.\n\n"
    "Quick, let's get back to\n"
    "Ishizu!\n\n"
)
SET_FLAG(EVENT_FLAG_DEFEATED_MIMIC_OF_DOOM)

EVENT_SCRIPT_REPLACEMENT(0x08ED4A98, map_39_state_01_08ED4A98, 0x08ED4AA4, 0x08F04040)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "What? I said hand it over!\n"
    "Now do it!\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()
