#include "event_macros.h"

/* map_14_state_10: map 14 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08E775C4, map_14_state_10_08E775C4, 0x08E775D0, 0x08E775DC)
  PLAY_MUSIC(230)
  HIDE_PORTRAIT()
  DELAY(64)
  PORTRAIT(4, 0, 8)
  LANGUAGE_TEXT(0, "Gotta hand it to you, Yugi.\nThat duel lasted barely a\n\nsecond!\n\nOn the other hand...\n\n")
  LANGUAGE_TEXT(1, "A toi de jouer, Yugi.\nC'\xe9tait instantan\xe9.\n\nD'un autre c\xf4t\xe9...\n\n")
  LANGUAGE_TEXT(2, "Das muss ich dir lassen,\nYugi. Das ging schnell.\n\nAndererseits...\n\n")
  LANGUAGE_TEXT(3, "I miei complimenti, Yugi.\n\xc8 stato fulmineo.\n\nD'altra parte...\n\n")
  LANGUAGE_TEXT(4, "Te lo reconozco, Yugi.\nHa sido instant\xe1neo\n\nPor otra parte...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 7, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, you had me\nworried!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, arr\xeate de\nme faire peur comme \xe7a.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, mach mir nicht\nsolche Angst.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, smettila\ndi spaventarmi cos\xec!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, deja de\nasustarme as\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "I... I couldn't afford to\nwaste any time.\n\nI have to find the spirit\nright away!\n\nBut {PLAYER}'s duel was\npretty impressive.\n\nLet's keep this up, guys!\n\n")
  LANGUAGE_TEXT(1, "Je... Je ne peux pas perdre\nde temps comme \xe7a.\n\nJe dois avant tout\ntrouver mon autre moi.\n\nMais le duel de {PLAYER}\n\xe9tait impressionnant.\n\nContinuez comme \xe7a,\nles amis !\n\n")
  LANGUAGE_TEXT(2, "Ich... ich darf keine Zeit\nvertr\xf6deln. Jedenfalls\n\nnicht, bis ich mein\nanderes Ich gefunden habe.\n\nAber das Duell von {PLAYER}\nwar ganz sch\xf6n\n\nbeeindruckend.\nWeiter so, Leute!\n\n")
  LANGUAGE_TEXT(3, "Io... Non posso mica\nsprecare il mio tempo.\n\nPrima devo trovare\nl'altro me stesso.\n\nMa il duello di {PLAYER}\n\xe8 stato notevole.\n\nForza e coraggio, amici!\n\n")
  LANGUAGE_TEXT(4, "No... No puedo perder\ntiempo.\n\nNo hasta que encuentre\nmi otro yo.\n\nPero el duelo de {PLAYER}\nha sido impresionante.\n\n\xa1A seguir as\xed, t\xedos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  CHECK_FLAG(200)
  FALLTHROUGH()
END_EVENT_SCRIPT()
