#include "event_macros.h"
#include "overworld.h"

/* map_00_state_02: map 0 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E349F4, map_00_state_02_08E349F4, 0x08E34A0C, 0x08E34A84)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_PUPPETEER_OF_DOOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A0C, map_00_state_02_08E34A0C, 0x08E34A18, 0x08F04040)
  WALK_OBJECT_Y(0, 29)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 39)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 39)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A18, map_00_state_02_08E34A18, 0x08E34A24, 0x08F0404C)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I am glad that you have\nreturned safely.\n\nI see that you have obtained\nthe Millennium Necklace.\n\nUnfortunately, it is not\nsufficient...\n\nA single Millennium Item\ndoes not have enough power.\n\nNot enough to restore the\nEgyptian God Cards from\n\nstone.\n\nThe next Millennium Item...\n\n")
  LANGUAGE_TEXT(1, "Je suis content\nque tu sois de retour.\n\nJe vois que tu as\nle Collier du mill\xe9nium.\n\nCependant, ce\nn'est pas suffisant.\n\nUn seul Objet du mill\xe9nium\nn'est pas assez puissant.\n\nPas assez pour restaurer\nles cartes de dieux\n\ntransform\xe9es en pierre.\n\nLe prochain Objet du\nmill\xe9nium...\n\n")
  LANGUAGE_TEXT(2, "Sch\xf6n, dass du wieder da\nbist.\n\nDu hast also die\nMillenniumskette.\n\nLeider reicht das aber\nnicht...\n\nEin einzelner Millenniums-\ngegenstand hat nicht\n\ngenug Kraft.\n\nNicht genug, um die G\xf6tter-\nkarten aus ihrer\n\nVersteinerung zu wecken.\n\nDer n\xe4chste\nMillenniumsgegenstand...\n\n")
  LANGUAGE_TEXT(3, "Sono felice di rivederti.\n\nVedo che hai ottenuto\nla Collana Millenaria.\n\nPurtroppo per\xf2, non \xe8\nsufficiente...\n\nUn solo Oggetto Millenario\nnon ha abbastanza potere.\n\nNon abbastanza per\nritrasformare la pietra\n\nin carte divine. Il prossimo\nOggetto Millenario...\n\n")
  LANGUAGE_TEXT(4, "Me satisface verte\nde nuevo.\n\nVeo que tienes el\nCollar del Milenio.\n\nSin embargo, no es\nbastante, por desgracia...\n\nUn solo Objeto del Milenio\nno tiene bastante poder.\n\nNo lo bastante para\nrestaurar las cartas\n\nde los dioses de su\nestado p\xe9treo.\n\nEl pr\xf3ximo\nObjeto del Milenio...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(2, 96)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, 8)
  LANGUAGE_TEXT(0, "W-what is this presence I'm\nfeeling?\n\n")
  LANGUAGE_TEXT(1, "C-c'est quoi,\ncette pr\xe9sence ?\n\n")
  LANGUAGE_TEXT(2, "W-was ist hier f\xfcr ein\nWesen?\n\n")
  LANGUAGE_TEXT(3, "E-e questo chi \xe8?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 es esta\npresencia?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  WALK_OBJECT_Y(2, 29)
  WALK_OBJECT_X(2, 68)
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(403)
  PORTRAIT(PORTRAIT_PUPPETEER_OF_DOOM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I am the Puppeteer of Doom!\n\nI won't let you meddle with\nMaster Chevalsky's plans!\n\nDuel!\n\n")
  LANGUAGE_TEXT(1, "Je suis le Puppeteer\nof Doom !\n\nJe ne vais pas te laisser\ninterf\xe9rer avec les plans\n\nde Ma\xeetre Chevalsky !\nBats-toi en duel !\n\n")
  LANGUAGE_TEXT(2, "Ich bin der Puppeteer of\nDoom!\n\nDu wirst die Pl\xe4ne von\nMeister Chevalsky\n\nnicht durcheinanderbringen!\n\nIch fordere dich zum Duell!\n\n")
  LANGUAGE_TEXT(3, "Sono il Puppeteer\nof Doom!\n\nNon lascer\xf2 che ti\nimmischi nei piani\n\ndel Maestro Chevalsky!\nDuella!\n\n")
  LANGUAGE_TEXT(4, "\xa1Soy el Puppeteer\nof Doom!\n\n\xa1No te dejar\xe9 interferir\nen los planes del\n\namo Chevalsky!\n\xa1Lucha!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(155)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A24, map_00_state_02_08E34A24, 0x08E34A30, 0x08F04040)
  SET_FLAG(EVENT_FLAG_DEFEATED_PUPPETEER_OF_DOOM)
  PORTRAIT(PORTRAIT_PUPPETEER_OF_DOOM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Gah! Don't get all cocky\njust because you beat me!\n\nThis is an invitation for a\nchallenge from Master Sol\n\nChevalsky!\n\n")
  LANGUAGE_TEXT(1, "Pff ! Tu ne devrais pas \xeatre\ntout excit\xe9 par le simple\n\nfait de me battre !\n\nC'est un d\xe9fi lanc\xe9 par\nMa\xeetre Sol Chevalsky !\n\n")
  LANGUAGE_TEXT(2, "Gah! Na und, du hast\nmich geschlagen!\n\nAber das hier ist eine\nHerausforderung von\n\nMeister Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(3, "Be', non ti dare tante arie\nper avermi sconfitto!\n\nQuesta \xe8 una sfida dal\nMaestro Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bah! \xa1No te emociones\ns\xf3lo por vencerme!\n\n\xa1Este es un reto del\namo Sol Chevalsky!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(285)
  SHOW_OBJECT(4, 64, 30, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(286)
  SLIDE_OBJECT(4, 1, 12)
  DELAY(16)
  WALK_OBJECT_X(2, 96)
  WALK_OBJECT_Y(2, 40)
  WALK_OBJECT_X(2, 128)
  DELAY(16)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This card... It's a video\ncard.\n\n")
  LANGUAGE_TEXT(1, "Cette carte...\nC'est une carte vid\xe9o.\n\n")
  LANGUAGE_TEXT(2, "Diese Karte...\nIst eine Videokarte.\n\n")
  LANGUAGE_TEXT(3, "Questa scheda...\n\xc8 una scheda video.\n\n")
  LANGUAGE_TEXT(4, "Esta carta...\nEs una tarjeta de v\xeddeo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Try setting it in your Duel\nDisk, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Essaie de la saisir sur ton\nDuel Disc, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Setze sie in deiner Duel\nDisc ein, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Prova a impostarla nel\ntuo Duel Disc, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Intenta ponerla en\ntu Duel Disc, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A30, map_00_state_02_08E34A30, 0x08E34A48, 0x08E34A3C)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A48, map_00_state_02_08E34A48, 0x08F04040, 0x08F04040)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(16)
  SHOW_OBJECT(4, 128, 96, 0, 0, 0)
  PLAY_MUSIC(287)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(64)
  PLAY_MUSIC(288)
  SHOW_OBJECT(3, 62, 29, 0, 1, 0)
  PLAY_MUSIC(413)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, 8)
  LANGUAGE_TEXT(0, "Bravo! I say bravissimo!\nCongratulations!\n\nI guess that both my agents\nhave failed me!\n\nHahaha! I had a feeling you\nguys will be a thorn in my\n\nside!\n\nBut why fret when I can make\na game out of this!\n\nHere are the rules. Let's\nsee you turn the Egyptian\n\nGod Cards back from stone...\n\nAnd bring them to my castle\nbefore time runs out!\n\nIf you don't make it in\ntime, I can't vouch for\n\nwhat happens to the world!\n\nHow does that sound?\nAhahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Bravo ! Je dis bravo !\nF\xe9licitations !\n\nJ'imagine que mes deux\nagents m'ont fait d\xe9faut !\n\nHa ha ha ! J'\xe9tais s\xfbr\nque vous alliez essayer\n\nde m'arr\xeater !\n\nAlors ! Tout \xe7a va\ndevenir un jeu excitant !\n\nVoyons comment vous changez\nles cartes de dieux en\n\npierre... Et comment vous\nles ramenez \xe0 mon ch\xe2teau\n\navant qu'il ne soit\ntrop tard !\n\nSi vous n'y arrivez pas,\nque va-t-il bien pouvoir\n\narriver au monde ?\n\nEh bien, qui sait ?\nAh ah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Bravo! Bravo!\nMeine Gl\xfcckw\xfcnsche!\n\nMeine beiden Agenten haben\nmich wohl im Stich\n\ngelassen!\n\nHahaha! Ich wusste, dass\nihr euch mir in den Weg\n\nstellen w\xfcrdet!\n\nDas wird ein tolles Spiel!\nMal sehen, ob ihr die\n\nG\xf6tterkarten aus ihrer Vers-\nteinerung befreien k\xf6nnt...\n\nBringt sie in meine Burg,\nbevor es zu sp\xe4t ist!\n\nWenn es euch nicht gelingt,\nwas wird dann mit der Welt?\n\nWer wei\xdf?\nAhahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Bravi! Complimenti!\nCongratulazioni!\n\nE cos\xec i miei due agenti\nmi hanno tradito! Ahahah!\n\nSapevo che avreste provato\na mettervi in mezzo!\n\nAllora! Ci sar\xe0 proprio\nda divertirsi!\n\nVediamo come ritrasformate\nla pietra in carte\n\ndivine...\n\nE portatele al mio castello\nprima dello scadere del\n\ntempo! Se non ce la farete,\nche ne sar\xe0 del mondo?\n\nMistero! Ahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bravo, bravo!\n\xa1Felicidades!\n\n\xa1Creo que mis dos agentes\nme han fallado!\n\n\xa1Jajaja! \xa1Sab\xeda que\nintentar\xedais fastidiarme!\n\n\xa1Ok! \xa1Haremos un gran\njuego de todo esto!\n\nVeamos c\xf3mo devolv\xe9is\na las cartas de los\n\ndioses su estado\noriginal...\n\n\xa1Y traedlas a mi castillo\nantes de que se acabe\n\nel tiempo!\n\nSi no lo consegu\xeds,\n\xbfqu\xe9 ser\xe1 del mundo?\n\n\xa1Qui\xe9n sabe!\n\xa1Jajajaja!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(289)
  OBJECT_EFFECT(8, 2)
  DELAY(64)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "He resurrected Reshef the\nDark Being...\n\n")
  LANGUAGE_TEXT(1, "Il a ressuscit\xe9 Reshef,\nl'Etre des t\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "Er lie\xdf Reschef den Dunklen\nwieder auferstehen...\n\n")
  LANGUAGE_TEXT(3, "Lui ha riportato in vita\nReshef il Tenebroso...\n\n")
  LANGUAGE_TEXT(4, "Ha resucitado a\nReshef, el Ser Oscuro...\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(8)
  CUTSCENE(1)
  WARP(0, 18, 3, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A3C, map_00_state_02_08E34A3C, 0x08E34A30, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't you want to know about\nthis mysterious Sol\n\nChevalsky?\n\nThis card doesn't look\ndangerous, so let's check\n\nit out!\n\n")
  LANGUAGE_TEXT(1, "Tu ne veux pas en savoir\nplus sur Sol Chevalsky ?\n\nCa a l'air d'une vraie\ncarte, alors v\xe9rifions.\n\n")
  LANGUAGE_TEXT(2, "Willst du nichts \xfcber diesen\nSol Chevalsky erfahren?\n\nDiese Karte sieht okay aus,\npr\xfcfen wir sie.\n\n")
  LANGUAGE_TEXT(3, "Non vuoi sapere qualcosa\ndi questo Sol Chevalsky?\n\nQuesta scheda sembra valida,\nallora diamole un'occhiata.\n\n")
  LANGUAGE_TEXT(4, "\xbfNo quieres saber sobre\neste Sol Chevalsky?\n\nEsta carta parece aut\xe9ntica,\nverifiqu\xe9moslo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F0404C, map_00_state_02_08F0404C, 0x08F04040, 0x08F04040)
  RESTORE_LIFE_POINTS()
  WARP(9, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A84, map_00_state_02_08E34A84, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "In order to imprison the\nDark Being resurrected by\n\nSol Chevalsky...\n\nWe need the Egyptian God\nCards.\n\nWe must restore the Egyptian\nGod Cards from stone.\n\nBut in order to do so, we\nrequire the Millennium\n\nItems.\n\nThe second Millennium Item\nis aboard a cruise ship.\n\nThe ship should be docked at\nDomino Pier.\n\n")
  LANGUAGE_TEXT(1, "Pour emprisonner\nl'Etre des t\xe9n\xe8bres\n\n\xe9lev\xe9 par Sol Chevalsky...\n\nLes cartes des dieux\nsont n\xe9cessaires.\n\nD'abord, les cartes de\ndieux doivent \xeatre\n\nrestaur\xe9es de leur \xe9tat\nde pierre.\n\nPour cela, les Objets du\nmill\xe9nium sont n\xe9cessaires.\n\nLe {BYTE_8251}\xe8me Objet du mill\xe9nium\nest \xe0 bord d'un paquebot de\n\ncroisi\xe8re. Ce paquebot\ndoit \xeatre amarr\xe9 \xe0 la\n\njet\xe9e de Domino.\n\n")
  LANGUAGE_TEXT(2, "Um den von Sol Chevalsky\ngeweckten Dunklen\n\nzu fassen...\n\n... brauchen wir die\nG\xf6tterkarten.\n\nBefreie zun\xe4chst die G\xf6tter-\nkarten aus dem Stein.\n\nDazu ben\xf6tigst du die\nMillenniumsgegenst\xe4nde.\n\nDer zweite Millenniums-\ngegenstand ist auf einem\n\nKreuzfahrtschiff.\n\nDas Schiff m\xfcsste am\nKai von Domino docken.\n\n")
  LANGUAGE_TEXT(3, "Per imprigionare il Tene-\nbroso liberato da Sol\n\nChevalsky...\n\nServono le carte divine.\n\nPrima bisogna recuperare\nle carte divine dalla\n\npietra. Per farlo, servono\ngli Oggetti Millenari.\n\nIl secondo Oggetto\nMillenario \xe8 a bordo di\n\nuna nave da crociera.\nLa nave dovrebbe\n\nessere ormeggiata al\nmolo di Domino.\n\n")
  LANGUAGE_TEXT(4, "Para encerrar al Ser\nOscuro, elevado por\n\nSol Chevalsky...\n\nSe necesitan las cartas\nde los dioses.\n\nPrimero, hay que\ndevolverlas a su\n\nestado original de su\nestado p\xe9treo actual.\n\nSe necesitan los Objetos\ndel Milenio para hacerlo.\n\nEl segundo Objeto del\nMilenio est\xe1 en un\n\ncrucero.\n\nEl barco deber\xeda estar\natracado en el muelle\n\nde Domino.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A00, map_00_state_02_08E34A00, 0x08E34A0C, 0x08E34A90)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_PUPPETEER_OF_DOOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34A90, map_00_state_02_08E34A90, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Please. Hurry to the cruise\nship.\n\nReshef the Dark Being will\nsoon engulf the world.\n\n")
  LANGUAGE_TEXT(1, "S'il te pla\xeet. Va vite\nsur ce paquebot.\n\nReshef, l'Etre des t\xe9n\xe8bres\nva bient\xf4t d\xe9truire le\n\nmonde et le plonger dans\nles t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Bitte. Lauf schnell zum\nKreuzfahrtschiff.\n\nReschef der Dunkle wird in\nK\xfcrze die Welt zerst\xf6ren.\n\n")
  LANGUAGE_TEXT(3, "Ti prego, corri alla nave\nda crociera.\n\nIl mondo cadr\xe0 presto\nnelle grinfie di\n\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Por favor, corre\nhasta el crucero.\n\nReshef, el Ser Oscuro\npronto acabar\xe1 con\n\nel mundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
