#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_34_state_05: map 34 state 5 */

LOAD_SPRITE(1, SPRITE_SERIOUS_ARCHEOLOGIST)
LOAD_SPRITE(2, SPRITE_CHIEF_ARCHEOLOGIST)
LOAD_SPRITE(3, SPRITE_FRIVOULOUS_ARCHEOLOGIST)
PLAY_MUSIC(MUSIC_707)
PLAY_MUSIC(MUSIC_381)
SHOW_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, 106, 32, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_DOWN, 4, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_SERIOUS_ARCHEOLOGIST, OBJECT_EFFECT_JUMPING)
DELAY(8)
TEXT
(
    "This is a huge discovery,\n"
    "eh!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_CHIEF_ARCHEOLOGIST | SPRITE_FRIVOULOUS_ARCHEOLOGIST)
DELAY(8)
MOVE_OBJECT(SPRITE_CHIEF_ARCHEOLOGIST, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_FRIVOULOUS_ARCHEOLOGIST, DIRECTION_RIGHT, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_UP, 4, 0)
SHOW_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, 128, 96, 0, 0, 0)
WALK_OBJECT_Y(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 64)
WALK_OBJECT_X(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 60)
WALK_OBJECT_Y(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 58)
WALK_OBJECT_X(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 92)
WALK_OBJECT_Y(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 48)
MOVE_OBJECT(SPRITE_CHIEF_ARCHEOLOGIST, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_CHIEF_ARCHEOLOGIST, OBJECT_EFFECT_JUMPING)
DELAY(8)
TEXT
(
    "We ought to hurry too.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_X(SPRITE_CHIEF_ARCHEOLOGIST, 106)
WALK_OBJECT_Y(SPRITE_CHIEF_ARCHEOLOGIST, 32)
SHOW_OBJECT(SPRITE_CHIEF_ARCHEOLOGIST, 128, 96, 0, 0, 0)
DELAY(16)
WALK_OBJECT_X(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 106)
WALK_OBJECT_Y(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 40)
DELAY(16)
MOVE_OBJECT(SPRITE_FRIVOULOUS_ARCHEOLOGIST, DIRECTION_DOWN, 0, 0)
DELAY(16)
TEXT
(
    "Maybe our find will really\n"
    "make us famous!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_273)
REACTION(REACTION_LOVE_HEART, SPRITE_FRIVOULOUS_ARCHEOLOGIST)
WALK_OBJECT_Y(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 32)
SHOW_OBJECT(SPRITE_FRIVOULOUS_ARCHEOLOGIST, 128, 96, 0, 0, 0)
FADE_MUSIC(8)
FADE_SCREEN(8)
WARP(LOCATION_CANADA_RUINS_MILLENNIUM_GUARDIAN, 3, 0, 0)
