#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_31_state_01: map 31 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EB4264, map_31_state_01_08EB4264, 0x08EB427C, 0x08EB4288)
  LOAD_SPRITE(1, SPRITE_PARA)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB427C, map_31_state_01_08EB427C, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Hiyah! This is a special dish for all, found only at",
      "the Great Wall!",
      "It's my Great Wall noodle soup! Eat and slurp!"
  )
  SET_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4288, map_31_state_01_08EB4288, EVENT_NOP, EVENT_NOP)
  TEXT("I'm very busy making noodles, okay?")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4258, map_31_state_01_08EB4258, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_706)
  PLAY_MUSIC(MUSIC_380)
  WALK_OBJECT_Y(0, 56)
  SHOW_OBJECT(13, 78, 88, 0, 0, 0)
  WALK_OBJECT_Y(13, 66)
  SHOW_OBJECT(14, 66, 88, 0, 0, 0)
  WALK_OBJECT_Y(14, 66)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(1, 72)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  TEXT(
      "Hiyah! This is a special dish for all, found only at",
      "the Great Wall!",
      "It's my Great Wall noodle soup! Eat and slurp!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 68)
  WALK_OBJECT_Y(1, 38)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  SET_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4270, map_31_state_01_08EB4270, 0x08EB427C, 0x08EB4294)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_PARA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4294, map_31_state_01_08EB4294, 0x08EB42A0, 0x08EB42D0)
  CHECK_FLAG(EVENT_FLAG_JOEY_FOUND_PARA_AND_DOX_SUSPICIOUS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42A0, map_31_state_01_08EB42A0, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Hiyah! You want to duel?",
      "I'm too busy making noodles and gruel. I have no time",
      "to duel."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42D0, map_31_state_01_08EB42D0, 0x08EB42DC, 0x08F0404C)
  PLAY_MUSIC(MUSIC_404)
  PLAY_MUSIC(MUSIC_330)
  TALK(PORTRAIT_PARA,
      "Grrr! How cleverly you surmise to see through our",
      "disguise!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 48)
  WALK_OBJECT_X(0, 68)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(13, 52)
  WALK_OBJECT_Y(13, 40)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(14, 84)
  WALK_OBJECT_Y(14, 40)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_PARA,
      "Very well! You leave us with no choice!",
      "I challenge you in Master Sol Chevalsky's place!",
      "We shall duel! Prepare to lose, you fool!"
  )
  DUEL(DUELIST_PARA_039)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42DC, map_31_state_01_08EB42DC, 0x08EB42E8, EVENT_NOP)
  PLAY_MUSIC(MUSIC_404)
  TALK(PORTRAIT_PARA,
      "That was cruel! I concede defeat in this duel!",
      "But our true skill is in tag duels!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, "Younger brother, let us take them down together!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(2, 92)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_14)
  SLIDE_OBJECT(14, 0, 6)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  WALK_OBJECT_X(2, 76)
  LOAD_SPRITE(2, SPRITE_DOX)
  DELAY(8)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_14)
  DELAY(8)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 8, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 6, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  DELAY(8)
  TALK(PORTRAIT_DOX, "Elder brother! I am here to help!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, "In a tag duel, defeating the likes of you...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(SPRITE_DOX, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, "...Would be so simple I already bid you adieu!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42E8, map_31_state_01_08EB42E8, 0x08EB42F4, 0x08EB4300)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_Y(6, 64)
  DELAY(16)
  PLAY_MUSIC(MUSIC_405)
  TALK(PORTRAIT_SETO,
      "I can't believe you're struggling against these",
      "amateurs!"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_1 | OBJECT_2 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_PARA, "Kaiba!")
  TALK(PORTRAIT_MOKUBA,
      "My big brother's here to take you down",
      "Because you work for Sol Chevalsky."
  )
  TALK(PORTRAIT_SETO,
      "The only duelist worthy of the Egyptian God Cards...",
      "Is me!",
      "I'll show no mercy, even against miserable duelists",
      "like you!"
  )
  TALK(PORTRAIT_SETO, 1,
      "{PLAYER}! Today's your lucky day!",
      "I'll help you! Choose which sissy to duel!"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Para\nDox{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB42F4, map_31_state_01_08EB42F4, 0x08EB430C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(5, DIRECTION_UP, 8, 0)
  WALK_OBJECT_X(5, 76)
  WALK_OBJECT_Y(5, 48)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(6, DIRECTION_RIGHT, 16, 0)
  WALK_OBJECT_Y(6, 48)
  MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  DUEL(DUELIST_SETO_040)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB430C, map_31_state_01_08EB430C, 0x08EB4318, EVENT_NOP)
  PLAY_MUSIC(MUSIC_405)
  TALK(PORTRAIT_SETO, 2, "Come forth, Blue-Eyes White Dragon!")
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, "White Lightning!")
  PLAY_MUSIC(MUSIC_338)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_ATTACK_UP_ALT)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4318, map_31_state_01_08EB4318, 0x08EB4324, EVENT_NOP)
  SLIDE_OBJECT(1, 2, 4)
  DELAY(8)
  TALK(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, "M-Master Sol Chevalsky...")
  HIDE_PORTRAIT()
  DELAY(8)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(8)
  TALK(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, "...W-we have failed you...")
  TALK(PORTRAIT_SETO, 1,
      "Run to Sol Chevalsky and tell him.",
      "That as long as Seto Kaiba lives...",
      "All his plans are doomed to fail! Wahahahahahaha!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4324, map_31_state_01_08EB4324, 0x08EB4330, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_Y(1, 96)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 8, 0)
  WALK_OBJECT_Y(2, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4330, map_31_state_01_08EB4330, 0x08EB436C, EVENT_NOP)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, "{PLAYER}, you only won because you had my help.")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2,
      "Listen, {PLAYER}.",
      "I walk my own road.",
      "I don't know if you'll win or fail on your journey...",
      "But try not to disappoint me."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 1,
      "Now go and look for your mystical trinkets.",
      "While you play scavenger hunt, I'll save the world.",
      "Wahahahahaha!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB436C, map_31_state_01_08EB436C, 0x08EB4378, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 96)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4378, map_31_state_01_08EB4378, 0x08EB4384, 0x08EB4390)
  WALK_OBJECT_Y(6, 56)
  WALK_OBJECT_X(6, 72)
  MOVE_OBJECT(6, DIRECTION_UP, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA,
      "You better hurry up and find the Millennium Items.",
      "We heard that the Neo Ghouls are hunting for them, too."
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Is that true?\nSo it was true...{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4384, map_31_state_01_08EB4384, 0x08EB439C, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA,
      "You can thank KaibaCorp's information network.",
      "That's why Seto's here, to give you this info...",
      "Oops, he told me not tell you that.",
      "Well, see ya!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB439C, map_31_state_01_08EB439C, EVENT_NOP, EVENT_NOP)
  HIDE_PORTRAIT()
  TEXT_FRAGMENT("{BYTE_8168}")
  WALK_OBJECT_Y(6, 96)
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_DEFEATED_PARA_AND_DOX)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4390, map_31_state_01_08EB4390, 0x08EB439C, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA,
      "Oh, you knew already?",
      "To think that we came all the way out here...",
      "Just because Seto wanted you to have this info...",
      "Oops, that's supposed to be a secret! Don't let Seto",
      "know that I told you!",
      "Well, see ya!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4300, map_31_state_01_08EB4300, 0x08EB433C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 76)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(5, 48)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(6, DIRECTION_LEFT, 24, 0)
  WALK_OBJECT_Y(6, 48)
  MOVE_OBJECT(6, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  DUEL(DUELIST_MOKUBA_041)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB433C, map_31_state_01_08EB433C, 0x08EB4348, EVENT_NOP)
  PLAY_MUSIC(MUSIC_405)
  TALK(PORTRAIT_SETO, 2, "Come forth, Blue-Eyes White Dragon!")
  PLAY_MUSIC(MUSIC_333)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, "White Lightning!")
  PLAY_MUSIC(MUSIC_338)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_ATTACK_UP)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4348, map_31_state_01_08EB4348, 0x08EB4354, EVENT_NOP)
  SLIDE_OBJECT(1, 2, 4)
  DELAY(8)
  TALK(PORTRAIT_PARA, EXPRESSION_PARA_DEFEATED, "M-Master Sol Chevalsky...")
  HIDE_PORTRAIT()
  DELAY(8)
  SLIDE_OBJECT(2, 2, 4)
  DELAY(8)
  TALK(PORTRAIT_DOX, EXPRESSION_DOX_DEFEATED, "...W-we have failed you...")
  TALK(PORTRAIT_SETO, 1,
      "Run to Sol Chevalsky and tell him.",
      "That as long as Seto Kaiba lives...",
      "All his plans are doomed to fail! Wahahahahahaha!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4354, map_31_state_01_08EB4354, 0x08EB4360, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_Y(1, 96)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 8, 0)
  WALK_OBJECT_Y(2, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB4360, map_31_state_01_08EB4360, 0x08EB436C, EVENT_NOP)
  MOVE_OBJECT(5, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, "{PLAYER}, you only won because you had my help.")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2,
      "Listen, {PLAYER}.",
      "I walk my own road.",
      "I don't know if you'll win or fail on your journey...",
      "But try not to disappoint me."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 1,
      "Now go and look for your mystical trinkets.",
      "While you play scavenger hunt, I'll save the world.",
      "Wahahahahaha!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
