#include "event_macros.h"
#include "overworld.h"

/* map_00_state_06: map 0 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E34B50, map_00_state_06_08E34B50, 0x08E34B5C, 0x08E34BB0)
  CHECK_FLAG(174)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B5C, map_00_state_06_08E34B5C, 0x08E34B68, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, 8)
  LANGUAGE_TEXT(0, "I could not foretell that\nSol Chevalsky was actually\n\nMaximillion Pegasus...\n\nHe has been missing since\nDuelist Kingdom...\n\n")
  LANGUAGE_TEXT(1, "Ce-ce Pegasus \xe9tait\nen fait Sol Chevalsky...\n\nOn ne l'avait pas vu\ndepuis le Duel Kingdom...\n\n")
  LANGUAGE_TEXT(2, "D-dieser Pegasus war\nSol Chevalsky...\n\nSeit dem Duel Kingdom hat\nihn niemand gesehen...\n\n")
  LANGUAGE_TEXT(3, "Cos\xec, Pegasus in realt\xe0\nera Sol Chevalsky...\n\nNon lo si vedeva pi\xf9\ndai tempi del Duel\n\nKingdom...\n\n")
  LANGUAGE_TEXT(4, "E-ese Pegasus era en\nverdad Sol Chevalsky...\n\nDesde lo del Duel Kingdom,\nno se le ha vuelto a ver...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What could have happened to\nhim during all this time?\n\nWe cannot worry about this\nnow. Let's resurrect an\n\nEgyptian God Card.\n\nWith the powers of the\nMillennium Ring and\n\nMillennium Eye...\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce qu'il lui\nest arriv\xe9 ?\n\nMais il faut d'abord\nressusciter une carte\n\nde dieu, gr\xe2ce \xe0 la\npuissance de l'Anneau\n\ndu mill\xe9nium et de l'\u0152il.\n\n")
  LANGUAGE_TEXT(2, "Was ist wohl mit ihm\ngeschehen?\n\nAber erst m\xfcssen wir eine\nG\xf6tterkarte\n\nwiederherstellen.\n\nMit der Kraft des Millenniu-\nmsrings und des Auges...\n\n")
  LANGUAGE_TEXT(3, "Che gli sar\xe0 successo?\n\nMa prima dobbiamo\nrisuscitare una carta\n\ndivina. Con i poteri di\nAnello ed Occhio\n\nMillenario...\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 le podr\xeda haber\npasado?\n\nPero, primero, tenemos que\nresucitar una carta del\n\ndios.\n\nCon los poderes del Anillo\ny del Ojo del Milenio...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B68, map_00_state_06_08E34B68, 0x08E34B74, 0x08F04040)
  PLAY_MUSIC(290)
  COMMAND_7C_ARG(8, 2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B74, map_00_state_06_08E34B74, 0x08E34B80, 0x08E34B8C)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Obelisk the Tormentor\nhas regained its power.\n\nHowever.")
  LANGUAGE_TEXT(1, "Ob\xe9lisk, le Bourreau a\nretrouv\xe9 sa puissance.")
  LANGUAGE_TEXT(2, "Obelisk, der Peiniger, ist\nwiedererstarkt.\n\nDennoch.")
  LANGUAGE_TEXT(3, "Obelisco del Tiranno\nha ripreso potere.\n\nTuttavia.")
  LANGUAGE_TEXT(4, "Obelisk el atormentador ha\nrecuperado su poder.\n\nNo obstante.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, "")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "Egyptian God\nCards choose their bearers.\n\nIt appears that Obelisk will\nnot accept you.\n\nIt seems you are not yet\nready to control its\n\nimmense powers.\n\nThe card has chosen as its\nbearer...\n\n")
  LANGUAGE_TEXT(1, "\n\nMais les cartes de\ndieux choisissent\n\nleur propri\xe9taire.\n\nApparemment, Ob\xe9lisk\nne t'accepte pas.\n\nLa carte n'est pas\nencore pr\xeate pour toi.\n\nElle a choisi comme\npropri\xe9taire...\n\n")
  LANGUAGE_TEXT(2, "G\xf6tterkarten w\xe4h-\nlen selbst ihren Besitzer.\n\nWie es aussieht, wird\nObelisk dich nicht\n\nakzeptieren.\n\nDie Zeit, dass er dein wird,\nist noch nicht gekommen.\n\nDie Karte w\xe4hlt als ihren\nBesitzer...\n\n")
  LANGUAGE_TEXT(3, "Le carte divine\nsi scelgono i loro\n\nportatori. Sembra che\nObelisco non ti accetter\xe0.\n\nNon \xe8 giunto il momento\nper lui di diventare tuo.\n\nLa carta ha scelto come\nsuo portatore...\n\n")
  LANGUAGE_TEXT(4, "Las cartas\nde los dioses eligen a sus\n\nportadores.\n\nParece que Obelisk\nno te acepta.\n\nNo es momento de que\nsea de tu propiedad.\n\nLa carta ha elegido como\nsu portador a...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(2, 48)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_X(3, 40)
  MOVE_OBJECT(3, 2, 0, 0)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Enough of this bogus mystic\ntalk!\n\nIt's obvious who deserves to\ncontrol Obelisk!\n\nWho else but me!\n\n")
  LANGUAGE_TEXT(1, "Assez de ton\nnum\xe9ro d'acteur !\n\nLe seul propri\xe9taire\ndigne de l'Ob\xe9lisk,\n\nc'est \xe9vident\nque c'est moi !\n\n")
  LANGUAGE_TEXT(2, "Genug von deinem l\xe4cherli-\nchen, mystischen Theater!\n\nDer rechtm\xe4\xdfige Besitzer\ndes Obelisk steht fest!\n\nWer k\xf6nnte es sein,\nwenn nicht ich?\n\n")
  LANGUAGE_TEXT(3, "Basta con questa\npagliacciata occulta!\n\nTutti sanno a chi spetta\ndi dovere Obelisco!\n\nA chi, se non a me?\n\n")
  LANGUAGE_TEXT(4, "\xa1Basta ya de tu rid\xedcula\nactuaci\xf3n m\xedstica!\n\n\xa1El debido portador de\nObelisk es obvio!\n\n\xbfQui\xe9n sino yo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Don't bet on it!\nI guess so...{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Rien n'est moins s\xfbr !\nC'est in\xe9luctable.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Verlass dich nicht darauf!\nDaran ist nichts zu \xe4ndern{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Non contarci troppo!\nNon si pu\xf2 evitare{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1No apuestes por ello!\nNo se puede hacer nada{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B80, map_00_state_06_08E34B80, 0x08E34B98, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(275)
  REACTION(5, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, 8)
  LANGUAGE_TEXT(0, "Don't bet on it? Don't talk\nto my brother that way!\n\nIf it wasn't for my\nbrother...\n\nYou wouldn't have won the\ntag duel!\n\n")
  LANGUAGE_TEXT(1, "Rien n'est moins s\xfbr ?\nEsp\xe8ce d'ingrat.\n\nSans mon grand\nfr\xe8re...\n\nTu n'aurais jamais\ngagn\xe9 le duel \xe0 deux !\n\n")
  LANGUAGE_TEXT(2, "Verlass dich nicht darauf?\nDu Undankbarer!\n\nWenn mein gro\xdfer Bruder\nnicht gewesen w\xe4re...\n\nH\xe4ttest du nie im Leben das\nDoppelduell gewonnen!\n\n")
  LANGUAGE_TEXT(3, "Non contarci troppo?\nRazza di ingrato!\n\nSe non fosse stato per\nmio fratello...\n\nNon avresti vinto il\nduello doppio!\n\n")
  LANGUAGE_TEXT(4, "\xbfNo apuestes por ello?\n\xa1Por qu\xe9, t\xfa, ingrato!\n\nSi no fuera por mi\ngran hermano...\n\n\xa1No habr\xedas ganado\nel duelo a dos!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B98, map_00_state_06_08E34B98, 0x08E34BA4, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 40)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  MOVE_OBJECT(0, 1, 8, 0)
  MOVE_OBJECT(0, 3, 0, 0)
  WALK_OBJECT_Y(2, 32)
  DELAY(43)
  PLAY_MUSIC(285)
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't care what you\namateurs think...\n\nIf you have a problem, come\nout and say it!\n\nTry to defeat me and take\nObelisk!\n\n")
  LANGUAGE_TEXT(1, "Ce ne sont pas\ndes gros nuls\n\nen train de pleurnicher\nqui vont m'apitoyer...\n\nMais si tu le veux, je\nsuis pr\xeat \xe0 t'affronter !\n\nBats-moi pour me soumettre\nOb\xe9lisk !\n\n")
  LANGUAGE_TEXT(2, "M\xf6ge der Abschaum\nwimmern - wen st\xf6rt's?\n\nAber wenn du unbedingt\nwillst, fordere mich ruhig\n\nzum Duell. Ich bin jederzeit\nbereit!\n\nBesiege mich und unterwirf\nObelisk!\n\n")
  LANGUAGE_TEXT(3, "I miagolii degli idioti\nnon hanno potere su\n\ndi me... Ma se proprio\ninsisti, sfidami in\n\nqualsiasi momento!\n\nBattimi e soggioga\nObelisco!\n\n")
  LANGUAGE_TEXT(4, "El lloriqueo de cutres no\ntiene influencia alguna\n\nen m\xed.\n\nPero si quieres forzarlo,\n\xa1r\xe9tame cuando quieras!\n\n\xa1Derr\xf3tame y subyuga\na Obelisk!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "Though I don't know how a\nbunch of incompetent fools\n\nare ever going to beat me!\n\nWahahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Mais bien s\xfbr, ce n'est\npas quelque chose\n\ndont les gros nuls\nsont capables !\n\nMouah ah ah ah !\n\n")
  LANGUAGE_TEXT(2, "Aber f\xfcr Abschaum ist das\nnat\xfcrlich nicht m\xf6glich!\n\nWahahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Ma naturalmente,\nci\xf2 \xe8 impossibile\n\nper degli idioti!\nUahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "\xa1Aunque, naturalmente,\nes imposible para cutres!\n\n\xa1Wajajajajaja!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 64)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_X(2, 128)
  WALK_OBJECT_Y(3, 64)
  WALK_OBJECT_X(3, 128)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You cannot deny destiny...\n\n")
  LANGUAGE_TEXT(1, "Ton destin le veut ainsi.\n\n")
  LANGUAGE_TEXT(2, "Es ist durch dein Schicksal\nvorbestimmt...\n\n")
  LANGUAGE_TEXT(3, "Cos\xec vuole il tuo\ndestino... Dovrai\n\n")
  LANGUAGE_TEXT(4, "Esto es ordenado por\ntu destino...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You must wait until it is\nyour time.\n\n")
  LANGUAGE_TEXT(1, "Tu dois attendre\nle bon moment.\n\n")
  LANGUAGE_TEXT(2, "Du musst warten, bis die\nZeit reif ist.\n\n")
  LANGUAGE_TEXT(3, "aspettare finch\xe9 non\nsar\xe0 il momento giusto.\n\n")
  LANGUAGE_TEXT(4, "Debes esperar a que sea el\nmomento adecuado.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BA4, map_00_state_06_08E34BA4, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(4, 64)
  WALK_OBJECT_X(4, 48)
  WALK_OBJECT_Y(4, 52)
  DELAY(16)
  PLAY_MUSIC(31)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hey, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "He, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Ehi, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hey, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hey, what's up, Tristan?\nWhat are you doing here?\n\nNothin' betta have happened\nto Serenity!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, \xe7a va Tristan ?\n\nMais qu'est-ce\nque tu fais l\xe0 ?\n\nJ'esp\xe8re qu'il n'est\nrien arriv\xe9 \xe0 Serenity...\n\n")
  LANGUAGE_TEXT(2, "He, was ist los, Tristan?\nWas machst du denn hier?\n\nIch hoffe, mit Serenity ist\nalles in Ordnung...\n\n")
  LANGUAGE_TEXT(3, "Ehi, che succede, Tristan?\nChe ci fai qui?\n\nNon sar\xe0 mica successo\nniente a Serenity?\n\n")
  LANGUAGE_TEXT(4, "Hey, \xbfqu\xe9 pasa, Tristan?\n\xbfQu\xe9 haces por aqu\xed?\n\nSer\xe1 mejor que no pase nada\nmalo con Serenity.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Uh... Well, actually,\nyeah... That's...what I'm\n\nhere about.\n\n")
  LANGUAGE_TEXT(1, "Mmm... Eh bien,\nen fait, si.\n\n")
  LANGUAGE_TEXT(2, "Uh... Na ja, nicht ganz.\n\n")
  LANGUAGE_TEXT(3, "Ehm... Be', a dire il vero,\nqualcosa \xe8 successo.\n\n")
  LANGUAGE_TEXT(4, "Uh... Bueno, en verdad, s\xed,\ns\xed que pasa.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Say what?! What happened to\nmy sister!\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Qu'est-il\narriv\xe9 \xe0 ma s\u0153ur ?\n\n")
  LANGUAGE_TEXT(2, "Was sagst du? Was ist\nmit meiner Schwester?\n\n")
  LANGUAGE_TEXT(3, "Che stai dicendo? Che \xe8\nsuccesso a mia sorella?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 dices?\n\xbfQu\xe9 pasa con mi hermana?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Well...\n\nShe really wants to see the\nKaibaman show.\n\n")
  LANGUAGE_TEXT(1, "Eh bien, voil\xe0...\n\nElle veut \xe0 tout prix voir\nle spectacle de Kaibaman.\n\n")
  LANGUAGE_TEXT(2, "Nun, sie will unbedingt die\nKaibaman Show sehen.\n\n")
  LANGUAGE_TEXT(3, "Be', ecco...\n\n\xc8 decisa a vedere il\nKaibaman Show.\n\n")
  LANGUAGE_TEXT(4, "Bueno, ver\xe1s...\n\nInsiste en que quiere ver el\nshow de Kaibaman.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "The Kaibaman show? What the\nheck is that?\n\n")
  LANGUAGE_TEXT(1, "Le spectacle\nde Kaibaman ?\n\nMais c'est quoi,\nce truc-l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Kaibaman Show?\nWas zum Teufel ist das?\n\n")
  LANGUAGE_TEXT(3, "Il Kaibaman Show?\nE che diavolo \xe8?\n\n")
  LANGUAGE_TEXT(4, "\xbfEl show de Kaibaman?\n\xbfQu\xe9 narices es eso?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You haven't heard of it?\n\nIt's the biggest thing right\nnow! Kids love it! Get with\n\nthe times, man!\n\n")
  LANGUAGE_TEXT(1, "Quoi, tu ne\nle connais pas ?\n\nC'est le truc dont tous\nles jeunes sont dingues\n\nen ce moment.\n\n")
  LANGUAGE_TEXT(2, "Was, du hast noch nie\ndavon geh\xf6rt?\n\nDas ist im Moment der Hit\nbei den Kids.\n\n")
  LANGUAGE_TEXT(3, "Come, non lo sai?\n\nTutti i ragazzini ne\nvanno pazzi.\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9, no lo sabes?\n\nEs lo m\xe1s popular entre\nlos chicos de ahora.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Well, I don't like anything\nwith the name Kaiba in\n\nit...\n\nBut if Serenity wants to go,\nI guess I'll take her.\n\n")
  LANGUAGE_TEXT(1, "Je ne connais pas tous ces\ntrucs Kaiba ou Cyber...\n\nMais si Serenity veut y\naller, je vais l'emmener.\n\n")
  LANGUAGE_TEXT(2, "Na, ich kenne mich nicht\naus mit Kaiba oder Cyber...\n\nAber wenn Serenity gehen\nwill, gehe ich mit ihr.\n\n")
  LANGUAGE_TEXT(3, "Be', non so niente di\nKaiba o cyber...\n\nMa se Serenity ci vuole\nandare, ce la porter\xf2 io.\n\n")
  LANGUAGE_TEXT(4, "Bueno, no s\xe9 nada\nde Kaiba o ciber...\n\nPero si Serenity quiere ir,\nla llevar\xe9.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Oh, but I can't just abandon\nmy duties without\n\npermission.\n\n")
  LANGUAGE_TEXT(1, "Oh, mais je ne peux pas\npartir comme \xe7a.\n\n")
  LANGUAGE_TEXT(2, "Oh, aber ich kann ja nicht\neinfach gehen.\n\n")
  LANGUAGE_TEXT(3, "Per\xf2 non posso\nandarmene cos\xec.\n\n")
  LANGUAGE_TEXT(4, "Ah, pero no me puedo\nir as\xed sin m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, can I take some\ntime off?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, qu'est-ce que\ntu penses d'un peu de\n\ntemps libre ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, kann ich eine\nkurze Pause einlegen?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, che ne\ndici di una piccola pausa?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfqu\xe9 hay de\nuna pausa?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hahaha...\n\n")
  LANGUAGE_TEXT(1, "Fufufu...\n\n")
  LANGUAGE_TEXT(2, "Fufufu...\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\n\n")
  LANGUAGE_TEXT(4, "Fufufu...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "I'm sorry for laughing.\n\nA little time off will help\nyou relax and rekindle your\n\nspirits.\n\nPerhaps you can all go see\nthe show.\n\n")
  LANGUAGE_TEXT(1, "D\xe9sol\xe9 !\n\nUn peu de temps libre ne\nnous ferait pas de mal.\n\nOn pourrait peut-\xeatre tous\naller voir le spectacle.\n\n")
  LANGUAGE_TEXT(2, "Tut mir Leid.\n\nEine Pause w\xfcrde uns\nungemein motivieren.\n\nVielleicht k\xf6nnt ihr euch\nja alle die Show ansehen.\n\n")
  LANGUAGE_TEXT(3, "Scusate.\n\nUna piccola pausa farebbe\nmeraviglie per il nostro\n\numore. Potreste andare\ntutti a vedere lo show.\n\n")
  LANGUAGE_TEXT(4, "Lo siento.\n\nUna pausa har\xeda maravillas\npara nuestros \xe1nimos.\n\nQuiz\xe1s pod\xe1is ir todos\na ver el show.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah! You know what's up,\nIshizu!\n\nAll right. I'd better find\nSerenity and...\n\n")
  LANGUAGE_TEXT(1, "Excellent !\nTu es trop cool, Ishizu !\n\nOK bon, je ferais bien\nde trouver Serenity et...\n\n")
  LANGUAGE_TEXT(2, "Perfekt!\nDu bist toll, Ishizu!\n\nOkay dann. Ich suche\nSerenity und...\n\n")
  LANGUAGE_TEXT(3, "Ottima idea! Sei\ngrande, Ishizu!\n\nBene, allora. Farei\nmeglio a trovare\n\nSerenity e...\n\n")
  LANGUAGE_TEXT(4, "\xa1Perfecto!\n\xa1Eres genial, Ishizu!\n\nDe acuerdo. Ser\xe1 mejor que\nencuentre a Serenity y...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, 8)
  LANGUAGE_TEXT(0, "I thought you'd say that, so\nI already brought her.\n\n")
  LANGUAGE_TEXT(1, "J'\xe9tais s\xfbr que\ntu allais dire \xe7a,\n\nalors je suis all\xe9\nla chercher pour toi.\n\n")
  LANGUAGE_TEXT(2, "Ich dachte mir schon, dass\ndu so reagieren w\xfcrdest,\n\ndarum habe ich sie hierher\ngebracht.\n\n")
  LANGUAGE_TEXT(3, "Sapevo che l'avresti detto,\ncos\xec l'ho portata con me.\n\n")
  LANGUAGE_TEXT(4, "Pens\xe9 que lo dir\xedas,\nas\xed que ya la he tra\xeddo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, 8)
  LANGUAGE_TEXT(0, "Serenity, come on in.\n\n")
  LANGUAGE_TEXT(1, "Serenity, viens donc ici.\n\n")
  LANGUAGE_TEXT(2, "Serenity, komm herein.\n\n")
  LANGUAGE_TEXT(3, "Serenity, vieni qui.\n\n")
  LANGUAGE_TEXT(4, "Serenity, ven.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_X(5, 40)
  WALK_OBJECT_Y(5, 52)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Joey, can I really go?\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re, c'est vrai,\nje peux y aller ?\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder, darf ich\nwirklich gehen?\n\n")
  LANGUAGE_TEXT(3, "Fratello, posso\nandarci davvero?\n\n")
  LANGUAGE_TEXT(4, "Gran hermano, \xbfpuedo\nir, de verdad?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No doubt!\n\n")
  LANGUAGE_TEXT(1, "Oui, bien s\xfbr.\n\n")
  LANGUAGE_TEXT(2, "Klar.\n\n")
  LANGUAGE_TEXT(3, "Ma certo.\n\n")
  LANGUAGE_TEXT(4, "Pues claro.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Thank you, Joey!\n\nI'll go ahead and save us a\nspot.\n\n")
  LANGUAGE_TEXT(1, "Merci, Joey !\n\nJe pars nous r\xe9server\nune place.\n\n")
  LANGUAGE_TEXT(2, "Danke, Joey!\n\nIch gehe schon vor und\nhalte uns einen Platz frei.\n\n")
  LANGUAGE_TEXT(3, "Grazie, Joey!\n\nAndr\xf2 avanti e\nprender\xf2 i posti.\n\n")
  LANGUAGE_TEXT(4, "\xa1Gracias, Joey!\n\nIr\xe9 antes y coger\xe9\nsitio.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_X(5, 128)
  MOVE_OBJECT(4, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Kaibaman show is being\nshown in front of\n\nKaibaCorp.\n\nNow you shouldn't keep a\nlady waiting, especially\n\nSerenity.\n\nI'm outta here.\n\n")
  LANGUAGE_TEXT(1, "Le spectacle Kaibaman\npasse avant celui de\n\nla Kaiba Corporation.\n\nTu ferais bien de\nrattraper Serenity.\n\nDe toute fa\xe7on,\nmoi, je pars.\n\n")
  LANGUAGE_TEXT(2, "Die Kaibaman Show findet\nvor der Kaiba Corp. statt.\n\nGeh schnell zu Serenity.\nIch gehe jetzt auch.\n\n")
  LANGUAGE_TEXT(3, "Il Kaibaman Show si\nsvolger\xe0 davanti\n\nalla Kaiba Corp.\n\nFareste meglio a\nraggiungere Serenity.\n\nAllora, io me ne vado.\n\n")
  LANGUAGE_TEXT(4, "El show de Kaibaman se\nrepresenta delante de\n\nKaiba Corp.\n\nMejor que des alcance\na Serenity.\n\nDe cualquier modo,\nyo me voy.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 64)
  WALK_OBJECT_X(4, 60)
  WALK_OBJECT_Y(4, 96)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "We should go too.\n\n")
  LANGUAGE_TEXT(1, "Je crois qu'on ferait bien\nde se mettre aussi en\n\nroute.\n\n")
  LANGUAGE_TEXT(2, "Na, ich glaube, wir sollten\nalle gehen.\n\n")
  LANGUAGE_TEXT(3, "Be', credo che dovremmo\nandare anche noi.\n\n")
  LANGUAGE_TEXT(4, "Bueno, supongo que\ndeber\xedamos ir tambi\xe9n.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 48)
  WALK_OBJECT_Y(0, 52)
  SET_FLAG(174)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B8C, map_00_state_06_08E34B8C, 0x08E34B98, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Heh. You finally realize\nyou're not in my league.\n\n")
  LANGUAGE_TEXT(1, "Humph. Au moins, tu\nsais \xe0 quoi t'en tenir.\n\n")
  LANGUAGE_TEXT(2, "Humph. Wenigstens kennst\ndu deinen Platz.\n\n")
  LANGUAGE_TEXT(3, "Be', almeno sembri avere\ncapito qual \xe8 il tuo posto.\n\n")
  LANGUAGE_TEXT(4, "Vaya. Parece que por\nfin conoces tu lugar.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BB0, map_00_state_06_08E34BB0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "Serenity is waiting for you.\n\nShe should be at Kaiba\nCorporation.\n\nWeren't you going to see the\nKaibaman show?\n\n")
  LANGUAGE_TEXT(1, "Serenity ne t'attend pas ?\n\nElle est s\xfbrement\n\xe0 la Kaiba Corporation.\n\nTu n'allais pas voir avec\nelle le spectacle\n\nKaibaman ?\n\n")
  LANGUAGE_TEXT(2, "Wartet Serenity nicht auf\ndich?\n\nSie ist bestimmt schon bei\nder Kaiba Corporation.\n\nWolltest du dir nicht die\nKaibaman Show mit ihr\n\nansehen?\n\n")
  LANGUAGE_TEXT(3, "Ma Serenity non ti\nsta aspettando?\n\nDovrebbe essere alla\nKaiba Corporation.\n\nNon dovevi vedere il\nKaibaman Show con lei?\n\n")
  LANGUAGE_TEXT(4, "\xbfNo te espera Serenity?\n\nDeber\xeda estar en la\nKaiba Corporation.\n\n\xbfNo estabas viendo el show\nde Kaibaman con ella?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
