#include "event_macros.h"
#include "overworld.h"

/* map_09_state_01: map 9 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E62160, map_09_state_01_08E62160, 0x08E6216C, 0x08E62178)
  PLAY_MUSIC(12)
  SET_FLAG(8)
  DELAY(32)
  PORTRAIT(PORTRAIT_TEA, 0, 0)
  LANGUAGE_TEXT(0, "Now I put this Monsta Card in\nhere, like so...\n\nAnd voila!\nI'm good to go!\n\n")
  LANGUAGE_TEXT(1, "Mets cette Carte Monstre,\ncomme \xe7a...\n\nOK ! Alors, tout est\npr\xeat, maintenant !\n\n")
  LANGUAGE_TEXT(2, "Leg diese Monsterkarte\nhier hinein, so...\n\nOkay!\nDas w\xe4re dann fertig!\n\n")
  LANGUAGE_TEXT(3, "Metti qui questa\nCarta Mostro, cos\xec...\n\nOkay! Allora \xe8 tutto a\nposto!\n\n")
  LANGUAGE_TEXT(4, "Pon esta Carta del\nMonstruo aqu\xed, as\xed...\n\n\xa1Vale! \xa1Todo est\xe1\npreparado ahora!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, how's adjustin'\nyour deck comin' along?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, comment tu\nt'en sors, avec ton Deck ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, wie l\xe4uft's mit\ndeiner\n\nDeckzusammenstellung?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, come va la\nsistemazione del tuo deck?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfqu\xe9 tal va\nla puesta a punto\n\nde tu deck?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Perfect\nLousy{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Parfait\nNul{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Perfekt\nMiserabel{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Benissimo\nMalissimo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Perfecto\nMal{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6216C, map_09_state_01_08E6216C, 0x08E62184, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "You sure about dat?\nLet the expert, the\n\none-and-only Joey Wheeler,\ncheck it out!\n\n")
  LANGUAGE_TEXT(1, "Dis donc, tu plaisantes ?\nAttends, fais-moi voir.\n\n")
  LANGUAGE_TEXT(2, "Hey, soll das ein Witz sein?\nZeig mal her.\n\n")
  LANGUAGE_TEXT(3, "Mi prendi in giro, per caso?\nDai, fammi vedere.\n\n")
  LANGUAGE_TEXT(4, "Eh, \xbfbromeas?\nVamos, d\xe9jame ver.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 16384)
  DELAY(16)
  PORTRAIT(4, 7, 0)
  LANGUAGE_TEXT(0, "Uh... It's cool to be\nconfident about your\n\nskills.\n\nBut you still have lots of\nwork to do on this Deck\n\nbefore it's any good.\n\n")
  LANGUAGE_TEXT(1, "C'est bien d'avoir\nconfiance en soi.\n\nMais ce Deck-l\xe0 est\nloin d'\xeatre parfait.\n\n")
  LANGUAGE_TEXT(2, "Selbstbewusstsein ist ja\nsch\xf6n und gut.\n\nAber an deinem Deck\nmusst du noch arbeiten.\n\n")
  LANGUAGE_TEXT(3, "Ehi, \xe8 bene sentirsi\nsicuri di s\xe9 stessi.\n\nMa questo deck deve\nancora essere migliorato\n\n")
  LANGUAGE_TEXT(4, "Hey, est\xe1 bien confiar\nen uno mismo.\n\nPero a este deck le\nqueda mucho a\xfan.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Hey,\ndon't feel bad. I know you\n\ncan construct an awesome\ndeck, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Mais bon, il y a\npire, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Hey, aber nimm es nicht so\nschwer, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "per andare bene. Non\ndemoralizzarti, per\xf2,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Hey, pero no te\ndeprimas, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62184, map_09_state_01_08E62184, 0x08E62190, 0x08E6219C)
  LANGUAGE_TEXT(0, "Alright guys, I'm gonna\ntotally rock with this\n\ndeck today!\n\nMan, I can't wait for the\nDuel Express train to come!\n\nIt's been too long since\nI've dueled in a\n\ntournament!\n\n{PLAYER} and Yugi and I are\ngonna own this tourney!\n\n")
  LANGUAGE_TEXT(1, "OK, mes amis, aujourd'hui,\nje vais assurer avec\n\nce Deck !\n\nH\xe9, je peux pas\nattendre le Duel Express.\n\nLe dernier tournoi de duels\nremonte \xe0 trop longtemps !\n\n{PLAYER} et Yugi,\nremportons ce tournoi !\n\n")
  LANGUAGE_TEXT(2, "O.k., Team, heute zeig ich's\nallen mit meinem Deck!\n\nHe, ich kann es gar nicht\nabwarten bis zum Duel\n\nExpress.\n\nEs ist schon lange her seit\ndem letzten Duellturnier!\n\n{PLAYER} und Yugi,\nstecken wir das Turnier\n\nin die Tasche!\n\n")
  LANGUAGE_TEXT(3, "Okay, gente, oggi far\xf2\nfaville con questo deck!\n\nMica posso aspettare il\ntreno Duel Express.\n\n\xc8 da troppo tempo che non\nsi fa un torneo di duelli!\n\n{PLAYER} e Yugi, questo\ntorneo sar\xe0 nostro!\n\n")
  LANGUAGE_TEXT(4, "Vale, panda, \xa1hoy me\nsobro con este deck!\n\nHeh, ans\xedo el tren\nDuel Express.\n\nHa pasado mucho desde\nel \xfaltimo torneo duelista.\n\n{PLAYER} y Yugi,\n\xa1ganemos este torneo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}By the way...\nLet's go for it!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Au fait...\nAllons-y !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}\xdcbrigens...\nPacken wir's an!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}A proposito...\nDiamoci dentro!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Por cierto...\n\xa1Ya es nuestro!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62190, map_09_state_01_08E62190, 0x08E621A8, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Huh, what's wrong? Oh yeah!\nWhere the heck's Yugi?\n\n")
  LANGUAGE_TEXT(1, "Au fait ? Ah, oui.\n\nPourquoi est-ce que\nYugi n'est pas encore l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "\xdcbrigens? Ach ja. Warum\nist Yugi noch nicht hier?\n\n")
  LANGUAGE_TEXT(3, "A proposito? Ah, gi\xe0. Come\nmai Yugi non \xe8 ancora qui?\n\n")
  LANGUAGE_TEXT(4, "\xbfPor cierto? Oh, s\xed.\n\xbfPor qu\xe9 no est\xe1 Yugi?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621A8, map_09_state_01_08E621A8, 0x08E621B4, 0x08E621C0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 1, 32, 0)
  MOVE_OBJECT(14, 3, 32, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  DELAY(8)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Oh man, this stinks!\nLook at the time already!\n\n")
  LANGUAGE_TEXT(1, "Oh non, c'est pas vrai !\nRegarde l'heure !\n\n")
  LANGUAGE_TEXT(2, "Oh Mann, das darf doch\nnicht wahr sein!\n\nHast du gesehen, wie\nsp\xe4t es schon ist?\n\n")
  LANGUAGE_TEXT(3, "Oh no, questa non ci\nvoleva! Il tempo stringe!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, t\xedo, qu\xe9 mal!\n\xa1Mira qu\xe9 hora es!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(8)
  PORTRAIT(4, 7, 0)
  LANGUAGE_TEXT(0, "He's late!\n\nC'mon Yugi...\nHow can ya even think\n\nabout being late on a day\nlike this!\n\nIf he doesn't get here\nsoon, we'll miss the Duel\n\nExpress!\n\nAnd he was the one who\npromised dat the three of\n\nus were gonna take the\ntrain together!\n\nMan, dat Yugi!\nArrrrgh!\n\nIf he doesn't get here, he\ncan give me all his rare\n\ncards and I still won't\nforgive him!\n\n")
  LANGUAGE_TEXT(1, "Il est en retard !\n\nAh, ce Yugi...\nToujours en retard !\n\nS'il ne se d\xe9p\xeache pas, on\nva louper le Duel Express !\n\nEst-ce qu'il a oubli\xe9\n\nqu'on devait prendre\nle train ensemble ?\n\nAh je vous jure, ce Yugi !\nPour se faire pardonner,\n\nil va lui falloir une carte\nsuper rare !\n\n")
  LANGUAGE_TEXT(2, "Er kommt zu sp\xe4t!\n\nDieser Yugi...\nEr ist viel zu sp\xe4t dran!\n\nWenn er sich nicht beeilt,\nist der Duel Express weg!\n\nWir wollten doch zusammen\nmit dem Zug fahren!\n\nMann, dieser Yugi!\nArrrrgh!\n\nEine seltene Karte allein\nmacht das nicht wett!\n\n")
  LANGUAGE_TEXT(3, "\xc8 in ritardo! Quello Yugi...\nHa troppo ritardo! Se non\n\nsi sbriga, perderemo il\nDuel Express! Si \xe8\n\ndimenticato che avevamo\npromesso di prendere il\n\ntreno insieme? Mannaggia\na Yugi! Arrrrgh!\n\nCi vorr\xe0 pi\xf9 di una carta\nrara per rimediare!\n\n")
  LANGUAGE_TEXT(4, "\xa1Llega tarde!\n\nEse Yugi...\n\xa1Llega muy tarde!\n\nSi no corre, \xa1perderemos\nel Duel Express!\n\n\xbfOlvid\xf3 nuestra promesa\nde coger el tren juntos?\n\nT\xedo, \xa1ese Yugi!\n\xa1Arrrrgh!\n\n\xa1Le va a costar m\xe1s de una\ncarta rara enmendar esto!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(212)
  SHOW_OBJECT(13, 50, 74, 0, 0, 0)
  MOVE_OBJECT(13, 2, 2, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  PORTRAIT(1, 6, 1)
  PLAY_MUSIC(400)
  LANGUAGE_TEXT(0, "{PLAYER}, everything's\nhorrible!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, un truc\ntr\xe8s grave est arriv\xe9 !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, hier stimmt\netwas nicht!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, c'\xe8\nqualcosa che non va!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xa1algo\nmalo pasa!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 1)
  DELAY(16)
  WALK_OBJECT_Y(13, 62)
  MOVE_OBJECT(13, 3, 8, 0)
  DELAY(16)
  PORTRAIT(1, 6, 1)
  LANGUAGE_TEXT(0, "My other self...\nThe Millennium Puzzle...\n\nMy Puzzle is gone, along\nwith the spirit inside!\n\n")
  LANGUAGE_TEXT(1, "L'autre moi...\nLe Puzzle du mill\xe9nium...\n\nLe Puzzle a disparu,\net mon autre moi aussi !\n\n")
  LANGUAGE_TEXT(2, "Mein anderes Ich...\nDas Millenniumspuzzle...\n\nDas Puzzle ist weg, und mit\nihm mein anderes Ich!\n\n")
  LANGUAGE_TEXT(3, "L'altro me stesso...\nIl Puzzle Millenario...\n\nIl Puzzle \xe8 sparito e con\nesso, l'altro me stesso!\n\n")
  LANGUAGE_TEXT(4, "Mi otro yo...\nEl Puzzle del Milenio...\n\nEl Puzzle se ha ido\n\xa1y mi otro yo con \xe9l!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 16385)
  DELAY(8)
  PORTRAIT(1, 3, 1)
  LANGUAGE_TEXT(0, "When I woke up this morning,\nit was gone...\n\nI... I... What am I\nsupposed to do?\n\n")
  LANGUAGE_TEXT(1, "Quand je me suis lev\xe9 ce\nmatin, il avait disparu...\n\nQu... Qu'est-ce que\nje vais faire ?\n\n")
  LANGUAGE_TEXT(2, "Als ich heute morgen\naufstand, war es fort...\n\nIch... Ich... Was\ngeschieht nur mit mir?\n\n")
  LANGUAGE_TEXT(3, "Quando mi sono alzato\nquesta mattina, era\n\nsparito... Io... Io...\nChe ne sar\xe0 di me?\n\n")
  LANGUAGE_TEXT(4, "Cuando despert\xe9 esta\nma\xf1ana se hab\xeda ido...\n\nYo... yo... \xbfQu\xe9 me\npasar\xe1 ahora?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  WALK_OBJECT_Y(14, 56)
  WALK_OBJECT_X(14, 58)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Hey, we can't waste time\nstandin' here and talkin'!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, pas la peine de\ns'apitoyer sur ton sort.\n\n")
  LANGUAGE_TEXT(2, "Hey, kein Grund deshalb\nTr\xfcbsal zu blasen.\n\n")
  LANGUAGE_TEXT(3, "Ehi, non serve a niente\nrattristarsi per questo.\n\n")
  LANGUAGE_TEXT(4, "Hey, no hay raz\xf3n\npara lloriquear.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, whattaya think\nwe should do?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, \xe0 ton avis,\nqu'est-ce qu'on doit\n\nfaire ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, was meinst\ndu, sollen wir tun?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, cosa pensi\nche dovremmo fare?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfqu\xe9 crees\nque debemos hacer?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Let's go look for it!\nLeave it to me!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Allons le chercher !\nLaissez-moi r\xe9gler \xe7a !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Gehen wir es suchen!\n\xdcberlasst das nur mir!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Partiamo alla ricerca!\nLasciate fare a me!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1A buscarle!\n\xa1Yo me encargo!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621B4, map_09_state_01_08E621B4, 0x08E621CC, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Okay! Then that's what\nwe're gonna do! You got\n\nit, Yugi?\n\n")
  LANGUAGE_TEXT(1, "OK ! C'est r\xe9gl\xe9, donc !\n\nArr\xeate de te plaindre,\nYugi !\n\n")
  LANGUAGE_TEXT(2, "Okay! Das w\xe4re also\nentschieden!\n\nGr\xe4m dich nicht mehr,\nYugi!\n\n")
  LANGUAGE_TEXT(3, "Okay!\nAllora intesi!\n\nSmettila di rattristarti,\nYugi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale! \xa1Arreglado!\n\xa1Deja de lloriquear, Yugi!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621CC, map_09_state_01_08E621CC, 0x08E621D8, 0x08F04040)
  PORTRAIT(1, 0, 1)
  LANGUAGE_TEXT(0, "I won't stop until I find my\ndearest friend...\n\nI promise!\n\nI'm counting on you,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je ne serais pas tranquille\ntant que je n'aurais pas\n\ntrouv\xe9 mon autre moi...\n\nJe compte sur toi,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich werde nicht ruhen, bis\nich mein anderes Ich\n\ngefunden habe.\n\nIch verlass mich auf dich,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Non mi fermer\xf2 finch\xe9\nnon avr\xf2 trovato l'altro\n\nme stesso... Conto su di\nte, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "No parar\xe9 hasta que\nd\xe9 con mi otro yo...\n\nCuento contigo,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621D8, map_09_state_01_08E621D8, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  WARP(1, 1, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621C0, map_09_state_01_08E621C0, 0x08E621CC, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Yeah! That's the spirit,\n{PLAYER}!\n\nYugi, let's go with\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "OK ! C'est le bon r\xe9flexe\n\xe0 adopter, {PLAYER} !\n\nYugi, accompagnons\n{PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Okay! Wohl gesprochen,\n{PLAYER}!\n\nYugi, gehen wir mit\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Okay! Cos\xec mi piaci,\n{PLAYER}!\n\nYugi, andiamo con\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale! \xa1As\xed se habla,\n{PLAYER}!\n\nYugi, \xa1vamos con\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6219C, map_09_state_01_08E6219C, 0x08E621A8, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "Yeah! But don't think I'm\ngonna let you win\n\n{PLAYER}. And that goes\ndouble for Yugi.\n\nSpeaking of who...\nWhy isn't Yugi here yet?\n\n")
  LANGUAGE_TEXT(1, "Ouais, je ne vais pas te\nlaisser gagner {PLAYER}\n\net pareil pour Yugi.\nH\xe9, mais au fait...\n\nPourquoi est-ce que Yugi\nn'est pas encore l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Keine Chance! Ich lass dich\nnicht gewinnen, {PLAYER},\n\nund das gilt auch f\xfcr Yugi.\n\nAber warte mal.\nWo steckt Yugi eigentlich?\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0! Non ti far\xf2 vincere,\n{PLAYER}, e nemmeno\n\nYugi. Ehi, un momento. Come\nmai Yugi non \xe8 ancora qui?\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed! No te dejar\xe9 ganar,\n{PLAYER}, como a Yugi.\n\nHey, un momento...\n\xbfPor qu\xe9 no est\xe1 Yugi?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62178, map_09_state_01_08E62178, 0x08E62184, 0x08F04040)
  PORTRAIT(4, 0, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, I guess ya still\nhave lots of work to do.\n\nBut you can learn from the\nexpert, the one-and-only\n\nJoey Wheeler, on making\ngreat decks.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu as\ndes progr\xe8s \xe0 faire.\n\nPrends exemple sur\nmoi, Joey Wheeler,\n\npour r\xe9aliser\nde super Decks.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du musst noch\neiniges lernen.\n\nPass auf, wie ich Joey\nWheeler tolle Decks\n\nzusammenstelle.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, scommetto\nche hai ancora un bel\n\npo' da fare. Impara da me,\nJoey Wheeler, come si\n\nfa a realizzare deck\neccezionali.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, creo que te\nqueda mucho por hacer.\n\nAprende de m\xed, Joey\nWheeler, sobre c\xf3mo\n\nhacer buenos decks.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62154, map_09_state_01_08E62154, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(0)
  CUTSCENE(8)
  WARP(9, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
