#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_09: map 23 state 9 */

LOAD_SPRITE(1, SPRITE_BANDIT_KEITH)
LOAD_SPRITE(2, SPRITE_ISHIZU)
LOAD_SPRITE(3, SPRITE_ATEM)
LOAD_SPRITE(4, SPRITE_PARA)
LOAD_SPRITE(5, SPRITE_VIDEO_CARD)
LOAD_SPRITE(6, SPRITE_MILLENNIUM_PUZZLE)
LOAD_SPRITE(7, SPRITE_MILLENNIUM_PUZZLE_PART_1)
LOAD_SPRITE(8, SPRITE_MILLENNIUM_PUZZLE_PART_3)
LOAD_SPRITE(9, SPRITE_MILLENNIUM_PUZZLE_PART_2)
LOAD_SPRITE(10, SPRITE_MILLENNIUM_PUZZLE_PART_2)
DELAY(16)
MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_218)
LOAD_SPRITE(13, SPRITE_ATEM)
DELAY(64)
WALK_OBJECT_Y(13, 50)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "You'll pay for how you\n"
    "treated my partner, Bandit\n\n"
    "Keith!\n\n"
)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Huh? What are you talking\n"
    "about?\n\n"
    "Just fork over your Egyptian\n"
    "God Card!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "So you don't care what\n"
    "happens to this woman?\n\n"
)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, it's clear you are\n"
    "a true duelist.\n\n"
    "The Egyptian God Cards\n"
    "choose who controls them...\n\n"
    "And you haven't earned the\n"
    "privilege!\n\n"
)
PLAY_MUSIC(MUSIC_347)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPHERE_RA_BLINK_IN)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Wh-what's this?!\n\n"
)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "It's Ra's judgment...\n"
    "Actually, it's more than\n\n"
    "that.\n\n"
    "Feel the wrath for angering\n"
    "the Egyptian Gods!\n\n"
)
PLAY_MUSIC(MUSIC_359)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_ENTERS_BATTLE_MODE)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_TRANSFORMS_TO_PHOENIX_MODE)
PLAY_MUSIC(MUSIC_348)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPARKLE_FLOATS_UP)
PLAY_MUSIC(MUSIC_302)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Gwaaah!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_303)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 58, 38, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_205)
OBJECT_EFFECT(SPRITE_BANDIT_KEITH, OBJECT_EFFECT_DISAPPEAR)
DELAY(32)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Ra's judgment...\n\n"
    "Even though he brought it\n"
    "upon himself...\n\n"
    "I cannot help to feel sad\n"
    "for the horrible punishment\n\n"
    "he received...\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
WALK_OBJECT_X(SPRITE_ISHIZU, 58)
WALK_OBJECT_Y(SPRITE_ISHIZU, 28)
DELAY(16)
PLAY_MUSIC(MUSIC_285)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 128, 96, 0, 0, 0)
DELAY(16)
WALK_OBJECT_X(0, 54)
WALK_OBJECT_Y(0, 40)
WALK_OBJECT_Y(14, 50)
WALK_OBJECT_X(14, 46)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
WALK_OBJECT_Y(13, 50)
WALK_OBJECT_X(13, 62)
MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
DELAY(16)
WALK_OBJECT_X(SPRITE_ISHIZU, 54)
WALK_OBJECT_Y(SPRITE_ISHIZU, 30)
DELAY(16)
PLAY_MUSIC(MUSIC_285)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 54, 32, 0, 0, 0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, take control of\n"
    "the Egyptian God Cards.\n\n"
    "You have earned the right.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
DELAY(8)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_POSITION_AUTO,
    "I know exactly how hard\n"
    "{PLAYER} has worked to get\n\n"
    "this far.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_POSITION_AUTO,
    "{PLAYER} is worthy of having\n"
    "the Egyptian God Cards.\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Heheh, I hate to admit it,\n"
    "but I gotta agree.\n\n"
    "{PLAYER}, you're an awesome\n"
    "duelist.\n\n"
)
HIDE_PORTRAIT()
DELAY(64)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(64)
PLAY_MUSIC(MUSIC_285)
ADD_CARD(297)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 128, 96, 0, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_290)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPHERE_RA_REVIVED)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Way to go, {PLAYER}.\n\n"
)
TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "Received The Winged Dragon\n"
    "of Ra {BYTE_8169}Sphere Mode{BYTE_816A}.\n\n"
)
PLAY_MUSIC(MUSIC_267)
SCREEN_SHAKE(16)
PLAY_MUSIC(MUSIC_408)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Please wait... I sense\n"
    "something...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_306)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RESHEF_TAKES_CONTROL_OF_KEITH)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO,
    "I feel the Dark Being\n"
    "summoning a vile spirit...\n\n"
    "No!\n\n"
    "The spirit is flooding into\n"
    "the hearts of defeated\n\n"
    "duelists!\n\n"
    "Reshef's will is taking\n"
    "control of their souls!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_307)
MOVE_OBJECT(SPRITE_BANDIT_KEITH, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(SPRITE_BANDIT_KEITH, 62, 40, 0, 3, 0)
DELAY(16)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(0, 1, 6)
SLIDE_OBJECT(13, 0, 6)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Gwehehehe!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Reshef the Dark Being has\n"
    "him under control.\n\n"
    "Dueling Bandit Keith now is\n"
    "too dangerous!\n\n"
)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO,
    "You...\n\n"
    "Give it to me!\n\n"
)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | OBJECT_13 | OBJECT_14)
WALK_OBJECT_Y(0, 48)
WALK_OBJECT_X(0, 66)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
WALK_OBJECT_Y(14, 48)
WALK_OBJECT_X(14, 58)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(0, 3, 10)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(14, 1, 10)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_BANDIT_KEITH, DIRECTION_DOWN, 6, 0)
PLAY_MUSIC(MUSIC_308)
SLIDE_OBJECT(13, 0, 2)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 62, 50, 0, 0, 0)
DELAY(16)
SLIDE_OBJECT(13, 2, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 2, 2)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 2)
DELAY(16)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 0, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 0, 2)
SLIDE_OBJECT(13, 0, 2)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "Wh-what are you doing,\n"
    "Bandit Keith?\n\n"
)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO,
    "Gwehehehehehe!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
SLIDE_OBJECT(13, 2, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 2, 2)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 2)
DELAY(8)
SLIDE_OBJECT(13, 0, 2)
DELAY(16)
PLAY_MUSIC(SOUND_NONE)
PLAY_MUSIC(MUSIC_309)
LOAD_SPRITE(6, SPRITE_SMALL_RUBBLE)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_1, 55, 42, 0, 0, 0)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_3, 69, 42, 0, 0, 0)
SHOW_OBJECT(9, 76, 42, 0, 0, 0)
SHOW_OBJECT(10, 76, 52, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | OBJECT_13 | OBJECT_14)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 12)
DELAY(8)
PLAY_MUSIC(MUSIC_205)
OBJECT_EFFECT(SPRITE_BANDIT_KEITH, OBJECT_EFFECT_DISAPPEAR)
DELAY(8)
LOAD_SPRITE(13, SPRITE_YUGI)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Waaaaaaah!\n\n"
    "M-my other self! The\n"
    "Millennium Puzzle!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_SMALL_RUBBLE, 128, 96, 0, 0, 0)
DELAY(8)
WALK_OBJECT_Y(SPRITE_YUGI, 44)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_LEFT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_1, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_RIGHT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_3, 128, 96, 0, 0, 0)
DELAY(8)
WALK_OBJECT_X(SPRITE_YUGI, 68)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(9, 128, 96, 0, 0, 0)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_POSITION_AUTO,
    "My friend... I'll save\n"
    "you...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_311)
PLAY_MUSIC(MUSIC_404)
SHOW_OBJECT(SPRITE_PARA, 20, 74, 0, 2, 0)
PLAY_MUSIC(MUSIC_312)
DELAY(16)
TALK(PORTRAIT_PARA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "Fufufu... This is amusing.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
LOAD_SPRITE(4, SPRITE_PARA_FLIPPING)
WALK_OBJECT_X(SPRITE_PARA_FLIPPING, 76)
LOAD_SPRITE(4, SPRITE_PARA)
WALK_OBJECT_Y(SPRITE_PARA, 64)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(10, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | SPRITE_YUGI | OBJECT_14)
DELAY(8)
WALK_OBJECT_Y(SPRITE_PARA, 74)
MOVE_OBJECT(SPRITE_PARA, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, PORTRAIT_RIGHT,
    "These puzzle pieces make a\n"
    "fine souvenir!\n\n"
    "If you want them, come to\n"
    "Master Chevalsky's castle.\n\n"
    "Fwahahahaha!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
LOAD_SPRITE(4, SPRITE_PARA_FLIPPING)
WALK_OBJECT_X(SPRITE_PARA_FLIPPING, 20)
LOAD_SPRITE(4, SPRITE_PARA)
WALK_OBJECT_Y(SPRITE_PARA, 96)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)
DELAY(16)
WALK_OBJECT_Y(SPRITE_YUGI, 50)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_POSITION_AUTO,
    "This can't be happening...\n"
    "The puzzle pieces...\n\n"
    "What's going to happen to\n"
    "him...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(0, 68)
WALK_OBJECT_Y(0, 42)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_YUGI)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You're right! Let's go to\n"
    "Pegasus's castle.\n\n"
    "Wait for me, my friend...\n\n"
)
SET_FLAG(EVENT_FLAG_DEFEATED_BANDIT_KEITH)

EVENT_SCRIPT_REPLACEMENT(0x08E95450, map_23_state_09_08E95450, 0x08E9545C, 0x08F04040)
PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_13)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Y-you're right...\n\n"
    "I don't have the time to\n"
    "feel sorry for myself.\n\n"
    "Wait for me, my friend...\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95414, map_23_state_09_08E95414, 0x08E95420, 0x08F04040)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You mustn't!\n\n"
    "Reshef the Dark Being has\n"
    "him under control.\n\n"
    "Dueling Bandit Keith now is\n"
    "too dangerous!\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E953CC, map_23_state_09_08E953CC, 0x08E953D8, 0x08F04040)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, it's tough, but\n"
    "that's the right decision.\n\n"
)
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Hurry up! Hand it over!\n\n"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()
