#include "event_macros.h"
#include "overworld.h"

/* map_22_state_01: map 22 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CAB0, map_22_state_01_08E8CAB0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Here sleeps the power of\nancient pharaohs.\n\nI know that ancient power\nwill make me stronger!\n\nI will become a guardian of\ndarkness...\n\nAs long as the pharaohs give\nme power!\n\n")
  LANGUAGE_TEXT(1, "C'est ici que le pouvoir\ndes pharaons est enseveli.\n\nCette puissance va\nme rendre plus fort !\n\nIci, je deviendrai\nle gardien des t\xe9n\xe8bres...\n\nTant que les anciens me\nconf\xe8reront leurs\n\npouvoirs !\n\n")
  LANGUAGE_TEXT(2, "Die Macht der alten\nPharaonen ruht hier.\n\nDiese alte Kraft wird mich\nsicher st\xe4rken!\n\nIch werde hier der H\xfcter der\nFinsternis werden...\n\nSolange mir die Pharaonen\nMacht schenken!\n\n")
  LANGUAGE_TEXT(3, "Qui riposa il potere\ndegli antichi faraoni.\n\nQuell'antico potere mi\nrafforzer\xe0 di certo!\n\nQui diventer\xf2 un custode\ndell'oscurit\xe0...\n\nPurch\xe9 gli antichi\nmi diano il potere!\n\n")
  LANGUAGE_TEXT(4, "Aqu\xed reposa el poder\nde los antiguos faraones.\n\nSeguro que ese antiguo poder\nme har\xe1 m\xe1s fuerte.\n\nAqu\xed ser\xe9 un guardi\xe1n\nde la oscuridad...\n\n\xa1Siempre que los\nantiguos me den poder!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CABC, map_22_state_01_08E8CABC, 0x08E8CAC8, 0x08E8CAE0)
  CHECK_FLAG(91)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CAC8, map_22_state_01_08E8CAC8, 0x08E8CAD4, 0x08F0404C)
  LANGUAGE_TEXT(0, "I'm most worthy of being a\nguardian of darkness.\n\nAs such, this place is the\nmost suitable location for\n\nmy abilities!\n\nThere is no way I can lose!\n\n")
  LANGUAGE_TEXT(1, "Je suis digne d'\xeatre\nle gardien des t\xe9n\xe8bres.\n\nEt cet endroit\nest digne de moi !\n\nJe ne risque donc pas\nde perdre !\n\n")
  LANGUAGE_TEXT(2, "Ich trage W\xfcrde als H\xfcter\nder Dunkelheit.\n\nUnd dieser Ort ist f\xfcr mich\nam w\xfcrdevollsten!\n\nIch kann unm\xf6glich\nverlieren!\n\n")
  LANGUAGE_TEXT(3, "Me lo merito di essere un\ncustode dell'oscurit\xe0.\n\nE questo \xe8 il posto pi\xf9\nadatto a me!\n\nNon hai scampo: io\nnon perder\xf2 di certo!\n\n")
  LANGUAGE_TEXT(4, "Soy digno como guardi\xe1n\nde la oscuridad.\n\nY este lugar es el\nque me corresponde.\n\n\xa1No hay posibilidad\nde que pierda!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(30)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CAD4, map_22_state_01_08E8CAD4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(230)
  LANGUAGE_TEXT(0, "I lost? B-but how?\n\n")
  LANGUAGE_TEXT(1, "J'ai perdu ?\nM-mais comment ?\n\n")
  LANGUAGE_TEXT(2, "Ich habe verloren?\nA-aber wie?\n\n")
  LANGUAGE_TEXT(3, "Ho perso?! Ma\ncome \xe8 possibile?\n\n")
  LANGUAGE_TEXT(4, "\xbfHe perdido?\n\xbfP-pero c\xf3mo?\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(91)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CAE0, map_22_state_01_08E8CAE0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Wh-where can I win?\n\n")
  LANGUAGE_TEXT(1, "O\xf9... o\xf9 dois-je aller\npour gagner ?\n\n")
  LANGUAGE_TEXT(2, "W-wo kann ich denn\n\xfcberhaupt gewinnen?\n\n")
  LANGUAGE_TEXT(3, "Dove potr\xf2 mai vincere?\n\n")
  LANGUAGE_TEXT(4, "\xbfD-d\xf3nde ganar\xe9?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CAEC, map_22_state_01_08E8CAEC, 0x08E8CAF8, 0x08E8CB04)
  CHECK_FLAG(92)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CAF8, map_22_state_01_08E8CAF8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Did a dark, big guy come\nthis way?\n\nWell, yes...\n\n")
  LANGUAGE_TEXT(1, "Est-ce qu'un grand brun\nhabill\xe9 en noir est pass\xe9\n\npar l\xe0 ?\n\nEh bien, oui...\n\n")
  LANGUAGE_TEXT(2, "Ist hier ein dunkler H\xfcne\nvorbeigekommen?\n\n\xc4h, ja...\n\n")
  LANGUAGE_TEXT(3, "Un tipo grande, in scuro,\nche \xe8 passato da qui?\n\nBe', s\xec...\n\n")
  LANGUAGE_TEXT(4, "\xbfHa pasado un tipo grande y oscuro por aqu\xed?\n\nBueno, s\xed...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 16, 0)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "He ran down the stairs here.\n\n")
  LANGUAGE_TEXT(1, "Il est parti en descendant\npar ces escaliers-l\xe0.\n\n")
  LANGUAGE_TEXT(2, "Er ging hier die Treppe\nhinunter.\n\n")
  LANGUAGE_TEXT(3, "\xc8 sceso da queste scale.\n\n")
  LANGUAGE_TEXT(4, "Sali\xf3 por las escaleras\nde aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(92)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB04, map_22_state_01_08E8CB04, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The big man took off down\nthe stairs here.\n\n")
  LANGUAGE_TEXT(1, "Le grand type est parti\nen descendant par\n\nces escaliers-l\xe0.\n\n")
  LANGUAGE_TEXT(2, "Der gro\xdfe Mann ging hier\ndie Treppe hinunter.\n\n")
  LANGUAGE_TEXT(3, "L'omone \xe8 sceso per\nqueste scale.\n\n")
  LANGUAGE_TEXT(4, "El grandull\xf3n sali\xf3 por las\nescaleras de aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CB10, map_22_state_01_08E8CB10, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, I don't duel. You should\nfind someone else.\n\n")
  LANGUAGE_TEXT(1, "Non, je ne me bats\npas en duel.\n\nTrouve quelqu'un\nd'autre.\n\n")
  LANGUAGE_TEXT(2, "Nein, ich duelliere mich\nnicht.\n\nSuch dir einen anderen.\n\n")
  LANGUAGE_TEXT(3, "No, io non duello. Dovresti\ntrovare qualcun altro.\n\n")
  LANGUAGE_TEXT(4, "No, no lucho. Busca\na otro para eso.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
