#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_41_state_01: map 41 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED7BDC, map_41_state_01_08ED7BDC, 0x08ED7BE8, 0x08ED7BF4)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  LOAD_SPRITE(2, SPRITE_CHEVALIER)
  LOAD_SPRITE(3, SPRITE_CHEVALIER)
  PLAY_MUSIC(MUSIC_253)
  DELAY(16)
  SHOW_OBJECT(0, 58, 62, 0, 0, 0)
  WALK_OBJECT_Y(0, 50)
  DELAY(8)
  SHOW_OBJECT(13, 66, 62, 0, 0, 0)
  WALK_OBJECT_Y(13, 56)
  DELAY(8)
  SHOW_OBJECT(14, 50, 62, 0, 0, 0)
  WALK_OBJECT_Y(14, 56)
  DELAY(64)
  PLAY_MUSIC(MUSIC_255)
  SET_FLAG(EVENT_FLAG_SHAKE_SCREEN_AND_MOVE_BACKGROUND)
  DELAY(64)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_14)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SAD, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "That Pegasus...\n\n"
      "What drove him to do this?\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TEXT
  (
      "{CARD_1}I don't know\n"
      "We'll know if we go{CARD_2}\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7BE8, map_41_state_01_08ED7BE8, 0x08ED7C00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Yeah, I'm with you,\n"
      "{PLAYER}.\n\n"
      "I have no clue what Pegasus\n"
      "is thinkin'.\n\n"
      "He's one mad sicko, but...\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C00, map_41_state_01_08ED7C00, 0x08ED7C0C, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Pegasus was always a master\n"
      "duelist.\n\n"
      "No one would argue with\n"
      "that.\n\n"
      "Especially since we faced\n"
      "him firsthand.\n\n"
      "So why would he resort to\n"
      "even dirtier tricks than\n\n"
      "before?\n\n"
      "I'm not the smartest guy on\n"
      "the planet...\n\n"
      "But I know that Pegasus\n"
      "isn't a real duelist\n\n"
      "anymore!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_258)
  PLAY_MUSIC(MUSIC_412)
  SCREEN_SHAKE(1)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_259)
  SHOW_OBJECT(1, 40, 54, 0, 2, 0)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C0C, map_41_state_01_08ED7C0C, 0x08ED7C18, 0x08ED7CF0)
  PLAY_MUSIC(MUSIC_260)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "Gawry nida! Gawry nida!\n\n"
      "You'll go no further! Gawry!\n\n"
  )
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Wha... Who are you?\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "I am one of many! Gawry!\n\n"
      "Master Chevalsky turned us\n"
      "into duelists! Gawry!\n\n"
      "We no longer have no names!\n"
      "Gawry nida!\n\n"
      "But if you must call us\n"
      "something, call us the\n\n"
      "Chevaliers!\n\n"
      "We have pledged allegiance\n"
      "to Master Chevalsky!\n\n"
  )
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "That Pegasus... He's really\n"
      "annoyin' me now!\n\n"
      "{PLAYER}, it's time to lay\n"
      "down the law!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 50)
  WALK_OBJECT_X(1, 48)
  DELAY(16)
  PLAY_MUSIC(SOUND_NONE)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C18, map_41_state_01_08ED7C18, 0x08ED7C24, 0x08F04040)
  PLAY_MUSIC(MUSIC_253)
  PLAY_MUSIC(MUSIC_257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "G-gawry nida... G-ga..\n"
      "n-niii.... urrri...\n\n"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  DELAY(32)
  PLAY_MUSIC(MUSIC_258)
  SCREEN_SHAKE(1)
  DELAY(16)
  PLAY_MUSIC(MUSIC_258)
  SCREEN_SHAKE(1)
  DELAY(8)
  PLAY_MUSIC(MUSIC_259)
  SHOW_OBJECT(2, 76, 42, 0, 2, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_259)
  SHOW_OBJECT(3, 46, 36, 0, 2, 0)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C24, map_41_state_01_08ED7C24, 0x08ED7C30, 0x08ED7CF0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_260)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "Gawry nida! Gawry nida!\n\n"
      "You'll go no further! Gawry!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 50)
  WALK_OBJECT_X(2, 68)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C30, map_41_state_01_08ED7C30, 0x08ED7C3C, 0x08F04040)
  PLAY_MUSIC(MUSIC_253)
  PLAY_MUSIC(MUSIC_257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT
  (
      "G-gawry nida... G-ga..\n"
      "n-niii.... urrri...\n\n"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C3C, map_41_state_01_08ED7C3C, 0x08ED7C48, 0x08ED7CF0)
  DELAY(32)
  PLAY_MUSIC(MUSIC_260)
  OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_JUMPING)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "Gawry nida! Gawry nida!\n\n"
      "You'll go no further! Gawry!\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 58)
  WALK_OBJECT_Y(3, 42)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  DELAY(16)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C48, map_41_state_01_08ED7C48, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_253)
  PLAY_MUSIC(MUSIC_257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT
  (
      "G-gawry nida... G-ga..\n"
      "n-niii.... urrri...\n\n"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_TELEPORT)
  DELAY(64)
  PLAY_MUSIC(MUSIC_256)
  CLEAR_FLAG(246)
  DELAY(96)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Looks like it's stopped.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Let's keep going, {PLAYER}.\n\n"
  )
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(13, 62)
  SHOW_OBJECT(13, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_Y(14, 62)
  SHOW_OBJECT(14, 128, 96, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 62)
  SHOW_OBJECT(0, 128, 96, 0, 0, 0)
  FADE_SCREEN(1)
  CLEAR_FLAG(180)
  SET_FLAG(EVENT_FLAG_DEFEATED_ALL_CABLE_CAR_CHEVALIERS_ONCE)
  WARP(LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7CF0, map_41_state_01_08ED7CF0, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(180)
  CLEAR_FLAG(246)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7BF4, map_41_state_01_08ED7BF4, 0x08ED7C00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "And ask him personally?\n\n"
      "I don't know much about\n"
      "savin' the world, but I\n\n"
      "wanna know why Pegasus lost\n"
      "his pride as a true\n\n"
      "duelist.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
