#include "event_macros.h"
#include "overworld.h"

/* map_12_state_01: map 12 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E6EF64, map_12_state_01_08E6EF64, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This is Kaiba Corporation.\nThis is not a place for\n\ncivilians.\n\n")
  LANGUAGE_TEXT(1, "Ceci est la\nKaiba Corporation.\n\nL'entr\xe9e est interdite\nau public.\n\n")
  LANGUAGE_TEXT(2, "Hier ist die Kaiba\nCorporation.\n\nKein Zugang f\xfcr Zivilisten.\n\n")
  LANGUAGE_TEXT(3, "Questa \xe8 la Kaiba\nCorporation. Non\n\n\xe8 un luogo per i civili.\n\n")
  LANGUAGE_TEXT(4, "Esto es Kaiba Corporation.\nNo es lugar para civiles.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF70, map_12_state_01_08E6EF70, 0x08E6EF7C, 0x08E6EF94)
  CHECK_FLAG(39)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF7C, map_12_state_01_08E6EF7C, 0x08E6EF88, 0x08F0404C)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Duel? No, that is not\npermitted on these\n\npremises.\n\n...Is what I'm ordered to\nsay.\n\n")
  LANGUAGE_TEXT(1, "Un duel ? Non, non.\nC'est interdit.\n\n... C'est ce que\nje suis suppos\xe9 dire.\n\n")
  LANGUAGE_TEXT(2, "Duell?\nNein, nicht gestattet.\n\n... Jedenfalls soll ich\ndas sagen.\n\n")
  LANGUAGE_TEXT(3, "Duellare? No, no.\nNon \xe8 permesso.\n\n... \xc8 quello che sono\ntenuto a dire.\n\n")
  LANGUAGE_TEXT(4, "\xbfDuelo?\nNo, no. No se permiten.\n\n... se supone que eso\nes lo que he de decir.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But I always wanted to play\nto see what it's like.\n\nLet's duel!\n\n")
  LANGUAGE_TEXT(1, "Mais j'aimerais bien\naussi m'amuser un peu.\n\nAllez, un duel !\n\n")
  LANGUAGE_TEXT(2, "Aber ich wollte es doch\neinmal selbst erleben.\n\nDuell!\n\n")
  LANGUAGE_TEXT(3, "Ma vorrei giocare solo\nuna volta, per vedere.\n\nDuelliamo!\n\n")
  LANGUAGE_TEXT(4, "Pero yo quiero luchar\nuna vez para ver.\n\n\xa1Luchemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(12)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF88, map_12_state_01_08E6EF88, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hmm... I think Mr. Kaiba is\nbetter at this than I am.\n\n")
  LANGUAGE_TEXT(1, "Mmm... Eh bien, je ne suis\npas aussi bon que M. Seto.\n\n")
  LANGUAGE_TEXT(2, "Hrmm... Ich bin wohl doch\nnicht so gut wie Herr Seto.\n\n")
  LANGUAGE_TEXT(3, "Hmm... A quanto\npare, in questo non\n\nsono come il signor Seto.\n\n")
  LANGUAGE_TEXT(4, "Hrmm... Creo que no soy\ncomo el Sr. Seto en esto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(39)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6EF94, map_12_state_01_08E6EF94, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No, no. Not again!\n\nIf Mr. Kaiba catches me,\nI'll be fired on the spot!\n\n")
  LANGUAGE_TEXT(1, "Non, non.\nPas cette fois !\n\nSi M. Seto me voit,\n\nil va me renvoyer\nsur-le-champ.\n\n")
  LANGUAGE_TEXT(2, "Nein, nein. Nicht jetzt!\nWenn mich Herr Seto er-\n\nwischt, entl\xe4sst er mich\nauf der Stelle.\n\n")
  LANGUAGE_TEXT(3, "No, no, non questa volta!\nSe mi becca il signor\n\nSeto, mi licenzia in\nquattro e quattr'otto.\n\n")
  LANGUAGE_TEXT(4, "No, no.\n\xa1Ahora no!\n\nSi el Sr. Seto me\npilla, me despide.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
