#include "event_macros.h"
#include "overworld.h"

/* map_15_state_03: map 15 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E7A5B4, map_15_state_03_08E7A5B4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I heard a most remarkable\nthing today.\n\nAn express train was\nchartered solely for\n\ndueling!\n\nSome people have the oddest\nideas, I daresay.\n\n")
  LANGUAGE_TEXT(1, "J'ai entendu un truc\nincroyable aujourd'hui.\n\nUn train express aurait\n\xe9t\xe9 affr\xe9t\xe9 pour un duel !\n\nAh vraiment, les gens\nont de ces id\xe9es !\n\n")
  LANGUAGE_TEXT(2, "Heute habe ich etwas sehr\nBemerkenswertes geh\xf6rt.\n\nEin Charterzug bef\xf6rdert\nDuellanten!\n\nManche kommen auf die merk-\nw\xfcrdigsten Dinge.\n\n")
  LANGUAGE_TEXT(3, "Oggi ho sentito una\ncosa incredibile.\n\nPer duellare \xe8 stato\nusato un treno espresso\n\nspeciale! Certa gente ha\nstrane idee, oserei dire.\n\n")
  LANGUAGE_TEXT(4, "Hoy he o\xeddo algo\ninteresante.\n\nSe utiliz\xf3 un tren\nch\xe1rter para duelos.\n\nCreo que hay gente\ncon ideas raras.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5C0, map_15_state_03_08E7A5C0, 0x08E7A5CC, 0x08E7A5E4)
  CHECK_FLAG(55)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5CC, map_15_state_03_08E7A5CC, 0x08E7A5D8, 0x08F0404C)
  LANGUAGE_TEXT(0, "A duel? With me?\n\nI do hope you don't under-\nestimate me as an amateur.\n\n")
  LANGUAGE_TEXT(1, "Un duel ?\nAvec moi ?\n\nTu ne me prendrais\npas pour un amateur ?\n\n")
  LANGUAGE_TEXT(2, "Ein Duell?\nMit mir?\n\nIch hoffe, du h\xe4ltst mich\nnicht f\xfcr einen Amateur.\n\n")
  LANGUAGE_TEXT(3, "Un duello?\nCon me?\n\nNon penserai mica che\nsono un dilettante?\n\n")
  LANGUAGE_TEXT(4, "\xbfUn duelo?\n\xbfConmigo?\n\nEspero que no me\nsubestimes como\n\nprincipiante.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(22)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5D8, map_15_state_03_08E7A5D8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "You're none too shabby.\n\nWe shall match wits again on\nthe train.\n\n")
  LANGUAGE_TEXT(1, "Tu n'es pas\nsi mauvais.\n\nOn s'affrontera encore\nune fois \xe0 bord du train.\n\n")
  LANGUAGE_TEXT(2, "Gar nicht so \xfcbel.\n\nIm Zug k\xf6nnen wir noch ein-\nmal unsere Kr\xe4fte messen.\n\n")
  LANGUAGE_TEXT(3, "Non sei affatto male.\n\nCi batteremo di\nnuovo sul treno.\n\n")
  LANGUAGE_TEXT(4, "No eres muy malo.\n\nVolveremos a vernos\nlas caras en el tren.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(55)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5E4, map_15_state_03_08E7A5E4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "We shall match wits again on\nthe train.\n\n")
  LANGUAGE_TEXT(1, "On s'affrontera encore\nune fois \xe0 bord du train.\n\n")
  LANGUAGE_TEXT(2, "Im Zug k\xf6nnen wir noch ein-\nmal unsere Kr\xe4fte messen.\n\n")
  LANGUAGE_TEXT(3, "Ci batteremo di\nnuovo sul treno.\n\n")
  LANGUAGE_TEXT(4, "Volveremos a vernos\nlas caras en el tren.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
