#include "event_macros.h"
#include "overworld.h"

/* map_12_state_11: map 12 state 11 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F168, map_12_state_11_08E6F168, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  LOAD_SPRITE(2, SPRITE_MOKUBA)
  LOAD_SPRITE(3, SPRITE_BIG_FIVE)
  LOAD_SPRITE(4, SPRITE_BIG_FIVE)
  LOAD_SPRITE(5, SPRITE_BIG_FIVE)
  LOAD_SPRITE(6, SPRITE_BIG_FIVE)
  LOAD_SPRITE(7, SPRITE_BIG_FIVE)
  PLAY_MUSIC(MUSIC_KAIBACORP)
  TEXT("M-master Mokuba...\n\nPlease, please give us one\nmore chance.\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, PORTRAIT_POSITION_AUTO)
  TEXT("After all the horrible\nthings you've done to us?\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I know we were wrong. But...\n\nTimes are tough. No one has\nany money!\n\nWe want to work, but no\none's hiring.\n\nPlease, we're begging you to\nrehire us.\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Well... I guess I have\nsomething for you...\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("R-really?\n\nOh, thank you!\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("All right. Quick, get\nchanged.\n\n")
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, 248)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Where's Serenity?\n\n")
  FADE_SCREEN(4)
  WARP(57, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
