#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_06: map 6 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CCC0, map_06_state_06_08E5CCC0, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_TRISTAN)
  LOAD_SPRITE(2, SPRITE_DUKE)
  LOAD_SPRITE(3, SPRITE_SERENITY)
  LOAD_SPRITE(4, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(5, SPRITE_LUCKY)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  DELAY(8)
  WALK_OBJECT_X(4, 52)
  DELAY(8)
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, PORTRAIT_RIGHT, "Eeek!")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, PORTRAIT_RIGHT, "Hey! What do you think you're doing to Serenity?")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "I'll protect you, Serenity!")
  WALK_OBJECT_X(1, 52)
  WALK_OBJECT_X(2, 52)
  WALK_OBJECT_X(4, 64)
  MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_Y(1, 44)
  WALK_OBJECT_X(1, 56)
  WALK_OBJECT_Y(2, 52)
  WALK_OBJECT_X(2, 56)
  DELAY(16)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Tsk...")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 144)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Are you okay, Serenity?")
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Yes, I'm fine, Tristan.",
      "And Duke, thank you too."
  )
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "You can count on me, Serenity.",
      "I won't let the Neo Ghouls lay a finger on you."
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "That goes double for me!")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "It's okay Tristan. Serenity's safe in my arms.",
      "She doesn't need you."
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_RIGHT, "Devlin, you...")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_3)
  DELAY(8)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Oh, hi {PLAYER}.")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1 | OBJECT_2)
  DELAY(16)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 82)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 82)
  DELAY(16)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_RIGHT, "{PLAYER}, you don't have to worry about us.")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Yeah, I'll protect Serenity.")
  SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DRIVE_AWAY_A_GHOUL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCCC, map_06_state_06_08E5CCCC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, Serenity's safe with me. I can't say the",
      "same about loverboy over there...",
      "The Neo Ghouls don't scare me one bit."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCD8, map_06_state_06_08E5CCD8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "What? You don't have the time to duel me!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCE4, map_06_state_06_08E5CCE4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{PLAYER}, let's drive the Neo Ghouls out of town!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCF0, map_06_state_06_08E5CCF0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I don't think we have any time to spare.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCFC, map_06_state_06_08E5CCFC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{PLAYER}, I'm fine. Please don't worry about me.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
