#include "event_macros.h"
#include "overworld.h"

/* map_55_state_01: map 55 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EF04D4, map_55_state_01_08EF04D4, 0x08EF04E0, 0x08F0404C)
  PLAY_MUSIC(20)
  WALK_OBJECT_Y(0, 72)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  WALK_OBJECT_Y(0, 66)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 1, 8)
  LANGUAGE_TEXT(0, "Congratulations for passing\nmy test!\n\nSo, {PLAYER}, it is you who\nsurvived until the end...\n\nFufufu, I, Sol Chevalsky,\nwelcome you!\n\n")
  LANGUAGE_TEXT(1, "F\xe9licitations !\nBienvenue duelliste,\n\ntoi qui a pers\xe9v\xe9r\xe9\njusqu'\xe0 la victoire !\n\nAlors, {PLAYER}, tu\nes rest\xe9 jusqu'\xe0 la fin...\n\nFufufu, moi,\nSol Chevalsky,\n\nje te souhaite\nla bienvenue !\n\n")
  LANGUAGE_TEXT(2, "Herzlichen Gl\xfcckwunsch!\nWillkommen, Duellant.\n\nDu warst hartn\xe4ckig und\nentschlossen!\n\nAlso bist du, {PLAYER},\nam Ende \xfcbrig geblieben.\n\nFufufu, ich, Sol Chevalsky,\nbegr\xfc\xdfe dich!\n\n")
  LANGUAGE_TEXT(3, "Congratulazioni!\n\nBenvenuto, duellante, che\nhai perseverato e vinto!\n\nAllora, {PLAYER}, alla\nfine sei rimasto tu...\n\nEheheh, io, Sol Chevalsky,\nti do il benvenuto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Felicidades!\n\n\xa1Bienvenido, oh, duelista,\nque persever\xf3 y se super\xf3!\n\nAs\xed que, {PLAYER}, t\xfa\nquedaste al final...\n\n\xa1Fufufu, yo, Sol Chevalsky,\nte doy la bienvenida!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(2, 68)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Pegasus, stop this nonsense\nat once.\n\n")
  LANGUAGE_TEXT(1, "Pegasus, arr\xeate tout\nde suite ces balivernes.\n\n")
  LANGUAGE_TEXT(2, "Pegasus, mach diesem\nUnsinn sofort ein Ende.\n\n")
  LANGUAGE_TEXT(3, "Pegasus, ora basta con\nqueste sciocchezze.\n\n")
  LANGUAGE_TEXT(4, "Pegasus, det\xe9n esta\ntonter\xeda ahora mismo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 0, 8)
  LANGUAGE_TEXT(0, "My past means nothing to me.\nI am no longer Pegasus.\n\nI am Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(1, "J'ai tir\xe9 un trait\nsur mon pass\xe9.\n\nJe ne suis plus\nPegasus.\n\nJe suis Sol Chevalsky !\n\n")
  LANGUAGE_TEXT(2, "Ich habe mich meiner\nVergangenheit entledigt.\n\nIch bin nicht mehr Pegasus.\n\nIch bin Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(3, "Ho rotto con il passato.\nNon sono pi\xf9 Pegasus.\n\nSono Sol Chevalsky!\n\n")
  LANGUAGE_TEXT(4, "Me he desecho de\nmi pasado.\n\nYa no soy Pegasus.\n\n\xa1Yo soy Sol Chevalsky!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Why are you acting like\nthis?\n\nIt's not too late.\n\nReturn Reshef the Dark Being\nto its prison.\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce qui t'as pouss\xe9\n\xe0 faire \xe7a ?\n\nIl n'est pas trop tard.\n\nRemets Reshef, l'Etre des\nt\xe9n\xe8bres en prison.\n\n")
  LANGUAGE_TEXT(2, "Was hat dich hierzu\ngetrieben?\n\nEs ist noch nicht zu sp\xe4t.\n\nBring Reschef den Dunklen\nin sein Gef\xe4ngnis zur\xfcck.\n\n")
  LANGUAGE_TEXT(3, "Cosa ti ha spinto a\nfare questo?\n\nNon \xe8 troppo tardi.\nRinchiudi Reshef\n\nil Tenebroso nella\nsua prigione.\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 te llev\xf3\na hacer esto?\n\nNo es demasiado tarde.\n\nDevuelve a Reshef, el\nSer Oscuro a su prisi\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 1, 8)
  LANGUAGE_TEXT(0, "What? Why should I do that?\n\nWhen Reshef gains full\npower, it would create a\n\nwonderful world!\n\nWhy can you not accept that?\n\n")
  LANGUAGE_TEXT(1, "Quoi ?\nEt pourquoi ?\n\nUn monde merveilleux\ngouvern\xe9 par Reshef...\n\nQui ne pourrait pas\nvouloir cela ?\n\n")
  LANGUAGE_TEXT(2, "Was?\nWarum sollte ich?\n\nEine herrliche Welt, in der\nReschef alle Macht\n\nbesitzt...\nWas st\xf6rt dich daran?\n\n")
  LANGUAGE_TEXT(3, "Cosa? Perch\xe9 mai\ndovrei farlo?\n\nUn mondo meraviglioso\ndominato da Reshef...\n\nPerch\xe9 non riesci ad\naccettarlo?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? \xbfPor qu\xe9 tendr\xeda\nyo que hacer eso?\n\nUn mundo maravilloso\nen el que Reshef tenga\n\ntodo el poder...\n\n\xbfPor qu\xe9 no puedes\naceptarlo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "He is under the spell of the\nDark Being...\n\n")
  LANGUAGE_TEXT(1, "Il est sous le charme\nde l'Etre des t\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "Er steht unter dem\nEinfluss des Dunklen...\n\n")
  LANGUAGE_TEXT(3, "\xc8 sotto l'incantesimo\ndel Tenebroso...\n\n")
  LANGUAGE_TEXT(4, "Est\xe1 bajo el hechizo\ndel Ser Oscuro...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 0, 8)
  LANGUAGE_TEXT(0, "To complete the resurrection\nof Reshef the Dark Being...\n\nThere is no greater\nsacrifice...\n\nThan the spirit of a\ndefeated duelist!\n\nAnd Yugi boy...\n\nThe only duelist to have\nbeaten me...\n\n")
  LANGUAGE_TEXT(1, "La r\xe9surrection de Reshef,\nl'Etre des t\xe9n\xe8bres...\n\nIl n'y a pas de sacrifice\nplus louable...\n\nque l'\xe2me d'un duelliste\nune fois battu !\n\nEt la puissance de\nce gar\xe7on, Yugi...\n\nLe seul \xe0 avoir r\xe9ussi\n\xe0 me battre...\n\n")
  LANGUAGE_TEXT(2, "Die vollst\xe4ndige Auferste-\nhung von Reschef\n\ndem Dunklen...\nWelch besseres Opfer...\n\nAls der Geist eines\nbesiegten Duellanten!\n\nUnd die Kraft Yugis...\n\nDer einzige, der mich je\nbesiegte...\n\n")
  LANGUAGE_TEXT(3, "La completa risurrezione di\nReshef il Tenebroso...\n\nQuale sacrificio migliore...\ndello spirito di un\n\nduellante sconfitto?\n\nE il potere di quel\nragazzo, Yugi...\n\nL'unico che mi abbia\nbattuto...\n\n")
  LANGUAGE_TEXT(4, "La completa resurrecci\xf3n de\nReshef, el Ser Oscuro...\n\nNo puede haber un\nmejor sacrificio...\n\n\xa1Que el esp\xedritu de un\nduelista derrotado!\n\nY el poder de ese\nchico, Yugi...\n\nEl \xfanico que me\nha vencido...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SET_OBJECT_POSITION(6, 64, 42, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 1, 8)
  LANGUAGE_TEXT(0, "I have his power right here.\n\nFufufu... There are no\nduelists left who can beat\n\nme.\n\nTherefore, you will lose...\n\nAnd I will sacrifice you to\nReshef the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "J'ai sa puissance\nl\xe0, entre mes mains.\n\nFufufu... Aucun autre\nduelliste ne peut me\n\nbattre.\nTu vas donc perdre...\n\nComme sacrifice pour Reshef,\nl'Etre des t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Ich besitze hier diese\nMacht.\n\nFufufu... Kein anderer Duel-\nlant kann mich schlagen.\n\nDu wirst verlieren...\n\nDu wirst Reschef dem\nDunklen geopfert.\n\n")
  LANGUAGE_TEXT(3, "Proprio qui ho il suo\npotere. Eheheh... Nessun\n\nduellante pu\xf2 pi\xf9 battermi.\nQuindi tu perderai...\n\nE sarai sacrificato a\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Tengo su poder\naqu\xed mismo.\n\nFufufu... No hay m\xe1s\nduelistas que me\n\npuedan vencer.\n\nY por eso t\xfa perder\xe1s...\n\nPara ser un sacrificio\na Reshef, el Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "He has the pieces of the\nMillennium Puzzle...\n\n")
  LANGUAGE_TEXT(1, "Il poss\xe8de les pi\xe8ces du\nPuzzle du mill\xe9nium...\n\n")
  LANGUAGE_TEXT(2, "Er h\xe4lt die Teile des Mil-\nlenniumspuzzles in den\n\nH\xe4nden...\n\n")
  LANGUAGE_TEXT(3, "Ha i pezzi del\nPuzzle Millenario...\n\n")
  LANGUAGE_TEXT(4, "Tiene las piezas\ndel Puzzle del Milenio...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SET_OBJECT_POSITION(6, 128, 96, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 1, 8)
  LANGUAGE_TEXT(0, "Come, the preparations have\nbeen made.\n\nWe will duel, and you will\ntaste defeat!\n\n")
  LANGUAGE_TEXT(1, "Viens, les pr\xe9parations\nont \xe9t\xe9 faites.\n\nBattons-nous en duel,\net tu vas go\xfbter\n\n\xe0 la d\xe9faite.\n\n")
  LANGUAGE_TEXT(2, "Komm, es ist alles\nvorbereitet.\n\nWir duellieren uns, und\ndu verlierst.\n\n")
  LANGUAGE_TEXT(3, "Forza, i preparativi\nsono stati fatti.\n\nDuelleremo e tu\nassaporerai la sconfitta.\n\n")
  LANGUAGE_TEXT(4, "Ven, se han hecho\nlas preparaciones.\n\nLucharemos y t\xfa\nser\xe1s derrotado.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "There is no choice. Please,\n{PLAYER}.\n\nYou must free Pegasus's\nspirit from Reshef.\n\n")
  LANGUAGE_TEXT(1, "Tu n'as pas le choix.\nS'il te pla\xeet, {PLAYER}.\n\nTu dois lib\xe9rer l'esprit\nde Pegasus des griffes\n\nde Reshef.\n\n")
  LANGUAGE_TEXT(2, "Du hast keine Wahl.\nBitte, {PLAYER}.\n\nBefrei Pegasus' Geist\nvon Reschef.\n\n")
  LANGUAGE_TEXT(3, "Non c'\xe8 altra scelta.\nTi prego, {PLAYER}.\n\nDevi liberare lo spirito\ndi Pegasus da Reshef.\n\n")
  LANGUAGE_TEXT(4, "No hay alternativa.\nPor favor, {PLAYER}.\n\nDebes liberar el esp\xedritu\nde Pegasus de Reshef.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(121)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF04E0, map_55_state_01_08EF04E0, 0x08EF04EC, 0x08EF04F8)
  CHECK_FLAG(203)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF04EC, map_55_state_01_08EF04EC, 0x08EF0504, 0x08F04040)
  PLAY_MUSIC(336)
  COMMAND_7C_ARG(8, 29)
  PLAY_MUSIC(335)
  COMMAND_7C_ARG(8, 30)
  PLAY_MUSIC(337)
  COMMAND_7C_ARG(8, 31)
  PLAY_MUSIC(350)
  COMMAND_7C_ARG(8, 32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0504, map_55_state_01_08EF0504, 0x08EF0510, 0x08EF051C)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 4, 8)
  LANGUAGE_TEXT(0, "Noooooooooooo!\n\n")
  LANGUAGE_TEXT(1, "Noooooooooon !\n\n")
  LANGUAGE_TEXT(2, "Neiiiiiiin!\n\n")
  LANGUAGE_TEXT(3, "Noooooooooooo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Noooooooooooo!\n\n")
  END_LANGUAGE_TEXT()
  SPECIAL(25)
  PLAY_MUSIC(317)
  SLIDE_OBJECT(1, 2, 14)
  DELAY(16)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 4, 8)
  LANGUAGE_TEXT(0, "It can't be...\nUnbelievable...\n\nHow could I lose with the\npower of Reshef?\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas possible...\nIncroyable...\n\nComment ai-je pu perdre\navec la puissance\n\nde Reshef ?\n\n")
  LANGUAGE_TEXT(2, "Es kann nicht sein...\nUnm\xf6glich...\n\nWie konnte ich mit Reschefs\nMacht verlieren?\n\n")
  LANGUAGE_TEXT(3, "Non pu\xf2 essere...\nIncredibile...\n\nCome ho fatto a perdere\ncon il potere di Reshef?\n\n")
  LANGUAGE_TEXT(4, "No puede ser...\nIncre\xedble...\n\n\xbfC\xf3mo he podido\nperder, con el\n\npoder de Reshef?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(318)
  SPECIAL(21)
  COMMAND_7C_ARG(8, 33)
  SPECIAL(24)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 7)
  DELAY(8)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  WALK_OBJECT_Y(2, 62)
  PORTRAIT(PORTRAIT_ISHIZU, 6, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being!\n\nI command you to return to\nthe stone tablet!\n\n")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des\nt\xe9n\xe8bres !\n\nRetourne \xe0 la tablette\nen pierre, je l'exige !\n\n")
  LANGUAGE_TEXT(2, "Reschef der Dunkle!\n\nIch befehle dir{BYTE_8146} Kehre zur\nSteintafel zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Reshef il Tenebroso!\n\nTi ordino di tornare\nnella tavoletta di pietra!\n\n")
  LANGUAGE_TEXT(4, "\xa1Reshef, el Ser Oscuro!\n\n\xa1Te ordeno regresar\na la tabla de piedra!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(4)
  PLAY_MUSIC(351)
  COMMAND_7C_ARG(8, 34)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(2, 0, 16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(0, 0, 8)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(1, 0, 24)
  DELAY(48)
  MOVE_OBJECT(1, 0, 4, 0)
  DELAY(4)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(6)
  MOVE_OBJECT(1, 0, 4, 0)
  DELAY(8)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(6)
  MOVE_OBJECT(1, 0, 4, 0)
  DELAY(4)
  MOVE_OBJECT(1, 3, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(32)
  PLAY_MUSIC(22)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 6, 8)
  LANGUAGE_TEXT(0, "Gwah! Wh-what... What is\nhappening?!\n\nNoooo! What happened to me?\n\n")
  LANGUAGE_TEXT(1, "Gouah ! Q-qu'est-ce...\nQu'est-ce qui se passe ?!\n\nNooon !\nQue m'est-il arriv\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Gwah! W-was...\nWas geschieht?!\n\nNeiiiin!\nWas ist mit mir passiert?\n\n")
  LANGUAGE_TEXT(3, "Guaah! Che-che cosa...\nCosa sta succedendo?!\n\nNoooo!\nCosa mi \xe8 successo?\n\n")
  LANGUAGE_TEXT(4, "\xa1Gwah! \xbfQ-qu\xe9...\n\xa1\xbfQu\xe9 est\xe1 pasando?!\n\n\xa1Noooo!\n\xbfQu\xe9 me pas\xf3?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 60)
  MOVE_OBJECT(0, 3, 0, 0)
  WALK_OBJECT_X(2, 44)
  WALK_OBJECT_Y(2, 64)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "You seem to have finally\nawoken from your nightmare.\n\n")
  LANGUAGE_TEXT(1, "Tu t'es r\xe9veill\xe9, tu\ncauchemardais.\n\n")
  LANGUAGE_TEXT(2, "Es scheint, du bist aus\ndeinem Alptraum erwacht.\n\n")
  LANGUAGE_TEXT(3, "Finalmente sembra che ti sia\nrisvegliato dall'incubo.\n\n")
  LANGUAGE_TEXT(4, "Parece que por fin has\ndespertado de tu pesadilla.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 3, 8)
  LANGUAGE_TEXT(0, "What... I almost ruined us\nall...\n\nEven though I was under\ncontrol, that is no\n\nexcuse...\n\nI gathered the spirits of\ndefeated duelists...\n\n")
  LANGUAGE_TEXT(1, "Quoi... J'ai fait quelque\nchose qui a failli conduire\n\n\xe0 notre perte...\n\nJ'ai \xe9t\xe9 sous\nson contr\xf4le...\n\nEt j'ai rassembl\xe9\nles esprits des\n\nduellistes vaincus...\n\n")
  LANGUAGE_TEXT(2, "Was... Ich habe etwas\ngetan, was beinahe uns\n\nallen Verderben gebracht\nh\xe4tte...\n\nIch wurde gesteuert...\nDennoch:\n\nIch sammelte die Geister\nbesiegter Duellanten...\n\n")
  LANGUAGE_TEXT(3, "Ma...Ho fatto qualcosa\nche ci ha quasi\n\nrovinati tutti...\n\nAnche se ero sotto il\ncontrollo... Ho riunito\n\ngli spiriti dei duellanti\nnella sconfitta...\n\n")
  LANGUAGE_TEXT(4, "Qu\xe9... He hecho algo\nque casi termina con\n\ntodos nosotros...\n\nAunque estaba bajo\ncontrol...\n\nReun\xed los esp\xedritus\nde duelistas derrotados...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Reshef needs their negative\nenergy to initiate its\n\nfinal ritual.\n\n")
  LANGUAGE_TEXT(1, "Reshef a besoin de l'\xe9nergie\nn\xe9gative de la d\xe9faite.\n\nIl va l'utiliser pour\nson rituel final.\n\n")
  LANGUAGE_TEXT(2, "Reschef braucht die negative\nEnergie der Niederlage.\n\nEr wird sie f\xfcr sein letztes\nRitual benutzen.\n\n")
  LANGUAGE_TEXT(3, "A Reshef serve l'energia\nnegativa della sconfitta.\n\nReshef la user\xe0 per il\nsuo rituale finale.\n\n")
  LANGUAGE_TEXT(4, "Reshef necesita la\nenerg\xeda negativa\n\nde la derrota.\n\nReshef la utilizar\xe1\npara su ritual final.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(271)
  REACTION(0, 2)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "The castle is sealed inside\na protective sphere...\n\nThere is no escape from\nReshef's final ritual.\n\n")
  LANGUAGE_TEXT(1, "Le ch\xe2teau est entour\xe9\nd'une sph\xe8re protectrice.\n\nImpossible d'\xe9chapper\nau rituel final de Reshef.\n\n")
  LANGUAGE_TEXT(2, "Die Burg ist in ihrer Schut-\nzsph\xe4re eingeschlossen...\n\nEs gibt kein Entkommen von\nReschefs letztem Ritual.\n\n")
  LANGUAGE_TEXT(3, "Il castello \xe8 isolato dentro\nla sua sfera di protezione.\n\nNon c'\xe8 scampo dal rituale\nfinale di Reshef.\n\n")
  LANGUAGE_TEXT(4, "El castillo est\xe1\nsellado dentro de\n\nsu esfera protectora...\n\nNo hay escapatoria del\nritual final de Reshef.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 6, 8)
  LANGUAGE_TEXT(0, "The final ritual? Of the\nancients?\n\nReshef is using negative\nenergy?\n\n")
  LANGUAGE_TEXT(1, "Le rituel final...\ndes anciens ?\n\nReshef accomplit ce\nrituel avec l'\xe9nergie\n\nde la d\xe9faite ?\n\n")
  LANGUAGE_TEXT(2, "Das letzte Ritual?\nDer Menschen der Antike?\n\nReschef vollzieht es mit der\nEnergie der Niederlage?\n\n")
  LANGUAGE_TEXT(3, "Il rituale finale?\nDegli antichi?\n\nReshef lo eseguir\xe0 con\nl'energia della sconfitta?\n\n")
  LANGUAGE_TEXT(4, "\xbfEl ritual final?\n\xbfDe los antiguos?\n\n\xbfReshef lo est\xe1\nejecutando con\n\nla energ\xeda de los\nderrotados?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(319)
  COMMAND_7C_ARG(8, 35)
  DELAY(8)
  CONDITION_CHECK(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0510, map_55_state_01_08EF0510, 0x08EF0528, 0x08F04040)
  PLAY_MUSIC(21)
  SPECIAL(22)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0528, map_55_state_01_08EF0528, 0x08EF0534, 0x08F0404C)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 7)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Reshef is regaining its\nform...\n\n")
  LANGUAGE_TEXT(1, "Reshef retrouve\nsa forme...\n\n")
  LANGUAGE_TEXT(2, "Reschef nimmt wieder seine\nForm an...\n\n")
  LANGUAGE_TEXT(3, "Reshef sta riprendendo\nforma...\n\n")
  LANGUAGE_TEXT(4, "Reshef est\xe1\nrecuper\xe1ndose...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 3, 8)
  LANGUAGE_TEXT(0, "It's hopeless... We're\nfinished.\n\nAll the duels that {PLAYER}\nfought to get here...\n\nAll the negative energies of\nthe defeated duelists...\n\nReshef has all their power.\n\nThe Dark Being has risen...\n\nWe have no hope for\ndefeating it.\n\n")
  LANGUAGE_TEXT(1, "C'est sans issue...\nNous sommes fichus.\n\nTous les duels de {PLAYER}\npour arriver jusqu'ici...\n\nToutes les \xe9nergies\nn\xe9gatives des\n\nduellistes vaincus...\n\nToute cette puissance\nest aux mains de Reshef.\n\nL'Etre des t\xe9n\xe8bres\ns'est lev\xe9...\n\nNous n'avons aucune\nchance de le battre.\n\n")
  LANGUAGE_TEXT(2, "Es nutzt nichts...\nWir sind erledigt.\n\nAlle Duelle von {PLAYER},\num hierher zu gelangen...\n\nDie ganze negative Energie\nder besiegten Duellanten...\n\nAll diese Kraft ist in\nReschef vereinigt.\n\nDer Dunkle hat sich\nerhoben...\n\nWir k\xf6nnen ihn nicht\nbesiegen.\n\n")
  LANGUAGE_TEXT(3, "Non c'\xe8 speranza... Per noi\n\xe8 la fine. Tutti i duelli\n\ncombattuti da {PLAYER}\nper arrivare qui...Tutte le\n\nenergie negative dei\nduellanti sconfitti...\n\nTutto quel potere \xe8\nfinito in mano a Reshef.\n\nIl Tenebroso \xe8 risorto...\n\nNon abbiamo la minima\nsperanza di sconfiggerlo.\n\n")
  LANGUAGE_TEXT(4, "No hay esperanza...\nEstamos acabados.\n\nTodos los duelos\nque {PLAYER}\n\nluch\xf3 para llegar\nhasta aqu\xed...\n\nTodas las energ\xedas\nnegativas de los\n\nduelistas derrotados...\n\nTodo ese poder ha\nido a Reshef.\n\nEl Ser Oscuro se ha\nlevantado...\n\nNo tenemos ninguna\nesperanza de derrotarlo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "A complete victory in a duel\nis needed to consummate the\n\nritual.\n\nThe Dark Being has grown\ninfinitely powerful...\n\n{PLAYER} has also grown\nstrong, but...\n\n")
  LANGUAGE_TEXT(1, "Ce rituel est consomm\xe9\npar une victoire\n\nabsolue au duel.\n\nL'Etre des t\xe9n\xe8bres est\ndevenu trop fort...\n\n{PLAYER} est devenu\nfort \xe9galement mais...\n\n")
  LANGUAGE_TEXT(2, "Das Ritual wird durch einen\nabsoluten Duellsieg\n\nverzehrt.\n\nDer Dunkle ist unglaub-\nlich stark geworden...\n\n{PLAYER} ist ebenfalls\nerstarkt, aber...\n\n")
  LANGUAGE_TEXT(3, "Il rituale viene consumato\ncon una vittoria assoluta\n\na duello. Il Tenebroso \xe8\ndiventato tremendamente\n\nforte... Anche {PLAYER}\n\xe8 diventato forte, ma...\n\n")
  LANGUAGE_TEXT(4, "El ritual se consuma\ncon una victoria\n\nde duelo absoluta.\n\nEl Ser Oscuro se ha hecho\nterriblemente fuerte...\n\n{PLAYER} tambi\xe9n se ha\nhecho fuerte, pero...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(272)
  REACTION(3, 1)
  WALK_OBJECT_Y(3, 76)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "What are you afraid of,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(1, "De quoi as-tu peur,\n{PLAYER} ?\n\n")
  LANGUAGE_TEXT(2, "Wovor hast du Angst,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(3, "Di cosa hai paura,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(4, "\xbfDe qu\xe9 tienes miedo,\n{PLAYER}?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Use my card and win!\n\n")
  LANGUAGE_TEXT(1, "Utilise ma carte et\nassure la victoire !\n\n")
  LANGUAGE_TEXT(2, "Mit meiner Karte kannst\ndu den Sieg davontragen!\n\n")
  LANGUAGE_TEXT(3, "Usa la mia carta e\nsuggella la vittoria!\n\n")
  LANGUAGE_TEXT(4, "\xa1Usa mi carta y deja\nsellada la victoria!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 68)
  WALK_OBJECT_Y(5, 76)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 2, 8)
  LANGUAGE_TEXT(0, "Kaiba's right, {PLAYER}!\n\nI don't believe this story\nabout a final ritual...\n\nBut I know you'll win!\n\n")
  LANGUAGE_TEXT(1, "Seto a raison, {PLAYER} !\n\nJe ne sais rien sur\nce rituel final...\n\nMais je sais que\ntu vas gagner !\n\n")
  LANGUAGE_TEXT(2, "Seto hat Recht, {PLAYER}!\n\nIch wei\xdf nichts von einem\nletzten Ritual...\n\nAber von deinem Sieg bin\nich \xfcberzeugt!\n\n")
  LANGUAGE_TEXT(3, "Seto ha ragione, {PLAYER}!\n\nNon so niente di questo\nrituale finale...\n\nMa so che vincerai tu!\n\n")
  LANGUAGE_TEXT(4, "\xa1Seto tiene raz\xf3n,\n{PLAYER}!\n\nNo s\xe9 nada acerca\nde un ritual final...\n\n\xa1Pero s\xe9 que vencer\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 3, 8)
  LANGUAGE_TEXT(0, "Yugi boy... I have treated\nyou terribly...\n\n")
  LANGUAGE_TEXT(1, "Yugi... J'ai \xe9t\xe9\nhorrible envers toi...\n\n")
  LANGUAGE_TEXT(2, "Yugi... Ich habe dir\nFurchtbares angetan...\n\n")
  LANGUAGE_TEXT(3, "Yugi... Ti ho fatto\nuna cosa terribile...\n\n")
  LANGUAGE_TEXT(4, "Yugi... Te he hecho\nalgo terrible...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PLAY_MUSIC(316)
  SHOW_OBJECT(6, 80, 64, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(0, 16)
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(320)
  SLIDE_OBJECT(6, 1, 16)
  DELAY(32)
  SHOW_OBJECT(6, 128, 96, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(218)
  SWAP_OBJECT_SPRITE(4, 2)
  DELAY(96)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 6, 8)
  LANGUAGE_TEXT(0, "Wh-what? Is this a miracle?\nIt's fantastic!\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? Un miracle ?\nC'est fantastique !\n\n")
  LANGUAGE_TEXT(2, "W-was? Ist das ein Wunder?\nEs ist unglaublich!\n\n")
  LANGUAGE_TEXT(3, "Co-cosa?! \xc8 un miracolo!\n\xc8 fantastico!\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9? \xbfEs un milagro?\n\xa1Es fant\xe1stico!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "You have nothing to fear\nagainst Reshef!\n\nMy spirit is united with all\nthe duelists I've faced.\n\nIncluding yours, {PLAYER}.\n\nWith all our souls united as\none...\n\nTake hold of the true\nduelist's spirit!\n\nUse it to defeat the Dark\nBeing!\n\n")
  LANGUAGE_TEXT(1, "Reshef n'est pas\n\xe0 craindre !\n\nMon esprit est li\xe9\n\xe0 tous les duellistes\n\nque j'ai affront\xe9s.\nEt aussi au tien, {PLAYER}.\n\nSoutiens la camaraderie\ndes duellistes...\n\nEt empare-toi du v\xe9ritable\nesprit des duellistes !\n\nAinsi, tu pourras m\xeame\nbattre l'Etre des\n\nt\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Wir haben nichts von Reschef\nzu f\xfcrchten!\n\nMein Geist ist mit allen\nDuellanten verbunden, mit\n\ndenen ich je gek\xe4mpft habe.\n\nAuch mit deinem, {PLAYER}.\n\nSch\xfctze die Kameradschaft\nder Duellanten...\n\nUnd nutze den wahren Geist\nder Duellanten!\n\nDas wird selbst den\nDunklen st\xfcrzen!\n\n")
  LANGUAGE_TEXT(3, "Non c'\xe8 niente da\ntemere in Reshef!\n\nIl mio spirito \xe8 legato a\ntutti i duellanti che ho\n\naffrontato. Anche con il\ntuo, {PLAYER}.\n\nTieni alto il cameratismo\ndei duellanti...\n\nE impadronisciti dello\nspirito del vero duellante!\n\nIn questo modo, anche il\nTenebroso soccomber\xe0!\n\n")
  LANGUAGE_TEXT(4, "\xa1No hay nada que\ntemer de Reshef!\n\nMi esp\xedritu est\xe1 unido\ncon todos los duelistas\n\na los que me he\nenfrentado.\n\nCon el tuyo tambi\xe9n,\n{PLAYER}.\n\nMant\xe9n la camarader\xeda\nde los duelistas...\n\n\xa1Y muestra el verdadero\nesp\xedritu de un duelista!\n\n\xa1As\xed derrotar\xe1s incluso\nal Ser Oscuro!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "All of us together... We'll\ndestroy Reshef!\n\n")
  LANGUAGE_TEXT(1, "Tous ensemble... Nous\nd\xe9truirons Reshef !\n\n")
  LANGUAGE_TEXT(2, "Wir alle gemeinsam... Wir\nwerden Reschef vernichten!\n\n")
  LANGUAGE_TEXT(3, "Noi tutti insieme...\nDistruggeremo Reshef!\n\n")
  LANGUAGE_TEXT(4, "Todos juntos...\n\xa1Destruiremos a Reshef!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 7)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "Yeah!\n\n")
  LANGUAGE_TEXT(1, "Ouais !\n\n")
  LANGUAGE_TEXT(2, "Genau!\n\n")
  LANGUAGE_TEXT(3, "S\xec\xec\xec\xec!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 8)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Humph... Come Blue-Eyes!\n\n")
  LANGUAGE_TEXT(1, "Mmm...\nViens ici, Yeux bleus !\n\n")
  LANGUAGE_TEXT(2, "Hmph...\nKomm her, Blauauge!\n\n")
  LANGUAGE_TEXT(3, "Bah...\nVieni qui, Occhi Blu!\n\n")
  LANGUAGE_TEXT(4, "Vaya...\n\xa1Ven aqu\xed, Ojos azules!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 9)
  DELAY(16)
  PLAY_MUSIC(352)
  COMMAND_7C_ARG(8, 10)
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "Go!\n\n")
  LANGUAGE_TEXT(1, "Allez !\n\n")
  LANGUAGE_TEXT(2, "Geh!\n\n")
  LANGUAGE_TEXT(3, "Vai!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ve!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(343)
  COMMAND_7C_ARG(8, 11)
  DELAY(16)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 6, 8)
  LANGUAGE_TEXT(0, "The sacred souls of\nduelists!\n\n")
  LANGUAGE_TEXT(1, "Les \xe2mes sacr\xe9es\ndes duellistes !\n\n")
  LANGUAGE_TEXT(2, "Die heiligen Seelen der\nDuellanten!\n\n")
  LANGUAGE_TEXT(3, "Le anime sacre dei\nduellanti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Las sagradas almas\nde los duelistas!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 6, 8)
  LANGUAGE_TEXT(0, "The pure and proud spirits\nof duelists have united!\n\nPerhaps this...\n\n")
  LANGUAGE_TEXT(1, "Les esprits purs\net fiers des duellistes\n\nont fusionn\xe9 !\nPeut-\xeatre que...\n\n")
  LANGUAGE_TEXT(2, "Die reinen, stolzen Geister\nder Duellanten haben sich\n\nvereinigt!\nVielleicht...\n\n")
  LANGUAGE_TEXT(3, "Gli spiriti puri e fieri\ndei duellanti si sono\n\nfusi! Forse questo...\n\n")
  LANGUAGE_TEXT(4, "\xa1Los esp\xedritus puros\ny orgullosos de los\n\nduelistas se\nhan fusionado!\n\nQuiz\xe1s esto...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "Now, {PLAYER}!\n\nSeal Reshef forever!\n\n")
  LANGUAGE_TEXT(1, "Maintenant, {PLAYER} !\n\nEnferme Reshef\n\xe0 tout jamais !\n\n")
  LANGUAGE_TEXT(2, "Jetzt, {PLAYER}!\n\nSperr Reschef auf ewig ein!\n\n")
  LANGUAGE_TEXT(3, "Ora, {PLAYER}!\n\nImprigiona Reshef\nper sempre!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ahora, {PLAYER}!\n\n\xa1Sella a Reshef por siempre!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(0, 50)
  DELAY(16)
  DUEL(122)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0534, map_55_state_01_08EF0534, 0x08EF0540, 0x08EF054C)
  PLAY_MUSIC(22)
  PLAY_MUSIC(391)
  COMMAND_7C_ARG(8, 36)
  PORTRAIT(PORTRAIT_JOEY, 2, 8)
  LANGUAGE_TEXT(0, "Is... Is it over?\n\n")
  LANGUAGE_TEXT(1, "C'est...\nC'est termin\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Ist...\nIst es vorbei?\n\n")
  LANGUAGE_TEXT(3, "\xc8...\n\xc8 finita?\n\n")
  LANGUAGE_TEXT(4, "Se...\n\xbfSe acab\xf3?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "Reshef fed on the darkness\nin duelists' souls.\n\nIt gained power from the\nfear of defeat.\n\nBut our proud duelist\nspirits won in the end.\n\n")
  LANGUAGE_TEXT(1, "Reshef se nourrissait\n\ndu c\xf4t\xe9 obscur des\n\xe2mes des duellistes.\n\nLa peur de l'\xe9chec\nalimentait sa puissance.\n\nMais notre fiert\xe9 de\nduellistes l'a remport\xe9.\n\n")
  LANGUAGE_TEXT(2, "Reschef n\xe4hrte sich von\nder Finsternis in den\n\nSeelen der Duellanten.\n\nDie Angst vor der Niederlage\nst\xe4rkte ihn.\n\nDoch unsere stolzen Geister\nals Duellanten siegten.\n\n")
  LANGUAGE_TEXT(3, "Reshef si nutriva del\nlato oscuro nelle\n\nanime dei duellanti e\ntraeva potere dal\n\ntimore della sconfitta.\nMa i nostri spiriti fieri\n\ndi duellanti hanno\ntrionfato.\n\n")
  LANGUAGE_TEXT(4, "Reshef se alimentaba\nde la oscuridad en\n\nlas almas de los\nduelistas.\n\nObten\xeda su poder del\nmiedo a la derrota.\n\nPero nuestros orgu-\nllosos esp\xedritus como\n\nduelistas vencieron.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "I wouldn't be so hasty..\n\n")
  LANGUAGE_TEXT(1, "Je ne serais pas\nsi press\xe9...\n\n")
  LANGUAGE_TEXT(2, "Nicht so voreilig...\n\n")
  LANGUAGE_TEXT(3, "Io aspetterei un po'\nprima di dirlo...\n\n")
  LANGUAGE_TEXT(4, "Yo no ir\xeda tan r\xe1pido...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 4, 0)
  DELAY(8)
  MOVE_OBJECT(1, 1, 7, 0)
  DELAY(8)
  MOVE_OBJECT(1, 2, 6, 0)
  DELAY(8)
  WALK_OBJECT_X(1, 64)
  DELAY(8)
  MOVE_OBJECT(1, 2, 4, 0)
  DELAY(8)
  MOVE_OBJECT(1, 2, 4, 0)
  DELAY(8)
  WALK_OBJECT_Y(1, 44)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(3, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 49)
  DELAY(8)
  PLAY_MUSIC(392)
  COMMAND_7C_ARG(8, 58)
  DELAY(8)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 6, 8)
  LANGUAGE_TEXT(0, "Noooooooooo!\n\nReshef! It's worming itself\ninto my soul!\n\nIt's found the darkness in\nmy heart!\n\nWhy? Do I fear defeat?\n\n")
  LANGUAGE_TEXT(1, "Nooooooon !\n\nReshef ! Il s'est introduit\nlentement dans mon \xe2me !\n\nIl a trouv\xe9 le c\xf4t\xe9\nsombre de mon c\u0153ur !\n\nMais pourquoi ?\nAi-je peur de perdre ?\n\n")
  LANGUAGE_TEXT(2, "Neiiiiiiiin!\n\nReschef! Er bohrt sich in\nmeine Seele!\n\nEr hat die Finsternis in\nmeinem Herzen entdeckt!\n\nWarum? F\xfcrchte\nich die Niederlage?\n\n")
  LANGUAGE_TEXT(3, "Noooooooooooo!\n\nReshef! Si sta insinuando\nnella mia anima!\n\nHa scovato il lato oscuro\nnel mio cuore!\n\nPerch\xe9? Temo forse\nla sconfitta?\n\n")
  LANGUAGE_TEXT(4, "\xa1Noooooooooo!\n\n\xa1Reshef! \xa1Se est\xe1\nmetiendo en mi alma!\n\n\xa1Ha encontrado la os-\ncuridad de mi coraz\xf3n!\n\n\xbfPor qu\xe9?\n\xbfTemo la derrota?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 3, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being...\n\nI let you into my soul to\nexploit its darkness...\n\nI helped release you...\n\n")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des\nt\xe9n\xe8bres...\n\nJe t'ai laiss\xe9 exploiter le\nc\xf4t\xe9 sombre de mon \xe2me...\n\nJe t'ai aid\xe9 \xe0 te lib\xe9rer...\n\n")
  LANGUAGE_TEXT(2, "Reschef der Dunkle...\n\nIch gew\xe4hrte dir Zugang zu\nmeiner Seele, ich lie\xdf dich\n\nihre Finsternis erkunden...\n\nIch half, dich freizu-\nsetzen...\n\n")
  LANGUAGE_TEXT(3, "Reshef il Tenebroso...\n\nTi ho lasciato entrare nella\nmia anima e sfruttarne il\n\nlato oscuro... Ho contri-\nbuito a liberarti...\n\n")
  LANGUAGE_TEXT(4, "Reshef, el Ser Oscuro...\n\nTe dejo entrar en mi\nalma y explotar su\n\noscuridad...\n\nAyud\xe9 a liberarte...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 5, 8)
  LANGUAGE_TEXT(0, "But... I won't lose to you!\n\n")
  LANGUAGE_TEXT(1, "Mais... Je ne vais pas\nperdre contre toi !\n\n")
  LANGUAGE_TEXT(2, "Aber... Ich werde nicht\ngegen dich verlieren!\n\n")
  LANGUAGE_TEXT(3, "Ma...\nNon perder\xf2 con te!\n\n")
  LANGUAGE_TEXT(4, "Pero...\n\xa1No me vencer\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 38)
  DELAY(8)
  WALK_OBJECT_X(1, 60)
  DELAY(8)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 5, 8)
  LANGUAGE_TEXT(0, "Now, {PLAYER}!\n\nSeal me while Reshef remains\ntrapped inside!\n\n")
  LANGUAGE_TEXT(1, "Maintenant, {PLAYER} !\n\nEnferme-moi pendant\nque Reshef est encore\n\nenferm\xe9 \xe0 l'int\xe9rieur !\n\n")
  LANGUAGE_TEXT(2, "Jetzt, {PLAYER}!\n\nVersiegele mich, solange\nReschef in mir gefangen\n\nist!\n\n")
  LANGUAGE_TEXT(3, "Ora, {PLAYER}!\n\nImprigionami mentre Reshef\n\xe8 intrappolato all'interno!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ahora, {PLAYER}!\n\n\xa1S\xe9llame mientras Reshef\nest\xe1 atrapado dentro!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 61)
  DELAY(8)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 3, 8)
  LANGUAGE_TEXT(0, "Nothing can forgive me for\nwhat I've done...\n\nI have to atone for my\ncrimes...\n\n")
  LANGUAGE_TEXT(1, "On ne peut pas excuser\nce que j'ai fait...\n\nJe dois expier\nmes crimes...\n\n")
  LANGUAGE_TEXT(2, "F\xfcr meine Taten gibt\nes keine Vergebung...\n\nIch muss f\xfcr meine\nVerbrechen b\xfc\xdfen...\n\n")
  LANGUAGE_TEXT(3, "Ci\xf2 che ho fatto \xe8\nimperdonabile...\n\nDevo espiare per i\nmiei crimini...\n\n")
  LANGUAGE_TEXT(4, "No hay perd\xf3n por\nlo que he hecho...\n\nTengo que expiar\nmis cr\xedmenes...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 5, 8)
  LANGUAGE_TEXT(0, "Quickly, before Reshef\nconsumes my soul!\n\n")
  LANGUAGE_TEXT(1, "Maintenant, vite,\navant que mon \xe2me\n\nne soit consum\xe9e\npar Reshef !\n\n")
  LANGUAGE_TEXT(2, "Jetzt, schnell, bevor meine\nSeele von Reschef\n\nverzehrt wird!\n\n")
  LANGUAGE_TEXT(3, "Fai in fretta, prima che\nla mia anima sia\n\nconsumata da Reshef!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ahora, r\xe1pido, antes\nde que mi alma sea\n\nconsumida por Reshef!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, there's no other\nchoice.\n\nYou must honor Pegasus as a\ntrue duelist.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, il n'y a\npas d'autre choix.\n\nEn tant que duelliste,\n\ntu dois faire honneur\n\xe0 Pegasus.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, es gibt keine\nAlternative.\n\nZolle dem Stolz des\nDuellanten Pegasus Tribut.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, non c'\xe8\naltra scelta.\n\nDevi onorare l'orgoglio di\nPegasus come duellante.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, no queda\notra opci\xf3n.\n\nTienes que honrar el\norgullo de Pegasus\n\ncomo duelista.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(32)
  CHECK_FLAG(203)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0540, map_55_state_01_08EF0540, 0x08EF0558, 0x08F04040)
  PLAY_MUSIC(350)
  COMMAND_7C_ARG(8, 32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0558, map_55_state_01_08EF0558, 0x08EF0564, 0x08F04040)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  PORTRAIT(PORTRAIT_SOL_CHEVELSKY, 0, 8)
  LANGUAGE_TEXT(0, "Thank you, {PLAYER}.\n\nI'm glad my final opponent\nwas you.\n\n")
  LANGUAGE_TEXT(1, "Merci, {PLAYER}.\n\nJe suis content\nde m'\xeatre battu en duel\n\ncontre toi pour la\nderni\xe8re fois.\n\n")
  LANGUAGE_TEXT(2, "Danke, {PLAYER}.\n\nIch bin froh, dass ich\nmein letztes Duell gegen\n\ndich f\xfchrte.\n\n")
  LANGUAGE_TEXT(3, "Grazie, {PLAYER}.\n\nSono felice che sarai tu\na duellare con me per\n\nl'ultima volta.\n\n")
  LANGUAGE_TEXT(4, "Gracias, {PLAYER}.\n\nMe satisface que\nfueras t\xfa el \xfaltimo\n\ncon el que luch\xe9.\n\n")
  END_LANGUAGE_TEXT()
  SPECIAL(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF0564, map_55_state_01_08EF0564, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "It's over, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "C'est fini, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Es ist vorbei, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "\xc8 finita, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Se acab\xf3, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(271)
  REACTION(0, 61)
  DELAY(8)
  PLAY_MUSIC(265)
  SET_FLAG(247)
  PLAY_MUSIC(23)
  DELAY(32)
  MOVE_OBJECT(3, 2, 4, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "This castle's not going to\nhold much longer.\n\n")
  LANGUAGE_TEXT(1, "Ce ch\xe2teau ne tiendra\npas plus longtemps.\n\n")
  LANGUAGE_TEXT(2, "Diese Burg wird nicht viel\nl\xe4nger standhalten.\n\n")
  LANGUAGE_TEXT(3, "Questo castello non\nresister\xe0 per molto.\n\n")
  LANGUAGE_TEXT(4, "Este castillono va a\naguantar mucho m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(32, 1)
  DELAY(8)
  WALK_OBJECT_X(5, 60)
  MOVE_OBJECT(5, 2, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, 2, 8)
  LANGUAGE_TEXT(0, "I'll say! Let's get out of\nhere!\n\n")
  LANGUAGE_TEXT(1, "Ca fait vraiment peur !\nPartons vite d'ici !\n\n")
  LANGUAGE_TEXT(2, "Es wird gef\xe4hrlich! Machen\nwir, dass wir rauskommen!\n\n")
  LANGUAGE_TEXT(3, "Siamo in pericolo!\nUsciamo da qui!\n\n")
  LANGUAGE_TEXT(4, "\xa1Pone los pelos de punta!\n\xa1Salgamos de aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(2, 52)
  WALK_OBJECT_Y(2, 96)
  WALK_OBJECT_Y(3, 96)
  DELAY(16)
  WALK_OBJECT_Y(4, 56)
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, we have to get\nout!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER},\nnous devons sortir !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, wir m\xfcssen\nhier raus!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, dobbiamo\nuscire da qui!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xa1tenemos\nque salir!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 96)
  WALK_OBJECT_Y(4, 96)
  WALK_OBJECT_Y(0, 72)
  DELAY(32)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(64)
  WALK_OBJECT_Y(0, 96)
  SET_FLAG(178)
  SET_FLAG(237)
  FADE_SCREEN(1)
  WARP(51, 9, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF054C, map_55_state_01_08EF054C, 0x08EF0558, 0x08F04040)
  PLAY_MUSIC(350)
  COMMAND_7C_ARG(8, 40)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF051C, map_55_state_01_08EF051C, 0x08EF0528, 0x08F04040)
  PLAY_MUSIC(21)
  SPECIAL(23)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF04F8, map_55_state_01_08EF04F8, 0x08EF0504, 0x08F04040)
  PLAY_MUSIC(336)
  COMMAND_7C_ARG(8, 29)
  PLAY_MUSIC(335)
  COMMAND_7C_ARG(8, 30)
  PLAY_MUSIC(388)
  COMMAND_7C_ARG(8, 57)
  PLAY_MUSIC(350)
  COMMAND_7C_ARG(8, 40)
  FALLTHROUGH()
END_EVENT_SCRIPT()
