#include "event_macros.h"
#include "overworld.h"

/* map_18_state_01: map 18 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E80A6C, map_18_state_01_08E80A6C, 0x08E80A84, 0x08E80AA8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RICH_FATHER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A84, map_18_state_01_08E80A84, 0x08E80A9C, 0x08E80A90)
  LANGUAGE_TEXT(0, "Hohoho, you wish to\nchallenge me?\n\n")
  LANGUAGE_TEXT(1, "Ho ho ho,\ntu veux me d\xe9fier ?\n\n")
  LANGUAGE_TEXT(2, "Hohoho, du willst mich\nherausfordern?\n\n")
  LANGUAGE_TEXT(3, "Ohohoh, e tu vorresti\nsfidare me?\n\n")
  LANGUAGE_TEXT(4, "Jojojo, \xbfdeseas\nretarme?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  LANGUAGE_TEXT(0, "Papa, show him you're the\nbest!\n\n")
  LANGUAGE_TEXT(1, "Papa, montre-lui\nque tu es le meilleur !\n\n")
  LANGUAGE_TEXT(2, "Papa, zeig ihm, dass du der\nBeste bist!\n\n")
  LANGUAGE_TEXT(3, "Pap\xe0, fagli vedere\nche sei il migliore!\n\n")
  LANGUAGE_TEXT(4, "Pap\xe1, \xa1demu\xe9strale\nque eres el mejor!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  LANGUAGE_TEXT(0, "Yes, dear! Put him in his\nplace!\n\n")
  LANGUAGE_TEXT(1, "Oui, mon amour,\n\nmontre-lui que\ntu es le plus fort !\n\n")
  LANGUAGE_TEXT(2, "Ja, mein Lieber, weise ihn\nin seine Schranken!\n\n")
  LANGUAGE_TEXT(3, "S\xec, caro, fagli vedere\nqual \xe8 il suo posto!\n\n")
  LANGUAGE_TEXT(4, "S\xed, querido, \xa1ponle\nen su lugar!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(26)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A9C, map_18_state_01_08E80A9C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(232)
  LANGUAGE_TEXT(0, "W-what? I lost?\n\nI must buy more expensive\nrare cards.\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? Comment \xe7a,\nj'ai perdu ?\n\nJe dois donc acheter des\ncartes plus ch\xe8res et\n\nplus rares.\n\n")
  LANGUAGE_TEXT(2, "W-was? Hei\xdft das, ich\nhabe verloren?\n\nIch muss mir wohl teurere,\nseltenere Karten kaufen.\n\n")
  LANGUAGE_TEXT(3, "Ma come? Io avrei perso?\nSembra proprio che dovr\xf2\n\ncomprare carte rare\npi\xf9 costose.\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9?\n\xbfDices que perd\xed?\n\nParece que tengo que\ncomprar cartas raras\n\nm\xe1s caras.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_RICH_FATHER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A90, map_18_state_01_08E80A90, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  CLEAR_FLAG(238)
  CLEAR_FLAG(4)
  CLEAR_FLAG(6)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80AA8, map_18_state_01_08E80AA8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll buy more pricey rare\ncards.\n\n")
  LANGUAGE_TEXT(1, "Je vais acheter d'autres\ncartes rares, celles qui\n\nsont les plus ch\xe8res.\n\n")
  LANGUAGE_TEXT(2, "Ich kaufe mir ein paar\nteure, seltene Karten.\n\n")
  LANGUAGE_TEXT(3, "Mi comprer\xf2 pi\xf9\ncarte rare costose.\n\n")
  LANGUAGE_TEXT(4, "Comprar\xe9 unas cartas\nraras m\xe1s caras.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A78, map_18_state_01_08E80A78, 0x08E80A84, 0x08E80AB4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RICH_FATHER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80AB4, map_18_state_01_08E80AB4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "We should duel again, but\nsometime else.\n\n")
  LANGUAGE_TEXT(1, "On s'affrontera\n\xe0 nouveau en duel\n\nmais \xe0 une autre\noccasion.\n\n")
  LANGUAGE_TEXT(2, "Wir m\xfcssen uns ein ander-\nmal erneut duellieren.\n\n")
  LANGUAGE_TEXT(3, "Dobbiamo duellare ancora,\nma in un'altra occasione.\n\n")
  LANGUAGE_TEXT(4, "Tenemos que luchar de nuevo,\npero en otra ocasi\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80AC0, map_18_state_01_08E80AC0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I only came for the Egypt\nExhibition.\n\nI had no clue that dueling\nwas my husband's hobby.\n\nI wouldn't have imagined it\nin a million years.\n\n")
  LANGUAGE_TEXT(1, "Je suis venue ici pour\nl'Exposition \xe9gyptienne.\n\nJe n'ai jamais entendu\nparler du hobby de mon\n\nmari.\nLui, se battre en duel ?\n\nJe n'aurais jamais\nimagin\xe9 une chose pareille.\n\n")
  LANGUAGE_TEXT(2, "Ich bin nur wegen der\n\xe4gypt. Ausstellung hier.\n\nVom Hobby meines Mannes\nwusste ich nichts.\n\nEr und Duelle? Das h\xe4tte ich\nnie gedacht.\n\n")
  LANGUAGE_TEXT(3, "Sono venuta solo per la\nMostra Egizia. Non avevo\n\ncerto il minimo sospetto\ndell'hobby di mio marito.\n\nDuellare, lui? Non riesco\nneanche a immaginarlo.\n\n")
  LANGUAGE_TEXT(4, "S\xf3lo vine por la\nExposici\xf3n Egipcia.\n\nDesconoc\xeda el hobby\nde mi marido.\n\n\xbf\xc9l, luchar?\nNo lo imagino.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80ACC, map_18_state_01_08E80ACC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Duel? Most certainly not.\nHow uncouth!\n\n")
  LANGUAGE_TEXT(1, "Un duel ?\nPas question.\n\n")
  LANGUAGE_TEXT(2, "Duell?\nAuf keinen Fall.\n\n")
  LANGUAGE_TEXT(3, "Duellare?\nCerto che no.\n\n")
  LANGUAGE_TEXT(4, "\xbfUn duelo?\nPor supuesto que no.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A18, map_18_state_01_08E80A18, 0x08E80A30, 0x08E80A54)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RICH_DAUGHTER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A30, map_18_state_01_08E80A30, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll have you know that my\npapa has many rare cards.\n\n")
  LANGUAGE_TEXT(1, "Mon papa poss\xe8de plusieurs\ncartes tr\xe8s rares,\n\ntu sais...\n\n")
  LANGUAGE_TEXT(2, "Du solltest wissen, dass\nmein Papa viele seltene\n\nKarten besitzt.\n\n")
  LANGUAGE_TEXT(3, "Ti informo che mio padre\nha molte carte rare.\n\n")
  LANGUAGE_TEXT(4, "Mi pap\xe1 tiene muchas\ncartas raras, \xbfsabes?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A54, map_18_state_01_08E80A54, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(232)
  LANGUAGE_TEXT(0, "I'll get my papa to buy me\nmore rare cards...\n\n")
  LANGUAGE_TEXT(1, "Je vais demander \xe0 mon papa\nde m'acheter d'autres\n\ncartes rares...\n\n")
  LANGUAGE_TEXT(2, "Ich sage meinem Papa,\ner soll mir mehr seltene\n\nKarten kaufen...\n\n")
  LANGUAGE_TEXT(3, "Mi far\xf2 comprare pi\xf9\ncarte rare da mio padre...\n\n")
  LANGUAGE_TEXT(4, "Le dir\xe9 a mi pap\xe1 que me\ncompre m\xe1s cartas raras...\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_RICH_DAUGHTER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A24, map_18_state_01_08E80A24, 0x08E80A3C, 0x08E80A60)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RICH_DAUGHTER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A3C, map_18_state_01_08E80A3C, 0x08E80A54, 0x08E80A48)
  LANGUAGE_TEXT(0, "Fine.\n\n")
  LANGUAGE_TEXT(1, "OK, comme tu veux.\n\n")
  LANGUAGE_TEXT(2, "Na gut.\n\n")
  LANGUAGE_TEXT(3, "Bene, allora.\n\n")
  LANGUAGE_TEXT(4, "Entonces, vale.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(27)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A48, map_18_state_01_08E80A48, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(0)
  CLEAR_FLAG(247)
  CLEAR_FLAG(245)
  CLEAR_FLAG(1)
  CLEAR_FLAG(2)
  CLEAR_FLAG(3)
  CLEAR_FLAG(238)
  CLEAR_FLAG(4)
  CLEAR_FLAG(5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E80A60, map_18_state_01_08E80A60, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Sure, but only after my papa\nbuys me more rare cards.\n\n")
  LANGUAGE_TEXT(1, "Oui, mais d'abord,\nje dois demander\n\n\xe0 mon papa de m'acheter\nd'autres cartes rares.\n\n")
  LANGUAGE_TEXT(2, "Ja, aber erst, wenn mir mein\nPapa seltene Karten kauft.\n\n")
  LANGUAGE_TEXT(3, "S\xec, ma dopo che mio padre\nmi avr\xe0 comprato pi\xf9\n\ncarte rare.\n\n")
  LANGUAGE_TEXT(4, "S\xed, pero despu\xe9s de que\nmi pap\xe1 me compre m\xe1s\n\ncartas raras.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
