#include "event_macros.h"
#include "overworld.h"

/* map_01_state_07: map 1 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E42910, map_01_state_07_08E42910, 0x08E4291C, 0x08F04040)
  PLAY_MUSIC(4)
  MOVE_OBJECT(1, 0, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 2, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  WALK_OBJECT_Y(6, 56)
  WALK_OBJECT_Y(9, 56)
  WALK_OBJECT_Y(7, 64)
  WALK_OBJECT_Y(8, 64)
  DELAY(16)
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "What's taking them so long?\n\n")
  LANGUAGE_TEXT(1, "Eh bien, qu'est-ce\nqu'il leur prend ?\n\n")
  LANGUAGE_TEXT(2, "Mann, warum dauert das\nbei ihnen so lange?\n\n")
  LANGUAGE_TEXT(3, "Come mai ci mettono\ncos\xec tanto?\n\n")
  LANGUAGE_TEXT(4, "T\xedo, \xbfqu\xe9 les pasa?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PORTRAIT(7, 0, 1)
  LANGUAGE_TEXT(0, "Mai! Everybody!\n\n")
  LANGUAGE_TEXT(1, "Mai !\nEt tout le monde !\n\n")
  LANGUAGE_TEXT(2, "Mai!\nUnd alle anderen!\n\n")
  LANGUAGE_TEXT(3, "Mai!\nE tutti gli altri!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mai!\n\xa1Y todos los dem\xe1s!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 16)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "Huh?\n\nWhat are you doing here? Are\nyou better duelists now?\n\n")
  LANGUAGE_TEXT(1, "Hein ?\n\nQu'est-ce que vous\nfaites l\xe0, vous aussi ?\n\nVous \xeates devenus\nplus fort ?\n\n")
  LANGUAGE_TEXT(2, "Ja? Was macht ihr denn\nauch hier?\n\nSeid ihr st\xe4rker geworden?\n\n")
  LANGUAGE_TEXT(3, "Eh?\n\nCome mai siete qui pure voi?\nSiete diventati pi\xf9 forti?\n\n")
  LANGUAGE_TEXT(4, "\xbfEh?\n\n\xbfQu\xe9 haces t\xfa tambi\xe9n aqu\xed?\n\xbfTe has vuelto m\xe1s fuerte?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 0, 1)
  LANGUAGE_TEXT(0, "You bet, Mai!\nLike ultra-strong!\n\n")
  LANGUAGE_TEXT(1, "Et comment, Mai !\nUltra-forts !\n\n")
  LANGUAGE_TEXT(2, "Na klar, Mai!\nUltra-stark!\n\n")
  LANGUAGE_TEXT(3, "Ci puoi scommettere, Mai!\nDirei ultra forti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Y que lo digas, Mai!\n\xa1Ultrafuerte!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, 1, 0, 0)
  DELAY(16)
  PORTRAIT(31, 5, 1)
  LANGUAGE_TEXT(0, "Ultra? Tristan...\n\n")
  LANGUAGE_TEXT(1, "Ultra ?\nTristan...\n\n")
  LANGUAGE_TEXT(2, "Ultra?\nTristan...\n\n")
  LANGUAGE_TEXT(3, "Ultra?\nTristan...\n\n")
  LANGUAGE_TEXT(4, "\xbfUltra?\nTristan...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, 2, 0, 0)
  DELAY(16)
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "Pipipi...\n\nAnd who might you be?\n\n")
  LANGUAGE_TEXT(1, "Pipipi...\n\nEt qui peux-tu\nbien \xeatre ?\n\n")
  LANGUAGE_TEXT(2, "Pipipi...\n\nUnd wer bist du?\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\n\nAddirittura!\n\n")
  LANGUAGE_TEXT(4, "Pipipi...\n\n\xbfY qui\xe9n eres t\xfa?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 28)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "I saw the others over there.\n\nWe've all known each other\nfor a long time... which\n\nhas both its good and bad\npoints.\n\n")
  LANGUAGE_TEXT(1, "J'ai aussi vu les autres\nun peu plus t\xf4t.\n\nDisons qu'il y a comme une\nhistoire entre nous.\n\n")
  LANGUAGE_TEXT(2, "Ich habe die anderen\nauch vorher gesehen.\n\nSagen wir mal, wir\nkennen uns von fr\xfcher.\n\n")
  LANGUAGE_TEXT(3, "Prima ho visto anche\ngli altri. Diciamo solo\n\nche c'\xe8 stato qualche\nproblema tra di noi.\n\n")
  LANGUAGE_TEXT(4, "Tambi\xe9n vi a los\notros antes.\n\nDigamos que hay algo de\nhistoria entre nosotros.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(271)
  REACTION(0, 1022)
  WALK_OBJECT_X(0, 12)
  WALK_OBJECT_X(13, 12)
  WALK_OBJECT_X(14, 12)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(6, 1, 0, 0)
  MOVE_OBJECT(9, 1, 0, 0)
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "J-Joey...\n\n")
  LANGUAGE_TEXT(1, "J-Joey...\n\n")
  LANGUAGE_TEXT(2, "J-Joey...\n\n")
  LANGUAGE_TEXT(3, "J-Joey...\n\n")
  LANGUAGE_TEXT(4, "J-Joey...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 3, 1)
  LANGUAGE_TEXT(0, "J-Joey!\n\n")
  LANGUAGE_TEXT(1, "G-grand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Fratello mio!\n\n")
  LANGUAGE_TEXT(4, "\xa1G-gran hermano!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(394)
  SLIDE_OBJECT(9, 1, 24)
  SLIDE_OBJECT(14, 1, 8)
  DELAY(16)
  PORTRAIT(4, 7, 1)
  LANGUAGE_TEXT(0, "Hey, hold on... Everyone's\nwatching us.\n\n")
  LANGUAGE_TEXT(1, "H\xe9, une minute... Tout\nle monde nous regarde.\n\n")
  LANGUAGE_TEXT(2, "He, warte...\nAlle schaun uns zu.\n\n")
  LANGUAGE_TEXT(3, "Ehi, aspetta...\nTutti ci guardano.\n\n")
  LANGUAGE_TEXT(4, "Hey, espera... Todo el mundo\nnos est\xe1 mirando.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 3, 1)
  LANGUAGE_TEXT(0, "I'm so glad you're safe, big\nbrother.\n\n")
  LANGUAGE_TEXT(1, "Je suis si contente\n\nde te voir sain\net sauf, grand fr\xe8re.\n\n")
  LANGUAGE_TEXT(2, "Ich bin so froh, dass es dir\ngut geht, gro\xdfer Bruder.\n\n")
  LANGUAGE_TEXT(3, "Sono felicissima che\ntu stia bene.\n\n")
  LANGUAGE_TEXT(4, "Estoy tan feliz de que est\xe9s\nbien, gran hermano.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "{BYTE_8169}There's nothing I can do\nabout this.{BYTE_816A}\n\n")
  LANGUAGE_TEXT(1, "{BYTE_8169}Je ne peux rien y faire.{BYTE_816A}\n\n")
  LANGUAGE_TEXT(2, "{BYTE_8169}Ich kann nichts daran\n\xe4ndern.{BYTE_816A}\n\n")
  LANGUAGE_TEXT(3, "{BYTE_8169}Non posso farci niente.{BYTE_816A}\n\n")
  LANGUAGE_TEXT(4, "{BYTE_8169}No hay nada que pueda\nhacer al respecto.{BYTE_816A}\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(1, 1, 1)
  LANGUAGE_TEXT(0, "Everyone... You waited for\nus?\n\nThank you.\n\nWe were able to defeat\nReshef because we had your\n\nhelp.\n\nBut the biggest credit has\nto be given to...\n\nYou, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Tout le monde... Vous\nnous avez attendus ?\n\nMerci.\n\nGr\xe2ce \xe0 vous, nous\navons battu Reshef.\n\nMais la personne qu'il\nfaut surtout remercier...\n\nC'est toi,\n{PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Habt ihr alle auf uns\ngewartet?\n\nDanke.\n\nDank euch konnten wir\nReschef besiegen.\n\nDen gr\xf6\xdften Verdienst\ndaran hast aber du...\n\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Salve a tutti...\nCi aspettavate?\n\nGrazie.\n\nSiamo riusciti a sconfiggere\nReshef grazie a voi.\n\nMa il merito maggiore\nva a...\n\nTe, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "Todos... \xbfEsperasteis\npor nosotros?\n\nGracias.\n\nPudimos derrotar a Reshef\ngracias a vosotros.\n\nPero el mayor cr\xe9dito\nhay que d\xe1rselo a...\n\n\xa1Ti, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "Yugi's right!\n\n{PLAYER} has gotten much\nstronger.\n\nAlmost as strong as me!\n\n")
  LANGUAGE_TEXT(1, "Yugi a raison.\n\n{PLAYER} est\ndevenu bien plus fort.\n\nPresque aussi fort\nque moi, d'ailleurs.\n\n")
  LANGUAGE_TEXT(2, "Stimmt genau, Yugi.\n\n{PLAYER} ist viel\nst\xe4rker geworden.\n\nSogar fast so stark\nwie ich.\n\n")
  LANGUAGE_TEXT(3, "Yugi ha perfettamente\nragione.\n\n{PLAYER} \xe8 diventato\nmolto pi\xf9 forte.\n\nPersino quasi forte\ncome me.\n\n")
  LANGUAGE_TEXT(4, "Yugi est\xe1 en lo cierto.\n\n{PLAYER} se ha hecho\nmucho m\xe1s fuerte.\n\nCasi tan fuerte como yo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4291C, map_01_state_07_08E4291C, 0x08E42928, 0x08E42934)
  WALK_OBJECT_X(10, 84)
  WALK_OBJECT_X(11, 84)
  DELAY(16)
  PORTRAIT(3, 0, 0)
  LANGUAGE_TEXT(0, "Hah! Big talk from a dog!\n\n")
  LANGUAGE_TEXT(1, "Ha ! De belles paroles\npour un minable !\n\n")
  LANGUAGE_TEXT(2, "Hah!\nGro\xdfe Worte von Abschaum!\n\n")
  LANGUAGE_TEXT(3, "Hah! Che spaccone,\nquel buono a nulla!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hah!\n\n\xa1Bonitas palabras\nde un cutre!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(6, 3, 0, 0)
  MOVE_OBJECT(7, 3, 0, 0)
  MOVE_OBJECT(8, 3, 0, 0)
  MOVE_OBJECT(9, 3, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(9, 36)
  WALK_OBJECT_X(14, 12)
  PORTRAIT(4, 5, 1)
  LANGUAGE_TEXT(0, "Why, you... Kaiba, what's\nyour problem?!\n\n")
  LANGUAGE_TEXT(1, "Pourquoi, toi... Kaiba,\nqu'est-ce que tu veux ?!\n\n")
  LANGUAGE_TEXT(2, "Warum, du...\nKaiba, was willst du?!\n\n")
  LANGUAGE_TEXT(3, "Ehi, ma...\nKaiba, cosa vuoi?!\n\n")
  LANGUAGE_TEXT(4, "Pero, t\xfa...\nKaiba, \xa1\xbfqu\xe9 quieres?!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(10, 28)
  SLIDE_OBJECT(8, 0, 8)
  PLAY_MUSIC(275)
  REACTION(5, 384)
  WALK_OBJECT_X(10, 20)
  WALK_OBJECT_Y(10, 48)
  MOVE_OBJECT(10, 1, 0, 0)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(6, 1, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  MOVE_OBJECT(8, 2, 0, 0)
  MOVE_OBJECT(9, 1, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  PORTRAIT(3, 2, 1)
  LANGUAGE_TEXT(0, "{PLAYER}...\n\nThank you for saving Mokuba.\n\nBut you all only survived\nbecause of me.\n\nI'm the one with the\nKaibaCorp helicopter.\n\nThat makes us even.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}...\n\nJe te remercierais\nbien pour ce que tu\n\nas fait pour Mokuba.\n\nMais tu as \xe9t\xe9 sauv\xe9\ngr\xe2ce \xe0 une chose.\n\nL'h\xe9licopt\xe8re de la\nKaiba Corporation.\n\nAlors on est quittes.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}...\n\nDanke f\xfcr das, was du\nf\xfcr Mokuba getan hast.\n\nAber du wurdest nur\ndurch eins gerettet:\n\nDen Hubschrauber der\nKaiba Corporation.\n\nDamit sind wir quitt.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}...\n\nGrazie per quello che\nhai fatto per Mokuba.\n\nMa sei stato portato in\nsalvo qui solo grazie a\n\nuna cosa: l'elicottero\ndella Kaiba Corporation.\n\nCos\xec siamo pari.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}...\n\nTe agradezco lo que\nhiciste por Mokuba.\n\nPero te has salvado\npor una cosa.\n\nEl helic\xf3ptero de\nKaiba Corporation.\n\nEstamos iguales.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(1, 0, 1)
  LANGUAGE_TEXT(0, "Kaiba...\n\n")
  LANGUAGE_TEXT(1, "Seto...\n\n")
  LANGUAGE_TEXT(2, "Seto...\n\n")
  LANGUAGE_TEXT(3, "Seto...\n\n")
  LANGUAGE_TEXT(4, "Seto...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(3, 0, 1)
  LANGUAGE_TEXT(0, "Yugi, I'm done talking.\n\n")
  LANGUAGE_TEXT(1, "Yugi, \xe7a suffit.\nNe me fais pas parler.\n\n")
  LANGUAGE_TEXT(2, "Yugi, genug.\nIch m\xf6chte nicht reden.\n\n")
  LANGUAGE_TEXT(3, "Basta, Yugi.\nNon farmi parlare.\n\n")
  LANGUAGE_TEXT(4, "Yugi, ya basta.\nNo me tires de la lengua.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(1, 0, 1)
  LANGUAGE_TEXT(0, "What?\n\n")
  LANGUAGE_TEXT(1, "Quoi ?\n\n")
  LANGUAGE_TEXT(2, "Was?\n\n")
  LANGUAGE_TEXT(3, "Cosa?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(3, 1, 1)
  LANGUAGE_TEXT(0, "These lame duelists...\n\nI don't want to be\nassociated with them.\n\n")
  LANGUAGE_TEXT(1, "Ces duellistes\nqui sont ici...\n\nJe ne veux pas \xeatre\nassoci\xe9 \xe0 eux.\n\n")
  LANGUAGE_TEXT(2, "Diese gew\xf6hnlichen\nDuellanten hier...\n\nIch m\xf6chte nichts mit\nihnen zu tun haben.\n\n")
  LANGUAGE_TEXT(3, "Con questi normalissimi\nduellanti che si ritrovano\n\nqui...Io non voglio avere\nniente a che fare.\n\n")
  LANGUAGE_TEXT(4, "Estos duelistas comunes\nque hay por aqu\xed...\n\nNo quiero que se me\nrelacione con ellos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 5, 1)
  LANGUAGE_TEXT(0, "You arrogant...\n\n")
  LANGUAGE_TEXT(1, "Eh bien,\nquelle arrogance...\n\n")
  LANGUAGE_TEXT(2, "Du arroganter...\n\n")
  LANGUAGE_TEXT(3, "Razza di arrogante...\n\n")
  LANGUAGE_TEXT(4, "\xbfPor qu\xe9, t\xfa, arrogante...\n\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(3, 0, 1)
  LANGUAGE_TEXT(0, "Real duelists don't need to\nspeak.\n\nThey let their cards do the\ntalking.\n\n")
  LANGUAGE_TEXT(1, "Pas la peine de parler\nentre duellistes.\n\nLaissez les cartes\ns'exprimer.\n\n")
  LANGUAGE_TEXT(2, "Geschickte Duellanten\nbrauchen keine Worte.\n\nSie sprechen durch\nihre Karten.\n\n")
  LANGUAGE_TEXT(3, "Non c'\xe8 bisogno di parole\ntra i duellanti abili.\n\nLasciano che a parlare\nsiano le loro carte.\n\n")
  LANGUAGE_TEXT(4, "No hay necesidad de palabras\nentre h\xe1biles duelistas.\n\nDejan que sus cartas hablen.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(272)
  REACTION(3, 1)
  PORTRAIT(3, 2, 1)
  LANGUAGE_TEXT(0, "{PLAYER}! The next time we\nmeet, things will be\n\ndifferent!\n\nYou're a speedbump on my\nroad to victory, and I will\n\ndefeat you!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} ! Notre\nprochaine rencontre\n\nsera diff\xe9rente !\n\nJe serais \xe0 nouveau sur\nle chemin de la victoire !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}! Unsere n\xe4chste\nBegegnung wird anders!\n\nDann werde ich wieder auf\ndem Weg zum Sieg sein!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}! Il nostro\nprossimo incontro sar\xe0\n\ndiverso! Riprender\xf2 il mio\ncammino verso la vittoria!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}! \xa1La pr\xf3xima\nvez que nos encontremos\n\nser\xe1 diferente!\n\n\xa1Retomar\xe9 mi camino\na la victoria!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(3, 1, 1)
  LANGUAGE_TEXT(0, "Until then, savor the taste\nof victory!\n\nCome on, Mokuba.\n\n")
  LANGUAGE_TEXT(1, "En attendant, appr\xe9cie\nau maximum ta victoire !\n\nAllez, Mokuba.\n\n")
  LANGUAGE_TEXT(2, "Bis dahin kannst du ruhig\ndeinen Ruhm auskosten!\n\nNa komm schon, Mokuba.\n\n")
  LANGUAGE_TEXT(3, "Fino a quel momento, goditi\nil gusto della vittoria!\n\nForza, Mokuba.\n\n")
  LANGUAGE_TEXT(4, "Hasta entonces, \xa1degusta el\nsabor de la victoria!\n\nVamos, Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(10, 64)
  SLIDE_OBJECT(8, 1, 8)
  PLAY_MUSIC(274)
  REACTION(4, 384)
  WALK_OBJECT_Y(10, 96)
  WALK_OBJECT_Y(11, 64)
  WALK_OBJECT_X(11, 20)
  WALK_OBJECT_Y(11, 48)
  MOVE_OBJECT(11, 1, 0, 0)
  PORTRAIT(10, 0, 1)
  LANGUAGE_TEXT(0, "Heheh, saved!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 h\xe9, sauv\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Heheh, gerettet!\n\n")
  LANGUAGE_TEXT(3, "Heheh, salvati!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jejeje, salvado!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(11, 0, 0, 0)
  DELAY(16)
  PORTRAIT(10, 0, 1)
  LANGUAGE_TEXT(0, "Wait for me, big brother!\n\n")
  LANGUAGE_TEXT(1, "Attends-moi,\ngrand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Warte auf mich,\ngro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Aspettami, fratello!\n\n")
  LANGUAGE_TEXT(4, "\xa1Esp\xe9rame,\ngran hermano!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(11, 96)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "That guy... He invented the\nword {BYTE_8168}annoying.{BYTE_8168}\n\n")
  LANGUAGE_TEXT(1, "Ce type... Qu'est-ce\nqu'il est pr\xe9tentieux.\n\n")
  LANGUAGE_TEXT(2, "Dieser Typ...\nGanz sch\xf6n eingebildet.\n\n")
  LANGUAGE_TEXT(3, "Quel ragazzo...\n\xc8 un concentrato di vanit\xe0.\n\n")
  LANGUAGE_TEXT(4, "Ese chico...\nMenudo engre\xeddo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "Kaiba has a point, you know.\n\nWe all helped create a new\nrival.\n\n")
  LANGUAGE_TEXT(1, "Kaiba n'a pas enti\xe8rement\ntort, tu sais.\n\nNous avons coop\xe9r\xe9\net nous avons gagn\xe9\n\nun puissant rival.\n\n")
  LANGUAGE_TEXT(2, "Kaiba hat aber Recht.\n\nWir haben zusammengear-\nbeitet und wurden so stark.\n\n")
  LANGUAGE_TEXT(3, "Sapete, Kaiba ha un\nmotivo per essere cos\xec.\n\nAbbiamo collaborato e\nsiamo diventati un\n\nrivale potente.\n\n")
  LANGUAGE_TEXT(4, "Kaiba tiene raz\xf3n, \xbfsabes?\n\nCooperamos y terminamos\nhaciendo un rival poderoso.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(6, 2, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  MOVE_OBJECT(8, 2, 0, 0)
  MOVE_OBJECT(9, 2, 0, 0)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "Mai... That's not very\nnice...\n\n")
  LANGUAGE_TEXT(1, "Mai... Comment\npeux-tu dire \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Mai... Wie konntest du\ndas nur sagen?\n\n")
  LANGUAGE_TEXT(3, "Mai... Come fai a dire\nuna cosa del genere?\n\n")
  LANGUAGE_TEXT(4, "Mai... \xbfC\xf3mo puedes\ndecir algo as\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(6, 0, 1)
  LANGUAGE_TEXT(0, "I'm joking.\n\nWe're friends, but we're\nalso duelists. All of us.\n\nAfter I leave, I'll work on\nmy deck.\n\nAll right, Yugi, Joey,\n{PLAYER}. See you.\n\n")
  LANGUAGE_TEXT(1, "Je plaisante.\n\nMais nous tous, nous\nsommes des duellistes.\n\nJe vais partir et\ntravailler sur mon Deck.\n\nOK, Yugi, Joey,\n{PLAYER}. A bient\xf4t.\n\n")
  LANGUAGE_TEXT(2, "Ich mache nur Spa\xdf.\n\nAber wir sind auch\nDuellanten. Wir alle.\n\nWenn ich gehe, dann feile\nich an meinem Deck.\n\nOkay, Yugi, Joey,\n{PLAYER}. Bis sp\xe4ter.\n\n")
  LANGUAGE_TEXT(3, "Sto scherzando.\n\nMa siamo anche duellanti.\nTutti noi lo siamo.\n\nQuando me ne andr\xf2,\nlavorer\xf2 al mio deck.\n\nAllora, ci si vede, Yugi,\nJoey e {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "S\xf3lo bromeo.\n\nPero tambi\xe9n somos\nduelistas. Todos nosotros.\n\nCuando me vaya,\ntrabajar\xe9 en mi deck.\n\nVale, Yugi, Joey,\n{PLAYER}. Nos vemos.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(1, 32)
  WALK_OBJECT_X(1, 0)
  MOVE_OBJECT(1, 1, 16, 0)
  WALK_OBJECT_Y(2, 32)
  WALK_OBJECT_X(2, 20)
  MOVE_OBJECT(2, 0, 0, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  MOVE_OBJECT(6, 2, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  MOVE_OBJECT(8, 2, 0, 0)
  MOVE_OBJECT(9, 2, 0, 0)
  PORTRAIT(14, 0, 1)
  LANGUAGE_TEXT(0, "You sure went through a lot.\n\nI think it's time we left\ntoo.\n\n")
  LANGUAGE_TEXT(1, "Vous avez eu pas\nmal d'aventure.\n\nIl est temps que nous\npartions, nous aussi.\n\n")
  LANGUAGE_TEXT(2, "Ihr habt wirklich einiges\nmitgemacht.\n\nIch glaube, wir sollten\njetzt auch gehen.\n\n")
  LANGUAGE_TEXT(3, "Sicuramente ne avrete\npassati di brutti momenti.\n\nPenso che sia ora che\nanche noi ce ne andiamo.\n\n")
  LANGUAGE_TEXT(4, "Hab\xe9is pasado\nmuchos pesares.\n\nCreo que es hora\nde que nos vayamos.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(2, 0)
  MOVE_OBJECT(2, 1, 8, 0)
  WALK_OBJECT_Y(3, 32)
  WALK_OBJECT_X(3, 20)
  MOVE_OBJECT(3, 0, 0, 0)
  PORTRAIT(0, 0, 1)
  LANGUAGE_TEXT(0, "Good bye!\n\n")
  LANGUAGE_TEXT(1, "Au revoir !\n\n")
  LANGUAGE_TEXT(2, "Lebt wohl!\n\n")
  LANGUAGE_TEXT(3, "Arrivederci!\n\n")
  LANGUAGE_TEXT(4, "\xa1Adi\xf3s!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, 1, 8, 0)
  WALK_OBJECT_X(4, 20)
  MOVE_OBJECT(4, 0, 0, 0)
  LANGUAGE_TEXT(0, "See you!\n\n")
  LANGUAGE_TEXT(1, "A bient\xf4t !\n\n")
  LANGUAGE_TEXT(2, "Bis sp\xe4ter!\n\n")
  LANGUAGE_TEXT(3, "Ci si vede!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nos vemos!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, 1, 8, 0)
  WALK_OBJECT_X(5, 20)
  MOVE_OBJECT(5, 0, 0, 0)
  LANGUAGE_TEXT(0, "Bye-bye!\n\n")
  LANGUAGE_TEXT(1, "Salut !\n\n")
  LANGUAGE_TEXT(2, "Tsch\xfcs!\n\n")
  LANGUAGE_TEXT(3, "Ciao!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hasta luego!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(5, 0)
  MOVE_OBJECT(5, 1, 8, 0)
  DELAY(16)
  WALK_OBJECT_Y(6, 40)
  MOVE_OBJECT(6, 1, 0, 0)
  WALK_OBJECT_Y(9, 48)
  WALK_OBJECT_X(9, 28)
  WALK_OBJECT_X(8, 28)
  WALK_OBJECT_Y(8, 56)
  MOVE_OBJECT(8, 1, 0, 0)
  WALK_OBJECT_X(7, 20)
  WALK_OBJECT_Y(7, 56)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(1, 0, 1)
  LANGUAGE_TEXT(0, "It's over, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "C'est termin\xe9,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Es ist vorbei, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "\xc8 finita, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Se acab\xf3, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "You were awesome, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Tu as \xe9t\xe9 g\xe9nial,\n{PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Du warst Klasse, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Sei stato eccezionale,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Has estado tremendo,\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(0, 0, 0, 0)
  PORTRAIT(9, 0, 1)
  LANGUAGE_TEXT(0, "Totally, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Tu as \xe9t\xe9 g\xe9nial, {PLAYER} !\n\n\n")
  LANGUAGE_TEXT(2, "Du warst Klasse, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Sei stato eccezionale,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xa1Has estado tremendo,\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 0, 1)
  LANGUAGE_TEXT(0, "Yeah, you really did great.\n\n")
  LANGUAGE_TEXT(1, "Ouais, tu as vraiment\nfait du bon boulot.\n\n")
  LANGUAGE_TEXT(2, "Ja, das hast du wirklich\ngut gemacht.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, sei proprio\nandato alla grande.\n\n")
  LANGUAGE_TEXT(4, "S\xed, has estado genial.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(0, 3, 0, 0)
  PORTRAIT(32, 0, 1)
  LANGUAGE_TEXT(0, "I'm impressed, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je suis impressionn\xe9e,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich bin beeindruckt,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Mi hai proprio sorpreso,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Estoy impresionada,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(7, 3, 1)
  LANGUAGE_TEXT(0, "You had us all worried...\n\n")
  LANGUAGE_TEXT(1, "On \xe9tait tous inquiets\n\xe0 cause de toi...\n\n")
  LANGUAGE_TEXT(2, "Wir hatten uns schon Sorgen\ngemacht...\n\n")
  LANGUAGE_TEXT(3, "Eravamo tutti\npreoccupati...\n\n")
  LANGUAGE_TEXT(4, "Nos ten\xedas preocupados...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(7, 0, 1)
  LANGUAGE_TEXT(0, "I'm so glad you're safe.\n\n")
  LANGUAGE_TEXT(1, "Heureusement,\ntu es sain et sauf.\n\n")
  LANGUAGE_TEXT(2, "Ich bin so froh, dass du in\nSicherheit bist.\n\n")
  LANGUAGE_TEXT(3, "Sono felicissima che\ntutto sia andato bene.\n\n")
  LANGUAGE_TEXT(4, "Estoy tan feliz de\nque est\xe9s bien.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(12, 37)
  WALK_OBJECT_Y(12, 32)
  WALK_OBJECT_X(12, 20)
  MOVE_OBJECT(12, 0, 0, 0)
  PORTRAIT(16, 1, 1)
  LANGUAGE_TEXT(0, "Thank you for everything.\n\n")
  LANGUAGE_TEXT(1, "Merci pour tout\nce que tu as fais.\n\n")
  LANGUAGE_TEXT(2, "Danke f\xfcr alles, was du\ngetan hast.\n\n")
  LANGUAGE_TEXT(3, "Grazie per tutto quello\nche hai fatto.\n\n")
  LANGUAGE_TEXT(4, "Gracias por todo\nlo que has hecho.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 1)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(6, 2, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  MOVE_OBJECT(8, 2, 0, 0)
  MOVE_OBJECT(9, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  PORTRAIT(16, 0, 1)
  LANGUAGE_TEXT(0, "Reshef the Dark Being will\nmost likely never rise\n\nagain.\n\nWe owe it all to you,\n{PLAYER}.\n\nTo prevent this tragedy from\nreoccurring...\n\nI would like to seal the\nEgyptian God Cards away.\n\nMay I have your Egyptian God\nCards?\n\n")
  LANGUAGE_TEXT(1, "Reshef, l'Etre des t\xe9n\xe8bres\nne reviendra plus.\n\nEt ceci gr\xe2ce \xe0 toi,\n{PLAYER}.\n\nJe n'aimerais pas que\ncela se reproduise...\n\nJ'aimerais pouvoir\nenfermer \xe0 l'abri\n\nla carte de dieu.\n\nEst-ce que je peux avoir\nles cartes de dieux\n\nque tu poss\xe8des ?\n\n")
  LANGUAGE_TEXT(2, "Reschef der Dunkle wird\nvermutlich nie wieder\n\nauferstehen.\n\nDas verdanken wir nur dir,\n{PLAYER}.\n\nIch m\xf6chte verhindern, dass\nes noch einmal geschieht...\n\nUnd m\xf6chte daher die\nG\xf6tterkarten versiegeln.\n\nGibst du mir deine\nG\xf6tterkarten?\n\n")
  LANGUAGE_TEXT(3, "Reshef il Tenebroso\nnon ritorner\xe0 pi\xf9.\n\nTutto questo lo dobbiamo\na te, {PLAYER}.\n\nVorrei che questo non si\nripetesse mai pi\xf9...\n\nPerci\xf2 vorrei rinchiudere\nper sempre la carta divina.\n\nPosso avere le carte\ndivine che hai con te?\n\n")
  LANGUAGE_TEXT(4, "Reshef, el Ser Oscuro\nprobablemente no\n\nvuelva a levantar cabeza.\n\nTodo te lo debemos\na ti, {PLAYER}.\n\nMe gustar\xeda evitar que\nvolviera a ocurrir...\n\nPor lo que me gustar\xeda\nsellar la carta del dios.\n\n\xbfMe das las cartas de los\ndioses que llevas?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 1)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42928, map_01_state_07_08E42928, 0x08E42940, 0x08F04040)
  WALK_OBJECT_X(0, 20)
  WALK_OBJECT_Y(0, 40)
  DELAY(16)
  PLAY_MUSIC(285)
  WALK_OBJECT_Y(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  PORTRAIT(16, 1, 1)
  LANGUAGE_TEXT(0, "Thank you...\n\nReshef was vanquished before\nit could engulf the world.\n\n{PLAYER}, you stopped it.\n\nThank you, and farewell.\n\n")
  LANGUAGE_TEXT(1, "Merci...\n\nReshef a disparu avant\nde d\xe9truire le monde.\n\nEt cela gr\xe2ce \xe0 toi,\n{PLAYER}.\n\nMerci et adieu.\n\n")
  LANGUAGE_TEXT(2, "Danke...\n\nReschef wurde vernichtet,\nbevor er die Welt in\n\nFinsternis st\xfcrzen konnte.\n\n{PLAYER}, das haben wir\ndir zu verdanken.\n\nDanke und lebe wohl.\n\n")
  LANGUAGE_TEXT(3, "Grazie...\n\nReshef \xe8 stato vinto prima\nche riuscisse a fare\n\npiombare il mondo nelle\ntenebre. {PLAYER},\n\ntu lo hai reso possibile.\nGrazie e addio.\n\n")
  LANGUAGE_TEXT(4, "Gracias...\n\nReshef ha sido\nvencido antes de\n\nque pudiera oscu-\nrecer el mundo.\n\n{PLAYER}, t\xfa lo\nhas hecho posible.\n\nGracias, y adi\xf3s.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(12, 0)
  SHOW_OBJECT(12, 128, 96, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42940, map_01_state_07_08E42940, 0x08F04040, 0x08F04040)
  DELAY(64)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(4, 5, 1)
  LANGUAGE_TEXT(0, "Whew... That really was\nsomething, wasn't it?\n\n")
  LANGUAGE_TEXT(1, "Eh bien... C'\xe9tait\nsi difficile que \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Wow... Das war vielleicht\nein Abenteuer, nicht wahr?\n\n")
  LANGUAGE_TEXT(3, "Fi\xf9\xf9... Gran bella\navventura, eh?\n\n")
  LANGUAGE_TEXT(4, "Vaya... No ha estado\nmal, \xbfeh?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(6, 1, 0, 0)
  MOVE_OBJECT(7, 1, 0, 0)
  MOVE_OBJECT(8, 1, 0, 0)
  MOVE_OBJECT(9, 1, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  DELAY(16)
  PORTRAIT(1, 1, 1)
  LANGUAGE_TEXT(0, "You're right.\n\nEven the spirit was nervous.\n\n{PLAYER}, you were great.\n\n")
  LANGUAGE_TEXT(1, "Tu as raison.\n\nM\xeame mon autre\nmoi \xe9tait intimid\xe9.\n\nMais {PLAYER}, tu\nas vraiment \xe9t\xe9 g\xe9nial.\n\n")
  LANGUAGE_TEXT(2, "Ja.\n\nSelbst mein anderes Ich\nf\xfcrchtete sich.\n\nAber du, {PLAYER}, warst\nSpitze.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, proprio cos\xec.\n\nAnche l'altro me stesso ha\nprovato timore. Ma per la\n\nmiseria, {PLAYER}, sei\nstato grande davvero.\n\n")
  LANGUAGE_TEXT(4, "Tienes raz\xf3n.\n\nIncluso mi otra mitad\nestaba impresionada.\n\nPero, t\xedo, {PLAYER},\nhas estado genial.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "What about me? I wasn't too\nshabby myself!\n\n")
  LANGUAGE_TEXT(1, "Et moi ? Je ne m'en\nsuis pas bien sorti ?\n\n")
  LANGUAGE_TEXT(2, "Na, und ich?\nWar ich etwa nicht gut?\n\n")
  LANGUAGE_TEXT(3, "E io allora?\nNon sono stato grande?\n\n")
  LANGUAGE_TEXT(4, "\xbfY qu\xe9 hay de m\xed?\n\xbfNo lo hice bien?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 9153)
  DELAY(16)
  PORTRAIT(9, 0, 1)
  LANGUAGE_TEXT(0, "Yeah, I'm sure you did\nalright.\n\n")
  LANGUAGE_TEXT(1, "Oh si, je suis s\xfbr que\ntu t'en es bien sorti.\n\n")
  LANGUAGE_TEXT(2, "Ja, du warst bestimmt\nauch toll.\n\n")
  LANGUAGE_TEXT(3, "Ma certo che lo sei\nstato anche tu.\n\n")
  LANGUAGE_TEXT(4, "S\xed, estoy seguro de que\ntambi\xe9n lo hiciste bien.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(14, 3, 0, 0)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "Tristan! Yeah, you got that\nright!\n\nI knew you'd understand,\npartna!\n\n")
  LANGUAGE_TEXT(1, "Tristan ! Ouais, tu as\nraison, tu le sais !\n\nJe savais que tu\ncomprendrais, mon ami !\n\n")
  LANGUAGE_TEXT(2, "Tristan! Ja genau!\n\nIch wusste, du w\xfcrdest es\nverstehen, mein Freund!\n\n")
  LANGUAGE_TEXT(3, "Tristan! Hai proprio\ndetto bene, sai!\n\nSapevo che avresti\ncapito, amico mio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tristan! S\xed, lo has\nentendido bien, \xa1lo sabes!\n\n\xa1Sab\xeda que lo entender\xedas,\namigo m\xedo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 0, 1)
  LANGUAGE_TEXT(0, "You bet I do!\n\nYou did your best to help\nYugi and {PLAYER}...\n\nBy staying out of their way!\n\n")
  LANGUAGE_TEXT(1, "Et plut\xf4t !\n\nTu as fait de ton mieux pour\naider Yugi et {PLAYER}...\n\nEn restant le plus\nloin d'eux possible !\n\n")
  LANGUAGE_TEXT(2, "Darauf kannst du wetten!\n\nDu hast dein Bestes getan\num Yugi und {PLAYER}\n\nzu helfen... indem du ihnen\nnicht im Weg standst!\n\n")
  LANGUAGE_TEXT(3, "Vorrei vedere!\n\nHai fatto del tuo meglio\nper aiutare Yugi e\n\n{PLAYER}... Tenendoti\nalla debita distanza, per\xf2!\n\n")
  LANGUAGE_TEXT(4, "\xa1Por supuesto!\n\nHiciste todo lo que\npudiste para ayudar\n\na Yugi y {PLAYER}...\n\n\xa1Qued\xe1ndote fuera\nde su camino!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "Right, I tried not to cause\nany trouble and...\n\n")
  LANGUAGE_TEXT(1, "Ben ouais, je voulais\npas les emb\xeater...\n\n")
  LANGUAGE_TEXT(2, "Ja, ich wollte keine\nBelastung f\xfcr sie sein...\n\n")
  LANGUAGE_TEXT(3, "Certo, ho cercato di non\nessere un peso...\n\n")
  LANGUAGE_TEXT(4, "S\xed, intent\xe9 no\nser una carga...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 16384)
  PLAY_MUSIC(275)
  REACTION(5, 16384)
  DELAY(8)
  PORTRAIT(4, 5, 1)
  LANGUAGE_TEXT(0, "Wait! Why would I have to\nstay out of their way?!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 ! Mais pourquoi\nje devais rester\n\nle plus loin d'eux\npossible ?!\n\n")
  LANGUAGE_TEXT(2, "Warte! Warum sollte ich\nihnen aus dem Weg gehen\n\nm\xfcssen?!\n\n")
  LANGUAGE_TEXT(3, "Aspetta! Perch\xe9 mi sarei\ntenuto a debita distanza?!\n\n")
  LANGUAGE_TEXT(4, "\xa1Un momento! \xa1\xbfPor qu\xe9\ntendr\xeda yo que estar\n\nfuera de su camino?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 1, 1)
  LANGUAGE_TEXT(0, "Hahaha, sorry, sorry.\n\nChill out, dude.\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha, d\xe9sol\xe9, d\xe9sol\xe9.\n\nPas la peine de t'\xe9nerver,\nJoey.\n\n")
  LANGUAGE_TEXT(2, "Hahaha, tut mir Leid.\n\nReg dich nicht auf, Joey.\n\n")
  LANGUAGE_TEXT(3, "Hahaha, scusa, scusa.\n\nNon c'\xe8 bisogno che ti\nscaldi tanto, Joey.\n\n")
  LANGUAGE_TEXT(4, "Jajaja, perd\xf3n, perd\xf3n.\n\nNo te enfades, Joey.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 1)
  LANGUAGE_TEXT(0, "Looks like everything's back\nto normal. Back to the\n\nusual Town of Domino.\n\n")
  LANGUAGE_TEXT(1, "H\xe9, mais on est\nde retour \xe0 Domino.\n\n")
  LANGUAGE_TEXT(2, "He, wir sind zur\xfcck. Im\ngewohnten Domino.\n\n")
  LANGUAGE_TEXT(3, "Ehi, siamo tornati, o no?\nNella Domino normale.\n\n")
  LANGUAGE_TEXT(4, "Hey, pero estamos\nde vuelta.\n\nDe vuelta a la Domino\nde siempre.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(1, 1, 1)
  LANGUAGE_TEXT(0, "Yeah...\n\n")
  LANGUAGE_TEXT(1, "Ouais...\n\n")
  LANGUAGE_TEXT(2, "Ja...\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0...\n\n")
  LANGUAGE_TEXT(4, "S\xed...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 0, 1)
  LANGUAGE_TEXT(0, "Welcome back.\n\n")
  LANGUAGE_TEXT(1, "Soyez \xe0 nouveau\nles bienvenus.\n\n")
  LANGUAGE_TEXT(2, "Willkommen daheim.\n\n")
  LANGUAGE_TEXT(3, "Bentornati.\n\n")
  LANGUAGE_TEXT(4, "Bienvenidos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 0, 1)
  LANGUAGE_TEXT(0, "I'm amazed you came back.\n\n")
  LANGUAGE_TEXT(1, "Je suis \xe9tonn\xe9 de\nvous voir de retour.\n\n")
  LANGUAGE_TEXT(2, "Ich bin \xfcberrascht, dass ihr\nes zur\xfcckgeschafft habt.\n\n")
  LANGUAGE_TEXT(3, "Sono sorpreso che\nsiate riusciti a tornare.\n\n")
  LANGUAGE_TEXT(4, "Me alucina que\nhay\xe1is vuelto.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 0, 1)
  LANGUAGE_TEXT(0, "Welcome home.\n\n")
  LANGUAGE_TEXT(1, "Bienvenue chez vous.\n\n")
  LANGUAGE_TEXT(2, "Willkommen daheim.\n\n")
  LANGUAGE_TEXT(3, "Bentornati a casa.\n\n")
  LANGUAGE_TEXT(4, "Bienvenidos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(7, 0, 1)
  LANGUAGE_TEXT(0, "Welcome home, everyone!\n\n")
  LANGUAGE_TEXT(1, "Bienvenue chez vous,\n\xe0 vous tous !\n\n")
  LANGUAGE_TEXT(2, "Euch allen ein herzliches\nWillkommen daheim!\n\n")
  LANGUAGE_TEXT(3, "Benvenuti a casa!\n\n")
  LANGUAGE_TEXT(4, "\xa1Bienvenidos, todos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  COMMAND_7C_ARG(2, 8)
  FADE_SCREEN(8)
  WARP(51, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42934, map_01_state_07_08E42934, 0x08E42928, 0x08E42934)
  PORTRAIT(16, 6, 1)
  LANGUAGE_TEXT(0, "Do you want to become just\nlike Pegasus?\n\nThe Egyptian God Cards must\nbe hidden from the world.\n\nPlease, may I have the\nEgyptian God Cards?\n\n")
  LANGUAGE_TEXT(1, "Est-ce que tu veux devenir\nun deuxi\xe8me Pegasus ?\n\nLes cartes de dieux\ndoivent \xeatre enferm\xe9es.\n\nTu veux bien me donner\nles cartes de dieux ?\n\n")
  LANGUAGE_TEXT(2, "Willst du etwa der zweite\nPegasus werden?\n\nDie G\xf6tterkarten d\xfcrfen\nnicht frei in der Welt\n\nbleiben.\nGibst du sie mir bitte?\n\n")
  LANGUAGE_TEXT(3, "Vuoi forse diventare il\nsecondo Pegasus?\n\nLe carte divine non devono\nuscire nel mondo.\n\nTi prego, vuoi darmi\nle carte divine?\n\n")
  LANGUAGE_TEXT(4, "\xbfQuieres decir ser\nel segundo Pegasus?\n\nLas cartas de los dioses no\ndeben andar por el mundo.\n\nPor favor, \xbfme puedes dar\nlas cartas de los dioses?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
