#include "event_macros.h"
#include "overworld.h"

/* map_06_state_09: map 6 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD74, map_06_state_09_08E5CD74, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(33)
  DELAY(64)
  SET_OBJECT_POSITION(4, 74, 40, 0)
  DELAY(48)
  WALK_OBJECT_Y(4, 48)
  DELAY(16)
  PLAY_MUSIC(324)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 8)
  LANGUAGE_TEXT(0, "Ukkiii!\n\n")
  LANGUAGE_TEXT(1, "Ukkiii !\n\n")
  LANGUAGE_TEXT(2, "Ukkiii!\n\n")
  LANGUAGE_TEXT(3, "Ukkiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukkiii!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 6, 8)
  LANGUAGE_TEXT(0, "Oh! This monkey...\n\n")
  LANGUAGE_TEXT(1, "Oh !\nCe singe...\n\n")
  LANGUAGE_TEXT(2, "Oh!\nDieser Affe...\n\n")
  LANGUAGE_TEXT(3, "Oh! Questa scimmia...\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh!\nEste mono...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 52)
  DELAY(16)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 8)
  LANGUAGE_TEXT(0, "Uki, uki. uki.\n\n")
  LANGUAGE_TEXT(1, "Uki, uki. uki.\n\n")
  LANGUAGE_TEXT(2, "Uki, uki. uki.\n\n")
  LANGUAGE_TEXT(3, "Uki, uki, uki.\n\n")
  LANGUAGE_TEXT(4, "Uki, uki. uki.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(273)
  REACTION(2, 16)
  WALK_OBJECT_X(1, 96)
  DELAY(16)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff kl\xe4ff kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, 3, 0, 0)
  WALK_OBJECT_X(1, 76)
  DELAY(16)
  WALK_OBJECT_X(4, 68)
  DELAY(16)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf.\n\n")
  LANGUAGE_TEXT(1, "Wouf.\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau.\n\n")
  LANGUAGE_TEXT(4, "Arf.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 8)
  LANGUAGE_TEXT(0, "Uki!\n\n")
  LANGUAGE_TEXT(1, "Uki !\n\n")
  LANGUAGE_TEXT(2, "Uki!\n\n")
  LANGUAGE_TEXT(3, "Uki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(326)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 8)
  LANGUAGE_TEXT(0, "Uki uki.\n\n")
  LANGUAGE_TEXT(1, "Uki uki.\n\n")
  LANGUAGE_TEXT(2, "Uki uki.\n\n")
  LANGUAGE_TEXT(3, "Uki uki.\n\n")
  LANGUAGE_TEXT(4, "Uki uki.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 0, 8)
  LANGUAGE_TEXT(0, "I read that monkeys and dogs\ndon't get along...\n\nBut this monkey and Lucky\nseem like best friends.\n\n")
  LANGUAGE_TEXT(1, "Les singes\net les chiens\n\nne sont pas\ncens\xe9s s'entendre...\n\nMais Lucky et ce singe ont\nl'air d'\xeatre li\xe9s d'amiti\xe9.\n\n")
  LANGUAGE_TEXT(2, "Affen und Hunde vertragen\nsich angeblich nicht...\n\nAber dieser Affe und Lucky\nsind die besten Freunde.\n\n")
  LANGUAGE_TEXT(3, "Di solito cani e scimmie\nnon vanno d'accordo...\n\nMa questa scimmia e Lucky\nsembrano molto amici.\n\n")
  LANGUAGE_TEXT(4, "Se supone que los\nperros y los monos\n\nno se llevan bien...\n\nPero este mono y\nLucky parecen\n\nbuenos amigos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "It can't be... This monkey\nrobot...\n\nCould it be Tristan?\n\n")
  LANGUAGE_TEXT(1, "C'est pas possible...\nHein... Ce singe robot...\n\nEst-ce que \xe7a pourrait\n\xeatre Tristan ?\n\n")
  LANGUAGE_TEXT(2, "Nicht m\xf6glich... Uh...\nDieser Affenroboter...\n\nK\xf6nnte es Tristan sein?\n\n")
  LANGUAGE_TEXT(3, "Non pu\xf2 essere... Uh...\nQuesta scimmia robot...\n\nNon sar\xe0 mica Tristan?\n\n")
  LANGUAGE_TEXT(4, "No puede ser... Uh...\nEste robot mono...\n\n\xbfPodr\xeda ser Tristan?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8)
  DELAY(8)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SERENITY, 6, 8)
  LANGUAGE_TEXT(0, "Really?!\n\nTristan turned into a robot?\n\n")
  LANGUAGE_TEXT(1, "Tu crois ?!\n\nTristan serait\ndevenu un robot ?\n\n")
  LANGUAGE_TEXT(2, "Wirklich?!\n\nTristan wurde in diesen\nRoboter verwandelt?\n\n")
  LANGUAGE_TEXT(3, "Davvero?!\n\nTristan si \xe8 trasformato\nin questo robot?\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfEn serio?!\n\n\xbfTristan convertido\nen este robot?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "Lucky is Tristan's dog, and\nit's getting along great\n\nwith this robot.\n\nThat's all the proof I need.\n\n")
  LANGUAGE_TEXT(1, "Regarde comme Lucky\na l'air de bien l'aimer.\n\nLucky est le chien de\nTristan, voil\xe0 pourquoi.\n\n")
  LANGUAGE_TEXT(2, "Schau, wie zugetan Lucky\nihm ist.\n\nLucky ist Tristans Hund,\ndas beweist es doch wohl.\n\n")
  LANGUAGE_TEXT(3, "Guardate come va\nd'accordo con Lucky.\n\nLucky \xe8 il cane di Tristan,\ne questo spiega tutto.\n\n")
  LANGUAGE_TEXT(4, "Mira qu\xe9 cari\xf1oso\nes Lucky con \xe9l.\n\nLucky es el perro de\nTristan; eso lo prueba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 0, 8)
  LANGUAGE_TEXT(0, "I... I guess so.\n\n")
  LANGUAGE_TEXT(1, "Oui... Tu dois avoir raison.\n\n")
  LANGUAGE_TEXT(2, "Ich... Ich glaube schon.\n\n")
  LANGUAGE_TEXT(3, "Dev'essere cos\xec...\n\n")
  LANGUAGE_TEXT(4, "Su... supongo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "And...\n\n")
  LANGUAGE_TEXT(1, "Et en plus...\n\n")
  LANGUAGE_TEXT(2, "Und...\n\n")
  LANGUAGE_TEXT(3, "E...\n\n")
  LANGUAGE_TEXT(4, "Y...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 0, 8)
  LANGUAGE_TEXT(0, "And?\n\n")
  LANGUAGE_TEXT(1, "Quoi ?\n\n")
  LANGUAGE_TEXT(2, "Und?\n\n")
  LANGUAGE_TEXT(3, "E cosa?\n\n")
  LANGUAGE_TEXT(4, "\xbfY?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "This may be another\nrepercussion due to\n\nReshef's resurrection.\n\n")
  LANGUAGE_TEXT(1, "Ca a peut-\xeatre\nquelque chose \xe0 voir\n\navec le retour de Reshef.\n\n")
  LANGUAGE_TEXT(2, "Es k\xf6nnte mit Reschefs\nR\xfcckkehr zusammenh\xe4ngen.\n\n")
  LANGUAGE_TEXT(3, "Questo pu\xf2 avere a che fare\ncon il ritorno di Reshef.\n\n")
  LANGUAGE_TEXT(4, "Puede que tenga relaci\xf3n\ncon el regreso de Reshef.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 6, 8)
  LANGUAGE_TEXT(0, "H-how...\n\n")
  LANGUAGE_TEXT(1, "M-mais...\n\n")
  LANGUAGE_TEXT(2, "A-aber...\n\n")
  LANGUAGE_TEXT(3, "M-ma...\n\n")
  LANGUAGE_TEXT(4, "Pe-pero...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "Who other reason can you\nthink of?\n\nI mean, if this was the\nvirtual world, I wouldn't\n\nbe surprised if Tristan\nturned into a monkey.\n\nBut a guy can't turn into a\nrobot in real life.\n\n")
  LANGUAGE_TEXT(1, "Je ne serais pas surpris si\non \xe9tait dans le monde\n\nvirtuel. Mais dans la vraie\nvie, un homme ne peut pas\n\ndevenir un robot. Il n'y a\npas d'autre explication.\n\n")
  LANGUAGE_TEXT(2, "Es w\xfcrde mich nicht \xfcber-\nraschen, wenn das die\n\nvirtuelle Welt ist.\n\nIn der Realit\xe4t kann sich\ndoch niemand in einen\n\nRoboter verwandeln.\n\nAnders kann man es\nnicht erkl\xe4ren.\n\n")
  LANGUAGE_TEXT(3, "Non mi sorprenderei se\nfosse il mondo virtuale.\n\nMa un ragazzo non si pu\xf2\ntrasformare in robot nella\n\nvita reale. Non c'\xe8 altra\nspiegazione possibile.\n\n")
  LANGUAGE_TEXT(4, "No me extra\xf1ar\xeda si\nfuera el mundo virtual.\n\nPero un chico no\npuede transformarse\n\nen robot en la vida real.\n\nNo hay otro modo\nde explicarlo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, 0, 8)
  LANGUAGE_TEXT(0, "I... I guess so.\n\n")
  LANGUAGE_TEXT(1, "Tu...Tu dois avoir raison.\n\n")
  LANGUAGE_TEXT(2, "\xc4h... das stimmt wohl.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0... Lo penso anch'io.\n\n")
  LANGUAGE_TEXT(4, "Eso... eso supongo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 5, 8)
  LANGUAGE_TEXT(0, "But if this is true...\nTristan might never regain\n\nhis human form...\n\n")
  LANGUAGE_TEXT(1, "Si c'est le cas...\nTristan risque\n\nde ne jamais retrouver\nsa forme humaine...\n\n")
  LANGUAGE_TEXT(2, "Das w\xfcrde bedeuten...\ndass Tristan vielleicht nie\n\nwieder er selbst wird.\n\n")
  LANGUAGE_TEXT(3, "In tal caso... Tristan\npotrebbe non riassumere\n\nmai la sua forma umana...\n\n")
  LANGUAGE_TEXT(4, "Si es as\xed... Puede\nque Tristan nunca\n\nrecupere su forma\nhumana...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 16)
  DELAY(8)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(8)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "Ukiiiiiiii!\n\n")
  LANGUAGE_TEXT(1, "Ukiiiiiiii !\n\n")
  LANGUAGE_TEXT(2, "Ukiiiiiiii!\n\n")
  LANGUAGE_TEXT(3, "Ukiiiiiiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiiiiiiii!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 144)
  PORTRAIT(PORTRAIT_SERENITY, 6, 8)
  LANGUAGE_TEXT(0, "Tristan!\n\n")
  LANGUAGE_TEXT(1, "Tristan !\n\n")
  LANGUAGE_TEXT(2, "Tristan!\n\n")
  LANGUAGE_TEXT(3, "Tristan!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tristan!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, 0, 8)
  LANGUAGE_TEXT(0, "Tristan!\n\n")
  LANGUAGE_TEXT(1, "Tristan !\n\n")
  LANGUAGE_TEXT(2, "Tristan!\n\n")
  LANGUAGE_TEXT(3, "Tristan!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tristan!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  WARP(6, 10, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
