#include "event_macros.h"
#include "overworld.h"

/* map_15_state_01: map 15 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E7A458, map_15_state_01_08E7A458, 0x08E7A464, 0x08E7A470)
  PLAY_MUSIC(231)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The Duel Express is reserved\nfor duelists only...\n\nI'm raring to go!\n\n")
  LANGUAGE_TEXT(1, "Le Duel Express est\nr\xe9serv\xe9 aux duellistes...\n\nJe suis impatient\nde partir !\n\n")
  LANGUAGE_TEXT(2, "Der Duel Express - nur\nf\xfcr Duellanten...\n\nIch will jetzt losfahren!\n\n")
  LANGUAGE_TEXT(3, "Il Duel Express solo\nper i duellanti...\n\nNon vedo l'ora di andare!\n\n")
  LANGUAGE_TEXT(4, "El Duel Express s\xf3lo\npara duelistas...\n\n\xa1Me muero por ir!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Our objective is...\nI won't lose!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Notre objectif, c'est...\nJe ne vais pas perdre !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Unser Ziel lautet...\nIch verliere nicht!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Il nostro obiettivo \xe8...\nIo non perder\xf2!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Nuestro objetivo es...\n\xa1No perder\xe9!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A464, map_15_state_01_08E7A464, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yeah, I know.\n\nBut if we raise our duelist\nlevel while we look for the\n\nMillennium Items...\n\nThat's like killing two\nbirds with one stone.\n\n")
  LANGUAGE_TEXT(1, "Ouais, je sais.\n\nOn devrait am\xe9liorer\nnotre niveau de duelliste\n\nau fur et \xe0 mesure.\n\nComme \xe7a, on ferait\nd'une pierre deux coups.\n\n")
  LANGUAGE_TEXT(2, "Ja, schon klar.\n\nAber wir sollten\ngleichzeitig unsere\n\nDuellantenstufe erh\xf6hen.\n\nDamit schlagen wir zwei\nFliegen mit einer Klappe.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, lo so.\n\nMa dovremmo alzare\nil nostro livello duellante\n\ndurante il percorso. Cos\xec\nprenderemo due\n\npiccioni con una fava.\n\n")
  LANGUAGE_TEXT(4, "S\xed, lo s\xe9.\n\nPero deber\xedamos elevar\nnuestro nivel de duelo\n\nmientras vamos.\n\nEso es matar dos\np\xe1jaros de un tiro.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A470, map_15_state_01_08E7A470, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Me neither!\n\nIt'll be a while until we\nreach the Egypt Exhibition.\n\nLet's raise our duelist\nlevels while we can!\n\n")
  LANGUAGE_TEXT(1, "Moi non plus !\n\nOn va mettre un bout\nde temps avant d'arriver \xe0\n\nl'Exposition \xe9gyptienne.\n\nEssayons d'am\xe9liorer\nnotre niveau en chemin.\n\n")
  LANGUAGE_TEXT(2, "Ich auch nicht!\n\nEs wird etwas dauern, bis\nwir zur \xe4gypt. Ausstellung\n\nkommen. Wir sollten uns\nunterwegs mit unserem\n\nDuellanten-Level befassen!\n\n")
  LANGUAGE_TEXT(3, "Neanche io!\n\nCi vorr\xe0 un bel po' per\narrivare alla Mostra\n\nEgizia. Nel frattempo,\nlavoriamo ai nostri\n\nlivelli duellante!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo tampoco!\n\nTardar\xe1 lo suyo en llegar a\nla Exposici\xf3n Egipcia.\n\n\xa1Mejoremos los niveles de\nduelo mientras vamos!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A47C, map_15_state_01_08E7A47C, 0x08E7A494, 0x08E7A4B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A494, map_15_state_01_08E7A494, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "W-")
  LANGUAGE_TEXT(1, "Q-")
  LANGUAGE_TEXT(2, "W-")
  LANGUAGE_TEXT(3, "Che-")
  LANGUAGE_TEXT(4, "\xbfQ-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "w-")
  LANGUAGE_TEXT(1, "q-")
  LANGUAGE_TEXT(2, "w-")
  LANGUAGE_TEXT(3, "che-")
  LANGUAGE_TEXT(4, "q-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "w-")
  LANGUAGE_TEXT(1, "q-")
  LANGUAGE_TEXT(2, "w-")
  LANGUAGE_TEXT(3, "che ")
  LANGUAGE_TEXT(4, "q-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "what?\n\nI-")
  LANGUAGE_TEXT(1, "quoi ?\n\nJe-")
  LANGUAGE_TEXT(2, "was?\n\nI-")
  LANGUAGE_TEXT(3, "cosa?\n\nI-")
  LANGUAGE_TEXT(4, "qu\xe9?\n\n\xa1N-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "I-")
  LANGUAGE_TEXT(1, "je-")
  LANGUAGE_TEXT(2, "I-")
  LANGUAGE_TEXT(3, "i-")
  LANGUAGE_TEXT(4, "n-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "I-")
  LANGUAGE_TEXT(1, "je-")
  LANGUAGE_TEXT(2, "I-")
  LANGUAGE_TEXT(3, "i-")
  LANGUAGE_TEXT(4, "n-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "I'm\nn-")
  LANGUAGE_TEXT(1, "je ")
  LANGUAGE_TEXT(2, "Ich bin n-")
  LANGUAGE_TEXT(3, "io no-non so-")
  LANGUAGE_TEXT(4, "no e-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "not ")
  LANGUAGE_TEXT(1, "ne ")
  LANGUAGE_TEXT(2, "nicht\n")
  LANGUAGE_TEXT(3, "so-")
  LANGUAGE_TEXT(4, "estoy\n")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "n-n-nervous!\n\n")
  LANGUAGE_TEXT(1, "suis\npas nerveux !\n\n")
  LANGUAGE_TEXT(2, "n-n-nerv\xf6s!\n\n")
  LANGUAGE_TEXT(3, "sono\nn-n-nervoso!\n\n")
  LANGUAGE_TEXT(4, "ne-nervioso!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4B8, map_15_state_01_08E7A4B8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "That one duel calmed me\ndown!\n\nThank you!\n\n")
  LANGUAGE_TEXT(1, "Ce duel avec toi,\n\xe7a m'a calm\xe9 !\n\nMerci beaucoup !\n\n")
  LANGUAGE_TEXT(2, "Das eine Duell mit dir\nhat mich beruhigt!\n\nDanke!\n\n")
  LANGUAGE_TEXT(3, "Duellare con te\nmi ha proprio calmato!\n\nGrazie!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ese duelo contigo me calm\xf3\npor completo!\n\n\xa1Gracias!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A488, map_15_state_01_08E7A488, 0x08E7A4A0, 0x08E7A4B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4A0, map_15_state_01_08E7A4A0, 0x08E7A4AC, 0x08F0404C)
  LANGUAGE_TEXT(0, "W-")
  LANGUAGE_TEXT(1, "B-")
  LANGUAGE_TEXT(2, "N-")
  LANGUAGE_TEXT(3, "B-")
  LANGUAGE_TEXT(4, "B-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "w-")
  LANGUAGE_TEXT(1, "b-")
  LANGUAGE_TEXT(2, "n-")
  LANGUAGE_TEXT(3, "b-")
  LANGUAGE_TEXT(4, "b-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "w-")
  LANGUAGE_TEXT(1, "b-")
  LANGUAGE_TEXT(2, "n-")
  LANGUAGE_TEXT(3, "b-")
  LANGUAGE_TEXT(4, "b-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "well, okay.\n\nI-")
  LANGUAGE_TEXT(1, "bien, OK.\nUn d-")
  LANGUAGE_TEXT(2, "na okay.\nD-")
  LANGUAGE_TEXT(3, "bene, okay.\nD-")
  LANGUAGE_TEXT(4, "bueno, vale.\n\xa1L-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "i-")
  LANGUAGE_TEXT(1, "d-")
  LANGUAGE_TEXT(2, "D-")
  LANGUAGE_TEXT(3, "d-")
  LANGUAGE_TEXT(4, "lu-")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "it's t-t-time to\nd-d-d-duel!\n\n")
  LANGUAGE_TEXT(1, "duel !\n\n")
  LANGUAGE_TEXT(2, "Duell!\n\n")
  LANGUAGE_TEXT(3, "duelliamo!\n\n")
  LANGUAGE_TEXT(4, "luchemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(17)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4AC, map_15_state_01_08E7A4AC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "Wow, ")
  LANGUAGE_TEXT(1, "Waouh, ")
  LANGUAGE_TEXT(2, "Wow, ")
  LANGUAGE_TEXT(3, "Uau, ")
  LANGUAGE_TEXT(4, "Vaya, ")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "losing helped me relax.\nThere's no more pressure to\n\nwin.\n\n")
  LANGUAGE_TEXT(1, "rien que de perdre,\nje me sens plus d\xe9tendu.\n\n")
  LANGUAGE_TEXT(2, "durch die Niederlage\nkann ich mich entspannen.\n\nIch f\xfchle mich nicht mehr so\nangespannt.\n\n")
  LANGUAGE_TEXT(3, "perdere mi ha\naiutato a rilassarmi.\n\nLa tensione \xe8 sparita.\n\n")
  LANGUAGE_TEXT(4, "perder me relaja.\nNo me siento tenso.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_NERVOUS_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4C4, map_15_state_01_08E7A4C4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "What a motley crew of\npathetic duelists.\n\n")
  LANGUAGE_TEXT(1, "Cette bande de duellistes a\nvraiment l'air trop nulle.\n\n")
  LANGUAGE_TEXT(2, "Was f\xfcr ein miserables Team\nschwacher Duellanten.\n\n")
  LANGUAGE_TEXT(3, "Che bel miscuglio di\nduellanti fiacchi.\n\n")
  LANGUAGE_TEXT(4, "Vaya panda de\ndebiluchos duelistas.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4D0, map_15_state_01_08E7A4D0, 0x08E7A4DC, 0x08E7A4F4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_ARROGANT_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4DC, map_15_state_01_08E7A4DC, 0x08E7A4E8, 0x08F0404C)
  LANGUAGE_TEXT(0, "Why? The tourney hasn't\nstarted yet, and we still\n\nhaven't boarded the Duel\nExpress!\n\nBut I like your spunk!\nI accept your challenge!\n\n")
  LANGUAGE_TEXT(1, "Le tournoi commence avant le\nd\xe9part du Duel Express ?\n\nCa me pla\xeet !\nJe rel\xe8ve ton d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Das Turnier startet vor der\nAbfahrt des Duel Express?\n\nDas gef\xe4llt mir! Ich nehme\ndeine Herausforderung an!\n\n")
  LANGUAGE_TEXT(3, "Il torneo ha inizio prima\nche parta il Duel Express?\n\nMi piace!\nAccetto la tua sfida!\n\n")
  LANGUAGE_TEXT(4, "\xbfEl torneo est\xe1 en\nmarcha antes de que\n\nruede el Duel Express?\n\n\xa1Me gusta!\n\xa1Acepto el reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(18)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4E8, map_15_state_01_08E7A4E8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "I'm saving my real\nstrategies for the\n\ntournament..\n\n")
  LANGUAGE_TEXT(1, "Je me r\xe9serve pour\nle vrai truc.\n\n")
  LANGUAGE_TEXT(2, "Meine besten Karten spare\nich allerdings f\xfcr das\n\nernste Duell auf.\n\n")
  LANGUAGE_TEXT(3, "Riservo le mie abilit\xe0\nmigliori per il torneo\n\nprincipale.\n\n")
  LANGUAGE_TEXT(4, "Reservo lo mejor\npara lo bueno.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_ARROGANT_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A4F4, map_15_state_01_08E7A4F4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll take you on again\ninside the train.\n\n")
  LANGUAGE_TEXT(1, "Je t'affronterai encore\nune fois dans le train.\n\n")
  LANGUAGE_TEXT(2, "Im Zug will ich meine\nRevanche.\n\n")
  LANGUAGE_TEXT(3, "Ti sfider\xf2 di nuovo\nsul treno.\n\n")
  LANGUAGE_TEXT(4, "Te retar\xe9 de nuevo\nen el tren.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A50C, map_15_state_01_08E7A50C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Everyone looks so tough.\n\nI'm not sure if I can last\nuntil the end.\n\n")
  LANGUAGE_TEXT(1, "Tout le monde\na l'air si fort.\n\nJe ne suis pas s\xfbr\nde pouvoir m'en sortir.\n\n")
  LANGUAGE_TEXT(2, "Sie sehen alle so entschlos-\nsen aus.\n\nOb ich es wohl bis zum Ende\ndurchhalte?\n\n")
  LANGUAGE_TEXT(3, "Sembrano tutti forti.\n\nNon so se ce la far\xf2 a\ntenere duro fino alla fine.\n\n")
  LANGUAGE_TEXT(4, "Todos parecen tan\nfuertes.\n\nNo s\xe9 si podr\xe9\naguantar hasta el fin.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A500, map_15_state_01_08E7A500, 0x08E7A518, 0x08E7A530)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_INSECURE_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A518, map_15_state_01_08E7A518, 0x08E7A524, 0x08F0404C)
  LANGUAGE_TEXT(0, "But you don't look so\ntough...\n\n")
  LANGUAGE_TEXT(1, "Enfin, toi... ")
  LANGUAGE_TEXT(2, "Na, du... ")
  LANGUAGE_TEXT(3, "Be', tu... ")
  LANGUAGE_TEXT(4, "Bien, t\xfa...\n")
  END_LANGUAGE_TEXT()
  DELAY(8)
  LANGUAGE_TEXT(0, "I think I can beat you.\n\n")
  LANGUAGE_TEXT(1, "Je crois que\nj'arriverai \xe0 te battre.\n\n")
  LANGUAGE_TEXT(2, "Ich glaube, dass\nich dich durchaus schlagen\n\nkann.\n\n")
  LANGUAGE_TEXT(3, "Penso di\nriuscire a batterti.\n\n")
  LANGUAGE_TEXT(4, "Creo que te puedo vencer.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(19)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A524, map_15_state_01_08E7A524, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "How could I lose to someone\nlike you?\n\n")
  LANGUAGE_TEXT(1, "Comment est-ce que\nje pourrais perdre\n\ncontre quelqu'un\ncomme toi ?\n\n")
  LANGUAGE_TEXT(2, "Wie konnte ich nur gegen\njemanden wie dich\n\nverlieren?\n\n")
  LANGUAGE_TEXT(3, "Come ho fatto a perdere\ncon te?\n\n")
  LANGUAGE_TEXT(4, "\xbfC\xf3mo puede perder\ncon alguien como t\xfa?\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_INSECURE_DUELIST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A530, map_15_state_01_08E7A530, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm fixing my deck.\n\n")
  LANGUAGE_TEXT(1, "Je travaille\nsur mon Deck.\n\n")
  LANGUAGE_TEXT(2, "Ich arbeite an meinem\nDeck.\n\n")
  LANGUAGE_TEXT(3, "Sto lavorando al\nmio deck.\n\n")
  LANGUAGE_TEXT(4, "Trabajo en mi deck.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A53C, map_15_state_01_08E7A53C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "KaibaCorp sure knows how to\nthrow an event.\n\nThey're letting us ride a\nchartered express train for\n\nfree.\n\n")
  LANGUAGE_TEXT(1, "La Kaiba Corporation sait\norganiser les \xe9v\xe8nements.\n\nElle affr\xe8te gratuitement\ndes trains express.\n\n")
  LANGUAGE_TEXT(2, "Die Kaiba Corporation wei\xdf,\nwie man etwas stilvoll\n\nin Szene setzt. Ein kosten-\nloser Charterzug.\n\n")
  LANGUAGE_TEXT(3, "La Kaiba Corporation sa\norganizzare proprio bene\n\ngli eventi. Ci fa salire\ngratuitamente su un\n\nespresso tutto per noi.\n\n")
  LANGUAGE_TEXT(4, "Kaiba Corporation sabe c\xf3mo\nmontar un evento.\n\nNos dejan viajar en\nun tren ch\xe1rter gratis.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A548, map_15_state_01_08E7A548, 0x08E7A554, 0x08E7A56C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_KAIBA_CORP_ADMIRER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A554, map_15_state_01_08E7A554, 0x08E7A560, 0x08F0404C)
  LANGUAGE_TEXT(0, "Huh, sure.\n\n")
  LANGUAGE_TEXT(1, "Heu, ouais, c'est s\xfbr.\n\n")
  LANGUAGE_TEXT(2, "\xc4h, ja, klar.\n\n")
  LANGUAGE_TEXT(3, "Come? Ma certo.\n\n")
  LANGUAGE_TEXT(4, "Ah, claro.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(20)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A560, map_15_state_01_08E7A560, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "Oh, yup, I lost. But that\nwas fun.\n\n")
  LANGUAGE_TEXT(1, "Oh, ouaip, j'ai perdu.\nMais je me suis bien amus\xe9.\n\n")
  LANGUAGE_TEXT(2, "Oh, ja, ich habe verloren.\nAber es hat Spa\xdf gemacht.\n\n")
  LANGUAGE_TEXT(3, "E cos\xec, ho perso.\nMa \xe8 stato divertente.\n\n")
  LANGUAGE_TEXT(4, "Oh, s\xed, perd\xed.\nPero me divert\xed.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_KAIBA_CORP_ADMIRER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A56C, map_15_state_01_08E7A56C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The train's leaving soon.\nNext time.\n\n")
  LANGUAGE_TEXT(1, "Le train part bient\xf4t.\nLa prochaine fois.\n\n")
  LANGUAGE_TEXT(2, "Der Zug f\xe4hrt bald ab.\nBeim n\xe4chsten Mal.\n\n")
  LANGUAGE_TEXT(3, "Il treno sta per partire.\nUn'altra volta.\n\n")
  LANGUAGE_TEXT(4, "El tren sale pronto.\nLa pr\xf3xima vez.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A578, map_15_state_01_08E7A578, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Duel Express is bound\nfor the Egypt Exhibition.\n\nThe station is very crowded\ndue to the duel tournament.\n\nPlease board the train in an\norderly manner.\n\n")
  LANGUAGE_TEXT(1, "Le Duel Express est\npr\xeat \xe0 partir pour\n\nl'Exposition \xe9gyptienne.\n\nIl y a beaucoup de monde\nen gare pour ce tournoi.\n\nVeuillez faire la queue\npour monter \xe0 bord.\n\n")
  LANGUAGE_TEXT(2, "Der Duel Express f\xe4hrt zur\n\xe4gypt. Ausstellung.\n\nDer Bahnhof ist beim Duell-\nTurnier sehr \xfcberlaufen.\n\nSteigt bitte gesittet ein.\n\n")
  LANGUAGE_TEXT(3, "Il Duel Express \xe8 diretto\nalla Mostra Egizia.\n\nLa stazione \xe8 molto\naffollata per il torneo di\n\nduelli. Salite con ordine\na bordo del treno.\n\n")
  LANGUAGE_TEXT(4, "El Duel Express va\na la Exposici\xf3n Egipcia.\n\nLa estaci\xf3n est\xe1 muy\nllena por el torneo.\n\nSuban al tren\nordenadamente.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A584, map_15_state_01_08E7A584, 0x08E7A590, 0x08E7A5A8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A590, map_15_state_01_08E7A590, 0x08E7A59C, 0x08F0404C)
  LANGUAGE_TEXT(0, "Uhh, I'm on duty...\n\nB-but, I did want to give\nthis game a try.\n\nLet's duel!\n\n")
  LANGUAGE_TEXT(1, "Mmm, je suis\nde service...\n\nM-mais, je veux bien\naussi essayer.\n\nAllez, battons-nous\nen duel !\n\n")
  LANGUAGE_TEXT(2, "\xc4h, ich bin im Dienst...\n\nA-aber ich w\xfcrde es gerne\nversuchen.\n\nDuellieren wir uns!\n\n")
  LANGUAGE_TEXT(3, "Veramente, sono\nin servizio...\n\nPer\xf2, vorrei proprio\nprovarci.\n\nDuelliamo pure!\n\n")
  LANGUAGE_TEXT(4, "Uh, estoy trabajando...\n\nP-pero quer\xeda probar.\n\n\xa1Luchemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(21)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A59C, map_15_state_01_08E7A59C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "I quite enjoyed that.\n\n")
  LANGUAGE_TEXT(1, "Dis donc,\n\xe7a m'a bien plu.\n\n")
  LANGUAGE_TEXT(2, "Das hat wirklich Spa\xdf\ngemacht.\n\n")
  LANGUAGE_TEXT(3, "Mi \xe8 piaciuto.\n\n")
  LANGUAGE_TEXT(4, "Lo he pasado bien.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7A5A8, map_15_state_01_08E7A5A8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The next stop is the Egypt\nExhibition.\n\n")
  LANGUAGE_TEXT(1, "Prochain arr\xeat :\nl'Exposition \xe9gyptienne.\n\n")
  LANGUAGE_TEXT(2, "Der n\xe4chste Halt ist die\n\xe4gypt. Ausstellung.\n\n")
  LANGUAGE_TEXT(3, "La prossima fermata \xe8\nla Mostra Egizia.\n\n")
  LANGUAGE_TEXT(4, "La pr\xf3xima parada\nes la Exposici\xf3n Egipcia.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
