#include "event_macros.h"
#include "overworld.h"

/* map_23_state_05: map 23 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E95480, map_23_state_05_08E95480, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(17)
  DELAY(64)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "I know exactly how hard\n{PLAYER} has worked to get\n\nthis far.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "{PLAYER} is worthy of having\nthe Egyptian God Cards.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  WARP(48, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
