#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_04_state_06: map 4 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E4D1C8, map_04_state_06_08E4D1C8, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_KID_3)
  LOAD_SPRITE(2, SPRITE_KID_3_2)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  TEXT("Let's duel!")
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  TEXT("Okay.")
  FADE_SCREEN(8)
  WARP(LOCATION_CLOCK_TOWER_SQUARE_SOUTHWEST, 6, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
