#include "event_macros.h"
#include "overworld.h"

/* map_00_state_08: map 0 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E34BF8, map_00_state_08_08E34BF8, 0x08E34C10, 0x08E34C1C)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_ROD_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C10, map_00_state_08_08E34C10, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I see you have obtained the\nMillennium Rod.\n\nOnly two Millennium Items\nremain...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24579)
  PLAY_MUSIC(264)
  COMMAND_7C_ARG(7, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef the Dark Being's\npower grows catastrophic!\n\nTime is running out!\n\nPlease search for the next\nMillennium Item.\n\nThe next Millennium Item\nis.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\n\nIn the Galapagos Islands.\nPlease hurry.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_ROD_TO_ISHIZU)
  SET_FLAG(EVENT_FLAG_UNLOCKED_GALAPAGOS)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C1C, map_00_state_08_08E34C1C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Dark Being was\nresurrected by Sol\n\nChevalsky...\n\nI'm sorry, I meant Pegasus.\n\nTo imprison Reshef, we need\none more Egyptian God Card.\n\nWe need the power of The\nWinged Dragon of Ra.\n\nWe must resurrect the card\nfrom stone.\n\nPlease find the Millennium\nItem to restore it.\n\nThe sixth Millennium Item is\nin the Galapagos Islands.\n\nPlease, you must hurry.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C04, map_00_state_08_08E34C04, 0x08E34C10, 0x08E34C28)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_ROD_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C28, map_00_state_08_08E34C28, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Please. Hurry to the\nGalapagos Islands.\n\nReshef the Dark Being will\nsoon engulf the world in\n\nshadows.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
