#include "event_macros.h"
#include "overworld.h"

/* map_06_state_08: map 6 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD68, map_06_state_08_08E5CD68, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(33)
  DELAY(16)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff kl\xe4ff kl\xe4ff kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau bau bau bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 0, 8)
  LANGUAGE_TEXT(0, "Lucky, what's wrong?\n\n")
  LANGUAGE_TEXT(1, "Lucky, il y a quelque\nchose qui ne va pas ?\n\n")
  LANGUAGE_TEXT(2, "Lucky, was ist los?\n\n")
  LANGUAGE_TEXT(3, "Lucky, che c'\xe8 che non va?\n\n")
  LANGUAGE_TEXT(4, "Lucky, \xbfqu\xe9 pasa?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 3, 0, 0)
  WALK_OBJECT_X(0, 80)
  WALK_OBJECT_X(13, 90)
  WALK_OBJECT_X(14, 90)
  DELAY(16)
  PORTRAIT(32, 0, 8)
  LANGUAGE_TEXT(0, "Hey Joey!\n\n")
  LANGUAGE_TEXT(1, "Oh, grand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Oh, gro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Oh, fratello mio!\n\n")
  LANGUAGE_TEXT(4, "Oh, \xa1gran hermano!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}! Yugi and Joey!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} !\nYugi et Joey !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}!\nYugi und Joey!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}!\nYugi e Joey!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER}!\n\xa1Yugi y Joey!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(32)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(32)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(4, 0, 8)
  LANGUAGE_TEXT(0, "Is Tristan around? I don't\nsee him...\n\n")
  LANGUAGE_TEXT(1, "Tristan n'est pas l\xe0 ?\nJe ne le vois pas...\n\n")
  LANGUAGE_TEXT(2, "Ist Tristan nicht hier?\nIch kann ihn nicht sehen...\n\n")
  LANGUAGE_TEXT(3, "Tristan non \xe8 qui?\nNon lo vedo...\n\n")
  LANGUAGE_TEXT(4, "\xbfNo est\xe1 Tristan\npor aqu\xed?\n\nNo le veo...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 3, 8)
  LANGUAGE_TEXT(0, "H-he...\n\n")
  LANGUAGE_TEXT(1, "E-eh...\n\n")
  LANGUAGE_TEXT(2, "E-er...\n\n")
  LANGUAGE_TEXT(3, "L-lui...\n\n")
  LANGUAGE_TEXT(4, "E-el...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 3, 8)
  LANGUAGE_TEXT(0, "T-Tristan...\n\n")
  LANGUAGE_TEXT(1, "T-Tristan...\n\n")
  LANGUAGE_TEXT(2, "T-Tristan...\n\n")
  LANGUAGE_TEXT(3, "T-Tristan...\n\n")
  LANGUAGE_TEXT(4, "T-Tristan...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  PORTRAIT(1, 6, 8)
  LANGUAGE_TEXT(0, "Is something wrong?\n\n")
  LANGUAGE_TEXT(1, "Il y a quelque chose\nqui ne va pas ?\n\n")
  LANGUAGE_TEXT(2, "Was ist los?\n\n")
  LANGUAGE_TEXT(3, "Qualcosa non va?\n\n")
  LANGUAGE_TEXT(4, "\xbfPasa algo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 2, 8)
  LANGUAGE_TEXT(0, "What? Did somethin' happen\nto Tristan?\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Quelque chose\nest arriv\xe9 \xe0 Tristan ?\n\n")
  LANGUAGE_TEXT(2, "Was? Ist etwas mit\nTristan passiert?\n\n")
  LANGUAGE_TEXT(3, "Cosa? \xc8 successo\nqualcosa a Tristan?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? \xbfLe ha pasado\nalgo a Tristan?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 12)
  WALK_OBJECT_X(14, 52)
  WALK_OBJECT_Y(14, 40)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(4, 2, 8)
  LANGUAGE_TEXT(0, "Serenity! Tell me! What\nhappened to Tristan?\n\n")
  LANGUAGE_TEXT(1, "Serenity ! Qu'est-ce\nqui ne va pas ?\n\nIl est arriv\xe9 quelque\nchose \xe0 Tristan ?\n\n")
  LANGUAGE_TEXT(2, "Serenity! Was ist los? Was\nist mit Tristan passiert?\n\n")
  LANGUAGE_TEXT(3, "Serenity! Qualcosa non va?\nCos'\xe8 successo a Tristan?\n\n")
  LANGUAGE_TEXT(4, "\xa1Serenity! \xbfQu\xe9 pasa? \xbfQu\xe9\nle ha pasado a Tristan?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(32, 3, 8)
  LANGUAGE_TEXT(0, "Joey...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder...\n\n")
  LANGUAGE_TEXT(3, "Oh, fratello...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 3, 8)
  LANGUAGE_TEXT(0, "Joey... Tristan isn't\nhere...\n\n")
  LANGUAGE_TEXT(1, "Joey...\nTristan n'est pas l\xe0...\n\n")
  LANGUAGE_TEXT(2, "Joey...\nTristan ist nicht hier...\n\n")
  LANGUAGE_TEXT(3, "Joey...\nTristan non \xe8 qui...\n\n")
  LANGUAGE_TEXT(4, "Joey...\nTristan no est\xe1...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 56)
  WALK_OBJECT_X(13, 63)
  DELAY(16)
  PORTRAIT(1, 0, 8)
  LANGUAGE_TEXT(0, "Duh, I can see that. So\nwhere is he?\n\n")
  LANGUAGE_TEXT(1, "Je le vois bien.\nMais o\xf9 est-il ?\n\n")
  LANGUAGE_TEXT(2, "Das sehe ich auch.\nWo ist er also?\n\n")
  LANGUAGE_TEXT(3, "Lo vedo. Allora dov'\xe8?\n\n")
  LANGUAGE_TEXT(4, "Ya lo veo.\n\xbfD\xf3nde est\xe1?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  SET_FLAG(243)
  WARP(6, 9, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
