#include "event_macros.h"
#include "overworld.h"

/* map_38_state_01: map 38 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED1640, map_38_state_01_08ED1640, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  DELAY(32)
  WALK_OBJECT_X(1, 40)
  DELAY(32)
  WALK_OBJECT_Y(1, 48)
  DELAY(32)
  WALK_OBJECT_X(1, 56)
  DELAY(32)
  WALK_OBJECT_Y(1, 40)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hyohyohyohyohyo!\n\nThis island is a treasure\ntrove of rare insects!\n\n")
  LANGUAGE_TEXT(1, "Hyo hyo hyo !\n\nCette \xeele regorge\nd'insectes rares !\n\n")
  LANGUAGE_TEXT(2, "Hyohyohyohyohyo!\n\nDiese Insel ist eine Schatz-\ntruhe f\xfcr seltene Insekten!\n\n")
  LANGUAGE_TEXT(3, "Ahahahahahahah!\n\nQuest'isola racchiude\nun tesoro d'insetti rari!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hyohyohyohyohyo!\n\n\xa1Esta isla es un teso-\nro de insectos raros!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_SAW_WEEVIL_TALK_TO_HIMSELF)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED164C, map_38_state_01_08ED164C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hyo? You're trying to steal\nmy beautiful bugs, aren't\n\nyou?\n\nI'm not sharing any of them\nwith you!\n\n")
  LANGUAGE_TEXT(1, "Tu essaies de voler\nmes insectes, c'est \xe7a ?\n\nJe ne partage pas avec toi !\n\n")
  LANGUAGE_TEXT(2, "Hyo? Du willst wohl meine\nInsekten stehlen?\n\nMit dir teile ich aber\nnicht!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Vuoi per caso\nrubarmi gli insetti?\n\nIo non ho niente\nda spartire con te!\n\n")
  LANGUAGE_TEXT(4, "\xbfHyo? T\xfa quieres ro-\nbar mis insectos, \xbfno?\n\n\xa1No comparto nada\ncontigo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1658, map_38_state_01_08ED1658, 0x08ED1664, 0x08ED167C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_WEEVIL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1664, map_38_state_01_08ED1664, 0x08ED1670, 0x08F0404C)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hyohyohyohyohyo! You measly\nmaggot!\n\nYou must have the brains of\na louse to challenge a\n\nformer champion!\n\nPrepare for a bug bashing\nwith my Super Insect Deck!\n\n")
  LANGUAGE_TEXT(1, "Hyo hyo hyo !\nPetit imb\xe9cile !\n\nJe suis l'ancien champion\nde duel japonais !\n\nTu es courageux,\nmais aussi tr\xe8s b\xeate !\n\nRegarde \xe0 quel point\nmon super Deck\n\nd'insectes est puissant !\n\n")
  LANGUAGE_TEXT(2, "Hyohyohyohyohyo!\nDu Narr!\n\nIch bin der fr\xfchere japan.\nDuellmeister!\n\nDu hast Mut, bist aber\nsehr dumm!\n\nLern die Kraft meines Super-\nInsektendecks kennen!\n\n")
  LANGUAGE_TEXT(3, "Uahahahahahah!\nStupido ragazzo!\n\nSono l'ex campione\ndi duelli giapponese!\n\nHai coraggio, ma sei\nmolto stupido!\n\nGuarda la potenza del mio\nsuper deck di insetti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hyohyohyohyohyo!\n\xa1Ni\xf1o tonto!\n\n\xa1Soy el actual campe\xf3n\nde duelo del Jap\xf3n!\n\n\xa1Eres valiente,\npero tonto!\n\n\xa1Mira el poder de mi\nsuperdeck de insectos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(49)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1670, map_38_state_01_08ED1670, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't get cocky! That was a\nfluke!\n\n")
  LANGUAGE_TEXT(1, "Ne crois pas que\ntu sois bon !\n\nTu n'as gagn\xe9 que\npar chance !\n\n")
  LANGUAGE_TEXT(2, "Glaub nicht, dass du gut\nbist! Du hast doch nur\n\ndurch einen Trick\ngewonnen!\n\n")
  LANGUAGE_TEXT(3, "Non credere di essere bravo!\nHai vinto solo per un pelo!\n\n")
  LANGUAGE_TEXT(4, "\xa1No creas que eres bueno!\n\xa1Has ganado de suerte!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_WEEVIL)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED167C, map_38_state_01_08ED167C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I caught most of the rare\ninsects in this area.\n\nI think I'll go to China\nnext.\n\n")
  LANGUAGE_TEXT(1, "J'ai attrap\xe9 la plupart\ndes insectes rares\n\ndans les parages.\n\nJe crois qu'ensuite,\nj'irai en Chine.\n\n")
  LANGUAGE_TEXT(2, "Ich habe die meisten\nseltenen Insekten hier\n\nerwischt.\n\nIch glaube, als N\xe4chstes\nfahre ich nach China.\n\n")
  LANGUAGE_TEXT(3, "Ho raccolto quasi tutti\ngli insetti rari che ci\n\nsono qui intorno.\n\nPenso che ora me\nne andr\xf2 in Cina.\n\n")
  LANGUAGE_TEXT(4, "He cogido la mayor\xeda\nde los insectos raros\n\nde por aqu\xed.\n\nCreo que la pr\xf3xima\nvez ir\xe9 a China.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
