#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_32_state_07: map 32 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08EB9114, map_32_state_07_08EB9114, 0x08EB9120, 0x08EB9168)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You'll proceed no further\n"
    "without defeating me!\n\n"
)
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_080)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9120, map_32_state_07_08EB9120, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_242)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Most impressive.\n"
    "You deserve a card.\n\n"
    "Take this Giant Soldier of\n"
    "Stone.\n\n"
)
  ADD_CARD(74)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Your path is clear.\n"
    "Advance.\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN3)
  FALLTHROUGH()
END_EVENT_SCRIPT()
