#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_06_state_03: map 6 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CC78, map_06_state_03_08E5CC78, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_TRISTAN)
  LOAD_SPRITE(2, SPRITE_DUKE)
  LOAD_SPRITE(3, SPRITE_LUCKY)
  LOAD_SPRITE(4, SPRITE_YUGI)
  LOAD_SPRITE(5, SPRITE_SERENITY)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  DELAY(32)
  MOVE_OBJECT(5, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Oh,"
  )
  DELAY(16)
  TEXT(
      "big brother!",
      "Is your work for Ishizu going smoothly?"
  )
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_14)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Joey,")
  DELAY(16)
  TEXT("what's wrong?")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(14, 48)
  WALK_OBJECT_X(14, 64)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_X(13, 72)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SAD, PORTRAIT_POSITION_AUTO,
      "Serenity, "
  )
  DELAY(16)
  TEXT("uh...")
  DELAY(16)
  TEXT("Er, um...")
  DELAY(16)
  TEXT("Tell me da truth. Is there")
  DELAY(16)
  TEXT("anybody that you like?")
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Yeah.")
  DELAY(16)
  TEXT("There sure is.")
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_14)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
      "S-"
  )
  DELAY(16)
  TEXT
  (
      "Serenity! "
  )
  DELAY(16)
  TEXT("Are you serious? Do I know this guy?")
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Yup. "
  )
  DELAY(16)
  TEXT("Tristan...")
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_14)
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(14, 52)
  DELAY(8)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
      "What? "
  )
  DELAY(16)
  TEXT("No! Anybody but him!")
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What's wrong, Joey?",
      "There's Tristan... and Duke...",
      "And Yugi and {PLAYER}...",
      "I also like Tea and Mai.",
      "But I like you the best, big brother."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  WALK_OBJECT_X(1, 80)
  WALK_OBJECT_X(2, 80)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, PORTRAIT_POSITION_AUTO,
      "B-"
  )
  DELAY(16)
  TEXT("but...")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "But "
  )
  DELAY(16)
  TEXT("you said you liked strong duelists...")
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_5)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Did I really say that?",
      "Well... come to think of it...",
      "I think it's coincidence that the people I like just",
      "happen to be good duelists."
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Awwwww, man...")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 4, 0)
  DELAY(8)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
      "Alright, ya idiots! Get outta here!",
      "Get back to work at the shop!"
  )
  SET_FLAG(EVENT_FLAG_UNLOCKED_MONKEY_ROBOT_SIDEQUEST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC90, map_06_state_03_08E5CC90, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, "
  )
  DELAY(16)
  TEXT(
      "I know you can win.",
      "You have to fight for me, too!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC9C, map_06_state_03_08E5CC9C, 0x08E5CCA8, 0x08F0404C)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I don't really feel like it, but I'll do anything for",
      "you, buddy!"
  )
  DUEL(DUELIST_TRISTAN_125)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCA8, map_06_state_03_08E5CCA8, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Did that even count as practice?")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCB4, map_06_state_03_08E5CCB4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "{PLAYER}, "
  )
  DELAY(16)
  TEXT(
      "leave it to me!",
      "I'll keep an eye on Tristan.",
      "...Especially to make sure that he doesn't hit on",
      "Serenity!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC6C, map_06_state_03_08E5CC6C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC84, map_06_state_03_08E5CC84, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Wouldn't it be great if we could stay friends forever?")
  FALLTHROUGH()
END_EVENT_SCRIPT()
