#include "event_macros.h"
#include "overworld.h"

/* map_12_state_11: map 12 state 11 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F168, map_12_state_11_08E6F168, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(12)
  LANGUAGE_TEXT(0, "M-master Mokuba...\n\nPlease, please give us one\nmore chance.\n\n")
  LANGUAGE_TEXT(1, "M-ma\xeetre Mokuba...\n\nS'il vous pla\xeet, donnez-nous\nune chance suppl\xe9mentaire.\n\n")
  LANGUAGE_TEXT(2, "M-Meister Mokuba...\n\nBitte geben Sie uns\nnoch eine Chance.\n\n")
  LANGUAGE_TEXT(3, "M-maestro Mokuba...\n\nVi prego, dateci un'altra\npossibilit\xe0.\n\n")
  LANGUAGE_TEXT(4, "A-amo Mokuba...\n\nPor favor, danos\notra oportunidad.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 2, 8)
  LANGUAGE_TEXT(0, "After all the horrible\nthings you've done to us?\n\n")
  LANGUAGE_TEXT(1, "Vous savez\nce que vous avez fait,\n\nesp\xe8ce d'imb\xe9ciles ?\n\n")
  LANGUAGE_TEXT(2, "Wisst ihr Idioten\neigentlich, was ihr\n\nangestellt habt?\n\n")
  LANGUAGE_TEXT(3, "Idioti! Sapete cosa\navete combinato?\n\n")
  LANGUAGE_TEXT(4, "\xbfSab\xe9is, idiotas, qu\xe9\nhab\xe9is hecho?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "I know we were wrong. But...\n\nTimes are tough. No one has\nany money!\n\nWe want to work, but no\none's hiring.\n\nPlease, we're begging you to\nrehire us.\n\n")
  LANGUAGE_TEXT(1, "Oui, oui, bien s\xfbr.\nMais...\n\nLes temps sont durs.\n\nIl n'y a plus\nassez d'argent !\n\nNous voulons travailler,\n\nmais il n'y a pas\nde travail.\n\nNous vous supplions de\nnous engager \xe0 nouveau.\n\n")
  LANGUAGE_TEXT(2, "Ja ja, nat\xfcrlich.\nAber...\n\nDie Zeiten sind hart.\nNiemand hat Geld!\n\nWir sind willens und f\xe4hig,\nund trotzdem heuert uns\n\nniemand an.\n\nBitte, wir flehen Sie an.\nGeben Sie uns Arbeit.\n\n")
  LANGUAGE_TEXT(3, "S\xec, s\xec, certo. Ma...\n\nSono tempi duri.\nNessuno ha denaro!\n\nAnche se siamo abili\ne volenterosi, nessuno\n\nci assume.\n\nVi supplichiamo di\nassumerci di nuovo.\n\n")
  LANGUAGE_TEXT(4, "S\xed, s\xed, claro.\nPero...\n\nLas cosas est\xe1n dif\xedciles.\n\xa1Nadie tiene dinero!\n\nAunque somos\nvoluntariosos y\n\ncapaces, nadie nos\ncontrata.\n\nPor favor, se lo rogamos.\n\nPor favor, contr\xe1tenos\nde nuevo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 0, 8)
  LANGUAGE_TEXT(0, "Well... I guess I have\nsomething for you...\n\n")
  LANGUAGE_TEXT(1, "Je vais y r\xe9fl\xe9chir...\n\nIl y a peut-\xeatre\nune possibilit\xe9...\n\n")
  LANGUAGE_TEXT(2, "Lasst mich nachdenken...\nEventuell...\n\n")
  LANGUAGE_TEXT(3, "Vediamo... Potrei\nanche essere disposto\n\na pensarci su...\n\n")
  LANGUAGE_TEXT(4, "Dejadme pensar... Es posible\nque lo considere...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "R-really?\n\nOh, thank you!\n\n")
  LANGUAGE_TEXT(1, "V-vraiment ?\n\nOh, merci !\n\n")
  LANGUAGE_TEXT(2, "W-wirklich?\n\nOh, danke!\n\n")
  LANGUAGE_TEXT(3, "Davvero?!\n\nOh, grazie!\n\n")
  LANGUAGE_TEXT(4, "\xbfD-de verdad?\n\nOh, \xa1gracias!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 0, 8)
  LANGUAGE_TEXT(0, "All right. Quick, get\nchanged.\n\n")
  LANGUAGE_TEXT(1, "Bon. Allez, vite,\nchangez-vous.\n\n")
  LANGUAGE_TEXT(2, "Okay. Schnell, zieht euch\num.\n\n")
  LANGUAGE_TEXT(3, "E va bene.\nCambiatevi, in fretta.\n\n")
  LANGUAGE_TEXT(4, "Vale.\nR\xe1pido, cambiaos.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(270)
  REACTION(1, 248)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Where's Serenity?\n\n")
  LANGUAGE_TEXT(1, "O\xf9 est-ce que\nSerenity est pass\xe9e ?\n\n")
  LANGUAGE_TEXT(2, "Wo ist Serenity?\n\n")
  LANGUAGE_TEXT(3, "Dove sar\xe0 Serenity?\n\n")
  LANGUAGE_TEXT(4, "\xbfD\xf3nde habr\xe1 ido\nSerenity?\n\n")
  END_LANGUAGE_TEXT()
  FADE_SCREEN(4)
  WARP(57, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
