#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_29_state_02: map 29 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC888, map_29_state_02_08EAC888, 0x08EAC894, 0x08EAC8A0)
  LOAD_SPRITE(1, SPRITE_BONZ)
  CHECK_FLAG(EVENT_FLAG_BONZ_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC894, map_29_state_02_08EAC894, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, "I think it's in the room ahead.")
  WALK_OBJECT_Y(1, 56)
  WALK_OBJECT_X(1, 80)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  SET_FLAG(EVENT_FLAG_BONZ_MOVED_OUT_OF_THE_WAY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8A0, map_29_state_02_08EAC8A0, 0x08EAC8AC, 0x08EAC8B8)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8AC, map_29_state_02_08EAC8AC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, "I think you'll find it in the back of the room.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8B8, map_29_state_02_08EAC8B8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ,
      "Looks like you found what you wanted.",
      "Lucky you."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC8C4, map_29_state_02_08EAC8C4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, "I'll duel you again when I make my deck stronger.")
  FALLTHROUGH()
END_EVENT_SCRIPT()
