#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_06: map 12 state 6 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08E6F024, map_12_state_06_08E6F024, 0x08E6F018, 0x08E6F06C)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  LOAD_SPRITE(2, SPRITE_MOKUBA)
  LOAD_SPRITE(3, SPRITE_SETO)
  CHECK_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F018, map_12_state_06_08E6F018, 0x08E6F03C, 0x08E6F054)
  CHECK_FLAG(EVENT_FLAG_NEO_GHOULS_ATTACKED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F03C, map_12_state_06_08E6F03C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "This is Kaiba Corporation.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F054, map_12_state_06_08E6F054, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Master Mokuba protects KaibaCorp, and I protect",
      "him!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F06C, map_12_state_06_08E6F06C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I guess things have calmed down for now.",
      "But, please stay safe and keep your guard up."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F030, map_12_state_06_08E6F030, 0x08E6F048, 0x08E6F060)
  CHECK_FLAG(EVENT_FLAG_NEO_GHOULS_ATTACKED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F048, map_12_state_06_08E6F048, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I don't have time to waste on you kids.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F060, map_12_state_06_08E6F060, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "If you have time to duel against me, then duel the",
      "Neo Ghouls."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F084, map_12_state_06_08E6F084, 0x08E6F078, 0x08E6F0B4)
  CHECK_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F078, map_12_state_06_08E6F078, 0x08E6F090, 0x08E6F0A8)
  CHECK_FLAG(EVENT_FLAG_KAIBA_WENT_TO_SEE_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F090, map_12_state_06_08E6F090, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Seto's Obelisk card turned into stone.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0A8, map_12_state_06_08E6F0A8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "My duty is to protect KaibaCorp.",
      "My big brother left me in charge, and I won't fail",
      "him!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0B4, map_12_state_06_08E6F0B4, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Seto left to meet the leader of the Neo Ghouls.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F09C, map_12_state_06_08E6F09C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'm too busy to play with you.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0C0, map_12_state_06_08E6F0C0, 0x08E6F0CC, 0x08E6F0D8)
  PLAY_MUSIC(MUSIC_405)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I figured you'd come.",
      "You're here to see about Obelisk the Tormentor.",
      "You want to know if it's turned into stone, right?"
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0CC, map_12_state_06_08E6F0CC, 0x08E6F0E4, EVENT_NOP)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "You think some stone magic trick is going to make me",
      "believe in your crazy mumbo jumbo?",
      "What do you take me for! I don't get fooled that",
      "easily!",
      "And now you want me to see Ishizu?"
  )
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Humph. I don't think so.",
      "I want nothing to do with you losers.",
      "I'll find out who did this to Obelisk the Tormentor on",
      "my own!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0E4, map_12_state_06_08E6F0E4, EVENT_NOP, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Mokuba, I have some errands to run.",
      "You're in charge of KaibaCorp while I'm gone."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You can count on me, bro!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, DIRECTION_LEFT, 40, 0)
  SET_FLAG(EVENT_FLAG_KAIBA_WENT_TO_SEE_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F0D8, map_12_state_06_08E6F0D8, 0x08E6F0E4, EVENT_NOP)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "No?",
      "Then there's nothing to talk about.",
      "Ishizu's probably behind this stupid magic trick",
      "anyway.",
      "I'll meet her in person and make her pay!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
