#include "event_macros.h"
#include "overworld.h"

/* map_22_state_08: map 22 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CBB8, map_22_state_08_08E8CBB8, 0x08E8CBC4, 0x08F04040)
  PLAY_MUSIC(405)
  DELAY(32)
  WALK_OBJECT_X(2, 52)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Big brother!\n\nMost of the Neo Ghouls have\nleft the Town of Domino.\n\n")
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Good.\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("I protected KaibaCorp, just\nlike you told me.\n\nSo you don't have to worry\nabout a thing.\n\n")
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Good work, Mokuba.\n\n")
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Heheh, thanks. You know I'll\ndo anything for you.\n\nSo, anything new with your\nEgyptian God Card?\n\n")
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Somehow, it's back to\nnormal.\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("I don't know what they did,\nbut...\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBC4, map_22_state_08_08E8CBC4, 0x08E8CBD0, 0x08F04040)
  PLAY_MUSIC(404)
  WALK_OBJECT_X(4, 48)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, PORTRAIT_LEFT)
  TEXT("Urk! S-Seto...\n\n")
  HIDE_PORTRAIT()
  DELAY(8)
  SET_OBJECT_POSITION(2, 128, 96, 0)
  PLAY_MUSIC(314)
  SWAP_OBJECT_SPRITE(4, 127)
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 6, PORTRAIT_RIGHT)
  TEXT("How dare you... What's the\nmeaning of this?\n\n")
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, PORTRAIT_LEFT)
  TEXT("Seto Kaiba! I have a message\nfrom Master Chevalsky!\n\nCome to my castle.\n\nIf you want to save your\ndear brother.\n\nYou have no choice but to\ncome to my castle!\n\n")
  PORTRAIT(PORTRAIT_SETO, 5, PORTRAIT_RIGHT)
  TEXT("You worm!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(4, 1, 8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBD0, map_22_state_08_08E8CBD0, 0x08E8CBDC, 0x08F04040)
  DELAY(16)
  SET_OBJECT_POSITION(3, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 24)
  WALK_OBJECT_X(3, 80)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, PORTRAIT_RIGHT)
  TEXT("Younger brother, you have\nfulfilled your mission!\n\nMaster Chevalsky will\npromote you to a higher\n\nposition!\n\n")
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, PORTRAIT_LEFT)
  TEXT("Elder brother, you also have\ndone your job with most\n\nexcellence!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_RIGHT)
  TEXT("You punks! How dare you mock\nme!\n\n")
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, PORTRAIT_RIGHT)
  TEXT("Fufufufufufu...\n\n")
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, PORTRAIT_LEFT)
  TEXT("Fufufufufufu...\n\n")
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  TEXT("Master Chevalsky demands\nyour presence, Kaiba!\n\n")
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Come to Master Chevalsky's\ncastle!\n\n")
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, PORTRAIT_RIGHT)
  TEXT("The castle that you...\n\n")
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, PORTRAIT_LEFT)
  TEXT("...Know so well! Fufufu...\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(3, 1, 96)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(4, 1, 64)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_RIGHT)
  TEXT("Mokuba!\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 4, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBDC, map_22_state_08_08E8CBDC, 0x08E8CBE8, 0x08E8CBF4)
  SET_OBJECT_POSITION(0, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 24)
  WALK_OBJECT_X(0, 82)
  DELAY(16)
  SET_OBJECT_POSITION(13, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(13, 18)
  WALK_OBJECT_X(13, 87)
  DELAY(16)
  SET_OBJECT_POSITION(14, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(14, 30)
  WALK_OBJECT_X(14, 87)
  DELAY(16)
  SET_OBJECT_POSITION(5, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(5, 24)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(0, 77)
  DELAY(16)
  TEXT("{CARD_1}Let us help!\nLend us your God Card!{CARD_2}\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBE8, map_22_state_08_08E8CBE8, 0x08E8CC00, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("{PLAYER} is right, Kaiba.\n\nNow is the time for\nteamwork.\n\nThe Dark Being must be\nsealed again...\n\n")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_LEFT)
  TEXT("Quiet, you!\n\nI'm never going to cooperate\nwith you!\n\nI'll crush Pegasus on my own\nand get Mokuba back!\n\nHow many times do I have to\nsay that I don't have time\n\nfor your so-called ancient\nmagic!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CC00, map_22_state_08_08E8CC00, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 0)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("We're left with no choice.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("We must also go to Sol\nChevalsky's... I mean...\n\nWe must also go to Pegasus's\ncastle.\n\n")
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("But who knows where the\ncastle is?\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24609)
  DELAY(16)
  PLAY_MUSIC(402)
  WALK_OBJECT_X(6, 48)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 32)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("You have proven yourselves\nto the Millennium Items.\n\nTrace the flow of time and\naccept your destiny.\n\nOne man knows where you must\ngo.\n\nYou must seek out Paradox.\n\n")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Paradox awaits you in China.\n\nHe will show you the way.\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(6, DIRECTION_LEFT, 64, 0)
  DELAY(32)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("The Millennium Guard comes\nfrom the order that\n\nprotects the Millennium\nItems...\n\nI sensed that he was telling\nthe truth.\n\n{PLAYER}, you must go to\nChina.\n\nAs soon as possible.\n\n")
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(5, 0)
  SET_OBJECT_POSITION(5, 128, 96, 0)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("I'm worried about Mokuba and\nKaiba...\n\nWe'd better find Pegasus's\ncastle quickly.\n\n")
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Yugi's right.\n\nIf this Parachute guy can\nhelp us...\n\nWe'd betta find him quick.\n\n")
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("That's Paradox, Joey.\nNot Parachute.\n\n{PLAYER}, let's go! We're\noff to China!\n\n")
  HIDE_PORTRAIT()
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  SET_FLAG(EVENT_FLAG_SAW_MOKUBA_GET_KIDNAPPED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBF4, map_22_state_08_08E8CBF4, 0x08E8CC00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, PORTRAIT_LEFT)
  TEXT("Don't make me laugh,\n{PLAYER}!\n\nReshef the Dark Being... The\nend of the world...\n\nYou've been reading too many\nfantasy novels!\n\nYou guys do what you want!\n\nBut I'll get Mokuba back on\nmy own!\n\nAnd nobody is going to stop\nme!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
