#include "event_macros.h"
#include "overworld.h"

/* map_38_state_05: map 38 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08ED1688, map_38_state_05_08ED1688, 0x08ED1694, 0x08ED16A0)
  CHECK_FLAG(129)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1694, map_38_state_05_08ED1694, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hyo?\n\nYou're looking for bugs too,\n{PLAYER}?\n\nToo bad. There aren't any\nbugs around.\n\nThey all disappeared as if\nsomething scared them.\n\nI have a really bad feeling\nabout this.\n\n")
  LANGUAGE_TEXT(1, "Hyo ?\n\nToi aussi, tu cherches\ndes insectes, {PLAYER} ?\n\nEh bien, ils ont tous\ndisparu...\n\nComme s'ils \xe9taient\neffray\xe9s.\n\nJ'ai un mauvais\npressentiment\n\npour tout cela.\n\n")
  LANGUAGE_TEXT(2, "Hyo?\n\nSuchst du auch K\xe4fer,\n{PLAYER}?\n\nLeider gibt es hier keine.\n\nSie sind alle verschwunden,\nso als h\xe4tten sie Angst.\n\nIch habe ein ungutes Gef\xfchl\nbei der Sache.\n\n")
  LANGUAGE_TEXT(3, "Ehi?\n\nAnche tu cerchi\ninsetti, {PLAYER}?\n\nPurtroppo, gli insetti\nnon si trovano.\n\nSono tutti scomparsi,\ncome se fossero\n\nspaventati. Ho un gran\nbrutto presentimento...\n\n")
  LANGUAGE_TEXT(4, "\xbfHyo?\n\n\xbfTambi\xe9n buscas insec-\ntos, {PLAYER}?\n\nEs una pena, pero no\nhay insectos por aqu\xed.\n\nTodos desaparecieron\ncomo si estuvieran\n\nasustados.\n\nTengo un presentimiento\nrealmente malo al respecto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(129)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16A0, map_38_state_05_08ED16A0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The bugs all disappeared as\nif they were scared.\n\nI have a really bad feeling\nabout this.\n\n")
  LANGUAGE_TEXT(1, "Les insectes ont disparu\ncomme s'ils avaient peur.\n\nJ'ai vraiment un\nmauvais pressentiment.\n\n")
  LANGUAGE_TEXT(2, "Die K\xe4fer sind alle versch-\nwunden, so als h\xe4tten sie\n\nAngst. Ich habe ein ungutes\nGef\xfchl bei der Sache.\n\n")
  LANGUAGE_TEXT(3, "Tutti gli insetti sono\nscomparsi, come se\n\nfossero spaventati. Ho un\nbrutto presentimento.\n\n")
  LANGUAGE_TEXT(4, "Todos los insectos\ndesaparecieron como si\n\nestuvieran asustados.\nTengo un presentimiento\n\nrealmente malo al\nrespecto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16AC, map_38_state_05_08ED16AC, 0x08ED16B8, 0x08ED16D0)
  CHECK_FLAG(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16B8, map_38_state_05_08ED16B8, 0x08ED16C4, 0x08F0404C)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hyohyohyo!\n\nYou want to be infested by\nmy Super Insect deck?\n\n")
  LANGUAGE_TEXT(1, "Hyo hyo hyo !\n\nTu veux\nque je t'\xe9crase\n\navec mon super Deck\nd'insectes ?\n\n")
  LANGUAGE_TEXT(2, "Hyohyohyo!\n\nSoll dich mein Super-\nInsektendeck zerquetschen?\n\n")
  LANGUAGE_TEXT(3, "Iohiohioh! Vuoi che ti\nannienti con il mio\n\nsuper deck di insetti?\n\n")
  LANGUAGE_TEXT(4, "\xa1Hyohyohyo!\n\n\xbfQuieres que mi deck de\nsuper insectos te aplaste?\n\n")
  END_LANGUAGE_TEXT()
  DUEL(104)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16C4, map_38_state_05_08ED16C4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(250)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My Queen!\n\nHumph, humph, humph!\n\nI can't beat you when you\ntake enormous risks in a\n\nduel! All my strategies\nbecome as weak as a worm!\n\nTake this with you.\n\nIt's Insect Queen, the card\nthat represents me.\n\nIt's a useful rare card...\n\nBut only if you consider it\nas my spirit...\n\n")
  LANGUAGE_TEXT(1, "Oh, ma Reine !\n\nHumph, humph, et humph !\n\nJe savais que tu allais\nte battre vaillamment !\n\nJe le savais\ndepuis toujours !\n\nJe ne pouvais pas te\nbattre car je ne suis\n\npas assez bon.\nPrends cela.\n\nC'est ma carte spirituelle.\nLa Reine des insectes.\n\nC'est une carte rare\nqui est d'ailleurs\n\ntrop bonne pour toi.\n\nMais si tu la consid\xe9rais\ncomme mon esprit...\n\n")
  LANGUAGE_TEXT(2, "Oh, meine K\xf6nigin!\n\nHmph, hmph und hmph!\n\nIch wusste, dass du deinen\nganzen Geist einbringst!\n\nDas war mir von Anfang an\nklar! Ich konnte dich nicht\n\nbesiegen, weil ich nicht\ngut genug bin.\n\nHier, nimm das mit.\n\nMeine Geisterkarte. Die\nInsektenk\xf6nigin.\n\nEine seltene Karte - eigent-\nlich zu gut f\xfcr dich.\n\nAber wenn du sie als\nmeinen Geist betrachtest...\n\n")
  LANGUAGE_TEXT(3, "Oh, mia Regina!\n\nAuff, auff e auff!\n\nSapevo che ti butti\na capofitto nei duelli!\n\nL'ho sempre saputo.\n\nNon potevo batterti,\nperch\xe9 non sono\n\nabbastanza bravo.\nPrendi questa con te.\n\n\xc8 la mia carta-spirito.\n\xc8 la Regina degli Insetti.\n\n\xc8 una carta rara, che ti\nfar\xe0 veramente comodo.\n\nMa se la considerassi\ncome il mio spirito...\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, mi Reina!\n\n\xa1Humph, humph y humph!\n\n\xa1Sab\xeda que estabas luchando\ncon toda tu alma!\n\n\xa1Siempre lo supe!\n\nNo te pude vencer porque no\nsoy lo bastante bueno.\n\nToma esto.\n\nEs mi carta de esp\xedritu.\nLa Reina de los insectos.\n\nEs una carta rara en verdad\ndemasiado buena para ti.\n\nPero si lo consideraras\nmi esp\xedritu...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Arrrrgh, what a terrible\nwaste...\n\nI wasted a rare card on\nyou...\n\nGet outta here! Bye-bye, my\nbeautiful bug!\n\n")
  LANGUAGE_TEXT(1, "Arrrrgh, quel horrible\ng\xe2chis !\n\nA cause de toi, j'ai\ng\xe2ch\xe9 une carte rare...\n\nAllez ! Hors de ma vue !\n\n")
  LANGUAGE_TEXT(2, "Arrrrgh, was f\xfcr eine\nVerschwendung...\n\nIch habe eine seltene Karte\nan dich vergeudet...\n\nNa los, geh mir aus den\nAugen!\n\n")
  LANGUAGE_TEXT(3, "Arrrrgh, che terribile\nspreco...\n\nHo sprecato una carta\nrara con te...\n\nOra vai! Levati di torno!\n\n")
  LANGUAGE_TEXT(4, "Arrrrgh, qu\xe9 terrible\ndesperdicio...\n\nHe desperdiciado una\ncarta rara en ti...\n\n\xa1Vamos! \xa1Desaparece\nde mi vista!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Received Insect Queen.")
  LANGUAGE_TEXT(1, "Re\xe7u la Reine des insectes.")
  LANGUAGE_TEXT(2, "Insektenk\xf6nigin erhalten.")
  LANGUAGE_TEXT(3, "Ricevuta una\nRegina degli Insetti.")
  LANGUAGE_TEXT(4, "Recibido una Reina\nde los insectos.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(250)
  PAGE_BREAK()
  ADD_CARD(762)
  SET_FLAG(130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16D0, map_38_state_05_08ED16D0, 0x08ED16DC, 0x08F0404C)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh, okay okay!\n\nIf you insist on bugging me,\nI'll duel you!\n\n")
  LANGUAGE_TEXT(1, "Oh, OK, OK !\n\nSi tu insistes, je vais\nme battre contre toi !\n\n")
  LANGUAGE_TEXT(2, "Oh, okay, okay!\n\nWenn du so beharrlich\nbist, duellieren wir uns!\n\n")
  LANGUAGE_TEXT(3, "Oh, okay, okay!\n\nSe insisti a irritarmi,\ndueller\xf2 con te!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, vale, vale!\n\nSi insistes en molestarme,\n\xa1luchar\xe9 contigo!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(151)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16DC, map_38_state_05_08ED16DC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  PORTRAIT(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You stole my technique!\n\nYou knew my strategies were\nthe best!\n\nIf you're using my tactics,\nyou better not lose! Or\n\nI'll pour cockroaches down\nyour pants!\n\n")
  LANGUAGE_TEXT(1, "Tu as vol\xe9 ma technique !\n\nTu me l'as vol\xe9e,\nexpert en duel !\n\nTu as int\xe9r\xeat \xe0\nne pas perdre !\n\nJe ne te le\npardonnerai pas !\n\n")
  LANGUAGE_TEXT(2, "Du hast meine Technik\nkopiert!\n\nDu hast ihn mir gestohlen,\ndas Duellgenie! Verliere\n\njetzt blo\xdf nicht! Das w\xfcrde\nich dir nicht verzeihen!\n\n")
  LANGUAGE_TEXT(3, "Mi hai rubato la tecnica!\n\nMe l'hai rubata, genio\ndel duello!\n\nVedi di non perdere!\nNon te lo perdoner\xf2!\n\n")
  LANGUAGE_TEXT(4, "\xa1Me has robado\nla t\xe9cnica!\n\n\xa1Me la robaste a m\xed,\nel genio del duelo!\n\n\xa1Mejor que no pierdas!\n\xa1No te perdonar\xe9!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
