#include "event_macros.h"
#include "overworld.h"

/* map_00_state_14: map 0 state 14 */

EVENT_SCRIPT_REPLACEMENT(0x08E34EC8, map_00_state_14_08E34EC8, 0x08E34ED4, 0x08E34EE0)
  CHECK_FLAG(188)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34ED4, map_00_state_14_08E34ED4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You must ask Paradox where\nPegasus's castle is.\n\nParadox is in China.\n\n")
  LANGUAGE_TEXT(1, "Vous devez demander\n\xe0 Paradox o\xf9 se trouve le\n\nch\xe2teau de Pegasus.\nParadox est en Chine.\n\n")
  LANGUAGE_TEXT(2, "Fragt Paradox, wo\nPegasus' Burg liegt.\n\nParadox ist in China.\n\n")
  LANGUAGE_TEXT(3, "Dovete chiedere a Paradox\ndove si trova il castello\n\ndi Pegasus. Paradox\n\xe8 in Cina.\n\n")
  LANGUAGE_TEXT(4, "Deb\xe9is preguntar a\nParadox d\xf3nde est\xe1 el\n\ncastillo de Pegasus.\nParadox est\xe1 en China.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EE0, map_00_state_14_08E34EE0, 0x08E34EEC, 0x08E34EF8)
  CHECK_FLAG(189)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EEC, map_00_state_14_08E34EEC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Did you meet Paradox?\n\n")
  LANGUAGE_TEXT(1, "Avez-vous rencontr\xe9\nParadox ?\n\n")
  LANGUAGE_TEXT(2, "Habt ihr Paradox getroffen?\n\n")
  LANGUAGE_TEXT(3, "Avete incontrato Paradox?\n\n")
  LANGUAGE_TEXT(4, "\xbfVisteis a Paradox?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Well...\n\n")
  LANGUAGE_TEXT(1, "Eh bien...\n\n")
  LANGUAGE_TEXT(2, "Nun...\n\n")
  LANGUAGE_TEXT(3, "Be'...\n\n")
  LANGUAGE_TEXT(4, "Bueno...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I see...\n\nOnly two men have deciphered\nthe ancient hieroglyphics\n\nneeded to awaken Ra..\n\nThe first is Kaiba.\nBut he is...\n\n")
  LANGUAGE_TEXT(1, "Je vois...\n\nLe texte hi\xe9ratique ancien\nn\xe9cessaire pour r\xe9veiller\n\nRa... Seuls deux hommes ont\nd\xe9chiffr\xe9 cette langue.\n\nL'un d'entre eux est\nKaiba Seto. Mais il est...\n\n")
  LANGUAGE_TEXT(2, "Verstehe...\n\nDie alte Priesterschrift\nzur Erweckung von Ra...\n\nNur zwei Menschen haben die\nalte Sprache entschl\xfcsselt.\n\nEiner ist Kaiba Seto.\nDoch Kaiba Seto ist...\n\n")
  LANGUAGE_TEXT(3, "Ho capito...\n\nL'antico testo ieratico\nnecessario per\n\ndestare Ra... Solo\ndue uomini hanno\n\ndecifrato quell'antico\nlinguaggio.\n\nUno \xe8 Kaiba Seto.\nMa Kaiba Seto \xe8...\n\n")
  LANGUAGE_TEXT(4, "Ya veo...\n\nEl antiguo texto\nhier\xe1tico necesario\n\npara despertar a Ra...\n\nS\xf3lo dos hombres han\ndescifrado el antiguo\n\nlenguaje.\n\nUno es Kaiba Seto.\nPero Kaiba Seto est\xe1...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "He went after Mokuba.\n\n")
  LANGUAGE_TEXT(1, "Il est parti \xe0 la\nrecherche de Mokuba.\n\n")
  LANGUAGE_TEXT(2, "Er verfolgte Mokuba.\n\n")
  LANGUAGE_TEXT(3, "\xc8 andato a cercare\nMokuba.\n\n")
  LANGUAGE_TEXT(4, "Se fue siguiendo\na Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Then we just hafta meet the\nother guy.\n\n")
  LANGUAGE_TEXT(1, "Alors, nous devons trouver\nle deuxi\xe8me homme.\n\n")
  LANGUAGE_TEXT(2, "Dann m\xfcssen wir eben\nden zweiten Mann finden.\n\n")
  LANGUAGE_TEXT(3, "Quindi dobbiamo andare\na cercare l'altro tizio.\n\n")
  LANGUAGE_TEXT(4, "Entonces, s\xf3lo\ntenemos que ir\n\na ver al otro tipo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The other... Is my brother\nMarik.\n\n")
  LANGUAGE_TEXT(1, "L'autre... C'est\nmon fr\xe8re Marik.\n\n")
  LANGUAGE_TEXT(2, "Der andere...\nIst mein Bruder Marik.\n\n")
  LANGUAGE_TEXT(3, "L'altro...\n\xc8 mio fratello Marik.\n\n")
  LANGUAGE_TEXT(4, "El otro...\nEs mi hermano Marik.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ah... That makes sense.\n\nThe Winged Dragon of Ra\nbelonged to Marik.\n\n")
  LANGUAGE_TEXT(1, "Ah...\nJe comprends tout.\n\nAu d\xe9part, le Dragon Ail\xe9 de\nRa appartenait \xe0 Marik.\n\n")
  LANGUAGE_TEXT(2, "Oh...\nDas ergibt einen Sinn.\n\nDer gefl\xfcgelte Drache von Ra\ngeh\xf6rte urspr\xfcnglich Marik.\n\n")
  LANGUAGE_TEXT(3, "Ah... Le cose quadrano.\nTanto per cominciare,\n\nil Drago Alato di Ra\nera di Marik.\n\n")
  LANGUAGE_TEXT(4, "Uh...\nTiene sentido.\n\nPara empezar, el Drag\xf3n\nAlado de Ra era de Marik.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Marik is living a new life\nin Egypt.\n\nPlease see him there.\n\n")
  LANGUAGE_TEXT(1, "Marik vit maintenant en\nEgypte.\n\nAllez le voir l\xe0-bas.\n\n")
  LANGUAGE_TEXT(2, "Marik f\xfchrt ein neues Leben\nin \xc4gypten.\n\nBitte besucht ihn dort.\n\n")
  LANGUAGE_TEXT(3, "Ora Marik ha cambiato\nvita e sta in Egitto.\n\nAndate a incontrarlo\nl\xec, vi prego.\n\n")
  LANGUAGE_TEXT(4, "Marik est\xe1 ahora viviendo\nuna nueva vida en Egipto.\n\nPor favor, vedle all\xed.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(189)
  SET_FLAG(228)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EF8, map_00_state_14_08E34EF8, 0x08E34F04, 0x08E34F10)
  CHECK_FLAG(190)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F04, map_00_state_14_08E34F04, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Has The Winged Dragon of Ra\nawoken?\n\nPlease meet my brother Marik\nin Egypt.\n\n")
  LANGUAGE_TEXT(1, "Est-ce que Dragon\nAil\xe9 de Ra s'est r\xe9veill\xe9 ?\n\nAllez voir mon fr\xe8re\nMarik en Egypte.\n\n")
  LANGUAGE_TEXT(2, "Ist der gefl\xfcgelte Drache\nvon Ra erwacht?\n\nBesucht bitte meinen\nBruder Marik in \xc4gypten.\n\n")
  LANGUAGE_TEXT(3, "Il Drago Alato di Ra\nsi \xe8 destato? Andate\n\na trovare mio fratello\nMarik in Egitto.\n\n")
  LANGUAGE_TEXT(4, "\xbfSe ha despertado el\nDrag\xf3n Alado de Ra?\n\nPor favor, ved a mi hermano\nMarik en Egipto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F10, map_00_state_14_08E34F10, 0x08E34F1C, 0x08E34F28)
  CHECK_FLAG(151)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F1C, map_00_state_14_08E34F1C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "It appears that Marik has\nawakened Ra.\n\nThere is no time to waste.\n\nYou must once again visit\nParadox in China.\n\nHe knows where Pegasus's\ncastle is.\n\nFind the location of the\ncastle and stop the Dark\n\nBeing.\n\n")
  LANGUAGE_TEXT(1, "Apparemment, Marik\na r\xe9veill\xe9 Ra.\n\nIl n'y a pas de temps\n\xe0 perdre.\n\nIl faut rendre visite \xe0\nParadox en Chine.\n\nIl sait o\xf9 se situe le\nch\xe2teau de Pegasus.\n\nTrouvez-le et arr\xeate\nl'Etre des t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Anscheinend hat Marik\nRa erweckt.\n\nWir d\xfcrfen keine Zeit\nverschwenden.\n\nIhr m\xfcsst wieder Paradox in\nChina besuchen.\n\nEr wei\xdf, wo Pegasus' Burg\nliegt.\n\nFindet sie und stoppt\nden Dunklen.\n\n")
  LANGUAGE_TEXT(3, "Sembra che Marik abbia\ndestato Ra.\n\nNon c'\xe8 tempo da perdere.\nDovete andare di nuovo\n\na trovare Paradox in Cina.\nLui sa dov'\xe8 il castello\n\ndi Pegasus. Scopritelo e\nfermate il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Parece ser que Marik ha\ndespertado a Ra.\n\nNo hay tiempo\nque perder.\n\nDeb\xe9is volver a visitar\na Paradox en China.\n\n\xc9l sabe d\xf3nde est\xe1\nel castillo de Pegasus.\n\nEnteraos y detened\nal Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34F28, map_00_state_14_08E34F28, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You must once again visit\nParadox in China.\n\nHe knows the location of\nPegasus's castle.\n\n")
  LANGUAGE_TEXT(1, "Vous devez \xe0 nouveau rendre\nvisite \xe0 Paradox en Chine.\n\nIl sait o\xf9 se situe le\nch\xe2teau de Pegasus.\n\n")
  LANGUAGE_TEXT(2, "Ihr m\xfcsst noch einmal\nParadox in China besuchen.\n\nEr wei\xdf, wo Pegasus' Burg\nliegt.\n\n")
  LANGUAGE_TEXT(3, "Dovete andare di nuovo a\ntrovare Paradox in Cina.\n\nLui sa dove si trova il\ncastello di Pegasus.\n\n")
  LANGUAGE_TEXT(4, "Deb\xe9is volver a visitar\na Paradox en China.\n\n\xc9l sabe d\xf3nde est\xe1\nel castillo de Pegasus.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34DFC, map_00_state_14_08E34DFC, 0x08E34E08, 0x08E34E14)
  CHECK_FLAG(112)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E08, map_00_state_14_08E34E08, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "Pipipi... You managed to\nsave Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Pipipi... Tu as r\xe9ussi\n\xe0 sauver Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Pipipi... Du hast Ishizu\nalso tats\xe4chlich gerettet.\n\n")
  LANGUAGE_TEXT(3, "Eheheh... Cos\xec sei\nriuscito a salvare Ishizu.\n\n")
  LANGUAGE_TEXT(4, "Pipipi... Has logrado\nsalvar a Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But you still have a huge\nchallenge ahead of you.\n\nI don't need psychic powers\nto predict this.\n\nI can tell just by the\nlooking into your eyes.\n\nYou'll be fine.\nDon't give up!\n\n")
  LANGUAGE_TEXT(1, "Mais tu as encore un\nimmense d\xe9fi \xe0 relever.\n\nSi je le sais, ce n\u2019est\npas gr\xe2ce \xe0 mes\n\npouvoirs psychiques.\nJe le vois dans tes yeux.\n\nMais tu t'en sortiras.\nTiens bon !\n\n")
  LANGUAGE_TEXT(2, "Doch vor dir liegt noch eine\nriesige Herausforderung.\n\nNicht meine psychischen\nKr\xe4fte sagen mir dies.\n\nDeine Augen sprechen\nB\xe4nde. Aber ich wei\xdf:\n\nDu wirst es schaffen.\nGib nur nicht auf!\n\n")
  LANGUAGE_TEXT(3, "Ma ti aspetta ancora\nun'enorme sfida.\n\nNon sono i miei poteri\nparanormali a dirmelo,\n\nma te lo leggo negli\nocchi. So che andr\xe0\n\ntutto bene. Non mollare!\n\n")
  LANGUAGE_TEXT(4, "Pero a\xfan tienes un\ngran reto esper\xe1ndote.\n\nNo son mis poderes s\xedquicos\nlos que me lo dicen.\n\nPuedo decirlo con\ns\xf3lo mirar tus ojos.\n\nS\xe9 que todo ir\xe1 bien.\n\xa1No abandones!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(112)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E14, map_00_state_14_08E34E14, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, 8)
  LANGUAGE_TEXT(0, "Pipipi...\n\nYou're fighting to save the\nworld.\n\n")
  LANGUAGE_TEXT(1, "Pipipi...\n\nTu dois faire face \xe0 un\nd\xe9fi \xe9norme pour sauver\n\nnotre monde.\n\n")
  LANGUAGE_TEXT(2, "Pipipi...\n\nDu stellst dich einer gro\xdfen\nHerausforderung f\xfcr die\n\nganze Welt.\n\n")
  LANGUAGE_TEXT(3, "Eheheh...\n\nTi aspetta un'enorme\nsfida e c'\xe8 in ballo il\n\nmondo.\n\n")
  LANGUAGE_TEXT(4, "Pipipi...\n\nTe enfrentas a un enorme\nreto para el mundo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You'll be fine as long as\nyou don't give up!\n\n")
  LANGUAGE_TEXT(1, "Je sais que\ntout ira bien. Tiens bon !\n\n")
  LANGUAGE_TEXT(2, "Aber ich wei\xdf:\n\nDu wirst es schaffen.\nGib nur nicht auf!\n\n")
  LANGUAGE_TEXT(3, "So che andr\xe0 tutto\nbene. Non mollare!\n\n")
  LANGUAGE_TEXT(4, "S\xe9 que todo ir\xe1 bien.\n\xa1No abandones!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EB0, map_00_state_14_08E34EB0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I'm exhausted.\nI need to rest.\n\n")
  LANGUAGE_TEXT(1, "Je n'en peux plus.\nJe dois me reposer.\n\n")
  LANGUAGE_TEXT(2, "Ich bin ersch\xf6pft.\nIch muss mich ausruhen.\n\n")
  LANGUAGE_TEXT(3, "Sono sfinito.\nHo bisogno di riposare.\n\n")
  LANGUAGE_TEXT(4, "Estoy agotado.\nNecesito descansar.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E5C, map_00_state_14_08E34E5C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "My big brother dueled great\nagainst the Neo Ghouls.\n\nHe really showed them who's\nboss!\n\nHe's the coolest guy I know!\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re a \xe9t\xe9 g\xe9nial\ncontre les Neo Ghouls.\n\nIl leur a donn\xe9\nune bonne le\xe7on.\n\nIl a vraiment \xe9t\xe9\ntrop cool.\n\n")
  LANGUAGE_TEXT(2, "Unser gro\xdfer Bruder war\ntoll im Kampf gegen die\n\nNeo Ghouls. Er hat es\nihnen wirklich gezeigt.\n\nEr war echt supercool.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello \xe8 stato grande\ncontro i Neo Ghouls.\n\nGliel'ha fatta vedere lui.\n\n\xc8 stato davvero forte.\n\n")
  LANGUAGE_TEXT(4, "Gran hermano estuvo\nfenomenal contra\n\nlos Neo Ghouls.\nLes dio una lecci\xf3n.\n\nFue muy bueno.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E68, map_00_state_14_08E34E68, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "My big brother always\nsays...\n\nA duelist becomes more\npowerful when he has\n\nfriends supporting him.\n\n")
  LANGUAGE_TEXT(1, "C'est ce que mon grand\nfr\xe8re me dit toujours.\n\nTu es fort quand\ntu es accompagn\xe9.\n\n")
  LANGUAGE_TEXT(2, "Mein gro\xdfer Bruder sagt\nimmer:\n\nDu bist stark, wenn du\nnicht allein bist.\n\n")
  LANGUAGE_TEXT(3, "Mio fratello dice\nsempre cos\xec:\n\nSei forte se non\nsei da solo.\n\n")
  LANGUAGE_TEXT(4, "Es lo que siempre\ndice mi gran hermano.\n\nEres fuerte si\nno est\xe1s s\xf3lo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E74, map_00_state_14_08E34E74, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I really like Espa! He's the\nbest!\n\n")
  LANGUAGE_TEXT(1, "J'aime vraiment\nmon grand fr\xe8re !\n\nIl est g\xe9nial !\n\n")
  LANGUAGE_TEXT(2, "Ich mag meinen gro\xdfen\nBruder wirklich sehr!\n\nEr ist Klasse!\n\n")
  LANGUAGE_TEXT(3, "Ammiro davvero mio\nfratello! \xc8 eccezionale!\n\n")
  LANGUAGE_TEXT(4, "\xa1Me encanta mi\ngran hermano!\n\n\xa1Es fenomenal!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
