#include "event_macros.h"
#include "overworld.h"

/* map_00_state_04: map 0 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08E34A9C, map_00_state_04_08E34A9C, 0x08E34AB4, 0x08E34AFC)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_KEY_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AB4, map_00_state_04_08E34AB4, 0x08E34AC0, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have obtained the\nMillennium Key.\n\nWith the power of two\nMillennium Items...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AC0, map_00_state_04_08E34AC0, 0x08E34ACC, 0x08F04040)
  PLAY_MUSIC(290)
  COMMAND_7C_ARG(8, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34ACC, map_00_state_04_08E34ACC, 0x08E34AD8, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Slifer the Sky Dragon has\nregained its power!\n\nEgyptian God Cards choose\ntheir bearers.\n\nThis card... chooses you,\nYugi.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 8192)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ishizu... Slifer the Sky\nDragon...\n\nI can't use it.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 16385)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That card belongs to my\nother self.\n\nIt doesn't belong to me.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But... After all the trouble\nyou undergone to attain it,\n\nyou will forfeit the\nresurrected Egyptian God\n\nCard?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I think {PLAYER} should\nhold on to that card.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER} also saw the\nMillennium Necklace's\n\nvision.\n\nI know he can control the\npower of the Egyptian God\n\nCards. I'm absolutely sure\nof it!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, don't be shy! Take\nit! I'd be leapin' outta my\n\nskin to get a card like dat!\n\nBesides, Slifer the Sky\nDragon proves that the\n\npower of our friendship can\ndefeat anybody!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I understand... Since you\nall agree...\n\n{PLAYER}, I will entrust you\nwith this card.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  PLAY_MUSIC(285)
  DELAY(16)
  LANGUAGE_TEXT(0, "Received Slifer the Sky\nDragon!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah! Awesome!\n\nWe have the first Egyptian\nGod Card!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Still... It seems that in\norder to restore a single\n\nEgyptian God Card...\n\nWe need the magical powers\nof two Millennium Items,\n\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You are correct.\n\nIn order to resurrect all\nthree Egyptian God Cards...\n\nYou must gather the other\nMillennium Items. And\n\nquickly!\n\n")
  END_LANGUAGE_TEXT()
  ADD_CARD(238)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AD8, map_00_state_04_08E34AD8, 0x08E34AF0, 0x08E34AE4)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Okay\nI don't get it{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AF0, map_00_state_04_08E34AF0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The next Millennium Item...\n\nIs in Italy.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ". ")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "Among the\nCatacombs...\n\nCatacombs are underground\ncemeteries.\n\nA Millennium Item is certain\nto be hidden there.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_KEY_TO_ISHIZU)
  SET_FLAG(EVENT_FLAG_UNLOCKED_ITALY)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AE4, map_00_state_04_08E34AE4, 0x08E34AD8, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "To resurrect a single\nEgyptian God Card...\n\nWe need the power from two\nMillennium Items.\n\nIn order to resurrect all\nthree Egyptian God Cards...\n\nYou must gather the other\nMillennium Items, and we do\n\nnot have much time!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AFC, map_00_state_04_08E34AFC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Sol Chevalsky resurrected\nthe Dark Being...\n\nWe must have the Egyptian\nGod Cards in order to stop\n\nthe terror.\n\nTherefore, we must restore\nthe Egyptian God Cards from\n\nstone.\n\nBut in order to do so, we\nneed the Millennium Items.\n\nThe third Millennium Item is\nin the Catacombs of Italy.\n\nPlease find it in the\ncommunal cemetery.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34AA8, map_00_state_04_08E34AA8, 0x08E34AB4, 0x08E34B08)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_KEY_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B08, map_00_state_04_08E34B08, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Please hurry to the\nCatacombs of Italy.\n\nReshef the Dark Being will\nsoon engulf the world in\n\ndarkness.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
