#include "event_macros.h"
#include "overworld.h"

/* map_54_state_01: map 54 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EE9C24, map_54_state_01_08EE9C24, 0x08EE9C30, 0x08EE9C3C)
  PLAY_MUSIC(19)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Go, Blue-Eyes White Dragon!\n\n")
  LANGUAGE_TEXT(1, "Viens ici, Dragon blanc\naux yeux bleus !\n\n")
  LANGUAGE_TEXT(2, "Kom her, blau\xe4ugiger\nwei\xdfer Drache!\n\n")
  LANGUAGE_TEXT(3, "Vieni qui, Drago\nBianco Occhi Blu!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ven aqu\xed, Drag\xf3n blanco de ojos azules!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 9)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "White Lightning Attack!\n\n")
  LANGUAGE_TEXT(1, "Burst Stream of Ruin !\n\n")
  LANGUAGE_TEXT(2, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(3, "Burst Stream of Ruin!\n\n")
  LANGUAGE_TEXT(4, "\xa1Burst Stream of Ruin!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(338)
  COMMAND_7C_ARG(8, 56)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(4, 2, 16)
  PLAY_MUSIC(282)
  OBJECT_EFFECT(16, 2)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Humph. So you finally showed\nup. But you're too late.\n\nThat Pegasus... I will crush\nhim myself!\n\n")
  LANGUAGE_TEXT(1, "Mm.. Alors tu te montres\nenfin.\n\nMais tu es en retard.\n\nCe Pegasus... Je vais\nl'\xe9craser en personne !\n\n")
  LANGUAGE_TEXT(2, "Hmph. Da bist du also\nendlich. Aber zu sp\xe4t.\n\nPegasus... Ich werde\nihn selbst erledigen!\n\n")
  LANGUAGE_TEXT(3, "Be', finalmente ti si\nrivede. Ma \xe8 troppo tardi.\n\nQuel Pegasus... Lo\nannienter\xf2 io stesso!\n\n")
  LANGUAGE_TEXT(4, "Vaya. Por fin apareces.\nPero llegas tarde.\n\nEse Pegasus...\n\xa1Le aplastar\xe9 yo mismo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(2, 72)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Kaiba... You cannot win\nalone... One Egyptian God\n\nCard isn't enough.\n\nYou have no chance.\n\nNot against Pegasus and\nReshef the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "Seto... Toi, seul... Non.\n\nUne seule carte de\ndieu ne suffit pas.\n\nTu n'as aucune\nchance de gagner.\n\nPas contre Pegasus et\nReshef, l'Etre des\n\nt\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Seto. Du allein, nein. Eine\nG\xf6tterkarte reicht nicht.\n\nDu h\xe4ttest keine Chance.\n\nWeder gegen Pegasus noch\ngegen Reschef den Dunklen.\n\n")
  LANGUAGE_TEXT(3, "Seto... Da solo... No. Una\ncarta divina non basta.\n\nNon avrai scampo.\n\nNon contro Pegasus e\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Seto... T\xfa solo... No.\n\nUna carta del dios\nno es suficiente.\n\nNo tendr\xe1s la\nm\xednima posibilidad.\n\nNo contra Pegasus y\nReshef, el Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "My deck is perfect!\n\nWhoever the opponent may be,\ndefeat isn't in the cards!\n\n")
  LANGUAGE_TEXT(1, "Mon Deck est toujours\nle plus fort !\n\nQuel que soit l'adversaire,\nje gagnerai toujours !\n\n")
  LANGUAGE_TEXT(2, "Mein Deck ist stets das\nst\xe4rkste!\n\nIch kann gegen keinen\nGegner verlieren!\n\n")
  LANGUAGE_TEXT(3, "Il mio deck \xe8 sempre\nil pi\xf9 forte!\n\nChiunque sia l'avversario,\nla sconfitta \xe8 impossibile!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mi deck es siempre\nel m\xe1s fuerte!\n\n\xa1Quienquiera que sea el\noponente, la derrota no\n\nes posible!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(3, 60, 18, 0, 0, 0)
  WALK_OBJECT_Y(3, 32)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 7)
  DELAY(8)
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Then duel me, big brother,\nwith your perfect deck.\n\n")
  LANGUAGE_TEXT(1, "Alors, affronte-moi\nen duel, grand fr\xe8re,\n\navec ton Deck\nle plus fort.\n\n")
  LANGUAGE_TEXT(2, "Dann duellier dich mit mir,\ngro\xdfer Bruder,\n\nmit deinem st\xe4rksten Deck.\n\n")
  LANGUAGE_TEXT(3, "Allora duella con me,\nfratello, con il tuo deck\n\npi\xf9 forte.\n\n")
  LANGUAGE_TEXT(4, "Entonces, lucha conmi-\ngo, gran hermano,\n\ncon tu deck, el\nm\xe1s fuerte de todos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 6, 8)
  LANGUAGE_TEXT(0, "Wh-what? Mokuba? Wh-what are\nyou saying?\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ? Mokuba ? Que\nveux-tu dire par l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "W-was? Mokuba?\nW-was sagst du da?\n\n")
  LANGUAGE_TEXT(3, "Che-che cosa? Mokuba?\nMa-ma che stai dicendo?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9? \xbfMokuba?\n\xbfQ-qu\xe9 dices?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Reshef is going to rule this\nworld anyway.\n\nIt's better to quit fighting\nand accept fate.\n\n")
  LANGUAGE_TEXT(1, "De toute fa\xe7on,\n\nReshef deviendra\nle ma\xeetre du monde.\n\nIl vaut mieux arr\xeater de\nse battre et se r\xe9signer.\n\n")
  LANGUAGE_TEXT(2, "Diese Welt wird ohnehin\nvon Reschef beherrscht\n\nwerden. Besser den Kampf\naufzugeben und sich mit\n\ndem Schicksal abfinden.\n\n")
  LANGUAGE_TEXT(3, "Questo mondo sar\xe0 governato\ncomunque da Reshef.\n\nMeglio smettere di lottare\ne accettare la situazione.\n\n")
  LANGUAGE_TEXT(4, "De cualquier modo, Reshef\nva a dominar el mundo.\n\nEs mejor dejar de\nluchar y aceptar\n\nla realidad.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Mokuba's spirit is under\ncontrol...\n\n")
  LANGUAGE_TEXT(1, "L'\xe2me de cet enfant\nest sous son contr\xf4le...\n\n")
  LANGUAGE_TEXT(2, "Der Geist dieses Kindes\nwird von einem anderen\n\ngesteuert...\n\n")
  LANGUAGE_TEXT(3, "Lo spirito di questo\nragazzino \xe8 sotto\n\ncontrollo...\n\n")
  LANGUAGE_TEXT(4, "El esp\xedritu de este chico\nest\xe1 bajo control...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 5, 8)
  LANGUAGE_TEXT(0, "Pegasus! How dare you!\n\n")
  LANGUAGE_TEXT(1, "Ce Pegasus, comment\nose-t-il dire \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Verdammt sei Pegasus!\nWie kann er es wagen!\n\n")
  LANGUAGE_TEXT(3, "Al diavolo Pegasus!\nCome ha osato fare questo?\n\n")
  LANGUAGE_TEXT(4, "\xa1Aniquila a ese Pegasus!\n\xa1C\xf3mo osa hacer esto!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Big brother, will you join\nme?\n\nOr would you like to duel?\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re,\ntu m'accompagnes ?\n\nOu pr\xe9f\xe8res-tu\nte battre en duel ?\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder, stehst du\nauf meiner Seite?\n\nOder willst du ein Duell?\n\n")
  LANGUAGE_TEXT(3, "Fratello, passerai\ndalla mia parte?\n\nOppure vuoi duellare?\n\n")
  LANGUAGE_TEXT(4, "Gran hermano,\n\xbfte unir\xe1s a m\xed?\n\n\xbfO te gustar\xeda luchar?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 3, 8)
  LANGUAGE_TEXT(0, "Mokuba...\n\nI... I can't duel against\nMokuba...\n\n")
  LANGUAGE_TEXT(1, "Mokuba...\n\nJe... Je ne peux pas me\nbattre contre Mokuba...\n\n")
  LANGUAGE_TEXT(2, "Mokuba...\n\nIch... Ich kann nicht gegen\nMokuba...\n\n")
  LANGUAGE_TEXT(3, "Mokuba...\n\nIo...Non posso duellare\ncontro Mokuba...\n\n")
  LANGUAGE_TEXT(4, "Mokuba...\n\nYo... Yo no puedo\nluchar contra Mokuba...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(32)
  PLAY_MUSIC(272)
  REACTION(3, 4)
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, you must duel in\nKaiba's place.\n\nThat is the only way to\nbreak the mind control over\n\nMokuba.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu dois te battre\nen duel \xe0 la place de Seto.\n\nC'est le seul moyen\nd'emp\xeacher Mokuba\n\nde contr\xf4ler les esprits.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, k\xe4mpf du an\nSetos Stelle.\n\nNur so kann Mokubas Gehirn-\nw\xe4sche aufgehoben werden.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, devi duellare tu\nal posto di Seto. Solo cos\xec\n\npotremo sottrarre Mokuba\nal controllo del pensiero.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, debes de\nluchar en lugar de Seto.\n\nSolamente de ese modo\nse puede romper el\n\ncontrol de la mente\nde Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C30, map_54_state_01_08EE9C30, 0x08EE9C48, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 8)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Huh? {PLAYER} wants to duel\nme?\n\nSure. You have to ante your\nEgyptian God Card.\n\nI don't care who I have to\nduel as long as I can get\n\nan Egyptian God Card.\n\n")
  LANGUAGE_TEXT(1, "Hein ? {PLAYER} veut\nm'affronter en duel ?\n\nOK. De toute fa\xe7on, la Carte\nAnte est ta carte de dieu.\n\nPeu importe l'adversaire\nsi je peux gagner\n\nune carte de dieu.\n\n")
  LANGUAGE_TEXT(2, "Was? {PLAYER} will sich\nmit mir duellieren?\n\nGut. Die Ante-Karte ist ohn-\nehin deine G\xf6tterkarte.\n\nEgal, mit wem ich mich duel-\nliere, solange ich eine\n\nG\xf6tterkarte daf\xfcr bekommen\nkann.\n\n")
  LANGUAGE_TEXT(3, "Come? {PLAYER} vuole\nduellare con me? Certo.\n\nL'Ante-carta \xe8 comunque\nla tua carta divina.\n\nNon m'importa con chi\nduello, se riesco ad avere\n\nuna carta divina.\n\n")
  LANGUAGE_TEXT(4, "\xbfHuh? \xbf{PLAYER} quiere\nluchar conmigo?\n\nClaro. De cualquier\nmodo, la Carta Ante es\n\ntu carta del dios.\n\nNo me importa con\nqui\xe9n lucho si puedo\n\nobtener una\ncarta del dios.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Grr... Mokuba...\n\n")
  LANGUAGE_TEXT(1, "Grr... Mokuba...\n\n")
  LANGUAGE_TEXT(2, "Grr... Mokuba...\n\n")
  LANGUAGE_TEXT(3, "Grr... Mokuba...\n\n")
  LANGUAGE_TEXT(4, "Grr... Mokuba...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Big brother, there's no need\nto be sad.\n\nAfter {PLAYER}, you're next!\n\nAhahahahahaha!\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re, pas la\npeine d'\xeatre si triste.\n\nApr\xe8s {PLAYER},\nc'est ton tour !\n\nAhahahahahaha !\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder, sei nicht\nso niedergeschlagen.\n\nNach {PLAYER} bist du\ndran!\n\nAhahahahahaha!\n\n")
  LANGUAGE_TEXT(3, "Fratello, non c'\xe8 motivo\ndi essere cos\xec triste.\n\nDopo {PLAYER}, sar\xe0\nil tuo turno!\n\nAhahahahahahah!\n\n")
  LANGUAGE_TEXT(4, "Gran hermano, no hay\nnecesidad de estar triste.\n\n\xa1Despu\xe9s de {PLAYER},\nes tu turno!\n\n\xa1Ahahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  WALK_OBJECT_Y(0, 52)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 8)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, 8, 8)
  LANGUAGE_TEXT(0, "Don't give me that look!\n\nI'll show you how it feels\nto lose!\n\n")
  LANGUAGE_TEXT(1, "C'est quoi, ce regard\nm\xe9chant ?\n\nJe vais te montrer ce\nque \xe7a fait de perdre !\n\n")
  LANGUAGE_TEXT(2, "Warum starrst du mich so an?\nH\xe4ltst dich wohl f\xfcr\n\nperfekt.\n\nIch zeige dir, wie schlimm\nverlieren ist!\n\n")
  LANGUAGE_TEXT(3, "Cos'\xe8 quello sguardo?\nPensi di essere tanto\n\nbravo? Ti far\xf2 assaporare\nl'amarezza della sconfitta!\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 pasa con\nla mirada?\n\nCrees que eres\nmuy bueno.\n\n\xa1Te mostrar\xe9 cu\xe1n\nmiserable es perder!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 37)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 63)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 42)
  DELAY(16)
  DUEL(119)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C48, map_54_state_01_08EE9C48, 0x08EE9C54, 0x08F0404C)
  PLAY_MUSIC(369)
  PORTRAIT(PORTRAIT_MOKUBA, 6, 8)
  LANGUAGE_TEXT(0, "Arrggh! M-my head! Seto, it\nhurts!\n\nHelp me, Seto!\n\n")
  LANGUAGE_TEXT(1, "Arrggh ! Ma t\xeate !\nGrand fr\xe8re, j'ai mal !\n\nA l'aide, grand fr\xe8re !\n\n")
  LANGUAGE_TEXT(2, "Arrggh! M-mein Kopf!\nDas tut weh, gro\xdfer Bruder!\n\nHilf mir, gro\xdfer Bruder!\n\n")
  LANGUAGE_TEXT(3, "Arrrggh! La mia testa!\nFratello, mi fa male!\n\nAiutami, fratello mio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arrggh! \xa1M-mi cabeza!\nGran hermano, \xa1duele!\n\n\xa1Ay\xfadame, gran hermano!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 6, 8)
  LANGUAGE_TEXT(0, "Mokuba!\n\n")
  LANGUAGE_TEXT(1, "Mokuba !\n\n")
  LANGUAGE_TEXT(2, "Mokuba!\n\n")
  LANGUAGE_TEXT(3, "Mokuba!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mokuba!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(1, 54)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 50)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Mokuba, have you regained\nyour senses?\n\n")
  LANGUAGE_TEXT(1, "Mokuba, tu as\nretrouv\xe9 tes esprits ?\n\n")
  LANGUAGE_TEXT(2, "Mokuba, bist du wieder\nbei Sinnen?\n\n")
  LANGUAGE_TEXT(3, "Mokuba, hai ripreso i sensi?\n\n")
  LANGUAGE_TEXT(4, "Mokuba, \xbfhas recobrado\nel sentido?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 3, 8)
  LANGUAGE_TEXT(0, "Seto... I... I...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re...\nJe... Je...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder... I... I...\n\n")
  LANGUAGE_TEXT(3, "Fratello... Io... Io...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano... Yo... yo..\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Don't say another word. It's\nover, Mokuba.\n\n")
  LANGUAGE_TEXT(1, "Plus la peine de parler.\nC'est fini, Mokuba.\n\n")
  LANGUAGE_TEXT(2, "Sag nichts mehr.\nEs ist vorbei, Mokuba.\n\n")
  LANGUAGE_TEXT(3, "Non dire altro.\n\xc8 finita, Mokuba.\n\n")
  LANGUAGE_TEXT(4, "No digas m\xe1s.\nSe termin\xf3, Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, 3, 8)
  LANGUAGE_TEXT(0, "Big brother...\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re...\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder...\n\n")
  LANGUAGE_TEXT(3, "Fratello...\n\n")
  LANGUAGE_TEXT(4, "Gran hermano...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 34)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 37)
  MOVE_OBJECT(1, 3, 0, 0)
  WALK_OBJECT_X(3, 68)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(405)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "I hate to say this, but I\nowe you one.\n\nYou have to duel Pegasus\nnext...\n\nYou need my Egyptian God\nCard, don't you?\n\nFine... I could just hand it\nto you....\n\n")
  LANGUAGE_TEXT(1, "J'ai une obligation\nenvers toi.\n\nTu dois maintenant te battre\nen duel contre Pegasus...\n\nTu auras besoin de ma\ncarte de dieu, non ?\n\nBien... Je veux bien\nte la donner...\n\n")
  LANGUAGE_TEXT(2, "Ich habe jetzt eine Aufgabe\nf\xfcr dich.\n\nDuelliere dich mit Pegasus.\n\nDazu ben\xf6tigst du meine\nG\xf6tterkarte, nicht wahr?\n\nOkay... Ich gebe sie dir...\n\n")
  LANGUAGE_TEXT(3, "Ti sono debitore. Ora devi\nduellare con Pegasus...\n\nTi serve la mia carta\ndivina, vero?\n\nBene... Potrei anche\nconvincermi a dartela...\n\n")
  LANGUAGE_TEXT(4, "Ahora tengo una\ndeuda contigo.\n\nAhora tienes que luchar\ncon Pegasus...\n\nNecesitas mi carta\ndel dios, \xbfno?\n\nVale... Si se me\npersuadiera para d\xe1rtela...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 5)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Kaiba...\n\n")
  LANGUAGE_TEXT(1, "Seto...\n\n")
  LANGUAGE_TEXT(2, "Seto...\n\n")
  LANGUAGE_TEXT(3, "Seto...\n\n")
  LANGUAGE_TEXT(4, "Seto...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "But you and I are duelists.\n\nTherefore, the only way you\ncan get my card is in a\n\nduel!\n\nThat's all that needs to be\nsaid.\n\nNow, come on, {PLAYER}.\n\nMy strongest monster will\nannhilate you!\n\nObelisk the Tormentor will\ndecide the outcome!\n\n")
  LANGUAGE_TEXT(1, "Mais toi et moi, nous\nsommes des duellistes.\n\nTout \xe9change de cartes\ndoit se faire par un duel !\n\nPour nous, duellistes,\npas la peine de parler.\n\nAllez, maintenant,\n{PLAYER}.\n\nLa plus forte de mes\ncartes va t'\xe9craser !\n\nOb\xe9lisk, le Bourreau\nva d\xe9cider de l'issue\n\ndu combat !\n\n")
  LANGUAGE_TEXT(2, "Aber nur wenn wir uns\nerst duellieren.\n\nAlle Karten werden nur im\nDuell ausgetauscht!\n\nWir Duellanten verstehen\nuns ohne Worte.\n\nKomm, {PLAYER}.\n\nMeine st\xe4rkste Karte wird\ndich vernichten!\n\nObelisk, der Peiniger, m\xf6ge\ndas Ergebnis verk\xfcnden!\n\n")
  LANGUAGE_TEXT(3, "Ma tu ed io siamo duellanti.\nQuindi, tutti gli scambi di\n\ncarte si fanno duellando!\nPer noi duellanti, non c'\xe8\n\nbisogno di altre parole.\nAllora, forza, {PLAYER}.\n\nLa pi\xf9 forte di tutte le mie\ncarte ti annienter\xe0!\n\nObelisco del Tiranno\ndecider\xe0 l'esito!\n\n")
  LANGUAGE_TEXT(4, "Pero, t\xfa y yo somos\nduelistas.\n\nY, por ello, \xa1todos los\nintercambios de cartas\n\nhan de ser por medio\nde duelos!\n\nPara nosotros, duelistas,\nno hay necesidad\n\nde m\xe1s palabras.\n\nAhora, vamos, {PLAYER}.\n\n\xa1La m\xe1s fuerte de mis\ncartas te destrozar\xe1!\n\n\xa1Dejemos que Obelisk\nel atormentador\n\ndecida el resultado!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 42)
  DELAY(32)
  DUEL(120)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C54, map_54_state_01_08EE9C54, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Urrrgh...\n\n")
  LANGUAGE_TEXT(1, "Urrrgh...\n\n")
  LANGUAGE_TEXT(2, "Arrrgh...\n\n")
  LANGUAGE_TEXT(3, "Urrrgh...\n\n")
  LANGUAGE_TEXT(4, "Urrrgh...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Your powers were evenly\nmatched...\n\nBut {PLAYER}'s pure spirit\nwon the duel.\n\nHe also received the help of\nhis fellow duelists...\n\nPerhaps his pure spirit can\ncounter the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "Vos pouvoirs sont\nbien \xe9quilibr\xe9s...\n\nL'esprit pur de {PLAYER},\ncelui qu'il a re\xe7u de ses\n\namis duelliste, a d\xe9cid\xe9\nde ce duel.\n\nSon esprit pur pourra\npeut-\xeatre battre l'Etre\n\ndes t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Eure Kr\xe4fte waren\nausgewogen...\n\n{PLAYER}s reiner Geist\nentschied das Duell.\n\nDer reine Geist, den ihm\nandere Duellanten gaben...\n\nVielleicht kann dieser reine\nGeist auch dem Dunklen\n\ntrutzen.\n\n")
  LANGUAGE_TEXT(3, "I vostri poteri erano\ndi pari livello...\n\nLe sorti del duello sono\nstate decise dallo spirito\n\npuro di {PLAYER}, che\nha ricevuto dagli amici\n\nduellanti... Forse il suo\nspirito puro riuscir\xe0 a\n\nbloccare il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Tus poderes estaban\nmuy igualados...\n\nLo que decidi\xf3 el\nduelo ha sido el\n\nesp\xedritu puro de\n{PLAYER}.\n\nEl esp\xedritu puro que\nrecibi\xf3 de sus\n\ncolegas duelistas...\n\nQuiz\xe1s su esp\xedritu\npuro pueda plantar\n\ncara al Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "There's nothing for me to\nsay.\n\nYou earned this card.\n\nI don't care if you duel\nPegasus or Reshef...\n\nJust don't lose using my\nbest card!\n\n")
  LANGUAGE_TEXT(1, "Les perdants doivent\nse taire.\n\nTu as gagn\xe9 ceci.\n\nPeu importe si c'est\nPegasus ou Reshef...\n\nMais tu ne dois pas\nperdre en utilisant mes\n\nmeilleures cartes !\n\n")
  LANGUAGE_TEXT(2, "Ein Verlierer hat nichts\nzu sagen.\n\nDu hast dir das hier\nverdient.\n\nMir ist es egal, ob Pegasus\noder Reschef...\n\nAber verlier besser nicht\nmit meiner besten Karte!\n\n")
  LANGUAGE_TEXT(3, "Un perdente non ha\nniente da dire.\n\nQuesta te la sei meritata.\nNon m'importa se sar\xe0\n\nPegasus o quel Reshef...\nMa tu farai meglio a non\n\nperdere usando la mia\ncarta migliore!\n\n")
  LANGUAGE_TEXT(4, "Un perdedor no tiene\nnada que decir.\n\nT\xfa lo has ganado.\n\nNo me importa si\nes Pegasus o\n\neste tal Reshef...\n\n\xa1Pero mejor que no\npierdas utilizando\n\nmi mejor carta!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(285)
  SHOW_OBJECT(5, 60, 46, 0, 0, 0)
  DELAY(32)
  PLAY_MUSIC(286)
  SLIDE_OBJECT(5, 0, 16)
  DELAY(32)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(32)
  LANGUAGE_TEXT(0, "Received Obelisk the\nTormentor!")
  LANGUAGE_TEXT(1, "Re\xe7u Ob\xe9lisk,\nle Bourreau !")
  LANGUAGE_TEXT(2, "Obelisk, den Peiniger,\nerhalten!")
  LANGUAGE_TEXT(3, "Ricevuto Obelisco\ndel Tiranno!")
  LANGUAGE_TEXT(4, "\xa1Recibido Obelisk\nel atormentador!")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PAGE_BREAK()
  ADD_CARD(234)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Come, {PLAYER}, we must go.\n\nThe time has come to seal\nReshef the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "Viens, {PLAYER}, partons.\n\nNous devons enfermer Reshef,\nl'Etre des t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Komm, {PLAYER}, wir\nm\xfcssen gehen.\n\nEs ist an der Zeit,\nReschef den Dunklen\n\neinzuschlie\xdfen.\n\n")
  LANGUAGE_TEXT(3, "Forza, {PLAYER},\ndobbiamo andare.\n\n\xc8 giunta l'ora di bloccare\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Vamos, {PLAYER},\ndebemos irnos.\n\nHa llegado la hora de sellar\na Reshef, el Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(173)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C3C, map_54_state_01_08EE9C3C, 0x08EE9C30, 0x08EE9C3C)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "But... If you refuse...\n\nReshef the Dark Being will\nrule the world.\n\nPlease, {PLAYER}!\n\nYou must duel in Kaiba's\nplace!\n\n")
  LANGUAGE_TEXT(1, "Mais...\nSi tu refuses...\n\nReshef, l'Etre des t\xe9n\xe8bres\nsera le ma\xeetre du monde.\n\nS'il te pla\xeet, {PLAYER} !\n\nTu dois te battre en duel\n\xe0 la place de Seto !\n\n")
  LANGUAGE_TEXT(2, "Aber...\nWenn du dich weigerst...\n\nWird Reschef der Dunkle\ndie Welt beherrschen.\n\nBitte, {PLAYER}!\n\nDuelliere dich an Setos\nstatt!\n\n")
  LANGUAGE_TEXT(3, "Ma...\nSe rifiuti...\n\nIl mondo cadr\xe0 in mano a\nReshef il Tenebroso.\n\nTi prego, {PLAYER}!\n\nDevi duellare al\nposto di Seto!\n\n")
  LANGUAGE_TEXT(4, "Pero...\nSi reh\xfasas...\n\nReshef, el Ser Oscuro\nvendr\xe1 a dominar\n\nel mundo.\n\xa1Por favor, {PLAYER}!\n\n\xa1Debes luchar en\nlugar de Seto!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, 0, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C60, map_54_state_01_08EE9C60, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, 0, 8)
  LANGUAGE_TEXT(0, "Hurry up and beat Pegasus.\n\n")
  LANGUAGE_TEXT(1, "Continue si tu veux\nbattre Pegasus...\n\n")
  LANGUAGE_TEXT(2, "Schlag Pegasus.\n\n")
  LANGUAGE_TEXT(3, "Pensa a battere Pegasus.\n\n")
  LANGUAGE_TEXT(4, "Vete a vencer a Pegasus.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C78, map_54_state_01_08EE9C78, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, 0, 8)
  LANGUAGE_TEXT(0, "Come, {PLAYER}, we must go.\n\nThe time has come to seal\nReshef the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "Allez, {PLAYER}, partons.\n\nNous devons enfermer Reshef,\nl'Etre des t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Los, {PLAYER}, wir m\xfcssen\naufbrechen.\n\nEs ist an der Zeit,\nReschef den Dunklen\n\neinzuschlie\xdfen.\n\n")
  LANGUAGE_TEXT(3, "Forza, {PLAYER},\ndobbiamo andare.\n\n\xc8 giunta l'ora di bloccare\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Vamos, {PLAYER},\ndebemos irnos.\n\nHa llegado la hora de sellar\na Reshef, el Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE9C6C, map_54_state_01_08EE9C6C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, 3, 8)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
