#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_57_state_02: map 57 state 2 */

LOAD_SPRITE(1, SPRITE_KAIBAMAN)
LOAD_SPRITE(2, SPRITE_MOKUBA)
LOAD_SPRITE(3, SPRITE_SEEKER)
LOAD_SPRITE(4, SPRITE_DEEPSEA_WARRIOR)
LOAD_SPRITE(5, SPRITE_NIGHTMARE_PENGUIN)
LOAD_SPRITE(6, SPRITE_JUDGE_MAN)
LOAD_SPRITE(7, SPRITE_ROBOTIC_KNIGHT)
LOAD_SPRITE(8, SPRITE_JINZO)
LOAD_SPRITE(9, SPRITE_ROBA_BROTHER_1)
LOAD_SPRITE(10, SPRITE_ROBA_BROTHER_2)
LOAD_SPRITE(11, SPRITE_ROBA_BROTHER_3)
LOAD_SPRITE(12, SPRITE_ESPA)
PLAY_MUSIC(MUSIC_KAIBALAND)
DELAY(32)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_11, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Yeah, do it, Kaibaman!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_10, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Bash the Big Bad Five!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Thanks, everyone!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Prepare for final justice,\n"
    "Big Bad Five!\n\n"
    "Prepare to feel Kaibaman's\n"
    "ultimate finisher, Final\n\n"
    "Card Flash!\n\n"
)
PLAY_MUSIC(MUSIC_296)
SPECIAL(1)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(4, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(5, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(6, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(7, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(8, 2, 16)
PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Graaah! We're done for!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_344)
PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Justice just rules! I am\n"
    "victorious in victory!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Uh... That's the weirdest\n"
    "catchphrase I've ever\n\n"
    "heard, but I guess it's\n"
    "cool.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_9, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Kaibaman!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_407)
WALK_OBJECT_X(3, 44)
WALK_OBJECT_Y(3, 55)
WALK_OBJECT_X(3, 71)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_9 | OBJECT_10 | OBJECT_11 | OBJECT_13 | OBJECT_14)
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_9, OBJECT_EFFECT_JUMPING)
TEXT
(
    "L-look at that guy!\n\n"
)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Kukuku... Kaibaman, is it?\n"
    "You claim to be powerful,\n\n"
    "but are you really?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_1)
DELAY(16)
PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Uh.. Yes, yes, of course!\n"
    "Justice just rules!\n\n"
)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Then let's put your theory\n"
    "to the test!\n\n"
)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Oh my gosh! It's a mystery\n"
    "opponent!\n\n"
)
FADE_SCREEN(4)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Exodia, obliterate!\n\n"
)
PLAY_MUSIC(MUSIC_340)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_EXODIA_ATTACK_BOTTOM_RIGHT)
DELAY(16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(1, 3, 18)
PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Gwaaaaah!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_205)
OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_DISAPPEAR)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_9, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Oh no! Kaibaman!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(3, 77)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "This scrub isn't worth\n"
    "recruiting into the Neo\n\n"
    "Ghouls...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_4 | OBJECT_5 | OBJECT_6 | OBJECT_7 | OBJECT_8)
DELAY(16)
WALK_OBJECT_Y(4, 38)
DELAY(16)
PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "What impeccable strategy!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(5, 28)
DELAY(16)
PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "After crunching the numbers,\n"
    "I've calculated that\n\n"
    "there's no one more powerful\n"
    "than a Neo Ghouls duelist!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(6, 38)
DELAY(16)
PORTRAIT(PORTRAIT_JUDGE_MAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "I judge that to be accurate!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(7, 28)
DELAY(16)
PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "My gut instincts were right\n"
    "about him.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(8, 38)
DELAY(16)
PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "You're exactly who we've\n"
    "been waiting for!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(3, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Who are you?\n\n"
)
PORTRAIT(PORTRAIT_JUDGE_MAN, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Ah, pardon our rudeness.\n\n"
    "We are the Big Five, and we\n"
    "seek a new leader.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
DELAY(8)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, PORTRAIT_LEFT)
TEXT
(
    "Are you guys turning on us\n"
    "again?\n\n"
)
PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "You were the one who\n"
    "betrayed us in the first\n\n"
    "place by firing us!\n\n"
)
PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Turnaround is fair play.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_275)
REACTION(REACTION_ANGRY, OBJECT_2)
DELAY(16)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, PORTRAIT_LEFT)
TEXT
(
    "Those traitors!\n\n"
)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Fine, I'll let you work for\n"
    "me.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "First, round up those kids.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(7, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(8, DIRECTION_LEFT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_9 | OBJECT_10 | OBJECT_11)
DELAY(16)
MOVE_OBJECT(3, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "I have business with their\n"
    "brother.\n\n"
    "Let's just say he didn't\n"
    "treat my minions with the\n\n"
    "respect that they deserve.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(6, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(7, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(8, DIRECTION_DOWN, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Right away, leader!\n\n"
)
PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "I don't think so... Huh?\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
DELAY(32)
MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
DELAY(8)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
WALK_OBJECT_X(12, 44)
WALK_OBJECT_Y(12, 55)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
WALK_OBJECT_X(12, 68)
DELAY(16)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_ANGRY, PORTRAIT_LEFT)
TEXT
(
    "Leave my brothers alone!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "It's you again!\n\n"
)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, PORTRAIT_LEFT)
TEXT
(
    "Pipipi...\n\n"
)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "My psychic powers led me\n"
    "here!\n\n"
)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Heh, whatever you say,\n"
    "freak.\n\n"
    "Big {BYTE_8254}, get him!\n\n"
)
PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "We'll help ya! Come on,\n"
    "{PLAYER}!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(12, 88)
MOVE_OBJECT(12, DIRECTION_UP, 4, 0)
WALK_OBJECT_X(0, 44)
WALK_OBJECT_Y(0, 55)
WALK_OBJECT_X(0, 68)
WALK_OBJECT_Y(13, 42)
WALK_OBJECT_X(13, 44)
WALK_OBJECT_Y(13, 55)
WALK_OBJECT_X(13, 58)
WALK_OBJECT_Y(14, 40)
WALK_OBJECT_X(14, 44)
WALK_OBJECT_Y(14, 49)
WALK_OBJECT_X(14, 58)
DELAY(16)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Unlike last time, I'm taking\n"
    "off the kiddie gloves!\n\n"
)
DUEL(DUELIST_SEEKER_051)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_ANGRY, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Come on, Jinzo!\n\n"
)
PLAY_MUSIC(MUSIC_333)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_JINZO_FULL_ART)
DELAY(16)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_ANGRY, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Cyber Energy Shock!\n\n"
)
PLAY_MUSIC(MUSIC_339)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_JINZO_ATTACK_UP)
DELAY(16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(4, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(5, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(6, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(7, 2, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(8, 2, 16)
DELAY(8)
PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "Waaaah!\n\n"
)
PORTRAIT(PORTRAIT_SEEKER, EXPRESSION_SEEKER_DEFEATED, PORTRAIT_POSITION_AUTO)
TEXT
(
    "N-not again...\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
WALK_OBJECT_X(3, 44)
WALK_OBJECT_Y(3, 72)
WALK_OBJECT_X(3, 0)
MOVE_OBJECT(3, DIRECTION_LEFT, 16, 0)
MOVE_OBJECT(8, DIRECTION_DOWN, 4, 0)
DELAY(8)
PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "P-please wait!\n\n"
)
FADE_SCREEN(4)
SHOW_OBJECT(4, 128, 96, 0, 0, 0)
SHOW_OBJECT(5, 128, 96, 0, 0, 0)
SHOW_OBJECT(6, 128, 96, 0, 0, 0)
SHOW_OBJECT(7, 128, 96, 0, 0, 0)
SHOW_OBJECT(8, 128, 96, 0, 0, 0)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_KAIBACORP)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "I knew I couldn't trust\n"
    "them!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(9, 42)
WALK_OBJECT_X(9, 88)
WALK_OBJECT_Y(9, 41)
MOVE_OBJECT(9, DIRECTION_DOWN, 0, 0)
WALK_OBJECT_Y(10, 42)
WALK_OBJECT_X(10, 95)
WALK_OBJECT_Y(10, 46)
MOVE_OBJECT(10, DIRECTION_LEFT, 0, 0)
WALK_OBJECT_Y(11, 42)
WALK_OBJECT_X(11, 81)
WALK_OBJECT_Y(11, 46)
MOVE_OBJECT(11, DIRECTION_RIGHT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_9, OBJECT_EFFECT_JUMPING)
TEXT
(
    "B-big brother...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_10, OBJECT_EFFECT_JUMPING)
TEXT
(
    "I was scared, Espa.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_11, OBJECT_EFFECT_JUMPING)
TEXT
(
    "I, I'm sorry, big brother.\n\n"
    "I didn't think you would\n"
    "come. I knew I should've\n\n"
    "believed in you...\n\n"
)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Don't worry about it. I\n"
    "didn't know if I'd get here\n\n"
    "in time either.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_11, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Big brother...\n\n"
    "We don't need Kaibaman!\n"
    "You're our hero, Espa!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Heh, maybe we should make\n"
    "Espa Roba the hero of the\n\n"
    "show.\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
DELAY(32)
PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_LEFT)
TEXT
(
    "Speaking of brothers... I\n"
    "wonder if Seto's okay...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(12, 55)
WALK_OBJECT_X(12, 77)
DELAY(16)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "That takes care of the Neo\n"
    "Ghouls.\n\n"
)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_ESPA_ROBA_EYES_CLOSED, PORTRAIT_LEFT)
TEXT
(
    "Pipipi...\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
DELAY(8)
PORTRAIT(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Ishizu is at the Egypt\n"
    "Exhibition.\n\n"
    "That's what my connection\n"
    "with the cosmic waves is\n\n"
    "telling me.\n\n"
    "Hurry, you've got to help\n"
    "Ishizu!\n\n"
)
SET_FLAG(EVENT_FLAG_DEFEATED_SEEKER2)
FADE_SCREEN(8)
WARP(LOCATION_KAIBACORP, 7, 1, 0)
