#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_60_state_01: map 60 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08F039CC, map_60_state_01_08F039CC, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MARIK)
  LOAD_SPRITE(2, SPRITE_ODION)
  PLAY_MUSIC(MUSIC_MARIK_ISHTAR)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Father, Mother...",
      "And all those people I harmed...",
      "I hope that the sun shines upon your spirits."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Hello. It has been a long time.")
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Master Marik, forgive us for disturbing your rituals.")
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "It does not matter. They are always welcome.",
      "Even my departed Father would have welcomed them."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Marik, we need your help.",
      "We have to awaken {PLAYER}'s The Winged Dragon of Ra."
  )
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...Tell me more.")
  HIDE_PORTRAIT()
  PLAY_MUSIC(MUSIC_332)
  FADE_SCREEN(4)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "So... That explains why my sister left in a hurry.",
      "It makes sense now..."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I understand what you seek.")
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Great! Then how about getting on it right away?")
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I will not awaken Ra so easily.")
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO, "What?!")
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I believe you know why.",
      "Ra is the most powerful of the Egyptian God Cards.",
      "You felt its mystical strength firsthand."
  )
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_332)
  FADE_MUSIC(4)
  FADE_SCREEN(4)
  SET_FLAG(EVENT_FLAG_FLASHBACK)
  WARP(LOCATION_EGYPT_EXHIBITION_MILLENNIUM_GUARDIAN, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A38, map_60_state_01_08F03A38, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "There must be a secret in the hieroglyphics.",
      "A secret method for awakening the Phoenix Mode."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A44, map_60_state_01_08F03A44, 0x08F03A50, 0x08F03A5C)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Fine.",
      "I have been freed of my obligations as a",
      "gravekeeper.",
      "When I duel, I duel for myself and will use all my",
      "arcane strategies!"
  )
  DUEL(DUELIST_MARIK_158)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A50, map_60_state_01_08F03A50, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_MARIK_ISHTAR)
  TALK(PORTRAIT_MARIK, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You won...",
      "You may be ready to face the Dark Being..."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A5C, map_60_state_01_08F03A5C, 0x08F0404C, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_EXITED_MARIKS_HOME)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A08, map_60_state_01_08F03A08, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Since you arrived, Master Marik has been chanting",
      "devoutly.",
      "He is chanting to atone for his past sins."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A14, map_60_state_01_08F03A14, 0x08F03A20, 0x08F03A2C)
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You dare enter my haven of traps?",
      "Fine! We shall duel!"
  )
  DUEL(DUELIST_ODION_157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A20, map_60_state_01_08F03A20, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_MARIK_ISHTAR)
  TALK(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Gah! Your fighting spirit is most impressive!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08F03A2C, map_60_state_01_08F03A2C, 0x08F0404C, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_EXITED_MARIKS_HOME)
  FALLTHROUGH()
END_EVENT_SCRIPT()
