#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_03: map 51 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EE3D34, map_51_state_03_08EE3D34, 0x08EE3D58, 0x08EE3DAC)
  LOAD_SPRITE(1, SPRITE_REX)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_REX_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D58, map_51_state_03_08EE3D58, 0x08EE3D64, 0x08EE3D94)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(1, 60, 48, 0, 1, 0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_REX3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D64, map_51_state_03_08EE3D64, 0x08EE3D70, 0x08EE3D7C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_REX_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D70, map_51_state_03_08EE3D70, 0x08EE3D88, 0x08EE401C)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I remember that you beat me!",
      "You're in for a prehistoric pounding!"
  )
  DUEL(DUELIST_REX_114)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D88, map_51_state_03_08EE3D88, 0x08EE3FD4, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "What? You're happy that you won?",
      "Ha ha ha... Like that's going to help you!",
      "I'm still not letting you get past me!"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_REX_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D7C, map_51_state_03_08EE3D7C, 0x08EE3D88, 0x08EE401C)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You're persistent, I'll give you that.",
      "But it won't change a thing."
  )
  DUEL(DUELIST_REX_114)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D94, map_51_state_03_08EE3D94, 0x08EE3DA0, 0x08EE401C)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Y-you! That card...",
      "No! Come on, duel!"
  )
  DUEL(DUELIST_REX_114)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DA0, map_51_state_03_08EE3DA0, 0x08EE3DAC, EVENT_NOP)
  TALK(PORTRAIT_REX, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "That card... That card represents me...",
      "That's my spirit card."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_393)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  DELAY(8)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(SPRITE_CHEVALIER, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_REX_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DAC, map_51_state_03_08EE3DAC, EVENT_NOP, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_GOT_PAST_DARK_REX_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D40, map_51_state_03_08EE3D40, 0x08EE3D34, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3D4C, map_51_state_03_08EE3D4C, 0x08EE3D34, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FE0, map_51_state_03_08EE3FE0, EVENT_NOP, EVENT_NOP)
  CLEAR_FLAG(230)
  WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
