#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_32_state_05: map 32 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EB90F0, map_32_state_05_08EB90F0, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Huh?\n"
      "Where are we?\n\n"
  )
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "We went into that tall\n"
      "building, but...\n\n"
  )
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "A-anyway, let's keep movin'.\n\n"
  )
  SET_FLAG(EVENT_FLAG_NOTICED_PARADOX_GAUNTLET_LOOP)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB90FC, map_32_state_05_08EB90FC, 0x08EB9108, 0x08EB9168)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "You'll proceed no further\n"
      "without defeating me!\n\n"
  )
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_079)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9108, map_32_state_05_08EB9108, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_242)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT
  (
      "Most impressive.\n"
      "You deserve a card.\n\n"
      "Take this Time Wizard.\n\n"
  )
  ADD_CARD(16)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Your path is clear.\n"
    "Advance.\n\n"
)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN2)
  FALLTHROUGH()
END_EVENT_SCRIPT()
