#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_32_state_04: map 32 state 4 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EB915C, map_32_state_04_08EB915C, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB90D8, map_32_state_04_08EB90D8, 0x08EB90E4, 0x08EB9168)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You'll proceed no further without defeating me!")
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_078)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB90E4, map_32_state_04_08EB90E4, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_242)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Most impressive. You deserve a card.",
      "Take this Kuriboh."
  )
  ADD_CARD(58)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Your path is clear. Advance.")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9168, map_32_state_04_08EB9168, 0x08F0404C, EVENT_NOP)
  CLEAR_FLAG(152)
  CLEAR_FLAG(154)
  CLEAR_FLAG(155)
  CLEAR_FLAG(156)
  CLEAR_FLAG(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()
