#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_27_state_01: map 27 state 1 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EA4F1C, map_27_state_01_08EA4F1C, 0x08EA4F34, 0x08EA4F70)
  LOAD_SPRITE(1, SPRITE_MILLENNIUM_GUARDIAN)
  LOAD_SPRITE(2, SPRITE_SHADI)
  LOAD_SPRITE(3, SPRITE_MILLENNIUM_KEY)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F34, map_27_state_01_08EA4F34, 0x08EA4F40, 0x08F0404C)
  PLAY_MUSIC(MUSIC_402)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "To the souls guided here by the Millennium Item...",
      "Prove your worth by conquering my duel",
      "challenge!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_Y(0, 56)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_X(14, 62)
  WALK_OBJECT_Y(14, 50)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  WALK_OBJECT_X(13, 62)
  WALK_OBJECT_Y(13, 62)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  DUEL(DUELIST_MILLENNIUM_GUARDIAN_035)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F40, map_27_state_01_08EA4F40, 0x08EA4F4C, EVENT_NOP)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Impressive. Take this item.")
  SET_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F4C, map_27_state_01_08EA4F4C, 0x08EA4F58, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_316)
  SHOW_OBJECT(3, 90, 56, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_278)
  SLIDE_OBJECT(3, 1, 14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(MUSIC_406)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(2, 82, 56, 0, 1, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F58, map_27_state_01_08EA4F58, 0x08EA4F64, EVENT_NOP)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "Waaah! W-what's goin' on?")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Sh-Shadi? But, how?")
  TALK(PORTRAIT_SHADI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "The Millennium Items retain the memories of their",
      "bearers.",
      "These memories will guide the chosen duelists in",
      "their quest.",
      "Follow them to the salvation of the world."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  PLAY_MUSIC(MUSIC_281)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_TELEPORT)
  SET_OBJECT_POSITION(2, 56, 248, 1)
  DELAY(64)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F64, map_27_state_01_08EA4F64, 0x08F04250, EVENT_NOP)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "H-he disappeared...")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Was that Shadi's memory in the Millennium Key?")
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "W-well, we scored the Millennium Key!")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Yeah! Joey, {PLAYER}, we should go see Ishizu.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F70, map_27_state_01_08EA4F70, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Millennium Items are believed to attract each",
      "other.",
      "The Millennium Key will lead you to the next item."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F28, map_27_state_01_08EA4F28, 0x08EA4F34, 0x08EA4F7C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F7C, map_27_state_01_08EA4F7C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "You are only allowed to duel me once.",
      "Did you not have to leave immediately?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
