#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_03: map 12 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E6EFF4, map_12_state_03_08E6EFF4, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  LOAD_SPRITE(2, SPRITE_MOKUBA)
  LOAD_SPRITE(3, SPRITE_TRISTAN)
  LOAD_SPRITE(4, SPRITE_DUKE)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  WALK_OBJECT_X(0, 16)
  WALK_OBJECT_Y(13, 54)
  WALK_OBJECT_X(13, 6)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 6)
  DELAY(16)
  TALK(PORTRAIT_ROLAND, "I told you! No!")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, "Oh, come on, please?")
  TALK(PORTRAIT_DUKE, "Yeah, we're Kaiba's best friends.")
  TALK(PORTRAIT_ROLAND, "I've never heard of you two before.")
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_3 | OBJECT_4)
  WALK_OBJECT_X(2, 102)
  WALK_OBJECT_Y(2, 56)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  TALK(PORTRAIT_MOKUBA, "What's going on?")
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_ROLAND, "Master Mokuba...")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, "M-Mokuba! We're friends, right?")
  TALK(PORTRAIT_DUKE, "Tristan, that's not what we're here for.")
  TALK(PORTRAIT_TRISTAN, "Whoops, that's right.")
  TALK(PORTRAIT_MOKUBA, "...Will somebody tell me what's going on?")
  TALK(PORTRAIT_ROLAND, "These two are demanding that...")
  TALK(PORTRAIT_TRISTAN, "Let us use your Duel Machine!")
  WALK_OBJECT_X(3, 94)
  WALK_OBJECT_X(4, 94)
  TALK(PORTRAIT_MOKUBA,
      "The Duel Machine?",
      "Why do you want it?"
  )
  SLIDE_OBJECT(3, 0, 4)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, "So Serenity will go out with me...")
  PLAY_MUSIC(MUSIC_395)
  SLIDE_OBJECT(4, 2, 4)
  SLIDE_OBJECT(3, 2, 4)
  TALK(PORTRAIT_DUKE,
      "N-no! That's not it!",
      "We want to improve our duel levels."
  )
  SLIDE_OBJECT(3, 0, 4)
  SLIDE_OBJECT(4, 0, 4)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, "Yeah! And THEN get a date with Serenity...")
  PLAY_MUSIC(MUSIC_395)
  SLIDE_OBJECT(4, 2, 4)
  SLIDE_OBJECT(3, 2, 4)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_2)
  TALK(PORTRAIT_MOKUBA,
      "Uh... Well, Seto's not here right now, so I guess it's",
      "okay..."
  )
  PLAY_MUSIC(MUSIC_273)
  REACTION(REACTION_LOVE_HEART, OBJECT_3 | OBJECT_4)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, "Thanks Mokuba!")
  WALK_OBJECT_X(3, 102)
  WALK_OBJECT_Y(3, 44)
  WALK_OBJECT_X(3, 128)
  TALK(PORTRAIT_DUKE, "Yeah, thank you Mokuba.")
  WALK_OBJECT_X(4, 102)
  WALK_OBJECT_Y(4, 44)
  WALK_OBJECT_X(4, 128)
  WALK_OBJECT_Y(2, 44)
  WALK_OBJECT_X(2, 128)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_POSITION_AUTO, "What the heck are those two up to?")
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_ENTER_THE_DUEL_MACHINE_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F000, map_12_state_03_08E6F000, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "This is the first time Master Mokuba invited his",
      "friends to visit him at work...",
      "But are those two really his friends?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
