#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_13_state_01: map 13 state 1 */

LOAD_SPRITE(1, SPRITE_MOKUBA)
LOAD_SPRITE(2, SPRITE_TRISTAN)
LOAD_SPRITE(3, SPRITE_DUKE)
LOAD_SPRITE(4, SPRITE_INVISIBLE)
PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Mokuba, crank it up to the\n"
    "max duelist level!\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "No way! The computer will\n"
    "totally pummel you! Start\n\n"
    "at level {BYTE_8251}.\n\n"
    "If you can't win at that\n"
    "level, then you're plain\n\n"
    "lame.\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Oh, fine. I guess that'll\n"
    "have to do.\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Set me up at the same level!\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Okay, start the Duel\n"
    "Machine!\n\n"
)
PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
FADE_SCREEN(2)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Gwaaaaaaah!\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I... I barely won.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
TEXT
(
    "ASSESSING DUELIST LEVEL...\n\n"
    "ASSESSING DUELIST LEVEL...\n\n"
    "ASSESSMENT COMPLETE.\n\n"
    "BOTH IDIOTS. BOTH IDIOTS.\n\n"
)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Are you serious?\n\n"
)
TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "But I won!\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Simply winning doesn't\n"
    "impress the Duel Machine.\n\n"
    "It also checks for spell and\n"
    "trap combos.\n\n"
    "Judging by your skills, I'd\n"
    "say the computer made the\n\n"
    "right call.\n\n"
)
TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Oh yeah? One more time!\n\n"
)
TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Go right ahead. But I think\n"
    "you're wasting your time.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(SPRITE_MOKUBA, 32)
WALK_OBJECT_Y(SPRITE_MOKUBA, 52)
WALK_OBJECT_X(SPRITE_MOKUBA, 16)
SET_OBJECT_POSITION(SPRITE_MOKUBA, 128, 96, 0)
SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DUELING_THE_DUEL_MACHINE)

EVENT_SCRIPT_REPLACEMENT(0x08E716AC, map_13_state_01_08E716AC, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "I'm training! Don't distract\n"
    "me!\n\n"
)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716B8, map_13_state_01_08E716B8, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Can't you see I'm dueling?\n\n"
)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716C4, map_13_state_01_08E716C4, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "I can't lose to Tristan.\n\n"
)
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E716D0, map_13_state_01_08E716D0, 0x08F04040, 0x08F04040)
TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Please don't bug me while\n"
    "I'm training.\n\n"
)
  MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E71760, map_13_state_01_08E71760, 0x08F04040, 0x08F04040)
PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  TEXT
  (
      "OPERATING AT DUELIST LEVEL\n"
      "{BYTE_8251}.\n\n"
      "SYSTEM IN OPERATION.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7176C, map_13_state_01_08E7176C, 0x08F04040, 0x08F04040)
PLAY_MUSIC(SFX_DUEL_COMPUTER_BEEP)
  TEXT
  (
      "OPERATING AT DUELIST LEVEL\n"
      "FOR IDIOTS.\n\n"
      "SYSTEM IN OPERATION.\n\n"
      "WAIT FOR YOUR TURN BEFORE\n"
      "STARTING.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
