#include "event_macros.h"
#include "overworld.h"

/* map_06_state_01: map 6 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CBB8, map_06_state_01_08E5CBB8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yo, {PLAYER}!\n\nI heard from Tea. I know you\ncan win!\n\n")
  LANGUAGE_TEXT(1, "Ho, {PLAYER} !\n\nJ'ai entendu, pour Tea.\nAllez, vas-y !\n\n")
  LANGUAGE_TEXT(2, "He, {PLAYER}!\n\nIch habe von Tea geh\xf6rt.\nNur zu!\n\n")
  LANGUAGE_TEXT(3, "Ehi, {PLAYER}!\n\nHo sentito di Tea.\nMetticela tutta!\n\n")
  LANGUAGE_TEXT(4, "Hey, {PLAYER}!\n\nMe lo dijo Tea.\n\xa1A por ello!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CBC4, map_06_state_01_08E5CBC4, 0x08E5CBD0, 0x08F0404C)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You want to duel me?\n\nSure thing! Let's duel!\n\n")
  LANGUAGE_TEXT(1, "Tu veux m'affronter\nen duel ?\n\nD'accord ! Je veux bien\nme battre en duel !\n\n")
  LANGUAGE_TEXT(2, "Du willst dich mit mir duel-\nlieren?\n\nNa klar doch!\nDa bin ich dabei!\n\n")
  LANGUAGE_TEXT(3, "Vuoi duellare con me?\n\nMa certo!\nDueller\xf2 con te!\n\n")
  LANGUAGE_TEXT(4, "\xbfQuieres luchar conmigo?\n\n\xa1Claro!\n\xa1Lo har\xe9!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(123)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CBD0, map_06_state_01_08E5CBD0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(6)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "If you're ever in the mood\nfor competition...\n\nYou know where to find me.\n\n")
  LANGUAGE_TEXT(1, "Si tu crois que je suis\nassez bon...\n\nJe t'affronterai\nd\xe8s que tu le veux.\n\n")
  LANGUAGE_TEXT(2, "Wenn du glaubst, dass ich\ngut genug bin...\n\nMit dir duelliere ich mich\ndoch jederzeit.\n\n")
  LANGUAGE_TEXT(3, "Sappi che me la cavo\nabbastanza bene...\n\nDueller\xf2 con te in\nqualsiasi momento.\n\n")
  LANGUAGE_TEXT(4, "Si crees que soy\nlo bastante bueno\n\nMe batir\xe9 contigo\nsiempre que quieras.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CBDC, map_06_state_01_08E5CBDC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hi, {PLAYER}.\n\nTea told me what's up..\nYou'll do awesome.\n\n")
  LANGUAGE_TEXT(1, "Salut, {PLAYER}.\n\nJ'ai eu des nouvelles\nde Tea.\n\nN'abandonne pas.\n\n")
  LANGUAGE_TEXT(2, "Hallo, {PLAYER}.\n\nIch habe von Tea geh\xf6rt.\nGib nicht auf.\n\n")
  LANGUAGE_TEXT(3, "Salve, {PLAYER}.\n\nHo sentito di Tea.\nNon mollare.\n\n")
  LANGUAGE_TEXT(4, "Hola, {PLAYER}.\n\nMe lo dijo Tea.\nNo abandones.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CBE8, map_06_state_01_08E5CBE8, 0x08E5CBF4, 0x08F0404C)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't really consider\nmyself a duelist...\n\nBut I can duel better than\nthat loser Tristan.\n\n")
  LANGUAGE_TEXT(1, "Je ne me consid\xe8re pas\ncomme un vrai duelliste.\n\nMais je serais toujours\nmeilleur que Tristan.\n\n")
  LANGUAGE_TEXT(2, "Ich sehe mich eigentlich\nnicht als Duellant...\n\nAber ich bin noch immer\nbesser als Tristan.\n\n")
  LANGUAGE_TEXT(3, "A dire il vero non mi\nconsidero un duellante...\n\nMa posso battermi\nmeglio di Tristan.\n\n")
  LANGUAGE_TEXT(4, "Realmente no me\nconsidero un duelista...\n\nPero puedo luchar\nmejor de lo que\n\npodr\xeda Tristan en\ntoda su vida.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(124)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CBF4, map_06_state_01_08E5CBF4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(6)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Duel Monsters is a pretty\ndeep game, isn't it?\n\n")
  LANGUAGE_TEXT(1, "Les Duel Monsters, c'est\npas du gateau, pas vrai ?\n\n")
  LANGUAGE_TEXT(2, "Duel Monsters ist ganz\nsch\xf6n komplex, nicht wahr?\n\n")
  LANGUAGE_TEXT(3, "Duel Monsters \xe8 un vero\nmistero, non \xe8 cos\xec?\n\n")
  LANGUAGE_TEXT(4, "Duel Monsters\nes fuerte, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CDD4, map_06_state_01_08E5CDD4, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Arf arf!\n\n")
  LANGUAGE_TEXT(3, "Bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
