#include "event_macros.h"
#include "overworld.h"

/* map_14_state_10: map 14 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08E775C4, map_14_state_10_08E775C4, 0x08E775D0, 0x08E775DC)
  PLAY_MUSIC(230)
  HIDE_PORTRAIT()
  DELAY(64)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Gotta hand it to you, Yugi.\nThat duel lasted barely a\n\nsecond!\n\nOn the other hand...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, you had me\nworried!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(REACTION_SWEATDROP, 1)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I... I couldn't afford to\nwaste any time.\n\nI have to find the spirit\nright away!\n\nBut {PLAYER}'s duel was\npretty impressive.\n\nLet's keep this up, guys!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  CHECK_FLAG(EVENT_FLAG_CHOSE_TO_FIGHT_DOX2)
  FALLTHROUGH()
END_EVENT_SCRIPT()
