#include "event_macros.h"
#include "overworld.h"

/* map_38_state_03: map 38 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08ED16E8, map_38_state_03_08ED16E8, 0x08ED16F4, 0x08F0404C)
  PLAY_MUSIC(33)
  DELAY(16)
  WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 76)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 0)
  LANGUAGE_TEXT(0, "Uki!\n\n")
  LANGUAGE_TEXT(1, "Uki !\n\n")
  LANGUAGE_TEXT(2, "Uki!\n\n")
  LANGUAGE_TEXT(3, "Uki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 0)
  LANGUAGE_TEXT(0, "Uki!\n\n")
  LANGUAGE_TEXT(1, "Uki !\n\n")
  LANGUAGE_TEXT(2, "Uki!\n\n")
  LANGUAGE_TEXT(3, "Uki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 48)
  WALK_OBJECT_X(2, 60)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 0)
  LANGUAGE_TEXT(0, "Ukiki!\n\n")
  LANGUAGE_TEXT(1, "Ukiki !\n\n")
  LANGUAGE_TEXT(2, "Ukiki!\n\n")
  LANGUAGE_TEXT(3, "Ukiki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiki!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(323)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 0, 0)
  LANGUAGE_TEXT(0, "Ukiki!\n\n")
  LANGUAGE_TEXT(1, "Ukiki !\n\n")
  LANGUAGE_TEXT(2, "Ukiki!\n\n")
  LANGUAGE_TEXT(3, "Ukiki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiki!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(3, 36)
  WALK_OBJECT_X(3, 48)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 0)
  LANGUAGE_TEXT(0, "Uki uki ukikki!\n\n")
  LANGUAGE_TEXT(1, "Uki uki ukikki !\n\n")
  LANGUAGE_TEXT(2, "Uki uki ukikki!\n\n")
  LANGUAGE_TEXT(3, "Uki uki ukikki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki uki ukikki!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16, 1)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 0)
  LANGUAGE_TEXT(0, "Ukiiiii!\n\n")
  LANGUAGE_TEXT(1, "Ukiiiii !\n\n")
  LANGUAGE_TEXT(2, "Ukiiiii!\n\n")
  LANGUAGE_TEXT(3, "Ukiiiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukiiiii!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 20)
  WALK_OBJECT_Y(4, 10)
  WALK_OBJECT_X(4, 12)
  SHOW_OBJECT(4, 128, 96, 0, 0, 0)
  WALK_OBJECT_X(0, 96)
  SHOW_OBJECT(13, 128, 46, 0, 0, 0)
  WALK_OBJECT_X(13, 106)
  SHOW_OBJECT(14, 128, 58, 0, 0, 0)
  WALK_OBJECT_X(14, 106)
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Look at all the monkey\nrobots...\n\n")
  LANGUAGE_TEXT(1, "Regarde tous ces\nrobots singes....\n\n")
  LANGUAGE_TEXT(2, "Schau dir nur die ganzen\nAffenroboter an...\n\n")
  LANGUAGE_TEXT(3, "Guarda tutte queste\nscimmie robot...\n\n")
  LANGUAGE_TEXT(4, "Mira todos esos\nrobots mono...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "It's impossible to tell\nwhich one is Tristan!\n\n")
  LANGUAGE_TEXT(1, "Impossible de dire\nlequel est Tristan !\n\n")
  LANGUAGE_TEXT(2, "Wie sollen wir da heraus-\nfinden, wer Tristan ist!\n\n")
  LANGUAGE_TEXT(3, "Come si fa a sapere\nquale \xe8 Tristan?\n\n")
  LANGUAGE_TEXT(4, "\xa1No se puede saber\ncu\xe1l es Tristan!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 1)
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(5, 2)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 0)
  LANGUAGE_TEXT(0, "Uki! Uki! Ukiiii!\n\n")
  LANGUAGE_TEXT(1, "Uki ! Uki !\nUkiiii !\n\n")
  LANGUAGE_TEXT(2, "Uki! Uki!\nUkiiii!\n\n")
  LANGUAGE_TEXT(3, "Uki! Uki!\nUkiiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Uki! \xa1Uki!\n\xa1Ukiiii!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 12)
  DELAY(8)
  WALK_OBJECT_Y(2, 36)
  WALK_OBJECT_X(2, 70)
  MOVE_OBJECT(2, 0, 0, 0)
  WALK_OBJECT_Y(3, 36)
  WALK_OBJECT_X(3, 58)
  MOVE_OBJECT(3, 0, 0, 0)
  WALK_OBJECT_Y(1, 52)
  WALK_OBJECT_X(1, 88)
  MOVE_OBJECT(1, 3, 0, 1)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PLAY_MUSIC(324)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 0)
  LANGUAGE_TEXT(0, "Ukikikki!\n\n")
  LANGUAGE_TEXT(1, "Ukikikki !\n\n")
  LANGUAGE_TEXT(2, "Ukikikki!\n\n")
  LANGUAGE_TEXT(3, "Ukikikki!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukikikki!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(126)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED16F4, map_38_state_03_08ED16F4, 0x08ED1700, 0x08ED170C)
  PLAY_MUSIC(247)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 0)
  LANGUAGE_TEXT(0, "Ukiiiii...\n\n")
  LANGUAGE_TEXT(1, "Ukiiiii...\n\n")
  LANGUAGE_TEXT(2, "Ukiiiii...\n\n")
  LANGUAGE_TEXT(3, "Ukiiiii...\n\n")
  LANGUAGE_TEXT(4, "Ukiiiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "I get it! The monkeys think\nwe're stealing their\n\nbananas.\n\nThat's why they're\nchallenging us to duel.\n\n")
  LANGUAGE_TEXT(1, "J'ai compris !\nLes singes pensent\n\nqu'on vole\nleurs bananes.\n\nC'est pour \xe7a qu'ils\nnous d\xe9fient en duel.\n\n")
  LANGUAGE_TEXT(2, "Jetzt verstehe ich!\n\nDie Affen glauben, wir wol-\nlen ihre Bananen stehlen.\n\nDarum fordern sie uns zum\nDuell heraus.\n\n")
  LANGUAGE_TEXT(3, "Ci sono! Le scimmie pensano\nche stiamo rubando banane.\n\nPer questo ci sfidano\nai duelli.\n\n")
  LANGUAGE_TEXT(4, "\xa1Ya lo tengo! Los monos\ncreen que estamos\n\nrobando pl\xe1tanos.\n\nPor eso nos retan\na un duelo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "These monkey robots can\nduel?\n\n")
  LANGUAGE_TEXT(1, "Ces singes robots savent\nse battre en duel ?\n\n")
  LANGUAGE_TEXT(2, "Diese Affenroboter k\xf6nnen\nsich duellieren?\n\n")
  LANGUAGE_TEXT(3, "Queste scimmie robot\nsanno duellare?\n\n")
  LANGUAGE_TEXT(4, "\xbfEstos robots mono\npueden hacer duelos?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 16384)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "I've got it, {PLAYER}!\n\nI know how we can find out\nwhich one is Tristan!\n\n")
  LANGUAGE_TEXT(1, "J'ai compris, {PLAYER} !\n\nJe sais comment\ntrouver Tristan !\n\n")
  LANGUAGE_TEXT(2, "Jetzt hab ich's, {PLAYER}!\n\nIch wei\xdf jetzt, wie wir\nTristan erkennen k\xf6nnen!\n\n")
  LANGUAGE_TEXT(3, "Ci sono, {PLAYER}!\n\nSo come fare per\ndistinguere Tristan!\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo tengo, {PLAYER}!\n\n\xa1S\xe9 c\xf3mo descubrir\na Tristan!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Tristan is a total amateur\nwhen it comes to dueling.\n\nSo all we need to do is duel\nthese monkey robots.\n\nThe weakest one is Tristan!\n\n")
  LANGUAGE_TEXT(1, "Tristan est class\xe9\nduelliste amateur.\n\nDonc, tout ce qu'il\nnous reste \xe0 faire,\n\nc'est d'affronter en duel\ntous ces singes robots.\n\nLe moins fort,\n\xe7a sera Tristan !\n\n")
  LANGUAGE_TEXT(2, "Tristan ist ein v\xf6lliger\nAnf\xe4nger im Duellieren.\n\nWir m\xfcssen also nur gegen\nall diese Roboter spielen.\n\nDer schw\xe4chste ist Tristan!\n\n")
  LANGUAGE_TEXT(3, "Come duellante, Tristan\n\xe8 un vero pivello.\n\nQuindi non dobbiamo fare\naltro che duellare con\n\nqueste scimmie robot. La\npi\xf9 scarsa sar\xe0 Tristan!\n\n")
  LANGUAGE_TEXT(4, "Tristan tiene rango\namateur como duelista.\n\nLo \xfanico que hay que\nhacer es batirse en\n\nduelo con estos\nrobots mono.\n\n\xa1El m\xe1s d\xe9bil\nser\xe1 Tristan!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Exactly!\nThat won't work...{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}C'est \xe7a !\nCe n'est pas croyable.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Genau!\nUnm\xf6glich!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}D'accordo!\nNon pu\xf2 essere vero.{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1Eso es!\nNo puede ser cierto.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1700, map_38_state_03_08ED1700, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah, I'm usin' my noodle!\n\n")
  LANGUAGE_TEXT(1, "Je suis trop bon !\n\n")
  LANGUAGE_TEXT(2, "Ich bin ja so clever!\n\n")
  LANGUAGE_TEXT(3, "Sono un genio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Soy tan listo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "Let's try dueling them,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Essayons de les affronter\nen duel, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Versuchen wir, uns mit\nihnen zu duellieren,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Proviamo a duellare con\nloro, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Intentemos luchar con\nellos, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(146)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED170C, map_38_state_03_08ED170C, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't think there's any\nother way to tell them\n\napart.\n\nLet's try dueling them,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je ne crois pas qu'il\ny ait un autre chemin.\n\nEssayons de les affronter\nen duel, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich glaube nicht, dass eine\nandere M\xf6glichkeit besteht.\n\nVersuchen wir, uns mit\nihnen zu duellieren,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Non credo ci sia\nun altro modo.\n\nProviamo a duellare con\nloro, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "No creo que haya\notro modo.\n\nIntentemos luchar con\nellos, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(146)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1718, map_38_state_03_08ED1718, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "Ukiii...\n\n")
  LANGUAGE_TEXT(1, "Ukiii...\n\n")
  LANGUAGE_TEXT(2, "Ukiii...\n\n")
  LANGUAGE_TEXT(3, "Ukiii...\n\n")
  LANGUAGE_TEXT(4, "Ukiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This one's too strong to be\nTristan. It's not him.\n\n")
  LANGUAGE_TEXT(1, "Celui-ci est trop fort.\nCe n'est pas Tristan.\n\n")
  LANGUAGE_TEXT(2, "Dieser hier ist zu stark. Er\nkann nicht Tristan sein.\n\n")
  LANGUAGE_TEXT(3, "Questa \xe8 troppo forte per\nessere Tristan. Non \xe8 lui.\n\n")
  LANGUAGE_TEXT(4, "Este es demasiado\nfuerte para ser Tristan.\n\nNo es \xe9l.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1724, map_38_state_03_08ED1724, 0x08ED1730, 0x08ED1718)
  CHECK_FLAG(147)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1730, map_38_state_03_08ED1730, 0x08ED173C, 0x08F0404C)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 8)
  LANGUAGE_TEXT(0, "Ukki! Ukki! Ukiii!\n\n")
  LANGUAGE_TEXT(1, "Ukki ! Ukki !\nUkiii !\n\n")
  LANGUAGE_TEXT(2, "Ukki! Ukki!\nUkiii!\n\n")
  LANGUAGE_TEXT(3, "Ukki! Ukki! Ukiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukki! \xa1Ukki!\n\xa1Ukiii!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(127)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED173C, map_38_state_03_08ED173C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "Ukiii...\n\n")
  LANGUAGE_TEXT(1, "Ukiii...\n\n")
  LANGUAGE_TEXT(2, "Ukiii...\n\n")
  LANGUAGE_TEXT(3, "Ukiii...\n\n")
  LANGUAGE_TEXT(4, "Ukiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This one's way tougher than\nTristan.\n\nLet's challenge another one.\n\n")
  LANGUAGE_TEXT(1, "Celui-ci est bien trop\nfort pour \xeatre Tristan.\n\nAllons d\xe9fier un\nautre singe robot.\n\n")
  LANGUAGE_TEXT(2, "Dieser hier ist viel st\xe4rker\nals Tristan.\n\nFordern wir einen anderen\nzum Duell heraus.\n\n")
  LANGUAGE_TEXT(3, "Questa \xe8 molto pi\xf9 forte\ndi Tristan.\n\nSfidiamone un'altra.\n\n")
  LANGUAGE_TEXT(4, "Este es mucho m\xe1s\nfuerte que Tristan.\n\nRetemos a otro.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(147)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1748, map_38_state_03_08ED1748, 0x08ED1754, 0x08ED1718)
  CHECK_FLAG(148)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1754, map_38_state_03_08ED1754, 0x08ED1760, 0x08F0404C)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PLAY_MUSIC(327)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 2, 8)
  LANGUAGE_TEXT(0, "Ukki! Ukki!\nUkiii!\n\n")
  LANGUAGE_TEXT(1, "Ukki ! Ukki !\nUkiii !\n\n")
  LANGUAGE_TEXT(2, "Ukki! Ukki!\nUkiii!\n\n")
  LANGUAGE_TEXT(3, "Ukki! Ukki!\nUkiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ukki! \xa1Ukki!\n\xa1Ukiii!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(128)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1760, map_38_state_03_08ED1760, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(247)
  PLAY_MUSIC(325)
  PORTRAIT(PORTRAIT_ROBOT_MOkNEY, 5, 8)
  LANGUAGE_TEXT(0, "Ukiii...\n\n")
  LANGUAGE_TEXT(1, "Ukiii...\n\n")
  LANGUAGE_TEXT(2, "Ukiii...\n\n")
  LANGUAGE_TEXT(3, "Ukiii...\n\n")
  LANGUAGE_TEXT(4, "Ukiii...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This one's still too strong\nto be Tristan.\n\nTry challenging another one.\n\n")
  LANGUAGE_TEXT(1, "Celui-ci est toujours trop\nfort pour \xeatre Tristan.\n\nEssayons de d\xe9fier\nun autre singe robot.\n\n")
  LANGUAGE_TEXT(2, "Dieser ist auch noch zu\nclever f\xfcr Tristan.\n\nDuellier dich mit einem\nanderen.\n\n")
  LANGUAGE_TEXT(3, "Pure questa \xe8 troppo\nforte per essere Tristan.\n\nProva a sfidarne un'altra.\n\n")
  LANGUAGE_TEXT(4, "Este es a\xfan muy\nfuerte para ser Tristan.\n\nIntenta retar a otro.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(148)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1784, map_38_state_03_08ED1784, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "This is a banana!\n\n")
  LANGUAGE_TEXT(1, "C'est une banane !\n\n")
  LANGUAGE_TEXT(2, "Eine Banane!\n\n")
  LANGUAGE_TEXT(3, "\xc8 una banana!\n\n")
  LANGUAGE_TEXT(4, "\xa1Es un pl\xe1tano!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED1790, map_38_state_03_08ED1790, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Sorry, you can't duel a\nbanana!\n\n")
  LANGUAGE_TEXT(1, "Dommage, mais\ntu ne peux pas\n\nte battre en duel\ncontre une banane !\n\n")
  LANGUAGE_TEXT(2, "Tut mir Leid, aber mit einer\nBanane kannst du dich\n\nnicht duellieren!\n\n")
  LANGUAGE_TEXT(3, "Mi dispiace, ma non puoi\nduellare con una banana!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vamos, no puedes\nbatirte con un pl\xe1tano!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
