#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_17_state_01: map 17 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E7F10C, map_17_state_01_08E7F10C, 0x08E7F118, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_PANIK)
  WALK_OBJECT_X(0, 92)
  WALK_OBJECT_X(13, 102)
  WALK_OBJECT_Y(13, 46)
  MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_X(14, 102)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7F118, map_17_state_01_08E7F118, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_414)
  TALK(PORTRAIT_PANICK, "Ha ha ha... You'll go no further.")
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_2 | OBJECT_3)
  WALK_OBJECT_X(1, 48)
  TALK(PORTRAIT_PANICK,
      "Ha ha ha... My name is PaniK.",
      "The Millennium Items will never be yours!"
  )
  SET_FLAG(EVENT_FLAG_DARKEN_SCREEN)
  FADE_SCREEN(2)
  WARP(LOCATION_DUEL_EXPRESS_CARRIAGE_MIDDLE, 7, 2, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
