#include "event_macros.h"
#include "overworld.h"

/* map_25_state_02: map 25 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E995B8, map_25_state_02_08E995B8, 0x08E995C4, 0x08E995D0)
  CHECK_FLAG(119)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E995C4, map_25_state_02_08E995C4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, no, please! I am not a\nduelist!\n\nThere are duelists on the\nnext floor!\n\n...Oh? You're not the Neo\nGhouls?\n\n")
  LANGUAGE_TEXT(1, "Non, non ! Je ne\nsuis pas un duelliste !\n\nIl y en a \xe0 l'\xe9tage\nsuivant !\n\n... Oh ? Vous n'\xeates\npas des Neo Ghouls ?\n\n")
  LANGUAGE_TEXT(2, "Oh nein, bitte!\nIch bin kein Duellant!\n\nDuellanten findet ihr in\nder n\xe4chsten Etage!\n\n... Ach? Ihr seid keine\nNeo Ghouls?\n\n")
  LANGUAGE_TEXT(3, "No, no, ti prego!\nNon sono un duellante!\n\nI duellanti li trovi\nal piano successivo.\n\n... Oh? Non siete\ndei Neo Ghouls?\n\n")
  LANGUAGE_TEXT(4, "\xa1No, no, por favor!\n\xa1No soy un duelista!\n\n\xa1Hay duelistas en el\npiso siguiente!\n\n... \xbfEh?\n\xbfNo sois los Neo Ghouls?\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(119)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E995D0, map_25_state_02_08E995D0, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "If only I were a duelist...\n\nThose Neo Ghouls wouldn't\nstand a chance!\n\n")
  LANGUAGE_TEXT(1, "Si j'\xe9tais un duelliste...\nCes Neo Ghouls ne\n\nperdraient rien\npour attendre !\n\n")
  LANGUAGE_TEXT(2, "Wenn ich doch nur ein\nDuellant w\xe4re...\n\nDiese Neo Ghouls h\xe4tten\nkeine Chance!\n\n")
  LANGUAGE_TEXT(3, "Se solo fossi un\nduellante...\n\nQuei Neo Ghouls non\navrebbero avuto scampo.\n\n")
  LANGUAGE_TEXT(4, "Si siquiera fuese\nun duelista...\n\n\xa1Esos Neo Ghouls no\ntendr\xedan una oportunidad!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E995DC, map_25_state_02_08E995DC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Hahaha, sorry, but I am not\na duelist.\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha, d\xe9sol\xe9, mais\nje ne suis pas un duelliste.\n\n")
  LANGUAGE_TEXT(2, "Hahaha, Pech, aber ich bin\nkein Duellant.\n\n")
  LANGUAGE_TEXT(3, "Hahaha, purtroppo non\nsono un duellante.\n\n")
  LANGUAGE_TEXT(4, "\xa1Ah!, \xa1ah!, es una\nverg\xfcenza, pero\n\nno soy duelista.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E995E8, map_25_state_02_08E995E8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "That dealer over there...\n\nAll he did was hide from the\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "Ce vendeur, l\xe0-bas...\n\nIl se cache toujours\ndes Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Der Geber da vorne...\n\nEr hat sich die ganze Zeit\nnur vor den\n\nNeo Ghouls versteckt.\n\n")
  LANGUAGE_TEXT(3, "Quel mazziere laggi\xf9...\nNon ha fatto altro che\n\nnascondersi dai\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "Ese comerciante...\nTodo lo que hizo\n\nfue esconderse\nde los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E995F4, map_25_state_02_08E995F4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, I'll pass.\n\n")
  LANGUAGE_TEXT(1, "Non, je passe.\n\n")
  LANGUAGE_TEXT(2, "Nein, lieber nicht.\n\n")
  LANGUAGE_TEXT(3, "No, io passo.\n\n")
  LANGUAGE_TEXT(4, "No, yo pasar\xe9.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
