#include "event_macros.h"
#include "overworld.h"

/* map_11_state_01: map 11 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E642EC, map_11_state_01_08E642EC, 0x08E64304, 0x08E6431C)
  CHECK_FLAG(38)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64304, map_11_state_01_08E64304, 0x08E64310, 0x08F0404C)
  LANGUAGE_TEXT(0, "You step into my territory\nand have the gall to\n\nchallenge me?\n\nWe'll duel for a rare card!\n\n")
  LANGUAGE_TEXT(1, "Tu es venu sur mon\nterritoire pour moi ?\n\nBattons-nous en duel\npour une carte rare !\n\n")
  LANGUAGE_TEXT(2, "Wegen mir hast du dein\nGebiet verlassen?\n\nDuellieren wir uns um\neine seltene Karte!\n\n")
  LANGUAGE_TEXT(3, "Sei venuto nel mio\nterritorio a cercarmi?\n\nDuelleremo per una\ncarta rara!\n\n")
  LANGUAGE_TEXT(4, "\xbfViniste a mi\nterritorio por m\xed?\n\n\xa1Lucharemos por\nuna carta rara!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64310, map_11_state_01_08E64310, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(7)
  LANGUAGE_TEXT(0, "Dagnabbit! You tricked me!\n\nI'm only here because I\nheard that all the tough\n\nduelists were somewhere\nelse.\n\nYou're supposed to be on the\nDuel Express, not dueling\n\nme!\n\n")
  LANGUAGE_TEXT(1, "Punaise !\nOn m'a jou\xe9 un tour !\n\nIl para\xeet que les duellistes\nles plus forts n'\xe9taient\n\npas l\xe0. Tu es cens\xe9 \xeatre\ndans le Duel Express !\n\n")
  LANGUAGE_TEXT(2, "Verdammt!\nDas war gelinkt!\n\nIch h\xf6rte, dass keiner der\nstarken Duellanten\n\nhier sein w\xfcrde.\n\nWarum bist du nicht im\nDuel Express!\n\n")
  LANGUAGE_TEXT(3, "Dannazione!\nMi hai fregato!\n\nAvevo sentito dire che\ntutti i duellanti forti\n\nnon erano qui. E tu\nperch\xe9 non sei sul\n\nDuel Express?\n\n")
  LANGUAGE_TEXT(4, "\xa1Maldita sea!\n\xa1Me han dado!\n\nHe o\xeddo que no\nestaban aqu\xed todos\n\nlos duelistas fuertes.\n\n\xa1Se supone que t\xfa\nhas de estar en el\n\nDuel Express!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(38)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6431C, map_11_state_01_08E6431C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Where's a wimpy duelist when\nyou need one...\n\n")
  LANGUAGE_TEXT(1, "Si seulement\nil pouvait y avoir\n\nun duelliste\nassez faible...\n\n")
  LANGUAGE_TEXT(2, "Ist hier denn kein schwacher\nDuellant...\n\n")
  LANGUAGE_TEXT(3, "Non si presenter\xe0 un\nduellante inetto...\n\n")
  LANGUAGE_TEXT(4, "\xbfNo vendr\xe1 un d\xe9bil\nduelista...?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E642F8, map_11_state_01_08E642F8, 0x08E64304, 0x08E64328)
  CHECK_FLAG(38)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E64328, map_11_state_01_08E64328, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Go away already!\n\nYou're scaring all the weak\nduelists away!\n\n")
  LANGUAGE_TEXT(1, "Allez, va-t-en !\nTu vas faire peur\n\n\xe0 tous les duellistes\nles plus faibles.\n\n")
  LANGUAGE_TEXT(2, "Hau endlich ab.\n\nDu vertreibst ja all die\nsch\xfcchternen Duellanten.\n\n")
  LANGUAGE_TEXT(3, "Te ne vuoi andare?\n\nSpaventerai tutti i\nduellanti inetti.\n\n")
  LANGUAGE_TEXT(4, "Vete ya.\n\nAsustar\xe1s a todos los\nduelistas debiluchos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
