#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_04: map 51 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EE3DB8, map_51_state_04_08EE3DB8, 0x08EE3DDC, 0x08EE3E30)
  LOAD_SPRITE(1, SPRITE_WEEVIL)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DDC, map_51_state_04_08EE3DDC, 0x08EE3DE8, 0x08EE3E18)
  PLAY_MUSIC(MUSIC_280)
  SHOW_OBJECT(1, 60, 48, 0, 1, 0)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_WEEVIL3)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DE8, map_51_state_04_08EE3DE8, 0x08EE3DF4, 0x08EE3E00)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DF4, map_51_state_04_08EE3DF4, 0x08EE3E0C, 0x08EE401C)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hyohyohyohyo!",
      "My anger still burns!"
  )
  DUEL(DUELIST_WEEVIL_115)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E0C, map_51_state_04_08EE3E0C, 0x08EE3FE0, EVENT_NOP)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Kiiiiiih!",
      "You're the last person I'll let pass!"
  )
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITHOUT_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E00, map_51_state_04_08EE3E00, 0x08EE3E0C, 0x08EE401C)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You're wasting your time!")
  DUEL(DUELIST_WEEVIL_115)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E18, map_51_state_04_08EE3E18, 0x08EE3E24, 0x08EE401C)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "It doesn't matter what you bring.",
      "When I win, it's all over for you."
  )
  DUEL(DUELIST_WEEVIL_115)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E24, map_51_state_04_08EE3E24, 0x08EE3E30, EVENT_NOP)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Qu-queen!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_393)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  DELAY(8)
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(SPRITE_CHEVALIER, OBJECT_EFFECT_TELEPORT)
  SET_FLAG(EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITH_SPIRIT_CARD)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3E30, map_51_state_04_08EE3E30, EVENT_NOP, EVENT_NOP)
  SET_FLAG(EVENT_FLAG_GOT_PAST_DARK_WEEVIL_ROOM)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DC4, map_51_state_04_08EE3DC4, 0x08EE3DB8, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3DD0, map_51_state_04_08EE3DD0, 0x08EE3DB8, EVENT_NOP)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EE3FEC, map_51_state_04_08EE3FEC, EVENT_NOP, EVENT_NOP)
  CLEAR_FLAG(231)
  WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
