#include "event_macros.h"
#include "overworld.h"

/* map_06_state_13: map 6 state 13 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CD08, map_06_state_13_08E5CD08, 0x08F04040, 0x08F04040)
  LOAD_SPRITE(1, SPRITE_TRISTAN)
  LOAD_SPRITE(2, SPRITE_DUKE)
  LOAD_SPRITE(3, SPRITE_SERENITY)
  LOAD_SPRITE(4, SPRITE_LUCKY)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("You did it, {PLAYER}.\n\nYou got rid of the Neo\nGhouls... Awesome!\n\nBut... Your battle isn't\nover yet, is it?\n\n{PLAYER}, I know you can\nwin!\n\nDon't worry about the Town\nof Domino. We'll take care\n\nof it.\n\nGo on ahead and duel like a\nchampion!\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD14, map_06_state_13_08E5CD14, 0x08E5CD20, 0x08F0404C)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Sure! If you think you can\nlearn something from me,\n\nI'll duel you!\n\n")
  DUEL(92)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD20, map_06_state_13_08E5CD20, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I hope that was good\npractice.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD2C, map_06_state_13_08E5CD2C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("We'll look after things\nwhile you're gone,\n\n{PLAYER}.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD38, map_06_state_13_08E5CD38, 0x08E5CD44, 0x08F0404C)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("No problem! I'll duel if you\nwant me to.\n\n")
  DUEL(93)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD44, map_06_state_13_08E5CD44, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_GAME_SHOP)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I guess I'm too weak to duel\nyou, {PLAYER}.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD50, map_06_state_13_08E5CD50, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("{PLAYER}, good luck.\n\nI hope Joey doesn't get in\nthe way...\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CD5C, map_06_state_13_08E5CD5C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("I wouldn't be much of a\nchallenge, {PLAYER}.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
