#include "event_macros.h"
#include "overworld.h"

/* map_29_state_04: map 29 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC984, map_29_state_04_08EAC984, 0x08EAC9A8, 0x08EAC990)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Do you want your fortune\ntold?\n\n")
  LANGUAGE_TEXT(1, "Est-ce que tu veux que je te\ndise la bonne aventure ?\n\n")
  LANGUAGE_TEXT(2, "Soll ich dir dein Schicksal\nvoraussagen?\n\n")
  LANGUAGE_TEXT(3, "Vuoi che ti predica\nil futuro?\n\n")
  LANGUAGE_TEXT(4, "\xbfQuieres que te diga\ntu suerte?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9A8, map_29_state_04_08EAC9A8, 0x08EAC9C0, 0x08EAC9B4)
  CHECK_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_PAST_LIFE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9C0, map_29_state_04_08EAC9C0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I may not look it, but I'm\nan expert fortuneteller.\n\nI'll peer into your previous\nlife, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je sais bien lire\nla bonne aventure.\n\nLaisse-moi lire ta\nvie pr\xe9c\xe9dente, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich kann die Zukunft gut\nvorhersagen.\n\nIch werde dein Vorleben\nunter die Lupe nehmen,\n\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Sono bravo nel predire\nil futuro. Dar\xf2 un'occhiata\n\nalla tua vita precedente,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Soy bueno adivinando.\n\nMirar\xe9 en tu vida\nanterior {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(368)
  LANGUAGE_TEXT(0, "Hmm... Yes, I can see it!\nI can feeeeeeeeeeeel it!\n\n")
  LANGUAGE_TEXT(1, "Voyons-voir... Je la vois !\nJe la vois parfaitement !\n\n")
  LANGUAGE_TEXT(2, "Schauen wir mal...\nIch sp\xfcre es!\n\nIch kann es sp\xfc\xfc\xfc\xfcren!\n\n")
  LANGUAGE_TEXT(3, "Vediamo... Lo sento!\nRiesco a sentiiiiiiirlo!\n\n")
  LANGUAGE_TEXT(4, "D\xe9jame ver... \xa1lo\nsiento! \xa1Lo sieeento!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I can see your past very\nclearly!\n\n^5{BYTE_02}!\n\nThat's what you were in your\nprevious life.\n\n")
  LANGUAGE_TEXT(1, "J'ai compris, maintenant !\n\n^5{BYTE_02} !\n\nVoil\xe0 ce que tu \xe9tais\ndans ta vie pr\xe9c\xe9dente.\n\n")
  LANGUAGE_TEXT(2, "Jetzt verstehe ich,\n\n^5{BYTE_02}!\n\nDas warst du doch in\ndeinem fr\xfcheren Leben.\n\n")
  LANGUAGE_TEXT(3, "Ora capisco!\n\n^5{BYTE_02}!\n\nEcco cosa eri prima\ndi questa vita.\n\n")
  LANGUAGE_TEXT(4, "\xa1Ya lo tengo!\n\n\xa1^5{BYTE_02}!\n\nEso es lo que eras\nantes de esta vida.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hahahaha!\n\n^5{BYTE_02}?\n\nThat's what {PLAYER} was\nin a past life?\n\nHahahaha, I can see the\nsimilarities!\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha ha !\n\n^5{BYTE_02} ?\n\nC'est ce que {PLAYER} \xe9tait\ndans une vie pr\xe9c\xe9dente ?\n\nHa ha ha, en fait, \xe7a lui\nva bien !\n\n")
  LANGUAGE_TEXT(2, "Hahahaha!\n\n^5{BYTE_02}?\n\nDas war {PLAYER} also\nin seinem fr\xfcheren Leben?\n\nHahahaha, der Name passt\n\xfcbrigens.\n\n")
  LANGUAGE_TEXT(3, "Hahahaha!\n\n^5{BYTE_02}?\n\nEra questo {PLAYER}\nin una vita precedente?\n\nHahahaha, sembra\nappropriato, davvero.\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajajaja!\n\n\xbf^5{BYTE_02}?\n\n\xbfEso era {PLAYER}\nen otra vida?\n\nJajajaja, en verdad\nle pega.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "In the past, you played\n^5{BYTE_05}...\n\nWith the past incarnation of\n^5{BYTE_04}.\n\nThis was\n^5{BYTE_03}.\n\nMy fortunes are never wrong.\n\n")
  LANGUAGE_TEXT(1, "Par le pass\xe9, il a jou\xe9\n^5{BYTE_05}...\n\nEn incarnant autrefois\n^5{BYTE_04}.\n\nC'\xe9tait\n^5{BYTE_03}\n\nJe ne plaisante pas.\n\n")
  LANGUAGE_TEXT(2, "Fr\xfcher spielte er\n^5{BYTE_05}...\n\nEr verk\xf6rperte\n^5{BYTE_04}.\n\nDas hier ist\n\n^5{BYTE_03}...\n\nDas ist kein Witz.\n\n")
  LANGUAGE_TEXT(3, "In passato, giocava a\n^5{BYTE_05}...\n\nCon la passata incarnazione\ndi ^5{BYTE_04}.\n\nIl luogo sar\xe0\n^5{BYTE_03}\n\nNon sto scherzando.\n\n")
  LANGUAGE_TEXT(4, "En el pasado, jug\xf3 a\n^5{BYTE_05}...\n\nCon la pasada\nencarnaci\xf3n de\n\n^5{BYTE_04}.\n\nEso fue\n^5{BYTE_03}\n\nNo bromeo.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_PAST_LIFE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9B4, map_29_state_04_08EAC9B4, 0x08EAC9CC, 0x08EAC9D8)
  CHECK_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_ROMANTIC_MATCH)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9CC, map_29_state_04_08EAC9CC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Fortunetelling is my\nspecialty.\n\nI'll predict your perfect\nromantic match, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je sais bien lire\nla bonne aventure.\n\nTu veux conna\xeetre tes\nfuturs amours, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich kann die Zukunft gut\nvorhersagen.\n\nIch schau mir deine roman-\ntischen Partneroptionen\n\nan, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Sono bravo nel predire\nil futuro. Dar\xf2 un'occhiata\n\nalle tue combinazioni\nromantiche, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Soy bueno adivinando.\n\nMirar\xe9 en tus parejas\nrom\xe1nticas, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(368)
  LANGUAGE_TEXT(0, "Hmm... I can see it!\nI can feeeeeeeeeeeel it!\n\n")
  LANGUAGE_TEXT(1, "Voyons voir...\n\nJ'ai une vision !\nC'est parfaitement clair !\n\n")
  LANGUAGE_TEXT(2, "Mal sehen...\n\nIch sp\xfcre es!\nIch kann es f\xfc\xfc\xfc\xfchlen!\n\n")
  LANGUAGE_TEXT(3, "Vediamo... Lo sento!\nRiesco a sentiiiiiiirlo!\n\n")
  LANGUAGE_TEXT(4, "D\xe9jame ver... \xa1lo\nsiento! \xa1Lo sieeento!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ah, I can see this person!\n\nYour partner's initials are\n{BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.\n\nIf you want to get closer to\nthat person...\n\nPlay ^5{BYTE_0B}\n^5{BYTE_0A}.\n\n")
  LANGUAGE_TEXT(1, "J'ai trouv\xe9 !\nL'initiale, c'est un {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.\n\nPour te rapprocher\nde cette personne...\n\nJoue\n^5{BYTE_0B}\n\n^5{BYTE_0A}\n\n")
  LANGUAGE_TEXT(2, "Ich hab's!\nDie Initialen sind {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.\n\nUm dieser Person n\xe4her\nzu kommen...\n\nSpiel ^5{BYTE_0B}\n^5{BYTE_0A}.\n\n")
  LANGUAGE_TEXT(3, "Ho capito!\nL'iniziale \xe8 {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.\n\nPer avvicinarti a quella\npersona...\n\nGioca a\n^5{BYTE_0B}\n\n^5{BYTE_0A}\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo tengo!\nLa inicial es {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.\n\nPara intimar con\nesa persona...\n\nJuega a\n^5{BYTE_0B}\n\n^5{BYTE_0A}\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 1)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Whoa, whoa, whoa!\nWho's {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}?\n\nWait a sec,\n\nyou can't be talking about\nTHAT person?!?\n\n")
  LANGUAGE_TEXT(1, "Wouah !\nC'est qui {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168} ?\n\nTu ne veux pas\ndire que c'est...\n\n")
  LANGUAGE_TEXT(2, "Woaw, woaw, woaw!\nWer ist {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}?\n\nDu meinst doch\nwohl nicht...\n\n")
  LANGUAGE_TEXT(3, "Uau, uau, uau!\nChi \xe8 {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}?\n\nNon sar\xe0 mica...\n\n")
  LANGUAGE_TEXT(4, "\xa1Ey, ey,ey!\n\xbfQui\xe9n es {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}?\n\nNo quieres decir que es...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 8192)
  SET_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_ROMANTIC_MATCH)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9D8, map_29_state_04_08EAC9D8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I've been fortunetelling all\nmy life.\n\nI even perfected my spooky\nvoice!\n\nI'll look into your future,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je sais bien lire\nla bonne aventure.\n\nTu veux conna\xeetre tes\nfuturs amours, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Ich kann die Zukunft gut\nvorhersagen.\n\nIch werde deine Zukunft\nunter die Lupe nehmen.\n\n")
  LANGUAGE_TEXT(3, "Sono bravo nel predire\nil futuro. Dar\xf2\n\nun'occhiata al tuo futuro,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Soy bueno adivinando.\n\nMirar\xe9 en tu futuro,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(368)
  LANGUAGE_TEXT(0, "Hmm... I can see it!\nI can feeeeeeeeeeeel it!\n\n")
  LANGUAGE_TEXT(1, "Voyons voir...\n\nJ'ai une vision !\nC'est parfaitement clair !\n\n")
  LANGUAGE_TEXT(2, "Schauen wir mal...\nIch sp\xfcre sie!\n\nIch kann sie f\xfc\xfc\xfc\xfc\xfchlen!\n\n")
  LANGUAGE_TEXT(3, "Vediamo... Lo sento!\nRiesco a sentiiiiiirlo!\n\n")
  LANGUAGE_TEXT(4, "D\xe9jame ver... \xa1lo\nsiento! \xa1Lo sieeento!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(2, 1)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Your future is clear!\n\n^5{BYTE_08},\n\n{PLAYER} will duel\nagainst...\n\n^5{BYTE_09}\nfor\n\n^5{BYTE_0C}.\n\nTo win, {PLAYER} must train\nwith ^5{BYTE_0E}...\n\nThe training will take place\n^5{BYTE_0D}.\n\n")
  LANGUAGE_TEXT(1, "Maintenant, j'ai compris !\n\nA ^5{BYTE_08},\n{PLAYER} va\n\naffronter\n^5{BYTE_09}\n\npour\n\n^5{BYTE_0C}.\n\nPour gagner, {PLAYER}\ndoit s'entra\xeener avec\n\n^5{BYTE_0E}...\n\nEt l'entra\xeenement doit se\nfaire\n\n^5{BYTE_0D}\n\n")
  LANGUAGE_TEXT(2, "Jetzt verstehe ich!\n\n^5{BYTE_08},\n{PLAYER} duelliert sich\n\nmit...\n\n^5{BYTE_09}\ngegen\n\n^5{BYTE_0C}.\n\nUm zu gewinnen, muss\n{PLAYER} mit\n\n^5{BYTE_0E}\ntrainieren...\n\nUnd das Training muss\n^5{BYTE_0D}\n\nstattfinden.\n\n")
  LANGUAGE_TEXT(3, "Ora ci sono!\n\n^5{BYTE_08},\n{PLAYER} dueller\xe0 con...\n\n^5{BYTE_09}\nper\n\n^5{BYTE_0C}.\n\nPer vincere, {PLAYER} deve\nallenarsi con\n\n^5{BYTE_0E}... E\nl'allenamento dovr\xe0\n\nsvolgersi\n^5{BYTE_0D}\n\n")
  LANGUAGE_TEXT(4, "\xa1Lo tengo!\n\n^5{BYTE_08},\n{PLAYER} luchar\xe1 con\n\n^5{BYTE_09}\npor la\n\n^5{BYTE_0C}.\n\nPara ganar, {PLAYER}\ndebe entrenar con\n\n^5{BYTE_0E}...\n\nY el entrenamiento ha de ser\n^5{BYTE_0D}\n\n")
  END_LANGUAGE_TEXT()
  CLEAR_FLAG(235)
  CLEAR_FLAG(236)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC990, map_29_state_04_08EAC990, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh... That's disappointing.\n\n")
  LANGUAGE_TEXT(1, "Oh...\nDommage.\n\n")
  LANGUAGE_TEXT(2, "Oh...\nWie entt\xe4uschend.\n\n")
  LANGUAGE_TEXT(3, "Oh... Peccato.\n\n")
  LANGUAGE_TEXT(4, "Oh...\nEs decepcionante.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC99C, map_29_state_04_08EAC99C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "My fortunetelling tells me\nthat I can't win.\n\nSo I won't duel right now..\n\n")
  LANGUAGE_TEXT(1, "Mon avenir me dit que\nje ne vais pas gagner.\n\nJe ne vais donc pas\nme battre en duel...\n\n")
  LANGUAGE_TEXT(2, "Mein Blick in die Zukunft\nsagt mir, dass ich\n\nnicht gewinnen kann.\n\nDarum duelliere ich mich\nmomentan nicht..\n\n")
  LANGUAGE_TEXT(3, "Io predico che non\nposso vincere.\n\nQuindi per ora non\ndueller\xf2...\n\n")
  LANGUAGE_TEXT(4, "Mi adivinaci\xf3n me dice\nque no puedo ganar.\n\nPor ello, no luchar\xe9 ahora.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
