#include "event_macros.h"
#include "overworld.h"

/* map_01_state_08: map 1 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E428B0, map_01_state_08_08E428B0, 0x08E428BC, 0x08F04040)
  WALK_OBJECT_X(0, 26)
  WALK_OBJECT_Y(0, 48)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  WALK_OBJECT_X(13, 16)
  WALK_OBJECT_Y(13, 54)
  MOVE_OBJECT(13, 3, 0, 0)
  WALK_OBJECT_X(14, 16)
  WALK_OBJECT_Y(14, 42)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SAD, 1)
  LANGUAGE_TEXT(0, "Sigh...\n\n")
  LANGUAGE_TEXT(1, "Soupir...\n\n")
  LANGUAGE_TEXT(2, "Seufz...\n\n")
  LANGUAGE_TEXT(3, "Sigh...\n\n")
  LANGUAGE_TEXT(4, "Suspiro...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "What's wrong, Tea? Why the\nbig sigh?\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce qui\nne va pas, Tea ?\n\nPourquoi est-ce que\ntu soupires comme \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Was ist los, Tea?\nWarum seufzt du so?\n\n")
  LANGUAGE_TEXT(3, "Cosa c'\xe8 che non va, Tea?\nCome mai quel sospiro?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 ocurre, Tea?\n\xbfPor qu\xe9 ese suspiro?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SAD, 8)
  LANGUAGE_TEXT(0, "Well...\n\nI had a famous fortuneteller\ndo my reading.\n\n")
  LANGUAGE_TEXT(1, "Eh bien...\n\nQuelqu'un vient\nde lire mon avenir.\n\n")
  LANGUAGE_TEXT(2, "Nun...\n\nEin ber\xfchmter Wahrsager hat\nmir die Zukunft weisgesagt.\n\n")
  LANGUAGE_TEXT(3, "Be'...\n\nMi sono fatta predire il\nfuturo da un famoso\n\nindovino.\n\n")
  LANGUAGE_TEXT(4, "Bien...\n\nUn famoso adivino\nme ley\xf3 la suerte.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "You had your fortune told?\n\n")
  LANGUAGE_TEXT(1, "On t'a lu ton avenir ?\n\n")
  LANGUAGE_TEXT(2, "Du warst bei einem\nWahrsager?\n\n")
  LANGUAGE_TEXT(3, "Ti sei fatta predire\nil futuro?\n\n")
  LANGUAGE_TEXT(4, "\xbfTe han le\xeddo la suerte?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SAD, 1)
  LANGUAGE_TEXT(0, "Sigh...\n\nYes, and... well...\n\n")
  LANGUAGE_TEXT(1, "Soupir...\n\nOui, et...\n\n")
  LANGUAGE_TEXT(2, "Seufz...\n\nJa, und also...\n\n")
  LANGUAGE_TEXT(3, "Sigh...\n\nEsatto, e, ecco...\n\n")
  LANGUAGE_TEXT(4, "Suspiro...\n\nS\xed, y, bien...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SET_OBJECT_POSITION(2, 36, 96, 0)
  WALK_OBJECT_Y(2, 60)
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(6)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(16)
  PLAY_MUSIC(32)
  LANGUAGE_TEXT(0, "Hey good-lookin'! Why don't\nyou mosey on over here to\n\nmy arm?\n\n")
  LANGUAGE_TEXT(1, "H\xe9, poup\xe9e ! Viens l\xe0\ndans mes bras !\n\n")
  LANGUAGE_TEXT(2, "He, Baby! Komm in\nmeine Arme!\n\n")
  LANGUAGE_TEXT(3, "Ehi, pupa! Il tuo posto\n\xe8 accanto a me!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hey, baby! \xa1Tienes que\ncogerte de mi brazo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "...\n\n")
  LANGUAGE_TEXT(1, "...\n\n")
  LANGUAGE_TEXT(2, "...\n\n")
  LANGUAGE_TEXT(3, "...\n\n")
  LANGUAGE_TEXT(4, "...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Ooh, she looks feisty, but\nshe's a shy one. Just the\n\nway I like it!\n\n")
  LANGUAGE_TEXT(1, "Oh, elle est timide,\nma copine, et pourtant,\n\nc'est la plus belle !\n\n")
  LANGUAGE_TEXT(2, "Oh, sie ist so sch\xfcchtern,\nmeine Kleine, und dabei\n\nsieht sie so s\xfc\xdf aus!\n\n")
  LANGUAGE_TEXT(3, "Fa la timida, la mia\nragazza, nonostante\n\nil suo dolce sguardo!\n\n")
  LANGUAGE_TEXT(4, "Oh, es una t\xedmida, mi\nchica, \xa1a pesar de su\n\naspecto dulce!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "{PLAYER}... You'll get rid\nof this jerk for me, right?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}... Tu vas bien\nfaire quelque chose, non ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}... Du wirst doch\netwas dagegen unternehmen?!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}... Ci\npensi tu a lui, vero?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}... \xbfHar\xe1s\nalgo al respecto? \xbfNo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428BC, map_01_state_08_08E428BC, 0x08E428D4, 0x08E428C8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428D4, map_01_state_08_08E428D4, 0x08E428E0, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(32)
  LANGUAGE_TEXT(0, "What do you want?\n\nYou think you can beat me in\na duel?\n\nHah, that's hilarious!\n\nOkay baby, you'll be mine\nafter I dance all over this\n\njoker!\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce que tu veux ?\n\nTu crois pouvoir\nm'affronter en duel ?\n\nArr\xeate, \xe7a me fait rire.\n\nOK, poup\xe9e, tu seras\n\xe0 moi une fois que j'aurais\n\nbattu ce minable !\n\n")
  LANGUAGE_TEXT(2, "Was willst du?\n\nGlaubst du, du kannst dich\neinfach mit mir duellieren?\n\nHaha, wie k\xf6stlich.\nOkay, Baby, sobald ich\n\ndiesen Witzbold erledigt\nhabe, geh\xf6rst du mir!\n\n")
  LANGUAGE_TEXT(3, "E tu cosa vuoi?\n\nPensi di poter duellare\ncon me, non \xe8 cos\xec?\n\nHah, che ridere!\n\nOkay pupa, sarai mia quando\navr\xf2 battuto questo tizio!\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 quieres?\n\nCrees que puedes\nluchar conmigo, \xbfno?\n\nJa, es gracioso.\n\nVale, baby, \xa1ser\xe1s m\xeda cuando\nvenza a este buf\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 26)
  MOVE_OBJECT(2, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  DUEL(132)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428E0, map_01_state_08_08E428E0, 0x08E428EC, 0x08F04040)
  PLAY_MUSIC(32)
  LANGUAGE_TEXT(0, "I wish you could have seen\nmy dance steps!\n\n")
  LANGUAGE_TEXT(1, "Oh poup\xe9e, si seulement\ntu m'avais vu danser !\n\n")
  LANGUAGE_TEXT(2, "Oh, Baby, du h\xe4ttest meine\nTanzschritte sehen sollen!\n\n")
  LANGUAGE_TEXT(3, "Oh, pupa, ti sei persa\nun gran ballerino!\n\n")
  LANGUAGE_TEXT(4, "Oh, baby, \xa1si s\xf3lo\nhubieras visto\n\nmis pasos de baile!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 72)
  DELAY(6)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(6)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(6)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  WALK_OBJECT_Y(2, 96)
  DELAY(32)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "What was up with dat guy?\n\n")
  LANGUAGE_TEXT(1, "Mais il est dingue,\nce type ou quoi ?\n\n")
  LANGUAGE_TEXT(2, "Was war das f\xfcr ein Typ?\n\n")
  LANGUAGE_TEXT(3, "Ma che voleva fare\nquel tipo?\n\n")
  LANGUAGE_TEXT(4, "\xbfDe qu\xe9 iba ese tipo?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428EC, map_01_state_08_08E428EC, 0x08E428F8, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(16)
  SET_OBJECT_POSITION(3, 36, 0, 0)
  WALK_OBJECT_Y(3, 32)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  PLAY_MUSIC(28)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "A-ha! I've found you at\nlast, Tea Gardner!!\n\n")
  LANGUAGE_TEXT(1, "A-ha ! Je t'ai enfin\ntrouv\xe9e, Tea Gardner !\n\n")
  LANGUAGE_TEXT(2, "A-hah! Endlich habe ich dich\ngefunden, Tea Gardner!\n\n")
  LANGUAGE_TEXT(3, "A-hah! Finalmente ti ho\ntrovata, Tea Gardner!\n\n")
  LANGUAGE_TEXT(4, "\xa1A-ja! \xa1Por fin te\nencuentro, Tea Gardner!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "The fortuneteller said\nyou'll bring me luck, so I\n\nwant you working for me!!\n\n")
  LANGUAGE_TEXT(1, "Je suis venu te demander\nde devenir ma secr\xe9taire !\n\nSelon le diseur de bonne\naventure, tu portes chance.\n\n")
  LANGUAGE_TEXT(2, "Willst du meine Sekret\xe4rin\nwerden?\n\nDer Wahrsager meinte, du\nw\xfcrdest mir Gl\xfcck bringen!\n\n")
  LANGUAGE_TEXT(3, "Sono venuto a chiederti\ndi farmi da segretaria.\n\nL'indovino mi ha detto\nche porterai portuna!\n\n")
  LANGUAGE_TEXT(4, "Vine a pedirte que\nseas mi secretaria.\n\n\xa1El adivino me dijo\nque traes suerte!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "I don't think so! Take you\nand your tux somewhere\n\nelse!\n\n")
  LANGUAGE_TEXT(1, "Oh, non...\nC'est une plaisanterie.\n\n")
  LANGUAGE_TEXT(2, "Oh, nein...\nDas ist nicht dein Ernst.\n\n")
  LANGUAGE_TEXT(3, "Oh, no...\nDimmi che \xe8 uno scherzo.\n\n")
  LANGUAGE_TEXT(4, "Oh, no...\nEst\xe1s de broma...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "On the contrary!\n\nYou're my last chance to\nrekindle my dream...\n\nMy dream of making Penguin\nLand!\n\nAnd you're going to help me!\n\n")
  LANGUAGE_TEXT(1, "Oh, non, non ! Tu\nne dois pas refuser !\n\nTu es mon seul espoir\nde r\xe9aliser mon r\xeave...\n\nMon r\xeave de rejoindre\nPenguin Land !\n\nS'il te pla\xeet, j'ai\nbesoin de ton aide !\n\n")
  LANGUAGE_TEXT(2, "Oh bitte!\nSag nicht nein!\n\nNur mit dir kann mein\nTraum in Erf\xfcllung gehen...\n\nMein Traum, Penguin Land\nzu schaffen!\n\nBitte, ich brauche deine\nHilfe!\n\n")
  LANGUAGE_TEXT(3, "Neanche per sogno!\nNon devi dire di no!\n\nSolo con te potr\xf2\nrealizzare il mio sogno...\n\nQuello di creare\nPenguin Land!\n\nTi prego, mi serve\nil tuo aiuto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh, no, no!\n\xa1No debes decir que no!\n\nEres mi oportunidad para\nreavivar mi sue\xf1o...\n\n\xa1Mi sue\xf1o de erigir\nPenguin Land!\n\n\xa1Por favor, necesito\ntu ayuda!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(275)
  REACTION(5, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Forget it, creep!\n\n")
  LANGUAGE_TEXT(1, "Tu ferais bien\nde m'oublier !\n\n")
  LANGUAGE_TEXT(2, "Vergiss es!\n{PLAYER}...\n\n")
  LANGUAGE_TEXT(3, "Scordatelo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Olv\xeddalo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, can you get rid of\nthis guy, too?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, tu peux aussi me\nd\xe9barrasser de ce type ?\n\n")
  LANGUAGE_TEXT(2, "Kannst du auch diesen Typen\nf\xfcr mich loswerden?\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, ti puoi\noccupare anche di\n\nquesto tipo?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfte puedes\ndeshacer de este tipo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(271)
  REACTION(0, 8)
  DELAY(16)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "A duel? Fine! A duel it is!\n\nMy calculations state that\nthe odds of you winning are\n\na billion to one!\n\nAnd then Tea will be working\nfor me!\n\n")
  LANGUAGE_TEXT(1, "Un duel ? Tr\xe8s bien,\nalors commen\xe7ons !\n\nTu as l'air bien s\xfbr de\ngagner... Quelle vanit\xe9 !\n\nJe vais te montrer que\nrien n'est moins s\xfbr.\n\nEt ensuite, Mlle Gardner\ndeviendra ma secr\xe9taire !\n\n")
  LANGUAGE_TEXT(2, "Ein Duell?\nNa gut!\n\nWie eitel von dir, von einem\nSieg so \xfcberzeugt zu\n\nsein...\n\nIch werde dir beweisen, dass\ner gar nicht so sicher ist!\n\nUnd dann nehme ich Frau\nGardner als Sekret\xe4rin!\n\n")
  LANGUAGE_TEXT(3, "Duellare? Bene,\nduelliamo pure!\n\nNon penserai mica\ndi poter vincere...\n\nFossi in te, non ne sarei\ncos\xec sicuro! Allora la\n\nSignorina Gardner\nmi far\xe0 da segretaria!\n\n")
  LANGUAGE_TEXT(4, "\xbfDuelo?\n\xa1Bien, que as\xed sea!\n\nTu vana confianza\nen la victoria...\n\nTe ense\xf1ar\xe9 que aqu\xed\nno hay nada seguro.\n\n\xa1Y entonces reclamar\xe9\na Miss Gardner como\n\nmi secretaria!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 26)
  MOVE_OBJECT(3, 0, 0, 0)
  MOVE_OBJECT(1, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DUEL(133)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428F8, map_01_state_08_08E428F8, 0x08E42904, 0x08F04040)
  PLAY_MUSIC(28)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "You should learn to respect\nyour elders, even if\n\nthey're penguins!\n\n")
  LANGUAGE_TEXT(1, "Les gens comme toi n'ont\naucun respect pour les\n\npersonnes \xe2g\xe9es...\n\nC'est de leur faute\nsi le monde va si mal !\n\n")
  LANGUAGE_TEXT(2, "Jemand wie du, der\n\xc4ltere nicht ehrt...\n\nSo welche ruinieren\ndie Erde!\n\n")
  LANGUAGE_TEXT(3, "Quelli come te non hanno\nrispetto per gli anziani...\n\nE siete voi a rovinare\nil mondo!\n\n")
  LANGUAGE_TEXT(4, "La gente como t\xfa no respeta\na los mayores...\n\n\xa1Los que son como t\xfa sois los\nque arruin\xe1is el mundo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 36)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "And believe me, Tea! My\nfeathered friends are cuter\n\nthan you!\n\n")
  LANGUAGE_TEXT(1, "Tea Gardner !\n\nUn conseil des pingouins :\nen grandissant, reste\n\ntoujours aussi gentille !\n\n")
  LANGUAGE_TEXT(2, "Tea Gardner!\n\nMach's wie die Pinguine -\nbleib niedlich!\n\n")
  LANGUAGE_TEXT(3, "Tea Gardner!\n\nPrendi esempio dai pinguini\ne diventa ingegnosa!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tea Gardner!\n\n\xa1Toma un consejo de los\nping\xfcinos y crece mona!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(3, 0)
  SET_OBJECT_POSITION(3, 128, 96, 0)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24579)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42904, map_01_state_08_08E42904, 0x08F04040, 0x08F04040)
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(4)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Wh-what's going on? This\nworld is full of\n\nweirdoes...\n\n")
  LANGUAGE_TEXT(1, "Q.. Qu'est-ce\nqui se passe ?\n\nC'est quoi, ces tordus ?\n\n")
  LANGUAGE_TEXT(2, "W-was ist los? Was ist mit\nden komischen Typen?\n\n")
  LANGUAGE_TEXT(3, "Cosa sta succedendo? Chi\nsono quei tipi strani?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ-qu\xe9 ocurre?\n\xbfQu\xe9 pasa con los tarados?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "It's just what the\nfortuneteller predicted.\n\n")
  LANGUAGE_TEXT(1, "C'est exactement ce que le\ndiseur de bonne aventure\n\navait pr\xe9vu.\n\n")
  LANGUAGE_TEXT(2, "Es ist so, wie der\nWahrsager sagte.\n\n")
  LANGUAGE_TEXT(3, "Si tratta di ci\xf2 che\naveva predetto l'indovino.\n\n")
  LANGUAGE_TEXT(4, "Es justo como lo\npredijo el adivino.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 8192)
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Oh, yeah, you were saying\nsomething about your\n\nfortune before those guys\nshowed up.\n\n")
  LANGUAGE_TEXT(1, "Ah ouais, tu avais parl\xe9\nd'un truc pareil.\n\n")
  LANGUAGE_TEXT(2, "Ach ja, du erw\xe4hntest\nes vorher.\n\n")
  LANGUAGE_TEXT(3, "Ah, gi\xe0, e stavi dicendo\nqualcosa a tale proposito.\n\n")
  LANGUAGE_TEXT(4, "Oh, s\xed, dijiste algo\nal respecto.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "The fortuneteller predicted\nthat I would have the worst\n\nluck with men today.\n\nAnd he was right on the\nmoney.\n\n")
  LANGUAGE_TEXT(1, "Il a dit que je n'aurais\naucune chance\n\navec les hommes.\n\nCe sont ses pr\xe9visions\npour aujourd'hui.\n\n")
  LANGUAGE_TEXT(2, "Er sagte, ich w\xfcrde nur\nPech mit M\xe4nnern haben.\n\nJedenfalls heute...\n\n")
  LANGUAGE_TEXT(3, "Disse che avrei avuto\nuna sfortuna nera con gli\n\nuomini. Aveva predetto\nquesto per oggi.\n\n")
  LANGUAGE_TEXT(4, "Dijo que yo tendr\xeda\np\xe9sima suerte con\n\nlos hombres.\n\nEs lo que predijo\npara hoy.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, 1)
  LANGUAGE_TEXT(0, "Yeah, men don't get any\nworse than them.\n\n")
  LANGUAGE_TEXT(1, "En effet, on dirait bien\nque tu n'as pas de chance.\n\n")
  LANGUAGE_TEXT(2, "Ja, so sieht es wirklich\naus.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, pi\xf9 nera di cos\xec\nsi muore...\n\n")
  LANGUAGE_TEXT(4, "S\xed, realmente parece\np\xe9sima.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "I'm going to lay low for the\nrest of the day. I don't\n\nwant to run into any more\npsychos.\n\nI'll be back at Yugi's\ngrandpa's shop...\n\n")
  LANGUAGE_TEXT(1, "Je ferais bien de\nme faire plus discr\xe8te.\n\nJe retourne au magasin\ndu grand-p\xe8re de Yugi...\n\n")
  LANGUAGE_TEXT(2, "Daher sollte ich mich wohl\nunauff\xe4llig verhalten.\n\nIch gehe zur\xfcck zum Laden\nvon Yugis Gro\xdfvater...\n\n")
  LANGUAGE_TEXT(3, "Vorr\xe0 dire che devo\ndarmi una calmata.\n\nMe ne torner\xf2 al negozio\ndel nonno di Yugi...\n\n")
  LANGUAGE_TEXT(4, "Creo que quiere decir\nque debo abandonar.\n\nVolver\xe9 a la tienda del\nabuelo de Yugi...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 64)
  WALK_OBJECT_X(1, 0)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  SET_FLAG(EVENT_FLAG_TEA_WENT_BACK_TO_THE_SHOP)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E428C8, map_01_state_08_08E428C8, 0x08E428BC, 0x08F04040)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SAD, 1)
  LANGUAGE_TEXT(0, "...Just my luck...\n\nI get hit on by a weirdo,\nand {PLAYER} won't help\n\nme...\n\n")
  LANGUAGE_TEXT(1, "... J'ai vraiment\npas de chance...\n\nD'abord, je tombe sur\nun tordu qui me drague\n\net ensuite, {PLAYER}\nne veut pas m'aider...\n\n")
  LANGUAGE_TEXT(2, "... Ich habe mehr Pech\nals jeder andere...\n\nEin komischer Typ verknallt\nsich in mich und verfolgt\n\nmich, und {PLAYER}\nunternimmt nichts...\n\n")
  LANGUAGE_TEXT(3, "... Non conosco nessuno\npi\xf9 sfortunato di me...\n\nM'imbatto in un balordo e\n{PLAYER} se ne infischia...\n\n")
  LANGUAGE_TEXT(4, "... Tengo la peor\nsuerte del mundo...\n\nMe golpea un tarado\ny {PLAYER} no ayuda...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, we should help\nher.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER},\non devrait l'aider.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, wir sollten\nihr helfen.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, dovremmo\ndarle una mano.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, deber\xedamos\nayudarla.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, I'm tellin' ya,\nthink of the consequences.\n\nTea is the toughest girl I\nknow, and she's not gonna\n\nlet the fact that you didn't\nhelp her slide by.\n\nBetween me and you, I'd say\nyou should help Tea.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER},\nce que je veux te dire,\n\nc'est : pense aux\ncons\xe9quences.\n\nJe ne veux pas savoir\nce que Tea te r\xe9serve.\n\nSi tu veux un conseil d'ami,\ntu devrais aider Tea.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, ich warne dich,\nbedenke die Folgen.\n\nWer wei\xdf, was Tea hinterher\nmit dir anstellt.\n\nUnter uns, ich finde, du\nsolltest Tea helfen.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, ti dico di\npensare alle conseguenze.\n\nNon oso pensare a cosa\nti farebbe Tea, dopo.\n\nVuoi un consiglio da amico?\nDovresti aiutare Tea.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, te aviso, piensa\nen las consecuencias.\n\nNo quiero pensar qu\xe9\nte har\xeda Tea despu\xe9s.\n\nEntre amigos, creo que\nhas de ayudar a Tea.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
