#include "event_macros.h"
#include "overworld.h"

/* map_20_state_02: map 20 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E84F48, map_20_state_02_08E84F48, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Grovel before me like the\ndog that you are!\n\nI'm trying to imitate Kaiba.\nPretty good, right?\n\nHuh? He doesn't sound like\nthat? A-are you sure?\n\n")
  LANGUAGE_TEXT(1, "Un combat en solde !\n\nJ'essaie d'imiter\nM. Kaiba Seto.\n\nHein ? Il n'est pas\ncomme \xe7a ? T-tu crois ?\n\n")
  LANGUAGE_TEXT(2, "Ein Schn\xe4ppchen!\n\nIch will Kaiba Seto\nnachahmen.\n\nWas? Er ist gar nicht so?\nMeinst du?\n\n")
  LANGUAGE_TEXT(3, "Proprio un bell'affare!\n\nSto cercando di imitare il\nSignor Kaiba Seto.\n\nCome? Lui non \xe8 cos\xec?\nLo pensi davvero?\n\n")
  LANGUAGE_TEXT(4, "\xa1Menudo lloriqueo!\n\nIntento imitar al\nSr. Kaiba Seto.\n\n\xbfEh? \xbfNo es as\xed?\n\xbfT-t\xfa crees?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E84F54, map_20_state_02_08E84F54, 0x08E84F60, 0x08E84F78)
  CHECK_FLAG(90)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E84F60, map_20_state_02_08E84F60, 0x08E84F6C, 0x08F0404C)
  LANGUAGE_TEXT(0, "The road to victory lies in\ncombat!\n\nWith this duel, I will\nfinish you!\n\n")
  LANGUAGE_TEXT(1, "Le chemin\nde notre bataille !\n\nAvec ce duel, tu es fichu !\n\n")
  LANGUAGE_TEXT(2, "Unsere Kampfstra\xdfe!\n\nMit diesem Duell mache\nich dich fertig!\n\n")
  LANGUAGE_TEXT(3, "La strada su cui ci\nbatteremo!\n\nCon questo duello, ti\nfinir\xf2!\n\n")
  LANGUAGE_TEXT(4, "\xa1Nuestro camino\na la batalla!\n\n\xa1Con este duelo,\nacabar\xe9 contigo!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(29)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E84F6C, map_20_state_02_08E84F6C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(231)
  LANGUAGE_TEXT(0, "Hahaha! Acting tough didn't\ndo a thing for my\n\nstrategies!\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha !\nCe n'est pas en jouant\n\nau gros dur que tu vas\ngagner !\n\n")
  LANGUAGE_TEXT(2, "Hahaha! Sich aufzuspielen\nverbessert jedenfalls nicht\n\ndie Kampftechnik!\n\n")
  LANGUAGE_TEXT(3, "Ahahah! Darsi le arie\nnon basta per vincere!\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajaja! \xa1Vacilar no\nayuda a ganar!\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(90)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E84F78, map_20_state_02_08E84F78, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "No, it's okay.\n\nI now know that I can't win\njust by pretending to be\n\nKaiba.\n\n")
  LANGUAGE_TEXT(1, "Non, c'est bon.\n\nMaintenant, je sais\nque je ne peux pas\n\ngagner en\nimitant M. Kaiba.\n\n")
  LANGUAGE_TEXT(2, "Nein, ist schon okay.\n\nJetzt wei\xdf ich, dass ich\nnicht gewinne, wenn ich\n\nnur versuche, Herrn\nKaiba nachzuahmen.\n\n")
  LANGUAGE_TEXT(3, "No, va bene. Lo so che\nnon posso vincere\n\nimitando il Signor Kaiba.\n\n")
  LANGUAGE_TEXT(4, "No, est\xe1 bien.\n\nS\xe9 que no puedo ganar\nimitando al Sr. Kaiba.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
