#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_59_state_04: map 59 state 4 */

LOAD_SPRITE(1, SPRITE_ODION)
PLAY_MUSIC(MUSIC_EGYPT)
DELAY(16)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, OBJECT_1)
DELAY(16)
MOVE_OBJECT(1, DIRECTION_RIGHT, 16, 0)
MOVE_OBJECT(0, DIRECTION_LEFT, 16, 0)
MOVE_OBJECT(13, DIRECTION_LEFT, 16, 0)
MOVE_OBJECT(14, DIRECTION_LEFT, 16, 0)
PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "What is the matter,\n"
    "{PLAYER}?\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
DELAY(8)
PORTRAIT(PORTRAIT_ODION, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
TEXT
(
    "I-Impossible!\n\n"
    "You obtained the secret of\n"
    "the Phoenix Mode?\n\n"
    "We must see Master Marik\n"
    "right away!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(1, 61)
WALK_OBJECT_Y(1, 24)
SHOW_OBJECT(1, 128, 96, 0, 0, 0)
WALK_OBJECT_X(0, 61)
WALK_OBJECT_Y(0, 24)
SHOW_OBJECT(0, 128, 96, 0, 0, 0)
CHECK_FLAG(EVENT_FLAG_YUGI_LEFT_THE_PARTY)
WALK_OBJECT_X(13, 61)
WALK_OBJECT_Y(13, 24)
SHOW_OBJECT(13, 128, 96, 0, 0, 0)
CHECK_FLAG(EVENT_FLAG_JOEY_LEFT_THE_PARTY)
WALK_OBJECT_X(14, 61)
WALK_OBJECT_Y(14, 24)
SHOW_OBJECT(14, 128, 96, 0, 0, 0)
FADE_MUSIC(4)
FADE_SCREEN(4)
WARP(LOCATION_EGYPT_MARIK_ROOM, 5, 0, 0)
