#include "event_macros.h"
#include "overworld.h"

/* map_12_state_13: map 12 state 13 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F174, map_12_state_13_08E6F174, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(31)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Roland, you played a good\nKaibaman.\n\n")
  LANGUAGE_TEXT(1, "Roland, c'\xe9tait un tr\xe8s\nbon Kaibaman.\n\n")
  LANGUAGE_TEXT(2, "Roland, das war ein guter\nKaibaman.\n\n")
  LANGUAGE_TEXT(3, "Roland, quello era un\nKaibaman buono.\n\n")
  LANGUAGE_TEXT(4, "Roland, ha sido un muy\nbueno Kaibaman.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Thank you, Master Mokuba.\n\n")
  LANGUAGE_TEXT(1, "Merci, ma\xeetre Mokuba.\n\n")
  LANGUAGE_TEXT(2, "Danke, Meister Mokuba.\n\n")
  LANGUAGE_TEXT(3, "Grazie, maestro Mokuba.\n\n")
  LANGUAGE_TEXT(4, "Gracias, amo Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Everyone, good work! I'm\ncounting on you again for\n\nthe next show!\n\n")
  LANGUAGE_TEXT(1, "Vous avez tous tr\xe8s\nbien travaill\xe9 !\n\nNous ferons \xe0 nouveau\nappel \xe0 vos services !\n\n")
  LANGUAGE_TEXT(2, "Ihr habt alle gute Arbeit\ngeleistet! Wir m\xf6chten euch\n\ngerne wiedersehen!\n\n")
  LANGUAGE_TEXT(3, "Vi siete comportati tutti\nbenissimo. Vi rivogliamo\n\ncon noi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Todos los hicisteis\nmuy bien!\n\n\xa1Os queremos de vuelta!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 248)
  DELAY(16)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Men, he did give us a job...\n\n")
  LANGUAGE_TEXT(1, "Il-il nous a donn\xe9\ndu travail...\n\n")
  LANGUAGE_TEXT(2, "E-er stellt uns ein...\n\n")
  LANGUAGE_TEXT(3, "Lui... ci ha dato\nun compito...\n\n")
  LANGUAGE_TEXT(4, "N-nos ha dado un empleo...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "But we were once The Big\nFive...\n\n")
  LANGUAGE_TEXT(1, "Mais avant, on nous appelait\nles Cinq M\xe9chants...\n\n")
  LANGUAGE_TEXT(2, "Aber man nannte uns einst\ndie {BYTE_8168}Big Five{BYTE_8168}...\n\n")
  LANGUAGE_TEXT(3, "Ma un tempo ci chiamavano\ni Temibili Cinque...\n\n")
  LANGUAGE_TEXT(4, "Pero una vez fuimos\nlos Cinco Malvados...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(5, 0, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Is this a job fit for the\nformer KaibaCorp Board of\n\nDirectors?\n\n")
  LANGUAGE_TEXT(1, "Tu crois que c'est un\ntravail digne de nous ?\n\n")
  LANGUAGE_TEXT(2, "Soll das eine Stelle sein,\ndie unser w\xfcrdig ist?\n\n")
  LANGUAGE_TEXT(3, "E secondo te questo\ncompito \xe8 adatto a noi?\n\n")
  LANGUAGE_TEXT(4, "\xbfA esto le llamas un trabajo\nbueno para nosotros?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 248)
  DELAY(16)
  LANGUAGE_TEXT(0, "No! It's not!\n\nI don't want a job\nentertaining runts!\n\n")
  LANGUAGE_TEXT(1, "Non ! Je ne veux\npas le faire !\n\nJe ne veux pas un\ntravail comme celui-l\xe0 !\n\n")
  LANGUAGE_TEXT(2, "Nein!\nNicht mit mir!\n\nSo einen Job will ich nicht!\n\n")
  LANGUAGE_TEXT(3, "No! Io non lo far\xf2!\n\nNon lo faccio un\nlavoro del genere!\n\n")
  LANGUAGE_TEXT(4, "\xa1No!\n\xa1No lo har\xe9!\n\n\xa1No quiero un trabajo as\xed!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(4)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(6, 0)
  MOVE_OBJECT(6, 1, 16, 0)
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  MOVE_OBJECT(5, 1, 0, 0)
  MOVE_OBJECT(7, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Wh-where are you going, Big\n{BYTE_8253}?\n\nWait for me!\n\n")
  LANGUAGE_TEXT(1, "O\xf9-o\xf9 tu vas,\nM\xe9chant {BYTE_8253} ?\n\nH\xe9, attendez-moi !\n\n")
  LANGUAGE_TEXT(2, "W-wohin willst du,\nBig {BYTE_8253}?\n\nWartet, ich komme mit!\n\n")
  LANGUAGE_TEXT(3, "Ma dove vai,\nTemibile {BYTE_8253}?\n\nAspettatemi, vengo\nanch'io!\n\n")
  LANGUAGE_TEXT(4, "\xbfD-d\xf3nde vais,\nMalvado N\xba {BYTE_8253}?\n\n\xa1Esperad, yo tambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, 1, 16, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Don't leave me alone!\n\n")
  LANGUAGE_TEXT(1, "Ne me laissez pas\nici tout seul !\n\n")
  LANGUAGE_TEXT(2, "Lasst mich hier nicht\nallein!\n\n")
  LANGUAGE_TEXT(3, "Non lasciatemi\nqui in questo modo!\n\n")
  LANGUAGE_TEXT(4, "\xa1No me dej\xe9is aqu\xed as\xed!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, 1, 16, 0)
  DELAY(32)
  MOVE_OBJECT(5, 0, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  DELAY(32)
  LANGUAGE_TEXT(0, "W-we should go, too.\n\nY-yes we should.\n\nWait for us!\n\n")
  LANGUAGE_TEXT(1, "On-on devrait\naussi y aller.\n\nO-oui.\n\nAttendez-nous !\n\n")
  LANGUAGE_TEXT(2, "W-wir sollten auch gehen.\n\nJ-ja.\n\nWartet auf uns!\n\n")
  LANGUAGE_TEXT(3, "Dovremmo andare\nanche noi.\n\nS-s\xec.\n\nAspettateci!\n\n")
  LANGUAGE_TEXT(4, "T-tambi\xe9n deber\xedamos ir.\n\nS-s\xed.\n\n\xa1Esperadnos!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(5, 0)
  MOVE_OBJECT(5, 1, 16, 0)
  WALK_OBJECT_X(7, 0)
  MOVE_OBJECT(7, 1, 16, 0)
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "The Big Five are a buncha\nweirdoes. Man, I'd hate to\n\nbe them.\n\n")
  LANGUAGE_TEXT(1, "Ces Cinq Grands\nM\xe9chants...\n\nJ'aimerais vraiment\npas \xeatre \xe0 leur place.\n\n")
  LANGUAGE_TEXT(2, "Die armen {BYTE_8168}Big Five{BYTE_8168}-\nTypen...\n\nIch m\xf6chte nicht in\nihrer Haut stecken.\n\n")
  LANGUAGE_TEXT(3, "Poveri Temibili Cinque...\nNon vorrei essere\n\nal posto loro.\n\n")
  LANGUAGE_TEXT(4, "Esos pobres Cinco Malvados\n... Odiar\xeda ser ellos.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, 2, 2, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Joey, Yugi, {PLAYER}, wasn't\nthat fun?\n\n")
  LANGUAGE_TEXT(1, "Joey, Yugi, {PLAYER},\non ne s'est pas amus\xe9 ?\n\n")
  LANGUAGE_TEXT(2, "Joey, Yugi, {PLAYER},\nhat das nicht Spa\xdf gemacht?\n\n")
  LANGUAGE_TEXT(3, "Joey, Yugi, {PLAYER},\nnon vi siete divertiti?\n\n")
  LANGUAGE_TEXT(4, "Joey, Yugi, {PLAYER},\n\xbfno ha sido divertido?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's all watch the show\nagain sometime!\n\n")
  LANGUAGE_TEXT(1, "On n'a qu'\xe0 tous revenir !\n\n")
  LANGUAGE_TEXT(2, "Irgendwann sollten wir uns\ndas noch einmal ansehen!\n\n")
  LANGUAGE_TEXT(3, "Torniamo tutti allo show!\n\n")
  LANGUAGE_TEXT(4, "\xa1Volvamos de nuevo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(8, 0)
  SHOW_OBJECT(8, 128, 96, 0, 0, 0)
  SET_FLAG(EVENT_FLAG_WATCHED_THE_KAIBAMAN_SHOW)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1B0, map_12_state_13_08E6F1B0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I was the one wearing the\nKaibaman costume.\n\nBut that's top secret!\n\n")
  LANGUAGE_TEXT(1, "Ouais, je portais le\ncostume Kaibaman.\n\nMais c'est top secret !\n\n")
  LANGUAGE_TEXT(2, "Ja, ich steckte im\nKaibaman-Kost\xfcm.\n\nAber das ist streng\ngeheim!\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, io indossavo il\ncostume da Kaibaman.\n\nMa deve restare un segreto!\n\n")
  LANGUAGE_TEXT(4, "S\xed, llevaba el traje\nde Kaibaman.\n\n\xa1Pero eso es\nsupersecreto!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1BC, map_12_state_13_08E6F1BC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "There's no way you can beat\nKaibaman.\n\nYou shouldn't even try.\n\n")
  LANGUAGE_TEXT(1, "Tu n'as aucune chance\nde battre Kaibaman.\n\nA ta place, je\nn'essayerais m\xeame pas.\n\n")
  LANGUAGE_TEXT(2, "Du besiegst Kaibaman\nnie im Leben.\n\nAn deiner Stelle w\xfcrde ich\nes auch gar nicht\n\nversuchen.\n\n")
  LANGUAGE_TEXT(3, "Non hai alcuna possibilit\xe0\ndi battere Kaibaman.\n\nTi consiglio di non\nprovarci nemmeno.\n\n")
  LANGUAGE_TEXT(4, "No hay modo de que\nvenzas a Kaibaman.\n\nTe sugiero que ni\nlo intentes.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(274)
  REACTION(REACTION_SWEATDROP, 1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F198, map_12_state_13_08E6F198, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Kaibaman show is really\npopular.\n\n")
  LANGUAGE_TEXT(1, "Le spectacle Kaibaman\nest vraiment populaire.\n\n")
  LANGUAGE_TEXT(2, "Die Kaibaman Show ist\nverteufelt beliebt.\n\n")
  LANGUAGE_TEXT(3, "Il Kaibaman Show \xe8\ntremendamente famoso.\n\n")
  LANGUAGE_TEXT(4, "El show de Kaibaman\nes superpopular.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1A4, map_12_state_13_08E6F1A4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I bet you think you're a\nbetter duelist because you\n\nsaw the show.\n\nBut you're really not, so\nyou should forget about\n\ndueling.\n\nYou'll only get humiliated.\n\n")
  LANGUAGE_TEXT(1, "Tu crois \xeatre plus dur\nparce que tu as vu le show.\n\nMais maintenant, oublie les\nduels. Tu ne feras que\n\nd\xe9couvrir \xe0 quel point tu\n\xe9tais mauvais.\n\n")
  LANGUAGE_TEXT(2, "Du h\xe4ltst dich f\xfcr hart,\nnur weil du die Show\n\ngesehen hast. Vergiss jetzt\nDuelle. Sonst w\xfcrdest du\n\nnur merken, wie schlecht\ndu eigentlich bist.\n\n")
  LANGUAGE_TEXT(3, "Pensi di essere pi\xf9\nforte perch\xe9 hai\n\nassistito allo show.\nOra non pensare a\n\nduellare. Scopriresti\nsolo quanto sei scarso.\n\n")
  LANGUAGE_TEXT(4, "Crees que eres m\xe1s duro\nporque has visto el show.\n\nOlv\xeddate de duelos\npor ahora.\n\nS\xf3lo comprobar\xe1s lo\nmalo que eres.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
