#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_51_state_09: map 51 state 9 */

LOAD_SPRITE(1, SPRITE_ISHIZU)
LOAD_SPRITE(2, SPRITE_SETO)
LOAD_SPRITE(3, SPRITE_ATEM)
LOAD_SPRITE(4, SPRITE_JOEY)
PLAY_MUSIC(MUSIC_ESCAPE_FROM_PEGASUS_CASTLE)
SHOW_OBJECT(SPRITE_ISHIZU, 56, 32, 0, 0, 0)
WALK_OBJECT_Y(SPRITE_ISHIZU, 60)
PLAY_MUSIC(MUSIC_321)
OBJECT_EFFECT(SPRITE_ISHIZU, OBJECT_EFFECT_DISAPPEAR)
SHOW_OBJECT(SPRITE_SETO, 64, 32, 0, 0, 0)
WALK_OBJECT_Y(SPRITE_SETO, 60)
DELAY(16)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_LEFT, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_DOWN, 0, 0)
DELAY(4)
SHOW_OBJECT(SPRITE_ISHIZU, 56, 60, 0, 3, 0)
DELAY(8)
WALK_OBJECT_Y(SPRITE_SETO, 96)
WALK_OBJECT_Y(SPRITE_ISHIZU, 96)
DELAY(16)
FADE_SCREEN(16)
WARP(LOCATION_PEGASUS_CASTLE_OUTSIDE, 3, 0, 0)
