#include "event_macros.h"

/* map_26_state_02: map 26 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3B78, map_26_state_02_08EA3B78, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  WALK_OBJECT_Y(2, 70)
  WALK_OBJECT_Y(2, 40)
  WALK_OBJECT_Y(3, 40)
  WALK_OBJECT_Y(3, 70)
  PORTRAIT(6, 2, 0)
  LANGUAGE_TEXT(0, "C'mon, boys! Work harder,\nyou two!\n\nAt this rate, you'll never\nbecome real duelists.\n\nIt'll take you a hundred\nyears to reach my skill\n\nlevel!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, h\xe9 !\nAu travail, vous deux !\n\nVous ne serez jamais\nde bons duellistes,\n\nsi vous travaillez comme\n\xe7a. A ce rythme-l\xe0,\n\nvous ne pourrez pas\nm'affronter avant {BYTE_8250}{BYTE_824F}{BYTE_824F} ans !\n\n")
  LANGUAGE_TEXT(2, "He, he! Strengt euch etwas\nmehr an, ihr beiden!\n\nSo werdet ihr nie\nrichtige Duellanten!\n\nIhr liegt ca. {BYTE_8250}{BYTE_824F}{BYTE_824F} Jahre\nhinter mir zur\xfcck!\n\n")
  LANGUAGE_TEXT(3, "Ehi, ehi! Lavorate\ndi pi\xf9, voi due!\n\nSe non lavorate bene,\nnon diventerete mai\n\nveri duellanti. Potrete\nsfidarmi tra {BYTE_8250}{BYTE_824F}{BYTE_824F} anni!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eh, eh!\n\xa1A trabajar m\xe1s duro!\n\nNunca ser\xe9is buenos\nduelistas de ese modo.\n\n\xa1No os queda nada\npara retarme!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 5, 0)
  LANGUAGE_TEXT(0, "Wh-why are we working for\nMai?\n\n")
  LANGUAGE_TEXT(1, "P-pourquoi\nest-ce qu'on fait \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "W-warum tust du das?\n\n\n")
  LANGUAGE_TEXT(3, "P-perch\xe9 stiamo\nfacendo questo?\n\n")
  LANGUAGE_TEXT(4, "\xbfP-por qu\xe9 hacemos esto?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 5, 0)
  LANGUAGE_TEXT(0, "What'd we do to deserve\nthis?\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce qu'on a\nfait pour m\xe9riter \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Womit haben wir das\nverdient?\n\n")
  LANGUAGE_TEXT(3, "Cos'abbiamo fatto\nper meritarci questo?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 hemos hecho\npara merecerlo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  PORTRAIT(6, 0, 0)
  LANGUAGE_TEXT(0, "Oh, hi Joey!\n\nDo you want me to train you\ntoo?\n\n")
  LANGUAGE_TEXT(1, "Oh, h\xe9, Wheeler ?\n\nTu es aussi venu\npour t'entra\xeener ?\n\n")
  LANGUAGE_TEXT(2, "Oh, he, Wheeler?\n\nWillst du hier auch etwas\nlernen?\n\n")
  LANGUAGE_TEXT(3, "Oh, ehi, Wheeler?\n\nSei venuto anche tu\nad allenarti?\n\n")
  LANGUAGE_TEXT(4, "Oh, eh, \xbfWheeler?\n\n\xbfTambi\xe9n has venido\na entrenar?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(4, 5, 0)
  LANGUAGE_TEXT(0, "Why would I need training?\n\n")
  LANGUAGE_TEXT(1, "Pourquoi j'aurais\nbesoin de m'entra\xeener ?\n\n")
  LANGUAGE_TEXT(2, "Wieso sollte ich?\nUnd dann noch von dir...\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 avrei bisogno di\nallenarmi?\n\nSoprattutto da te.\n\n")
  LANGUAGE_TEXT(4, "\xbfPara qu\xe9 necesito\nentrenar?\n\nY especialmente contigo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(6, 0, 0)
  LANGUAGE_TEXT(0, "Ahahaha, I'm only joking.\n\nMinion One and Minion Two,\nstop slacking off!\n\n")
  LANGUAGE_TEXT(1, "Ah ah ah, je plaisante.\n\nServiteur {BYTE_8250} et {BYTE_8251},\nau boulot !\n\n")
  LANGUAGE_TEXT(2, "Ahahaha, war nur Spa\xdf.\n\nDiener {BYTE_8250} und {BYTE_8251}, nicht\nnachlassen!\n\n")
  LANGUAGE_TEXT(3, "Ahahahah, scherzavo.\n\nSchiavo {BYTE_8250} e {BYTE_8251}, non mollate!\n\n")
  LANGUAGE_TEXT(4, "Jajaja, s\xf3lo bromeaba.\n\nPringaos {BYTE_8250} y {BYTE_8251},\n\xa1no os pele\xe9is!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 5, 0)
  LANGUAGE_TEXT(0, "M-Minion One?\n\n")
  LANGUAGE_TEXT(1, "S-Serviteur {BYTE_8250} ?\n\n")
  LANGUAGE_TEXT(2, "D-Diener {BYTE_8250}?\n\n")
  LANGUAGE_TEXT(3, "S-schiavo {BYTE_8250}?\n\n")
  LANGUAGE_TEXT(4, "\xbfP-pringao {BYTE_8250}?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 5, 0)
  LANGUAGE_TEXT(0, "Two?!\n\n")
  LANGUAGE_TEXT(1, "Et deux ?!\n\n")
  LANGUAGE_TEXT(2, "Zwei?!\n\n")
  LANGUAGE_TEXT(3, "Due?!\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfDos?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 0)
  LANGUAGE_TEXT(0, "This sucks...\n\n")
  LANGUAGE_TEXT(1, "Alors \xe7a...\n\n")
  LANGUAGE_TEXT(2, "Das ist doch wohl\nder Gipfel...\n\n")
  LANGUAGE_TEXT(3, "\xc8 terribile...\n\n")
  LANGUAGE_TEXT(4, "Eso molesta...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(6, 7, 0)
  LANGUAGE_TEXT(0, "Wipe those frowns off your\nfaces.\n\nIf you really want to\nimprove your dueling\n\nskills, you should hit the\nroad on a training quest.\n\n")
  LANGUAGE_TEXT(1, "Arr\xeatez de faire la t\xeate.\nSi vous partiez en qu\xeate\n\nd'un entra\xeenement ?\nCa am\xe9liorera\n\nvos aptitudes au duel,\net rapidement !\n\n")
  LANGUAGE_TEXT(2, "Schaut doch nicht so\nwehleidig drein.\n\nWarum unternehmt ihr nicht\neine Trainingsmission?\n\nSo werdet ihr im Duell\nschnell besser.\n\n")
  LANGUAGE_TEXT(3, "Smettetela di fare\nquelle espressioni pietose.\n\nPerch\xe9 non partite per una\nmissione di allenamento?\n\nMigliorerete in fretta le\nabilit\xe0 di duellanti.\n\n")
  LANGUAGE_TEXT(4, "Borrad esas muecas\nmiserables de la cara.\n\n\xbfPor qu\xe9 no os\nlarg\xe1is a buscar pelea\n\nen una misi\xf3n de\nentrenamiento?\n\nMejorar\xe1 vuestras\naptitudes, y r\xe1pido.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(31, 0, 0)
  LANGUAGE_TEXT(0, "A training quest?\n\n")
  LANGUAGE_TEXT(1, "En qu\xeate d'un\nentra\xeenement ?\n\n")
  LANGUAGE_TEXT(2, "Eine Trainingsmission?\n\n")
  LANGUAGE_TEXT(3, "Una missione di allenamento?\n\n")
  LANGUAGE_TEXT(4, "\xbfUna misi\xf3n de\nentrenamiento?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(9, 1, 0)
  LANGUAGE_TEXT(0, "I'm going! I am soooo going!\n\nAnything beats getting\nworked like a mule.\n\nI would rather be anywhere\nelse but here!\n\nDuke, let's go!\n\n")
  LANGUAGE_TEXT(1, "Je veux y aller !\nC'est clair !\n\nC'est bien mieux\n\nque de travailler ici\ncomme serviteur.\n\nJe serais mieux n'importe\no\xf9, mais pas ici.\n\nDuke, allons-y !\n\n")
  LANGUAGE_TEXT(2, "Okay, ich gehe!\nIch gehe wirklich!\n\nImmer noch besser, als hier\nwie ein Sklave zu arbeiten.\n\nWas k\xf6nnte schlimmer\nsein?\n\nDuke, komm, wir gehen!\n\n")
  LANGUAGE_TEXT(3, "Io vado!\nParto subito!\n\nPiuttosto di lavorare\nda schiavo qui!\n\nPreferirei trovarmi in\nqualsiasi altro posto\n\ndiverso da qui, oggi.\nAndiamo, Duke!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo voy!\n\xa1Yo s\xed que voy!\n\nCualquier cosa mejor\nque hacer de esclavo aqu\xed.\n\nEn cualquier lugar\nmejor que aqu\xed.\n\nDuke, \xa1v\xe1monos!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(2, 70)
  WALK_OBJECT_X(2, 52)
  WALK_OBJECT_Y(2, 96)
  PORTRAIT(31, 0, 0)
  LANGUAGE_TEXT(0, "S-sure. Wait for me,\nTristan.\n\n")
  LANGUAGE_TEXT(1, "Bon... D'accord.\nAttends-moi, Tristan.\n\n")
  LANGUAGE_TEXT(2, "O-okay.\nWarte auf mich, Tristan.\n\n")
  LANGUAGE_TEXT(3, "C-certo. Aspettami,\nTristan.\n\n")
  LANGUAGE_TEXT(4, "Cl-claro.\nEsp\xe9rame, Tristan.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(3, 60)
  WALK_OBJECT_Y(3, 96)
  PORTRAIT(6, 7, 0)
  LANGUAGE_TEXT(0, "Those two... I was only\nkidding. I mean, what's a\n\ntraining quest anyway?\n\nSigh... Now that my minions\nare gone, I have to do my\n\nown work.\n\n")
  LANGUAGE_TEXT(1, "Ces deux-l\xe0...\nO\xf9 est-ce qu'ils vont ?\n\nBon, maintenant que\nmes larbins sont partis,\n\nje ferais bien de me\nmettre au travail.\n\n")
  LANGUAGE_TEXT(2, "Die beiden...\nWohin gehen sie?\n\nAber nun, da meine Diener\nfort sind, sollte ich mich\n\nbesser an die Arbeit\nmachen.\n\n")
  LANGUAGE_TEXT(3, "Ma dove vanno quei\ndue?\n\nComunque, ora che i miei\nschiavi se ne sono andati,\n\nfarei meglio a mettermi\nal lavoro.\n\n")
  LANGUAGE_TEXT(4, "Esos dos...\n\xbfAd\xf3nde van?\n\nBueno, ahora que se han\nido, mejor volver al curro.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(62)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3B84, map_26_state_02_08EA3B84, 0x08F04040, 0x08F04040)
  PORTRAIT(6, 0, 0)
  LANGUAGE_TEXT(0, "Tristan and Duke left on a\ntraining quest.\n\nBut what are they training\nfor?\n\n")
  LANGUAGE_TEXT(1, "Tristan et Duke sont\npartis en qu\xeate\n\nd'entra\xeenement. Mais je ne\nsais pas pourquoi ils vont\n\ns'entra\xeener.\n\n")
  LANGUAGE_TEXT(2, "Tristan und Duke haben\neine Trainingsmission.\n\nIch wei\xdf aber nicht, wof\xfcr\nsie geschult werden.\n\n")
  LANGUAGE_TEXT(3, "Tristan e Duke sono\npartiti per una missione\n\ndi allenamento. Non so\na cosa gli serva, per\xf2.\n\n")
  LANGUAGE_TEXT(4, "Tristan y Duke se han\nido en misi\xf3n de\n\nentrenamiento.\n\nAunque... No s\xe9 para\nqu\xe9 entrenan...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
