#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_44_state_01: map 44 state 1 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08EDA8AC, map_44_state_01_08EDA8AC, 0x08EDA8B8, 0x08F0404C)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Gawry nida! Gawry nida!",
      "We win all duels! Gawry!"
  )
  DUEL(DUELIST_CHEVALIER_108)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDA8B8, map_44_state_01_08EDA8B8, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_DUNGEON)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "G-gawry nida... G-ga.. n-niii.... urrri...")
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
