#include "event_macros.h"
#include "overworld.h"

/* map_22_state_08: map 22 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CBB8, map_22_state_08_08E8CBB8, 0x08E8CBC4, 0x08F04040)
  PLAY_MUSIC(405)
  DELAY(32)
  WALK_OBJECT_X(2, 52)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Big brother!\n\nMost of the Neo Ghouls have\nleft the Town of Domino.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Good.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I protected KaibaCorp, just\nlike you told me.\n\nSo you don't have to worry\nabout a thing.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Good work, Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Heheh, thanks. You know I'll\ndo anything for you.\n\nSo, anything new with your\nEgyptian God Card?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Somehow, it's back to\nnormal.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I don't know what they did,\nbut...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBC4, map_22_state_08_08E8CBC4, 0x08E8CBD0, 0x08F04040)
  PLAY_MUSIC(404)
  WALK_OBJECT_X(4, 48)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 0)
  LANGUAGE_TEXT(0, "Urk! S-Seto...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  SET_OBJECT_POSITION(2, 128, 96, 0)
  PLAY_MUSIC(314)
  SWAP_OBJECT_SPRITE(4, 127)
  DELAY(8)
  MOVE_OBJECT(1, 1, 0, 0)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 6, 1)
  LANGUAGE_TEXT(0, "How dare you... What's the\nmeaning of this?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Seto Kaiba! I have a message\nfrom Master Chevalsky!\n\nCome to my castle.\n\nIf you want to save your\ndear brother.\n\nYou have no choice but to\ncome to my castle!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 5, 1)
  LANGUAGE_TEXT(0, "You worm!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(4, 1, 8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBD0, map_22_state_08_08E8CBD0, 0x08E8CBDC, 0x08F04040)
  DELAY(16)
  SET_OBJECT_POSITION(3, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 24)
  WALK_OBJECT_X(3, 80)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "Younger brother, you have\nfulfilled your mission!\n\nMaster Chevalsky will\npromote you to a higher\n\nposition!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Elder brother, you also have\ndone your job with most\n\nexcellence!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 1)
  LANGUAGE_TEXT(0, "You punks! How dare you mock\nme!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "Fufufufufufu...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Fufufufufufu...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Master Chevalsky demands\nyour presence, Kaiba!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Come to Master Chevalsky's\ncastle!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "The castle that you...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "...Know so well! Fufufu...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(3, 1, 96)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(4, 1, 64)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 1)
  LANGUAGE_TEXT(0, "Mokuba!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 4, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBDC, map_22_state_08_08E8CBDC, 0x08E8CBE8, 0x08E8CBF4)
  SET_OBJECT_POSITION(0, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 24)
  WALK_OBJECT_X(0, 82)
  DELAY(16)
  SET_OBJECT_POSITION(13, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(13, 18)
  WALK_OBJECT_X(13, 87)
  DELAY(16)
  SET_OBJECT_POSITION(14, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(14, 30)
  WALK_OBJECT_X(14, 87)
  DELAY(16)
  SET_OBJECT_POSITION(5, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(5, 24)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(0, 77)
  DELAY(16)
  LANGUAGE_TEXT(0, "{CARD_1}Let us help!\nLend us your God Card!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBE8, map_22_state_08_08E8CBE8, 0x08E8CC00, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER} is right, Kaiba.\n\nNow is the time for\nteamwork.\n\nThe Dark Being must be\nsealed again...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Quiet, you!\n\nI'm never going to cooperate\nwith you!\n\nI'll crush Pegasus on my own\nand get Mokuba back!\n\nHow many times do I have to\nsay that I don't have time\n\nfor your so-called ancient\nmagic!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CC00, map_22_state_08_08E8CC00, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 0)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "We're left with no choice.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "We must also go to Sol\nChevalsky's... I mean...\n\nWe must also go to Pegasus's\ncastle.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "But who knows where the\ncastle is?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 24609)
  DELAY(16)
  PLAY_MUSIC(402)
  WALK_OBJECT_X(6, 48)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 32)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You have proven yourselves\nto the Millennium Items.\n\nTrace the flow of time and\naccept your destiny.\n\nOne man knows where you must\ngo.\n\nYou must seek out Paradox.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Paradox awaits you in China.\n\nHe will show you the way.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(6, 1, 64, 0)
  DELAY(32)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The Millennium Guard comes\nfrom the order that\n\nprotects the Millennium\nItems...\n\nI sensed that he was telling\nthe truth.\n\n{PLAYER}, you must go to\nChina.\n\nAs soon as possible.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(5, 0)
  SET_OBJECT_POSITION(5, 128, 96, 0)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I'm worried about Mokuba and\nKaiba...\n\nWe'd better find Pegasus's\ncastle quickly.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yugi's right.\n\nIf this Parachute guy can\nhelp us...\n\nWe'd betta find him quick.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "That's Paradox, Joey.\nNot Parachute.\n\n{PLAYER}, let's go! We're\noff to China!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  MOVE_OBJECT(0, 1, 0, 0)
  SET_FLAG(EVENT_FLAG_SAW_MOKUBA_GET_KIDNAPPED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBF4, map_22_state_08_08E8CBF4, 0x08E8CC00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Don't make me laugh,\n{PLAYER}!\n\nReshef the Dark Being... The\nend of the world...\n\nYou've been reading too many\nfantasy novels!\n\nYou guys do what you want!\n\nBut I'll get Mokuba back on\nmy own!\n\nAnd nobody is going to stop\nme!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
