#include "event_macros.h"
#include "overworld.h"

/* map_41_state_01: map 41 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08ED7BDC, map_41_state_01_08ED7BDC, 0x08ED7BE8, 0x08ED7BF4)
  PLAY_MUSIC(253)
  DELAY(16)
  SHOW_OBJECT(0, 58, 62, 0, 0, 0)
  WALK_OBJECT_Y(0, 50)
  DELAY(8)
  SHOW_OBJECT(13, 66, 62, 0, 0, 0)
  WALK_OBJECT_Y(13, 56)
  DELAY(8)
  SHOW_OBJECT(14, 50, 62, 0, 0, 0)
  WALK_OBJECT_Y(14, 56)
  DELAY(64)
  PLAY_MUSIC(255)
  SET_FLAG(246)
  DELAY(64)
  PLAY_MUSIC(272)
  REACTION(3, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SAD, 8)
  LANGUAGE_TEXT(0, "That Pegasus...\n\nWhat drove him to do this?\n\n")
  LANGUAGE_TEXT(1, "Ce Pegasus...\n\nQu'est-ce qui l'a\nconduit \xe0 faire \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Dieser Pegasus...\n\nWas hat ihn so weit\ngetrieben?\n\n")
  LANGUAGE_TEXT(3, "Quel Pegasus...\n\nCosa l'avr\xe0 spinto a farlo?\n\n")
  LANGUAGE_TEXT(4, "Ese Pegasus...\n\n\xbfQu\xe9 le llev\xf3 a hacer esto?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "{CARD_1}I don't know\nWe'll know if we go{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Je ne sais pas\nOn le saura si on y va{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ich wei\xdf es nicht\nDas werden wir herausfinden{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Non lo so\nLo sapremo andando da lui{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}No lo s\xe9\nLo sabremos si vamos{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7BE8, map_41_state_01_08ED7BE8, 0x08ED7C00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah, I'm with you,\n{PLAYER}.\n\nI have no clue what Pegasus\nis thinkin'.\n\nHe's one mad sicko, but...\n\n")
  LANGUAGE_TEXT(1, "Ouais, je suis comme\ntoi, {PLAYER}.\n\nJe n'ai aucune id\xe9e\n\nde ce qui motive\nPegasus.\n\nTu sais, c'est peut-\xeatre un\nclown path\xe9tique mais...\n\n")
  LANGUAGE_TEXT(2, "Ja, ich stehe dir bei,\n{PLAYER}.\n\nIch habe keine Ahnung, was\nsich Pegasus dabei denkt.\n\nAber auch wenn er\nverr\xfcckt ist...\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, nemmeno io,\n{PLAYER}.\n\nNon ho idea di cos'abbia\nin mente di fare Pegasus.\n\nMagari \xe8 solo un\npagliaccio stufo, ma...\n\n")
  LANGUAGE_TEXT(4, "S\xed, estoy contigo,\n{PLAYER}.\n\nNo tengo ni idea sobre\nlo que piensa Pegasus.\n\nPero, sabes, puede que \xe9l\nsea un payaso enfermo\n\npero...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C00, map_41_state_01_08ED7C00, 0x08ED7C0C, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 8193)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Pegasus was always a master\nduelist.\n\nNo one would argue with\nthat.\n\nEspecially since we faced\nhim firsthand.\n\nSo why would he resort to\neven dirtier tricks than\n\nbefore?\n\nI'm not the smartest guy on\nthe planet...\n\nBut I know that Pegasus\nisn't a real duelist\n\nanymore!\n\n")
  LANGUAGE_TEXT(1, "Pegasus a toujours \xe9t\xe9\nun duelliste hors-pair.\n\nPersonne ne dira\nle contraire.\n\nApr\xe8s tout, on a tous\nvoulu lui ressembler.\n\nAlors pourquoi\nferait-il cela ?\n\nJe ne suis pas le mec\nle plus intelligent\n\nde la plan\xe8te...\n\nMais je ne peux pas\npardonner Pegasus\n\nen tant que duelliste !\n\n")
  LANGUAGE_TEXT(2, "Pegasus war stets ein\nerstklassiger Duellant.\n\nDas leugnet niemand.\n\nJa, fr\xfcher wollten wir alle\nso sein wie er.\n\nWarum sollte er uns dann\nalle so entt\xe4uschen?\n\nIch bin ja nicht der\nCleverste...\n\nAber ich kann Pegasus als\nDuellant nicht verzeihen!\n\n")
  LANGUAGE_TEXT(3, "Pegasus \xe8 sempre stato\nun duellante di prima\n\ncategoria. Nessuno lo\nmetterebbe in dubbio.\n\nPer la miseria, tutti noi\ncercavamo di essere come\n\nlui, prima. Allora perch\xe9\navrebbe fatto qualcosa\n\nper disilluderci tutti? Non\nsar\xf2 il ragazzo pi\xf9\n\nintelligente del pianeta,\nma come duellante non\n\nriesco a perdonare Pegasus!\n\n")
  LANGUAGE_TEXT(4, "Pegasus siempre ha sido un\nduelista de primera.\n\nNadie lo pondr\xeda en duda.\n\nDemonios, todos intentamos\nser como \xe9l antes.\n\nAs\xed, \xbfpor qu\xe9 har\xeda \xe9l algo\nque nos desilusionara?\n\nNo soy el tipo m\xe1s\ninteligente del mundo...\n\n\xa1Pero no puedo aceptar a\nPegasus como duelista!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(258)
  PLAY_MUSIC(412)
  COMMAND_7C_ARG(7, 1)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  PLAY_MUSIC(259)
  SHOW_OBJECT(1, 40, 54, 0, 2, 0)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C0C, map_41_state_01_08ED7C0C, 0x08ED7C18, 0x08ED7CF0)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(2, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Gawry nida! Gawry nida!\n\nYou'll go no further! Gawry!\n\n")
  LANGUAGE_TEXT(1, "Grrrrrrr ah !\nGrrrrrrr ah !\n\nTu n'iras pas plus loin !\nAhhh !\n\n")
  LANGUAGE_TEXT(2, "Grrrrrr!\nGrrrrrr!\n\nKeinen Schritt weiter!\nGrrrr!\n\n")
  LANGUAGE_TEXT(3, "Uaaahhhhhh!\nUaaahhhhhh!\n\nNon andrete oltre!\nUaahhhh!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vas a ver!\n\xa1Vas a ver!\n\n\xa1No pasar\xe1s!\n\xa1Vas a ver!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Wha... Who are you?\n\n")
  LANGUAGE_TEXT(1, "Q... qui es-tu ?\n\n")
  LANGUAGE_TEXT(2, "Wha... Wer bist du?\n\n")
  LANGUAGE_TEXT(3, "Che... Tu chi sei?\n\n")
  LANGUAGE_TEXT(4, "\xbfEh?...\n\xbfQui\xe9n eres t\xfa?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I am one of many! Gawry!\n\nMaster Chevalsky turned us\ninto duelists! Gawry!\n\nWe no longer have no names!\nGawry nida!\n\nBut if you must call us\nsomething, call us the\n\nChevaliers!\n\nWe have pledged allegiance\nto Master Chevalsky!\n\n")
  LANGUAGE_TEXT(1, "Un parmi les autres !\nGrr !\n\nMa\xeetre Chevalsky a fait\nde nous des duellistes !\n\nNous n'avons pas\nde nom ! Grrrr ah !\n\nSi vous voulez nous donner\nun nom, appellez-nous\n\nles Chevaliers !\n\nNous avons pr\xeat\xe9 all\xe9geance\n\xe0 Ma\xeetre Chevalsky !\n\n")
  LANGUAGE_TEXT(2, "Ich bin einer von vielen!\nGrrrrr!\n\nMeister Chevalsky machte\nuns zu Duellanten! Grrrr!\n\nWir haben keine Namen!\nGrrrr!\n\nWenn ihr uns bei einem\nNamen nennen m\xfcsst,\n\ndann {BYTE_8168}die Chevaliers{BYTE_8168}!\n\nWir haben Meister Chevals-\nky die Treue geschworen!\n\n")
  LANGUAGE_TEXT(3, "Sono uno dei tanti!\nUaahhh!\n\nIl maestro Chevalsky\nci ha fatti diventare\n\nduellanti! Uaahhh!\nNon abbiamo nomi!\n\nUaahhhh! Se dovete\nchiamarci per nome,\n\nsiamo i Cavalieri! Abbiamo\ngiurato fedelt\xe0 al\n\nmaestro Chevalsky!\n\n")
  LANGUAGE_TEXT(4, "\xa1Soy uno de muchos!\n\xa1Vas a ver!\n\n\xa1Fuimos hechos duelistas por\nel amo Chevalsky! \xa1Grrrrr!\n\n\xa1No tenemos nombres!\n\xa1Vas a ver!\n\n\xa1Si hab\xe9is de llamarnos\nalgo, somos los Chevaliers!\n\n\xa1Hemos jurado lealtad al\namo Chevalsky!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "That Pegasus... He's really\nannoyin' me now!\n\n{PLAYER}, it's time to lay\ndown the law!\n\n")
  LANGUAGE_TEXT(1, "Ce Pegasus...\nIl a vraiment fait \xe7a !\n\n{PLAYER}, il est temps\nde passer au combat !\n\n")
  LANGUAGE_TEXT(2, "Dieser Pegasus... Jetzt\n\xfcbertreibt er aber\n\nwirklich!\n\n{PLAYER}, es ist Zeit,\nernsthaft anzugreifen!\n\n")
  LANGUAGE_TEXT(3, "Quel Pegasus...\nL'ha proprio fatta grossa!\n\n{PLAYER}, \xe8 ora di\npassare all'attacco!\n\n")
  LANGUAGE_TEXT(4, "Ese Pegasus...\n\xa1Ahora s\xed que la ha hecho!\n\n{PLAYER}, \xa1es hora de\npasar al ataque!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 50)
  WALK_OBJECT_X(1, 48)
  DELAY(16)
  PLAY_MUSIC(0)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C18, map_41_state_01_08ED7C18, 0x08ED7C24, 0x08F04040)
  PLAY_MUSIC(253)
  PLAY_MUSIC(257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "G-gawry nida... G-ga..\nn-niii.... urrri...\n\n")
  LANGUAGE_TEXT(1, "G-grrrr ahhh...\nG-ga... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(2, "G-grrrrrr...\nG-grr... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(3, "U-uaahhhh...\nU-uah... ahhh...\n\n")
  LANGUAGE_TEXT(4, "V-vas a ver...\nV-va... A aa... V-v-e..\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(282)
  OBJECT_EFFECT(2, 2)
  DELAY(32)
  PLAY_MUSIC(258)
  COMMAND_7C_ARG(7, 1)
  DELAY(16)
  PLAY_MUSIC(258)
  COMMAND_7C_ARG(7, 1)
  DELAY(8)
  PLAY_MUSIC(259)
  SHOW_OBJECT(2, 76, 42, 0, 2, 0)
  DELAY(8)
  PLAY_MUSIC(259)
  SHOW_OBJECT(3, 46, 36, 0, 2, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C24, map_41_state_01_08ED7C24, 0x08ED7C30, 0x08ED7CF0)
  DELAY(32)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(4, 1)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Gawry nida! Gawry nida!\n\nYou'll go no further! Gawry!\n\n")
  LANGUAGE_TEXT(1, "Grrrrrrr ah !\nGrrrrrrr ah !\n\nTu n'iras pas plus loin !\nAhhh !\n\n")
  LANGUAGE_TEXT(2, "Grrrrrr!\nGrrrrrr!\n\nKeinen Schritt weiter!\nGrrrr!\n\n")
  LANGUAGE_TEXT(3, "Uaaahhhhhh!\nUaaahhhhhh!\n\nNon andrete oltre!\nUaahhhh!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vas a ver!\n\xa1Vas a ver!\n\n\xa1No pasar\xe1s!\n\xa1Vas a ver!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 50)
  WALK_OBJECT_X(2, 68)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(16)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C30, map_41_state_01_08ED7C30, 0x08ED7C3C, 0x08F04040)
  PLAY_MUSIC(253)
  PLAY_MUSIC(257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "G-gawry nida... G-ga..\nn-niii.... urrri...\n\n")
  LANGUAGE_TEXT(1, "G-grrrr ahhh...\nG-ga... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(2, "G-grrrrrr...\nG-grr... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(3, "U-uaahhhh...\nU-uah... ahhh...\n\n")
  LANGUAGE_TEXT(4, "V-vas a ver...\nV-va... A aa... V-v-e..\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(282)
  OBJECT_EFFECT(4, 2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C3C, map_41_state_01_08ED7C3C, 0x08ED7C48, 0x08ED7CF0)
  DELAY(32)
  PLAY_MUSIC(260)
  OBJECT_EFFECT(8, 1)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Gawry nida! Gawry nida!\n\nYou'll go no further! Gawry!\n\n")
  LANGUAGE_TEXT(1, "Grrrrrrr ah !\nGrrrrrrr ah !\n\nTu n'iras pas plus loin !\nAhhh !\n\n")
  LANGUAGE_TEXT(2, "Grrrrrr!\nGrrrrrr!\n\nKeinen Schritt weiter!\nGrrrr!\n\n")
  LANGUAGE_TEXT(3, "Uaaahhhhhh!\nUaaahhhhhh!\n\nNon andrete oltre!\nUaahhhh!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vas a ver!\n\xa1Vas a ver!\n\n\xa1No pasar\xe1s!\n\xa1Vas a ver!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 58)
  WALK_OBJECT_Y(3, 42)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  DUEL(105)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7C48, map_41_state_01_08ED7C48, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(253)
  PLAY_MUSIC(257)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "G-gawry nida... G-ga..\nn-niii.... urrri...\n\n")
  LANGUAGE_TEXT(1, "G-grrrr ahhh...\nG-ga... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(2, "G-grrrrrr...\nG-grr... n-niii... urrri...\n\n")
  LANGUAGE_TEXT(3, "U-uaahhhh...\nU-uah... ahhh...\n\n")
  LANGUAGE_TEXT(4, "V-vas a ver...\nV-va... A aa... V-v-e..\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(282)
  OBJECT_EFFECT(8, 2)
  DELAY(64)
  PLAY_MUSIC(256)
  CLEAR_FLAG(246)
  DELAY(96)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Looks like it's stopped.\n\n")
  LANGUAGE_TEXT(1, "On dirait que\n\xe7a s'est arr\xeat\xe9.\n\n")
  LANGUAGE_TEXT(2, "Es hat anscheinend\naufgeh\xf6rt.\n\n")
  LANGUAGE_TEXT(3, "Pare che si sia fermata.\n\n")
  LANGUAGE_TEXT(4, "Parece que ha parado.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Let's keep going, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Continuons \xe0 bouger,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Gehen wir weiter, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Proseguiamo, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Sigamos, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(13, 62)
  SHOW_OBJECT(13, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_Y(14, 62)
  SHOW_OBJECT(14, 128, 96, 0, 0, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 62)
  SHOW_OBJECT(0, 128, 96, 0, 0, 0)
  FADE_SCREEN(1)
  CLEAR_FLAG(180)
  SET_FLAG(164)
  WARP(42, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7CF0, map_41_state_01_08ED7CF0, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(180)
  CLEAR_FLAG(246)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08ED7BF4, map_41_state_01_08ED7BF4, 0x08ED7C00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "And ask him personally?\n\nI don't know much about\nsavin' the world, but I\n\nwanna know why Pegasus lost\nhis pride as a true\n\nduelist.\n\n")
  LANGUAGE_TEXT(1, "Et lui demander ?\n\nNon, ce que je ne\ncomprends pas,\n\nce n'est pas \xe7a,\npas sur cette crise.\n\nJe veux savoir\npourquoi Pegasus\n\na perdu sa fiert\xe9\nen tant que duelliste.\n\n")
  LANGUAGE_TEXT(2, "Ihn fragen?\n\nNein, das ist nicht das,\nwas ich nicht verstehe.\n\nEs geht nicht um diese\nKrise.\n\nIch will mehr \xfcber\nPegasus' Stolz erfahren.\n\nIch will wissen, warum er\nseinen Duellantenstolz\n\nverloren hat.\n\n")
  LANGUAGE_TEXT(3, "Cos\xec glielo chiediamo?\n\nNo, ci\xf2 che non capisco\nnon \xe8 affatto questo.\n\nNon ha a che vedere con\nquesta situazione. Voglio\n\nsapere che fine ha fatto\nl'orgoglio di Pegasus.\n\nVoglio sapere come\nmai ha perso l'orgoglio\n\ndi duellante.\n\n")
  LANGUAGE_TEXT(4, "\xbfY preguntarle?\n\nNo, lo que no entiendo no\nes eso en absoluto.\n\nNo es sobre esta\ncrisis.\n\nQuiero saber sobre\nel orgullo de Pegasus.\n\nQuiero saber por qu\xe9\nperdi\xf3 su orgullo\n\ncomo duelista.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
