#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_37_state_06: map 37 state 6 */

#define LOCALID_MAKO             1
#define LOCALID_MONKEY_ROBOT_1   2
#define LOCALID_MONKEY_ROBOT_2   3
#define LOCALID_MONKEY_ROBOT_3   4
#define LOCALID_MONKEY_ROBOT_4   5

LOAD_SPRITE(LOCALID_MAKO, SPRITE_MAKO)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_1, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_2, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_3, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(LOCALID_MONKEY_ROBOT_4, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(6, SPRITE_FISH_1)
LOAD_SPRITE(7, SPRITE_FISH_2)
LOAD_SPRITE(8, SPRITE_FISH_3)
LOAD_SPRITE(9, SPRITE_FISH_4)
PLAY_MUSIC(MUSIC_MONKEY_ROBOTS)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_MAKO)
DELAY(8)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_UP, 0, 0)
DELAY(8)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT,
    "Hey! Wait! Wait up!\n\n"
)
PLAY_MUSIC(MUSIC_326)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukki! Ukikki!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
SHOW_OBJECT(SPRITE_FISH_1, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_FISH_2, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_FISH_3, 128, 96, 0, 0, 0)
SHOW_OBJECT(SPRITE_FISH_4, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_1, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_1, 1, 42)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_1, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_2, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_2, 1, 42)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_2, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_3, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_3, 2, 40)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_3, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_4, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_4, 2, 56)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_4, 128, 96, 0, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_UP, 8, 0)
DELAY(32)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT,
    "Tsk, these annoying little\n"
    "monkeys...\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 0, 0)
DELAY(32)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT,
    "Oh well. I'll just catch\n"
    "more fish.\n\n"
    "The sea is plentiful with\n"
    "her bounty.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_MAKO)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "...The sea isn't screaming\n"
    "anymore...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_273)
REACTION(REACTION_LOVE_HEART, SPRITE_MAKO)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT,
    "Those guys... They did it.\n\n"
    "But I can't let them become\n"
    "better duelists than me!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_MAKO, 96)
PLAY_MUSIC(MUSIC_93)
FADE_SCREEN(4)
PLAY_MUSIC(MUSIC_94)
WALK_OBJECT_Y(SPRITE_MAKO, 64)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT,
    "Gahahahaha!\n\n"
    "What a haul! What a catch!\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(SPRITE_FISH_1, 50, 48, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(SPRITE_FISH_3, 62, 48, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(SPRITE_FISH_2, 50, 56, 0, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_364)
SHOW_OBJECT(SPRITE_FISH_4, 62, 56, 0, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_1, DIRECTION_RIGHT, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_1, 8, 48, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_2, DIRECTION_RIGHT, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_2, 8, 56, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_3, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_3, 62, 8, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_363)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_4, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_4, 70, 8, 0, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 8, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_1, 3, 34)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_2, 3, 34)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_3, 0, 32)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_4, 0, 48)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_4, DIRECTION_LEFT, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_275)
REACTION(REACTION_ANGRY, SPRITE_MAKO)
DELAY(8)
SLIDE_OBJECT(SPRITE_MAKO, 2, 8)
DELAY(8)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_SWEATDROP, PORTRAIT_RIGHT,
    "You guys! You're asking for\n"
    "it now!\n\n"
)
PLAY_MUSIC(MUSIC_324)
TALK(PORTRAIT_ROBOT_MOkNEY, 6, PORTRAIT_RIGHT,
    "Ukiiiii!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_1, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_1, 1, 42)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_1, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_2, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_2, 1, 42)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_2, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_3, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_3, 2, 40)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_3, 128, 96, 0, 0, 0)
MOVE_OBJECT(LOCALID_MONKEY_ROBOT_4, DIRECTION_UP, 0, 0)
PLAY_MUSIC(MUSIC_362)
SLIDE_OBJECT(LOCALID_MONKEY_ROBOT_4, 2, 56)
SHOW_OBJECT(LOCALID_MONKEY_ROBOT_4, 128, 96, 0, 0, 0)
FADE_SCREEN(8)
WARP(LOCATION_GALAPAGOS_FOREST, 6, 0, 0)
