#include "event_macros.h"
#include "overworld.h"

/* map_16_state_03: map 16 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E7DEDC, map_16_state_03_08E7DEDC, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Thank you for riding with\nus.\n\n")
  LANGUAGE_TEXT(1, "Merci d'avoir voyag\xe9\navec nous.\n\n")
  LANGUAGE_TEXT(2, "Danke, dass sie mit uns\ngefahren sind.\n\n")
  LANGUAGE_TEXT(3, "Grazie per avere\nviaggiato con noi.\n\n")
  LANGUAGE_TEXT(4, "Gracias por venir\ncon nosotros.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF78, map_16_state_03_08E7DF78, 0x08E7DF84, 0x08E7DFA8)
  CHECK_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF84, map_16_state_03_08E7DF84, 0x08E7DF90, 0x08E7DF9C)
  CHECK_FLAG(EVENT_FLAG_LEAVING_THE_DUEL_EXPRESS_LEADS_TO_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF90, map_16_state_03_08E7DF90, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Thank you for riding with\nus.\n\n")
  LANGUAGE_TEXT(1, "Merci d'avoir voyag\xe9\navec nous.\n\n")
  LANGUAGE_TEXT(2, "Danke, dass sie mit uns\ngefahren sind.\n\n")
  LANGUAGE_TEXT(3, "Grazie per avere\nviaggiato con noi.\n\n")
  LANGUAGE_TEXT(4, "Gracias por venir\ncon nosotros.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF9C, map_16_state_03_08E7DF9C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "If you try to duel me, the\ntrain will depart.\n\nPlease be aware of that.\n\n")
  LANGUAGE_TEXT(1, "Si tu veux te battre\nen duel contre moi,\n\nrappelle-toi que\nle train va partir.\n\n")
  LANGUAGE_TEXT(2, "Wenn du dich mit mir duel-\nlierst, f\xe4hrt der Zug ab.\n\nDenk daran.\n\n")
  LANGUAGE_TEXT(3, "Sappi che se provi a\nduellare con me,\n\nil treno partir\xe0.\n\n")
  LANGUAGE_TEXT(4, "Si tratas de luchar\nconmigo, el tren saldr\xe1.\n\nTenlo en cuenta.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DFA8, map_16_state_03_08E7DFA8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "If you try to duel me, the\ntrain will arrive.\n\nPlease be aware of that.\n\n")
  LANGUAGE_TEXT(1, "Si tu veux te battre\nen duel contre moi,\n\nrappelle-toi que\nle train va arriver.\n\n")
  LANGUAGE_TEXT(2, "Wenn du dich mit mir duel-\nlierst, f\xe4hrt der Zug ein.\n\nDenke daran.\n\n")
  LANGUAGE_TEXT(3, "Sappi che se provi a\nduellare con me,\n\nil treno arriver\xe0.\n\n")
  LANGUAGE_TEXT(4, "Si tratas de luchar\nconmigo, el tren llegar\xe1.\n\nTenlo en cuenta.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEE8, map_16_state_03_08E7DEE8, 0x08E7DEF4, 0x08E7DF18)
  CHECK_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DEF4, map_16_state_03_08E7DEF4, 0x08E7DF00, 0x08E7DF0C)
  CHECK_FLAG(EVENT_FLAG_LEAVING_THE_DUEL_EXPRESS_LEADS_TO_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF00, map_16_state_03_08E7DF00, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Thank you for riding with\nus.\n\n")
  LANGUAGE_TEXT(1, "Merci d'avoir voyag\xe9\navec nous.\n\n")
  LANGUAGE_TEXT(2, "Danke, dass sie mit uns\ngefahren sind.\n\n")
  LANGUAGE_TEXT(3, "Grazie per avere\nviaggiato con noi.\n\n")
  LANGUAGE_TEXT(4, "Gracias por venir\ncon nosotros.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF0C, map_16_state_03_08E7DF0C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Our departure time has\narrived.\n\n")
  LANGUAGE_TEXT(1, "Le train va maintenant\npartir.\n\n")
  LANGUAGE_TEXT(2, "Der Zug f\xe4hrt ab.\nAlle einsteigen, bitte!\n\n")
  LANGUAGE_TEXT(3, "\xc8 ora di partire.\nTutti a bordo!\n\n")
  LANGUAGE_TEXT(4, "Es hora de partir.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(4, 108)
  MOVE_OBJECT(4, 1, 0, 0)
  LANGUAGE_TEXT(0, "All aboard!\n\n")
  LANGUAGE_TEXT(1, "En voiture !\n\n")
  LANGUAGE_TEXT(2, "Die n\xe4chste und einzige\n\n")
  LANGUAGE_TEXT(3, "La prossima e unica\n\n")
  LANGUAGE_TEXT(4, "\xa1Todos a bordo!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(234)
  SET_FLAG(EVENT_FLAG_SHAKE_SCREEN)
  LANGUAGE_TEXT(0, "The next and only stop is\nthe Egypt Exhibition!\n\n")
  LANGUAGE_TEXT(1, "Prochain et dernier arr\xeat,\nl'Exposition \xe9gyptienne !\n\n")
  LANGUAGE_TEXT(2, "Haltestelle ist die\n\xe4gypt. Ausstellung!\n\n")
  LANGUAGE_TEXT(3, "fermata \xe8 la Mostra Egizia!\n\n")
  LANGUAGE_TEXT(4, "La pr\xf3xima y \xfanica parada es\nla Exposici\xf3n Egipcia.\n\n")
  END_LANGUAGE_TEXT()
  MOVE_OBJECT(1, 2, 8, 0)
  MOVE_OBJECT(1, 3, 24, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  SET_MAP_MUSIC(234)
  SET_FLAG(EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF18, map_16_state_03_08E7DF18, 0x08E7DF24, 0x08F04040)
  LANGUAGE_TEXT(0, "We will be arriving very\nshortly.\n\n")
  LANGUAGE_TEXT(1, "Nous allons\nbient\xf4t arriver.\n\n")
  LANGUAGE_TEXT(2, "In K\xfcrze werden wir unser\nZiel erreichen.\n\n")
  LANGUAGE_TEXT(3, "Stiamo per arrivare\na destinazione.\n\n")
  LANGUAGE_TEXT(4, "Llegaremos muy pronto.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(4, 88)
  MOVE_OBJECT(4, 0, 0, 0)
  PLAY_MUSIC(0)
  PLAY_MUSIC(235)
  CLEAR_FLAG(247)
  LANGUAGE_TEXT(0, "Egypt Exhibition! Egypt\nExhibition!\n\nPlease make sure to take all\nyour belongings with you.\n\n")
  LANGUAGE_TEXT(1, "Exposition \xe9gyptienne !\nExposition \xe9gyptienne !\n\nVeuillez vous assurez que\nvous n'avez rien oubli\xe9\n\navant de descendre\ndu train.\n\n")
  LANGUAGE_TEXT(2, "Die \xe4gypt. Ausstellung!\n\xc4gypt. Ausstellung!\n\nBitte lassen Sie nichts im\nZug zur\xfcck.\n\n")
  LANGUAGE_TEXT(3, "Mostra Egizia!\nMostra Egizia!\n\nNon dimenticate oggetti\na bordo.\n\n")
  LANGUAGE_TEXT(4, "\xa1Exposici\xf3n Egipcia!\n\xa1Exposici\xf3n Egipcia!\n\nAseg\xfarense de coger\nsus pertenencias.\n\n")
  END_LANGUAGE_TEXT()
  SET_MAP_MUSIC(232)
  CLEAR_FLAG(245)
  CLEAR_FLAG(244)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF24, map_16_state_03_08E7DF24, 0x08E7DF48, 0x08E7DF30)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_PANIK)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF48, map_16_state_03_08E7DF48, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  WARP(20, 0, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF30, map_16_state_03_08E7DF30, 0x08E7DF54, 0x08E7DF3C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF54, map_16_state_03_08E7DF54, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  WARP(20, 1, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF3C, map_16_state_03_08E7DF3C, 0x08E7DF60, 0x08E7DF6C)
  CHECK_FLAG(EVENT_FLAG_SAW_MOKUBA_GET_KIDNAPPED)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF60, map_16_state_03_08E7DF60, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  WARP(20, 2, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E7DF6C, map_16_state_03_08E7DF6C, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  WARP(20, 5, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
