#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_34_state_02: map 34 state 2 */

#define LOCALID_SERIOUS_ARCH     1
#define LOCALID_CHIEF_ARCH       2
#define LOCALID_FRIVOLOUS_ARCH   3
#define LOCALID_NEO_GHOUL_1      4
#define LOCALID_NEO_GHOUL_2      5

LOAD_SPRITE(LOCALID_SERIOUS_ARCH, SPRITE_SERIOUS_ARCHEOLOGIST)
LOAD_SPRITE(LOCALID_CHIEF_ARCH, SPRITE_CHIEF_ARCHEOLOGIST)
LOAD_SPRITE(LOCALID_FRIVOLOUS_ARCH, SPRITE_FRIVOULOUS_ARCHEOLOGIST)
LOAD_SPRITE(LOCALID_NEO_GHOUL_1, SPRITE_NEO_GHOUL)
LOAD_SPRITE(LOCALID_NEO_GHOUL_2, SPRITE_NEO_GHOUL)
PLAY_MUSIC(MUSIC_NEO_GHOULS)
DELAY(16)
WALK_OBJECT_X(LOCALID_NEO_GHOUL_1, 88)
DELAY(16)
TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "There's a duelist here,\n"
    "I know it!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_X(LOCALID_NEO_GHOUL_2, 88)
DELAY(16)
TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You better not cross the Neo\n"
    "Ghouls or we'll punish you\n\n"
    "hard!\n\n"
    "Be a good boy and tell us!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_SERIOUS_ARCHEOLOGIST, OBJECT_EFFECT_JUMPING)
WALK_OBJECT_X(SPRITE_SERIOUS_ARCHEOLOGIST, 78)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_RIGHT, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_UP, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_DOWN, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_SERIOUS_ARCHEOLOGIST, DIRECTION_RIGHT, 0, 0)
DELAY(32)
TEXT
(
    "H-he's in the cave...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(LOCALID_NEO_GHOUL_1, DIRECTION_DOWN, 0, 0)
DELAY(4)
MOVE_OBJECT(LOCALID_NEO_GHOUL_2, DIRECTION_UP, 0, 0)
DELAY(32)
WALK_OBJECT_X(LOCALID_NEO_GHOUL_1, 106)
WALK_OBJECT_Y(LOCALID_NEO_GHOUL_1, 32)
SET_OBJECT_POSITION(LOCALID_NEO_GHOUL_1, 128, 96, 0)
WALK_OBJECT_X(LOCALID_NEO_GHOUL_2, 106)
WALK_OBJECT_Y(LOCALID_NEO_GHOUL_2, 32)
SET_OBJECT_POSITION(LOCALID_NEO_GHOUL_2, 128, 96, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_CHIEF_ARCHEOLOGIST, DIRECTION_RIGHT, 0, 0)
DELAY(16)
SET_FLAG(EVENT_FLAG_SAW_NEO_GHOULS_ENTER_CANADA_CAVE)

EVENT_SCRIPT_REPLACEMENT(0x08EC2614, map_34_state_02_08EC2614, 0x08F04040, 0x08F04040)
TEXT
  (
      "I can't believe the Neo\n"
      "Ghouls are here, eh?\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2620, map_34_state_02_08EC2620, 0x08F04040, 0x08F04040)
TEXT
  (
      "I'm in no mood for dueling,\n"
      "buddy.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC262C, map_34_state_02_08EC262C, 0x08F04040, 0x08F04040)
TEXT
  (
      "I hope the duelist in the\n"
      "cave's all right, eh?\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2638, map_34_state_02_08EC2638, 0x08F04040, 0x08F04040)
TEXT
  (
      "I'm no duelist, buddy.\n"
      "So I don't duel.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2644, map_34_state_02_08EC2644, 0x08F04040, 0x08F04040)
TEXT
  (
      "What do you suppose brought\n"
      "the Neo Ghouls out here?\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EC2650, map_34_state_02_08EC2650, 0x08F04040, 0x08F04040)
TEXT
  (
      "Sorry, pal, I dedicated my\n"
      "life to fossils.\n\n"
      "No more dueling for me.\n\n"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
