#include "event_macros.h"
#include "overworld.h"

/* map_57_state_01: map 57 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EFB3F0, map_57_state_01_08EFB3F0, 0x08EFB3FC, 0x08F04040)
  PLAY_MUSIC(13)
  WALK_OBJECT_X(14, 22)
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 16384)
  WALK_OBJECT_X(13, 14)
  WALK_OBJECT_X(0, 6)
  DELAY(16)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(64)
  WALK_OBJECT_Y(13, 63)
  WALK_OBJECT_X(13, 10)
  PLAY_MUSIC(366)
  MOVE_OBJECT(13, 3, 0, 0)
  WALK_OBJECT_X(14, 14)
  WALK_OBJECT_Y(14, 57)
  WALK_OBJECT_X(14, 9)
  PLAY_MUSIC(366)
  MOVE_OBJECT(14, 3, 0, 0)
  WALK_OBJECT_X(0, 14)
  WALK_OBJECT_Y(0, 50)
  WALK_OBJECT_X(0, 9)
  PLAY_MUSIC(366)
  MOVE_OBJECT(0, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFB3FC, map_57_state_01_08EFB3FC, 0x08EFB408, 0x08EFB414)
  DELAY(64)
  WALK_OBJECT_Y(2, 42)
  WALK_OBJECT_X(2, 68)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hey! Good to see such a\ngreat crowd!\n\nNow on with the show here at\nKaiba Land!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 ! Content de\nvous voir tous ici !\n\nCommen\xe7ons le\nspectacle Kaibaland !\n\n")
  LANGUAGE_TEXT(2, "He! Sch\xf6n, euch alle hier\nzu sehen!\n\nDie Kaibaland Show m\xf6ge\nbeginnen!\n\n")
  LANGUAGE_TEXT(3, "Ehi! Ma che bello\nvedervi tutti qui!\n\nProcediamo con il\nKaibaland Show!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hey! \xa1Qu\xe9 bien veros\na todos por aqu\xed!\n\n\xa1Empecemos con el show\nde la Tierra de Kaiba!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 74)
  WALK_OBJECT_Y(2, 68)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(32)
  LANGUAGE_TEXT(0, "Kiyaaaaah! Help!\n\n")
  LANGUAGE_TEXT(1, "Kiyaaaaah !\nAu secours !\n\n")
  LANGUAGE_TEXT(2, "Kiyaaaaah! Hilfe!\n\n")
  LANGUAGE_TEXT(3, "Kiyaaaaaah! Aiuto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kiyaaaaah! \xa1Ayuda!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(3, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(3, 88)
  WALK_OBJECT_Y(3, 14)
  DELAY(16)
  MOVE_OBJECT(3, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(3, 3, 0, 0)
  DELAY(16)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SAD, 0)
  LANGUAGE_TEXT(0, "Help me! Please, someone\nhelp!\n\n")
  LANGUAGE_TEXT(1, "A l'aide !\nQuelqu'un ! Aidez-moi !\n\n")
  LANGUAGE_TEXT(2, "Hilfe!\nSo hilf mir doch jemand!\n\n")
  LANGUAGE_TEXT(3, "Aiuto! Qualcuno mi aiuti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ayudadme!\nPor favor, \xa1ayuda!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  SHOW_OBJECT(4, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(4, 76)
  WALK_OBJECT_Y(4, 38)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(292)
  PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Behold Deepsea Warrior!\n\n")
  LANGUAGE_TEXT(1, "Et voici le Guerrier\ndes profondeurs marines !\n\n")
  LANGUAGE_TEXT(2, "Achtung, der Tiefseekrieger!\n\n")
  LANGUAGE_TEXT(3, "Guardate il Guerriero\ndegli Abissi!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mirad al Guerrero de las\nprofundidades marinas!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 0, 0, 0)
  SHOW_OBJECT(5, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(5, 82)
  WALK_OBJECT_Y(5, 28)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(292)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I'm Nightmare Penguin!\n\n")
  LANGUAGE_TEXT(1, "Et moi je suis le\nNightmare Penguin !\n\n")
  LANGUAGE_TEXT(2, "Nightmare Penguin ist\nmein Name!\n\n")
  LANGUAGE_TEXT(3, "Io sono il Nightmare\nPenguin!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo soy el Nightmare\nPenguin!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(6, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(6, 100)
  WALK_OBJECT_Y(6, 38)
  MOVE_OBJECT(6, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(292)
  PORTRAIT(PORTRAIT_JUDGE_MAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I am Judge Man!\n\n")
  LANGUAGE_TEXT(1, "Moi, je suis le Juge !\n\n")
  LANGUAGE_TEXT(2, "Ich bin der Vollstrecker!\n\n")
  LANGUAGE_TEXT(3, "Io sono il Giudicatore!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo soy El Juez!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(7, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(7, 94)
  WALK_OBJECT_Y(7, 28)
  MOVE_OBJECT(7, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(292)
  PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Robotic Knight, at your\nservice!\n\n")
  LANGUAGE_TEXT(1, "Robotic Knight,\n\xe0 votre service !\n\n")
  LANGUAGE_TEXT(2, "Robotic Knight zu euren\nDiensten!\n\n")
  LANGUAGE_TEXT(3, "Robotic Knight al\nvostro servizio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Robotic Knight a\nvuestro servicio!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(8, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(8, 88)
  WALK_OBJECT_Y(8, 38)
  MOVE_OBJECT(8, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(292)
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "And I am Jinzo!\n\n")
  LANGUAGE_TEXT(1, "Et moi, je suis Jinzo !\n\n")
  LANGUAGE_TEXT(2, "Und ich bin Jinzo!\n\n")
  LANGUAGE_TEXT(3, "E io sono Jinzo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Y yo soy Jinzo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 2, 0, 0)
  MOVE_OBJECT(5, 2, 0, 0)
  MOVE_OBJECT(6, 2, 0, 0)
  MOVE_OBJECT(7, 2, 0, 0)
  MOVE_OBJECT(8, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You will not elude us again,\nyou brat!\n\n")
  LANGUAGE_TEXT(1, "Petit imb\xe9cile, cette fois,\ntu ne vas pas nous\n\n\xe9chapper.\n\n")
  LANGUAGE_TEXT(2, "Du Kr\xf6te entkommst uns\nnicht noch einmal.\n\n")
  LANGUAGE_TEXT(3, "E tu, monella, non\nci sfuggirai di nuovo.\n\n")
  LANGUAGE_TEXT(4, "T\xfa, mocoso, no nos\neludir\xe1s de nuevo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 2, 2, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 0)
  LANGUAGE_TEXT(0, "Y-you're the evil criminal\nsyndicate...\n\nThe Big Bad Five!\n\n")
  LANGUAGE_TEXT(1, "C'est vous, le syndicat\ndu crime organis\xe9...\n\nLes Cinq Grands M\xe9chants !\n\n")
  LANGUAGE_TEXT(2, "Ihr seid die Mafia im\nUntergrund...\n\nDie Big Five!\n\n")
  LANGUAGE_TEXT(3, "V-voi siete l'agenzia\ncriminale segreta...\n\nI Temibili Cinque!\n\n")
  LANGUAGE_TEXT(4, "S-sois la organizaci\xf3n\ncriminal clandestina...\n\n\xa1Los Cinco Malvados!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 0)
  LANGUAGE_TEXT(0, "Oh my gosh, everyone!\nThey've captured the girl!\n\n")
  LANGUAGE_TEXT(1, "Oh l\xe0 l\xe0, tout le monde !\nIls ont kidnapp\xe9 la fille !\n\n")
  LANGUAGE_TEXT(2, "Oh mein Gott!\nSie haben das M\xe4dchen!\n\n")
  LANGUAGE_TEXT(3, "Oddio! Hanno\npreso la ragazzina!\n\n")
  LANGUAGE_TEXT(4, "Madre m\xeda, \xa1todos vosotros!\n\xa1Han cogido a la chica!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "We are the strongest evil\nduelists in the world!\n\n")
  LANGUAGE_TEXT(1, "Nous sommes les meilleurs\nduellistes des t\xe9n\xe8bres !\n\n")
  LANGUAGE_TEXT(2, "Wir sind die allerbesten\ndunklen Duellanten!\n\n")
  LANGUAGE_TEXT(3, "Siamo il fior fiore dei\nduellanti oscuri!\n\n")
  LANGUAGE_TEXT(4, "\xa1Somos los mejores de los\nmejores duelistas oscuros!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "My calculations state that\nno duelist has the power...\n\n")
  LANGUAGE_TEXT(1, "Aucun duelliste\nn'est assez puissant...\n\n")
  LANGUAGE_TEXT(2, "Kein Duellant hat die\nMacht...\n\n")
  LANGUAGE_TEXT(3, "Nessun duellante ha\nil potere...\n\n")
  LANGUAGE_TEXT(4, "Ning\xfan duelista\ntiene el poder...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(6, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JUDGE_MAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "...To make us cower!\n\n")
  LANGUAGE_TEXT(1, "... pour nous\nimpressionner !\n\n")
  LANGUAGE_TEXT(2, "... uns einzusch\xfcchtern!\n\n")
  LANGUAGE_TEXT(3, "... Di spaventarci!\n\n")
  LANGUAGE_TEXT(4, "... \xa1De amedrentarnos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(7, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "If anyone dares challenge\nour might...\n\n")
  LANGUAGE_TEXT(1, "Si quelqu'un ose d\xe9fier\nnotre puissance...\n\n")
  LANGUAGE_TEXT(2, "Wer es wagt, unsere Macht\nzu hinterfragen...\n\n")
  LANGUAGE_TEXT(3, "Se qualcuno osa sfidare\nla nostra potenza...\n\n")
  LANGUAGE_TEXT(4, "Si alguien se atreve\na retar nuestra fuerza...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "...We'll crush them without\na fight!\n\n")
  LANGUAGE_TEXT(1, "... nous le r\xe9duirons\nen bouillie sans plus\n\nattendre !\n\n")
  LANGUAGE_TEXT(2, "... wird kampflos\nvernichtet!\n\n")
  LANGUAGE_TEXT(3, "... Noi lo schiacceremo\nsenza neanche combattere!\n\n")
  LANGUAGE_TEXT(4, "... \xa1Acabaremos con \xe9l\nsin luchar siquiera!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "WAHAHAHAHAHA!\n\n")
  LANGUAGE_TEXT(1, "WOUAH AH AH AH !\n\n")
  LANGUAGE_TEXT(2, "WAHAHAHAHAHA!\n\n")
  LANGUAGE_TEXT(3, "UAHAHAHAHAHAH!\n\n")
  LANGUAGE_TEXT(4, "\xa1WAJAJAJAJA!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The Big Bad Five have issued\na challenge!\n\nIs there a duelist brave\nenough to face them?\n\n")
  LANGUAGE_TEXT(1, "Les Cinq Grands M\xe9chants\nont lanc\xe9 un d\xe9fi !\n\nY-a-t-il un duelliste\nassez courageux\n\npour le relever ?\n\n")
  LANGUAGE_TEXT(2, "Die Big Five fordern\nuns heraus!\n\nIst denn kein Duellant\ntapfer genug, um es mit\n\nihnen aufzunehmen?\n\n")
  LANGUAGE_TEXT(3, "I Temibili Cinque hanno\nlanciato una sfida! Non c'\xe8\n\nun duellante abbastanza\ncoraggioso da accettarla?\n\n")
  LANGUAGE_TEXT(4, "\xa1Los Cinco Malvados\nlanzan un reto!\n\n\xbfNo hay un duelista\nlo suficientemente\n\nvaliente como para\nrecoger el guante?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(512, 1)
  LANGUAGE_TEXT(0, "I'm scared!\n\n")
  LANGUAGE_TEXT(1, "J'ai peur !\n\n")
  LANGUAGE_TEXT(2, "Ich habe Angst!\n\n")
  LANGUAGE_TEXT(3, "Io ho paura!\n\n")
  LANGUAGE_TEXT(4, "\xa1Tengo miedo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(1024, 1)
  LANGUAGE_TEXT(0, "I can't beat the Big Bad\nFive!\n\n")
  LANGUAGE_TEXT(1, "Je n'arriverais\njamais \xe0 battre\n\nles Cinq Grands M\xe9chants !\n\n")
  LANGUAGE_TEXT(2, "Ich kann die Big Five\nnicht besiegen!\n\n")
  LANGUAGE_TEXT(3, "Io non posso battere i\nTemibili Cinque!\n\n")
  LANGUAGE_TEXT(4, "\xa1No puedo con los\nCinco Malvados!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Serenity's in trouble!\n\n")
  LANGUAGE_TEXT(1, "Serenity est en difficult\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Serenity ist in Gefahr!\n\n")
  LANGUAGE_TEXT(3, "Serenity \xe8 nei guai!\n\n")
  LANGUAGE_TEXT(4, "\xa1Serenity est\xe1 en apuros!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, let's get 'em!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, affrontons-les !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, schnappen\nwir sie uns!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, facciamogliela\nvedere!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xa1luchemos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  DELAY(8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFB408, map_57_state_01_08EFB408, 0x08EFB420, 0x08F0404C)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah! You da man!\n\n")
  LANGUAGE_TEXT(1, "Ouais ! T'es\nvraiment sympa !\n\n")
  LANGUAGE_TEXT(2, "Prima! Du bist unser Mann!\n\n")
  LANGUAGE_TEXT(3, "Tu s\xec che hai del fegato!\n\n")
  LANGUAGE_TEXT(4, "\xa1S\xed! \xa1T\xfa eres el hombre!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(14, 14)
  WALK_OBJECT_Y(14, 40)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(14, 3, 2, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Big Bad Five! You're in\ntrouble now!\n\n")
  LANGUAGE_TEXT(1, "Les Cinq Grands M\xe9chants !\n\nFaites vos\nderni\xe8res pri\xe8res !\n\n")
  LANGUAGE_TEXT(2, "Big Five! Macht\neuch auf etwas gefasst!\n\n")
  LANGUAGE_TEXT(3, "I Temibili Cinque!\nOra avete uno sfidante!\n\n")
  LANGUAGE_TEXT(4, "\xa1Los Cinco Malvados!\n\xa1Acepto el reto!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "Joey... He's really into\nthis show, isn't he?\n\n")
  LANGUAGE_TEXT(1, "Joey...\nIl est en plein dedans.\n\n")
  LANGUAGE_TEXT(2, "Joey...\nEr ist richtig begeistert.\n\n")
  LANGUAGE_TEXT(3, "Joey...\nC'\xe8 dentro fino al collo.\n\n")
  LANGUAGE_TEXT(4, "Joey...\nEst\xe1 en ello.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You want to duel, kid?\n\n")
  LANGUAGE_TEXT(1, "Tu vas te battre\nen duel, d\xe9butant ?\n\n")
  LANGUAGE_TEXT(2, "Du willst dich duellieren,\ndu kleine Kr\xf6te?\n\n")
  LANGUAGE_TEXT(3, "E tu vorresti duellare?\n\n")
  LANGUAGE_TEXT(4, "\xbfT\xfa vas a luchar,\nbasura?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "{PLAYER} will crush you ta\npieces!\n\nSerenity, come over here!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} va t'\xe9craser !\nSerenity, viens ici !\n\n")
  LANGUAGE_TEXT(2, "{PLAYER} wird dich in den\nErdboden stampfen!\n\nSerenity, komm her!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER} ti\nfar\xe0 a pezzi!\n\nSerenity, vieni qui!\n\n")
  LANGUAGE_TEXT(4, "\xa1{PLAYER} te destrozar\xe1!\n\n\xa1Serenity, ven aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_Y(3, 23)
  WALK_OBJECT_X(3, 68)
  WALK_OBJECT_Y(3, 40)
  WALK_OBJECT_X(3, 24)
  DELAY(8)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Joey, you came to rescue me?\n\n")
  LANGUAGE_TEXT(1, "Joey, tu es venu\nme sauver ?\n\n")
  LANGUAGE_TEXT(2, "Joey, bist du hier, um\nmich zu retten?\n\n")
  LANGUAGE_TEXT(3, "Joey, sei venuto\na salvarmi?\n\n")
  LANGUAGE_TEXT(4, "Joey, \xbfhas venido\na rescatarme?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Huh? Uh, yeah... Of course!\n\n")
  LANGUAGE_TEXT(1, "Mmm ? Euh,\nouais... Bien s\xfbr !\n\n")
  LANGUAGE_TEXT(2, "Hm? \xc4h, ja...\nNat\xfcrlich!\n\n")
  LANGUAGE_TEXT(3, "Come? Oh, gi\xe0...\nMa certo!\n\n")
  LANGUAGE_TEXT(4, "\xbfHuh? Uh, s\xed...\n\xa1Claro!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(273)
  REACTION(2, 8)
  DELAY(32)
  WALK_OBJECT_X(0, 14)
  WALK_OBJECT_Y(0, 42)
  WALK_OBJECT_X(0, 88)
  MOVE_OBJECT(13, 3, 0, 0)
  MOVE_OBJECT(3, 3, 0, 0)
  MOVE_OBJECT(2, 2, 0, 0)
  MOVE_OBJECT(11, 2, 0, 0)
  MOVE_OBJECT(4, 0, 0, 0)
  MOVE_OBJECT(5, 0, 0, 0)
  MOVE_OBJECT(6, 0, 0, 0)
  MOVE_OBJECT(7, 0, 0, 0)
  MOVE_OBJECT(8, 0, 0, 0)
  WALK_OBJECT_Y(0, 56)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Fine! Let's duel!\n\n")
  LANGUAGE_TEXT(1, "Bien !\nBattons-nous en duel !\n\n")
  LANGUAGE_TEXT(2, "Sch\xf6n!\nDuellieren wir uns!\n\n")
  LANGUAGE_TEXT(3, "Bene!\nDuelliamo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale!\n\xa1Luchemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(43)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFB420, map_57_state_01_08EFB420, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(28)
  PORTRAIT(PORTRAIT_DEEPSEA_WARRIOR, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Losing to kids is not good\ncorporate strategy!\n\n")
  LANGUAGE_TEXT(1, "Qu'\xeates-vous en train\nde faire \xe0 cet enfant ?\n\n")
  LANGUAGE_TEXT(2, "Was willst du mit einem\nKind wie ihm hier?\n\n")
  LANGUAGE_TEXT(3, "Che ci volete fare con un\nragazzino del genere?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 hac\xe9is contra un\nchiquillo como \xe9ste?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NIGHTMARE_PENGUIN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "According to my figures,\nthis never would have\n\nhappened it we fought with\nour special strategy.\n\n")
  LANGUAGE_TEXT(1, "D\xe8s le d\xe9but, nous\nn'aurions pas pu\n\ncacher notre identit\xe9.\n\n")
  LANGUAGE_TEXT(2, "Wir h\xe4tten uns von Anfang\nan nicht verstellen sollen.\n\n")
  LANGUAGE_TEXT(3, "Non avremmo dovuto\nnascondere la nostra\n\nidentit\xe0 fin dall'inizio.\n\n")
  LANGUAGE_TEXT(4, "No deber\xedamos haber\nocultado nuestra identidad\n\ndesde el principio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JUDGE_MAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Indubitably so!\n\n")
  LANGUAGE_TEXT(1, "Oui, c'est bien vrai !\n\n")
  LANGUAGE_TEXT(2, "Das stimmt!\n\n")
  LANGUAGE_TEXT(3, "Proprio cos\xec!\n\n")
  LANGUAGE_TEXT(4, "S\xed, \xa1es verdad!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Observe the true extent of\nour arsenal!\n\n")
  LANGUAGE_TEXT(1, "Voici toute l'\xe9tendue\nde notre puissance !\n\n")
  LANGUAGE_TEXT(2, "Achtet auf das wahre Ma\xdf\nunserer Macht!\n\n")
  LANGUAGE_TEXT(3, "State a vedere fin dove\narriva il nostro potere!\n\n")
  LANGUAGE_TEXT(4, "\xa1Observad el verdadero\nalcance de nuestro poder!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You left us with no choice!\n\nIntegral fusion!\n\n")
  LANGUAGE_TEXT(1, "Tr\xe8s bien, vous ne me\nlaissez pas le choix !\n\nFusion int\xe9grale !\n\n")
  LANGUAGE_TEXT(2, "Na sch\xf6n, ihr lasst mir\nkeine andere Wahl!\n\nIntegrale Fusion!\n\n")
  LANGUAGE_TEXT(3, "Benissimo, non mi\ndate altra scelta!\n\nFusione integrale!\n\n")
  LANGUAGE_TEXT(4, "Muy bien, \xa1no me\ndej\xe1is alternativa!\n\n\xa1Fusi\xf3n integral!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(294)
  SWAP_OBJECT_SPRITE(4, 140)
  SHOW_OBJECT(4, 88, 38, 0, 4, 0)
  SWAP_OBJECT_SPRITE(5, 141)
  SHOW_OBJECT(5, 88, 22, 0, 4, 0)
  SWAP_OBJECT_SPRITE(6, 142)
  SHOW_OBJECT(6, 104, 38, 0, 4, 0)
  SWAP_OBJECT_SPRITE(7, 143)
  SHOW_OBJECT(7, 93, 28, 0, 4, 0)
  SWAP_OBJECT_SPRITE(8, 144)
  SHOW_OBJECT(8, 82, 28, 0, 4, 0)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(11, 1, 0, 0)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Oh my double gosh, everyone!\n\nThe Big Bad Five have\nsummoned a monster!\n\nIt's F.G.D., the strongest\nmonster in history!\n\nThey can't win on their own!\nWe need Kaibaman's help!\n\nEveryone, we have to call\nhim!\n\nKaibaman!\n\n")
  LANGUAGE_TEXT(1, "Oh, ce n'est pas vrai !\n\nLes Cinq Grands M\xe9chants ont\nfait appel \xe0 un monstre !\n\nC'est le F.G.D., le\nmonstre le plus fort !\n\nIl n'y a pas le choix !\nNous avons besoin\n\nde l'aide de Kaibaman !\n\nTous ensemble, nous devons\ncrier pour l'appeler !\n\nKaibaman !\n\n")
  LANGUAGE_TEXT(2, "Oh je, alle aufgepasst!\n\nDie Big Five haben\nein Monster gerufen!\n\nEs ist der F.G.D., das\nst\xe4rkste aller Monster!\n\nWir haben keine Wahl! Wir\nbrauchen Kaibamans Hilfe!\n\nWir m\xfcssen ihn alle um\nHilfe rufen!\n\nKaibaman!\n\n")
  LANGUAGE_TEXT(3, "Oddio, guardate tutti!\n\nI Temibili Cinque hanno\nevocato un mostro!\n\n\xc8 F.G.D., il mostro\npi\xf9 forte!\n\nNon abbiamo scelta! Ci\nserve l'aiuto di Kaibaman!\n\nChiamiamolo tutti insieme\nperch\xe9 venga ad aiutarci!\n\nKaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Madre m\xeda, escuchad!\n\n\xa1Los Cinco Malvados han\nllamado a un monstruo!\n\nEs el F.G.D., \xa1el monstruo\nm\xe1s fuerte!\n\n\xa1No hay salida! \xa1Necesitamos\nla ayuda de Kaibaman!\n\n\xa1Escuchad, tenemos que\ngritar su nombre para\n\nque nos ayude!\n\n\xa1Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(11, 64)
  WALK_OBJECT_X(11, 109)
  SHOW_OBJECT(11, 128, 96, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(512, 1)
  LANGUAGE_TEXT(0, "Help, Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "A l'aide, Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Hilfe, Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "Aiuto, Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ayuda, Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(1024, 1)
  LANGUAGE_TEXT(0, "Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_ANGRY, 1)
  LANGUAGE_TEXT(0, "Kaibaman, help!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman, \xe0 l'aide !\n\n")
  LANGUAGE_TEXT(2, "Kaibaman, hilf uns!\n\n")
  LANGUAGE_TEXT(3, "Kaibaman, aiuto!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kaibaman, ayuda!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 1)
  LANGUAGE_TEXT(0, "Hurry, Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "D\xe9p\xeache-toi,\nKaibaman !\n\n")
  LANGUAGE_TEXT(2, "Beeil dich, Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "Sbrigati, Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1R\xe1pido, Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 8193)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "It looks like he heard you!\n\n")
  LANGUAGE_TEXT(1, "On dirait qu'il\nnous a entendu !\n\n")
  LANGUAGE_TEXT(2, "Es scheint, als habe er\neure Rufe geh\xf6rt!\n\n")
  LANGUAGE_TEXT(3, "A quanto pare, ha\nudito i vostri appelli!\n\n")
  LANGUAGE_TEXT(4, "\xa1Parece que ha o\xeddo\nvuestras s\xfaplicas!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  SHOW_OBJECT(1, 109, 64, 0, 0, 0)
  WALK_OBJECT_X(1, 88)
  MOVE_OBJECT(1, 2, 0, 0)
  WALK_OBJECT_X(0, 98)
  MOVE_OBJECT(0, 0, 8, 0)
  MOVE_OBJECT(0, 2, 0, 0)
  WALK_OBJECT_Y(1, 56)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Throughout history, when\nevil duelists rear their\n\nugly heads, I awaken from\nmy chaotic slumber!\n\n")
  LANGUAGE_TEXT(1, "Les duellistes des t\xe9n\xe8bres\nn'ont jamais r\xe9gn\xe9 !\n\n")
  LANGUAGE_TEXT(2, "Noch nie haben dunkle\nDuellanten geherrscht!\n\n")
  LANGUAGE_TEXT(3, "Nella storia, i duellanti\noscuri non hanno mai\n\n")
  LANGUAGE_TEXT(4, "\xa1Nunca en la historia\nlos duelistas oscuros\n\nhan imperado!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(295)
  LANGUAGE_TEXT(0, "From the deck of my golden\nsoul, I draw thunderous\n\npower!\n\n")
  LANGUAGE_TEXT(1, "Mon esprit invoque\nun \xe9clair foudroyant !\n\n")
  LANGUAGE_TEXT(2, "Vom Deck meines Geistes\nschleudere ich einen Blitz!\n\n")
  LANGUAGE_TEXT(3, "dominato! Dal deck del\nmio spirito estraggo una\n\n")
  LANGUAGE_TEXT(4, "\xa1De la deck de mi \xe1nimo,\nextraigo un rayo!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(344)
  LANGUAGE_TEXT(0, "I am the emperor of\nduelists! Kaibaman is here!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman, l'Empereur\ndes duellistes, est l\xe0 !\n\n")
  LANGUAGE_TEXT(2, "Der Kaiser der Duellanten,\nKaibaman, ist erschienen!\n\n")
  LANGUAGE_TEXT(3, "saetta! L'imperatore dei\nduellanti, Kaibaman, \xe8 qui!\n\n")
  LANGUAGE_TEXT(4, "\xa1El emperador de los\nduelistas, Kaibaman,\n\nest\xe1 aqu\xed!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(512, 1)
  LANGUAGE_TEXT(0, "Yeeeeeah! Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "G\xe9nial ! Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Jaaaa! Kaibaman!\n\n")
  LANGUAGE_TEXT(3, "S\xec\xec\xec\xec\xec\xec\xec! Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Siiiiiiiiii\xed! \xa1Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(1024, 1)
  LANGUAGE_TEXT(0, "Kaibaman, take them out!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman,\ndonne-leur une le\xe7on !\n\n")
  LANGUAGE_TEXT(2, "Kaibaman, zeig's ihnen!\n\n")
  LANGUAGE_TEXT(3, "Kaibaman, fagli vedere!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kaibaman, dales una\nlecci\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(8, 1)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Kaibaman, I love you!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman, je t'aime !\n\n")
  LANGUAGE_TEXT(2, "Kaibaman, ich liebe euch!\n\n")
  LANGUAGE_TEXT(3, "Kaibaman, ti\nvoglio bene!\n\n")
  LANGUAGE_TEXT(4, "Kaibaman, \xa1te quiero!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(4, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Everyone, thank you!\n\nYour positive energy\nstrengthens my spirit!\n\n")
  LANGUAGE_TEXT(1, "Merci \xe0 tous !\n\nVos \xe9nergies positives\nme r\xe9confortent !\n\n")
  LANGUAGE_TEXT(2, "Ich danke euch allen!\n\nEure positive Energie\nst\xe4rkt mich!\n\n")
  LANGUAGE_TEXT(3, "Grazie a tutti!\n\nLa vostra energia\npositiva mi solleva!\n\n")
  LANGUAGE_TEXT(4, "\xa1A todos, gracias!\n\n\xa1Vuestra energ\xeda posi-\ntiva me da \xe1nimos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  PLAY_MUSIC(295)
  LANGUAGE_TEXT(0, "Come hither, Black Luster\nSoldier!\n\n")
  LANGUAGE_TEXT(1, "Viens ici, Lustre\nnoir du soldat !\n\n")
  LANGUAGE_TEXT(2, "Komm her, schwarz\ngl\xe4nzender Soldat!\n\n")
  LANGUAGE_TEXT(3, "Fatti avanti, Glorioso\nSoldato Nero!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ven aqu\xed, Lustroso\nsoldado negro!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(295)
  LANGUAGE_TEXT(0, "Also, Blue-Eyes Ultimate\nDragon!\n\nFinally, I fuse the two\nmonsters!\n\n")
  LANGUAGE_TEXT(1, "Et encore ! Dragon\nsupr\xeame aux yeux bleus !\n\nOK ! Les deux monstres...\nFusion !\n\n")
  LANGUAGE_TEXT(2, "Mehr! Letzter blau\xe4ugiger\nDrache!\n\nOkay! Die zwei Monster...\nFusion!\n\n")
  LANGUAGE_TEXT(3, "Di pi\xf9! Drago\nFinale Occhi Blu!\n\nOkay! I due mostri...\nFusione!\n\n")
  LANGUAGE_TEXT(4, "\xa1M\xe1s! \xa1Gran drag\xf3n de\nojos azules!\n\n\xa1Vale! Los dos monstruos...\n\xa1Fusi\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(345)
  COMMAND_7C_ARG(8, 20)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(4, 1)
  DELAY(8)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh my triple gosh! Can it\nbe?! Can it actually be?!\n\nYes it is! It's Master of\nDragon Soldier!\n\n")
  LANGUAGE_TEXT(1, "Oh, ce n'est pas vrai !\nCe-ce monstre !\n\nC'est le Ma\xeetre du\nDragon Soldat !\n\n")
  LANGUAGE_TEXT(2, "Oh je!\nD-dieses Monster!\n\nEs ist der Meister des\nDrachensoldaten!\n\n")
  LANGUAGE_TEXT(3, "Diamine! Q-questo\nmostro!\n\n\xc8 il Soldato\nMaestro di Drago!\n\n")
  LANGUAGE_TEXT(4, "\xa1Madre m\xeda!\n\xa1E-este monstruo!\n\n\xa1Es el Maestro del\nSoldado Drag\xf3n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(374)
  OBJECT_EFFECT(496, 1)
  LANGUAGE_TEXT(0, "Wh-what?!\n\n")
  LANGUAGE_TEXT(1, "Q-quoi ?!\n\n")
  LANGUAGE_TEXT(2, "W-was?!\n\n")
  LANGUAGE_TEXT(3, "Che-che cosa?!\n\n")
  LANGUAGE_TEXT(4, "\xa1\xbfQ-qu\xe9?!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Master of Dragon Soldier,\nattack!\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre du Dragon\nSoldat, attaque !\n\n")
  LANGUAGE_TEXT(2, "Meister des Drachen-\nsoldaten, geh hin!\n\n")
  LANGUAGE_TEXT(3, "Soldato Maestro\ndi Drago, vai!\n\n")
  LANGUAGE_TEXT(4, "Maestro del Soldado\nDrag\xf3n, \xa1vamos!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 16)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Dragon Sabre Blast!\n\n")
  LANGUAGE_TEXT(1, "Galaxy Crush!\n\n")
  LANGUAGE_TEXT(2, "Galaxy Crush!\n\n")
  LANGUAGE_TEXT(3, "Galaxy Crush!\n\n")
  LANGUAGE_TEXT(4, "\xa1Galaxy Crush!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(342)
  COMMAND_7C_ARG(8, 17)
  DELAY(16)
  PLAY_MUSIC(346)
  COMMAND_7C_ARG(8, 23)
  DELAY(8)
  PLAY_MUSIC(374)
  OBJECT_EFFECT(496, 1)
  LANGUAGE_TEXT(0, "How dare you, Kaibaman!\n\nWe'll defeat you next time!\n\n")
  LANGUAGE_TEXT(1, "Comment oses-tu, Kaibaman !\n\nA notre prochaine rencontre,\ntu vas le regretter !\n\n")
  LANGUAGE_TEXT(2, "Wie kannst du es wagen,\nKaibaman!\n\nDaf\xfcr wirst du bei unserer\nn\xe4chsten Begegnung zahlen!\n\n")
  LANGUAGE_TEXT(3, "Come osi, Kaibaman!\n\nPagherai per questo al\nnostro prossimo incontro!\n\n")
  LANGUAGE_TEXT(4, "\xa1C\xf3mo osas,\nKaibaman!\n\n\xa1Pagar\xe1s por esto la pr\xf3xima\nvez que nos encontremos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_KAIBAMAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Justice always prevails over\ndarkness! Farewell,\n\neveryone!\n\n")
  LANGUAGE_TEXT(1, "La justice triomphe\ntoujours !\n\nA bient\xf4t, tout le monde !\n\n")
  LANGUAGE_TEXT(2, "Die Gerechtigkeit siegt\nletzten Endes immer!\n\nLebt wohl, ihr alle!\n\n")
  LANGUAGE_TEXT(3, "La giustizia vince sempre!\nAddio a tutti!\n\n")
  LANGUAGE_TEXT(4, "\xa1La justicia siempre gana!\n\xa1Adi\xf3s a todos!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(1, 64)
  WALK_OBJECT_X(1, 109)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  MOVE_OBJECT(0, 3, 0, 0)
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Thank you, Kaibaman!\n\n")
  LANGUAGE_TEXT(1, "Merci, Kaibaman !\n\n")
  LANGUAGE_TEXT(2, "Danke, Kaibaman!\nOkay, ihr alle!\n\n")
  LANGUAGE_TEXT(3, "Grazie, Kaibaman!\n\n")
  LANGUAGE_TEXT(4, "\xa1Gracias, Kaibaman!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Okay, everyone! Join us\nagain for the next show!\n\n")
  LANGUAGE_TEXT(1, "OK, tout le monde !\n\nRejoignez-nous\npour le prochain show !\n\n")
  LANGUAGE_TEXT(2, "Besucht uns wieder bei\nder n\xe4chsten Show!\n\n")
  LANGUAGE_TEXT(3, "Okay, ragazzi! Unitevi di\nnuovo a noi per il\n\nprossimo show!\n\n")
  LANGUAGE_TEXT(4, "\xa1Vale, todos vosotros!\n\xa1Venid de nuevo para\n\nver el nuevo show!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(512, 1)
  LANGUAGE_TEXT(0, "Kaibaman's so cool!\n\n")
  LANGUAGE_TEXT(1, "Kaibaman, il est trop\ncool !\n\n")
  LANGUAGE_TEXT(2, "Kaibaman ist so cool!\n\n")
  LANGUAGE_TEXT(3, "Kaibaman \xe8 fortissimo!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kaibaman es tan\nfen\xf3meno!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(1024, 1)
  LANGUAGE_TEXT(0, "Dragon Sabre Blast!\n\nI'm going to summon that\nmonster, too!\n\n")
  LANGUAGE_TEXT(1, "Galaxy Crush !\n\nMoi aussi, je vais faire\nappel \xe0 ce monstre !\n\n")
  LANGUAGE_TEXT(2, "Galaxy Crush!\n\nIch werde das Monster\nauch rufen!\n\n")
  LANGUAGE_TEXT(3, "Galaxy Crush!\n\nAnch'io evocher\xf2\nquel mostro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Galaxy Crush!\n\n\xa1Voy a llamar tambi\xe9n\na ese monstruo!\n\n")
  END_LANGUAGE_TEXT()
  COMMAND_7C_ARG(2, 8)
  FADE_SCREEN(8)
  WARP(12, 13, 1, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFB414, map_57_state_01_08EFB414, 0x08EFB408, 0x08EFB414)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "We can't let those thugs get\naway with this!\n\n")
  LANGUAGE_TEXT(1, "On ne peut pas laisser\nces criminels s'en sortir\n\naussi facilement !\n\n")
  LANGUAGE_TEXT(2, "Wir k\xf6nnen diese Kriminellen\nnicht ungeschoren\n\ndavonkommen lassen!\n\n")
  LANGUAGE_TEXT(3, "Non possiamo farla\npassare liscia a quei\n\ncriminali!\n\n")
  LANGUAGE_TEXT(4, "\xa1No podemos dejar\nque esos criminales\n\nse salgan con la suya!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Yugi, tell him!\n\n")
  LANGUAGE_TEXT(1, "Yugi, viens aussi\nlui dire !\n\n")
  LANGUAGE_TEXT(2, "Yugi,\nlos sag du es ihm auch!\n\n")
  LANGUAGE_TEXT(3, "Dai, Yugi,\ndiglielo anche tu!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yugi, vamos, d\xedselo,\ntambi\xe9n!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 8)
  LANGUAGE_TEXT(0, "It'll get the crowd excited,\nso I think you should play\n\nalong.\n\n")
  LANGUAGE_TEXT(1, "Eh bien, \xe7a a l'air marrant\nalors pourquoi tu ne veux\n\npas jouer, toi aussi ?\n\n")
  LANGUAGE_TEXT(2, "Es ist vielversprechend,\nwarum machst du dann\n\nnicht auch mit?\n\n")
  LANGUAGE_TEXT(3, "Be', sembra divertente,\nallora perch\xe9 non giochi?\n\n")
  LANGUAGE_TEXT(4, "Vaya, parece divertido,\n\xbfpor qu\xe9 no te apuntas?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
