#include "event_macros.h"
#include "overworld.h"

/* map_04_state_02: map 4 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08E4D090, map_04_state_02_08E4D090, 0x08E4D09C, 0x08E4D0A8)
  CHECK_FLAG(EVENT_FLAG_SCARED_DUELIST_HATER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D09C, map_04_state_02_08E4D09C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm not a duelist!\n\nPlease, spare me!\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas\nun duelliste !\n\nJe vous supplie\nde m'\xe9pargner !\n\n")
  LANGUAGE_TEXT(2, "Ich bin kein Duellant!\n\nBitte erspart mir das!\n\n")
  LANGUAGE_TEXT(3, "Non sono un duellante!\n\nVi prego, risparmiatemi!\n\n")
  LANGUAGE_TEXT(4, "\xa1No soy un duelista!\n\n\xa1Por favor, perdonadme!\n\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "...")
  LANGUAGE_TEXT(1, "... ")
  LANGUAGE_TEXT(2, "... ")
  LANGUAGE_TEXT(3, "... ")
  LANGUAGE_TEXT(4, "... ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Oh, you're not one of the\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "Oh, vous n'\xeates\npas les Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Oh, ihr seid nicht die\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "Oh, non siete dei\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "Oh, no sois los Neo\nGhouls.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_SCARED_DUELIST_HATER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0A8, map_04_state_02_08E4D0A8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Duelists sure are scaredy\ncats.\n\n")
  LANGUAGE_TEXT(1, "C'est s\xfbr, les\nduellistes font peur.\n\n")
  LANGUAGE_TEXT(2, "Duellanten sind ganz\nsch\xf6n Angst einfl\xf6\xdfend.\n\n")
  LANGUAGE_TEXT(3, "I duellanti mettono\nproprio paura.\n\n")
  LANGUAGE_TEXT(4, "Los duelistas seguro\nque dan pavor.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0B4, map_04_state_02_08E4D0B4, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I should've never come to\nthe Town of Domino.\n\n")
  LANGUAGE_TEXT(1, "Je n'aurais jamais\nd\xfb venir \xe0 Domino.\n\n")
  LANGUAGE_TEXT(2, "Ich h\xe4tte nie zu einem Ort\nwie Domino kommen sollen.\n\n")
  LANGUAGE_TEXT(3, "Non sarei mai dovuto venire\nin un posto come Domino.\n\n")
  LANGUAGE_TEXT(4, "No deber\xeda haber venido a un\nsitio como Domino.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0C0, map_04_state_02_08E4D0C0, 0x08E4D0CC, 0x08E4D0FC)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Like all other cities, this\ntown will also fall to the\n\nNeo Ghouls.\n\n")
  LANGUAGE_TEXT(1, "Cette ville aussi va\ntomber sous l'emprise\n\ndes Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Auch diese Stadt wird an\ndie Neo Ghouls fallen.\n\n")
  LANGUAGE_TEXT(3, "I Neo Ghouls faranno capito-\nlare anche questa citt\xe0.\n\n")
  LANGUAGE_TEXT(4, "Esta ciudad, tambi\xe9n, caer\xe1\nante los Neo Ghouls.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(59)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0CC, map_04_state_02_08E4D0CC, 0x08E4D0D8, 0x08E4D0E4)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0D8, map_04_state_02_08E4D0D8, 0x08E4D0F0, 0x08F04040)
  PLAY_MUSIC(10)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0F0, map_04_state_02_08E4D0F0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't think that this is\nover.\n\n")
  LANGUAGE_TEXT(1, "Ne croyez pas que\nce soit termin\xe9.\n\n")
  LANGUAGE_TEXT(2, "Glaub nicht, dass es\nvorbei ist.\n\n")
  LANGUAGE_TEXT(3, "Non credere che sia\nfinita qui.\n\n")
  LANGUAGE_TEXT(4, "No cre\xe1is que se\nha acabado.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 128)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0E4, map_04_state_02_08E4D0E4, 0x08E4D0F0, 0x08F04040)
  PLAY_MUSIC(11)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D0FC, map_04_state_02_08E4D0FC, 0x08E4D108, 0x08F0404C)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4D108, map_04_state_02_08E4D108, 0x08F0404C, 0x08F04040)
  CLEAR_FLAG(79)
  CLEAR_FLAG(78)
  CLEAR_FLAG(182)
  CLEAR_FLAG(102)
  FALLTHROUGH()
END_EVENT_SCRIPT()
