#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_06: map 23 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E9548C, map_23_state_06_08E9548C, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_BANDIT_KEITH)
  LOAD_SPRITE(2, SPRITE_ISHIZU)
  LOAD_SPRITE(3, SPRITE_ATEM)
  LOAD_SPRITE(4, SPRITE_YUGI)
  LOAD_SPRITE(5, SPRITE_SETO)
  PLAY_MUSIC(MUSIC_DUNGEON)
  DELAY(64)
  TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_RIGHT,
      "Never forget that no matter what, we're always",
      "together."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, "Right!")
  HIDE_PORTRAIT()
  DELAY(64)
  FADE_SCREEN(4)
  CLEAR_FLAG(243)
  CLEAR_FLAG(239)
  WARP(LOCATION_PEGASUS_ISLAND_DUNGEON_STAIRCASE, 4, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
