#include "event_macros.h"
#include "overworld.h"

/* map_05_state_07: map 5 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E51094, map_05_state_07_08E51094, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "I can't believe Tristan made\nus go all the way around\n\nthe world just because his\nstomach was growlin'!\n\n")
  LANGUAGE_TEXT(1, "Cet imb\xe9cile de Tristan...\n\nQu'est-ce qu'on va\nfaire de ce type ?\n\n")
  LANGUAGE_TEXT(2, "Tristan, dieser Idiot...\n\nWie sollen wir es mit\nihm nur aushalten?\n\n")
  LANGUAGE_TEXT(3, "Quell'idiota di\nTristan...\n\nChe dobbiamo fare\ncon quel ragazzo?\n\n")
  LANGUAGE_TEXT(4, "Ese memo de Tristan...\n\n\xbfC\xf3mo vamos a\nhacerlo con ese tipo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "It wasn't Tristan's fault.\nIt was just a\n\nmisunderstanding.\n\nAnyway, we have more\nimportant things to do.\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas de\nla faute de Tristan\n\nsi on s'est mis\ndans cette affaire.\n\nEt en plus, il faut\nvraiment avancer.\n\n")
  LANGUAGE_TEXT(2, "Es ist doch nicht Tristans\nSchuld,\n\ndass wir uns in dieser\nLage befinden.\n\nAu\xdferdem m\xfcssen wir\nuns wirklich beeilen.\n\n")
  LANGUAGE_TEXT(3, "Non \xe8 colpa di Tristan se\nsiamo in questa situazione.\n\nInoltre dobbiamo proprio\ndarci una mossa.\n\n")
  LANGUAGE_TEXT(4, "No es por Tristan\nque estemos en esto.\n\nAdem\xe1s, tenemos\nque hacer algo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Oh yeah! Maybe Ishizu has\ngood news.\n\nShe may have found a way to\nrestore the Egyptian God\n\nCards.\n\n")
  LANGUAGE_TEXT(1, "Ouais, peut-\xeatre qu'Ishizu\naura de bonnes nouvelles.\n\nElle aura peut-\xeatre\ntrouv\xe9 un moyen\n\npour restaurer les\ncartes des dieux.\n\n")
  LANGUAGE_TEXT(2, "Ja, vielleicht hat ja Ishizu\ngute Nachrichten.\n\nVielleicht hat sie einen\nWeg gefunden,\n\num die G\xf6tterkarten\nzur\xfcckzubekommen.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0. Forse Ishizu avr\xe0\nbuone notizie. Magari ha\n\ntrovato il modo di ripristi-\nnare le carte divine.\n\n")
  LANGUAGE_TEXT(4, "S\xed, puede que Ishizu\ntenga buenas nuevas.\n\nPuede que haya\nencontrado un modo\n\nde restaurar las\ncartas divinas.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Yes, I hope so.\n\n{PLAYER}, Joey, let's meet\nup with Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Oui, je l'esp\xe8re.\n{PLAYER}, Joey,\n\nnous devons\nretrouver Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Das hoffe ich auch.\n\n{PLAYER}, Joey, wir\nsollten zu Ishizu gehen.\n\n")
  LANGUAGE_TEXT(3, "S\xec, lo spero. {PLAYER},\nJoey, dobbiamo\n\nraggiungere Ishizu.\n\n")
  LANGUAGE_TEXT(4, "S\xed, eso espero.\n\n{PLAYER}, Joey,\ndeber\xedamos\n\npillar a Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(185)
  FALLTHROUGH()
END_EVENT_SCRIPT()
