#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_21_state_04: map 21 state 4 */


END()
EVENT_SCRIPT_REPLACEMENT(0x08E863FC, map_21_state_04_08E863FC, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(2, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(3, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(4, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(5, SPRITE_NEO_GHOUL)
  LOAD_SPRITE(6, SPRITE_EGYPT_EXHIBITION_GUARD)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You will proceed no further!")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E863A8, map_21_state_04_08E863A8, 0x08E863B4, 0x08E863C0)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You will proceed no further!")
  DUEL(DUELIST_NEO_GHOUL_076)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E863B4, map_21_state_04_08E863B4, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_NEO_GHOULS)
  TALK(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Neo Ghouls...are...forever...")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 28)
  WALK_OBJECT_X(5, 144)
  SET_FLAG(EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL5)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E863C0, map_21_state_04_08E863C0, 0x08F0404C, EVENT_NOP)
  CLEAR_FLAG(99)
  CLEAR_FLAG(247)
  CLEAR_FLAG(100)
  CLEAR_FLAG(101)
  CLEAR_FLAG(109)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E863CC, map_21_state_04_08E863CC, EVENT_NOP, EVENT_NOP)
  TEXT(
      "This is total chaos!",
      "Please do something about the Neo Ghouls!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E863D8, map_21_state_04_08E863D8, EVENT_NOP, EVENT_NOP)
  TEXT("At a time like this? You have to be joking!")
  FALLTHROUGH()
END_EVENT_SCRIPT()
