#include "event_macros.h"
#include "event_object_slots.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_23_state_09: map 23 state 9 */

#define LOCALID_ATEM_FIELD           3
#define LOCALID_PUZZLE_PART_2_LEFT   9
#define LOCALID_PUZZLE_PART_2_RIGHT  10
#define LOCALID_ATEM_WALKIN         13

LOAD_SPRITE(1, SPRITE_BANDIT_KEITH)
LOAD_SPRITE(2, SPRITE_ISHIZU)
LOAD_SPRITE(LOCALID_ATEM_FIELD, SPRITE_ATEM)
LOAD_SPRITE(4, SPRITE_PARA)
LOAD_SPRITE(5, SPRITE_VIDEO_CARD)
LOAD_SPRITE(6, SPRITE_MILLENNIUM_PUZZLE)
LOAD_SPRITE(7, SPRITE_MILLENNIUM_PUZZLE_PART_1)
LOAD_SPRITE(8, SPRITE_MILLENNIUM_PUZZLE_PART_3)
LOAD_SPRITE(LOCALID_PUZZLE_PART_2_LEFT, SPRITE_MILLENNIUM_PUZZLE_PART_2)
LOAD_SPRITE(LOCALID_PUZZLE_PART_2_RIGHT, SPRITE_MILLENNIUM_PUZZLE_PART_2)
DELAY(16)
MOVE_OBJECT(LOCALID_ATEM_WALKIN, DIRECTION_DOWN, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_218)
LOAD_SPRITE(LOCALID_ATEM_WALKIN, SPRITE_ATEM)
DELAY(64)
WALK_OBJECT_Y(LOCALID_ATEM_WALKIN, 50)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "You'll pay for how you treated my partner, Bandit",
    "Keith!"
)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Huh? What are you talking about?",
    "Just fork over your Egyptian God Card!"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "So you don't care what happens to this woman?")
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, it's clear you are a true duelist.",
    "The Egyptian God Cards choose who controls them...",
    "And you haven't earned the privilege!"
)
PLAY_MUSIC(MUSIC_347)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPHERE_RA_BLINK_IN)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_SURPRISED, PORTRAIT_POSITION_AUTO, "Wh-what's this?!")
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO,
    "It's Ra's judgment... Actually, it's more than",
    "that.",
    "Feel the wrath for angering the Egyptian Gods!"
)
PLAY_MUSIC(MUSIC_359)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_ENTERS_BATTLE_MODE)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_TRANSFORMS_TO_PHOENIX_MODE)
PLAY_MUSIC(MUSIC_348)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPARKLE_FLOATS_UP)
PLAY_MUSIC(MUSIC_302)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_DEFEATED, PORTRAIT_POSITION_AUTO, "Gwaaah!")
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_303)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 58, 38, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_205)
OBJECT_EFFECT(SPRITE_BANDIT_KEITH, OBJECT_EFFECT_DISAPPEAR)
DELAY(32)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Ra's judgment...",
    "Even though he brought it upon himself...",
    "I cannot help to feel sad for the horrible punishment",
    "he received..."
)
HIDE_PORTRAIT()
DELAY(32)
WALK_OBJECT_X(SPRITE_ISHIZU, 58)
WALK_OBJECT_Y(SPRITE_ISHIZU, 28)
DELAY(16)
PLAY_MUSIC(MUSIC_285)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 128, 96, 0, 0, 0)
DELAY(16)
WALK_OBJECT_X(0, 54)
WALK_OBJECT_Y(0, 40)
WALK_OBJECT_Y(14, 50)
WALK_OBJECT_X(14, 46)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
WALK_OBJECT_Y(LOCALID_ATEM_WALKIN, 50)
WALK_OBJECT_X(LOCALID_ATEM_WALKIN, 62)
MOVE_OBJECT(LOCALID_ATEM_WALKIN, DIRECTION_UP, 0, 0)
DELAY(16)
WALK_OBJECT_X(SPRITE_ISHIZU, 54)
WALK_OBJECT_Y(SPRITE_ISHIZU, 30)
DELAY(16)
PLAY_MUSIC(MUSIC_285)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 54, 32, 0, 0, 0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, take control of the Egyptian God Cards.",
    "You have earned the right."
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
DELAY(8)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_POSITION_AUTO,
    "I know exactly how hard {PLAYER} has worked to get",
    "this far."
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_HAPPY, PORTRAIT_POSITION_AUTO, "{PLAYER} is worthy of having the Egyptian God Cards.")
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Heheh, I hate to admit it, but I gotta agree.",
    "{PLAYER}, you're an awesome duelist."
)
HIDE_PORTRAIT()
DELAY(64)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(64)
PLAY_MUSIC(MUSIC_285)
ADD_CARD(297)
SHOW_OBJECT(SPRITE_VIDEO_CARD, 128, 96, 0, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_290)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPHERE_RA_REVIVED)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Way to go, {PLAYER}.")
TALK(PORTRAIT_NONE, "Received The Winged Dragon of Ra {BYTE_8169}Sphere Mode{BYTE_816A}.")
PLAY_MUSIC(MUSIC_267)
SCREEN_SHAKE(16)
PLAY_MUSIC(MUSIC_408)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO, "Please wait... I sense something...")
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_306)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RESHEF_TAKES_CONTROL_OF_KEITH)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO,
    "I feel the Dark Being summoning a vile spirit...",
    "No!",
    "The spirit is flooding into the hearts of defeated",
    "duelists!",
    "Reshef's will is taking control of their souls!"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_307)
MOVE_OBJECT(SPRITE_BANDIT_KEITH, DIRECTION_DOWN, 0, 0)
SHOW_OBJECT(SPRITE_BANDIT_KEITH, 62, 40, 0, 3, 0)
DELAY(16)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(0, 1, 6)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 0, 6)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO, "Gwehehehe!")
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Reshef the Dark Being has him under control.",
    "Dueling Bandit Keith now is too dangerous!"
)
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO,
    "You...",
    "Give it to me!"
)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | OBJECT_13 | OBJECT_14)
WALK_OBJECT_Y(0, 48)
WALK_OBJECT_X(0, 66)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
WALK_OBJECT_Y(14, 48)
WALK_OBJECT_X(14, 58)
MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(0, 3, 10)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
PLAY_MUSIC(MUSIC_277)
SLIDE_OBJECT(14, 1, 10)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_BANDIT_KEITH, DIRECTION_DOWN, 6, 0)
PLAY_MUSIC(MUSIC_308)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 0, 2)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 62, 50, 0, 0, 0)
DELAY(16)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 2, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 2, 2)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 2)
DELAY(16)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 0, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 0, 2)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 0, 2)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_YAMI_YUGI_ANGRY, PORTRAIT_POSITION_AUTO, "Wh-what are you doing, Bandit Keith?")
TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_BANDIT_KEITH_POSSESSED, PORTRAIT_POSITION_AUTO, "Gwehehehehehe!")
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 2, 2)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE, 2, 2)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 2)
DELAY(8)
SLIDE_OBJECT(LOCALID_ATEM_WALKIN, 0, 2)
DELAY(16)
PLAY_MUSIC(SOUND_NONE)
PLAY_MUSIC(MUSIC_309)
LOAD_SPRITE(6, SPRITE_SMALL_RUBBLE)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_1, 55, 42, 0, 0, 0)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_3, 69, 42, 0, 0, 0)
SHOW_OBJECT(LOCALID_PUZZLE_PART_2_LEFT, 76, 42, 0, 0, 0)
SHOW_OBJECT(LOCALID_PUZZLE_PART_2_RIGHT, 76, 52, 0, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | OBJECT_13 | OBJECT_14)
SLIDE_OBJECT(SPRITE_BANDIT_KEITH, 2, 12)
DELAY(8)
PLAY_MUSIC(MUSIC_205)
OBJECT_EFFECT(SPRITE_BANDIT_KEITH, OBJECT_EFFECT_DISAPPEAR)
DELAY(8)
LOAD_SPRITE(LOCALID_ATEM_WALKIN, SPRITE_YUGI)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Waaaaaaah!",
    "M-my other self! The Millennium Puzzle!"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_SMALL_RUBBLE, 128, 96, 0, 0, 0)
DELAY(8)
WALK_OBJECT_Y(SPRITE_YUGI, 44)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_LEFT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_1, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_RIGHT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_3, 128, 96, 0, 0, 0)
DELAY(8)
WALK_OBJECT_X(SPRITE_YUGI, 68)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(LOCALID_PUZZLE_PART_2_LEFT, 128, 96, 0, 0, 0)
DELAY(8)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_POSITION_AUTO, "My friend... I'll save you...")
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_311)
PLAY_MUSIC(MUSIC_404)
SHOW_OBJECT(SPRITE_PARA, 20, 74, 0, 2, 0)
PLAY_MUSIC(MUSIC_312)
DELAY(16)
TALK(PORTRAIT_PARA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Fufufu... This is amusing.")
HIDE_PORTRAIT()
DELAY(16)
LOAD_SPRITE(4, SPRITE_PARA_FLIPPING)
WALK_OBJECT_X(SPRITE_PARA_FLIPPING, 76)
LOAD_SPRITE(4, SPRITE_PARA)
WALK_OBJECT_Y(SPRITE_PARA, 64)
DELAY(8)
PLAY_MUSIC(MUSIC_310)
SHOW_OBJECT(LOCALID_PUZZLE_PART_2_RIGHT, 128, 96, 0, 0, 0)
DELAY(8)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | SPRITE_YUGI | OBJECT_14)
DELAY(8)
WALK_OBJECT_Y(SPRITE_PARA, 74)
MOVE_OBJECT(SPRITE_PARA, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, PORTRAIT_RIGHT,
    "These puzzle pieces make a fine souvenir!",
    "If you want them, come to Master Chevalsky's castle.",
    "Fwahahahaha!"
)
HIDE_PORTRAIT()
DELAY(16)
LOAD_SPRITE(4, SPRITE_PARA_FLIPPING)
WALK_OBJECT_X(SPRITE_PARA_FLIPPING, 20)
LOAD_SPRITE(4, SPRITE_PARA)
WALK_OBJECT_Y(SPRITE_PARA, 96)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)
DELAY(16)
WALK_OBJECT_Y(SPRITE_YUGI, 50)
TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, PORTRAIT_POSITION_AUTO,
    "This can't be happening... The puzzle pieces...",
    "What's going to happen to him..."
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_X(0, 68)
WALK_OBJECT_Y(0, 42)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, SPRITE_YUGI)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You're right! Let's go to Pegasus's castle.",
    "Wait for me, my friend..."
)
SET_FLAG(EVENT_FLAG_DEFEATED_BANDIT_KEITH)

EVENT_SCRIPT_REPLACEMENT(0x08E95450, map_23_state_09_08E95450, 0x08E9545C, EVENT_NOP)
PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_13)
  MOVE_OBJECT(LOCALID_ATEM_WALKIN, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Y-you're right...",
      "I don't have the time to feel sorry for myself.",
      "Wait for me, my friend..."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E95414, map_23_state_09_08E95414, 0x08E95420, EVENT_NOP)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You mustn't!",
    "Reshef the Dark Being has him under control.",
    "Dueling Bandit Keith now is too dangerous!"
)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E953CC, map_23_state_09_08E953CC, 0x08E953D8, EVENT_NOP)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{PLAYER}, it's tough, but that's the right decision.")
  TALK(PORTRAIT_BANDIT_KEITH, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Hurry up! Hand it over!")
  FALLTHROUGH()
END_EVENT_SCRIPT()
