#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_26_state_10: map 26 state 10 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3E60, map_26_state_10_08EA3E60, 0x08EA3E6C, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MAI)
  LOAD_SPRITE(2, SPRITE_JEAN_CLAUDE_MAGNUM)
  PLAY_MUSIC(MUSIC_JEAN_CLAUDE_MAGNUM)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM,
      "Mai Valentine, be mine! Marry me!",
      "Please!"
  )
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, "Would you quit already? You're annoying me.")
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, "But if you marry me, I won't annoy you anymore.")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1)
  DELAY(16)
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM,
      "I'm a Hollywood star. I have my pride.",
      "I'm not leaving until you say yes."
  )
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP,
      "Listen to me, Romeo.",
      "I already have someone special."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI, "So you can give up now, Jean Claude.")
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, "Wh-who is he?")
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, "That's none of your business.")
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM,
      "You're lying, aren't you? You're just trying to make",
      "me leave."
  )
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, "Er, um...")
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, "See! There really isn't anyone special!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 4, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, "Th-that's not true! There really is someone!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 4, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1 | OBJECT_2)
  DELAY(32)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_1)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI,
      "{BYTE_8169}...Why am I getting so worked up over this?{BYTE_816A}",
      "{BYTE_8169}And why do I keep thinking about him?{BYTE_816A}"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI, "...I wonder... How he's doing...")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(8)
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, "He? W-wait!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY,
      "Would you be quiet!",
      "I'm going out. Cover for me as the dealer."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(8)
  MOVE_OBJECT(2, DIRECTION_DOWN, 4, 0)
  DELAY(8)
  TALK(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, "B-but! Wait! Mai, please!")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 72)
  WALK_OBJECT_X(1, 64)
  WALK_OBJECT_Y(1, 96)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3E6C, map_26_state_10_08EA3E6C, EVENT_NOP, EVENT_NOP)
  FADE_MUSIC(16)
  FADE_SCREEN(16)
  WARP(LOCATION_ITALY_CATACOMBS_LEFT, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
