#include "event_macros.h"
#include "overworld.h"

/* map_06_state_03: map 6 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CC78, map_06_state_03_08E5CC78, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(31)
  DELAY(32)
  MOVE_OBJECT(5, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Oh,")
  LANGUAGE_TEXT(1, "Oh,")
  LANGUAGE_TEXT(2, "Oh,")
  LANGUAGE_TEXT(3, "Oh,")
  LANGUAGE_TEXT(4, "Oh,")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, " big brother!\n\nIs your work for Ishizu\ngoing smoothly?\n\n")
  LANGUAGE_TEXT(1, "grand fr\xe8re !\n\nTout se passe bien avec\nton travail pour Ishizu ?\n\n")
  LANGUAGE_TEXT(2, "gro\xdfer Bruder!\n\nL\xe4uft deine Arbeit f\xfcr\nIshizu reibungslos?\n\n")
  LANGUAGE_TEXT(3, "fratello mio!\n\nIl tuo lavoro per\nIshizu procede bene?\n\n")
  LANGUAGE_TEXT(4, "\xa1gran hermano!\n\n\xbfVa bien tu trabajo\npara Ishizu?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(272)
  REACTION(3, 16384)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Joey,\n")
  LANGUAGE_TEXT(1, "Quelque chose ne va pas,\n\n")
  LANGUAGE_TEXT(2, "Ist etwas los,\n\n")
  LANGUAGE_TEXT(3, "Qualcosa non va,\n\n")
  LANGUAGE_TEXT(4, "\xbfHay alg\xfan problema,\n\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "what's wrong?\n\n")
  LANGUAGE_TEXT(1, "grand fr\xe8re ?\n\n")
  LANGUAGE_TEXT(2, "gro\xdfer Bruder?\n\n")
  LANGUAGE_TEXT(3, "fratello?\n\n")
  LANGUAGE_TEXT(4, "gran hermano?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(14, 48)
  WALK_OBJECT_X(14, 64)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_X(13, 72)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SAD, 8)
  LANGUAGE_TEXT(0, "Serenity, ")
  LANGUAGE_TEXT(1, "Serenity, ")
  LANGUAGE_TEXT(2, "Serenity, ")
  LANGUAGE_TEXT(3, "Serenity, ")
  LANGUAGE_TEXT(4, "Serenity, ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "uh...\n")
  LANGUAGE_TEXT(1, "euh...\n")
  LANGUAGE_TEXT(2, "\xe4h...\n")
  LANGUAGE_TEXT(3, "uh...\n")
  LANGUAGE_TEXT(4, "uh...\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Er, um...\n\n")
  LANGUAGE_TEXT(1, "Euh, mmm...\n\n")
  LANGUAGE_TEXT(2, "\xc4h, \xe4hm...\n\n")
  LANGUAGE_TEXT(3, "Ehm, dunque...\n\n")
  LANGUAGE_TEXT(4, "Er, um...\n\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Tell me da truth. Is there\n")
  LANGUAGE_TEXT(1, "Est-ce qu'il y a un mec\n")
  LANGUAGE_TEXT(2, "Also, gibt es jemanden, den\n")
  LANGUAGE_TEXT(3, "Ti piace per caso\n")
  LANGUAGE_TEXT(4, "Como, \xbfhay alg\xfan chico\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "anybody that you like?\n\n")
  LANGUAGE_TEXT(1, "qui te pla\xeet en ce moment ?\n\n")
  LANGUAGE_TEXT(2, "du besonders magst?\n\n")
  LANGUAGE_TEXT(3, "qualche ragazzo?\n\n")
  LANGUAGE_TEXT(4, "que te gusta?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah.\n\n")
  LANGUAGE_TEXT(1, "Oui.\n\n")
  LANGUAGE_TEXT(2, "Ja.\n\n")
  LANGUAGE_TEXT(3, "S\xec.\n\n")
  LANGUAGE_TEXT(4, "S\xed.\n\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "There sure is.\n\n")
  LANGUAGE_TEXT(1, "Oui, en effet.\n\n")
  LANGUAGE_TEXT(2, "Ja, den gibt es allerdings.\n\n")
  LANGUAGE_TEXT(3, "Certo che s\xec.\n\n")
  LANGUAGE_TEXT(4, "Claro que lo hay.\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(271)
  REACTION(0, 16384)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "S-")
  LANGUAGE_TEXT(1, "S-")
  LANGUAGE_TEXT(2, "S-")
  LANGUAGE_TEXT(3, "S-")
  LANGUAGE_TEXT(4, "\xa1S-")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Serenity! ")
  LANGUAGE_TEXT(1, "Serenity! ")
  LANGUAGE_TEXT(2, "Serenity! ")
  LANGUAGE_TEXT(3, "Serenity! ")
  LANGUAGE_TEXT(4, "Serenity!\n")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Are you serious?\nDo I know this guy?\n\n")
  LANGUAGE_TEXT(1, "C'est\nquelqu'un que je connais ?\n\n")
  LANGUAGE_TEXT(2, "Ist es jemand,\nden ich kenne?\n\n")
  LANGUAGE_TEXT(3, "Questo\nragazzo lo conosco?\n\n")
  LANGUAGE_TEXT(4, "\xbfLe conozco?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yup. ")
  LANGUAGE_TEXT(1, "Ouais, ")
  LANGUAGE_TEXT(2, "Ja, ")
  LANGUAGE_TEXT(3, "Gi\xe0, ")
  LANGUAGE_TEXT(4, "S\xed, ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "Tristan...\n\n")
  LANGUAGE_TEXT(1, "c'est Tristan...\n\n")
  LANGUAGE_TEXT(2, "Tristan...\n\n")
  LANGUAGE_TEXT(3, "Tristan...\n\n")
  LANGUAGE_TEXT(4, "Tristan...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(271)
  REACTION(0, 16384)
  HIDE_PORTRAIT()
  DELAY(8)
  WALK_OBJECT_X(14, 52)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "What? ")
  LANGUAGE_TEXT(1, "Quoi ? ")
  LANGUAGE_TEXT(2, "Was? ")
  LANGUAGE_TEXT(3, "Cosa? ")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "No! Anybody but him!\n\n")
  LANGUAGE_TEXT(1, "Non ! C'est\npas possible, pas lui !\n\n")
  LANGUAGE_TEXT(2, "Nein!\nNur nicht er!\n\n")
  LANGUAGE_TEXT(3, "No! Non\npu\xf2 essere lui!\n\n")
  LANGUAGE_TEXT(4, "\xa1No!\n\xa1Que no sea \xe9l!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What's wrong, Joey?\n\nThere's Tristan... and\nDuke...\n\nAnd Yugi and {PLAYER}...\n\nI also like Tea and Mai.\n\nBut I like you the best, big\nbrother.\n\n")
  LANGUAGE_TEXT(1, "Il y a un truc qui ne\nva pas, grand fr\xe8re ?\n\nJ'aime bien\nTristan et Duke...\n\nEt Yugi et {PLAYER}...\nJ'aime aussi Tea et Mai.\n\nMais c'est toi que je\npr\xe9f\xe8re, grand fr\xe8re.\n\n")
  LANGUAGE_TEXT(2, "Was ist los, gro\xdfer Bruder?\nTristan und Duke...\n\nUnd Yugi und {PLAYER}...\nUnd ich mag Tea und Mai.\n\nAber du bist mir am\nliebsten, gro\xdfer Bruder.\n\n")
  LANGUAGE_TEXT(3, "Che c'\xe8 di male, fratello?\n\nTristan e Duke...\n\nYugi e {PLAYER}...\n\nMi piacciono anche\nTea e Mai.\n\nMa pi\xf9 di tutti mi\npiaci tu, fratello.\n\n")
  LANGUAGE_TEXT(4, "\xbfAlg\xfan problema,\ngran hermano?\n\nTristan y Duke...\n\nY Yugi y {PLAYER}...\n\nTambi\xe9n me gustan\nTea y Mai.\n\nPero t\xfa el que m\xe1s,\ngran hermano.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  WALK_OBJECT_X(1, 80)
  WALK_OBJECT_X(2, 80)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_SURPRISED, 8)
  LANGUAGE_TEXT(0, "B-")
  LANGUAGE_TEXT(1, "M-")
  LANGUAGE_TEXT(2, "A-")
  LANGUAGE_TEXT(3, "M-")
  LANGUAGE_TEXT(4, "Pe-")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "but...\n\n")
  LANGUAGE_TEXT(1, "mais.\n\n")
  LANGUAGE_TEXT(2, "aber...\n\n")
  LANGUAGE_TEXT(3, "ma...\n\n")
  LANGUAGE_TEXT(4, "pero...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But ")
  LANGUAGE_TEXT(1, "Mais ")
  LANGUAGE_TEXT(2, "Warte, ")
  LANGUAGE_TEXT(3, "Ma come, ")
  LANGUAGE_TEXT(4, "Espera, ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "you said you liked\nstrong duelists...\n\n")
  LANGUAGE_TEXT(1, "tu avais dit que tu\naimais les duellistes\n\nles plus forts...\n\n")
  LANGUAGE_TEXT(2, "du hast doch gesagt,\ndu magst starke Duellanten.\n\n")
  LANGUAGE_TEXT(3, "avevi detto\nche ti piacevano i\n\nduellanti forti...\n\n")
  LANGUAGE_TEXT(4, "dijiste que te\ngustaban los duelistas\n\nfuertes...\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(270)
  REACTION(1, 32)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Did I really say that?\n\nWell... come to think of\nit...\n\nI think it's coincidence\nthat the people I like just\n\nhappen to be good duelists.\n\n")
  LANGUAGE_TEXT(1, "Ah, j'ai dit \xe7a ?\n\nOui, probablement.\n\nJ'aime les bons duellistes.\n\n")
  LANGUAGE_TEXT(2, "Habe ich das wirklich\ngesagt?\n\nNa ja, vielleicht hast du\nRecht.\n\nIch mag gute Duellanten.\n\n")
  LANGUAGE_TEXT(3, "Davvero l'ho detto?\n\nBe', sar\xe0 cos\xec.\n\nLa gente che mi piace\nsono i bravi duellanti.\n\n")
  LANGUAGE_TEXT(4, "\xbfLo dije?\n\nBueno, lo supongo.\n\nLa gente que me gusta\nson buenos duelistas.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Awwwww, man...\n\n")
  LANGUAGE_TEXT(1, "Ohhhh, mec...\n\n")
  LANGUAGE_TEXT(2, "Ooooohhh, verdammt...\n\n")
  LANGUAGE_TEXT(3, "Ohhh, no...\n\n")
  LANGUAGE_TEXT(4, "Awwwww, hombre...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(14, 3, 4, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Alright, ya idiots! Get\noutta here!\n\nGet back to work at the\nshop!\n\n")
  LANGUAGE_TEXT(1, "Vous deux, arr\xeatez\nde faire les imb\xe9ciles.\n\nRetournez vite au\nmagasin et au travail !\n\n")
  LANGUAGE_TEXT(2, "H\xf6rt auf mit diesen\nDummheiten.\n\nZur\xfcck ins Gesch\xe4ft und\nwieder an die Arbeit.\n\n")
  LANGUAGE_TEXT(3, "Voi due smettetela\ncon queste stupidate.\n\nTornate in fretta al negozio\ne rimettetevi al lavoro.\n\n")
  LANGUAGE_TEXT(4, "Vosotros dos ten\xe9is que\ndejar esta estupidez.\n\nVolved a la tienda y\na trabajar.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(65)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC90, map_06_state_03_08E5CC90, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, ")
  LANGUAGE_TEXT(1, "{PLAYER}, ")
  LANGUAGE_TEXT(2, "{PLAYER}, ")
  LANGUAGE_TEXT(3, "{PLAYER}, ")
  LANGUAGE_TEXT(4, "{PLAYER}, ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "I know you can\nwin.\n\nYou have to fight for me,\ntoo!\n\n")
  LANGUAGE_TEXT(1, "vas-y !\n\nIl faut aussi que\ntu fasses mon truc !\n\n")
  LANGUAGE_TEXT(2, "nur zu!\n\nDu musst auch meinen\nTeil \xfcbernehmen!\n\n")
  LANGUAGE_TEXT(3, "metticela\ntutta!\n\nDevi fare anche la\nmia parte!\n\n")
  LANGUAGE_TEXT(4, "\xa1a por ello!\n\nAdem\xe1s, \xa1tienes que\nhacer mi parte!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC9C, map_06_state_03_08E5CC9C, 0x08E5CCA8, 0x08F0404C)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't really feel like it,\nbut I'll do anything for\n\nyou, buddy!\n\n")
  LANGUAGE_TEXT(1, "Je ne veux pas vraiment,\nmais je le ferais\n\npar amiti\xe9.\n\n")
  LANGUAGE_TEXT(2, "Ich will es eigentlich\nnicht, aber um der\n\nFreundschaft willen - okay!\n\n")
  LANGUAGE_TEXT(3, "Non voglio proprio, ma\nlo far\xf2 per amicizia!\n\n")
  LANGUAGE_TEXT(4, "Realmente no quiero,\npero \xa1lo har\xe9 por amistad!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(125)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCA8, map_06_state_03_08E5CCA8, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(6)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Did that even count as\npractice?\n\n")
  LANGUAGE_TEXT(1, "Est-ce que j'ai\n\xe9t\xe9 \xe0 la hauteur\n\ncomme partenaire\nd'entra\xeenement ?\n\n")
  LANGUAGE_TEXT(2, "War ich \xfcberhaupt ein loh-\nnender Trainingspartner?\n\n")
  LANGUAGE_TEXT(3, "\xc8 valsa la pena di avere\nun partner di allenamento\n\ncome me, almeno?\n\n")
  LANGUAGE_TEXT(4, "\xbfHe sido bueno como\ncolega de entrenamiento?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCB4, map_06_state_03_08E5CCB4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, ")
  LANGUAGE_TEXT(1, "{PLAYER}, ")
  LANGUAGE_TEXT(2, "{PLAYER}, ")
  LANGUAGE_TEXT(3, "{PLAYER}, ")
  LANGUAGE_TEXT(4, "{PLAYER}, ")
  END_LANGUAGE_TEXT()
  DELAY(16)
  LANGUAGE_TEXT(0, "leave it to me!\n\nI'll keep an eye on Tristan.\n\n...Especially to make sure\nthat he doesn't hit on\n\nSerenity!\n\n")
  LANGUAGE_TEXT(1, "laisse-moi faire.\n\nJe vais garder l'\u0153il\nsur Tristan.\n\nPour \xeatre s\xfbr qu'il ne\ndrague pas Serenity.\n\n")
  LANGUAGE_TEXT(2, "\xfcberlass alles\nnur mir.\n\nIch behalte Tristan\nim Auge.\n\nIch sorge schon daf\xfcr,\ndass er Serenity nicht\n\nanbaggert.\n\n")
  LANGUAGE_TEXT(3, "lascia\nfare a me.\n\nTerr\xf2 d'occhio Tristan.\nFar\xf2 in modo che non\n\nfaccia avance a Serenity.\n\n")
  LANGUAGE_TEXT(4, "d\xe9jamelo a m\xed.\n\nVigilar\xe9 a Tristan.\n\nMe asegurar\xe9 de que no\nlo intenta con Serenity.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC6C, map_06_state_03_08E5CC6C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(274)
  REACTION(4, 16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CC84, map_06_state_03_08E5CC84, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wouldn't it be great if we\ncould stay friends forever?\n\n")
  LANGUAGE_TEXT(1, "Ca serait g\xe9nial\n\nsi on pouvait \xeatre\namis pour toujours ?\n\n")
  LANGUAGE_TEXT(2, "W\xe4re es nicht sch\xf6n, wenn\nwir Freunde f\xfcr immer\n\nsein k\xf6nnten?\n\n")
  LANGUAGE_TEXT(3, "Non sarebbe bello se\nfossimo amici per sempre?\n\n")
  LANGUAGE_TEXT(4, "\xbfNo ser\xeda estupendo\nque fu\xe9ramos amigos\n\npara siempre?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
