#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_28_state_01: map 28 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EA69C8, map_28_state_01_08EA69C8, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_OLD_MAN)
  LOAD_SPRITE(2, SPRITE_OLD_WOMAN)
  PLAY_MUSIC(MUSIC_ITALY)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  TEXT("Now this is rare.")
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_UP, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TEXT("It certainly is.")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  DELAY(32)
  TEXT("This is a community cemetery from long ago.")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
  DELAY(32)
  TEXT("I know. It's called the Catacombs.")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1)
  DELAY(16)
  TEXT("That's right! You've done your homework.")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_2)
  DELAY(16)
  TEXT("I haven't done any homework in decades, dear.")
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_1 | OBJECT_2)
  SET_FLAG(EVENT_FLAG_SAW_ELDERS_TALK_TO_EACH_OTHER)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69D4, map_28_state_01_08EA69D4, EVENT_NOP, EVENT_NOP)
  TEXT("This is a community cemetery from long ago.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69E0, map_28_state_01_08EA69E0, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Duo? What do you mean? Do you want me to be your",
      "partner?",
      "Do you want to perform a duo and sing with me?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69EC, map_28_state_01_08EA69EC, EVENT_NOP, EVENT_NOP)
  TEXT(
      "It's called the Catacombs.",
      "For some reason, this place makes me feel calm."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA69F8, map_28_state_01_08EA69F8, EVENT_NOP, EVENT_NOP)
  TEXT(
      "Jewel?",
      "You'll buy one for me?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
