#include "event_macros.h"
#include "overworld.h"

/* map_26_state_06: map 26 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3CEC, map_26_state_06_08EA3CEC, 0x08EA3CF8, 0x08EA3D04)
  PLAY_MUSIC(407)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Harpie Lady!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(333)
  COMMAND_7C_ARG(8, 12)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Harpies' Triangle Ecstasy!\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(341)
  COMMAND_7C_ARG(8, 13)
  DELAY(16)
  PLAY_MUSIC(284)
  SLIDE_OBJECT(3, 1, 8)
  PLAY_MUSIC(282)
  OBJECT_EFFECT(8, 2)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hyahahahaha! Nice attack...\n\nBut how much longer can you\nkeep this up?\n\nGo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 24)
  MOVE_OBJECT(4, 3, 0, 0)
  SET_OBJECT_POSITION(3, 0, 52, 0)
  WALK_OBJECT_X(3, 24)
  WALK_OBJECT_Y(3, 32)
  WALK_OBJECT_X(3, 84)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "Grr... There's too many of\nthem...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 70)
  WALK_OBJECT_X(0, 21)
  WALK_OBJECT_Y(0, 30)
  WALK_OBJECT_X(0, 40)
  WALK_OBJECT_Y(13, 70)
  WALK_OBJECT_X(13, 21)
  WALK_OBJECT_Y(13, 36)
  WALK_OBJECT_X(13, 30)
  WALK_OBJECT_Y(14, 70)
  WALK_OBJECT_X(14, 21)
  WALK_OBJECT_Y(14, 36)
  WALK_OBJECT_X(14, 30)
  WALK_OBJECT_Y(14, 24)
  WALK_OBJECT_X(14, 30)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 4)
  DELAY(8)
  PLAY_MUSIC(407)
  MOVE_OBJECT(2, 1, 0, 0)
  MOVE_OBJECT(3, 1, 0, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hyahahahaha! How good of you\nto visit!\n\nWhat's the fun without a\ncaptive audience!\n\nI'll give you two choices.\n\nDo nothing but watch this\nstunning show as I defeat\n\nthis woman...\n\nOr step in and be magically\ndefeated by me!\n\nHyahahahahaha!\n\nWhichever choice you make,\nI win!\n\nHyahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}I'm going to win!\nI'll let you surrender.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3CF8, map_26_state_06_08EA3CF8, 0x08EA3D10, 0x08F0404C)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Are you that anxious to be\nhumiliated?!\n\nI will have you begging on\nyour knees before it's\n\nover!\n\nI, Arkana, accept your\nchallenge!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(156)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D10, map_26_state_06_08EA3D10, 0x08EA3D1C, 0x08EA3D28)
  PLAY_MUSIC(407)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_ARKANA_DEFEATED, 0)
  LANGUAGE_TEXT(0, "Wh-what? I lost? The great\nArkana lost?\n\nHyahahahaha! This simply\ncannot be!\n\nThis must be a mistake!\nHyahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 102)
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 60)
  WALK_OBJECT_Y(2, 96)
  WALK_OBJECT_X(3, 102)
  WALK_OBJECT_Y(3, 68)
  WALK_OBJECT_X(3, 60)
  WALK_OBJECT_Y(3, 96)
  WALK_OBJECT_Y(4, 32)
  WALK_OBJECT_X(4, 102)
  WALK_OBJECT_Y(4, 68)
  WALK_OBJECT_X(4, 60)
  WALK_OBJECT_Y(4, 96)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  WALK_OBJECT_Y(1, 32)
  WALK_OBJECT_X(1, 72)
  DELAY(16)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You came here to save me?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D1C, map_26_state_06_08EA3D1C, 0x08EA3D34, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Thanks. I couldn't have done\nit without you.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D34, map_26_state_06_08EA3D34, 0x08EA3D4C, 0x08EA3D40)
  LANGUAGE_TEXT(0, "So what exactly brings you\nout here?\n\nDid you want to see me about\nsomething?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PLAY_MUSIC(702)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, 0)
  LANGUAGE_TEXT(0, "What! Those creeps...\n\nThe Neo Ghouls are\ndestroying the city?\n\nI won't let those cheaters\nget away with it!\n\nAll right, I'll help.\n\nWe'll show them what a\nreal duelist is all about!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 102)
  WALK_OBJECT_Y(1, 68)
  WALK_OBJECT_X(1, 60)
  WALK_OBJECT_Y(1, 96)
  SET_FLAG(EVENT_FLAG_DEFEATED_ARKANA)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D4C, map_26_state_06_08EA3D4C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Okay! Let's go find another\nally!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D40, map_26_state_06_08EA3D40, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Okay! We should also get\nback to the Town of Domino!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D28, map_26_state_06_08EA3D28, 0x08EA3D34, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Well, I didn't really need\nyour help, anyway.\n\nI could've beaten the Neo\nGhouls by myself!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D04, map_26_state_06_08EA3D04, 0x08EA3D10, 0x08F0404C)
  PORTRAIT(PORTRAIT_ARCANA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You must be joking.\n\nYou're demanding that I beg\nyou for forgiveness?\n\nHyahahahaha! Whatever!\n\nYou're about to witness my\ndazzling duel skills!\n\nPrepare for Arkana's most\nexhilarating performance\n\nyet!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(156)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D58, map_26_state_06_08EA3D58, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "The Neo Ghouls are\nfrightening individuals\n\nindeed.\n\nIf it weren't for Mai, my\nrare cards would be gone.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D64, map_26_state_06_08EA3D64, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Oh, no. No more duels for\nme, thank you kindly.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D70, map_26_state_06_08EA3D70, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "How could we be attacked by\nthe Neo Ghouls?\n\nDear me, this ship's\nsecurity is not up to\n\nsnuff.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D7C, map_26_state_06_08EA3D7C, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'm sorry, the idea doesn't\nenthuse me.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
