#include "event_macros.h"
#include "overworld.h"

/* map_00_state_06: map 0 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E34B50, map_00_state_06_08E34B50, 0x08E34B5C, 0x08E34BB0)
  CHECK_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_EYE_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B5C, map_00_state_06_08E34B5C, 0x08E34B68, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, 8)
  LANGUAGE_TEXT(0, "I could not foretell that\nSol Chevalsky was actually\n\nMaximillion Pegasus...\n\nHe has been missing since\nDuelist Kingdom...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What could have happened to\nhim during all this time?\n\nWe cannot worry about this\nnow. Let's resurrect an\n\nEgyptian God Card.\n\nWith the powers of the\nMillennium Ring and\n\nMillennium Eye...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B68, map_00_state_06_08E34B68, 0x08E34B74, 0x08F04040)
  PLAY_MUSIC(290)
  COMMAND_7C_ARG(8, 2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B74, map_00_state_06_08E34B74, 0x08E34B80, 0x08E34B8C)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Obelisk the Tormentor\nhas regained its power.\n\nHowever.")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "Egyptian God\nCards choose their bearers.\n\nIt appears that Obelisk will\nnot accept you.\n\nIt seems you are not yet\nready to control its\n\nimmense powers.\n\nThe card has chosen as its\nbearer...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 1)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(2, 48)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_X(3, 40)
  MOVE_OBJECT(3, 2, 0, 0)
  PORTRAIT(PORTRAIT_SETO, 2, 8)
  LANGUAGE_TEXT(0, "Enough of this bogus mystic\ntalk!\n\nIt's obvious who deserves to\ncontrol Obelisk!\n\nWho else but me!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Don't bet on it!\nI guess so...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B80, map_00_state_06_08E34B80, 0x08E34B98, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(275)
  REACTION(REACTION_ANGRY, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, 8)
  LANGUAGE_TEXT(0, "Don't bet on it? Don't talk\nto my brother that way!\n\nIf it wasn't for my\nbrother...\n\nYou wouldn't have won the\ntag duel!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B98, map_00_state_06_08E34B98, 0x08E34BA4, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 40)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  MOVE_OBJECT(0, 1, 8, 0)
  MOVE_OBJECT(0, 3, 0, 0)
  WALK_OBJECT_Y(2, 32)
  DELAY(43)
  PLAY_MUSIC(285)
  DELAY(16)
  MOVE_OBJECT(2, 0, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't care what you\namateurs think...\n\nIf you have a problem, come\nout and say it!\n\nTry to defeat me and take\nObelisk!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 1, 8)
  LANGUAGE_TEXT(0, "Though I don't know how a\nbunch of incompetent fools\n\nare ever going to beat me!\n\nWahahahahahaha!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 64)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_X(2, 128)
  WALK_OBJECT_Y(3, 64)
  WALK_OBJECT_X(3, 128)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You cannot deny destiny...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You must wait until it is\nyour time.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BA4, map_00_state_06_08E34BA4, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(4, 64)
  WALK_OBJECT_X(4, 48)
  WALK_OBJECT_Y(4, 52)
  DELAY(16)
  PLAY_MUSIC(31)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hey, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Hey, what's up, Tristan?\nWhat are you doing here?\n\nNothin' betta have happened\nto Serenity!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Uh... Well, actually,\nyeah... That's...what I'm\n\nhere about.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Say what?! What happened to\nmy sister!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Well...\n\nShe really wants to see the\nKaibaman show.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "The Kaibaman show? What the\nheck is that?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You haven't heard of it?\n\nIt's the biggest thing right\nnow! Kids love it! Get with\n\nthe times, man!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Well, I don't like anything\nwith the name Kaiba in\n\nit...\n\nBut if Serenity wants to go,\nI guess I'll take her.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 8)
  LANGUAGE_TEXT(0, "Oh, but I can't just abandon\nmy duties without\n\npermission.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, can I take some\ntime off?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "Hahaha...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 24577)
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "I'm sorry for laughing.\n\nA little time off will help\nyou relax and rekindle your\n\nspirits.\n\nPerhaps you can all go see\nthe show.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yeah! You know what's up,\nIshizu!\n\nAll right. I'd better find\nSerenity and...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, 8)
  LANGUAGE_TEXT(0, "I thought you'd say that, so\nI already brought her.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, 8)
  LANGUAGE_TEXT(0, "Serenity, come on in.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_X(5, 40)
  WALK_OBJECT_Y(5, 52)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Joey, can I really go?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "No doubt!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Thank you, Joey!\n\nI'll go ahead and save us a\nspot.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(5, 64)
  WALK_OBJECT_X(5, 128)
  MOVE_OBJECT(4, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Kaibaman show is being\nshown in front of\n\nKaibaCorp.\n\nNow you shouldn't keep a\nlady waiting, especially\n\nSerenity.\n\nI'm outta here.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(4, 64)
  WALK_OBJECT_X(4, 60)
  WALK_OBJECT_Y(4, 96)
  MOVE_OBJECT(13, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "We should go too.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 48)
  WALK_OBJECT_Y(0, 52)
  SET_FLAG(EVENT_FLAG_BROUGHT_MILLENNIUM_EYE_TO_ISHIZU)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B8C, map_00_state_06_08E34B8C, 0x08E34B98, 0x08F04040)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Heh. You finally realize\nyou're not in my league.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BB0, map_00_state_06_08E34BB0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 8)
  LANGUAGE_TEXT(0, "Serenity is waiting for you.\n\nShe should be at Kaiba\nCorporation.\n\nWeren't you going to see the\nKaibaman show?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
