#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_55_state_01: map 55 state 1 */

LOAD_SPRITE(1, SPRITE_PEGASUS)
LOAD_SPRITE(2, SPRITE_ISHIZU)
LOAD_SPRITE(3, SPRITE_SETO)
LOAD_SPRITE(4, SPRITE_YUGI)
LOAD_SPRITE(5, SPRITE_JOEY)
LOAD_SPRITE(6, SPRITE_MILLENNIUM_PUZZLE_PART_2)
LOAD_SPRITE(7, SPRITE_MEDIUM_RUBBLE)
LOAD_SPRITE(8, SPRITE_SMALL_RUBBLE)
LOAD_SPRITE(9, SPRITE_BIG_RUBBLE)
PLAY_MUSIC(MUSIC_SOL_CHEVALSKY)
WALK_OBJECT_Y(0, 72)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0)
WALK_OBJECT_Y(0, 66)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, PORTRAIT_POSITION_AUTO,
    "Congratulations for passing\n"
    "my test!\n\n"
    "So, {PLAYER}, it is you who\n"
    "survived until the end...\n\n"
    "Fufufu, I, Sol Chevalsky,\n"
    "welcome you!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
WALK_OBJECT_Y(SPRITE_ISHIZU, 68)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Pegasus, stop this nonsense\n"
    "at once.\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "My past means nothing to me.\n"
    "I am no longer Pegasus.\n\n"
    "I am Sol Chevalsky!\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Why are you acting like\n"
    "this?\n\n"
    "It's not too late.\n\n"
    "Return Reshef the Dark Being\n"
    "to its prison.\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, PORTRAIT_POSITION_AUTO,
    "What? Why should I do that?\n\n"
    "When Reshef gains full\n"
    "power, it would create a\n\n"
    "wonderful world!\n\n"
    "Why can you not accept that?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "He is under the spell of the\n"
    "Dark Being...\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "To complete the resurrection\n"
    "of Reshef the Dark Being...\n\n"
    "There is no greater\n"
    "sacrifice...\n\n"
    "Than the spirit of a\n"
    "defeated duelist!\n\n"
    "And Yugi boy...\n\n"
    "The only duelist to have\n"
    "beaten me...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_316)
SET_OBJECT_POSITION(SPRITE_MILLENNIUM_PUZZLE_PART_2, 64, 42, 0)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, PORTRAIT_POSITION_AUTO,
    "I have his power right here.\n\n"
    "Fufufu... There are no\n"
    "duelists left who can beat\n\n"
    "me.\n\n"
    "Therefore, you will lose...\n\n"
    "And I will sacrifice you to\n"
    "Reshef the Dark Being.\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "He has the pieces of the\n"
    "Millennium Puzzle...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_316)
SET_OBJECT_POSITION(SPRITE_MILLENNIUM_PUZZLE_PART_2, 128, 96, 0)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_HAPPY, PORTRAIT_POSITION_AUTO,
    "Come, the preparations have\n"
    "been made.\n\n"
    "We will duel, and you will\n"
    "taste defeat!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "There is no choice. Please,\n"
    "{PLAYER}.\n\n"
    "You must free Pegasus's\n"
    "spirit from Reshef.\n\n"
)
DUEL(DUELIST_ISHIZU_121)
CHECK_FLAG(EVENT_FLAG_OBTAINED_PHOENIX_MODE)
PLAY_MUSIC(MUSIC_336)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SLIFER_FULL_ART)
PLAY_MUSIC(MUSIC_335)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_OBELISK_FULL_ART)
PLAY_MUSIC(MUSIC_337)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RA_FULL_ART)
PLAY_MUSIC(MUSIC_350)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_GODS_ATTACK_RESHEF_WHITE_FADE)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Noooooooooooo!\n\n"
)
SPECIAL(25)
PLAY_MUSIC(MUSIC_317)
SLIDE_OBJECT(SPRITE_PEGASUS, 2, 14)
DELAY(16)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_DEFEATED, PORTRAIT_POSITION_AUTO,
    "It can't be...\n"
    "Unbelievable...\n\n"
    "How could I lose with the\n"
    "power of Reshef?\n\n"
)
HIDE_PORTRAIT()
PLAY_MUSIC(MUSIC_318)
SPECIAL(21)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_33)
SPECIAL(24)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_PEGASUS | SPRITE_ISHIZU)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 0, 0)
DELAY(8)
WALK_OBJECT_Y(SPRITE_ISHIZU, 62)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Reshef the Dark Being!\n\n"
    "I command you to return to\n"
    "the stone tablet!\n\n"
)
HIDE_PORTRAIT()
DELAY(4)
PLAY_MUSIC(MUSIC_351)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RESHEF_BEAM)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(SPRITE_ISHIZU, 0, 16)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(0, 0, 8)
PLAY_MUSIC(MUSIC_284)
SLIDE_OBJECT(SPRITE_PEGASUS, 0, 24)
DELAY(48)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 4, 0)
DELAY(4)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_RIGHT, 8, 0)
DELAY(6)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 4, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_RIGHT, 8, 0)
DELAY(6)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 4, 0)
DELAY(4)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_RIGHT, 8, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_RIGHT, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_LEFT, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 0, 0)
DELAY(32)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_RESHEF_DEFEATED)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Gwah! Wh-what... What is\n"
    "happening?!\n\n"
    "Noooo! What happened to me?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(0, 60)
MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
WALK_OBJECT_X(SPRITE_ISHIZU, 44)
WALK_OBJECT_Y(SPRITE_ISHIZU, 64)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You seem to have finally\n"
    "awoken from your nightmare.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SAD, PORTRAIT_POSITION_AUTO,
    "What... I almost ruined us\n"
    "all...\n\n"
    "Even though I was under\n"
    "control, that is no\n\n"
    "excuse...\n\n"
    "I gathered the spirits of\n"
    "defeated duelists...\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Reshef needs their negative\n"
    "energy to initiate its\n\n"
    "final ritual.\n\n"
)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_PEGASUS)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "The castle is sealed inside\n"
    "a protective sphere...\n\n"
    "There is no escape from\n"
    "Reshef's final ritual.\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SURPRISED, PORTRAIT_POSITION_AUTO,
    "The final ritual? Of the\n"
    "ancients?\n\n"
    "Reshef is using negative\n"
    "energy?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_319)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_UNUSED_35)
DELAY(8)
CONDITION_CHECK(1)
PLAY_MUSIC(MUSIC_RESHEF)
SPECIAL(22)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_PEGASUS | SPRITE_ISHIZU)
DELAY(8)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Reshef is regaining its\n"
    "form...\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SAD, PORTRAIT_POSITION_AUTO,
    "It's hopeless... We're\n"
    "finished.\n\n"
    "All the duels that {PLAYER}\n"
    "fought to get here...\n\n"
    "All the negative energies of\n"
    "the defeated duelists...\n\n"
    "Reshef has all their power.\n\n"
    "The Dark Being has risen...\n\n"
    "We have no hope for\n"
    "defeating it.\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "A complete victory in a duel\n"
    "is needed to consummate the\n\n"
    "ritual.\n\n"
    "The Dark Being has grown\n"
    "infinitely powerful...\n\n"
    "{PLAYER} has also grown\n"
    "strong, but...\n\n"
)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_0)
WALK_OBJECT_Y(SPRITE_SETO, 76)
DELAY(16)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "What are you afraid of,\n"
    "{PLAYER}?\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "Use my card and win!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_YUGI, 68)
WALK_OBJECT_Y(SPRITE_JOEY, 76)
DELAY(16)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}!\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Kaiba's right, {PLAYER}!\n\n"
    "I don't believe this story\n"
    "about a final ritual...\n\n"
    "But I know you'll win!\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SAD, PORTRAIT_POSITION_AUTO,
    "Yugi boy... I have treated\n"
    "you terribly...\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_PEGASUS)
DELAY(8)
PLAY_MUSIC(MUSIC_316)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_2, 80, 64, 0, 0, 0)
DELAY(32)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, SPRITE_YUGI)
DELAY(8)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_RIGHT, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_320)
SLIDE_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_2, 1, 16)
DELAY(32)
SHOW_OBJECT(SPRITE_MILLENNIUM_PUZZLE_PART_2, 128, 96, 0, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_YUGI, DIRECTION_DOWN, 0, 0)
DELAY(48)
PLAY_MUSIC(MUSIC_218)
LOAD_SPRITE(4, SPRITE_ATEM)
DELAY(96)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Wh-what? Is this a miracle?\n"
    "It's fantastic!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_UP, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You have nothing to fear\n"
    "against Reshef!\n\n"
    "My spirit is united with all\n"
    "the duelists I've faced.\n\n"
    "Including yours, {PLAYER}.\n\n"
    "With all our souls united as\n"
    "one...\n\n"
    "Take hold of the true\n"
    "duelist's spirit!\n\n"
    "Use it to defeat the Dark\n"
    "Being!\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "All of us together... We'll\n"
    "destroy Reshef!\n\n"
)
PLAY_MUSIC(MUSIC_333)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RED_EYES_FULL_ART)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Yeah!\n\n"
)
PLAY_MUSIC(MUSIC_333)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_DARK_MAGICIAN_FULL_ART)
DELAY(16)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Humph... Come Blue-Eyes!\n\n"
)
PLAY_MUSIC(MUSIC_333)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_BLUE_EYES_WHITE_DRAGON_FULL_ART)
DELAY(16)
PLAY_MUSIC(MUSIC_352)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_CUTIN_YUGI_JOEY_KAIBA)
TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Go!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(8)
PLAY_MUSIC(MUSIC_343)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_TRIPLE_DRAGON_ATTACK_RESHEF)
DELAY(16)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SURPRISED, PORTRAIT_POSITION_AUTO,
    "The sacred souls of\n"
    "duelists!\n\n"
)
TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_POSITION_AUTO,
    "The pure and proud spirits\n"
    "of duelists have united!\n\n"
    "Perhaps this...\n\n"
)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Now, {PLAYER}!\n\n"
    "Seal Reshef forever!\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
WALK_OBJECT_Y(0, 50)
DELAY(16)
DUEL(DUELIST_ATEM_122)
PLAY_MUSIC(MUSIC_RESHEF_DEFEATED)
PLAY_MUSIC(MUSIC_391)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SPARKS_ON_RESHEF_DEATH)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "Is... Is it over?\n\n"
)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Reshef fed on the darkness\n"
    "in duelists' souls.\n\n"
    "It gained power from the\n"
    "fear of defeat.\n\n"
    "But our proud duelist\n"
    "spirits won in the end.\n\n"
)
TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I wouldn't be so hasty..\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_LEFT, 4, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_LEFT, 7, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 6, 0)
DELAY(8)
WALK_OBJECT_X(SPRITE_PEGASUS, 64)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 4, 0)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_UP, 4, 0)
DELAY(8)
WALK_OBJECT_Y(SPRITE_PEGASUS, 44)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_JOEY, DIRECTION_UP, 0, 0)
MOVE_OBJECT(SPRITE_ISHIZU, DIRECTION_UP, 0, 0)
DELAY(8)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 0, 0)
DELAY(32)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ATEM | SPRITE_JOEY)
DELAY(8)
PLAY_MUSIC(MUSIC_392)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_RESHEF_ENTERS_PEGASUS)
DELAY(8)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SURPRISED, PORTRAIT_POSITION_AUTO,
    "Noooooooooo!\n\n"
    "Reshef! It's worming itself\n"
    "into my soul!\n\n"
    "It's found the darkness in\n"
    "my heart!\n\n"
    "Why? Do I fear defeat?\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SAD, PORTRAIT_POSITION_AUTO,
    "Reshef the Dark Being...\n\n"
    "I let you into my soul to\n"
    "exploit its darkness...\n\n"
    "I helped release you...\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "But... I won't lose to you!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_PEGASUS, 38)
DELAY(8)
WALK_OBJECT_X(SPRITE_PEGASUS, 60)
DELAY(8)
MOVE_OBJECT(SPRITE_PEGASUS, DIRECTION_DOWN, 0, 0)
DELAY(32)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Now, {PLAYER}!\n\n"
    "Seal me while Reshef remains\n"
    "trapped inside!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | SPRITE_SETO | SPRITE_ATEM | SPRITE_JOEY)
DELAY(8)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_SAD, PORTRAIT_POSITION_AUTO,
    "Nothing can forgive me for\n"
    "what I've done...\n\n"
    "I have to atone for my\n"
    "crimes...\n\n"
)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_SOL_CHEVALSKY_TEETH_GRITTED, PORTRAIT_POSITION_AUTO,
    "Quickly, before Reshef\n"
    "consumes my soul!\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(32)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, there's no other\n"
    "choice.\n\n"
    "You must honor Pegasus as a\n"
    "true duelist.\n\n"
)
HIDE_PORTRAIT()
DELAY(32)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(32)
CHECK_FLAG(EVENT_FLAG_OBTAINED_PHOENIX_MODE)
PLAY_MUSIC(MUSIC_350)
SHOW_OVERWORLD_GRAPHIC(GRAPHIC_GODS_ATTACK_RESHEF_WHITE_FADE)
SHOW_OBJECT(SPRITE_PEGASUS, 128, 96, 0, 0, 0)
TALK(PORTRAIT_SOL_CHEVELSKY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Thank you, {PLAYER}.\n\n"
    "I'm glad my final opponent\n"
    "was you.\n\n"
)
SPECIAL(32)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "It's over, {PLAYER}.\n\n"
)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | SPRITE_ISHIZU | SPRITE_SETO | SPRITE_ATEM | SPRITE_JOEY)
DELAY(8)
PLAY_MUSIC(MUSIC_265)
SET_FLAG(EVENT_FLAG_SHAKE_SCREEN)
PLAY_MUSIC(MUSIC_ESCAPE_FROM_PEGASUS_CASTLE)
DELAY(32)
MOVE_OBJECT(SPRITE_SETO, DIRECTION_UP, 4, 0)
DELAY(8)
TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
    "This castle's not going to\n"
    "hold much longer.\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(SPRITE_JOEY, OBJECT_EFFECT_JUMPING)
DELAY(8)
WALK_OBJECT_X(SPRITE_JOEY, 60)
MOVE_OBJECT(SPRITE_JOEY, DIRECTION_UP, 0, 0)
DELAY(8)
TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, PORTRAIT_POSITION_AUTO,
    "I'll say! Let's get out of\n"
    "here!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_ATEM, DIRECTION_DOWN, 0, 0)
DELAY(16)
WALK_OBJECT_X(SPRITE_ISHIZU, 52)
WALK_OBJECT_Y(SPRITE_ISHIZU, 96)
WALK_OBJECT_Y(SPRITE_SETO, 96)
DELAY(16)
WALK_OBJECT_Y(SPRITE_ATEM, 56)
DELAY(16)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_ATEM, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, we have to get\n"
    "out!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
WALK_OBJECT_Y(SPRITE_JOEY, 96)
WALK_OBJECT_Y(SPRITE_ATEM, 96)
WALK_OBJECT_Y(0, 72)
DELAY(32)
MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
DELAY(64)
WALK_OBJECT_Y(0, 96)
SET_FLAG(EVENT_FLAG_FINISHED_GAME)
SET_FLAG(EVENT_FLAG_UNLOCKED_HALL_OF_ETERNITY)
FADE_SCREEN(1)
WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 9, 0, 0)

EVENT_SCRIPT_REPLACEMENT(0x08EF054C, map_55_state_01_08EF054C, 0x08EF0558, 0x08F04040)
PLAY_MUSIC(MUSIC_350)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_GODS_ATTACK_RESHEF_PHOENIX_RA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF051C, map_55_state_01_08EF051C, 0x08EF0528, 0x08F04040)
PLAY_MUSIC(MUSIC_RESHEF)
  SPECIAL(23)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EF04F8, map_55_state_01_08EF04F8, 0x08EF0504, 0x08F04040)
PLAY_MUSIC(MUSIC_336)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_SLIFER_FULL_ART)
  PLAY_MUSIC(MUSIC_335)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_OBELISK_FULL_ART)
  PLAY_MUSIC(MUSIC_388)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_PHOENIX_RA_FULL_ART)
  PLAY_MUSIC(MUSIC_350)
  SHOW_OVERWORLD_GRAPHIC(GRAPHIC_GODS_ATTACK_RESHEF_PHOENIX_RA)
  FALLTHROUGH()
END_EVENT_SCRIPT()
