#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_49_state_01: map 49 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EDEBF0, map_49_state_01_08EDEBF0, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  SET_FLAG(EVENT_FLAG_UNLOCKED_PEGASUS_CASTLE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDEBD8, map_49_state_01_08EDEBD8, 0x08EDEBE4, 0x08F0404C)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Gawry nida! Gawry nida!",
      "You'll go no further! Gawry!"
  )
  DUEL(DUELIST_CHEVALIER_112)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDEBE4, map_49_state_01_08EDEBE4, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_DUNGEON)
  TALK(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "G-gawry n-nida... M-master... G-gaah...")
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
