#include "event_macros.h"
#include "overworld.h"

/* map_09_state_01: map 9 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E62160, map_09_state_01_08E62160, 0x08E6216C, 0x08E62178)
  PLAY_MUSIC(12)
  SET_FLAG(EVENT_FLAG_SAW_INTRO_CUTSCENE)
  DELAY(32)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Now I put dis Monsta Card in\nhere, like so...\n\nAnd voila!\nI'm good to go!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, how's adjustin'\nyour deck comin' along?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Perfect\nLousy{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6216C, map_09_state_01_08E6216C, 0x08E62184, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You sure about dat?\nLet the expert, the\n\none-and-only Joey Wheeler,\ncheck it out!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(REACTION_ELLIPSIS, 16384)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 0)
  LANGUAGE_TEXT(0, "Uh... It's cool to be\nconfident about your\n\nskills.\n\nBut you still have lots of\nwork to do on this Deck\n\nbefore it's any good.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(274)
  REACTION(REACTION_SWEATDROP, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hey,\ndon't feel bad. I know you\n\ncan construct an awesome\ndeck, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62184, map_09_state_01_08E62184, 0x08E62190, 0x08E6219C)
  LANGUAGE_TEXT(0, "Alright guys, I'm gonna\ntotally rock with this\n\ndeck today!\n\nMan, I can't wait for the\nDuel Express train to come!\n\nIt's been too long since\nI've dueled in a\n\ntournament!\n\n{PLAYER} and Yugi and I are\ngonna own this tourney!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}By the way...\nLet's go for it!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62190, map_09_state_01_08E62190, 0x08E621A8, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Huh, what's wrong? Oh yeah!\nWhere the heck's Yugi?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621A8, map_09_state_01_08E621A8, 0x08E621B4, 0x08E621C0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 1, 32, 0)
  MOVE_OBJECT(14, 3, 32, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Oh man, this stinks!\nLook at the time already!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(275)
  REACTION(REACTION_ANGRY, 16384)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, 0)
  LANGUAGE_TEXT(0, "He's late!\n\nC'mon Yugi...\nHow can ya even think\n\nabout being late on a day\nlike this!\n\nIf he doesn't get here\nsoon, we'll miss the Duel\n\nExpress!\n\nAnd he was the one who\npromised dat the three of\n\nus were gonna take the\ntrain together!\n\nMan, dat Yugi!\nArrrrgh!\n\nIf he doesn't get here, he\ncan give me all his rare\n\ncards and I still won't\nforgive him!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(212)
  SHOW_OBJECT(13, 50, 74, 0, 0, 0)
  MOVE_OBJECT(13, 2, 2, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 1)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 1)
  PLAY_MUSIC(400)
  LANGUAGE_TEXT(0, "{PLAYER}, everything's\nhorrible!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(REACTION_QUESTION_MARK, 1)
  DELAY(16)
  WALK_OBJECT_Y(13, 62)
  MOVE_OBJECT(13, 3, 8, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 1)
  LANGUAGE_TEXT(0, "My other self...\nThe Millennium Puzzle...\n\nMy Puzzle is gone, along\nwith the spirit inside!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 16385)
  DELAY(8)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SAD, 1)
  LANGUAGE_TEXT(0, "When I woke up this morning,\nit was gone...\n\nI... I... What am I\nsupposed to do?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  WALK_OBJECT_Y(14, 56)
  WALK_OBJECT_X(14, 58)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Hey, we can't waste time\nstandin' here and talkin'!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 3, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, whattaya think\nwe should do?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{CARD_1}Let's go look for it!\nLeave it to me!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621B4, map_09_state_01_08E621B4, 0x08E621CC, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Okay! Then that's what\nwe're gonna do! You got\n\nit, Yugi?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621CC, map_09_state_01_08E621CC, 0x08E621D8, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I won't stop until I find my\ndearest friend...\n\nI promise!\n\nI'm counting on you,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621D8, map_09_state_01_08E621D8, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  WARP(1, 1, 4, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E621C0, map_09_state_01_08E621C0, 0x08E621CC, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yeah! That's the spirit,\n{PLAYER}!\n\nYugi, let's go with\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6219C, map_09_state_01_08E6219C, 0x08E621A8, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yeah! But don't think I'm\ngonna let you win\n\n{PLAYER}. And that goes\ndouble for Yugi.\n\nSpeaking of who...\nWhy isn't Yugi here yet?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62178, map_09_state_01_08E62178, 0x08E62184, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER}, I guess ya still\nhave lots of work to do.\n\nBut you can learn from the\nexpert, the one-and-only\n\nJoey Wheeler, on making\ngreat decks.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E62154, map_09_state_01_08E62154, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(0)
  CUTSCENE(8)
  WARP(9, 2, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
