#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_33_state_03: map 33 state 3 */

EVENT_SCRIPT_REPLACEMENT(0x08EBEB38, map_33_state_03_08EBEB38, 0x08EBEB44, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_WEEVIL)
  LOAD_SPRITE(2, SPRITE_LUMIS)
  LOAD_SPRITE(3, SPRITE_UMBRA)
  PLAY_MUSIC(MUSIC_407)
  TALK(PORTRAIT_UMBRA, "You listen to us...")
  TALK(PORTRAIT_LUMIS, "You're going to join us as a Neo Ghoul.")
  TALK(PORTRAIT_WEEVIL, "You're smart as a spider to recruit me.")
  TALK(PORTRAIT_UMBRA, "You'll join us?")
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, "Hyohyohyo! Okay!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB44, map_33_state_03_08EBEB44, 0x08EBEB50, 0x08EBEB5C)
  WALK_OBJECT_Y(0, 46)
  WALK_OBJECT_X(0, 62)
  WALK_OBJECT_Y(13, 52)
  WALK_OBJECT_X(13, 56)
  WALK_OBJECT_Y(14, 40)
  WALK_OBJECT_X(14, 56)
  TEXT("{CARD_1}Don't join them!\nTraitor!{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB50, map_33_state_03_08EBEB50, 0x08EBEB68, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO, "Hyohyohyohyo!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_2 | OBJECT_3)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyo! Just kidding!",
      "There's no way I'd join you wimpy worms!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB68, map_33_state_03_08EBEB68, 0x08EBEB74, EVENT_NOP)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "H-how dare you...")
  TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You tricked us!")
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You leave us with no options!")
  TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "We'll settle this in a duel!")
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I'm not falling into your web! I won't take on two",
      "duelists at the same time."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO, "{PLAYER}, you duel one of them.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB74, map_33_state_03_08EBEB74, 0x08EBEB80, 0x08EBEB98)
  TEXT("{CARD_1}Lumis\nUmbra{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB80, map_33_state_03_08EBEB80, 0x08EBEB8C, 0x08F0404C)
  WALK_OBJECT_Y(1, 52)
  WALK_OBJECT_X(1, 78)
  WALK_OBJECT_Y(0, 40)
  WALK_OBJECT_X(0, 78)
  DELAY(16)
  TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "You'll make an excellent prize for Master Keith!")
  DUEL(DUELIST_LUMIS_068)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB8C, map_33_state_03_08EBEB8C, 0x08EBEBB0, EVENT_NOP)
  PLAY_MUSIC(MUSIC_243)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "How dare you!")
  WALK_OBJECT_Y(3, 68)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(3, 16)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO, "You were just lucky!")
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 34)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO, "Don't you forget about me!")
  WALK_OBJECT_X(2, 16)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(1, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBB0, map_33_state_03_08EBEBB0, 0x08EBEBBC, EVENT_NOP)
  WALK_OBJECT_X(13, 64)
  WALK_OBJECT_X(14, 64)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyo! Long time no see.",
      "There are lots of rare bugs here in China."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "This guy bugs me, but I gotta admit, he is a good",
      "duelist.",
      "{PLAYER}, let's get him to help us beat the Neo",
      "Ghouls."
  )
  PLAY_MUSIC(MUSIC_332)
  FADE_SCREEN(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBBC, map_33_state_03_08EBEBBC, 0x08EBEBC8, 0x08EBEBD4)
  PLAY_MUSIC(MUSIC_702)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Humph. They ignored me and overran the Town of Domino",
      "instead?",
      "That bugs me! How can they ignore the best duelist!",
      "Count me in to help you!"
  )
  MOVE_OBJECT(1, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_Y(1, 68)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(1, 16)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  SET_FLAG(EVENT_FLAG_DEFEATED_LUMIS_AND_UMBRA)
  CONDITION_CHECK(0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBC8, map_33_state_03_08EBEBC8, EVENT_NOP, EVENT_NOP)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Let's go find another ally!")
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBD4, map_33_state_03_08EBEBD4, EVENT_NOP, EVENT_NOP)
  MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Okay! Let's also get back to the Town of Domino!")
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB98, map_33_state_03_08EBEB98, 0x08EBEBA4, 0x08F0404C)
  WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 78)
  WALK_OBJECT_Y(0, 52)
  WALK_OBJECT_X(0, 78)
  DELAY(16)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "I'll make you regret defying the Neo Ghouls!")
  DUEL(DUELIST_UMBRA_069)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBA4, map_33_state_03_08EBEBA4, 0x08EBEBB0, EVENT_NOP)
  PLAY_MUSIC(MUSIC_243)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "How dare you!")
  WALK_OBJECT_Y(3, 68)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(3, 16)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO, "You were just lucky!")
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 34)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO, "Don't you forget about me!")
  WALK_OBJECT_X(2, 16)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB5C, map_33_state_03_08EBEB5C, 0x08EBEB68, EVENT_NOP)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Traitor? Hyohyohyo! Why am I a traitor?",
      "I don't remember being on your side!"
  )
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Fufufu... He'll make an excellent addition to our",
      "ranks!"
  )
  TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Yes! He's one of ours! He's a member of the Neo Ghouls!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyo! Actually, I don't want to be on your team",
      "either!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2 | OBJECT_3)
  DELAY(8)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "But... But you just agreed to join us.")
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyohyo!",
      "I changed my mind!"
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
