#include "event_macros.h"
#include "overworld.h"

/* map_26_state_02: map 26 state 2 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3B78, map_26_state_02_08EA3B78, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  WALK_OBJECT_Y(2, 70)
  WALK_OBJECT_Y(2, 40)
  WALK_OBJECT_Y(3, 40)
  WALK_OBJECT_Y(3, 70)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_ANGRY, PORTRAIT_LEFT)
  TEXT("C'mon, boys! Work harder,\nyou two!\n\nAt this rate, you'll never\nbecome real duelists.\n\nIt'll take you a hundred\nyears to reach my skill\n\nlevel!\n\n")
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_LEFT)
  TEXT("Wh-why are we working for\nMai?\n\n")
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_LEFT)
  TEXT("What'd we do to deserve\nthis?\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  PLAY_MUSIC(271)
  REACTION(REACTION_EXCLAMATION_MARK, 2)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Oh, hi Joey!\n\nDo you want me to train you\ntoo?\n\n")
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_LEFT)
  TEXT("Why would I need training?\n\n")
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Ahahaha, I'm only joking.\n\nMinion One and Minion Two,\nstop slacking off!\n\n")
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, PORTRAIT_LEFT)
  TEXT("M-Minion One?\n\n")
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_LEFT)
  TEXT("Two?!\n\n")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("This sucks...\n\n")
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT)
  TEXT("Wipe those frowns off your\nfaces.\n\nIf you really want to\nimprove your dueling\n\nskills, you should hit the\nroad on a training quest.\n\n")
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("A training quest?\n\n")
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_LEFT)
  TEXT("I'm going! I am soooo going!\n\nAnything beats getting\nworked like a mule.\n\nI would rather be anywhere\nelse but here!\n\nDuke, let's go!\n\n")
  WALK_OBJECT_Y(2, 70)
  WALK_OBJECT_X(2, 52)
  WALK_OBJECT_Y(2, 96)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("S-sure. Wait for me,\nTristan.\n\n")
  WALK_OBJECT_X(3, 60)
  WALK_OBJECT_Y(3, 96)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_MAI_SWEATDROP, PORTRAIT_LEFT)
  TEXT("Those two... I was only\nkidding. I mean, what's a\n\ntraining quest anyway?\n\nSigh... Now that my minions\nare gone, I have to do my\n\nown work.\n\n")
  SET_FLAG(EVENT_FLAG_SAW_TRISTAN_AND_DUKE_LEAVING_ON_A_TRAINING_QUEST)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3B84, map_26_state_02_08EA3B84, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  TEXT("Tristan and Duke left on a\ntraining quest.\n\nBut what are they training\nfor?\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
