#include "event_macros.h"
#include "overworld.h"

/* map_06_state_06: map 6 state 6 */

EVENT_SCRIPT_REPLACEMENT(0x08E5CCC0, map_06_state_06_08E5CCC0, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(11)
  DELAY(8)
  WALK_OBJECT_X(4, 52)
  DELAY(8)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SURPRISED, 1)
  LANGUAGE_TEXT(0, "Eeek!\n\n")
  LANGUAGE_TEXT(1, "Hiiii !\n\n")
  LANGUAGE_TEXT(2, "Iiiiiiih!\n\n")
  LANGUAGE_TEXT(3, "Ehiii!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eeeh!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_ANGRY, 1)
  LANGUAGE_TEXT(0, "Hey! What do you think\nyou're doing to Serenity?\n\n")
  LANGUAGE_TEXT(1, "H\xe9 ! Qu'est-ce tu fais\navec Serenity ?\n\n")
  LANGUAGE_TEXT(2, "He, was stellst du da mit\nSerenity an?\n\n")
  LANGUAGE_TEXT(3, "Ehi! Cosa vorresti\nfare a Serenity?\n\n")
  LANGUAGE_TEXT(4, "\xa1Eh! \xbfQu\xe9 crees que\nhaces a Serenity?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I'll protect you, Serenity!\n\n")
  LANGUAGE_TEXT(1, "Je vais te prot\xe9ger,\nSerenity !\n\n")
  LANGUAGE_TEXT(2, "Ich besch\xfctze dich,\nSerenity!\n\n")
  LANGUAGE_TEXT(3, "Ti proteggo io, Serenity!\n\n")
  LANGUAGE_TEXT(4, "\xa1Yo te proteger\xe9,\nSerenity!\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(1, 52)
  WALK_OBJECT_X(2, 52)
  WALK_OBJECT_X(4, 64)
  MOVE_OBJECT(4, 1, 0, 0)
  WALK_OBJECT_Y(1, 44)
  WALK_OBJECT_X(1, 56)
  WALK_OBJECT_Y(2, 52)
  WALK_OBJECT_X(2, 56)
  DELAY(16)
  PORTRAIT(PORTRAIT_NEO_GHOUL, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Tsk...\n\n")
  LANGUAGE_TEXT(1, "Tch...\n\n")
  LANGUAGE_TEXT(2, "Tss...\n\n")
  LANGUAGE_TEXT(3, "Pfui...\n\n")
  LANGUAGE_TEXT(4, "\xa1Chs!...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 144)
  PLAY_MUSIC(31)
  MOVE_OBJECT(1, 1, 0, 0)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Are you okay, Serenity?\n\n")
  LANGUAGE_TEXT(1, "Ca va, Serenity ?\n\n")
  LANGUAGE_TEXT(2, "Ist alles in Ordnung,\nSerenity?\n\n")
  LANGUAGE_TEXT(3, "Tutto bene, Serenity?\n\n")
  LANGUAGE_TEXT(4, "\xbfEst\xe1s bien, Serenity?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Yes, I'm fine, Tristan.\n\nAnd Duke, thank you too.\n\n")
  LANGUAGE_TEXT(1, "Oui, je vais bien,\nTristan.\n\nEt merci \xe0 toi, Duke.\n\n")
  LANGUAGE_TEXT(2, "Ja, alles in Ordnung,\nTristan.\n\nUnd Duke, Danke.\n\n")
  LANGUAGE_TEXT(3, "S\xec, sto bene, Tristan.\n\nGrazie, Duke.\n\n")
  LANGUAGE_TEXT(4, "S\xed, muy bien, Tristan.\n\nY, Duke, gracias.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "You can count on me,\nSerenity.\n\nI won't let the Neo Ghouls\nlay a finger on you.\n\n")
  LANGUAGE_TEXT(1, "Tu peux compter\nsur moi, Serenity.\n\nJe te prot\xe9gerai\ndes Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "Du kannst dich auf mich\nverlassen, Serenity.\n\nDie Neo Ghouls werden dir\nkein Haar kr\xfcmmen.\n\n")
  LANGUAGE_TEXT(3, "Puoi contare su di\nme, Serenity.\n\nNon permetter\xf2 ai Neo\nGhouls di farti del male.\n\n")
  LANGUAGE_TEXT(4, "Puedes contar conmigo,\nSerenity.\n\nNo permitir\xe9 a los\nNeo Ghouls ponerte\n\nun dedo encima.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "That goes double for me!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, moi aussi !\n\n")
  LANGUAGE_TEXT(2, "He, ich werde das auch\nnicht zulassen!\n\n")
  LANGUAGE_TEXT(3, "Ehi, neanche io!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eh, ni yo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "It's okay Tristan.\nSerenity's safe in my arms.\n\nShe doesn't need you.\n\n")
  LANGUAGE_TEXT(1, "Oh, non. Je peux la\nprot\xe9ger tout seul.\n\n")
  LANGUAGE_TEXT(2, "Oh, nein. Ich kann Serenity\nalleine besch\xfctzen.\n\n")
  LANGUAGE_TEXT(3, "Oh, no. Posso proteggere\nSerenity da solo.\n\n")
  LANGUAGE_TEXT(4, "Oh, no. Puedo proteger\na Serenity yo solo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_TEETH_GRITTED, 1)
  LANGUAGE_TEXT(0, "Devlin, you...\n\n")
  LANGUAGE_TEXT(1, "Devlin, tu...\n\n")
  LANGUAGE_TEXT(2, "Devlin, du...\n\n")
  LANGUAGE_TEXT(3, "Devlin, tu...\n\n")
  LANGUAGE_TEXT(4, "Devlin, t\xfa...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8)
  DELAY(8)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Oh, hi {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Oh, salut, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Oh, hallo, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Oh, ciao, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh!, hola, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 6)
  DELAY(16)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 82)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 82)
  DELAY(16)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, you don't have to\nworry about us.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, ne t'inqui\xe8te\npas pour nous.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, mach dir keine\nSorgen um uns hier.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, non ti\npreoccupare per noi.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, no te\npreocupes por\n\nnuestra presencia.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Yeah, I'll protect Serenity.\n\n")
  LANGUAGE_TEXT(1, "Ouais, on prot\xe8ge Serenity.\n\n")
  LANGUAGE_TEXT(2, "Ja, wir besch\xfctzen\nSerenity schon.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0, scorteremo\nnoi Serenity.\n\n")
  LANGUAGE_TEXT(4, "S\xed, cuidaremos\nde Serenity.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(102)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCCC, map_06_state_06_08E5CCCC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, Serenity's safe\nwith me. I can't say the\n\nsame about loverboy over\nthere...\n\nThe Neo Ghouls don't scare\nme one bit.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, avec moi, Serenity\nest en s\xe9curit\xe9.\n\nLes Neo Ghouls ne\nme font pas peur.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, du kannst mir\nSerenity anvertrauen.\n\nDie Neo Ghouls machen mir\nkeine Angst.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, Serenity\nla puoi affidare a me.\n\nI Neo Ghouls non mi fanno\nminimamente paura.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, puedes\nconfiarme a Serenity.\n\nLos Neo Ghouls no\nme asustan nada.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCD8, map_06_state_06_08E5CCD8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What? You don't have the\ntime to duel me!\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Mais tu\nn'as pas le temps !\n\n")
  LANGUAGE_TEXT(2, "Was? Daf\xfcr hast du\nkeine Zeit!\n\n")
  LANGUAGE_TEXT(3, "Cosa? Non hai il\ntempo per farlo!\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? \xa1No tienes\ntiempo de hacerlo!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCE4, map_06_state_06_08E5CCE4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, let's drive the\nNeo Ghouls out of town!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER},\nd\xe9barrassons-nous\n\nd'abord des Neo Ghouls.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, verscheuchen\nwir erst die Neo Ghouls.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, per prima cosa\ncacciamo via i Neo Ghouls.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, echemos a los\nNeo Ghouls primero.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCF0, map_06_state_06_08E5CCF0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I don't think we have any\ntime to spare.\n\n")
  LANGUAGE_TEXT(1, "Je ne crois pas qu'on\nait du temps \xe0 perdre.\n\n")
  LANGUAGE_TEXT(2, "Ich glaube nicht, dass\nwir daf\xfcr Zeit haben.\n\n")
  LANGUAGE_TEXT(3, "Non penso che abbiamo\ntempo da perdere.\n\n")
  LANGUAGE_TEXT(4, "No creo que tengamos\ntiempo que perder.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E5CCFC, map_06_state_06_08E5CCFC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, I'm fine. Please\ndon't worry about me.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, \xe7a va. Ne\nt'inqui\xe8te pas pour moi.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, es geht mir gut.\nMach dir keine Sorgen.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, io sto bene.\nNon ti preoccupare per me.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, estoy bien.\nPor favor, no te\n\npreocupes por m\xed.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
