#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_53_state_02: map 53 state 2 */

LOAD_SPRITE(1, SPRITE_MEDIUM_RUBBLE)
LOAD_SPRITE(2, SPRITE_SMALL_RUBBLE)
LOAD_SPRITE(3, SPRITE_BIG_RUBBLE)
LOAD_SPRITE(4, SPRITE_MEDIUM_RUBBLE)
LOAD_SPRITE(5, SPRITE_SMALL_RUBBLE)
LOAD_SPRITE(6, SPRITE_BIG_RUBBLE)
LOAD_SPRITE(7, SPRITE_MEDIUM_RUBBLE)
LOAD_SPRITE(8, SPRITE_SMALL_RUBBLE)
LOAD_SPRITE(9, SPRITE_BIG_RUBBLE)
LOAD_SPRITE(10, SPRITE_MEDIUM_RUBBLE)
LOAD_SPRITE(11, SPRITE_SMALL_RUBBLE)
LOAD_SPRITE(12, SPRITE_PEGASUS)
DELAY(128)
FADE_SCREEN(8)
CUTSCENE(7)
DELAY(48)
RESTORE_LIFE_POINTS()
SAVE()
SPECIAL(20)
