#include "event_macros.h"

/* map_00_state_05: map 0 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08E34B14, map_00_state_05_08E34B14, 0x08E34B2C, 0x08E34B38)
  CHECK_FLAG(57)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B2C, map_00_state_05_08E34B2C, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(16, 0, 8)
  LANGUAGE_TEXT(0, "Bandit Keith is also\nsearching for the\n\nMillennium Items...\n\nI am afraid that he\ncomplicates matters\n\ngreatly.\n\nOur need for urgency has\nincreased.\n\nReshef the Dark Being is\ninsidious.\n\nHe exploits the weaknesses\nin the souls of duelists.\n\nI hope that Bandit Keith\ndoes not succumb to his\n\npower...\n\nFortunately, Bandit Keith\ndid not find the Millennium\n\nRing.\n\nThat is a ray of hope among\nall this darkness.\n\nFour Millennium Items\nremain...\n\nAnd the next one is in.")
  LANGUAGE_TEXT(1, "Ken est \xe9galement\n\xe0 la recherche des\n\nObjets du mill\xe9nium...\n\nJ'ai bien peur qu'il\ncomplique les choses.\n\nNous devons plus que\njamais nous d\xe9p\xeacher.\n\nReshef, l'Etre des t\xe9n\xe8bres\nest un tra\xeetre.\n\nIl exploite les failles dans\nles esprits des duellistes.\n\nJe prie pour que Ken\nne soit pas attir\xe9\n\npar son pouvoir...\n\nMais ce n'est pas Ken\nqui a trouv\xe9 l'Anneau du\n\nmill\xe9nium. Cela nous donne\nune lueur d'espoir.\n\nIl reste encore quatre\nObjets du mill\xe9nium...\n\nEt le prochain est en.")
  LANGUAGE_TEXT(2, "Keith sucht ebenfalls die\nMillenniumsgegenst\xe4nde...\n\nEr macht alles noch\nkomplizierter.\n\nWir m\xfcssen umso schneller\nhandeln.\n\nReschef der Dunkle ist\nhinterlistig.\n\nEr nutzt die Schw\xe4chen im\nVerstand der Duellanten\n\naus.\n\nIch hoffe, Keith wird nicht\nvon der Kraft angezogen...\n\nAber es war nicht Keith, der\nden Millenniumsring fand.\n\nDas gibt uns Hoffnung im\nAngesicht der Finsternis.\n\nEs sind noch vier weitere\nMillenniumsgegenst\xe4nde zu\n\nfinden...\n\nDer n\xe4chste ist in.")
  LANGUAGE_TEXT(3, "Anche Keith \xe8 in cerca\ndegli Oggetti Millenari...\n\nPurtroppo render\xe0 le\ncose pi\xf9 complicate.\n\nDobbiamo agire ancora\npi\xf9 in fretta.\n\nReshef il Tenebroso\n\xe8 insidioso.\n\nSfrutta la debolezza\nd'animo dei duellanti.\n\nSpero tanto che Keith\nnon sia attratto da\n\nquel potere...\n\nMa l'Anello Millenario\nnon \xe8 stato trovato da\n\nKeith. Abbiamo speranza nei\nconfronti dell'oscurit\xe0.\n\nCi restano altri quattro\nOggetti Millenari...\n\nE il prossimo si trova in.")
  LANGUAGE_TEXT(4, "Keith tambi\xe9n busca\nlos Objetos del Milenio...\n\nMe temo que complica\nlas cosas.\n\nTenemos que correr\na\xfan m\xe1s.\n\nReshef, el Ser Oscuro\nes insidioso.\n\nExplota la debilidad en los\nesp\xedritus de los duelistas.\n\nRezo para que Keith no sea\natra\xeddo por ese poder.\n\nPero Keith no encontr\xf3 el\nAnillo del Milenio.\n\nEso nos da esperanza frente\na la oscuridad.\n\nQuedan cuatro Objetos\ndel Milenio m\xe1s...\n\nY el pr\xf3ximo est\xe1 en")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ".")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, "")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, ".")
  LANGUAGE_TEXT(1, ".")
  LANGUAGE_TEXT(2, ". ")
  LANGUAGE_TEXT(3, ".")
  LANGUAGE_TEXT(4, "")
  END_LANGUAGE_TEXT()
  DELAY(43)
  LANGUAGE_TEXT(0, "\nChina. At the Great Wall.\n\nThe Dark Being's power is\nintensifying with every\n\npassing moment.\n\nPlease find the next\nMillennium Item quickly.\n\n")
  LANGUAGE_TEXT(1, "\nChine, la Grande Muraille.\n\nLes pouvoirs de l'Etre des\nt\xe9n\xe8bres augmentent\n\nau fil des heures.\n\nIl faut vite trouver le\nprochain Objet du\n\nmill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "China.\nAn der Chinesischen Mauer.\n\nDie Macht des Dunklen\nw\xe4chst mit jeder Minute.\n\nFindet den n\xe4chsten\nMillenniumsgegenstand\n\nschnell. Bitte.\n\n")
  LANGUAGE_TEXT(3, "\nCina. La Grande Muraglia.\n\nIl potere del Tenebroso\naumenta di ora in ora.\n\nVi prego, trovate in\nfretta il prossimo\n\nOggetto Millenario.\n\n")
  LANGUAGE_TEXT(4, "\nChina. La Gran Muralla.\n\nEl poder del Ser\nOscuro crece y crece.\n\nEncontrad r\xe1pidamente el\npr\xf3ximo Objeto del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(57)
  SET_FLAG(253)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B38, map_00_state_05_08E34B38, 0x08F04040, 0x08F04040)
  PORTRAIT(16, 0, 8)
  LANGUAGE_TEXT(0, "Sol Chevalsky resurrected\nthe Dark Being...\n\nWe need the Egyptian God\nCards to stop it.\n\nWe must restore the Egyptian\nGod Cards from stone.\n\nBut in order to do so, we\nrequire the Millennium\n\nItems.\n\nThe fourth item is at the\nGreat Wall of China.\n\nPlease recover it as soon as\nyou can.\n\n")
  LANGUAGE_TEXT(1, "L'Etre des t\xe9n\xe8bres,\nressuscit\xe9 par Sol\n\nChevalsky...\nNous devons l'arr\xeater\n\n\xe0 l'aide des cartes\nde dieux.\n\nIl faut d'abord restaurer\nles cartes p\xe9trifi\xe9es.\n\nPour cela, nous aurons\nbesoin des Objets du\n\nmill\xe9nium.\n\nLe {BYTE_8253}\xe8me objet se trouve \xe0 la\nGrande Muraille de Chine.\n\nEssayez de le trouver le\nplus rapidement possible.\n\n")
  LANGUAGE_TEXT(2, "Der Dunkle wurde von\nSol Chevalsky auferweckt...\n\nWir brauchen die G\xf6tterkar-\nten, um ihn aufzuhalten.\n\nErst m\xfcssen die G\xf6tterkarten\naus ihrer Versteinerung\n\nbefreit werden. Dazu sind\ndie Millenniumsgegenst\xe4nde\n\nn\xf6tig.\n\nDer vierte Gegenstand ist an\nder Chinesischen Mauer.\n\nBesorgt ihn so schnell wie\nm\xf6glich.\n\n")
  LANGUAGE_TEXT(3, "Il Tenebroso risuscitato\nda Sol Chevalsky...\n\nDobbiamo avere le carte\ndivine per fermarlo.\n\nPrima bisogna ripristinare\nle carte divine dalla\n\npietra. Per farlo servono\ngli Oggetti Millenari.\n\nIl quarto oggetto si trova\nnella Grande Muraglia\n\ncinese. Recuperatelo pi\xf9\nin fretta che potete.\n\n")
  LANGUAGE_TEXT(4, "El Ser Oscuro resucitado\npor Sol Chevalsky...\n\nTenemos que tener las cartas\nde los dioses para\n\ndetenerlo.\n\nPrimero, hay que\nrestaurar las cartas\n\nde los dioses a su estado\nanterior.\n\nPara ello, son necesarios\nlos Objetos del Milenio.\n\nEl cuarto Objeto del Milenio\nest\xe1 en la Gran Muralla de\n\nChina. Encontradlo tan\npronto como pod\xe1is.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B20, map_00_state_05_08E34B20, 0x08E34B2C, 0x08E34B44)
  CHECK_FLAG(57)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34B44, map_00_state_05_08E34B44, 0x08F04040, 0x08F04040)
  PORTRAIT(16, 0, 8)
  LANGUAGE_TEXT(0, "Please. Hurry to the Great\nWall of China.\n\nReshef the Dark Being will\nsoon engulf the world.\n\n")
  LANGUAGE_TEXT(1, "S'il vous pla\xeet.\nD\xe9p\xeachez-vous.\n\nAllez \xe0 la Grande Muraille\nde Chine.\n\nReshef, l'Etre des t\xe9n\xe8bres\nva bient\xf4t plonger le monde\n\ndans les t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Bitte. Eilt zur Chinesischen\nMauer. Reschef der Dunkle\n\nwird bald die Welt in\nFinsternis h\xfcllen.\n\n")
  LANGUAGE_TEXT(3, "Vi prego, recatevi in fretta\nalla Grande Muraglia\n\ncinese. Il mondo cadr\xe0\npresto nelle grinfie di\n\nReshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "Por favor, corred a la\nGran Muralla China.\n\nReshef, el Ser Oscuro pronto\nacabar\xe1 con el mundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
