#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_57_state_03: map 57 state 3 */

LOAD_SPRITE(1, SPRITE_ROLAND)
LOAD_SPRITE(2, SPRITE_BIG_FIVE)
LOAD_SPRITE(3, SPRITE_BIG_FIVE)
LOAD_SPRITE(4, SPRITE_BIG_FIVE)
LOAD_SPRITE(5, SPRITE_BIG_FIVE)
LOAD_SPRITE(6, SPRITE_BIG_FIVE)
PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "All right, crew! Everyone\n"
    "ready?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
TEXT
(
    "Yes, I understand. But...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_JUMPING)
TEXT
(
    "We're missing two of our\n"
    "members...\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_JUMPING)
TEXT
(
    "What's the point of doing a\n"
    "children's show?\n\n"
)
PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "You fools!\n\n"
)
HIDE_PORTRAIT()
DELAY(8)
PLAY_MUSIC(MUSIC_271)
REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2 | OBJECT_3 | OBJECT_4 | OBJECT_5 | OBJECT_6)
DELAY(8)
PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "The children are afraid!\n\n"
    "The Neo Ghouls stole their\n"
    "rare cards.\n\n"
    "Kaibaman represents hope to\n"
    "the kids.\n\n"
    "When Masters Mokuba and Seto\n"
    "return, how would they feel\n\n"
    "if children aren't enjoying\n"
    "dueling?\n\n"
    "We can't let Masters Mokuba\n"
    "and Seto see that.\n\n"
    "That's why we have to give\n"
    "hope to the kids.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(3, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
DELAY(16)
PORTRAIT(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "As a bonus, I'll speak to\n"
    "Master Kaiba about giving\n\n"
    "you better jobs.\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(1, SPRITE_KAIBAMAN)
DELAY(16)
PLAY_MUSIC(MUSIC_272)
REACTION(REACTION_ELLIPSIS, OBJECT_2 | OBJECT_3 | OBJECT_4 | OBJECT_5 | OBJECT_6)
DELAY(16)
MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_5, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(5, SPRITE_ROBOTIC_KNIGHT)
PORTRAIT(PORTRAIT_ROBOTIC_KNIGHT, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "I... I'll do it!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(6, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_6, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(6, SPRITE_JINZO)
PORTRAIT(PORTRAIT_JINZO, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TEXT
(
    "Yes!\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(3, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(2, SPRITE_DEEPSEA_WARRIOR)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(3, SPRITE_NIGHTMARE_PENGUIN)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_361)
LOAD_SPRITE(4, SPRITE_JUDGE_MAN)
FADE_SCREEN(8)
WARP(LOCATION_KAIBA_LAND, 4, 0, 0)
