#include "event_macros.h"
#include "overworld.h"

/* map_26_state_05: map 26 state 5 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3C74, map_26_state_05_08EA3C74, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "It seems you found what you\nwere looking for.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C80, map_26_state_05_08EA3C80, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD, 8)
  LANGUAGE_TEXT(0, "I'm the Hollywood heartthrob\nJean Claude Magnum, the\n\nbiggest action hero in the\nworld.\n\nBut Mai Valentine still\nwon't marry me...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3C8C, map_26_state_05_08EA3C8C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_JEAN_CLAUDE_MAGNUM, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Without Mai's hand in\nmarriage on the line...\n\nThere's no point in dueling.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(2, 3, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
