#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_33_state_03: map 33 state 3 */

LOAD_SPRITE(1, SPRITE_WEEVIL)
LOAD_SPRITE(2, SPRITE_LUMIS)
LOAD_SPRITE(3, SPRITE_UMBRA)
PLAY_MUSIC(MUSIC_407)
TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You listen to us...\n\n"
)
TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You're going to join us as a\n"
    "Neo Ghoul.\n\n"
)
TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You're smart as a spider to\n"
    "recruit me.\n\n"
)
TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_LEFT,
    "You'll join us?\n\n"
)
TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_LEFT,
    "Hyohyohyo! Okay!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
WALK_OBJECT_Y(0, 46)
WALK_OBJECT_X(0, 62)
WALK_OBJECT_Y(13, 52)
WALK_OBJECT_X(13, 56)
WALK_OBJECT_Y(14, 40)
WALK_OBJECT_X(14, 56)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Hyohyohyohyo!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, OBJECT_0)
PLAY_MUSIC(MUSIC_270)
REACTION(REACTION_QUESTION_MARK, SPRITE_LUMIS | SPRITE_UMBRA)
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Hyohyohyo! Just kidding!\n\n"
    "There's no way I'd join you\n"
    "wimpy worms!\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "H-how dare you...\n\n"
)
TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You tricked us!\n\n"
)
TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You leave us with no\n"
    "options!\n\n"
)
TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "We'll settle this in a duel!\n\n"
)
TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I'm not falling into your\n"
    "web! I won't take on two\n\n"
    "duelists at the same time.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_LEFT, 0, 0)
DELAY(16)
TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "{PLAYER}, you duel one of\n"
    "them.\n\n"
)
PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
WALK_OBJECT_Y(SPRITE_WEEVIL, 52)
WALK_OBJECT_X(SPRITE_WEEVIL, 78)
WALK_OBJECT_Y(0, 40)
WALK_OBJECT_X(0, 78)
DELAY(16)
TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "You'll make an excellent\n"
    "prize for Master Keith!\n\n"
)
DUEL(DUELIST_LUMIS_068)
PLAY_MUSIC(MUSIC_243)
TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "How dare you!\n\n"
)
WALK_OBJECT_Y(SPRITE_UMBRA, 68)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
WALK_OBJECT_X(SPRITE_UMBRA, 16)
SHOW_OBJECT(SPRITE_UMBRA, 128, 96, 0, 0, 0)
TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO,
    "You were just lucky!\n\n"
)
WALK_OBJECT_Y(SPRITE_LUMIS, 68)
WALK_OBJECT_X(SPRITE_LUMIS, 34)
MOVE_OBJECT(SPRITE_LUMIS, DIRECTION_RIGHT, 0, 0)
TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Don't you forget about me!\n\n"
)
WALK_OBJECT_X(SPRITE_LUMIS, 16)
SHOW_OBJECT(SPRITE_LUMIS, 128, 96, 0, 0, 0)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_UP, 0, 0)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
WALK_OBJECT_X(13, 64)
WALK_OBJECT_X(14, 64)
TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Hyohyohyo! Long time no see.\n\n"
    "There are lots of rare bugs\n"
    "here in China.\n\n"
)
TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "This guy bugs me, but I\n"
    "gotta admit, he is a good\n\n"
    "duelist.\n\n"
    "{PLAYER}, let's get him to\n"
    "help us beat the Neo\n\n"
    "Ghouls.\n\n"
)
PLAY_MUSIC(MUSIC_332)
FADE_SCREEN(4)
PLAY_MUSIC(MUSIC_702)
TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Humph. They ignored me and\n"
    "overran the Town of Domino\n\n"
    "instead?\n\n"
    "That bugs me! How can they\n"
    "ignore the best duelist!\n\n"
    "Count me in to help you!\n\n"
)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_LEFT, 8, 0)
WALK_OBJECT_Y(SPRITE_WEEVIL, 68)
MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
WALK_OBJECT_X(SPRITE_WEEVIL, 16)
SHOW_OBJECT(SPRITE_WEEVIL, 128, 96, 0, 0, 0)
SET_FLAG(EVENT_FLAG_DEFEATED_LUMIS_AND_UMBRA)
CONDITION_CHECK(0)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Let's go find another ally!\n\n"
)
HIDE_PORTRAIT()
FADE_MUSIC(2)
DELAY(32)

EVENT_SCRIPT_REPLACEMENT(0x08EBEBD4, map_33_state_03_08EBEBD4, 0x08F04040, 0x08F04040)
MOVE_OBJECT(0, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Okay! Let's also get back to\n"
    "the Town of Domino!\n\n"
)
  HIDE_PORTRAIT()
  FADE_MUSIC(2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_FOUND_ALL_ALLIES)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB98, map_33_state_03_08EBEB98, 0x08EBEBA4, 0x08F0404C)
WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 78)
  WALK_OBJECT_Y(0, 52)
  WALK_OBJECT_X(0, 78)
  DELAY(16)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "I'll make you regret defying\n"
    "the Neo Ghouls!\n\n"
)
  DUEL(DUELIST_UMBRA_069)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEBA4, map_33_state_03_08EBEBA4, 0x08EBEBB0, 0x08F04040)
PLAY_MUSIC(MUSIC_243)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "How dare you!\n\n"
)
  WALK_OBJECT_Y(3, 68)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_X(3, 16)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO,
    "You were just lucky!\n\n"
)
  WALK_OBJECT_Y(2, 68)
  WALK_OBJECT_X(2, 34)
  MOVE_OBJECT(2, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_LUMIS, EXPRESSION_LUMIS_DEFEATED, PORTRAIT_POSITION_AUTO,
    "Don't you forget about me!\n\n"
)
  WALK_OBJECT_X(2, 16)
  SHOW_OBJECT(2, 128, 96, 0, 0, 0)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EBEB5C, map_33_state_03_08EBEB5C, 0x08EBEB68, 0x08F04040)
HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Traitor? Hyohyohyo! Why am I\n"
    "a traitor?\n\n"
    "I don't remember being on\n"
    "your side!\n\n"
)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Fufufu... He'll make an\n"
    "excellent addition to our\n\n"
    "ranks!\n\n"
)
  TALK(PORTRAIT_LUMIS, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "Yes! He's one of ours! He's\n"
    "a member of the Neo Ghouls!\n\n"
)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Hyohyohyo! Actually, I don't\n"
    "want to be on your team\n\n"
    "either!\n\n"
)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2 | OBJECT_3)
  DELAY(8)
  TALK(PORTRAIT_UMBRA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
    "But... But you just agreed\n"
    "to join us.\n\n"
)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
    "Hyohyohyohyo!\n\n"
    "I changed my mind!\n\n"
)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
