#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_12_state_12: map 12 state 12 */

EVENT_SCRIPT_REPLACEMENT(0x08E6F138, map_12_state_12_08E6F138, 0x08E6F144, 0x08E6F150)
  LOAD_SPRITE(1, SPRITE_ROLAND)
  LOAD_SPRITE(2, SPRITE_MOKUBA)
  LOAD_SPRITE(3, SPRITE_SETO)
  LOAD_SPRITE(4, SPRITE_REBECCA)
  LOAD_SPRITE(5, SPRITE_TEDDY)
  PLAY_MUSIC(MUSIC_HAPPY_CUTSCENE)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 8, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 8, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 8, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO, "You're Seto Kaiba, aren't you?")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_270)
  REACTION(REACTION_QUESTION_MARK, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_13)
  DELAY(8)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, PORTRAIT_POSITION_AUTO, "Who are you? You're not very polite.")
  TALK(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I'm Rebecca.",
      "And this is my friend Teddy."
  )
  HIDE_PORTRAIT()
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "A stuffed animal is your friend?")
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "Be quiet! Teddy's not a stuffed animal!",
      "Teddy is the best bear in the galaxy! Growl!",
      "And we know a secret, don't we, Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "You're the one who tore up Solomon Muto's card.",
      "You tore up his Blue-Eyes White Dragon."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_2)
  DELAY(8)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "...")
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SAD, PORTRAIT_POSITION_AUTO, "H-how did you know...")
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(32)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "My grandfather gave Mr. Muto that card.",
      "That Blue-Eyes White Dragon was a symbol of their",
      "friendship, but you tore it up!",
      "You're not going to get away with that! Right, Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "So what do you want me to do?")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_ANGRY, PORTRAIT_POSITION_AUTO, "Seto, just ignore her...")
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO, "I challenge you to a duel!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "I'll wipe that smirk off your face.",
      "Because you're facing the United States champion!",
      "Right, Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "U.S. champ? That's it?",
      "At your duelist level, I can defeat you blindfolded."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_4)
  DELAY(8)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO, "At my level?! Are you making fun of me?!")
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "No, I'm just telling the truth.",
      "Your skills are nothing but a joke.",
      "But if you still insist on challenging me..."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_3)
  DELAY(8)
  TALK(PORTRAIT_SETO, 1, PORTRAIT_POSITION_AUTO,
      "I have a better idea. Duel against {PLAYER}.",
      "If you can beat him, I'll duel you."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_0 | OBJECT_4 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(13, 24)
  WALK_OBJECT_Y(13, 48)
  MOVE_OBJECT(13, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  DELAY(48)
  WALK_OBJECT_Y(13, 44)
  WALK_OBJECT_X(13, 30)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(0, 54)
  WALK_OBJECT_X(0, 40)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 54)
  WALK_OBJECT_X(14, 20)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Rebecca, I know you're upset, but there's no point",
      "attacking Kaiba."
  )
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "Yugi...",
      "I'm not challenging Kaiba because I'm angry.",
      "I want to duel him to test my skills.",
      "Right, Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Rebecca...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 2, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 40)
  WALK_OBJECT_Y(4, 40)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_372)
  SHOW_OBJECT(5, 48, 40, 0, 0, 0)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  DELAY(8)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hmm... Are you really that strong of a duelist?",
      "You sure don't look it. Teddy doesn't think so,",
      "either."
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "But I'm still dueling you!")
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F144, map_12_state_12_08E6F144, 0x08E6F15C, 0x08F0404C)
  DUEL(DUELIST_REBECCA_130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F15C, map_12_state_12_08E6F15C, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_KAIBACORP)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "I... I lost?",
      "Did I really lose? Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 1, PORTRAIT_POSITION_AUTO, "Humph. That duel was a joke.")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(5, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_POSITION_AUTO,
      "If you want your revenge, come back when you actually",
      "pose a challenge.",
      "You know where to find me!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, DIRECTION_LEFT, 16, 0)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Just to let you know, my brother would have finished",
      "you off in half the number of turns!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 16, 0)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_14)
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_4)
  DELAY(16)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Rebecca...",
      "I know Kaiba is arrogant and says terrible things, but",
      "he is a different person.",
      "The Kaiba you saw today isn't like the Kaiba of",
      "old."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(64)
  MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "I don't care...",
      "Kaiba's right. Without Pegasus and Bandit Keith,",
      "America doesn't have the top duelists anymore.",
      "That's why I came here. To prove that we're still",
      "pretty good!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "But losing to {PLAYER}... That was an eye-opener.",
      "I should have been training than complaining.",
      "I'm turning over a new leaf. I'm going to raise my",
      "duelist level so that I can put the United States back",
      "on the map!",
      "Just you wait. I'll beat Kaiba, Yugi, and you.",
      "Right, Teddy?"
  )
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_TEDDY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  DELAY(96)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, PORTRAIT_POSITION_AUTO, "Yup! And I'll also train so that I won't lose!")
  TALK(PORTRAIT_REBECCA, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I'm going home to practice!",
      "Say bye to Solomon Muto for me!"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, DIRECTION_RIGHT, 2, 0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_372)
  SHOW_OBJECT(5, 128, 96, 0, 0, 0)
  DELAY(8)
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, DIRECTION_LEFT, 16, 0)
  DELAY(16)
  SET_FLAG(EVENT_FLAG_DEFEATED_REBECCA)
  PLAY_MUSIC(MUSIC_KAIBACORP)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F150, map_12_state_12_08E6F150, 0x08E6F15C, 0x08F0404C)
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_JUMPING)
  DELAY(8)
  TALK(PORTRAIT_REBECCA, 5, PORTRAIT_POSITION_AUTO,
      "Even if you don't want to duel, I do!",
      "Come on! Or are you chicken!"
  )
  DUEL(DUELIST_REBECCA_130)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E6F1C8, map_12_state_12_08E6F1C8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_ROLAND, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "That girl is no match for Master Seto, but in ten",
      "years, she will be ready to take on the world."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
