#include "event_macros.h"
#include "overworld.h"

/* map_59_state_01: map 59 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EFDA58, map_59_state_01_08EFDA58, 0x08EFDA64, 0x08F04040)
  PLAY_MUSIC(26)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  MOVE_OBJECT(1, 3, 16, 0)
  MOVE_OBJECT(0, 1, 16, 0)
  MOVE_OBJECT(13, 1, 16, 0)
  MOVE_OBJECT(14, 1, 16, 0)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Ah! It has been too long!\n\nGreetings, Pharaoh!\nWelcome, powerful duelists!\n\n")
  LANGUAGE_TEXT(1, "Ah ! Je suis vraiment\nnostalgique !\n\nIl faut saluer\nles Pharaons.\n\nBienvenue, oh\npuissants duellistes !\n\n")
  LANGUAGE_TEXT(2, "Ah! Die Nostalgie\n\xfcberw\xe4ltigt mich!\n\nLobet die Pharaonen.\nWillkommen, wackere\n\nDuellanten!\n\n")
  LANGUAGE_TEXT(3, "Ah! La nostalgia mi\nassale!\n\nSia lode ai Faraoni.\nBenvenuti, forti duellanti!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ah! \xa1Me embarga\nla nostalgia!\n\nLoados sean los\nfaraones.\n\n\xa1Bienvenidos, fuertes\nduelistas!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Heheh, powerful duelists,\nhuh?\n\nI love hearin' that every\ntime!\n\nOdion, how are ya?\n\n")
  LANGUAGE_TEXT(1, "H\xe9 h\xe9, de puissants\nduellistes, hein ?\n\nJe le sais d\xe9j\xe0 mais c'est\ntoujours bien de\n\nl'entendre.\n\nOdion, est-ce que tu\nvas bien, toi aussi ?\n\n")
  LANGUAGE_TEXT(2, "Hmm, wackere\nDuellanten?\n\nStimmt zwar, f\xfchlt\nsich trotzdem gut an.\n\nOdion, bist du auch\nnoch so gut?\n\n")
  LANGUAGE_TEXT(3, "Heheh, forti\nduellanti, eh?\n\nLo so che lo siamo,\nma fa piacere\n\nsentirselo dire. E tu\nstai bene, Odion?\n\n")
  LANGUAGE_TEXT(4, "Jejeje, fuertes\nduelistas, \xbfeh?\n\nS\xe9 que es un hecho,\npero sigue haci\xe9ndome\n\nsentir bien.\n\nOdion, \xbfte has mantenido\nbien t\xfa tambi\xe9n?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "I am well, as you can see.\n\n")
  LANGUAGE_TEXT(1, "Comme tu peux le voir.\n\n")
  LANGUAGE_TEXT(2, "Nat\xfcrlich, wie man sieht.\n\n")
  LANGUAGE_TEXT(3, "Sto come mi vedi.\n\n")
  LANGUAGE_TEXT(4, "Soy lo que ves.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Hahaha! Yeah, you're lookin'\ngood.\n\n")
  LANGUAGE_TEXT(1, "Ha ha ha !\nOui, tu as l'air en forme.\n\n")
  LANGUAGE_TEXT(2, "Hahaha!\nJa, du siehst gut aus.\n\n")
  LANGUAGE_TEXT(3, "Hahaha! Gi\xe0, sembra\nche te la passi bene.\n\n")
  LANGUAGE_TEXT(4, "\xa1Jajaja!\nS\xed, te ves bien.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "My friends, what brings you\nhere?\n\n")
  LANGUAGE_TEXT(1, "Eh bien, mes amis.\n\nQu'est-ce qui\nvous am\xe8ne ici ?\n\n")
  LANGUAGE_TEXT(2, "Nun, meine Freunde.\nWas f\xfchrt euch her?\n\n")
  LANGUAGE_TEXT(3, "Ebbene, cari amici.\nCosa vi porta qui?\n\n")
  LANGUAGE_TEXT(4, "Bueno, amigos m\xedos.\n\xbfQu\xe9 os trae aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "We're here to see Marik.\n\nWe have to talk to him.\n\n")
  LANGUAGE_TEXT(1, "Nous sommes\nvenus voir Marik.\n\nNous devons le voir,\nc'est important.\n\n")
  LANGUAGE_TEXT(2, "Wir wollen zu Marik.\n\nWir m\xfcssen ihn sprechen.\n\n")
  LANGUAGE_TEXT(3, "Siamo qui per vedere\nMarik. Dobbiamo vederlo.\n\n")
  LANGUAGE_TEXT(4, "Estamos aqu\xed para\nver a Marik.\n\nTenemos que verle.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 2)
  DELAY(16)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "It is most unfortunate,\nbut...\n\nI cannot permit you to see\nhim.\n\n")
  LANGUAGE_TEXT(1, "Je suis d\xe9sol\xe9 mais...\n\nJe ne peux pas vous\npermettre de le voir.\n\n")
  LANGUAGE_TEXT(2, "Es ist bedauerlich,\naber...\n\nIch kann nicht gestatten,\ndass ihr jetzt zu ihm geht.\n\n")
  LANGUAGE_TEXT(3, "Mi dispiace tanto,\nma... Ora non vi\n\nposso permettere\ndi vederlo.\n\n")
  LANGUAGE_TEXT(4, "Es una pena,\npero...\n\nNo le pod\xe9is ver\nahora.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "That isn't the answer we're\nlookin' for.\n\n{PLAYER}, that's not cool,\nright?\n\n")
  LANGUAGE_TEXT(1, "Nous ne sommes pas venu\njusqu'ici pour entendre\n\ncette r\xe9ponse. {PLAYER},\ntu es content de \xe7a ?\n\n")
  LANGUAGE_TEXT(2, "Wir kamen nicht her, um\nuns das sagen zu lassen.\n\n{PLAYER}, das k\xf6nnen wir\nnicht akzeptieren, oder?\n\n")
  LANGUAGE_TEXT(3, "Non siamo venuti qui\nper ricevere quella\n\nrisposta. {PLAYER},\nnon sarai mica contento\n\ndi tale risposta, vero?\n\n")
  LANGUAGE_TEXT(4, "No vinimos hasta aqu\xed para\nobtener esa respuesta.\n\n{PLAYER}, no est\xe1s\nsatisfecho con eso, \xbfno?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDA64, map_59_state_01_08EFDA64, 0x08EFDA70, 0x08EFDA7C)
  PORTRAIT(PORTRAIT_NONE, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Let's come back later.\nLet's decide in a duel.{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Revenons plus tard.\nR\xe9glons \xe7a en duel.{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Kehren wir sp\xe4ter zur\xfcck.\nLasst uns darum k\xe4mpfen.{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Torniamo pi\xf9 tardi.\nDuelliamo per questo.{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Volvamos m\xe1s tarde.\nLuchemos para arreglarlo.{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDA70, map_59_state_01_08EFDA70, 0x08EFDA94, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, 7, 8)
  LANGUAGE_TEXT(0, "Wha... Come back later?!\n\nWe don't have time!\n\n")
  LANGUAGE_TEXT(1, "Quoi...\nRevenir plus tard ?!\n\nMais tu ne comprends pas ?\nNous n'avons pas le temps !\n\n")
  LANGUAGE_TEXT(2, "Waaa...\nSp\xe4ter wiederkommen?!\n\nVerstehst du nicht?\nWir haben keine Zeit!\n\n")
  LANGUAGE_TEXT(3, "Ma come sarebbe a\ndire che torniamo pi\xf9\n\ntardi?! Non hai capito?\nNon ne abbiamo il tempo!\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9...\n\xa1\xbfVolver m\xe1s tarde?!\n\n\xbfNo te enteras?\n\xa1No tenemos tiempo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Joey, {PLAYER} knows that.\n\n")
  LANGUAGE_TEXT(1, "Joey, {PLAYER} le sait bien.\n\n")
  LANGUAGE_TEXT(2, "Joey, {PLAYER} wei\xdf das.\n\n")
  LANGUAGE_TEXT(3, "Joey, {PLAYER} lo sa.\n\n")
  LANGUAGE_TEXT(4, "Joey, {PLAYER}\nlo sabe.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDA94, map_59_state_01_08EFDA94, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "Let them enter, Odion.\n\n")
  LANGUAGE_TEXT(1, "Laisse-les entrer, Odion.\n\n")
  LANGUAGE_TEXT(2, "Lass sie eintreten, Odion.\n\n")
  LANGUAGE_TEXT(3, "Falli entrare, Odion.\n\n")
  LANGUAGE_TEXT(4, "Que entren, Odion.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "M-master Marik... Are you\ncertain?\n\n")
  LANGUAGE_TEXT(1, "M-ma\xeetre Marik...\nVous \xeates s\xfbr ?\n\n")
  LANGUAGE_TEXT(2, "M-Meister Marik...\nSeid ihr sicher?\n\n")
  LANGUAGE_TEXT(3, "M-maestro Marik...\nNe siete sicuro?\n\n")
  LANGUAGE_TEXT(4, "A-amo Marik...\n\xbfEst\xe1 seguro?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MARIK, 0, 8)
  LANGUAGE_TEXT(0, "Of course. I don't mind.\n\n")
  LANGUAGE_TEXT(1, "Mais oui. Ca ne\nme d\xe9range pas.\n\n")
  LANGUAGE_TEXT(2, "Selbstverst\xe4ndlich.\nIch habe nichts dagegen.\n\n")
  LANGUAGE_TEXT(3, "Ma certo. Non mi\nd\xe0 fastidio.\n\n")
  LANGUAGE_TEXT(4, "Seguro.\nNo me importa.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Please forgive my rudeness.\nPlease enter.\n\n")
  LANGUAGE_TEXT(1, "Veuillez m'excuser.\nEntrez, s'il vous pla\xeet.\n\n")
  LANGUAGE_TEXT(2, "Vergebt mir meine Rohheit.\nBitte, tretet ein.\n\n")
  LANGUAGE_TEXT(3, "Vi prego di scusare\nla mia scortesia.\n\nEntrate, prego.\n\n")
  LANGUAGE_TEXT(4, "Por favor, perdonad\nmi groser\xeda.\n\nPasad, por favor.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_X(1, 61)
  WALK_OBJECT_Y(1, 24)
  SHOW_OBJECT(1, 128, 96, 0, 0, 0)
  WALK_OBJECT_X(0, 61)
  WALK_OBJECT_Y(0, 24)
  SHOW_OBJECT(0, 128, 96, 0, 0, 0)
  WALK_OBJECT_X(13, 61)
  WALK_OBJECT_Y(13, 24)
  SHOW_OBJECT(13, 128, 96, 0, 0, 0)
  WALK_OBJECT_X(14, 61)
  WALK_OBJECT_Y(14, 24)
  SHOW_OBJECT(14, 128, 96, 0, 0, 0)
  COMMAND_7C_ARG(2, 4)
  FADE_SCREEN(4)
  WARP(60, 1, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDA7C, map_59_state_01_08EFDA7C, 0x08EFDA88, 0x08F0404C)
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "Yeah, that simplifies\nthings.\n\n")
  LANGUAGE_TEXT(1, "Eh bien, voil\xe0 qui\nsimplifie les choses.\n\n")
  LANGUAGE_TEXT(2, "Na, das macht\ndie Sache leichter.\n\n")
  LANGUAGE_TEXT(3, "Be', questo semplifica\nle cose.\n\n")
  LANGUAGE_TEXT(4, "Bueno, eso simplifica\nlas cosas.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "I see that you are unwilling\nto leave.\n\nI guess it cannot be helped.\n\nI, Odion, will not allow you\nto disturb Master Marik.\n\nLet's duel!\n\n")
  LANGUAGE_TEXT(1, "Je vois que vous\nne voulez pas partir.\n\nC'est in\xe9vitable.\nMais moi, Odion, je ne vous\n\nlaisserai pas d\xe9ranger\nma\xeetre Marik.\n\nEn duel !\n\n")
  LANGUAGE_TEXT(2, "Ich sehe, dass ihr\nnicht gehen m\xf6chtet.\n\nEs geht nicht anders.\n\nIch, Odion, gestatte nicht,\ndass die Ruhe von\n\nMeister Marik gest\xf6rt wird.\nDas bedeutet: Duell!\n\n")
  LANGUAGE_TEXT(3, "Vedo che non avete\nintenzione di andarvene.\n\nNon si pu\xf2 evitare.\nIo, Odion, non vi\n\npermetter\xf2 di disturbare\nil maestro Marik.\n\nDuelliamo!\n\n")
  LANGUAGE_TEXT(4, "Veo que no est\xe1is\ndispuestos a iros.\n\nNo hay nada que hacer.\n\nYo, Odion, no os permitir\xe9\nmolestar al amo Marik.\n\n\xa1Luchad!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(157)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EFDA88, map_59_state_01_08EFDA88, 0x08EFDA94, 0x08F04040)
  PLAY_MUSIC(26)
  PORTRAIT(PORTRAIT_ODION, 0, 8)
  LANGUAGE_TEXT(0, "Gah! What strength and\ndetermination... Why do you\n\nneed to speak with Master\nMarik so urgently?\n\n")
  LANGUAGE_TEXT(1, "Grr ! Alors vous \xeates venus\ntous puissants et pleins\n\nde bonnes volont\xe9s...\n\n")
  LANGUAGE_TEXT(2, "Pah! Also kamt ihr mit viel\nKraft und werdet...\n\n")
  LANGUAGE_TEXT(3, "Ah! Siete venuti\narmati di tanta forza e\n\ndi buona volont\xe0...\n\n")
  LANGUAGE_TEXT(4, "\xa1Vaya! Hab\xe9is venido con\nmucha fuerza y ganas...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
