#include "event_macros.h"

/* map_04_state_07: map 4 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E4D1D4, map_04_state_07_08E4D1D4, 0x08F04040, 0x08F04040)
  DELAY(16)
  WALK_OBJECT_X(1, 96)
  DELAY(32)
  MOVE_OBJECT(1, 2, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 0, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(16)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(11, 0, 0)
  LANGUAGE_TEXT(0, "I'm sure they're supposed to\nbe around here somewhere.\n\nHuh? They're not here yet?\n\n")
  LANGUAGE_TEXT(1, "Je suis s\xfbr que c'\xe9tait\ndans les parages.\n\nHein ? Pas encore l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Ich bin mir sicher, es war\nhier irgendwo.\n\nHm?\nNoch nicht hier?\n\n")
  LANGUAGE_TEXT(3, "Sono sicuro che era\nda queste parti.\n\nEh?\nNon ancora qui?\n\n")
  LANGUAGE_TEXT(4, "Estoy seguro de que\nestaba en alg\xfan lugar\n\nde por aqu\xed.\n\n\xbfEh?\n\xbfTodav\xeda no est\xe1 aqu\xed?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 24)
  PORTRAIT(15, 0, 0)
  LANGUAGE_TEXT(0, "My cosmic powers tell me\nthis is the place.\n\nI hope they come back\nsafely.\n\n")
  LANGUAGE_TEXT(1, "D'apr\xe8s mes pr\xe9dictions,\nc'est ici.\n\nJ'esp\xe8re qu'ils reviendront\nsains et saufs.\n\n")
  LANGUAGE_TEXT(2, "Meine prophetischen Kr\xe4fte\nsagen mir, es ist hier.\n\nIch hoffe, sie kommen heil\nzur\xfcck.\n\n")
  LANGUAGE_TEXT(3, "Come indovino, dico\nche si trova qui.\n\nSpero che tornino\nsani e salvi.\n\n")
  LANGUAGE_TEXT(4, "Mis poderes de adivinaci\xf3n\nme dicen que est\xe1 aqu\xed.\n\nEspero que vuelvan\nsanos y salvos.\n\n")
  END_LANGUAGE_TEXT()
  COMMAND_7C_ARG(2, 8)
  FADE_SCREEN(8)
  WARP(1, 7, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()
