#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_47_state_01: map 47 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EDB06C, map_47_state_01_08EDB06C, 0x08EDB078, 0x08F0404C)
  LOAD_SPRITE(1, SPRITE_CHEVALIER)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Gawry nida! Gawry nida!\n\nWe win all duels! Gawry!\n\n")
  DUEL(111)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EDB078, map_47_state_01_08EDB078, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(MUSIC_DUNGEON)
  PORTRAIT(PORTRAIT_CHEVALIER, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("G-gawry nida... G-ga..\nn-niii.... urrri...\n\n")
  PLAY_MUSIC(MUSIC_282)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_TELEPORT)
  FALLTHROUGH()
END_EVENT_SCRIPT()
