#include "event_macros.h"
#include "overworld.h"

/* map_22_state_08: map 22 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08E8CBB8, map_22_state_08_08E8CBB8, 0x08E8CBC4, 0x08F04040)
  PLAY_MUSIC(405)
  DELAY(32)
  WALK_OBJECT_X(2, 52)
  DELAY(16)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Big brother!\n\nMost of the Neo Ghouls have\nleft the Town of Domino.\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re !\n\nLa plupart des Neo\nGhouls ont quitt\xe9 Domino.\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder! Die\nmeisten Neo Ghouls sind\n\naus Domino verschwunden.\n\n")
  LANGUAGE_TEXT(3, "Fratello!\n\nQuasi tutti i Neo Ghouls se\nne sono andati da Domino.\n\n")
  LANGUAGE_TEXT(4, "\xa1Gran hermano!\n\nLa mayor\xeda de Neo Ghouls\nse ha ido de Domino.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Good.\n\n")
  LANGUAGE_TEXT(1, "Tant mieux.\n\n")
  LANGUAGE_TEXT(2, "Gut.\n\n")
  LANGUAGE_TEXT(3, "Bene.\n\n")
  LANGUAGE_TEXT(4, "Bien.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I protected KaibaCorp, just\nlike you told me.\n\nSo you don't have to worry\nabout a thing.\n\n")
  LANGUAGE_TEXT(1, "J'ai prot\xe9g\xe9 la Kaiba Corp\ncomme tu me l'as demand\xe9.\n\nTu n'as pas de soucis \xe0\nte faire.\n\n")
  LANGUAGE_TEXT(2, "Ich habe die Kaiba Corp.\ngesch\xfctzt, wie du\n\nes mir aufgetragen hast.\nEs ist alles in Ordnung.\n\n")
  LANGUAGE_TEXT(3, "Ho protetto la Kaiba Corp\ncome mi avevi detto.\n\nNon c'\xe8 niente di cui\ndebba preoccuparti.\n\n")
  LANGUAGE_TEXT(4, "Defend\xed Kaiba Corp\ncomo me dijiste.\n\nNo tienes que\npreocuparte de nada.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Good work, Mokuba.\n\n")
  LANGUAGE_TEXT(1, "Tu as bien travaill\xe9,\nMokuba.\n\n")
  LANGUAGE_TEXT(2, "Gut gemacht, Mokuba.\n\n")
  LANGUAGE_TEXT(3, "Ottimo lavoro, Mokuba.\n\n")
  LANGUAGE_TEXT(4, "Buen trabajo, Mokuba.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Heheh, thanks. You know I'll\ndo anything for you.\n\nSo, anything new with your\nEgyptian God Card?\n\n")
  LANGUAGE_TEXT(1, "H\xe9, h\xe9, pour toi,\ngrand fr\xe8re,\n\nc'est toujours facile.\n\nEt ta carte de dieu ?\nQuoi de neuf ?\n\n")
  LANGUAGE_TEXT(2, "Heheh, f\xfcr dich, gro\xdfer\nBruder, ist alles einfach.\n\nWas ist jetzt mit deiner\nG\xf6tterkarte?\n\nWas ist passiert?\n\n")
  LANGUAGE_TEXT(3, "Hehe, per te, fratello, \xe8\ntutto facile. Che mi dici\n\ndella tua carta divina?\n\xc8 successo qualcosa?\n\n")
  LANGUAGE_TEXT(4, "Je,je, por ti, gran hermano,\nsiempre es f\xe1cil.\n\nAs\xed que, \xbfpas\xf3 algo\ncon tu carta del dios?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Somehow, it's back to\nnormal.\n\n")
  LANGUAGE_TEXT(1, "Je ne sais pas comment,\nmais elle a \xe9t\xe9 totalement\n\nrestaur\xe9e.\n\n")
  LANGUAGE_TEXT(2, "Aus irgendeinem Grund\nscheint sie v\xf6llig\n\nhergestellt zu sein.\n\n")
  LANGUAGE_TEXT(3, "Per qualche motivo, sembra\ncompletamente ripristinata.\n\n")
  LANGUAGE_TEXT(4, "Por alguna raz\xf3n,\nparece que se ha\n\nrestaurado del todo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_SETO, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I don't know what they did,\nbut...\n\n")
  LANGUAGE_TEXT(1, "Je ne sais pas ce qu'ils ont\nfait exactement, mais...\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf nicht, wer es\ngetan hat, aber...\n\n")
  LANGUAGE_TEXT(3, "Non so esattamente\ncome hanno fatto, ma...\n\n")
  LANGUAGE_TEXT(4, "No s\xe9 qu\xe9 hicieron\nexactamente, pero...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBC4, map_22_state_08_08E8CBC4, 0x08E8CBD0, 0x08F04040)
  PLAY_MUSIC(404)
  WALK_OBJECT_X(4, 48)
  PORTRAIT(PORTRAIT_MOKUBA, EXPRESSION_MOKUBA_SURPRISED, 0)
  LANGUAGE_TEXT(0, "Urk! S-Seto...\n\n")
  LANGUAGE_TEXT(1, "Hi !\nGrand fr\xe8re...\n\n")
  LANGUAGE_TEXT(2, "Urk!\nGro\xdfer Bruder...\n\n")
  LANGUAGE_TEXT(3, "Diamine!\nFratello...\n\n")
  LANGUAGE_TEXT(4, "\xa1Urk!\nGran hermano...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  SET_OBJECT_POSITION(2, 128, 96, 0)
  PLAY_MUSIC(314)
  SWAP_OBJECT_SPRITE(4, 127)
  DELAY(8)
  MOVE_OBJECT(1, 1, 0, 0)
  PLAY_MUSIC(271)
  REACTION(0, 2)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 6, 1)
  LANGUAGE_TEXT(0, "How dare you... What's the\nmeaning of this?\n\n")
  LANGUAGE_TEXT(1, "Quoi, toi... Qu'est-ce\nque cela signifie ?\n\n")
  LANGUAGE_TEXT(2, "He, du... Was hat das\nzu bedeuten?\n\n")
  LANGUAGE_TEXT(3, "Ehi, tu... Che\nsignifica questo?\n\n")
  LANGUAGE_TEXT(4, "\xbfPor qu\xe9?, t\xfa... \xbfQu\xe9\nsignifica esto?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Seto Kaiba! I have a message\nfrom Master Chevalsky!\n\nCome to my castle.\n\nIf you want to save your\ndear brother.\n\nYou have no choice but to\ncome to my castle!\n\n")
  LANGUAGE_TEXT(1, "Kaiba Seto ! Un message\nde ma\xeetre Chevalsky !\n\nViens \xe0 mon ch\xe2teau.\n\nBien s\xfbr, si tu veux\nsauver cet imb\xe9cile...\n\nIl faudra venir\nau ch\xe2teau !\n\n")
  LANGUAGE_TEXT(2, "Kaiba Seto! Eine Botschaft\nvon Meister Chevalsky!\n\nKomm in meine Burg.\n\nNat\xfcrlich, wenn du diesen\nL\xfcmmel retten willst...\n\nMusst du in die Burg\nkommen!\n\n")
  LANGUAGE_TEXT(3, "Kaiba Seto! Ecco un\nmessaggio del maestro\n\nChevalsky! Vieni al mio\ncastello. Naturalmente,\n\nse vuoi salvare questo\nbamboccio... dovrai\n\nvenirci per forza,\nal castello!\n\n")
  LANGUAGE_TEXT(4, "\xa1Kaiba Seto, hay un mensaje\ndel amo Chevalsky!\n\nVen a mi castillo.\n\nDesde luego, si quieres\nsalvar este...\n\n\xa1Tendr\xe1s que venir\nal castillo!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SETO, 5, 1)
  LANGUAGE_TEXT(0, "You worm!\n\n")
  LANGUAGE_TEXT(1, "Petite vermine !\n\n")
  LANGUAGE_TEXT(2, "Du Ratte!\n\n")
  LANGUAGE_TEXT(3, "Verme schifoso!\n\n")
  LANGUAGE_TEXT(4, "\xa1Alima\xf1a!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 8, 0)
  PLAY_MUSIC(277)
  SLIDE_OBJECT(4, 1, 8)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBD0, map_22_state_08_08E8CBD0, 0x08E8CBDC, 0x08F04040)
  DELAY(16)
  SET_OBJECT_POSITION(3, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(3, 24)
  WALK_OBJECT_X(3, 80)
  DELAY(16)
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "Younger brother, you have\nfulfilled your mission!\n\nMaster Chevalsky will\npromote you to a higher\n\nposition!\n\n")
  LANGUAGE_TEXT(1, "H\xe9, fr\xe8re, alors tu as\naccompli ta mission !\n\nMa\xeetre Chevalsky sera\ns\xfbrement tr\xe8s content.\n\n")
  LANGUAGE_TEXT(2, "Bruder, du hast deinen\nAuftrag erf\xfcllt!\n\nMeister Chevalsky wird\nsich freuen!\n\n")
  LANGUAGE_TEXT(3, "Fratello, cos\xec hai portato\na termine la tua missione!\n\nIl maestro Chevalsky ne\nsar\xe0 pi\xf9 che felice!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hermano, cumpliste\ntu misi\xf3n!\n\n\xa1El amo Chevalsky\nestar\xe1 encantado!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Elder brother, you also have\ndone your job with most\n\nexcellence!\n\n")
  LANGUAGE_TEXT(1, "H\xe9 fr\xe8re, toi aussi, tu\nas bien fait ton boulot !\n\n")
  LANGUAGE_TEXT(2, "Auch du scheinst deine\nArbeit getan zu haben!\n\n")
  LANGUAGE_TEXT(3, "Fratello, a quanto pare,\nanche tu hai portato a\n\ntermine il tuo lavoro!\n\n")
  LANGUAGE_TEXT(4, "\xa1Hermano, t\xfa tambi\xe9n\npareces haber\n\nhecho tu trabajo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(32)
  MOVE_OBJECT(1, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 1)
  LANGUAGE_TEXT(0, "You punks! How dare you mock\nme!\n\n")
  LANGUAGE_TEXT(1, "Petite vermine ! Vous osez\nvous moquer de moi ?\n\n")
  LANGUAGE_TEXT(2, "Du Ratte! Ihr wagt es, euch\n\xfcber mich lustig zu machen?\n\n")
  LANGUAGE_TEXT(3, "Sporchi bastardi! Come\nosate burlarvi di me?\n\n")
  LANGUAGE_TEXT(4, "\xa1Alima\xf1as! \xbfOs\xe1is\nburlaros de m\xed?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(1, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(2, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(3, "Uohohohohoh...\n\n")
  LANGUAGE_TEXT(4, "Fufufufufufu...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(1, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(2, "Fufufufufufu...\n\n")
  LANGUAGE_TEXT(3, "Uohohohohoh...\n\n")
  LANGUAGE_TEXT(4, "Fufufufufufu......\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Master Chevalsky demands\nyour presence, Kaiba!\n\n")
  LANGUAGE_TEXT(1, "Ma\xeetre Chevalsky exige\nta pr\xe9sence, Kaiba !\n\n")
  LANGUAGE_TEXT(2, "Meister Chevalsky w\xfcnscht\ndich zu sprechen, Kaiba!\n\n")
  LANGUAGE_TEXT(3, "Il maestro Chevalsky esige\nla tua presenza, Kaiba!\n\n")
  LANGUAGE_TEXT(4, "\xa1El amo Chevalsky demanda\ntu presencia, Kaiba!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Come to Master Chevalsky's\ncastle!\n\n")
  LANGUAGE_TEXT(1, "Viens au ch\xe2teau de\nma\xeetre Chevalsky !\n\n")
  LANGUAGE_TEXT(2, "Komm in Meister\nChevalskys Burg!\n\n")
  LANGUAGE_TEXT(3, "Vieni al castello del\nmaestro Chevalsky!\n\n")
  LANGUAGE_TEXT(4, "\xa1Ven al castillo del\namo Chevalsky!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_PARA, EXPRESSION_PARA_HAPPY, 1)
  LANGUAGE_TEXT(0, "The castle that you...\n\n")
  LANGUAGE_TEXT(1, "Ce ch\xe2teau que tu...\n\n")
  LANGUAGE_TEXT(2, "Die Burg, die du...\n\n")
  LANGUAGE_TEXT(3, "Il castello che tu...\n\n")
  LANGUAGE_TEXT(4, "El castillo que t\xfa...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_DOX, EXPRESSION_DOX_HAPPY, 0)
  LANGUAGE_TEXT(0, "...Know so well! Fufufu...\n\n")
  LANGUAGE_TEXT(1, "... connais bien !\nFufufu...\n\n")
  LANGUAGE_TEXT(2, "... so gut kennst!\nFufufu...\n\n")
  LANGUAGE_TEXT(3, "... Conosci fin troppo\nbene! Uohohohoh...\n\n")
  LANGUAGE_TEXT(4, "... \xa1Conoces \xedntimamente!\n\nFufufu...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(3, 1, 96)
  PLAY_MUSIC(315)
  SLIDE_OBJECT(4, 1, 64)
  DELAY(16)
  PORTRAIT(PORTRAIT_SETO, 2, 1)
  LANGUAGE_TEXT(0, "Mokuba!\n\n")
  LANGUAGE_TEXT(1, "Mokuba !\n\n")
  LANGUAGE_TEXT(2, "Mokuba!\n\n")
  LANGUAGE_TEXT(3, "Mokuba!\n\n")
  LANGUAGE_TEXT(4, "\xa1Mokuba!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(1, 1, 4, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBDC, map_22_state_08_08E8CBDC, 0x08E8CBE8, 0x08E8CBF4)
  SET_OBJECT_POSITION(0, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(0, 24)
  WALK_OBJECT_X(0, 82)
  DELAY(16)
  SET_OBJECT_POSITION(13, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(13, 18)
  WALK_OBJECT_X(13, 87)
  DELAY(16)
  SET_OBJECT_POSITION(14, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(14, 30)
  WALK_OBJECT_X(14, 87)
  DELAY(16)
  SET_OBJECT_POSITION(5, 95, 16, 0)
  DELAY(16)
  WALK_OBJECT_Y(5, 24)
  MOVE_OBJECT(5, 1, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(0, 77)
  DELAY(16)
  LANGUAGE_TEXT(0, "{CARD_1}Let us help!\nLend us your God Card!{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}On va t'aider !\nPr\xeate ta carte de dieu !{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Helfen wir ihm!\nBorg uns die G\xf6tterkarte!{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Aiutiamolo!\nPrestaci la carta divina!{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1D\xe9janos ayudar!\n\xa1Danos tu carta del dios!{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBE8, map_22_state_08_08E8CBE8, 0x08E8CC00, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "{PLAYER} is right, Kaiba.\n\nNow is the time for\nteamwork.\n\nThe Dark Being must be\nsealed again...\n\n")
  LANGUAGE_TEXT(1, "{PLAYER} a raison,\nSeto.\n\nIl est d\xe9sormais\ntemps de coop\xe9rer.\n\nIl faut \xe0 nouveau enfermer\nl'Etre des t\xe9n\xe8bres...\n\n")
  LANGUAGE_TEXT(2, "{PLAYER} hat Recht, Seto.\n\nJetzt m\xfcssen wir\nzusammenarbeiten.\n\nDer Dunkle muss\nwieder eingesperrt werden.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER} ha ragione,\nSeto.\n\n\xc8 il momento di collaborare.\n\nIl Tenebroso deve essere\nrinchiuso di nuovo...\n\n")
  LANGUAGE_TEXT(4, "{PLAYER} tiene raz\xf3n, Seto.\n\nAhora es el momento\nde la cooperaci\xf3n.\n\nHay que volver a\nsellar al Ser Oscuro...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Quiet, you!\n\nI'm never going to cooperate\nwith you!\n\nI'll crush Pegasus on my own\nand get Mokuba back!\n\nHow many times do I have to\nsay that I don't have time\n\nfor your so-called ancient\nmagic!\n\n")
  LANGUAGE_TEXT(1, "Tais-toi !\n\nJe ne coop\xe9rerais\njamais avec toi !\n\nJe battrais Pegasus et\nr\xe9cup\xe9rerais Mokuba !\n\nJe n'ai pas de temps\n\xe0 perdre avec toutes\n\nces inepties occultes !\n\n")
  LANGUAGE_TEXT(2, "Sei still!\n\nMit einem wie dir\nwerde ich nie arbeiten!\n\nIch werde Pegasus vernich-\nten und Mokuba befreien!\n\nF\xfcr deinen okkulten Bl\xf6dsinn\nhabe ich keine Zeit!\n\n")
  LANGUAGE_TEXT(3, "Basta parlare!\n\nNon collaborer\xf2 mai\ncon tipi come te!\n\nDistrugger\xf2 Pegasus e\nriporter\xf2 indietro Mokuba!\n\nNon ho tempo per i tuoi\ndiscorsi senza senso!\n\n")
  LANGUAGE_TEXT(4, "\xa1Calla!\n\n\xa1Nunca cooperar\xe9\ncon seres como t\xfa!\n\n\xa1Aplastar\xe9 a Pegasus\ny rescatar\xe9 a Mokuba!\n\n\xa1No tengo tiempo para\ntu estupidez ocultista!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CC00, map_22_state_08_08E8CC00, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 0)
  SET_OBJECT_POSITION(1, 128, 96, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "We're left with no choice.\n\n")
  LANGUAGE_TEXT(1, "Nous n'avons pas le choix.\n\n")
  LANGUAGE_TEXT(2, "Wir haben keine Wahl.\n\n")
  LANGUAGE_TEXT(3, "Non abbiamo\naltra scelta.\n\n")
  LANGUAGE_TEXT(4, "No tenemos elecci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "We must also go to Sol\nChevalsky's... I mean...\n\nWe must also go to Pegasus's\ncastle.\n\n")
  LANGUAGE_TEXT(1, "Nous devons aussi\naller voir Sol Chevalsky...\n\nNon. Le ch\xe2teau o\xf9\nattend Pegasus.\n\n")
  LANGUAGE_TEXT(2, "Wir m\xfcssen ebenfalls zu\nSol Chevalsky...\n\nNein. Zur Burg, in der\nPegasus weilt.\n\n")
  LANGUAGE_TEXT(3, "Anche noi dobbiamo\nandare da Sol Chevalsky...\n\nNo. Il castello dove\naspetta Pegasus.\n\n")
  LANGUAGE_TEXT(4, "Nosotros tambi\xe9n\ndebemos ir donde\n\nSol Chevalsky...\n\nNo. El castillo donde\nespera Pegasus.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "But who knows where the\ncastle is?\n\n")
  LANGUAGE_TEXT(1, "Tu sais o\xf9 il est,\nce ch\xe2teau ?\n\n")
  LANGUAGE_TEXT(2, "Wei\xdft du, wo die Burg\nzu finden ist?\n\n")
  LANGUAGE_TEXT(3, "Allora tu sai dove si\ntrova questo castello?\n\n")
  LANGUAGE_TEXT(4, "\xbfSabes d\xf3nde est\xe1\neste castillo?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24609)
  DELAY(16)
  PLAY_MUSIC(402)
  WALK_OBJECT_X(6, 48)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 32)
  DELAY(8)
  MOVE_OBJECT(0, 1, 0, 0)
  MOVE_OBJECT(13, 1, 0, 0)
  MOVE_OBJECT(14, 1, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "You have proven yourselves\nto the Millennium Items.\n\nTrace the flow of time and\naccept your destiny.\n\nOne man knows where you must\ngo.\n\nYou must seek out Paradox.\n\n")
  LANGUAGE_TEXT(1, "Vous avez m\xe9rit\xe9 les\nObjets du mill\xe9nium.\n\nIl ne vous reste plus\nqu'\xe0 tracer votre chemin\n\net \xe0 accepter votre destin.\n\nOn vous montrera la\nbonne voie.\n\nVous devez rechercher\nParadox.\n\n")
  LANGUAGE_TEXT(2, "Ihr habt euch der\nMillenniumsgegenst\xe4nde\n\nals w\xfcrdig erwiesen.\n\nFolgt dem Fluss der Zeit und\nnehmt euer Schicksal an.\n\nDann wird sich der Weg\nf\xfcr euch auftun.\n\nSucht Paradox.\n\n")
  LANGUAGE_TEXT(3, "Avete dato prova di\nmeritare gli Oggetti\n\nMillenari. Seguite il flusso\ndel tempo e accettate\n\nil vostro destino. Vi\nsar\xe0 indicata la via.\n\nDovete cercare Paradox.\n\n")
  LANGUAGE_TEXT(4, "Hab\xe9is demostrado\nvuestra val\xeda con\n\nlos Objetos del Milenio.\nSeguid el paso del\n\ntiempo y aceptad\nvuestro destino.\n\nSe os mostrar\xe1\nel camino.\n\nDeb\xe9is buscar a\nParadox.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Paradox awaits you in China.\n\nHe will show you the way.\n\n")
  LANGUAGE_TEXT(1, "Paradox vous attend\nen Chine.\n\nIl vous montrera\nle chemin.\n\n")
  LANGUAGE_TEXT(2, "Paradox erwartet euch\nin China.\n\nEr wird euch den Weg\nweisen.\n\n")
  LANGUAGE_TEXT(3, "Paradox vi aspetta in Cina.\n\nVi indicher\xe0 la via.\n\n")
  LANGUAGE_TEXT(4, "Paradox os espera\nen China.\n\nOs mostrar\xe1 el camino.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(6, 1, 64, 0)
  DELAY(32)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "The Millennium Guard comes\nfrom the order that\n\nprotects the Millennium\nItems...\n\nI sensed that he was telling\nthe truth.\n\n{PLAYER}, you must go to\nChina.\n\nAs soon as possible.\n\n")
  LANGUAGE_TEXT(1, "Un famille de gardiens\ndes Objets du mill\xe9nium...\n\nIl fait partie de ce clan.\n\nJe n'ai ressenti aucune\nmauvaise intention\n\ndans ses paroles.\n\n{PLAYER}, tu devrais\naller en Chine.\n\nEt le plus rapidement\npossible.\n\n")
  LANGUAGE_TEXT(2, "Eine W\xe4chterfamilie f\xfcr die\nMillenniumsgegenst\xe4nde...\n\nEr geh\xf6rt zu dem Clan.\n\nIch sp\xfcrte keine b\xf6se\nAbsicht in seinen Worten.\n\n{PLAYER}, du solltest nach\nChina aufbrechen.\n\nM\xf6glichst bald.\n\n")
  LANGUAGE_TEXT(3, "Una famiglia di guardiani\nper gli Oggetti\n\nMillenari... Lui fa\nparte di quel clan.\n\nNon ho percepito alcuna\nmalignit\xe0 nelle sue parole.\n\n{PLAYER}, dovresti\nandare in Cina.\n\nE al pi\xf9 presto possibile.\n\n")
  LANGUAGE_TEXT(4, "Una familia de guardianes de\nlos Objetos del Milenio...\n\n\xc9l es de ese clan.\n\nNo sent\xed mala intenci\xf3n\nen sus palabras.\n\n{PLAYER}, deber\xedas\nir a China.\n\nY lo antes posible.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(5, 0)
  SET_OBJECT_POSITION(5, 128, 96, 0)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "I'm worried about Mokuba and\nKaiba...\n\nWe'd better find Pegasus's\ncastle quickly.\n\n")
  LANGUAGE_TEXT(1, "Je me fais du souci pour\nMokuba et Seto...\n\nOn ferait bien\nde vite trouver\n\nle ch\xe2teau de Pegasus.\n\n")
  LANGUAGE_TEXT(2, "Ich mache mir Sorgen um\nMokuba und Seto...\n\nWir sollten Pegasus' Burg\nschnell finden.\n\n")
  LANGUAGE_TEXT(3, "Sono preoccupato per\nMokuba e Seto...\n\nMeglio trovare in fretta\nil castello di Pegasus.\n\n")
  LANGUAGE_TEXT(4, "Me preocupaban\nMokuba y Seto...\n\nMejor hallamos el\ncastillo de Pegasus\n\nr\xe1pidamente.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Yugi's right.\n\nIf this Parachute guy can\nhelp us...\n\nWe'd betta find him quick.\n\n")
  LANGUAGE_TEXT(1, "Yugi a raison.\n\nSi ces deux types\npeuvent nous le dire...\n\nOn ferait bien de le\ntrouver rapidement.\n\n")
  LANGUAGE_TEXT(2, "Yugi hat Recht.\n\nWenn dieser Typ uns\netwas sagen kann...\n\nSollten wir ihn besser\nschnell finden.\n\n")
  LANGUAGE_TEXT(3, "Yugi ha ragione.\n\nSe quello sa qualcosa...\nMeglio trovarlo in fretta.\n\n")
  LANGUAGE_TEXT(4, "Yugi tiene raz\xf3n.\n\nSi este par de tipejos\nnos puede decir...\n\nMejor lo buscamos\nnosotros, r\xe1pido.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "That's Paradox, Joey.\nNot Parachute.\n\n{PLAYER}, let's go! We're\noff to China!\n\n")
  LANGUAGE_TEXT(1, "C'est Paradox, Joey.\n\n{PLAYER}, allons-y !\nEn route pour la Chine !\n\n")
  LANGUAGE_TEXT(2, "Das ist Paradox, Joey.\n\n{PLAYER}, gehen wir!\nAuf nach China!\n\n")
  LANGUAGE_TEXT(3, "Quello \xe8 Paradox, Joey.\n\n{PLAYER}, andiamo!\nSi parte per la Cina!\n\n")
  LANGUAGE_TEXT(4, "Es Paradox, Joey.\n\n\xa1{PLAYER}, vamos!\n\xa1A China!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  MOVE_OBJECT(0, 1, 0, 0)
  SET_FLAG(108)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E8CBF4, map_22_state_08_08E8CBF4, 0x08E8CC00, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(8)
  MOVE_OBJECT(1, 3, 0, 0)
  DELAY(8)
  PORTRAIT(PORTRAIT_SETO, 2, 0)
  LANGUAGE_TEXT(0, "Don't make me laugh,\n{PLAYER}!\n\nReshef the Dark Being... The\nend of the world...\n\nYou've been reading too many\nfantasy novels!\n\nYou guys do what you want!\n\nBut I'll get Mokuba back on\nmy own!\n\nAnd nobody is going to stop\nme!\n\n")
  LANGUAGE_TEXT(1, "Ne me fais pas rire,\n{PLAYER} !\n\nReshef, l'Etre des\nt\xe9n\xe8bres...\n\nLa fin du monde...\n\nCe sont de vraies\nbalivernes !\n\nVous faites ce que\nvous voulez !\n\nJe vais retrouver\nMokuba tout seul !\n\nPersonne ne m'arr\xeatera !\n\n")
  LANGUAGE_TEXT(2, "Du spinnst doch,\n{PLAYER}!\n\nReschef der Dunkle...\nDer Weltuntergang...\n\nUnglaubw\xfcrdiger\nSchwachsinn!\n\nIhr k\xf6nnt ja tun, was ihr\nwollt!\n\nIch werde Mokuba alleine\nbefreien!\n\nNiemand wird mich\naufhalten!\n\n")
  LANGUAGE_TEXT(3, "Ma non farmi ridere,\n{PLAYER}.\n\nReshef il Tenebroso...\nLa fine del mondo...\n\nChe sciocchezze\nincredibili!\n\nVoi fate pure come\nvi pare!\n\nRiporter\xf2 indietro\nMokuba da solo.\n\nNessuno potr\xe0 fermarmi!\n\n")
  LANGUAGE_TEXT(4, "\xa1No me hagas re\xedr,\n{PLAYER}!\n\nReshef, el Ser Oscuro...\nEl fin del mundo...\n\n\xa1Incre\xedble estupidez!\n\n\xa1Vosotros pod\xe9is hacer\ncomo quer\xe1is!\n\n\xa1Rescatar\xe9 a Mokuba\nyo solo!\n\n\xa1Nadie me detendr\xe1!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
