#include "event_macros.h"
#include "overworld.h"

/* map_00_state_09: map 0 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08E34C34, map_00_state_09_08E34C34, 0x08E34C4C, 0x08E34CB8)
  CHECK_FLAG(77)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C4C, map_00_state_09_08E34C4C, 0x08E34C7C, 0x08E34C64)
  CHECK_FLAG(163)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C7C, map_00_state_09_08E34C7C, 0x08E34C94, 0x08E34C88)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(1, 0, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, 2, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, 2, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have obtained the\nMillennium Scale.\n\nWe now have six Millennium\nItems... Thank you.\n\nWe should now be able to use\nall three Egyptian God\n\nCards!\n\n")
  LANGUAGE_TEXT(1, "Je vois que vous avez obtenu\nla Balance du mill\xe9nium.\n\nNous avons d\xe9sormais six\nObjets du mill\xe9nium...\n\nMerci.\n\nNous devrions \xe0 nouveau\npouvoir utiliser les trois\n\ncartes de dieux.\n\n")
  LANGUAGE_TEXT(2, "Ihr habt also die Millenniu-\nmsschale gefunden.\n\nDamit haben wir jetzt sechs\nMillenniumsgegenst\xe4nde...\n\nDanke.\n\nDie drei G\xf6tterkarten\nm\xfcssten jetzt wieder\n\naktiviert werden k\xf6nnen.\n\n")
  LANGUAGE_TEXT(3, "Cos\xec, avete ottenuto\nla Bilancia Millenaria.\n\nOra abbiamo sei\nOggetti Millenari...\n\nGrazie. Le tre carte\ndivine dovrebbero\n\nessere di nuovo\nutilizzabili.\n\n")
  LANGUAGE_TEXT(4, "Veo que hab\xe9is conseguido\nlas Pesas del Milenio.\n\nYa tenemos seis Objetos del\nMilenio... Gracias.\n\nAhora, deben de poder\nusarse otra vez las tres\n\ncartas de los dioses.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PLAY_MUSIC(0)
  PLAY_MUSIC(704)
  PLAY_MUSIC(291)
  REMOVE_CARD(238)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  LANGUAGE_TEXT(0, "Slifer the Sky Dragon card\nturned into stone!\n\n")
  LANGUAGE_TEXT(1, "La carte de Slifer,\nle Dragon c\xe9leste\n\na \xe9t\xe9 transform\xe9e\nen pierre !\n\n")
  LANGUAGE_TEXT(2, "Schleifer der Himmelsdrache,\nwurde versteinert!\n\n")
  LANGUAGE_TEXT(3, "La carta Slifer Drago del\nCielo si \xe8 tramutata\n\nin pietra!\n\n")
  LANGUAGE_TEXT(4, "\xa1La carta de Slifer, el\ndrag\xf3n del cielo se ha\n\nconvertido en piedra!\n\n")
  END_LANGUAGE_TEXT()
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  LANGUAGE_TEXT(1, "Le menu de r\xe9glage\ndu deck va s'afficher.")
  LANGUAGE_TEXT(2, "Das Men\xfc zur Deckeinstellung\nwird ge\xf6ffnet.")
  LANGUAGE_TEXT(3, "Verr\xe0 aperto il menu di\nsistemazione del deck.")
  LANGUAGE_TEXT(4, "Se abrir\xe1 el men\xfa de\najuste del deck.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C94, map_00_state_09_08E34C94, 0x08E34CA0, 0x08E34CAC)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Wh-what's happening?\n\n")
  LANGUAGE_TEXT(1, "Qu-qu'est-ce qui se passe ?\n\n")
  LANGUAGE_TEXT(2, "W-was geht hier vor?\n\n")
  LANGUAGE_TEXT(3, "Ma... ma che succede?\n\n")
  LANGUAGE_TEXT(4, "\xbfQ...qu\xe9 est\xe1 pasando?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 1)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, 8)
  LANGUAGE_TEXT(0, "What's wrong?\n\nN-no! The Winged Dragon of\nRa did not resurrect...\n\nAnd even worse, Slifer the\nSky Dragon has turned back\n\ninto stone...\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce qui ne va pas ?\n\nN-non ! Le Dragon ail\xe9 de\nRa demeure inchang\xe9...\n\nEt en plus, Slifer,\nle Dragon c\xe9leste\n\ns'est \xe0 nouveau\ntransform\xe9 en pierre...\n\n")
  LANGUAGE_TEXT(2, "Was ist passiert?\n\nN-nein! Der gefl\xfcgelte\nDrache von Ra ist\n\nunver\xe4ndert...\n\nSchlimmer ist aber, dass\nsich Schleifer der Himmels-\n\ndrache, wieder in Stein\nverwandelt hat.\n\n")
  LANGUAGE_TEXT(3, "Che c'\xe8 che non va?\n\nNo! Il Drago Alato di Ra\nresta immutato...\n\nLa cosa peggiore \xe8 che\nSlifer Drago del Cielo\n\nsi \xe8 tramutato di nuovo\nin pietra...\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 va mal?\n\n\xa1N...no! El Drag\xf3n con alas\nde Ra sigue sin cambiar...\n\nPeor, Slifer, el drag\xf3n del\ncielo se ha vuelto de\n\npiedra...\n\n")
  END_LANGUAGE_TEXT()
  CHECK_FLAG(65)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CA0, map_00_state_09_08E34CA0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Reshef's power must be\ngrowing exponentially!\n\nThe same fate most likely\nbefell Kaiba's card.\n\nObelisk the Tormentor has\nalso turned back into\n\nstone.\n\nPlease bring Kaiba here\nquickly.\n\nWe must fully revive the\nEgyptian God Cards...\n\nBut in order to do so, we\nneed the power of all seven\n\nMillennium Items.\n\nFurthermore, all three\nEgyptian God Cards must be\n\nreunited in one location.\n\n")
  LANGUAGE_TEXT(1, "Reshef doit s\xfbrement\nregagner en puissance.\n\nJ'ai peur que le m\xeame\nsort soit r\xe9serv\xe9 aux\n\ncartes de Kaiba Seto.\n\nIl faut \xe9galement que\nOb\xe9lisk, le Bourreau\n\nsoit transform\xe9\nen pierre.\n\nFaites imm\xe9diatement\nappel \xe0 Kaiba Seto.\n\nNous devons restaurer\nenti\xe8rement les\n\ncartes de dieux...\n\nPour cela, nous devons\nutiliser le septi\xe8me\n\nObjet du mill\xe9nium.\n\nEt r\xe9unir \xe0 nouveau\nles cartes de dieux.\n\n")
  LANGUAGE_TEXT(2, "Reschef muss unglaublich\nstark werden.\n\nIch f\xfcrchte, Kaiba Setos\nKarte erging es ebenso.\n\nObelisk, der Peiniger, ist\nvermutlich auch\n\nversteinert.\n\nBitte ruft sofort Kaiba\nSeto.\n\nWir m\xfcssen die G\xf6tterkarten\nwieder ganz herstellen.\n\nDazu m\xfcssen wir den {BYTE_8256}.\nMillenniumsgegenstand\n\neinsetzen.\n\nUnd die G\xf6tterkarten m\xfcssen\nwieder vereint werden.\n\n")
  LANGUAGE_TEXT(3, "Reshef star\xe0 accumulando\nuna forza incredibile.\n\nTemo che la stessa sorte\nsia toccata alla carta di\n\nKaiba Seto. Anche Obelisco\ndel Tiranno si sar\xe0\n\ntramutata in pietra. Convo-\ncate subito Kaiba Seto.\n\nDobbiamo ripristinare\ntotalmente le carte divine.\n\nPer farlo, dobbiamo usare\nil settimo Oggetto Mille-\n\nnario e le carte divine\nvanno riunite di nuovo.\n\n")
  LANGUAGE_TEXT(4, "Reshef debe de estar ganando\nuna incre\xedble fuerza.\n\nMe temo que la carta de\nKaiba Seto corra la misma\n\nsuerte.\n\nObelisk el Atormentador\ntambi\xe9n debe de haberse\n\nvuelto de piedra.\n\nPor favor, llamad a Kaiba\nSeto ahora mismo.\n\nDebemos restaurar las\ncartas de los dioses...\n\nPara hacerlo, debemos usar\nel s\xe9ptimo Objeto del\n\nMilenio.\n\nY deben reunirse las cartas\nde los dioses una vez m\xe1s.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The final Millennium Item...\n\nWe have yet to find the\nMillennium Puzzle.\n\nBut I have an idea as to its\nwhereabouts.\n\nPlease leave the Millennium\nPuzzle to me.\n\nWhile I look for it, please\nbring Kaiba here.\n\n")
  LANGUAGE_TEXT(1, "Le dernier Objet du\nmill\xe9nium...\n\nLe Puzzle du mill\xe9nium n'a\ntoujours pas \xe9t\xe9 trouv\xe9,\n\nje sais. J'ai une id\xe9e d'o\xf9\nil peut se trouver.\n\nLaissez-moi m'occuper\ndu Puzzle du mill\xe9nium.\n\nPendant ce temps,\nfaites appel \xe0 Kaiba Seto.\n\n")
  LANGUAGE_TEXT(2, "Der letzte Millenniums-\ngegenstand...\n\nDas Millenniumspuzzle wurde\nnoch nicht gefunden.\n\nIch wei\xdf in etwa, wo es\nsich befindet.\n\n\xdcberlasst mir das\nMillenniumspuzzle.\n\nBitte ruft unterdessen\nKaiba Seto.\n\n")
  LANGUAGE_TEXT(3, "L'ultimo Oggetto\nMillenario...\n\nIl Puzzle Millenario non\n\xe8 stato trovato, lo so.\n\nForse so dove potrebbe\nessere. Al Puzzle\n\nMillenario ci penso io. Nel\nfrattempo, vi chiedo di\n\nconvocare Kaiba Seto.\n\n")
  LANGUAGE_TEXT(4, "El Objeto del Milenio\nfinal...\n\nEl Puzzle del Milenio no se\nha encontrado, lo s\xe9.\n\nTengo una idea sobre\nsu paradero.\n\nPor favor, dejadme a m\xed\nel Puzzle del Milenio.\n\nEntre tanto, os ruego\nque llam\xe9is a Kaiba Seto.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(77)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CAC, map_00_state_09_08E34CAC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Is this the force of Reshef\nthe Dark Being?\n\nBut without the Egyptian God\nCards, we are helpless.\n\n")
  LANGUAGE_TEXT(1, "Est-ce que... \xe7a pourrait\n\xeatre l'\u0153uvre de Reshef,\n\nl'Etre des t\xe9n\xe8bres ?\n\nSans les cartes des dieux,\nnous ne pouvons rien faire.\n\n")
  LANGUAGE_TEXT(2, "K\xf6nnte Reschef der Dunkle\nverantwortlich sein?\n\nOhne gute Karten haben\nwir keine Chance.\n\n")
  LANGUAGE_TEXT(3, "Potrebbe essere opera\ndi Reshef il Tenebroso?\n\nNon avendo le carte divine,\nnon possiamo fare niente.\n\n")
  LANGUAGE_TEXT(4, "\xbfPo-podr\xeda \xe9sta ser\nla obra de Reshef,\n\nel Ser Oscuro?\n\nSin las cartas divinas\nno podemos hacer nada.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(272)
  REACTION(3, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "There must be something we\ncan do.\n\nI must think of all\npossibilities, no matter\n\nhow small.\n\nIn the meantime, please\ntrain diligently.\n\nYou must raise your duelist\nlevel, or you will have no\n\nchance to win.\n\n")
  LANGUAGE_TEXT(1, "On doit bien pouvoir\nfaire quelque chose.\n\nJe vais y r\xe9fl\xe9chir.\n\nPendant ce temps,\nentra\xeenez-vous\n\npour augmenter votre\nniveau de duelliste.\n\n")
  LANGUAGE_TEXT(2, "Aber wir m\xfcssen doch etwas\nunternehmen k\xf6nnen.\n\nIch werde dar\xfcber\nnachdenken.\n\nDerweil solltest du aber\nsorgsam trainieren.\n\nDu musst dein Duellanten-\nLevel erh\xf6hen.\n\n")
  LANGUAGE_TEXT(3, "Ma ci dev'essere qualcosa\nche si possa fare.\n\nCi penser\xf2 su.\n\nNel frattempo, vi chiedo di\nallenarvi diligentemente.\n\nDovete aumentare il vostro\nlivello duellante.\n\n")
  LANGUAGE_TEXT(4, "Pero algo se podr\xe1 hacer.\nPensar\xe9 al respecto.\n\nMientras, te pido\nque entrenes bien.\n\nDebes de elevar\ntu nivel de duelista.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "If you insist, Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Si tu le dis, Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Wenn du es sagst,\nIshizu.\n\n")
  LANGUAGE_TEXT(3, "Se lo dici tu, Ishizu.\n\n")
  LANGUAGE_TEXT(4, "Si t\xfa lo dices, Ishizu.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I guess we have no other\nchoice.\n\n")
  LANGUAGE_TEXT(1, "J'imagine qu'on\nn'a pas le choix.\n\n")
  LANGUAGE_TEXT(2, "Wir haben vermutlich keine\nandere Wahl.\n\n")
  LANGUAGE_TEXT(3, "Immagino che non\nabbiamo scelta.\n\n")
  LANGUAGE_TEXT(4, "Creo que no\ntenemos elecci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  WALK_OBJECT_Y(2, 56)
  WALK_OBJECT_X(2, 48)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24579)
  DELAY(8)
  MOVE_OBJECT(0, 0, 0, 0)
  MOVE_OBJECT(13, 0, 0, 0)
  MOVE_OBJECT(14, 0, 0, 0)
  DELAY(16)
  PLAY_MUSIC(33)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff kl\xe4ff kl\xe4ff kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau bau bau bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "This dog... Isn't this\nLucky, Tristan's dog?\n\n")
  LANGUAGE_TEXT(1, "Ce chien...\n\nCe n'est pas Lucky,\nle chien de Tristan ?\n\n")
  LANGUAGE_TEXT(2, "Dieser Hund ...\n\nIst das nicht Tristans\nLucky?\n\n")
  LANGUAGE_TEXT(3, "Questo cane...\nNon \xe8 Lucky di Tristan?\n\n")
  LANGUAGE_TEXT(4, "Este perro...\n\n\xbfNo es Lucky?\n\xbfEl perro de Tristan?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "What would Lucky be doing\nhere?\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce que\nle chien de Tristan\n\npourrait bien faire ici ?\n\n")
  LANGUAGE_TEXT(2, "Was macht denn Tristans\nHund hier?\n\n")
  LANGUAGE_TEXT(3, "E che ci farebbe qui\nil cane di Tristan?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 har\xe1 por aqu\xed\nel perro de Tristan?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf arf arf arf arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf wouf wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff kl\xe4ff kl\xe4ff kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau bau bau bau bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf arf arf arf arf!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(2, 55)
  WALK_OBJECT_Y(2, 71)
  MOVE_OBJECT(2, 2, 0, 0)
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24577)
  DELAY(8)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_JOEY_ANGRY, 8)
  LANGUAGE_TEXT(0, "Do ya think somethin'\nhappened at Tristan's\n\nhouse?\n\n")
  LANGUAGE_TEXT(1, "Il se passe peut-\xeatre\n\nquelque chose de\nbizarre chez les Taylor.\n\n")
  LANGUAGE_TEXT(2, "Vielleicht ist etwas bei\nden Taylors geschehen.\n\n")
  LANGUAGE_TEXT(3, "Forse sta succedendo\nqualcosa dai Taylor.\n\n")
  LANGUAGE_TEXT(4, "Puede que algo pase\nen casa de los Taylor.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Don't worry about me.\n\nYou should check on your\nfriend immediately.\n\nIn the meantime, I will\nthink of a plan to stop\n\nReshef.\n\n")
  LANGUAGE_TEXT(1, "Je suis d'accord\npour que vous partiez.\n\nVous devriez tout de\nsuite aller voir votre ami.\n\nPendant ce temps,\nje vais r\xe9fl\xe9chir\n\n\xe0 notre propre\nsituation.\n\n")
  LANGUAGE_TEXT(2, "Ich habe nichts dagegen,\nwenn du gehst.\n\nGeh und schau nach\ndeinem Freund.\n\nIch werde inzwischen \xfcber\nunsere Lage nachdenken.\n\n")
  LANGUAGE_TEXT(3, "Se volete andare, a\nme sta bene.\n\nDovreste andare a vedere\nsubito il vostro amico.\n\nNel frattempo penser\xf2\nalla nostra situazione.\n\n")
  LANGUAGE_TEXT(4, "No tengo objeci\xf3n\na que vayas.\n\nDebes de ir a ver a\ntu amigo al instante.\n\nMientras, pensar\xe9\nsobre nuestra situaci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_SURPRISED, 8)
  LANGUAGE_TEXT(0, "Okay, Ishizu. Good luck!\n\n{PLAYER}, Joey, let's go!\n\n")
  LANGUAGE_TEXT(1, "D'accord, Ishizu.\nOn y va tout de suite.\n\n{PLAYER}, Joey, en route !\n\n")
  LANGUAGE_TEXT(2, "Okay, Ishizu.\nDas machen wir.\n\n{PLAYER}, Joey,\ngehen wir!\n\n")
  LANGUAGE_TEXT(3, "Okay, Ishizu.\nLo faremo.\n\n{PLAYER}, Joey, andiamo!\n\n")
  LANGUAGE_TEXT(4, "OK, Ishizu.\nAs\xed se har\xe1.\n\n{PLAYER}, Joey,\n\xa1vamos!\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 0)
  PLAY_MUSIC(203)
  LANGUAGE_TEXT(0, "Arf!\n\n")
  LANGUAGE_TEXT(1, "Wouf !\n\n")
  LANGUAGE_TEXT(2, "Kl\xe4ff!\n\n")
  LANGUAGE_TEXT(3, "Bau!\n\n")
  LANGUAGE_TEXT(4, "\xa1Arf!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(2, 112)
  SET_FLAG(163)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C88, map_00_state_09_08E34C88, 0x08E34C94, 0x08E34C88)
  LANGUAGE_TEXT(0, "The deck adjustment menu\nwill be opened.")
  LANGUAGE_TEXT(1, "Le menu de r\xe9glage\ndu deck va s'afficher.")
  LANGUAGE_TEXT(2, "Das Men\xfc zur Deckeinstellung\nwird ge\xf6ffnet.")
  LANGUAGE_TEXT(3, "Verr\xe0 aperto il menu di\nsistemazione del deck.")
  LANGUAGE_TEXT(4, "Se abrir\xe1 el men\xfa de\najuste del deck.")
  END_LANGUAGE_TEXT()
  PAGE_BREAK()
  START_MENU()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C64, map_00_state_09_08E34C64, 0x08E34CD0, 0x08E34CE8)
  CHECK_FLAG(149)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CD0, map_00_state_09_08E34CD0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "In order to restore the\nEgyptian God Cards from\n\nstone...\n\nI'm sorry, but I have yet to\nfind the solution.\n\n")
  LANGUAGE_TEXT(1, "Restaurer les cartes\nde dieux p\xe9trifi\xe9es...\n\nJe n'ai pas encore\ntrouv\xe9 la solution.\n\n")
  LANGUAGE_TEXT(2, "Die G\xf6tterkarten aus ihrer\nVersteinerung befreien...\n\nIch habe die L\xf6sung noch\nnicht gefunden.\n\n")
  LANGUAGE_TEXT(3, "Recuperare le carte\ndivine dalla pietra...\n\nNon ho ancora trovato\nla soluzione.\n\n")
  LANGUAGE_TEXT(4, "Restaurar las cartas\nde los dioses a su estado\n\noriginal...\n\nNo he encontrado\na\xfan la soluci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CE8, map_00_state_09_08E34CE8, 0x08F04040, 0x08F04040)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You have returned at the\nright time.\n\nTo restore the Egyptian God\nCards from stone...\n\nWe need the Millennium\nItems.\n\n")
  LANGUAGE_TEXT(1, "Vous revenez au bon moment.\nPour restaurer les cartes\n\nde dieux transform\xe9es\nen pierre...\n\nVous aurez besoin des\nObjets du mill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "Ihr kommt genau zur rechten\nZeit zur\xfcck.\n\nOhne die Millenniumsgegen-\nst\xe4nde k\xf6nnen die G\xf6tter-\n\nkarten nicht aus ihrer\nVersteinerung befreit\n\nwerden...\n\n")
  LANGUAGE_TEXT(3, "Siete tornati al\nmomento giusto.\n\nPer recuperare le carte\ndivine dalla pietra...\n\nDi certo servono gli\nOggetti Millenari.\n\n")
  LANGUAGE_TEXT(4, "Hab\xe9is regresado en el\nmomento adecuado.\n\nPara restaurar las\ncartas de los dioses\n\nde su estado p\xe9treo...\n\nSon necesarios los\nObjetos del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "But we tried that already.\nIt didn't work.\n\n")
  LANGUAGE_TEXT(1, "Mais nous avons d\xe9j\xe0 essay\xe9.\nEt \xe7a n'a pas march\xe9.\n\n")
  LANGUAGE_TEXT(2, "Das versuchten wir schon.\nEs funktionierte nicht.\n\n")
  LANGUAGE_TEXT(3, "Ma ci abbiamo gi\xe0 provato\ne non ha funzionato.\n\n")
  LANGUAGE_TEXT(4, "Ya lo hemos intentado.\nNo funcion\xf3.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "That was because the Items\nwere too weak.\n\nWe need all the Millennium\nItems in one place.\n\nIf we have them all, the\nEgyptian God Cards will be\n\nrestored.\n\n")
  LANGUAGE_TEXT(1, "Parce que les objets que\nnous avions \xe9taient trop\n\nfaibles. Nous avons besoin\nde tous les Objets du\n\nmill\xe9nium en un seul\nendroit. Si nous les avons\n\ntous, les cartes de dieux\nseront restaur\xe9es.\n\n")
  LANGUAGE_TEXT(2, "Weil unsere Gegenst\xe4nde\nzu schwach waren.\n\nWir m\xfcssen alle\nMillenniumsgegenst\xe4nde an\n\neinem Ort vereinen.\n\nNur so k\xf6nnen wir die G\xf6t-\nterkarten wiederherstellen.\n\n")
  LANGUAGE_TEXT(3, "Perch\xe9 gli oggetti che\navevamo erano troppo\n\ndeboli. Tutti gli Oggetti\nMillenari devono essere\n\nriuniti. Se li abbiamo\ntutti, le carte divine\n\nsaranno recuperate.\n\n")
  LANGUAGE_TEXT(4, "Eso es porque los objetos\nque ten\xedamos eran\n\ndemasiado d\xe9biles.\nNecesitamos todos los\n\nObjetos del Milenio en\nun lugar.\n\nSi los tenemos todos,\npodremos restaurar\n\nlas cartas de los dioses.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "All the Millennium Items...\n\n")
  LANGUAGE_TEXT(1, "Tous les Objets du\nmill\xe9nium...\n\n")
  LANGUAGE_TEXT(2, "Alle Millenniumsgegen-\nst\xe4nde...\n\n")
  LANGUAGE_TEXT(3, "Tutti gli Oggetti\nMillenari...\n\n")
  LANGUAGE_TEXT(4, "Todos los Objetos del\nMilenio...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Yes, all that remains is the\nMillennium Puzzle.\n\n")
  LANGUAGE_TEXT(1, "Oui, il ne reste plus que\nle Puzzle du mill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "Ja, es bleibt nur das\nMillenniumspuzzle.\n\n")
  LANGUAGE_TEXT(3, "S\xec. Tutto ci\xf2 che rimane\n\xe8 il Puzzle Millenario.\n\n")
  LANGUAGE_TEXT(4, "S\xed, todo lo que queda es\nel Puzzle del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 8192)
  DELAY(8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Have no fear.\n\nI have an idea of its\nwhereabouts.\n\nI will retrieve the\nMillennium Puzzle.\n\n")
  LANGUAGE_TEXT(1, "Ce n'est pas un probl\xe8me.\n\nJ'ai une id\xe9e d'o\xf9\nil peut se trouver.\n\nJe vais aller chercher\nle Puzzle du mill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "Keine Angst.\n\nIch denke, ich wei\xdf,\nwo es ist.\n\nIch besorge das\nMillenniumspuzzle.\n\n")
  LANGUAGE_TEXT(3, "Non abbiate paura!\n\nHo un'idea di dove\nsi possa trovare.\n\nAndr\xf2 a recuperare il\nPuzzle Millenario.\n\n")
  LANGUAGE_TEXT(4, "No tem\xe1is.\n\nTengo una idea de\nd\xf3nde puede estar.\n\nIr\xe9 a recuperar el\nPuzzle del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ishizu, you don't have to\ngo.\n\nLet us handle it.\n\n")
  LANGUAGE_TEXT(1, "Ishizu, ce n'est pas la\npeine.\n\nSi tu nous laissais\naller le chercher ?\n\n")
  LANGUAGE_TEXT(2, "Ishizu, du musst es\nnicht finden.\n\nWarum \xfcberl\xe4sst du es\nnicht uns?\n\n")
  LANGUAGE_TEXT(3, "Ishizu, non c'\xe8\nbisogno che ci vada tu.\n\nPerch\xe9 non lasci che\nce ne occupiamo noi?\n\n")
  LANGUAGE_TEXT(4, "Ishizu, no tienes que\nir a buscarlo.\n\n\xbfPor qu\xe9 no nos lo\ndejas a nosotros?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I have a different task for\nyou.\n\n")
  LANGUAGE_TEXT(1, "J'aimerais vous confier\nune autre t\xe2che.\n\n")
  LANGUAGE_TEXT(2, "Ich m\xf6chte euch mit einer\nanderen Aufgabe betrauen.\n\n")
  LANGUAGE_TEXT(3, "Vorrei affidarvi un\ncompito diverso.\n\n")
  LANGUAGE_TEXT(4, "Deseo confiaros\nuna tarea diferente.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "A different one?\n\n")
  LANGUAGE_TEXT(1, "Une autre t\xe2che ?\n\n")
  LANGUAGE_TEXT(2, "Eine andere Aufgabe?\n\n")
  LANGUAGE_TEXT(3, "Un compito diverso?\n\n")
  LANGUAGE_TEXT(4, "\xbfUna tarea diferente?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Ra and Slifer were not the\nonly Egyptian God Cards\n\nthat turned into stone...\n\nKaiba's Obelisk the\nTormentor must have turned\n\ninto stone as well.\n\nPlease find Kaiba.\n\nWe need to bring the seven\nMillennium Items...\n\nAnd the three Egyptian God\nCards together.\n\nOnly then can we fully\nrestore the Egyptian God\n\nCards.\n\n")
  LANGUAGE_TEXT(1, "Les cartes des dieux\np\xe9trifi\xe9es...\n\nJ'ai bien peur que Ra\net Slifer ne soient pas\n\nles seules cartes\naffect\xe9es.\n\nKaiba Seto poss\xe8de\nOb\xe9lisk, le Bourreau.\n\nCette carte a s\xfbrement\n\xe9t\xe9 aussi p\xe9trifi\xe9e.\n\nS'il vous pla\xeet, appellez\nKaiba Seto.\n\nNous allons rassembler\nles {BYTE_8256} Objets du mill\xe9nium.\n\nEt puis ces trois\ncartes des dieux.\n\nEnsuite, nous restaurerons\nenti\xe8rement les cartes\n\nde dieux.\n\n")
  LANGUAGE_TEXT(2, "Die versteinerten G\xf6tter-\nkarten...\n\nIch f\xfcrchte, es traf nicht\nnur Ra und Schleifer.\n\nKaiba Seto hat Obelisk,\nden Peiniger.\n\nAuch diese G\xf6tterkarte\nmuss versteinert sein.\n\nRuft bitte Seto Kaiba.\n\nWir vereinigen die {BYTE_8256}\nMillenniumsgegenst\xe4nde...\n\nUnd die {BYTE_8252} G\xf6tterkarten.\n\nDann stellen wir die G\xf6tter-\nkarten wieder v\xf6llig her.\n\n")
  LANGUAGE_TEXT(3, "Le carte divine trasformate\nin pietra...\n\nTemo che questa sorte\nnon sia toccata solo\n\na Ra e a Slifer. Kaiba\nSeto ha Obelisco del\n\nTiranno. Anche quella\ncarta deve essersi\n\ntramutata in pietra.\n\nVi prego di convocare\nKaiba Seto.\n\nRiuniremo i sette\nOggetti Millenari...\n\nE le tre carte divine.\n\nAllora potremo recuperare\ntutte le carte divine.\n\n")
  LANGUAGE_TEXT(4, "Las cartas de los dioses\nconvertidas en piedra...\n\nTemo que no hayan\nsido solamente Ra y\n\nSlifer las afectadas.\n\nKaiba Seto tiene a Obelisk\nel atormentador.\n\nEsa carta del dios se\nhabr\xe1 convertido\n\nen piedra tambi\xe9n.\n\nPor favor, llamad\na Kaiba Seto.\n\nAunaremos los siete\nObjetos del Milenio...\n\nY las tres cartas de\nlos dioses.\n\nEntonces, restaura-\nremos totalmente las\n\ncartas de los dioses.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(77)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CB8, map_00_state_09_08E34CB8, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I will find the Millennium\nPuzzle..\n\nIn the meantime, please\nbring Kaiba here.\n\n")
  LANGUAGE_TEXT(1, "Je vais trouver le\nPuzzle du mill\xe9nium.\n\nEn attendant, je vous\ndemande de faire appel\n\n\xe0 Kaiba Seto.\n\n")
  LANGUAGE_TEXT(2, "Ich werde das Millenniums-\npuzzle finden.\n\nRuft unterdessen Kaiba\nSeto.\n\n")
  LANGUAGE_TEXT(3, "Trover\xf2 il Puzzle\nMillenario.\n\nNel frattempo, vi chiedo di\nconvocare Kaiba Seto.\n\n")
  LANGUAGE_TEXT(4, "Encontrar\xe9 el\nPuzzle del Milenio.\n\nEntre tanto, os ruego\nque llam\xe9is a Kaiba Seto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C40, map_00_state_09_08E34C40, 0x08E34C58, 0x08E34CC4)
  CHECK_FLAG(77)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C58, map_00_state_09_08E34C58, 0x08E34C7C, 0x08E34C70)
  CHECK_FLAG(163)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34C70, map_00_state_09_08E34C70, 0x08E34CDC, 0x08E34CE8)
  CHECK_FLAG(149)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CDC, map_00_state_09_08E34CDC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "I thought you were going to\nlook for your friend\n\nTristan.\n\nI'm having difficulty\nfinding out how to restore\n\nthe Egyptian God Cards.\n\nIt will take me more time.\nSince there is little that\n\nyou can do to help...\n\nYou should concentrate on\nfinding your friend.\n\n")
  LANGUAGE_TEXT(1, "Vous n'alliez pas chercher\nvotre ami Tristan ?\n\nJe n'ai pas de chance\ndans mes recherches.\n\nLes cartes de dieux\nne peuvent pas\n\n\xeatre restaur\xe9es.\n\nPuisque vous ne pouvez\npresque rien faire...\n\nConcentrez-vous et\nrecherche votre ami.\n\n")
  LANGUAGE_TEXT(2, "Wolltet ihr nicht euren\nFreund Tristan suchen?\n\nIch habe mit meiner\nSuche wenig Gl\xfcck.\n\nDie G\xf6tterkarten k\xf6nnen\nnoch nicht\n\nwiederhergestellt werden.\n\nDa ihr nicht viel tun\nk\xf6nnt...\n\nSucht doch besser nach\neurem Freund.\n\n")
  LANGUAGE_TEXT(3, "Non dovevate cercare il\nvostro amico Tristan?\n\nNon ho molta fortuna\nnella mia ricerca.\n\nLe carte divine non\npossono ancora essere\n\nrecuperate. Dato che\npotete fare ben poco...\n\nPotete concentrarvi sulla\nricerca del vostro amico.\n\n")
  LANGUAGE_TEXT(4, "\xbfNo ibais a buscar a\nvuestro amigo Tristan?\n\nNo tengo mucha suerte\ncon mi b\xfasqueda.\n\nLas cartas de los dioses a\xfan\nno pueden restaurarse.\n\nYa que hay poco\nque pod\xe9is hacer...\n\nOs pod\xe9is concentrar en\nencontrar a vuestro amigo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34CC4, map_00_state_09_08E34CC4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The Egyptian God Cards have\nbeen turned back into\n\nstone.\n\nTo fully resurrect them, the\nseven Millennium Items...\n\nAnd the three Egyptian God\nCards must be brought\n\ntogether.\n\nPlease bring Kaiba here\nright away.\n\n")
  LANGUAGE_TEXT(1, "Les cartes de dieux ont\n\xe9t\xe9 \xe0 nouveau p\xe9trifi\xe9es.\n\nPour les ressusciter, les\nsept Objets du mill\xe9nium...\n\net les trois cartes\nde dieux doivent\n\n\xeatre rassembl\xe9s.\n\nVeuillez imm\xe9diatement\nappeler Kaiba Seto.\n\n")
  LANGUAGE_TEXT(2, "Die G\xf6tterkarten wurden\nwieder zu Stein.\n\nUm sie wieder v\xf6llig herzu-\nstellen, m\xfcssen die\n\nsieben Millenniumsgegen-\nst\xe4nde...\n\nUnd die drei G\xf6tterkarten\nvereint werden.\n\nBitte ruft sofort\nKaiba Seto.\n\n")
  LANGUAGE_TEXT(3, "Le carte divine sono\nstate tramutate di\n\nnuovo in pietra. Per risu-\nscitarle completamente, i\n\nsette Oggetti Millenari...\n\nE le tre carte divine\ndevono essere riuniti.\n\nVi prego, convocate\nsubito Kaiba Seto.\n\n")
  LANGUAGE_TEXT(4, "Las cartas de los dioses se\nhan vuelto de piedra de\n\nnuevo. Para resucitarlas\ncompletamente, los siete\n\nObjetos del Milenio...\n\nY las tres cartas de los\ndioses deben ponerse\n\njuntos.\n\nPor favor, llamad a\nKaiba Seto ahora mismo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
