#include "event_macros.h"

/* map_00_state_12: map 0 state 12 */

EVENT_SCRIPT_REPLACEMENT(0x08E34E80, map_00_state_12_08E34E80, 0x08E34E8C, 0x08E34E98)
  PLAY_MUSIC(9)
  MOVE_OBJECT(2, 1, 4, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Big brother, we can go too,\nright?\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re, on peut\nvenir aussi, non ?\n\n")
  LANGUAGE_TEXT(2, "Gro\xdfer Bruder, d\xfcrfen\nwir mitkommen?\n\n")
  LANGUAGE_TEXT(3, "Fratello, anche noi\npossiamo andarci, vero?\n\n")
  LANGUAGE_TEXT(4, "Gran hermano, nosotros\npodemos ir tambi\xe9n,\n\n\xbfverdad?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 4, 0)
  MOVE_OBJECT(2, 1, 0, 0)
  DELAY(16)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "No... I have a bad feeling\nabout this.\n\n")
  LANGUAGE_TEXT(1, "Non... J'ai un mauvais\npressentiment.\n\n")
  LANGUAGE_TEXT(2, "Nein... Ich habe kein gutes\nGef\xfchl bei der Sache.\n\n")
  LANGUAGE_TEXT(3, "No... Ho un brutto\npresentimento.\n\n")
  LANGUAGE_TEXT(4, "No... Tengo un mal\npresentimiento sobre ello.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 4, 0)
  LANGUAGE_TEXT(0, "But the Neo Ghouls...\nThey're almost gone.\n\n")
  LANGUAGE_TEXT(1, "Mais les Neo Ghouls...\nIls sont presque partis.\n\n")
  LANGUAGE_TEXT(2, "Aber die Neo Ghouls...\nSie sind fast fort.\n\n")
  LANGUAGE_TEXT(3, "Ma i Neo Ghouls... Se ne\nsono andati, praticamente.\n\n")
  LANGUAGE_TEXT(4, "Pero los Neo Ghouls...\nCasi han desaparecido.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 3, 4, 0)
  MOVE_OBJECT(3, 1, 0, 0)
  DELAY(16)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "Let's wait until {PLAYER}\nand his friends come back.\n\n")
  LANGUAGE_TEXT(1, "Attendons le retour de\n{PLAYER} et ses amis.\n\n")
  LANGUAGE_TEXT(2, "Warten wir, bis {PLAYER} und\nseine Freunde zur\xfcck sind.\n\n")
  LANGUAGE_TEXT(3, "Aspettiamo che tornino\n{PLAYER} e i suoi amici.\n\n")
  LANGUAGE_TEXT(4, "Esperemos hasta que {PLAYER}\ny sus amigos vuelvan.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 1, 4, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "You never let us do\nanything!\n\n")
  LANGUAGE_TEXT(1, "Grand fr\xe8re, c'est\nvraiment un radin !\n\n")
  LANGUAGE_TEXT(2, "Unser gro\xdfer Bruder\nist ein Angsthase!\n\n")
  LANGUAGE_TEXT(3, "Nostro fratello \xe8\nun gran tirchio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Gran hermano\nes un taca\xf1o!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 4, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  PORTRAIT(14, 7, 8)
  LANGUAGE_TEXT(0, "I'm only trying to keep you\nsafe!\n\n")
  LANGUAGE_TEXT(1, "Un radin ? Que\nveux-tu dire par l\xe0 ?\n\n")
  LANGUAGE_TEXT(2, "Angsthase?\nWas meinst du damit?\n\n")
  LANGUAGE_TEXT(3, "Tirchio?\nChe vorresti dire?\n\n")
  LANGUAGE_TEXT(4, "\xbfTaca\xf1o?\n\xbfQu\xe9 quieres decir?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 1, 4, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "I'm old enough to take care\nof myself! I mean, I need\n\nboth my hands to count my\nage!\n\n")
  LANGUAGE_TEXT(1, "Tu es radin,\nc'est tout !\n\n")
  LANGUAGE_TEXT(2, "Du bist ein Angsthase,\nweil du Angst hast!\n\n")
  LANGUAGE_TEXT(3, "Sei un tirchio perch\xe9\nsei uno spilorcio!\n\n")
  LANGUAGE_TEXT(4, "\xa1Eres un taca\xf1o\nporque vales poco!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(4, 3, 4, 0)
  MOVE_OBJECT(4, 1, 0, 0)
  DELAY(16)
  MOVE_OBJECT(2, 3, 0, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "C'mon, don't fight.\n\n")
  LANGUAGE_TEXT(1, "N-ne vous battez pas.\n\n")
  LANGUAGE_TEXT(2, "Streitet euch nicht.\n\n")
  LANGUAGE_TEXT(3, "Non vi azzuffate.\n\n")
  LANGUAGE_TEXT(4, "N...no luch\xe9is.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(14, 7, 8)
  LANGUAGE_TEXT(0, "If that's what you want to\ndo, fine.\n\n")
  LANGUAGE_TEXT(1, "Bien, tu peux faire\nce que tu veux.\n\n")
  LANGUAGE_TEXT(2, "Mach doch, was du\nwillst.\n\n")
  LANGUAGE_TEXT(3, "Bene, fai pure come vuoi.\n\n")
  LANGUAGE_TEXT(4, "Bien, pues puedes\nhacer lo que quieras.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "But you're going to have to\nlook after everyone.\n\n")
  LANGUAGE_TEXT(1, "Mais tu vas devoir t'occuper\nde tout le monde.\n\n")
  LANGUAGE_TEXT(2, "Aber du musst auf\nalle aufpassen.\n\n")
  LANGUAGE_TEXT(3, "Ma dovrai badare a tutti.\n\n")
  LANGUAGE_TEXT(4, "Pero tendr\xe1s que\ncuidar de todos.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 1, 4, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Okay, big brother, I will.\n\n")
  LANGUAGE_TEXT(1, "OK, grand fr\xe8re,\nj'ai compris.\n\n")
  LANGUAGE_TEXT(2, "Okay, gro\xdfer Bruder,\nich verspreche es.\n\n")
  LANGUAGE_TEXT(3, "Okay, fratello, lo far\xf2.\n\n")
  LANGUAGE_TEXT(4, "Bueno, gran hermano,\nlo har\xe9.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(2, 3, 4, 0)
  DELAY(16)
  LANGUAGE_TEXT(0, "Let's go, you guys.\n\nYay!\n\n")
  LANGUAGE_TEXT(1, "Bon allez, venez les gars.\n\nOuais !\n\n")
  LANGUAGE_TEXT(2, "Los, kommt dann.\n\nYay!\n\n")
  LANGUAGE_TEXT(3, "Allora andiamo, ragazzi.\n\nS\xec!\n\n")
  LANGUAGE_TEXT(4, "Bueno, vamos, t\xedos.\n\n\xa1Guay!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(4, 97)
  WALK_OBJECT_Y(4, 37)
  WALK_OBJECT_X(4, 144)
  WALK_OBJECT_X(3, 97)
  WALK_OBJECT_Y(3, 37)
  WALK_OBJECT_X(3, 144)
  WALK_OBJECT_X(2, 97)
  WALK_OBJECT_Y(2, 37)
  WALK_OBJECT_X(2, 144)
  DELAY(16)
  PORTRAIT(14, 7, 8)
  LANGUAGE_TEXT(0, "My brothers can be so\nfrustrating...\n\n")
  LANGUAGE_TEXT(1, "Mes fr\xe8res sont\nparfois \xe9nervants...\n\n")
  LANGUAGE_TEXT(2, "Meine Br\xfcder k\xf6nnen mich\nzur Verzweiflung bringen...\n\n")
  LANGUAGE_TEXT(3, "A volte i miei fratelli\nmi deludono proprio...\n\n")
  LANGUAGE_TEXT(4, "Mis hermanos pueden\nser tan frustrantes...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(0, 31)
  WALK_OBJECT_X(0, 38)
  WALK_OBJECT_Y(13, 37)
  WALK_OBJECT_X(13, 28)
  WALK_OBJECT_Y(14, 25)
  WALK_OBJECT_X(14, 28)
  DELAY(32)
  WALK_OBJECT_Y(1, 31)
  WALK_OBJECT_X(1, 48)
  DELAY(16)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "Oh, you're back.\n\nMost of the Neo Ghouls have\nbeen routed from the Town\n\nof Domino.\n\nBut there are some still\nlurking around.\n\nCan you find and defeat\nthem?\n\n")
  LANGUAGE_TEXT(1, "Ah, vous \xeates l\xe0.\n\nLa plupart des Neo Ghouls\nont \xe9t\xe9 chass\xe9s de Domino.\n\nMais certains r\xe9sistent.\n\nVous pouvez les trouver\net les battre en duel ?\n\n")
  LANGUAGE_TEXT(2, "Oh, da seid ihr wieder.\n\nDie meisten Neo Ghouls\nsind aus Domino vertrieben.\n\nNur einige Unbesiegte\nh\xe4ngen hier noch rum.\n\nK\xf6nnt ihr sie nicht\nfinden und besiegen?\n\n")
  LANGUAGE_TEXT(3, "Oh, eccovi di ritorno.\n\nQuasi tutti i Neo Ghouls\nsono stati cacciati da\n\nDomino. Ma alcuni si\naggirano ancora imbattuti.\n\nPotreste andare a scovarli\ne batterli?\n\n")
  LANGUAGE_TEXT(4, "\xa1Oh!, hab\xe9is vuelto.\n\nHan echado a la mayor\xeda de\nNeo Ghouls de Domino.\n\nPero a\xfan hay unos\nacechando invictos.\n\n\xbfPodr\xedais buscarlos\ny batirlos?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E8C, map_00_state_12_08E34E8C, 0x08F04040, 0x08F04040)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "Okay, thanks!\n\nThey should still be in\nClocktower Square.\n\n")
  LANGUAGE_TEXT(1, "OK, merci !\n\nIls doivent encore\n\xeatre Place du clocher.\n\n")
  LANGUAGE_TEXT(2, "Okay, danke!\n\nSie sind bestimmt noch\nauf dem Turmuhrenplatz.\n\n")
  LANGUAGE_TEXT(3, "Okay, grazie!\n\nDovrebbero ancora essere\nin Piazza Campanile.\n\n")
  LANGUAGE_TEXT(4, "Bien, \xa1gracias!\n\nDeben de estar\na\xfan en Plaza del reloj.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(159)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34E98, map_00_state_12_08E34E98, 0x08E34E8C, 0x08E34E98)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "Oh, come on, don't be that\nway. We need your help.\n\n")
  LANGUAGE_TEXT(1, "Oh, allez, ne dites pas \xe7a.\nOn a besoin de votre aide.\n\n")
  LANGUAGE_TEXT(2, "Oh, kommt schon, seid\ndoch nicht so.\n\nWir brauchen eure Hilfe.\n\n")
  LANGUAGE_TEXT(3, "Ma dai, non fate cos\xec.\nCi serve il vostro aiuto.\n\n")
  LANGUAGE_TEXT(4, "Oh, venga, no se\xe1is as\xed.\nPrecisamos vuestra ayuda.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(0, 0, 8)
  LANGUAGE_TEXT(0, "{CARD_1}Yes\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Oui\nNon{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Ja\nNein{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}S\xec\nNo{CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}S\xed\nNo{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34EA4, map_00_state_12_08E34EA4, 0x08F04040, 0x08F04040)
  PORTRAIT(14, 0, 8)
  LANGUAGE_TEXT(0, "Most of the Neo Ghouls have\nbeen routed from the Town\n\nof Domino.\n\nBut there are still some\nlurking around.\n\nThey should still be in\nClocktower Square.\n\nPlease find and defeat them.\n\n")
  LANGUAGE_TEXT(1, "La plupart des Neo Ghouls\nont \xe9t\xe9 chass\xe9s de Domino.\n\nMais certains r\xe9sistent.\n\nIls doivent encore \xeatre\nPlace du clocher.\n\nTrouve-les et bats-les\nen duel.\n\n")
  LANGUAGE_TEXT(2, "Die meisten Neo Ghouls\nsind aus Domino vertrieben.\n\nNur einige Unbesiegte\nh\xe4ngen hier noch rum.\n\nSie sind bestimmt noch\nauf dem Uhrenturmplatz.\n\nFindet und schlagt sie\nbitte.\n\n")
  LANGUAGE_TEXT(3, "Quasi tutti i Neo Ghouls\nsono stati cacciati da\n\nDomino. Ma alcuni si\naggirano ancora imbattuti.\n\nDovrebbero ancora essere\nin Piazza Campanile.\n\nTi prego, trovali\ne sconfiggili.\n\n")
  LANGUAGE_TEXT(4, "Han echado a la mayor\xeda de\nNeo Ghouls de Domino.\n\nPero a\xfan hay unos\nacechando invictos.\n\nDeben de estar\na\xfan en Plaza del reloj.\n\nPor favor, ve a\nbuscarlos y b\xe1telos.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
