#include "event_macros.h"
#include "overworld.h"

/* map_01_state_01: map 1 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08E42670, map_01_state_01_08E42670, 0x08E4267C, 0x08F04040)
  PLAY_MUSIC(4)
  WALK_OBJECT_X(0, 24)
  WALK_OBJECT_X(14, 28)
  WALK_OBJECT_X(13, 28)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{PLAYER}, what are you still\ndoing here?\n\nWeren't the three of you\ntaking the Duel Express?\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, qu'est-ce que\ntu fais encore par ici ?\n\nTous les trois, vous\nn'\xe9tiez pas cens\xe9s\n\nprendre le Duel Express ?\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, was machst du\ndenn hier?\n\nWolltet ihr drei nicht mit\ndem Duel Express fahren?\n\n")
  LANGUAGE_TEXT(3, "Cosa ci fai qui adesso,\n{PLAYER}?\n\nVoi tre non dovevate\nprendere il Duel Express?\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, \xbfqu\xe9 haces\npor aqu\xed ahora?\n\n\xbfNo ibais a coger los\ntres el Duel Express?\n\n")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(332)
  FADE_SCREEN(4)
  PLAY_MUSIC(8)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_TEA_SURPRISED, 1)
  LANGUAGE_TEXT(0, "Whaaat? The Millennium\nPuzzle is gone?\n\nBut how? How did that\nhappen?\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Le Puzzle du\nmill\xe9nium a disparu ?\n\nMais comment est-ce\nque cela a pu arriver ?\n\n")
  LANGUAGE_TEXT(2, "Waaas? Das Millenniums-\npuzzle ist verschwunden?\n\nAber wie? Wie konnte das\nnur passieren?\n\n")
  LANGUAGE_TEXT(3, "Che cosa? Il Puzzle\nMillenario \xe8 sparito?\n\nMa come?\nCosa sar\xe0 successo?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9\xe9\xe9? \xbfNo est\xe1\nel Puzzle del Milenio?\n\nPero, \xbfc\xf3mo?\n\xbfQu\xe9 habr\xe1 pasado?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(64)
  WALK_OBJECT_X(4, 40)
  WALK_OBJECT_Y(4, 32)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Forgive me, but I overheard\nyour conversation.\n\n")
  LANGUAGE_TEXT(1, "Excusez-moi, mais j'ai\nentendu votre conversation.\n\n")
  LANGUAGE_TEXT(2, "Entschuldigt, aber ich habe\nzuf\xe4llig euer Gespr\xe4ch\n\nmit angeh\xf6rt.\n\n")
  LANGUAGE_TEXT(3, "Scusatemi, ma ho sentito\nla vostra conversazione.\n\n")
  LANGUAGE_TEXT(4, "Perd\xf3n, pero o\xed\nvuestra conversaci\xf3n.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24585)
  DELAY(8)
  MOVE_OBJECT(0, 2, 0, 0)
  MOVE_OBJECT(14, 2, 0, 0)
  MOVE_OBJECT(13, 2, 0, 0)
  MOVE_OBJECT(3, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "So it seems the Millennium\nPuzzle has also\n\ndisappeared...\n\nWhat I have feared the most\nis coming to fruition...\n\nPlease.\n\nI need your help.\n\n")
  LANGUAGE_TEXT(1, "Alors le Puzzle du\nmill\xe9nium a disparu.\n\nCe que je craignais est\nen train d'arriver...\n\nS'il vous pla\xeet. Je vous\nsupplie de m'aider.\n\n")
  LANGUAGE_TEXT(2, "Das Millenniumspuzzle ist\nalso auch verschwunden.\n\nMeine Bef\xfcrchtungen\nbewahrheiten sich...\n\nBitte.\n\nIch bitte euch dringend um\neure Hilfe.\n\n")
  LANGUAGE_TEXT(3, "E cos\xec, \xe8 sparito anche il\nPuzzle Millenario.\n\nQuello che temevo si sta\nrealizzando... Vi prego,\n\ndovete aiutarmi.\n\n")
  LANGUAGE_TEXT(4, "As\xed que tambi\xe9n ha\ndesaparecido el\n\nPuzzle del Milenio.\n\nLo que tem\xeda ha\nocurrido...\n\nPor favor.\n\nNecesito vuestra\nayuda.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 24585)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I see you're puzzled, but\nthat is only to be\n\nexpected.\n\nPlease bear with me and\nlisten to my words\n\ncarefully.\n\n")
  LANGUAGE_TEXT(1, "Je comprends que vous\nsoyez \xe9tonn\xe9s.\n\nMais veuillez m'accorder\ndeux minutes pour vous\n\n")
  LANGUAGE_TEXT(2, "Eure \xdcberraschung ist\nverst\xe4ndlich.\n\nBitte geduldet euch und\nh\xf6rt mir zu.\n\n")
  LANGUAGE_TEXT(3, "\xc8 normale che siate\nconfusi. Vi prego,\n\nabbiate pazienza e\nstatemi a sentire.\n\n")
  LANGUAGE_TEXT(4, "Es l\xf3gico vuestro\nasombro.\n\nPor favor,\nescuchadme.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4267C, map_01_state_01_08E4267C, 0x08E42688, 0x08F04040)
  LANGUAGE_TEXT(0, "I have come to ask you\nduelists for your help.\n\nYou must save the world from\nReshef the Dark Being.\n\n")
  LANGUAGE_TEXT(1, "expliquer. Je suis venu vous\ndemander votre aide,\n\n\xe0 vous les duellistes.\n\nVeuillez sauver le monde\ndesgriffes de Reshef,\n\nl'\xeatre des t\xe9n\xe8bres.\n\n")
  LANGUAGE_TEXT(2, "Ich m\xf6chte euch Duellanten\num Hilfe bitten.\n\nBitte befreit die Welt von\nReschef dem Dunklen.\n\n")
  LANGUAGE_TEXT(3, "Sono venuta a chiedere\nil vostro aiuto, duellanti.\n\nVi prego, salvate il mondo\nda Reshef il Tenebroso.\n\n")
  LANGUAGE_TEXT(4, "He venido a rogar vuestra\nayuda, duelistas.\n\nPor favor, salvad al mundo\nde Reshef, el Ser Oscuro.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(271)
  REACTION(0, 24585)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I understand this is sudden\nand confusing.\n\nHowever, the world is in\ngrave peril.\n\nOnly strong duelists, such\nas yourselves, can save us\n\nall from ruin before it's\ntoo late!\n\n")
  LANGUAGE_TEXT(1, "Je comprends que ce soit\nun choc pour vous.\n\nMais le monde court\nun grand danger.\n\nSeuls vous,\nles grands duellistes,\n\nserez capables de\nnous sauver du chaos.\n\n")
  LANGUAGE_TEXT(2, "Es ist sicher ein schwerer\nSchock f\xfcr euch.\n\nAber die Welt ist in\ngro\xdfer Gefahr.\n\nNur ihr starken Duellanten\nk\xf6nnt sie retten.\n\n")
  LANGUAGE_TEXT(3, "So che per voi sar\xe0\nun duro colpo, ma il\n\nmondo \xe8 in grave\npericolo. Solo voi,\n\nforti duellanti, potrete\nsalvarci dalla catastrofe.\n\n")
  LANGUAGE_TEXT(4, "Comprendo que os\nsorprenda.\n\nSin embargo, el mundo\ncorre un gran peligro.\n\nS\xf3lo vosotros, duelistas\npoderosos, pod\xe9is\n\nsalvarnos de la ruina.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(4, 24)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "All the Millennium Items\nhave disappeared...\n\nThis is most likely due to\nReshef's resurrection.\n\nAn unknown entity must have\ncommenced a fusion ritual\n\non the Egyptian God Cards...\n\n")
  LANGUAGE_TEXT(1, "La disparition des\nObjets du mill\xe9nium...\n\nest probablement li\xe9e\nau retour de Reshef.\n\nQuelqu'un a r\xe9alis\xe9\nune fusion des\n\ncartes de dieux...\n\n")
  LANGUAGE_TEXT(2, "Das Verschwinden der\nMillenniumsgegenst\xe4nde...\n\nMuss mit der Auferstehung\nvon Reschef zusammenh\xe4ngen.\n\nJemand hat ein Fusionsritual\nan G\xf6tterkarten\n\nvollf\xfchrt...\n\n")
  LANGUAGE_TEXT(3, "La sparizione degli Oggetti\nMillenari... probabilmente\n\n\xe8 dovuta alla risurrezione\ndi Reshef. Qualcuno ha\n\neseguito un rituale di\nfusione sulle\n\ncarte divine...\n\n")
  LANGUAGE_TEXT(4, "La desaparici\xf3n de\nObjetos del Milenio...\n\nSe debe probablemente\na la resurrecci\xf3n\n\nde Reshef.\n\nAlguien hizo un ritual\nde fusi\xf3n de las\n\ncartas de los dioses...\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Which re-released Reshef the\nDark Being into the world.\n\nThe ritual stole the mighty\npower of the Egyptian God\n\nCards.\n\nAnd the cards, now drained\nof its mystical energies,\n\ntransformed into stone.\n\nYou must send the Dark Being\nto its eternal rest before\n\nthe world is destroyed.\n\nBut in order to accomplish\nthis feat, the Egyptian God\n\nCards are absolutely\nessential.\n\nHowever, since the Egyptian\nGod Cards have been turned\n\nto stone, they no longer\nhave power.\n\nOnly the Millennium Items\ncan restore them to their\n\nformer glory.\n\nThe Items have been\nscattered all over the\n\nworld.\n\nThey must be regained to\nresurrect the Egyptian God\n\nCards.\n\nAnd with help from the\nEgyptian Gods, we may have\n\na chance of sealing away the\nDark Being.\n\nI am counting on you to\naccomplish this task.\n\n")
  LANGUAGE_TEXT(1, "Et Reshef, l'Etre des\nt\xe9n\xe8bres est de retour\n\ndans notre monde.\n\nLe pouvoir des cartes\nde dieux avait \xe9t\xe9 vol\xe9.\n\nSans aucun pouvoir,\nles cartes ont \xe9t\xe9\n\ntransform\xe9es en pierres.\n\nL'Etre des t\xe9n\xe8bres doit\n\xeatre de retour dans son\n\ndonjon. Pour cela, les\ncartes de dieux sont\n\nabsolument essentielles.\n\nEt pourtant, transform\xe9es en\npierre ces cartes de dieux\n\nsont totalement inutiles.\n\nPour les restaurer,\nnous devons trouver\n\nles Objets du mill\xe9nium.\n\nIls ont \xe9t\xe9 \xe9parpill\xe9s\ndans le monde entier.\n\nIl faut les r\xe9cup\xe9rer\npour restaurer\n\nles cartes de dieux.\nEt il ne restera plus qu'\xe0\n\nenfermer l'Etre des\nt\xe9n\xe8bres.\n\nC'est ce que je suis venu\nvous demander.\n\n")
  LANGUAGE_TEXT(2, "Und Reschef der Dunkle be-\ntrat diese Welt aufs Neue.\n\nEr stahl die Macht der\nG\xf6tterkarten.\n\nOhne diese Macht wurden\ndie Karten zu Stein.\n\nDer Dunkle muss in sein\nVerlies zur\xfcckkehren.\n\nDazu sind aber die G\xf6tter-\nkarten unerl\xe4sslich.\n\nVersteinert sind die G\xf6tter-\nkarten allerdings nutzlos.\n\nSie k\xf6nnen nur mit den\nMillenniumsgegenst\xe4nden\n\nwiederhergestellt werden.\n\nDiese sind \xfcber die\nganze Welt zerstreut.\n\nIhr m\xfcsst sie beschaffen.\n\nDann muss Reschef wieder\nhinter Schloss und Riegel.\n\nDas ist es, worum ich\neuch bitte.\n\n")
  LANGUAGE_TEXT(3, "E Reshef il Tenebroso\n\xe8 riapparso in questo\n\nmondo. Aveva rubato il\npotere delle carte divine.\n\nPrivate del potere, le carte\nsi mutarono in pietra.\n\nIl Tenebroso deve\nessere riportato nella\n\nsua prigione. Per farlo, le\ncarte divine sono assolu-\n\ntamente indispensabili.\n\nTuttavia, se trasformate\nin pietra, le carte divine\n\nnon servono a niente.\n\nPer ripristinarle, ci servo-\nno gli Oggetti Millenari.\n\nSono stati sparsi per\ntutto il mondo. Devono\n\nessere recuperati per\nripristinare le carte\n\ndivine. Poi occorre isolare\ndi nuovo il Tenebroso.\n\nSono venuta qui per\nchiedervi questo.\n\n")
  LANGUAGE_TEXT(4, "Y Reshef, el Ser Oscuro\nresurgi\xf3 en este mundo.\n\nRob\xf3 el poder de\nlas cartas de los dioses.\n\nLas cartas, sin poder,\nse convirtieron en piedra.\n\nEl Ser Oscuro ha de\nregresar a su mazmorra.\n\nPara ello, las cartas de los\ndioses son esenciales.\n\nPero, de piedra, las cartas\nde los dioses son in\xfatiles.\n\nPara restaurarlas,\ntenemos que tener\n\nlos Objetos del Milenio.\n\nEst\xe1n esparcidos por\ntodo el mundo.\n\nHan de recuperarse para\nrestaurar las cartas.\n\nY, entonces, el Ser Oscuro\ntendr\xe1 que retornar a su\n\nencierro.\nEsto vengo a pediros.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  MOVE_OBJECT(4, 0, 4, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Please, my powerful\nduelists...\n\nIf left unchecked, the Dark\nBeing's strength will keep\n\ngrowing.\n\nThe world will be shrouded\nin perpetual darkness.\n\nPlease help save the world!\n\n")
  LANGUAGE_TEXT(1, "S'il vous pla\xeet, oh\npuissants duellistes.\n\nSi on laisse l'Etre des\nt\xe9n\xe8bres faire, il\n\ncontinuera \xe0 grandir.\nEt bient\xf4t, le monde\n\nsera plong\xe9 dans les\nt\xe9n\xe8bres.\n\nJe vous supplie\nde me venir en aide.\n\n")
  LANGUAGE_TEXT(2, "Bitte, ihr m\xe4chtigen\nDuellanten...\n\nWenn ihm niemand\ntrutzt, w\xe4chst der\n\nDunkle immer weiter,\nund die Welt wird bald\n\nvon seiner Finsternis\numh\xfcllt.\n\nBitte, helft mir.\n\n")
  LANGUAGE_TEXT(3, "Vi prego, potenti\nduellanti... Se non lo\n\nfermiamo, il Tenebroso\ncontinuer\xe0 a crescere e\n\npresto il mondo sar\xe0\navvolto dalle sue tenebre.\n\nVi supplico, aiutatemi.\n\n")
  LANGUAGE_TEXT(4, "Por favor, o poderosos\nduelistas...\n\nSi no se le controla, el\nSer Oscuro seguir\xe1\n\ncreciendo.\n\nPronto, el mundo estar\xe1\nsumido en la oscuridad.\n\nPor favor, ruego\nvuestra ayuda.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "What should we do, {PLAYER}?\n\n")
  LANGUAGE_TEXT(1, "Qu'est-ce que tu vas\nfaire, {PLAYER} ?\n\n")
  LANGUAGE_TEXT(2, "Was willst du tun,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(3, "Tu che vuoi fare,\n{PLAYER}?\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9 vas a hacer,\n{PLAYER}?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 0, 0, 0)
  MOVE_OBJECT(0, 0, 0, 0)
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42688, map_01_state_01_08E42688, 0x08E42694, 0x08E426D0)
  LANGUAGE_TEXT(0, "{CARD_1}Defeat the Dark Being\nThat's impossible...{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}Battre l'Etre des t\xe9n\xe8bres\nC'est impossible...{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}Den Dunklen besiegen...\nUnm\xf6glich...{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Sconfiggere il Tenebroso\n\xc8 impossibile... {CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}Derrotar al Ser Oscuro\nEso es imposible...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42694, map_01_state_01_08E42694, 0x08E426A0, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, 1)
  LANGUAGE_TEXT(0, "I knew you'd say that.\n\nBesides, I have to find my\nMillennium Puzzle.\n\nI'll go with you, {PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Je pensais bien\nque tu dirais \xe7a.\n\nDe toute fa\xe7on,\n\nil faut que je trouve\nle Puzzle du mill\xe9nium.\n\nJe viens avec toi,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Das dachte ich mir schon,\ndass du das sagen w\xfcrdest.\n\nIch muss ohnehin das\nMillenniumspuzzle finden.\n\nIch werde dich begleiten,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Sapevo che l'avresti detto.\n\nDevo trovare comunque\nil Puzzle Millenario.\n\nIo vengo con te,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "Sab\xeda que dir\xedas eso.\n\nDe todos modos,\ntengo que encontrar\n\nel Puzzle del Milenio.\n\nIr\xe9 contigo,\n{PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(293)
  OBJECT_EFFECT(16384, 1)
  DELAY(16)
  PORTRAIT(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "Since you said I'm a\npowerful duelist, how can I\n\nrefuse!\n\nI'm coming along, too,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "En tant que duelliste,\nje ne peux pas refuser.\n\nJe viens aussi avec\ntoi, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "Als starker Duellant, wie\ndu zu Recht sagtest,\n\nkann ich wohl schlecht\nablehnen.\n\nIch bin ebenfalls dabei,\n{PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Come hai detto tu, sono un\npotente duellante e non\n\nposso tirarmi indietro.\nVengo anch'io, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "Como poderoso\nduelista, como t\xfa\n\ndijiste, no puedo\nnegarme.\n\n\xa1Yo tambi\xe9n voy,\n{PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, 2, 0, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426A0, map_01_state_01_08E426A0, 0x08E426AC, 0x08E426B8)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "I thank you from the bottom\nof my heart.\n\n")
  LANGUAGE_TEXT(1, "Sinc\xe8rement,\nje vous remercie.\n\n")
  LANGUAGE_TEXT(2, "Ich bin euch sehr dankbar.\n\n")
  LANGUAGE_TEXT(3, "Vi ringrazio di cuore.\n\n")
  LANGUAGE_TEXT(4, "Oye, os lo agradezco.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, 2, 0, 0)
  DELAY(16)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "First, the Millennium Items\nmust be recovered.\n\nAs a descendent of a clan of\ngravekeepers...\n\nI can sense the faint pulses\nof the Millennium Items.\n\nYou must first make your way\nto the Egypt Exhibition.\n\nIf my feelings are correct,\nthe first of the Millennium\n\nItems should be there.\n\n")
  LANGUAGE_TEXT(1, "D'abord, il faut r\xe9cup\xe9rer\nles Objets du mill\xe9nium.\n\nEn tant que descendant\ndu clan des gardiens\n\nde la crypte...\n\nje ressens les pulsions\ndes Objets du mill\xe9nium.\n\nVous devez d'abord\nvous diriger vers\n\nl'exposition \xe9gyptienne.\nLe premier Objet du\n\nmill\xe9nium est\ncertainement l\xe0-bas.\n\n")
  LANGUAGE_TEXT(2, "Erst m\xfcssen die Millenniums-\ngegenst\xe4nde wieder her.\n\nAls Nachfahre einer langen\nLinie von Kryptaw\xe4chtern...\n\nkann ich den Puls der Mill-\nenniumsgegenst\xe4nde ahnen.\n\nZuerst m\xfcsst ihr zur\n\xe4gyptischen Ausstellung.\n\nDort d\xfcrfte der erste\nMillenniumsgegenstand sein.\n\n")
  LANGUAGE_TEXT(3, "Prima bisogna recuperare\ngli Oggetti Millenari.\n\nCome discendente di un clan\ndi custodi di cripte...\n\npercepisco leggermente\nle pulsazioni degli Oggetti\n\nMillenari. Prima dovete\nrecarvi alla Mostra Egizia,\n\ndove dovrebbe trovarsi\nil primo degli Oggetti\n\nMillenari.\n\n")
  LANGUAGE_TEXT(4, "Primero, hay que recuperar\nlos Objetos del Milenio.\n\nComo descendiente de un clan\nde guardas de criptas puedo\n\nsentir un poco el latido de\nlos Objetos del Milenio.\n\nPrimero, hay que ir a la\nExposici\xf3n Egipcia. El\n\nprimero de los Objetos del\nMilenio deber\xeda estar ah\xed.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(4, 16)
  DELAY(32)
  MOVE_OBJECT(4, 0, 0, 0)
  DELAY(32)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I know what I ask is a great\nimposition.\n\nBut I have no one to turn to\nexcept for you...\n\n")
  LANGUAGE_TEXT(1, "Je sais que ce que je vous\ndemande est difficile.\n\nMais vous \xeates les seules\npersonnes \xe0 qui je peux\n\nm'adresser...\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf, dass ich viel von\neuch verlange. Aber ich\n\nwusste nicht, an wen ich\nmich sonst wenden konnte...\n\n")
  LANGUAGE_TEXT(3, "Lo so che vi sto\nchiedendo molto.\n\nMa non avevo altri a cui\nrivolgermi, se non a voi...\n\n")
  LANGUAGE_TEXT(4, "S\xe9 que lo que pido es\nuna gran imposici\xf3n.\n\nPero no tengo a nadie\nm\xe1s que vosotros...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "{CARD_1}Leave it to us!\n...{CARD_2}\n\n")
  LANGUAGE_TEXT(1, "{CARD_1}On s'en charge !\n...{CARD_2}\n\n")
  LANGUAGE_TEXT(2, "{CARD_1}\xdcberlass das nur uns!\n...{CARD_2}\n\n")
  LANGUAGE_TEXT(3, "{CARD_1}Lascia fare a noi!\n... {CARD_2}\n\n")
  LANGUAGE_TEXT(4, "{CARD_1}\xa1D\xe9janoslo a nosotros!\n...{CARD_2}\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426AC, map_01_state_01_08E426AC, 0x08E426C4, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, 1)
  LANGUAGE_TEXT(0, "Your words have given me\nhope for the first time in\n\na long time.\n\nI leave the fate of the\nworld in your hands...\n\n")
  LANGUAGE_TEXT(1, "Vous me redonnez\ndu courage.\n\nQuelqu'un comme vous sauvera\npeut-\xeatre le monde...\n\n")
  LANGUAGE_TEXT(2, "Deine Worte geben mir Mut.\n\nVielleicht wird einer wie du\ndie Welt retten...\n\n")
  LANGUAGE_TEXT(3, "Le vostre parole mi\ninfondono coraggio.\n\nForse qualcuno come voi\nsalver\xe0 il mondo...\n\n")
  LANGUAGE_TEXT(4, "Vuestras palabras me\ndan valor.\n\nQuiz\xe1s alguien como\nvosotros salve el mundo...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426C4, map_01_state_01_08E426C4, 0x08F04040, 0x08F04040)
  COMMAND_7C_ARG(2, 4)
  MOVE_OBJECT(4, 1, 32, 0)
  PLAY_MUSIC(4)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426B8, map_01_state_01_08E426B8, 0x08E426C4, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "I know this seems like an\nimpossible task...\n\nBut I have faith in your\nspirit that you will save\n\nthe world...\n\n")
  LANGUAGE_TEXT(1, "Je sais, cette t\xe2che\nn'a pas l'air facile...\n\nMais j'ai confiance\nen vous, je crois que\n\nvous y arriverez...\n\n")
  LANGUAGE_TEXT(2, "Ich wei\xdf, die Aufgabe\nscheint unm\xf6glich...\n\nAber ich vertraue darauf,\ndass ihr die Welt vor dem\n\nUntergang bewahren werdet.\n\n")
  LANGUAGE_TEXT(3, "So che sembra una\nmissione impossibile...\n\nMa credo fermamente\nche salverete il mondo...\n\n")
  LANGUAGE_TEXT(4, "S\xe9 que parece una\nlabor imposible...\n\nPero conf\xedo en que\nsalvar\xe9is el mundo...\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426D0, map_01_state_01_08E426D0, 0x08E42688, 0x08F04040)
  PORTRAIT(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "What? And pretend that this\nDark Being doesn't exist?\n\nThis doesn't sound like you,\n{PLAYER}.\n\n")
  LANGUAGE_TEXT(1, "Quoi ? Et faire comme si\nl'Etre des t\xe9n\xe8bres\n\nn'existait pas ?\n\nCa ne te ressemble\npas, {PLAYER}.\n\n")
  LANGUAGE_TEXT(2, "Was? Und so tun, als g\xe4be\nes diesen Dunklen nicht?\n\nDas passt so gar nicht zu\ndir, {PLAYER}.\n\n")
  LANGUAGE_TEXT(3, "Cosa? Vuoi fingere che\nquesto Tenebroso non\n\nesista? Non \xe8 da te dire\nquesto, {PLAYER}.\n\n")
  LANGUAGE_TEXT(4, "\xbfQu\xe9? \xbfY pretender que\nel Ser Oscuro no existi\xf3?\n\nNo te pega decir\neso, {PLAYER}.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426E8, map_01_state_01_08E426E8, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I want to ride the Duel\nExpress...\n\nBut at my level, I'll get\ncreamed in seconds.\n\n")
  LANGUAGE_TEXT(1, "J'aimerais prendre\nle Duel Express...\n\nMais \xe0 mon niveau,\nje vais me faire\n\nimm\xe9diatement\nr\xe9duire en bouillie.\n\n")
  LANGUAGE_TEXT(2, "Ich m\xf6chte mit dem Duel\nExpress fahren...\n\nAber so schlecht wie ich\nbin, werde ich sofort\n\nkaltgemacht.\n\n")
  LANGUAGE_TEXT(3, "Mi piacerebbe andare\nsul Duel Express...\n\nMa al mio livello, mi\nfarebbero fuori subito.\n\n")
  LANGUAGE_TEXT(4, "Me gustar\xeda ir en\nel Duel Express...\n\nPero en mi nivel, no\ndurar\xeda un segundo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426F4, map_01_state_01_08E426F4, 0x08E42700, 0x08E42718)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_RED_HAT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42700, map_01_state_01_08E42700, 0x08E4270C, 0x08F0404C)
  LANGUAGE_TEXT(0, "A street duel? Sure! Let's\nduel!\n\n")
  LANGUAGE_TEXT(1, "Un duel dans la rue ?\nOK ! Battons-nous !\n\n")
  LANGUAGE_TEXT(2, "Ein Stra\xdfenduell?\nKlar, da bin ich dabeil!\n\n")
  LANGUAGE_TEXT(3, "Un duello di strada?\nBene! Duelliamo pure!\n\n")
  LANGUAGE_TEXT(4, "\xbfUn duelo callejero?\n\xa1Vale! \xa1Luchemos!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(1)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4270C, map_01_state_01_08E4270C, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "Sigh... I knew I needed to\nbe better.\n\n")
  LANGUAGE_TEXT(1, "Tu vois ? Je savais que\nje devais m'am\xe9liorer.\n\n")
  LANGUAGE_TEXT(2, "Siehst du? Ich wusste doch,\ndass ich noch \xfcben muss.\n\n")
  LANGUAGE_TEXT(3, "Visto? Sapevo che dovevo\navere un livello maggiore.\n\n")
  LANGUAGE_TEXT(4, "\xbfVes? Sab\xeda que ten\xeda\nque ser mejor que esto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_RED_HAT)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42718, map_01_state_01_08E42718, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "I'll challenge you when I\nhave more experience.\n\n")
  LANGUAGE_TEXT(1, "Je t'affronterai quand\nj'aurai plus d'exp\xe9rience.\n\n")
  LANGUAGE_TEXT(2, "Ich fordere meine Revanche,\nwenn ich etwas mehr\n\nErfahrung besitze.\n\n")
  LANGUAGE_TEXT(3, "Ti sfider\xf2 quando\navr\xf2 pi\xf9 esperienza.\n\n")
  LANGUAGE_TEXT(4, "Te retar\xe9 cuando tenga\nm\xe1s experiencia.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42724, map_01_state_01_08E42724, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "Today's the day the Duel\nExpress starts chugging!\n\nThe best duelists have\nentered this tournament,\n\nand when I say the best, I\nmean the best!\n\n")
  LANGUAGE_TEXT(1, "Aujourd'hui, c'est la\njourn\xe9e Duel Express !\n\nTous les duellistes\nles plus forts\n\nparticipent au tournoi.\n\n")
  LANGUAGE_TEXT(2, "Heute ist der Tag des Duel\nExpress!\n\nAlle starken Duellanten sind\nf\xfcr das Turnier gemeldet.\n\n")
  LANGUAGE_TEXT(3, "Oggi \xe8 il giorno del Duel\nExpress!\n\nSono ammessi al torneo tutti\ni duellanti forti.\n\n")
  LANGUAGE_TEXT(4, "\xa1Hoy es el d\xeda del\nDuel Express!\n\nTodos los duelistas\nbuenos est\xe1n inscritos\n\nen el torneo.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42730, map_01_state_01_08E42730, 0x08E4273C, 0x08E42754)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_STYLISH_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4273C, map_01_state_01_08E4273C, 0x08E42748, 0x08F0404C)
  LANGUAGE_TEXT(0, "You must be a bad duelist if\nyou're out here.\n\n")
  LANGUAGE_TEXT(1, "Si tu es l\xe0, tu ne dois\npas \xeatre tr\xe8s bon.\n\n")
  LANGUAGE_TEXT(2, "Wenn du hier drau\xdfen stehst,\nbist du wohl nicht sehr\n\ngut.\n\n")
  LANGUAGE_TEXT(3, "Non devi essere granch\xe9\nse sei qui fuori.\n\n")
  LANGUAGE_TEXT(4, "No debes de ser muy\nbueno si est\xe1s aqu\xed.\n\n")
  END_LANGUAGE_TEXT()
  DUEL(2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42748, map_01_state_01_08E42748, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(4)
  LANGUAGE_TEXT(0, "I said all the top duelists\nare aboard the Duel\n\nExpress.\n\n...But I may be wrong.\nYou're pretty tough!\n\n")
  LANGUAGE_TEXT(1, "Tous les bons duellistes\nsont sur le Duel Express.\n\nC'est ce que je pensais.\nMais tu es fort.\n\n")
  LANGUAGE_TEXT(2, "Alle guten Duellanten soll-\nten im Duel Express sein.\n\nDas dachte ich jedenfalls.\nAber du bist stark.\n\n")
  LANGUAGE_TEXT(3, "Tutti i bravi duellanti\ndovrebbero essere sul\n\nDuel Express. Cos\xec credevo.\nMa tu sei forte.\n\n")
  LANGUAGE_TEXT(4, "Todos los duelistas\nbuenos deber\xedan estar\n\nen el Duel Express.\n\nEs lo que pens\xe9.\nPero t\xfa eres fuerte.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(EVENT_FLAG_DEFEATED_STYLISH_HAIR)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42754, map_01_state_01_08E42754, 0x08F04040, 0x08F04040)
  LANGUAGE_TEXT(0, "You know I'm no match for\nyou.\n\n")
  LANGUAGE_TEXT(1, "Je ne suis pas un\nadversaire pour toi.\n\n")
  LANGUAGE_TEXT(2, "Ich bin dir nicht\ngewachsen.\n\n")
  LANGUAGE_TEXT(3, "Per te non sono\nun buon avversario.\n\n")
  LANGUAGE_TEXT(4, "No soy rival para ti.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E426DC, map_01_state_01_08E426DC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_TEA, EXPRESSION_NEUTRAL, 1)
  LANGUAGE_TEXT(0, "You're going, {PLAYER}?\n\nThe Egypt Exhibition is the\nlast stop on the Duel\n\nExpress.\n\nI don't think it's left yet,\nbut it will soon! If you\n\nhurry, you can still catch\nit at the station.\n\nI'll be waiting at Yugi's\ngrandpa's place.\n\nCome see us when you get\nback, okay?\n\n")
  LANGUAGE_TEXT(1, "Tu t'en vas, {PLAYER} ?\n\nL'Exposition \xe9gyptienne,\nc'est le dernier arr\xeat\n\ndu Duel Express.\nSi tu te d\xe9p\xeaches,\n\ntu pourras encore\nle prendre \xe0 la gare.\n\nJe t'attendrais chez le\ngrand-p\xe8re de Yugi.\n\nViens nous voir quand\ntu seras de retour, OK ?\n\n")
  LANGUAGE_TEXT(2, "Du willst gehen, {PLAYER}?\n\nDie \xe4gypt. Ausstellung ist\nbei der letzten Haltestelle\n\ndes Duel Express.\n\nWenn du dich beeilst, kannst\ndu ihn noch am Bahnhof\n\nerwischen. Ich warte bei\nYugis Gro\xdfvater auf dich.\n\nKomm dorthin, wenn du\nzur\xfcck bist, ja?\n\n")
  LANGUAGE_TEXT(3, "Tu ci vai, {PLAYER}?\n\nLa Mostra Egizia \xe8 l'ultima\nfermata del Duel Express.\n\nSe ti sbrighi, puoi ancora\nprenderlo alla stazione.\n\nIo aspetter\xf2 dal nonno\ndi Yugi.\n\nVieni a trovarci quando\ntorni, ok?\n\n")
  LANGUAGE_TEXT(4, "\xbfT\xfa vas, {PLAYER}?\n\nLa Exposici\xf3n Egipcia\nes la \xfaltima parada del\n\nDuel Express.\n\nSi corres, todav\xeda puedes\ncogerlo en la estaci\xf3n.\n\nEstar\xe9 esperando en\ncasa del abuelo de Yugi.\n\nVuelve a vernos cuando\nregreses, \xbfvale?\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(3, 1, 48, 0)
  SET_FLAG(EVENT_FLAG_TEA_LEFT_FOR_THE_SHOP)
  FALLTHROUGH()
END_EVENT_SCRIPT()
