#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_00_state_07: map 0 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E34BBC, map_00_state_07_08E34BBC, 0x08E34BD4, 0x08E34BE0)
  LOAD_SPRITE(1, SPRITE_ISHIZU)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_ISHIZU_AFTER_WATCHING_THE_KAIBAMAN_SHOW)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BD4, map_00_state_07_08E34BD4, 0x08F04040, 0x08F04040)
  WALK_OBJECT_Y(0, 32)
  WALK_OBJECT_X(0, 48)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  WALK_OBJECT_Y(13, 42)
  WALK_OBJECT_X(13, 54)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  WALK_OBJECT_Y(14, 42)
  WALK_OBJECT_X(14, 42)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(MUSIC_ISHIZU_ISHTAR)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("It is always important to\nrelax and take a step away\n\nfrom your main mission.\n\nFor the road of destiny is\nnot a straight path.\n\nThere are many side roads\nand streets that you can\n\nwander along.\n\nThe more roads you take, the\nmore you will see of the\n\nworld, and the more you will\nlearn.\n\nHowever, Reshef is gaining\npower far faster than\n\nexpected.\n\nWe must return to the main\npath. Hurry and resurrect\n\nthe Egyptian God Cards.\n\nThe last Egyptian God Card\nremaining is The Winged\n\nDragon of Ra.\n\nIn order to restore the\nfinal Egyptian God Card\n\nfrom stone...\n\nPlease hurry and obtain the\nnext Millennium Item.\n\nThe next Millennium Item\nis.")
  DELAY(43)
  TEXT(".")
  DELAY(43)
  TEXT(".")
  DELAY(43)
  TEXT("\n\nIn a place where prehistoric\nlife forms are preserved in\n\nrock...\n\nA fossil excavation site in\nCanada.\n\n")
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  SET_FLAG(EVENT_FLAG_TALKED_TO_ISHIZU_AFTER_WATCHING_THE_KAIBAMAN_SHOW)
  SET_FLAG(EVENT_FLAG_UNLOCKED_CANADA)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BE0, map_00_state_07_08E34BE0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("The Dark Being was\nresurrected by Sol\n\nChevalsky...\n\nNo, not Sol Chevalsky, but\nPegasus.\n\nTo imprison Reshef, we need\none more Egyptian God Card.\n\nWe need the power of The\nWinged Dragon of Ra.\n\nWe must resurrect the card\nfrom stone.\n\nPlease find the Millennium\nItems to restore it.\n\nThe fifth Millennium Item is\nin Canada among fossils.\n\nYou will find it at a fossil\nexcavation site.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BC8, map_00_state_07_08E34BC8, 0x08E34BD4, 0x08E34BEC)
  CHECK_FLAG(EVENT_FLAG_TALKED_TO_ISHIZU_AFTER_WATCHING_THE_KAIBAMAN_SHOW)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E34BEC, map_00_state_07_08E34BEC, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO)
  TEXT("Please. Hurry to the fossil\nexcavation site.\n\nReshef the Dark Being will\nsoon engulf the world.\n\n")
  FALLTHROUGH()
END_EVENT_SCRIPT()
