#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_29_state_04: map 29 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08EAC984, map_29_state_04_08EAC984, 0x08EAC9A8, 0x08EAC990)
  LOAD_SPRITE(1, SPRITE_BONZ)
  LOAD_SPRITE(2, SPRITE_FORTUNE_TABLE)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Do you want your fortune told?")
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9A8, map_29_state_04_08EAC9A8, 0x08EAC9C0, 0x08EAC9B4)
  CHECK_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_PAST_LIFE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9C0, map_29_state_04_08EAC9C0, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I may not look it, but I'm an expert fortuneteller.",
      "I'll peer into your previous life, {PLAYER}."
  )
  PLAY_MUSIC(MUSIC_368)
  TEXT("Hmm... Yes, I can see it! I can feeeeeeeeeeeel it!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I can see your past very clearly!",
      "^5{BYTE_02}!",
      "That's what you were in your previous life."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  DELAY(16)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_14, OBJECT_EFFECT_JUMPING)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_14, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Hahahaha!",
      "^5{BYTE_02}?",
      "That's what {PLAYER} was in a past life?",
      "Hahahaha, I can see the similarities!"
  )
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "In the past, you played ^5{BYTE_05}...",
      "With the past incarnation of ^5{BYTE_04}.",
      "This was ^5{BYTE_03}.",
      "My fortunes are never wrong."
  )
  SET_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_PAST_LIFE)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9B4, map_29_state_04_08EAC9B4, 0x08EAC9CC, 0x08EAC9D8)
  CHECK_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_ROMANTIC_MATCH)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9CC, map_29_state_04_08EAC9CC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Fortunetelling is my specialty.",
      "I'll predict your perfect romantic match, {PLAYER}."
  )
  PLAY_MUSIC(MUSIC_368)
  TEXT("Hmm... I can see it! I can feeeeeeeeeeeel it!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Ah, I can see this person!",
      "Your partner's initials are {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}.",
      "If you want to get closer to that person...",
      "Play ^5{BYTE_0B} ^5{BYTE_0A}."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0)
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_14, OBJECT_EFFECT_JUMPING)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_14, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Whoa, whoa, whoa! Who's {BYTE_8168}^5{BYTE_06} ^5{BYTE_07}{BYTE_8168}?",
      "Wait a sec,",
      "you can't be talking about THAT person?!?"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_13)
  SET_FLAG(EVENT_FLAG_BONZ_PREDICTED_PLAYER_ROMANTIC_MATCH)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC9D8, map_29_state_04_08EAC9D8, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "I've been fortunetelling all my life.",
      "I even perfected my spooky voice!",
      "I'll look into your future, {PLAYER}."
  )
  PLAY_MUSIC(MUSIC_368)
  TEXT("Hmm... I can see it! I can feeeeeeeeeeeel it!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0 | OBJECT_13 | OBJECT_14)
  DELAY(8)
  PLAY_MUSIC(MUSIC_293)
  OBJECT_EFFECT(OBJECT_1, OBJECT_EFFECT_JUMPING)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Your future is clear!",
      "^5{BYTE_08},",
      "{PLAYER} will duel against...",
      "^5{BYTE_09} for",
      "^5{BYTE_0C}.",
      "To win, {PLAYER} must train with ^5{BYTE_0E}...",
      "The training will take place ^5{BYTE_0D}."
  )
  CLEAR_FLAG(235)
  CLEAR_FLAG(236)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC990, map_29_state_04_08EAC990, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO, "Oh... That's disappointing.")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EAC99C, map_29_state_04_08EAC99C, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_BONZ, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "My fortunetelling tells me that I can't win.",
      "So I won't duel right now.."
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
