#include "event_macros.h"
#include "overworld.h"

/* map_32_state_08: map 32 state 8 */

EVENT_SCRIPT_REPLACEMENT(0x08EB912C, map_32_state_08_08EB912C, 0x08EB9138, 0x08EB9168)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "You'll proceed no further\nwithout defeating me!\n\n")
  LANGUAGE_TEXT(1, "Vous n'irez pas plus loin\n\nsans m'avoir battu\nen duel !\n\n")
  LANGUAGE_TEXT(2, "Ihr geht keinen Schritt\nweiter, es sei denn,\n\nihr besiegt mich!\n\n")
  LANGUAGE_TEXT(3, "Non andrete oltre se\nprima non mi batterete!\n\n")
  LANGUAGE_TEXT(4, "\xa1No pasar\xe9is sin\nderrotarme!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(81)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EB9138, map_32_state_08_08EB9138, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(242)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Most impressive.\nYou deserve a card.\n\nTake this Celtic Guardian.\n\n")
  LANGUAGE_TEXT(1, "Tr\xe8s impressionnant.\nVous m\xe9ritez une carte.\n\nPrenez ce Gardien celte.\n\n")
  LANGUAGE_TEXT(2, "Sehr beeindruckend.\nIhr habt eine Karte\n\nverdient. Nehmt diesen\nkeltischen W\xe4chter.\n\n")
  LANGUAGE_TEXT(3, "Davvero notevole.\nVi meritate una carta.\n\nPrendete questo\nGuardiano Celtico.\n\n")
  LANGUAGE_TEXT(4, "\xa1Qu\xe9 b\xe1rbaro!\nMerec\xe9is una carta.\n\nTomad este Guardi\xe1n\ncelta.\n\n")
  END_LANGUAGE_TEXT()
  ADD_CARD(41)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(270)
  REACTION(1, 24577)
  DELAY(16)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Your path is clear.\nAdvance.\n\n")
  LANGUAGE_TEXT(1, "La voie est libre.\nVous pouvez avancer.\n\n")
  LANGUAGE_TEXT(2, "Euer Weg ist frei.\nIhr d\xfcrft gehen.\n\n")
  LANGUAGE_TEXT(3, "Via libera.\nAvanzate pure.\n\n")
  LANGUAGE_TEXT(4, "El camino est\xe1 despejado.\n\xa1Adelante!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(2, 2)
  SET_FLAG(156)
  FALLTHROUGH()
END_EVENT_SCRIPT()
