#include "event_macros.h"
#include "overworld.h"

/* map_27_state_01: map 27 state 1 */

EVENT_SCRIPT_REPLACEMENT(0x08EA4F1C, map_27_state_01_08EA4F1C, 0x08EA4F34, 0x08EA4F70)
  CHECK_FLAG(17)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F34, map_27_state_01_08EA4F34, 0x08EA4F40, 0x08F0404C)
  PLAY_MUSIC(402)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "To the souls guided here by\nthe Millennium Item...\n\nProve your worth by\nconquering my duel\n\nchallenge!\n\n")
  LANGUAGE_TEXT(1, "Ceux qui sont attir\xe9s par\nl'Objet du mill\xe9nium...\n\nDevront prouver\nqu'ils en sont dignes\n\nen m'affrontant\nen duel !\n\n")
  LANGUAGE_TEXT(2, "Wer vom Millenniumsgegen-\nstand angezogen wird...\n\nBew\xe4hre dich, indem du\nmeine Herausforderung\n\nzum Duell annimmst und\nmich besiegst.\n\n")
  LANGUAGE_TEXT(3, "Coloro che sono attratti\ndall'Oggetto Millenario...\n\nDevono provare di esserne\ndegni battendomi a duello!\n\n")
  LANGUAGE_TEXT(4, "Esos atra\xeddos por\nel Objeto del Milenio...\n\n\xa1Demostrad vuestra val\xeda\nderrotando mi reto\n\nde duelo!\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(0, 72)
  WALK_OBJECT_Y(0, 56)
  MOVE_OBJECT(0, 3, 0, 0)
  MOVE_OBJECT(1, 1, 0, 0)
  WALK_OBJECT_X(14, 62)
  WALK_OBJECT_Y(14, 50)
  MOVE_OBJECT(14, 3, 0, 0)
  WALK_OBJECT_X(13, 62)
  WALK_OBJECT_Y(13, 62)
  MOVE_OBJECT(13, 3, 0, 0)
  DELAY(16)
  DUEL(35)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F40, map_27_state_01_08EA4F40, 0x08EA4F4C, 0x08F04040)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "Impressive. Take this item.\n\n")
  LANGUAGE_TEXT(1, "Impressionnant.\nPrends cet objet.\n\n")
  LANGUAGE_TEXT(2, "Beeindruckend.\nNimm das hier.\n\n")
  LANGUAGE_TEXT(3, "Davvero notevole.\nPrendi questo oggetto.\n\n")
  LANGUAGE_TEXT(4, "Impresionante.\nToma este objeto.\n\n")
  END_LANGUAGE_TEXT()
  SET_FLAG(17)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F4C, map_27_state_01_08EA4F4C, 0x08EA4F58, 0x08F04040)
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(316)
  SHOW_OBJECT(3, 90, 56, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(278)
  SLIDE_OBJECT(3, 1, 14)
  DELAY(8)
  PLAY_MUSIC(279)
  SHOW_OBJECT(3, 128, 96, 0, 0, 0)
  DELAY(48)
  PLAY_MUSIC(406)
  PLAY_MUSIC(280)
  SHOW_OBJECT(2, 82, 56, 0, 1, 0)
  DELAY(16)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F58, map_27_state_01_08EA4F58, 0x08EA4F64, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, 7, 8)
  LANGUAGE_TEXT(0, "Waaah! W-what's goin' on?\n\n")
  LANGUAGE_TEXT(1, "Ouaah ! Q-qu'est-ce\nqui se passe ?\n\n")
  LANGUAGE_TEXT(2, "Waaah!\nW-was geht hier vor?\n\n")
  LANGUAGE_TEXT(3, "Uaaah!\nC-che succede?\n\n")
  LANGUAGE_TEXT(4, "\xa1Waaah!\n\xbfQ-qu\xe9 ocurre?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Sh-Shadi? But, how?\n\n")
  LANGUAGE_TEXT(1, "Sh-Shadi ? Mais,\ncomment c'est possible ?\n\n")
  LANGUAGE_TEXT(2, "Sh-Shadi?\nAber wie?\n\n")
  LANGUAGE_TEXT(3, "Sh-Shadi?\nMa come?\n\n")
  LANGUAGE_TEXT(4, "\xbfSh-Shadi?\nPero, \xbfc\xf3mo?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_SHADI, 0, 8)
  LANGUAGE_TEXT(0, "The Millennium Items retain\nthe memories of their\n\nbearers.\n\nThese memories will guide\nthe chosen duelists in\n\ntheir quest.\n\nFollow them to the salvation\nof the world.\n\n")
  LANGUAGE_TEXT(1, "Les Objets du mill\xe9nium\nconservent la m\xe9moire\n\nde ceux qui les ont\nport\xe9s.\n\nCette m\xe9moire guide les\nduellistes dans leur qu\xeate.\n\nLaissez-la vous guider pour\nr\xe9ussir \xe0 sauver le monde.\n\n")
  LANGUAGE_TEXT(2, "Millenniumsgegenst\xe4nde\nbewahren die Erinnerungen\n\nihrer Tr\xe4ger. Diese\nErinnerungen leiten\n\nDuellanten.\n\nLasst euch von ihnen zur\nRettung der Welt f\xfchren.\n\n")
  LANGUAGE_TEXT(3, "Gli Oggetti Millenari\nnon scordano i loro\n\nportatori. Quelle memorie\ncondurranno i duellanti\n\nnella loro ricerca. Lasciate\nche vi conducano a\n\nsalvare il mondo.\n\n")
  LANGUAGE_TEXT(4, "Los Objetos del Milenio\nretienen los recuerdos\n\nde sus portadores.\n\nEsos recuerdos guiar\xe1n a los\nduelistas en su b\xfasqueda.\n\nDejadles llevaros a la\nsalvaci\xf3n del mundo.\n\n")
  END_LANGUAGE_TEXT()
  HIDE_PORTRAIT()
  DELAY(16)
  HIDE_PORTRAIT()
  COMMAND_7C_ARG(2, 2)
  DELAY(32)
  PLAY_MUSIC(281)
  OBJECT_EFFECT(4, 2)
  SET_OBJECT_POSITION(2, 56, 248, 1)
  DELAY(64)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F64, map_27_state_01_08EA4F64, 0x08F04250, 0x08F04040)
  PORTRAIT(PORTRAIT_JOEY, 7, 8)
  LANGUAGE_TEXT(0, "H-he disappeared...\n\n")
  LANGUAGE_TEXT(1, "Il- il a disparu...\n\n")
  LANGUAGE_TEXT(2, "E-er ist verschwunden...\n\n")
  LANGUAGE_TEXT(3, "\xc8-\xe8 scomparso...\n\n")
  LANGUAGE_TEXT(4, "Ha... ha desaparecido...\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Was that Shadi's memory in\nthe Millennium Key?\n\n")
  LANGUAGE_TEXT(1, "C'\xe9tait la m\xe9moire de Shadi\ndans la Cl\xe9 du mill\xe9nium ?\n\n")
  LANGUAGE_TEXT(2, "War das Shadis Erinnerung\nim Millenniumsschl\xfcssel?\n\n")
  LANGUAGE_TEXT(3, "Quella era la memoria di\nShadi nella Chiave\n\nMillenaria?\n\n")
  LANGUAGE_TEXT(4, "\xbfEstaba el recuerdo de Shadi\nen la Llave del Milenio?\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_JOEY, 0, 8)
  LANGUAGE_TEXT(0, "W-well, we scored the\nMillennium Key!\n\n")
  LANGUAGE_TEXT(1, "Eh bien, de toute fa\xe7on, on\na obtenu la Cl\xe9 du\n\nmill\xe9nium.\n\n")
  LANGUAGE_TEXT(2, "A-aber jedenfalls haben wir\nden Millenniumsschl\xfcssel.\n\n")
  LANGUAGE_TEXT(3, "Be', comunque, abbiamo\nottenuto la Chiave\n\nMillenaria.\n\n")
  LANGUAGE_TEXT(4, "B-bueno, de cualquier\nmodo nos hemos\n\nhecho con la\nLlave del Milenio.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_YUGI, 0, 8)
  LANGUAGE_TEXT(0, "Yeah! Joey, {PLAYER}, we\nshould go see Ishizu.\n\n")
  LANGUAGE_TEXT(1, "Ouais. Joey, {PLAYER},\nallons voir Ishizu.\n\n")
  LANGUAGE_TEXT(2, "Ja. Joey, {PLAYER}, wir\nsollten jetzt zu Ishizu\n\ngehen.\n\n")
  LANGUAGE_TEXT(3, "Gi\xe0. Joey, {PLAYER},\ndovremmo andare da Ishizu.\n\n")
  LANGUAGE_TEXT(4, "S\xed. Joey, {PLAYER},\ndeber\xedamos ir a ver a\n\nIshizu.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F70, map_27_state_01_08EA4F70, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "Millennium Items are\nbelieved to attract each\n\nother.\n\nThe Millennium Key will lead\nyou to the next item.\n\n")
  LANGUAGE_TEXT(1, "On dit que les Objets du\nmill\xe9nium s'attirent les\n\nuns les autres. La Cl\xe9 du\nmill\xe9nium va te conduire\n\nau prochain objet.\n\n")
  LANGUAGE_TEXT(2, "Millenniumsgegenst\xe4nde\nziehen sich angeblich an.\n\nDer Millenniumsschl\xfcssel\nf\xfchrt euch zum n\xe4chsten\n\nGegenstand.\n\n")
  LANGUAGE_TEXT(3, "Si dice che gli Oggetti\nMillenari si attraggano a\n\nvicenda. La Chiave\nMillenaria ti condurr\xe0 al\n\nprossimo oggetto.\n\n")
  LANGUAGE_TEXT(4, "Se dice que los Objetos del\nMilenio se atraen entre s\xed.\n\nLa Llave del Milenio te\nllevar\xe1 al siguiente\n\nobjeto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F28, map_27_state_01_08EA4F28, 0x08EA4F34, 0x08EA4F7C)
  CHECK_FLAG(17)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA4F7C, map_27_state_01_08EA4F7C, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MILLENIUM_GUADIAN, 0, 8)
  LANGUAGE_TEXT(0, "You are only allowed to duel\nme once.\n\nDid you not have to leave\nimmediately?\n\n")
  LANGUAGE_TEXT(1, "Tu n'auras qu'une\nseule occasion\n\nde m'affronter en duel.\n\nTu ne devais pas\npartir imm\xe9diatement ?\n\n")
  LANGUAGE_TEXT(2, "Du hast nur eine Chance,\num dich mit mir zu\n\nduellieren. Das ist alles.\n\nMusst du nicht sofort\ngehen?\n\n")
  LANGUAGE_TEXT(3, "Hai una sola possibilit\xe0\ndi duellare con me,\n\nuna e basta. Non dovevi\npartire subito?\n\n")
  LANGUAGE_TEXT(4, "S\xf3lo tienes una oportunidad\nde luchar conmigo,\n\nnada m\xe1s.\n\n\xbfNo ten\xedas que marchar\nde inmediato?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
