#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_01_state_04: map 1 state 4 */

EVENT_SCRIPT_REPLACEMENT(0x08E427CC, map_01_state_04_08E427CC, EVENT_NOP, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_RED_HAT)
  LOAD_SPRITE(2, SPRITE_STYLISH_HAIR)
  LOAD_SPRITE(3, SPRITE_WEEVIL)
  TEXT(
      "You know that duelist with the weird laugh?",
      "He chased away the Neo Ghouls!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E427D8, map_01_state_04_08E427D8, EVENT_NOP, EVENT_NOP)
  TEXT(
      "That weird little kid with glasses saved us.",
      "But he's kind of arrogant and annoying, isn't he?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E427E4, map_01_state_04_08E427E4, 0x08E42808, 0x08E427F0)
  CHECK_FLAG(EVENT_FLAG_SEARCHING_FOR_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42808, map_01_state_04_08E42808, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyohyo!",
      "How could anyone lose to the Neo Ghouls?"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E427F0, map_01_state_04_08E427F0, 0x08E427FC, 0x08E42808)
  CHECK_FLAG(EVENT_FLAG_DEFEATED_SEEKER2)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E427FC, map_01_state_04_08E427FC, EVENT_NOP, EVENT_NOP)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "You want to know where the Neo Ghouls are hiding the",
      "Town of Domino?",
      "What makes you think I would know, you foolish flea!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42814, map_01_state_04_08E42814, 0x08E42820, 0x08F0404C)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_WEEVIL_HAPPY, PORTRAIT_POSITION_AUTO,
      "Hyohyohyo! You're wasting my time, you gruesome grub!",
      "You can't beat me in a duel!"
  )
  DUEL(DUELIST_WEEVIL_056)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42820, map_01_state_04_08E42820, EVENT_NOP, EVENT_NOP)
  PLAY_MUSIC(MUSIC_DOMINO_CITY_LIBERATED)
  TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_POSITION_AUTO,
      "Gyooeeeeeh!",
      "Just buzz off!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()
