#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_01_state_07: map 1 state 7 */

EVENT_SCRIPT_REPLACEMENT(0x08E42910, map_01_state_07_08E42910, 0x08E4291C, EVENT_NOP)
  LOAD_SPRITE(1, SPRITE_MAI)
  LOAD_SPRITE(2, SPRITE_ESPA)
  LOAD_SPRITE(3, SPRITE_ROBA_BROTHER_1)
  LOAD_SPRITE(4, SPRITE_ROBA_BROTHER_2)
  LOAD_SPRITE(5, SPRITE_ROBA_BROTHER_3)
  LOAD_SPRITE(6, SPRITE_TEA)
  LOAD_SPRITE(7, SPRITE_TRISTAN)
  LOAD_SPRITE(8, SPRITE_DUKE)
  LOAD_SPRITE(9, SPRITE_SERENITY)
  LOAD_SPRITE(10, SPRITE_SETO)
  LOAD_SPRITE(11, SPRITE_MOKUBA)
  LOAD_SPRITE(12, SPRITE_ISHIZU)
  LOAD_SPRITE(13, SPRITE_YUGI_WITH_MILLENNIUM_PUZZLE)
  LOAD_SPRITE(14, SPRITE_JOEY)
  PLAY_MUSIC(MUSIC_CLOCK_TOWER_SQUARE)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_UP, 8, 0)
  DELAY(16)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(32)
  WALK_OBJECT_Y(6, 56)
  WALK_OBJECT_Y(9, 56)
  WALK_OBJECT_Y(7, 64)
  WALK_OBJECT_Y(8, 64)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "What's taking them so long?")
  HIDE_PORTRAIT()
  DELAY(16)
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Mai! Everybody!")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(1, 16)
  WALK_OBJECT_Y(1, 48)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Huh?",
      "What are you doing here? Are you better duelists now?"
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "You bet, Mai! Like ultra-strong!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, DIRECTION_LEFT, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_DUKE, EXPRESSION_DUKE_TEETH_GRITTED, PORTRAIT_RIGHT, "Ultra? Tristan...")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(8, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Pipipi...",
      "And who might you be?"
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(1, 40)
  WALK_OBJECT_X(1, 28)
  MOVE_OBJECT(1, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "I saw the others over there.",
      "We've all known each other for a long time... which",
      "has both its good and bad points."
  )
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_1 | OBJECT_2 | OBJECT_3 | OBJECT_4 | OBJECT_5 | OBJECT_6 | OBJECT_7 | OBJECT_8 | OBJECT_9)
  WALK_OBJECT_X(0, 12)
  WALK_OBJECT_X(13, 12)
  WALK_OBJECT_X(14, 12)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(9, DIRECTION_LEFT, 0, 0)
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "J-Joey...")
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SAD, PORTRAIT_RIGHT, "J-Joey!")
  HIDE_PORTRAIT()
  PLAY_MUSIC(MUSIC_394)
  SLIDE_OBJECT(9, 1, 24)
  SLIDE_OBJECT(14, 1, 8)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_SWEATDROP, PORTRAIT_RIGHT, "Hey, hold on... Everyone's watching us.")
  TALK(PORTRAIT_SERENITY, EXPRESSION_SERENITY_SAD, PORTRAIT_RIGHT, "I'm so glad you're safe, big brother.")
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "{BYTE_8169}There's nothing I can do about this.{BYTE_816A}")
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, PORTRAIT_RIGHT,
      "Everyone... You waited for us?",
      "Thank you.",
      "We were able to defeat Reshef because we had your",
      "help.",
      "But the biggest credit has to be given to...",
      "You, {PLAYER}!"
  )
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Yugi's right!",
      "{PLAYER} has gotten much stronger.",
      "Almost as strong as me!"
  )
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E4291C, map_01_state_07_08E4291C, 0x08E42928, 0x08E42934)
  WALK_OBJECT_X(10, 84)
  WALK_OBJECT_X(11, 84)
  DELAY(16)
  TALK(PORTRAIT_SETO, "Hah! Big talk from a dog!")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(1, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(6, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(7, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(8, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(9, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  DELAY(16)
  WALK_OBJECT_X(9, 36)
  WALK_OBJECT_X(14, 12)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_RIGHT, "Why, you... Kaiba, what's your problem?!")
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_X(10, 28)
  SLIDE_OBJECT(8, 0, 8)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_7 | OBJECT_8)
  WALK_OBJECT_X(10, 20)
  WALK_OBJECT_Y(10, 48)
  MOVE_OBJECT(10, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(1, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(7, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(8, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(9, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_RIGHT,
      "{PLAYER}...",
      "Thank you for saving Mokuba.",
      "But you all only survived because of me.",
      "I'm the one with the KaibaCorp helicopter.",
      "That makes us even."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Kaiba...")
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Yugi, I'm done talking.")
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "What?")
  TALK(PORTRAIT_SETO, 1, PORTRAIT_RIGHT,
      "These lame duelists...",
      "I don't want to be associated with them."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_RIGHT, "You arrogant...")
  TALK(PORTRAIT_SETO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Real duelists don't need to speak.",
      "They let their cards do the talking."
  )
  PLAY_MUSIC(MUSIC_272)
  REACTION(REACTION_ELLIPSIS, OBJECT_0)
  TALK(PORTRAIT_SETO, 2, PORTRAIT_RIGHT,
      "{PLAYER}! The next time we meet, things will be",
      "different!",
      "You're a speedbump on my road to victory, and I will",
      "defeat you!"
  )
  TALK(PORTRAIT_SETO, 1, PORTRAIT_RIGHT,
      "Until then, savor the taste of victory!",
      "Come on, Mokuba."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  WALK_OBJECT_Y(10, 64)
  SLIDE_OBJECT(8, 1, 8)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_7 | OBJECT_8)
  WALK_OBJECT_Y(10, 96)
  WALK_OBJECT_Y(11, 64)
  WALK_OBJECT_X(11, 20)
  WALK_OBJECT_Y(11, 48)
  MOVE_OBJECT(11, DIRECTION_LEFT, 0, 0)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Heheh, saved!")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(11, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_MOKUBA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Wait for me, big brother!")
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_Y(11, 96)
  MOVE_OBJECT(14, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "That guy... He invented the word {BYTE_8168}annoying.{BYTE_8168}")
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Kaiba has a point, you know.",
      "We all helped create a new rival."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(6, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(7, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(8, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(9, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Mai... That's not very nice...")
  TALK(PORTRAIT_MAI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "I'm joking.",
      "We're friends, but we're also duelists. All of us.",
      "After I leave, I'll work on my deck.",
      "All right, Yugi, Joey, {PLAYER}. See you."
  )
  WALK_OBJECT_Y(1, 32)
  WALK_OBJECT_X(1, 0)
  MOVE_OBJECT(1, DIRECTION_LEFT, 16, 0)
  WALK_OBJECT_Y(2, 32)
  WALK_OBJECT_X(2, 20)
  MOVE_OBJECT(2, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(6, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(7, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(8, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(9, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_ESPA_ROBA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "You sure went through a lot.",
      "I think it's time we left too."
  )
  WALK_OBJECT_X(2, 0)
  MOVE_OBJECT(2, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_Y(3, 32)
  WALK_OBJECT_X(3, 20)
  MOVE_OBJECT(3, DIRECTION_DOWN, 0, 0)
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Good bye!")
  WALK_OBJECT_X(3, 0)
  MOVE_OBJECT(3, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_X(4, 20)
  MOVE_OBJECT(4, DIRECTION_DOWN, 0, 0)
  TEXT("See you!")
  WALK_OBJECT_X(4, 0)
  MOVE_OBJECT(4, DIRECTION_LEFT, 8, 0)
  WALK_OBJECT_X(5, 20)
  MOVE_OBJECT(5, DIRECTION_DOWN, 0, 0)
  TEXT("Bye-bye!")
  WALK_OBJECT_X(5, 0)
  MOVE_OBJECT(5, DIRECTION_LEFT, 8, 0)
  DELAY(16)
  WALK_OBJECT_Y(6, 40)
  MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_Y(9, 48)
  WALK_OBJECT_X(9, 28)
  WALK_OBJECT_X(8, 28)
  WALK_OBJECT_Y(8, 56)
  MOVE_OBJECT(8, DIRECTION_LEFT, 0, 0)
  WALK_OBJECT_X(7, 20)
  WALK_OBJECT_Y(7, 56)
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "It's over, {PLAYER}.")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "You were awesome, {PLAYER}!")
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Totally, {PLAYER}!")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Yeah, you really did great.")
  MOVE_OBJECT(0, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "I'm impressed, {PLAYER}.")
  TALK(PORTRAIT_TEA, EXPRESSION_TEA_SAD, PORTRAIT_RIGHT, "You had us all worried...")
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "I'm so glad you're safe.")
  WALK_OBJECT_X(12, 37)
  WALK_OBJECT_Y(12, 32)
  WALK_OBJECT_X(12, 20)
  MOVE_OBJECT(12, DIRECTION_DOWN, 0, 0)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, PORTRAIT_RIGHT, "Thank you for everything.")
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(6, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(7, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(8, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(9, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(13, DIRECTION_UP, 0, 0)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Reshef the Dark Being will most likely never rise",
      "again.",
      "We owe it all to you, {PLAYER}.",
      "To prevent this tragedy from reoccurring...",
      "I would like to seal the Egyptian God Cards away.",
      "May I have your Egyptian God Cards?"
  )
  TALK(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42928, map_01_state_07_08E42928, 0x08E42940, EVENT_NOP)
  WALK_OBJECT_X(0, 20)
  WALK_OBJECT_Y(0, 40)
  DELAY(16)
  PLAY_MUSIC(MUSIC_285)
  WALK_OBJECT_Y(0, 48)
  MOVE_OBJECT(0, DIRECTION_UP, 0, 0)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_HAPPY, PORTRAIT_RIGHT,
      "Thank you...",
      "Reshef was vanquished before it could engulf the world.",
      "{PLAYER}, you stopped it.",
      "Thank you, and farewell."
  )
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, PORTRAIT_LEFT)
  HIDE_PORTRAIT()
  DELAY(32)
  WALK_OBJECT_X(12, 0)
  SHOW_OBJECT(12, 128, 96, 0, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42940, map_01_state_07_08E42940, EVENT_NOP, EVENT_NOP)
  DELAY(64)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_RIGHT, "Whew... That really was something, wasn't it?")
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(0, DIRECTION_DOWN, 0, 0)
  MOVE_OBJECT(6, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(7, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(8, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(9, DIRECTION_LEFT, 0, 0)
  MOVE_OBJECT(13, DIRECTION_DOWN, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, PORTRAIT_RIGHT,
      "You're right.",
      "Even the spirit was nervous.",
      "{PLAYER}, you were great."
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "What about me? I wasn't too shabby myself!")
  HIDE_PORTRAIT()
  DELAY(16)
  PLAY_MUSIC(MUSIC_274)
  REACTION(REACTION_SWEATDROP, OBJECT_0 | OBJECT_6 | OBJECT_7 | OBJECT_8 | OBJECT_9 | OBJECT_13)
  DELAY(16)
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Yeah, I'm sure you did alright.")
  MOVE_OBJECT(14, DIRECTION_RIGHT, 0, 0)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Tristan! Yeah, you got that right!",
      "I knew you'd understand, partna!"
  )
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "You bet I do!",
      "You did your best to help Yugi and {PLAYER}...",
      "By staying out of their way!"
  )
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Right, I tried not to cause any trouble and...")
  HIDE_PORTRAIT()
  DELAY(8)
  PLAY_MUSIC(MUSIC_271)
  REACTION(REACTION_EXCLAMATION_MARK, OBJECT_14)
  PLAY_MUSIC(MUSIC_275)
  REACTION(REACTION_ANGRY, OBJECT_14)
  DELAY(8)
  TALK(PORTRAIT_JOEY, EXPRESSION_JOEY_TEETH_GRITTED, PORTRAIT_RIGHT, "Wait! Why would I have to stay out of their way?!")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_TRISTAN_HAPPY, PORTRAIT_RIGHT,
      "Hahaha, sorry, sorry.",
      "Chill out, dude."
  )
  HIDE_PORTRAIT()
  DELAY(16)
  MOVE_OBJECT(14, DIRECTION_UP, 0, 0)
  DELAY(16)
  TALK(PORTRAIT_JOEY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
      "Looks like everything's back to normal. Back to the",
      "usual Town of Domino."
  )
  TALK(PORTRAIT_YUGI, EXPRESSION_YUGI_HAPPY, PORTRAIT_RIGHT, "Yeah...")
  TALK(PORTRAIT_DUKE, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Welcome back.")
  TALK(PORTRAIT_TRISTAN, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "I'm amazed you came back.")
  TALK(PORTRAIT_SERENITY, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Welcome home.")
  TALK(PORTRAIT_TEA, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT, "Welcome home, everyone!")
  HIDE_PORTRAIT()
  DELAY(16)
  FADE_MUSIC(8)
  FADE_SCREEN(8)
  WARP(LOCATION_PEGASUS_CASTLE_HALLWAY, 10, 0, 0)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08E42934, map_01_state_07_08E42934, 0x08E42928, 0x08E42934)
  TALK(PORTRAIT_ISHIZU, EXPRESSION_ISHIZU_SURPRISED, PORTRAIT_RIGHT,
      "Do you want to become just like Pegasus?",
      "The Egyptian God Cards must be hidden from the world.",
      "Please, may I have the Egyptian God Cards?"
  )
  TALK(PORTRAIT_NONE, "{CARD_1}Yes\nNo{CARD_2}")
  FALLTHROUGH()
END_EVENT_SCRIPT()
