#include "event_macros.h"
#include "overworld.h"
#include "constants/music_ids.h"

/* map_02_state_07: map 2 state 7 */

LOAD_SPRITE(1, SPRITE_MAKO)
LOAD_SPRITE(2, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(3, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(4, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(5, SPRITE_MONKEY_ROBOT)
LOAD_SPRITE(6, SPRITE_WEEVIL)
DELAY(16)
WALK_OBJECT_Y(SPRITE_MAKO, 40)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 0, 0)
DELAY(16)
WALK_OBJECT_Y(2, 48)
WALK_OBJECT_Y(3, 48)
WALK_OBJECT_Y(4, 56)
WALK_OBJECT_Y(5, 56)
DELAY(16)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_DOWN, 0, 0)
DELAY(16)
TALK(PORTRAIT_MAKO, EXPRESSION_MAKO_HAPPY, PORTRAIT_RIGHT,
    "Gahaha!\n\n"
    "All duelists swim in the\n"
    "same ocean!\n\n"
    "Hurry home!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_2, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukkikki!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_3, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_326)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_LEFT,
    "Ukikkiki, kikiiki!!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_4, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Ukikiiikiki!\n\n"
)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_2 | OBJECT_5, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_3 | OBJECT_4, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_2 | OBJECT_5, OBJECT_EFFECT_JUMPING)
PLAY_MUSIC(MUSIC_293)
OBJECT_EFFECT(OBJECT_3 | OBJECT_4, OBJECT_EFFECT_JUMPING)
WALK_OBJECT_X(SPRITE_WEEVIL, 24)
DELAY(32)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_UP, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_DOWN, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_LEFT, 0, 0)
DELAY(16)
MOVE_OBJECT(SPRITE_WEEVIL, DIRECTION_RIGHT, 0, 0)
DELAY(16)
TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "I'm here to check on my card\n"
    "I gave away.\n\n"
    "So? Where are they?\n\n"
)
HIDE_PORTRAIT()
DELAY(16)
MOVE_OBJECT(SPRITE_MAKO, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(2, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(3, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(4, DIRECTION_LEFT, 0, 0)
MOVE_OBJECT(5, DIRECTION_LEFT, 0, 0)
DELAY(16)
PLAY_MUSIC(MUSIC_323)
TALK(PORTRAIT_ROBOT_MOkNEY, 0, PORTRAIT_RIGHT,
    "Uki?\n\n"
)
TALK(PORTRAIT_MAKO, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "Are you worried about those\n"
    "guys?\n\n"
)
TALK(PORTRAIT_WEEVIL, EXPRESSION_NEUTRAL, PORTRAIT_RIGHT,
    "I'm only worried about my\n"
    "card!\n\n"
)
FADE_SCREEN(8)
WARP(LOCATION_CLOCK_TOWER_SQUARE_SOUTH, 7, 0, 0)
