#include "event_macros.h"
#include "overworld.h"

/* map_26_state_09: map 26 state 9 */

EVENT_SCRIPT_REPLACEMENT(0x08EA3D88, map_26_state_09_08EA3D88, 0x08EA3D94, 0x08EA3DA0)
  CHECK_FLAG(137)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3D94, map_26_state_09_08EA3D94, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}... You came here\nfor a reason, didn't you?\n\nWhatever it is, I'm here to\nhelp.\n\nChallenge me whenever you\nfeel ready.\n\nAs duelists, we understand\neach other the best when we\n\nduel.\n\nIt sounds weird, but it's\ntrue.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}... Tu es venu\nici pour quelque chose,\n\nn'est-ce pas ?\n\nEh bien, je suis l\xe0\npour t'aider.\n\nLance-moi un d\xe9fi\nd\xe8s que tu sera pr\xeat\n\nd'un point de vue\n\xe9motionnel.\n\nNous sommes des duellistes.\n\nNous ne pouvons nous\ntoucher qu'en duel.\n\nCela limite les choses,\nmais c'est ainsi.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}... Du bist doch\naus einem Grund hier, oder?\n\nWas er auch sein mag, ich\nm\xf6chte dir helfen.\n\nFordere mich zum Duell, wenn\ndu dich dazu bereit f\xfchlst.\n\nWir sind Duellanten.\n\nWir k\xf6nnen nur \xfcber Duelle\nKontakt haben.\n\nEs ist nicht viel, aber\ndaran k\xf6nnen wir nichts\n\n\xe4ndern.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}... Sei venuto\nqui per un motivo, vero?\n\nQualunque esso sia,\nsono qui per aiutarti.\n\nSfidami pure quando\nti senti pronto.\n\nSiamo duellanti.\n\nPossiamo parlare e scambiare\ncarte solo con i duelli.\n\nQuesto ci limita, ma\nnon si pu\xf2 evitare.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}... Viniste\npor un motivo, \xbfno?\n\nSea lo que fuere, estoy\naqu\xed para ayudar.\n\nR\xe9tame siempre que est\xe9s\npreparado emocionalmente.\n\nSomos duelistas.\n\nSolamente nos podemos tocar\nen nuestros duelos.\n\nEs limitador, pero no hay\nnada que hacer al respecto.\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DA0, map_26_state_09_08EA3DA0, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "The people in the Town of\nDomino are happy now that\n\nthe Neo Ghouls are gone.\n\nBut don't you sense\nsomething strange?\n\nI don't know what it is, but\nit doesn't feel good.\n\nIt feels like the last turn\nof a duel that I'm about to\n\nlose.\n\nIt's just awful!\n\n{PLAYER}, this enemy that\nyou're facing...\n\nWho is it?\n\nWho can create so much\ntension in the air?\n\n")
  LANGUAGE_TEXT(1, "Les habitants de\nDomino sont heureux\n\nque les Neo Ghouls\nsoient partis.\n\nMais est-ce que tu\nressens quelque chose ?\n\nC'est bizarre, mais j'ai\nun horrible pressentiment.\n\nComme si, avant un\nmatch, tu savais que\n\ntu allais perdre.\n\nC'est un peu la m\xeame\nsensation horrible.\n\n{PLAYER}, cet ennemi\nque tu vas affronter...\n\nC'est qui, au juste ?\nQuel \xeatre peut bien\n\navoir une pr\xe9sence\naussi terrifiante ?\n\n")
  LANGUAGE_TEXT(2, "Die Menschen in Domino sind\nsind froh, dass die Neo\n\nGhouls verschwunden sind.\nAber sp\xfcrst du auch etwas?\n\nIch wei\xdf nicht, was es ist,\naber mir l\xe4uft ein Schauer\n\n\xfcber den R\xfccken. Es ist\nwie der letzte Zug in\n\neinem Spiel, bei dem du\nwei\xdft, dass du verlierst.\n\nSo ein furchtbares Gef\xfchl\nist es.\n\n{PLAYER}, dein Gegner...\n\nWas ist er?\n\nWelches Wesen besitzt eine\nso schwere Pr\xe4senz?\n\n")
  LANGUAGE_TEXT(3, "La gente di Domino \xe8\nfelice che i Neo Ghouls\n\nse ne siano andati. Ma\ntu non senti qualcosa?\n\nNon so cosa sia, ma ho\nuna terribile sensazione.\n\n\xc8 come l'ultimo round di\nuna partita che gi\xe0 sai di\n\nperdere. \xc8 una sensazione\ndel genere, tremenda.\n\n{PLAYER}, il nemico\nche dovrai affrontare...\n\nChe cos'\xe8 di preciso?\nChe tipo di essere ha\n\nquesta presenza che\nsembra incombere?\n\n")
  LANGUAGE_TEXT(4, "Las gentes de Domino est\xe1n\ncontentas porque se han ido\n\nlos Neo Ghouls.\nPero, \xbfno sientes algo?\n\nNo s\xe9 qu\xe9 es, pero tengo un\npresentimiento espantoso.\n\nEs como el \xfaltimo turno en\nun combate que sabes que\n\nvas a perder.\n\nEs ese tipo de pre-\nsentimiento horrible.\n\n{PLAYER}, el enemigo al que\nte vas a enfrentar...\n\n\xbfQu\xe9 es?\n\n\xbfQu\xe9 tipo de ser tiene una\npresencia tan fuerte?\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DAC, map_26_state_09_08EA3DAC, 0x08EA3DB8, 0x08EA3DD0)
  CHECK_FLAG(137)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DB8, map_26_state_09_08EA3DB8, 0x08EA3DC4, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Duelists get to know each\nother through dueling.\n\nOnce duelists battle, a bond\ndevelops that didn't exist\n\nbefore.\n\n{PLAYER}, I accept your\nduel!\n\n")
  LANGUAGE_TEXT(1, "Nous, les duellistes,\nnous nous comprenons\n\nles uns les autres.\n\nDans la bataille, des\nliens se d\xe9veloppent.\n\n{PLAYER}, j'accepte\nde relever ton d\xe9fi !\n\n")
  LANGUAGE_TEXT(2, "Wir Duellanten, wir lernen,\neinander zu sp\xfcren.\n\nWir lernen einander durch\nunsere Duelle zu verstehen.\n\nIm Kampf bauen Duellanten\neine Beziehung auf.\n\n{PLAYER}, ich nehme deine\nHerausforderung an!\n\n")
  LANGUAGE_TEXT(3, "Noi duellanti possiamo\nentrare in sintonia.\n\nDuellando, ci capiamo\nsempre di pi\xf9. Quando i\n\nduellanti si affrontano,\nnasce un legame.\n\n{PLAYER}, accetto\nla tua sfida!\n\n")
  LANGUAGE_TEXT(4, "Nosotros los duelistas,\npodemos sentir por el otro.\n\nPor medio de los duelos\nllegamos a entendernos\n\nentre nosotros.\n\nUna vez que los duelistas\nluchan, se crea un v\xednculo.\n\n\xa1{PLAYER}, acepto\ntu reto!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(97)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DC4, map_26_state_09_08EA3DC4, 0x08F04040, 0x08F04040)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}...\n\nI can tell you're planning\nto face something huge and\n\nterrible...\n\nBut you'll be fine.\n\nThere's a bond between us!\n\nEven when we're far apart,\nour hearts beat as one.\n\nThis is Harpie Lady. It\nrepresents my spirit as a\n\nduelist.\n\nI'm not required to give it\nto you, but I want you to\n\nhave it.\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}...\n\nTu as une t\xe2che\nbien difficile...\n\nJe le sais.\n\nMais tu t'en sortiras.\n\nEn tant que duellistes,\nnous nous comprenons.\n\nNous sommes distincts\nmais nos c\u0153urs\n\nbattent \xe0 l'unisson.\n\nVoici une Harpie {BYTE_8146} elle\nrepr\xe9sente mon esprit.\n\nCe n'est pas une Carte Ante.\n\nJe veux que tu la prennes.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}...\n\nDu versuchst da, es mit\netwas Gigantischem\n\naufzunehmen. Ich sp\xfcre es.\nAber sei unbesorgt.\n\nUnser Geist als Duellanten\nhat sich vereint! Auch wenn\n\nwir getrennt sind, schlagen\nunsere Herzen wie eins.\n\nDies ist die Fl\xfcgel-Lady.\n\nSie repr\xe4sentiert meinen\nGeist.\n\nEs ist keine Ante-Karte.\n\nNimm sie mit.\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}...\n\nStai tentando di affrontare\nqualcosa di grande...\n\nLo sento.\n\nMa ti andr\xe0 bene.\n\nI nostri spiriti di\nduellanti sono uniti!\n\nAnche se siamo lontani, i\nnostri cuori battono\n\nall'unisono. Ecco Arpia\nSpendente. Rappresenta\n\nil mio spirito.\nNon \xe8 un'Ante-carta.\n\nVoglio che la porti con te.\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}...\n\nIntentas hacer frente\na algo brutal...\n\nLo s\xe9.\n\nPero estar\xe1s bien.\n\n\xa1Nuestros esp\xedritus,\ncomo duelistas que\n\nsomos, est\xe1n\nunidos!\n\nPuede que estemos\nseparados, pero\n\nnuestros corazones\nlaten como uno s\xf3lo.\n\nEsta es la Harpie Lady.\nRepresenta mi esp\xedritu.\n\nNo es una Carta Ante.\n\nQuiero que la lleves\ncontigo.\n\n")
  END_LANGUAGE_TEXT()
  PORTRAIT(PORTRAIT_NONE, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Received Harpie Lady.")
  LANGUAGE_TEXT(1, "Re\xe7u une Harpie.")
  LANGUAGE_TEXT(2, "Fl\xfcgel-Lady erhalten.")
  LANGUAGE_TEXT(3, "Ricevuta un'Arpia\nSplendente.")
  LANGUAGE_TEXT(4, "Recibido una Harpie Lady.")
  END_LANGUAGE_TEXT()
  PLAY_MUSIC(701)
  DELAY(240)
  DELAY(80)
  PLAY_MUSIC(15)
  PAGE_BREAK()
  ADD_CARD(62)
  SET_FLAG(137)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DD0, map_26_state_09_08EA3DD0, 0x08EA3DDC, 0x08F0404C)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "{PLAYER}, I don't know what\nyou're facing.\n\nBut I know it won't be easy.\n\nRemember that every duelist\nhas unlimited potential.\n\nIf you think it'll help,\nI'll duel you anytime!\n\n")
  LANGUAGE_TEXT(1, "{PLAYER}, je ne sais\npas \xe0 quoi tu fais face.\n\nMais je sais que \xe7a\nne va pas \xeatre facile.\n\nLes duellistes ont des\ncapacit\xe9s infinies.\n\nAlors, si cela peut t'aider,\nje t'affronterai en duel\n\nd\xe8s que tu le voudras.\n\n")
  LANGUAGE_TEXT(2, "{PLAYER}, ich wei\xdf nicht,\nwas dir bevorsteht.\n\nAber ich sehe, du erkennst,\ndass es kein Kinderspiel\n\nwird. Denk nur daran, dass\nDuellanten ein unendliches\n\nPotenzial besitzen. Wenn\nich dir helfen kann, trete\n\nich jederzeit gerne gegen\ndich an!\n\n")
  LANGUAGE_TEXT(3, "{PLAYER}, non so\ncosa ti aspetti.\n\nMa intuisco che sai\nche non sar\xe0 facile.\n\nRicordati per\xf2 che i\nduellanti hanno\n\npotenzialit\xe0 infinite.\nSe ti pu\xf2 aiutare,\n\nduella pure con me\nquando vuoi!\n\n")
  LANGUAGE_TEXT(4, "{PLAYER}, no s\xe9\na qu\xe9 te enfrentas.\n\nPero s\xe9 que sabes\nque no ser\xe1 f\xe1cil.\n\nPero recuerda que\nlos duelistas tienen\n\nun potencial infinito.\n\nSi puedo ser de\nayuda, \xa1luchar\xe9\n\ncontigo cuando sea!\n\n")
  END_LANGUAGE_TEXT()
  DUEL(147)
  FALLTHROUGH()
END_EVENT_SCRIPT()

EVENT_SCRIPT_REPLACEMENT(0x08EA3DDC, map_26_state_09_08EA3DDC, 0x08F04040, 0x08F04040)
  PLAY_MUSIC(15)
  PORTRAIT(PORTRAIT_MAI, EXPRESSION_NEUTRAL, 8)
  LANGUAGE_TEXT(0, "Did this duel help you?\n\nDon't lose, {PLAYER}!\n\n")
  LANGUAGE_TEXT(1, "Cela ne t'a pas \xe9t\xe9 utile ?\n\nNe perds pas, {PLAYER} !\n\n")
  LANGUAGE_TEXT(2, "War ich wenigstens ein\nwenig n\xfctzlich?\n\nVerlier nicht, {PLAYER}!\n\n")
  LANGUAGE_TEXT(3, "Ti sono stata utile,\nalmeno un po'?\n\nNon perdere, {PLAYER}!\n\n")
  LANGUAGE_TEXT(4, "\xbfTe he servido de algo,\naunque sea un poco?\n\n\xa1No pierdas, {PLAYER}!\n\n")
  END_LANGUAGE_TEXT()
  FALLTHROUGH()
END_EVENT_SCRIPT()
