#include "global.h"
#include "configs/runtime.h"
#include "constants/card_ids.h"
#include "constants/music_ids.h"
#include "debug_deck_swap.h"
#include "debug_menu_internal.h"

const u16 sDirectDamage_Deck[] APPEND_RODATA = {
    LEOGUN, LEOGUN, LEOGUN, LEOGUN, LEOGUN, LEOGUN, LEOGUN, LEOGUN,
    UMI, UMI, UMI, UMI, UMI, UMI, UMI, UMI,
    THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY,
    THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY, THE_INEXPERIENCED_SPY,
    MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN,
    BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON,
    BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_WHITE_DRAGON,
};

const u16 sRAPhoenixMode_Deck[] APPEND_RODATA = {
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
    THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE, THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE,
};

const u16 sEmptyExtraDeck[] APPEND_RODATA = {
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sGladiatorBeasts_Deck[] APPEND_RODATA = {
    COLOSSEUM_CAGE_OF_THE_GLADIATOR_BEASTS, FLAVIAN_COLOSSEUM_OF_THE_GLADIATOR_BEASTS, GLADIATOR_BEAST_ALEXANDER, GLADIATOR_BEAST_ANDAL,
    GLADIATOR_BEAST_ATTORIX, GLADIATOR_BEAST_AUGUSTUS, GLADIATOR_BEAST_BATTLE_HALBERD, GLADIATOR_BEAST_BESTIARI,
    GLADIATOR_BEAST_DARIUS, GLADIATOR_BEAST_DIMACARI, GLADIATOR_BEAST_EQUESTE, GLADIATOR_BEAST_GISTEL,
    GLADIATOR_BEAST_HOPLOMUS, GLADIATOR_BEAST_LANISTA, GLADIATOR_BEAST_LAQUARI, GLADIATOR_BEAST_MURMILLO,
    GLADIATOR_BEAST_NOXIOUS, GLADIATOR_BEAST_OCTAVIUS, GLADIATOR_BEAST_RETIARI, GLADIATOR_BEAST_SAGITTARII,
    GLADIATOR_BEAST_SAMNITE, GLADIATOR_BEAST_SECUTOR, GLADIATOR_BEAST_SPARTACUS, GLADIATOR_BEAST_TORAX,
    GLADIATOR_BEAST_TYGERIUS, GLADIATOR_BEAST_VESPASIUS, GLADIATOR_BEAST_WAR_CHARIOT, GLADIATOR_BEASTS_BATTLE_ARCHFIEND_SHIELD,
    GLADIATOR_BEASTS_BATTLE_GLADIUS, GLADIATOR_BEASTS_BATTLE_MANICA, GLADIATOR_BEASTS_MEDUSA_SHIELD, GLADIATOR_BEASTS_VALOR,
    GLADIATOR_NAUMACHIA, TROJAN_GLADIATOR_BEAST, GLADIATOR_PROVING_GROUND, COLOSSEUM_CAGE_OF_THE_GLADIATOR_BEASTS,
    FLAVIAN_COLOSSEUM_OF_THE_GLADIATOR_BEASTS, GLADIATOR_BEAST_ALEXANDER, GLADIATOR_BEAST_ANDAL, GLADIATOR_BEAST_ATTORIX,
};

const u16 sGladiatorBeasts_Extra[] APPEND_RODATA = {
    GLADIATOR_BEAST_ANDABATA, GLADIATOR_BEAST_CLAUDIUS, GLADIATOR_BEAST_DAREIOS, GLADIATOR_BEAST_DOMITIANUS,
    GLADIATOR_BEAST_DRAGASES, GLADIATOR_BEAST_ESSEDARII, GLADIATOR_BEAST_GAIODIAZ, GLADIATOR_BEAST_GYZARUS,
    GLADIATOR_BEAST_HERAKLINOS, GLADIATOR_BEAST_NEROKIUS, GLADIATOR_BEAST_TAMER_EDITOR, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sBlueEyes_Deck[] APPEND_RODATA = {
    BLUE_EYES_WHITE_DRAGON, BLUE_EYES_TOON_DRAGON, BLUE_EYES_SHINING_DRAGON, PALADIN_OF_WHITE_DRAGON,
    BLUE_EYES_CHAOS_MAX_DRAGON, KAIBAMAN, BLUE_EYES_ALTERNATIVE_WHITE_DRAGON, BLUE_EYES_CHAOS_DRAGON,
    TRADE_IN, BLUE_EYES_JET_DRAGON, BLUE_EYES_SOLID_DRAGON, DRAGON_SPIRIT_OF_WHITE,
    RETURN_OF_THE_DRAGON_LORDS, SILVERS_CRY, THE_MELODY_OF_AWAKENING_DRAGON, THE_WHITE_STONE_OF_ANCIENTS,
    THE_WHITE_STONE_OF_LEGEND, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_TOON_DRAGON, BLUE_EYES_SHINING_DRAGON,
    PALADIN_OF_WHITE_DRAGON, BLUE_EYES_CHAOS_MAX_DRAGON, KAIBAMAN, BLUE_EYES_ALTERNATIVE_WHITE_DRAGON,
    BLUE_EYES_CHAOS_DRAGON, TRADE_IN, BLUE_EYES_JET_DRAGON, BLUE_EYES_SOLID_DRAGON,
    DRAGON_SPIRIT_OF_WHITE, RETURN_OF_THE_DRAGON_LORDS, SILVERS_CRY, THE_MELODY_OF_AWAKENING_DRAGON,
    THE_WHITE_STONE_OF_ANCIENTS, THE_WHITE_STONE_OF_LEGEND, BLUE_EYES_WHITE_DRAGON, BLUE_EYES_TOON_DRAGON,
    BLUE_EYES_SHINING_DRAGON, PALADIN_OF_WHITE_DRAGON, BLUE_EYES_CHAOS_MAX_DRAGON, KAIBAMAN,
};

const u16 sBlueEyes_Extra[] APPEND_RODATA = {
    BLUE_EYES_ULTIMATE_DRAGON, BLUE_EYES_ALTERNATIVE_ULTIMATE_DRAGON, NEO_BLUE_EYES_ULTIMATE_DRAGON, BLUE_EYES_TYRANT_DRAGON,
    BLUE_EYES_ULTIMATE_SPIRIT_DRAGON, BLUE_EYES_SPIRIT_DRAGON, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sAmazoness_Deck[] APPEND_RODATA = {
    AMAZONESS_TIGER, AMAZONESS_ARCHER, AMAZONESS_BABY_TIGER, AMAZONESS_PRINCESS,
    AMAZONESS_QUEEN, AMAZONESS_SAGE, AMAZONESS_SCOUTS, AMAZONESS_CALL,
    AMAZONESS_FIGHTING_SPIRIT, AMAZONESS_HEIRLOOM, AMAZONESS_SECRET_ARTS, AMAZONESS_HALL,
    AMAZONESS_HOT_SPRING, AMAZONESS_ONSLAUGHT, AMAZONESS_SHAMANISM, AMAZONESS_SPELLCASTER,
    AMAZONESS_VILLAGE, AMAZONESS_WILLPOWER, AMAZONESS_SPIRITUALIST, AMAZONESS_SPY,
    AMAZONESS_TRAINEE, AMAZONESS_WAR_CHIEF, AMAZONESS_TIGER, AMAZONESS_ARCHER,
    AMAZONESS_BABY_TIGER, AMAZONESS_PRINCESS, AMAZONESS_QUEEN, AMAZONESS_SAGE,
    AMAZONESS_SCOUTS, AMAZONESS_CALL, AMAZONESS_FIGHTING_SPIRIT, AMAZONESS_HEIRLOOM,
    AMAZONESS_SECRET_ARTS, AMAZONESS_HALL, AMAZONESS_HOT_SPRING, AMAZONESS_ONSLAUGHT,
    AMAZONESS_SHAMANISM, AMAZONESS_SPELLCASTER, AMAZONESS_VILLAGE, AMAZONESS_WILLPOWER,
};

const u16 sAmazoness_Extra[] APPEND_RODATA = {
    AMAZONESS_AUGUSTA, AMAZONESS_EMPRESS, AMAZONESS_PET_LIGER, AMAZONESS_PET_LIGER_KING,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sLightsworn_Deck[] APPEND_RODATA = {
    JUDGMENT_DRAGON, AURKUS_LIGHTSWORN_DRUID, CELESTIA_LIGHTSWORN_ANGEL, CHARGE_OF_THE_LIGHT_BRIGADE,
    EHREN_LIGHTSWORN_MONK, FELIS_LIGHTSWORN_ARCHER, GARONITH_LIGHTSWORN_DRAGON, GAROTH_LIGHTSWORN_WARRIOR,
    JAIN_LIGHTSWORN_PALADIN, JAIN_TWILIGHTSWORN_GENERAL, JENIS_LIGHTSWORN_MENDER, LIGHT_OF_DESTRUCTION,
    LIGHTSWORN_AEGIS, LIGHTSWORN_BARRIER, LIGHTSWORN_DRAGONLING, LIGHTSWORN_JUDGEMENT,
    LIGHTSWORN_SABRE, LIGHTSWORN_SANCTUARY, LUMINA_LIGHTSWORN_SUMMONER, LUMINA_TWILIGHTSWORN_SHAMAN,
    LYLA_LIGHTSWORN_SORCERESS, LYLA_TWILIGHTSWORN_ENCHANTRESS, MINERVA_LIGHTSWORN_MAIDEN, RAIDEN_HAND_OF_THE_LIGHTSWORN,
    REALM_OF_LIGHT, RINYAN_LIGHTSWORN_ROGUE, RYKO_LIGHTSWORN_HUNTER, RYKO_TWILIGHTSWORN_FIGHTER,
    SHIRE_LIGHTSWORN_SPIRIT, SOLAR_RECHARGE, WEISS_LIGHTSWORN_ARCHFIEND, WULF_LIGHTSWORN_BEAST,
    JUDGMENT_DRAGON, AURKUS_LIGHTSWORN_DRUID, CELESTIA_LIGHTSWORN_ANGEL, CHARGE_OF_THE_LIGHT_BRIGADE,
    EHREN_LIGHTSWORN_MONK, FELIS_LIGHTSWORN_ARCHER, GARONITH_LIGHTSWORN_DRAGON, GAROTH_LIGHTSWORN_WARRIOR,
};

const u16 sLightsworn_Extra[] APPEND_RODATA = {
    CURIOUS_THE_LIGHTSWORN_DOMINION, MICHAEL_THE_ARCH_LIGHTSWORN, MINERVA_THE_ATHENIAN_LIGHTSWORN, MINERVA_THE_EXHALTED_LIGHTSWORN,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sDeepSea_Deck[] APPEND_RODATA = {
    DEEPSEA_SHARK, DEEPSEA_WARRIOR, A_LEGENDARY_OCEAN, WARRIOR_OF_ATLANTIS,
    ATLANTEAN_ATTACK_SQUAD, ATLANTEAN_DRAGOONS, ATLANTEAN_HEAVY_INFANTRY, ATLANTEAN_MARKSMAN,
    DEEP_SEA_DIVA, LEMURIA_THE_FORGOTTEN_CITY, POSEIDRA_THE_ATLANTEAN_DRAGON, DEEPSEA_SHARK,
    DEEPSEA_WARRIOR, A_LEGENDARY_OCEAN, WARRIOR_OF_ATLANTIS, ATLANTEAN_ATTACK_SQUAD,
    ATLANTEAN_DRAGOONS, ATLANTEAN_HEAVY_INFANTRY, ATLANTEAN_MARKSMAN, DEEP_SEA_DIVA,
    LEMURIA_THE_FORGOTTEN_CITY, POSEIDRA_THE_ATLANTEAN_DRAGON, DEEPSEA_SHARK, DEEPSEA_WARRIOR,
    A_LEGENDARY_OCEAN, WARRIOR_OF_ATLANTIS, ATLANTEAN_ATTACK_SQUAD, ATLANTEAN_DRAGOONS,
    ATLANTEAN_HEAVY_INFANTRY, ATLANTEAN_MARKSMAN, DEEP_SEA_DIVA, LEMURIA_THE_FORGOTTEN_CITY,
    POSEIDRA_THE_ATLANTEAN_DRAGON, DEEPSEA_SHARK, DEEPSEA_WARRIOR, A_LEGENDARY_OCEAN,
    WARRIOR_OF_ATLANTIS, ATLANTEAN_ATTACK_SQUAD, ATLANTEAN_DRAGOONS, ATLANTEAN_HEAVY_INFANTRY,
};

const u16 sDeepSea_Extra[] APPEND_RODATA = {
    CORAL_DRAGON, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sDarkMagician_Deck[] APPEND_RODATA = {
    DARK_MAGICIAN, DARK_MAGICIAN_KNIGHT, MAGICIAN_OF_BLACK_CHAOS, DARK_MAGIC_RITUAL,
    DARK_MAGICIAN_GIRL, MAGICIANS_VALKYRIA, DARK_MAGIC_CURTAIN, MAGIC_CYLINDER,
    THOUSAND_KNIVES, DARK_MAGICIAN_OF_CHAOS, DEDICATION_THROUGH_LIGHT_AND_DARKNESS, APPRENTICE_ILLUSION_MAGICIAN,
    CHAOS_FORM, SKILLED_DARK_MAGICIAN, THE_EYE_OF_TIMAEUS, BOND_BETWEEN_TEACHER_AND_STUDENT,
    DARK_MAGIC_ATTACK, DARK_MAGIC_INHERITANCE, DARK_MAGIC_VEIL, ETERNAL_SOUL,
    ILLUSION_MAGIC, ILLUSION_OF_CHAOS, MAGICIAN_NAVIGATION, MAGICIAN_OF_DARK_ILLUSION,
    MAGICIANS_COMBINATION, MAGICIANS_ROBE, MAGICIANS_ROD, MAGICIANS_SOULS,
    SECRETS_OF_DARK_MAGIC, SOUL_SERVANT, THE_GAZE_OF_TIMAEUS, DARK_MAGICIAN_GIRL_THE_MAGICIANS_APPRENTICE,
    DARK_MAGICIAN_CIRCLE, DARK_MAGICIAN_THE_MAGICIAN_OF_BLACK_CHAOS, MAGICIANS_CIRCLE, MAGICIANS_LEFT_HAND,
    MAGICIANS_RIGHT_HAND, DARK_MAGICIAN, DARK_MAGICIAN_KNIGHT, MAGICIAN_OF_BLACK_CHAOS,
};

const u16 sDarkMagician_Extra[] APPEND_RODATA = {
    DARK_MAGICIAN_GIRL_THE_DRAGON_KNIGHT, DARK_MAGICIAN_THE_DRAGON_KNIGHT, DARK_MAGICIAN_OF_DESTRUCTION, EBON_ILLUSION_MAGICIAN,
    THE_DARK_MAGICIANS, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sGravekeepers_Deck[] APPEND_RODATA = {
    GRAVEKEEPERS_SERVANT, NECROVALLEY, GRAVEKEEPERS_AMBUSHER, GRAVEKEEPERS_CANNONHOLDER,
    GRAVEKEEPERS_CHIEF, GRAVEKEEPERS_COMMANDANT, GRAVEKEEPERS_CURSE, GRAVEKEEPERS_DESCENDANT,
    GRAVEKEEPERS_GUARD, GRAVEKEEPERS_HEADMAN, GRAVEKEEPERS_HERATIC, GRAVEKEEPERS_INSCRIPTION,
    GRAVEKEEPERS_NOBLEMAN, GRAVEKEEPERS_ORACLE, GRAVEKEEPERS_PRIESTESS, GRAVEKEEPERS_RECRUITER,
    GRAVEKEEPERS_SHAMAN, GRAVEKEEPERS_SPEAR_SOLDIER, GRAVEKEEPERS_SPIRITUALIST, GRAVEKEEPERS_SPY,
    GRAVEKEEPERS_STELE, GRAVEKEEPERS_TRAP, GRAVEKEEPERS_VASSAL, IMPERIAL_TOMBS_OF_NECROVALLEY,
    HIDDEN_TEMPLES_OF_NECROVALLEY, GRAVEKEEPERS_VISIONARY, GRAVEKEEPERS_WATCHER, NECROVALLEY_THRONE,
    NECROVALLEY_TEMPLE, RITE_OF_SPIRIT, ROYAL_TRIBUTE, GRAVEKEEPERS_SERVANT,
    NECROVALLEY, GRAVEKEEPERS_AMBUSHER, GRAVEKEEPERS_CANNONHOLDER, GRAVEKEEPERS_CHIEF,
    GRAVEKEEPERS_COMMANDANT, GRAVEKEEPERS_CURSE, GRAVEKEEPERS_DESCENDANT, GRAVEKEEPERS_GUARD,
};

const u16 sGravekeepers_Extra[] APPEND_RODATA = {
    GRAVEKEEPERS_SUPERNATURALIST, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sHarpieLadies_Deck[] APPEND_RODATA = {
    HARPIE_LADY, HARPIE_LADY_SISTERS, ELEGANT_EGOTIST, HARPIES_PET_DRAGON,
    HARPIES_BROTHER, HARPIES_FEATHER_DUSTER, CYBER_HARPIE, HARPIE_LADY_1,
    HARPIE_LADY_2, HARPIE_LADY_3, HARPIES_PET_BABY_DRAGON, HARPIE_LADY_PHOENIX_FORMATION,
    HARPIE_CHANNELER, HARPIE_DANCER, HARPIE_HARPIST, HARPIE_LADY_ELEGANCE,
    HARPIE_ORACLE, HARPIE_PERFUMER, HARPIE_QUEEN, HARPIES_FEATHER_REST,
    HARPIES_FEATHER_STORM, HARPIES_HUNTING_GROUND, TRIANGLE_ECSTASY_SPARK, HARPIE_LADY,
    HARPIE_LADY_SISTERS, ELEGANT_EGOTIST, HARPIES_PET_DRAGON, HARPIES_BROTHER,
    HARPIES_FEATHER_DUSTER, CYBER_HARPIE, HARPIE_LADY_1, HARPIE_LADY_2,
    HARPIE_LADY_3, HARPIES_PET_BABY_DRAGON, HARPIE_LADY_PHOENIX_FORMATION, HARPIE_CHANNELER,
    HARPIE_DANCER, HARPIE_HARPIST, HARPIE_LADY_ELEGANCE, HARPIE_ORACLE,
};

const u16 sHarpieLadies_Extra[] APPEND_RODATA = {
    CYBER_SLASH_HARPIE_LADY, HARPIE_CONDUCTOR, HARPIES_PET_PHANTASMAL_DRAGON, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sElementalHero_Deck[] APPEND_RODATA = {
    POLYMERIZATION, ELEMENTAL_HERO_AVIAN, ELEMENTAL_HERO_BURSTINATRIX, ELEMENTAL_HERO_SPARKMAN,
    ELEMENTAL_HERO_BUBBLEMAN, ELEMENTAL_HERO_WILDHEART, ELEMENTAL_HERO_BLADEDGE, ELEMENTAL_HERO_CLAYMAN,
    ELEMENTAL_HERO_NECROSHADE, MIRACLE_FUSION, ELEMENTAL_HERO_WOODSMAN, ELEMENTAL_HERO_OCEAN,
    ELEMENTAL_HERO_HEAT, ELEMENTAL_HERO_LADY_HEAT, ELEMENTAL_HERO_KNOSPE, ELEMENTAL_HERO_POISON_ROSE,
    ELEMENTAL_HERO_VOLTIC, ELEMENTAL_HERO_FLASH, SKYSCRAPER, ELEMENTAL_HERO_CAPTAIN_GOLD,
    ELEMENTAL_HERO_ICE_EDGE, ELEMENTAL_HERO_BLAZEMAN, ELEMENTAL_HERO_STRATOS, A_HERO_EMERGES,
    A_HERO_LIVES, HERO_FLASH, PARALLEL_WORLD_FUSION, SKYSCRAPER_2_HERO_CITY,
    SUPER_POLYMERIZATION, HERO_KID, ULTRA_POLYMERIZATION, POLYMERIZATION,
    ELEMENTAL_HERO_AVIAN, ELEMENTAL_HERO_BURSTINATRIX, ELEMENTAL_HERO_SPARKMAN, ELEMENTAL_HERO_BUBBLEMAN,
    ELEMENTAL_HERO_WILDHEART, ELEMENTAL_HERO_BLADEDGE, ELEMENTAL_HERO_CLAYMAN, ELEMENTAL_HERO_NECROSHADE,
};

const u16 sElementalHero_Extra[] APPEND_RODATA = {
    ELEMENTAL_HERO_MUDBALLMAN, ELEMENTAL_HERO_RAMPART_BLASTER, ELEMENTAL_HERO_STEAM_HEALER, ELEMENTAL_HERO_PHOENIX_ENFORCER,
    ELEMENTAL_HERO_SHINING_PHOENIX_ENFORCER, ELEMENTAL_HERO_FLAME_WINGMAN, ELEMENTAL_HERO_SHINING_FLARE_WINGMAN, ELEMENTAL_HERO_TEMPEST,
    ELEMENTAL_HERO_WILDEDGE, ELEMENTAL_HERO_THUNDER_GIANT, ELEMENTAL_HERO_MARINER, ELEMENTAL_HERO_ELECTRUM,
    ELEMENTAL_HERO_GREAT_TORNADO, ELEMENTAL_HERO_TERRA_FIRMA, ELEMENTAL_HERO_ABSOLUTE_ZERO,
};

const u16 sVisionHero_Deck[] APPEND_RODATA = {
    POLYMERIZATION, MIRACLE_FUSION, A_HERO_EMERGES, A_HERO_LIVES,
    SUPER_POLYMERIZATION, VISION_HERO_FARIS, VISION_HERO_GRAVITO, VISION_HERO_INCREASE,
    VISION_HERO_MINIMUM_RAY, VISION_HERO_MULTIPLY_GUY, VISION_HERO_POISONER, VISION_HERO_VYON,
    VISION_HERO_WITCH_RAIDER, ULTRA_POLYMERIZATION, POLYMERIZATION, MIRACLE_FUSION,
    A_HERO_EMERGES, A_HERO_LIVES, SUPER_POLYMERIZATION, VISION_HERO_FARIS,
    VISION_HERO_GRAVITO, VISION_HERO_INCREASE, VISION_HERO_MINIMUM_RAY, VISION_HERO_MULTIPLY_GUY,
    VISION_HERO_POISONER, VISION_HERO_VYON, VISION_HERO_WITCH_RAIDER, ULTRA_POLYMERIZATION,
    POLYMERIZATION, MIRACLE_FUSION, A_HERO_EMERGES, A_HERO_LIVES,
    SUPER_POLYMERIZATION, VISION_HERO_FARIS, VISION_HERO_GRAVITO, VISION_HERO_INCREASE,
    VISION_HERO_MINIMUM_RAY, VISION_HERO_MULTIPLY_GUY, VISION_HERO_POISONER, VISION_HERO_VYON,
};

const u16 sVisionHero_Extra[] APPEND_RODATA = {
    VISION_HERO_ADORATION, VISION_HERO_TRINITY, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sEvilHero_Deck[] APPEND_RODATA = {
    SUPER_POLYMERIZATION, DARK_CALLING, DARK_FUSION, EVIL_HERO_ADUSTED_GOLD,
    EVIL_HERO_DEAD_END_PRISON, EVIL_HERO_INFERNAL_GAINER, EVIL_HERO_INFERNAL_PRODIGY, EVIL_HERO_INFERNAL_RIDER,
    EVIL_HERO_MALICIOUS_EDGE, EVIL_HERO_SINISTER_NECROM, EVIL_HERO_TOXIC_BUBBLE, EVIL_HERO_VICIOUS_CLAWS,
    EVIL_MIND, SUPER_POLYMERIZATION, DARK_CALLING, DARK_FUSION,
    EVIL_HERO_ADUSTED_GOLD, EVIL_HERO_DEAD_END_PRISON, EVIL_HERO_INFERNAL_GAINER, EVIL_HERO_INFERNAL_PRODIGY,
    EVIL_HERO_INFERNAL_RIDER, EVIL_HERO_MALICIOUS_EDGE, EVIL_HERO_SINISTER_NECROM, EVIL_HERO_TOXIC_BUBBLE,
    EVIL_HERO_VICIOUS_CLAWS, EVIL_MIND, SUPER_POLYMERIZATION, DARK_CALLING,
    DARK_FUSION, EVIL_HERO_ADUSTED_GOLD, EVIL_HERO_DEAD_END_PRISON, EVIL_HERO_INFERNAL_GAINER,
    EVIL_HERO_INFERNAL_PRODIGY, EVIL_HERO_INFERNAL_RIDER, EVIL_HERO_MALICIOUS_EDGE, EVIL_HERO_SINISTER_NECROM,
    EVIL_HERO_TOXIC_BUBBLE, EVIL_HERO_VICIOUS_CLAWS, EVIL_MIND, SUPER_POLYMERIZATION,
};

const u16 sEvilHero_Extra[] APPEND_RODATA = {
    EVIL_HERO_DARK_GAIA, EVIL_HERO_DARKEST_KNIGHT, EVIL_HERO_INFERNAL_SNIPER, EVIL_HERO_INFERNO_WING,
    EVIL_HERO_INFERNO_WING_BACKFIRE, EVIL_HERO_LIGHTNING_GOLEM, EVIL_HERO_MALICIOUS_BANE, EVIL_HERO_MALICIOUS_FIEND,
    EVIL_HERO_NEOS_LORD, EVIL_HERO_WILD_CYCLONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sNeoSpacians_Deck[] APPEND_RODATA = {
    ELEMENTAL_HERO_NEOS, ELEMENTAL_HERO_NEOS_ALIUS, DARK_CONTACT, CONTACT,
    CONTACT_GATE, CONVERT_CONTACT, ELEMENTAL_HERO_SPIRIT_OF_NEOS, EN_ENGAGE_NEO_SPACE,
    FAVOURITE_CONTACT, GENERATION_NEXT, INSTANT_CONTACT, INSTANT_NEO_SPACE,
    MIRACLE_CONTACT, NEO_SPACE, NEO_SPACE_CONNECTOR, NEO_SPACIAN_AIR_HUMMINGBIRD,
    NEO_SPACIAN_AQUA_DOLPHIN, NEO_SPACIAN_DARK_PANTHER, NEO_SPACIAN_FLARE_SCARAB, NEO_SPACIAN_GLOW_MOSS,
    NEO_SPACIAN_GRAND_MOLE, NEX, NEXT, ELEMENTAL_HERO_NEOS,
    ELEMENTAL_HERO_NEOS_ALIUS, DARK_CONTACT, CONTACT, CONTACT_GATE,
    CONVERT_CONTACT, ELEMENTAL_HERO_SPIRIT_OF_NEOS, EN_ENGAGE_NEO_SPACE, FAVOURITE_CONTACT,
    GENERATION_NEXT, INSTANT_CONTACT, INSTANT_NEO_SPACE, MIRACLE_CONTACT,
    NEO_SPACE, NEO_SPACE_CONNECTOR, NEO_SPACIAN_AIR_HUMMINGBIRD, NEO_SPACIAN_AQUA_DOLPHIN,
};

const u16 sNeoSpacians_Extra[] APPEND_RODATA = {
    ELEMENTAL_HERO_NEOS_KLUGER, ELEMENTAL_HERO_AIR_NEOS, ELEMENTAL_HERO_AQUA_NEOS, ELEMENTAL_HERO_BRAVE_NEOS,
    ELEMENTAL_HERO_CHAOS_NEOS, ELEMENTAL_HERO_COSMO_NEOS, ELEMENTAL_HERO_DARK_NEOS, ELEMENTAL_HERO_FLARE_NEOS,
    ELEMENTAL_HERO_GLOW_NEOS, ELEMENTAL_HERO_GRAND_NEOS, ELEMENTAL_HERO_MAGMA_NEOS, ELEMENTAL_HERO_MARINE_NEOS,
    ELEMENTAL_HERO_NEBULA_NEOS, ELEMENTAL_HERO_SHINING_NEOS_WINGMAN, ELEMENTAL_HERO_STORM_NEOS,
};

const u16 sArcanaForce_Deck[] APPEND_RODATA = {
    ARCANA_CALL, ARCANA_FORCE_0_THE_FOOL, ARCANA_FORCE_EX_THE_DARK_RULER, ARCANA_FORCE_EX_THE_LIGHT_RULER,
    ARCANA_FORCE_I_THE_MAGICIAN, ARCANA_FORCE_III_THE_EMPRESS, ARCANA_FORCE_IV_THE_EMPEROR, ARCANA_FORCE_V_THE_HIEROPHANT,
    ARCANA_FORCE_VI_THE_LOVERS, ARCANA_FORCE_VII_THE_CHARIOT, ARCANA_FORCE_VIII_THE_STRENGTH, ARCANA_FORCE_XII_THE_HANGMAN,
    ARCANA_FORCE_XIV_TEMPERANCE, ARCANA_FORCE_XIX_THE_SUN, ARCANA_FORCE_XV_THE_FIEND, ARCANA_FORCE_XVIII_THE_MOON,
    ARCANA_FORCE_XXI_THE_WORLD, LIGHT_BARRIER, REVERSAL_OF_FATE, SUIT_OF_SWORD_X,
    TOUR_OF_DOOM, ARCANA_CALL, ARCANA_FORCE_0_THE_FOOL, ARCANA_FORCE_EX_THE_DARK_RULER,
    ARCANA_FORCE_EX_THE_LIGHT_RULER, ARCANA_FORCE_I_THE_MAGICIAN, ARCANA_FORCE_III_THE_EMPRESS, ARCANA_FORCE_IV_THE_EMPEROR,
    ARCANA_FORCE_V_THE_HIEROPHANT, ARCANA_FORCE_VI_THE_LOVERS, ARCANA_FORCE_VII_THE_CHARIOT, ARCANA_FORCE_VIII_THE_STRENGTH,
    ARCANA_FORCE_XII_THE_HANGMAN, ARCANA_FORCE_XIV_TEMPERANCE, ARCANA_FORCE_XIX_THE_SUN, ARCANA_FORCE_XV_THE_FIEND,
    ARCANA_FORCE_XVIII_THE_MOON, ARCANA_FORCE_XXI_THE_WORLD, LIGHT_BARRIER, REVERSAL_OF_FATE,
};

const u16 sArcanaForce_Extra[] APPEND_RODATA = {
    ARCANA_FORCE_THE_CHAOS_RULER, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sMorphtronic_Deck[] APPEND_RODATA = {
    MORPHTRONIC_CELFON, MORPHTRONIC_BOOMBOXEN, DOUBLE_TOOL_C_AND_D, MORPHTRONIC_ACCELERATOR,
    MORPHTRONIC_BIND, MORPHTRONIC_BOARDEN, MORPHTRONIC_CAMERAN, MORPHTRONIC_CLOCKEN,
    MORPHTRONIC_CONVERTER, MORPHTRONIC_CORD, MORPHTRONIC_DATATRON, MORPHTRONIC_ENGINE,
    MORPHTRONIC_FORCEFIELD, MORPHTRONIC_IMPACT_RETURN, MORPHTRONIC_LANTRON, MORPHTRONIC_MAGNEN,
    MORPHTRONIC_MAGNEN_BAR, MORPHTRONIC_MAP, MORPHTRONIC_MONITRON, MORPHTRONIC_RADION,
    MORPHTRONIC_REMOTEN, MORPHTRONIC_REPAIR_UNIT, MORPHTRONIC_RUSTY_ENGINE, MORPHTRONIC_SCANNEN,
    MORPHTRONIC_SCOPEN, MORPHTRONIC_SLINGEN, MORPHTRONIC_MIXUP, MORPHTRONIC_SMARTFON,
    MORPHTRONIC_STAPLEN, MORPHTRONIC_TELEFON, MORPHTRONIC_VACUUMEN, MORPHTRONIC_VIDEON,
    MORPHTRONIC_CELFON, MORPHTRONIC_BOOMBOXEN, MORPHTRONIC_CELFON, MORPHTRONIC_BOOMBOXEN,
    DOUBLE_TOOL_C_AND_D, MORPHTRONIC_ACCELERATOR, MORPHTRONIC_BIND, MORPHTRONIC_BOARDEN,
};

const u16 sMorphtronic_Extra[] APPEND_RODATA = {
    POWER_TOOL_DRAGON, LIFE_STREAM_DRAGON, MORPHTRONIC_EARFON, POWER_TOOL_BRAVER_DRAGON,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sCyberDragon_Deck[] APPEND_RODATA = {
    CYBER_DRAGON, PROTO_CYBER_DRAGON, POLYMERIZATION, FUTURE_FUSION,
    CYBERNETIC_FUSION_SUPPORT, OVERLOAD_FUSION, POWER_BOND, CYBER_BARRIER_DRAGON,
    CYBER_LASER_DRAGON, CYBER_PHOENIX, CYBER_VALLEY, CYBERNETIC_ZONE,
    SUPER_POLYMERIZATION, ULTRA_POLYMERIZATION, CYBER_DRAGON, PROTO_CYBER_DRAGON,
    CYBER_DRAGON, PROTO_CYBER_DRAGON, POLYMERIZATION, FUTURE_FUSION,
    CYBERNETIC_FUSION_SUPPORT, OVERLOAD_FUSION, POWER_BOND, CYBER_BARRIER_DRAGON,
    CYBER_LASER_DRAGON, CYBER_PHOENIX, CYBER_VALLEY, CYBERNETIC_ZONE,
    SUPER_POLYMERIZATION, ULTRA_POLYMERIZATION, CYBER_DRAGON, PROTO_CYBER_DRAGON,
    CYBER_DRAGON, PROTO_CYBER_DRAGON, POLYMERIZATION, FUTURE_FUSION,
    CYBERNETIC_FUSION_SUPPORT, OVERLOAD_FUSION, POWER_BOND, CYBER_BARRIER_DRAGON,
};

const u16 sCyberDragon_Extra[] APPEND_RODATA = {
    CYBER_TWIN_DRAGON, CYBER_END_DRAGON, CYBER_DRAGON_INFINITY, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sAncientGear_Deck[] APPEND_RODATA = {
    ANCIENT_GEAR_GOLEM, ANCIENT_GEAR_FRAME, GEARTOWN, ANCIENT_GEAR,
    ANCIENT_GEAR_ADVANCE, ANCIENT_GEAR_BEAST, ANCIENT_GEAR_CANNON, ANCIENT_GEAR_CASTLE,
    ANCIENT_GEAR_COMMANDER, ANCIENT_GEAR_DARK_GOLEM, ANCIENT_GEAR_DRAGON, ANCIENT_GEAR_DRILL,
    ANCIENT_GEAR_DUEL, ANCIENT_GEAR_ENGINEER, ANCIENT_GEAR_EXPLOSIVE, ANCIENT_GEAR_FACTORY,
    ANCIENT_GEAR_FIST, ANCIENT_GEAR_FUSION, ANCIENT_GEAR_GADJILTRON_CHIMERA, ANCIENT_GEAR_GADJILTRON_DRAGON,
    ANCIENT_GEAR_GOLEM_ULTIMATE_POUND, ANCIENT_GEAR_KNIGHT, ANCIENT_GEAR_SOLDIER, ANCIENT_GEAR_STATUE,
    ANCIENT_GEAR_TANK, ANCIENT_GEAR_TANKER, ANCIENT_GEAR_WORKSHOP, SPELL_GEAR,
    ANCIENT_GEAR_GOLEM, ANCIENT_GEAR_FRAME, GEARTOWN, ANCIENT_GEAR_GOLEM,
    ANCIENT_GEAR_FRAME, GEARTOWN, ANCIENT_GEAR, ANCIENT_GEAR_ADVANCE,
    ANCIENT_GEAR_BEAST, ANCIENT_GEAR_CANNON, ANCIENT_GEAR_CASTLE, ANCIENT_GEAR_COMMANDER,
};

const u16 sAncientGear_Extra[] APPEND_RODATA = {
    ANCIENT_GEAR_MEGATON_GOLEM, CHAOS_ANCIENT_GEAR_GIANT, ULTIMATE_ANCIENT_GEAR_GOLEM, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sVenom_Deck[] APPEND_RODATA = {
    VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES, VENNOMINON_THE_KING_OF_POISONOUS_SNAKES, VENOM_SWAMP, SNAKE_RAIN,
    VENOM_BOA, VENOM_BURN, VENOM_COBRA, VENOM_SERPENT,
    VENOM_SHOT, VENOM_SNAKE, VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES, VENNOMINON_THE_KING_OF_POISONOUS_SNAKES,
    VENOM_SWAMP, VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES, VENNOMINON_THE_KING_OF_POISONOUS_SNAKES, VENOM_SWAMP,
    SNAKE_RAIN, VENOM_BOA, VENOM_BURN, VENOM_COBRA,
    VENOM_SERPENT, VENOM_SHOT, VENOM_SNAKE, VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES,
    VENNOMINON_THE_KING_OF_POISONOUS_SNAKES, VENOM_SWAMP, VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES, VENNOMINON_THE_KING_OF_POISONOUS_SNAKES,
    VENOM_SWAMP, SNAKE_RAIN, VENOM_BOA, VENOM_BURN,
    VENOM_COBRA, VENOM_SERPENT, VENOM_SHOT, VENOM_SNAKE,
    VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES, VENNOMINON_THE_KING_OF_POISONOUS_SNAKES, VENOM_SWAMP, VENNOMINAGA_THE_DEITY_OF_POISONOUS_SNAKES,
};

const u16 sVenom_Extra[] APPEND_RODATA = {
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sShaddoll_Deck[] APPEND_RODATA = {
    SHADDOLL_FUSION, SHADDOLL_SQUAMATA, SHADDOLL_BEAST, EL_SHADDOLL_FUSION,
    HELSHADDOLL_HOLLOW, LEV_SHADDOLL_FUSION, NAELSHADDOLL_ARIEL, NEHSHADDOLL_GENIUS,
    NEPHE_SHADDOLL_FUSION, QADSHADDOLL_KEIOS, REESHADDOLL_WENDI, SHADDOLL_CORE,
    SHADDOLL_DRAGON, SHADDOLL_FALCO, SHADDOLL_HEDGEHOG, SHADDOLL_HOUND,
    SHADDOLL_SCHISM, TOHUSHADDOLL_GRYSTA, SHADDOLL_FUSION, SHADDOLL_SQUAMATA,
    SHADDOLL_BEAST, SHADDOLL_FUSION, SHADDOLL_SQUAMATA, SHADDOLL_BEAST,
    EL_SHADDOLL_FUSION, HELSHADDOLL_HOLLOW, LEV_SHADDOLL_FUSION, NAELSHADDOLL_ARIEL,
    NEHSHADDOLL_GENIUS, NEPHE_SHADDOLL_FUSION, QADSHADDOLL_KEIOS, REESHADDOLL_WENDI,
    SHADDOLL_CORE, SHADDOLL_DRAGON, SHADDOLL_FALCO, SHADDOLL_HEDGEHOG,
    SHADDOLL_HOUND, SHADDOLL_SCHISM, TOHUSHADDOLL_GRYSTA, SHADDOLL_FUSION,
};

const u16 sShaddoll_Extra[] APPEND_RODATA = {
    EL_SHADDOLL_ANOYATYLLIS, EL_SHADDOLL_APKALLONE, EL_SHADDOLL_CONSTRUCT, EL_SHADDOLL_GRYSTA,
    EL_SHADDOLL_MESHAHRAIL, EL_SHADDOLL_SHEKHINAGA, EL_SHADDOLL_WENDIGO, EL_SHADDOLL_WINDA,
    REESHADDOLL_WENDIKURUHU, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sAroma_Deck[] APPEND_RODATA = {
    AROMAGE_JASMINE, AROMA_GARDEN, AROMA_BLEND, AROMA_GARDENING,
    AROMA_JAR, AROMAGE_BERGAMOT, AROMAGE_CANANGA, AROMAGE_LAUREL,
    AROMAGE_MARJORAM, AROMAGE_ROSEMARY, AROMALILITH_ROSALINA, AROMAGE_JASMINE,
    AROMA_GARDEN, AROMAGE_JASMINE, AROMA_GARDEN, AROMA_BLEND,
    AROMA_GARDENING, AROMA_JAR, AROMAGE_BERGAMOT, AROMAGE_CANANGA,
    AROMAGE_LAUREL, AROMAGE_MARJORAM, AROMAGE_ROSEMARY, AROMALILITH_ROSALINA,
    AROMAGE_JASMINE, AROMA_GARDEN, AROMAGE_JASMINE, AROMA_GARDEN,
    AROMA_BLEND, AROMA_GARDENING, AROMA_JAR, AROMAGE_BERGAMOT,
    AROMAGE_CANANGA, AROMAGE_LAUREL, AROMAGE_MARJORAM, AROMAGE_ROSEMARY,
    AROMALILITH_ROSALINA, AROMAGE_JASMINE, AROMA_GARDEN, AROMAGE_JASMINE,
};

const u16 sAroma_Extra[] APPEND_RODATA = {
    AROMALILITH_MAGNOLIA, AROMALILITH_ROSEMARY, AROMASERAPHY_JASMINE, AROMASERAPHY_ROSEMARY,
    AROMASERAPHY_SWEET_MARJORAM, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

const u16 sFairy_Deck[] APPEND_RODATA = {
    THE_SPLENDID_VENUS, THE_AGENT_OF_CREATION_VENUS, HONEST, THE_AGENT_OF_DESTRUCTION_VENUS,
    THE_AGENT_OF_FORCE_MARS, THE_AGENT_OF_JUDGMENT_SATURN, THE_AGENT_OF_WISDOM_MERCURY, THE_AGENT_OF_LIFE_NEPTUNE,
    THE_AGENT_OF_MIRACLES_JUPITER, THE_AGENT_OF_ENTROPY_URANUS, THE_AGENT_OF_MYSTERU_EARTH, THE_SANCTUARY_IN_THE_SKY,
    VALHALLA_HALL_OF_THE_FALLEN, COURT_OF_JUSTICE, ARCHLORD_KRISTYA, MASTER_HYPERION,
    ATHENA, TETHYS_GODDESS_OF_LIGHT, ZERADIAS_HERALD_OF_HEAVEN, AIRKNIGHT_PARSHATH,
    GUARDIAN_ANGEL_JOAN, VICTORIA, TUALATIN, HOSHININGEN,
    DUNAMES_DARK_WITCH, GYAKUTENNO_MEGAMI, ORION_THE_BATTLE_KING, MOISTER_CREATURE,
    MIGHTY_ANGEL_VIRCH, SERAPHIM_BLASTER, MAJESTIC_MECH_GORYU, PROTECTOR_OF_THE_SANCTUARY,
    GODDESS_WITH_THE_THIRD_EYE, WEATHER_CONTROL, BANISHER_OF_THE_LIGHT, SPIRIT_OF_THE_HARP,
    SENJU_OF_THE_THOUSAND_HANDS, KEY_MACE, HAPPY_LOVER, PETIT_ANGEL,
};

const u16 sFairy_Extra[] APPEND_RODATA = {
    PROTECTOR_OF_THE_AGENTS_MOON, CELESTIAL_KNIGHTLORD_PARSHATH, MASTERFLARE_HYPERION, ANCIENT_SACRED_WYVERN,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE, CARD_NONE,
    CARD_NONE, CARD_NONE, CARD_NONE,
};

#define DEBUG_MENU_DECK_RESTORE_ENTRY(title) {NULL, NULL, title},
#define DEBUG_MENU_DECK_ENTRY(deckSym, extraSym, title) {deckSym, extraSym, title},

static const struct DebugMenuDeckEntry sDecks[] APPEND_RODATA = {
#include "debug_menu_deck_table.inc"
};

#undef DEBUG_MENU_DECK_RESTORE_ENTRY
#undef DEBUG_MENU_DECK_ENTRY

const u16 *DebugMenuDeck_GetCards(u8 index) {
  if (index == 0 || index >= ARRAY_COUNT(sDecks))
    return NULL;
  return sDecks[index].cards;
}

const u16 *DebugMenuDeck_GetExtraCards(u8 index) {
  if (index == 0 || index >= ARRAY_COUNT(sDecks))
    return NULL;
  return sDecks[index].extraCards;
}

static bool8 DebugMenuIsDeckRowActive(u8 index, u8 activePreset) {
  if (index == 0)
    return activePreset == DEBUG_DECK_SWAP_INACTIVE;
  return activePreset == index;
}

static void DebugMenuFormatDeckRow(u8 *out, const struct DebugMenuDeckEntry *e, bool8 active) {
  DebugMenuFormatListRow(out, e->title, active);
}

void DebugMenuDrawDecks(u8 scrollTop, u8 activePreset) {
  u8 row, buf[2 + DEBUG_CHARS + 1];

  for (row = 0; row < DEBUG_ROWS; row++) {
    u8 index = scrollTop + row;

    if (index < ARRAY_COUNT(sDecks)) {
      DebugMenuFormatDeckRow(buf, &sDecks[index], DebugMenuIsDeckRowActive(index, activePreset));
      DebugMenuCopyLine(row, buf);
    } else {
      DebugMenuCopyLine(row, gDebugMenuBlankLine);
    }
  }
}

void DebugDeckPresetViewer(void) {
  u8 cursor = 0, scrollTop = 0;
  const u8 n = ARRAY_COUNT(sDecks);
  DebugMenuRedraw(0, DebugDeckSwap_GetActivePreset(), DEBUG_VIEW_DECK_PRESET);
  DebugMenuWaitVBlank();

  while (1) {
    u16 buttons = DebugMenuButtons();
    u8 activePreset = DebugDeckSwap_GetActivePreset();

    if (buttons & B_BUTTON)
      break;
    if (buttons & DPAD_UP && cursor != 0) {
      PlayMusic(SFX_MOVE_CURSOR);
      if (--cursor < scrollTop)
        scrollTop = cursor;
      DebugMenuRedraw(scrollTop, activePreset, DEBUG_VIEW_DECK_PRESET);
    }
    if (buttons & DPAD_DOWN && cursor < n - 1) {
      PlayMusic(SFX_MOVE_CURSOR);
      if (++cursor >= scrollTop + DEBUG_ROWS)
        scrollTop = cursor - (DEBUG_ROWS - 1);
      DebugMenuRedraw(scrollTop, activePreset, DEBUG_VIEW_DECK_PRESET);
    }
    if (buttons & A_BUTTON) {
      PlayMusic(SFX_SELECT);
      if (cursor == 0) {
        DebugDeckSwap_RestoreOriginal();
      } else if (sDecks[cursor].cards != NULL) {
        DebugDeckSwap_ApplyPreset(cursor, sDecks[cursor].cards, sDecks[cursor].extraCards);
      }
      activePreset = DebugDeckSwap_GetActivePreset();
      DebugMenuRedraw(scrollTop, activePreset, DEBUG_VIEW_DECK_PRESET);
      DebugMenuWaitRelease(A_BUTTON);
    }

    DebugMenuUpdateCursor(cursor - scrollTop);
    LoadOam();
    DebugMenuWaitVBlank();
  }

  DebugMenuWaitRelease(B_BUTTON);
  DebugMenuVBlankNoWin();
  DebugMenuRedraw(0, 0, DEBUG_VIEW_ROOT);
  DebugMenuVBlankNoWin();
  DebugMenuWaitVBlank();
}
