#include "global.h"
#include "continuous_trap_turn_start.h"

void TryActivateALL_OUT_ATTACKSOnOpponentTurnStart(void);
void TryActivateAMAZONESS_HALLOnOpponentTurnStart(void);
void TryActivateAMAZONESS_HOT_SPRINGOnOpponentTurnStart(void);
void TryActivateAMAZONESS_ONSLAUGHTOnOpponentTurnStart(void);
void TryActivateANCIENT_GEAR_DUELOnOpponentTurnStart(void);
void TryActivateANTI_SPELL_FRAGRANCEOnOpponentTurnStart(void);
void TryActivateAPPROPRIATEOnOpponentTurnStart(void);
void TryActivateBACKFIREOnOpponentTurnStart(void);
void TryActivateBLESSED_WINDSOnOpponentTurnStart(void);
void TryActivateDES_COUNTERBLOWOnOpponentTurnStart(void);
void TryActivateDOPPELGANGEROnOpponentTurnStart(void);
void TryActivateDRAGON_S_RAGEOnOpponentTurnStart(void);
void TryActivateDRIED_WINDSOnOpponentTurnStart(void);
void TryActivateD_TACTICSOnOpponentTurnStart(void);
void TryActivateETERNAL_SOULOnOpponentTurnStart(void);
void TryActivateFORGOTTEN_TEMPLE_OF_THE_DEEPOnOpponentTurnStart(void);
void TryActivateGIFT_CARDOnOpponentTurnStart(void);
void TryActivateGLADIATOR_BEASTS_VALOROnOpponentTurnStart(void);
void TryActivateGLADIATOR_NAUMACHIAOnOpponentTurnStart(void);
void TryActivateGRAVEKEEPERS_TRAPOnOpponentTurnStart(void);
void TryActivateHUMID_WINDSOnOpponentTurnStart(void);
void TryActivateLIGHTSWORN_BARRIEROnOpponentTurnStart(void);
void TryActivateLIGHT_OF_DESTRUCTIONOnOpponentTurnStart(void);
void TryActivateLIGHT_SPIRALOnOpponentTurnStart(void);
void TryActivateMAGICIANS_COMBINATIONOnOpponentTurnStart(void);
void TryActivateMORPHTRONIC_BINDOnOpponentTurnStart(void);
void TryActivateMORPHTRONIC_MONITRONOnOpponentTurnStart(void);
void TryActivateNECROVALLEY_TEMPLEOnOpponentTurnStart(void);
void TryActivateNEEDLE_WALLOnOpponentTurnStart(void);
void TryActivateSERPENT_SUPPRESSIONOnOpponentTurnStart(void);
void TryActivateSHADDOLL_SCHISMOnOpponentTurnStart(void);
void TryActivateSOUL_LEVYOnOpponentTurnStart(void);
void TryActivateTHUMBS_DOWNOnOpponentTurnStart(void);
void TryActivateTORNADO_WALLOnOpponentTurnStart(void);
void TryActivateTOUR_OF_DOOMOnOpponentTurnStart(void);

void TryActivateAngelsTearOnOpponentTurnStart(void);
void TryActivateBlastingTheRuinsOnOpponentTurnStart(void);
void TryActivateCallOfTheHauntedOnOpponentTurnStart(void);
void TryActivateCurseOfDarknessOnOpponentTurnStart(void);
void TryActivateGiftOfTheMysticalElfOnOpponentTurnStart(void);
void TryActivateJarOfGreedOnOpponentTurnStart(void);
void TryActivateJustDesertsOnOpponentTurnStart(void);
void TryActivateLevelLimitAreaAOnOpponentTurnStart(void);
void TryActivateOjamaTrioOnOpponentTurnStart(void);
void TryActivateRecklessGreedOnOpponentTurnStart(void);
void TryActivateRobbinGoblinOnOpponentTurnStart(void);
void TryActivateRobbinZombieOnOpponentTurnStart(void);
void TryActivateSecretBarrelOnOpponentTurnStart(void);
void TryActivateSelfDestructButtonOnOpponentTurnStart(void);
void TryActivateSkullInvitationOnOpponentTurnStart(void);
void TryActivateSolarRayOnOpponentTurnStart(void);
void TryActivateTimeSealOnOpponentTurnStart(void);

void ContinuousTraps_TryActivateOnOpponentTurnStart(void)
{
  TryActivateALL_OUT_ATTACKSOnOpponentTurnStart();
  TryActivateAMAZONESS_HALLOnOpponentTurnStart();
  TryActivateAMAZONESS_HOT_SPRINGOnOpponentTurnStart();
  TryActivateAMAZONESS_ONSLAUGHTOnOpponentTurnStart();
  TryActivateANCIENT_GEAR_DUELOnOpponentTurnStart();
  TryActivateANTI_SPELL_FRAGRANCEOnOpponentTurnStart();
  TryActivateAPPROPRIATEOnOpponentTurnStart();
  TryActivateBACKFIREOnOpponentTurnStart();
  TryActivateBLESSED_WINDSOnOpponentTurnStart();
  TryActivateDES_COUNTERBLOWOnOpponentTurnStart();
  TryActivateDOPPELGANGEROnOpponentTurnStart();
  TryActivateDRAGON_S_RAGEOnOpponentTurnStart();
  TryActivateDRIED_WINDSOnOpponentTurnStart();
  TryActivateD_TACTICSOnOpponentTurnStart();
  TryActivateETERNAL_SOULOnOpponentTurnStart();
  TryActivateFORGOTTEN_TEMPLE_OF_THE_DEEPOnOpponentTurnStart();
  TryActivateGIFT_CARDOnOpponentTurnStart();
  TryActivateGLADIATOR_BEASTS_VALOROnOpponentTurnStart();
  TryActivateGLADIATOR_NAUMACHIAOnOpponentTurnStart();
  TryActivateGRAVEKEEPERS_TRAPOnOpponentTurnStart();
  TryActivateHUMID_WINDSOnOpponentTurnStart();
  TryActivateLIGHTSWORN_BARRIEROnOpponentTurnStart();
  TryActivateLIGHT_OF_DESTRUCTIONOnOpponentTurnStart();
  TryActivateLIGHT_SPIRALOnOpponentTurnStart();
  TryActivateMAGICIANS_COMBINATIONOnOpponentTurnStart();
  TryActivateMORPHTRONIC_BINDOnOpponentTurnStart();
  TryActivateMORPHTRONIC_MONITRONOnOpponentTurnStart();
  TryActivateNECROVALLEY_TEMPLEOnOpponentTurnStart();
  TryActivateNEEDLE_WALLOnOpponentTurnStart();
  TryActivateSERPENT_SUPPRESSIONOnOpponentTurnStart();
  TryActivateSHADDOLL_SCHISMOnOpponentTurnStart();
  TryActivateSOUL_LEVYOnOpponentTurnStart();
  TryActivateTHUMBS_DOWNOnOpponentTurnStart();
  TryActivateTORNADO_WALLOnOpponentTurnStart();
  TryActivateTOUR_OF_DOOMOnOpponentTurnStart();

  TryActivateAngelsTearOnOpponentTurnStart();
  TryActivateBlastingTheRuinsOnOpponentTurnStart();
  TryActivateCallOfTheHauntedOnOpponentTurnStart();
  TryActivateCurseOfDarknessOnOpponentTurnStart();
  TryActivateGiftOfTheMysticalElfOnOpponentTurnStart();
  TryActivateJarOfGreedOnOpponentTurnStart();
  TryActivateJustDesertsOnOpponentTurnStart();
  TryActivateLevelLimitAreaAOnOpponentTurnStart();
  TryActivateOjamaTrioOnOpponentTurnStart();
  TryActivateRecklessGreedOnOpponentTurnStart();
  TryActivateRobbinGoblinOnOpponentTurnStart();
  TryActivateRobbinZombieOnOpponentTurnStart();
  TryActivateSecretBarrelOnOpponentTurnStart();
  TryActivateSelfDestructButtonOnOpponentTurnStart();
  TryActivateSkullInvitationOnOpponentTurnStart();
  TryActivateSolarRayOnOpponentTurnStart();
  TryActivateTimeSealOnOpponentTurnStart();
}
