#include "global.h"

static const unsigned char YugiUnused_todo[] = INCBIN_U8("src/overworld/entities/yugi_unused.4bpp");
static const unsigned char Yugi[] = INCBIN_U8("src/overworld/entities/yugi.4bpp");
static const unsigned char Atem[] = INCBIN_U8("src/overworld/entities/atem.4bpp");
static const unsigned char Seto[] = INCBIN_U8("src/overworld/entities/seto.4bpp");
static const unsigned char Joey[] = INCBIN_U8("src/overworld/entities/joey.4bpp");
static const unsigned char Marik[] = INCBIN_U8("src/overworld/entities/marik.4bpp");
static const unsigned char Ishizu[] = INCBIN_U8("src/overworld/entities/ishizu.4bpp");
static const unsigned char Mai[] = INCBIN_U8("src/overworld/entities/mai.4bpp");

// TODO: write a comment in the palette num(bank) array to fix the corresponding palettes (BUGFIX?)
//       same for yugi_running
static const unsigned char SolomonUnused_todo[] = INCBIN_U8("src/overworld/entities/solomon.4bpp");
static const unsigned char JoeyRunning_todo[] = INCBIN_U8("src/overworld/entities/joey_running.4bpp");

static const unsigned char Tea[] = INCBIN_U8("src/overworld/entities/tea.4bpp");
static const unsigned char Solomon[] = INCBIN_U8("src/overworld/entities/solomon.4bpp");
static const unsigned char Lumis[] = INCBIN_U8("src/overworld/entities/lumis.4bpp");
static const unsigned char Umbra[] = INCBIN_U8("src/overworld/entities/umbra.4bpp");
static const unsigned char Strings[] = INCBIN_U8("src/overworld/entities/strings.4bpp");
static const unsigned char Seeker[] = INCBIN_U8("src/overworld/entities/seeker.4bpp");
static const unsigned char Arkana[] = INCBIN_U8("src/overworld/entities/arkana.4bpp");
static const unsigned char Espa[] = INCBIN_U8("src/overworld/entities/espa.4bpp");
static const unsigned char Weevil[] = INCBIN_U8("src/overworld/entities/weevil.4bpp");
static const unsigned char Rex[] = INCBIN_U8("src/overworld/entities/rex.4bpp");
static const unsigned char Mako[] = INCBIN_U8("src/overworld/entities/mako.4bpp");
static const unsigned char Bonz[] = INCBIN_U8("src/overworld/entities/bonz.4bpp");
static const unsigned char Bakura[] = INCBIN_U8("src/overworld/entities/bakura.4bpp");
static const unsigned char Para[] = INCBIN_U8("src/overworld/entities/para.4bpp");
static const unsigned char Dox[] = INCBIN_U8("src/overworld/entities/dox.4bpp");
static const unsigned char Player[] = INCBIN_U8("src/overworld/entities/player.4bpp");
static const unsigned char NeoGhoul[] = INCBIN_U8("src/overworld/entities/neo_ghoul.4bpp");
static const unsigned char MimicOfDoom[] = INCBIN_U8("src/overworld/entities/mimic_of_doom.4bpp");
static const unsigned char PuppeteerOfDoom[] = INCBIN_U8("src/overworld/entities/puppeteer_of_doom.4bpp");
static const unsigned char Panik[] = INCBIN_U8("src/overworld/entities/panik.4bpp");
static const unsigned char MillenniumGuardian[] = INCBIN_U8("src/overworld/entities/millennium_guardian.4bpp");
static const unsigned char Pegasus[] = INCBIN_U8("src/overworld/entities/pegasus.4bpp");
static const unsigned char Shadi[] = INCBIN_U8("src/overworld/entities/shadi.4bpp");
static const unsigned char Roland[] = INCBIN_U8("src/overworld/entities/roland.4bpp");
static const unsigned char EspaBiggerBrother_todo[] = INCBIN_U8("src/overworld/entities/34.4bpp");
static const unsigned char EspaLittleBrother_todo[] = INCBIN_U8("src/overworld/entities/35.4bpp");

// TSC uses different palettes, so there is no correct palette for these in reshef
static const unsigned char TSC_Blue_Eyes_todo[] = INCBIN_U8("src/overworld/entities/tsc_blue_eyes.4bpp");
static const unsigned char TSC_Slifer_todo[] = INCBIN_U8("src/overworld/entities/tsc_slifer.4bpp");
static const unsigned char TSC_Ra_todo[] = INCBIN_U8("src/overworld/entities/tsc_ra.4bpp");

static const unsigned char Chevalier[] = INCBIN_U8("src/overworld/entities/chevalier.4bpp");
static const unsigned char s40[] = INCBIN_U8("src/overworld/entities/40.4bpp");
static const unsigned char Invisible[] = INCBIN_U8("src/overworld/entities/invisible.4bpp");
static const unsigned char Takeshi[] = INCBIN_U8("src/overworld/entities/takeshi.4bpp");
static const unsigned char s43[] = INCBIN_U8("src/overworld/entities/43.4bpp");
static const unsigned char s44[] = INCBIN_U8("src/overworld/entities/44.4bpp");
static const unsigned char s45[] = INCBIN_U8("src/overworld/entities/45.4bpp");
static const unsigned char DuelExpressConductor[] = INCBIN_U8("src/overworld/entities/duel_express_conductor.4bpp");
static const unsigned char s47[] = INCBIN_U8("src/overworld/entities/47.4bpp");
static const unsigned char s48[] = INCBIN_U8("src/overworld/entities/48.4bpp");
static const unsigned char Tristan[] = INCBIN_U8("src/overworld/entities/tristan.4bpp");
static const unsigned char s50[] = INCBIN_U8("src/overworld/entities/50.4bpp");
static const unsigned char s51[] = INCBIN_U8("src/overworld/entities/51.4bpp");
static const unsigned char s52[] = INCBIN_U8("src/overworld/entities/52.4bpp");
static const unsigned char s53[] = INCBIN_U8("src/overworld/entities/53.4bpp");
static const unsigned char Duke[] = INCBIN_U8("src/overworld/entities/duke.4bpp");
static const unsigned char Mokuba[] = INCBIN_U8("src/overworld/entities/mokuba.4bpp");
static const unsigned char Serenity[] = INCBIN_U8("src/overworld/entities/serenity.4bpp");
static const unsigned char Lucky[] = INCBIN_U8("src/overworld/entities/lucky.4bpp");
static const unsigned char s58[] = INCBIN_U8("src/overworld/entities/58.4bpp");
static const unsigned char s59[] = INCBIN_U8("src/overworld/entities/59.4bpp");

// TSC uses different palettes, so there is no correct palette for these in reshef
static const unsigned char TSC_Red_Eyes_todo[] = INCBIN_U8("src/overworld/entities/tsc_red_eyes.4bpp");
static const unsigned char TSC_Flame_Swordsman_todo[] = INCBIN_U8("src/overworld/entities/tsc_flame_swordsman.4bpp");

static const unsigned char s62[] = INCBIN_U8("src/overworld/entities/62.4bpp");
static const unsigned char BanditKeith[] = INCBIN_U8("src/overworld/entities/bandit_keith.4bpp");
static const unsigned char S64[] = INCBIN_U8("src/overworld/entities/64.4bpp");
static const unsigned char s65[] = INCBIN_U8("src/overworld/entities/65.4bpp");
static const unsigned char JeanClaudeMagnum[] = INCBIN_U8("src/overworld/entities/jean_claude_magnum.4bpp");
static const unsigned char s67[] = INCBIN_U8("src/overworld/entities/67.4bpp");
static const unsigned char s68[] = INCBIN_U8("src/overworld/entities/68.4bpp");
static const unsigned char s69[] = INCBIN_U8("src/overworld/entities/69.4bpp");
static const unsigned char s70[] = INCBIN_U8("src/overworld/entities/70.4bpp");
static const unsigned char s71[] = INCBIN_U8("src/overworld/entities/71.4bpp");
static const unsigned char s72[] = INCBIN_U8("src/overworld/entities/72.4bpp");
static const unsigned char s73[] = INCBIN_U8("src/overworld/entities/73.4bpp");
static const unsigned char s74[] = INCBIN_U8("src/overworld/entities/74.4bpp");
static const unsigned char s75[] = INCBIN_U8("src/overworld/entities/75.4bpp");
static const unsigned char s76[] = INCBIN_U8("src/overworld/entities/76.4bpp");
static const unsigned char s77[] = INCBIN_U8("src/overworld/entities/77.4bpp");
static const unsigned char s78[] = INCBIN_U8("src/overworld/entities/78.4bpp");
static const unsigned char s79[] = INCBIN_U8("src/overworld/entities/79.4bpp");
static const unsigned char s80[] = INCBIN_U8("src/overworld/entities/80.4bpp");
static const unsigned char s81[] = INCBIN_U8("src/overworld/entities/81.4bpp");
static const unsigned char s82[] = INCBIN_U8("src/overworld/entities/82.4bpp");
static const unsigned char s83[] = INCBIN_U8("src/overworld/entities/83.4bpp");
static const unsigned char s84[] = INCBIN_U8("src/overworld/entities/84.4bpp");
static const unsigned char s85[] = INCBIN_U8("src/overworld/entities/85.4bpp");
static const unsigned char s86[] = INCBIN_U8("src/overworld/entities/86.4bpp");
static const unsigned char s87[] = INCBIN_U8("src/overworld/entities/87.4bpp");
static const unsigned char s88[] = INCBIN_U8("src/overworld/entities/88.4bpp");
static const unsigned char PlayerRunning[] = INCBIN_U8("src/overworld/entities/player_running.4bpp");
static const unsigned char YugiRunning_todo[] = INCBIN_U8("src/overworld/entities/yugi_running.4bpp");
static const unsigned char s91[] = INCBIN_U8("src/overworld/entities/91.4bpp");
static const unsigned char s92[] = INCBIN_U8("src/overworld/entities/92.4bpp");
static const unsigned char s93[] = INCBIN_U8("src/overworld/entities/93.4bpp");
static const unsigned char s94[] = INCBIN_U8("src/overworld/entities/94.4bpp");
static const unsigned char s95[] = INCBIN_U8("src/overworld/entities/95.4bpp");
static const unsigned char s96[] = INCBIN_U8("src/overworld/entities/96.4bpp");
static const unsigned char Paradox[] = INCBIN_U8("src/overworld/entities/paradox.4bpp");
static const unsigned char Noah[] = INCBIN_U8("src/overworld/entities/noah.4bpp");
static const unsigned char MonkeyRobot[] = INCBIN_U8("src/overworld/entities/monkey_robot.4bpp");
static const unsigned char Rebecca[] = INCBIN_U8("src/overworld/entities/rebecca.4bpp");
static const unsigned char s101[] = INCBIN_U8("src/overworld/entities/101.4bpp");
static const unsigned char s102[] = INCBIN_U8("src/overworld/entities/102.4bpp");
static const unsigned char NightmarePenguin[] = INCBIN_U8("src/overworld/entities/nightmare_penguin.4bpp");
static const unsigned char DeepseaWarrior[] = INCBIN_U8("src/overworld/entities/deepsea_warrior.4bpp");
static const unsigned char RoboticKnight[] = INCBIN_U8("src/overworld/entities/robotic_knight.4bpp");
static const unsigned char JudgeMan[] = INCBIN_U8("src/overworld/entities/judge_man.4bpp");
static const unsigned char Jinzo[] = INCBIN_U8("src/overworld/entities/jinzo.4bpp");
static const unsigned char Kaibaman[] = INCBIN_U8("src/overworld/entities/kaibaman.4bpp");
static const unsigned char JohnnySteps[] = INCBIN_U8("src/overworld/entities/johnny_steps.4bpp");
static const unsigned char Arthur[] = INCBIN_U8("src/overworld/entities/arthur.4bpp"); //TODO: fix palette entry
static const unsigned char s111[] = INCBIN_U8("src/overworld/entities/111.4bpp");
static const unsigned char s112[] = INCBIN_U8("src/overworld/entities/112.4bpp");
static const unsigned char VideoCard[] = INCBIN_U8("src/overworld/entities/video_card.4bpp");
static const unsigned char s114[] = INCBIN_U8("src/overworld/entities/114.4bpp");
static const unsigned char s115[] = INCBIN_U8("src/overworld/entities/115.4bpp");
static const unsigned char s116[] = INCBIN_U8("src/overworld/entities/116.4bpp");
static const unsigned char s117[] = INCBIN_U8("src/overworld/entities/117.4bpp");
static const unsigned char s118[] = INCBIN_U8("src/overworld/entities/118.4bpp");
static const unsigned char s119[] = INCBIN_U8("src/overworld/entities/119.4bpp");
static const unsigned char s120[] = INCBIN_U8("src/overworld/entities/120.4bpp");
static const unsigned char s121[] = INCBIN_U8("src/overworld/entities/121.4bpp");
static const unsigned char ParaFlipping[] = INCBIN_U8("src/overworld/entities/para_flipping.4bpp");
static const unsigned char DoxFlipping[] = INCBIN_U8("src/overworld/entities/dox_flipping.4bpp");
static const unsigned char MediumRubble[] = INCBIN_U8("src/overworld/entities/medium_rubble.4bpp");
static const unsigned char SmallRubble[] = INCBIN_U8("src/overworld/entities/small_rubble.4bpp");
static const unsigned char BigRubble[] = INCBIN_U8("src/overworld/entities/big_rubble.4bpp");
static const unsigned char DoxWithMokuba[] = INCBIN_U8("src/overworld/entities/dox_with_mokuba.4bpp");
static const unsigned char s128[] = INCBIN_U8("src/overworld/entities/128.4bpp");
static const unsigned char BigFive[] = INCBIN_U8("src/overworld/entities/big_five.4bpp");
static const unsigned char Teddy[] = INCBIN_U8("src/overworld/entities/teddy.4bpp");
static const unsigned char s131[] = INCBIN_U8("src/overworld/entities/131.4bpp");
static const unsigned char s132[] = INCBIN_U8("src/overworld/entities/132.4bpp");
static const unsigned char s133[] = INCBIN_U8("src/overworld/entities/133.4bpp");
static const unsigned char s134[] = INCBIN_U8("src/overworld/entities/134.4bpp");
static const unsigned char s135[] = INCBIN_U8("src/overworld/entities/135.4bpp");
static const unsigned char s136[] = INCBIN_U8("src/overworld/entities/136.4bpp");
static const unsigned char s137[] = INCBIN_U8("src/overworld/entities/137.4bpp");
static const unsigned char s138[] = INCBIN_U8("src/overworld/entities/138.4bpp");
static const unsigned char Odion[] = INCBIN_U8("src/overworld/entities/odion.4bpp");
static const unsigned char FGD_Body[] = INCBIN_U8("src/overworld/entities/fgd_body.4bpp");
static const unsigned char FGD_Middle_Head[] = INCBIN_U8("src/overworld/entities/fgd_middle_head.4bpp");
static const unsigned char FGD_Tail[] = INCBIN_U8("src/overworld/entities/fgd_tail.4bpp");
static const unsigned char Fgd_Right_Heads[] = INCBIN_U8("src/overworld/entities/fgd_right_heads.4bpp");
static const unsigned char Fgd_Left_Heads[] = INCBIN_U8("src/overworld/entities/fgd_left_heads.4bpp");
static const unsigned char s145[] = INCBIN_U8("src/overworld/entities/145.4bpp");
static const unsigned char s146[] = INCBIN_U8("src/overworld/entities/146.4bpp");
static const unsigned char s147[] = INCBIN_U8("src/overworld/entities/147.4bpp");
static const unsigned char s148[] = INCBIN_U8("src/overworld/entities/148.4bpp");
static const unsigned char Butterfly[] = INCBIN_U8("src/overworld/entities/butterfly.4bpp");
static const unsigned char s150[] = INCBIN_U8("src/overworld/entities/150.4bpp");
static const unsigned char s151[] = INCBIN_U8("src/overworld/entities/151.4bpp");
static const unsigned char YugiWithMillenniumPuzzle[] = INCBIN_U8("src/overworld/entities/yugi_with_millennium_puzzle.4bpp");
const unsigned char ShadowTiles[] = INCBIN_U8("src/overworld/entities/shadow.4bpp");
static const unsigned char Unknown_82A902C[] = INCBIN_U8("src/overworld/entities/unknown_82A902C.4bpp");
const unsigned char ReactionBubbleTiles[] = INCBIN_U8("src/overworld/entities/reaction_bubbles.4bpp");

//TODO naming scheme: Palette (singular) or palettes since it's 4bpp?
const unsigned short gOverworldEntityPalettes[] = INCBIN_U16("src/overworld/entities/palette.gbapal");
static const unsigned short sFiller[] = {0, 0x7FFF, 0x7EB0, 0x6528, 0x43FF, 0x029F, 0x577, 0x8AA, 0, 0, 0, 0, 0, 0, 0, 0}; // TODO: is this part of palette^ ? (it's not used)

const unsigned char g82AD20C[] = {
  [SPRITE_YUGI_UNUSED] = 0,
  [SPRITE_YUGI] = 0,
  [SPRITE_ATEM] = 0,
  [SPRITE_SETO] = 0,
  [SPRITE_JOEY] = 1,
  [SPRITE_MARIK] = 0,
  [SPRITE_ISHIZU] = 1,
  [SPRITE_MAI] = 3,
  [SPRITE_GRANDPA_MUTO_UNUSED] = 0,
  [SPRITE_JOEY_UNUSED] = 0,
  [SPRITE_TEA] = 3,
  [SPRITE_GRANDPA_MUTO] = 5,
  [SPRITE_LUMIS] = 0,
  [SPRITE_UMBRA] = 0,
  [SPRITE_STRINGS] = 5,
  [SPRITE_SEEKER] = 0,
  [SPRITE_ARKANA] = 4,
  [SPRITE_ESPA] = 4,
  [SPRITE_WEEVIL] = 5,
  [SPRITE_REX] = 4,
  [SPRITE_MAKO] = 1,
  [SPRITE_BONZ] = 5,
  [SPRITE_BAKURA] = 2,
  [SPRITE_PARA] = 6,
  [SPRITE_DOX] = 6,
  [SPRITE_PLAYER] = 6,
  [SPRITE_NEO_GHOUL] = 0,
  [SPRITE_MIMIC_OF_DOOM] = 0,
  [SPRITE_PUPPETEER_OF_DOOM] = 0,
  [SPRITE_PANIK] = 0,
  [SPRITE_MILLENNIUM_GUARDIAN] = 6,
  [SPRITE_PEGASUS] = 4,
  [SPRITE_SHADI] = 0,
  [SPRITE_ROLAND] = 0,
  [SPRITE_ROBA_BROTHER_1] = 4,
  [SPRITE_ROBA_BROTHER_2] = 4,
  [SPRITE_BLUE_EYES_UNUSED] = 0,
  [SPRITE_SLIFER_UNUSED] = 0,
  [SPRITE_RA_UNUSED] = 0,
  [SPRITE_CHEVALIER] = 4,
  [SPRITE_FENG_LONG] = 1,
  [SPRITE_INVISIBLE] = 0,
  [SPRITE_TAKESHI] = 1,
  [SPRITE_RICH_FATHER] = 3,
  [SPRITE_RICH_MOTHER] = 2,
  [SPRITE_RICH_DAUGHTER] = 4,
  [SPRITE_DUEL_EXPRESS_CONDUCTOR] = 3,
  [SPRITE_RED_HAT] = 3,
  [SPRITE_ETSUKO] = 3,
  [SPRITE_TRISTAN] = 3,
  [SPRITE_SHIP_DEALER] = 6,
  [SPRITE_NIBBLES] = 1,
  [SPRITE_DOMINO_STATION_GUARD] = 0,
  [SPRITE_YELLOW_SCARF] = 1,
  [SPRITE_DUKE] = 0,
  [SPRITE_MOKUBA] = 1,
  [SPRITE_SERENITY] = 0,
  [SPRITE_LUCKY] = 0,
  [SPRITE_DAMIEN_DRACO] = 1,
  [SPRITE_STYLISH_HAIR] = 2,
  [SPRITE_RED_EYES_UNUSED] = 0,
  [SPRITE_FLAME_SWORDSMAN_UNUSED] = 0,
  [SPRITE_BLUE_JACKET] = 1,
  [SPRITE_BANDIT_KEITH] = 0,
  [SPRITE_LINT] = 1,
  [SPRITE_KAIBA_FAN] = 2,
  [SPRITE_JEAN_CLAUDE_MAGNUM] = 1,
  [SPRITE_RED_HAIR] = 4,
  [SPRITE_DUELIST_HATER] = 0,
  [SPRITE_TOURIST] = 5,
  [SPRITE_STRINGER] = 3,
  [SPRITE_RED_MOHAWK] = 4,
  [SPRITE_LOST_DUELIST] = 2,
  [SPRITE_AMBUSHER] = 3,
  [SPRITE_NON_DUELIST_PASSENGER] = 0,
  [SPRITE_NERVOUS_DUELIST] = 5,
  [SPRITE_ARROGANT_DUELIST] = 1,
  [SPRITE_INSECURE_DUELIST] = 0,
  [SPRITE_KAIBACORP_ADMIRER] = 6,
  [SPRITE_DOMINO_STATION_GUARD_2] = 0,
  [SPRITE_KAIBAS_BUTLER] = 3,
  [SPRITE_YELLOW_SHIRT] = 1,
  [SPRITE_KAIBA_COSPLAYER] = 0,
  [SPRITE_EGYPT_EXHIBITION_GUARD] = 0,
  [SPRITE_EGYPT_EXHIBITION_VISITOR] = 3,
  [SPRITE_CASINO_PLAYER] = 0,
  [SPRITE_RICH_HUSBAND] = 6,
  [SPRITE_RICHE_WIFE] = 0,
  [SPRITE_SERIOUS_ARCHEOLOGIST] = 5,
  [SPRITE_PLAYER_RUNNING] = 6,
  [SPRITE_YUGI_UNUSED_2] = 1,
  [SPRITE_ZERA_THE_MANT_UNUSED] = 0,
  [SPRITE_THE_LEGENDARY_FISHERMAN_UNUSED] = 0,
  [SPRITE_CHIEF_ARCHEOLOGIST] = 4,
  [SPRITE_FRIVOULOUS_ARCHEOLOGIST] = 5,
  [SPRITE_GIRL_ARCHEOLOGIST] = 4,
  [SPRITE_THOUGHTFUL_ARCHEOLOGIST] = 4,
  [SPRITE_PARADOX] = 6,
  [SPRITE_NOAH] = 2,
  [SPRITE_MONKEY_ROBOT] = 3,
  [SPRITE_REBECCA] = 3,
  [SPRITE_OLD_MAN] = 0,
  [SPRITE_OLD_WOMAN] = 4,
  [SPRITE_NIGHTMARE_PENGUIN] = 0,
  [SPRITE_DEEPSEA_WARRIOR] = 5,
  [SPRITE_ROBOTIC_KNIGHT] = 0,
  [SPRITE_JUDGE_MAN] = 1,
  [SPRITE_JINZO] = 4,
  [SPRITE_KAIBAMAN] = 0,
  [SPRITE_JOHNNY_STEPS] = 3,
  [SPRITE_ARTHUR] = 1,
  [SPRITE_KID_1] = 6,
  [SPRITE_KID_2] = 1,
  [SPRITE_VIDEO_CARD] = 0,
  [SPRITE_GREENDALE_ZOMPIRE] = 0,
  [SPRITE_MILLENNIUM_NECKLACE] = 6,
  [SPRITE_MILLENNIUM_ROD] = 6,
  [SPRITE_MILLENNIUM_PUZZLE] = 6,
  [SPRITE_MILLENNIUM_KEY] = 6,
  [SPRITE_MILLENNIUM_EYE] = 6,
  [SPRITE_MILLENNIUM_RING] = 6,
  [SPRITE_MILLENNIUM_SCALE] = 6,
  [SPRITE_PARA_FLIPPING] = 6,
  [SPRITE_DOX_FLIPPING] = 6,
  [SPRITE_MEDIUM_RUBBLE] = 6,
  [SPRITE_SMALL_RUBBLE] = 6,
  [SPRITE_BIG_RUBBLE] = 6,
  [SPRITE_DOX_WITH_MOKUBA] = 6,
  [SPRITE_ROBA_BROTHER_3] = 4,
  [SPRITE_BIG_FIVE] = 3,
  [SPRITE_TEDDY] = 5,
  [SPRITE_FORTUNE_TABLE] = 1,
  [SPRITE_RAFT] = 3,
  [SPRITE_BANANA] = 3,
  [SPRITE_MILLENNIUM_PUZZLE_PART_1] = 6,
  [SPRITE_MILLENNIUM_PUZZLE_PART_2] = 6,
  [SPRITE_MILLENNIUM_PUZZLE_PART_3] = 6,
  [SPRITE_HORIZONTAL_LOG] = 3,
  [SPRITE_VERTICAL_LOG] = 3,
  [SPRITE_ODION] = 0,
  [SPRITE_FGD_BODY] = 3,
  [SPRITE_FGD_MIDDLE_HEAD] = 3,
  [SPRITE_FGD_TAIL] = 3,
  [SPRITE_FGD_RIGHT_HEADS] = 6,
  [SPRITE_FGD_LEFT_HEADS] = 0,
  [SPRITE_FISH_1] = 6,
  [SPRITE_FISH_2] = 3,
  [SPRITE_FISH_3] = 3,
  [SPRITE_FISH_4] = 6,
  [SPRITE_BUTTERFLY] = 3,
  [SPRITE_KID_3] = 6,
  [SPRITE_KID_3_2] = 3,
  [SPRITE_YUGI_WITH_MILLENNIUM_PUZZLE] = 0
};

static const unsigned char sFiller2[17] = {0};

// TODO: create enum for reaction bubbles
const unsigned char g82AD2B6[] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  4,
  0,
  0,
  0,
  2,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
};

static const unsigned char Filler3[] = {0, 0}; //padding?

/*
const unsigned char * CONST_DATA gOverworldEntitySprites[] = {
  [SPRITE_YUGI_UNUSED] = YugiUnused,
  [SPRITE_YUGI] = Yugi,
  [SPRITE_ATEM] = Atem,
  [SPRITE_SETO] = Seto,
  [SPRITE_JOEY] = Joey,
  [SPRITE_MARIK] = Marik,
  [SPRITE_ISHIZU] = Ishizu,
  [SPRITE_MAI] = Mai,
  [SPRITE_GRANDPA_MUTO_UNUSED] = SolomonUnused_todo,
  [SPRITE_JOEY_UNUSED] = JoeyUnused_todo,
  [SPRITE_TEA] = Tea,
  [SPRITE_GRANDPA_MUTO] = Solomon,
  [SPRITE_LUMIS] = Lumis,
  [SPRITE_UMBRA] = Umbra,
  [SPRITE_STRINGS] = Strings,
  [SPRITE_SEEKER] = Seeker,
  [SPRITE_ARKANA] = Arkana,
  [SPRITE_ESPA] = Espa,
  [SPRITE_WEEVIL] = Weevil,
  [SPRITE_REX] = Rex,
  [SPRITE_MAKO] = Mako,
  [SPRITE_BONZ] = Bonz,
  [SPRITE_BAKURA] = Bakura,
  [SPRITE_PARA] = Para,
  [SPRITE_DOX] = Dox,
  [SPRITE_PLAYER] = Player,
  [SPRITE_NEO_GHOUL] = NeoGhoul,
  [SPRITE_MIMIC_OF_DOOM] = MimicOfDoom,
  [SPRITE_PUPPETEER_OF_DOOM] = PuppeteerOfDoom,
  [SPRITE_PANIK] = Panik,
  [SPRITE_MILLENNIUM_GUARDIAN] = MillenniumGuardian,
  [SPRITE_PEGASUS] = Pegasus,
  [SPRITE_SHADI] = Shadi,
  [SPRITE_ROLAND] = Roland,
  [SPRITE_ROBA_BROTHER_1] = EspaBiggerBrother_todo,
  [SPRITE_ROBA_BROTHER_2] = EspaLittleBrother_todo,
  [SPRITE_BLUE_EYES_UNUSED] = Blue_eyes_unused_todo,
  [SPRITE_SLIFER_UNUSED] = Slifer_todo,
  [SPRITE_RA_UNUSED] = Ra_todo,
  [SPRITE_CHEVALIER] = Chevalier,
  [SPRITE_FENG_LONG] = s40,
  [SPRITE_INVISIBLE] = Invisible,
  [SPRITE_TAKESHI] = Takeshi,
  [SPRITE_RICH_FATHER] = s43,
  [SPRITE_RICH_MOTHER] = s44,
  [SPRITE_RICH_DAUGHTER] = s45,
  [SPRITE_DUEL_EXPRESS_CONDUCTOR] = DuelExpressConductor,
  [SPRITE_RED_HAT] = s47,
  [SPRITE_ETSUKO] = s48,
  [SPRITE_TRISTAN] = Tristan,
  [SPRITE_SHIP_DEALER] = s50,
  [SPRITE_NIBBLES] = s51,
  [SPRITE_DOMINO_STATION_GUARD] = s52,
  [SPRITE_YELLOW_SCARF] = s53,
  [SPRITE_DUKE] = Duke,
  [SPRITE_MOKUBA] = Mokuba,
  [SPRITE_SERENITY] = Serenity,
  [SPRITE_LUCKY] = Lucky,
  [SPRITE_DAMIEN_DRACO] = s58,
  [SPRITE_STYLISH_HAIR] = s59,
  [SPRITE_RED_EYES_UNUSED] = s60,
  [SPRITE_FLAME_SWORDSMAN_UNUSED] = s61,
  [SPRITE_BLUE_JACKET] = s62,
  [SPRITE_BANDIT_KEITH] = BanditKeith,
  [SPRITE_LINT] = s64,
  [SPRITE_KAIBA_FAN] = s65,
  [SPRITE_JEAN_CLAUDE_MAGNUM] = JeanClaudeMagnum,
  [SPRITE_RED_HAIR] = s67,
  [SPRITE_DUELIST_HATER] = s68,
  [SPRITE_TOURIST] = s69,
  [SPRITE_STRINGER] = s70,
  [SPRITE_RED_MOHAWK] = s71,
  [SPRITE_LOST_DUELIST] = s72,
  [SPRITE_AMBUSHER] = s73,
  [SPRITE_NON_DUELIST_PASSENGER] = s74,
  [SPRITE_NERVOUS_DUELIST] = s75,
  [SPRITE_ARROGANT_DUELIST] = s76,
  [SPRITE_INSECURE_DUELIST] = s77,
  [SPRITE_KAIBACORP_ADMIRER] = s78,
  [SPRITE_DOMINO_STATION_GUARD_2] = s79,
  [SPRITE_KAIBAS_BUTLER] = s80,
  [SPRITE_YELLOW_SHIRT] = s81,
  [SPRITE_KAIBA_COSPLAYER] = s82,
  [SPRITE_EGYPT_EXHIBITION_GUARD] = s83,
  [SPRITE_EGYPT_EXHIBITION_VISITOR] = s84,
  [SPRITE_CASINO_PLAYER] = s85,
  [SPRITE_RICH_HUSBAND] = s86,
  [SPRITE_RICHE_WIFE] = s87,
  [SPRITE_SERIOUS_ARCHEOLOGIST] = s88,
  [SPRITE_PLAYER_RUNNING] = PlayerRunning,
  [SPRITE_YUGI_UNUSED_2] = s90,
  [SPRITE_ZERA_THE_MANT_UNUSED] = s91,
  [SPRITE_THE_LEGENDARY_FISHERMAN_UNUSED] = s92,
  [SPRITE_CHIEF_ARCHEOLOGIST] = s93,
  [SPRITE_FRIVOULOUS_ARCHEOLOGIST] = s94,
  [SPRITE_GIRL_ARCHEOLOGIST] = s95,
  [SPRITE_THOUGHTFUL_ARCHEOLOGIST] = s96,
  [SPRITE_PARADOX] = Paradox,
  [SPRITE_NOAH] = Noah,
  [SPRITE_MONKEY_ROBOT] = MonkeyRobot,
  [SPRITE_REBECCA] = Rebecca,
  [SPRITE_OLD_MAN] = s101,
  [SPRITE_OLD_WOMAN] = s102,
  [SPRITE_NIGHTMARE_PENGUIN] = NightmarePenguin,
  [SPRITE_DEEPSEA_WARRIOR] = DeepseaWarrior,
  [SPRITE_ROBOTIC_KNIGHT] = RoboticKnight,
  [SPRITE_JUDGE_MAN] = JudgeMan,
  [SPRITE_JINZO] = Jinzo,
  [SPRITE_KAIBAMAN] = Kaibaman,
  [SPRITE_JOHNNY_STEPS] = JohnnySteps,
  [SPRITE_ARTHUR] = Arthur,
  [SPRITE_KID_1] = s111,
  [SPRITE_KID_2] = s112,
  [SPRITE_VIDEO_CARD] = VideoCard,
  [SPRITE_GREENDALE_ZOMPIRE] = s114,
  [SPRITE_MILLENNIUM_NECKLACE] = s115,
  [SPRITE_MILLENNIUM_ROD] = s116,
  [SPRITE_MILLENNIUM_PUZZLE] = s117,
  [SPRITE_MILLENNIUM_KEY] = s118,
  [SPRITE_MILLENNIUM_EYE] = s119,
  [SPRITE_MILLENNIUM_RING] = s120,
  [SPRITE_MILLENNIUM_SCALE] = s121,
  [SPRITE_PARA_FLIPPING] = ParaFlipping,
  [SPRITE_DOX_FLIPPING] = DoxFlipping,
  [SPRITE_MEDIUM_RUBBLE] = MediumRubble,
  [SPRITE_SMALL_RUBBLE] = SmallRubble,
  [SPRITE_BIG_RUBBLE] = BigRubble,
  [SPRITE_DOX_WITH_MOKUBA] = DoxWithMokuba,
  [SPRITE_ROBA_BROTHER_3] = s128,
  [SPRITE_BIG_FIVE] = BigFive,
  [SPRITE_TEDDY] = Teddy,
  [SPRITE_FORTUNE_TABLE] = s131,
  [SPRITE_RAFT] = s132,
  [SPRITE_BANANA] = s133,
  [SPRITE_MILLENNIUM_PUZZLE_PART_1] = s134,
  [SPRITE_MILLENNIUM_PUZZLE_PART_2] = s135,
  [SPRITE_MILLENNIUM_PUZZLE_PART_3] = s136,
  [SPRITE_HORIZONTAL_LOG] = s137,
  [SPRITE_VERTICAL_LOG] = s138,
  [SPRITE_ODION] = Odion,
  [SPRITE_FGD_BODY] = FGD_Body,
  [SPRITE_FGD_MIDDLE_HEAD] = FGD_MiddleHead,
  [SPRITE_FGD_TAIL] = FGD_Tail,
  [SPRITE_FGD_RIGHT_HEADS] = Fgd_Right_Heads,
  [SPRITE_FGD_LEFT_HEADS] = Fgd_Left_Heads,
  [SPRITE_FISH_1] = s145,
  [SPRITE_FISH_2] = s146,
  [SPRITE_FISH_3] = s147,
  [SPRITE_FISH_4] = s148,
  [SPRITE_BUTTERFLY] = Butterfly,
  [SPRITE_KID_3] = s150,
  [SPRITE_KID_3_2] = s151,
  [SPRITE_YUGI_WITH_MILLENNIUM_PUZZLE] = sYugiWithMillenniumPuzzle
};
*/
