#ifndef GUARD_AI_ACTIONS_H
#define GUARD_AI_ACTIONS_H

#define AI_ACTION_1_TRIBUTE_SUMMON              3
#define AI_ACTION_2_TRIBUTE_SUMMON              4
#define AI_ACTION_3_TRIBUTE_SUMMON              11
#define AI_ACTION_PERM_CARD_1_TRIBUTE_SUMMON    26
#define AI_ACTION_PERM_CARD_2_TRIBUTE_SUMMON    27
#define AI_ACTION_PERM_CARD_3_TRIBUTE_SUMMON    28
#define AI_ACTION_DIRECT_ATTACK_NO_TRAP         7
#define AI_ACTION_ATTACK_FACE_UP_NO_TRAP        8
#define AI_ACTION_DIRECT_ATTACK_WITH_TRAP       9
#define AI_ACTION_ATTACK_FACE_UP_WITH_TRAP      10
#define AI_ACTION_ATTACK_FACE_DOWN_NO_TRAP      12
#define AI_ACTION_ATTACK_FACE_DOWN_WITH_TRAP    13
#define AI_ACTION_MONSTER_EFFECT                23
#define AI_ACTION_PERM_CARD_DIRECT_ATTACK_NO_TRAP      41
#define AI_ACTION_PERM_CARD_ATTACK_FACE_UP_NO_TRAP     42
#define AI_ACTION_PERM_CARD_DIRECT_ATTACK_WITH_TRAP    43
#define AI_ACTION_PERM_CARD_ATTACK_FACE_UP_WITH_TRAP   44
#define AI_ACTION_PERM_CARD_ATTACK_FACE_DOWN_NO_TRAP   45
#define AI_ACTION_PERM_CARD_ATTACK_FACE_DOWN_WITH_TRAP 46

u8 IsAiTributeSummonAction(u16 action);
u8 IsAiDirectAttackVoicingAction(u16 action);

void TryPlayCustomOpponentAttackVoice(void);

#endif // GUARD_AI_ACTIONS_H
