#ifndef GUARD_BOND_BETWEEN_TEACHER_AND_STUDENT_H
#define GUARD_BOND_BETWEEN_TEACHER_AND_STUDENT_H

#include "gba/types.h"

u8 CanActivateBOND_BETWEEN_TEACHER_AND_STUDENT(void);

#endif /* GUARD_BOND_BETWEEN_TEACHER_AND_STUDENT_H */
