#ifndef GUARD_OVERWORLD_H
#define GUARD_OVERWORLD_H

#define OVERWORLD_FLAG_EXIT_OVERWORLD 1
#define OVERWORLD_FLAG_MAP_TRANSITION 2
#define OVERWORLD_FLAG_WORLD_MAP_TRANSITION 4

//TODO: ObjectDirection?
enum Direction {
  DIRECTION_DOWN = 0,
  DIRECTION_LEFT = 1,
  DIRECTION_UP = 2,
  DIRECTION_RIGHT = 3
};

enum OverworldLocation {
  LOCATION_CLOCK_TOWER_SQUARE_NORTHWEST = 0,
  LOCATION_CLOCK_TOWER_SQUARE_NORTH = 1,
  LOCATION_CLOCK_TOWER_SQUARE_NORTHEAST = 2,
  LOCATION_CLOCK_TOWER_SQUARE_SOUTHEAST = 3,
  LOCATION_CLOCK_TOWER_SQUARE_SOUTH = 4,
  LOCATION_CLOCK_TOWER_SQUARE_SOUTHWEST = 5,
  LOCATION_CARD_SHOP_OUTSIDE = 6,
  LOCATION_CARD_SHOP_INSIDE = 7,
  LOCATION_PLAYER_HOUSE_OUTSIDE = 8,
  LOCATION_PLAYER_HOUSE_INSIDE = 9,
  LOCATION_CLOCK_TOWER_SQUARE_BACK_ALLEY_NORTH = 10,
  LOCATION_CLOCK_TOWER_SQUARE_BACK_ALLEY_NORTH_EAST = 11,
  LOCATION_KAIBACORP = 12,
  LOCATION_DUEL_MACHINE = 13,
  LOCATION_DOMINO_STATION_TURNSTILES = 14,
  LOCATION_DOMINO_STATION_TRAIN_STATION = 15,
  LOCATION_DUEL_EXPRESS_CARRIAGE_RIGHT = 16,
  LOCATION_DUEL_EXPRESS_CARRIAGE_MIDDLE = 17,
  LOCATION_DUEL_EXPRESS_CARRIAGE_LEFT = 18,
  LOCATION_ITALY_CATACOMBS_MIDDLE = 19,
  LOCATION_EGYPT_EXHIBITION_TRAIN_STATION = 20,
  LOCATION_EGYPT_EXHIBITION_TURNSTILES = 21,
  LOCATION_EGYPT_EXHIBITION_ARTWORK = 22,
  LOCATION_EGYPT_EXHIBITION_MILLENNIUM_GUARDIAN = 23,
  LOCATION_DOMINO_PIER_DOCKS = 24,
  LOCATION_DOMINO_PIER_CASINO_LEFT_ROOM = 25,
  LOCATION_DOMINO_PIER_CASINO_MAIN_ROOM = 26,
  LOCATION_DOMINO_PIER_MILLENNIUM_GUARDIAN = 27,
  LOCATION_ITALY_CATACOMBS_LEFT = 28,
  LOCATION_ITALY_CATACOMBS_RIGHT = 29,
  LOCATION_ITALY_MILLENNIUM_GUARDIAN = 30,
  LOCATION_CHINA_GREAT_WALL_ENTRANCE = 31,
  LOCATION_CHINA_GREAT_WALL = 32,
  LOCATION_CHINA_GREAT_WALL_MILLENNIUM_GUARDIAN = 33,
  LOCATION_CANADA_RUINS_OUTSIDE = 34,
  LOCATION_CANADA_RUINS_INSIDE = 35,
  LOCATION_CANADA_RUINS_MILLENNIUM_GUARDIAN = 36,
  LOCATION_GALAPAGOS_BEACH = 37,
  LOCATION_GALAPAGOS_FOREST = 38,
  LOCATION_GALAPAGOS_TEMPLE = 39,
  LOCATION_PEGASUS_ISLAND_CABLE_CAR_BOTTOM_OUTSIDE = 40,
  LOCATION_PEGASUS_ISLAND_CABLE_CAR_INSIDE = 41,
  LOCATION_PEGASUS_ISLAND_CABLE_CAR_TOP_OUTSIDE = 42,
  LOCATION_PEGASUS_ISLAND_DUNGEON_ENTRANCE = 43,
  LOCATION_PEGASUS_ISLAND_DUNGEON_LAVA_ROOM_SOUTH = 44,
  LOCATION_PEGASUS_ISLAND_DUNGEON_CLIFF = 45,
  LOCATION_PEGASUS_ISLAND_DUNGEON_LAVA_ROOM_NORTH = 46,
  LOCATION_PEGASUS_ISLAND_DUNGEON_BRIDGE = 47,
  LOCATION_PEGASUS_ISLAND_DUNGEON_STAIRCASE = 48,
  LOCATION_PEGASUS_ISLAND_DUNGEON_RUINS = 49,
  LOCATION_PEGASUS_CASTLE_OUTSIDE = 50,
  LOCATION_PEGASUS_CASTLE_HALLWAY = 51,
  LOCATION_PEGASUS_CASTLE_LEFT_ROOM = 52,
  LOCATION_PEGASUS_CASTLE_RIGHT_ROOM = 53,
  LOCATION_PEGASUS_CASTLE_DUEL_ROOM = 54,
  LOCATION_PEGASUS_CASTLE_RESHEF_TABLET_ROOM = 55,
  LOCATION_HALL_OF_ETERNITY = 56,
  LOCATION_KAIBA_LAND = 57,
  LOCATION_CLOCK_TOWER_SQUARE_NORTH_WEST2_TODO = 58,
  LOCATION_EGYPT = 59,
  LOCATION_EGYPT_MARIK_ROOM = 60
};

// TODO: OVERWORLD_ENTITY_SPRITE?
enum OverworldEntitySprite {
  SPRITE_NONE = -1,
  SPRITE_YUGI_UNUSED,
  SPRITE_YUGI,
  SPRITE_ATEM,
  SPRITE_SETO,
  SPRITE_JOEY,
  SPRITE_MARIK,
  SPRITE_ISHIZU,
  SPRITE_MAI,
  SPRITE_GRANDPA_MUTO_UNUSED,
  SPRITE_JOEY_UNUSED,
  SPRITE_TEA,
  SPRITE_GRANDPA_MUTO,
  SPRITE_LUMIS,
  SPRITE_UMBRA,
  SPRITE_STRINGS,
  SPRITE_SEEKER,
  SPRITE_ARKANA,
  SPRITE_ESPA,
  SPRITE_WEEVIL,
  SPRITE_REX,
  SPRITE_MAKO,
  SPRITE_BONZ,
  SPRITE_BAKURA,
  SPRITE_PARA,
  SPRITE_DOX,
  SPRITE_PLAYER,
  SPRITE_NEO_GHOUL,
  SPRITE_MIMIC_OF_DOOM,
  SPRITE_PUPPETEER_OF_DOOM,
  SPRITE_PANIK,
  SPRITE_MILLENNIUM_GUARDIAN,
  SPRITE_PEGASUS,
  SPRITE_SHADI,
  SPRITE_ROLAND,
  SPRITE_ROBA_BROTHER_1,
  SPRITE_ROBA_BROTHER_2,
  SPRITE_BLUE_EYES_UNUSED,
  SPRITE_SLIFER_UNUSED,
  SPRITE_RA_UNUSED,
  SPRITE_CHEVALIER,
  SPRITE_FENG_LONG,
  SPRITE_INVISIBLE,
  SPRITE_TAKESHI,
  SPRITE_RICH_FATHER,
  SPRITE_RICH_MOTHER,
  SPRITE_RICH_DAUGHTER,
  SPRITE_DUEL_EXPRESS_CONDUCTOR,
  SPRITE_RED_HAT,
  SPRITE_ETSUKO,
  SPRITE_TRISTAN,
  SPRITE_SHIP_DEALER,
  SPRITE_NIBBLES,
  SPRITE_DOMINO_STATION_GUARD,
  SPRITE_YELLOW_SCARF,
  SPRITE_DUKE,
  SPRITE_MOKUBA,
  SPRITE_SERENITY,
  SPRITE_LUCKY,
  SPRITE_DAMIEN_DRACO,
  SPRITE_STYLISH_HAIR,
  SPRITE_RED_EYES_UNUSED,
  SPRITE_FLAME_SWORDSMAN_UNUSED,
  SPRITE_BLUE_JACKET,
  SPRITE_BANDIT_KEITH,
  SPRITE_LINT,
  SPRITE_KAIBA_FAN,
  SPRITE_JEAN_CLAUDE_MAGNUM,
  SPRITE_RED_HAIR,
  SPRITE_DUELIST_HATER,
  SPRITE_TOURIST,
  SPRITE_STRINGER,
  SPRITE_RED_MOHAWK, //Mohawk red hair guy
  SPRITE_LOST_DUELIST,
  SPRITE_AMBUSHER,
  SPRITE_NON_DUELIST_PASSENGER,
  SPRITE_NERVOUS_DUELIST,
  SPRITE_ARROGANT_DUELIST,
  SPRITE_INSECURE_DUELIST,
  SPRITE_KAIBACORP_ADMIRER,
  SPRITE_DOMINO_STATION_GUARD_2,
  SPRITE_KAIBAS_BUTLER,
  SPRITE_YELLOW_SHIRT,
  SPRITE_KAIBA_COSPLAYER, //seto wannabe
  SPRITE_EGYPT_EXHIBITION_GUARD,
  SPRITE_EGYPT_EXHIBITION_VISITOR,
  SPRITE_CASINO_PLAYER,
  SPRITE_RICH_HUSBAND,
  SPRITE_RICHE_WIFE,
  SPRITE_SERIOUS_ARCHEOLOGIST,
  SPRITE_PLAYER_RUNNING,
  SPRITE_YUGI_UNUSED_2,
  SPRITE_ZERA_THE_MANT_UNUSED,
  SPRITE_THE_LEGENDARY_FISHERMAN_UNUSED,
  SPRITE_CHIEF_ARCHEOLOGIST,
  SPRITE_FRIVOULOUS_ARCHEOLOGIST,
  SPRITE_GIRL_ARCHEOLOGIST,
  SPRITE_THOUGHTFUL_ARCHEOLOGIST,
  SPRITE_PARADOX,
  SPRITE_NOAH,
  SPRITE_MONKEY_ROBOT,
  SPRITE_REBECCA,
  SPRITE_OLD_MAN,
  SPRITE_OLD_WOMAN,
  SPRITE_NIGHTMARE_PENGUIN,
  SPRITE_DEEPSEA_WARRIOR,
  SPRITE_ROBOTIC_KNIGHT,
  SPRITE_JUDGE_MAN,
  SPRITE_JINZO,
  SPRITE_KAIBAMAN,
  SPRITE_JOHNNY_STEPS,
  SPRITE_ARTHUR,
  SPRITE_KID_1,
  SPRITE_KID_2,
  SPRITE_VIDEO_CARD,
  SPRITE_GREENDALE_ZOMPIRE,
  SPRITE_MILLENNIUM_NECKLACE,
  SPRITE_MILLENNIUM_ROD,
  SPRITE_MILLENNIUM_PUZZLE,
  SPRITE_MILLENNIUM_KEY,
  SPRITE_MILLENNIUM_EYE,
  SPRITE_MILLENNIUM_RING,
  SPRITE_MILLENNIUM_SCALE,
  SPRITE_PARA_FLIPPING,
  SPRITE_DOX_FLIPPING,
  SPRITE_MEDIUM_RUBBLE,
  SPRITE_SMALL_RUBBLE,
  SPRITE_BIG_RUBBLE,
  SPRITE_DOX_WITH_MOKUBA,
  SPRITE_ROBA_BROTHER_3,
  SPRITE_BIG_FIVE,
  SPRITE_TEDDY,
  SPRITE_FORTUNE_TABLE,
  SPRITE_RAFT,
  SPRITE_BANANA,
  SPRITE_MILLENNIUM_PUZZLE_PART_1,
  SPRITE_MILLENNIUM_PUZZLE_PART_2,
  SPRITE_MILLENNIUM_PUZZLE_PART_3,
  SPRITE_HORIZONTAL_LOG,
  SPRITE_VERTICAL_LOG,
  SPRITE_ODION,
  SPRITE_FGD_BODY,
  SPRITE_FGD_MIDDLE_HEAD,
  SPRITE_FGD_TAIL,
  SPRITE_FGD_RIGHT_HEADS,
  SPRITE_FGD_LEFT_HEADS,
  SPRITE_FISH_1,
  SPRITE_FISH_2,
  SPRITE_FISH_3,
  SPRITE_FISH_4,
  SPRITE_BUTTERFLY,
  SPRITE_KID_3,
  SPRITE_KID_3_2,
  SPRITE_YUGI_WITH_MILLENNIUM_PUZZLE
};

enum PortraitPosition {
  PORTRAIT_POSITION_LEFT,
  PORTRAIT_POSITION_RIGHT,
  PORTRAIT_POSITION_OFF_SCREEN,
  PORTRAIT_POSITION_AUTO = 8
};

enum Portrait {
  PORTRAIT_NONE = 0,
  PORTRAIT_YUGI = 1,
  PORTRAIT_ATEM = 2,
  PORTRAIT_SETO = 3,
  PORTRAIT_JOEY = 4,
  PORTRAIT_SOL_CHEVELSKY = 5,
  PORTRAIT_MAI = 6,
  PORTRAIT_TEA = 7,
  PORTRAIT_SOLOMON = 8,
  PORTRAIT_TRISTAN = 9,
  PORTRAIT_MOKUBA = 10,
  PORTRAIT_REX = 11,
  PORTRAIT_MAKO = 12,
  PORTRAIT_WEEVIL = 13,
  PORTRAIT_ESPA_ROBA = 14,
  PORTRAIT_BONZ = 15,
  PORTRAIT_ISHIZU = 16,
  PORTRAIT_SHADI = 17,
  PORTRAIT_MIMIC_OF_DOOM = 18,
  PORTRAIT_PANICK = 19,
  PORTRAIT_BANDIT_KEITH = 20,
  PORTRAIT_STRINGS = 21,
  PORTRAIT_SEEKER = 22,
  PORTRAIT_ARCANA = 23,
  PORTRAIT_PARA = 24,
  PORTRAIT_DOX = 25,
  PORTRAIT_LUMIS = 26,
  PORTRAIT_UMBRA = 27,
  PORTRAIT_PUPPETEER_OF_DOOM = 28,
  PORTRAIT_JEAN_CLAUDE_MAGNUM = 29,
  PORTRAIT_ROLAND = 30,
  PORTRAIT_DUKE = 31,
  PORTRAIT_SERENITY = 32,
  PORTRAIT_DARK_MARIK = 33,
  PORTRAIT_DARK_BAKURA = 34,
  PORTRAIT_PARADOX = 35,
  PORTRAIT_NOAH = 36,
  PORTRAIT_DARK_JOEY = 37,
  PORTRAIT_ROBOT_MOkNEY = 38,
  PORTRAIT_REBECCA = 39,
  PORTRAIT_TEDDY = 40,
  PORTRAIT_NIGHTMARE_PENGUIN = 41,
  PORTRAIT_DEEPSEA_WARRIOR = 42,
  PORTRAIT_ROBOTIC_KNIGHT = 43,
  PORTRAIT_JINZO = 44,
  PORTRAIT_JUDGE_MAN = 45,
  PORTRAIT_MILLENIUM_GUADIAN = 46,
  PORTRAIT_KAIBAMAN = 47,
  PORTRAIT_MARIK = 48,
  PORTRAIT_NEO_GHOUL = 49,
  PORTRAIT_CHEVALIER = 50,
  PORTRAIT_ODION = 51,
};

enum Expressions {
  EXPRESSION_NEUTRAL = 0,

  EXPRESSION_YUGI_HAPPY = 1,
  EXPRESSION_YUGI_SAD = 3,
  EXPRESSION_YUGI_SURPRISED = 6,

  EXPRESSION_YAMI_YUGI_HAPPY = 1,
  EXPRESSION_YAMI_YUGI_ANGRY = 2,
  
  EXPRESSION_KAIBA_HAPPY = 1,
  EXPRESSION_KAIBA_ANGRY = 2,
  EXPRESSION_KAIBA_SAD = 3,
  EXPRESSION_KAIBA_TEETH_GRITTED = 5,
  EXPRESSION_KAIBA_SURPRISED = 6,

  EXPRESSION_JOEY_ANGRY = 2,
  EXPRESSION_JOEY_SAD = 3,
  EXPRESSION_JOEY_TEETH_GRITTED = 5,
  EXPRESSION_JOEY_SWEATDROP = 7,

  EXPRESSION_SOL_CHEVALSKY_HAPPY = 1,
  EXPRESSION_SOL_CHEVALSKY_SAD = 3,
  EXPRESSION_SOL_CHEVALSKY_DEFEATED = 4,
  EXPRESSION_SOL_CHEVALSKY_TEETH_GRITTED = 5,
  EXPRESSION_SOL_CHEVALSKY_SURPRISED = 6,

  EXPRESSION_MAI_ANGRY = 2,
  EXPRESSION_MAI_SWEATDROP = 7,

  EXPRESSION_TEA_SAD = 3,
  EXPRESSION_TEA_SURPRISED = 6,
  EXPRESSION_TEA_SWEATDROP = 7,

  EXPRESSION_TRISTAN_HAPPY = 1,
  EXPRESSION_TRISTAN_ANGRY = 2,
  EXPRESSION_TRISTAN_DEFEATED = 4,
  EXPRESSION_TRISTAN_TEETH_GRITTED = 5,
  EXPRESSION_TRISTAN_SURPRISED = 6,

  EXPRESSION_MOKUBA_ANGRY = 2,
  EXPRESSION_MOKUBA_SAD = 3,
  EXPRESSION_MOKUBA_SURPRISED = 6,
  EXPRESSION_MOKUBA_POSSESSED = 8,

  EXPRESSION_REX_ANGRY = 2,
  EXPRESSION_REX_SURPRISED = 6,

  EXPRESSION_MAKO_HAPPY = 1,
  EXPRESSION_MAKO_SWEATDROP = 7,

  EXPRESSION_WEEVIL_HAPPY = 1,

  EXPRESSION_ESPA_ROBA_ANGRY = 2,
  EXPRESSION_ESPA_ROBA_SWEATDROP = 7,
  EXPRESSION_ESPA_ROBA_EYES_CLOSED = 9,

  EXPRESSION_ISHIZU_HAPPY = 1,
  EXPRESSION_ISHIZU_SURPRISED = 6,

  EXPRESSION_MIMIC_OF_DOOM_DEFEATED = 4,

  EXPRESSION_PANIK_DEFEATED = 4,

  EXPRESSION_BANDIT_KEITH_DEFEATED = 4,
  EXPRESSION_BANDIT_KEITH_SURPRISED = 6,
  EXPRESSION_BANDIT_KEITH_POSSESSED = 8,

  EXPRESSION_SEEKER_DEFEATED = 4,

  EXPRESSION_ARKANA_DEFEATED = 4,
  EXPRESSION_ARKANA_SURPRISED = 6,

  EXPRESSION_PARA_HAPPY = 1,
  EXPRESSION_PARA_DEFEATED = 4,

  EXPRESSION_DOX_HAPPY = 1,
  EXPRESSION_DOX_DEFEATED = 4,

  EXPRESSION_LUMIS_DEFEATED = 4,

  EXPRESSION_JEAN_CLAUDE_MAGNUM_SAD = 3,

  EXPRESSION_DUKE_SAD = 3,
  EXPRESSION_DUKE_TEETH_GRITTED = 5,

  EXPRESSION_SERENITY_ANGRY = 2,
  EXPRESSION_SERENITY_SAD = 3,
  EXPRESSION_SERENITY_SURPRISED = 6,
};

enum EventFlags {
  EVENT_FLAG_DUEL_EXPRESS_TOURNAMENT_STARTED = 0,
  EVENT_FLAG_DEFEATED_YELLOW_SCARF = 1,
  EVENT_FLAG_DEFEATED_DAMIEN_DRACO = 2,
  EVENT_FLAG_DEFEATED_TRAIN_GUARD = 3,
  EVENT_FLAG_DEFEATED_PANIK = 4,
  EVENT_FLAG_DEFEATED_RICH_FATHER = 5,
  EVENT_FLAG_DEFEATED_RICH_DAUGHTER = 6,
  EVENT_FLAG_UNUSED_7 = 7,
  EVENT_FLAG_SAW_INTRO_CUTSCENE = 8, // from when Joey talks about his deck to when the player gains control of the protagonist
  EVENT_FLAG_TEA_LEFT_FOR_THE_SHOP = 9,
  EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD = 10,
  EVENT_FLAG_SAW_PANIK_ENTER_DOMINO_STATION = 11,
  EVENT_FLAG_INTERACTED_WITH_YELLOW_SCARF = 12,
  EVENT_FLAG_INTERACTED_WITH_DAMIEN_DRACO = 13,
  EVENT_FLAG_INTERACTED_WITH_CONDUCTOR = 14,
  EVENT_FLAG_DEFEATED_MAI = 15,
  EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN1 = 16,
  EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN2 = 17,
  EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN3 = 18,
  EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN4 = 19,
  EVENT_FLAG_DEFEATED_MILLENNIUM_GUARDIAN5 = 20,
  EVENT_FLAG_DEFEATED_MIMIC_OF_DOOM = 21,
  EVENT_FLAG_TRISTAN_AND_DUKE_WENT_TO_SEE_MAI = 22,
  EVENT_FLAG_SAW_TAKESHI_BRAG = 23,
  EVENT_FLAG_DEFEATED_TAKESHI = 24,
  EVENT_FLAG_SAW_PANIK_ENTER_EGYPT_EXHIBITION = 25,
  EVENT_FLAG_UNUSED_26 = 26,
  EVENT_FLAG_DEFEATED_RED_HAT = 27,
  EVENT_FLAG_DEFEATED_STYLISH_HAIR = 28,
  EVENT_FLAG_DEFEATED_BLUE_JACKET = 29,
  EVENT_FLAG_DEFEATED_LINT = 30,
  EVENT_FLAG_DEFEATED_KAIBA_FAN = 31,
  EVENT_FLAG_DEFEATED_RED_HAIR = 32,
  EVENT_FLAG_DEFEATED_TOURIST = 33,
  EVENT_FLAG_DEFEATED_STRINGER = 34,
  EVENT_FLAG_DEFEATED_RED_MOHAWK = 35,
  EVENT_FLAG_DEFEATED_PUPPETEER_OF_DOOM = 36,
  EVENT_FLAG_DEFEATED_LOST_DUELIST = 37,
  EVENT_FLAG_DEFEATED_AMBUSHER = 38,
  EVENT_FLAG_DEFEATED_ROLAND = 39,
  EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM = 40,
  EVENT_FLAG_DEFEATED_RICH_WIFE = 41,
  EVENT_FLAG_SAW_JEAN_CLAUDE_MAGNUM_PROPOSE = 42,
  EVENT_FLAG_SAW_OPENING_CUTSCENE = 43, // from right after the naming screen to just before Joey talks about his deck
  EVENT_FLAG_RICH_SPOUSES_MOVED_OUT_OF_THE_WAY = 44,
  EVENT_FLAG_BROUGHT_MILLENNIUM_KEY_TO_ISHIZU = 45,
  EVENT_FLAG_DEFEATED_MOKUBA = 46,
  EVENT_FLAG_DEFEATED_NERVOUS_DUELIST = 47,
  EVENT_FLAG_DEFEATED_ARROGANT_DUELIST = 48,
  EVENT_FLAG_DEFEATED_INSECURE_DUELIST = 49,
  EVENT_FLAG_DEFEATED_KAIBA_CORP_ADMIRER = 50,
  EVENT_FLAG_DEFEATED_DOMINO_STATION_GUARD2 = 51,
  EVENT_FLAG_DEFEATED_BONZ = 52,
  EVENT_FLAG_BONZ_SAID_THERE_IS_A_HIDDEN_CHAMBER = 53,
  EVENT_FLAG_BONZ_MOVED_OUT_OF_THE_WAY = 54,
  EVENT_FLAG_DEFEATED_KAIBAS_BUTTLER = 55,
  EVENT_FLAG_DEFEATED_KAIBAS_BUTTLER2 = 56,
  EVENT_FLAG_BROUGHT_MILLENNIUM_RING_TO_ISHIZU = 57,
  EVENT_FLAG_TALKED_TO_PARA = 58,
  EVENT_FLAG_TALKED_TO_DOX = 59,
  EVENT_FLAG_JOEY_FOUND_PARA_AND_DOX_SUSPICIOUS = 60,
  EVENT_FLAG_DEFEATED_PARA_AND_DOX = 61,
  EVENT_FLAG_SAW_TRISTAN_AND_DUKE_LEAVING_ON_A_TRAINING_QUEST = 62,
  EVENT_FLAG_SAW_TRISTAN_AND_DUKE_ENTER_THE_DUEL_MACHINE_ROOM = 63,
  EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DUELING_THE_DUEL_MACHINE = 64,
  EVENT_FLAG_UNLOCKED_MONKEY_ROBOT_SIDEQUEST = 65,
  EVENT_FLAG_DEFEATED_SERIOUS_ARCHEOLOGIST = 66,
  EVENT_FLAG_TALKED_TO_CHIEF_ARCHEOLOGIST = 67,
  EVENT_FLAG_DEFEATED_FRIVOLOUS_ARCHEOLOGIST = 68,
  EVENT_FLAG_DEFEATED_REX = 69,
  EVENT_FLAG_TALKED_TO_ISHIZU_AFTER_WATCHING_THE_KAIBAMAN_SHOW = 70,
  EVENT_FLAG_BROUGHT_MILLENNIUM_ROD_TO_ISHIZU = 71,
  EVENT_FLAG_SAW_CAVE_EARTHQUAKE = 72,
  EVENT_FLAG_TALKED_TO_MAKO = 73,
  EVENT_FLAG_SAW_MAKO_TALK_TO_HIMSELF = 74,
  EVENT_FLAG_DEFEATED_WEEVIL = 75,
  EVENT_FLAG_SAW_WEEVIL_TALK_TO_HIMSELF = 76,
  EVENT_FLAG_ISHIZU_IS_WAITING_FOR_KAIBA = 77,
  EVENT_FLAG_NEO_GHOULS_ATTACKED = 78,
  EVENT_FLAG_KAIBA_WENT_TO_SEE_ISHIZU = 79,
  EVENT_FLAG_DEFEATED_KAIBA_FAN_GHOUL = 80,
  EVENT_FLAG_DEFEATED_RED_HAIR_GHOUL = 81,
  EVENT_FLAG_DEFEATED_ARKANA = 82,
  EVENT_FLAG_DEFEATED_BONZ_GHOUL = 83,
  EVENT_FLAG_DEFEATED_REX_GHOULS = 84,
  EVENT_FLAG_DEFEATED_LUMIS_AND_UMBRA = 85,
  EVENT_FLAG_DEFEATED_STRINGS = 86,
  EVENT_FLAG_SCARED_DUELIST_HATER = 87,
  EVENT_FLAG_SCARED_LOST_DUELIST = 88,
  EVENT_FLAG_SCARED_AMBUSHER = 89,
  EVENT_FLAG_DEFEATED_KAIBA_COSPLAYER = 90,
  EVENT_FLAG_DEFEATED_DAMIEN_DRACO2 = 91,
  EVENT_FLAG_TAKESHI_MOVED_OUT_OF_THE_WAY = 92,
  EVENT_FLAG_SAW_STRINGS_MAKING_MAKO_UNCOMFORTABLE = 93,
  EVENT_FLAG_SAW_KAIBA_AT_EGYPT_EXHIBITION = 94,
  EVENT_FLAG_DEFEATED_SEEKER = 95,
  EVENT_FLAG_FOUND_ALL_ALLIES = 96,
  EVENT_FLAG_DEFEATED_DOMINO_STATION_GHOUL = 97,
  EVENT_FLAG_ESPA_ROBA_SAID_ISHIZU_IS_AT_THE_EGYPT_EXHIBITION = 98,
  EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL1 = 99,
  EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL2 = 100,
  EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL3 = 101,
  EVENT_FLAG_SAW_TRISTAN_AND_DUKE_DRIVE_AWAY_A_GHOUL = 102,
  EVENT_FLAG_SAW_TAKESHI_GIVE_HIS_CARDS_TO_A_GHOUL = 103,
  EVENT_FLAG_SCARED_TAKESHI = 104,
  EVENT_FLAG_SAW_KAIBA_DEFEAT_A_GHOUL = 105,
  EVENT_FLAG_KAIBA_MOVED_OUT_OF_THE_WAY = 106,
  EVENT_FLAG_DEFEATED_BANDIT_KEITH = 107,
  EVENT_FLAG_SAW_MOKUBA_GET_KIDNAPPED = 108,
  EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL4 = 109,
  EVENT_FLAG_DEFEATED_GAUNTLET_GHOUL5 = 110,
  EVENT_FLAG_DEFEATED_ESPA_ROBA2 = 111,
  EVENT_FLAG_ESPA_ROBA_THANKED_YOU_FOR_SAVING_ISHIZU = 112,
  EVENT_FLAG_DEFEATED_RED_HAT2 = 113,
  EVENT_FLAG_DEFEATED_STYLISH_HAIR2 = 114,
  EVENT_FLAG_WEEVIL_LEFT_CLOCK_TOWER_SQUARE = 115,
  EVENT_FLAG_DEFEATED_BLUE_JACKET2 = 116,
  EVENT_FLAG_DEFEATED_LINT2 = 117,
  EVENT_FLAG_MAI_LEFT_CLOCK_TOWER_SQUARE = 118,
  EVENT_FLAG_SCARED_SHIP_DEALER = 119,
  EVENT_FLAG_BONZ_LEFT_CLOCK_TOWER_SQUARE = 120,
  EVENT_FLAG_DEFEATED_STRINGER2 = 121,
  EVENT_FLAG_DEFEATED_RED_MOHAWK2 = 122,
  EVENT_FLAG_MAKO_LEFT_CLOCK_TOWER_SQUARE = 123,
  EVENT_FLAG_DEFEATED_RED_HAIR2 = 124,
  EVENT_FLAG_REX_LEFT_CLOCK_TOWER_SQUARE = 125,
  EVENT_FLAG_TOLD_TEA_YOU_WILL_GO_FACE_PEGASUS = 126,
  EVENT_FLAG_DEFEATED_LOST_DUELIST2 = 127, // Unused because no flags are set for the state where he is duelable
  EVENT_FLAG_DEFEATED_AMBUSHER2 = 128,
  EVENT_FLAG_TALKED_TO_WEEVIL3 = 129,
  EVENT_FLAG_DEFEATED_WEEVIL3 = 130,
  EVENT_FLAG_DEFEATED_MAKO3 = 131,
  EVENT_FLAG_DEFEATED_REX3 = 132,
  EVENT_FLAG_TOLD_ROLAND_MOKUBA_WAS_KIDNAPPED = 133,
  EVENT_FLAG_DEFEATED_SERIOUS_ARCHEOLOGIST2 = 134,
  EVENT_FLAG_DEFEATED_BONZ3 = 135,
  EVENT_FLAG_DEFEATED_KAIBA_COSPLAYER2 = 136,
  EVENT_FLAG_DEFEATED_MAI3 = 137,
  EVENT_FLAG_DEFEATED_RICH_HUSBAND = 138,
  EVENT_FLAG_DEFEATED_RICH_WIFE2 = 139,
  EVENT_FLAG_ENTERED_PEGASUS_ISLAND = 140,
  EVENT_FLAG_DEFEATED_PANIK_AND_MIMIC_OF_DOOM2 = 141,
  EVENT_FLAG_ENTERED_DUNGEON = 142,
  EVENT_FLAG_DEFEATED_PARA_AND_DOX2 = 143,
  EVENT_FLAG_TEA_WENT_BACK_TO_THE_SHOP = 144,
  EVENT_FLAG_ASKED_MOKUBA_ABOUT_THE_MONKEY_ROBOTS = 145,
  EVENT_FLAG_DEFEATED_FIRST_MONKEY_ROBOT = 146,
  EVENT_FLAG_DEFEATED_RIGHT_MONKEY_ROBOT = 147,
  EVENT_FLAG_DEFEATED_LEFT_MONKEY_ROBOT = 148,
  EVENT_FLAG_COMPLETED_ROBOT_MONKEY_SIDEQUEST = 149,
  EVENT_FLAG_SAW_NEO_GHOULS_ENTER_CANADA_CAVE = 150,
  EVENT_FLAG_SAW_PARADOX_FLEE = 151,
  EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN1 = 152,
  EVENT_FLAG_NOTICED_PARADOX_GAUNTLET_LOOP = 153,
  EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN2 = 154,
  EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN3 = 155,
  EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN4 = 156,
  EVENT_FLAG_DEFEATED_GAUNTLET_GUARDIAN5 = 157,
  EVENT_FLAG_DEFEATED_PARADOX = 158,
  EVENT_FLAG_SEARCHING_FOR_SEEKER2 = 159,
  EVENT_FLAG_DEFEATED_SEEKER2 = 160,
  EVENT_FLAG_SEARCHING_FOR_ROBOT_TRISTAN = 161,
  EVENT_FLAG_GRANDPA_MUTO_SAID_KAIBA_CORP_PRODUCES_MONKEY_ROBOTS = 162,
  EVENT_FLAG_SAW_LUCKY_IN_CLOCK_TOWER_SQUARE = 163,
  EVENT_FLAG_DEFEATED_ALL_CABLE_CAR_CHEVALIERS_ONCE = 164,
  EVENT_FLAG_PARADOX_SAID_TO_GET_SPIRIT_CARDS = 165,
  EVENT_FLAG_DEFEATED_DARK_BONZ_WITHOUT_SPIRIT_CARD = 166,
  EVENT_FLAG_DEFEATED_DARK_REX_WITHOUT_SPIRIT_CARD = 167,
  EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITHOUT_SPIRIT_CARD = 168,
  EVENT_FLAG_DEFEATED_DARK_MAKO_WITHOUT_SPIRIT_CARD = 169,
  EVENT_FLAG_DEFEATED_DARK_ESPA_ROBA_WITHOUT_SPIRIT_CARD = 170,
  EVENT_FLAG_DEFEATED_DARK_MAI_WITHOUT_SPIRIT_CARD = 171,
  EVENT_FLAG_GOT_PAST_FIRST_PEGASUS_CASTLE_ROOM = 172,
  EVENT_FLAG_DEFEATED_KAIBA = 173,
  EVENT_FLAG_BROUGHT_MILLENNIUM_EYE_TO_ISHIZU = 174,
  EVENT_FLAG_WATCHED_THE_KAIBAMAN_SHOW = 175,
  EVENT_FLAG_DEFEATED_REBECCA = 176,
  EVENT_FLAG_DEFEATED_JEAN_CLAUDE_MAGNUM2 = 177,
  EVENT_FLAG_FINISHED_GAME = 178,
  EVENT_FLAG_ENTERED_THE_SHOP = 179,
  EVENT_FLAG_LEAVING_THE_CABLE_CAR_LEADS_TO_THE_TOP_OF_PEGASUS_ISLAND = 180,
  EVENT_FLAG_TALKED_TO_SHADIS_PORTRAIT = 181,
  EVENT_FLAG_LINT_FAINTED = 182,
  EVENT_FLAG_DEFEATED_FENG_LONG = 183,
  EVENT_FLAG_SAW_ELDERS_TALK_TO_EACH_OTHER = 184,
  EVENT_FLAG_JOEY_COMPLAINED_ABOUT_TRISTAN = 185,
  EVENT_FLAG_TEA_SAID_TO_LOOK_FOR_BANANAS = 186,
  EVENT_FLAG_ENTERED_PEGASUS_CASTLE = 187,
  EVENT_FLAG_TALKED_TO_PARADOX_ABOUT_RA = 188,
  EVENT_FLAG_ISHIZU_SAID_TO_GO_SEE_MARIK = 189,
  EVENT_FLAG_DEFEATED_MARIK = 190,
  EVENT_FLAG_DEFEATED_DARK_BONZ_WITH_SPIRIT_CARD = 191,
  EVENT_FLAG_DEFEATED_DARK_REX_WITH_SPIRIT_CARD = 192,
  EVENT_FLAG_DEFEATED_DARK_WEEVIL_WITH_SPIRIT_CARD = 193,
  EVENT_FLAG_DEFEATED_DARK_MAKO_WITH_SPIRIT_CARD = 194,
  EVENT_FLAG_DEFEATED_DARK_ESPA_ROBA_WITH_SPIRIT_CARD = 195,
  EVENT_FLAG_DEFEATED_DARK_MAI_WITH_SPIRIT_CARD = 196,
  EVENT_FLAG_TAG_DUELED_WITH_JOEY_AGAINST_THE_DOMINO_STATIONS_GUARDS = 197,
  EVENT_FLAG_CHOSE_TO_FIGHT_THE_RIGHT_DOMINO_STATION_GUARD = 198, // the game does not leave a choice, so this flag is always set
  EVENT_FLAG_CHOSE_TO_FIGHT_THE_MIMIC_OF_DOOM2 = 199,
  EVENT_FLAG_CHOSE_TO_FIGHT_DOX2 = 200,
  EVENT_FLAG_UNUSED_201 = 201,
  EVENT_FLAG_UNUSED_202 = 202,
  EVENT_FLAG_OBTAINED_PHOENIX_MODE = 203,
  EVENT_FLAG_UNUSED_204 = 204,
  EVENT_FLAG_EXITED_MARIKS_HOME = 205,
  EVENT_FLAG_ENTERED_CANADA = 206,
  EVENT_FLAG_UNUSED_207 = 207,
  EVENT_FLAG_UNUSED_208 = 208,
  EVENT_FLAG_UNUSED_209 = 209,
  EVENT_FLAG_UNUSED_210 = 210,
  EVENT_FLAG_UNUSED_211 = 211,
  EVENT_FLAG_UNUSED_212 = 212,
  EVENT_FLAG_UNUSED_213 = 213,
  EVENT_FLAG_UNUSED_214 = 214,
  EVENT_FLAG_UNUSED_215 = 215,
  EVENT_FLAG_UNUSED_216 = 216,
  EVENT_FLAG_UNUSED_217 = 217,
  EVENT_FLAG_UNUSED_218 = 218,
  EVENT_FLAG_UNUSED_219 = 219,
  EVENT_FLAG_UNUSED_220 = 220,
  EVENT_FLAG_UNUSED_221 = 221,
  EVENT_FLAG_UNUSED_222 = 222,
  EVENT_FLAG_UNUSED_223 = 223,
  EVENT_FLAG_UNUSED_224 = 224,
  EVENT_FLAG_UNUSED_225 = 225,
  EVENT_FLAG_LIGHT_THE_CANDLE_IN_MARIKS_ROOM = 226,
  EVENT_FLAG_ENTERED_PHOENIX_MODE_PASSWORD = 227,
  EVENT_FLAG_UNLOCKED_EGYPT = 228,
  EVENT_FLAG_GOT_PAST_DARK_BONZ_ROOM = 229,
  EVENT_FLAG_GOT_PAST_DARK_REX_ROOM = 230,
  EVENT_FLAG_GOT_PAST_DARK_WEEVIL_ROOM = 231,
  EVENT_FLAG_GOT_PAST_DARK_MAKO_ROOM = 232,
  EVENT_FLAG_GOT_PAST_DARK_ESPA_ROBA_ROOM = 233,
  EVENT_FLAG_GOT_PAST_DARK_MAI_ROOM = 234,
  EVENT_FLAG_BONZ_PREDICTED_PLAYER_PAST_LIFE = 235,
  EVENT_FLAG_BONZ_PREDICTED_PLAYER_ROMANTIC_MATCH = 236,
  EVENT_FLAG_UNLOCKED_HALL_OF_ETERNITY = 237,
  EVENT_FLAG_UNLOCKED_EGYPT_EXHIBITION = 238,
  EVENT_FLAG_MAKE_BACKGROUND_BLACK = 239, // Used for the "innter monologue" between Yugi and Yami Yugi
  EVENT_FLAG_DARKEN_SCREEN = 240, // Used for the "Tunnel" effect when dueling PaniK
  EVENT_FLAG_JOEY_LEFT_THE_PARTY = 241,
  EVENT_FLAG_YUGI_LEFT_THE_PARTY = 242,
  EVENT_FLAG_FLASHBACK = 243,
  EVENT_FLAG_NON_DUEL_EXPRESS_HAS_LEFT_DOMINO_STATION = 244,
  EVENT_FLAG_LEAVING_THE_DUEL_EXPRESS_LEADS_TO_DOMINO_STATION = 245,
  EVENT_FLAG_SHAKE_SCREEN_AND_MOVE_BACKGROUND = 246, // Used only by the cable car on Pegasus Island
  EVENT_FLAG_SHAKE_SCREEN = 247,
  EVENT_FLAG_UNLOCKED_PEGASUS_CASTLE = 248,
  EVENT_FLAG_UNLOCKED_DUNGEON = 249,
  EVENT_FLAG_UNLOCKED_PEGASUS_ISLAND = 250,
  EVENT_FLAG_UNLOCKED_GALAPAGOS = 251,
  EVENT_FLAG_UNLOCKED_CANADA = 252,
  EVENT_FLAG_UNLOCKED_CHINA = 253,
  EVENT_FLAG_UNLOCKED_ITALY = 254,
  EVENT_FLAG_UNLOCKED_DOMINO_PIER = 255,
};

enum OverworldReactions {
  REACTION_EXCLAMATION_MARK = 0,
  REACTION_QUESTION_MARK = 1,
  REACTION_LOVE_HEART = 2,
  REACTION_ELLIPSIS = 3,
  REACTION_SWEATDROP = 4,
  REACTION_ANGRY = 5,
  REACTION_CHANT = 6,
};

enum Languages {
  LANGUAGE_ENGLISH = 0,
  LANGUAGE_FRENCH = 1,
  LANGUAGE_GERMAN = 2,
  LANGUAGE_ITALIAN = 3,
  LANGUAGE_SPANISH = 4,
};

enum PortraitDirections {
  PORTRAIT_LEFT = 0,
  PORTRAIT_RIGHT = 1,
};

enum Motion {
  MOTION_STATIONARY,
  MOTION_WALKING,
  MOTION_RUNNING
};

enum OverworldBackground {
  OVERWORLD_BACKGROUND_NORMAL,
  OVERWORLD_BACKGROUND_RESHEF,
  OVERWORLD_BACKGROUND_GOEMON_IMPACT
};

void OverworldMain (void);
void sub_804DF5C (int objectId);
void sub_804EB04 (struct OamData* arg0, u8 arg1);
void sub_804EC4C (void);
void sub_804EC64 (void);
void sub_804ECA8 (void);
void OverworldLoadGraphics (void);

//script structs
struct Script
{
    u8* start;
    struct Script* unk4; // script to execute when flag is cleared/selected yes/duel won...
    struct Script* unk8; // script to execute when flag is set/selected no/duel lost...
};

//TODO: rename to ScriptContext?
struct ScriptCtx {
  unsigned short portraitId;
  u32 pointer; // rename to offset?
  u32 unk8; //current glyph offset?
  u8 unkC;
  u8 unkD;
  struct Script currentScript;
  u16 unk1C; //frame counter for text cursor when waiting for user input
  u8 unk1E; //decides the next script to be executed based on certain outcomes
  u16 unk20;
  u8 unk22[0x52];
  u16 unk74;
  u16 unk76;
  u8 unk78;
  u16 unk7A;
  u16 unk7C;
  u16 unk7E;
  u16 unk80;
  u16 unk82;
  u8 unk84;
  u8 unk85;
  u8 unk86;
};

//TODO: change terminology from Map to Location? (struct OverworldLocation)

//overworld structs
struct Map //MapHeader?
{
    u16 id;
    u16 state;
    u16 unk4; //which connection the player came from?
    u8 unk6;
    u16 unk8;
    u16 unkA;
    u16 unkC;
};

//struct OverworldObject
struct Object
{
    s16 spriteId;
    u8 direction; //facing D L U R
    s16 x; //pos[0]?
    s16 y; //pos[1]?
    s16 unk8;
    u8 unkA;
    u16 unkC;
    u8 unkE;
    u8 unkF;
    struct Script *scriptA;
    struct Script *scriptR;
    unsigned char motionState;
    s16 unk1A;
    u8 unk1C;
    u8 hasShadow : 1;
    u8 facePlayer : 1;
    u8 wander : 1;
    u8 unk1Dl : 1;
    u8 enableBlending : 1;
    u8 unk1E;
};

struct Overworld
{
    struct Map map; //inline instead?
    struct Object objects[15];
    unsigned char unk1F0;
    unsigned char unk1F1;
    unsigned char unk1F2;
    unsigned char unk1F3;
    struct Script *unk1F4[5];
    struct Script *unk208[5];
    signed short unk21C[15];
    unsigned char unk23A;
    u16 *unk23C; //collision data
    unsigned char flags;
    unsigned short music;
    long unk244;
    long unk248;
    s16 unk24C; // used when the screen shakes due to earthquake effect; it modifies the background and sprite y position
    s16 unk24E; // ^same but x position
    enum OverworldBackground background;
};

struct ObjectData {
  signed short spriteId;
  enum Direction direction;
  unsigned short x; //signed short? (also matches)
  unsigned short y; //signed short? (also matches)
  struct Script *scriptA;
  struct Script *scriptR;
  unsigned char hasShadow : 1;
  unsigned char facePlayer : 1;
  unsigned char wander : 1;
  unsigned char unk11; //elevation? modifies y coord of sprite (y -= unk11)
                       //(the higher the value, the higher the sprite is on the screen)
};

struct MapScript
{
    struct Script *unk0;
    unsigned char unk4;  //unused?? //mapid, map connection
    unsigned char unk5;  //unused??
};

struct MapData
{
    struct ObjectData objects[16];  //terminated by a -1 (0xFFFF) spriteId
    struct MapScript unk140[5];
    struct MapScript unk168[5];
    struct ObjectData playerInitialState[5]; //TODO: playerInitialStates? // num_connections (including world map)
    u16 music;
    u8 unk1F6; //bitfield?
};

extern struct Overworld gOverworld;
extern u16* gMapCollisions[]; //gMapCollisionData
extern struct MapData** gMapData[]; //0xE19274

extern unsigned char * gOverworldEntitySprites[];
extern u16 gUnk08103264[];
extern u16 g8103284[];
extern u16 g81032A2[];
extern struct Script* g8F04040;

void sub_8052088(u8); //implicit declaration?
void sub_804DF5C(int);
void sub_804EF10 (void);
void InitiateScript (struct Script *);
u16 sub_80520E0(u8 x, u8 y);
u32 CheckFlag(u32);


void sub_8053388(struct ScriptCtx *script);
void sub_805339C (void);
void sub_80533BC (void);
void sub_8053404 ();  //TODO: implicit declaration
void sub_8053CF0 (u8 obj, s16 x, s16 y, u16 arg3, struct ScriptCtx* script);
void sub_8053D50(u8, u8, struct ScriptCtx *script);
void sub_8053D88(u8, u8, u8, struct ScriptCtx *script);
void sub_8053E34(u8);
inline void sub_8053E94(struct ScriptCtx* script);


extern const u32 g8E0E4CC[];
extern const u32 g8E0E53C[];

void ClearFlag(u32);
void DuelTrunkMenu(void);
void OverworldSetRegDispcnt2(void);



void sub_805345C(u8, u8, u8, u8, struct ScriptCtx *script);
void sub_8034FE0(void);
void sub_8053520(u8, s16, s16, u16, u8, u8, struct ScriptCtx *script);
void sub_8053984(u8, u8, struct ScriptCtx *script);
void sub_8053A74(u8, u8, struct ScriptCtx *script);
void sub_8053884(u16, u8, struct ScriptCtx *script);
void sub_8054AB0(u8, struct ScriptCtx *script);
void sub_804F218(void);


void sub_8053C18(struct ScriptCtx *script, u8);
unsigned sub_80524A4(u16);
void sub_805339C(void);
void OverworldSetRegDispcnt(void);
void sub_8053B40(u8, u16, struct ScriptCtx *script);
void sub_80512E0(struct ScriptCtx *script, u8);

void PlayOverworldMusic (void);


void sub_804F750(u8);

void sub_80523EC(u16, u16, u16);
void sub_0804F76C(void);
void SetFlag(u32);
void SaveGame(void);
void InitiateScript(struct Script *);
void PlayOverworldMusic(void);
void sub_804F5D8(void);

void sub_8035038(u16);


extern u16 g82AD48C[];
extern const u32 g82AD2D0[];

extern u32 gE0E674[];
extern u32 gE0E754[];

s8 sub_8051E48 (u8, u8, u8);
void sub_804F19C (int);



void sub_804F124 (u8 objectId);
void sub_804F254 (void);
void sub_804F054 (int spriteId, int arg1, u8* dest);
void sub_804F1F4 (void);
void SaveLfsrState (u32);

extern u32 g84C9FBC[];
extern u16 g84D0CE0[];
extern u16 g84CFCE0[];
extern u16 g84D04E0[];
extern u32 g84D0EC0[];
extern u16 g84D69D0[];
extern u16 g84D59D0[];
extern u16 g84D61D0[];

extern const unsigned char ShadowTiles[];
extern const unsigned char ReactionBubbleTiles[];

#endif // GUARD_OVERWORLD_H
