#ifndef GUARD_SPELL_EFFECTS_H
#define GUARD_SPELL_EFFECTS_H

#include "global.h"
#include "common-chax.h"

extern void EffectMooyanCurry(void);
extern void EffectRedMedicine(void);
extern void EffectGoblinsSecretRemedy(void);
extern void EffectSoulOfThePure(void);
extern void EffectDianKetoTheCureMaster(void);
extern void EffectSparks(void);
extern void EffectHinotama(void);
extern void EffectFinalFlame(void);
extern void EffectOokazi(void);
extern void EffectTremendousFire(void);
extern void EffectDarkHole(void);
extern void EffectRaigeki(void);
extern void EffectLegendarySword(void);
extern void EffectSwordOfDarkDestruction(void);
extern void EffectDarkEnergy(void);
extern void EffectAxeOfDespair(void);
extern void EffectLaserCannonArmor(void);
extern void EffectInsectArmorWithLaserCannon(void);
extern void EffectElfsLight(void);
extern void EffectBeastFangs(void);
extern void EffectSteelShell(void);
extern void EffectVileGerms(void);
extern void EffectBlackPendant(void);
extern void EffectSilverBowAndArrow(void);
extern void EffectHornOfLight(void);
extern void EffectHornOfTheUnicorn(void);
extern void EffectDragonTreasure(void);
extern void EffectElectroWhip(void);
extern void EffectCyberShield(void);
extern void EffectMysticalMoon(void);
extern void EffectMalevolentNuzzler(void);
extern void EffectVioletCrystal(void);
extern void EffectBookOfSecretArts(void);
extern void EffectInvigoration(void);
extern void EffectMachineConversionFactory(void);
extern void EffectRaiseBodyHeat(void);
extern void EffectFollowWind(void);
extern void EffectPowerOfKaishin(void);
extern void EffectStopDefense(void);
extern void EffectSwordsOfRevealingLight(void);
extern void EffectDarkPiercingLight(void);
extern void EffectSpellBindingCircle(void);
extern void EffectElegantEgotist(void);
extern void EffectBlackLusterRitual(void);
extern void LeftoverRitualFromSacredCards_804AED8(void);
extern void LeftoverRitualFromSacredCards_804AF58(void);
extern void LeftoverRitualFromSacredCards_804AFD8(void);
extern void LeftoverRitualFromSacredCards_804B058(void);
extern unsigned sub_804B144(u8* zones, u16* ritualArr);
extern void LeftoverRitualFromSacredCards_804B20C(void);
extern void LeftoverRitualFromSacredCards_804B294(void);
extern void LeftoverRitualFromSacredCards_804B31C(void);
extern void LeftoverRitualFromSacredCards_804B3A4(void);
extern void LeftoverRitualFromSacredCards_804B42C(void);
extern void LeftoverRitualFromSacredCards_804B4B4(void);
extern void EffectMagicalLabyrinth(void);
extern void EffectSalamandra(void);
extern void EffectKunaiWithChain(void);
extern void EffectBrightCastle(void);
extern void EffectCrushCard(void);
extern void EffectShadowSpell(void);
extern void ApplyGladiatorBeastsBattleGladiusAtkCorrection(const struct DuelCard *zone);
extern u8 GladiatorBeastsBattleGladius_RecyclesWhenTargetReturnsToDeck(
    const struct DuelCard *zone);
extern u8 GladiatorBeastsBattleManica_PreventsBattleDestruction(
    const struct DuelCard *zone);
extern u8 GladiatorBeastsBattleManica_RecyclesWhenTargetReturnsToDeck(
    const struct DuelCard *zone);
extern u8 GenerationNext_BlocksCardActivation(u16 cardId);
extern void GenerationNext_ClearOnTurnBoundary(void);
extern u8 GladiatorBeastBattleHalberd_IsEquippedTo(const struct DuelCard *zone);
extern u8 GladiatorBeastBattleHalberd_RecyclesWhenTargetReturnsToDeck(
    const struct DuelCard *zone);
extern u8 GladiatorBeastsBattleArchfiendShield_PreventsDestruction(
    const struct DuelCard *zone);
extern u8 GladiatorBeastsBattleArchfiendShield_RecyclesWhenTargetReturnsToDeck(
    const struct DuelCard *zone);
extern u8 GravekeepersInscription_GetActiveMode(void);
extern u8 GravekeepersInscription_BlocksGraveyardEffects(void);
extern u8 GravekeepersInscription_BlocksGraveyardBanish(void);
extern u8 GravekeepersInscription_BlocksSpecialSummonFromGraveyard(void);
extern void TryClearGravekeepersInscriptionEndPhase(void);
extern u8 CanActivateMYSTIK_WOK(void);
extern u8 Necrovalley_IsActive(void);
extern u8 Necrovalley_IsGravekeeperMonster(u16 cardId);
extern void Necrovalley_ApplyGravekeeperStatBonusToCardInfo(const struct DuelCard *zone);
extern u8 CanActivateNECROVALLEY_THRONE(void);
extern u8 CanActivateILLUSION_MAGIC(void);
extern u8 CanInfectedMailMonsterAttackDirectly(const struct DuelCard *zone);
extern void InfectedMail_SendTargetToGraveyardAtBattlePhaseEnd(void);
extern u8 CanActivateINFERNO_FIRE_BLAST(void);
extern u8 LevelTuning_CanTarget(const struct DuelCard *zone);
extern void LevelTuning_ApplyToTarget(struct DuelCard *zone);
extern void LevelTuning_ApplyLevelToCardInfo(const struct DuelCard *zone);
extern void LevelTuning_ClearAtTurnBoundary(void);
extern void TryApplyMirageOfNightmareStandby(void);
extern u8 MoltingEscape_PreventsBattleDestruction(const struct DuelCard *target);
extern void MoltingEscape_ApplyBattleProtection(struct DuelCard *target);
extern void MaskOfDispel_OnTargetLeave(struct DuelCard *zone);
extern void TryApplyMaskOfDispelStandbyDamage(void);
extern u8 MaskOfTheAccursed_CanMonsterDeclareAttack(const struct DuelCard *zone);
extern void TryApplyMaskOfTheAccursedStandbyDamage(void);
extern u8 MorphtronicRepairUnit_PreventsBattlePositionChange(const struct DuelCard *zone);
extern void MorphtronicRustyEngine_InflictDestroyBurn(const struct DuelCard *target);
extern u8 MysticMine_IsActiveOnField(void);
extern u8 MysticMine_GetLockedFixedDuelist(void);
extern u8 MysticMine_LocksFixedDuelist(u8 fixedDuelist);
extern void TryApplyMysticMineEndPhase(void);
extern u8 LightBarrier_IsActiveForDuelist(u8 fixedDuelist);
extern u8 LightBarrier_IsNegatedForDuelist(u8 fixedDuelist);
extern void LightBarrier_ResolveStandbyCoin(u8 fixedDuelist, u8 heads);
extern u8 LightBarrier_AllowsArcanaForceCoinChoice(u8 fixedDuelist);
extern u16 LightBarrier_GetArcanaForceBattleDestroyLp(u8 fixedDuelist,
                                                       const struct DuelCard *attacker,
                                                       const struct DuelCard *destroyed);
extern u8 LightForce_IsActiveForDuelist(u8 fixedDuelist);
extern u8 LightForce_IsNegatedForDuelist(u8 fixedDuelist);
extern void LightForce_ResolveStandbyCoin(u8 fixedDuelist, u8 heads);
extern u8 LightForce_BlocksSpecialSummon(u8 fixedDuelist, u16 cardId);
extern void LightForce_ClearTurnState(void);
extern void ApplyLightForceFairyStatBoostForZone(struct DuelCard *zone);
extern u8 CanActivateLIGHTNING_STORM(void);
extern u8 CanActivateLIGHTSWORN_SABRE(void);
extern void ApplyLightswornSabreAtkBonusToCardInfo(const struct DuelCard *zone);
extern u8 LightswornSanctuary_IsFaceUp(const struct DuelCard *zone);
extern u8 LightswornSanctuary_IsLightswornMonster(u16 cardId);
extern void MoraleBoost_OnEquipSpellEquipped(void);
extern void MoraleBoost_OnEquipSpellSentFromField(void);
extern u8 MorphtronicCord_ShouldDestroySpellTrapOnPositionChange(
    const struct DuelCard *zone);
extern void TryApplyMorphtronicEngineStandby(void);
extern void MorphtronicMap_OnBattlePositionChanged(void);
extern void ApplyMorphtronicMapAtkBonusToCardInfo(const struct DuelCard *zone);
extern void ApplyMorphtronicEngineAtkBonusToCardInfo(const struct DuelCard *zone);
extern void ApplyMoltingEscapeAtkBonusToCardInfo(const struct DuelCard *zone);
extern u8 MagiciansLeftHand_ShouldNegateTrap(u8 activatingFixedDuelist);
extern void MagiciansLeftHand_MarkTrapNegationUsed(u8 activatingFixedDuelist);
extern u8 MagiciansRightHand_ShouldNegateSpell(u8 activatingFixedDuelist);
extern void MagiciansRightHand_MarkSpellNegationUsed(u8 activatingFixedDuelist);
extern u8 CanActivateMARCH_OF_THE_DARK_BRIGADE(void);
extern void LeftoverRitualFromSacredCards_804B9D0(void);
extern void LeftoverRitualFromSacredCards_804BA58(void);
extern void LeftoverRitualFromSacredCards_804BAE0(void);
extern void LeftoverRitualFromSacredCards_804BB68(void);
extern void LeftoverRitualFromSacredCards_804BBF0(void);
extern void LeftoverRitualFromSacredCards_804BC78(void);
extern void LeftoverRitualFromSacredCards_804BD00(void);
extern void LeftoverRitualFromSacredCards_804BD88(void);
extern void LeftoverRitualFromSacredCards_804BE10(void);
extern void LeftoverRitualFromSacredCards_804BE98(void);
extern void LeftoverRitualFromSacredCards_804BF18(void);
extern void LeftoverRitualFromSacredCards_804BF98(void);
extern void EffectWarriorElimination(void);
extern void EffectCurseBreaker(void);
extern void EffectEternalRest(void);
extern void EffectMegamorph(void);
extern void EffectMetalmorph(void);
extern void EffectWingedTrumpeter(void);
extern void EffectStainStorm(void);
extern void EffectEradicatingAerosol(void);
extern void EffectBreathOfLight(void);
extern void EffectEternalDrought(void);
extern void EffectTheInexperiencedSpy(void);
extern void EffectDarkMagicRitual(void);
extern void EffectPotOfGreed(void);
extern void EffectRestructerRevolution(void);
extern void EffectLastDayOfWitch(void);
extern void EffectExileOfTheWicked(void);
extern void EffectMultiply(void);
extern void EffectChangeOfHeart(void);
extern void EffectBlackIllusionRitual(void);
extern void EffectBrainControl(void);
extern void EffectMonsterReborn(void);
extern void Effect7Completed(void);
extern void EffectBeckonToDarkness(void);
extern void EffectGravediggerGhoul(void);
extern void EffectHeavyStorm(void);
extern void EffectFinalDestiny(void);
extern void TSC_EffectMessengerOfPeace(void);
extern void EffectDarknessApproaches(void);
extern void EffectCyclonLaser(void);
extern void EmptyFunc_804D140(void);
extern void EmptyFunc_804D144(void);
extern void EmptyFunc_804D148(void);
extern void EmptyFunc_804D14C(void);
extern void EffectForest(void);
extern void EffectWasteland(void);
extern void EffectMountain(void);
extern void EffectSogen(void);
extern void EffectUmi(void);
extern void EffectYami(void);
extern void EmptyFunc_804D378(void);
extern void EmptyFunc_804D37C(void);
extern void EmptyFunc_804D380(void);
extern void EmptyFunc_804D384(void);
extern void EmptyFunc_804D388(void);
extern void EmptyFunc_804D38C(void);
extern void EmptyFunc_804D390(void);
extern void EmptyFunc_804D394(void);
extern void EmptyFunc_804D398(void);
extern void EmptyFunc_804D39C(void);
extern void EmptyFunc_804D3A0(void);
extern void EmptyFunc_804D3A4(void);
extern void EmptyFunc_804D3A8(void);
extern void EffectHarpiesFeatherDuster(void);
extern void EmptyFunc_804D4E0(void);
extern void EmptyFunc_804D4E4(void);
extern void EmptyFunc_804D550(void);
extern void EmptyFunc_804D5A4(void);
extern void EmptyFunc_804D5A8(void);
extern void EmptyFunc_804D5AC(void);
extern void EmptyFunc_804D5B0(void);
extern void EmptyFunc_804D5B4(void);
extern void EmptyFunc_804D5B8(void);
extern void EmptyFunc_804D5BC(void);
extern void EmptyFunc_804D5C0(void);
extern void EmptyFunc_804D5C4(void);
extern void EmptyFunc_804D5C8(void);
extern void EmptyFunc_804D5CC(void);
extern void EmptyFunc_804D5D0(void);
extern void EmptyFunc_804D5D4(void);
extern void EmptyFunc_804D5D8(void);
extern void EmptyFunc_804D5DC(void);
extern void EmptyFunc_804D5E0(void);
extern void EmptyFunc_804D5E4(void);
extern void EmptyFunc_804D5E8(void);
extern void EmptyFunc_804D5EC(void);
extern void EmptyFunc_804D5F0(void);
extern void EmptyFunc_804D5F4(void);
extern void EmptyFunc_804D5F8(void);
extern void EmptyFunc_804D5FC(void);
extern void SetRitualMonsterInZone(struct DuelCard* zone, u16 id);

#endif // GUARD_SPELL_EFFECTS_H
