#!/usr/bin/env python3
"""Extract palette indices used by vanilla title-screen save dialog tiles."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM_PATH = ROOT / "ygodm8.gba"
ROM_BASE = 0x08000000
G_TEXT_REPLACE_SAVE_DATA = 0x080DD498
G_TEXT_REPLACE_SAVE_DATA_BYTES = 0x4FF


def rom_offset(rom_addr: int) -> int:
    return rom_addr - ROM_BASE


def collect_dialog_palette_indices(rom: bytes) -> list[int]:
    start = rom_offset(G_TEXT_REPLACE_SAVE_DATA)
    end = start + G_TEXT_REPLACE_SAVE_DATA_BYTES
    if end > len(rom):
        raise SystemExit(
            f"ROM too small for gText_ReplaceSaveData: need {end:#x} bytes, have {len(rom):#x}"
        )
    chunk = rom[start:end]
    return sorted(set(chunk))


def render_reserved_indices(indices: list[int]) -> str:
    lines = [
        "/* Generated by tools/extract_title_screen_palette_reservations.py. Do not edit. */",
        "",
        f"#define TITLE_SCREEN_RESERVED_PALETTE_COUNT {len(indices)}",
        "",
        "static const u8 sTitleScreenReservedPaletteIndices[TITLE_SCREEN_RESERVED_PALETTE_COUNT] APPEND_RODATA = {",
    ]
    chunk: list[str] = []
    for index in indices:
        chunk.append(str(index))
        if len(chunk) == 12:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rom",
        type=Path,
        default=ROM_PATH,
        help=f"Built ROM to scan (default: {ROM_PATH.relative_to(ROOT)})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "src_custom" / "generated" / "title_screen_palette_reservations_generated.inc",
        help="Generated include path",
    )
    args = parser.parse_args()

    if not args.rom.is_file():
        raise SystemExit(f"missing ROM for palette reservation scan: {args.rom}")

    indices = collect_dialog_palette_indices(args.rom.read_bytes())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_reserved_indices(indices))
    print(
        "extract_title_screen_palette_reservations: ok "
        f"({len(indices)} reserved palette index(es))"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
