#!/usr/bin/env python3
"""Generate debug menu scene table from events/scripts/map_*_state_*.c filenames."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT / "events/scripts"
DEFAULT_OUT = ROOT / "src_custom/debug/debug_menu_scene_table.inc"

FILENAME_RE = re.compile(r"^map_(\d+)_state_(\d+)\.c$")


def collect_scenes() -> list[tuple[int, int, str]]:
    entries: list[tuple[int, int, str]] = []
    for path in sorted(SCRIPTS_DIR.glob("map_*_state_*.c")):
        match = FILENAME_RE.match(path.name)
        if not match:
            continue
        map_id = int(match.group(1))
        state = int(match.group(2))
        entries.append((map_id, state, path.stem))
    return entries


def render_table(entries: list[tuple[int, int, str]]) -> str:
    lines = [
        "/* Auto-generated by tools/generate_debug_menu_scene_table.py */",
        "/* One row per events/scripts/map_XX_state_YY.c; connection 0 = on-enter script slot. */",
    ]
    for map_id, state, label in entries:
        lines.append(f'DEBUG_MENU_SCENE_ENTRY({map_id}, {state}, 0, "{label}")')
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    entries = collect_scenes()
    if not entries:
        raise SystemExit(f"no scene scripts found in {SCRIPTS_DIR}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_table(entries))
    print(f"wrote {len(entries)} scene entries to {args.out}")


if __name__ == "__main__":
    main()
