#!/usr/bin/env python3
"""Scan src_custom/assets/cgs/*.png and generate enum + INCBIN registration."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CG_DIR = ROOT / "src_custom" / "assets" / "cgs"
GENERATED_ENUM = ROOT / "include" / "constants" / "event_cg_generated.h"
GENERATED_INC = ROOT / "src_custom" / "generated" / "event_cg_assets_generated.inc"


def discover_cg_pngs(directory: Path = CG_DIR) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(path for path in directory.glob("*.png") if path.is_file())


def stem_to_enum(stem: str) -> str:
    return "CG_" + re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").upper()


def stem_to_symbol(stem: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", stem) if part]
    if not parts:
        raise ValueError(f"invalid CG asset stem {stem!r}")
    return "sCg" + "".join(part[:1].upper() + part[1:] for part in parts)


def render_enum_header(stems: list[str]) -> str:
    lines = [
        "/* Generated by tools/generate_cg_assets.py. Do not edit. */",
        "#ifndef GUARD_EVENT_CG_GENERATED_H",
        "#define GUARD_EVENT_CG_GENERATED_H",
        "",
        "enum EventCg {",
        "  CG_NONE = 0,",
    ]
    for stem in stems:
        lines.append(f"  {stem_to_enum(stem)},")
    lines.extend(
        [
            "  EVENT_CG_COUNT",
            "};",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def render_assets_inc(stems: list[str]) -> str:
    lines = [
        "/* Generated by tools/generate_cg_assets.py. Do not edit. */",
        "",
    ]

    for stem in stems:
        symbol = stem_to_symbol(stem)
        base = f"src_custom/assets/cgs/{stem}"
        lines.append(f"const u8 {symbol}Tiles[] APPEND_ASSET =")
        lines.append(f'    INCBIN_U8("{base}.lz");')
        lines.append(f"const u16 {symbol}Palette[] APPEND_ASSET =")
        lines.append(f'    INCBIN_U16("{base}.gbapal");')
        lines.append("")

    lines.append("static void EventCg_GetAssetFromTable(u8 cgId, const u8 **tiles, const u16 **palette) {")
    lines.append("  *tiles = NULL;")
    lines.append("  *palette = NULL;")
    lines.append("  switch (cgId) {")
    for stem in stems:
        enum_name = stem_to_enum(stem)
        symbol = stem_to_symbol(stem)
        lines.append(f"  case {enum_name}:")
        lines.append(f"    *tiles = {symbol}Tiles;")
        lines.append(f"    *palette = {symbol}Palette;")
        lines.append("    break;")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("const u8 gEventCgTableCount = EVENT_CG_COUNT;")
    lines.append("")
    return "\n".join(lines)


def generate() -> tuple[list[str], str, str]:
    stems = [path.stem for path in discover_cg_pngs()]
    if not stems:
        raise SystemExit(f"no CG PNGs found under {CG_DIR}")
    return stems, render_enum_header(stems), render_assets_inc(stems)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--enum-out",
        type=Path,
        default=GENERATED_ENUM,
        help=f"Generated enum header (default: {GENERATED_ENUM.relative_to(ROOT)})",
    )
    parser.add_argument(
        "--inc-out",
        type=Path,
        default=GENERATED_INC,
        help=f"Generated INCBIN include (default: {GENERATED_INC.relative_to(ROOT)})",
    )
    args = parser.parse_args()

    _, enum_text, inc_text = generate()
    args.enum_out.parent.mkdir(parents=True, exist_ok=True)
    args.inc_out.parent.mkdir(parents=True, exist_ok=True)
    args.enum_out.write_text(enum_text)
    args.inc_out.write_text(inc_text)
    print(f"generate_cg_assets: ok ({len(discover_cg_pngs())} CG(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
