#ifndef GUARD_CONSTANTS_CARD_IDS_H
#define GUARD_CONSTANTS_CARD_IDS_H

#define CARD_NONE                                0x0000
#define BLUE_EYES_WHITE_DRAGON                   0x0001
#define SORCERER_OF_DARK_MAGIC                   0x0002
#define TEST_GOLDEN_CUSTOM_CARD                  0x0003

#define NUM_CARDS                               0x0002
#define NUM_TRUE_CARDS                          (NUM_CARDS - 1)
#define CUSTOM_CARD_START                       SORCERER_OF_DARK_MAGIC
#define NUM_TOTAL_CARDS                         0x0004
#define NUM_CUSTOM_CARDS                        0x0002

#endif // GUARD_CONSTANTS_CARD_IDS_H
